/* ─── Interpretive Frameworks — Annals of the World ─── */
/* Source of truth: docs/guidelines/framework_matrix.md */
import type { Framework } from '../types'

export const FRAMEWORKS: Framework[] = [
  {
    id: 'CAUSE_AND_EFFECT',
    name: 'Cause & Effect',
    description: 'Foregrounds causal chains, technological or institutional drivers, and immediate impacts.',
    verbs: ['CAUSES', 'ENABLES', 'TRIGGERS', 'TRANSFORMS'],
    relatedFrameworks: ['CULTURAL_DIFFUSION', 'ADAPTATION', 'CONFLICT_AND_RESOLUTION'],
    color: '#E53E3E',
    icon: 'Zap',
  },
  {
    id: 'CULTURAL_DIFFUSION',
    name: 'Cultural Diffusion',
    description: 'Transmission, borrowing, and spread of practices or ideas across regions and groups.',
    verbs: ['DIFFUSES', 'INTRODUCES', 'ADAPTS', 'ADOPTS'],
    relatedFrameworks: ['CAUSE_AND_EFFECT', 'TEXTUAL_TRANSMISSION', 'ADAPTATION'],
    color: '#38A169',
    icon: 'Globe',
  },
  {
    id: 'DOCTRINE_DEVELOPMENT',
    name: 'Doctrine Development',
    description: 'Formalization, systematization, and canonical consolidation within traditions.',
    verbs: ['CANONIZES', 'SYSTEMATIZES', 'STANDARDIZES', 'INTERPRETS'],
    relatedFrameworks: ['TEXTUAL_TRANSMISSION', 'LEGAL_INTERPRETATION'],
    color: '#805AD5',
    icon: 'BookOpen',
  },
  {
    id: 'TEXTUAL_TRANSMISSION',
    name: 'Textual Transmission',
    description: 'Copying, translation, editorial history, and preservation of texts.',
    verbs: ['TRANSMITS', 'TRANSLATES', 'PRESERVES', 'EDITS'],
    relatedFrameworks: ['DOCTRINE_DEVELOPMENT', 'CULTURAL_DIFFUSION'],
    color: '#D69E2E',
    icon: 'Scroll',
  },
  {
    id: 'LEGAL_INTERPRETATION',
    name: 'Legal Interpretation',
    description: 'Jurisprudential, canonical, or administrative rulings and their reform.',
    verbs: ['INTERPRETS', 'CODIFIES', 'REFORMS', 'REJECTS'],
    relatedFrameworks: ['DOCTRINE_DEVELOPMENT', 'RITUAL_STANDARDIZATION'],
    color: '#2B6CB0',
    icon: 'Scale',
  },
  {
    id: 'RITUAL_STANDARDIZATION',
    name: 'Ritual Standardization',
    description: 'Formalization and institutional adoption of ritual practice across communities.',
    verbs: ['STANDARDIZES', 'INSTITUTES', 'REGULATES'],
    relatedFrameworks: ['LEGAL_INTERPRETATION', 'DOCTRINE_DEVELOPMENT'],
    color: '#B7791F',
    icon: 'Flame',
  },
  {
    id: 'GEOPOLITICAL_LINKAGE',
    name: 'Geopolitical Linkage',
    description: 'Imperial, diplomatic, and territorial relationships that reorganize authority.',
    verbs: ['LINKS', 'CONNECTS', 'RECONFIGURES'],
    relatedFrameworks: ['CAUSE_AND_EFFECT', 'CONFLICT_AND_RESOLUTION'],
    color: '#C53030',
    icon: 'Map',
  },
  {
    id: 'CONFLICT_AND_RESOLUTION',
    name: 'Conflict & Resolution',
    description: 'Schisms, wars, negotiations, reconciliations and their effects.',
    verbs: ['CAUSES', 'RESOLVES', 'RADICALIZES', 'RECONCILES_WITH'],
    relatedFrameworks: ['GEOPOLITICAL_LINKAGE', 'ADAPTATION'],
    color: '#9B2C2C',
    icon: 'Swords',
  },
  {
    id: 'ADAPTATION',
    name: 'Adaptation',
    description: 'Contextual reinterpretation and local reworking of imported practices or ideas.',
    verbs: ['ADAPTS', 'TRANSFORMS', 'REINTERPRETS'],
    relatedFrameworks: ['CULTURAL_DIFFUSION', 'CAUSE_AND_EFFECT'],
    color: '#2F855A',
    icon: 'RefreshCw',
  },
  {
    id: 'TEMPORAL_LINKAGE',
    name: 'Temporal Linkage',
    description: 'Ordering and periodization claims connecting events across time.',
    verbs: ['PRECEDES', 'FOLLOWS', 'IS_ANTECEDENT_TO'],
    relatedFrameworks: ['CAUSE_AND_EFFECT', 'CONFLICT_AND_RESOLUTION'],
    color: '#4A5568',
    icon: 'Clock',
  },
  {
    id: 'ECONOMIC_SYSTEMS',
    name: 'Economic Systems',
    description: 'Trade networks, monetary systems, labor organization, and material exchange across time.',
    verbs: ['TRADES_WITH', 'PRODUCES', 'EXPLOITS', 'DISRUPTS'],
    relatedFrameworks: ['CAUSE_AND_EFFECT', 'GEOPOLITICAL_LINKAGE', 'EMPIRE_AND_COLONIALISM'],
    color: '#DD6B20',
    icon: 'TrendingUp',
  },
  {
    id: 'POLITICAL_SYSTEMS',
    name: 'Political Systems',
    description: 'Governance structures, constitutions, sovereignty claims, and administrative evolution.',
    verbs: ['GOVERNS', 'LEGISLATES', 'REFORMS', 'DEPOSES'],
    relatedFrameworks: ['LEGAL_INTERPRETATION', 'CONFLICT_AND_RESOLUTION', 'EMPIRE_AND_COLONIALISM'],
    color: '#2D3748',
    icon: 'Building',
  },
  {
    id: 'COMPARATIVE_RELIGION',
    name: 'Comparative Religion',
    description: 'Cross-tradition analysis of beliefs, rituals, institutions, and doctrinal exchange.',
    verbs: ['CONVERTS', 'SYNCRETIZES', 'PROSELYTIZES', 'PERSECUTES'],
    relatedFrameworks: ['DOCTRINE_DEVELOPMENT', 'CULTURAL_DIFFUSION', 'RITUAL_STANDARDIZATION'],
    color: '#9B2C2C',
    icon: 'Heart',
  },
  {
    id: 'EMPIRE_AND_COLONIALISM',
    name: 'Empire & Colonialism',
    description: 'Imperial expansion, colonial extraction, resistance, decolonization, and postcolonial effects.',
    verbs: ['COLONIZES', 'PARTITIONS', 'EXPLOITS', 'DECOLONIZES'],
    relatedFrameworks: ['GEOPOLITICAL_LINKAGE', 'CONFLICT_AND_RESOLUTION', 'ECONOMIC_SYSTEMS'],
    color: '#744210',
    icon: 'Crown',
  },
  {
    id: 'ENVIRONMENTAL_HISTORY',
    name: 'Environmental History',
    description: 'Human-environment interaction: agriculture, climate, ecology, resource use, and landscape change.',
    verbs: ['CULTIVATES', 'DEPLETES', 'ADAPTS_TO', 'MIGRATES_FROM'],
    relatedFrameworks: ['ADAPTATION', 'ECONOMIC_SYSTEMS', 'CAUSE_AND_EFFECT'],
    color: '#276749',
    icon: 'Leaf',
  },
  {
    id: 'INNOVATION_AND_TECHNOLOGY',
    name: 'Innovation & Technology',
    description: 'Scientific discovery, technological invention, engineering achievements, and knowledge diffusion.',
    verbs: ['INVENTS', 'DISCOVERS', 'ENGINEERS', 'DIFFUSES'],
    relatedFrameworks: ['CAUSE_AND_EFFECT', 'CULTURAL_DIFFUSION', 'ECONOMIC_SYSTEMS'],
    color: '#3182CE',
    icon: 'Cpu',
  },
]

export const FRAMEWORK_MAP = Object.fromEntries(
  FRAMEWORKS.map(f => [f.id, f])
) as Record<string, Framework>
