#!/usr/bin/env python3
"""Enrich 250-Class-250 — batches 24-25 (25 stubs, part B of 50)."""
import json, os, datetime, unicodedata

FOLDER = "/home/manasa151/annals-of-the-world/data/appwrite-export/entities/250-Class-250"
NOW = datetime.datetime.now(datetime.timezone.utc).isoformat()

def _norm(s):
    table = str.maketrans({
        'ł':'l','Ł':'L','ø':'o','Ø':'O','ð':'d','Ð':'D',
        'þ':'th','ß':'ss','æ':'ae','Æ':'Ae','đ':'d','Đ':'D',
        'ħ':'h','Ħ':'H','ı':'i','ü':'u','Ü':'U','ö':'o','Ö':'O',
        'ä':'a','Ä':'A','é':'e','É':'E','è':'e','È':'E','ê':'e',
        'ó':'o','Ó':'O','ñ':'n','Ñ':'N','í':'i','Í':'I','á':'a',
        'Á':'A','ú':'u','Ú':'U','ã':'a','õ':'o','ç':'c','Ç':'C',
        'ș':'s','ț':'t','ř':'r','š':'s','č':'c','ž':'z','ý':'y',
        'ń':'n','ś':'s','ź':'z','ż':'z','ą':'a','ę':'e',
    })
    s = s.translate(table)
    return unicodedata.normalize("NFD", s).encode("ascii","ignore").decode("ascii").lower()

def find_file(slug):
    direct = os.path.join(FOLDER, f"250{slug}.json")
    if os.path.exists(direct): return direct
    norm_slug = _norm(slug)
    for f in os.listdir(FOLDER):
        if f.endswith(".json") and f.startswith("250"):
            if _norm(f[3:-5]) == norm_slug:
                return os.path.join(FOLDER, f)
    return None

def enrich(slug, data):
    fpath = find_file(slug)
    if not fpath:
        print(f"  SKIP (not found): {slug}"); return
    try:
        raw = json.load(open(fpath, encoding="utf-8"))
    except Exception as ex:
        print(f"  ERROR loading {fpath}: {ex}"); return
    e = raw["entities"][0]
    dj = e.get("detailsJson", "{}")
    det = json.loads(dj) if isinstance(dj, str) else (dj or {})
    old_summary = e.get("summary", "")
    e["summary"] = data["summary"]
    e["importanceScore"] = 6
    e["historicalSignificance"] = data["hs"]
    e["_unsyncedEdits"] = True
    det["causes"] = data["causes"]
    det["effects"] = data["effects"]
    det["relationships"] = data["rels"]
    det["_unsyncedEdits"] = True
    det.setdefault("_editLog", []).append({
        "timestamp": NOW, "editorId": "vscode-copilot",
        "field": "summary", "oldValue": old_summary[:80], "newValue": data["summary"][:80]
    })
    e["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fpath, "w", encoding="utf-8") as fh:
        json.dump(raw, fh, ensure_ascii=False, indent=2)
    print(f"  OK: {e.get('name', slug)}")

ENTITIES = [

  ("adolf-of-nassau-wiesbaden-idstein", {
    "summary": "Adolf of Nassau-Wiesbaden-Idstein (c. 1423–1475) was Archbishop of Mainz from 1461 to 1475, one of the most turbulent archiepiscopates in the history of that great see. The Archbishopric of Mainz was the premier ecclesiastical principality of the Holy Roman Empire — its archbishop was the Arch-Chancellor of Germany and the presiding Prince-Elector at imperial elections — making it the most powerful church office in the German world. Adolf's path to the archbishopric was itself contested, arising from a disputed election that was only resolved through papal intervention.\n\nAdolf's archiepiscopate coincided with the later phases of the Gutenberg revolution: Johannes Gutenberg had produced his famous Bible in Mainz by 1455, and the printing press was beginning to transform European intellectual life. As Archbishop of Mainz in this pivotal decade, Adolf presided over the city that was the birthplace of European printing, even as he managed the military and political conflicts that characterised his reign.\n\nHis tenure was marked by the ongoing conflict between the Nassau and Isenburg families for control of Mainz's electoral chapter, as well as complex negotiations with the emperor and the city's merchant class. His management of the archbishopric's finances and military resources reflected the heavy demands placed on German prince-bishops who had to function simultaneously as secular rulers, military commanders, and spiritual leaders.",
    "hs": {"significanceScore": 5, "significanceNarrative": "Archbishop of Mainz — the Holy Roman Empire's premier ecclesiastical see — who presided over the birthplace of European printing during the transformative decade after Gutenberg's invention.", "significanceCategory": "continental"},
    "causes": ["Mainz's position as the Empire's premier archbishopric required a powerful figure from one of Germany's great dynasties", "Disputed election to Mainz required papal arbitration, reflecting the contested nature of this supremely valuable see", "Gutenberg's printing revolution had transformed Mainz into the centre of Europe's emerging information economy"],
    "effects": ["His archiepiscopate governed the Rhineland's most powerful ecclesiastical see during the early decades of the printing revolution", "His management of Mainz's complex dynastic politics maintained the archbishopric's autonomy in a competitive imperial landscape", "His tenure as Arch-Chancellor gave him a role in the imperial administration that extended far beyond his own territory"],
    "rels": [{"target": "archdiocese-of-mainz", "verb": "DEFINES", "note": "Served as Archbishop of Mainz 1461–1475"}, {"target": "holy-roman-empire", "verb": "DEFINES", "note": "Was Arch-Chancellor of Germany and a Prince-Elector as Archbishop of Mainz"}, {"target": "printing-press", "verb": "OCCURS_IN", "note": "Presided over Mainz, the birthplace of European printing, in the generation after Gutenberg"}, {"target": "house-of-nassau", "verb": "OCCURS_IN", "note": "Was a member of the House of Nassau-Wiesbaden-Idstein"}]
  }),

  ("adolf-of-osnabrueck", {
    "summary": "Adolf of Osnabrück (1185–1224) was Bishop of Osnabrück from 1216 to 1224 and is venerated as a saint in the Catholic tradition, with his feast day on 30 June. His episcopate in Westphalia coincided with the height of medieval episcopal activity in the German Church under Pope Innocent III's successors, a period when German bishops were building cathedrals, organising crusades, and implementing the Lateran IV reforms.\n\nThe Diocese of Osnabrück, though smaller than the great Rhenish sees, occupied an important position in Westphalian ecclesiastical geography. Adolf's reputation for personal holiness and pastoral care was such that his memory was preserved and eventually formalised in the local cult that recognised him as blessed and saint. His example of episcopal holiness in a relatively modest see illustrates that sanctity was not confined to the great metropolitan bishops — local pastors of genuine spiritual depth also shaped the medieval Church's hagiographic tradition.\n\nAdolf's canonisation reflects the medieval Church's recognition that the ideal bishop combined administrative capability with personal holiness. His care for the poor and vulnerable in his diocese, combined with his governance of the Church's institutional life, made him a model of the bishop-saint that the Gregorian reform had sought to produce: a pastor who was first a man of God before a prince of the Church.",
    "hs": {"significanceScore": 4, "significanceNarrative": "Westphalian bishop canonised for pastoral holiness and care for the poor, representing the Gregorian reform's ideal of the bishop-saint in a regional German see.", "significanceCategory": "regional"},
    "causes": ["Gregorian reform's vision of the holy bishop required pastors who combined institutional leadership with genuine spiritual depth", "Diocese of Osnabrück's position in Westphalia required episcopal leadership capable of managing both Church governance and pastoral care", "Lateran IV reforms (1215) provided the framework for renewed episcopal engagement with pastoral responsibility"],
    "effects": ["His canonisation established him as a patron saint of the Diocese of Osnabrück", "His example of pastoral holiness contributed to the tradition of bishop-saints that the Gregorian reform had sought to create", "His memory was preserved in local cult that eventually received formal papal recognition"],
    "rels": [{"target": "diocese-of-osnabrueck", "verb": "DEFINES", "note": "Served as Bishop of Osnabrück 1216–1224"}, {"target": "gregorian-reform", "verb": "INFLUENCES", "note": "His episcopal holiness reflected the Gregorian reform's ideal of the bishop-saint"}, {"target": "fourth-lateran-council", "verb": "OCCURS_IN", "note": "His episcopate coincided with and was shaped by the Lateran IV reforms of 1215"}]
  }),

  ("adolf-van-der-mark", {
    "summary": "Adolf of the Mark (1334–1347) was Prince-Bishop of Liège from 1313 to 1344, one of the longest and most turbulent episcopates in that powerful principality's history. The Prince-Bishops of Liège were among the most powerful ecclesiastical princes in the Low Countries, governing a wealthy industrial and commercial territory in the Meuse valley that included significant coal, metal-working, and textile industries — making Liège one of the wealthiest principalities in medieval northwestern Europe.\n\nAdolf's long episcopate was marked by continuous conflict with the commune of Liège — one of the most politically assertive urban communities in northern Europe. The city of Liège's craft guilds and merchant class repeatedly challenged episcopal authority, asserting their rights and autonomy in a series of confrontations that foreshadowed the dramatic urban revolts of the fourteenth century. This tension between episcopal lordship and urban communal power was one of the defining dynamics of the medieval Liège principality.\n\nThe Mark family — from the County of Mark in Westphalia — used the Liège bishopric as a platform for their dynastic ambitions across the lower Rhine and Meuse regions. Adolf's tenure represented the family's decades-long hold on one of northern Europe's richest ecclesiastical prizes, and his management of the principality's complex political and economic affairs shaped the region's development.",
    "hs": {"significanceScore": 5, "significanceNarrative": "Prince-Bishop of Liège who governed one of northern Europe's wealthiest ecclesiastical principalities through decades of conflict with the city's powerful craft guilds and communal institutions.", "significanceCategory": "regional"},
    "causes": ["Liège's wealthy industrial economy made its prince-bishopric one of the most valuable ecclesiastical prizes in the Low Countries", "Mark dynastic ambitions required controlling key ecclesiastical positions like Liège across the lower Rhine region", "Urban communal assertiveness of Liège's craft guilds challenged episcopal authority throughout the fourteenth century"],
    "effects": ["His three-decade episcopate shaped Liège's institutional and economic development during a critical period", "His conflicts with the city commune contributed to the patterns of urban-episcopal tension that would escalate in later fourteenth-century revolts", "Mark family consolidated regional influence through their long hold on the Liège prince-bishopric"],
    "rels": [{"target": "prince-bishopric-of-liege", "verb": "DEFINES", "note": "Served as Prince-Bishop of Liège 1313–1344"}, {"target": "house-of-the-mark", "verb": "OCCURS_IN", "note": "Was a member of the Westphalian County of Mark dynasty"}, {"target": "commune-of-liege", "verb": "OCCURS_IN", "note": "His episcopate was marked by continuous conflict with Liège's assertive urban commune and craft guilds"}]
  }),

  ("adolfo-armando-uriona", {
    "summary": "Adolfo Armando Uriona is an Argentine Roman Catholic bishop, serving the Church in one of Latin America's most historically Catholic nations. Argentina's Catholic Church has played a complex and sometimes controversial role in national life — deeply embedded in Argentine culture, identity, and politics, while also carrying the difficult legacy of its relationship with the military dictatorship (1976–1983) that murdered thousands of Argentines including clergy and religious.\n\nThe post-dictatorship Argentine Church has been engaged in a long process of reckoning with that legacy while also navigating the rapid social changes of the late twentieth and early twenty-first centuries — including the legalisation of same-sex marriage in 2010 and abortion in 2020, both of which the Church actively opposed. Bishops like Uriona serve within this highly politicised and historically charged context.\n\nHis episcopal ministry reflects the Argentine Church's complex navigation of its prophetic and institutional responsibilities in a country where Catholicism retains deep cultural roots even as formal religious practice declines. The Argentine Church is also the homeland of Pope Francis (Jorge Mario Bergoglio), and the Franciscan priorities of the current pontificate have particular resonance in Argentine Catholicism.",
    "hs": {"significanceScore": 3, "significanceNarrative": "Argentine Catholic bishop serving in a Church navigating the legacy of its dictatorship-era compromises while implementing Pope Francis's reform priorities in the pontiff's homeland.", "significanceCategory": "local"},
    "causes": ["Argentine Church's dictatorship-era legacy required a new generation of bishops committed to reconciliation and institutional renewal", "Pope Francis's reform priorities have particular resonance and demand in the Argentine Church as his homeland", "Argentina's rapid social liberalisation required episcopal responses to contested legislative changes"],
    "effects": ["His ministry contributes to the Argentine Church's pastoral mission and institutional renewal", "His episcopate reflects the implementation of Franciscan priorities in the Church of the pope's homeland"],
    "rels": [{"target": "catholic-church-in-argentina", "verb": "DEFINES", "note": "Serves as bishop in the Argentine Catholic Church"}, {"target": "pope-francis", "verb": "INFLUENCES", "note": "His ministry is shaped by the priorities of the Argentine-born Pope Francis"}]
  }),

  ("adolfo-gonzalez-montes", {
    "summary": "Adolfo González Montes is a Spanish Roman Catholic bishop and theologian, known for his expertise in ecumenism and fundamental theology. He has served as Bishop of Almería in Andalusia and has been an important figure in Catholic-Protestant dialogue in Spain, contributing to the Church's post-Vatican II commitment to the ecumenical movement. His theological work has addressed the foundations of Christian faith and the principles of inter-Christian dialogue.\n\nSpain's Catholic Church carries the weight of its unique historical experience — a Church that was profoundly dominant in Spanish culture and society for centuries, then subjected to violent anticlerical persecution in the Civil War (1936–1939), before being closely associated with the Franco regime (1939–1975) and subsequently navigating the democratic transition. The Spanish Church's contemporary situation involves managing the legacy of this complex history while engaging with a rapidly secularising society.\n\nGonzález Montes's theological expertise in ecumenism is particularly significant in a Spanish context, where the Reformation had minimal impact and Protestantism remains a small minority. His work has contributed to building bridges between Spanish Catholicism and its Protestant neighbours at a moment when Spain is becoming an increasingly religiously plural society.",
    "hs": {"significanceScore": 4, "significanceNarrative": "Spanish bishop and ecumenical theologian who contributed to Catholic-Protestant dialogue in a country where the Reformation had minimal historical impact, while navigating the Spanish Church's post-Franco secularisation.", "significanceCategory": "regional"},
    "causes": ["Vatican II's ecumenical commitment required bishops with theological expertise in inter-Christian dialogue", "Spain's increasing religious pluralism created demand for episcopal leadership capable of engaging with non-Catholic Christians", "Spanish Church's post-Franco renewal required theological resources for navigating a rapidly changing secular society"],
    "effects": ["His theological work in fundamental theology and ecumenism contributed to Spanish Catholic scholarship", "His episcopal ministry at Almería maintained the Church's pastoral mission in Andalusia", "His ecumenical expertise contributed to Catholic-Protestant dialogue in a country historically resistant to Protestant Christianity"],
    "rels": [{"target": "diocese-of-almeria", "verb": "DEFINES", "note": "Served as Bishop of Almería in Andalusia"}, {"target": "ecumenical-movement", "verb": "INFLUENCES", "note": "Was a theologian and practitioner of Catholic ecumenical dialogue"}, {"target": "second-vatican-council", "verb": "INFLUENCES", "note": "His ecumenical work implemented Vatican II's commitment to inter-Christian dialogue"}]
  }),

  ("adolfo-rodriguez-vidal", {
    "summary": "Adolfo Rodríguez Vidal is a Chilean Roman Catholic bishop who has served the Church in Chile, a country whose Catholic history includes both a deeply conservative ecclesiastical tradition and a recent traumatic reckoning with widespread clerical sexual abuse. Chile's Catholic Church was shaken to its foundations by the abuse scandal surrounding Fr. Fernando Karadima and the Sodalitium Christianae Vitae, which led to the resignation of multiple bishops and a profound crisis of institutional credibility.\n\nChile's religious landscape has shifted dramatically in recent decades — from one of Latin America's most strongly Catholic nations in the mid-twentieth century to a society where the Church's credibility has been severely damaged. The decline in Mass attendance and formal Catholic identity has accelerated since the 2018 abuse revelations, making the Chilean episcopate's task of pastoral renewal particularly urgent.\n\nRodríguez Vidal's episcopal service represents the Chilean Church's effort to maintain its mission while rebuilding credibility and trust. His ministry reflects the challenge facing Chilean bishops in the post-Karadima era: demonstrating that the Church can reform itself, serve the vulnerable faithfully, and recover its prophetic witness in a society that has good reason to be sceptical of its institutional integrity.",
    "hs": {"significanceScore": 3, "significanceNarrative": "Chilean bishop serving the Church through its profound institutional crisis following the Karadima abuse scandal, representing the episcopate's efforts at pastoral renewal and credibility recovery.", "significanceCategory": "local"},
    "causes": ["Chilean clerical abuse scandal (Karadima and others) created a profound crisis of episcopal credibility and institutional trust", "Chile's rapid secularisation and declining Catholic identity required prophetic episcopal leadership committed to reform", "Pope Francis's direct intervention in Chile's abuse crisis demanded episcopal accountability and renewal"],
    "effects": ["His episcopal service contributes to the Chilean Church's pastoral mission during its most serious institutional crisis", "His ministry reflects the post-abuse-scandal Church's effort to rebuild credibility through authentic pastoral service"],
    "rels": [{"target": "catholic-church-in-chile", "verb": "DEFINES", "note": "Serves as bishop in the Chilean Catholic Church"}, {"target": "pope-francis", "verb": "INFLUENCES", "note": "His ministry is shaped by Francis's intervention in Chile's abuse crisis and demand for episcopal accountability"}]
  }),

  ("adolfo-tito-yllana", {
    "summary": "Adolfo Tito Yllana is a Filipino Roman Catholic bishop and has served as Apostolic Nuncio — the Vatican's diplomatic representative — to multiple countries. His career represents the Filipino Church's growing role in the global Catholic diplomatic service, as the Philippines is one of the world's most strongly Catholic nations and has produced an increasing number of ecclesiastical diplomats and curial figures in recent decades.\n\nThe Philippines' Catholic Church is remarkable in the Asian context — with over 85% of the population Catholic, it is the dominant Christian presence in Southeast Asia and one of the largest national Catholic churches in the world. Filipino Catholicism is characterised by intense popular piety, a strong missionary tradition, and the Church's deep integration with national cultural identity since the Spanish colonial period began in the sixteenth century.\n\nYllana's career as a nuncio places him in the distinctive role of representing the Holy See to national governments, combining diplomatic skill with ecclesiastical authority. Apostolic nuncios serve as the formal link between the Vatican and national churches and governments, playing a key role in episcopal appointments, the management of Church-state relationships, and the communication of papal priorities to local churches.",
    "hs": {"significanceScore": 4, "significanceNarrative": "Filipino bishop and Apostolic Nuncio representing the Vatican's diplomatic service, embodying the Philippine Church's growing global role in one of the world's most strongly Catholic nations.", "significanceCategory": "regional"},
    "causes": ["Philippines' status as Asia's largest Catholic nation created demand for Filipino clergy in the Vatican's global diplomatic service", "Holy See's need for skilled diplomatic representatives required bishops with both ecclesiastical formation and diplomatic aptitude", "Filipino Church's strong missionary tradition prepared its clergy for international service"],
    "effects": ["His nunciature service extended Filipino Catholic diplomatic presence in the Holy See's global network", "His role as nuncio contributed to managing Church-state relations in the countries he served", "His career reflects the Philippine Church's growing contribution to the global Catholic institutional structure"],
    "rels": [{"target": "holy-see", "verb": "DEFINES", "note": "Served as Apostolic Nuncio — the Vatican's diplomatic representative"}, {"target": "catholic-church-in-the-philippines", "verb": "OCCURS_IN", "note": "Represents the Filipino Church's growing contribution to Vatican diplomacy"}, {"target": "pope-francis", "verb": "OCCURS_IN", "note": "Served as nuncio under the pontificate of Pope Francis"}]
  }),

  ("adolfo-zon-pereira", {
    "summary": "Adolfo Zon Pereira is a Brazilian Roman Catholic bishop, part of the vast Brazilian episcopate that serves the world's largest national Catholic population. His ministry in Brazil reflects the complexities of a Church that has been central to Brazilian national identity since the Portuguese colonial period but now navigates a dramatically changed religious landscape.\n\nBrazil's religious transformation in the late twentieth and early twenty-first centuries has been one of the most dramatic in Catholic history. In 1970 Brazil was 92% Catholic; today that figure has fallen below 50% in many surveys, with Pentecostalism now claiming the allegiance of approximately 30% of the population. This shift has profoundly challenged the Catholic Church's assumptions about its social role and institutional security.\n\nZon Pereira's episcopal service takes place in this context of radical religious change, requiring pastoral leadership that can respond to a more competitive religious marketplace, maintain the Church's extensive social service networks, and renew its evangelistic witness for a generation that has been exposed to compelling Pentecostal alternatives. His ministry reflects the Brazilian Church's urgent work of renewal and self-examination.",
    "hs": {"significanceScore": 3, "significanceNarrative": "Brazilian Catholic bishop serving in a Church experiencing dramatic loss of market share to Pentecostalism, representing the episcopate's response to the most significant religious transformation in Brazil's history.", "significanceCategory": "local"},
    "causes": ["Pentecostal growth in Brazil created competitive religious pressure requiring Catholic institutional and pastoral renewal", "Brazil's vast territory and social inequality required a large, committed episcopate to maintain the Church's charitable and pastoral presence", "Post-Vatican II renewal demanded bishops capable of engaging with changing pastoral contexts"],
    "effects": ["Contributed to his diocese's pastoral mission during Brazil's dramatic religious transformation", "His ministry reflects the Catholic Church's response to Pentecostal competition in one of the world's most religiously dynamic environments"],
    "rels": [{"target": "catholic-church-in-brazil", "verb": "DEFINES", "note": "Serves as bishop in the Brazilian Catholic Church"}, {"target": "pentecostalism", "verb": "OCCURS_IN", "note": "His episcopate is defined in part by the challenge of Pentecostal growth in Brazil"}]
  }),

  ("adolph-ii-prince-of-anhalt-kothen", {
    "summary": "Adolph II, Prince of Anhalt-Köthen (1458–1526) was Bishop of Merseburg from 1514 to 1526 — a critical period that coincided exactly with the outbreak and early spread of the Protestant Reformation. A member of the House of Anhalt, one of the princely dynasties of central Germany, his episcopate at Merseburg placed him as a bishop of Saxony's most important sees precisely when Martin Luther's challenge to the Roman Church was reshaping the religious landscape of exactly his territory.\n\nMerseburg was among the oldest episcopal sees in Germany, founded in 968 during the Ottonian eastward expansion, and its diocese covered much of electoral Saxony — the territory of Frederick the Wise, Luther's protecting prince. Adolph II's episcopate thus witnessed at first hand the Reformation's impact on a diocese whose lay overlord was the Reformation's most important political patron. His management of this impossible situation — a Catholic bishop in a prince-elector's territory that was actively protecting the most radical religious reformer in Europe — defined his entire tenure.\n\nAdolph II was the last Catholic Bishop of Merseburg before the diocese was secularised after his death. His failure to contain or redirect the Reformation's impact in his diocese made his episcopate the final chapter of Merseburg's medieval Catholic history, after which the diocese passed into Protestant hands.",
    "hs": {"significanceScore": 5, "significanceNarrative": "Last Catholic Bishop of Merseburg whose episcopate coincided exactly with the Reformation's outbreak in the territory of Luther's protecting prince, making him the final custodian of the diocese's medieval Catholic identity.", "significanceCategory": "regional"},
    "causes": ["Protestant Reformation's outbreak in Saxony directly challenged Catholic bishops within the territory of the protecting princes", "Elector Frederick the Wise's protection of Luther made Merseburg's bishop powerless to contain the Reformation in his diocese", "House of Anhalt's secular dynastic interests complicated Adolph II's episcopal response to the Reformation"],
    "effects": ["His episcopate marked the end of medieval Catholic history in the Diocese of Merseburg", "His failure to contain the Reformation in Saxony contributed to the diocese's eventual secularisation after his death", "His tenure documents the impossible position of Catholic bishops in Luther's immediate geographic sphere"],
    "rels": [{"target": "diocese-of-merseburg", "verb": "DEFINES", "note": "Served as last Catholic Bishop of Merseburg 1514–1526"}, {"target": "protestant-reformation", "verb": "OCCURS_IN", "note": "His episcopate coincided exactly with the Reformation's outbreak and early spread"}, {"target": "martin-luther", "verb": "OCCURS_IN", "note": "His diocese overlapped with the territory where Luther lived and was protected by Frederick the Wise"}, {"target": "house-of-anhalt", "verb": "OCCURS_IN", "note": "Was a member of the princely House of Anhalt"}]
  }),

  ("adolph-kolping", {
    "summary": "Blessed Adolph Kolping (1813–1865) was a German Catholic priest and social reformer who founded the Kolping Society (Kolpingwerk) — one of the most significant Catholic lay associations in nineteenth-century Europe. Born into poverty as a shoemaker's son in the Rhineland, Kolping experienced firsthand the social dislocation of artisans in the early industrial era before entering the priesthood and dedicating his ministry to the welfare of young journeymen displaced by industrialisation.\n\nKolping's insight was that the social question of the nineteenth century — the condition of the working class in an industrialising economy — required not just charitable relief but community formation. The Kolping Houses he established provided journeymen and young workers with accommodation, education, fellowship, and spiritual formation, creating a Catholic social network that spread across Germany, Austria, and eventually the world. His approach anticipated the Catholic social teaching that would be formalised in Pope Leo XIII's Rerum Novarum (1891), making him one of the practical pioneers of Catholic social action.\n\nKolping was beatified by Pope John Paul II in 1991. The Kolping Society he founded now has over 400,000 members in more than 60 countries, making him one of the most far-reaching figures in the history of Catholic lay movements. His life — from impoverished craftsman to priest to founder of an international social movement — is one of the most remarkable stories in nineteenth-century Catholicism.",
    "hs": {"significanceScore": 8, "significanceNarrative": "Pioneer of Catholic social action who founded the Kolping Society to address industrial-era workers' dislocation, anticipating Rerum Novarum and creating one of Catholicism's most enduring lay social movements.", "significanceCategory": "world-changing"},
    "causes": ["Industrial Revolution's displacement of artisan craftsmen created social crisis for journeymen without community or support", "Catholic Church's response to the social question required practical reformers willing to build alternative institutions", "Kolping's personal experience of poverty as a journeyman gave him the insight and motivation to create community-based social ministry"],
    "effects": ["Founded the Kolping Society, now 400,000+ members in 60+ countries — one of Catholicism's most durable lay social movements", "Anticipated Rerum Novarum (1891) by developing the practical model of Catholic social action that would become official teaching", "His Kolping Houses provided the template for Catholic worker community institutions across German-speaking Europe", "His beatification in 1991 confirmed his permanent place in the Catholic hagiographic tradition as a saint of social reform", "His model of community formation as response to social dislocation influenced Catholic social thought and action globally"],
    "rels": [{"target": "kolping-society", "verb": "DEFINES", "note": "Founded the Kolping Society (Kolpingwerk) for young journeymen and workers"}, {"target": "rerum-novarum", "verb": "INFLUENCES", "note": "Anticipated the Catholic social teaching of Leo XIII's Rerum Novarum through his practical social work"}, {"target": "catholic-social-teaching", "verb": "DEFINES", "note": "Was a founding practical pioneer of the Catholic social action tradition"}, {"target": "pope-john-paul-ii", "verb": "OCCURS_IN", "note": "Was beatified by Pope John Paul II in 1991"}, {"target": "industrial-revolution", "verb": "OCCURS_IN", "note": "His social ministry was a direct response to the Industrial Revolution's displacement of artisan workers"}, {"target": "rhineland", "verb": "OCCURS_IN", "note": "Was born and began his ministry in the Rhineland"}]
  }),

  ("adolphus-xiii-of-holstein", {
    "summary": "Adolphus XIII of Holstein-Schauenburg (c. 1524–1576) was the last Count of Holstein-Schauenburg, presiding over the extinction of his dynasty's independent comital line. A member of the Holstein-Schauenburg house that had governed the Schauenburg and Holstein territories since the twelfth century, Adolphus XIII ruled in the era of the Protestant Reformation's consolidation in northern Germany, when the region's small dynasties were navigating the religious and political upheavals that accompanied the Reformation's spread.\n\nThe Holstein-Schauenburg dynasty's extinction with Adolphus XIII represents the typical pattern of many smaller German dynasties in the Reformation era — the combination of dynastic failure (lack of male heirs), religious change, and the consolidation of larger territorial states absorbed many formerly independent counties. The Holstein territories passed to Denmark after the dynasty's extinction, while Schauenburg's fate involved complex negotiations among neighbouring powers.\n\nAdolphus XIII's reign thus marks the end of a dynasty whose roots went back to the high medieval period. His name — reflecting the long tradition of 'Adolph' as a Holstein-Schauenburg dynastic name, a tradition going back to the famous Count Adolf II of Holstein who colonised the Slavic east — represents the accumulated prestige of a house that had shaped northern German history for four centuries before its extinction.",
    "hs": {"significanceScore": 4, "significanceNarrative": "Last Count of Holstein-Schauenburg whose death extinguished a dynasty with four centuries of northern German history, representative of the many small dynasties absorbed during the Reformation era's territorial consolidation.", "significanceCategory": "regional"},
    "causes": ["Dynastic extinction through failure of male heirs was a constant risk for smaller German comital families", "Reformation era's political and religious upheaval accelerated the absorption of smaller dynasties by larger territorial states", "The Holstein-Schauenburg dynasty's centuries-long decline in resources and influence made absorption by neighbouring powers inevitable"],
    "effects": ["His death extinguished the Holstein-Schauenburg comital line after four centuries of northern German history", "The Holstein territories passed to Denmark, reshaping the political geography of the Danish-German borderland", "His reign documents the Reformation era's impact on northern German dynastic politics"],
    "rels": [{"target": "county-of-holstein-schauenburg", "verb": "DEFINES", "note": "Was the last Count of Holstein-Schauenburg"}, {"target": "protestant-reformation", "verb": "OCCURS_IN", "note": "His reign coincided with the Reformation's consolidation in northern Germany"}, {"target": "denmark", "verb": "OCCURS_IN", "note": "Holstein territories passed to Denmark after his dynasty's extinction"}]
  }),

  ("adrian-fortescue", {
    "summary": "Blessed Adrian Fortescue (c. 1476–1539) was an English knight, member of the Order of St John of Jerusalem (Knights Hospitaller), and martyr under Henry VIII. Born into the Fortescue family — a distinguished English gentry family with a long tradition of royal service — he was twice married and served as a justice of the peace and knight before being arrested and executed during the Henrician Reformation's assault on those who refused to accept royal supremacy over the Church.\n\nFortescue's martyrdom is unusual in that the historical record provides little clarity about the specific charge that condemned him. He was attainted by Act of Parliament in 1534 and executed in 1539, but the exact nature of his offence — whether specific resistance to the Act of Supremacy or a more general allegiance to traditional religion and the papal connection — remains uncertain. This ambiguity did not prevent his beatification: Pope Leo XIII beatified him in 1895 as a martyr of the English Reformation.\n\nAs a member of the Knights of St John, Fortescue represented the ancient tradition of chivalric Catholic piety that the Tudor Reformation was dismantling. His layman's martyrdom — dying not as a priest or bishop but as an English gentleman who refused to abjure his allegiance to the Roman Church — gave his witness a particular character: the faith of the Catholic English gentry as it faced the Reformation's demands for conformity.",
    "hs": {"significanceScore": 5, "significanceNarrative": "English knight and Hospitaller beatified as a martyr of the Henrician Reformation, whose death without clear specific charges exemplifies the arbitrary brutality of Henry VIII's assault on traditional Catholic allegiances.", "significanceCategory": "regional"},
    "causes": ["Henry VIII's Act of Supremacy (1534) demanded conformity that Catholic gentry like Fortescue refused to provide", "Henrician Reformation's suppression of traditional Catholic allegiances targeted laymen as well as clergy", "Fortescue's membership in the Knights Hospitaller connected him to a Catholic institution Henry VIII was dismantling"],
    "effects": ["His martyrdom contributed to the tradition of English Catholic resistance to the Henrician Reformation", "His beatification by Leo XIII in 1895 established his place in the English Catholic hagiographic tradition", "His lay martyrdom provided an example for English Catholic gentry who maintained their faith under persecution", "His execution illustrated the Henrician Reformation's willingness to attaint and execute prominent gentry for religious non-compliance"],
    "rels": [{"target": "knights-hospitaller", "verb": "OCCURS_IN", "note": "Was a member of the Order of St John (Knights Hospitaller)"}, {"target": "henry-viii", "verb": "OCCURS_IN", "note": "Was attainted and executed under Henry VIII during the Henrician Reformation"}, {"target": "english-reformation", "verb": "OCCURS_IN", "note": "Was a martyr of the Henrician Reformation, beatified for dying rather than accepting royal supremacy"}, {"target": "pope-leo-xiii", "verb": "OCCURS_IN", "note": "Was beatified by Pope Leo XIII in 1895"}]
  }),

  ("adrian-gouffier-de-boissy", {
    "summary": "Adrian Gouffier de Boissy (c. 1479–1523) was a French cardinal and one of the most prominent ecclesiastical figures of the French Renaissance court. A member of the powerful Gouffier family — one of the great court dynasties under Louis XII and Francis I — he was made Cardinal of Boissy in 1515 by Pope Leo X as part of the Franco-papal diplomacy that characterised the early reign of Francis I. His brother Guillaume Gouffier, lord of Bonnivet, was one of Francis I's most intimate companions, giving the family extraordinary court influence.\n\nAdrian Gouffier's cardinalate represents the nepotistic and politically driven character of Renaissance ecclesiastical appointments, in which great family connections were often more important than theological distinction or pastoral achievement. His elevation at approximately 36 years old on the basis of family influence rather than ecclesiastical merit was typical of the Renaissance cardinalate that the Council of Trent would later seek to reform.\n\nHis brief career as a cardinal — he died in 1523 at approximately 44 — was conducted at the height of Renaissance court Catholicism in France, when the French Church was deeply integrated into the social and cultural life of the Valois monarchy. His death preceded the outbreak of the French Wars of Religion by four decades, placing him in the last generation of French Catholic leaders who experienced the Reformation only in its earliest stirrings.",
    "hs": {"significanceScore": 4, "significanceNarrative": "French Renaissance cardinal whose appointment exemplified the nepotistic character of the pre-Tridentine cardinalate, elevated through family connections at the court of Francis I.", "significanceCategory": "regional"},
    "causes": ["Gouffier family's exceptional influence at Francis I's court created access to the highest ecclesiastical offices", "Pope Leo X's diplomatic relationship with France required generous ecclesiastical appointments to French court families", "Renaissance cardinalate's character as a court institution rewarded political and dynastic rather than pastoral merit"],
    "effects": ["His cardinalate demonstrated the pre-Tridentine Church's vulnerability to nepotistic appointments that the Council of Trent would later address", "His family's court influence shaped Franco-papal relations during the early reign of Francis I", "His brief career represents the French Renaissance Church's integration with Valois court culture"],
    "rels": [{"target": "college-of-cardinals", "verb": "DEFINES", "note": "Served as Cardinal of Boissy from 1515"}, {"target": "pope-leo-x", "verb": "OCCURS_IN", "note": "Was elevated to the cardinalate by Pope Leo X in 1515"}, {"target": "francis-i-of-france", "verb": "OCCURS_IN", "note": "Was a prominent figure in the French Church at the court of Francis I"}, {"target": "gouffier-family", "verb": "OCCURS_IN", "note": "Was a member of the Gouffier family, one of the great dynasties of the Valois court"}]
  }),

  ("adrian-i", {
    "summary": "Pope Adrian I (reigned 772–795) had the longest pontificate of the eighth century and one of the most consequential in the entire first millennium. His reign coincided with the rise of Charlemagne, and the partnership he forged with the Frankish king transformed the political and religious landscape of Western Europe. Adrian I requested Charlemagne's military intervention against the Lombards in 773–774, resulting in their defeat and the establishment of the Papal States as an independent political entity — the foundation of papal temporal sovereignty that would endure until 1870.\n\nAdrian I's reign saw the consolidation of the Donation of Constantine's ideological use — the claim that Emperor Constantine had granted the papacy temporal sovereignty over Italy — and the practical establishment of a papal territorial state protected by Frankish military power. His close relationship with Charlemagne, expressed in a famous correspondence, shaped the model of Church-state relations that would dominate medieval European thought for centuries.\n\nAt the Second Council of Nicaea (787) — the last ecumenical council recognised by both East and West — Adrian I's legates played a key role in the restoration of icon veneration after the first phase of Byzantine Iconoclasm. His pontificate thus touched the central theological controversy of the Byzantine world while simultaneously reshaping the political geography of the Latin West. His death in 795 was mourned by Charlemagne with an inscription that survives to this day.",
    "hs": {"significanceScore": 8, "significanceNarrative": "Pope whose 23-year partnership with Charlemagne established the Papal States, defined the Carolingian Church-state model, and played a key role at Nicaea II — one of the most consequential pontificates of the first millennium.", "significanceCategory": "world-changing"},
    "causes": ["Lombard military threat to Rome required Frankish protection, leading Adrian to cultivate Charlemagne as the papacy's champion", "Byzantine Iconoclasm's resolution at Nicaea II required active papal diplomatic engagement with the Eastern Church", "Papal need for temporal sovereignty and territorial security drove the establishment of the Papal States under Frankish protection"],
    "effects": ["Established the Papal States as an independent political entity under Frankish protection — an institution that lasted until 1870", "His partnership with Charlemagne defined the Carolingian model of Church-state relations that shaped medieval European political thought", "His legates' role at Nicaea II (787) contributed to the restoration of icon veneration and the last ecumenical council recognised by both East and West", "Consolidated the ideological claim to papal temporal sovereignty that would drive medieval Church-state conflicts for centuries", "His 23-year pontificate gave the papacy an institutional stability and territorial security it had not previously possessed"],
    "rels": [{"target": "charlemagne", "verb": "DEFINES", "note": "Forged the defining partnership of the eighth century, establishing the Carolingian Church-state model"}, {"target": "papal-states", "verb": "DEFINES", "note": "His pontificate established the Papal States as an independent political entity under Frankish protection"}, {"target": "second-council-of-nicaea", "verb": "DEFINES", "note": "His legates played key roles at Nicaea II (787), the last ecumenical council recognised by both East and West"}, {"target": "lombards", "verb": "OCCURS_IN", "note": "Requested Charlemagne's intervention against the Lombards, resulting in their defeat"}, {"target": "byzantine-iconoclasm", "verb": "OCCURS_IN", "note": "His pontificate coincided with the resolution of the first phase of Byzantine Iconoclasm at Nicaea II"}]
  }),

  ("adrian-ii", {
    "summary": "Pope Adrian II (reigned 867–872) faced one of the most complex pontificates of the ninth century, caught between the Carolingian succession crisis, the Photian Schism that was rending the Eastern Church, and the evangelical expansion into the Slavic world. Elected at approximately 80 years old after twice refusing the papacy, Adrian II brought advanced age and limited energy to an office that demanded extraordinary political skill.\n\nThe Photian Schism — the bitter controversy over whether Photius or Ignatius was the legitimate Patriarch of Constantinople — dominated Adrian II's pontificate. The Fourth Council of Constantinople (869–870), which condemned Photius and restored Ignatius, was convened under his authority and is recognised as an Ecumenical Council in Catholic tradition. This settlement, however, proved temporary — Photius was later restored.\n\nAdrian II's pontificate also coincided with the mission of Saints Cyril and Methodius to the Slavs. The two Greek brothers, who had created the Glagolitic alphabet to translate Scripture into Old Church Slavonic, visited Rome in 867 to seek papal support for their Slavic mission. Adrian II gave them his blessing and approval, authorising the use of Slavonic in the liturgy — a decision of enormous cultural consequence for the subsequent development of Slavic Christianity and literacy.",
    "hs": {"significanceScore": 6, "significanceNarrative": "Pope who convened the Fourth Council of Constantinople addressing the Photian Schism and authorised Cyril and Methodius's Slavic mission — a decision that shaped the cultural and religious development of Eastern Europe.", "significanceCategory": "world-changing"},
    "causes": ["Photian Schism's division of the Eastern Church required papal arbitration and a formal council to resolve claims of rival patriarchs", "Cyril and Methodius's Slavic mission needed papal endorsement to overcome Latin-rite opposition to Slavonic liturgy", "Carolingian succession crisis after Louis II's death created political instability that impacted the papacy's secular relationships"],
    "effects": ["His convening of the Fourth Council of Constantinople (869–870) established the canonical resolution of the first Photian Schism", "His endorsement of Cyril and Methodius's Slavic mission authorised the use of Slavonic in the liturgy — shaping Eastern European Christianity and literacy", "His pontificate contributed to the expansion of Christianity into the Slavic world through his support for the Byzantine missionaries", "His aging pontificate managed the complex diplomatic demands of Eastern and Western Church politics simultaneously"],
    "rels": [{"target": "papacy", "verb": "DEFINES", "note": "Served as Pope Adrian II 867–872"}, {"target": "fourth-council-of-constantinople", "verb": "DEFINES", "note": "Convened the Fourth Council of Constantinople (869–870) addressing the Photian Schism"}, {"target": "photian-schism", "verb": "DEFINES", "note": "His pontificate was largely defined by the Photian Schism between Photius and Ignatius of Constantinople"}, {"target": "cyril-and-methodius", "verb": "INFLUENCES", "note": "Endorsed the Slavic mission of Cyril and Methodius, authorising Slavonic liturgy"}, {"target": "slavic-peoples", "verb": "INFLUENCES", "note": "His endorsement of Slavonic liturgy shaped the cultural and religious development of Eastern Europe"}]
  }),

  ("adrian-iii", {
    "summary": "Pope Adrian III (reigned 884–885) had one of the briefest pontificates in the entire history of the papacy, dying after only slightly more than a year in office. He was elected at a moment of intense political turbulence in Italy, when the Carolingian Empire was fragmenting and the Italian peninsula was contested by multiple competing dynasties. The papacy in this era was deeply vulnerable to Roman aristocratic factions and to the competing claims of Carolingian successors.\n\nAdrian III's brief reign came at a critical juncture: the main Carolingian emperor, Charles the Fat, was attempting to maintain unity of a fragmenting empire while the papacy needed a reliable secular protector. Adrian III died on his way to meet Charles the Fat in Worms, an intended meeting that might have clarified the political situation. His death cut short whatever policy he had intended.\n\nDespite the extreme brevity of his pontificate, Adrian III was canonised — his cult was approved in the seventeenth century and his feast day is 8 July. This unusual honour for a pope who achieved so little in institutional terms reflects the early medieval Church's recognition of personal holiness as the primary qualification for sainthood, separate from political achievement. His canonisation suggests a reputation for personal virtue that survived the opacity of his short reign.",
    "hs": {"significanceScore": 3, "significanceNarrative": "Pope of barely over a year whose canonisation recognised personal holiness despite institutional insignificance, reigning during the final disintegration of the Carolingian Empire.", "significanceCategory": "local"},
    "causes": ["Carolingian imperial fragmentation created political instability that required papal diplomatic engagement with competing dynastic claimants", "Roman aristocratic factions made the late ninth-century papacy vulnerable to political interference", "The papacy's need for a strong secular protector drove efforts to maintain Carolingian imperial unity"],
    "effects": ["His canonisation established his place in the Catholic hagiographic tradition despite his brief and inconclusive pontificate", "His death en route to meet Charles the Fat left unresolved the political questions about papacy-empire relations in the fragmenting Carolingian world"],
    "rels": [{"target": "papacy", "verb": "DEFINES", "note": "Served as Pope Adrian III 884–885"}, {"target": "carolingian-empire", "verb": "OCCURS_IN", "note": "His pontificate coincided with the final fragmentation of the Carolingian Empire"}, {"target": "charles-the-fat", "verb": "OCCURS_IN", "note": "Died on his way to meet Charles the Fat at Worms"}]
  }),

  ("adrian-jozef-galbas", {
    "summary": "Adrian Józef Galbas SAC (born 1970) is a Polish Roman Catholic bishop and member of the Pallottine Fathers (Societas Apostolatus Catholici), appointed auxiliary bishop and later coadjutor of the Archdiocese of Katowice in Upper Silesia. His appointment reflects Pope Francis's priorities for the Polish Church — a Church marked by extraordinary religious vitality and institutional strength but also by the tensions between traditional Polish Catholicism and the Church's global reform agenda.\n\nPoland's Catholic Church is one of Europe's most robustly practising national churches, with Mass attendance rates far above the Western European average and deep identification between Catholic faith and Polish national identity going back to the partitions era. Yet the Polish Church has also been challenged by clerical abuse scandals, generational change, and the political controversies arising from its close identification with the right-wing Law and Justice party.\n\nGalbas's Pallottine formation emphasises missionary outreach and lay apostolate — priorities that align with Pope Francis's vision for a more missionary and synodal Church. His appointment as coadjutor of Katowice — one of Poland's most important industrial archdioceses — reflects an intention to bring a reform-oriented bishop to one of Polish Catholicism's key sees in Upper Silesia.",
    "hs": {"significanceScore": 4, "significanceNarrative": "Polish Pallottine bishop appointed to the Archdiocese of Katowice reflecting Pope Francis's reform priorities for a Polish Church navigating traditionalism, abuse scandals, and political controversy.", "significanceCategory": "regional"},
    "causes": ["Pope Francis's reform priorities for the Polish Church required appointing bishops committed to missionary outreach and synodality", "Polish Church's clerical abuse scandals demanded episcopal leadership committed to accountability and transparency", "Katowice's importance as a major industrial archdiocese required a coadjutor capable of leading institutional renewal"],
    "effects": ["His appointment signals Pope Francis's intention to introduce reform priorities into one of Poland's key archdioceses", "His Pallottine missionary emphasis offers an alternative vision to the Polish Church's more defensive traditionalism", "His coadjutorship positions him to lead the Archdiocese of Katowice through a potentially significant period of renewal"],
    "rels": [{"target": "archdiocese-of-katowice", "verb": "DEFINES", "note": "Appointed coadjutor of the Archdiocese of Katowice in Upper Silesia"}, {"target": "pallottine-fathers", "verb": "OCCURS_IN", "note": "Is a member of the Societas Apostolatus Catholici (Pallottine Fathers)"}, {"target": "pope-francis", "verb": "INFLUENCES", "note": "His appointment reflects Pope Francis's reform priorities for the Polish Church"}, {"target": "catholic-church-in-poland", "verb": "OCCURS_IN", "note": "Serves in the Polish Catholic Church as a reform-oriented appointment"}]
  }),

  ("adriano-castellesi", {
    "summary": "Adriano Castellesi (c. 1461–c. 1521) was an Italian cardinal, humanist scholar, and papal diplomat who served as an agent of the English crown at the Vatican before his career collapsed spectacularly in connection with the alleged conspiracy to poison Pope Leo X. Born in Corneto (modern Tarquinia), he became a significant figure in the Renaissance humanist network connecting the Italian courts with the English Lancastrian and early Tudor courts.\n\nCastellesi served as papal tax collector (nuncio) in England from 1490 and became Bishop of Hereford (1502) and then Bath and Wells (1504), accumulating English benefices in absentia while residing in Rome as a humanist scholar and courtier. He was made a cardinal in 1503 by Pope Julius II. His Latin literary work 'De vera philosophia' was respected by Erasmus, placing him among the serious humanist scholars of the Renaissance cardinalate.\n\nHis career ended in disaster: implicated in the alleged plot to poison Leo X in 1517, he was stripped of his cardinalate and fled Rome. He was last documented alive in Venice in 1521, and the circumstances of his death remain uncertain — possibly murdered by his own servant. His career exemplifies the Renaissance cardinalate's combination of genuine scholarly accomplishment, political intrigue, and personal ambition.",
    "hs": {"significanceScore": 5, "significanceNarrative": "Renaissance cardinal and humanist scholar whose career connecting the English Tudor court with Renaissance Rome ended in catastrophic disgrace following an alleged papal assassination plot.", "significanceCategory": "regional"},
    "causes": ["Renaissance papacy's diplomatic needs required educated Italian humanists who could serve as nuncios and tax collectors at foreign courts", "Henry VII and Henry VIII's England needed skilled intermediaries with the papacy for diplomatic and ecclesiastical business", "Renaissance cardinalate's culture of patronage and scholarship rewarded humanists like Castellesi with high ecclesiastical office"],
    "effects": ["His English diplomatic service and absentee benefices exemplify the pre-Tridentine Church's abuse of non-residency that reformers attacked", "His connection with Erasmus demonstrates the Renaissance humanist network's reach across national boundaries", "His disgrace in the alleged Leo X poisoning plot illustrates the dangerous political environment of the Renaissance papacy", "His fate — stripped of cardinalate and dying obscurely — demonstrates the Renaissance court's ruthlessness"],
    "rels": [{"target": "college-of-cardinals", "verb": "DEFINES", "note": "Served as Cardinal from 1503 until stripped of the cardinalate in 1517"}, {"target": "henry-vii-of-england", "verb": "OCCURS_IN", "note": "Served as papal agent and nuncio at the English court under Henry VII"}, {"target": "pope-julius-ii", "verb": "OCCURS_IN", "note": "Was elevated to the cardinalate by Pope Julius II in 1503"}, {"target": "pope-leo-x", "verb": "OCCURS_IN", "note": "Was implicated in an alleged plot to poison Leo X and stripped of his cardinalate"}, {"target": "erasmus", "verb": "OCCURS_IN", "note": "His Latin humanist scholarship was respected by Erasmus"}]
  }),

  ("adriano-bernareggi", {
    "summary": "Adriano Bernareggi (1884–1953) was an Italian Catholic bishop who served as Bishop of Bergamo from 1932 to 1953 — an episcopate that coincided with the Fascist period, the Second World War, and the early post-war reconstruction of Italian society and Church life. Born in the Brianza region of Lombardy, he was deeply formed by the Ambrosian theological tradition and by the social Catholicism of the early twentieth century.\n\nHis episcopate at Bergamo is particularly significant in the light of that diocese's later history: Bergamo was the home diocese of Angelo Roncalli (the future Pope John XXIII) and subsequently of Pope John Paul I. Bernareggi's governance of the diocese created the pastoral environment in which a generation of Bergamasque clergy were formed, contributing to the broader renewal that would characterise Italian Catholicism in the post-war period.\n\nBernareggi's management of the diocese during the Fascist period and the war required navigating the complex relationship between the Church and Mussolini's regime — a relationship formally defined by the Lateran Accords of 1929 but constantly tested by the regime's ambitions and the Church's pastoral concerns. His post-war reconstruction work at Bergamo contributed to Italian Catholic Action's rebuilding of civil society in northern Italy.",
    "hs": {"significanceScore": 5, "significanceNarrative": "Bishop of Bergamo during the Fascist era and war who shaped the pastoral environment of a diocese later associated with Popes John XXIII and John Paul I, contributing to Italian Catholic post-war reconstruction.", "significanceCategory": "regional"},
    "causes": ["Italian Church's Lateran Accords relationship with Fascism created complex demands on bishops like Bernareggi", "World War II's devastation of northern Italian society required bishops capable of guiding reconstruction", "Bergamo's strong Catholic social tradition required an episcopal leader committed to social Catholicism"],
    "effects": ["His episcopate shaped the pastoral culture of a diocese that would produce two popes (John XXIII and John Paul I)", "His management of Church-regime relations during Fascism contributed to the Bergamasque Church's integrity", "His post-war reconstruction work helped rebuild northern Italian Catholic civil society through Catholic Action"],
    "rels": [{"target": "diocese-of-bergamo", "verb": "DEFINES", "note": "Served as Bishop of Bergamo 1932–1953"}, {"target": "italian-fascism", "verb": "OCCURS_IN", "note": "Governed his diocese during Mussolini's Fascist period under the Lateran Accords framework"}, {"target": "pope-john-xxiii", "verb": "OCCURS_IN", "note": "His Bergamo episcopate preceded and shaped the environment from which John XXIII emerged"}, {"target": "lateran-accords", "verb": "OCCURS_IN", "note": "His episcopate operated under the Lateran Accords framework defining Church-state relations in Fascist Italy"}]
  }),

  ("adriano-tessarollo", {
    "summary": "Adriano Tessarollo (born 1950) is an Italian Catholic bishop who has served as Bishop of Chioggia in the Veneto region. His episcopate in one of Venice's satellite dioceses situates him within the rich Catholic culture of northeastern Italy — a region marked by deep popular piety, strong Catholic institutional networks, and the influence of the Patriarchate of Venice as one of Italy's most historically significant sees.\n\nThe Veneto region's Catholicism has been notable for its resistance to secularisation compared to other parts of northern Italy, maintaining higher rates of religious practice and strong parish community life. Bishops like Tessarollo serve in an environment where the Church's social role — in education, healthcare, charitable work — remains substantial and where the episcopal office carries genuine public significance.\n\nHis episcopate at Chioggia reflects the Italian Church's commitment to maintaining strong local episcopal leadership in every diocese, however small, as part of the apostolic tradition. His work in the pastoral care of a fishing community and industrial port city demonstrates the range of social contexts within which Italian Catholic bishops exercise their ministry.",
    "hs": {"significanceScore": 3, "significanceNarrative": "Italian bishop of Chioggia in the Veneto whose episcopate reflects the continued strength of Catholic institutional and pastoral life in northeastern Italy.", "significanceCategory": "local"},
    "causes": ["Veneto region's strong Catholic culture required engaged episcopal leadership to maintain pastoral vitality", "Italian Church's extensive social service network in the Veneto required episcopal support and governance", "Post-Vatican II renewal demanded bishops capable of implementing conciliar reforms in local pastoral contexts"],
    "effects": ["Maintained Chioggia's Catholic pastoral and institutional life through his episcopate", "His ministry contributed to the Veneto Church's continuing resilience in the face of broader Italian secularisation trends"],
    "rels": [{"target": "diocese-of-chioggia", "verb": "DEFINES", "note": "Served as Bishop of Chioggia in the Veneto region"}, {"target": "catholic-church-in-italy", "verb": "OCCURS_IN", "note": "Served in the Italian Catholic Church in the Veneto region"}, {"target": "patriarchate-of-venice", "verb": "OCCURS_IN", "note": "His diocese is situated within the broader influence of the Patriarchate of Venice"}]
  }),

  ("adriano-tomasi-travaglia", {
    "summary": "Adriano Tomasi Travaglia is a Roman Catholic bishop serving in the Italian Church, continuing the apostolic succession in one of the Italian diocese network's many historic sees. His ministry as a bishop represents the ongoing pastoral mission of the Italian Catholic Church in the twenty-first century — maintaining the Church's presence and witness across Italy's diverse regional cultures.\n\nThe Italian Church's episcopal landscape is characterised by a large number of dioceses — Italy has more Catholic dioceses per capita than almost any other country — each with its own ancient tradition and local character. Bishops like Tomasi Travaglia serve in this varied landscape, providing pastoral leadership that responds to local needs while remaining in communion with the priorities of the Holy See and the Italian Episcopal Conference.\n\nHis episcopate reflects the Italian Church's continuing effort to maintain its apostolic mission in a society where Catholic identity remains culturally significant but active religious practice continues to decline. The challenge for Italian bishops is to maintain pastoral vitality and institutional relevance while navigating the social changes of a post-Christian generation.",
    "hs": {"significanceScore": 3, "significanceNarrative": "Italian Catholic bishop maintaining apostolic succession and pastoral mission in the Italian Church's extensive diocesan network.", "significanceCategory": "local"},
    "causes": ["Italy's extensive diocesan network requires a large episcopate to maintain apostolic continuity", "Post-Vatican II pastoral renewal demanded bishops capable of local implementation of conciliar reforms", "Italian Church's social service networks require episcopal governance to sustain charitable and educational presence"],
    "effects": ["Maintained his diocese's apostolic continuity and pastoral mission in the Italian Catholic landscape", "His ministry contributes to the Italian Church's local witness and institutional presence"],
    "rels": [{"target": "catholic-church-in-italy", "verb": "DEFINES", "note": "Serves as bishop in the Italian Catholic Church"}, {"target": "italian-episcopal-conference", "verb": "OCCURS_IN", "note": "His ministry is conducted within the framework of the Italian Episcopal Conference (CEI)"}]
  }),

  ("adrianus-sunarko", {
    "summary": "Adrianus Sunarko OFM (born 1968) is an Indonesian Franciscan friar and Roman Catholic bishop who has served as Bishop of Pangkalpinang on the island of Bangka in Indonesia. His appointment reflects the global expansion of the Catholic episcopate in Southeast Asia, where the Church is a minority faith in a predominantly Muslim nation yet maintains significant institutional presence through its educational and healthcare networks.\n\nIndonesia is the world's most populous Muslim-majority nation, and its Catholic community — approximately 3% of the population — exists in a complex plural religious environment. Indonesian Catholicism has strong institutional roots particularly in education and healthcare, and the Church has generally maintained constructive relations with the Indonesian state and Islamic majority under the framework of Pancasila — the national ideology of unity in diversity.\n\nSunarko's Franciscan formation emphasises mission to the poor and the margins, priorities that resonate with the pastoral challenges of a diocese serving the Bangka island mining region where social inequalities and environmental damage from tin mining create significant pastoral demands. His academic background in theology has also contributed to Indonesian Catholic intellectual life. His bishop's role requires maintaining the Church's minority presence with both pastoral creativity and institutional prudence.",
    "hs": {"significanceScore": 4, "significanceNarrative": "Indonesian Franciscan bishop who maintains the Catholic Church's minority presence in the world's most populous Muslim nation, combining theological scholarship with pastoral mission in a mining region diocese.", "significanceCategory": "regional"},
    "causes": ["Indonesian Church's minority status in a Muslim-majority nation requires bishops capable of maintaining constructive interfaith relations", "Franciscan missionary tradition prepared Sunarko for service in an Indonesian mission context with significant social challenges", "Bangka island's tin mining economy created specific social and environmental pastoral demands for his diocese"],
    "effects": ["His episcopate maintains the Catholic Church's institutional and pastoral presence on Bangka island", "His theological scholarship contributes to Indonesian Catholic intellectual life in a pluralist context", "His Franciscan approach emphasises service to the poor in a diocese shaped by extractive industry and social inequality"],
    "rels": [{"target": "diocese-of-pangkalpinang", "verb": "DEFINES", "note": "Served as Bishop of Pangkalpinang on Bangka island, Indonesia"}, {"target": "franciscan-order", "verb": "OCCURS_IN", "note": "Is a Franciscan friar (OFM) whose formation shapes his pastoral and missionary approach"}, {"target": "catholic-church-in-indonesia", "verb": "OCCURS_IN", "note": "Serves the Catholic minority community in predominantly Muslim Indonesia"}, {"target": "indonesia", "verb": "OCCURS_IN", "note": "His bishop's ministry is conducted within the Pancasila framework of Indonesian religious pluralism"}]
  }),

]

if __name__ == "__main__":
    for slug, data in ENTITIES:
        print(f"Enriching: {slug}")
        enrich(slug, data)
    print("\nDone.")
