#!/usr/bin/env python3
"""Batch 73 — Class 312 Dynasties IV (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/312-Class-312"
FILE_PREFIX = "312"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("ghaznavids", {
        "summary": "The Ghaznavid dynasty was a Turkic Muslim dynasty that ruled from Ghazni (in modern Afghanistan) from 977 to 1186 CE, renowned for creating one of the Islamic world's most culturally brilliant courts and for the military campaigns of Sultan Mahmud of Ghazni (r. 998-1030 CE) that brought Islam to the Indian subcontinent through 17 devastating raids on northern India. The Ghaznavids created a Persian-language court culture that patronized poets including Firdausi (author of the Shahnameh) and al-Biruni, who accompanied Mahmud to India and wrote the first systematic account of Indian geography and religion.\n\nMahmud of Ghazni's 17 raids into India (1001-1027 CE) were primarily motivated by treasure, not permanent conquest: he looted Hindu temples including Somnath (1025), destroying what Muslims considered idols and Muslims as the iconoclasm of victorious faith, taking enormous wealth back to beautify Ghazni. These raids established patterns of Islamic-Hindu conflict that persist in historical memory to this day.\n\nAl-Biruni's accompanying Mahmud to India produced Kitab al-Hind (Book of India, 1030), the most comprehensive account of Indian science, mathematics, philosophy, and religion written in the medieval Islamic world. The Ghaznavid dynasty was eventually displaced by the Ghurids; their cultural legacy persisted through the Persianate court culture that shaped all subsequent Islamic dynasties in South Asia.",
        "causes": ["Alp-Tigin's establishment of Ghaznavid state in Khorasan from Samanid disintegration", "Mahmud's military genius and religious zeal justifying Indian raids as jihad", "Ghazni's position between Central Asia and India enabling profitable raiding strategy", "Persian court culture's establishment as alternative to Arab-centric Islamic tradition"],
        "effects": ["17 Indian raids established earliest pattern of Islamic-Hindu military conflict", "Somnath temple destruction remains politically charged historical memory in contemporary India", "Al-Biruni's Kitab al-Hind provided systematic Islamic account of Indian civilization", "Persianate court model established template for subsequent South Asian Islamic courts"],
        "relationships": [{"entity": "Mahmud of Ghazni", "relationship": "LED_BY", "note": "Sultan Mahmud's 17 Indian raids (1001-1027) defined Ghaznavid legacy"}, {"entity": "Al-Biruni", "relationship": "PATRONIZED", "note": "Scholar accompanying Mahmud to India produced Kitab al-Hind, systematic account of Indian civilization"}, {"entity": "Firdausi", "relationship": "PATRONIZED", "note": "Persian poet patronized at Ghaznavid court; wrote Shahnameh — Persian national epic"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Ghaznavids' 17 Indian raids established the earliest pattern of Islamic-Hindu military conflict still contested in South Asian historical memory, while their Persian court culture shaped Islamic civilization from Central Asia to India for centuries.", "significanceCategory": "world-changing"},
    }),
    ("khalji-dynasty", {
        "summary": "The Khalji dynasty (1290-1320 CE) was the second dynasty of the Delhi Sultanate, ruling India for 30 years under three sultans. Despite its brief duration, the Khalji period was historically pivotal: Alauddin Khalji (r. 1296-1316 CE) created India's first centralized Muslim state, defeated five Mongol invasions that threatened to destroy Islamic India, introduced revolutionary price control edicts that stabilized Delhi's economy, and conquered much of peninsular India through his general Malik Kafur's campaigns.\n\nJalal-ud-din Khalji founded the dynasty in 1290 after the assassination of the last Mamluk sultan. His nephew Alauddin Khalji murdered him in 1296 and seized the throne — beginning a reign of ruthless efficiency. Alauddin's price controls (fixing the prices of grain, cloth, cattle, and slaves across Delhi) were implemented through a comprehensive market surveillance system using spies and inspectors, and were effective in keeping food cheap for Delhi's population — a medieval experiment in economic planning unprecedented in scale.\n\nAlauddin Khalji's repulsion of the Mongol invasions (1299, 1303, 1305, 1306, 1308) is considered one of the great military feats of medieval history: the Mongols had conquered from China to Poland, yet Alauddin's reforms of his army (paid in cash, not land grants) created a force that repeatedly defeated them. Alauddin's death in 1316 led to the dynasty's rapid collapse under his eunuch general Malik Kafur's manipulation, ending in the Tughluq dynasty's rise in 1320.",
        "causes": ["Jalal-ud-din Khalji's 1290 coup ending Mamluk dynasty and establishing Khalji rule", "Mongol threat requiring exceptional military and administrative response", "Alauddin's ambition to conquer all of India requiring revenue reforms", "Delhi's military expansion requiring economic reforms to support large paid army"],
        "effects": ["Five successful Mongol repulsions saved Islamic India from Mongol conquest", "Market price control system created medieval India's most ambitious economic regulation", "Deccan conquests by Malik Kafur extended Islamic rule into peninsular India", "Administrative reforms including cash-paid army influenced subsequent Delhi Sultanate dynasties"],
        "relationships": [{"entity": "Alauddin Khalji", "relationship": "RULED_BY", "note": "Alauddin's reign 1296-1316 defined Khalji dynasty through Mongol defeats and price controls"}, {"entity": "Mongol Empire", "relationship": "DEFEATED", "note": "Alauddin defeated five Mongol invasion attempts protecting Islamic India"}, {"entity": "Delhi Sultanate", "relationship": "PART_OF", "note": "Second dynasty of Delhi Sultanate, ruling 1290-1320 CE"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Alauddin Khalji's repulsion of five Mongol invasions saved Islamic India from the destruction wrought on Persia, Iraq, and Central Asia, while his market price controls represent medieval history's most ambitious experiment in state economic management.", "significanceCategory": "world-changing"},
    }),
    ("keita-dynasty", {
        "summary": "The Keita dynasty was the ruling dynasty of the Mali Empire (c. 1230-1600 CE), one of medieval Africa's greatest empires, which at its height controlled the gold and salt trade across the western Sahara, encompassing modern Mali, Senegal, Gambia, Guinea-Bissau, Guinea, and parts of Mauritania and Niger. The dynasty's most famous ruler, Mansa Musa I (r. 1312-1337 CE), made a 1324-1325 pilgrimage to Mecca that is legendary for the gold he distributed, causing currency devaluation across North Africa and the Middle East.\n\nThe dynasty traces its origins to Sundiata Keita, who defeated the Sosso king Sumanguru Kante at the Battle of Kirina (c. 1235 CE), founding the Mali Empire. Sundiata's story is preserved in the Sundiata Epic, an oral tradition still performed by West African griots. The Keita dynasty presided over the construction of Timbuktu as an Islamic scholarly center — Sankore mosque-university became one of the medieval world's great centers of learning with 25,000 students.\n\nMansa Musa I's 1324 Hajj pilgrimage through Cairo — with a retinue of 60,000 and 80 camels laden with gold — is sometimes cited as the act of the wealthiest individual in history, who spent so much gold in Cairo that it devalued for the next 12 years. His return journey included the capture of Timbuktu and Gao, consolidating Mali's control of trans-Saharan trade.",
        "causes": ["Sundiata Keita's victory at Battle of Kirina c. 1235 establishing Mali Empire", "Mali's control of trans-Saharan gold and salt trade routes creating imperial wealth", "Mansa Musa's Islamic faith and wealth enabling legendary Mecca pilgrimage", "Timbuktu's development as Saharan trade hub requiring Islamic scholarly infrastructure"],
        "effects": ["Mansa Musa's 1324 Cairo gold distribution devalued Egyptian and Mediterranean currencies for 12 years", "Sankore mosque-university educated 25,000 students making Timbuktu Africa's intellectual capital", "Sundiata Epic preserved in griot oral tradition for 800 years", "Mali Empire's trans-Saharan trade brought Islam across West Africa"],
        "relationships": [{"entity": "Mansa Musa I", "relationship": "RULED_BY", "note": "Mansa Musa's 1312-1337 reign included legendary Mecca pilgrimage and Timbuktu development"}, {"entity": "Sundiata Keita", "relationship": "FOUNDED_BY", "note": "Sundiata's c. 1235 victory at Kirina founded Mali Empire and Keita dynasty"}, {"entity": "Timbuktu", "relationship": "DEVELOPED", "note": "Keita dynasty developed Timbuktu as Islamic scholarly center with 25,000 students"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Keita dynasty's Mali Empire was medieval West Africa's greatest state, and Mansa Musa's legendary gold pilgrimage to Mecca — which devalued currencies across North Africa — remains history's most famous demonstration of African imperial wealth.", "significanceCategory": "world-changing"},
    }),
    ("macedonian-dynasty", {
        "summary": "The Macedonian dynasty (867-1056 CE) was the ruling house of the Byzantine Empire during its greatest medieval flourishing, named for its founder Basil I's origins in Macedonia. The Macedonian period produced Byzantine civilization's highest achievements: the reconquest of Crete, Cyprus, and parts of Syria; the Christianization of Bulgaria, Serbia, and Kievan Rus; the creation of the Cyrillic alphabet by Cyril and Methodius (technically under their predecessors but supported by this dynasty); and a cultural renaissance that produced the finest Byzantine mosaics and manuscripts.\n\nBasil I (r. 867-886 CE) founded the dynasty after murdering his way to power — first assassinating Emperor Michael III with whom he had an unusual intimate relationship, then ruling as one of Byzantium's most capable emperors. His successors Leo VI (the Wise), Constantine VII Porphyrogennetos (the Purple-Born), and Basil II (the Bulgar-Slayer) represent Byzantine civilization's literary, diplomatic, and military peaks respectively.\n\nBasil II (r. 976-1025 CE), the dynasty's greatest military ruler, ended the Bulgarian First Empire by blinding 15,000 Bulgarian prisoners (leaving 1 eye per 100 to guide them home) — earning the name 'Bulgar-Slayer.' Yet Basil II's 49-year reign was also one of Byzantium's most stable, extending Byzantine territory to the Danube, expanding into Syria and Armenia, and converting Vladimir of Kiev to Christianity, spreading Orthodox Christianity to Russia.",
        "causes": ["Basil I's 867 murder of Michael III and seizure of Byzantine throne founding dynasty", "Byzantine Empire's administrative and military recovery from Arab and Bulgarian pressures", "Eastern Mediterranean reconquest providing resources for cultural renaissance", "Missionary activities to Slavs extending Byzantine civilization northward"],
        "effects": ["Christianization of Bulgaria, Serbia, and Kievan Rus created Eastern Orthodox civilization", "Cyrillic alphabet's development created written language for Slavic peoples", "Basil II's blinding of 15,000 Bulgarians ended First Bulgarian Empire", "Byzantine cultural renaissance produced finest mosaics, manuscripts, and ivory carvings"],
        "relationships": [{"entity": "Basil I", "relationship": "FOUNDED_BY", "note": "Macedonian-born Basil I founded dynasty after murdering Michael III in 867"}, {"entity": "Basil II", "relationship": "GREATEST_RULER", "note": "Basil the Bulgar-Slayer's 49-year reign extended Byzantine power to its medieval peak"}, {"entity": "Vladimir of Kiev", "relationship": "CONVERTED", "note": "Basil II's arrangement with Vladimir created Orthodox Christian Kievan Rus"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Macedonian dynasty's Christianization of the Slavs and the Cyrillic alphabet's creation represent Byzantium's most consequential cultural legacy — establishing the Orthodox Christian civilization that shaped Russia, Bulgaria, Serbia, and Eastern Europe.", "significanceCategory": "world-changing"},
    }),
    ("kushan-empire-india", {
        "summary": "The Kushan Empire (c. 30-375 CE) was a major Central Asian empire that at its height controlled territory spanning modern Afghanistan, Pakistan, northern India, and parts of China's Xinjiang, creating a crossroads civilization that was the pivot point for the exchange of Buddhism, art, trade, and ideas between Rome, Persia, India, and China. The Kushans created the first iconographic representations of the Buddha in human form — previously Buddha was represented only by symbols — establishing the Gandharan art style that became the foundation of Buddhist visual culture worldwide.\n\nThe Kushans were originally a Yuezhi people displaced from Central Asia by the Xiongnu, who migrated through Bactria to create a prosperous trading empire along the Silk Road. Kanishka the Great (r. c. 127-163 CE), the dynasty's greatest ruler, convened the Fourth Buddhist Council, sponsored the translation of Buddhist texts into Sanskrit, patronized the arts that created Gandharan Buddhist sculpture, and was personally connected to the spread of Mahayana Buddhism.\n\nKushan territory along the Silk Road meant it was simultaneously exposed to Roman, Persian, Indian, and Chinese influences: Kushan coins showed Greek gods, Indian deities, Zoroastrian figures, and Buddha — sometimes on the same coin series. The empire declined from the 3rd century CE under Sasanian Persian pressure, fragmenting into local kingdoms, but the Gandharan art tradition it created spread Buddhist iconography across Central and East Asia.",
        "causes": ["Yuezhi displacement from Central Asia by Xiongnu leading to Bactrian migration and empire formation", "Silk Road position providing wealth from taxing trade between Rome, Persia, India, China", "Kanishka's Buddhist patronage catalyzing creation of Gandharan art tradition", "Mahayana Buddhism's development requiring iconographic representation of Buddha"],
        "effects": ["First human-form images of Buddha created at Gandhara became foundation of all Buddhist art", "Fourth Buddhist Council under Kanishka catalyzed Mahayana Buddhism's development", "Silk Road crossroads position created unique multicultural coinage mixing Greek, Iranian, Indian, Buddhist iconography", "Gandharan art tradition spread Buddhist visual culture across Central and East Asia"],
        "relationships": [{"entity": "Kanishka the Great", "relationship": "GREATEST_RULER", "note": "Kanishka convened Fourth Buddhist Council and patronized Gandharan Buddhist art"}, {"entity": "Silk Road", "relationship": "CONTROLLED", "note": "Kushan territory along Silk Road pivotal for trade and cultural exchange between East and West"}, {"entity": "Gandharan Art", "relationship": "CREATED", "note": "Kushan patronage created first human-form Buddha images that became foundation of Buddhist art"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Kushan Empire created the first images of the Buddha in human form — establishing the visual vocabulary of Buddhist art used across Asia for 2,000 years — making it the most consequential empire in the history of Buddhist civilization.", "significanceCategory": "world-changing"},
    }),
    ("abbadid-dynasty", {
        "summary": "The Abbadid dynasty (c. 1023-1091 CE) was a Muslim Arab dynasty that ruled Seville (Ishbiliyya) as an independent taifa kingdom during al-Andalus's fragmentation period following the collapse of the Umayyad Caliphate of Córdoba. Despite ruling for less than 70 years, the Abbadids created one of the most brilliant cultural courts of the taifa period, with the last Abbadid ruler al-Mu'tamid ibn Abbad (r. 1069-1091) being the most celebrated Arabic poet-king of medieval Iberia.\n\nThe taifa period (1031-1085 CE) followed the Umayyad Caliphate's collapse, fragmenting al-Andalus into small competing kingdoms. The Abbadids rose under Abu al-Qasim Muhammad, a Seville judge who exploited the chaos to establish independence. Under his son al-Mu'tadid (r. 1042-1069) and grandson al-Mu'tamid, Seville expanded to control most of southern Iberia.\n\nAl-Mu'tamid ibn Abbad is remembered as one of the greatest Arabic poets and a tragic figure: a cultivated ruler who wrote exquisite poetry about love, wine, and nature while presiding over political collapse. When Alfonso VI of Castile captured Toledo in 1085 threatening all of Iberia, al-Mu'tamid invited the Almoravids from North Africa, who expelled Alfonso but then took al-Mu'tamid prisoner in 1091, ending the Abbadid dynasty. Al-Mu'tamid died in exile in Morocco in 1095, writing his most moving poems in captivity.",
        "causes": ["Umayyad Caliphate's collapse in 1031 fragmenting al-Andalus into taifa kingdoms", "Abu al-Qasim's exploitation of political vacuum to establish Seville independence", "Taifa competition requiring military and cultural patronage to maintain prestige", "Alfonso VI's Toledo conquest 1085 forcing al-Mu'tamid to invite Almoravids"],
        "effects": ["Al-Mu'tamid's poetry created one of Arabic literature's most celebrated bodies of work", "Almoravid invitation ended taifa independence replacing Arab dynasties with Berber rule", "Seville under Abbadids became cultural capital rivaling Córdoba in literary achievement", "Al-Mu'tamid's tragic exile and captivity poetry made him symbol of Andalusian civilization's twilight"],
        "relationships": [{"entity": "Al-Mu'tamid ibn Abbad", "relationship": "RULED_BY", "note": "Last Abbadid ruler and celebrated Arabic poet-king; died in Moroccan exile in 1095"}, {"entity": "Almoravid Dynasty", "relationship": "ENDED_BY", "note": "Almoravids invited by al-Mu'tamid imprisoned him in 1091 ending the Abbadid dynasty"}, {"entity": "Alfonso VI of Castile", "relationship": "PRESSURED_BY", "note": "Alfonso's 1085 Toledo capture forced al-Mu'tamid to invite Almoravids who ended his rule"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Abbadid dynasty's cultural brilliance and its tragic end — al-Mu'tamid dying in exile writing poetry — embody the Andalusian taifa era's paradox of cultural splendor amid political collapse, making it the most poignant chapter in al-Andalus's history.", "significanceCategory": "regional"},
    }),
    ("abydos-dynasty", {
        "summary": "The Abydos Dynasty (c. 1650-1600 BCE) was a brief dynasty of ancient Egyptian rulers who controlled the city of Abydos and surrounding regions during the Second Intermediate Period, when Egypt was divided among the Hyksos (ruling the Delta from Avaris), the Theban 17th Dynasty (ruling Upper Egypt), and the Nubian Kushite kingdom. The Abydos Dynasty represents one of ancient Egypt's most obscure ruling groups, known primarily from recent archaeological discovery.\n\nThe Second Intermediate Period (c. 1650-1550 BCE) was Egypt's most fragmented historical moment before the New Kingdom's reunification under Ahmose I. The Hyksos, who introduced horse-drawn chariots and composite bows to Egypt, ruled the Delta; Theban kings of the 17th Dynasty ruled Upper Egypt; and the Abydos rulers — whose names appear on limited archaeological evidence — controlled a small territory in Middle Egypt including Abydos, sacred burial site of Osiris and Egypt's earliest pharaohs.\n\nThe Abydos Dynasty's importance lies partly in the recent excavation of its rulers' tombs (2013-2014 discovery by Josef Wegner at the University of Pennsylvania), which revealed previously unknown pharaohs. The discovery of the pharaoh Senebkay's remains (c. 1650 BCE), showing he died from wounds in battle, provided direct physical evidence of warfare during this fragmented period. The dynasty connects the sacred Abydos landscape — Egypt's most ancient burial ground — with this poorly documented era.",
        "causes": ["Second Intermediate Period fragmentation providing political opportunity for local rulers", "Hyksos invasion of Delta disrupting unified Egyptian state", "Abydos's sacred significance requiring a local protector-dynasty to maintain shrine administration", "Competition between Hyksos, Thebans, and local rulers creating space for minor dynasties"],
        "effects": ["Archaeological discovery of Abydos Dynasty tombs 2013-2014 revised understanding of Second Intermediate Period", "Senebkay's battle-wound remains provided direct evidence of inter-dynastic warfare", "Sacred Abydos shrine administration maintained through period of Egyptian fragmentation", "Dynasty bridges Hyksos period and eventual Theban reunification under New Kingdom"],
        "relationships": [{"entity": "Senebkay", "relationship": "RULED_BY", "note": "Pharaoh whose 2013-discovered remains showed he died from battle wounds c. 1650 BCE"}, {"entity": "Hyksos", "relationship": "CONTEMPORANEOUS_WITH", "note": "Abydos Dynasty existed simultaneously with Hyksos Delta rule and Theban Upper Egyptian rulers"}, {"entity": "Abydos", "relationship": "BASED_AT", "note": "Dynasty centered on Egypt's most sacred burial site and Osiris shrine"}],
        "historicalSignificance": {"significanceScore": 4, "significanceNarrative": "The Abydos Dynasty, only recently discovered through 2013-2014 excavations, represents the most obscure chapter in ancient Egyptian royal history and the fragmented Second Intermediate Period when Egypt was ruled simultaneously by three competing dynasties.", "significanceCategory": "regional"},
    }),
    ("aeacidae", {
        "summary": "The Aeacidae were the royal dynasty of Epirus (northwestern Greece/Albania), claiming divine descent from Aeacus (grandson of Zeus and grandfather of Achilles), making them one of antiquity's most prestigious royal lineages. The dynasty produced two historically significant figures: Pyrrhus of Epirus (r. 306-272 BCE), one of antiquity's greatest commanders, whose campaigns against Rome introduced the term 'Pyrrhic victory'; and Alexander I of Epirus (r. 342-331 BCE), who campaigned in Italy before Alexander the Great's Eastern campaigns.\n\nPyrrhus of Epirus was considered by contemporaries — including Hannibal — to be the greatest general of antiquity after Alexander the Great. Pyrrhus's campaigns in Macedon, Thessaly, and his Italian campaigns (280-275 BCE) fighting against Rome and the Samnites demonstrated tactical brilliance. His victories at Heraclea (280 BCE) and Asculum (279 BCE) inflicted heavy Roman losses but at such high cost to his own army that 'another such victory and we are undone' entered language as the Pyrrhic victory concept.\n\nAlexander I of Epirus, Pyrrhus's predecessor and uncle, crossed to Italy in 334 BCE — two years before Alexander the Great crossed into Asia — at the invitation of Tarentum (Taranto) fighting against the Lucanians and Samnites. He was killed in 331 BCE in Italy. The Aeacid dynasty's claim of Achilles' lineage made Epirus a culturally significant kingdom disproportionate to its small territory, connecting Greek heroic tradition to political legitimacy.",
        "causes": ["Divine descent claim from Aeacus and Achilles providing dynastic legitimacy", "Epirus's strategic position between Macedonia and Illyria requiring military competence", "Pyrrhus's military genius making small Epirus a major power in Hellenistic world", "Italian city-states inviting Pyrrhus and Alexander to oppose Rome and Italic peoples"],
        "effects": ["Pyrrhic victory concept entered permanent usage across languages from Pyrrhus's Italian campaigns", "Hannibal naming Pyrrhus greatest general after Alexander influenced Carthaginian tactical thinking", "Alexander I of Epirus's Italian campaign pre-figured Alexander the Great's Asian campaigns", "Aeacid divine lineage claims demonstrated Greek royal genealogical tradition connecting to Homeric heroes"],
        "relationships": [{"entity": "Pyrrhus of Epirus", "relationship": "PRODUCED", "note": "Aeacid dynasty's most famous ruler; his Italian campaigns coined 'Pyrrhic victory'"}, {"entity": "Alexander the Great", "relationship": "RELATED_TO", "note": "Alexander's mother Olympias was Aeacid; connecting Macedonian and Epirote royal houses"}, {"entity": "Achilles", "relationship": "CLAIMS_DESCENT_FROM", "note": "Aeacid dynasty claimed divine descent from Aeacus, grandfather of Achilles"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Aeacidae dynasty's Pyrrhus of Epirus gave the world the concept of the 'Pyrrhic victory' — a military success so costly as to be defeat — making it the royal family whose military legacy permanently entered global vocabulary.", "significanceCategory": "regional"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 73 — Class 312 Dynasties IV")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
