#!/usr/bin/env python3
"""Batch 106 — Class 363 Theaters V: World Opera Houses (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/363-Class-363"
FILE_PREFIX = "363"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("abay-opera-house", {
        "summary": "The Abay Opera House (officially the Abai Kazakh State Academic Opera and Ballet Theatre) in Almaty, Kazakhstan, named for the revered 19th-century Kazakh poet and composer Abai Qunanbaiuly, was founded in 1933 during the Soviet era and stands as the oldest and most prestigious performing arts venue in Central Asia. The building — designed in neo-classical style with Kazakh ornamental elements by A.V. Shchusev (architect of Lenin's Mausoleum) and opened in 1941 — was part of the Soviet nationalities policy that established opera and ballet institutions in each republic to develop 'national' high culture while maintaining ideological uniformity.\n\nThe Abay Opera House was the primary venue where Kazakh folk melodies were elevated to operatic form: Soviet composers collaborated with Kazakh musicians to create a distinctly Kazakh operatic repertoire, including Akhmet Zhubanov's Abai opera (1944) — based on the life of the poet for whom the theater is named. This Soviet-Kazakh cultural synthesis created an authentic performance tradition that outlasted Soviet ideology.\n\nSince Kazakhstan's 1991 independence, the Abay Opera House has served as a flagship of Kazakh cultural identity, hosting the country's leading opera and ballet companies while also presenting international productions. Its location in Almaty (formerly Alma-Ata, Kazakhstan's largest city and former capital until 1997) makes it the cultural heart of Central Asia's most prosperous country. The theater has been renovated multiple times and continues to commission new Kazakh opera and ballet works.",
        "causes": ["1933 Soviet founding to develop 'national form, socialist content' Kazakh performing arts", "Named for Abai Qunanbaiuly as the defining poet-composer of Kazakh cultural identity", "1941 neo-classical building by Shchusev (Lenin's Mausoleum architect) as Soviet prestige project", "1991 Kazakhstan independence elevating it to flagship of national cultural identity"],
        "effects": ["Oldest and most prestigious performing arts venue in Central Asia", "Kazakh operatic repertoire developed through Soviet-era collaborations persisting to present", "Almaty's position as Central Asia's cultural capital anchored by the Abay Opera House", "Post-Soviet Kazakh cultural identity using the theater as national cultural expression"],
        "relationships": [{"entity": "Abai Qunanbaiuly", "relationship": "NAMED_FOR", "note": "Theater named for the revered 19th-century Kazakh poet; his life inspired the house's signature opera"}, {"entity": "Soviet Cultural Policy", "relationship": "FOUNDED_UNDER", "note": "1933 Soviet nationalities policy created opera houses in each republic to develop 'national' culture"}, {"entity": "Kazakhstan", "relationship": "FLAGSHIP_CULTURAL_INSTITUTION_OF", "note": "Since 1991 independence, Abay Opera House is Kazakhstan's leading cultural institution"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Abay Opera House — Central Asia's oldest and most prestigious performing arts venue, the birthplace of Kazakh operatic repertoire, and the flagship of Kazakhstan's cultural identity since independence — represents the most successful example of Soviet national culture policy creating genuinely lasting indigenous artistic traditions.", "significanceCategory": "regional"},
    }),
    ("alexandria-opera-house", {
        "summary": "The Alexandria Opera House (Bibliotheca Alexandrina Cultural Center), Egypt's second-largest opera house built adjacent to the reconstructed Bibliotheca Alexandrina on the Mediterranean seafront of Alexandria, opened in 2003 and represents Egypt's effort to restore Alexandria's ancient reputation as the intellectual and cultural capital of the Mediterranean world. The modern opera house — with a 1,600-seat main hall designed for European-standard opera and ballet — is managed jointly with the Bibliotheca Alexandrina and hosts international performers alongside the Alexandria Opera's own productions.\n\nHistorically, Alexandria had a rich operatic tradition: the old Zizinia Theater (opened 1862) and the Royal Opera House (opened 1918, demolished 1981) made Alexandria Egypt's operatic capital before Cairo's Cairo Opera House (opened 1988) claimed that role. The most famous operatic connection: Giuseppe Verdi's Aida — whose story is set in ancient Egypt — was commissioned for the original Cairo Opera House's 1871 opening (not Alexandria, though it was the first African city to perform it).\n\nThe Alexandria Opera House's significance lies in its dual role as a cultural institution and a political statement: Mubarak's government invested heavily in cultural infrastructure to project Egyptian soft power in the Arab world and signal Egypt's alignment with European cultural values. The Alexandria Opera House's opening coincided with the Bibliotheca Alexandrina's 2002 opening — both projects funded partly by UNESCO — and together they represent the most ambitious cultural reconstruction of an ancient city in modern history.",
        "causes": ["Egypt's desire to restore Alexandria's Mediterranean cultural prestige through cultural infrastructure", "Bibliotheca Alexandrina reconstruction (2002) providing context for adjacent opera house", "Egyptian government cultural soft power investment in Arab world and European cultural alignment", "Alexandria's historical operatic tradition (Zizinia Theater, 1862) providing institutional foundation"],
        "effects": ["Alexandria's modern Mediterranean cultural identity anchored by opera house and library", "International performers access to Alexandria as touring venue alongside Cairo Opera House", "Egypt's cultural soft power projection in Arab world reinforced", "Dual institutions (Bibliotheca + Opera) as most ambitious ancient city cultural reconstruction project"],
        "relationships": [{"entity": "Bibliotheca Alexandrina", "relationship": "ADJACENT_TO_AND_CO_MANAGED_WITH", "note": "Opera house is managed with the Bibliotheca Alexandrina as part of Alexandria's cultural renaissance"}, {"entity": "Cairo Opera House", "relationship": "EGYPT_SECOND_OPERA_HOUSE_AFTER", "note": "Alexandria Opera House is Egypt's second major opera house after Cairo Opera (1988)"}, {"entity": "UNESCO", "relationship": "PARTIALLY_FUNDED_BY", "note": "Both Bibliotheca Alexandrina and Alexandria cultural infrastructure received UNESCO funding support"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Alexandria Opera House — part of the most ambitious reconstruction of an ancient cultural capital (alongside the Bibliotheca Alexandrina) and Egypt's Mediterranean cultural soft power instrument — represents the 21st century's largest investment in reviving ancient Alexandria's global cultural role.", "significanceCategory": "regional"},
    }),
    ("astana-opera", {
        "summary": "The Astana Opera, opened in June 2013 in Kazakhstan's purpose-built capital Astana (now renamed Nur-Sultan and back to Astana in 2022), is the newest major opera house in Central Asia and a centerpiece of President Nursultan Nazarbayev's program to transform the newly designated capital into a showcase of Kazakhstani architectural ambition and cultural aspiration. The 1,200-seat neo-baroque building was designed by Italian architect Manfredi Nicoletti and built in just two years — remarkable speed for a major cultural institution.\n\nThe Astana Opera's opening represented Kazakhstan's desire to present a dual cultural identity: the theater's repertoire balances Western operatic canon (Verdi, Puccini, Tchaikovsky) with Kazakh national works, and its artistic director model follows European professional management while celebrating Kazakh identity. The opening gala featured internationally renowned Kazakh mezzo-soprano Bibigul Tulegenova.\n\nThe Astana Opera exemplifies the Central Asian 'petrodollar cultural institution' pattern — oil wealth funding rapid cultural institution creation that bypasses the slow organic development typical of European opera houses. Unlike the Abay Opera House (which evolved over decades), Astana Opera arrived fully formed as a prestige project. The theater sits within Astana's hypermodern right-bank district alongside Norman Foster's Khan Shatyr (world's largest tent structure) and other architectural spectacles, making it part of one of the 21st century's most concentrated architectural experiments.",
        "causes": ["Nazarbayev's program to establish Astana as a showcase capital with world-class cultural institutions", "Kazakhstan's oil wealth enabling rapid construction of major cultural infrastructure", "Italian architect Manfredi Nicoletti's neo-baroque design built in just two years", "Desire to complement Abay Opera House in Almaty with a capital-city cultural flagship"],
        "effects": ["Astana's emergence as Central Asia's second major opera center alongside Almaty", "Fastest construction of a major European-standard opera house in modern history (2 years)", "Kazakh-Western operatic repertoire balance modeling regional cultural integration", "Part of Astana's hypermodern architectural district as Central Asia's most concentrated design experiment"],
        "relationships": [{"entity": "Nursultan Nazarbayev", "relationship": "FUNDED_AND_DIRECTED_BY_VISION_OF", "note": "Nazarbayev's capital-building program funded the Astana Opera as cultural prestige project"}, {"entity": "Abay Opera House", "relationship": "SISTER_INSTITUTION_IN_KAZAKHSTAN", "note": "Astana Opera (2013) complements the Abay Opera House (1941) as Kazakhstan's two flagship opera venues"}, {"entity": "Manfredi Nicoletti", "relationship": "DESIGNED_BY", "note": "Italian architect Nicoletti designed the neo-baroque building constructed in 2 years"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "The Astana Opera — the world's fastest-built major opera house, a centerpiece of Kazakhstan's petrodollar cultural institution-building, and part of Astana's unprecedented architectural experiment — represents the 21st century's new model for rapid cultural infrastructure creation in resource-wealthy states.", "significanceCategory": "regional"},
    }),
    ("azerbaijan-state-academic-opera-and-ballet-theater", {
        "summary": "The Azerbaijan State Academic Opera and Ballet Theatre in Baku, founded in 1920 and operating in a neo-baroque building designed by Polish architect Józef Plśnik (completed 1911), is the oldest opera house in the South Caucasus and the birthplace of Azerbaijani national opera — a unique synthesis of European operatic form with Azerbaijani mugham (modal music tradition) that created one of the world's most distinctive national opera traditions. The theater's most famous work, Uzeyir Hajibeyov's Leyli and Majnun (1908) — the first opera by a Muslim composer, often called the first Eastern opera — premiered here and launched Azerbaijani operatic culture.\n\nUzeyir Hajibeyov (1885-1948) — Azerbaijan's defining composer — created the 'mugham opera' genre that synthesized European four-part harmony with Azerbaijani pentatonic mugham modes: his works Koroğlu (1937, considered the greatest Azerbaijani opera) and Leyli and Majnun drew on pre-Islamic epic poetry while using Western orchestration. This synthesis created a unique idiom that influenced composers across the Muslim world who sought to create 'national' operas.\n\nThe theater survived Soviet nationalization (1920), continued performing under Soviet cultural policy (which promoted Azerbaijani 'national form, socialist content'), and has thrived since Azerbaijan's 1991 independence. Today it performs to audiences drawn from Baku's oil-wealth cultural scene alongside traditional Azerbaijani music lovers. Mugham — Azerbaijan's classical music tradition — was inscribed on UNESCO's Intangible Cultural Heritage list in 2008, and the opera house remains its most prestigious performance venue.",
        "causes": ["1908 premiere of Leyli and Majnun (first Muslim-composer opera) founding Azerbaijani opera tradition", "Uzeyir Hajibeyov's synthesis of European harmony and Azerbaijani mugham creating unique genre", "Soviet nationalization (1920) and 'national form, socialist content' policy developing the institution", "Azerbaijan's oil wealth since 1991 independence funding the theater's continued prestige"],
        "effects": ["First opera by a Muslim composer (Leyli and Majnun, 1908) creating a model for Eastern opera", "Mugham opera genre unique to Azerbaijan influencing national opera development across Muslim world", "UNESCO Intangible Cultural Heritage recognition of mugham (2008) elevating the tradition globally", "South Caucasus's oldest opera house as Baku's cultural crown jewel"],
        "relationships": [{"entity": "Uzeyir Hajibeyov", "relationship": "NATIONAL_OPERA_TRADITION_FOUNDED_BY", "note": "Hajibeyov's Leyli and Majnun (1908) and Koroğlu (1937) created the Azerbaijani mugham opera tradition"}, {"entity": "Mugham", "relationship": "PERFORMS_AND_PRESERVES", "note": "The theater is the most prestigious venue for mugham — UNESCO-listed Azerbaijani classical music"}, {"entity": "UNESCO Intangible Cultural Heritage", "relationship": "TRADITION_RECOGNIZED_BY", "note": "Mugham inscribed on UNESCO list in 2008; the theater is its primary institutional home"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Azerbaijan State Opera — home to the world's first Muslim-composer opera (1908), birthplace of the unique mugham opera genre, and oldest opera house in the South Caucasus — created a national operatic tradition that influenced how Muslim-majority cultures adapted Western musical forms to indigenous traditions.", "significanceCategory": "continental"},
    }),
    ("chichester-festival-theatre", {
        "summary": "The Chichester Festival Theatre, opened in 1962 in the small English cathedral city of Chichester, is one of the most architecturally and theatrically influential theaters of the 20th century — its distinctive hexagonal thrust stage design (placing the audience on three sides of the acting area, inspired by Tyrone Guthrie's Stratford Festival Theatre in Ontario) influenced the design of theater stages worldwide and is directly responsible for the National Theatre of Great Britain's Olivier Theatre stage design.\n\nThe theater's founding was driven by theatre director Leslie Evershed-Martin's vision of bringing professional classical theater to southern England; its first artistic director was Laurence Olivier, who used it as a laboratory for what would become the National Theatre (NT). The first season (1962) featured productions with Olivier, Michael Redgrave, Joan Plowright, and Sybil Thorndike that were subsequently transferred to the NT's founding season. Chichester thus effectively served as the National Theatre's 'pilot season,' directly shaping British theater for the next 60 years.\n\nThe Chichester Festival Theatre has maintained its reputation for ambitious new work and classical productions under directors including Peter Hall, Patrick Garland, Jonathan Church, and Daniel Evans. It regularly transfers productions to the West End — a distinctive model for a regional theater. Its 2010s renovation expanded capacity and added education facilities. The theater's influence extends far beyond its modest size: its thrust stage design has been adopted by theaters on every continent, and the companies and productions it developed have defined 60 years of British theatrical tradition.",
        "causes": ["Leslie Evershed-Martin's 1962 vision to bring professional theater to southern England", "Hexagonal thrust stage design inspired by Guthrie's Stratford Ontario stage — revolutionary for British theater", "Laurence Olivier's founding artistic directorship using it as NT laboratory", "First season (1962) with Olivier, Redgrave, Plowright serving as National Theatre pilot season"],
        "effects": ["National Theatre's Olivier Theatre thrust stage design directly influenced by Chichester's", "National Theatre's founding repertoire developed from Chichester's first two seasons", "Thrust stage theater design model spread to theaters on every continent", "Regional theater model of West End transfer adopted as standard for British regional theater"],
        "relationships": [{"entity": "Laurence Olivier", "relationship": "FOUNDING_ARTISTIC_DIRECTOR", "note": "Olivier's first two seasons at Chichester (1962-63) directly led to the National Theatre"}, {"entity": "National Theatre", "relationship": "DESIGN_AND_REPERTOIRE_INFLUENCED", "note": "NT's Olivier Theatre thrust stage and founding repertoire came from Chichester"}, {"entity": "Tyrone Guthrie", "relationship": "STAGE_DESIGN_INSPIRED_BY", "note": "Guthrie's Stratford Ontario thrust stage (1953) directly inspired Chichester's hexagonal design"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Chichester Festival Theatre — directly spawning the National Theatre through Olivier's seasons, spreading the thrust stage design worldwide, and pioneering the regional-to-West End transfer model — is the most institutionally consequential small theater in British history, with influence far exceeding its size.", "significanceCategory": "continental"},
    }),
    ("detroit-opera-house", {
        "summary": "The Detroit Opera House (Michigan Opera Theatre), originally built as the Capitol Theatre in 1922 as one of Detroit's great movie palaces during the silent film era, was rescued from demolition in 1989 by David DiChiera (founder of Michigan Opera Theatre) and restored through a $15.5 million renovation (completed 1996) as the home of the Michigan Opera Theatre — one of America's most socially mission-driven opera companies. The theater's survival represents one of the most successful historic preservation stories in American urban history.\n\nDetroit's operatic history reflects the city's industrial and demographic story: the Motor City's automotive wealth funded a rich cultural life in the early 20th century (Carnegie Hall equivalent, world-class orchestra, opera); the city's post-1960s decline threatened its cultural institutions. David DiChiera's decision to purchase and restore the Capitol Theatre (renamed Detroit Opera House) against the backdrop of Detroit's deindustrialization was a bet on the arts as urban regeneration — a bet that has been partially vindicated.\n\nMichigan Opera Theatre under DiChiera was known for commissioning operas with African American themes and performers at a time when major opera companies rarely featured Black singers in leading roles. The company commissioned X: The Life and Times of Malcolm X by Anthony Davis (premiered 1986), a landmark of American opera that addressed racial history directly. The Detroit Opera House thus became a symbol of both civic resilience and the American opera world's belated engagement with racial diversity.",
        "causes": ["1922 Capitol Theatre construction as Detroit's silent film era movie palace", "1989 DiChiera rescue from demolition as urban preservation bet amid Detroit's decline", "$15.5 million restoration (1989-1996) transforming movie palace to world-class opera house", "Michigan Opera's racial diversity mission commissioning Malcolm X opera and Black lead roles"],
        "effects": ["Most successful American urban historic theater preservation story", "X: The Life and Times of Malcolm X (1986) as landmark American opera on racial history", "Detroit arts sector resilience model amid urban deindustrialization", "African American opera representation model adopted by other companies"],
        "relationships": [{"entity": "David DiChiera", "relationship": "RESCUED_AND_RESTORED_BY", "note": "DiChiera purchased and restored the theater (1989-1996) making it the Michigan Opera Theatre home"}, {"entity": "Michigan Opera Theatre", "relationship": "HOME_OF", "note": "Michigan Opera Theatre — known for racial diversity programming — has been based here since 1996"}, {"entity": "Malcolm X Opera", "relationship": "ASSOCIATED_WITH_COMMISSION_OF", "note": "Anthony Davis's X (1986), commissioned by Michigan Opera, is a landmark of American racial opera history"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Detroit Opera House — rescued from demolition to symbolize Detroit's cultural resilience, home to a company that pioneered African American opera representation, and site of the landmark Malcolm X opera — is the most socially consequential opera house restoration in American urban history.", "significanceCategory": "regional"},
    }),
    ("ellie-caulkins-opera-house", {
        "summary": "The Ellie Caulkins Opera House in Denver, Colorado, opened in 2005 as the centerpiece of the Denver Performing Arts Complex (DPAC), is the home of Opera Colorado and one of the largest and most acoustically sophisticated opera houses in the American West. Named for Denver philanthropist Ellie Caulkins (who donated $5 million to its construction), it was renovated from the older Auditorium Theatre (1908) and features 2,200 seats with one of the largest stage footprints in American opera — enabling productions of comparable scale to the Metropolitan Opera.\n\nThe opera house's acoustic renovation, designed by Wrightson, Johnson, Haddon & Williams Inc. (WJHW), won international awards for solving the challenging acoustic problem of a horseshoe-shaped hall: the 2005 renovation introduced acoustic panels, ceiling reflectors, and a new 8,000-pipe Austin organ to transform a cinema-style auditorium into a European-quality opera house. The project is studied in acoustic engineering programs as an exemplary renovation.\n\nOpera Colorado, founded in 1981, has used the Ellie Caulkins to present a full operatic season to Denver's growing cultural audience — a city whose altitude and dry air presented distinctive acoustic challenges that the renovation specifically addressed. The theater's location in the Denver Performing Arts Complex (the second-largest arts complex in North America) ensures year-round activity alongside the Colorado Symphony, Colorado Ballet, and Denver Center for the Performing Arts, making Denver one of the best-served mid-size American cities for performing arts.",
        "causes": ["2005 renovation of 1908 Auditorium Theatre creating world-class opera facility", "Ellie Caulkins's $5 million donation enabling and naming the facility", "WJHW acoustic renovation solving horseshoe hall challenges — award-winning acoustic engineering", "Denver's cultural growth requiring expanded performing arts capacity in Mountain West"],
        "effects": ["Award-winning acoustic renovation as case study in international acoustic engineering programs", "Opera Colorado gaining world-class stage enabling Metropolitan Opera-scale productions", "Denver Performing Arts Complex as second-largest arts complex in North America", "Mountain West's most acoustically sophisticated opera house enabling full European-scale opera"],
        "relationships": [{"entity": "Opera Colorado", "relationship": "HOME_OF", "note": "Opera Colorado — Mountain West's leading opera company — has performed here since 2005"}, {"entity": "Denver Performing Arts Complex", "relationship": "CENTERPIECE_OF", "note": "Ellie Caulkins is the DPAC's anchor venue — second-largest arts complex in North America"}, {"entity": "Ellie Caulkins", "relationship": "NAMED_FOR_DONOR", "note": "Denver philanthropist Ellie Caulkins donated $5 million to the 2005 renovation"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "The Ellie Caulkins Opera House — award-winning acoustic renovation study, centerpiece of North America's second-largest arts complex, and Mountain West's finest opera venue — demonstrates how thoughtful renovation can transform a historic building into world-class performing arts infrastructure.", "significanceCategory": "local"},
    }),
    ("damascus-opera-house", {
        "summary": "The Damascus Opera House (Dar al-Assad lil-Funun wal-Thaqafa, 'House of Assad for Arts and Culture'), inaugurated in 2004 as Syria's first purpose-built opera house and the largest performing arts venue in the Arab world at its opening (1,850-seat main hall), represented Bashar al-Assad's attempt to project a modernizing, culturally sophisticated Syria to the international community just years before the 2011 civil war that would devastate the country. The building — designed by Spanish architects, built with international funding — sits in central Damascus.\n\nThe Damascus Opera House was used for major international productions and cultural diplomacy events before 2011: European orchestras, Arabic music festivals, and the annual Damascus International Theater Festival were held here. Its programming reflected Assad's cultural liberalization (relative to his father Hafez's more austere policies) and Syria's aspiration to position Damascus as the Arab world's cultural capital.\n\nThe Syrian Civil War (2011-present) has severely damaged Damascus's cultural life. While the opera house was not directly bombed (it is in central Damascus, which remained under government control), its programming collapsed and international performers ceased visiting. The fate of the Damascus Opera House — unable to function as intended amid ongoing conflict while the building itself survives — exemplifies the broader destruction of Syrian cultural institutions by the civil war. Whether it can ever return to its pre-2011 role as an Arab cultural showcase remains uncertain.",
        "causes": ["Bashar al-Assad's 2000s cultural modernization program projecting sophisticated Syria internationally", "Arab world's need for a major performing arts venue to host international cultural events", "Spanish architectural commission creating a European-quality performing arts center in Damascus", "Syrian Civil War (2011-) devastating Damascus's cultural programming despite the building's physical survival"],
        "effects": ["Largest performing arts venue in Arab world at 2004 opening (1,850 seats)", "Syrian cultural diplomacy platform for European orchestras and international events pre-2011", "Civil war cultural collapse making Damascus Opera House a symbol of Syria's pre-war ambitions", "Arab world cultural infrastructure development inspired by Damascus's example"],
        "relationships": [{"entity": "Bashar al-Assad", "relationship": "CULTURAL_MODERNIZATION_PROGRAM_OF", "note": "Assad's 2000s cultural program built the opera house to project a modernizing Syria"}, {"entity": "Syrian Civil War", "relationship": "CULTURAL_LIFE_DESTROYED_BY", "note": "2011 civil war ended international programming and devastated Damascus's cultural sector"}, {"entity": "Damascus International Theater Festival", "relationship": "HOSTED", "note": "Damascus Opera House hosted the DITF — Arab world's most important theater festival pre-2011"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Damascus Opera House — the Arab world's largest performing arts venue at its 2004 opening, a symbol of Syria's pre-war cultural aspirations, and now a monument to the civil war's cultural destruction — represents both the promise and tragedy of Arab cultural institution-building in the 21st century.", "significanceCategory": "regional"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 106 — Class 363 Theaters V: World Opera Houses")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
