#!/usr/bin/env python3
"""Batch 113 — Class 316 Parties VII: African & Communist Parties (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/316-Class-316"
FILE_PREFIX = "316"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("afar-national-democratic-party", {
        "summary": "The Afar National Democratic Party (ANDP), the main political party representing the Afar people — a Cushitic ethnic group of approximately 3-5 million inhabiting the Afar Triangle (the desert lowlands where Ethiopia, Eritrea, and Djibouti meet, including the Danakil Depression) — emerged in the post-1991 Ethiopian federal political reorganization under the EPRDF system and has served as the ruling party of the Afar Regional State in Ethiopia, one of the country's nine ethnic federal units.\n\nThe Afar people are historically significant beyond their numbers: the Afar Triangle is one of the most geologically active regions on Earth (the Danakil Depression reaches 100 meters below sea level, where three tectonic plates are pulling apart) and is the site of the most ancient hominid fossils including 'Lucy' (Australopithecus afarensis, 3.2 million years old). The Afar have maintained a nomadic pastoral tradition in one of the world's hottest and most inhospitable environments.\n\nThe ANDP operated within the EPRDF's ethnic federal framework, which divided Ethiopia into ethnically-defined regional states with their own governments. This system — created by Meles Zenawi to manage Ethiopia's ethnic diversity — gave the Afar Regional State formal autonomy while keeping it within a controlled federal structure. After Abiy Ahmed's 2018 reforms dissolving the EPRDF into the Prosperity Party, many ethnic regional parties including ANDP faced pressure to join the new national party. The Afar region has been affected by the Tigray War (2020-2022) and ongoing drought and development challenges.",
        "causes": ["Post-1991 Ethiopian ethnic federalism creating regional states and ethnic parties under EPRDF", "Afar people's distinct Cushitic identity and nomadic pastoral culture requiring dedicated political representation", "Afar Regional State's establishment within Ethiopia's nine-unit ethnic federal system", "Abiy Ahmed's 2018 reforms creating pressure to merge ethnic regional parties into Prosperity Party"],
        "effects": ["ANDP governing Afar Regional State as dominant ethnic party within EPRDF federal framework", "Afar region's formal autonomy providing institutional voice for nomadic pastoral communities", "Tigray War (2020-2022) creating major humanitarian crisis in Afar region requiring political management", "Ethnic federal model enabling Afar political representation in one of Africa's most ethnically diverse states"],
        "relationships": [{"entity": "Afar People", "relationship": "POLITICAL_PARTY_OF", "note": "ANDP represents the 3-5 million Afar people in Ethiopia's Afar Regional State"}, {"entity": "Ethiopian People's Revolutionary Democratic Front", "relationship": "MEMBER_PARTY_WITHIN", "note": "ANDP operated within the EPRDF's ethnic federal framework as the Afar regional affiliate"}, {"entity": "Afar Regional State", "relationship": "GOVERNING_PARTY_OF", "note": "ANDP has served as the dominant governing party of Ethiopia's Afar Regional State"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "The Afar National Democratic Party — representing one of Africa's most ancient and geologically significant regions, operating within Ethiopia's ethnic federal system, and navigating the Tigray War's humanitarian impact on Afar territory — is an institution of regional importance in the Horn of Africa's political development.", "significanceCategory": "regional"},
    }),
    ("african-christian-democratic-party", {
        "summary": "The African Christian Democratic Party (ACDP), founded in South Africa in 1993 by Reverend Kenneth Meshoe just before the first democratic elections, is South Africa's principal Christian democratic party — combining conservative Christian social values (opposing abortion, pornography, and same-sex marriage) with a pro-free market economic stance and a political history of consistent, if small, parliamentary representation since 1994.\n\nThe ACDP emerged as South Africa transitioned from apartheid to democracy, carving a niche as a party for South African Christians — primarily evangelical Protestants — who found the ANC's social liberalism (particularly its support for abortion rights from 1996) unacceptable but were also committed to racial reconciliation and rejected the racial politics of Afrikaner nationalist parties. Meshoe, a Pentecostal pastor, built the party on a Christian moral platform explicitly rejecting both apartheid (which he condemned as un-Christian) and the ANC's moral and governance failures.\n\nThe ACDP has consistently won 1-3% of the national vote and maintains parliamentary representation, distinguishing it from many similar small parties that have disappeared. Its longevity reflects the significant size of South Africa's evangelical Christian community (particularly among Colored and Black Pentecostal/charismatic communities) and Meshoe's personal political brand. The party has opposed same-sex marriage legislation, called for stronger anti-corruption measures, and positioned itself as a 'clean governance' alternative to the ANC's corruption — a positioning that has gained traction as ANC governance failures accumulated.",
        "causes": ["1993 founding by Pastor Kenneth Meshoe for Christians rejecting both apartheid and ANC social liberalism", "South Africa's 1996 abortion rights legislation alienating evangelical voters from the ANC", "Significant evangelical Protestant community (particularly Colored and Black Pentecostal) requiring political voice", "ANC governance failures and corruption creating space for 'clean governance' Christian democratic alternative"],
        "effects": ["Consistent 1-3% national vote share and parliamentary representation since 1994 elections", "Christian democratic voice in South Africa's parliament opposing abortion and same-sex marriage legislation", "ACDP model demonstrating viability of explicitly Christian democratic party in post-apartheid South Africa", "Meshoe's personal pastoral credibility providing party stability against patron-client political norms"],
        "relationships": [{"entity": "Kenneth Meshoe", "relationship": "FOUNDED_AND_LED_BY", "note": "Pentecostal pastor Meshoe founded the ACDP in 1993 and has led it since"}, {"entity": "African National Congress", "relationship": "CHRISTIAN_CONSERVATIVE_ALTERNATIVE_TO", "note": "ACDP positioned as alternative for Christians rejecting ANC's social liberalism and governance failures"}, {"entity": "South African Democracy", "relationship": "CONSISTENT_PARTICIPANT_IN_SINCE_1994", "note": "ACDP has maintained parliamentary representation across all South African democratic elections since 1994"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "The African Christian Democratic Party — South Africa's principal Christian democratic party, consistently represented in parliament since 1994, and carving a stable niche for evangelical Christians in post-apartheid democracy — demonstrates the enduring relevance of faith-based political parties in diverse democracies.", "significanceCategory": "regional"},
    }),
    ("african-democratic-rally", {
        "summary": "The African Democratic Rally (Rassemblement Démocratique Africain, RDA), founded in 1946 at Bamako under the leadership of Félix Houphouët-Boigny of Côte d'Ivoire, was the most important pan-African political party of the French decolonization era — the organization through which French West African political elites negotiated the terms of independence from France, eventually leading to the independence of 14 French African states between 1958 and 1960.\n\nThe RDA was founded immediately after France's 1946 constitution extended limited citizenship rights to African subjects, creating the first opportunity for organized African political participation in the French system. Houphouët-Boigny and other African leaders affiliated the RDA with the French Communist Party (PCF) for electoral and organizational support — a pragmatic alliance that brought intense colonial repression (the 1949-1950 RDA riots and the Bloody Dimbokro incident). In 1950 Houphouët-Boigny broke the PCF affiliation, shifting the RDA toward accommodation with the French government.\n\nThe RDA's most consequential moment was the 1958 constitutional referendum on De Gaulle's Fifth Republic, when Houphouët-Boigny advised African territories to vote 'Yes' for autonomy within the French Community rather than full independence. Only Guinea under Sékou Touré voted 'No' and received immediate independence and hostile French treatment. The remaining territories gained independence in 1960 — but largely as French-friendly states under leaders like Houphouët-Boigny who maintained close ties with France (Françafrique). The RDA thus shaped the character of Franco-African post-independence relations for decades.",
        "causes": ["1946 Bamako congress founding RDA under Houphouët-Boigny as pan-French West African party", "French 1946 constitution creating limited African political participation enabling organized party activity", "PCF affiliation (1946-1950) providing organizational support and triggering colonial repression", "1958 De Gaulle referendum shaping independence character as French-aligned autonomy"],
        "effects": ["14 French African states achieving independence 1958-1960 primarily through RDA-organized political process", "Françafrique model of French-friendly African independence shaped by Houphouët-Boigny's 1958 strategy", "Guinea's 'No' vote creating immediate French punitive withdrawal — demonstration of costs of defying France", "RDA model establishing cross-border pan-African party organization as framework for independence politics"],
        "relationships": [{"entity": "Félix Houphouët-Boigny", "relationship": "FOUNDED_AND_LED_BY", "note": "Houphouët-Boigny founded the RDA in 1946 and led it through the decisive 1958 independence negotiations"}, {"entity": "French Decolonization in Africa", "relationship": "PRINCIPAL_POLITICAL_VEHICLE_OF", "note": "The RDA was the main organization through which French West African independence was negotiated"}, {"entity": "Françafrique", "relationship": "SHAPED_FRAMEWORK_OF", "note": "Houphouët-Boigny's RDA strategy created the Franco-African relationship model (Françafrique) of post-independence dependencies"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The African Democratic Rally — the pan-African party that negotiated the independence of 14 French African states, shaped the Françafrique post-colonial relationship, and represented the most organized political force in French decolonization — is one of the most consequential political organizations in African history.", "significanceCategory": "world-changing"},
    }),
    ("algerian-communist-party", {
        "summary": "The Algerian Communist Party (Parti Communiste Algérien, PCA), founded in 1936 as an autonomous branch of the French Communist Party with a predominantly European (pied-noir) membership, evolved through an often contradictory relationship with Algerian nationalism — initially downplaying Algerian independence in favor of class solidarity, then supporting and eventually joining the FLN independence movement, and ultimately being banned by independent Algeria's single-party FLN state in 1962.\n\nThe PCA's founding was complicated by the Comintern position that French Algeria should be seen as part of France for Communist Party purposes — a position that prioritized French metropolitan class politics over Algerian national liberation. This created ongoing tension with the emerging Algerian nationalist movement led by Messali Hadj and later the FLN. When the FLN launched the independence war in 1954, the PCA initially maintained ambiguity before eventually supporting armed struggle and joining the FLN.\n\nAlgerian Communist Party members (including Henri Alleg, whose 1958 memoir La Question exposed French torture of Algerians and became one of the most important anti-colonial documents) participated in the independence struggle, but the party was dissolved by Ben Bella's government in 1962 as the FLN established its single-party state. Some PCA members joined FLN; others formed a clandestine Party of the Socialist Vanguard (PAGS). The PCA's history illuminates the contradictions of French colonial communism's relationship to Third World nationalism.",
        "causes": ["1936 founding as autonomous branch of French Communist Party with European settler membership", "Comintern position treating Algeria as part of France creating contradiction with independence politics", "1954 FLN revolution forcing PCA to choose between class politics and national liberation support", "1962 FLN single-party state banning the PCA after independence achieved"],
        "effects": ["Henri Alleg's La Question (1958) exposing French torture as influential anti-colonial document", "PCA members participating in independence war contributing to multi-ideological nature of Algerian nationalism", "1962 dissolution demonstrating that communist parties in newly independent states faced repression regardless of support", "PCA legacy informing debates about communist parties' relationship to Third World national liberation movements"],
        "relationships": [{"entity": "Front de Libération Nationale", "relationship": "EVENTUALLY_SUPPORTED_AND_ABSORBED_INTO", "note": "The PCA initially maintained ambiguity before supporting the FLN revolution; members joined the FLN after 1962 dissolution"}, {"entity": "Henri Alleg", "relationship": "MEMBER_WHOSE_MEMOIR_BECAME_ANTI-COLONIAL_DOCUMENT", "note": "Alleg's La Question (1958) exposing French torture became one of the most important anti-colonial texts"}, {"entity": "French Communist Party", "relationship": "PARENT_BODY_THAT_SHAPED_COLONIAL_CONTRADICTIONS", "note": "PCA's founding as a French PCF branch created its contradictory relationship with Algerian nationalism"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Algerian Communist Party — whose history of contradictions between class politics and national liberation, Henri Alleg's torture testimony, and ultimate dissolution by the state it helped create — is a significant case study in colonial communism's fraught relationship with anti-colonial nationalism.", "significanceCategory": "continental"},
    }),
    ("american-communist-party", {
        "summary": "The Communist Party USA (CPUSA), founded in 1919 by members of the Socialist Party of America who supported the Bolshevik Revolution, was at its height in the 1930s-1940s one of the most influential radical organizations in American political history — organizing industrial unions, leading anti-fascist movements, providing the backbone of the CIO labor federation, and running Progressive Party candidate Henry Wallace for president (1948) — before being decimated by McCarthyism, the Cold War, and the 1956 Soviet crimes revelations.\n\nThe CPUSA's most significant contributions to American life came not through electoral success but through labor organizing (party members were key organizers in the 1930s steel, auto, and electrical workers' unions), civil rights advocacy (the CPUSA defended the Scottsboro Boys in 1931, championed Black equality before it was mainstream, and had significant African American membership), and cultural production (party members and fellow travelers included Paul Robeson, Lillian Hellman, Richard Wright, and numerous Hollywood figures).\n\nMcCarthy-era repression (the Smith Act prosecutions of party leaders, the Hollywood blacklist, FBI surveillance) effectively destroyed CPUSA's mass influence by the mid-1950s. Nikita Khrushchev's 1956 'Secret Speech' revealing Stalin's crimes caused further mass resignations. Today CPUSA exists as a tiny organization with perhaps 5,000 members. But its historical role — in building industrial unionism, advancing Black civil rights decades before the mainstream, and providing an organized left during the New Deal era — gave American labor and civil rights movements a significant leftist infrastructure that shaped 20th-century US politics.",
        "causes": ["1919 founding by Socialist Party members inspired by the Bolshevik Revolution", "1930s Great Depression creating mass organizing opportunities in industrial labor movement", "Anti-fascist politics and CIO labor organizing making CPUSA central to American radical life", "McCarthyism (1947-1957) and Khrushchev's 1956 revelations devastating party membership and influence"],
        "effects": ["CIO industrial union organizing with Communist key organizers transforming American labor relations", "Scottsboro Boys defense and Black civil rights advocacy decades ahead of mainstream politics", "Hollywood blacklist and McCarthy trials as defining moments of Cold War political repression", "Cultural production (Robeson, Hellman, Wright) making CPUSA a major force in 20th-century American art and literature"],
        "relationships": [{"entity": "Congress of Industrial Organizations", "relationship": "KEY_ORGANIZERS_OF", "note": "CPUSA members were central to the CIO's 1930s industrial union organizing drives in steel, auto, and electrical"}, {"entity": "McCarthyism", "relationship": "TARGETED_AND_DECIMATED_BY", "note": "Smith Act prosecutions, FBI surveillance, and McCarthy-era repression effectively destroyed CPUSA's mass influence"}, {"entity": "Scottsboro Boys", "relationship": "DEFENDED_AS_CIVIL_RIGHTS_CASE", "note": "CPUSA's 1931 Scottsboro Boys defense was a landmark in Black civil rights advocacy before the mainstream movement"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Communist Party USA — building American industrial unionism, advocating Black civil rights decades early, producing major cultural figures, and being the central target of McCarthyism — shaped 20th-century American labor, civil rights, and political repression history far beyond its modest electoral success.", "significanceCategory": "world-changing"},
    }),
    ("all-india-nr-congress", {
        "summary": "The All India N. R. Congress (AINRC), founded in 2011 by N. Rangasamy — who broke from the Indian National Congress to form his own party — is the dominant political party of Puducherry (Pondicherry), the small Union Territory of India comprising former French colonial enclaves on India's southeastern coast, with approximately 1.5 million people. AINRC's political significance lies primarily in its role as the main political vehicle for Puducherry's unique semi-autonomous governance and its French colonial cultural heritage.\n\nPuducherry's political structure is distinctive: as a Union Territory with a legislature, it has a Chief Minister but less constitutional autonomy than Indian states. Puducherry's French colonial heritage (France transferred sovereignty in 1954, with formal merger in 1962) has left enduring cultural markers including significant Tamil-French bilingual communities, French-style paved streets in the heritage district, and a proportion of Franco-Pondichérien (French-Indian) residents maintaining French citizenship.\n\nRangasamy served as Puducherry's Chief Minister under Congress, broke away in 2011, and returned to power through the AINRC. The party's politics are primarily focused on Puducherry's specific interests: increased autonomy from the Union Government, development funds, and maintaining the territory's distinctive cultural identity. AINRC has been in coalition with BJP at the national level while maintaining its regional identity in Puducherry — exemplifying the pragmatic coalition arithmetic of Indian small parties.",
        "causes": ["2011 Rangasamy's break from Congress to form independent political vehicle in Puducherry", "Puducherry's unique French colonial heritage creating distinct political identity requiring regional representation", "Union Territory status creating political dependence on national government requiring local advocacy party", "AINRC's coalition flexibility enabling governance through alliances with both national parties"],
        "effects": ["AINRC dominating Puducherry politics as the territory's principal regional party", "Rangasamy serving multiple terms as Chief Minister through AINRC", "Puducherry's distinct French heritage preserved partly through regional party advocating local interests", "AINRC model demonstrating how small Union Territory parties navigate national coalition arithmetic"],
        "relationships": [{"entity": "N. Rangasamy", "relationship": "FOUNDED_BY", "note": "Rangasamy founded AINRC in 2011 after breaking from Congress to build his own political base in Puducherry"}, {"entity": "Puducherry", "relationship": "DOMINANT_PARTY_OF", "note": "AINRC is Puducherry's principal regional party governing the former French colonial Union Territory"}, {"entity": "Indian National Congress", "relationship": "BROKE_AWAY_FROM", "note": "AINRC was founded when Rangasamy split from the Congress, which had governed Puducherry"}],
        "historicalSignificance": {"significanceScore": 4, "significanceNarrative": "All India NR Congress — governing India's smallest and most culturally distinctive territory (former French colonial Puducherry) and navigating Union Territory politics through coalition flexibility — is a regional party whose significance lies in representing a unique Franco-Indian cultural heritage within Indian democracy.", "significanceCategory": "local"},
    }),
    ("angolan-communist-party", {
        "summary": "The Angolan Communist Party (Partido Comunista de Angola, PCA), founded clandestinely during the Portuguese colonial period, operated in the political landscape of Angola's independence struggle alongside the more powerful MPLA (Popular Movement for the Liberation of Angola) — the Marxist-Leninist organization that achieved power in Angola's independence (1975) and has ruled the country ever since. The PCA's role was largely absorbed by and subordinated to the MPLA's dominant position in Angolan left politics.\n\nAngola's independence in 1975 was immediately followed by a devastating civil war between the MPLA (backed by Cuba and the Soviet Union), FNLA (backed by Zaire and CIA), and UNITA (backed by South Africa and the US) — one of the Cold War's most brutal proxy conflicts, killing between 300,000-500,000 people over 27 years. Within this conflict, the MPLA's Marxist-Leninist single-party state left little space for competing communist or socialist parties; the PCA had no significant independent role in post-independence politics.\n\nAngola's post-civil war period (after the 2002 peace agreement killing UNITA's Jonas Savimbi) has seen the MPLA transform from Marxist-Leninist party to a state-capitalist ruling party overseeing Angola's vast oil wealth — one of sub-Saharan Africa's largest oil producers. The MPLA under José Eduardo dos Santos (1979-2017) and João Lourenço (2017-) has maintained power while the PCA remains a marginal entity in Angolan politics.",
        "causes": ["Clandestine colonial-era founding as communist organization in Portuguese-controlled Angola", "MPLA's dominance in Angolan left politics absorbing communist organizing energy", "1975 independence and immediate civil war eliminating space for small leftist parties", "MPLA's monopoly on Marxist-Leninist governance in post-independence Angola"],
        "effects": ["PCA marginalized by MPLA's dominant Marxist-Leninist single-party state after 1975", "Angola's Cold War proxy conflict (1975-2002) framing politics through MPLA vs. FNLA/UNITA rather than PCA", "Post-2002 MPLA state capitalism making communist ideology largely irrelevant to Angola's oil-driven governance", "PCA as historical footnote in a state where the ruling party itself originated in Marxist-Leninist tradition"],
        "relationships": [{"entity": "MPLA", "relationship": "OVERSHADOWED_BY_IN_ANGOLAN_LEFT_POLITICS", "note": "The MPLA's dominant Marxist-Leninist position left the PCA no significant independent role in Angola"}, {"entity": "Angolan Civil War", "relationship": "POLITICAL_CONTEXT_THAT_MARGINALIZED", "note": "The 1975-2002 civil war's MPLA-vs.-UNITA framing left no space for minor communist parties"}, {"entity": "Portuguese Colonial Rule", "relationship": "CONTEXT_OF_CLANDESTINE_FOUNDING", "note": "PCA was founded clandestinely under Portuguese colonial rule before Angolan independence"}],
        "historicalSignificance": {"significanceScore": 4, "significanceNarrative": "The Angolan Communist Party — a colonial-era resistance organization overshadowed by the MPLA's dominant Marxist-Leninist politics, marginalized by Angola's brutal civil war, and rendered irrelevant by the MPLA's post-Marxist transformation — represents the periphery of a political tradition where one party monopolized the left.", "significanceCategory": "local"},
    }),
    ("armenian-communist-party", {
        "summary": "The Communist Party of Armenia (Hayastani Komunistakan Kusaktsutyun), which governed Soviet Armenia from 1921 to 1990 — the entire Soviet period — as the sole legal party, was the institutional vehicle through which Soviet power organized, controlled, and developed the Armenian Soviet Socialist Republic. The party oversaw both Soviet Armenia's worst moments (Stalinist purges, collectivization, population deportations) and its most productive (industrialization, universal education, cultural flourishing through Armenian-language institutions).\n\nSoviet Armenia was established in 1920-1921 after Bolshevik forces overthrew the First Armenian Republic. The Armenian Communist Party, under Moscow's control, implemented collectivization (destroying the Armenian peasantry's traditional agriculture), industrialized Armenia (creating Yerevan's industrial base), and managed the Stalinist purges of the 1930s that killed thousands of Armenian intellectuals, party leaders, and ordinary citizens. Anastas Mikoyan (a Georgian-born Armenian) was among the most powerful Soviet leaders of the Stalin era, serving as a CP Armenia leader before his Moscow career.\n\nUnder Mikhail Gorbachev's glasnost and perestroika, the Armenian Communist Party was challenged by the Armenian National Movement (HHSh), which swept to power in 1990 elections. Armenia declared independence in 1991; the Communist Party was suspended and renamed but continued as a marginal political force. Post-independence Armenia has been dominated by the HHSh and later the Republican Party and My Step Alliance — the Communist Party having lost its Soviet-era monopoly and finding no significant mass constituency in independent Armenia.",
        "causes": ["1921 Bolshevik takeover of the First Armenian Republic establishing Soviet Armenia and its Communist Party", "Stalin's collectivization and purges creating both industrialization and mass suffering under party rule", "Gorbachev-era reforms enabling Armenian National Movement to challenge Communist Party monopoly in 1990", "1991 independence declaration ending the Communist Party's legal monopoly on Armenian political life"],
        "effects": ["Soviet Armenia's industrialization and universal education programs transforming pre-industrial society", "Stalinist purges killing thousands of Armenian party members, intellectuals, and peasants", "1990 elections' Armenian National Movement victory leading to independence declaration", "Post-independence Communist Party reduced to marginal force in pluralist Armenian democracy"],
        "relationships": [{"entity": "Soviet Armenia", "relationship": "SOLE_GOVERNING_PARTY_OF_1921-1990", "note": "The Armenian Communist Party was Soviet Armenia's only legal party for the entire 70-year Soviet period"}, {"entity": "Anastas Mikoyan", "relationship": "NOTABLE_MEMBER_WHO_ROSE_TO_SOVIET_LEADERSHIP", "note": "Mikoyan (CP Armenia background) became one of the most powerful Soviet leaders under Stalin"}, {"entity": "Armenian National Movement", "relationship": "DISPLACED_BY_IN_1990_ELECTIONS", "note": "HHSh's 1990 election victory began the end of Communist Party rule and led to Armenian independence"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Armenian Communist Party — governing Soviet Armenia for 70 years through Stalinist terror, industrialization, and cultural policy, producing Soviet leaders of national importance, and being peacefully displaced by the independence movement — is a central institution in the making and unmaking of Soviet Armenia.", "significanceCategory": "continental"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 113 — Class 316 Parties VII: African & Communist Parties")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
