#!/usr/bin/env python3
"""Batch 111 — Class 340 Religious Orgs IV: Global Denominations (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/340-Class-340"
FILE_PREFIX = "340"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("african-methodist-episcopal-zion-church", {
        "summary": "The African Methodist Episcopal Zion Church (AME Zion), founded in 1796 in New York City by James Varick and other free Black Methodists who separated from the segregated John Street Methodist Church, is one of the oldest and most historically significant African American Christian denominations — known as 'the Freedom Church' because of its deep roots in the abolitionist movement and the fact that Frederick Douglass, Harriet Tubman, and Sojourner Truth were all members or associated with AME Zion congregations.\n\nAME Zion was established because Black Methodists in New York were denied full participation in white Methodist congregations — they could not preach, vote on church matters, or receive communion at the same table. James Varick led the effort to establish an independent African Methodist congregation, incorporated in 1801 and receiving its first bishop in 1822. The denomination spread throughout the Northern states and, after the Civil War, rapidly expanded into the South among newly freed enslaved people.\n\nThe denomination's association with Frederick Douglass (who lectured and preached from AME Zion pulpits), Harriet Tubman (a devoted member who received church support for her Underground Railroad activities), and Sojourner Truth made it synonymous with Black freedom and dignity in 19th-century America. Today AME Zion has approximately 1.4 million members, primarily in the United States, with congregations in Africa, the Caribbean, and Europe. It remains an active voice in African American civic and religious life.",
        "causes": ["1796 separation from segregated John Street Methodist Church by free Black New Yorkers", "Denial of full Methodist participation (preaching, voting, communion) to Black members", "James Varick's leadership organizing first independent African Methodist congregation", "Abolitionist era making AME Zion a spiritual and organizational base for freedom movement"],
        "effects": ["'Freedom Church' becoming center for abolitionism through Frederick Douglass, Harriet Tubman, Sojourner Truth", "Post-Civil War rapid expansion into the South among newly emancipated people", "1.4 million-member denomination providing African American religious and civic infrastructure", "Historical precedent for Black institutional independence from white Christian denominations"],
        "relationships": [{"entity": "Frederick Douglass", "relationship": "MEMBER_AND_PREACHER_OF", "note": "Douglass was closely associated with AME Zion, preaching from its pulpits and relying on its networks"}, {"entity": "Harriet Tubman", "relationship": "DEVOTED_MEMBER_OF", "note": "Tubman was a faithful AME Zion member who received support for Underground Railroad activities"}, {"entity": "Abolitionist Movement", "relationship": "SPIRITUAL_BASE_OF", "note": "AME Zion earned the title 'Freedom Church' as a central organizational base for abolitionism"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "AME Zion — the 'Freedom Church' founded by free Black New Yorkers, associated with Frederick Douglass, Harriet Tubman, and Sojourner Truth, and a foundational institution of African American spiritual and civic independence — is one of the most historically significant Black Christian denominations in American history.", "significanceCategory": "world-changing"},
    }),
    ("american-baptist-churches-usa", {
        "summary": "American Baptist Churches USA (ABC-USA), established in its current form as the American Baptist Convention in 1907 (building on the Triennial Convention founded in 1814 — America's first national Protestant organization), is one of the oldest and largest Baptist denominations in the United States with approximately 1.3 million members and a theologically and racially diverse tradition historically associated with religious liberty, abolition, and social justice.\n\nThe Triennial Convention of 1814 — the first national Protestant cooperative body in America — was founded partly through the efforts of Adoniram Judson and Luther Rice, who had converted to Baptist beliefs en route to India as Congregationalist missionaries. This founding marked American Baptists' entrance into organized international missions. The convention split in 1845 over slavery — Southern Baptists withdrew to form the Southern Baptist Convention — leaving the Northern/American Baptists with a more diverse and progressive theological tradition.\n\nABC-USA has historically been associated with social justice causes: it was integrated before the Civil Rights Movement (though never without tension), maintained women in ministry, and produced important 20th-century social gospel theologians. Martin Luther King Jr. came from the Black Baptist tradition closely linked to American Baptist fellowship. The denomination's Valley Forge, Pennsylvania headquarters coordinates 5,000+ congregations spanning significant racial diversity — reflecting the ABC-USA's position as one of America's most theologically inclusive major Baptist bodies.",
        "causes": ["1814 Triennial Convention founding as America's first national Protestant cooperative body", "1845 slavery-driven split with Southern Baptist Convention leaving diverse Northern Baptist tradition", "Adoniram Judson's missionary conversion and Luther Rice's organizing creating international Baptist missions", "20th-century social gospel theology and racial integration distinguishing ABC-USA from other Baptist bodies"],
        "effects": ["Triennial Convention as model for subsequent American inter-denominational cooperative organizations", "1845 North-South split creating two distinct Baptist traditions (progressive vs. conservative)", "International missionary network from Judson's India work spreading American Baptist missions globally", "ABC-USA's diverse membership model representing inclusive Baptist Christianity in the US"],
        "relationships": [{"entity": "Adoniram Judson", "relationship": "INSPIRED_BY_MISSIONARY_CONVERSION_OF", "note": "Judson's conversion to Baptist beliefs en route to India led to the 1814 Triennial Convention founding"}, {"entity": "Southern Baptist Convention", "relationship": "SPLIT_FROM_OVER_SLAVERY", "note": "Southern Baptists withdrew from the Triennial Convention in 1845 over slavery, creating two Baptist traditions"}, {"entity": "Social Gospel Movement", "relationship": "THEOLOGICAL_TRADITION_ASSOCIATED_WITH", "note": "ABC-USA produced key social gospel theologians and maintained social justice commitments through the 20th century"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "American Baptist Churches USA — tracing from America's first national Protestant cooperative body (1814), defined by its anti-slavery stance in the 1845 split, and maintaining a theologically inclusive social justice tradition — is a foundational institution in American Protestant denominational history.", "significanceCategory": "continental"},
    }),
    ("association-of-shinto-shrines", {
        "summary": "The Association of Shinto Shrines (Jinja Honcho), established in 1946 under the American occupation of Japan as a voluntary religious organization replacing the pre-war state-controlled system of Shrine Shinto, is the central coordinating body for approximately 80,000 Shinto shrines throughout Japan — representing the organized continuation of Japan's indigenous religious tradition after the fundamental transformation imposed by the postwar constitutional separation of religion and state.\n\nBefore World War II, Shrine Shinto (Kokka Shinto) was administered by the Japanese state and treated as non-religious 'national customs' — attendance at shrines was compulsory, shrines were ranked in a government hierarchy, and the Emperor was regarded as a living deity. After Japan's defeat, the 1945 Shinto Directive of the American occupation and Japan's 1947 constitution disestablished state Shinto, ended government support for shrines, and required the Emperor's renunciation of divinity (the Ningen Sengen of January 1, 1946).\n\nJinja Honcho was created to coordinate the now-private shrines and has served since as the main institutional voice of Shinto in Japan. It trains priests, maintains shrine standards, coordinates festivals (matsuri), and represents Shinto in public and interfaith discussions. The Association has been associated with conservative nationalist politics — advocating for constitutional revision to restore Shinto's public status and supporting the Yasukuni Shrine (which honors war dead including convicted war criminals). Jinja Honcho connects Japan's 80,000+ shrines into a single organizational network, making it one of the world's most extensive religious organizational networks.",
        "causes": ["1946 establishment under American occupation replacing state-controlled Shrine Shinto system", "1945 Shinto Directive disestablishing state Shinto and requiring private religious organization", "Japan's 1947 constitution mandating separation of religion and state", "Emperor Hirohito's 1946 Ningen Sengen renouncing divine status transforming Shinto's institutional basis"],
        "effects": ["80,000+ Shinto shrines coordinated under single voluntary organization", "Priest training and matsuri (festival) coordination preserving Shinto practice in secular Japan", "Conservative nationalist association with Yasukuni Shrine creating ongoing political controversy", "Jinja Honcho as one of the world's most extensive religious organizational networks by shrine count"],
        "relationships": [{"entity": "American Occupation of Japan", "relationship": "ESTABLISHED_UNDER_DIRECTIVES_OF", "note": "Jinja Honcho was created in 1946 in direct response to the American occupation's Shinto Directive"}, {"entity": "Yasukuni Shrine", "relationship": "ASSOCIATED_WITH_POLITICALLY", "note": "Jinja Honcho has associations with the controversial Yasukuni Shrine, which honors Japanese war dead"}, {"entity": "Meiji Shrine", "relationship": "MOST_PROMINENT_MEMBER_SHRINE", "note": "Meiji Shrine (Tokyo) is one of Jinja Honcho's most prominent member shrines"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Association of Shinto Shrines — born from Japan's postwar constitutional transformation, coordinating 80,000+ shrines as a voluntary organization where Shinto was once state religion, and embodying the ongoing tension between Japan's indigenous religious identity and its secular democratic constitution — is a pivotal institution in postwar Japanese religious and political history.", "significanceCategory": "world-changing"},
    }),
    ("bulgarian-orthodox-church-alternative-synod", {
        "summary": "The Bulgarian Orthodox Church Alternative Synod (also known as the Bulgarian Orthodox Church in Schism, or the Pimen Schism after its patriarch Pimen), which existed from 1992 to 2004, was a schismatic Bulgarian Orthodox body that rejected the post-communist Bulgarian Orthodox Church's leadership under Patriarch Maxim (elected 1971 under communist oversight) as illegitimate — a dispute that reflected the broader post-1989 struggle in Eastern Europe over churches' communist-era institutional legacies and their claims to authentic Orthodox identity.\n\nPatriarch Maxim had been elected in 1971 through a process controlled by the communist state security services (according to declassified files), and a significant portion of the Bulgarian Orthodox clergy and laity viewed his leadership as tainted by collaboration. After communism's fall (1989-1990), a reform movement within the Bulgarian church pressed for Maxim's resignation; when he refused, the reformers convened an alternative synod in 1992 and elected Metropolitan Pimen as rival patriarch, triggering a schism that divided Bulgarian Orthodoxy for over a decade.\n\nThe dispute became entangled in Bulgarian politics — the UDF (anti-communist opposition) tended to support the Alternative Synod, while the BSP (ex-communist) government supported Patriarch Maxim. Physical confrontations occurred at Orthodox churches as each side tried to take control of buildings. The schism ended in 2004 when the Council of European Churches and the Ecumenical Patriarchate of Constantinople facilitated reconciliation, and all bishops of the Alternative Synod were received back into canonical unity under Patriarch Maxim.",
        "causes": ["Patriarch Maxim's 1971 election under communist state security oversight tainting his legitimacy", "Post-1989 democratic transition enabling public challenge to communist-era church leadership", "Alternative Synod's 1992 rival patriarch election creating formal Orthodox schism in Bulgaria", "Bulgarian political polarization (UDF vs BSP) reinforcing the church schism along political lines"],
        "effects": ["12-year Orthodox schism dividing Bulgarian congregations and clergy until 2004 reconciliation", "Physical confrontations at church buildings as rival synods contested control of property", "2004 Council of European Churches/Ecumenical Patriarchate-mediated reconciliation ending the schism", "Precedent for examining communist-era church leadership legitimacy across post-communist Eastern Europe"],
        "relationships": [{"entity": "Patriarch Maxim of Bulgaria", "relationship": "OPPOSED_AS_RIVAL_SYNOD_TO", "note": "The Alternative Synod was created to challenge Patriarch Maxim's legitimacy due to his communist-era election"}, {"entity": "Ecumenical Patriarchate of Constantinople", "relationship": "RECONCILIATION_FACILITATED_BY", "note": "Constantinople helped mediate the 2004 reconciliation ending the Bulgarian Orthodox schism"}, {"entity": "Communism in Eastern Europe", "relationship": "INSTITUTIONAL_LEGACY_CONFLICT_OF", "note": "The schism reflected post-communist reckoning with church-state collaboration under communist regimes"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Bulgarian Orthodox Church Alternative Synod — a 12-year schism reflecting post-communist Bulgaria's struggle with the institutional legacy of communist-controlled religion, resolved through pan-Orthodox mediation — is a significant case study in post-communist religious de-legitimation and reconciliation.", "significanceCategory": "regional"},
    }),
    ("al-gamaa-al-islamiyya", {
        "summary": "Al-Gama'a al-Islamiyya (The Islamic Group), founded in Egypt in the 1970s from the Islamic student movement at Egyptian universities — particularly Asyut University in Upper Egypt — became one of the most violent Islamist organizations in Egyptian history during the 1990s, responsible for assassinations, attacks on tourists, and the 1997 Luxor Massacre (killing 62 people, mostly foreign tourists, at the Temple of Hatshepsut) before renouncing violence in 1997-1999 and undergoing a theological transformation.\n\nAl-Gama'a al-Islamiyya emerged from the same ideological milieu as Egyptian Islamic Jihad (which later merged with al-Qaeda): both were radicalized by the defeat of 1967, Sadat's peace with Israel, and the influence of Sayyid Qutb's prison writings arguing that contemporary Muslim-majority societies were in a state of jahiliyya (pre-Islamic ignorance) requiring revolutionary overthrow. The group was involved in the assassination of President Anwar Sadat in 1981 (in coalition with Islamic Jihad).\n\nThe organization's 1997 renunciation of violence — initiated by imprisoned leaders engaging in a theological review — was a significant moment in Islamist ideological evolution, eventually formalized in a 2002 document repudiating terrorist tactics on religious grounds. After the 2011 Egyptian Revolution, Al-Gama'a al-Islamiyya formed a political party (the Building and Development Party) and participated in parliamentary elections — completing an extraordinary transformation from designated terrorist organization to electoral participant in a single decade.",
        "causes": ["1970s Egyptian university radicalization under Sayyid Qutb's influence rejecting secular nationalism", "1981 Sadat assassination co-involvement and subsequent state crackdown driving underground militancy", "1990s insurgency in Upper Egypt targeting state security, Coptic Christians, and foreign tourists", "1997 Luxor Massacre backlash causing imprisoned leaders to initiate theological renunciation of violence"],
        "effects": ["Luxor Massacre (1997) killing 62 tourists devastated Egypt's tourism industry and triggered international pressure", "1997-2002 theological renunciation of violence as landmark Islamist ideological transformation", "Post-2011 electoral participation as a terrorist-to-political-party transformation case study", "Al-Gama'a's deradicalization process as model studied by counter-terrorism scholars"],
        "relationships": [{"entity": "Anwar Sadat", "relationship": "PARTICIPATED_IN_ASSASSINATION_OF", "note": "Al-Gama'a al-Islamiyya co-participated with Islamic Jihad in Sadat's 1981 assassination"}, {"entity": "Luxor Massacre", "relationship": "PERPETRATED", "note": "The 1997 Luxor attack killing 62 tourists was perpetrated by Al-Gama'a al-Islamiyya"}, {"entity": "Sayyid Qutb", "relationship": "IDEOLOGICALLY_FOUNDED_ON_WRITINGS_OF", "note": "Qutb's concept of modern jahiliyya requiring revolutionary overthrow informed Al-Gama'a's founding ideology"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Al-Gama'a al-Islamiyya — responsible for Egypt's most deadly terrorist attack (Luxor 1997), involved in Sadat's assassination, but subsequently undergoing a landmark theological renunciation of violence and transforming into a political party — is one of the most significant case studies in Islamist radicalization and deradicalization.", "significanceCategory": "world-changing"},
    }),
    ("brethren", {
        "summary": "The Brethren (also known as Church of the Brethren in the US, originally called 'Dunkers' or 'Dunkards' from their practice of trine immersion baptism), founded in 1708 in Schwarzenau, Germany by Alexander Mack and seven others — drawing on Anabaptist, Pietist, and Reformed traditions — is one of the historic peace churches alongside Quakers and Mennonites, whose commitment to nonresistance, adult baptism, simplicity, and refusal of oaths has shaped distinctive pacifist Christian communities for over three centuries.\n\nThe Brethren movement emerged from the Radical Pietist milieu of early 18th-century Germany: disillusioned with established churches and influenced by the Pietist emphasis on inner spiritual transformation, Mack's group rejected infant baptism, church-state alliances, and military service. Facing persecution in Germany, most Brethren emigrated to Pennsylvania beginning in 1719 — joining the Mennonites and Quakers in creating colonial Pennsylvania's extraordinary concentration of peace church communities.\n\nIn America, the Brethren diversified over centuries: the Church of the Brethren (mainstream, headquartered in Elgin, Illinois) maintains its historic peace church identity; the Brethren Church and other groups represent various 19th-century separations. The denomination was central to Conscientious Objector provision recognition in World War I and II, and the Brethren Volunteer Service (1948) — one of America's oldest voluntary service programs — influenced the later creation of the Peace Corps. The Brethren contribution to American religious pluralism and civil conscientious objection frameworks has been disproportionate to their relatively small numbers (about 130,000 members).",
        "causes": ["1708 founding by Alexander Mack in Schwarzenau combining Anabaptist, Pietist, and Reformed traditions", "German persecution driving Brethren emigration to Pennsylvania (from 1719) joining peace church communities", "Nonresistance, adult baptism, simplicity, and refusal of oaths defining Brethren identity", "American Civil War and World Wars testing and affirming Brethren pacifist commitments"],
        "effects": ["Historic peace church tradition alongside Quakers and Mennonites shaping American religious pluralism", "Conscientious Objector recognition in WWI/WWII influenced by Brethren and other peace church advocacy", "Brethren Volunteer Service (1948) as one of America's oldest voluntary service programs preceding Peace Corps", "Pennsylvania's peace church concentration creating colonial model of religious tolerance and nonviolent civic culture"],
        "relationships": [{"entity": "Alexander Mack", "relationship": "FOUNDED_BY", "note": "Alexander Mack led the 1708 Schwarzenau founding of the first Brethren congregation"}, {"entity": "Mennonites", "relationship": "FELLOW_ANABAPTIST_PEACE_CHURCH_TRADITION", "note": "Brethren, Mennonites, and Quakers form the historic peace churches sharing nonresistance commitment"}, {"entity": "Conscientious Objection", "relationship": "SHAPED_LEGAL_FRAMEWORK_FOR", "note": "Brethren advocacy helped establish CO status recognition in WWI and WWII US law"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Brethren — one of the historic peace churches, shaping American conscientious objection law, founding a voluntary service program that influenced the Peace Corps, and maintaining a 315-year tradition of nonresistance and simplicity — have had an outsized influence on American civil religious pluralism relative to their small numbers.", "significanceCategory": "continental"},
    }),
    ("catholic-apostolic-church", {
        "summary": "The Catholic Apostolic Church (Irvingites), founded in London in the early 1830s around the charismatic ministry of Edward Irving (1792-1834) — a Scottish Presbyterian minister whose congregations at Regent Square experienced the restoration of speaking in tongues (glossolalia) and prophecy beginning in 1830 — was the first modern Christian community to experience and institutionalize charismatic gifts, making it the direct forerunner of the Pentecostal and Charismatic movements that today encompass 600+ million Christians worldwide.\n\nEdward Irving's Regent Square congregation began experiencing what participants believed to be miraculous gifts of the Holy Spirit in 1830 — including speaking in tongues, prophecy, and healing — a full 70 years before the Azusa Street Revival (1906) that launched Pentecostalism. Irving, though died in 1834 before the Church was fully organized, inspired the movement; the Catholic Apostolic Church was formally organized with twelve 'apostles' (to restore the primitive church) beginning in 1835.\n\nThe Catholic Apostolic Church developed an elaborate liturgy combining Catholic, Anglican, and Eastern Orthodox elements — believing it was restoring the complete primitive church before Christ's imminent return. When the twelve apostles died without being replaced (the last in 1901) and Christ had not returned, the church entered terminal decline, though German and Dutch branches (becoming the New Apostolic Church in 1863) survived with replaced apostles. The New Apostolic Church, with approximately 10 million members, is the Catholic Apostolic Church's living descendant — making the Irvingites indirectly ancestral to one of the world's fastest-growing churches.",
        "causes": ["1830 Regent Square glossolalia emergence in Edward Irving's congregation — first modern charismatic outbreak", "Irving's theology of restored primitive church gifts creating framework for charismatic institutionalization", "1835 organization of twelve apostles to restore the New Testament church structure", "Imminent Second Coming expectation creating urgency to restore all primitive church offices before Christ's return"],
        "effects": ["First modern Christian community institutionalizing tongues-speaking — forerunner of Pentecostalism and Charismatic Christianity", "New Apostolic Church (1863 split) as living descendant with approximately 10 million members today", "Irvingite elaborate liturgy demonstrating charismatic gifts were not incompatible with formal liturgical worship", "Historical precedent making Catholic Apostolic Church the link between 19th-century revival Christianity and 20th-century Pentecostalism"],
        "relationships": [{"entity": "Edward Irving", "relationship": "INSPIRED_AND_NAMED_FOR", "note": "Irving's 1830 congregation was the first site of modern glossolalia — the movement is named 'Irvingites' after him"}, {"entity": "Pentecostalism", "relationship": "HISTORICAL_FORERUNNER_OF", "note": "The Catholic Apostolic Church's 1830 glossolalia preceded the 1906 Azusa Street Revival by 76 years"}, {"entity": "New Apostolic Church", "relationship": "PARENT_BODY_OF", "note": "The New Apostolic Church (1863) split from the Catholic Apostolic Church and has approximately 10 million members today"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Catholic Apostolic Church — hosting the first modern outbreak of glossolalia (1830), institutionalizing charismatic gifts 76 years before Azusa Street, and being ancestral to the New Apostolic Church (10 million members) and indirectly to the entire Pentecostal-Charismatic tradition (600+ million Christians) — is one of Christianity's most consequential 19th-century religious movements.", "significanceCategory": "world-changing"},
    }),
    ("all-ukrainian-union-of-churches-of-evangelical-christians-baptists", {
        "summary": "The All-Ukrainian Union of Churches of Evangelical Christians-Baptists (VUTSEHB), the largest Protestant denomination in Ukraine with approximately 2,500 churches and 120,000+ members, traces its roots to the 19th-century Baptist and Evangelical movements that emerged in the Russian Empire's Ukrainian territories despite tsarist persecution — and has survived Soviet repression (including Stalin's near-liquidation of its leadership in the 1930s), forced union with state-controlled religious councils, and now operates in the context of Russia's 2022 full-scale invasion of Ukraine.\n\nBaptist Christianity spread to the Ukrainian territories of the Russian Empire in the 1860s-1870s through German colonist communities in the south (particularly around Odessa) and through indigenous revival movements. The movement grew despite periodic tsarist persecution; after the 1917 Revolution, Baptists briefly enjoyed religious freedom before Stalin's terror decimated Baptist and Evangelical leadership in the 1930s with mass arrests and executions.\n\nDuring the Soviet era, Ukraine's Baptists faced the choice of registering with the state-controlled All-Union Council of Evangelical Christians-Baptists (a government oversight body) or facing illegality — a compromise that many communities accepted but some 'unregistered' or 'underground' congregations rejected. After Ukrainian independence (1991), the All-Ukrainian Union emerged as the main successor body, navigating post-Soviet religious pluralism. Since 2022, Ukrainian Baptist churches have been actively involved in humanitarian assistance to displaced civilians and in supporting Ukrainian soldiers, giving the denomination a new national-service profile in wartime Ukraine.",
        "causes": ["1860s-1870s Baptist mission spread to Ukrainian territories via German colonists and indigenous revival movements", "Stalin's 1930s terror decimating Baptist leadership through mass arrests and executions", "Soviet-era forced registration with state-controlled religious council as condition of legal existence", "1991 Ukrainian independence enabling free re-establishment of the All-Ukrainian Baptist Union"],
        "effects": ["Largest Protestant denomination in Ukraine with 2,500 churches and 120,000+ members", "Post-1991 religious pluralism creating space for evangelical Christianity's growth in post-Soviet Ukraine", "2022 Russian invasion activating Ukrainian Baptist humanitarian networks for civilian and military assistance", "Survival of Baptist communities through tsarist, Soviet, and wartime persecution as model of resilience"],
        "relationships": [{"entity": "Ukraine", "relationship": "NATIONAL_DENOMINATION_OF", "note": "The All-Ukrainian Union is Ukraine's largest Protestant body with 2,500 churches"}, {"entity": "Soviet Religious Policy", "relationship": "REPRESSED_AND_CONTROLLED_UNDER", "note": "Soviet policy forced Baptist registration with state-controlled councils and persecuted unregistered congregations"}, {"entity": "Russian Invasion of Ukraine", "relationship": "HUMANITARIAN_RESPONSE_DURING", "note": "Ukrainian Baptist churches have been major humanitarian actors since Russia's 2022 full-scale invasion"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The All-Ukrainian Union of Evangelical Christians-Baptists — surviving tsarist persecution, Stalinist terror, Soviet control, and now supporting Ukraine during Russia's 2022 invasion — is a resilient Protestant institution whose history maps the arc of religious freedom in Eastern Europe from empire to independence.", "significanceCategory": "continental"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 111 — Class 340 Religious Orgs IV: Global Denominations")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
