#!/usr/bin/env python3
"""Batch 68 — Class 363 Theaters I (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/363-Class-363"
FILE_PREFIX = "363"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("globe-theatre", {
        "summary": "The Globe Theatre was the playhouse built in 1599 in Southwark, London by the acting company to which William Shakespeare belonged — the Lord Chamberlain's Men, later the King's Men. The timber-framed, open-air theater constructed with timbers from the dismantled Theatre in Shoreditch hosted the first performances of Hamlet, Othello, King Lear, Macbeth, and many of Shakespeare's greatest works, making it the most historically important theater in the English-speaking world.\n\nThe Globe was a circular, three-story structure accommodating approximately 3,000 spectators: wealthy patrons in covered galleries surrounding an open-air pit where 'groundlings' stood for a penny. The thrust stage extended into the yard, surrounded by spectators on three sides, creating the intimate relationship between actor and audience that characterizes Shakespearean performance. The thatched roof caught fire during a 1613 performance of Henry VIII and burned to the ground; a second Globe (with a tiled roof) operated until 1644, when Puritan authorities closed London's theaters.\n\nThe Globe Theatre was rebuilt in 1997 as 'Shakespeare's Globe,' 230 meters from the original site on the Bankside, using historical construction methods: green oak, lime plaster, and Norfolk water reed thatch (the only new thatched roof permitted in London since 1666). The reconstructed theater performs Shakespeare under original conditions — no microphones, no artificial lighting during day performances. Sam Wanamaker, the American actor who championed the reconstruction, died in 1993 before seeing it completed.",
        "causes": ["Lord Chamberlain's Men's need for permanent playhouse after dispute over land at the Theatre", "Timbers from demolished Theatre transported across Thames to Southwark to build Globe", "Elizabethan London's popular theater culture requiring large-capacity venue", "Shakespeare's membership in the acting company giving him part ownership of the Globe"],
        "effects": ["First performances of Hamlet, Othello, King Lear, Macbeth at the Globe", "Open thrust-stage design established conventions of Shakespearean performance", "1997 reconstruction as Shakespeare's Globe enables original-practices performances", "Globe model influenced playhouse design across England"],
        "relationships": [{"entity": "William Shakespeare", "relationship": "PERFORMED_AT", "note": "Shakespeare was part-owner and primary playwright for the Globe Theatre 1599-1613"}, {"entity": "Lord Chamberlain's Men", "relationship": "OWNED_BY", "note": "Acting company built and operated the Globe Theatre"}, {"entity": "Sam Wanamaker", "relationship": "RECONSTRUCTED_BY", "note": "American actor championed 1997 reconstruction of Globe using historical methods"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Globe Theatre hosted the first performances of Shakespeare's greatest works and defined the theatrical conventions of the English Renaissance, making it the single most historically significant theater in the English language.", "significanceCategory": "world-changing"},
    }),
    ("la-scala", {
        "summary": "Teatro alla Scala (La Scala) in Milan, Italy is the world's most famous opera house, opened in 1778 and named after the Church of Santa Maria alla Scala it replaced. La Scala is to opera what Carnegie Hall is to classical music or the Louvre is to art: the supreme institution that defines world-class achievement, where careers are made or destroyed by the response of its notoriously demanding audience.\n\nLa Scala was built by Empress Maria Theresa of Austria, who ruled Milan as part of the Habsburg Empire. The Neoclassical theater by architect Giuseppe Piermarini held 2,800 (now 2,030 after renovations). La Scala's premieres include Verdi's Otello (1887) and Falstaff (1893), Puccini's La Gioconda (1876), Catalani's La Wally (1892), and important works by Rossini, Donizetti, and Bellini — essentially the canon of Italian opera. Arturo Toscanini, who conducted at La Scala 1898-1929, established the modern standard of operatic conducting.\n\nLa Scala's social and political history parallels Italy's: the theater was damaged by Allied bombing in 1943 and its 1946 reopening under Toscanini, conducted free for a devastated population, was one of post-war Italy's most emotionally significant cultural acts. Maria Callas's triumphant La Scala debut in 1951, her legendary 1955 Norma, and her 1958 walking off mid-performance in front of the Italian president are among opera's most famous episodes. The current artistic director Riccardo Chailly continues La Scala's central role in world opera.",
        "causes": ["Empress Maria Theresa's commission requiring new opera house for Milan after 1776 fire", "Neoclassical architectural fashion requiring rebuilding of Italian theater in modern form", "Milan's position as Habsburg capital requiring prestigious cultural institution", "Italian operatic tradition requiring supreme venue for world premieres"],
        "effects": ["World premieres of Verdi's Otello, Falstaff, Puccini and Bellini established Italian opera canon", "Toscanini's tenure 1898-1929 established modern operatic conducting standards", "Maria Callas's La Scala career defined 20th-century soprano achievement", "La Scala audiences' demanding standards set global benchmark for operatic excellence"],
        "relationships": [{"entity": "Giuseppe Verdi", "relationship": "PREMIERED_AT", "note": "Otello (1887) and Falstaff (1893) world premieres at La Scala"}, {"entity": "Arturo Toscanini", "relationship": "CONDUCTED_AT", "note": "Toscanini's tenure 1898-1929 established modern conducting standards at La Scala"}, {"entity": "Maria Callas", "relationship": "PERFORMED_AT", "note": "Callas's La Scala career 1951-1958 defined 20th-century soprano achievement"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "La Scala is the world's premier opera house, where Italian opera's greatest works premiered and where Toscanini and Callas defined modern operatic performance — the institution that sets the global standard for operatic excellence.", "significanceCategory": "world-changing"},
    }),
    ("mariinsky-theatre", {
        "summary": "The Mariinsky Theatre in St. Petersburg, Russia is one of the world's great opera and ballet companies, founded in 1783 and named for Empress Maria Alexandrovna. The Mariinsky Ballet Company is arguably the greatest ballet institution in history: birthplace of the classical ballet canon, home of Petipa's Sleeping Beauty and Swan Lake, training ground for Pavlova, Nijinsky, Nureyev, Baryshnikov, and generations of the world's finest dancers.\n\nThe current Mariinsky Theatre building opened in 1860, replacing earlier theaters. The Imperial Ballet and Imperial Opera Companies performed under successive directors, but the era of choreographer Marius Petipa (1862-1903) created the classical ballet canon: The Sleeping Beauty (1890, Tchaikovsky), The Nutcracker (1892), Swan Lake revival (1895), and Raymonda (1898) — works still performed at every major ballet company worldwide. Petipa's Mariinsky created the 'Russian style' of classical ballet that became the global standard.\n\nThe 20th century brought revolution and flight: Anna Pavlova left Russia in 1907, Rudolf Nureyev defected to the West in 1961 (Paris), Mikhail Baryshnikov defected in 1974 (Canada). Each defection brought Russian ballet technique to Western companies. Valery Gergiev, conductor from 1988 and artistic director from 1996, transformed the Mariinsky into a year-round festival theater with new venues including the Mariinsky II (2013) and concert hall. Gergiev's pro-Putin stance cost him the Munich Philharmonic directorship in 2022.",
        "causes": ["Imperial Russian court's establishment of state opera and ballet companies in St. Petersburg", "Empress Maria Alexandrovna's patronage enabling creation of world's finest dance institution", "Marius Petipa's 41-year choreographic tenure creating classical ballet canon", "Tchaikovsky's collaboration with Petipa producing ballet masterworks still defining the form"],
        "effects": ["Classical ballet canon — Sleeping Beauty, Swan Lake, Nutcracker — created at Mariinsky", "Ballet defections by Nureyev and Baryshnikov transferred Russian technique to Western companies", "Mariinsky training system produced most of 20th century's greatest ballet artists", "Gergiev's expansion created year-round international festival theater"],
        "relationships": [{"entity": "Marius Petipa", "relationship": "SHAPED_BY", "note": "Choreographer's 41-year tenure 1862-1903 created the classical ballet canon"}, {"entity": "Rudolf Nureyev", "relationship": "HOME_OF", "note": "Nureyev trained at Mariinsky before 1961 defection to France"}, {"entity": "Pyotr Tchaikovsky", "relationship": "COLLABORATED_WITH", "note": "Tchaikovsky composed Sleeping Beauty, Nutcracker for Mariinsky premieres"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Mariinsky Theatre created classical ballet as a global art form through the Petipa-Tchaikovsky collaboration, and its training of Pavlova, Nijinsky, Nureyev, and Baryshnikov shaped the 20th century's entire dance culture.", "significanceCategory": "world-changing"},
    }),
    ("metropolitan-opera-house", {
        "summary": "The Metropolitan Opera in New York City is the largest classical music organization in the United States and among the world's great opera institutions, founded in 1880 when a group of millionaires unable to obtain boxes at the Academy of Music built their own opera house. The Met's current home at Lincoln Center (opened 1966) accommodates 3,800 and serves as the primary venue for grand opera in the Americas.\n\nThe original Metropolitan Opera House on Broadway (1883-1967) was the site of American premieres of many major operas and home to legendary singers including Enrico Caruso, whose voice defined operatic stardom in the early 20th century. Caruso's 1903 Met debut began a 17-year career there that established the Met as the world's premier destination for great voices. The Met's radio broadcasts, beginning in 1931, made opera accessible to millions across North America — the Saturday afternoon Met broadcasts (the longest-running commercial classical music program in American history) continue to this day.\n\nThe Met at Lincoln Center under Peter Gelb's leadership (from 2006) introduced HD cinema broadcasts to 70+ countries, making Met performances accessible to millions who cannot attend in person. The Met's $300+ million annual budget, 800 full-time employees, and 230+ performances per season make it the world's largest opera organization. Financial crises in 2020 (COVID closure) and ongoing labor-management disputes about costs reflect the fundamental challenge of sustaining grand opera in the 21st century.",
        "causes": ["Millionaires excluded from Academy of Music boxes building their own opera house in 1880", "New York's emergence as America's cultural capital requiring world-class opera institution", "Enrico Caruso's Met career establishing New York as premier destination for great voices", "Radio broadcasts from 1931 making opera accessible to mass American audience"],
        "effects": ["American premieres of major operas established Met as cultural gateway for European art", "Saturday afternoon broadcasts from 1931 created mass American opera audience", "HD cinema broadcasts to 70+ countries extended Met's cultural influence globally", "World's largest opera organization with $300M+ budget established American operatic infrastructure"],
        "relationships": [{"entity": "Enrico Caruso", "relationship": "HOME_OF", "note": "Caruso's 1903-1920 Met career defined operatic stardom and established the house's reputation"}, {"entity": "Lincoln Center", "relationship": "LOCATED_AT", "note": "Met moved to Lincoln Center in 1966; current building accommodates 3,800"}, {"entity": "Peter Gelb", "relationship": "LED_BY", "note": "Gelb's leadership from 2006 introduced HD broadcasts to 70+ countries"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Metropolitan Opera's Saturday broadcasts from 1931 created America's mass opera audience, and its HD cinema broadcasts from 2006 extended grand opera to millions globally — making it the most influential disseminator of classical operatic culture.", "significanceCategory": "world-changing"},
    }),
    ("carnegie-hall", {
        "summary": "Carnegie Hall in New York City is the most prestigious concert hall in the Western Hemisphere and one of the world's most recognized venues for classical music, opened on May 5, 1891 with Pyotr Tchaikovsky conducting. Financed by industrialist Andrew Carnegie as a gift to New York City, Carnegie Hall has hosted virtually every major classical musician, jazz artist, and popular performer of the 20th century — 'to play Carnegie Hall' is the most widely understood shorthand for achieving musical excellence in American culture.\n\nThe hall was designed by architect William Burnet Tuthill with advice from conductor Walter Damrosch, who campaigned Carnegie to fund it. The 2,804-seat main auditorium (Stern Auditorium) is renowned for acoustics so exceptional that the surface of the hall cannot be altered without creating acoustic committees. Tchaikovsky conducted the opening concert; subsequent performers include Gustav Mahler, Arturo Toscanini, Leonard Bernstein, Maria Callas, Judy Garland, Frank Sinatra, the Beatles (1964), Billie Holiday, and virtually every major classical and popular artist of the past century.\n\nCarnegie Hall was almost demolished in 1960 to make way for an office tower until violinist Isaac Stern organized a preservation campaign, saving it as a city landmark. The 1986 and 2003 renovations restored and improved the acoustic shell. Carnegie Hall's international footprint includes music education programs, the Carnegie Hall Archives (over 100,000 items), and the Weill Music Institute serving 75,000 students annually in New York.",
        "causes": ["Andrew Carnegie's philanthropic ambition to give New York City a world-class concert hall", "Walter Damrosch's successful campaign to convince Carnegie to fund the hall", "New York's emergence as America's cultural capital requiring appropriate concert venue", "Tchaikovsky's 1891 opening concerts establishing international prestige immediately"],
        "effects": ["'Playing Carnegie Hall' became universal American shorthand for musical achievement", "Isaac Stern's 1960 preservation campaign established model for landmark preservation activism", "Carnegie Hall recordings and broadcasts created archive of 20th-century performance practice", "Weill Music Institute serves 75,000 students annually in music education"],
        "relationships": [{"entity": "Andrew Carnegie", "relationship": "FUNDED_BY", "note": "Carnegie financed construction as gift to New York; hall opened 1891"}, {"entity": "Pyotr Tchaikovsky", "relationship": "INAUGURATED_BY", "note": "Tchaikovsky conducted Carnegie Hall's opening concert on May 5, 1891"}, {"entity": "Isaac Stern", "relationship": "SAVED_BY", "note": "Violinist's 1960 preservation campaign saved Carnegie Hall from demolition"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Carnegie Hall's 130+ years as the premier concert hall in the Americas have made 'playing Carnegie Hall' the universal symbol of musical achievement — the hall where every major artist of the 20th century performed.", "significanceCategory": "world-changing"},
    }),
    ("royal-opera-house", {
        "summary": "The Royal Opera House at Covent Garden in London is the United Kingdom's principal opera and ballet venue, home to the Royal Opera and the Royal Ballet, dating from 1732 with the current building opened in 1858. The Royal Ballet Company, founded by Ninette de Valois in 1931, developed its own British classical ballet tradition distinct from Russian models — and trained Margot Fonteyn, whose 1962 partnership with Rudolf Nureyev became the most celebrated in ballet history.\n\nThe current building, designed by Edward Barry, has been the scene of premieres of major works by Britten, Walton, and Tippett, and the debut venue for many of the 20th century's greatest singers. The ROH underwent a complete reconstruction 1997-1999, creating a new backstage, a second stage, and public spaces while preserving the Victorian auditorium. The £78 million project was the largest arts capital project in UK history.\n\nThe Royal Ballet's Margot Fonteyn-Rudolf Nureyev partnership (1962-1979) transcended ballet: Nureyev's defection from the Soviet Union had made him a Cold War symbol, and his partnership with Fonteyn — she 43, he 24, when they first danced together — was a sensation that packed every house and brought ballet to television audiences across Britain. Their 1962 Giselle at Covent Garden received 89 curtain calls. The ROH also hosts the BBC Proms final night traditions and serves as a cornerstone of British cultural identity.",
        "causes": ["Royal patents from 1732 establishing Covent Garden as licensed theater for opera and ballet", "Victorian cultural expansion requiring new grand opera house matching Continental equivalents", "Ninette de Valois' founding of Vic-Wells Ballet creating British ballet institution", "Nureyev's defection from Soviet Union creating opportunity for Cold War ballet partnership"],
        "effects": ["British classical ballet tradition developed at ROH distinct from Russian models", "Fonteyn-Nureyev partnership's 89 curtain call Giselle became ballet's most celebrated event", "£78 million reconstruction 1997-99 created model for major arts venue renovation", "ROH has hosted world premieres of Britten, Walton, Tippett operas"],
        "relationships": [{"entity": "Rudolf Nureyev", "relationship": "DANCED_AT", "note": "Nureyev partnered Margot Fonteyn at ROH from 1962; partnership received 89 curtain calls"}, {"entity": "Ninette de Valois", "relationship": "HOME_OF_COMPANY_FOUNDED_BY", "note": "De Valois founded Vic-Wells Ballet that became the Royal Ballet at Covent Garden"}, {"entity": "Margot Fonteyn", "relationship": "HOME_OF", "note": "Fonteyn's career at ROH defined British ballet; Fonteyn-Nureyev partnership was global sensation"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Royal Opera House created British classical ballet through Ninette de Valois's institution-building, and the Fonteyn-Nureyev partnership's 89-curtain-call Giselle represents the most celebrated moment in 20th-century ballet history.", "significanceCategory": "world-changing"},
    }),
    ("apollo-theater", {
        "summary": "The Apollo Theater in Harlem, New York City is the most important venue in the history of African American music and entertainment, transformed from a whites-only burlesque house to Black performance venue in 1934. The Apollo's Amateur Night — still held on Wednesdays — launched the careers of Ella Fitzgerald, Sarah Vaughan, Billie Holiday, James Brown, Stevie Wonder, Marvin Gaye, Jimi Hendrix, Michael Jackson, and Luther Vandross, establishing the Apollo as the crucible of American popular music.\n\nFrank Schiffman and Leo Brecher purchased the 125th Street theater in 1934 and immediately opened it to Black performers and audiences, breaking Harlem's racial entertainment barrier at the height of the Harlem Renaissance. The Amateur Night tradition, where audiences judged acts (and booed off poor performers), became the defining test of raw talent. Ella Fitzgerald won in 1934, launching a career that redefined jazz singing. James Brown recorded 'Live at the Apollo' (1963), which became the best-selling live album in history at the time.\n\nThe Apollo was designated a National Historic Landmark in 1983 and became a non-profit in 1991. The theater's symbolic importance in Black American culture equals its musical importance: during the Civil Rights movement, the Apollo hosted fundraisers; after Martin Luther King's assassination, his body lay in repose at the Apollo as 150,000 mourners filed past. Today the Apollo hosts the Tony Goldwyn-led Apollo Theater Foundation and its education programs reaching 350,000+ students annually.",
        "causes": ["Frank Schiffman's 1934 transformation of whites-only venue to Black entertainment space", "Harlem Renaissance creating extraordinary concentration of Black artistic talent requiring venue", "Amateur Night tradition creating democratizing talent competition attracting undiscovered artists", "African American community's exclusion from mainstream entertainment requiring dedicated venue"],
        "effects": ["Amateur Night launched careers of Ella Fitzgerald, James Brown, Stevie Wonder, Michael Jackson", "James Brown 'Live at the Apollo' (1963) became best-selling live album defining Black music", "150,000 mourners paid respects to MLK at Apollo after 1968 assassination", "Apollo Foundation education programs reach 350,000+ students annually"],
        "relationships": [{"entity": "Ella Fitzgerald", "relationship": "LAUNCHED", "note": "Fitzgerald won Apollo Amateur Night in 1934, launching her career"}, {"entity": "James Brown", "relationship": "HOME_OF", "note": "Brown's 'Live at the Apollo' (1963) became defining document of Black American music"}, {"entity": "Martin Luther King Jr.", "relationship": "HONORED_AT", "note": "King's body lay in repose at Apollo; 150,000 mourners filed past after 1968 assassination"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Apollo Theater's Amateur Night launched the careers of virtually every major Black American musical artist from Ella Fitzgerald to Michael Jackson, making it the single most important incubator of American popular music.", "significanceCategory": "world-changing"},
    }),
    ("radio-city-music-hall", {
        "summary": "Radio City Music Hall in New York City is the largest indoor theater in the world, opened on December 27, 1932 as part of the Rockefeller Center complex, accommodating 5,960 guests. Its Art Deco interior — designed by Donald Deskey with sunburst motifs, 24-karat gold leaf, and curved ceilings — is one of the most spectacular entertainment interiors ever created, and the venue became the premier showcase for Hollywood films before the era of multiplex theaters.\n\nJohn D. Rockefeller Jr. commissioned Radio City as the crown jewel of his Rockefeller Center development during the Great Depression. The theater's opening was not with the planned opera but with vaudeville variety shows that had been the Radio City Music Hall's model from the beginning. The house's scale required staging innovation: the 'hydraulic orchestra pit' that can rise to stage level, three 70-foot elevator-equipped stage platforms, and a turntable stage enabled productions of unprecedented scale.\n\nRadio City is most famous for the Rockettes, the precision dance company that has performed there since opening and whose Christmas Spectacular has played annually since 1933. The venue hosted the Oscars (1945), Grammys (1968), and Tony Awards (1970). When Radio City faced demolition in 1978, preservationists saved it as a New York City landmark — like Carnegie Hall, its survival required a preservation campaign. The venue was fully restored in 1999 to its original 1932 Art Deco splendor.",
        "causes": ["John D. Rockefeller Jr.'s Rockefeller Center development requiring flagship entertainment venue", "Great Depression era requiring large-scale entertainment employment and public uplift", "Art Deco movement at its height providing design vocabulary for spectacular interior", "Hollywood's golden age requiring large-capacity first-run film premieres"],
        "effects": ["World's largest indoor theater established scale benchmark for entertainment venues", "Rockettes Christmas Spectacular (since 1933) became America's most enduring seasonal performance tradition", "Hosted Oscars, Grammys, Tony Awards establishing Radio City as platform for American entertainment royalty", "1999 restoration preserved Art Deco interior as landmark of 20th-century design"],
        "relationships": [{"entity": "John D. Rockefeller Jr.", "relationship": "COMMISSIONED_BY", "note": "Rockefeller built Radio City as crown jewel of Rockefeller Center 1929-1932"}, {"entity": "The Rockettes", "relationship": "HOME_OF", "note": "Precision dance company has performed at Radio City since its 1932 opening"}, {"entity": "Donald Deskey", "relationship": "DESIGNED_BY", "note": "Deskey created the Art Deco interior considered one of America's greatest design achievements"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Radio City Music Hall's Art Deco interior and scale made it the supreme entertainment venue of the 20th century, and the Rockettes' Christmas Spectacular remains America's most enduring performance tradition — a symbol of New York cultural identity.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 68 — Class 363 Theaters I")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
