#!/usr/bin/env python3
"""Batch 125 — Class 341 Cathedrals VII: Strasbourg + European Churches (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/341-Class-341"
FILE_PREFIX = "341"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("church-of-notre-dame-of-dijon", {
        "summary": "The Church of Notre-Dame of Dijon (Église Notre-Dame de Dijon), built primarily between 1220 and 1240 CE, is one of the finest examples of early Gothic architecture in Burgundy, France — remarkable for its highly unusual west façade featuring three arcaded galleries of blind arches decorated with 54 gargoyles (replaced in modern times after they fell), and for housing the celebrated 11th-century Black Madonna of Dijon (Notre-Dame de Bon-Espoir, 'Our Lady of Good Hope'), one of the most venerated Marian images in Burgundy and the center of major historical events.\n\nNotre-Dame's architecture is genuinely exceptional: the west façade's three-story arcaded galleries (each level with two rows of pointed arches) create one of the most unusual compositions in French Gothic architecture, unlike any other major church of its period. The original 54 gargoyles (reproduced today after structural failures) were carved in the distinctive aggressive style of the Gothic grotesque tradition. The false tribunes of the façade have no counterpart in the Gothic canon, making Notre-Dame de Dijon a unique architectural document.\n\nThe 11th-century Black Madonna (carved ebony or dark-stained wooden figure) was carried in procession in 1513 and is credited with preserving Dijon from Swiss siege — creating the 'Jacquemart' bell tradition commemorating the victory. The same Black Madonna was processed again in 1944 when the city was liberated from German occupation, creating a tradition of the city's major crises being addressed through Marian procession. The church also houses the famous Jacquemart clock (a mechanical figure striking the hours), originally looted from Flanders by Philip the Bold of Burgundy.",
        "causes": ["1220-1240 construction during Burgundy's peak Gothic building period under Capetian French rule", "Exceptional Gothic façade design with unique three-story arcaded galleries marking Notre-Dame as architectural experiment", "Black Madonna's 1513 procession during Swiss siege establishing the church's role in Dijon's civic protective mythology", "Jacquemart clock's installation after Philip the Bold's Flemish campaign bringing Burgundian trophy to Dijon"],
        "effects": ["West façade's unique arcaded gallery design influencing scholarly understanding of Gothic architectural experimentation", "Black Madonna procession tradition (1513, 1944) establishing the church as focus of Dijon's crisis religious responses", "Jacquemart clock tradition making Notre-Dame the center of Dijon's civic time-keeping heritage", "Notre-Dame's architectural uniqueness making it Burgundy's most studied Gothic building"],
        "relationships": [{"entity": "Black Madonna of Dijon", "relationship": "HOUSES_MOST_VENERATED_MARIAN_IMAGE_OF", "note": "Notre-Dame houses the 11th-century Black Madonna processed in 1513 and 1944 as Dijon's protective civic religious symbol"}, {"entity": "Philip the Bold", "relationship": "JACQUEMART_CLOCK_BROUGHT_TO_DIJON_BY", "note": "Philip the Bold of Burgundy looted the Jacquemart mechanical clock figure from Flanders and installed it at Notre-Dame"}, {"entity": "Burgundy", "relationship": "MOST_ARCHITECTURALLY_DISTINCTIVE_GOTHIC_CHURCH_OF", "note": "Notre-Dame's unique façade makes it Burgundy's most studied and unusual Gothic architectural monument"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Church of Notre-Dame Dijon — with its uniquely experimental Gothic façade, the Black Madonna that twice saved the city, and the Jacquemart clock from Burgundian conquest — is one of France's most architecturally distinctive Gothic churches and a central monument of Dijon's civic and religious identity.", "significanceCategory": "world-changing"},
    }),
    ("eisenstadt-cathedral", {
        "summary": "Eisenstadt Cathedral (Cathedral Basilica of Saint Martin, German: Domkirche zum heiligen Martin) in Eisenstadt, the capital of the Austrian province of Burgenland, is most historically significant as the place of burial of Joseph Haydn (1732-1809) — one of the greatest composers in Western musical history, often called the 'Father of the Symphony' and 'Father of the String Quartet' for his foundational role in developing these musical forms — who spent most of his professional career (1761-1790) in the service of the Esterházy princes at nearby Esterháza Palace, and was buried at the Bergkirche (Mountain Church) in Eisenstadt, which is closely associated with the cathedral.\n\nJoseph Haydn's Esterházy years (1761-1790) were the most productive period of his career: composing over 100 symphonies, 68 string quartets, 45 piano trios, and numerous operas, masses, and other works while directing the Esterházy court orchestra and opera company. The relative isolation of the Esterházy estates forced Haydn to develop his musical ideas without reference to outside trends — 'I was cut off from the world, and could experiment freely,' he later recalled — producing the classical style's most systematic development.\n\nEisenstadt's Bergkirche houses Haydn's tomb (with a famous morbid Viennese story: his skull was separated from his body for decades by phrenologists before being reunited in the 20th century). The cathedral and Bergkirche together constitute Eisenstadt's primary historical significance as a site of pilgrimage for music lovers worldwide. The Haydn House (museum of his Eisenstadt residence) and the annual Haydn Days festival continue his legacy in the city.",
        "causes": ["Haydn's 1761-1790 Esterházy employment in Eisenstadt region producing the systematic development of classical style", "Esterházy princes' extraordinary musical patronage enabling Haydn's experimental freedom in relative isolation", "Haydn's burial at Eisenstadt Bergkirche making the city his permanent memorial site", "Habsburg provincial capital tradition requiring cathedral in Burgenland's regional center"],
        "effects": ["Haydn's Eisenstadt years producing over 100 symphonies and 68 string quartets defining the classical instrumental canon", "Eisenstadt as global pilgrimage site for music lovers visiting Haydn's tomb and residence", "Skull separation and 20th-century reunion creating one of classical music history's strangest biographical episodes", "Annual Haydn Days festival maintaining Eisenstadt's identity as Haydn's city"],
        "relationships": [{"entity": "Joseph Haydn", "relationship": "BURIAL_SITE_ASSOCIATED_WITH", "note": "Haydn is buried in Eisenstadt's Bergkirche, making the city his permanent memorial and a music pilgrimage destination"}, {"entity": "Esterházy Family", "relationship": "PATRONAGE_CONTEXT_FOR_HAYDN_IN", "note": "The Esterházy princes' Eisenstadt/Esterháza patronage (1761-1790) produced Haydn's most productive creative period"}, {"entity": "Classical Music Canon", "relationship": "HAYDN'S_SYMPHONIES_AND_QUARTETS_FOUNDATIONAL_TO", "note": "Haydn's Eisenstadt-era compositions defined the symphony and string quartet forms central to Western classical music"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Eisenstadt Cathedral — associated with Joseph Haydn's tomb, the musical context that produced over 100 symphonies defining the classical style, and the extraordinary Esterházy patronage that shaped Western music — is historically significant primarily as a site of Haydn's legacy and the music history that makes Eisenstadt a global pilgrimage destination.", "significanceCategory": "world-changing"},
    }),
    ("hans-tausens-church", {
        "summary": "Hans Tausen's Church (Danish: Hans Tausens Kirke) in Roskilde, Denmark, is a significant Lutheran church named for Hans Tausen (1494-1561), the Danish religious reformer known as 'the Danish Luther' — who was among the first major figures to spread Lutheran theology in Denmark and whose preaching in the early 1520s (beginning in Viborg in 1526) initiated the Danish Reformation, ultimately leading to the establishment of the Danish Lutheran state church under King Christian III in 1536 and the complete transformation of Danish religious and cultural life.\n\nHans Tausen's significance in Danish Reformation history parallels Luther's in Germany but with distinctive national character: a former Knight of St. John who converted to Lutheranism after possible contact with Luther himself, Tausen began preaching in Viborg in 1526 under the protection of King Frederick I. His popularity attracted thousands of listeners, created religious conflict with Catholic authorities, and demonstrated that Lutheran ideas could take root in Scandinavian soil as powerfully as in Germany. The Danish Reformation's official completion in 1536 made Denmark one of the first kingdoms to establish a state Lutheran church.\n\nRoskilde — the historic medieval capital of Denmark and the burial place of Danish kings at Roskilde Cathedral (a UNESCO World Heritage Site) — is an appropriate location for a church honoring Tausen, as Roskilde represents the old pre-Reformation Danish ecclesiastical establishment that Tausen's movement transformed. The church named for him memorializes the Reformation's founding figure in the city that symbolizes Denmark's pre-Reformation heritage.",
        "causes": ["Hans Tausen's 1526 Viborg preaching initiating the Danish Reformation under King Frederick I's protection", "Lutheran theology's spread to Scandinavia through reformers like Tausen making Denmark a founding Lutheran kingdom", "King Christian III's 1536 establishment of Danish state Lutheran church completing Tausen's reformation", "Roskilde's historic ecclesiastical significance making it appropriate site for Reformation memorial church"],
        "effects": ["Danish Reformation (1536) transforming Denmark's religious culture and church property through Lutheran state establishment", "Hans Tausen's legacy as 'the Danish Luther' preserved in church dedication and Danish Protestant historiography", "State Lutheran church establishment creating the Church of Denmark that remains the dominant Danish religious institution", "Roskilde's dual identity as both pre-Reformation royal burial site and post-Reformation Lutheran memorial city"],
        "relationships": [{"entity": "Hans Tausen", "relationship": "DEDICATED_TO_'DANISH_LUTHER'_AND_NAMED_FOR", "note": "The church honors Hans Tausen, Denmark's principal Reformation initiator who began preaching in Viborg in 1526"}, {"entity": "Danish Reformation", "relationship": "MEMORIAL_TO_FOUNDING_FIGURE_OF", "note": "The church memorializes Tausen's role in initiating the Danish Reformation that established the state Lutheran church in 1536"}, {"entity": "Roskilde", "relationship": "SITUATED_IN_HISTORIC_DANISH_ECCLESIASTICAL_CAPITAL", "note": "Roskilde's status as the pre-Reformation Danish ecclesiastical center makes it an appropriate site for Reformation memorial"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "Hans Tausen's Church in Roskilde — honoring the 'Danish Luther' who initiated the Reformation that made Denmark one of the first Lutheran kingdoms, standing in the city that symbolizes pre-Reformation Danish ecclesiastical heritage — is historically meaningful as a memorial to the Danish Reformation's founding figure.", "significanceCategory": "continental"},
    }),
    ("old-saint-peters-church-strasbourg", {
        "summary": "Old Saint Peter's Church (Alte Sankt-Peterskirche, French: Église Saint-Pierre-le-Vieux) in Strasbourg, Alsace, is one of the oldest churches in the city — occupying a site with Christian worship dating to the early medieval period and representing Strasbourg's complex religious history as a city that has been alternately French, German, Catholic, and Protestant across the centuries, and that during the Reformation became one of the most important Protestant cities in the Holy Roman Empire under the influence of reformers Martin Bucer and Johann Sturm.\n\nStrasbourg was one of the great free imperial cities of the Holy Roman Empire and an early center of the Protestant Reformation — Martin Bucer established the Strasbourg Reformation from 1523, creating a distinctive Reformed tradition (more inclusive and irenic than Calvin or Zwingli) that influenced John Calvin and the broader Reformed tradition. The Old Saint Peter's Church, like many Strasbourg churches, was caught in the Reformation's transformation of sacred space: Protestant and Catholic communities contested the city's churches during the 16th-17th centuries.\n\nStrasbourg's territorial transfers — French city 1648-1871, German city 1871-1918, French again 1918-1940, German 1940-1944, French 1944-present — meant that its churches physically embodied the Franco-German cultural conflict at its most intense. Old Saint Peter's participates in the Strasbourg ensemble of historic churches (alongside the magnificent Gothic Strasbourg Cathedral) that together document the city's exceptional religious and cultural complexity. The Alsatian concordat (maintained since Napoleon's time) means Strasbourg maintains unique French-German church-state arrangements.",
        "causes": ["Early medieval Christian site establishing Strasbourg's oldest church continuous worship tradition", "Protestant Reformation's Strasbourg center under Martin Bucer transforming the city's religious landscape", "Franco-German border conflicts repeatedly transferring Strasbourg between French and German sovereignty", "Alsatian Concordat maintaining Napoleon-era church-state arrangements unique to Strasbourg"],
        "effects": ["Protestant-Catholic contest for Strasbourg's churches during Reformation documenting the urban Reformation process", "Franco-German territorial conflicts expressed through church linguistic and liturgical transformations", "Strasbourg's Reformed tradition under Bucer influencing Calvin and the broader Reformed theological tradition", "Old Saint Peter's participation in Strasbourg's UNESCO World Heritage historic center ensemble"],
        "relationships": [{"entity": "Martin Bucer", "relationship": "REFORMATION_CONTEXT_SHAPED_BY", "note": "Bucer's Strasbourg Reformation (from 1523) transformed Old Saint Peter's and the city's entire ecclesiastical landscape"}, {"entity": "Strasbourg", "relationship": "OLDEST_CHURCH_COMPONENT_OF_RELIGIOUS_HERITAGE", "note": "Old Saint Peter's occupies one of Strasbourg's oldest continuously used Christian sites in the historic center"}, {"entity": "Alsace", "relationship": "MONUMENT_OF_FRANCO-GERMAN_CONTESTED_HERITAGE", "note": "The church's history embodies Alsace's repeated transfer between French and German sovereignty"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "Old Saint Peter's Church Strasbourg — one of the city's oldest Christian sites, shaped by Bucer's Reformed tradition, and embodying Alsace's Franco-German contested heritage — is historically significant as part of Strasbourg's exceptional religious landscape that influenced the Protestant Reformation and endured centuries of national conflict.", "significanceCategory": "continental"},
    }),
    ("princely-church-saint-nicholas-curtea-de-argeș", {
        "summary": "The Princely Church of Saint Nicholas (Romanian: Biserica Domnească Sfântul Nicolae din Curtea de Argeș) in Curtea de Argeș, Romania, is a 14th-century Orthodox church built by the Wallachian prince Basarab I (founder of the Wallachian principality) circa 1352 — one of the oldest surviving medieval Christian buildings in Romania and a monument to the founding of the Wallachian state, which would eventually become part of modern Romania. The church stands near the famous 16th-century Curtea de Argeș Monastery (Cathedral) that is the burial site of Romanian royalty.\n\nBasarab I of Wallachia (ruled circa 1310-1352) was the founder of the independent Wallachian principality — the first independent Romanian state — following his victory over Hungarian forces at the Battle of Posada (1330). The Princely Church of Saint Nicholas, constructed toward the end of his reign, was the religious expression of the new state's independence and its Orthodox Christian identity. Wallachia's Orthodoxy (in contrast to Catholic Hungary and Poland to its north and west) was a defining cultural characteristic that aligned it with the Byzantine tradition and with Serbia and Bulgaria.\n\nThe church's Byzantine-influenced architectural style, with its frescoes (some original 14th-century work surviving alongside later restorations), documents the artistic and religious connections between Wallachia and the broader Orthodox Christian world of the 14th century. Curtea de Argeș (literally 'Argeș Court') was the first capital of independent Wallachia, making the church a site of Romanian state origins. The later Curtea de Argeș Monastery (built 1512-1517) would house the tombs of Romanian kings.",
        "causes": ["Basarab I's founding of independent Wallachia requiring princely church as religious expression of state sovereignty", "Battle of Posada (1330) victory over Hungary establishing Wallachian independence and requiring state church", "Orthodox Christian tradition aligning Wallachia with Byzantium against Catholic Hungarian pressure", "Curtea de Argeș as Wallachian first capital requiring monumental church befitting a new state"],
        "effects": ["Oldest surviving medieval Christian building in Romania as monument to Romanian state origins", "Wallachian Orthodox identity established through princely church building defining the state's religious character", "14th-century Byzantine-influenced frescoes documenting Wallachia's artistic connections to Orthodox Christian world", "Curtea de Argeș's sacred status established making it the later location of Romanian royal burial monastery"],
        "relationships": [{"entity": "Basarab I", "relationship": "BUILT_BY_FOUNDER_OF_WALLACHIAN_STATE", "note": "Basarab I built the church as expression of the independent Wallachian state he founded after the 1330 Battle of Posada"}, {"entity": "Wallachian Principality", "relationship": "FOUNDING_RELIGIOUS_MONUMENT_OF", "note": "The church is the oldest surviving monument of the independent Wallachian state, predecessor of modern Romania"}, {"entity": "Romanian Orthodox Church", "relationship": "FOUNDING_STATE_CHURCH_MONUMENT_OF", "note": "The church established Wallachia's Orthodox identity that defined Romanian national-religious character for centuries"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Princely Church of Saint Nicholas Curtea de Argeș — built by Basarab I, founder of Wallachia (the first independent Romanian state), Romania's oldest surviving medieval church, and the founding religious monument of Romanian Orthodox statehood — is one of Romania's most historically significant medieval monuments.", "significanceCategory": "world-changing"},
    }),
    ("saint-aurelias-church-strasbourg", {
        "summary": "Saint Aurelia's Church (Église Sainte-Aurélie, German: Sankt-Aureliuskirche) in Strasbourg is a significant Evangelical Lutheran church in the city — one of Strasbourg's historic Reformation-era Protestant churches — dedicated to Saint Aurelia of Strasbourg, a 3rd-century Christian martyr who, according to hagiographic tradition, was one of the companions of Saint Ursula and the 11,000 virgins martyred at Cologne, and whose relics were brought to Strasbourg making her the city's principal early Christian martyr.\n\nSaint Aurelia was the patron saint of Strasbourg before the Reformation, and her church was one of the city's principal pre-Reformation Catholic churches that was subsequently converted to Protestant use during Strasbourg's Reformation under Martin Bucer (1520s-1530s). The conversion of Strasbourg's Catholic churches to Protestant use is one of the key processes of the urban Reformation — as Protestant civic majorities gained control of city governments across the Holy Roman Empire, they took over church buildings, removed 'idolatrous' images and altars, and adapted the spaces to Reformed worship.\n\nSaint Aurelia's church thus embodies the transition from Catholic to Lutheran Strasbourg — the relics of the city's patron martyr contained in a church now serving a community that rejected the cult of relics and saints. This theological paradox is characteristic of the Reformation's complex relationship to the sacred geography it inherited. The church is part of Strasbourg's extraordinary collection of historic religious buildings that together document the city's medieval Catholic, Reformation Protestant, and Franco-German heritage.",
        "causes": ["Saint Aurelia's 3rd-century martyrdom and relic translation to Strasbourg establishing her as city patron", "Pre-Reformation Strasbourg Catholicism requiring major church for the city's patron martyr", "Martin Bucer's Strasbourg Reformation (1520s-1530s) converting Catholic churches including Saint Aurelia's to Protestant use", "Strasbourg's Reformed tradition under Bucer creating distinctive Evangelical Lutheran (rather than strictly Calvinist) character"],
        "effects": ["Conversion from Catholic martyr church to Protestant Evangelical church embodying Reformation's transformation of sacred space", "Relics of Catholic patron saint preserved in Protestant church creating theological paradox of Reformed sacred geography", "Saint Aurelia's church participating in Strasbourg's UNESCO World Heritage historic ensemble", "Protestant worship in an early Christian martyr church documenting the complex continuities of Reformation"],
        "relationships": [{"entity": "Saint Aurelia", "relationship": "DEDICATED_TO_PATRON_MARTYR_OF_STRASBOURG", "note": "Saint Aurelia was Strasbourg's patron martyr whose relics made her church the city's principal pre-Reformation martyr shrine"}, {"entity": "Martin Bucer", "relationship": "CONVERSION_TO_PROTESTANT_USE_UNDER_REFORMATION_OF", "note": "Bucer's Strasbourg Reformation converted Saint Aurelia's (like many Strasbourg churches) from Catholic to Protestant use"}, {"entity": "Strasbourg Reformation", "relationship": "PHYSICAL_MONUMENT_OF_CATHOLIC-TO-PROTESTANT_TRANSITION", "note": "The church's conversion documents the Strasbourg Reformation's transformation of Catholic sacred space to Protestant worship"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "Saint Aurelia's Church Strasbourg — dedicated to the city's patron martyr, converted from Catholic to Protestant use during Bucer's Reformation, and embodying the paradox of Protestant worship in an early Christian martyr shrine — is historically significant as a monument of the urban Reformation's transformation of Catholic sacred geography.", "significanceCategory": "continental"},
    }),
    ("saint-stephens-church-strasbourg", {
        "summary": "Saint Stephen's Church (Église Saint-Étienne de Strasbourg, German: Stephanskirche) in Strasbourg, one of the oldest church foundations in the city (traditional founding attributed to the 7th century CE by Bishop Arbogast), is historically significant as an ancient episcopal church of Strasbourg's pre-medieval Christian community that was later used by a Catholic women's convent before the Reformation converted it — like most of Strasbourg's churches — to Protestant use, and whose early medieval origins connect it to the Frankish Christianization of Alsace that transformed the region from a Roman border province to a Christian Frankish territory.\n\nThe traditional founding of Saint Stephen's by Bishop Arbogast of Strasbourg (died circa 678 CE) places its origins in the Merovingian period — the era when Frankish kings like Clovis's successors were systematically Christianizing the Rhine region and establishing episcopal sees throughout the formerly Roman territories. Arbogast himself is venerated as a saint in Strasbourg; his church foundations (including Saint Stephen's) established the ecclesiastical geography of what would become medieval Strasbourg.\n\nThe Merovingian origins of Saint Stephen's connect it to the foundational layer of Alsatian Christian heritage — predating the Carolingian empire, the Holy Roman Empire, and the Gothic Strasbourg Cathedral. The current church building is a much later reconstruction, as the original Merovingian structures rarely survived the subsequent building and rebuilding cycles. Saint Stephen's as part of Strasbourg's historic religious ensemble contributes to understanding how the earliest layers of Frankish Christian city-building created the ecclesiastical geography inherited by medieval, Reformation-era, and modern Strasbourg.",
        "causes": ["7th-century Merovingian founding by Bishop Arbogast establishing Strasbourg's earliest ecclesiastical geography", "Frankish Christianization of Alsace requiring episcopal church foundations throughout Rhine border territory", "Women's convent establishment in medieval period providing continuity of religious use before Reformation", "Reformation conversion to Protestant use as part of Strasbourg's systematic church transformation under Bucer"],
        "effects": ["Merovingian foundation preserving the earliest layer of Strasbourg's Christian ecclesiastical history", "Arbogast's church network establishing Strasbourg's episcopal identity from Frankish Merovingian period", "Protestant conversion adding Saint Stephen's to Strasbourg's Reformed ecclesiastical heritage", "Early medieval church site contributing to Strasbourg's UNESCO World Heritage ensemble of historic religious buildings"],
        "relationships": [{"entity": "Bishop Arbogast of Strasbourg", "relationship": "TRADITIONALLY_FOUNDED_BY", "note": "Saint Stephen's traditional founding by 7th-century Bishop Arbogast connects it to Strasbourg's Merovingian Christian origins"}, {"entity": "Merovingian Frankish Christianization", "relationship": "FOUNDED_DURING", "note": "The church's Merovingian origins connect it to the Frankish Christianization that transformed Alsace's Rhine border region"}, {"entity": "Strasbourg Historic Religious Ensemble", "relationship": "PART_OF_UNESCO_HERITAGE", "note": "Saint Stephen's contributes to Strasbourg's UNESCO World Heritage collection of historic religious buildings"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "Saint Stephen's Church Strasbourg — one of the city's oldest church foundations with Merovingian origins under Bishop Arbogast, converted during Bucer's Reformation, and representing the earliest layer of Frankish Christianization in Alsace — is historically significant for its deep temporal roots in Strasbourg's Christian heritage.", "significanceCategory": "continental"},
    }),
    ("saint-thomas-church-strasbourg", {
        "summary": "The Church of Saint Thomas (Église Saint-Thomas de Strasbourg, German: Thomaskirche) in Strasbourg is one of the most historically and artistically significant Evangelical Lutheran churches in France — a collegiate church founded in the 12th century, converted to Lutheranism in 1524 (one of the first churches taken over in Strasbourg's Reformation under Martin Bucer), home to the celebrated Silbermann organ (played by Albert Schweitzer and the principal instrument of the Strasbourg Bach tradition), and containing the extraordinary Maréchal de Saxe tomb (by Jean-Baptiste Pigalle, 1777), one of the greatest sculptural monuments in France.\n\nSaint Thomas was a collegiate church (staffed by a chapter of canons rather than a parish priest) — one of Strasbourg's most important pre-Reformation ecclesiastical foundations. Its early Reformation conversion in 1524 made it the center of Strasbourg's Protestant theological life; it housed the theological faculty that trained Reformation-era ministers. Albert Schweitzer, the Nobel Peace Prize-winning humanitarian, musician, and theologian, was a choirmaster and organist at Saint Thomas in the early 20th century and his recordings on the Silbermann organ produced the definitive interpretations of Bach's organ works for their era.\n\nThe Maréchal de Saxe monument (the tomb of Maurice, Marshal of Saxony, erected posthumously by Louis XV's mistress Madame de Pompadour's influence) is one of the most remarkable Baroque sculptural programs in France — depicting the marshal striding toward death while France and his allies weep, Death opens the tomb, and allegorical figures of his opponents celebrate. Its placement in a Protestant church (by a Catholic king's decree for a Protestant marshal) is a historical curiosity reflecting the marshal's fame.",
        "causes": ["12th-century collegiate church foundation establishing Saint Thomas as major Strasbourg ecclesiastical institution", "1524 Reformation conversion making it the first or among first Strasbourg churches taken over by Protestants", "Silbermann organ (18th century) making Saint Thomas the premier Bach performance venue in Strasbourg", "Maréchal de Saxe monument commissioned by Madame de Pompadour's influence for France's greatest Protestant general"],
        "effects": ["Saint Thomas as center of Strasbourg's Protestant theological education during the Reformation era", "Albert Schweitzer's Bach recordings on the Silbermann organ producing the 20th century's most influential Bach organ interpretations", "Maréchal de Saxe monument as one of France's greatest Baroque sculptural programs in an unexpected Protestant setting", "Strasbourg's Reformed tradition under Bucer originating in Saint Thomas's early conversion"],
        "relationships": [{"entity": "Albert Schweitzer", "relationship": "ORGANIST_AND_BACH_INTERPRETER_AT", "note": "Schweitzer's Silbermann organ recordings at Saint Thomas produced the 20th century's most influential Bach organ interpretations"}, {"entity": "Maréchal de Saxe", "relationship": "EXTRAORDINARY_BAROQUE_TOMB_OF_IN", "note": "Pigalle's 1777 monument to Maurice de Saxe is one of France's most remarkable Baroque sculptures, housed in this Protestant church"}, {"entity": "Martin Bucer", "relationship": "REFORMATION_BEGAN_AT_STRASBOURG_WITH_CONVERSION_OF", "note": "Saint Thomas's 1524 conversion was among the first acts of Bucer's Strasbourg Reformation"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Saint Thomas Church Strasbourg — site of Strasbourg's first Reformation conversion (1524), home of the Silbermann organ that Albert Schweitzer used for his defining Bach recordings, and containing Pigalle's extraordinary Maréchal de Saxe monument — is one of France's most historically and artistically significant Protestant churches.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 125 — Class 341 Cathedrals VII: Strasbourg + European Churches")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
