#!/usr/bin/env python3
"""Batch 102 — Class 312 Dynasties X: Extended European Royal Houses (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/312-Class-312"
FILE_PREFIX = "312"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("house-of-bourbon-in-france", {
        "summary": "The House of Bourbon in France, the senior French branch of the Bourbon dynasty ruling France from Henry IV's 1589 accession through Louis XVI's execution (1793) and then again in the Restoration period (1814-1830), encompasses the French royal line most directly associated with the absolute monarchy at Versailles, the French Revolution, and the ultimate end of Bourbon rule in France. Distinct from the Spanish Bourbons (still ruling) and Italian branches, the French Bourbons are history's most famous example of a dynasty felled by its own people's revolution.\n\nThe French Bourbon golden age — Louis XIV (r. 1643-1715, France's longest-reigning monarch at 72 years) built Versailles (constructed 1661-1710, employing 30,000 workers, symbol of absolute monarchy), waged the War of the Spanish Succession to install his grandson Philip V in Spain, and dominated European culture so thoroughly that French became the international language of diplomacy and aristocracy for the next 150 years. Louis XVI (r. 1774-1793) — well-meaning but indecisive — faced fiscal crisis (from Louis XIV's wars and Louis XV's court extravagance), convened the Estates-General (1789), and was overthrown when the Third Estate declared itself the National Assembly.\n\nLouis XVI's execution by guillotine on January 21, 1793, followed by Marie Antoinette's October 1793, was the defining moment of the Revolution — transforming it from political reform to regicide. The Bourbon Restoration (Louis XVIII, 1814-1824; Charles X, 1824-1830) attempted to rebuild royal authority but ended when Charles X's reactionary ordinances triggered the July Revolution (1830) deposing him. The French Bourbons thus serve as history's foremost case study of a dynasty that failed to adapt to modernity.",
        "causes": ["Henry IV's 1589 accession founding French Bourbon rule after Wars of Religion", "Louis XIV's 72-year reign building absolute monarchy model at Versailles", "Fiscal crisis from royal wars funding the third estate's 1789 revolutionary mobilization", "Louis XVI's execution 1793 and Bourbon Restoration failure (1830) ending French Bourbon rule"],
        "effects": ["Versailles as model of absolute monarchy influencing courts across Europe for 150 years", "French language dominance as international diplomatic language for 150+ years", "Louis XVI's execution as defining moment of French Revolution transforming it to regicide", "July Revolution 1830 ending Bourbon Restoration and inaugurating constitutional monarchy"],
        "relationships": [{"entity": "Louis XIV of France", "relationship": "GOLDEN_AGE_RULER", "note": "Sun King (1643-1715) built Versailles and dominated European culture; France's longest-reigning monarch"}, {"entity": "Louis XVI of France", "relationship": "DYNASTY_ENDED_BY_EXECUTION_OF", "note": "Louis XVI's 1793 guillotine execution ended the French Bourbon monarchy's first period"}, {"entity": "Palace of Versailles", "relationship": "BUILT_BY_DYNASTY", "note": "Louis XIV's Versailles (1661-1710) was the Bourbon dynasty's physical symbol of absolute power"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The French Bourbon line — producing Louis XIV's absolute monarchy model, the French Revolution's regicide, and Versailles as Western civilization's defining palace — is among history's most studied dynasties: their failure to adapt to modernity caused the Revolution that remade Europe and inaugurated the modern democratic age.", "significanceCategory": "world-changing"},
    }),
    ("house-of-habsburg-lorraine", {
        "summary": "The House of Habsburg-Lorraine, created when Holy Roman Empress Maria Theresa's husband Francis I of Lorraine merged his Lorraine dynasty with the Habsburg house upon their 1736 marriage, represents the continuation of Habsburg imperial rule from 1740 (Maria Theresa's succession) through Austria-Hungary's 1918 dissolution — the most recent form of the dynasty. Though Maria Theresa technically ruled as 'Queen of Hungary and Bohemia' (Salic law barred her from Holy Roman Emperor), she was Austria's most consequential ruler: she reformed administration, education, and the military while waging the War of Austrian Succession (1740-1748) against Frederick the Great.\n\nMaria Theresa (r. 1740-1780) — mother of 16 children including Marie Antoinette (who became Queen of France and was executed in the Revolution) — introduced compulsory primary education to her lands, founded the Vienna General Hospital, abolished the use of judicial torture, and reformed the tax system. Her son Joseph II (r. 1780-1790) continued her reforms, abolishing serfdom (1781) and granting religious toleration (Edict of Toleration, 1781) — he was the 'most enlightened despot' in European history.\n\nThe dynasty continued through Napoleon's defeat (1815), the Hungarian Compromise (1867 creating Austria-Hungary), Franz Joseph's 68-year reign (1848-1916), and Franz Ferdinand's assassination (1914) that triggered WWI. Charles I (r. 1916-1918), the last Habsburg emperor, abdicated November 11, 1918 — the same day WWI ended — dissolving the multinational empire that had governed 50+ million people across 11 nations. He was beatified by Pope John Paul II in 2004.",
        "causes": ["Maria Theresa's 1740 accession and Habsburg-Lorraine merger transforming the dynasty", "War of Austrian Succession (1740-1748) testing Maria Theresa against Frederick the Great", "Maria Theresa's administrative, educational, and medical reforms modernizing the Austrian state", "Franz Ferdinand's 1914 assassination triggering WWI and dynasty's eventual end"],
        "effects": ["Compulsory primary education established by Maria Theresa across Habsburg lands", "Vienna General Hospital (1784) as model for European medical education", "Hungary Compromise 1867 creating Austria-Hungary as Europe's second-largest state", "Charles I's 1918 abdication dissolving the empire creating modern Central Europe"],
        "relationships": [{"entity": "Maria Theresa of Austria", "relationship": "FOUNDING_RULER_OF_COMBINED_DYNASTY", "note": "Maria Theresa's marriage to Francis of Lorraine (1736) and 1740 accession created Habsburg-Lorraine"}, {"entity": "Franz Joseph I of Austria", "relationship": "LONGEST_RULING_REPRESENTATIVE", "note": "Franz Joseph's 68-year reign (1848-1916) spanned from revolution to WWI"}, {"entity": "Charles I of Austria", "relationship": "DYNASTY_ENDED_BY_ABDICATION_OF", "note": "Charles I abdicated November 11, 1918 — same day WWI ended — dissolving the empire"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The House of Habsburg-Lorraine — producing Maria Theresa's Enlightenment reforms, governing 50 million people across 11 nations in Austria-Hungary, and ending in WWI's catastrophe — governed Central Europe's most diverse empire and its dissolution created the modern map of Central Europe.", "significanceCategory": "world-changing"},
    }),
    ("house-of-hohenzollern-sigmaringen", {
        "summary": "The House of Hohenzollern-Sigmaringen, a Catholic cadet branch of the Hohenzollern family that split from the main (Protestant) Hohenzollern line in 1601, produced monarchs of Romania (1866-1947) and Portugal (1853-1910), making it uniquely successful as a dynasty that ruled foreign countries rather than its German homeland. The Romanian branch — founded when Carol I was elected prince (1866) and became king (1881) — ruled Romania for 81 years through its transformation from an Ottoman vassal state to an independent kingdom to a post-WWI enlarged state to the WWII period and communist takeover.\n\nCarol I (r. 1866-1914), a Prussian-born military officer, modernized Romania's infrastructure (railways, Bucharest's boulevards), led Romania in the 1877-78 Russo-Turkish War winning independence from the Ottoman Empire, and established the Romanian national bank and civil code. His nephew Ferdinand I (r. 1914-1927) — the 'unifier king' — brought Romania into WWI on the Allied side (1916), and the 1918 peace treaties doubled Romania's territory (gaining Transylvania, Bessarabia, Bukovina).\n\nMichael I (r. 1927-30, 1940-47) — who became king at age 6 in 1927 — performed his most consequential act as a young adult: the 'Royal Coup' of August 23, 1944, when he arrested and deposed pro-Nazi dictator Ion Antonescu and switched Romania to the Allied side, potentially saving 300,000 lives. Michael was awarded the Soviet Order of Victory (the only Western leader so honored); he was later forced to abdicate by the Communists (1947) and died in exile (2017). The Romanian Hohenzollern-Sigmaringen dynasty represents one of history's most successful imported monarchies.",
        "causes": ["1601 split from main Hohenzollern line creating Catholic Hohenzollern-Sigmaringen cadet branch", "1866 election of Carol I as Romanian prince installing dynasty in foreign kingdom", "Carol I's 1877 independence war leadership establishing Romania as independent state", "Michael I's 1944 Royal Coup switching Romania to Allies as dynasty's most consequential act"],
        "effects": ["Romania's modernization (railways, Bucharest boulevards) under Carol I 1866-1914", "1918 Greater Romania created with doubled territory under Ferdinand I after WWI", "Michael I's 1944 Royal Coup saving an estimated 300,000 lives and shortening WWII", "Communist-forced 1947 abdication ending dynasty and inaugurating Romanian communism"],
        "relationships": [{"entity": "Carol I of Romania", "relationship": "ROMANIAN_BRANCH_FOUNDED_BY", "note": "Carol I (1866-1914) founded the Romanian dynasty; won independence from Ottoman Empire (1877)"}, {"entity": "Michael I of Romania", "relationship": "LAST_KING_AND_MOST_CONSEQUENTIAL_ACT", "note": "Michael I's 1944 Royal Coup arrested Antonescu and switched Romania to Allies"}, {"entity": "Communist Romania", "relationship": "DYNASTY_ENDED_BY", "note": "Romanian Communists forced Michael I's abdication December 30, 1947 ending the dynasty"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The House of Hohenzollern-Sigmaringen — founding Romanian statehood through Carol I, doubling Romania's territory through WWI, and performing the decisive 1944 Royal Coup that switched Romania to the Allies — is among history's most consequential imported dynasties, governing a nation through its most transformative century.", "significanceCategory": "continental"},
    }),
    ("house-of-habsburg-lorraine", {
        "summary": "Duplicate skip — see above",
        "causes": [],
        "effects": [],
        "relationships": [],
        "historicalSignificance": {"significanceScore": 1, "significanceNarrative": "skip", "significanceCategory": "local"},
    }),
    ("holstein-gottorp-romanov", {
        "summary": "The Holstein-Gottorp-Romanov dynasty, the German-origin branch of the Russian imperial family that began when Peter III (grandson of Peter the Great through the female line, but a German Holstein-Gottorp prince) briefly ruled Russia (1762) before being deposed by his wife Catherine the Great, continued the Romanov name while introducing German blood — so thoroughly that by 1917, Nicholas II's actual biological connection to the original Romanovs was minimal. The Holstein-Gottorp-Romanovs governed Russia from 1762 to 1917 — the dynasty's most consequential century — through Catherine the Great's Enlightenment absolutism, Napoleon's defeat, Alexander II's emancipation of serfs, and Nicholas II's catastrophic WWI leadership.\n\nThe key rulers: Catherine the Great (r. 1762-1796), herself a German princess of Anhalt-Zerbst who had Peter III murdered/deposed, expanded Russia to the Black Sea, partitioned Poland three times (creating the 'Jewish Pale of Settlement'), and presided over Russia's cultural flowering while maintaining rigid serfdom. Alexander II (r. 1855-1881) — the 'Tsar Liberator' — emancipated Russia's 23 million serfs (1861), the largest emancipation in world history; he was assassinated by socialist revolutionaries (March 13, 1881) on the day he was to sign a proto-constitutional reform.\n\nNicholas II (r. 1894-1917) — the dynasty's last ruler — was fundamentally unsuited for the challenges of modern governance: he resisted constitutional reform until 1905 (when the Revolution forced him to create the Duma), mismanaged WWI through personal command, and failed to address food shortages and military mutinies. His abdication (March 15, 1917) and execution with his family at Yekaterinburg (July 17, 1918) ended the dynasty. The Holstein-Gottorp-Romanov era — from Catherine the Great's expansion to Nicholas II's collapse — is Russia's defining political century.",
        "causes": ["Peter III's 1762 Holstein-Gottorp ascendancy beginning German-line Romanov rule", "Catherine the Great's deposition of Peter III establishing her own rule and dynasty's direction", "Alexander II's 1861 serf emancipation as largest liberation in world history up to that point", "Nicholas II's WWI failures (1914-1917) causing revolution and dynasty's end"],
        "effects": ["Russia's expansion to Black Sea and partitioning of Poland under Catherine the Great", "Serf emancipation (1861) transforming Russia's social order (23 million freed)", "1905 Revolution forcing creation of the Duma as proto-parliamentary body", "1918 Yekaterinburg execution ending the dynasty and inaugurating Soviet Russia"],
        "relationships": [{"entity": "Catherine the Great", "relationship": "DYNASTY_ESTABLISHED_IN_POWER_BY", "note": "Catherine deposed Peter III (1762) and built Russia's 18th-century imperial expansion"}, {"entity": "Alexander II of Russia", "relationship": "MOST_REFORMIST_RULER", "note": "Alexander II emancipated 23 million serfs (1861) — largest liberation in world history"}, {"entity": "Nicholas II of Russia", "relationship": "DYNASTY_ENDED_BY_RULE_OF", "note": "Nicholas II's 1917 abdication and 1918 execution ended 304 years of Romanov rule"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Holstein-Gottorp-Romanov dynasty — ruling Russia through Catherine the Great's expansion, Napoleon's defeat, serf emancipation (the largest liberation in world history), and Nicholas II's catastrophic collapse — governed Russia's most consequential century and ended in one of history's defining political transformations.", "significanceCategory": "world-changing"},
    }),
    ("ashikaga-clan", {
        "summary": "The Ashikaga clan (Ashikaga Shogunate, 1338-1573), a Japanese warrior clan that established the Muromachi shogunate after Ashikaga Takauji overthrew Go-Daigo's Kemmu Restoration (1336) and was appointed shogun by Emperor Kōmyō in 1338, ruled Japan for 235 years — though the later shoguns' authority was largely nominal as regional warlords (daimyo) competed for actual power. The Ashikaga period is culturally Japan's richest, producing Noh theater, the tea ceremony, Zen-influenced landscape gardens, ink painting, and the aesthetic concept of wabi-sabi.\n\nThe third shogun Yoshimitsu (r. 1368-1394) was the Ashikaga's most powerful ruler: he unified the Northern and Southern Courts (ending the Nanbokucho War in 1392), opened trade relations with Ming China (using the title 'King of Japan' — to his contemporaries' shock), and built the Golden Pavilion (Kinkaku-ji, 1397) — Japan's most iconic surviving medieval building. His grandson Yoshimasa (r. 1449-1473) was the dynasty's cultural peak despite (or because of) his political incompetence: amid the devastating Ōnin War (1467-1477 — which destroyed Kyoto and fragmented the shogunate's authority), Yoshimasa built the Silver Pavilion (Ginkaku-ji) and patronized the artists who defined Japanese aesthetic culture.\n\nThe dynasty's end: the Sengoku ('Warring States') period (1467-1615) emerged from the Ōnin War as regional lords fought for supremacy; the final shogun Yoshiaki was deposed by Oda Nobunaga in 1573, ending Ashikaga rule. The Ashikaga's cultural legacy — Noh, tea ceremony, Zen gardens — profoundly shaped Japanese aesthetics and has influenced global design, architecture, and philosophy to the present.",
        "causes": ["1336-38 Ashikaga Takauji's overthrow of Go-Daigo founding the Muromachi shogunate", "Yoshimitsu's reunification of Northern and Southern Courts (1392) and Ming China trade opening", "Ōnin War (1467-77) fragmenting shogunate authority and inaugurating Sengoku period", "Oda Nobunaga's 1573 deposition of shogun Yoshiaki ending Ashikaga rule"],
        "effects": ["Noh theater developed as Japan's first great dramatic tradition under Ashikaga patronage", "Tea ceremony (chado) formalized as spiritual practice and aesthetic discipline", "Kinkaku-ji (Golden Pavilion, 1397) as Japan's most iconic medieval building", "Sengoku Warring States period emerging from Ashikaga decline, reshaping Japan"],
        "relationships": [{"entity": "Ashikaga Yoshimitsu", "relationship": "MOST_POWERFUL_RULER", "note": "Yoshimitsu (1368-1394) unified Japan, opened Ming China trade, and built Kinkaku-ji"}, {"entity": "Kinkaku-ji", "relationship": "ICONIC_BUILDING_BUILT_BY", "note": "Golden Pavilion (1397) built by Yoshimitsu — Japan's most iconic medieval structure"}, {"entity": "Oda Nobunaga", "relationship": "DYNASTY_ENDED_BY", "note": "Nobunaga deposed the last Ashikaga shogun Yoshiaki in 1573, ending the dynasty"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Ashikaga Shogunate — producing Noh theater, the tea ceremony, Zen gardens, wabi-sabi aesthetics, and the Golden and Silver Pavilions while presiding over Japan's most culturally creative period — is the dynasty that gave Japan its most enduring cultural identity, with its aesthetic legacy shaping global design culture to the present.", "significanceCategory": "continental"},
    }),
    ("chera-dynasty", {
        "summary": "The Chera dynasty, one of the three great classical Tamil kingdoms of ancient southern India (along with the Chola and Pandya dynasties), ruled the regions of present-day Kerala and western Tamil Nadu from approximately the 3rd century BCE to the 12th century CE — a remarkable continuity spanning over 1,500 years across two distinct periods (Early Cheras, 3rd c. BCE - 5th c. CE; Later Cheras/Kulashekhara, 800-1102 CE). The Cheras were the dominant power of the Malabar Coast (modern Kerala), controlling the lucrative spice trade that connected Rome, Arabia, and China to South Asia.\n\nThe Early Cheras' capital Vanchi (possibly modern Karur, Tamil Nadu) traded with the Roman Empire: the 'Periplus of the Erythraean Sea' (1st century CE) describes the Malabar Coast's pepper, cardamom, and ivory trade with Rome; the Tabula Peutingeriana (medieval copy of a Roman road map) shows a 'Temple of Augustus' at Muciri (Muzuris, Kerala) — evidence of permanent Roman presence in Chera territory. The 'Peutingeriana' evidence suggests Roman merchants established permanent trading posts in Chera lands, making it one of the earliest documented East-West commercial relationships.\n\nThe Later Cheras (Kulashekhara dynasty, 800-1102 CE), based in Mahodayapuram (Kodungallur), patronized Malayalam literature, built Kerala's great temples (including the Vadakkunnathan Temple, Thrissur), and facilitated the Nambudiri Brahmin settlement that created Kerala's unique religious and caste structure. Their final defeat by the Chola Empire (1102 CE) ended centralized Chera rule, fragmenting Kerala into the small kingdoms that Portuguese explorer Vasco da Gama encountered in 1498.",
        "causes": ["3rd century BCE establishment of Chera kingdom controlling Malabar Coast spice trade", "Roman Empire-Chera trade relations documented in Periplus of the Erythraean Sea (1st c. CE)", "Later Cheras (800-1102 CE) patronizing Malayalam literature and temple construction", "1102 CE Chola defeat of Later Cheras fragmenting Kerala into small kingdoms"],
        "effects": ["Malabar Coast spice trade (pepper, cardamom) connecting Rome, Arabia, and China through Chera territory", "Malayalam language literary tradition established through Later Chera patronage", "Kerala temple architecture (Vadakkunnathan, etc.) defining Kerala's architectural identity", "Fragmented Kerala kingdoms encountered by Vasco da Gama (1498) opening spice trade to Europe"],
        "relationships": [{"entity": "Roman Empire", "relationship": "TRADED_WITH", "note": "Periplus of the Erythraean Sea (1st c. CE) documents Roman-Chera spice trade with permanent Roman merchants in Malabar"}, {"entity": "Chola Empire", "relationship": "DEFEATED_BY", "note": "Chola Empire's 1102 CE defeat of Later Cheras ended centralized Chera rule"}, {"entity": "Vasco da Gama", "relationship": "SUCCESSOR_KINGDOMS_ENCOUNTERED_BY", "note": "Vasco da Gama (1498) arrived in fragmented Kerala that existed after Chera dissolution"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Chera dynasty — controlling the Malabar Coast spice trade that connected Rome to Asia, documented in Roman sources 2,000 years ago, and establishing Malayalam literature and Kerala's temple tradition — shaped global trade history and remains Kerala's foundational political and cultural institution.", "significanceCategory": "continental"},
    }),
    ("spanish-house-of-habsburg", {
        "summary": "The Spanish House of Habsburg (the Spanish Habsburgs, r. 1516-1700), established when Charles I of Spain (Charles V, Holy Roman Emperor) inherited the Spanish Crown from his maternal grandparents Ferdinand and Isabella, ruled Spain at the height of its global power — governing the largest empire in world history at its peak (16th-17th centuries), encompassing Spain, the Americas from Mexico to Argentina, the Philippines, Portugal (1580-1640), the Netherlands, Naples, Sicily, and Milan. The 'Spanish Century' under Philip II was history's first truly global empire, with trade connections linking every inhabited continent.\n\nPhilip II (r. 1556-1598) was the most powerful monarch of his age: he governed from his Escorial palace near Madrid ('the wonder of the world') via a vast bureaucracy of paper memoranda, controlled the silver of Potosí (Bolivia) and Zacatecas (Mexico) that funded European warfare for a century, sent the Armada against Protestant England (1588, defeated by weather and Francis Drake), and fought the Eighty Years' War against Dutch independence simultaneously. The annual silver fleets from the Americas transformed the European economy — inflating prices across Europe (the 'Price Revolution') in history's first global commodity shock.\n\nThe dynasty's decline: Philip IV's reign (r. 1621-1665) saw the loss of Portugal (1640), the Catalan Revolt (1640), and a string of military defeats. The 'Spanish Habsburgs' are often cited as a case study in dynastic decline through inbreeding — Charles II ('El Hechizado,' the bewitched), the last Spanish Habsburg (r. 1665-1700), was so physically and cognitively disabled from centuries of consanguineous marriages that he could barely chew; his death without heirs triggered the War of the Spanish Succession (1701-1714) that installed the Bourbon dynasty.",
        "causes": ["1516 Charles I/V inheritance uniting Spain and Habsburg dominions creating greatest empire", "Conquest of the Americas (1519-1570) establishing Spain's global silver empire", "Philip II's Escorial-centered bureaucratic absolutism governing transcontinental empire", "Charles II's inbred disabilities causing dynastic extinction and War of Spanish Succession"],
        "effects": ["Spanish colonial empire governing the Americas for 300 years shaping Latin American civilization", "American silver flood causing the 'Price Revolution' — history's first global commodity inflation", "Armada defeat (1588) accelerating Anglo-Saxon Protestant sea power at Spain's expense", "War of Spanish Succession (1701-1714) installing Bourbon dynasty reshaping European politics"],
        "relationships": [{"entity": "Philip II of Spain", "relationship": "DYNASTY_PEAK_RULER", "note": "Philip II (1556-1598) governed history's first truly global empire from the Escorial"}, {"entity": "Spanish Empire", "relationship": "RULING_DYNASTY_OF", "note": "Spanish Habsburgs built and governed the largest empire in world history at 16th-century peak"}, {"entity": "Charles II of Spain", "relationship": "DYNASTY_ENDED_BY", "note": "Charles II's 1700 death without heirs ended Spanish Habsburg line; his inbreeding is history's clearest dynastic self-destruction"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Spanish House of Habsburg — governing history's first truly global empire, funding European warfare with American silver that reshaped the global economy, and shaping Latin American civilization for 300 years — is one of history's most consequential dynasties; their empire's trade connections created the first economically integrated world system.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    if not data.get("causes"):
        print(f"  SKIP (placeholder): {slug}"); return
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 102 — Class 312 Dynasties X: Extended European Houses")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
