#!/usr/bin/env python3
"""Batch 66 — Class 342 Mosques I (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/342-Class-342"
FILE_PREFIX = "342"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("al-aqsa-mosque", {
        "summary": "Al-Aqsa Mosque is the third holiest site in Islam, located on the Temple Mount (Haram al-Sharif) in Jerusalem, where Muslims believe the Prophet Muhammad was taken during the Night Journey (Isra and Mi'raj) and from where he ascended to heaven. The mosque complex, which encompasses both Al-Aqsa Mosque and the Dome of the Rock, is administered by the Jordanian Waqf and sits directly above Judaism's most sacred site — the Temple Mount — making it the most contested religious site on earth.\n\nThe original Al-Aqsa Mosque was built by the Umayyad Caliph al-Walid I (705-715 CE) on the southern end of the Haram al-Sharif. The mosque has been destroyed by earthquakes (749 CE, 1033 CE) and rebuilt multiple times. Crusaders used it as a palace (1099-1187 CE) before Saladin restored it to Islamic use. The silver dome of Al-Aqsa and the golden Dome of the Rock form the iconic Jerusalem skyline.\n\nAl-Aqsa's political status is among the world's most explosive: Israeli sovereignty over the Temple Mount is accepted internationally, but Jordan administers Muslim sites through the Waqf. Jewish access to pray on the mount is restricted. Palestinian leaders have consistently cited Israeli encroachments on Al-Aqsa as a provocation; the 1969 arson attack by an Australian Christian, the 1996 tunnel opening riots, and Ariel Sharon's 2000 visit that triggered the Second Intifada all centered on Al-Aqsa. Hamas cited Al-Aqsa in its October 7, 2023 attack justification.",
        "causes": ["Prophet Muhammad's Night Journey making the site the third holiest in Islam", "Umayyad Caliph al-Walid I's construction 705-715 CE establishing permanent mosque", "Jerusalem's sacred geography for Judaism, Christianity, and Islam creating inevitable conflict", "Israeli-Palestinian conflict making control of holy sites a flashpoint for violence"],
        "effects": ["Temple Mount/Haram al-Sharif became world's most contested religious site", "Ariel Sharon's 2000 visit triggered Second Palestinian Intifada killing 4,000+", "Hamas cited Al-Aqsa in justification for October 7, 2023 attack on Israel", "Status quo agreement between Israel and Jordan prevents resolution of access disputes"],
        "relationships": [{"entity": "Prophet Muhammad", "relationship": "SACRED_TO", "note": "Site of Prophet's Night Journey and ascension to heaven in Islamic tradition"}, {"entity": "Israeli-Palestinian Conflict", "relationship": "FOCAL_POINT_OF", "note": "Control of Al-Aqsa has triggered multiple rounds of Israeli-Palestinian violence"}, {"entity": "Saladin", "relationship": "RESTORED_BY", "note": "Saladin restored Al-Aqsa to Islamic worship after Crusader occupation 1099-1187"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "Al-Aqsa Mosque's contested sacred status as Islam's third holiest site standing above Judaism's holiest ground makes it the most geopolitically explosive religious site on earth, repeatedly triggering regional conflicts.", "significanceCategory": "world-changing"},
    }),
    ("al-azhar-mosque", {
        "summary": "Al-Azhar Mosque is one of the oldest mosques in Cairo and the founding structure of Al-Azhar University, built by the Fatimid general Jawhar al-Siqilli in 970-972 CE to serve as the first congregational mosque of the new Fatimid capital of Cairo. The mosque and the university that grew around it became inseparable: Al-Azhar is simultaneously a mosque where Friday prayers are held and the world's oldest continuously operating Islamic university.\n\nBuilt in the Fatimid Ismaili tradition initially dedicated to the Prophet's daughter Fatima al-Zahra (from whom it takes its name), the mosque was transformed after Saladin conquered Egypt in 1171 CE and abolished the Fatimid caliphate. Al-Azhar was converted to Sunni Shafi'i practice and gradually developed into the supreme scholarly institution of Sunni Islam. Multiple minarets from different dynasties — Fatimid, Mamluk, and Ottoman — create a layered architectural record of Cairo's history.\n\nThe mosque's interior features a forest of marble columns, gold Quranic inscriptions, and ancient wooden screens from the Fatimid period. The Mamluk sultan Qansuh al-Ghawri's gate tower (1468-96 CE) and the mosque's five minarets — each from a different period — make Al-Azhar's exterior one of Cairo's most complex architectural assemblages. The mosque hosts Friday prayers attended by thousands, Quran recitation competitions, and serves as the ceremonial venue for major Islamic events announced by Al-Azhar's Grand Sheikh.",
        "causes": ["Fatimid Caliphate's founding of Cairo as imperial capital requiring flagship congregational mosque", "General Jawhar al-Siqilli's construction commission 970-972 CE", "Ismaili Fatimid tradition venerating Fatima al-Zahra inspiring the mosque's name", "Cairo's position as Islamic intellectual capital requiring supreme scholarly institution"],
        "effects": ["Al-Azhar University developing around the mosque became Islam's supreme scholarly institution", "Layered architectural additions created visual record of Cairo's dynastic history", "Friday prayers at Al-Azhar attended by thousands maintain living religious function", "Mosque-university model replicated in dozens of Islamic educational institutions worldwide"],
        "relationships": [{"entity": "Al-Azhar University", "relationship": "FOUNDING_STRUCTURE_OF", "note": "University grew from educational circles in the mosque beginning in 975 CE"}, {"entity": "Fatimid Caliphate", "relationship": "BUILT_BY", "note": "General Jawhar built mosque 970-972 CE for the new Fatimid capital"}, {"entity": "Saladin", "relationship": "REFORMED_BY", "note": "Saladin converted mosque from Fatimid Ismaili to Sunni Shafi'i after 1171 conquest"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "Al-Azhar Mosque is the founding structure of the world's oldest Islamic university, and its transformation from Shia Fatimid to Sunni Shafi'i institution mirrors the transformation of Egypt's religious identity over a millennium.", "significanceCategory": "world-changing"},
    }),
    ("blue-mosque", {
        "summary": "The Blue Mosque (Sultan Ahmed Mosque, Sultanahmet Camii) is the most famous mosque in Istanbul, built between 1609 and 1616 CE by Ottoman Sultan Ahmed I. Distinguished by its six minarets — unusual and once controversial, as six minarets had previously been the exclusive prerogative of the Masjid al-Haram in Mecca — the mosque's interior features 20,000 hand-painted İznik tiles in shades of blue and turquoise that give it its popular name.\n\nSultan Ahmed I commissioned the mosque at age 19 to demonstrate Ottoman piety and power, building it directly across from the Byzantine Hagia Sophia. The architect Sedefkâr Mehmed Ağa created a mosque with five main domes, eight secondary domes, and six minarets that dominates Istanbul's skyline. The 20,000 İznik tiles, created in more than 50 different tulip designs, cover the interior walls in one of the greatest displays of Ottoman decorative ceramics.\n\nThe mosque remains an active place of worship and closes to tourists during the five daily prayer times. Its construction is considered the last great mosque of the classical Ottoman period before a long architectural decline. The mosque sits at the center of Sultanahmet Square in Istanbul's historic center, facing Hagia Sophia across an open plaza — a deliberately staged dialogue between Byzantine and Ottoman architectural achievement. Both buildings were designated UNESCO World Heritage sites as part of the Historic Areas of Istanbul (1985).",
        "causes": ["Sultan Ahmed I's desire to demonstrate Ottoman piety following difficult wars with Persia and Austria", "Architectural competition with adjacent Hagia Sophia motivating unprecedented six-minaret design", "Ottoman imperial tradition of sultans building magnificent mosques as legacy monuments", "İznik ceramic tradition reaching its height providing unparalleled decorative materials"],
        "effects": ["Six minarets created controversy with Mecca as only other mosque with six minarets", "20,000 İznik tiles established standard for Ottoman interior decoration", "Blue Mosque became Istanbul's defining image and most-visited tourist destination", "Final great mosque of classical Ottoman period marks beginning of architectural decline"],
        "relationships": [{"entity": "Sultan Ahmed I", "relationship": "COMMISSIONED_BY", "note": "19-year-old Sultan Ahmed I commissioned mosque 1609-1616 CE"}, {"entity": "Hagia Sophia", "relationship": "FACES", "note": "Deliberately positioned across plaza from Hagia Sophia as Ottoman response to Byzantine achievement"}, {"entity": "İznik Tiles", "relationship": "DECORATED_WITH", "note": "20,000 hand-painted İznik tiles in tulip designs create distinctive blue interior"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Blue Mosque's six minarets and 20,000 İznik tiles represent the apex of Ottoman decorative achievement, while its deliberate positioning facing Hagia Sophia embodies Ottoman civilization's self-conscious dialogue with Byzantine heritage.", "significanceCategory": "world-changing"},
    }),
    ("sultan-ahmed-mosque", {
        "summary": "The Sultan Ahmed Mosque and the Blue Mosque refer to the same building — the Sultanahmet Camii in Istanbul. This entity represents the same sacred structure as the blue-mosque entry above. See that entry for the full description of the mosque built by Sultan Ahmed I between 1609-1616 CE, famous for its six minarets, 20,000 İznik tiles, and position facing Hagia Sophia in Istanbul's historic center.",
        "causes": ["Sultan Ahmed I's imperial ambition to surpass Hagia Sophia's architectural presence", "Ottoman tradition of sultanic mosque construction as dynastic legacy", "Six-minaret controversy with Mecca requiring diplomatic resolution", "İznik ceramic tradition providing finest tiles in Ottoman decorative history"],
        "effects": ["Created Istanbul's most recognizable and photographed monument", "Six minarets established new standard for imperial mosque design", "20,000 İznik tiles preserved Ottoman ceramic art at its peak", "Remains active mosque and major tourist site receiving millions annually"],
        "relationships": [{"entity": "Blue Mosque", "relationship": "SAME_AS", "note": "Sultan Ahmed Mosque is the same building as the Blue Mosque (Sultanahmet Camii)"}, {"entity": "Sultan Ahmed I", "relationship": "COMMISSIONED_BY", "note": "Commissioned 1609 CE by Sultan Ahmed I at age 19"}, {"entity": "Istanbul", "relationship": "LOCATED_IN", "note": "Central location in Sultanahmet district defines Istanbul skyline"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Sultan Ahmed Mosque (Blue Mosque) represents the culmination of Ottoman mosque architecture, its six minarets and İznik tile interior establishing the standard for Islamic monumental architecture.", "significanceCategory": "world-changing"},
    }),
    ("umayyad-mosque", {
        "summary": "The Umayyad Mosque (Great Mosque of Damascus) is one of the oldest and most magnificent mosques in the world, built by Umayyad Caliph al-Walid I between 706 and 715 CE in Damascus, Syria. Constructed on the site of a Byzantine cathedral (itself built over a Roman temple to Jupiter), the mosque was the third holiest site in early Islam, the first great monumental mosque of the Islamic world, and the architectural prototype for mosques across North Africa and Spain.\n\nAl-Walid I demolished the Cathedral of Saint John the Baptist — which Christians had shared with Muslims since the Arab conquest of Damascus in 636 CE — and built the Great Mosque incorporating the earlier structure's Byzantine mosaics and columns. The mosque contains the Shrine of John the Baptist, where Muslims believe the head of the prophet Yahya (John the Baptist) is buried, making it sacred to both Islam and Christianity.\n\nThe mosque's three minarets (the oldest surviving Islamic minarets) and its magnificent Byzantine-style mosaic program depicting paradise cities were revolutionary. The treasury dome supported on Roman columns and the Dome of the Eagle over the prayer hall created architectural innovations copied across the Islamic world. The mosque was a model for the Great Mosque of Córdoba, Al-Qarawiyyin in Morocco, and dozens of other mosques. In 2001, Pope John Paul II visited the Umayyad Mosque — the first pope to enter a mosque — praying at the Shrine of John the Baptist.",
        "causes": ["Umayyad Caliph al-Walid I's ambition to create Islam's greatest architectural monument", "Damascus's status as Umayyad capital requiring appropriate grand mosque", "Byzantine cathedral site providing existing sacred geography and building materials", "Islamic world's need for prototype monumental mosque architecture"],
        "effects": ["Three minarets established minaret as defining feature of mosque architecture", "Mosaic program became template for Islamic decorative arts", "Architectural model influenced Great Mosque of Córdoba, Al-Qarawiyyin, and hundreds of others", "John the Baptist shrine created unique Islamic-Christian sacred convergence"],
        "relationships": [{"entity": "Caliph al-Walid I", "relationship": "BUILT_BY", "note": "Umayyad Caliph al-Walid I built mosque 706-715 CE demolishing Byzantine cathedral"}, {"entity": "John the Baptist", "relationship": "HOUSES_SHRINE_OF", "note": "Mosque contains shrine where Muslims believe head of Prophet Yahya is buried"}, {"entity": "Pope John Paul II", "relationship": "VISITED_BY", "note": "First pope to enter a mosque; prayed at John the Baptist shrine in 2001"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Umayyad Mosque was the first monumental Islamic mosque and its architectural innovations — minarets, mosaic programs, dome designs — became the template for Islamic sacred architecture across the world.", "significanceCategory": "world-changing"},
    }),
    ("hassan-ii-mosque", {
        "summary": "The Hassan II Mosque in Casablanca, Morocco is the world's largest mosque outside of Mecca and Medina, completed in 1993 at a cost of $800 million. Designed by French architect Michel Pinseau and built over the Atlantic Ocean on a rocky promontory, it can accommodate 25,000 worshippers inside and 80,000 in the surrounding esplanade. Its 210-meter minaret — the world's tallest — is topped by a laser that points toward Mecca.\n\nKing Hassan II commissioned the mosque in 1980 to create a monument worthy of Morocco's millennium of Islamic civilization and to celebrate his 60th birthday. The project was funded through a national subscription, with Moroccans across all social classes contributing. Over 6,000 Moroccan artisans spent 7 years creating the mosque's hand-carved cedar ceilings, hand-laid marble floors, and intricate zellige tile work, making it the largest commission of traditional Moroccan craftsmanship in the modern era.\n\nThe mosque's most unusual feature is its glass floor over the ocean, fulfilling a Quranic verse about God's throne being built upon water. The retractable roof can open to allow the interior to be flooded with sunlight and ocean breezes. The complex includes a museum of Moroccan heritage, a library, a Quranic school, and ablution facilities for 20,000. Non-Muslim visitors are permitted for guided tours, a notable openness for a major mosque.",
        "causes": ["King Hassan II's commissioning as millennium monument and 60th birthday memorial", "Morocco's desire to demonstrate Islamic civilization's continuing architectural achievement", "National subscription funding model creating Moroccan civic ownership of the project", "Atlantic coastal site fulfilling Quranic verse about God's throne over water"],
        "effects": ["World's tallest minaret (210m) with Mecca-pointing laser became global architectural icon", "6,000 artisans preserved traditional Moroccan craftsmanship on unprecedented scale", "Glass floor over ocean created unique intersection of sacred and natural space", "Non-Muslim visitor access established model for mosque interfaith engagement"],
        "relationships": [{"entity": "King Hassan II", "relationship": "COMMISSIONED_BY", "note": "Moroccan king commissioned mosque in 1980, completed 1993"}, {"entity": "Michel Pinseau", "relationship": "DESIGNED_BY", "note": "French architect designed mosque combining Moroccan and international influences"}, {"entity": "Atlantic Ocean", "relationship": "BUILT_OVER", "note": "Mosque's glass floor and promontory location built directly over the Atlantic"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Hassan II Mosque's 210-meter minaret and glass floor over the Atlantic Ocean represent the most ambitious statement of Islamic architectural achievement in the modern era, combining traditional Moroccan craft with 20th-century engineering.", "significanceCategory": "continental"},
    }),
    ("jama-masjid-delhi", {
        "summary": "The Jama Masjid of Delhi is India's largest mosque, built by Mughal Emperor Shah Jahan between 1644 and 1656 CE at the same time as the Red Fort, creating the heart of his new capital Shahjahanabad (old Delhi). Capable of holding 25,000 worshippers, the mosque with its three marble domes, two 40-meter minarets of red sandstone and marble, and broad courtyard is the supreme achievement of Mughal mosque architecture.\n\nShah Jahan, builder of the Taj Mahal, commissioned the Jama Masjid as the principal Friday mosque of his imperial capital, spending 1 million rupees (an enormous sum) and employing 5,000 workers over 12 years. The mosque stands on a natural rocky hill, elevated above the city on a broad plinth, requiring 36 broad stairs to ascend. Three immense gates open on north, south, and east; the main eastern gate was reserved for the Mughal emperor's exclusive entry.\n\nThe mosque houses several sacred relics: a Quran written by the son of Tamerlane, a sandal of the Prophet Muhammad, and strands of his beard. The sandstone and white marble construction creates the red-white contrast characteristic of Shah Jahan's architecture, echoed in the Taj Mahal and Red Fort. Today the mosque conducts Friday prayers attended by over 25,000 people, Eid prayers filling the entire courtyard with 100,000+ worshippers, and serves as the religious heart of Delhi's Muslim community.",
        "causes": ["Shah Jahan's construction of Shahjahanabad requiring imperial Friday mosque", "Mughal tradition of emperor building mosques as acts of piety and dynastic legacy", "Natural rocky hill providing dramatic elevated position for architectural statement", "Mughal synthesis of Persian, Central Asian, and Indian architectural traditions"],
        "effects": ["Supreme example of Mughal mosque architecture influencing subsequent South Asian mosques", "Friday prayers 25,000 and Eid prayers 100,000+ maintained as living religious tradition", "Relic collection including Prophet's sandal and beard made mosque pilgrimage destination", "Post-partition India's retention of mosque demonstrated secular commitment to Muslim heritage"],
        "relationships": [{"entity": "Shah Jahan", "relationship": "BUILT_BY", "note": "Mughal Emperor built Jama Masjid 1644-1656 as heart of new capital Shahjahanabad"}, {"entity": "Taj Mahal", "relationship": "COMPANION_TO", "note": "Built simultaneously with Taj Mahal by same emperor using similar red sandstone and marble"}, {"entity": "Red Fort", "relationship": "ADJACENT_TO", "note": "Built beside Red Fort to serve as imperial mosque for emperor's adjacent palace"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Jama Masjid Delhi is the supreme achievement of Mughal mosque architecture, built by the same emperor who created the Taj Mahal, and remains the religious heart of Delhi's Muslim community with 25,000+ Friday prayers.", "significanceCategory": "world-changing"},
    }),
    ("dome-of-the-rock", {
        "summary": "The Dome of the Rock (Qubbat al-Sakhra) is an Islamic shrine on the Temple Mount in Jerusalem, built by Umayyad Caliph Abd al-Malik ibn Marwan between 688 and 691 CE. The oldest surviving Islamic architectural monument, its golden dome has dominated Jerusalem's skyline for 1,330 years, making it the world's most recognizable religious building and the defining symbol of Islamic sacred architecture.\n\nThe Dome of the Rock was built over the Foundation Stone (the Sacred Rock), which Jewish tradition holds as the site where Abraham prepared to sacrifice Isaac, where Jacob dreamed of the ladder to heaven, and where the Holy of Holies of Solomon's Temple stood. Islamic tradition identifies it as the site from which Muhammad ascended to heaven during the Isra and Mi'raj. This triple sacred significance — to Judaism, Christianity, and Islam — makes the Foundation Stone the most sacred square meter of earth in Abrahamic religion.\n\nAbd al-Malik's construction was architectural and theological statement: the octagonal plan and Byzantine mosaic program challenged the Church of the Holy Sepulchre's circular plan; the dome's golden exterior (re-gilded with actual gold financed by Jordan's King Hussein in 1993) asserted Islamic splendor; and the Quranic inscriptions inside explicitly addressed Christian theology ('God has no son'). The Byzantine craftsmen who built it created a synthesis of Greco-Roman, Byzantine, and emerging Islamic aesthetics that defined Islamic architecture for centuries.",
        "causes": ["Umayyad Caliph Abd al-Malik's political need for Islamic monument rivaling Byzantine churches", "Sacred Rock's significance to Muhammad's Night Journey and ascension to heaven", "Foundation Stone's existing Jewish and Christian sanctity requiring Islamic claim", "Byzantine craftsmen's skill being harnessed for first great Islamic architectural monument"],
        "effects": ["Oldest surviving Islamic monument defined dome-over-octagon as Islamic architectural form", "Golden dome became defining symbol of Jerusalem in global visual culture", "Quranic inscriptions challenging Christian theology established religious polemics in architecture", "Triple Abrahamic sanctity made Temple Mount the world's most contested sacred site"],
        "relationships": [{"entity": "Caliph Abd al-Malik", "relationship": "BUILT_BY", "note": "Umayyad caliph commissioned Dome of the Rock 688-691 CE"}, {"entity": "Foundation Stone", "relationship": "BUILT_OVER", "note": "Dome protects the Sacred Rock sacred to Judaism, Christianity, and Islam"}, {"entity": "Temple Mount", "relationship": "LOCATED_ON", "note": "Part of the Haram al-Sharif, the Noble Sanctuary in Jerusalem"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Dome of the Rock, built in 691 CE, is Islam's oldest surviving monument and its golden dome has been Jerusalem's defining image for 1,330 years — embodying the Abrahamic religions' most contested sacred geography.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 66 — Class 342 Mosques I")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
