#!/usr/bin/env python3
"""Batch 67 — Class 342 Mosques II (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/342-Class-342"
FILE_PREFIX = "342"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("istiqlal-mosque", {
        "summary": "Istiqlal Mosque in Jakarta, Indonesia is the largest mosque in Southeast Asia and one of the largest in the world, completed in 1978. 'Istiqlal' means 'independence' in Arabic, and the mosque was conceived as Indonesia's monument to both Islam and national independence from Dutch colonialism — its cornerstone was laid by President Sukarno in 1961 on the site of a Dutch colonial fort, symbolically replacing colonial power with Islamic identity.\n\nDesigned by Friedrich Silaban, a Christian architect (a deliberate choice reflecting Indonesia's pluralist national ideology of Pancasila), the mosque was built over 17 years. The central dome is 45 meters in diameter, supported on eight pillars representing the date of Indonesian independence: August 17, 1945. The mosque can accommodate 120,000 worshippers, making Eid al-Fitr and Eid al-Adha prayers spectacular mass gatherings.\n\nIstiqlal faces the Jakarta Cathedral across a plaza in a deliberate architectural symbol of Indonesia's Muslim-Christian tolerance. The two religious buildings share a car park, their congregants exchanging vehicles during major Christian and Muslim festivals. Indonesia, the world's most populous Muslim country (230 million Muslims), chose Pancasila — a state ideology emphasizing unity, humanity, democracy, social justice, and belief in God — over a formally Islamic state, and Istiqlal embodies this synthesis of Islam and pluralist nationalism.",
        "causes": ["Indonesian independence creating need for national mosque as sovereign identity monument", "Sukarno's vision of Islam and nationalism as complementary rather than competing", "Pancasila ideology requiring monument embodying Islamic faith within pluralist framework", "Site of Dutch colonial fort creating powerful symbolic replacement of colonialism with sovereignty"],
        "effects": ["Largest mosque in Southeast Asia became symbol of Indonesian Muslim identity", "Christian architect's design embodied Indonesian pluralist Pancasila ideology", "Shared car park with Jakarta Cathedral created model for interfaith coexistence", "120,000-capacity mosque hosts world's largest single-building prayer gatherings"],
        "relationships": [{"entity": "Sukarno", "relationship": "COMMISSIONED_BY", "note": "President Sukarno laid cornerstone in 1961 as monument to independence and Islam"}, {"entity": "Friedrich Silaban", "relationship": "DESIGNED_BY", "note": "Christian architect designed mosque as symbol of Indonesia's pluralist identity"}, {"entity": "Jakarta Cathedral", "relationship": "FACES", "note": "Mosque and cathedral face each other across shared plaza, symbolizing interfaith tolerance"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Istiqlal Mosque's placement on a colonial fort site, designed by a Christian architect, represents Indonesia's unique synthesis of Islamic faith with pluralist nationalism — the world's most populous Muslim country's model for democracy and diversity.", "significanceCategory": "continental"},
    }),
    ("suleymaniye-mosque", {
        "summary": "The Süleymaniye Mosque in Istanbul is the largest and most magnificent mosque in Istanbul and considered the masterwork of Mimar Sinan, the greatest architect of the Ottoman Empire. Built for Sultan Suleiman the Magnificent between 1550 and 1558 CE, the mosque complex (külliye) includes the mosque, four minarets, libraries, madrasas, caravanserai, hospital, bath, and the tombs of Suleiman and his wife Hürrem Sultan.\n\nMimar Sinan, who also designed the Selimiye Mosque in Edirne (which he considered his masterwork), created the Süleymaniye as a response to Byzantine Hagia Sophia visible from the mosque's terrace. The central dome (53 meters high, 26.5 meters wide) is supported by two semi-domes and four immense pillars, creating the open, luminous interior characteristic of Sinan's mature style. The mosque's hillside position commands views of the Golden Horn and the Bosphorus.\n\nThe mosque complex housed madrasas that became training grounds for the Ottoman scholarly elite, a Quran school, hospital, and caravanserai serving Istanbul's Muslim community. Suleiman the Magnificent's tomb in the mosque's garden, an octagonal structure topped by an elaborate lead dome with a tiled interior, became a pilgrimage site. The Süleymaniye was damaged in an 1766 earthquake and a 1660 fire, restored multiple times, and remains an active mosque today.",
        "causes": ["Suleiman the Magnificent's desire to create legacy mosque equaling Hagia Sophia's scale", "Mimar Sinan's architectural genius combining Byzantine dome techniques with Ottoman innovation", "Ottoman imperial tradition of sultan building a Friday mosque as supreme act of piety", "Istanbul's hilltop geography providing commanding position for architectural monumentality"],
        "effects": ["Established Mimar Sinan as history's greatest pre-modern architect", "Ottoman külliye complex model of mosque plus social services disseminated across Ottoman territories", "Mosque complex educated Ottoman scholarly elite through its multiple madrasas", "Remains one of Istanbul's most-visited landmarks and active Friday mosque"],
        "relationships": [{"entity": "Mimar Sinan", "relationship": "DESIGNED_BY", "note": "Ottoman imperial architect's masterpiece demonstrating response to Hagia Sophia"}, {"entity": "Suleiman the Magnificent", "relationship": "COMMISSIONED_BY", "note": "Sultan commissioned mosque 1550-1558 CE as imperial monument"}, {"entity": "Hagia Sophia", "relationship": "RESPONDS_TO", "note": "Sinan designed mosque partly as Ottoman response to Byzantine architectural achievement"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Süleymaniye Mosque by Mimar Sinan represents the apex of Ottoman architecture — its dome engineering answering Hagia Sophia, its külliye social complex establishing the model for Islamic institutional architecture.", "significanceCategory": "world-changing"},
    }),
    ("badshahi-mosque", {
        "summary": "The Badshahi Mosque (Emperor's Mosque) in Lahore, Pakistan is the world's second-largest mosque and one of the finest examples of Mughal architecture, built by Emperor Aurangzeb between 1671 and 1673 CE. The mosque's dramatic red sandstone construction with white marble inlay, four towering minarets (each 54 meters high), and an octagonal forecourt accommodating 100,000 worshippers creates one of the most visually striking religious monuments in Asia.\n\nAurangzeb, the last of the great Mughal emperors, built the Badshahi Mosque directly facing the Lahore Fort across the Hazuri Bagh garden, creating the most magnificent ceremonial ensemble in Mughal architecture. The prayer hall's marble interior contains black marble pedestals and traces of original mirrorwork; the forecourt is large enough to accommodate 100,000 worshippers during Eid prayers — more than any other mosque at the time of its construction.\n\nThe mosque's history reflects South Asian turmoil: during Sikh rule (1799-1849), Maharaja Ranjit Singh stabled horses in the prayer hall; the British used it as a garrison and powder magazine until 1856. Pakistani independence in 1947 restored the mosque to Muslim use, and extensive restoration through the 1960s-1970s repaired colonial damage. The mosque houses relics including alleged strands of the Prophet Muhammad's beard, his mantle, and sandals, making it a major pilgrimage destination. The Badshahi Mosque is on Pakistan's Rs.10 banknote.",
        "causes": ["Aurangzeb's piety and imperial ambition requiring the grandest mosque in the Mughal Empire", "Lahore Fort's adjacent position creating opportunity for ceremonial palace-mosque ensemble", "Red sandstone availability from Rajasthan providing Mughal building material", "Mughal tradition of imperial mosque construction as demonstration of religious legitimacy"],
        "effects": ["100,000-capacity forecourt created Asia's largest congregational prayer space", "Sikh and British occupation illustrates colonial disruption of Muslim heritage", "Pakistani national icon on banknotes symbolizes Islamic civilization heritage", "Prophet's relics made mosque major pilgrimage destination in South Asia"],
        "relationships": [{"entity": "Aurangzeb", "relationship": "BUILT_BY", "note": "Last great Mughal emperor built mosque 1671-1673 CE"}, {"entity": "Lahore Fort", "relationship": "FACES", "note": "Mosque directly faces the Mughal fort creating ceremonial ensemble across Hazuri Bagh"}, {"entity": "Pakistan", "relationship": "NATIONAL_SYMBOL_OF", "note": "Featured on Rs.10 banknote as symbol of Pakistani Islamic heritage"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Badshahi Mosque is the culminating achievement of Mughal mosque architecture, its 100,000-person capacity forecourt making it Asia's grandest congregational space and a symbol of the Mughal Empire's magnificent final flowering.", "significanceCategory": "continental"},
    }),
    ("wazir-khan-mosque", {
        "summary": "Wazir Khan Mosque in Lahore, Pakistan is considered the most ornately decorated mosque in the Mughal Empire, built between 1634 and 1641 CE by Shah Jahan's governor of Lahore, Hakim Ilm ud-din Ansari (known as Wazir Khan). Unlike the massive scale of imperial mosques, Wazir Khan is intimate, jewel-like — its every surface covered in kashi (faience tile work) depicting geometric and floral patterns in brilliant turquoise, green, yellow, and ultramarine, creating what has been called 'the most beautifully decorated mosque in the world.'\n\nThe mosque's five-arched façade is covered entirely in Lahori faience tile work in arabesque patterns, Quranic verses, and calligraphic inscriptions — more extensive than any other Mughal building. The four tall, slender minarets frame a courtyard whose every surface — entrance gateway, prayer hall exterior, interior walls — is covered in painted stucco (parchin kari) and tile mosaics. The total effect is unlike any other mosque: precious and intricate rather than monumental.\n\nThe mosque remained active but deteriorated significantly during British colonialism, when surrounding bazaar construction narrowed the entrance passage. The 2009 Aga Khan Trust for Culture partnership with the Lahore Conservation Society launched the most comprehensive restoration of a Mughal monument in Pakistan's history, cleaning and repairing the unique faience tile work. Wazir Khan Mosque's detailed tile patterns are now Pakistan's most significant conservation challenge.",
        "causes": ["Wazir Khan's personal piety and desire for legacy as Shah Jahan's Lahore governor", "Lahori faience tile tradition at its peak in early 17th century providing finest craftsmen", "Shah Jahan's architectural reign creating cultural environment demanding highest craftsmanship", "Intimate scale deliberate choice prioritizing decoration over monumental size"],
        "effects": ["Created world's most ornately decorated mosque and finest example of Lahori tile craft", "Kashi tile work tradition preserved at highest level requiring specialized conservation expertise", "2009 Aga Khan Trust restoration became Pakistan's most significant heritage project", "Mosque's intimacy and detail influenced South Asian mosques favoring decoration over scale"],
        "relationships": [{"entity": "Hakim Ilm ud-din Ansari", "relationship": "COMMISSIONED_BY", "note": "Wazir Khan, Shah Jahan's Lahore governor, built mosque 1634-1641 CE"}, {"entity": "Aga Khan Trust for Culture", "relationship": "RESTORED_BY", "note": "2009 partnership launched Pakistan's most comprehensive Mughal monument restoration"}, {"entity": "Shah Jahan", "relationship": "DURING_REIGN_OF", "note": "Built during Shah Jahan's reign representing Mughal architectural culture's decorative peak"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Wazir Khan Mosque's extraordinary faience tile decoration represents the apex of Lahori craft tradition and Mughal architectural decoration, making it the world's most ornate mosque and South Asia's most demanding conservation challenge.", "significanceCategory": "continental"},
    }),
    ("fatih-mosque", {
        "summary": "The Fatih Mosque (Mosque of the Conqueror) in Istanbul is one of the most important mosques in Turkey, built by Sultan Mehmed II (the Conqueror) after his conquest of Constantinople in 1453 CE. The original mosque, completed in 1470 CE, was built on the site of the Byzantine Church of the Holy Apostles — the burial church of Byzantine emperors and second most important church in Christendom after Hagia Sophia — creating a powerful statement of Ottoman succession to Byzantine empire.\n\nMehmed II's choice of the Church of the Holy Apostles site was deliberate: the Apostoleion was where Constantine I and Byzantine emperors were buried, where the relics of Andrew, Luke, and Timothy were kept, and which Constantine himself had built as his mausoleum. By replacing this imperial Christian structure with a mosque, Mehmed symbolically completed the Islamic succession to Roman imperial power. The original mosque was destroyed in the 1766 earthquake; the current building is an 18th-century replacement.\n\nThe Fatih complex (külliye) was among the most ambitious social complexes in Ottoman history: eight madrasas, a hospital, library, caravanserai, public baths, and the mosque formed a comprehensive educational and social welfare system. The complex produced graduates who became the Ottoman religious and intellectual elite. Mehmed II's own tomb, in the mosque garden, is one of Istanbul's most-visited Ottoman imperial shrines.",
        "causes": ["Mehmed II's conquest of Constantinople in 1453 requiring appropriately grand mosque to mark victory", "Byzantine Church of Holy Apostles site chosen to symbolize Ottoman succession to Byzantine empire", "Ottoman külliye tradition requiring comprehensive social complex around imperial mosque", "Istanbul's transformation from Christian to Islamic capital requiring symbolic architectural statements"],
        "effects": ["Replacement of Holy Apostles symbolically completed Islamic succession to Byzantine Roman power", "Eight madrasas became principal Ottoman educational institution training Islamic scholars", "Fatih complex model disseminated Ottoman social welfare and educational architecture", "Mehmed II's tomb created major pilgrimage site in Istanbul"],
        "relationships": [{"entity": "Mehmed II", "relationship": "COMMISSIONED_BY", "note": "Conqueror of Constantinople built mosque on Byzantine imperial church site 1463-1470 CE"}, {"entity": "Church of the Holy Apostles", "relationship": "REPLACED", "note": "Mosque built on site of second most important Byzantine church, burial place of emperors"}, {"entity": "Byzantine Empire", "relationship": "SYMBOLICALLY_SUCCEEDED", "note": "Choice of imperial church site symbolized Ottoman succession to Byzantine power"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Fatih Mosque's construction on the Byzantine imperial church site is one of history's most powerful symbolic acts of imperial succession, marking Constantinople's transformation from Christian to Islamic capital.", "significanceCategory": "world-changing"},
    }),
    ("grand-mosque-of-paris", {
        "summary": "The Grand Mosque of Paris (Grande Mosquée de Paris) is the largest mosque in France and one of the most historically significant mosques in the Western world, inaugurated in 1926 as a gift from the French government to the Muslim soldiers — primarily from Algeria, Morocco, Tunisia, Senegal, and other French colonies — who died fighting for France in World War I. Over 500,000 Muslim soldiers fought for France; approximately 100,000 died.\n\nThe mosque was built in Hispano-Moorish style inspired by the Bou Inania Madrasa in Fez, Morocco, featuring geometric tile work, carved plasterwork, and a 33-meter minaret. The architect Robert Fournez and Algerian artisans created the complex including the mosque, gardens, hammam (Turkish bath), restaurant, and café over seven years (1919-1926). President Gaston Doumergue inaugurated it in the presence of the Sultan of Morocco.\n\nThe Grand Mosque's history reflects Franco-Muslim relations: during World War II occupation, French police records indicate the mosque's rector Si Kaddour Benghabrit issued certificates of Muslim identity to protect hundreds of Jews from deportation — an act of Muslim-Jewish solidarity that inspired the 2011 novel 'The Avenue of the Giants' (A'Ali Si Benghabrit). France's 5-6 million Muslim community — Europe's largest — has grown far beyond what the 1926 mosque symbolically represented, and debates over mosque building permits, Islamic schools, and the hijab reflect ongoing tensions in French-Muslim relations.",
        "causes": ["French government's gratitude and debt to 500,000 Muslim colonial soldiers who died for France in WWI", "French colonial policy requiring gesture of recognition to Muslim subjects", "Hispano-Moorish architectural tradition providing precedent for French mosque design", "Paris's position as global cultural capital requiring grand mosque matching Jewish and Christian institutions"],
        "effects": ["First major mosque in Western Europe established precedent for Islamic architecture in non-Muslim lands", "WWII era Jewish protection by mosque rector created Muslim-Jewish solidarity narrative", "Symbol of France's colonial debt and multicultural heritage", "France's largest mosque became focal point for French Muslim identity debates"],
        "relationships": [{"entity": "World War I", "relationship": "BUILT_TO_HONOR", "note": "Built as French gift to Muslim soldiers who died for France in WWI"}, {"entity": "Si Kaddour Benghabrit", "relationship": "DIRECTED_BY", "note": "Mosque rector who reportedly protected Jews from Nazi deportation during WWII"}, {"entity": "French Algeria", "relationship": "CONNECTED_TO", "note": "Mosque design inspired by Moroccan architecture; North African Muslims its primary community"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Grand Mosque of Paris, built to honor Muslim WWI soldiers who died for France, is the most historically charged mosque in the Western world — embodying colonial history, Muslim sacrifice, WWII resistance, and contemporary debates about Islam in Europe.", "significanceCategory": "world-changing"},
    }),
    ("faisal-mosque", {
        "summary": "The Faisal Mosque in Islamabad, Pakistan is the national mosque of Pakistan and one of the largest mosques in the world, built between 1976 and 1986 with funding from Saudi Arabia's King Faisal bin Abdulaziz, after whom it was named. Designed by Turkish architect Vedat Dalokay, the mosque departs radically from traditional mosque design: instead of a dome, a triangular prayer hall shaped like a desert tent is flanked by four 90-meter minarets — the tallest in the world at the time of construction.\n\nKing Faisal's $120 million donation (massive for the era) as part of Saudi Arabia's global mosque-building program came with the condition of naming the mosque after him. The unconventional tent-shaped design, which Dalokay won in an international competition among 43 designs, was controversial: Turkish modernism replacing traditional Islamic architectural forms. The mosque can accommodate 74,000 worshippers simultaneously, with space for 100,000 in the surrounding grounds.\n\nThe Faisal Mosque's construction coincided with Pakistan's Islamization under President Zia ul-Haq (1977-1988), who promoted Saudi-influenced Wahhabism through mosque construction, Islamic banking, and the Hudood Ordinances. The mosque became a symbol of this transformation of Pakistani Islam toward a more conservative form. The grave of General Zia ul-Haq is located in the mosque complex, cementing the association between the mosque and Pakistani Islamization. The mosque is Islamabad's most recognizable landmark.",
        "causes": ["Saudi Arabia's global mosque-building program extending Wahhabi influence through construction funding", "King Faisal's personal commitment to Islam as unifying force for Muslim world", "Pakistan's 1976 need for national mosque symbolizing Islamic identity in new capital", "Vedat Dalokay's modernist design winning international competition"],
        "effects": ["Saudi mosque-funding model extended Wahhabi Islamic influence to Pakistani religious practice", "Tent-shaped design became controversial model for modern mosque architecture", "Association with Zia ul-Haq's Islamization linked mosque to Pakistan's shift toward conservative Islam", "Most recognizable landmark of Pakistani capital"], 
        "relationships": [{"entity": "King Faisal bin Abdulaziz", "relationship": "FUNDED_BY", "note": "Saudi king donated $120 million; mosque named in his memory"}, {"entity": "Vedat Dalokay", "relationship": "DESIGNED_BY", "note": "Turkish architect's tent-shaped design won international competition"}, {"entity": "Zia ul-Haq", "relationship": "ASSOCIATED_WITH", "note": "Construction coincided with Zia's Islamization; his tomb in mosque complex"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Faisal Mosque represents Saudi Arabia's global mosque-building program that extended Wahhabi influence to South Asia, its construction coinciding with Pakistan's Islamization under Zia ul-Haq in a transformation with lasting regional consequences.", "significanceCategory": "continental"},
    }),
    ("al-azhar-great-mosque", {
        "summary": "The Great Mosque of Al-Azhar is the mosque component of the Al-Azhar complex in Cairo, representing the heart of Islamic learning and worship for over 1,050 years. While Al-Azhar Al-Sharif as an institutional entry covers the university-mosque complex broadly, the Great Mosque specifically refers to the prayer hall and architectural complex built from 970 CE onwards, which combines Fatimid, Mamluk, and Ottoman architectural elements in a palimpsest of Islamic history.\n\nThe original Fatimid mosque of 970-972 CE established the basic structure: a courtyard (sahn) surrounded by arcaded riwaqs on three sides and a five-aisled prayer hall on the qibla side, with the central aisle slightly wider and taller. Subsequent rulers added minarets, madrasas, and porticos, each in the prevailing style of their era — Mamluk minarets with their characteristic stalactite capitals, Ottoman additions after 1517, and modern 20th-century works.\n\nThe mosque's historical significance exceeds its current architectural state. Al-Azhar's Friday prayers are attended by thousands; the Grand Sheikh delivers sermons on matters of global Islamic importance. When Al-Azhar's Grand Sheikh Ahmed el-Tayeb condemned terrorism as un-Islamic, issued guidelines on treatment of religious minorities, or called for 'religious revolution' against extremism, he spoke from the pulpit of this mosque — giving his words authority drawn from 1,050 years of unbroken scholarly tradition. Al-Azhar's library, attached to the mosque, holds 12,000 manuscripts.",
        "causes": ["Fatimid founding of Cairo requiring central congregational mosque for new capital", "Al-Azhar's evolution from mosque to mosque-university requiring expanding architecture", "Mamluk and Ottoman patronage adding architectural layers reflecting dynastic pride", "Al-Azhar's scholarly tradition requiring library and educational spaces adjacent to prayer hall"],
        "effects": ["1,050 years of Friday prayers maintained unbroken scholarly and devotional tradition", "12,000 manuscripts preserved represent one of Islam's most important textual archives", "Grand Sheikh's sermons reach global Muslim audience through accumulated institutional authority", "Architectural accumulation from 970 CE to present created Islamic architectural history in stone"],
        "relationships": [{"entity": "Al-Azhar University", "relationship": "ARCHITECTURAL_CENTER_OF", "note": "The mosque is the physical and spiritual center of the Al-Azhar complex"}, {"entity": "Grand Sheikh of Al-Azhar", "relationship": "PULPIT_OF", "note": "Grand Sheikh's sermons delivered from this mosque carry global Islamic authority"}, {"entity": "Fatimid Caliphate", "relationship": "ORIGINALLY_BUILT_BY", "note": "Fatimid general Jawhar built the original mosque in 970-972 CE"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Great Mosque of Al-Azhar is the world's most continuously significant mosque for Sunni Islam, its 1,050-year unbroken tradition of Friday prayers and scholarly authority making it the spiritual center of 1.8 billion Sunni Muslims.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 67 — Class 342 Mosques II")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
