#!/usr/bin/env python3
"""Batch 120 — Class 343 Temples III: Ancient Sacred Temples (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/343-Class-343"
FILE_PREFIX = "343"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("temple-of-ephesian-artemis", {
        "summary": "The Temple of Artemis at Ephesus (Greek: Ἀρτεμίσιον, Artemision), situated in ancient Ephesus (modern Selçuk, Turkey), was one of the Seven Wonders of the Ancient World — a colossal Ionic temple dedicated to the goddess Artemis that reached its most magnificent form circa 550 BCE under Lydian King Croesus's patronage, measuring approximately 115 meters long by 55 meters wide with 127 columns standing 18 meters high, and making it the largest building in the Greek world for several centuries until surpassed by the Parthenon.\n\nThe Artemision had several iterations. An earlier archaic temple was destroyed by a catastrophic flood circa 600 BCE; the famous version funded by King Croesus (whose wealth was proverbial) was constructed from around 560 BCE and took approximately 120 years to complete, with contributions from artists including the sculptor Scopas. The temple was destroyed by arson on July 21, 356 BCE — the same night, according to the Roman historian Plutarch, that Alexander the Great was born — by Herostratus, who wished to achieve immortality through infamy. Alexander himself later offered to pay for its reconstruction on his campaigns through the region.\n\nA third version was rebuilt after Herostratus's destruction, standing until its plunder by the Gothic peoples in 262 CE and final demolition when Christianity became the Roman Empire's religion in the late 4th century CE. Today only a single reconstructed column marks the site. The Temple of Artemis at Ephesus represents the apex of archaic Greek religious architecture and the ambition of ancient sacred building programs.",
        "causes": ["Artemis cult worship in Ephesus as one of the most important goddess sanctuaries in the ancient Aegean world", "King Croesus of Lydia's patronage (~560 BCE) providing the wealth for the temple's most magnificent construction", "Greek colonization of Ionia making Ephesus a wealthy commercial city capable of sustaining enormous building projects", "Herostratus's 356 BCE arson destroying the original Wonder and creating the legend of fame-through-infamy"],
        "effects": ["Temple's designation as one of Seven Wonders of the Ancient World certifying its status as antiquity's greatest building", "Herostratus's arson creating the concept of 'Herostratic fame' — the idea of achieving immortality through destruction", "Alexander the Great's offer to fund reconstruction demonstrating sacred architecture's diplomatic significance", "Christian destruction in late 4th century CE as paradigmatic case of ancient polytheistic temple obliteration"],
        "relationships": [{"entity": "Seven Wonders of the Ancient World", "relationship": "LISTED_AMONG", "note": "The Temple of Artemis was among antiquity's Seven Wonders for its extraordinary scale and architectural achievement"}, {"entity": "King Croesus", "relationship": "PRINCIPAL_PATRON_OF_MOST_FAMOUS_VERSION", "note": "Croesus's (~560 BCE) patronage funded the massive reconstruction that made the temple a Wonder of the Ancient World"}, {"entity": "Herostratus", "relationship": "DESTROYED_IN_356_BCE_BY", "note": "Herostratus burned the temple for fame — the same night, tradition holds, that Alexander the Great was born"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Temple of Artemis at Ephesus — one of the Seven Wonders, the largest Greek building of its era, destroyed by arson for fame and eventually by Christian religious transformation — is both a supreme achievement of ancient sacred architecture and a paradigmatic tale of human ambition and destruction.", "significanceCategory": "world-changing"},
    }),
    ("temple-of-amenhotep-iv", {
        "summary": "The temples of Amenhotep IV (Akhenaten) — particularly the Aten temples at Karnak (the Gempaaten complex) and at Akhetaten (modern Amarna) — represent the physical manifestation of one of history's most radical religious revolutions: the monotheistic reform of Pharaoh Amenhotep IV, who renamed himself Akhenaten ('Servant of the Aten'), established the worship of the sun disk Aten as Egypt's sole official deity, and built an entirely new capital city (Akhetaten/Amarna) with temples designed to allow the sun's rays to reach the altar through open-air sanctuaries rather than the enclosed dark sanctuaries of traditional Egyptian religion.\n\nAkhenaten's Aten temples were architecturally revolutionary: whereas traditional Egyptian sacred architecture featured progressively darker enclosed spaces culminating in an inner sanctuary accessible only to priests, Akhenaten's temples were open-air — a design where the god (the sun disk itself) could physically reach the altar and offerings. The Gempaaten complex at Karnak, built during the early years of Akhenaten's reign (circa 1353 BCE), was one of the largest temple complexes in Egypt, featuring thousands of sandstone blocks (talatat) carved with images of Aten worship.\n\nAfter Akhenaten's death (circa 1336 BCE), the Aten revolution was reversed: subsequent pharaohs (including Tutankhamun and Horemheb) restored traditional polytheism, dismantled Akhenaten's temples, reused their stones as rubble fill in other building projects, and erased Akhenaten's name from records. The talatat blocks, rediscovered embedded in later structures, have been partially reconstructed and represent the principal physical evidence of Egypt's Aten revolution. Akhenaten's monotheism is considered by some scholars a possible influence on the Abrahamic monotheistic tradition.",
        "causes": ["Akhenaten's religious revolution establishing Aten worship as Egypt's official monotheism (~1353 BCE)", "Open-air architectural design reflecting the theology that the sun disk itself was the god and needed direct access to offerings", "New capital at Akhetaten (Amarna) requiring entirely new temple complex construction", "Political motive to break priestly power of Amun cult by establishing alternative religious center"],
        "effects": ["Architectural innovation of open-air temple sanctuary replacing enclosed dark sanctuary — theologically motivated design", "Post-Akhenaten destruction and memory erasure as one of history's most thorough attempts at damnatio memoriae", "Talatat blocks discovery and partial reconstruction providing evidence for Aten revolution's physical manifestation", "Akhenaten's monotheism scholarly debate about possible influence on Abrahamic religious tradition"],
        "relationships": [{"entity": "Akhenaten", "relationship": "BUILT_BY_AND_EXPRESSING_THEOLOGY_OF", "note": "Akhenaten's Aten revolution produced open-air temple designs where the sun disk itself could reach the altar"}, {"entity": "Aten", "relationship": "DEDICATED_TO", "note": "Akhenaten's temples were dedicated to Aten, the sun disk, Egypt's only officially recognized deity during his reign"}, {"entity": "Amarna Period", "relationship": "PHYSICAL_MONUMENT_OF", "note": "The Aten temples represent the architectural expression of the Amarna religious revolution"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Akhenaten's Aten temples — physically manifesting one of history's most radical monotheistic religious revolutions, featuring architecturally revolutionary open-air sanctuaries, and subsequently destroyed in one of history's most systematic damnatio memoriae campaigns — are among antiquity's most historically significant sacred buildings.", "significanceCategory": "world-changing"},
    }),
    ("mortuary-temple-of-thutmosis-iii", {
        "summary": "The Mortuary Temple of Thutmose III (Henket-Ankh, 'She Who Embraces Life') at Deir el-Bahari in Upper Egypt, constructed by Thutmose III (one of Egypt's greatest warrior pharaohs, who ruled from 1479 to 1425 BCE and expanded Egypt's empire to its greatest territorial extent), is a significant New Kingdom funerary temple complex positioned near the more famous Mortuary Temple of Hatshepsut on the west bank of the Nile at Luxor, and containing important relief carvings and inscriptions commemorating Thutmose III's military campaigns and religious life.\n\nThutmose III's reign saw Egypt expand to its greatest extent — from the fourth cataract of the Nile in Nubia to the Euphrates River in Syria, through seventeen military campaigns. The Battle of Megiddo (1457 BCE), recorded in the temple's annals (the most detailed battle account surviving from ancient Egypt), was the first recorded battle in history with enough detail to reconstruct its strategic context. The Mortuary Temple's Botanical Garden Room (Room of the Seasons), containing painted reliefs of exotic plants and animals brought back from military campaigns in the Levant, represents an early example of what might be called natural history documentation in art.\n\nThe temple has suffered significant damage from antiquity through modern times but remains an important archaeological site. The hieroglyphic inscriptions recording Thutmose III's military campaigns, and particularly the Megiddo annals, are primary historical sources for the period. The temple was partially restored in the 20th century and continues to be studied by Egyptologists.",
        "causes": ["Thutmose III's military expansion to Egypt's greatest territorial extent requiring monumental funerary complex", "New Kingdom funerary temple tradition requiring construction on the Theban west bank", "Egyptian royal propaganda traditions memorializing military campaigns in temple reliefs", "Deir el-Bahari's sacred status as preferred location for New Kingdom mortuary temples"],
        "effects": ["Battle of Megiddo annals providing first detailed battle record in history with reconstructable strategic context", "Botanical Garden Room reliefs providing early natural history documentation of Levantine flora and fauna", "Temple complex contributing to Deir el-Bahari as the most significant cluster of New Kingdom mortuary temples", "Thutmose III's campaign records informing modern understanding of 15th-century BCE Near Eastern geopolitics"],
        "relationships": [{"entity": "Thutmose III", "relationship": "BUILT_AS_FUNERARY_MONUMENT_FOR", "note": "The temple was built for Thutmose III, Egypt's greatest military pharaoh who expanded the empire from Nubia to the Euphrates"}, {"entity": "Battle of Megiddo", "relationship": "FIRST_DETAILED_BATTLE_RECORD_PRESERVED_IN", "note": "The Megiddo annals in the temple are the first battle account in history with enough detail for strategic reconstruction"}, {"entity": "Deir el-Bahari", "relationship": "SITUATED_AT_ALONGSIDE_HATSHEPSUT_TEMPLE", "note": "The temple is at Deir el-Bahari near Hatshepsut's mortuary temple, in the most important cluster of New Kingdom funerary sites"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Mortuary Temple of Thutmose III — containing the first detailed battle record in history (Megiddo annals), early natural history documentation, and commemorating Egypt's greatest military pharaoh at its empire's peak — is a primary historical source for New Kingdom Egypt's most consequential era.", "significanceCategory": "world-changing"},
    }),
    ("temple-of-faunus", {
        "summary": "The Temple of Faunus (Latin: Aedes Faunus), located on the Tiber Island (Insula Tiberina) in Rome, was an ancient Roman temple dedicated to Faunus, the Roman god of the forest, plains, and animals — the equivalent of the Greek god Pan — vowed and built following Roman military victories in the early 2nd century BCE. The Tiber Island location was significant: the island had long been associated with healing (it housed the Temple of Aesculapius, god of medicine) and with the intersection of natural forces through Rome's central river.\n\nFaunus was among Rome's oldest italic deities, predating Greek religious influence. His festival, the Faunalia, was celebrated on February 13 and December 5 — rustic celebrations associated with shepherds, hunters, and agricultural workers rather than urban elites. The Temple of Faunus on the Tiber Island was vowed by the aediles Gnaeus Domitius Ahenobarbus and Gaius Scribonius Curio following their victory in Sardinia (circa 194 BCE), with the funds derived from fines on people who had illegally grazed cattle on public lands — a fitting dedication given Faunus's pastoral associations.\n\nThe temple no longer survives above ground; its existence is known primarily from ancient literary sources including Ovid's Fasti and Roman historians. The Tiber Island today hosts the hospital of Fatebenefratelli, continuing the medical associations of the island since antiquity. The Temple of Faunus represents the persistence of pre-Greek Italic religious tradition within Rome's increasingly Hellenized religious culture.",
        "causes": ["Faunus worship as one of Rome's oldest Italic deities predating Greek religious influence", "Aediles' military victory vow in Sardinia (~194 BCE) providing the temple's founding impetus", "Tiber Island's sacred character as site of multiple Roman religious establishments", "Faunalia festivals maintaining pastoral community traditions in agricultural Rome"],
        "effects": ["Temple establishing Italic Faunus worship on the sacred Tiber Island alongside Greek-influenced Aesculapius", "Faunalia celebrations preserving pre-Hellenistic rustic Roman religious traditions", "Temple's survival in literary sources (Ovid's Fasti) documenting the calendar of Roman religious life", "Tiber Island's continued religious and healing associations from antiquity to modern hospital"],
        "relationships": [{"entity": "Faunus", "relationship": "DEDICATED_TO", "note": "The temple honored Faunus, Rome's ancient Italic god of forest and pastoral life equivalent to Greek Pan"}, {"entity": "Tiber Island", "relationship": "LOCATED_ON", "note": "The temple occupied the Tiber Island, Rome's sacred central river island also home to the Temple of Aesculapius"}, {"entity": "Ovid", "relationship": "DOCUMENTED_IN_FASTI_OF", "note": "Ovid's Fasti is among the primary literary sources describing the Temple of Faunus and its associated festivals"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "The Temple of Faunus — representing pre-Hellenistic Italic religious tradition, establishing pastoral deity worship on Rome's sacred Tiber Island, and documented in Ovid's Fasti — is a modest but historically informative example of Rome's layered religious geography.", "significanceCategory": "local"},
    }),
    ("temple-of-bona-dea", {
        "summary": "The Temple of Bona Dea ('Good Goddess'), located on the Aventine Hill in Rome, was the principal sanctuary of Bona Dea — a Roman goddess of fertility, healing, and women, whose identity was kept deliberately mysterious and whose cult was one of the most strictly observed single-sex religious institutions in Rome, with her annual December festival (held in the house of the current consul or praetor) being one of the most closely guarded religious ceremonies of the Roman world, from which men were absolutely excluded.\n\nBona Dea's cult was remarkable in Roman religion for its strict sex exclusivity: her festival, held in December in the home of a high magistrate's wife, was presided over by the Vestal Virgins and attended only by women of rank. No man was permitted to know what transpired — her name, her image, and her rites were kept secret from men. This made her the center of Rome's most celebrated religious scandal: in 62 BCE, the populist politician Publius Clodius Pulcher disguised himself as a woman to infiltrate the festival held in Julius Caesar's house (presided over by Caesar's wife Pompeia). Caesar subsequently divorced Pompeia, giving the famous reason that 'Caesar's wife must be above suspicion' — a phrase that has passed into common use.\n\nThe Aventine Temple itself was the center of the public cult, where a sacred snake was kept and medical herbs were grown and distributed. The temple was associated with healing, and women (but not men) could visit to receive medicinal herbs. The Bona Dea cult represents one of Roman religion's most distinctive gendered religious spaces.",
        "causes": ["Bona Dea's ancient Italic identity as fertility and healing goddess requiring a permanent Aventine sanctuary", "Women's religious autonomy in Rome finding expression in exclusively female sacred space", "December festival tradition requiring recurring high-status household hosting by wives of senior magistrates", "Medical herb cultivation and distribution establishing temple as women's healing resource"],
        "effects": ["Clodius Pulcher scandal (62 BCE) — infiltrating Bona Dea festival — producing Caesar's famous 'wife above suspicion' divorce", "Exclusively female sacred space as historically significant model of women's autonomous religious institution in ancient Rome", "Medical herb distribution establishing temple as healthcare resource within Rome's religious infrastructure", "Bona Dea's secret rites representing Roman religion's most strictly maintained gendered mystery tradition"],
        "relationships": [{"entity": "Julius Caesar", "relationship": "FESTIVAL_SCANDAL_INVOLVING_HOUSEHOLD_OF", "note": "Clodius's infiltration of the Bona Dea festival in Caesar's house (62 BCE) produced the famous 'Caesar's wife must be above suspicion' divorce"}, {"entity": "Vestal Virgins", "relationship": "CEREMONY_PRESIDED_OVER_BY", "note": "The Vestal Virgins presided over the annual Bona Dea festival, the most exclusively female ceremony in Roman religion"}, {"entity": "Aventine Hill", "relationship": "PRINCIPAL_SANCTUARY_LOCATED_ON", "note": "The Bona Dea temple on the Aventine Hill was the center of her public cult and medicinal herb distribution"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Temple of Bona Dea — center of Rome's most exclusively female religious cult, site of the Clodius scandal producing Caesar's famous 'wife above suspicion' divorce, and representing women's autonomous sacred space in Roman religion — is historically significant for both its gender dimensions and its connection to Republican Rome's most notable religious scandal.", "significanceCategory": "continental"},
    }),
    ("temple-of-clitumnus", {
        "summary": "The Temple of Clitumnus (Italian: Tempio del Clitunno), located near Spoleto in Umbria, Italy, at the source of the Clitunno River, is one of the best-preserved examples of late Roman or early Christian sacred architecture in Italy — a small but exquisite temple dating to the 4th-5th century CE that has been variously interpreted as a Corinthian-columned Roman temple converted to Christian use and as an early Christian church built in Classical style, representing the architectural transition between pagan and Christian sacred space.\n\nThe Clitunno spring and its associated sacred site were famous in antiquity: Pliny the Younger (circa 100 CE) wrote admiringly about the crystal-clear spring and the small temple structures surrounding it. Virgil mentioned the white oxen of Clitumnus — the famous white cattle that grazed near the sacred spring and were considered especially sacred for Roman triumphal sacrifices. The site was a popular tourist destination among educated Romans of the late Republic and early Empire.\n\nThe surviving temple structure, originally thought to be purely Roman, is now dated to approximately the 4th-5th century CE — the period of Christianity's Romanization or Roman culture's Christianization. The structure incorporates both Classical (Corinthian columns, classical entablature) and early Christian elements (an apse, dedication to Saints Illuminata and Lawrence), representing the blending of architectural traditions during Rome's religious transformation. The temple is a UNESCO World Heritage Site component and inspired Romantic-era writers including Byron (who mentioned it in Childe Harold's Pilgrimage) and Goethe.",
        "causes": ["Clitunno spring's ancient sacred character as purity source inspiring Roman religious structures", "4th-5th century CE religious transformation requiring architectural forms bridging pagan and Christian traditions", "White oxen of Clitumnus fame as sacrificial animals for Roman triumphs establishing site's sacred reputation", "Pliny the Younger's literary description preserving the site's classical fame for later ages"],
        "effects": ["Temple serving as architectural evidence of pagan-Christian transition in late Roman sacred building", "Byron's Childe Harold and Goethe's Italian Journey establishing the site as Romantic literary landmark", "UNESCO World Heritage status recognizing its significance as transitional sacred architecture", "The white Chianina cattle breed of Umbria connected historically to the white oxen of Clitumnus tradition"],
        "relationships": [{"entity": "Pliny the Younger", "relationship": "DESCRIBED_IN_LETTERS_OF", "note": "Pliny's admiring description of the Clitunno spring and temple preserved the site's literary reputation into the medieval period"}, {"entity": "Byron", "relationship": "IMMORTALIZED_IN_CHILDE_HAROLD_OF", "note": "Byron mentioned the Temple of Clitumnus in Childe Harold's Pilgrimage, establishing it as a Romantic-era literary landmark"}, {"entity": "Late Antique Sacred Architecture", "relationship": "EXAMPLE_OF_PAGAN-CHRISTIAN_TRANSITION_IN", "note": "The temple's mixed Classical and early Christian elements make it a key example of late Roman sacred architectural transition"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Temple of Clitumnus — combining Classical and early Christian architectural elements at one of antiquity's most admired sacred springs, inspiring Pliny, Virgil, Goethe, and Byron, and representing the architectural transition from pagan to Christian Rome — is a historically and aesthetically significant site of sacred continuity.", "significanceCategory": "continental"},
    }),
    ("temple-of-earth", {
        "summary": "The Temple of Earth (Dìtán, 地坛) in Beijing, also known as the Square Altar of Earth (Fangze Tan), is one of the four major royal sacrifice altars of imperial Beijing — complementing the Temple of Heaven (for sacrifices to Heaven), the Temple of the Sun (for solar sacrifices), and the Temple of the Moon (for lunar sacrifices) — and was the site where the Emperor of China offered annual sacrifices to the Earth God at the Summer Solstice, embodying the cosmological framework of imperial Chinese governance in which the emperor served as the intermediary between Heaven and Earth.\n\nDitan was constructed in 1530 during the Jiajing Emperor's reign in the Ming Dynasty, as part of a systematic restructuring of Beijing's sacrificial altar network. The altar is square (representing Earth in Chinese cosmology, contrasting with Heaven's circular form) and situated to the north of the Imperial City, as the traditional cosmological association placed Earth in the north (Yin direction). The Jiajing Emperor, who also established the Temple of Heaven in its current form, comprehensively reorganized China's state sacrificial system according to classical ritual texts.\n\nThe Summer Solstice ceremony at Ditan was one of the most important state rituals in the Chinese imperial calendar — the Emperor would arrive in formal procession, perform ablutions and fasting, and offer ritual sacrifices to ensure the Earth's continued fertility and the stability of the agricultural foundation of Chinese civilization. Today Ditan Park is a public space in central Beijing and hosts Spring Festival fairs that attract millions of visitors annually, representing the conversion of imperial ritual space into popular public culture.",
        "causes": ["Jiajing Emperor's 1530 restructuring of Beijing's sacrificial altar system during Ming Dynasty ritual reform", "Chinese cosmological framework requiring Earth sacrifices as complement to Heaven sacrifices", "Square altar form expressing Earth's Yin character in Chinese cosmology contrasting with Heaven's circular Yang form", "Summer Solstice sacrifice tradition ensuring agricultural fertility as foundation of Chinese civilization"],
        "effects": ["Ditan completing Beijing's four-altar sacrificial system as physical expression of imperial cosmological governance", "Summer Solstice Earth sacrifices maintaining agricultural ritual calendar of Chinese imperial civilization", "Ditan Park conversion from exclusive imperial ritual space to public park and Spring Festival venue", "Beijing's four altars as UNESCO-recognized architectural expression of Chinese cosmological worldview"],
        "relationships": [{"entity": "Temple of Heaven", "relationship": "COSMOLOGICAL_COMPLEMENT_TO", "note": "Ditan (Earth altar, square, north) complements the Temple of Heaven (circular, south) in Beijing's imperial sacrificial system"}, {"entity": "Jiajing Emperor", "relationship": "BUILT_DURING_RITUAL_RESTRUCTURING_OF", "note": "Jiajing Emperor's 1530 construction organized Beijing's four major sacrifice altars according to classical ritual texts"}, {"entity": "Summer Solstice", "relationship": "ANNUAL_SACRIFICE_TIMING_AT", "note": "The Emperor performed annual Earth sacrifices at Ditan at the Summer Solstice to ensure agricultural fertility"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Temple of Earth (Ditan) — completing Beijing's imperial cosmological sacrifice system, embodying Chinese imperial governance's intermediary role between Heaven and Earth, and now a beloved public park — is a significant monument of Ming Dynasty ritual organization and Chinese cosmological worldview.", "significanceCategory": "world-changing"},
    }),
    ("temple-of-all-religions", {
        "summary": "The Temple of All Religions (Russian: Храм всех религий, Khram vsekh religiy) in Kazan, Russia — an unusual architectural complex built by the private citizen Ildar Khanov (an artist and healer, 1940-2013) beginning in 1992 on his own initiative and funded by his artwork sales and donations — is a unique contemporary sacred building that incorporates architectural elements of 16 world religions (including Islam, Christianity, Judaism, Buddhism, Hinduism, and others) into a single eclectic structure, expressing an individual vision of religious unity and human spiritual harmony.\n\nIldar Khanov's Temple of All Religions is exceptional in the history of sacred architecture: unlike nearly all historic religious buildings (which are built by institutions to serve a specific faith community), Kazan's temple was a personal artistic project by a single individual seeking to create a physical statement of inter-religious harmony. Kazan — where Russian Orthodox Christianity meets Tatar Islamic culture — is geographically appropriate for such a statement; the city has been a meeting point of Slavic and Turkic cultures since the Russian conquest of the Kazan Khanate in 1552.\n\nThe building, still under construction at Khanov's 2013 death and continued by family members, incorporates a Russian Orthodox dome, Islamic crescent and minarets, Buddhist pagoda elements, Star of David windows, Hindu temple forms, and many other architectural religious symbols in a deliberately syncretic composition. It has no active congregation or ritual function — it serves primarily as a cultural and tourism site, and as a statement of one artist's vision of religious coexistence. In a region that has experienced religious conflict, its existence is historically notable.",
        "causes": ["Ildar Khanov's personal religious and artistic vision seeking physical expression of inter-religious harmony", "Kazan's unique position as meeting point of Slavic Orthodox and Tatar Islamic cultures since 1552", "Post-Soviet 1990s spiritual searching in Russia creating space for unconventional religious expression", "Individual artist funding through artwork sales demonstrating private initiative in sacred architecture"],
        "effects": ["Unique architectural statement of religious syncretism incorporating 16 world religions in single structure", "Kazan tourism attraction and cultural landmark representing the city's multi-religious identity", "Khanov's vision of religious coexistence as counter-narrative to religious conflict in post-Soviet space", "Continued post-Khanov construction by family members demonstrating community adoption of individual vision"],
        "relationships": [{"entity": "Ildar Khanov", "relationship": "BUILT_AS_LIFETIME_PROJECT_OF", "note": "Khanov privately funded and personally built the Temple of All Religions from 1992 until his 2013 death through art sales"}, {"entity": "Kazan", "relationship": "LOCATED_IN_AS_SYMBOL_OF_MUSLIM-ORTHODOX_COEXISTENCE", "note": "The temple's Kazan location is significant as the city has been a meeting point of Orthodox and Islamic cultures since 1552"}, {"entity": "Religious Syncretism", "relationship": "ARCHITECTURAL_EXPRESSION_OF", "note": "The temple incorporates architectural elements of 16 world religions in a unique statement of spiritual unity"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "The Temple of All Religions — a unique private architectural statement of inter-religious harmony incorporating 16 faith traditions in post-Soviet Kazan, built by a single artist's personal vision — is a historically distinctive example of individual sacred architecture and religious syncretism at the crossroads of Slavic and Islamic cultures.", "significanceCategory": "local"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 120 — Class 343 Temples III: Ancient Sacred Temples")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
