#!/usr/bin/env python3
"""Batch 60 — Class 341 Cathedrals I (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/341-Class-341"
FILE_PREFIX = "341"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("aachen-cathedral", {
        "summary": "Aachen Cathedral (Dom zu Aachen) in western Germany is the oldest cathedral in Northern Europe and one of the finest examples of Carolingian architecture. Built by Charlemagne between 796 and 805 CE as his palatine chapel, it became the coronation site of German kings for 600 years — 30 kings and 12 queens were crowned here between 936 and 1531 — and remains a UNESCO World Heritage site and a symbol of European Christian civilization.\n\nCharlemagne's Palatine Chapel, the octagonal core of the cathedral, was modeled on the Byzantine Basilica of San Vitale in Ravenna, which Charlemagne visited and admired. The emperor brought Roman columns from Ravenna and Rome to decorate it. Charlemagne's throne — a simple marble chair assembled from quarried Roman stones — stands in the gallery above the nave and was used for coronations from Otto I (936 CE) onward. Charlemagne himself was buried in the chapel after his death in 814 CE.\n\nThe cathedral grew through medieval additions: the Gothic choir hall (14th century) houses the golden Shrine of Charlemagne (1215 CE) containing his bones, making Aachen a major pilgrimage center. The cathedral treasury includes the Cross of Lothair (c. 1000 CE), the Lothar Crystal, and the Persephone Sarcophagus in which Charlemagne was originally buried. As the symbolic center of the Carolingian Empire, Aachen Cathedral represents the fusion of Roman, Byzantine, and Germanic cultural traditions that created medieval European civilization.",
        "causes": ["Charlemagne's determination to create capital rivaling Byzantine Constantinople", "Carolingian Renaissance promoting scholarship, architecture, and the arts", "Christian pilgrimage tradition requiring magnificent sacred architecture", "Byzantine Basilica of San Vitale as direct architectural inspiration"],
        "effects": ["Established Carolingian architectural style influencing medieval German church design", "Became principal coronation site for Holy Roman Emperors 936-1531 CE", "Major pilgrimage destination for Shrine of Charlemagne drawing medieval Christians", "UNESCO World Heritage status established in 1978 as first site in Germany"],
        "relationships": [{"entity": "Charlemagne", "relationship": "BUILT_BY", "note": "Charlemagne ordered construction as his palatine chapel 796-805 CE"}, {"entity": "Holy Roman Empire", "relationship": "CENTRAL_TO", "note": "Coronation site for 30 kings from Otto I (936) to Ferdinand I (1531)"}, {"entity": "San Vitale", "relationship": "MODELED_ON", "note": "Octagonal design inspired by Byzantine San Vitale in Ravenna"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Aachen Cathedral as Charlemagne's throne and coronation chapel was the symbolic center of the Carolingian Empire — the political entity that created medieval European civilization and the precursor of the European Union.", "significanceCategory": "world-changing"},
    }),
    ("notre-dame-de-chartres", {
        "summary": "Chartres Cathedral (Cathédrale Notre-Dame de Chartres) is widely considered the finest example of French High Gothic architecture, built primarily between 1194 and 1220 CE in Chartres, France, 80 kilometers southwest of Paris. A UNESCO World Heritage site, it is renowned for its extraordinary medieval stained glass — 176 windows covering 2,600 square meters — which remain among the best-preserved in the world, including the famous 'Chartres blue' glass.\n\nThe cathedral stands on a site of pre-Christian sacred significance: a well in the crypt venerated since Druidic times, and a small statue of Notre Dame de Sous-Terre (Our Lady Below the Earth) considered miraculous. The Sancta Camisia — the robe allegedly worn by the Virgin Mary when she gave birth to Jesus — was the cathedral's most precious relic, donated by Charlemagne and drawing pilgrims from across Europe. When the previous cathedral burned in 1194, the survival of the relic was seen as a miracle mandating rebuilding.\n\nChartres pioneered Gothic architectural innovations: pointed arches, flying buttresses, ribbed vaulting, and large windows that flooded interiors with light representing divine illumination. The cathedral's two contrasting spires — the south Romanesque (1145) and north Flamboyant Gothic (1513) — have become a symbol of how medieval builders added to structures across centuries. Rodin called Chartres 'the Acropolis of France.'",
        "causes": ["1194 fire destroying previous cathedral triggering urgent rebuilding campaign", "French Gothic architectural revolution of 12th century enabling new structural possibilities", "Miraculous relic of Sancta Camisia making Chartres major pilgrimage destination", "Royal French patronage and donations from across Christendom funding construction"],
        "effects": ["Chartres blue glass set the standard for medieval stained glass aesthetics", "Gothic architectural innovations disseminated to England, Germany, and Iberia", "Pilgrimage trade made Chartres one of medieval Europe's wealthiest market towns", "UNESCO World Heritage designation (1979) preserved 176 medieval windows for posterity"],
        "relationships": [{"entity": "Virgin Mary", "relationship": "DEDICATED_TO", "note": "Cathedral dedicated to Notre-Dame; houses the Sancta Camisia relic"}, {"entity": "Gothic Architecture", "relationship": "EXEMPLIFIES", "note": "Considered the finest example of High Gothic architectural principles"}, {"entity": "French Monarchy", "relationship": "PATRONIZED_BY", "note": "Royal and noble donations funded construction after 1194 fire"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Chartres Cathedral is the supreme achievement of Gothic architecture, its stained glass creating Europe's most complete medieval visual program and its innovations influencing church building across the continent for centuries.", "significanceCategory": "world-changing"},
    }),
    ("cologne-cathedral", {
        "summary": "Cologne Cathedral (Kölner Dom) is Germany's most visited landmark and the largest Gothic church in Northern Europe, taking 632 years to complete — construction began in 1248 CE and finished in 1880, making it the world's longest-running building project. A UNESCO World Heritage site housing the Shrine of the Three Kings (purportedly containing relics of the Biblical Magi), it was medieval Germany's greatest pilgrimage destination.\n\nThe cathedral was begun under Archbishop Konrad von Hochstaden to house the Shrine of the Three Kings, brought from Milan in 1164 by Emperor Frederick Barbarossa. Construction proceeded enthusiastically through the 14th century, reaching the choir (1322) and the south tower base (1437), then stalled for 400 years when medieval funding dried up and cranes stood idle against the unfinished towers. The cathedral's completion in the 1840s-1880s, financed by the Prussian state and enthusiastic German nationalism, was a deliberate symbol of German national unity during the period leading to unification in 1871.\n\nThe cathedral survived WWII with remarkable success — fourteen Allied bombing raids damaged but did not destroy it, and its undamaged spires became a navigation landmark for Allied pilots over the devastated city. The building contains masterpieces including the Gero Cross (c. 970 CE), the oldest surviving monumental crucifix north of the Alps; the Altar of the City Patrons (c. 1440); and the Shrine of the Three Kings in gold and enamel.",
        "causes": ["Shrine of the Three Kings acquisition making Cologne major pilgrimage center", "Archbishop Konrad von Hochstaden's 1248 decision to rebuild on grandest possible scale", "German Gothic architectural ambitions matching French cathedral grandeur", "19th-century German nationalism funding completion as symbol of national unity"],
        "effects": ["Pilgrimage to Three Kings Shrine made Cologne wealthiest German city in Middle Ages", "632-year construction history became symbol of perseverance and German identity", "WWII survival intact while city burned around it created powerful symbolic meaning", "UNESCO designation (1996) recognized both Gothic architecture and urban landscape"],
        "relationships": [{"entity": "Shrine of the Three Kings", "relationship": "HOUSES", "note": "Golden shrine with relics of Biblical Magi brought from Milan in 1164"}, {"entity": "Holy Roman Empire", "relationship": "PATRONIZED_BY", "note": "Imperial patronage drove initial construction and relic acquisition"}, {"entity": "German Unification", "relationship": "SYMBOLIZED", "note": "Completion in 1880 made cathedral symbol of newly unified German nation"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Cologne Cathedral's 632-year construction history made it both a masterpiece of Gothic engineering and a symbol of German national identity, surviving World War II as a beacon amid devastation.", "significanceCategory": "continental"},
    }),
    ("milan-cathedral", {
        "summary": "Milan Cathedral (Duomo di Milano) is the largest Gothic cathedral in Italy and the third largest in the world, built primarily from 1386 to 1965 — a construction period of nearly 600 years. Dedicated to the Nativity of Mary, it sits at the physical and symbolic heart of Milan, and its extraordinary marble façade, 135 spires, and 3,400 statues make it one of the most complex Gothic structures ever built.\n\nConstruction began under Gian Galeazzo Visconti, Duke of Milan, in 1386, with the Duke promising to fund the whole project — which he did not. For centuries, the common Milanese expression 'fabbrica del Duomo' ('cathedral workshop') meant a project that would never be completed, because construction so often halted when funding ran dry. Napoleon Bonaparte ordered the façade completed in 1805 for his coronation as King of Italy in the cathedral.\n\nThe Duomo's roof terrace is a unique architectural feature, accessible since medieval times, allowing visitors to walk among the forest of marble spires and statues. The golden Madonnina statue (4.16 meters tall) on the highest spire (108.5 meters) has been Milan's guardian since 1774; a Milanese law historically prohibited any building from exceeding her height — a rule gradually relaxed as modern skyscrapers rose. The Last Supper by Leonardo da Vinci, painted nearby at Santa Maria delle Grazie, was created during the same era as the Duomo's nave construction.",
        "causes": ["Gian Galeazzo Visconti's ambition to create dynastic monument legitimizing Visconti power", "Milan's economic wealth from textile trade providing resources for massive construction", "Gothic architectural fashion spreading from France through Northern Italy", "Religious devotion and civic competition with other Italian cities driving ambition"],
        "effects": ["Milan Cathedral became defining symbol of Milanese civic and religious identity", "Napoleon's coronation in 1805 connected the Duomo to Italian national memory", "600-year construction project created unmatched complexity of Gothic sculpture and decoration", "Roof terrace tradition established unique relationship between public and Gothic architecture"],
        "relationships": [{"entity": "Gian Galeazzo Visconti", "relationship": "COMMISSIONED_BY", "note": "Visconti Duke of Milan began cathedral in 1386 as dynastic monument"}, {"entity": "Napoleon Bonaparte", "relationship": "COMPLETED_BY", "note": "Napoleon ordered façade completed for his 1805 Italian coronation"}, {"entity": "Virgin Mary", "relationship": "DEDICATED_TO", "note": "Cathedral dedicated to the Nativity of the Blessed Virgin Mary"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Milan Cathedral's nearly 600-year construction history, extraordinary sculptural program, and role in Napoleon's coronation make it both a Gothic masterpiece and a monument to Italian civic and religious identity.", "significanceCategory": "continental"},
    }),
    ("florence-cathedral", {
        "summary": "Florence Cathedral (Cattedrale di Santa Maria del Fiore) is the architectural masterpiece of the Italian Renaissance, dominated by Filippo Brunelleschi's magnificent dome — the largest masonry dome ever built and the first major dome constructed in Europe since Rome's Pantheon. Built between 1296 and 1436, the cathedral and its dome transformed Western architecture by demonstrating that ancient Roman engineering could be revived, launching the Renaissance architectural revolution.\n\nBrunelleschi's dome, constructed between 1420 and 1436 without scaffolding using innovative double-shell construction and herringbone brick laying, solved a structural problem that had stumped Florentine architects for a century: how to span the 42-meter-wide octagonal crossing without wooden centering. He invented new machines to hoist materials and studied the Pantheon's construction methods. The dome, weighing 37,000 tonnes, remained the world's largest masonry dome until the 20th century.\n\nThe Florentine Cathedral complex — including Giotto's Campanile (bell tower, 1334) and the Baptistery with Ghiberti's 'Gates of Paradise' doors (1401-1452) — represents the full flowering of Florentine art and civic pride. Ghiberti beat Brunelleschi in the 1401 Baptistery doors competition; both were instrumental to the Renaissance. The Cathedral Museum (Museo dell'Opera del Duomo) houses Michelangelo's Pietà Bandini and Donatello's Cantoria, making Florence Cathedral the epicenter of Renaissance art.",
        "causes": ["Florentine merchants' civic pride requiring cathedral surpassing rival cities of Siena and Pisa", "Classical revival movement studying Roman architectural techniques", "Medici patronage of arts and architecture as civic and political statement", "Brunelleschi's engineering genius solving problems that blocked previous architects"],
        "effects": ["Brunelleschi's dome launched the architectural Renaissance influencing Europe for centuries", "Double-shell dome construction technique became model for subsequent domes including St. Peter's", "Florence Cathedral established Italy as center of architectural innovation", "Dome engineering innovations created new understanding of structural mechanics"],
        "relationships": [{"entity": "Filippo Brunelleschi", "relationship": "DOME_DESIGNED_BY", "note": "Brunelleschi's innovative dome completed 1436 without scaffolding"}, {"entity": "Medici Family", "relationship": "PATRONIZED_BY", "note": "Medici patronage funded cathedral construction and Florence's artistic culture"}, {"entity": "St. Peter's Basilica", "relationship": "INFLUENCED", "note": "Michelangelo explicitly studied Brunelleschi's dome when designing St. Peter's"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "Florence Cathedral's dome by Brunelleschi launched the architectural Renaissance by reviving Roman engineering, demonstrating that ancient mastery could be surpassed and transforming how European architects understood structure and space.", "significanceCategory": "world-changing"},
    }),
    ("bath-abbey", {
        "summary": "Bath Abbey (Abbey Church of Saint Peter and Saint Paul, Bath) is a magnificent Perpendicular Gothic church in Bath, England, built primarily between 1499 and 1616 CE. Located at the heart of one of England's most historic cities — a Roman spa city reactivated by Georgian tourism — the Abbey is famous for its dramatic fan vaulting, its unusual 'Jacob's ladder' west façade featuring angels climbing and descending to heaven, and its status as the site of England's first recorded coronation.\n\nBath Abbey was founded as a Benedictine monastery in the 7th century. The Norman cathedral that preceded the current building was the scene of Edgar's coronation in 973 CE — the first coronation of all England, establishing a ceremony template used to this day. The current building was begun by Bishop Oliver King in 1499, who reportedly dreamed of angels ascending and descending ladders between heaven and earth — inspiring the distinctive tower carvings. Construction halted during the Dissolution of the Monasteries (1539) leaving the roof unfinished for 75 years.\n\nElizabeth I intervened to have Bath Abbey reroofed after visiting in 1574, observing the building exposed to rain. Queen Victoria funded restoration in the 1860s. The Abbey's Perpendicular Gothic interior creates a 'lantern church' effect — nearly half the wall area is glass from 52 windows. Famous residents interred include the mathematician James Montagu and explorer James Quin, while a famous wall tablet commemorates Beau Nash, Bath's Georgian social arbiter.",
        "causes": ["7th-century Saxon monastery foundation at site of Roman sacred springs", "Edgar's 973 CE coronation establishing Bath's royal and ecclesiastical importance", "Bishop Oliver King's visionary dream inspiring current Perpendicular Gothic design", "Bath's Georgian revival creating restoration funding and new civic prominence"],
        "effects": ["Edgar coronation ceremony template used for all subsequent English and British coronations", "Fan vaulting ceiling represents finest example of Perpendicular Gothic achievement", "Angels and ladders west façade created unique iconographic program", "Bath Abbey's setting in Roman spa city creates unique fusion of Classical and Gothic heritage"],
        "relationships": [{"entity": "Edgar of England", "relationship": "HOSTED_CORONATION_OF", "note": "973 CE coronation of Edgar first coronation of all England"}, {"entity": "Oliver King", "relationship": "REBUILT_BY", "note": "Bishop King began current building in 1499 following his visionary dream"}, {"entity": "Elizabeth I", "relationship": "RESTORED_BY", "note": "Elizabeth funded reroofing after visiting the roofless church in 1574"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Bath Abbey hosted England's first unified coronation in 973 CE, establishing a ceremony template used for every subsequent British monarch, making it foundational to British monarchical tradition despite its modest size.", "significanceCategory": "continental"},
    }),
    ("notre-dame-de-paris", {
        "summary": "Notre-Dame de Paris is the most famous Gothic cathedral in the world, built between 1163 and 1345 CE on the Île de la Cité in the heart of Paris. The cathedral revolutionized Gothic architecture with its innovative flying buttresses, pioneering rose windows, and masterful synthesis of structural engineering with artistic achievement — becoming the definitive model for Gothic cathedrals across France and Europe.\n\nBishop Maurice de Sully began construction in 1163 on a site of previous churches, with King Louis VII attending the foundation ceremony. The early Gothic structure pioneered flying buttresses which, by transferring the thrust of the vaulted ceiling to exterior supports, allowed enormously tall, thin walls filled with stained glass rather than thick stone. The three rose windows — south (1260), north (1250), and west (1200s) — remain among the finest medieval stained glass in existence.\n\nNotre-Dame witnessed pivotal moments in French and European history: the coronation of Henry VI of England as King of France (1431), Napoleon's coronation as Emperor (1804), Masses after French liberation (1944), and the funeral of Charles de Gaulle (1970). Victor Hugo's novel Notre-Dame de Paris (1831) — The Hunchback of Notre-Dame — sparked massive public interest in the threatened building, creating the modern historic preservation movement. The April 2019 fire that destroyed the spire and much of the roof became a global moment of grief, followed by a remarkable €840 million international restoration campaign.",
        "causes": ["Bishop Maurice de Sully's ambition to build Paris a cathedral worthy of its status", "Gothic architectural revolution in engineering enabling unprecedented height and light", "Île de la Cité's position as heart of Paris requiring the grandest possible monument", "Victor Hugo's 1831 novel creating modern architectural heritage preservation movement"],
        "effects": ["Flying buttress innovation became defining element of Gothic architecture worldwide", "Victor Hugo's novel sparked the modern historic preservation movement", "2019 fire and restoration campaign mobilized €840 million international solidarity", "Notre-Dame established Paris as world's cultural capital through its symbolic dominance"],
        "relationships": [{"entity": "Victor Hugo", "relationship": "CELEBRATED_BY", "note": "The Hunchback of Notre-Dame (1831) created global interest and preservation advocacy"}, {"entity": "Napoleon Bonaparte", "relationship": "CORONATION_SITE_FOR", "note": "Napoleon crowned himself Emperor of the French at Notre-Dame in 1804"}, {"entity": "Gothic Architecture", "relationship": "PIONEERED", "note": "Notre-Dame's flying buttresses pioneered Gothic structural engineering"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "Notre-Dame de Paris is the world's most recognized Gothic cathedral, a symbol of Western civilization's spiritual and artistic achievements, and through its 2019 fire and restoration, a living monument to collective human memory and cultural solidarity.", "significanceCategory": "world-changing"},
    }),
    ("york-minster", {
        "summary": "York Minster is the largest Gothic cathedral in Northern Europe and one of the finest examples of Gothic architecture in the world, built in the heart of York, England, between 1220 and 1472 CE. Seat of the Archbishop of York, the second-highest office in the Church of England after Canterbury, it contains the largest collection of medieval stained glass in England including the Great East Window — the world's largest expanse of medieval stained glass.\n\nThe site has been a place of Christian worship since 627 CE when King Edwin of Northumbria was baptized by Bishop Paulinus in a small wooden church that was the first York Minster. The current Gothic building, incorporating earlier Roman, Saxon, and Norman remains in its foundations, took 252 years to complete in stages — the chapter house (1270s), nave (1291-1360), towers, and finally the central tower (1471). The Gothic construction incorporated innovative engineering: the central tower rebuilt in 1470s used a novel 'inverted arch' support system still visible in the undercroft.\n\nYork Minster houses extraordinary medieval treasures: the Great West Window (1338) known as the 'Heart of Yorkshire' for its elegant tracery; Five Sisters Window (1250) the oldest complete window in England; and the Great East Window (1405-1408) covering 18 square meters depicting the beginning and end of all things. A devastating 1984 fire caused by lightning destroyed the south transept roof, prompting a £2.25 million restoration that completed in 1988.",
        "causes": ["Roman York's importance as northern military headquarters requiring ecclesiastical presence", "627 CE baptism of King Edwin making York historically significant for Christianity", "Norman conquest restructuring English church requiring grand northern cathedral", "Archbishop of York's status as second ecclesiastical figure in England justifying grandeur"],
        "effects": ["Great East Window preserved world's largest expanse of medieval stained glass", "York Minster's Gothic architecture influenced subsequent northern English church design", "Cathedral treasury and undercroft house Roman and Viking artifacts from York's 2,000-year history", "1984 fire restoration demonstrated modern conservation techniques and public fundraising"],
        "relationships": [{"entity": "Archbishop of York", "relationship": "SERVES_AS_SEAT_FOR", "note": "Cathedral of the Archbishop of York, second in Church of England hierarchy"}, {"entity": "King Edwin of Northumbria", "relationship": "HISTORICALLY_LINKED_TO", "note": "First baptized at the site in 627 CE in a small wooden church"}, {"entity": "Church of England", "relationship": "PART_OF", "note": "Second most important cathedral in Church of England hierarchy"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "York Minster's 252-year Gothic construction created the largest collection of medieval stained glass in England, establishing the seat of the Archbishop of York and the religious heart of northern England for 1,400 years.", "significanceCategory": "continental"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 60 — Class 341 Cathedrals I")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
