#!/usr/bin/env python3
"""Batch 119 — Mixed: Class 330 Companies VII (4) + Class 364 Studios V (4)"""
import json, os
from datetime import datetime, timezone

FOLDER_330 = "data/appwrite-export/entities/330-Class-330"
FOLDER_364 = "data/appwrite-export/entities/364-Class-364"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("morgan-stanley", {
        "summary": "Morgan Stanley, founded in 1935 in New York by Henry S. Morgan (grandson of J.P. Morgan) and Harold Stanley — who both resigned from J.P. Morgan & Co. in response to the Glass-Steagall Act of 1933 that required the separation of commercial and investment banking — is one of the world's leading global investment banks and financial services companies, managing approximately $5-6 trillion in client assets and consistently ranked among the world's most systemically important financial institutions.\n\nMorgan Stanley's founding was a direct consequence of New Deal financial regulation: the Glass-Steagall Act (Banking Act of 1933), passed in response to the 1929 crash and Depression, prohibited commercial banks from underwriting securities. J.P. Morgan & Co. chose to remain a commercial bank, leading Morgan and Stanley to leave and create a dedicated investment bank. Morgan Stanley's first-day underwriting ($1.1 billion in 1935 dollars) reflected the enormous investment banking demand that Glass-Steagall's separation had created.\n\nThe firm's 20th-century trajectory included major corporate bond and equity underwriting, the growth of its institutional sales and trading divisions, and the 1986 decision to go public. Its 2008 financial crisis near-collapse (liquidity crisis following Lehman Brothers' failure) required Federal Reserve emergency lending and a $9 billion investment by Mitsubishi UFJ Financial Group — transforming it into a bank holding company. Post-crisis Morgan Stanley has refocused on wealth management (the 2009 acquisition of Smith Barney from Citigroup and the 2020 acquisition of E*Trade) making it one of the world's largest wealth management firms alongside its investment banking operations.",
        "causes": ["1935 founding as Glass-Steagall Act response requiring separation of commercial and investment banking", "Henry S. Morgan and Harold Stanley leaving J.P. Morgan & Co. to create dedicated investment bank", "New Deal financial regulation creating enormous unmet demand for pure investment banking services", "Post-WWII American capital markets expansion creating growth context for Morgan Stanley's underwriting"],
        "effects": ["Glass-Steagall Act compliance creating first generation of pure US investment banks (Morgan Stanley, First Boston, etc.)", "2008 financial crisis near-collapse requiring Federal Reserve emergency lending and Mitsubishi UFJ $9 billion investment", "Post-crisis wealth management pivot through Smith Barney (2009) and E*Trade (2020) acquisitions", "Morgan Stanley as one of world's most systemically important financial institutions managing $5-6 trillion in assets"],
        "relationships": [{"entity": "Glass-Steagall Act", "relationship": "CREATED_BY_REGULATORY_SEPARATION_OF", "note": "Morgan Stanley was founded in 1935 directly because Glass-Steagall required separation of commercial and investment banking"}, {"entity": "J.P. Morgan & Co.", "relationship": "SPUN_OFF_FROM_BY_FOUNDERS", "note": "Founders Henry Morgan and Harold Stanley resigned from J.P. Morgan to create the new investment bank"}, {"entity": "2008 Financial Crisis", "relationship": "NEAR-COLLAPSED_DURING", "note": "Morgan Stanley's 2008 liquidity crisis required Federal Reserve emergency lending and Mitsubishi UFJ's $9 billion lifeline"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Morgan Stanley — born from New Deal regulation, managing trillions in global assets, surviving the 2008 financial crisis with Federal Reserve emergency support, and pivoting to become one of the world's largest wealth managers — is one of the most systemically important financial institutions in global capitalism.", "significanceCategory": "world-changing"},
    }, FOLDER_330, "330"),
    ("kia", {
        "summary": "Kia Corporation (KIA Motors, originally Kyungsung Precision Industry, founded 1944 in Seoul), South Korea's second-largest automobile manufacturer after Hyundai (its parent company since 1998), has undergone one of the most remarkable brand transformations in automotive history — from being consistently ranked among the worst-regarded automotive brands in the 1990s and early 2000s to winning major automotive design and quality awards in the 2010s-2020s under chief design officer Peter Schreyer's leadership, including the 2023 World Car of the Year award for the Kia EV6.\n\nKia's origins were in steel tubing and bicycle manufacturing (Kyungsung Precision Industry). It began making motorcycles in 1952, trucks and cars in the 1970s, and entered the US market in 1992. Early American Kia products were plagued by quality and reliability problems; the brand was often cited in 'worst cars' rankings. The 1997 Asian financial crisis bankrupted Kia, leading Hyundai to acquire a controlling stake in 1998 — a rescue that led to the Hyundai-Kia partnership that now operates as the world's third-largest automotive group by volume.\n\nThe transformation came through design: Peter Schreyer (former Volkswagen/Audi designer) was hired in 2006 and introduced the 'tiger nose' grille identity along with cohesive design language that made Kia vehicles visually distinctive. The concurrent quality improvements — Kia and Hyundai now regularly appear at or near the top of JD Power quality surveys — have created one of automotive history's most dramatic brand rehabilitations. The EV6 and Kia's aggressive electric vehicle strategy position it among the leaders of the automotive industry's electric transition.",
        "causes": ["1944 Korean founding as steel tubing and bicycle manufacturer transitioning to vehicle production", "1997 Asian financial crisis bankruptcy leading to Hyundai's acquisition and partnership", "Peter Schreyer's 2006 hiring and tiger-nose design language transforming brand aesthetic identity", "Hyundai-Kia partnership enabling shared R&D investment dramatically improving quality metrics"],
        "effects": ["One of automotive history's most dramatic brand transformations from 'worst cars' to design award winner", "Hyundai-Kia Group emerging as world's third-largest automotive group by volume", "EV6's World Car of the Year 2023 establishing Kia as serious electric vehicle competitor", "Kia's design-led brand strategy becoming model for automotive brand rehabilitation"],
        "relationships": [{"entity": "Hyundai Motor Company", "relationship": "PARENT_COMPANY_SINCE_1998_ACQUISITION", "note": "Hyundai acquired Kia during the 1997 Asian financial crisis and the Hyundai-Kia Group is now the world's third-largest automaker"}, {"entity": "Peter Schreyer", "relationship": "BRAND_TRANSFORMATION_DRIVEN_BY_CHIEF_DESIGN_OFFICER", "note": "Schreyer's 2006 appointment and tiger-nose design language were central to Kia's dramatic quality and aesthetic rehabilitation"}, {"entity": "1997 Asian Financial Crisis", "relationship": "BANKRUPTCY_CONTEXT_OF", "note": "Kia's 1997 bankruptcy during the Asian financial crisis led directly to Hyundai's rescue acquisition"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Kia Corporation — transformed from bankrupt Korean automaker ridiculed for poor quality to World Car of the Year winner and major EV competitor, and demonstrating how design-led strategy can rehabilitate even deeply damaged automotive brands — is one of the most remarkable industrial turnaround stories of the 21st century.", "significanceCategory": "world-changing"},
    }, FOLDER_330, "330"),
    ("bankia", {
        "summary": "Bankia, the Spanish financial institution created in 2011 through the forced merger of seven failing Spanish savings banks (cajas) including Caja Madrid (founded 1702) and Bancaja, became the central figure in Spain's 2012 banking crisis — when its €23.5 billion bailout request (the single largest in Spanish banking history) triggered the European Union's €100 billion Spanish bank bailout package and became the defining case of the European sovereign debt crisis's impact on Spain's financial system.\n\nBankia's creation was itself a product of Spain's property bubble collapse: the cajas (savings banks, traditional non-profit regional banks with political boards) had massively over-lent to Spain's property sector during the 2000s construction boom. When the 2008 financial crisis burst Spain's property bubble — the world's largest property bubble relative to GDP at its peak — the cajas' non-performing real estate loans destroyed their capital bases. The Spanish government forced their merger into Bankia, believing concentration would resolve their problems.\n\nBankia was briefly floated on the stock exchange in 2011, and investors (including many small Spanish retail savers who had been advised by Bankia's own branch staff to convert savings into shares) bought into the IPO — which was subsequently found to have contained materially false financial information. Bankia's 2012 bailout request wiped out shareholders and convertible bondholders, triggering thousands of legal actions. The Bankia scandal became Spain's most significant corporate governance and financial fraud case, with multiple executives including former Bankia CEO Rodrigo Rato (former IMF Managing Director) convicted of financial crimes. Bankia was eventually merged into CaixaBank in 2021.",
        "causes": ["2011 merger of 7 failing cajas (savings banks) as Spanish government attempt to resolve property bubble bad loans", "Spain's 2000s construction boom property bubble causing catastrophic bad loan accumulation in regional cajas", "Bankia's fraudulent 2011 IPO presenting false financial information to small retail investors", "2012 bailout request triggering EU's €100 billion Spanish banking sector rescue"],
        "effects": ["€23.5 billion bailout — Spain's largest ever — triggering EU's €100 billion Spanish banking rescue package", "Retail investor devastation when IPO shares became worthless — thousands of legal actions by small savers", "Rodrigo Rato (former IMF MD) conviction for financial crimes becoming Spain's most prominent banking fraud case", "2021 CaixaBank merger absorbing Bankia and ending its existence as independent institution"],
        "relationships": [{"entity": "Spanish Banking Crisis 2012", "relationship": "CENTRAL_INSTITUTION_OF", "note": "Bankia's €23.5 billion bailout request was the central event of Spain's 2012 banking crisis"}, {"entity": "Rodrigo Rato", "relationship": "CONVICTED_FORMER_CEO_OF", "note": "Former IMF MD Rato served as Bankia CEO before its collapse and was convicted of financial crimes"}, {"entity": "European Sovereign Debt Crisis", "relationship": "SPANISH_BANKING_COMPONENT_OF", "note": "Bankia's bailout triggered the EU's €100 billion Spanish banking rescue as part of the broader European debt crisis"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Bankia — whose collapse triggered Spain's €100 billion EU banking bailout, whose fraudulent IPO destroyed thousands of small investors' savings, and whose former CEO (a former IMF chief) was convicted of financial crimes — is the defining institution of Spain's devastating post-property-bubble banking crisis.", "significanceCategory": "world-changing"},
    }, FOLDER_330, "330"),
    ("grupo-televisa", {
        "summary": "Grupo Televisa, founded in its current form through the 1991 merger of four Mexican television networks and headquartered in Mexico City, is Latin America's largest media company and one of the world's largest Spanish-language content producers — controlling approximately 70% of Mexico's television market at its peak, producing major telenovelas (soap operas) that have been broadcast across Latin America and to Spanish-language audiences in the United States, and exercising media influence over Mexican political life that has been both enabling and distorting of Mexican democracy.\n\nTelevisa's origins trace to the early history of Mexican commercial television in the 1950s, with Emilio Azcárraga Milmo ('El Tigre') building it into a near-monopoly with explicit partnership with the ruling PRI (Institutional Revolutionary Party). This relationship was symbiotic: Televisa gave the PRI highly favorable media coverage for decades, and the PRI gave Televisa protected market position and regulatory advantages. The relationship was so explicit that Azcárraga Milmo famously declared 'I am a soldier of the PRI' in 1994.\n\nTelevisa's telenovela production (over 10,000 hours of Spanish-language content annually at peak) has been Mexico's most significant cultural export — Televisa productions have been broadcast in 79+ countries and helped standardize Spanish across Latin America while also representing Mexican cultural values worldwide. Televisa's 2021 merger with Univision (the largest Spanish-language US broadcaster) creating TelevisaUnivision is one of the largest Spanish-language media transactions in history, reflecting the enormous commercial potential of the Hispanic US market.",
        "causes": ["1991 merger of four Mexican TV networks creating Televisa as Latin America's largest media company", "PRI political partnership giving Televisa protected market dominance through regulatory favoritism", "Telenovela production scale creating Latin America's most significant cultural export industry", "2021 Univision merger reflecting commercial potential of US Hispanic media market"],
        "effects": ["70% Mexican television market control at peak — near-monopoly over Mexico's most important news and entertainment medium", "Telenovela production reaching 79+ countries and shaping Spanish-language cultural identity globally", "PRI media partnership enabling decades of soft-authoritarian political management through favorable coverage", "TelevisaUnivision creation as largest Spanish-language media company targeting 60+ million US Hispanics"],
        "relationships": [{"entity": "PRI", "relationship": "POLITICAL_MEDIA_PARTNER_OF_FOR_DECADES", "note": "Televisa's 'soldier of the PRI' relationship provided the ruling party favorable coverage in exchange for protected monopoly"}, {"entity": "Telenovela", "relationship": "WORLD'S_LARGEST_PRODUCER_OF", "note": "Televisa has been the world's largest telenovela producer with content broadcast in 79+ countries"}, {"entity": "Univision", "relationship": "MERGED_WITH_TO_CREATE_TELEVISAUNIVISION", "note": "Televisa's 2021 Univision merger created TelevisaUnivision, the largest Spanish-language media company globally"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Grupo Televisa — the PRI's media partner in Mexico's soft-authoritarian period, Latin America's largest media company, producer of telenovelas watched in 79+ countries, and creator of TelevisaUnivision targeting 60+ million US Hispanics — is the most consequential media institution in the Spanish-speaking world.", "significanceCategory": "world-changing"},
    }, FOLDER_330, "330"),
    ("bbc-radio", {
        "summary": "BBC Radio, the world's largest and arguably most prestigious radio broadcasting organization — comprising 10 national networks (Radio 1 through 6 Music and several specialist services) and 40+ local/regional stations, broadcasting continuously since the British Broadcasting Company's first transmission on November 14, 1922 — is one of the most historically significant and culturally influential broadcasting institutions in history, inventing modern public service broadcasting, pioneering spoken word and musical programming traditions, and reaching approximately 40 million UK listeners weekly alongside global audiences through BBC World Service Radio.\n\nBBC Radio's founding on November 14, 1922 marked the beginning of regular public broadcasting in Britain; John Reith's appointment as General Manager (later Director-General) and his articulation of the Reithian public service broadcasting mission — 'to inform, educate and entertain' — established the model that has shaped public broadcasting institutions worldwide from ABC Australia to NHK Japan to CBC Canada. Reith's BBC was governed by a Royal Charter (maintained since 1927) keeping it independent of both government control and commercial advertising.\n\nThe cultural legacy of BBC Radio is immense: the BBC Third Programme (1946, later Radio 3) championed classical music and serious arts broadcasting; the BBC Home Service (now Radio 4) has been the world's most significant spoken-word radio network with Today Programme, The Archers (the world's longest-running drama), and BBC Radio drama traditions; Radio 1's launch (1967) in response to pirate radio stations marked the beginning of pop music's integration into public service broadcasting. The BBC World Service reaches approximately 365 million people weekly in 42 languages, making it the world's most-listened-to international broadcaster.",
        "causes": ["November 14 1922 British Broadcasting Company first transmission beginning UK public broadcasting", "John Reith's public service broadcasting mission ('inform, educate, entertain') establishing BBC's institutional philosophy", "1927 Royal Charter converting BBC from company to public corporation with independence from government and advertisers", "BBC World Service founding (1932) expanding to global audiences in multiple languages"],
        "effects": ["Reithian public service broadcasting model adopted by public broadcasters worldwide (ABC, NHK, CBC, etc.)", "Radio 3/Third Programme championing classical music and arts establishing BBC's highbrow cultural mission", "World Service reaching 365 million weekly listeners in 42 languages as world's largest international broadcaster", "Radio 4's The Archers (1951-present) as world's longest-running drama and Today Programme as most influential morning news format"],
        "relationships": [{"entity": "John Reith", "relationship": "MISSION_DEFINED_BY_FIRST_DIRECTOR_GENERAL", "note": "Reith's articulation of public service broadcasting ('inform, educate, entertain') remains BBC Radio's guiding principle"}, {"entity": "BBC World Service", "relationship": "INTERNATIONAL_BROADCASTING_ARM_OF", "note": "BBC World Service reaches 365 million weekly listeners in 42 languages as the world's most listened-to international broadcaster"}, {"entity": "Public Service Broadcasting", "relationship": "MODEL_CREATOR_AND_GLOBAL_STANDARD_SETTER_FOR", "note": "BBC Radio's Reithian model has been adopted and adapted by public broadcasters on every continent"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "BBC Radio — founding modern public service broadcasting in 1922, defining the Reithian mission adopted worldwide, reaching 365 million people through the World Service, and producing Radio 4's The Archers (world's longest-running drama) — is among the most historically significant broadcasting institutions in human history.", "significanceCategory": "world-changing"},
    }, FOLDER_364, "364"),
    ("nbc-news", {
        "summary": "NBC News, the news division of the National Broadcasting Company (NBC), founded as a radio network in 1926 by RCA and operating as a television news organization since NBC's first experimental broadcasts in the late 1930s and regular broadcasts from 1939, is one of the three major American broadcast news organizations (alongside CBS News and ABC News) and historically one of the most significant news institutions in the United States — home to David Brinkley, Chet Huntley, Tom Brokaw, and the pioneering evening news formats that shaped American television journalism.\n\nNBC News' broadcast history includes landmark television journalism: the Huntley-Brinkley Report (1956-1970) was the dominant evening news broadcast of its era, pioneering the co-anchor format; the 1963 Kennedy assassination coverage demonstrated television news's capacity for continuous breaking news; and Tom Brokaw's 1989 Berlin Wall fall coverage became defining television news moments. NBC's Today show (premiering 1952) is the longest-running US morning news program.\n\nIn the cable era, NBC News expanded through MSNBC (launched 1996 in partnership with Microsoft) — which became America's leading left-center cable news network under Rachel Maddow, Brian Williams, and other anchors. NBC Nightly News with Lester Holt continues the legacy of Brinkley, Huntley, and Brokaw. NBC News is now part of NBCUniversal, a Comcast subsidiary. The network's extraordinary archive of American history coverage — from Eisenhower through Obama to Trump — makes it one of the most significant documentary records of 20th-21st century American life.",
        "causes": ["1926 NBC founding by RCA creating first US national radio network", "NBC television news operations beginning in late 1930s and expanding post-WWII", "Huntley-Brinkley Report (1956) pioneering dual-anchor format that became industry standard", "MSNBC launch (1996) expanding NBC News into cable news competition"],
        "effects": ["Huntley-Brinkley Report as dominant evening news program defining television news format for its era", "Today show (1952-present) as longest-running US morning news program setting morning television format", "MSNBC becoming America's leading left-center cable news network in cable era", "NBC News archive providing definitive visual record of American history from Eisenhower to present"],
        "relationships": [{"entity": "Huntley-Brinkley Report", "relationship": "LANDMARK_BROADCAST_OF", "note": "The Huntley-Brinkley Report (1956-1970) was NBC News's dominant evening broadcast and pioneered the co-anchor format"}, {"entity": "MSNBC", "relationship": "CABLE_NEWS_EXTENSION_OF", "note": "MSNBC (launched 1996) became NBC News's cable arm and America's leading left-center cable news network"}, {"entity": "Tom Brokaw", "relationship": "DEFINING_ANCHOR_OF", "note": "Brokaw's 21-year NBC Nightly News tenure and Berlin Wall coverage became defining NBC News moments"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "NBC News — pioneering the co-anchor format, covering Kennedy's assassination, anchoring the Berlin Wall fall, and extending through MSNBC to become America's leading left-center cable network — is one of America's most historically significant broadcast journalism institutions.", "significanceCategory": "world-changing"},
    }, FOLDER_364, "364"),
    ("abc-records", {
        "summary": "ABC Records (American Broadcasting-Paramount Theatres Records), founded in 1955 by ABC and Paramount Theatres as a joint record label venture, was a significant American record label from the late 1950s through the 1970s — home to Ray Charles (who moved from Atlantic Records to ABC in 1959), B.B. King, Jim Croce, Steely Dan, and various other major artists before its 1979 acquisition by MCA Records, which absorbed ABC-Dunhill (its parent by then) into what became Universal Music Group.\n\nABC Records' most historically significant achievement was the 1959 signing of Ray Charles from Atlantic Records — a landmark moment that gave Charles not only a significant signing bonus but, crucially, ownership of his masters and distribution control unprecedented for Black artists of the era. This contractual achievement, negotiated by Charles's manager, made Ray Charles among the first Black American artists to own his recordings — a precedent that would influence subsequent artist-label negotiations. Charles's ABC recordings include the country-crossing Modern Sounds in Country and Western Music (1962, the year's best-selling album), demonstrating the cross-genre appeal that Atlantic had recognized but ABC fully commercial developed.\n\nABC-Dunhill (formed through ABC's acquisition of Dunhill Records) was home to Steely Dan and other major 1970s acts. The label's 1979 MCA acquisition ended its independent existence, though its back catalog (including Ray Charles's defining ABC albums) remains in circulation. ABC Records' significance rests primarily on the Ray Charles master ownership precedent, which influenced the broader evolution of artist rights in the American recording industry.",
        "causes": ["1955 founding as joint ABC/Paramount Theatres venture to enter the growing recorded music market", "1959 Ray Charles signing from Atlantic with master ownership rights — unprecedented for Black artists", "ABC-Dunhill formation through Dunhill Records acquisition expanding into 1970s rock market", "1979 MCA acquisition ending ABC Records as independent entity"],
        "effects": ["Ray Charles's master ownership precedent influencing subsequent artist rights negotiations in the industry", "Modern Sounds in Country and Western Music (1962) as country-crossing commercial breakthrough under ABC", "Steely Dan, Jim Croce at ABC-Dunhill establishing label's 1970s presence", "MCA absorption contributing to the major-label consolidation that eventually created Universal Music Group"],
        "relationships": [{"entity": "Ray Charles", "relationship": "MOST_HISTORICALLY_SIGNIFICANT_ARTIST_SIGNED", "note": "Charles's 1959 ABC signing with master ownership rights was a landmark moment in artist rights history"}, {"entity": "Atlantic Records", "relationship": "COMPETED_FOR_AND_SIGNED_RAY_CHARLES_FROM", "note": "ABC signed Ray Charles from Atlantic in 1959, with the offer of master ownership rights being decisive"}, {"entity": "MCA Records", "relationship": "ACQUIRED_BY_IN_1979", "note": "MCA's 1979 acquisition absorbed ABC-Dunhill into what eventually became Universal Music Group"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "ABC Records — primarily historically significant for Ray Charles's master ownership precedent (1959) influencing artist rights evolution, and for his crossover hit Modern Sounds in Country and Western Music — is a label whose importance is larger than its commercial lifespan suggests due to the Ray Charles rights innovation.", "significanceCategory": "continental"},
    }, FOLDER_364, "364"),
    ("cbs-sports", {
        "summary": "CBS Sports, the sports division of the CBS television network — home since 1956 to major American sports broadcasting including the NFL (current rights to AFC games), NCAA March Madness basketball tournament, Masters golf, PGA Championship, the US Open tennis tournament, and formerly the NBA and MLB — is one of the most historically significant sports broadcasting organizations in American media history, responsible for landmark sports television moments and for shaping the role of sports in American broadcast television culture.\n\nCBS Sports' golden era spanned the 1960s-1980s: the network's NFL coverage with iconic announcers including Phyllis George, Pat Summerall, and John Madden (who became the defining NFL voice through his CBS, Fox, and NBC stints), its early Super Bowl broadcasts, and its famous Wide World of Sports-era sports anthology programming established the cultural template for sports television. The NFL relationship — the most commercially valuable in American sports television — has been CBS's most important partnership across six decades.\n\nCBS Sports' March Madness coverage (since 1982, extended through a deal with Turner) is the network's most emotionally significant annual programming: the NCAA Basketball Tournament's 64-team bracket, Cinderella stories, and 'One Shining Moment' finale have become one of American sports culture's most beloved traditions. CBS's golf coverage including the Masters and PGA Championship maintains the highest production standards in golf broadcasting. CBS Sports Network (cable) and Paramount+ streaming have extended the brand into new distribution channels. Jim Nantz remains one of television sports broadcasting's most respected voices.",
        "causes": ["1956 CBS Sports establishment creating dedicated sports broadcasting division", "NFL broadcasting relationships (from 1950s) establishing sports as major network programming category", "March Madness coverage (1982-present) creating annually most-watched NCAA athletic event", "Masters golf and US Open tennis coverage establishing CBS as prestige sports broadcaster"],
        "effects": ["Super Bowl broadcasts establishing the game as America's most-watched annual television event", "March Madness 'One Shining Moment' tradition creating most beloved annual sports television ritual", "John Madden's CBS tenure establishing the color commentator role model that shaped all subsequent sports broadcasting", "Masters golf broadcast establishing production standards for golf television adopted globally"],
        "relationships": [{"entity": "NFL", "relationship": "PRINCIPAL_SPORTS_BROADCASTING_PARTNER", "note": "CBS's NFL relationship (AFC games) is its most commercially valuable sports property and spans six decades"}, {"entity": "NCAA March Madness", "relationship": "BROADCAST_PARTNER_FOR_SINCE_1982", "note": "CBS's March Madness coverage (with Turner) is the network's most emotionally significant annual sports programming"}, {"entity": "Masters Tournament", "relationship": "PRESTIGE_GOLF_BROADCAST_PARTNER", "note": "CBS's Masters golf coverage is considered the gold standard of golf broadcasting"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "CBS Sports — broadcasting Super Bowls, shaping March Madness culture, housing John Madden's defining color commentary, and maintaining the Masters and NFL as cornerstone American sports television properties — is one of the most historically significant sports broadcasting institutions in American media.", "significanceCategory": "world-changing"},
    }, FOLDER_364, "364"),
]

def enrich_entity(slug, data, folder, prefix):
    fname = os.path.join(folder, f"{prefix}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 119 — Mixed: Class 330 Companies VII (4) + Class 364 Studios V (4)")
    for slug, data, folder, prefix in ENTITIES:
        enrich_entity(slug, data, folder, prefix)
    print("Done.")
