#!/usr/bin/env python3
"""Batch 140 — Class 364 Studios VI: Media & Broadcasting Organizations (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/364-Class-364"
FILE_PREFIX = "364"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("discovery-kids", {
        "summary": "Discovery Kids is a children's television network that has operated as part of Discovery's global media portfolio — originally launched in the United States in 1996 as a dedicated children's programming channel focused on educational, nature, and science content aligned with Discovery Channel's brand values, before being relaunched and reformatted, with the Latin American version of Discovery Kids becoming one of the region's most significant children's media brands.\n\nDiscovery Kids Latin America has been particularly significant in the region's children's media landscape: operating in Spanish and Portuguese across Latin America, it has provided educational children's programming at a scale that traditional local broadcasters struggled to match, covering science, nature, history, and adventure content appropriate for children. The channel has been part of Discovery's broader Latin American media operations alongside other channels like Discovery Channel, Animal Planet, and TLC.\n\nChildren's educational television has significant implications for early childhood development, literacy, and scientific curiosity — the pedagogical approach of channels like Discovery Kids, influenced by educational television research (from Sesame Street and Mr. Rogers' legacy), emphasizes science exploration, problem-solving, and curiosity cultivation rather than purely entertainment. The Latin American version has been a significant player in the region's children's media market alongside competitors like Cartoon Network, Nickelodeon, and Disney Channel.",
        "causes": ["Discovery Communications expanding children's educational programming as extension of its nature and science brand", "1996 launch of US Discovery Kids channel creating educational children's programming aligned with Discovery values", "Latin American market's demand for quality educational children's programming in Spanish and Portuguese", "Discovery's global expansion strategy requiring dedicated children's channels in major regional markets"],
        "effects": ["Discovery Kids Latin America becoming a significant children's media brand in Latin American markets", "Educational science and nature content for children provided at regional scale across Latin America", "Children's educational television pedagogy influenced by Discovery Kids' approach to science and curiosity content", "Latin American children's media market shaped by Discovery Kids alongside Cartoon Network and Nickelodeon competition"],
        "relationships": [{"entity": "Discovery Communications", "relationship": "CHILDREN'S_EDUCATIONAL_BRANCH_OF_GLOBAL_MEDIA_EMPIRE", "note": "Discovery Kids is the children's educational programming extension of Discovery Communications' nature and science brand"}, {"entity": "Latin American Children's Media", "relationship": "SIGNIFICANT_EDUCATIONAL_COMPONENT_OF", "note": "Discovery Kids Latin America has been one of the significant educational children's channels in Latin American television markets"}, {"entity": "Children's Educational Television", "relationship": "SCIENCE_AND_NATURE_FOCUSED_PARTICIPANT_IN_TRADITION_OF", "note": "Discovery Kids continues the tradition of educational children's television pioneered by Sesame Street and Mr. Rogers' Neighborhood"}],
        "historicalSignificance": {"significanceScore": 4, "significanceNarrative": "Discovery Kids — educational children's television extending Discovery's science and nature brand to young audiences globally and in Latin America — is locally significant as a component of children's educational media landscape in Latin America.", "significanceCategory": "local"},
    }),
    ("discovery-records", {
        "summary": "Discovery Records was an independent American record label that specialized in jazz and related genres — operating primarily in the late 20th century as a dedicated jazz label that documented significant jazz artists and performances for the recorded catalog, contributing to the preservation and documentation of American jazz music during a period when many major labels were reducing their jazz commitments in favor of more commercially mainstream genres.\n\nIndependent jazz labels have played a crucial role in jazz music history: from Blue Note (founded 1939), Prestige (1949), Riverside (1953), and Impulse! (1960) in the classic era, through Contemporary, Fantasy, and smaller labels in later decades — independent labels have provided the commercial infrastructure for recording jazz music that the major corporate labels were often unwilling to provide when jazz was not commercially dominant. Discovery Records fits within this tradition of independent labels serving the jazz ecosystem.\n\nThe label's catalog contributes to the documentation of jazz performance in the later 20th century — a period when jazz had moved from popular music to art music, with a smaller but dedicated audience. Independent labels like Discovery Records provided the commercial infrastructure for jazz musicians to record and reach that dedicated audience, serving the important archival and cultural function of documenting American jazz heritage.",
        "causes": ["Independent music label filling the commercial gap for jazz recording when major labels reduced jazz commitments", "Jazz music's transition from popular to art music requiring specialized labels serving dedicated audiences", "American jazz heritage requiring documentation through independent label recording and distribution", "Music industry's commercial mainstream focus requiring independent labels to serve non-mainstream genres"],
        "effects": ["Jazz catalog documentation providing recordings of 20th-century jazz artists for historical archive", "Independent jazz label model supporting musicians not commercially viable for major labels", "Jazz heritage preservation through independent label recording of performances and artists", "Specialized jazz audience served by dedicated labels maintaining the genre's commercial infrastructure"],
        "relationships": [{"entity": "American Jazz Music", "relationship": "INDEPENDENT_LABEL_DOCUMENTING_AND_DISTRIBUTING", "note": "Discovery Records contributed to jazz music documentation and distribution as an independent label serving the jazz community"}, {"entity": "Independent Record Labels", "relationship": "JAZZ-SPECIALIZED_COMPONENT_OF_TRADITION_OF", "note": "Discovery Records is part of the tradition of independent jazz labels (Blue Note, Prestige, Riverside) that have been central to jazz music history"}, {"entity": "Jazz Music Heritage", "relationship": "ARCHIVAL_DOCUMENTATION_CONTRIBUTION_TO", "note": "Independent labels like Discovery Records serve the crucial archival function of documenting jazz performances for historical preservation"}],
        "historicalSignificance": {"significanceScore": 3, "significanceNarrative": "Discovery Records — an independent American jazz label documenting 20th-century jazz performances — is locally significant as a component of the independent jazz label ecosystem that has been central to jazz music's documentation and survival.", "significanceCategory": "local"},
    }),
    ("discovery-travel-living", {
        "summary": "Discovery Travel & Living (also known as Travel & Living or TLC Travel & Living in some markets) was a television channel that operated as part of Discovery Communications' portfolio — focusing on travel, lifestyle, food, design, and home-oriented programming that appealed to aspirational middle-class audiences interested in global travel, gourmet food culture, home decoration, and lifestyle content, eventually evolving into the TLC (The Learning Channel) brand that Discovery reoriented toward lifestyle and reality television content.\n\nDiscovery Communications' channel portfolio strategy evolved significantly from the network's educational origins (Discovery Channel launched 1985 with nature/science focus) to encompass multiple specialized channels targeting different demographic segments: the shift from an educational 'Travel & Living' focus to reality television (The Learning Channel/TLC's reality TV pivot in the 2000s) reflected broader changes in cable television economics as reality television proved dramatically cheaper to produce than documentary and travel content.\n\nTravel and lifestyle programming has played a significant role in shaping aspirational consumer culture, particularly in the globalization era: channels like Discovery Travel & Living and competitor Travel Channel contributed to democratizing visual travel experiences for audiences who couldn't afford to travel extensively, creating cultural familiarity with global destinations while stimulating travel demand. The food and cooking content from such channels has been part of the broader food culture revolution of the 2000s-2010s.",
        "causes": ["Discovery Communications diversifying from science and nature into travel and lifestyle programming for broader audience demographics", "Cable television's multi-channel environment enabling specialized channels targeting specific lifestyle interests", "Growing aspirational middle-class interest in global travel, food culture, and lifestyle content creating market for dedicated channel", "Shift in cable programming economics toward lifestyle and eventually reality television content"],
        "effects": ["Travel and lifestyle programming channel serving Discovery's aspirational middle-class demographic", "Programming evolution from educational travel content toward lifestyle and reality television format", "Contribution to democratizing visual global travel experiences for non-traveling audiences", "Food and cooking programming contributing to broader food culture revolution of the 2000s-2010s"],
        "relationships": [{"entity": "Discovery Communications", "relationship": "LIFESTYLE_AND_TRAVEL_PROGRAMMING_CHANNEL_IN_PORTFOLIO_OF", "note": "Discovery Travel & Living was part of Discovery's cable channel portfolio strategy targeting lifestyle-oriented demographics"}, {"entity": "TLC", "relationship": "EVOLVED_INTO_OR_MERGED_WITH_REALITY_TV_PIVOT_OF", "note": "The channel eventually evolved into or was replaced by TLC's reality television programming model"}, {"entity": "Travel Tourism Industry", "relationship": "TRAVEL_DESIRE_STIMULATED_BY_ASPIRATIONAL_PROGRAMMING_OF", "note": "Travel and lifestyle programming on channels like Discovery Travel & Living contributed to stimulating travel demand and cultural familiarity with destinations"}],
        "historicalSignificance": {"significanceScore": 3, "significanceNarrative": "Discovery Travel & Living — lifestyle and travel programming channel within Discovery's portfolio — is locally significant as part of the cable television lifestyle programming evolution that contributed to food culture and aspirational travel media.", "significanceCategory": "local"},
    }),
    ("interscope-geffen-am", {
        "summary": "Interscope Geffen A&M (IGA) is one of the most powerful label groups in the global music industry — formed from the combination of Interscope Records (founded 1989 by Jimmy Iovine and Ted Field), Geffen Records (founded 1980 by David Geffen), and A&M Records (founded 1962 by Herb Alpert and Jerry Moss) into a single major label group under Universal Music Group, collectively representing an extraordinary catalog including artists across virtually every genre of popular music from the 1960s to the present.\n\nA&M Records was one of the great independent labels before corporate acquisition: Herb Alpert and Jerry Moss built A&M from the Alpert-created Tijuana Brass sound to one of the most artist-friendly major labels, signing artists like Carole King, Janet Jackson, Joe Cocker, Supertramp, and The Police (all of whose foundational catalogs are now in the IGA portfolio). Geffen Records similarly represented David Geffen's artist-focused vision with artists including John Lennon, Joni Mitchell, Nirvana, Guns N' Roses, and Aerosmith.\n\nInterscope itself, under Jimmy Iovine, became one of the defining labels of 1990s-2000s American music — signing Tupac Shakur, Dr. Dre, Eminem, Nine Inch Nails, No Doubt, and Lady Gaga. The combination of these three label legacies under Universal Music Group creates one of the world's most valuable music catalogs, though critics note that the consolidation of the music industry into three major groups (Universal, Sony, Warner) raises significant concerns about music industry concentration and independent artist representation.",
        "causes": ["Universal Music Group's consolidation strategy merging multiple labels into IGA label group", "Music industry consolidation reducing major labels from six to three through mergers and acquisitions", "Interscope's commercial success and Iovine's industry relationships positioning it as the leading IGA label", "A&M and Geffen catalogs' extraordinary value requiring integration into larger corporate structure"],
        "effects": ["IGA catalog representing one of the world's most valuable collections of recorded music across six decades", "Music industry concentration in three major groups (Universal, Sony, Warner) following label consolidation", "Combined catalog including defining artists from 1960s through 2020s across rock, hip-hop, pop, and R&B", "Jimmy Iovine's influence over American popular music through Interscope's centrality to the IGA group"],
        "relationships": [{"entity": "Universal Music Group", "relationship": "MAJOR_LABEL_GROUP_OPERATING_WITHIN_LARGEST_MUSIC_CORPORATION", "note": "IGA is the primary label group within Universal Music Group, the world's largest music company"}, {"entity": "Jimmy Iovine", "relationship": "KEY_ARCHITECT_THROUGH_INTERSCOPE_LEADERSHIP_OF", "note": "Iovine's Interscope became the dominant label in the IGA group, making him one of the music industry's most powerful figures"}, {"entity": "Music Industry Consolidation", "relationship": "MAJOR_EXAMPLE_OF_INDEPENDENT_LABELS_ABSORBED_INTO_CORPORATE", "note": "IGA represents the absorption of formerly independent labels A&M and Geffen into Universal's corporate structure"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Interscope Geffen A&M — combining the catalogs of Interscope, Geffen, and A&M into one of the world's most valuable music archives — is historically significant as a monument to music industry consolidation and the commercial organization of six decades of recorded American popular music.", "significanceCategory": "world-changing"},
    }),
    ("nbc-sports", {
        "summary": "NBC Sports is the sports division of NBCUniversal, one of the United States' most historically significant sports broadcasting entities — with a legacy dating to NBC's earliest television sports programming (1940s-1950s) and encompassing decades of Olympics coverage, NFL football, NBA basketball, Notre Dame football, Premier League soccer, and numerous other major sports properties, establishing NBC as one of the two or three most important networks in American sports television history.\n\nNBC's Olympics broadcasting legacy is particularly remarkable: NBC has broadcast more Olympic Games than any other American network, beginning with the 1964 Tokyo Summer Olympics and continuing through the 2032 deals that extend NBC's Olympic broadcasting rights for decades. The Olympics have been simultaneously NBC's most prestigious and most financially risky programming: the network has lost money on some Olympics while profiting significantly from others, with the rights costs escalating dramatically.\n\nNBC Sports' portfolio has evolved dramatically with the digital transformation: the launch of NBC Sports Network (originally Versus, then NBC Sports Network, then merged into USA Network in 2022) and the Peacock streaming service's acquisition of various sports rights represent the continuing evolution from traditional broadcast to multi-platform sports media. The acquisition of Premier League rights (2013) was transformative for American soccer audiences, dramatically expanding Premier League viewership in the United States from its previously minimal American presence.",
        "causes": ["NBC's early television sports programming establishing the network as a major sports broadcaster from the 1940s-1950s", "Olympic Games broadcasting deals establishing NBC's dominant position in US Olympics coverage", "NFL, NBA, and college football rights defining NBC Sports' major American sports portfolio", "Digital transformation requiring NBC Sports to develop streaming and multi-platform sports media strategy"],
        "effects": ["NBC Sports' Olympics coverage making it the dominant American Olympic broadcaster for 70+ years", "Premier League rights (2013) dramatically expanding American soccer audiences and Premier League's US market", "NBC Sports Network's eventual merger into USA Network representing cable sports television's consolidation", "Peacock streaming service's sports rights acquisition defining NBC Sports' multi-platform future"],
        "relationships": [{"entity": "Olympic Games", "relationship": "PRIMARY_US_BROADCASTER_OF_SINCE_1964_THROUGH_2032_DEALS", "note": "NBC Sports has been the dominant US Olympics broadcaster, holding rights from 1964 through deals extending to 2032"}, {"entity": "English Premier League", "relationship": "US_BROADCASTING_RIGHTS_HOLDER_DRAMATICALLY_EXPANDING_AMERICAN_AUDIENCE_FOR", "note": "NBC Sports' 2013 Premier League rights deal dramatically expanded the league's American viewership"}, {"entity": "American Sports Television", "relationship": "ONE_OF_THE_THREE_MOST_HISTORICALLY_SIGNIFICANT_NETWORKS_IN", "note": "NBC Sports is one of the most important networks in American sports television history alongside ESPN and CBS Sports"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "NBC Sports — dominant US Olympics broadcaster for 70+ years, transformative Premier League rights holder, historic NFL and NBA broadcaster — is historically significant as one of the defining institutions of American sports television culture.", "significanceCategory": "world-changing"},
    }),
    ("nbcuniversal-entertainment-japan-llc", {
        "summary": "NBCUniversal Entertainment Japan LLC is the Japanese subsidiary of NBCUniversal — the American media conglomerate formed by the merger of NBC and Universal Studios and now owned by Comcast — responsible for distribution, marketing, and local operations in Japan, one of the world's largest media and entertainment markets, coordinating the introduction of Universal film releases, NBCUniversal television content, and Universal theme park activities to Japanese audiences and corporate partners.\n\nJapan is one of the world's most sophisticated and valuable media markets, with unique characteristics that require dedicated local operations: Japanese audiences consume both dubbed and subtitled foreign content (unlike many markets where dubbing dominates), have particularly strong cinema-going traditions, represent major consumers of franchise properties (Star Wars, Harry Potter, Jurassic Park, Fast & Furious all have extraordinary Japanese fan bases), and support multiple major theme parks including Universal Studios Japan (USJ) in Osaka, which became one of Asia's most visited theme parks after opening in 2001.\n\nUniversal Studios Japan's extraordinary success — particularly after the introduction of The Wizarding World of Harry Potter (2014) transformed attendance — makes NBCUniversal Entertainment Japan's local operations particularly significant. USJ became Japan's most visited theme park in some years, overtaking Tokyo Disneyland and Disneysea in visitor counts. The Japanese entertainment market's value and sophistication make the local subsidiary an important strategic operation for NBCUniversal's global business.",
        "causes": ["NBCUniversal's global expansion requiring dedicated Japanese subsidiary for Japan's sophisticated media market", "Universal Studios Japan's 2001 opening creating need for coordinated local entertainment operations", "Japan's unique media market characteristics requiring localized distribution, dubbing/subtitling, and marketing strategies", "Japanese consumer enthusiasm for NBCUniversal franchises (Universal films, Harry Potter, Jurassic Park) requiring local brand management"],
        "effects": ["Universal Studios Japan's extraordinary success partly supported by NBCUniversal Entertainment Japan's operations", "Harry Potter attraction at USJ (2014) transforming the park's attendance and competitive position in Japan", "NBCUniversal's film and television content successfully distributed and marketed in Japan's large media market", "Japan operations contributing to NBCUniversal's Asia Pacific regional strategy and revenue"],
        "relationships": [{"entity": "NBCUniversal", "relationship": "JAPANESE_SUBSIDIARY_OF_AMERICAN_MEDIA_CONGLOMERATE", "note": "NBCUniversal Entertainment Japan is the dedicated Japanese operations subsidiary of NBCUniversal/Comcast"}, {"entity": "Universal Studios Japan", "relationship": "SUPPORTS_OPERATIONS_OF_OSAKA_THEME_PARK", "note": "The Japanese subsidiary coordinates with and supports Universal Studios Japan's Osaka theme park operations"}, {"entity": "Japanese Entertainment Market", "relationship": "NBCUNIVERSAL_CONTENT_DISTRIBUTED_AND_MANAGED_IN", "note": "The subsidiary manages NBCUniversal's film, TV, and brand operations in Japan's large sophisticated entertainment market"}],
        "historicalSignificance": {"significanceScore": 4, "significanceNarrative": "NBCUniversal Entertainment Japan — managing Universal's film, TV, and theme park operations in one of the world's most sophisticated media markets — is locally significant as the local operations hub for one of entertainment's largest conglomerates in the crucial Japanese market.", "significanceCategory": "local"},
    }),
    ("abc-clio", {
        "summary": "ABC-CLIO is an American academic and reference publisher — founded in 1953 by Eric Boehm as the American Bibliographical Center-CLIO, Inc. — specializing in history, social studies, and humanities reference works for academic and educational institutions, and representing one of the most significant American academic publishers of encyclopedias, databases, and reference resources for libraries and educational institutions.\n\nABC-CLIO's publication portfolio includes major reference works widely used in American academic libraries: the America: History and Life database (comprehensive bibliographical index of articles on American and Canadian history), Historical Abstracts (similar index for world history), and numerous encyclopedias covering world history, political systems, and social issues. These databases have been standard research tools in academic libraries for decades, serving historians, students, and researchers with bibliographical access to scholarly literature.\n\nThe transition from print to digital reference publishing has been a major challenge and transformation for publishers like ABC-CLIO: their traditional business model of selling expensive multi-volume print encyclopedias to libraries has been disrupted by internet reference resources, but the databases like America: History and Life and Historical Abstracts have maintained value as curated scholarly bibliographic tools. ABC-CLIO (merged with Greenwood, Praeger, and Heinemann into ABC-CLIO's expanded portfolio) is now owned by private equity and navigates the challenging academic publishing market.",
        "causes": ["Eric Boehm's 1953 founding to provide bibliographical services for history and social science researchers", "Academic libraries' need for comprehensive research databases indexing historical and social science scholarship", "Reference publishing's commercial opportunity in the growing American higher education market of the mid-20th century", "Historians' and students' need for systematic bibliographical access to scholarly literature"],
        "effects": ["America: History and Life and Historical Abstracts becoming standard academic research databases in US libraries", "ABC-CLIO encyclopedias and reference works widely adopted in school and academic library collections", "Academic reference publishing model challenged by internet reference resources and digital disruption", "ABC-CLIO's expansion through acquisitions (Greenwood, Praeger) creating broader academic humanities publisher"],
        "relationships": [{"entity": "Academic Reference Publishing", "relationship": "MAJOR_AMERICAN_PARTICIPANT_IN_HUMANITIES_AND_HISTORY", "note": "ABC-CLIO is one of the most significant American publishers of academic reference works in history and social studies"}, {"entity": "America History and Life Database", "relationship": "PUBLISHER_AND_MAINTAINER_OF_STANDARD_ACADEMIC_DATABASE", "note": "ABC-CLIO's America: History and Life database is a standard bibliographic research tool for historians"}, {"entity": "American Academic Libraries", "relationship": "PRIMARY_CUSTOMER_BASE_FOR_REFERENCE_DATABASES_AND_ENCYCLOPEDIAS", "note": "US academic and school libraries are the primary market for ABC-CLIO's reference publications and databases"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "ABC-CLIO — academic publisher of history and social studies reference works and databases serving American educational institutions for 70+ years — is historically significant as a major infrastructure provider for historical scholarship and academic research.", "significanceCategory": "continental"},
    }),
    ("abc-color", {
        "summary": "ABC Color (also known as Diario ABC Color) is Paraguay's most widely read and influential newspaper — founded in 1967 and owned by the Zuccolillo family — representing the most significant independent press institution in Paraguay, a country that only ended 35 years of General Alfredo Stroessner's dictatorship in 1989 and has had a challenging relationship with press freedom and democratic governance. ABC Color has played a significant role in Paraguayan journalism and political life.\n\nParaguay's media landscape reflects the country's difficult democratic history: Stroessner's 1954-1989 dictatorship was one of South America's longest single-person authoritarian rules, and press freedom was severely constrained throughout. ABC Color was founded in 1967 during the Stroessner era and faced significant government pressure, including forced closure from 1984 to 1989 by the Stroessner government — a period during which the newspaper's critical journalism was suppressed. The newspaper's reopening coincided with the 1989 coup that ended Stroessner's rule.\n\nABC Color's post-Stroessner role as Paraguay's leading newspaper has involved significant influence over Paraguayan public opinion and political coverage, including coverage of the Colorado Party's continuing political dominance (the Colorado Party ruled Paraguay without interruption from 1947 to 2008, an extraordinary 61-year single-party dominance), and the country's ongoing governance challenges including land inequality (Paraguay has one of the world's most unequal land distributions), corruption, and institutional development.",
        "causes": ["1967 Zuccolillo family founding creating Paraguay's major independent newspaper during the Stroessner dictatorship", "Stroessner's 1984-1989 forced closure of ABC Color as punishment for critical journalism", "Paraguay's 1989 democratic transition after Stroessner's overthrow allowing ABC Color's reopening and expansion", "Paraguayan media market's need for independent quality journalism in a country with weak democratic institutions"],
        "effects": ["ABC Color as Paraguay's most widely read and influential newspaper shaping public opinion and political discourse", "Newspaper's journalism documenting Colorado Party dominance and Paraguayan political life for decades", "ABC Color's 1984-1989 forced closure as documented case of Latin American press freedom violation", "Independent Paraguayan journalism serving crucial accountability function in country with corruption challenges"],
        "relationships": [{"entity": "Alfredo Stroessner", "relationship": "NEWSPAPER_FORCED_CLOSED_BY_DICTATORSHIP_OF", "note": "Stroessner's government forcibly closed ABC Color from 1984-1989 as punishment for critical journalism"}, {"entity": "Paraguay", "relationship": "MOST_INFLUENTIAL_AND_WIDELY_READ_NEWSPAPER_IN", "note": "ABC Color is Paraguay's most significant independent newspaper, shaping political discourse and public opinion"}, {"entity": "Paraguayan Democracy", "relationship": "PRESS_FREEDOM_INSTITUTION_CRITICAL_TO_ACCOUNTABILITY_IN_FRAGILE", "note": "ABC Color serves as an independent accountability institution in Paraguay's challenging post-Stroessner democratic development"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "ABC Color Paraguay — forced closed by Stroessner's dictatorship, reopening with Paraguay's democratization, serving as the country's most influential independent newspaper — is historically significant as a monument to press freedom's role in Latin American democratic transitions.", "significanceCategory": "continental"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 140 — Class 364 Studios VI: Media & Broadcasting Organizations")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
