#!/usr/bin/env python3
"""Batch 133 — Class 381 Universities VII: California State Universities (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/381-Class-381"
FILE_PREFIX = "381"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("california-polytechnic-state-university", {
        "summary": "California Polytechnic State University (Cal Poly San Luis Obispo, Cal Poly SLO, founded 1901) is a public polytechnic university in San Luis Obispo, California, part of the California State University system — and one of America's premier polytechnic universities, known for its 'learn by doing' philosophy, consistently ranked among the top public universities in the western United States, and producing graduates who have disproportionate impact in engineering, architecture, agriculture, and technology sectors.\n\nCal Poly San Luis Obispo's founding in 1901 as a polytechnic school reflected the late 19th-century American conviction that practical technical and agricultural education was as important as classical liberal arts for national development. The California Polytechnic School was established to provide hands-on agricultural and mechanical education at a time when California's economy was dominated by farming and natural resource industries. This practical educational philosophy was institutionalized in Cal Poly's motto 'Discere Faciendo' (learn by doing).\n\nCal Poly's modern reputation is exceptional among public universities: consistently ranked first or second among western regional comprehensive universities (U.S. News), its engineering, architecture, and agriculture programs are among the nation's best. The university's distinctive model — combining professional education with genuine hands-on learning through student farms, engineering projects, and studio-based architecture programs — has made it highly sought-after with admission rates that rival selective private universities. Its graduates' success in Silicon Valley and major technology companies has further enhanced its reputation.",
        "causes": ["1901 California Polytechnic School founding reflecting late 19th-century practical agricultural and mechanical education philosophy", "California's agricultural and industrial economy requiring technically trained workers produced by hands-on polytechnic education", "California State University system expansion requiring polytechnic institution for technical and professional programs", "'Learn by doing' philosophy institutionalized as distinctive educational approach differentiating Cal Poly from liberal arts universities"],
        "effects": ["Premier polytechnic education producing graduates with outsized impact in engineering, technology, and architecture", "Silicon Valley technology sector benefiting from Cal Poly engineering graduates' practical education", "Highly competitive admissions making the public polytechnic effectively selective comparable to private universities", "Model of hands-on polytechnic education influencing American technical higher education approaches"],
        "relationships": [{"entity": "California State University System", "relationship": "PREMIER_POLYTECHNIC_INSTITUTION_OF", "note": "Cal Poly SLO is the California State University system's most prestigious polytechnic institution"}, {"entity": "Silicon Valley Technology Economy", "relationship": "MAJOR_ENGINEERING_TALENT_SUPPLIER_TO", "note": "Cal Poly engineering graduates have disproportionate presence in Silicon Valley technology companies"}, {"entity": "American Polytechnic Education", "relationship": "LEADING_EXEMPLAR_OF_LEARN-BY-DOING_PHILOSOPHY_IN", "note": "Cal Poly's 'learn by doing' model represents America's most successful polytechnic public university approach"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "California Polytechnic State University — America's premier public polytechnic university, training engineers, architects, and agricultural scientists through distinctive hands-on learning, supplying Silicon Valley's technology economy with graduates — is historically significant as the most successful exemplar of practical polytechnic education in American public higher education.", "significanceCategory": "world-changing"},
    }),
    ("california-state-university-long-beach", {
        "summary": "California State University, Long Beach (CSULB, Cal State Long Beach, founded 1949) is one of the largest universities in the California State University system (enrollment approximately 37,000 students), located in Long Beach in Los Angeles County — serving one of the most ethnically and socioeconomically diverse student populations in American higher education and recognized as one of the most diverse major universities in the United States, reflecting the extraordinary demographic complexity of the greater Los Angeles metropolitan area.\n\nCSULB's post-WWII founding reflects the dramatic expansion of California's population during the war (workers flooding into Southern California's defense industries) and baby boom that followed. Long Beach, as home to a major port and naval base, was a center of wartime industrial activity, and the postwar population boom created urgent demand for accessible higher education. California's 1960 Master Plan for Higher Education designated Cal State institutions to provide accessible education to the broader population while reserving University of California campuses for graduate education and research.\n\nCSULB has achieved national recognition for its diversity, educational mobility, and economic impact: it is consistently ranked as one of America's top universities for social mobility — graduating students from low-income backgrounds into middle-class professional careers. The university's enrollment of approximately 37,000 students includes a student body that is over 50% minority (majority Hispanic/Latino, Asian, and African American), making it a major institution of educational access in one of America's most diverse regions.",
        "causes": ["Post-WWII Southern California population boom requiring accessible public university in Long Beach area", "1960 California Master Plan designating Cal State system for broad access education", "Long Beach's port and defense industry growth creating large working-class population requiring higher education access", "Greater Los Angeles area's demographic diversity requiring educational institutions serving diverse student populations"],
        "effects": ["One of America's most diverse major universities serving 37,000+ students from varied backgrounds", "Social mobility achievement through graduating low-income first-generation students into professional careers", "Greater Los Angeles region's economic development supported through trained professional workforce", "Model of diverse public higher education demonstrating accessibility in America's most complex demographic environment"],
        "relationships": [{"entity": "California Master Plan 1960", "relationship": "CAL_STATE_BROAD_ACCESS_MISSION_ENACTED_IN", "note": "CSULB fulfills the 1960 Master Plan's vision of accessible Cal State education for California's diverse population"}, {"entity": "Greater Los Angeles", "relationship": "MAJOR_EDUCATIONAL_INSTITUTION_OF_DIVERSE_METROPOLITAN_AREA", "note": "CSULB serves one of America's most ethnically diverse metropolitan populations in greater Los Angeles"}, {"entity": "Social Mobility", "relationship": "TOP-RANKED_INSTITUTION_FOR_EDUCATIONAL", "note": "CSULB consistently ranks among America's top universities for social mobility — graduating low-income students to middle-class careers"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "California State University Long Beach — one of America's most diverse major universities, top-ranked for social mobility, serving 37,000+ students in greater Los Angeles's complex demographic environment — is historically significant as a model of accessible public higher education serving America's most diverse population.", "significanceCategory": "world-changing"},
    }),
    ("california-state-university-los-angeles", {
        "summary": "California State University, Los Angeles (Cal State LA, CSULA, founded 1947) is a public university in Los Angeles, California, part of the California State University system — serving one of America's most ethnically diverse urban student populations, with approximately 70% of students from minority backgrounds and a majority Hispanic-serving institution designation, making it one of the most diverse major universities in the United States and a critical institution of educational opportunity in one of the world's largest and most diverse urban centers.\n\nCal State LA's founding in 1947 — two years before CSULB — responded to the same post-WWII Southern California population surge, but with a focus on Los Angeles's urban core. The university's East Los Angeles location situates it in the heart of the city's largest Latino community, and its enrollment patterns reflect this geography: Cal State LA has been a Hispanic-Serving Institution (HSI) since the designation was created, with its student body majority Hispanic and serving large proportions of first-generation college students.\n\nCal State LA has achieved significant recognition for its educational access mission: consistently ranked among America's top universities for social mobility, it graduates large numbers of first-generation college students from working-class backgrounds into professional careers. The university's research programs (including CSULA's NASA-affiliated Jet Propulsion Laboratory collaborations) combine with its access mission, and its College of Engineering, Computer Science, and Technology has produced graduates who have contributed significantly to Los Angeles's technology and aerospace industries.",
        "causes": ["Post-WWII Los Angeles population expansion requiring accessible public university in the city's urban core", "East Los Angeles Latino community's educational access needs requiring university in the community's geographic center", "1947 California State educational expansion reflecting WWII veterans' GI Bill and baby boom educational demand", "Urban diversity requiring accessible higher education institution for working-class and first-generation students"],
        "effects": ["Hispanic-Serving Institution providing higher education access to America's largest urban Latino community", "Top social mobility rankings demonstrating successful graduation of first-generation low-income students", "NASA Jet Propulsion Laboratory collaborations connecting urban access institution to America's space program", "Los Angeles's diverse workforce development supported through engineering, business, and health science programs"],
        "relationships": [{"entity": "East Los Angeles", "relationship": "MAJOR_HIGHER_EDUCATION_INSTITUTION_IN_AMERICA'S_LARGEST_LATINO_COMMUNITY", "note": "Cal State LA is situated in and primarily serves East Los Angeles, the heart of America's largest Latino urban community"}, {"entity": "Hispanic-Serving Institution", "relationship": "DESIGNATED_AND_FLAGSHIP_EXAMPLE_OF", "note": "Cal State LA is one of America's premier Hispanic-Serving Institutions serving a majority Latino student body"}, {"entity": "Social Mobility", "relationship": "TOP-RANKED_URBAN_UNIVERSITY_FOR_EDUCATIONAL", "note": "Cal State LA consistently ranks among America's most effective social mobility institutions for first-generation students"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "California State University Los Angeles — a top-ranked Hispanic-Serving Institution in America's largest Latino urban community, consistently recognized for exceptional social mobility — is historically significant as a model of urban educational access for America's most diverse city.", "significanceCategory": "world-changing"},
    }),
    ("california-state-university-sacramento", {
        "summary": "California State University, Sacramento (Sacramento State, Sac State, CSUS, founded 1947) is a public university and California's capital city university — the main higher education institution serving the Sacramento region, home to California state government and a major hub of public administration, law, and government-related professions. With approximately 31,000 students, Sacramento State serves one of California's fastest-growing metropolitan areas and trains a significant proportion of the public sector professionals who work in California's state government.\n\nSacramento's role as California's state capital — housing the state legislature, governor's office, and hundreds of state government agencies — gives Sacramento State a distinctive educational role: it trains students who disproportionately enter public administration, public health, social work, and government-related professions. The university's public administration and government programs serve the unique needs of a state capital region where state government employment is a dominant economic sector.\n\nSacramento State's founding in 1947 reflected the same post-WWII population boom that drove CSU expansion across California, but the Sacramento Valley's specific growth was accelerated by Cold War era government expansion and defense-related industries. The university has grown to serve a diverse Sacramento Valley population that includes significant communities of Hmong, Somali, Mexican-American, and other immigrant groups — making Sac State one of California's most diverse CSU campuses and a major institution of immigrant community educational integration.",
        "causes": ["Post-WWII Sacramento region population expansion requiring accessible public university in the state capital area", "California state capital's public administration needs requiring university training public sector professionals", "Sacramento Valley's diverse immigrant communities requiring accessible higher education for first-generation students", "Cold War government expansion in Sacramento driving population growth and higher education demand"],
        "effects": ["State capital region university training California's public sector workforce in government, law, and administration", "Diverse Sacramento Valley communities served including significant Hmong, Somali, and Mexican-American student populations", "31,000+ student enrollment making Sac State a major component of Sacramento's economic and civic life", "Public administration programs serving the distinctive needs of California's state government employment hub"],
        "relationships": [{"entity": "California State Government", "relationship": "PRIMARY_PROFESSIONAL_TRAINING_INSTITUTION_FOR_EMPLOYEES_OF", "note": "Sacramento State trains a disproportionate share of California's state government public administration professionals"}, {"entity": "Sacramento", "relationship": "PRIMARY_HIGHER_EDUCATION_INSTITUTION_OF_CALIFORNIA'S_CAPITAL", "note": "Sac State is the main university serving Sacramento, California's state capital and fastest-growing major metropolitan area"}, {"entity": "Immigrant Communities", "relationship": "MAJOR_EDUCATIONAL_ACCESS_INSTITUTION_FOR_HMONG_AND_DIVERSE", "note": "Sacramento State serves significant Hmong, Somali, and other immigrant communities in the Sacramento Valley"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "California State University Sacramento — California's state capital university training the public sector professionals who administer the world's fifth-largest economy's state government — is historically significant as the higher education institution serving California's government hub.", "significanceCategory": "continental"},
    }),
    ("california-state-university-northridge", {
        "summary": "California State University, Northridge (CSUN, founded 1958) is a public university in the San Fernando Valley area of Los Angeles, California — and the campus associated with one of the most significant events in American earthquake history: the 1994 Northridge earthquake (magnitude 6.7), which caused catastrophic damage to the university and fundamentally changed American understanding of earthquake engineering and seismic building design. CSUN's destruction and reconstruction after the earthquake has influenced building codes and seismic engineering standards nationwide.\n\nThe January 17, 1994, Northridge earthquake caused extensive structural damage to CSUN's campus, collapsing the parking structure and damaging many buildings, resulting in the tragic death of two campus employees. The university's rapid reconstruction (returning to full operation within months despite massive damage) was itself a remarkable achievement, and the lessons learned from CSUN's building damage patterns were incorporated into significantly revised California and national seismic building codes. CSUN's engineering department became a center of post-earthquake research.\n\nCSUN serves approximately 38,000 students in the San Fernando Valley, which became increasingly Latino and immigrant-community dominant after the 1960s white flight to suburbs. The university has significant programs in business, arts, and sciences, and its National Center on Deafness is nationally recognized for deaf education services. CSUN has invested heavily in supporting students with disabilities, including deaf and hard-of-hearing students.",
        "causes": ["1958 CSU expansion serving the post-WWII San Fernando Valley residential population surge", "San Fernando Valley's rapid suburban growth requiring local public university for its large population", "1994 Northridge earthquake creating unprecedented campus destruction requiring emergency rebuilding", "Valley's demographic transition to Latino and immigrant communities requiring accessible higher education institution"],
        "effects": ["1994 earthquake damage and reconstruction reshaping American seismic engineering and building codes", "National Center on Deafness making CSUN a national leader in deaf higher education services", "38,000+ student campus serving the San Fernando Valley's large and increasingly diverse population", "Earthquake engineering research contributions improving structural safety standards nationwide"],
        "relationships": [{"entity": "1994 Northridge Earthquake", "relationship": "CAMPUS_EXTENSIVELY_DAMAGED_BY_HISTORIC", "note": "The 1994 earthquake caused catastrophic damage to CSUN, whose reconstruction influenced American seismic building codes"}, {"entity": "California State University System", "relationship": "MAJOR_CAMPUS_OF_SERVING_SAN_FERNANDO_VALLEY", "note": "CSUN is the CSU's main campus for the 1.8 million-person San Fernando Valley"}, {"entity": "Deaf Education", "relationship": "NATIONAL_CENTER_ON_DEAFNESS_MAKING_CSUN_LEADER_IN", "note": "CSUN's National Center on Deafness is nationally recognized for higher education services to deaf students"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "California State University Northridge — whose catastrophic damage in the 1994 Northridge earthquake led to nationwide revision of seismic building codes, hosting the National Center on Deafness — is historically significant both as a seismic engineering landmark and a model of accessible education for diverse and disabled students.", "significanceCategory": "world-changing"},
    }),
    ("california-state-university-fresno", {
        "summary": "California State University, Fresno (Fresno State, founded 1911) is the oldest California State University campus after the first normal schools — located in Fresno, the commercial center of California's Central Valley, the world's most productive agricultural region — and serving the San Joaquin Valley's largely agricultural economy and increasingly diverse population, with significant programs in agriculture, viticulture and enology, and agricultural sciences that reflect its unique position as the university of America's most important farming region.\n\nFresno and the San Joaquin Valley are extraordinary in American agriculture: the region produces over half of the nation's fruits, nuts, and vegetables, making California (and specifically the Central Valley) the world's most diverse and productive agricultural region. Fresno State's agricultural programs — particularly its Jordan College of Agricultural Sciences and Technology, viticulture and enology program, and food science programs — serve the educational needs of an industry that is foundational to American and global food supply.\n\nFresno State's student body is one of California's most diverse CSU campuses, reflecting the San Joaquin Valley's large Mexican-American community (descended from generations of agricultural workers who settled as the crops changed from seasonal to permanent), Hmong community (one of the largest US Hmong populations outside Minnesota), and other agricultural worker communities. The university's social mobility metrics reflect its role in educating first-generation students from agricultural worker families into professional careers.",
        "causes": ["1911 founding as normal school serving California's Central Valley's teacher education needs", "San Joaquin Valley's world-leading agricultural economy requiring university-level agricultural education", "Central Valley's diverse agricultural worker communities requiring accessible higher education for first-generation students", "CSU expansion to serve the large inland California population historically underserved by higher education"],
        "effects": ["Agricultural sciences programs supporting America's most important farming region's technical workforce", "Viticulture and enology programs supporting California's premium wine industry in the San Joaquin Valley", "Diverse student population serving Mexican-American and Hmong communities in one of California's most diverse valleys", "Social mobility function graduating agricultural worker families' children into professional careers"],
        "relationships": [{"entity": "San Joaquin Valley Agriculture", "relationship": "PRIMARY_HIGHER_EDUCATION_INSTITUTION_SERVING_WORLD'S_MOST_PRODUCTIVE_FARMING_REGION", "note": "Fresno State's agricultural programs serve the San Joaquin Valley, which produces over half of America's fruits, nuts, and vegetables"}, {"entity": "California Wine Industry", "relationship": "VITICULTURE_AND_ENOLOGY_PROGRAMS_SUPPORTING", "note": "Fresno State's wine programs serve California's Central Valley viticulture industry"}, {"entity": "Central Valley Immigrant Communities", "relationship": "MAJOR_EDUCATIONAL_INSTITUTION_FOR_MEXICAN-AMERICAN_AND_HMONG", "note": "The university serves large Mexican-American and Hmong communities who form the Central Valley's agricultural workforce"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "California State University Fresno — serving the world's most productive agricultural region with specialized agricultural programs, educating the diverse communities of California's Central Valley — is historically significant as the higher education anchor of America's most critical farming region.", "significanceCategory": "continental"},
    }),
    ("california-state-university-fullerton", {
        "summary": "California State University, Fullerton (CSUF, founded 1957) is the largest university in the California State University system by enrollment (approximately 40,000 students), located in Fullerton in Orange County, Southern California — serving the densely populated inland Orange County region and recognized as a diverse commuter university that is among America's most attended public universities, a Hispanic-Serving Institution, and consistently ranked among top social mobility institutions.\n\nCSUF's size reflects both the extraordinary population density of Orange County (population approximately 3.2 million, making it one of America's most populous counties) and the CSU system's commitment to serving students who cannot afford or choose not to live on campuses. As a commuter university, CSUF primarily serves working adults, first-generation students, and community college transfer students — a model that makes higher education accessible to populations that traditional residential universities do not serve.\n\nCSUF's academic programs span business, arts, communications, engineering, science, and health, with the College of Business and Economics (consistently ranked among California's best) and its performing arts programs particularly recognized. The university's journalism and communications programs have produced significant numbers of Southern California media professionals. As the system's largest campus, CSUF plays a significant role in Orange County's and Southern California's workforce development.",
        "causes": ["1957 CSU expansion to serve the rapidly growing post-WWII Orange County suburban population", "Orange County's extraordinary population density (3.2 million) requiring major university capacity", "Commuter university model providing higher education access to working adults and community college transfers", "Hispanic-serving institution needs reflecting Orange County's large Latino population"],
        "effects": ["Largest CSU campus serving 40,000+ students as a major commuter and transfer university", "Social mobility function as top-ranked institution graduating first-generation and working adult students", "Orange County's diverse workforce supplied through comprehensive academic programs", "Business, communications, and performing arts programs producing significant Southern California professional workforce"],
        "relationships": [{"entity": "California State University System", "relationship": "LARGEST_CAMPUS_OF_BY_ENROLLMENT", "note": "CSUF is the CSU system's largest campus with approximately 40,000 students"}, {"entity": "Orange County", "relationship": "PRIMARY_HIGHER_EDUCATION_INSTITUTION_SERVING", "note": "CSUF serves Orange County, one of America's most populous counties with 3.2 million residents"}, {"entity": "Social Mobility", "relationship": "TOP-RANKED_COMMUTER_UNIVERSITY_FOR_EDUCATIONAL", "note": "CSUF is consistently ranked among America's best social mobility universities serving first-generation and transfer students"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "California State University Fullerton — the CSU system's largest campus, a top social mobility institution serving 40,000+ students in densely populated Orange County — is historically significant as America's most successful commuter university model serving diverse first-generation and working adult students.", "significanceCategory": "world-changing"},
    }),
    ("california-state-university-chico", {
        "summary": "California State University, Chico (Chico State, founded 1887 as the California State Normal School, Chico) is one of the oldest campuses in the California State University system — a comprehensive university located in Chico, Northern California, in the Sacramento Valley's upper reach — and historically known both for its academic programs in areas including agriculture, arts, and sciences and for a national notoriety as a party school that resulted in significant administrative reform and cultural transformation in the late 1980s-1990s.\n\nChico State's 1887 founding as a normal school (teacher training institution) reflects California's systematic approach to providing teacher education throughout the state in the post-Civil War period. As one of California's earliest normal schools, Chico has 135+ years of educational history, serving the largely agricultural and forestry-dependent communities of Northern California's Sacramento Valley and the Cascade/Sierra foothill region.\n\nChico State's academic programs include respected offerings in computer science, social work, journalism, and agriculture, with particular strength in sustainability and environmental studies reflecting the region's natural resource economy. The university's campus is noted for its attractive setting and architectural character including historic buildings. The city of Chico, a college town in the Northern Sacramento Valley, has significant agricultural (almond, walnut orchards) and technological industries (including the Chico area's role in early Silicon Valley connections).",
        "causes": ["1887 normal school founding as California's systematic teacher education expansion to Northern California", "Sacramento Valley's agricultural communities requiring accessible higher education in the region's northern tier", "CSU system's northern California educational mission requiring comprehensive university for the region", "Post-WWII CSU expansion transforming normal school into full university reflecting California's higher education democratization"],
        "effects": ["135+ years of education serving Northern California's agricultural, forestry, and increasingly diverse communities", "Computer science, social work, and environmental programs developing workforce for Northern California industries", "Administrative reform transforming campus culture and academic reputation in the 1990s", "Chico's college town character shaped by 135+ years of university presence in the Sacramento Valley community"],
        "relationships": [{"entity": "California Normal School System", "relationship": "ONE_OF_CALIFORNIA'S_OLDEST_NORMAL_SCHOOLS_EVOLVED_INTO", "note": "Founded in 1887 as a normal school, Chico State is one of California's oldest continuous higher education institutions"}, {"entity": "Northern California", "relationship": "PRIMARY_CSU_UNIVERSITY_SERVING_UPPER_SACRAMENTO_VALLEY_OF", "note": "Chico State is the main CSU institution serving Northern California's agricultural and forestry communities"}, {"entity": "California State University System", "relationship": "OLDEST_CONTINUOUS_NORMAL_SCHOOL_HERITAGE_CAMPUS_IN", "note": "The 1887 founding makes Chico one of the CSU system's historically oldest campuses"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "California State University Chico — one of California's oldest normal schools (1887), serving Northern California's agricultural communities for 135+ years — is regionally significant as a historic educational institution serving the Sacramento Valley's rural and increasingly diverse communities.", "significanceCategory": "local"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 133 — Class 381 Universities VII: California State Universities")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
