#!/usr/bin/env python3
"""Batch 118 — Class 364 Studios IV: Major Record Labels (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/364-Class-364"
FILE_PREFIX = "364"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("atlantic-records", {
        "summary": "Atlantic Records, founded in 1947 in New York City by Ahmet Ertegün (a Turkish diplomat's son with an extraordinary ear for Black American music) and Herb Abramson, is one of the most historically significant record labels in American music history — credited with pioneering rhythm and blues, soul, and rock and roll recording from the late 1940s through the 1970s, and launching the careers of Ray Charles, Aretha Franklin, Led Zeppelin, and hundreds of other defining artists.\n\nAhmet Ertegün's Atlantic was distinguished by its founder's genuine love for and knowledge of Black American music, unusual among record label executives of the era. Atlantic's early roster included Ruth Brown, the Clovers, Joe Turner, and Ray Charles — whose Atlantic recordings from 1952-1959 defined the R&B/soul synthesis. The 1967 signing of Aretha Franklin — who had failed to breakthrough at Columbia Records — and the immediate recognition that producer Jerry Wexler and Atlantic's approach (combined with Muscle Shoals studio musicians) could unlock her genius produced the definitive recordings of her career.\n\nAtlantic's expansion into rock began with the Cream, Led Zeppelin, and Crosby, Stills, Nash & Young in the late 1960s. The label was acquired by Warner-Seven Arts in 1967 (becoming part of what eventually became WMG) while maintaining editorial independence. Modern Atlantic has been home to Coldplay, Bruno Mars, Ed Sheeran, Cardi B, and many contemporary acts. The label's heritage — from Ray Charles and Aretha Franklin through Led Zeppelin to Bruno Mars — makes it one of the most musically significant institutions in 20th-century American culture.",
        "causes": ["1947 founding by Ahmet Ertegün combining music passion with business acumen targeting under-served Black music market", "R&B/soul innovation through Ray Charles, Ruth Brown, and Clovers establishing Atlantic's distinctive sound", "Jerry Wexler's production approach combining Muscle Shoals studio musicians with exceptional soul vocalists", "1967 Warner acquisition providing major-label distribution while maintaining Atlantic's editorial independence"],
        "effects": ["Ray Charles's Atlantic recordings (1952-1959) defining soul music as a genre", "Aretha Franklin's Atlantic years (1967-1979) producing the defining recordings of the Queen of Soul", "Led Zeppelin's Atlantic career making it one of rock history's most commercially successful label relationships", "Atlantic's heritage spanning R&B to rock to contemporary pop making it one of American music's most consequential labels"],
        "relationships": [{"entity": "Ahmet Ertegün", "relationship": "FOUNDED_AND_SHAPED_BY", "note": "Ertegün's 1947 founding and personal musical taste defined Atlantic's extraordinary roster for 50 years"}, {"entity": "Aretha Franklin", "relationship": "CAREER-DEFINING_LABEL_FOR", "note": "Aretha's Atlantic years (1967-1979) produced her greatest recordings including 'Respect' and 'Chain of Fools'"}, {"entity": "Ray Charles", "relationship": "DISCOVERED_AND_RECORDED_DEFINING_WORK_OF", "note": "Ray Charles's 1952-1959 Atlantic recordings defined the R&B/soul synthesis that transformed American popular music"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "Atlantic Records — launching Ray Charles, Aretha Franklin, Led Zeppelin, and dozens of other defining artists, pioneering R&B and soul recording with genuine cultural investment, and spanning 75+ years of American musical history — is one of the most historically significant record labels ever created.", "significanceCategory": "world-changing"},
    }),
    ("capitol-records", {
        "summary": "Capitol Records, founded in 1942 in Hollywood, California by songwriter Johnny Mercer, Glenn Wallichs (music store owner), and Buddy DeSylva (producer) — becoming the first major American record label based on the West Coast — is one of the most significant labels in American popular music history, home to Frank Sinatra, Nat King Cole, Dean Martin, the Beatles' American releases, and Beach Boys, and headquartered since 1956 in the iconic Capitol Records Tower (designed by Welton Becket) in Hollywood — one of the most recognizable building in American music.\n\nCapitol was the first label to recognize California as a cultural force: its West Coast base gave it access to Hollywood and the film industry's entertainment ecosystem, enabling early crossover between film and popular music that shaped the entertainment industry's consolidation. The label signed Frank Sinatra at a career low point in 1953 (Sinatra had left Columbia after a commercial decline), and producer Nelson Riddle's orchestral arrangements combined with Sinatra's vocal maturity produced the definitive recordings of the Chairman of the Board — the 'concept albums' such as In the Wee Small Hours (1955) and Songs for Swingin' Lovers (1956) that established the LP as an art form.\n\nThe Beatles' US distribution through Capitol (after their UK label EMI acquired Capitol in 1955) meant Capitol released most Beatles albums in North America, though with modified track listings initially. The Beach Boys were the quintessential Capitol act — Brian Wilson's productions from Pet Sounds (1966) to Smile expanded what pop music could achieve. Capitol was acquired by EMI in 1955 and later became part of Universal Music Group (2012). The Capitol Tower remains both a working music facility and an architectural landmark.",
        "causes": ["1942 West Coast founding as first major California-based label serving Hollywood's entertainment ecosystem", "Frank Sinatra signing (1953) at career low producing definitive recordings that revived his career and pioneered LP art", "Beatles' US distribution through Capitol bringing British Invasion to American market", "Capitol Tower (1956) building creating most iconic record label headquarters in American music"],
        "effects": ["Frank Sinatra's Capitol years (1953-1961) defining the 'concept album' LP format and establishing him as American popular music's pre-eminent voice", "Beatles' Capitol releases driving the British Invasion and transforming American popular music 1964-1970", "Beach Boys' Capitol recordings including Pet Sounds setting new creative standards for pop music production", "Capitol Tower as architectural symbol of American recorded music and Hollywood entertainment culture"],
        "relationships": [{"entity": "Frank Sinatra", "relationship": "CAREER-REVIVING_LABEL_FOR", "note": "Sinatra's Capitol years (1953-1961) with Nelson Riddle produced his definitive recordings and established the concept album"}, {"entity": "The Beatles", "relationship": "US_DISTRIBUTOR_OF_RECORDINGS_FOR", "note": "Capitol released most Beatles albums in North America as part of EMI's American distribution"}, {"entity": "Beach Boys", "relationship": "DEFINING_ARTIST_OF_CALIFORNIA_SOUND_AT", "note": "Beach Boys' Capitol recordings from 1962-1969 including Pet Sounds defined California's musical identity"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Capitol Records — home to Sinatra, the Beatles, and the Beach Boys, pioneering the LP as an art form, and headquartered in Hollywood's most iconic music building — is one of American popular music's most consequential institutions.", "significanceCategory": "world-changing"},
    }),
    ("columbia-records", {
        "summary": "Columbia Records, founded in 1887 as the Columbia Phonograph Company — making it one of the oldest recorded music companies in existence, predating the sound recording industry's commercial foundations — is one of the most historically significant and commercially successful record labels ever established, responsible for pioneering the development of the LP (long-playing record) in 1948, and home to Miles Davis, Bob Dylan, Billie Holiday, Johnny Cash, Bruce Springsteen, Beyoncé, and hundreds of other defining artists across every genre and era.\n\nColumbia's early history is intertwined with the very foundations of the recorded music industry: it was one of the first companies to commercially exploit Edison's phonograph technology, competing with Victor (later RCA Victor) for the infant market. Columbia's most technically significant contribution was the invention of the LP by Peter Goldmark in 1948 — the 33⅓ RPM long-playing vinyl record that replaced the 78 RPM shellac disc, enabling continuous music for 22+ minutes per side and transforming how music was organized, sold, and experienced by listeners worldwide.\n\nColumbia Records' artistic legacy is incomparable: Miles Davis's decade-long relationship produced Kind of Blue (1959, the best-selling jazz album of all time), Bitches Brew (1970, defining jazz fusion), and multiple other masterpieces. Bob Dylan signed with Columbia in 1961 and made the label the home of the folk-rock revolution. Johnny Cash recorded at Columbia from 1958-1986. Beyoncé, Bruce Springsteen, Adele, and contemporary superstars have continued the tradition. Now part of Sony Music Entertainment, Columbia maintains its status as one of the music industry's most prestigious labels.",
        "causes": ["1887 founding as Columbia Phonograph Company at the very birth of commercial recorded music industry", "1948 LP invention by Peter Goldmark revolutionizing recorded music format from 78 RPM to 33⅓ RPM", "Miles Davis's sustained relationship producing the most important jazz recordings of the 20th century", "Bob Dylan's 1961 signing establishing Columbia as home of the folk-rock revolution"],
        "effects": ["LP invention (1948) transforming recorded music — enabling concept albums, classical symphonies, and full-length releases", "Miles Davis's Kind of Blue becoming best-selling jazz album of all time through Columbia's recording and distribution", "Bob Dylan's Columbia discography defining American folk-rock and creating the singer-songwriter tradition", "Columbia's 135+ year continuous existence making it one of recorded music's most enduring institutional continuities"],
        "relationships": [{"entity": "Miles Davis", "relationship": "PRINCIPAL_LABEL_FOR_DEFINING_RECORDINGS_OF", "note": "Davis's Columbia years produced Kind of Blue, Bitches Brew, and the defining recordings of jazz's greatest instrumentalist"}, {"entity": "Long-Playing Record", "relationship": "INVENTOR_OF_FORMAT_THROUGH", "note": "Columbia's Peter Goldmark invented the LP (33⅓ RPM) in 1948 — the most significant format innovation in recorded music history"}, {"entity": "Bob Dylan", "relationship": "CAREER-DEFINING_LABEL_FOR", "note": "Dylan signed with Columbia in 1961 and recorded his most important work through the label's decades of support"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "Columbia Records — the oldest major label (1887), inventor of the LP format (1948), home to Miles Davis's Kind of Blue, Bob Dylan's revolution, Johnny Cash, and Beyoncé — is the most historically continuous and arguably most significant record label in the history of recorded music.", "significanceCategory": "world-changing"},
    }),
    ("interscope-records", {
        "summary": "Interscope Records, founded in 1990 by Jimmy Iovine and Ted Field as an independent label distributed by WEA (Warner), is one of the most commercially successful and artistically significant American record labels of the 1990s-2010s — achieving prominence through its relationship with Death Row Records (distributing Snoop Dogg, Tupac, and the birth of West Coast gangsta rap), its signing of Dr. Dre's Aftermath label, and its development of major artists including Nine Inch Nails, Eminem, Lady Gaga, Kendrick Lamar, and U2's later catalog.\n\nJimmy Iovine's trajectory from recording engineer (working with Springsteen, Patti Smith, John Lennon) to executive reflects Interscope's combination of technical recording knowledge and commercial instincts. The label's early signing of Suge Knight and Dr. Dre's Death Row relationship (1992-1996) distributed Snoop Dogg's Doggystyle, Tupac's All Eyez on Me, and Dre's The Chronic — albums that defined West Coast hip-hop and sold tens of millions worldwide. Despite controversy over Death Row's gangsta rap content (Congressional hearings, Tipper Gore's PMRC), Interscope maintained the relationship.\n\nAfter Death Row's collapse following Tupac's murder (1996) and Suge Knight's imprisonment, Interscope acquired Dr. Dre's Aftermath Entertainment and signed Eminem (through Aftermath) — creating one of the most commercially successful label-within-label relationships in hip-hop history. Lady Gaga's career was developed entirely through Interscope. Today Interscope (now part of Universal Music Group's Interscope Geffen A&M division) remains one of American popular music's most powerful label imprints.",
        "causes": ["1990 founding by Jimmy Iovine and Ted Field as independent label with WEA distribution", "Death Row distribution relationship (1992-1996) bringing West Coast gangsta rap mainstream through Snoop, Tupac, Dre", "Aftermath Entertainment partnership with Dr. Dre and Eminem signing creating 2000s hip-hop dominance", "Lady Gaga development establishing Interscope as defining label for 2010s pop music"],
        "effects": ["West Coast gangsta rap mainstreaming through Snoop's Doggystyle and Tupac's All Eyez on Me", "Eminem's commercial breakthrough as best-selling artist of 2000s decade through Aftermath/Interscope", "Lady Gaga's complete career development making Interscope the defining pop label of the 2010s", "Congressional controversies over gangsta rap content shaping PMRC debates about music industry self-regulation"],
        "relationships": [{"entity": "Jimmy Iovine", "relationship": "CO-FOUNDED_AND_SHAPED_BY", "note": "Iovine co-founded Interscope in 1990 and shaped its trajectory from Death Row to Eminem to Lady Gaga"}, {"entity": "Death Row Records", "relationship": "DISTRIBUTED_AND_ENABLED_WEST_COAST_RAP_THROUGH", "note": "Interscope's Death Row distribution (1992-1996) brought Snoop, Tupac, and Dre's defining albums to market"}, {"entity": "Dr. Dre", "relationship": "AFTERMATH_PARTNERSHIP_ENABLING_HIP-HOP_DOMINANCE", "note": "Dre's Aftermath label (within Interscope) signed Eminem and produced the 2000s' most successful hip-hop releases"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Interscope Records — distributing West Coast gangsta rap's defining albums, developing Eminem and Lady Gaga, and navigating music industry controversies from PMRC to streaming — is one of the most commercially successful and artistically consequential American labels of the past 30 years.", "significanceCategory": "world-changing"},
    }),
    ("island-records", {
        "summary": "Island Records, founded in 1959 in Jamaica by Chris Blackwell — a young Englishman of Jamaican heritage who had been driving around Kingston distributing Jamaican music before establishing a proper label — is one of the most creatively significant record labels in British and global music history, responsible for bringing reggae to the world through Bob Marley and the Wailers, developing U2, Cat Stevens, Robert Palmer, and many other defining artists, and maintaining a distinctive independent creative ethos that shaped rock, reggae, and pop across six decades.\n\nChris Blackwell's genius was cultural bridging: born into Jamaican landed gentry (his father was a Jamaican planter, his mother was the actress Blanche Lindo), he understood both Jamaican music culture and the British and American markets where it could break through. His 1972 decision to invest in Bob Marley and the Wailers — then a poorly recorded reggae group with limited international profile — and to present them to the rock audience (through rock-venue appearances, rock producer (Jimmy Miller working with them initially), and high-quality album production) transformed Marley from Jamaican star to global superstar and reggae from Jamaican niche to worldwide genre.\n\nIsland's rock roster — Traffic, Free, King Crimson, Cat Stevens, Roxy Music, and the defining relationship with U2 from Boy (1980) through the mega-success of The Joshua Tree (1987) and beyond — made it one of the most artistically respected independent labels in the world. Blackwell sold Island to PolyGram in 1989; it is now part of Universal Music Group. Island Records' Jamaica-to-world journey is one of the music industry's most extraordinary stories of cultural vision and commercial success.",
        "causes": ["1959 founding in Kingston Jamaica by Chris Blackwell distributing Jamaican ska and later reggae", "1972 Bob Marley investment and rock-audience positioning bringing reggae to global consciousness", "U2 signing (1980) and decade-long development producing The Joshua Tree as one of rock's biggest albums", "Chris Blackwell's Jamaica-rock-market cultural bridging enabling unique cross-genre artist roster"],
        "effects": ["Bob Marley's global breakthrough transforming reggae from Jamaican niche to worldwide music genre", "U2's Island Records development producing The Joshua Tree (1987) as one of best-selling albums in history", "Island model as template for culturally-rooted independent labels maintaining artistic vision while achieving global reach", "Jamaican music's global spread from ska through reggae to dancehall partly enabled by Island's early investment"],
        "relationships": [{"entity": "Chris Blackwell", "relationship": "FOUNDED_AND_DEFINED_BY", "note": "Blackwell founded Island in Jamaica in 1959 and his cultural vision drove its extraordinary roster for 30 years"}, {"entity": "Bob Marley and the Wailers", "relationship": "GLOBAL_BREAKTHROUGH_ARTIST_SIGNED_AND_DEVELOPED", "note": "Blackwell's 1972 signing and rock-positioning of Marley transformed reggae into a global music movement"}, {"entity": "U2", "relationship": "CAREER-DEFINING_LABEL_FOR_FROM_1980", "note": "Island developed U2 from debut Boy (1980) through The Joshua Tree's global mega-success"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Island Records — founded in Jamaica, bringing Bob Marley to the world, developing U2's career, and maintaining extraordinary creative integrity across 60+ years — is one of the music industry's most historically significant and culturally impactful labels.", "significanceCategory": "world-changing"},
    }),
    ("capitol-records-nashville", {
        "summary": "Capitol Records Nashville, established in 1989 as a dedicated country music imprint of Capitol Records, emerged from Capitol's earlier Nashville operations to become one of the most commercially successful country music labels in the industry — home to Garth Brooks (whose albums are among the best-selling of any artist in any genre in the history of recorded music), Kenny Rogers, Dierks Bentley, and Kacey Musgraves — and representing the mainstreaming of country music from regional American genre to billion-dollar global industry.\n\nCapitol Nashville's founding coincided with the 'New Country' movement of the late 1980s and early 1990s: artists like Garth Brooks, Clint Black, and Alan Jackson who combined traditional country values with production values, arena-rock showmanship, and crossover appeal. Garth Brooks' career at Capitol Nashville — his self-titled debut (1989) through Ropin' the Wind (1991, the first country album to debut at #1 on the Billboard pop chart) through No Fences (1990, the best-selling country album of all time) — transformed country music from a regional genre into a mainstream American and eventually global phenomenon. Brooks became the best-selling solo American music artist of the RIAA certification era, ahead of Elvis and Michael Jackson in total certifications.\n\nModern Capitol Nashville continues with significant country artists; Kacey Musgraves' Golden Hour (2019) Grammy Album of the Year win for a country album marked the label's continued artistic credibility. Capitol Nashville is part of Universal Music Group Nashville and remains one of Nashville's most prestigious country imprints.",
        "causes": ["1989 establishment as dedicated country imprint serving Nashville's specialized music industry infrastructure", "New Country movement of late 1980s creating demand for production-quality country music label", "Garth Brooks signing and development transforming label into country music's commercial powerhouse", "Country music's crossover ambitions requiring dedicated West Coast label infrastructure via Capitol Nashville"],
        "effects": ["Garth Brooks becoming best-selling solo American artist in RIAA certification history through Capitol Nashville", "No Fences (1990) best-selling country album of all time demonstrating country's mainstream crossover potential", "Country music transformed from regional American genre to billion-dollar global industry partly through label's commercial template", "Kacey Musgraves' Golden Hour Grammy Album of the Year showing label's continued artistic as well as commercial significance"],
        "relationships": [{"entity": "Garth Brooks", "relationship": "MOST_COMMERCIALLY_SUCCESSFUL_ARTIST_OF", "note": "Brooks at Capitol Nashville became America's best-selling solo artist — more RIAA certifications than Elvis or Michael Jackson"}, {"entity": "Country Music Industry", "relationship": "COMMERCIAL_INFRASTRUCTURE_FOR_MAINSTREAMING", "note": "Capitol Nashville's commercial approach helped transform country music into a global billion-dollar industry"}, {"entity": "Kacey Musgraves", "relationship": "GRAMMY-WINNING_ARTISTIC_VALIDATION_ARTIST", "note": "Musgraves' Golden Hour (2019) Grammy Album of the Year validated Capitol Nashville's continued artistic relevance"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Capitol Records Nashville — home to Garth Brooks (America's best-selling solo artist), instrumental in country music's mainstream crossover, and producing Grammy Album of the Year winners — is one of the most commercially and culturally consequential country music labels ever established.", "significanceCategory": "world-changing"},
    }),
    ("cbs-films", {
        "summary": "CBS Films, established in 2007 as CBS Corporation's film production and distribution division, is a relatively small studio created to leverage CBS's television brand in theatrical film production — notable primarily for films such as The Woman in Black (2012, starring Daniel Radcliffe), The Dictator (2012, Sacha Baron Cohen), and a handful of other mid-budget films before restructuring in 2013 reduced its independent production profile.\n\nCBS Films was founded as CBS Corporation CEO Les Moonves sought to expand the media company's revenue streams beyond television into theatrical film distribution, following other major broadcasters' attempts at studio creation. The venture was managed by Amy Baer and later Lincoln Bandlow. CBS Films acquired and produced a mix of horror films, comedies, and dramas targeting mid-budget theatrical audiences — The Woman in Black with Daniel Radcliffe performing his post-Harry Potter image transition was the most commercially successful CBS Films release.\n\nThe venture illustrated the challenges facing traditional broadcasters entering the competitive theatrical film market against established studios. After early commercial results were mixed, CBS Films transitioned primarily to acquisitions and limited production rather than full-scale studio operations. CBS Corporation's 2019 merger with Viacom creating ViacomCBS (subsequently Paramount Global) rendered the CBS Films imprint largely redundant within a company that now includes Paramount Pictures. CBS Films remains a minor footnote in the history of broadcaster-studio ventures, notable primarily for its post-Harry Potter Radcliffe horror film.",
        "causes": ["2007 founding by CBS Corporation seeking to leverage television brand in theatrical film market", "Les Moonves's strategy to expand CBS beyond television into theatrical distribution revenue", "Mid-budget theatrical market providing opportunity for new entrant without full blockbuster infrastructure", "The Woman in Black (2012) acquisition and Radcliffe post-Potter casting as strategic prestige play"],
        "effects": ["The Woman in Black (2012) as most commercially successful CBS Films release demonstrating horror genre viability", "2013 reduction of production operations reflecting competitive challenges for broadcaster-studio model", "2019 ViacomCBS merger rendering CBS Films imprint largely redundant within Paramount Pictures portfolio", "CBS Films as case study in traditional broadcasters' difficult attempts to enter theatrical film business"],
        "relationships": [{"entity": "CBS Corporation", "relationship": "FILM_DIVISION_OF", "note": "CBS Films was established as CBS Corporation's theatrical film production and distribution arm"}, {"entity": "Daniel Radcliffe", "relationship": "POST-POTTER_IMAGE_TRANSITION_VEHICLE_FOR", "note": "Radcliffe's horror role in The Woman in Black (CBS Films) was his first major post-Harry Potter image transition"}, {"entity": "ViacomCBS", "relationship": "RENDERED_REDUNDANT_BY_MERGER_INTO", "note": "The 2019 CBS-Viacom merger creating ViacomCBS with Paramount Pictures made CBS Films largely redundant"}],
        "historicalSignificance": {"significanceScore": 4, "significanceNarrative": "CBS Films — a modestly-scaled broadcaster-studio venture most notable for The Woman in Black, illustrating the difficulties traditional TV companies face entering theatrical film, and absorbed into the ViacomCBS Paramount orbit — is a minor footnote in media industry consolidation history.", "significanceCategory": "local"},
    }),
    ("cbs-records", {
        "summary": "CBS Records, the recorded music division of CBS Corporation operating under that name from 1938 through its 1988 acquisition by Sony (becoming Sony Music Entertainment), was one of the most important record labels in 20th-century American music history — encompassing Columbia Records, Epic Records, and other imprints — and home to Bob Dylan, Barbra Streisand, Michael Jackson, Bruce Springsteen, Billy Joel, Julio Iglesias, and dozens of other major artists, making it the 20th century's most commercially successful recorded music company at its peak.\n\nCBS's recorded music roots trace to the Columbia Phonograph Company (founded 1887), which CBS acquired in 1938. Under this ownership, Columbia Records expanded into one of America's dominant labels. CBS Records as an entity was formally named in 1974, incorporating Columbia Records (the flagship US label), Epic Records (second label targeting different markets), Portrait, ARC, and other imprints. The combination of Columbia's prestige roster (Dylan, Springsteen) with Epic's Michael Jackson relationship (Jackson moved to Epic from Motown's parent in 1975) made CBS Records the world's most commercially powerful music company in the 1970s-1980s.\n\nMichael Jackson's CBS/Epic recordings — Off the Wall (1979), Thriller (1982, the best-selling album in recorded music history at 66+ million copies), and Bad (1987) — represent the commercial apex of any record company's roster. CBS sold the records division to Sony in 1988 for $2 billion, creating Sony Music Entertainment and ending CBS's music presence. The sale was described as part of Japan's cultural acquisition of American entertainment assets, marking a significant transformation in the music industry's corporate ownership.",
        "causes": ["1938 CBS acquisition of Columbia Phonograph Company establishing the recorded music division", "1974 formal CBS Records naming consolidating Columbia, Epic, and other imprints into coherent label group", "Michael Jackson's Epic recordings (Thriller, Off the Wall, Bad) creating world-record commercial success", "1988 Sony acquisition for $2 billion ending CBS's recorded music ownership"],
        "effects": ["Michael Jackson's Thriller (1982) as best-selling album in recorded music history (66+ million copies) through CBS/Epic", "Sony's 1988 $2 billion acquisition creating Sony Music Entertainment and beginning Japanese ownership of American music industry", "CBS Records roster (Dylan, Springsteen, Michael Jackson, Streisand, Billy Joel) as most commercially successful in music history", "1988 sale representing broader wave of Japanese corporate acquisition of American entertainment assets"],
        "relationships": [{"entity": "Michael Jackson", "relationship": "MOST_COMMERCIALLY_SUCCESSFUL_ARTIST_THROUGH_EPIC/CBS", "note": "Jackson's Thriller at CBS/Epic is the best-selling album in history; his CBS-era was the commercial apex of any label"}, {"entity": "Sony Music Entertainment", "relationship": "BECAME_UPON_1988_ACQUISITION", "note": "Sony's 1988 $2 billion CBS Records purchase created Sony Music Entertainment"}, {"entity": "Columbia Records", "relationship": "FLAGSHIP_IMPRINT_OF", "note": "Columbia Records (founded 1887) was CBS Records' flagship label carrying the most prestigious artists"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "CBS Records — the parent of Columbia and Epic, home to Thriller (best-selling album in history) and the most commercially successful record company roster of the 20th century, and whose 1988 Sony sale transformed the music industry's corporate ownership landscape — is one of recorded music's most historically significant institutions.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 118 — Class 364 Studios IV: Major Record Labels")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
