#!/usr/bin/env python3
"""Batch 62 — Class 361 Museums I (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/361-Class-361"
FILE_PREFIX = "361"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("acropolis-museum", {
        "summary": "The Acropolis Museum is a world-class archaeological museum in Athens, Greece, opened in 2009 to house the surviving artifacts from the Acropolis of Athens, including sculptures from the Parthenon, Erechtheion, and other temples. Designed by Swiss-American architect Bernard Tschumi, the glass-and-concrete building's transparent ground floor reveals excavated ruins from an ancient Athenian neighborhood, making it a museum built above an archaeological site.\n\nThe museum was designed with deliberate space for the Parthenon Marbles — the sculptures removed by Lord Elgin in 1801-12 and now held in the British Museum in London. The top-floor Parthenon Gallery, oriented at the same angle as the Parthenon itself and with panoramic views of the Acropolis, displays original sculptures alongside cast replicas of those in London, creating a fragmented visual argument for reunification.\n\nWith over 4,000 objects displayed across 14,000 square meters, the museum's collection includes the Caryatid porch statues from the Erechtheion (originals, with one Elgin marble in London replaced by a cast), the Archaic Kore and Kouros statues, and the Parthenon frieze fragments. The museum's construction itself was delayed 30 years by Greek politics and the discovery of archaeological remains, reflecting the complexity of heritage and urban development. Since opening, Greece has intensified calls for Elgin Marble reunification.",
        "causes": ["Greece's long-standing need to house Acropolis artifacts removed from exposed outdoor storage", "Greek state's desire to create internationally credible space for Elgin Marble repatriation argument", "Archaeological discoveries beneath the museum site requiring transparent floor design", "Athens 2004 Olympics providing impetus and funding for cultural infrastructure"],
        "effects": ["World-class facility created compelling argument for Elgin Marble repatriation", "Transparent floor reveals living archaeological site beneath modern museum", "4 million annual visitors made it Greece's most important cultural institution", "International debate over Elgin Marbles intensified following museum's opening"],
        "relationships": [{"entity": "Parthenon", "relationship": "HOUSES_ARTIFACTS_FROM", "note": "Contains surviving Parthenon sculptures with spaces for those still in British Museum"}, {"entity": "Bernard Tschumi", "relationship": "DESIGNED_BY", "note": "Swiss-American architect designed transparent building revealing ruins below"}, {"entity": "British Museum", "relationship": "REPATRIATION_DISPUTE_WITH", "note": "Museum's Parthenon Gallery deliberately frames argument for Elgin Marble return"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Acropolis Museum is both a world-class repository of ancient Greek art and a deliberate political argument for cultural repatriation, making it the center of the most significant global debate about who owns antiquity.", "significanceCategory": "world-changing"},
    }),
    ("american-museum-of-natural-history", {
        "summary": "The American Museum of Natural History (AMNH) in New York City is one of the world's largest natural history museums, founded in 1869, with 45 permanent exhibition halls, over 33 million specimens, and 5 million annual visitors. Its collections cover biodiversity, anthropology, astronomy, geology, and paleontology, and it has produced over 1,000 scientific publications annually through its research departments.\n\nThe museum was founded by Theodore Roosevelt Sr. (father of President Theodore Roosevelt) and other prominent New Yorkers, and the central Theodore Roosevelt Memorial Hall with its equestrian statue outside became a contested symbol of colonial-era natural history museums — the statue was removed in 2022 following criticism of its racial symbolism depicting Roosevelt with an African and a Native American flanking him.\n\nThe museum's collections are foundational to modern science: its meteorite collection is the world's largest; the Rose Center for Earth and Space's Hayden Planetarium has presented cutting-edge cosmology since 1935; Margaret Mead's anthropological work on Pacific cultures was conducted through the museum. The dinosaur halls, including the 94-foot Titanosaur (discovered 2014), are among the world's most complete. The museum was the unlikely setting for the comedy film Night at the Museum (2006), which drove a 20% increase in youth visitors.",
        "causes": ["American scientific ambition requiring world-class natural history institution", "Theodore Roosevelt Sr.'s civic leadership mobilizing New York philanthropists", "19th-century scientific expeditions collecting global biodiversity specimens", "New York City's wealth enabling construction and maintenance of vast collections"],
        "effects": ["33 million specimens created foundational resource for global natural history research", "Theodore Roosevelt statue's 2022 removal reflected changing standards for colonial-era representations", "Hayden Planetarium advanced public understanding of cosmology and space", "Night at the Museum franchise brought millions of young visitors to natural history museums"],
        "relationships": [{"entity": "Theodore Roosevelt", "relationship": "ASSOCIATED_WITH", "note": "Museum named in memory of Theodore Roosevelt Sr.; equestrian statue of President Roosevelt removed 2022"}, {"entity": "Margaret Mead", "relationship": "EMPLOYED", "note": "Cultural anthropologist conducted Pacific research through museum from 1926"}, {"entity": "Hayden Planetarium", "relationship": "CONTAINS", "note": "Rose Center planetarium presents cutting-edge cosmological research"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The American Museum of Natural History's 33 million specimens and century-long scientific research made it foundational to evolutionary biology, anthropology, and cosmology, while its contested statues reflect changing valuations of scientific heritage.", "significanceCategory": "world-changing"},
    }),
    ("hermitage-museum", {
        "summary": "The State Hermitage Museum in St. Petersburg, Russia is one of the world's largest and most prestigious art museums, founded in 1764 by Empress Catherine the Great. Housing over 3 million items across six interconnected buildings including the Winter Palace — former residence of Russian emperors — the Hermitage's collection spans 3 million years of human civilization and includes masterpieces by Leonardo, Rembrandt, Michelangelo, Raphael, and Van Gogh.\n\nCatherine the Great began the collection by purchasing 225 Dutch and Flemish paintings in 1764, then systematically acquired the greatest private collections in Europe over her 34-year reign. She purchased works from Prussia, France, Britain, and other European states, building one of the finest art collections in existence by the time of her death in 1796. The Hermitage became the visible embodiment of Russia's aspiration to be recognized as a European civilization.\n\nThe museum survived the 1917 Revolution, the Siege of Leningrad (1941-1944) during which collections were evacuated to Sverdlovsk, and Soviet ideological pressures. The Hermitage complex — Winter Palace, Small Hermitage, Large Hermitage, New Hermitage, and Hermitage Theater — was built across three centuries and represents the pinnacle of European palatial architecture on Russian soil. The museum's unique character blends unparalleled imperial collections with the building that witnessed the October Revolution in 1917.",
        "causes": ["Catherine the Great's ambition to demonstrate Russia's cultural equivalence with Western Europe", "Strategic bulk purchases of European collections creating instant world-class institution", "Russian imperial wealth enabling unprecedented art acquisition over decades", "St. Petersburg's construction as European-style capital requiring appropriate cultural institutions"],
        "effects": ["3 million items established one of world's most comprehensive art and artifact collections", "Winter Palace's role in 1917 Revolution made museum a site of world-historical events", "Siege of Leningrad evacuation became model for wartime cultural heritage preservation", "Post-Soviet museum became symbol of Russian cultural pride and international engagement"],
        "relationships": [{"entity": "Catherine the Great", "relationship": "FOUNDED_BY", "note": "Catherine began collection with 1764 Dutch and Flemish painting purchase"}, {"entity": "Winter Palace", "relationship": "HOUSED_IN", "note": "Former imperial residence is the museum's main building"}, {"entity": "Siege of Leningrad", "relationship": "SURVIVED", "note": "Collections evacuated to Sverdlovsk 1941-1944 during Nazi siege"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Hermitage embodies Catherine the Great's vision of Russia as a European civilization, its 3 million items representing the most comprehensive imperial art collection in existence and a palace that witnessed the Russian Revolution.", "significanceCategory": "world-changing"},
    }),
    ("guggenheim-museum-bilbao", {
        "summary": "The Guggenheim Museum Bilbao is a contemporary art museum in Bilbao, Spain, designed by Frank Gehry and opened in 1997. Its titanium, glass, and limestone exterior — a seemingly random assemblage of curving shapes that shift appearance with the light — became the most influential building of the late 20th century and created the 'Bilbao Effect': the concept that a single iconic building could transform a city's economy and identity.\n\nFrank Gehry's design used CATIA aerospace software (normally used for aircraft design) to model the complex titanium curves, making Bilbao Guggenheim one of the first major buildings designed using computer-aided manufacturing. The building's extraordinary complexity — 33,000 titanium shingles, each unique — would have been impossible without digital design tools, pioneering a new era of computer-assisted architecture.\n\nThe 'Bilbao Effect' — in which a depressed industrial city in the Basque region tripled tourism, attracted international investment, and transformed its economy within a decade — became a template for urban regeneration through cultural investment. By 1997-2007, the museum generated over €1 billion in economic activity for the Basque Country. Governments worldwide attempted to replicate the model, commissioning 'starchitects' for iconic cultural buildings in hopes of similar transformation, though few achieved Bilbao's impact.",
        "causes": ["Bilbao's industrial decline requiring economic regeneration strategy", "Basque government's cultural investment as economic development strategy", "Frank Gehry's design revolution using CATIA aerospace software for complex curves", "Solomon R. Guggenheim Foundation's expansion strategy requiring European presence"],
        "effects": ["'Bilbao Effect' created global model for cultural-led urban regeneration", "Titanium-cladded curved architecture became dominant language of 21st-century landmark buildings", "Basque economy tripled tourism and attracted investment within decade of opening", "Spawned global trend of commissioning starchitects for cultural institutions"],
        "relationships": [{"entity": "Frank Gehry", "relationship": "DESIGNED_BY", "note": "Gehry's titanium and glass design became most influential building of late 20th century"}, {"entity": "Guggenheim Foundation", "relationship": "OPERATED_BY", "note": "Solomon R. Guggenheim Foundation operates international network including Bilbao"}, {"entity": "Basque Country", "relationship": "TRANSFORMED", "note": "Museum's success created Bilbao Effect transforming regional economy"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Guggenheim Bilbao revolutionized both architectural design (through computer-aided manufacturing) and urban policy (through the Bilbao Effect), making it the most influential single building of the late 20th century.", "significanceCategory": "world-changing"},
    }),
    ("angkor-national-museum", {
        "summary": "The Angkor National Museum in Siem Reap, Cambodia is a world-class archaeological museum dedicated to the Khmer civilization and the Angkor archaeological complex, opened in 2007. Housing over 1,000 artifacts from the Khmer Empire (802-1431 CE) including sculptures, reliefs, and inscriptions, it serves as the educational gateway to the Angkor World Heritage site visited by over 2 million tourists annually.\n\nThe museum presents Khmer civilization chronologically from pre-Angkorian cultures through the empire's height under Jayavarman II, Jayavarman VII, and Suryavarman II. Its Gallery of a Thousand Buddhas contains an extraordinary collection of Buddha images from across the Khmer period, while galleries dedicated to Angkor Wat and Angkor Thom explain the cosmic symbolism of these extraordinary temples.\n\nThe museum opened following a period when UNESCO and international conservation organizations worked to prevent illegal excavation and artifact looting from Angkor sites during and after Cambodia's civil war. The collection includes artifacts repatriated from international auction markets, highlighting the global trade in stolen cultural property. Thai-Cambodian cooperation in the museum reflects broader rapprochement between the two countries over the disputed Preah Vihear temple.",
        "causes": ["Need to educate 2 million annual Angkor visitors about Khmer civilization context", "UNESCO and international pressure to protect and curate Khmer artifacts", "Post-civil war Cambodia's cultural recovery requiring institutional heritage infrastructure", "Repatriation movement demanding return of looted Khmer artifacts"],
        "effects": ["Created world's premier educational resource on Khmer Empire civilization", "Artifact repatriation program recovered stolen pieces from international markets", "Museum tourism supports Cambodia's economic recovery and cultural confidence", "Gallery of 1,000 Buddhas established unique visual record of Khmer Buddhist art"],
        "relationships": [{"entity": "Angkor Wat", "relationship": "INTERPRETS", "note": "Museum provides contextual education for 2+ million Angkor Wat annual visitors"}, {"entity": "Khmer Empire", "relationship": "DEDICATED_TO", "note": "Museum houses and explains artifacts from 802-1431 CE Khmer civilization"}, {"entity": "UNESCO", "relationship": "PARTNERED_WITH", "note": "UNESCO collaboration on artifact protection and repatriation"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Angkor National Museum's mission to protect, repatriate, and present Khmer artifacts reflects Cambodia's cultural recovery after decades of war and the global challenge of preserving archaeological heritage against illicit trade.", "significanceCategory": "regional"},
    }),
    ("national-gallery-of-canada", {
        "summary": "The National Gallery of Canada in Ottawa is the country's premier art museum, founded in 1880 and now housed in a striking Moshe Safdie building of glass and granite since 1988. With over 75,000 works spanning Canadian, Inuit, and international art, it is the most visited museum in Canada's capital and houses the world's largest collection of Canadian art, including key works by the Group of Seven.\n\nFounded by the Marquess of Lorne in 1880 to encourage the fine arts in Canada, the gallery moved several times before commissioning architect Moshe Safdie for its permanent home on Sussex Drive. Safdie's design of geometric glass pavilions — inspired by crystal structures and connected indoor gardens — created one of Canada's most celebrated public buildings. The exterior's glass-encased neo-Gothic arcade mirrors the adjacent Parliament buildings.\n\nThe gallery's collection reflects Canada's complex identity: European masters (Rembrandt, El Greco, Rubens) alongside Indigenous and Inuit art galleries that present centuries of non-European artistic traditions; the Group of Seven's defining Canadian landscape paintings; and contemporary international art including the controversial 1990 purchase of Barnett Newman's Voice of Fire for $1.76 million (Canadian), which sparked a national debate about public arts funding. The museum holds the only Raphael painting in the Western Hemisphere.",
        "causes": ["Marquess of Lorne's cultural ambition to establish Canadian cultural institutions", "Canada's need for national art collection representing growing national identity", "Government of Canada's cultural investment in the capital as national identity project", "Moshe Safdie commission creating distinctly Canadian architectural monument"],
        "effects": ["World's largest collection of Canadian art including all major Group of Seven works", "Only Raphael painting in Western Hemisphere making it continental center for Renaissance art", "1990 Voice of Fire controversy sparked national debate on arts funding", "Moshe Safdie's glass pavilion became architectural landmark of Ottawa"],
        "relationships": [{"entity": "Group of Seven", "relationship": "HOUSES_WORKS_OF", "note": "Largest collection of Group of Seven Canadian landscape paintings"}, {"entity": "Moshe Safdie", "relationship": "DESIGNED_BY", "note": "Safdie's 1988 glass and granite building is Canada's premier cultural landmark"}, {"entity": "Raphael", "relationship": "HOLDS_ONLY_WESTERN_HEMISPHERE_WORK_BY", "note": "The Holy Family with a Lamb (1507) is the only Raphael in the Western Hemisphere"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The National Gallery of Canada is the primary custodian of Canadian artistic identity, housing the world's largest collection of Canadian art while Safdie's iconic building defines Ottawa's cultural landscape.", "significanceCategory": "regional"},
    }),
    ("chicago-history-museum", {
        "summary": "The Chicago History Museum, founded in 1856, is one of America's oldest historical societies and the primary repository of Chicago's and Illinois's history. Located in Lincoln Park, it houses over 23 million documents, photographs, artifacts, and works of art spanning from Native American cultures and early American exploration to contemporary Chicago urban history.\n\nFounded two years before Chicago was incorporated as a city, the Historical Society was destroyed in the Great Chicago Fire of 1871 — losing virtually its entire collection — then rebuilt. The museum's rebirth after the Fire made it an institution deeply identified with Chicago's most defining trauma and its remarkable recovery: a city that destroyed and rebuilt itself became the prototype for American urban resilience.\n\nThe museum's collection includes Abraham Lincoln's deathbed, pieces from the Chicago Fire, an extensive Civil War collection, and comprehensive documentation of Chicago's labor movement (the Haymarket Affair of 1886), jazz and blues history, architectural history, and the city's immigrant communities. The Great Chicago Fire Collection and the 1968 Democratic Convention materials make it indispensable for American social and political history. The 1968 convention — where police clashed with anti-Vietnam War protesters outside the museum's Lincoln Park neighborhood — left lasting marks on American political culture.",
        "causes": ["Chicago's rapid 1840s-50s growth requiring historical documentation of the new metropolis", "1871 Great Fire creating urgent mission to preserve what remained of the city's record", "Chicago's position as America's second city generating major social, political, and labor history", "Abraham Lincoln's Illinois connections making Lincoln materials natural collecting focus"],
        "effects": ["Preserved primary documentation of America's most dynamic 19th-century city", "Chicago Fire collection became national symbol of urban resilience and recovery", "Labor history collections document Haymarket Affair and American workers' rights movement", "1968 Democratic Convention materials preserved pivotal moment in American political history"],
        "relationships": [{"entity": "Great Chicago Fire", "relationship": "AFFECTED_BY", "note": "1871 fire destroyed original collection; rebuilding made museum symbol of Chicago's resilience"}, {"entity": "Abraham Lincoln", "relationship": "HOLDS_ARTIFACTS_OF", "note": "Museum houses Abraham Lincoln's deathbed and extensive Lincoln collection"}, {"entity": "Haymarket Affair", "relationship": "DOCUMENTS", "note": "Comprehensive documentation of 1886 labor movement event"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Chicago History Museum documents America's most dynamic industrial city through its triumphs (the Chicago School of architecture, jazz and blues, labor movement) and tragedies (the Great Fire, Haymarket, 1968 convention).", "significanceCategory": "regional"},
    }),
    ("academy-museum-of-motion-pictures", {
        "summary": "The Academy Museum of Motion Pictures in Los Angeles is the world's largest museum dedicated to the history and science of filmmaking, opened in 2021 after a $388 million renovation of the former May Company building. Created by the Academy of Motion Picture Arts and Sciences — the organization that presents the Oscars — it houses over 13 million objects in the world's most comprehensive film archive.\n\nThe museum's design by Italian architect Renzo Piano added a new spherical glass structure containing the 1,000-seat David Geffen Theater and the Dolby Family Terrace, connected to the 1939 Streamline Moderne building by glass bridges. The opening exhibition, 'Stories of Cinema,' presented 200 years of cinematic history through artifacts including Dorothy's ruby slippers from The Wizard of Oz, Rosebud from Citizen Kane, and Darth Vader's helmet from Star Wars.\n\nThe museum opened to controversy over its representation of marginalized communities: the original opening exhibition was criticized for underrepresenting Black filmmakers, Japanese-American cinema, and other non-Western traditions. The 'Backdrop' exhibition on the history of racist portrayals in Hollywood, and dedicated programs on Japanese-American cinema and Latin representation, reflected reckonings with Hollywood's complex racial history. Annual Oscar screenings and education programs make it the educational hub of the global film industry.",
        "causes": ["Academy of Motion Picture Arts and Sciences' mission to celebrate filmmaking history", "Los Angeles's centrality to global film production requiring institutional home", "13-million-item archive needing world-class display and access infrastructure", "Renzo Piano's spherical theater creating landmark cultural destination in Los Angeles"],
        "effects": ["World's largest film museum creating definitive resource on cinema history", "Exhibition on racist Hollywood representations contributed to industry reckoning", "Ruby slippers, Rosebud, and Vader's helmet became pilgrimage objects for film culture", "Academy Museum established Los Angeles as hub of film heritage tourism"],
        "relationships": [{"entity": "Academy of Motion Picture Arts and Sciences", "relationship": "OPERATED_BY", "note": "Museum founded and operated by the Oscar-awarding Academy"}, {"entity": "Renzo Piano", "relationship": "DESIGNED_BY", "note": "Italian architect added spherical glass theater to 1939 Streamline Moderne building"}, {"entity": "Hollywood", "relationship": "DOCUMENTS", "note": "13 million objects document the complete history of Hollywood filmmaking"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Academy Museum is the world's most comprehensive film archive, created by Hollywood's own institution to grapple with cinema's century of both artistic achievement and racial representation failures.", "significanceCategory": "continental"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 62 — Class 361 Museums I")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
