#!/usr/bin/env python3
"""Batch 141 — Class 316 Parties X: Balkan & Central Asian Political Parties (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/316-Class-316"
FILE_PREFIX = "316"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("azerbaijani-popular-front", {
        "summary": "The Azerbaijan Popular Front Party (APFP, Azərbaycan Xalq Cəbhəsi Partiyası), founded in 1988-1989 as the Popular Front of Azerbaijan during the late Soviet period — was the driving force behind Azerbaijan's independence movement and briefly held power under Abulfaz Elchibey (1992-1993) before being overthrown in a coup supported by Heydar Aliyev, whose subsequent dynasty has ruled Azerbaijan continuously. The Popular Front's brief nationalist democratic government represented the high point of Azerbaijani liberal democratic politics.\n\nThe Popular Front emerged in the context of Gorbachev's glasnost and perestroika reforms, organizing mass protests and eventually taking over the Azerbaijani Supreme Soviet. The Nagorno-Karabakh conflict — the disputed Armenian-majority enclave within Azerbaijan's Soviet-era borders — was central to the Popular Front's politics, as Armenian-Azerbaijani ethnic violence and the Soviet government's perceived favoritism toward Armenia galvanized Azerbaijani nationalist sentiment.\n\nElchibey's 1992-1993 presidency was cut short by the Gangut coup (supported by Heydar Aliyev, former KGB chief and Soviet-era Azerbaijani Communist Party leader) in June 1993, when military commander Surat Huseynov rebelled and Aliyev took power. Aliyev established an authoritarian dynasty that his son Ilham Aliyev continues: the APFP became opposition and has faced systematic repression. Elchibey's brief democratic government represents a historical counterfactual for Azerbaijan — a democratic path the country briefly attempted before authoritarian consolidation.",
        "causes": ["Gorbachev's glasnost creating space for Popular Front movements across Soviet republics including Azerbaijan", "Nagorno-Karabakh conflict galvanizing Azerbaijani nationalist sentiment and mass political organization", "Azerbaijan's independence movement requiring political organization capable of replacing Communist party rule", "Soviet Union's collapse creating conditions for new independent Azerbaijani state requiring nationalist political leadership"],
        "effects": ["Popular Front leading Azerbaijan to independence and Elchibey's 1992 democratic presidency", "1993 Gangut coup overthrowing Elchibey and establishing Aliyev dynasty that rules Azerbaijan today", "APFP's opposition role under systematic repression demonstrating the failure of Azerbaijan's democratic transition", "Azerbaijani democratic politics represented by APFP remaining in opposition against Aliyev authoritarianism"],
        "relationships": [{"entity": "Abulfaz Elchibey", "relationship": "LED_BY_FIRST_DEMOCRATICALLY_ELECTED_AZERBAIJANI_PRESIDENT", "note": "Elchibey led the Popular Front and briefly served as Azerbaijan's first democratically elected president (1992-1993)"}, {"entity": "Heydar Aliyev", "relationship": "OVERTHROWN_BY_COUP_SUPPORTED_BY_DYNASTY_FOUNDED_BY", "note": "Aliyev's coup overthrew the Popular Front government in 1993, establishing the authoritarian dynasty that rules Azerbaijan today"}, {"entity": "Nagorno-Karabakh Conflict", "relationship": "AZERBAIJANI_NATIONALIST_POLITICS_SHAPED_BY_DISPUTE_OVER", "note": "The Nagorno-Karabakh conflict was central to the Popular Front's founding and Azerbaijani nationalist politics"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Azerbaijani Popular Front — briefly holding power under Elchibey before the Aliyev coup established the authoritarian dynasty still ruling today — is historically significant as Azerbaijan's lost democratic moment and the political movement that could have established a different post-Soviet trajectory.", "significanceCategory": "world-changing"},
    }),
    ("bashkir-agrarian-party", {
        "summary": "The Bashkir Agrarian Party was a regional political party operating in the Republic of Bashkortostan in the Russian Federation — one of many regional and ethnic-based parties that emerged in the Russian Federation's regions during the 1990s period of regional political experimentation and 'parade of sovereignties' before Vladimir Putin's subsequent recentralization of federal authority marginalized regional political autonomy.\n\nBashkortostan (Bashkir Republic) is one of the Russian Federation's most significant ethnic republics: home to the Bashkir people (a Turkic ethnic group with their own language, Bashkir, and significant cultural traditions), Bashkortostan also has large Russian and Tatar minorities and sits on significant oil reserves in the southern Urals. The republic's political development in the 1990s involved significant autonomy under President Murtaza Rakhimov, who maintained a degree of regional semi-independence during the Yeltsin era.\n\nThe Bashkir Agrarian Party, representing agricultural interests in the region, reflects the broader pattern of Russian regional politics in the 1990s: when Boris Yeltsin needed regional support and gave regions significant autonomy ('take as much sovereignty as you can swallow'), regional political parties and interest groups proliferated. Putin's subsequent federal reforms (vertical of power, gubernatorial appointment system, elimination of regional parties) effectively ended this regional political pluralism.",
        "causes": ["Yeltsin's 'parade of sovereignties' giving Russian regions autonomy to develop regional political organizations", "Bashkortostan's agricultural economy requiring political representation for farming interests in the regional assembly", "Bashkir ethnic republic's political autonomy in the 1990s creating space for regional party formation", "Russian Federation's 1990s regional political experimentation before Putin's recentralization"],
        "effects": ["Regional agricultural political representation in Bashkortostan's assembly during the 1990s autonomy period", "Putin's federal reforms eliminating regional parties and recentralizing political authority", "Bashkir regional political pluralism ended by federal reforms eliminating sub-federal political parties", "Agricultural interests in Bashkortostan subsequently absorbed into United Russia's dominant party structure"],
        "relationships": [{"entity": "Bashkortostan", "relationship": "REGIONAL_AGRICULTURAL_PARTY_OPERATING_WITHIN_RUSSIAN_REPUBLIC_OF", "note": "The Bashkir Agrarian Party operated within Bashkortostan's regional political system during the 1990s autonomy period"}, {"entity": "Russian Federation Regional Politics", "relationship": "TYPICAL_REGIONAL_PARTY_OF_1990S_AUTONOMY_PERIOD_IN", "note": "The party is typical of the regional parties that proliferated in Russian Federation regions during Yeltsin's autonomy era"}, {"entity": "Vladimir Putin", "relationship": "REGIONAL_PARTY_SYSTEM_ENDED_BY_FEDERAL_REFORMS_OF", "note": "Putin's federal reforms eliminated the regional party system within which the Bashkir Agrarian Party operated"}],
        "historicalSignificance": {"significanceScore": 3, "significanceNarrative": "The Bashkir Agrarian Party — a regional agricultural party in the 1990s Russian Federation's brief period of regional political pluralism — is locally significant as a documentation of Russia's lost regional democratic experiment before Putin's recentralization.", "significanceCategory": "local"},
    }),
    ("bolivian-socialist-falange", {
        "summary": "The Bolivian Socialist Falange (FSB, Falange Socialista Boliviana), founded in 1937 by Oscar Unzaga de la Vega — was a right-wing nationalist political party inspired by the Spanish Falange movement and Bolivian nationalism, representing one of Latin America's more significant fascist-influenced political organizations of the mid-20th century. The FSB competed in Bolivian politics during the turbulent post-Chaco War era and was a major player in Bolivia's political crises of the 1940s-1960s.\n\nBolivia's post-Chaco War period (after the catastrophic 1932-1935 war with Paraguay that cost approximately 65,000 Bolivian lives) was politically volatile, with the war's traumatic defeat generating intense nationalist sentiment that spawned multiple nationalist movements, including the National Revolutionary Movement (MNR) on the left-nationalist side and the FSB on the right-nationalist side. The FSB drew inspiration from European fascism and combined nationalism, anti-communism, and Catholic conservatism with a corporatist economic vision.\n\nThe FSB was involved in several attempted coups and political crises in Bolivia, and competed with the MNR for nationalist political space. After the 1952 MNR Revolution (which introduced land reform, nationalized the tin mines, and extended universal suffrage), the FSB remained an opposition force. The party gradually evolved and declined as Bolivian politics transformed, though it remained active for decades. It represented the right-nationalist tradition in a country where political violence and instability were endemic for most of the 20th century.",
        "causes": ["Chaco War's catastrophic defeat galvanizing Bolivian nationalist sentiment and spawning multiple nationalist parties", "Spanish Falange ideology inspiring right-wing nationalist movements across Latin America including Bolivia's FSB", "Oscar Unzaga de la Vega's 1937 founding inspired by European fascism and Bolivian conservative nationalism", "Post-war political chaos in Bolivia requiring organized right-nationalist party to compete with left-nationalist MNR"],
        "effects": ["FSB as major right-nationalist political player in Bolivia's turbulent 1940s-1960s political crises", "MNR Revolution of 1952 marginalizing the FSB as the left-nationalist vision triumphed", "FSB's involvement in coup attempts reflecting Bolivia's endemic political violence and instability", "Bolivian right-nationalist tradition represented by FSB eventually evolving and declining in subsequent decades"],
        "relationships": [{"entity": "Chaco War", "relationship": "NATIONALIST_RESPONSE_MOVEMENT_TO_CATASTROPHIC_DEFEAT_IN", "note": "The FSB was founded as part of Bolivia's nationalist political response to the traumatic Chaco War defeat"}, {"entity": "Spanish Falange", "relationship": "IDEOLOGICAL_INSPIRATION_AND_MODEL_FOR_BOLIVIAN_FSB", "note": "The FSB drew directly from the Spanish Falange movement's nationalist, anti-communist, and corporatist ideology"}, {"entity": "MNR Revolution 1952", "relationship": "MAJOR_OPPONENT_OF_LEFT-NATIONALIST_REVOLUTION_THAT_MARGINALIZED_FSB", "note": "The 1952 MNR Revolution implementing land reform and nationalization triumphed over FSB's right-nationalist alternative"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Bolivian Socialist Falange — a right-nationalist fascist-inspired party competing in Bolivia's post-Chaco War turbulence, opposing the 1952 MNR Revolution — is historically significant as a documentation of fascist political movements in Latin America and Bolivia's violent 20th-century political history.", "significanceCategory": "continental"},
    }),
    ("bharatiya-janata-party", {
        "summary": "The Bharatiya Janata Party (BJP, भारतीय जनता पार्टी, meaning 'Indian People's Party'), founded in 1980 from the ruins of the Janata Party — is India's dominant right-wing Hindu nationalist political party, currently the world's largest political party by membership (approximately 180 million members) and the governing party of India under Prime Minister Narendra Modi since 2014. The BJP represents the political expression of Hindu nationalism (Hindutva ideology) developed by the Rashtriya Swayamsevak Sangh (RSS) organizational ecosystem.\n\nThe BJP's ideological foundations trace to the RSS (founded 1925), the Vishwa Hindu Parishad (VHP, 1964), and other organizations of the Sangh Parivar (family of RSS-affiliated organizations) that advocate for Hindu Rashtra (Hindu nation) as the vision for India. The BJP was the political wing of this broader Hindutva movement, though the party's mainstream positioning often softens the harder-edge Hindutva positions of affiliated organizations.\n\nNarendra Modi's 2014 and 2019 election victories with large majorities represented a historic shift in Indian politics: BJP governments have pursued Hindu nationalist policies including the revocation of Jammu and Kashmir's special constitutional status (Article 370, 2019), the Citizenship Amendment Act (2019), and the Ram Temple construction at Ayodhya (consecrated 2024) on the disputed site of the demolished Babri Masjid. Critics argue India's secular democratic character is under threat; supporters argue these represent rightful assertions of Hindu cultural heritage. The BJP's period is one of Indian history's most consequential political transformations.",
        "causes": ["1980 founding from Janata Party collapse as vehicle for Hindu nationalist politics in India", "RSS organizational infrastructure providing membership, ideological training, and electoral ground organization", "1992 Babri Masjid demolition by Hindu nationalists galvanizing Hindu nationalist politics toward BJP", "Narendra Modi's Gujarat model of economic development and Hindu nationalism attracting aspirational voters"],
        "effects": ["BJP becoming India's dominant party and the world's largest political party by membership under Modi", "Revocation of Jammu and Kashmir's Article 370 special constitutional status (2019)", "Citizenship Amendment Act (2019) critics argue discriminatorily excludes Muslims from citizenship fast-track", "Ram Temple construction at Ayodhya (2024) representing Hindutva's most symbolic political achievement"],
        "relationships": [{"entity": "Rashtriya Swayamsevak Sangh", "relationship": "POLITICAL_WING_OF_BROADER_HINDUTVA_MOVEMENT_LED_BY", "note": "The BJP is the electoral political expression of the RSS's Hindu nationalist movement and Sangh Parivar ecosystem"}, {"entity": "Narendra Modi", "relationship": "PRIME_MINISTER_LED_TO_HISTORIC_2014_2019_VICTORIES_BY", "note": "Modi's leadership brought BJP to large parliamentary majorities in 2014 and 2019, making him India's dominant political figure"}, {"entity": "India's Secular Constitution", "relationship": "GOVERNING_PARTY_CRITICS_ARGUE_IS_UNDERMINING_SECULAR_FOUNDATIONS_OF", "note": "Critics argue BJP policies (CAA, Article 370 revocation, Ram Temple) are undermining India's secular constitutional foundations"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Bharatiya Janata Party — India's dominant Hindu nationalist party, world's largest party by membership, implementing transformative policies under Modi — is historically significant as one of the most consequential political transformations in India's post-independence history.", "significanceCategory": "world-changing"},
    }),
    ("communist-party-of-nepal-unified-marxist-leninist", {
        "summary": "The Communist Party of Nepal (Unified Marxist-Leninist) (CPN-UML), formed in 1991 through the merger of several communist parties after Nepal's 1990 People's Movement (Jana Andolan) that ended the Panchayat system and restored democracy — is one of Nepal's two dominant parties alongside the Nepali Congress, representing the mainstream of Nepalese democratic left politics in a country where communist parties have been electorally extremely successful.\n\nNepal's unusual political landscape features communist parties as mainstream electoral forces rather than marginal radical movements: the CPN-UML and the related CPN (Maoist Centre) — the former Maoist insurgency that fought the 10-year civil war (1996-2006) and then entered mainstream politics after the 2006 Comprehensive Peace Agreement — together dominate Nepalese politics. Nepal has had communist prime ministers for significant periods, making it one of the few functioning democracies where communist parties regularly win elections.\n\nThe CPN-UML has been a central actor in Nepal's extraordinary political transformation: from a Hindu monarchy with the Panchayat system, through the 1990 democracy restoration, through the 2001 royal massacre (King Birendra and his family killed by Crown Prince Dipendra), through the Maoist civil war, through the 2006 peace agreement and 2008 abolition of the monarchy, to the establishment of Nepal as a federal democratic republic. The CPN-UML has held power multiple times including under Prime Minister K.P. Sharma Oli.",
        "causes": ["1990 Jana Andolan (People's Movement) restoring multiparty democracy and creating space for communist electoral participation", "1991 merger of communist parties creating unified mainstream left party capable of winning elections", "Nepal's left-leaning political culture supporting communist parties as normal electoral forces", "Post-Maoist civil war (1996-2006) peace process incorporating former rebels into mainstream politics alongside UML"],
        "effects": ["CPN-UML as one of Nepal's two dominant parties governing Nepal through multiple administrations", "Nepal's establishment as a federal democratic republic partly through CPN-UML's parliamentary role", "Communist-led government in a functioning democracy demonstrating Nepal's unusual electoral left politics", "Nepal's monarchy abolished (2008) with CPN-UML supporting the federal republican transformation"],
        "relationships": [{"entity": "Nepal", "relationship": "ONE_OF_TWO_DOMINANT_PARTIES_GOVERNING_DEMOCRATIC_REPUBLIC_OF", "note": "CPN-UML is one of Nepal's two dominant parties, having governed the country through multiple administrations"}, {"entity": "1990 Jana Andolan", "relationship": "DEMOCRACY_RESTORED_BY_ENABLING_COMMUNIST_PARTY_ELECTORAL_PARTICIPATION", "note": "The 1990 People's Movement restored democracy that enabled the CPN-UML's formation and electoral participation"}, {"entity": "Nepal Monarchy Abolition", "relationship": "PARLIAMENTARY_SUPPORTER_OF_2008", "note": "CPN-UML supported the 2008 abolition of Nepal's monarchy and establishment of a federal democratic republic"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Communist Party of Nepal (UML) — one of Nepal's two dominant parties in one of democracy's most unusual electoral landscapes where communists regularly govern — is historically significant as a monument to Nepal's extraordinary political transformation from Hindu monarchy to federal democratic republic.", "significanceCategory": "world-changing"},
    }),
    ("democratic-alliance-of-hungarians-in-romania", {
        "summary": "The Democratic Alliance of Hungarians in Romania (DAHR, Romanian: Uniunea Democrată Maghiară din România, UDMR; Hungarian: Romániai Magyar Demokrata Szövetség, RMDSZ), founded in 1989 following Romania's December Revolution — is the primary political organization representing Romania's Hungarian minority (approximately 1.2 million ethnic Hungarians, roughly 6% of Romania's population, primarily in Transylvania) and one of the most successful ethnic minority political parties in post-Communist Eastern Europe.\n\nTransylvania's Hungarian minority is one of Europe's most significant: Transylvania was part of Hungary until the 1920 Treaty of Trianon (which awarded Transylvania to Romania), and the Hungarian population that remained became Romania's largest ethnic minority. The DAHR has been an extraordinary success story in minority political representation: participating in governing coalitions multiple times, successfully negotiating Hungarian-language educational rights at multiple levels, and maintaining a consistent parliamentary presence for over 30 years.\n\nThe DAHR's governance participations have been crucial for Romanian democratic consolidation: by incorporating the Hungarian minority party into governing coalitions, Romania avoided the ethnic minority exclusion that generated serious conflicts in some other post-Communist states. DAHR's cooperative approach (accepting Romanian statehood while advocating minority cultural and language rights) is often contrasted with more confrontational minority politics elsewhere and cited as a positive model for minority-majority accommodation in multi-ethnic states.",
        "causes": ["1989 Romanian Revolution creating political space for founding DAHR as Hungarian minority political representation", "Transylvanian Hungarian minority's need for political advocacy after becoming Romania's largest ethnic minority in 1920", "Post-Communist Romania's democratic transition requiring inclusive minority political participation to ensure stability", "Hungarian minority's demands for language rights, cultural autonomy, and educational institutions in Romanian system"],
        "effects": ["DAHR as most successful ethnic minority party in post-Communist Eastern Europe maintaining 30+ years of parliamentary presence", "Hungarian-language educational rights including university (Babes-Bolyai's Hungarian-language instruction) achieved through DAHR advocacy", "DAHR's coalition participations contributing to Romanian democratic consolidation by including minority party in governance", "DAHR model cited as positive example of minority-majority accommodation in multi-ethnic European democracies"],
        "relationships": [{"entity": "Romanian Hungarians", "relationship": "PRIMARY_POLITICAL_REPRESENTATIVE_OF_TRANSYLVANIAN_MINORITY", "note": "DAHR has been the primary political organization for Romania's 1.2 million ethnic Hungarians for 30+ years"}, {"entity": "Transylvania", "relationship": "ADVOCATES_FOR_HUNGARIAN_MINORITY_RIGHTS_IN", "note": "DAHR represents the Hungarian community in Transylvania that became a Romanian minority after the 1920 Treaty of Trianon"}, {"entity": "Romanian Democratic Consolidation", "relationship": "MINORITY_COALITION_PARTICIPANT_CONTRIBUTING_TO", "note": "DAHR's governance coalition participations contributed to Romania's democratic consolidation by including the Hungarian minority in power"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Democratic Alliance of Hungarians in Romania — the most successful ethnic minority party in post-Communist Eastern Europe, governing coalition participant for 30+ years — is historically significant as a monument to successful minority-majority political accommodation and a model for multiethnic democratic societies.", "significanceCategory": "world-changing"},
    }),
    ("communist-party-of-india-marxist", {
        "summary": "The Communist Party of India (Marxist) (CPI(M) or CPM), founded in 1964 following a split with the Communist Party of India — is one of India's most significant left-wing political parties and one of the world's longest-governing communist parties in a democratic system, having ruled West Bengal continuously from 1977 to 2011 (34 years under the Left Front coalition) and Kerala multiple times, making these states extraordinary laboratories for democratic communist governance in a developing country.\n\nThe CPI(M)'s 34-year uninterrupted rule of West Bengal under the Left Front coalition was one of democracy's longest single-party or coalition dominances — eventually ended by Mamata Banerjee's Trinamool Congress in 2011. The West Bengal government implemented land reform (Operation Barga, 1978-79 — registering approximately 1.4 million sharecroppers and securing their tenancy rights), decentralization through panchayati raj institutions, and literacy programs. Critics also noted increasing political violence, party machine entrenchment, and eventually the Singur and Nandigram controversies over industrial land acquisition.\n\nKerala under CPI(M) governance represents a different but equally significant achievement: Kerala has achieved extraordinary social development outcomes (near-universal literacy, high life expectancy, strong female education) that have been called the 'Kerala Model' — demonstrating that social investment through state policy can achieve developmental indicators comparable to wealthy countries even at low income levels. The 'Kerala Model' has been widely studied internationally as evidence of alternative development paths.",
        "causes": ["1964 split from Communist Party of India over ideological differences and strategic direction under Soviet vs Chinese influence", "West Bengal's peasant movement and left politics providing electoral base for the CPI(M)'s 34-year governance", "Kerala's labor movement and Nair-Ezhava caste alliance providing CPI(M)'s strong social base in South India", "Land reform agenda and peasant mobilization as the organizational foundation of the party's electoral success"],
        "effects": ["CPI(M) West Bengal governance implementing Operation Barga land reform securing rights for 1.4 million sharecroppers", "34-year West Bengal Left Front rule as one of democracy's longest single coalition dominances", "Kerala Model of social development demonstrating social investment paths to high human development despite low income", "CPI(M) political machine's entrenchment and political violence ultimately contributing to 2011 West Bengal electoral defeat"],
        "relationships": [{"entity": "West Bengal", "relationship": "GOVERNING_PARTY_FOR_34_CONSECUTIVE_YEARS_IN", "note": "CPI(M)-led Left Front governed West Bengal continuously from 1977-2011, implementing land reform and decentralization"}, {"entity": "Kerala Model", "relationship": "COMMUNIST_GOVERNANCE_CREDITED_WITH_DEVELOPING", "note": "CPI(M)'s Kerala governance is credited with developing the 'Kerala Model' of social development with exceptional outcomes"}, {"entity": "Operation Barga", "relationship": "IMPLEMENTED_LAND_REFORM_SECURING_TENANT_RIGHTS_THROUGH", "note": "CPI(M)'s West Bengal government implemented Operation Barga in 1978-79, securing land rights for 1.4 million sharecroppers"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Communist Party of India (Marxist) — implementing the Kerala Model of social development and 34-year West Bengal governance — is historically significant as one of the world's most successful democratic communist parties and a living experiment in progressive governance within India's democratic system.", "significanceCategory": "world-changing"},
    }),
    ("democratic-progressive-party-taiwan", {
        "summary": "The Democratic Progressive Party (DPP, 民主進步黨, Mínzhǔ Jìnbù Dǎng), founded in 1986 as Taiwan's first opposition party under martial law — broke the Kuomintang's (KMT) 40-year monopoly on political power and has become one of Taiwan's two dominant parties, representing the Taiwan independence/Taiwanese identity strand of Taiwanese politics, governing Taiwan under Presidents Chen Shui-bian (2000-2008) and Tsai Ing-wen (2016-2024) and winning the 2024 presidential election.\n\nThe DPP's founding in September 1986 was an act of political courage: martial law remained in effect until 1987, and forming a political party outside the KMT was technically illegal. The KMT government's decision not to suppress the new party was itself a significant indicator of the liberalization that would lead to formal democratization. The DPP represented the Tangwai (outside the party) democratic opposition movement that had been pushing for Taiwanese democratization throughout the 1970s-1980s.\n\nThe DPP's core political identity is the question of Taiwan's status: the party broadly favors formal Taiwanese independence or at minimum resistance to unification with the People's Republic of China, reflecting the identity politics of the Taiwan independence (本土派, nativist) wing. This contrasts with the KMT's traditional (though evolving) preference for eventual Chinese unification. The DPP's political positions have significant geopolitical implications for cross-strait relations and the perpetually tense relationship between Taiwan, the PRC, and the United States.",
        "causes": ["1986 founding as illegal opposition party breaking KMT's 40-year political monopoly under martial law Taiwan", "Tangwai democratic opposition movement providing the political foundation and personnel for the DPP", "Taiwan's democratization process (martial law lifted 1987, multiparty elections beginning 1991) creating legal space for the DPP", "Taiwanese identity politics and independence sentiment providing the party's core electoral base"],
        "effects": ["DPP's 2000 election victory ending KMT's 55-year monopoly on the presidency under Chen Shui-bian", "Taiwan's democratic consolidation partly achieved through DPP-KMT competitive party system", "Cross-strait tensions heightened by DPP governance's resistance to Beijing's unification pressure", "DPP model as inspiration for opposition movements against authoritarian party rule in Asia"],
        "relationships": [{"entity": "Taiwan Democratization", "relationship": "DRIVING_FORCE_AND_BENEFICIARY_OF", "note": "The DPP was both a driver of Taiwan's democratization and the major beneficiary of the democratic system it helped create"}, {"entity": "People's Republic of China", "relationship": "PRINCIPAL_RESISTANCE_AGAINST_UNIFICATION_PRESSURE_FROM", "note": "The DPP's core position of resisting unification with the PRC creates the party's fundamental geopolitical significance"}, {"entity": "Kuomintang", "relationship": "TWO-PARTY_COMPETITOR_THAT_BROKE_MONOPOLY_OF", "note": "The DPP broke the KMT's political monopoly and became its main democratic competitor in Taiwan's two-party dominated system"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Democratic Progressive Party Taiwan — founded illegally under martial law, ending KMT's 55-year presidential monopoly, governing in perpetual tension with Beijing — is historically significant as the political force most central to Taiwan's democratic transformation and its geopolitically consequential relationship with the PRC.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 141 — Class 316 Parties X: Balkan & Central Asian Political Parties")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
