#!/usr/bin/env python3
"""Batch 114 — Class 311 Parliaments II: Cabinets, Councils & Assemblies (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/311-Class-311"
FILE_PREFIX = "311"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("cabinet-of-brazil", {
        "summary": "The Cabinet of Brazil (Conselho de Ministros), the executive body comprising the President of Brazil and the ministers heading federal ministries, operates within Brazil's presidential system established by the 1988 Federal Constitution — a democratic constitution adopted after 21 years of military dictatorship (1964-1985) and designed with specific provisions to prevent executive overreach while enabling effective governance of the world's fifth-largest country.\n\nBrazil's cabinet functions within a complex presidential-legislative relationship: the President appoints ministers and sets policy, but in Brazil's highly fragmented multi-party system (with 25+ parties typically represented in the legislature), governing requires building extensive congressional coalitions. This dynamic has produced what scholars call 'coalitional presidentialism' — the President typically distributes ministerial positions as bargaining chips to secure legislative support from coalition parties, making Brazil's cabinet a coalition-management mechanism as much as a governance tool.\n\nThe cabinet has reflected Brazil's major political transitions: the return of civilian government under José Sarney (1985), the economic stabilization under Fernando Henrique Cardoso's Plano Real (1994), the Workers' Party governments of Lula and Dilma (2003-2016), the traumatic Dilma Rousseff impeachment (2016), and Bolsonaro's military-heavy administration (2019-2022). Lula's third-term cabinet (2023-) reflects the complex of parties needed to govern in Brazil's fragmented legislature, with ministers drawn from across the political spectrum from Workers' Party to center-right parties.",
        "causes": ["1988 Federal Constitution establishing Brazil's presidential system after military dictatorship", "Multi-party fragmentation requiring coalition cabinet construction for legislative majority", "Presidential system giving President cabinet appointment power as central political resource", "Redemocratization creating institutional design choices balancing executive power with legislative control"],
        "effects": ["Coalitional presidentialism as Brazil's distinctive governance model requiring multi-party cabinet coalitions", "Ministerial portfolios as bargaining chips shaping Brazilian party system incentives", "Dilma Rousseff impeachment (2016) demonstrating cabinet coalition management failures' political consequences", "Cabinet composition reflecting major political-economic shifts from Lula's Workers' Party to Bolsonaro's military-heavy government"],
        "relationships": [{"entity": "President of Brazil", "relationship": "APPOINTED_BY_AND_SERVES_UNDER", "note": "Brazil's cabinet ministers are appointed by and serve at the pleasure of the President"}, {"entity": "Brazilian Federal Constitution of 1988", "relationship": "ESTABLISHED_BY", "note": "The 1988 constitution, adopted after military dictatorship, defines Brazil's presidential cabinet system"}, {"entity": "Workers' Party", "relationship": "FORMED_GOVERNMENT_THROUGH", "note": "The PT under Lula (2003-2010, 2023-) formed major cabinets that transformed Brazil's social policy"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Brazil's cabinet — the executive instrument of the world's fifth-largest country, operating within a distinctive coalitional presidentialism model, and reflecting the full arc from military dictatorship redemocratization to Workers' Party social programs to political crisis — is central to understanding Latin America's largest democracy.", "significanceCategory": "world-changing"},
    }),
    ("cabinet-of-malaysia", {
        "summary": "The Cabinet of Malaysia (Jemaah Menteri), established under the Westminster-model constitutional monarchy inherited from British colonial rule (with Malaysian independence in 1957), is the principal executive decision-making body comprising the Prime Minister (typically the leader of the majority coalition in parliament) and appointed ministers — and has operated primarily under the Barisan Nasional (National Front) coalition's dominance from 1957 to 2018, when Malaysia's first-ever opposition victory ended one of Asia's longest single-coalition governing runs.\n\nMalaysia's cabinet operates within a distinctive political context: the constitutional monarchy (with a rotating federal kingship among the nine hereditary Malay rulers), a 13-state federation, and a complex ethnic affirmative action system (the New Economic Policy, NEP, from 1971) reserving quotas for Malay Bumiputera in government, education, and business. Cabinet composition has reflected UMNO's (United Malays National Organisation) dominance within Barisan Nasional, with the Prime Minister invariably from UMNO until Mahathir Mohamad's Pakatan Harapan victory in 2018.\n\nMahathir's 2018 victory — the first change of governing coalition in Malaysia's 61-year independence — was followed by a period of extreme political instability: three governments in three years (2020-2022) as the Sheraton Move political crisis unfolded, with Prime Ministers changing through parliamentary maneuvers rather than elections. Anwar Ibrahim finally became PM in late 2022 following a hung parliament, forming a 'unity government' cabinet that included former rivals — a major transition in Malaysia's political history.",
        "causes": ["1957 independence establishing Westminster-model constitutional monarchy with Prime Ministerial cabinet system", "UMNO-led Barisan Nasional dominance from independence to 2018 shaping single-coalition cabinet governance", "New Economic Policy (1971) requiring cabinet management of ethnic-based affirmative action system", "2018 Mahathir-led opposition victory ending 61-year BN rule and beginning political instability"],
        "effects": ["2018 Pakatan Harapan victory as historic end of single-coalition dominance requiring new cabinet formation model", "2020-2022 Sheraton Move political crisis and three governments in three years demonstrating Westminster system fragility", "Anwar Ibrahim's 2022 unity government cabinet as model for post-BN inclusive coalition governance", "Malaysia's cabinet as instrument of NEP ethnic affirmative action policy affecting every ministry"],
        "relationships": [{"entity": "Mahathir Mohamad", "relationship": "PRIME_MINISTER_AND_CABINET_HEAD_FOR_LONGEST_PERIOD", "note": "Mahathir served as PM for 22 years (1981-2003) and again briefly (2018-2020), leading Malaysia's longest cabinet tenure"}, {"entity": "United Malays National Organisation", "relationship": "DOMINATED_CABINET_COMPOSITION_UNTIL_2018", "note": "UMNO's dominance within Barisan Nasional meant the PM and most cabinet ministers came from UMNO"}, {"entity": "Anwar Ibrahim", "relationship": "CURRENT_CABINET_HEAD_AFTER_UNITY_GOVERNMENT", "note": "Anwar formed Malaysia's first 'unity government' cabinet in 2022 after a hung parliament"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Malaysia's cabinet — governing one of Southeast Asia's most economically successful multiethnic societies, ending a 61-year single-coalition run in 2018, experiencing three governments in three years, and navigating the complex NEP ethnic affirmative action system — is central to understanding Malaysian democracy's evolution.", "significanceCategory": "continental"},
    }),
    ("cabinet-of-turkey", {
        "summary": "The Cabinet of Turkey (Bakanlar Kurulu), substantially transformed by the 2017 constitutional referendum and 2018 elections from a parliamentary cabinet model to an executive presidential system, represents one of the most significant constitutional transitions in a NATO member state's modern history — concentrating executive power in the presidency under Recep Tayyip Erdoğan while eliminating the Prime Minister role and dramatically reshaping Turkey's governance structure.\n\nTurkey's cabinet operated under a parliamentary model from the republic's founding by Atatürk in 1923 through 2018: the Prime Minister (from the majority parliamentary coalition) led the cabinet, while the President was a largely ceremonial figure. Under this system, Turkey experienced multiple military coups (1960, 1971, 1980, 1997 'postmodern coup') as the military treated itself as guardian of secularism. The AKP's rise (2002) and Erdoğan's consolidation of power gradually challenged this structure.\n\nThe April 2017 constitutional referendum — passed 51.4% to 48.6% amid disputed fairness — replaced parliamentary government with an executive presidential system, abolishing the Prime Ministership (held by Ahmet Davutoğlu, then Binali Yıldırım). Since June 2018, Turkey's cabinet ministers are directly appointed by and accountable solely to the President, without parliamentary confirmation. This transition has been criticized by opposition parties and democratic governance observers as concentrating power incompatible with democratic checks and balances, while defenders argue it ended the political instability of coalition governments.",
        "causes": ["AKP's electoral dominance enabling Erdoğan's systematic accumulation of executive power 2002-2017", "2017 constitutional referendum (51.4% Yes) abolishing parliamentary system and Prime Minister role", "Military coup attempt (July 2016) providing political pretext for emergency powers and constitutional change", "Erdoğan's shift from Prime Minister to President (2014) preceding the formal executive presidential transition"],
        "effects": ["Executive presidency concentrating cabinet appointment solely in President's hands without parliamentary confirmation", "Elimination of Prime Minister role ending Turkey's parliamentary governance model after 95 years", "Cabinet composition reflecting personal presidential preference rather than coalition parliamentary arithmetic", "Turkey's democratic regression in Freedom House and international democracy indices following executive concentration"],
        "relationships": [{"entity": "Recep Tayyip Erdoğan", "relationship": "CABINET_FORMED_BY_AND_ACCOUNTABLE_TO", "note": "Since 2018, Turkey's cabinet ministers are appointed by and solely accountable to President Erdoğan"}, {"entity": "2017 Turkish Constitutional Referendum", "relationship": "TRANSFORMED_CABINET_SYSTEM_THROUGH", "note": "The narrow 2017 referendum abolished parliamentary cabinet and created an executive presidential system"}, {"entity": "Justice and Development Party", "relationship": "DOMINANT_POLITICAL_SOURCE_OF_CABINET_MEMBERS", "note": "AKP members have filled the cabinet since Erdoğan's AKP came to power in 2002"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Turkey's cabinet system — transformed by the 2017 executive presidential transition from parliamentary to personal-presidential governance, concentrating power in Erdoğan, and representing a major democratic backslide in a NATO member — is one of the most consequential constitutional transitions in post-Cold War European politics.", "significanceCategory": "world-changing"},
    }),
    ("assembly-of-first-nations", {
        "summary": "The Assembly of First Nations (AFN), the national advocacy organization representing the 634+ First Nations communities across Canada with an estimated 900,000+ people (status and non-status First Nations, Métis and Inuit represented by other bodies), is Canada's principal Indigenous political organization — the institutional voice through which First Nations exercise collective political advocacy on treaty rights, land claims, self-governance, resource development, and the ongoing implementation of the Truth and Reconciliation Commission's 94 Calls to Action.\n\nThe AFN emerged from the National Indian Brotherhood (NIB), which had itself emerged from the political mobilization triggered by Pierre Trudeau's 1969 White Paper — which proposed abolishing special Indigenous legal status and integrating First Nations as individual Canadian citizens, generating massive opposition that became the foundational moment of modern Indigenous political organizing in Canada. The NIB was reconstituted as the AFN in 1982, giving it a more democratic structure with elected regional chiefs.\n\nThe AFN has been central to landmark moments in Canadian Indigenous rights: opposing the 1969 White Paper, contributing to Section 35's constitutional recognition of Aboriginal rights in 1982, negotiating the Indian Residential Schools Settlement Agreement (2006), and responding to the Truth and Reconciliation Commission's 2015 report. The discovery of unmarked graves at former residential school sites (2021) — where over 150,000 Indigenous children were forcibly removed from families — created a major national reckoning with which AFN worked closely. National Chief Phil Fontaine's public disclosure of residential school abuse (1990) was a pivotal moment in making this history visible.",
        "causes": ["1969 White Paper proposing to abolish Indigenous legal status triggering founding political mobilization", "National Indian Brotherhood's 1969-1982 advocacy leading to 1982 AFN reorganization", "Section 35 of the Constitution Act (1982) recognizing Aboriginal and treaty rights requiring national Indigenous advocacy body", "Truth and Reconciliation Commission (2008-2015) creating institutional framework for addressing residential school legacy"],
        "effects": ["1982 Section 35 constitutional recognition of Aboriginal rights — historic First Nations political victory", "Indian Residential Schools Settlement Agreement (2006) — largest class action in Canadian history", "2021 unmarked graves discoveries creating national reckoning with genocide in which AFN was primary voice", "94 Calls to Action (2015) providing framework for ongoing government-AFN reconciliation negotiations"],
        "relationships": [{"entity": "Truth and Reconciliation Commission of Canada", "relationship": "COLLABORATED_WITH_AND_RESPONDED_TO", "note": "AFN worked with and publicly responded to the TRC's 2015 94 Calls to Action on residential school legacy"}, {"entity": "1969 White Paper", "relationship": "OPPOSITION_TO_WHICH_CATALYZED_FOUNDING", "note": "AFN's predecessor NIB was mobilized in opposition to Trudeau's 1969 White Paper proposing to abolish Indigenous status"}, {"entity": "Indian Residential Schools", "relationship": "ADVOCACY_BODY_FOR_SURVIVORS_OF", "note": "AFN negotiated the $1.9 billion Indian Residential Schools Settlement Agreement (2006)"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Assembly of First Nations — opposing the 1969 White Paper, securing Section 35 constitutional rights, negotiating Canada's largest class action settlement for residential school survivors, and leading the national reckoning with unmarked graves — is the central institution in the ongoing reconciliation between Canada and First Nations peoples.", "significanceCategory": "world-changing"},
    }),
    ("chamber-of-peers", {
        "summary": "The Chamber of Peers (Chambre des Pairs), France's upper legislative chamber operating during the Restoration (1814-1830) and July Monarchy (1830-1848) periods, was the French equivalent of the British House of Lords — a hereditary and appointed upper house comprising the traditional aristocracy, Napoleonic nobility, and royal appointees — serving as the institutional embodiment of the Orleanist constitutional monarchy's attempt to balance royal prerogative with representative government in post-Napoleonic France.\n\nThe Chamber of Peers was established by the Constitutional Charter of 1814, which Louis XVIII granted upon his restoration after Napoleon's defeat. It was modeled on the British House of Lords, serving alongside the elected Chamber of Deputies as France's bicameral legislature. Peers (pairs de France) held their positions hereditarily or by royal appointment for life; the chamber included both 'old nobility' of pre-Revolutionary France and 'new men' ennobled by Napoleon. This mixture reflected the Restoration's attempt to reconcile the Old Regime with the Napoleonic legacy.\n\nThe Chamber of Peers' most dramatic moments came as a court: it tried the marshals of Napoleon condemned by the Restoration (Michel Ney was condemned to death, 1815), tried the Ultraroyalist ministers of Charles X after the 1830 July Revolution, and served as an arena for France's political class to negotiate the balance between royalist and constitutional principles. The Second Republic (1848) abolished the Chamber of Peers, replacing it with a unicameral National Assembly, ending the 34-year experiment in French upper chamber conservatism.",
        "causes": ["1814 Constitutional Charter establishing Chamber of Peers as upper house of Restoration France", "Louis XVIII's compromise with constitutional government after Napoleon requiring bicameral legislature", "Model of British House of Lords providing institutional template for French hereditary upper chamber", "Restoration's need to balance Old Regime nobility with Napoleonic new nobility in single upper house"],
        "effects": ["Michel Ney trial (1815) — execution of one of Napoleon's most famous marshals as political act of the Restoration", "Trial of Charles X's ministers after 1830 July Revolution demonstrating peer chamber's judicial function", "34-year experiment in constitutional monarchy upper chamber informing French republican thought about hereditary institutions", "1848 abolition ending hereditary upper chamber — French Republic's consistent rejection of aristocratic representation"],
        "relationships": [{"entity": "Louis XVIII of France", "relationship": "ESTABLISHED_BY", "note": "Louis XVIII's 1814 Constitutional Charter created the Chamber of Peers as France's upper legislative house"}, {"entity": "Michel Ney", "relationship": "CONDEMNED_TO_DEATH_BY", "note": "The Chamber of Peers tried and condemned Marshal Ney to execution in 1815 for serving Napoleon's Hundred Days"}, {"entity": "July Monarchy", "relationship": "UPPER_LEGISLATIVE_CHAMBER_OF", "note": "The Chamber of Peers served as the upper house of France's July Monarchy (1830-1848) under Louis-Philippe"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "France's Chamber of Peers — the Restoration-era upper house that tried Napoleon's marshals, balanced old and new nobility, and embodied the constitutional monarchy experiment between Napoleonic empire and Republican revolution — is a significant institution in France's complex 19th-century political history.", "significanceCategory": "continental"},
    }),
    ("conclave", {
        "summary": "The Papal Conclave (from Latin cum clave, 'with key' — referring to the locked room), the secret assembly of the College of Cardinals meeting to elect a new Pope, is one of the world's oldest and most elaborate electoral institutions — with procedures dating to the 13th century that represent the Catholic Church's solution to the problem of legitimate succession in a 1.3 billion-member global institution with no democratic accountability to ordinary members.\n\nThe conclave's current form derives from the long and chaotic vacancy of 1268-1271 at Viterbo, where the Cardinals were unable to agree on a Pope for nearly three years. The local population, frustrated, locked the cardinals in, reduced their food, and eventually removed the roof to expose them to the elements — forcing agreement. Pope Gregory X's 1274 constitution Ubi periculum formalized the conclave's sequestration and isolation procedures, which have been refined over centuries.\n\nMajor historical conclaves include the 1492 election of Alexander VI (Rodrigo Borgia) — one of history's most corrupt Popes, whose election involved direct payment to cardinals; the 1513 election of Leo X (Giovanni de' Medici) who faced Martin Luther; the 2005 election of Joseph Ratzinger (Benedict XVI) in the shortest post-Vatican II conclave (2 days); and the 2013 election of Francis — the first Jesuit Pope, first from the Americas, and first from the Southern Hemisphere, chosen after Benedict XVI's unprecedented resignation (the first resignation in 598 years). The conclave represents simultaneously an ancient institution and a living mechanism adapting to the global Catholic Church's leadership needs.",
        "causes": ["1268-1271 Viterbo vacancy — three-year papal election impasse — creating demand for formal conclave procedures", "Gregory X's 1274 Ubi periculum constitution formalizing conclave sequestration", "Catholic Church's need for clear legitimate succession mechanism in a global 1.3-billion-member institution", "Benedict XVI's 2013 resignation (first in 598 years) modernizing conclave's context for contemporary leadership transitions"],
        "effects": ["Two-thirds supermajority requirement creating consensus rather than simple majority for papal election", "Cardinal College's global expansion (now 60+ nations) transforming conclave from European to worldwide institution", "2013 election of Francis as first non-European Pope in 1,285 years reflecting global Catholic demographic shift", "Conclave model influencing other institutional successor-selection mechanisms requiring legitimacy and secrecy"],
        "relationships": [{"entity": "College of Cardinals", "relationship": "ELECTORAL_BODY_OF", "note": "The College of Cardinals (approximately 120 under age 80) is the electorate that participates in conclaves"}, {"entity": "Pope Francis", "relationship": "MOST_RECENT_PRODUCT_OF", "note": "The 2013 conclave elected Cardinal Jorge Bergoglio as Pope Francis — first Jesuit and first Americas Pope"}, {"entity": "Gregory X", "relationship": "FORMALIZED_PROCEDURES_BY", "note": "Gregory X's 1274 constitution Ubi periculum established the formal conclave procedures still used today"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Papal Conclave — one of the world's oldest electoral institutions, developed from a 13th-century locked-room innovation, selecting the leader of a 1.3 billion-member global institution, and producing historic elections including Francis's 2013 election as first non-European Pope in 1,285 years — is among the most consequential and ancient institutional processes in human history.", "significanceCategory": "world-changing"},
    }),
    ("armenian-national-assembly", {
        "summary": "The National Assembly of Armenia (Azgayin Zhoghov), the unicameral parliament of the Republic of Armenia established after independence from the Soviet Union in 1991, is the central legislative institution of one of the South Caucasus's most politically dynamic states — having experienced two revolutions (1998 and 2018), intermittent electoral fraud controversies, and the aftermath of the devastating 2020 Nagorno-Karabakh war that resulted in Armenia's effective loss of the disputed territory.\n\nThe National Assembly was established under Armenia's 1995 constitution and initially operated under presidential-parliamentary hybrid governance. The 2015 constitutional amendments (passed 63% to 32% in a controversial referendum) transformed Armenia from a presidential to a parliamentary system, making the Prime Minister the dominant executive and reducing the President to a ceremonial role. This transition shaped the context of Nikol Pashinyan's 2018 Velvet Revolution — when massive peaceful street protests forced Prime Minister Serj Sargsyan to resign just days after assuming the role despite promising not to — and Pashinyan became PM.\n\nThe 2020 Armenia-Azerbaijan war over Nagorno-Karabakh — in which Azerbaijan rapidly recaptured most of the territory with Turkish-supplied drones, ending with a Russian-brokered ceasefire — created profound political crisis in Armenia, with opposition demanding Pashinyan's resignation for military failure. The 2021 elections returned Pashinyan with a majority, and the National Assembly has subsequently managed the aftermath of the Karabakh defeat, Azerbaijan's September 2023 offensive that resulted in the flight of 100,000+ ethnic Armenians from Karabakh, and delicate diplomacy with Azerbaijan, Russia, EU, and the US.",
        "causes": ["1991 Soviet dissolution establishing independent Armenia requiring new parliamentary institutions", "1995 constitution founding National Assembly as Armenia's unicameral legislature", "2015 constitutional referendum shifting from presidential to parliamentary system", "2018 Velvet Revolution bringing Pashinyan to power through parliamentary vote after mass protests"],
        "effects": ["2018 Velvet Revolution demonstrating parliamentary system's role in peaceful democratic transition", "2020 Karabakh defeat creating political crisis that tested National Assembly's crisis management capacity", "2023 Azerbaijan offensive causing 100,000+ Karabakh Armenian displacement with National Assembly managing response", "Parliamentary system making PM (not President) dominant executive, with National Assembly as key political arena"],
        "relationships": [{"entity": "Nikol Pashinyan", "relationship": "PARLIAMENTARY_BASE_OF_GOVERNANCE", "note": "Pashinyan came to power through National Assembly vote during 2018 Velvet Revolution and leads his parliamentary majority"}, {"entity": "2020 Nagorno-Karabakh War", "relationship": "POLITICAL_CRISIS_MANAGED_BY", "note": "The National Assembly managed the political fallout of Armenia's defeat, including opposition demands for Pashinyan's resignation"}, {"entity": "2018 Armenian Velvet Revolution", "relationship": "INSTITUTIONAL_ARENA_OF", "note": "The 2018 Velvet Revolution used the National Assembly as its formal mechanism — Pashinyan was elected PM by parliament after street protests"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Armenia's National Assembly — arena of the 2018 Velvet Revolution, parliamentary manager of the catastrophic 2020 Karabakh defeat, and institution navigating Armenia's existential geopolitical repositioning between Russia and the West — is the central democratic institution in one of the most crisis-tested small states in the post-Soviet world.", "significanceCategory": "continental"},
    }),
    ("asean-inter-parliamentary-assembly", {
        "summary": "The ASEAN Inter-Parliamentary Assembly (AIPA), established in 1977 as the ASEAN Inter-Parliamentary Organisation (AIPO) and renamed in 2007, is the inter-parliamentary body of the Association of Southeast Asian Nations (ASEAN) — a consultative forum bringing together the national parliaments of ASEAN's 10 member states (Indonesia, Malaysia, Philippines, Singapore, Thailand, Brunei, Vietnam, Laos, Myanmar, Cambodia) to promote parliamentary cooperation, regional integration, and democratic governance across Southeast Asia.\n\nAIPA operates in a uniquely challenging context among inter-parliamentary bodies: its membership includes both multi-party democracies (Philippines, Indonesia), constitutional monarchies with limited pluralism (Thailand, Malaysia), quasi-one-party states (Cambodia, Laos, Vietnam, Singapore's quasi-competitive system), and a military junta (Myanmar, which ASEAN suspended following the 2021 coup). This diversity of political systems means AIPA must balance advocacy for democratic governance with ASEAN's foundational 'non-interference' principle.\n\nThe body has no legislative power — it issues statements, resolutions, and recommendations that are not binding on ASEAN governments. However, it has become increasingly active on issues including anti-corruption, human rights, environmental governance, and women's empowerment. The most consequential recent challenge has been Myanmar: AIPA suspended Myanmar's parliament (Pyidaungsu Hluttaw) following the February 2021 military coup and has navigated the tension between ASEAN principles of non-interference and the international community's expectation that regional bodies respond to military takeovers of democratic governments.",
        "causes": ["1977 founding to create inter-parliamentary cooperation mechanism among ASEAN member state legislatures", "ASEAN 1967 establishment providing regional framework that AIPO/AIPA extends to parliamentary level", "2007 transformation to AIPA deepening engagement with regional integration processes", "Myanmar 2021 coup creating major challenge for AIPA's balance of democratic advocacy and ASEAN non-interference"],
        "effects": ["Inter-parliamentary forum for 10 Southeast Asian legislatures covering 680+ million people", "Myanmar parliament suspension (2021) demonstrating AIPA's willingness to act on democratic governance violations", "Non-binding resolutions on anti-corruption, human rights, and environmental governance across member states", "AIPA model providing consultation mechanism bridging diverse political systems from Singapore to Indonesia to Vietnam"],
        "relationships": [{"entity": "ASEAN", "relationship": "INTER-PARLIAMENTARY_BODY_OF", "note": "AIPA serves as the parliamentary dimension of the 10-member ASEAN regional organization"}, {"entity": "Myanmar Parliament", "relationship": "SUSPENDED_AFTER_2021_COUP", "note": "AIPA suspended Myanmar's parliament following the February 2021 military coup"}, {"entity": "ASEAN Non-Interference Principle", "relationship": "CONSTRAINED_BY", "note": "AIPA's advocacy on democratic governance operates within the tension created by ASEAN's non-interference principle"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "AIPA — the inter-parliamentary body of 10 Southeast Asian nations covering 680+ million people, navigating democratic governance advocacy amid ASEAN's non-interference principle, and making the consequential decision to suspend Myanmar after its 2021 military coup — is a significant institution in Southeast Asian regional integration.", "significanceCategory": "continental"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 114 — Class 311 Parliaments II: Cabinets, Councils & Assemblies")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
