#!/usr/bin/env python3
"""Batch 112 — Class 316 Parties VI: South Asian & Middle Eastern Parties (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/316-Class-316"
FILE_PREFIX = "316"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("all-india-anna-dravida-munnetra-kazhagam", {
        "summary": "The All India Anna Dravida Munnetra Kazhagam (AIADMK), founded in 1972 by M. G. Ramachandran (MGR) — one of Tamil cinema's greatest stars who turned mass film popularity into political power — is one of India's two dominant regional parties in Tamil Nadu, the state that is home to India's most politically self-conscious regional identity, the Dravidian movement. AIADMK has ruled Tamil Nadu for extended periods and has influenced national politics through coalition arrangements.\n\nM. G. Ramachandran broke from the Dravida Munnetra Kazhagam (DMK) in 1972 after clashing with DMK leader M. Karunanidhi. MGR's film stardom — he had played heroic roles embodying working-class virtue for 30 years — translated directly into electoral support; his personal popularity was so immense that his death (1987) triggered mass grief unprecedented in modern Indian politics, with hundreds of reported suicides among devotees. Under MGR, AIADMK became one of India's most powerful regional parties.\n\nAfterhim, the party was led by Jayalalithaa (J. Jayalalithaa, 1987-2016), another iconic Tamil film actress turned politician, who served as Tamil Nadu's Chief Minister six times. Jayalalithaa's tenure was marked by both populist welfare schemes (noon meal programs, free goods distribution) and corruption controversies (the Tansi land deal, disproportionate assets case). The AIADMK's Dravidian identity — rooted in anti-Brahmin rationalist social reform movements — distinguishes it from Hindi-belt national parties and reflects Tamil Nadu's unique political culture.",
        "causes": ["1972 founding by MGR after split from DMK over leadership rivalry with Karunanidhi", "MGR's 30-year film stardom translating into unparalleled electoral popularity in Tamil Nadu", "Dravidian movement's anti-Brahmin rationalist tradition providing AIADMK's ideological foundation", "Jayalalithaa's six terms as Chief Minister establishing AIADMK as alternating-ruling party in Tamil Nadu"],
        "effects": ["AIADMK ruling Tamil Nadu for decades in alternation with DMK as Dravidian two-party system", "MGR's death (1987) triggering hundreds of reported suicides — unprecedented political mourning in India", "Jayalalithaa's populist welfare schemes (noon meals, free goods) setting Tamil Nadu welfare state standards", "AIADMK coalition influence on national politics during coalition governments in New Delhi"],
        "relationships": [{"entity": "M. G. Ramachandran", "relationship": "FOUNDED_BY", "note": "Film star and politician MGR founded AIADMK in 1972 after splitting from the DMK"}, {"entity": "Jayalalithaa", "relationship": "DOMINATED_BY_LEADERSHIP_OF", "note": "Jayalalithaa led AIADMK from 1987 to her death in 2016, serving as Tamil Nadu's CM six times"}, {"entity": "Dravida Munnetra Kazhagam", "relationship": "SPLIT_FROM", "note": "AIADMK was formed by MGR's break from the DMK in 1972, creating Tamil Nadu's Dravidian two-party system"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "AIADMK — founded by a film star whose death triggered mass grief, led by Jayalalithaa for three decades of welfare populism, and representing Tamil Nadu's distinctive Dravidian political culture — is one of India's most culturally unique and electorally significant regional parties.", "significanceCategory": "continental"},
    }),
    ("all-india-trinamool-congress", {
        "summary": "The All India Trinamool Congress (AITC or TMC), founded in 1998 by Mamata Banerjee — who broke from the Indian National Congress — is the dominant political party of West Bengal, the eastern Indian state with 90 million people, and represents the most successful challenge to the Communist Party of India (Marxist)'s 34-year stranglehold on West Bengal (1977-2011), one of the longest single-party runs in democratic Indian politics.\n\nMamata Banerjee (popularly called 'Didi' — elder sister) built TMC through fierce opposition to CPM's often violent political machine in West Bengal, becoming a symbol of resistance to Left Front dominance. Her party's 2011 victory ending CPM's 34-year rule was one of the most consequential electoral upsets in Indian state politics. Since 2011, Mamata has served as West Bengal's Chief Minister, fundamentally transforming the state's political landscape.\n\nTMC has positioned itself as a regional alternative to both the Congress and the BJP — particularly significant as Prime Minister Modi's BJP has targeted West Bengal as a key expansion state. The 2021 West Bengal election became India's most high-profile state election in years, with a direct contest between Mamata's TMC and the BJP backed by Modi's personal campaigning; TMC won decisively, making Mamata one of the BJP's most formidable opponents nationally. TMC's identity combines Bengali cultural pride, welfare populism ('Duare Sarkar' welfare camps), and strong opposition to Hindu nationalism.",
        "causes": ["1998 founding by Mamata Banerjee breaking from Congress to challenge CPM's West Bengal dominance", "34-year CPM rule (1977-2011) creating the political target that unified TMC's opposition identity", "Mamata's 'Didi' populist persona bridging urban and rural West Bengal electorates", "2021 high-profile BJP vs TMC West Bengal election becoming national test of Modi's expansion strategy"],
        "effects": ["2011 ending of CPM's 34-year West Bengal rule as historic democratic electoral transformation", "Mamata becoming BJP's most visible national opposition leader after 2021 West Bengal victory", "West Bengal welfare infrastructure under TMC ('Duare Sarkar' camps) providing model for state-level welfarism", "TMC as regional party blocking BJP national expansion into eastern India's largest state"],
        "relationships": [{"entity": "Mamata Banerjee", "relationship": "FOUNDED_AND_LED_BY", "note": "Mamata Banerjee founded TMC in 1998 and has led it to dominant power in West Bengal since 2011"}, {"entity": "Communist Party of India (Marxist)", "relationship": "DISPLACED_FROM_34-YEAR_RULE", "note": "TMC's 2011 victory ended CPM's 34-year West Bengal rule — one of India's longest single-party state runs"}, {"entity": "Bharatiya Janata Party", "relationship": "PRINCIPAL_NATIONAL_RIVAL", "note": "TMC vs BJP has become the defining contest in West Bengal, with Mamata as BJP's major national obstacle"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "All India Trinamool Congress — ending one of Indian democracy's longest single-party runs (CPM's 34 years in West Bengal), making Mamata Banerjee one of the BJP's most formidable opponents, and defining eastern India's political landscape — is one of the most consequential regional parties in contemporary Indian democracy.", "significanceCategory": "continental"},
    }),
    ("arab-socialist-baath-party-iraq-region", {
        "summary": "The Arab Socialist Baath Party – Iraq Region, the Iraqi branch of the pan-Arab Baath Party, which seized power in a 1968 coup and ruled Iraq until the 2003 US invasion, was the governing party of Saddam Hussein's totalitarian state — responsible for the mass murder of Kurds (Anfal campaign, 1986-1989, killing 50,000-182,000 Kurds including chemical weapons attacks at Halabja killing 5,000 in one day), the suppression of Shia uprisings, the Iran-Iraq War (1980-1988), the invasion of Kuwait (1990), and the Gulf War's aftermath.\n\nThe Iraqi Baath Party came to power in the July 17 Revolution (1968), initially under Ahmad Hassan al-Bakr before Saddam Hussein consolidated personal control in 1979. Saddam's rule transformed the Baath Party from an ideological pan-Arab socialist movement into a personal despotism using Baathist structures as instruments of control. The party's ideology — combining Arab nationalism, secularism, and socialism — was progressively subordinated to Saddam's cult of personality and tribal-clan power networks centered on Tikrit.\n\nThe 2003 US invasion toppled Saddam; the Coalition Provisional Authority's 'de-Baathification' policy (dismissing all Baath Party members from government, security forces, and state enterprises) is widely considered a catastrophic error that created the unemployment and grievance pool recruited by the subsequent Sunni insurgency and eventually by ISIS. The Iraqi Baath Party's legacy directly shaped the sectarian civil war that followed, making it one of the most consequential political parties in modern Middle Eastern history.",
        "causes": ["July 1968 Baathist coup establishing party control over Iraqi state apparatus", "Saddam Hussein's 1979 consolidation of personal power transforming party into personal despotism", "Anfal campaign (1986-1989) using chemical weapons against Kurds as genocidal counter-insurgency", "2003 US invasion and de-Baathification creating unemployed soldiers feeding subsequent insurgency"],
        "effects": ["Halabja chemical attack (1988) killing ~5,000 Kurds in one day as first WMD use against civilians in the Middle East", "Iran-Iraq War (1980-1988) killing over a million people and reshaping the Persian Gulf regional order", "Kuwait invasion (1990) triggering the Gulf War and US military presence in the Gulf", "De-Baathification creating the personnel pipeline for the Sunni insurgency and ultimately ISIS"],
        "relationships": [{"entity": "Saddam Hussein", "relationship": "PERSONAL_CONTROL_VEHICLE_OF", "note": "Saddam used the Iraqi Baath Party as the instrument of his totalitarian personal rule from 1979-2003"}, {"entity": "Anfal Campaign", "relationship": "STATE_APPARATUS_OF_PERPETRATION", "note": "The Iraqi Baath state perpetrated the Anfal genocidal campaign against Kurds including Halabja chemical attack"}, {"entity": "2003 Iraq War", "relationship": "DESTROYED_BY", "note": "The US-led 2003 invasion toppled the Baath regime; de-Baathification policy had catastrophic long-term consequences"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Iraqi Baath Party — presiding over the Anfal genocide, Iran-Iraq War, Kuwait invasion, and three decades of totalitarian rule, and whose dissolution via de-Baathification directly fed the insurgency and ISIS — is one of the most destructive political parties in 20th-century history, reshaping the entire Middle East.", "significanceCategory": "world-changing"},
    }),
    ("arab-socialist-baath-party-syria-region", {
        "summary": "The Arab Socialist Baath Party – Syria Region, the Syrian branch of the pan-Arab Baath Party, has ruled Syria continuously since the March 8 Revolution (1963) — making it one of the world's longest-ruling single parties — first through a series of military coups and party factions, then under Hafez al-Assad's consolidated personal dictatorship (1970-2000), and now under Bashar al-Assad whose mishandling of the 2011 Arab Spring protests triggered a civil war that has killed over 500,000 people and displaced 13 million.\n\nThe Syrian Baath Party's rule has been defined by the Assad family dynasty (Hafez and Bashar), the dominant role of the Alawite minority (Assad's sect) in the security services, and a brutal suppression of opposition exemplified by the 1982 Hama massacre (killing 10,000-40,000 Muslim Brotherhood supporters in the city of Hama). The Baath Party's pan-Arab socialist ideology — which promised unity, freedom, and socialism — was progressively hollowed out, serving as ideological veneer for Assad family rule and Alawite sectarian dominance.\n\nThe 2011 Syrian uprising — part of the Arab Spring — began as peaceful protests responding to the torture of children and rapidly escalated into civil war as Assad's government responded with mass arrests, torture, and military force. The conflict drew in ISIS, Al-Qaeda affiliates, Kurdish militias, Turkey, Russia, Iran, the US, and other powers, creating one of the most complex multi-actor wars of the 21st century. The Baath Party's decisions in 2011 — to crush rather than reform — produced one of the largest humanitarian disasters since World War II.",
        "causes": ["March 1963 Baathist coup installing party control over Syrian state", "Hafez al-Assad's 1970 'Corrective Movement' establishing personal dynastic Baathist rule", "1982 Hama Massacre as model of violent suppression maintaining Baathist control", "2011 Arab Spring response with torture and military force triggering civil war instead of reform"],
        "effects": ["500,000+ killed and 13 million displaced in Syrian Civil War (2011-present)", "Hama Massacre (1982) killing 10,000-40,000 as most deadly state massacre in Arab history", "Assad family 60+ year dynasty making Syria's Baath the Middle East's longest-ruling governing party", "Syrian conflict drawing in Russia, Iran, ISIS, Turkey, and US reshaping Middle Eastern geopolitics"],
        "relationships": [{"entity": "Hafez al-Assad", "relationship": "PERSONAL_RULE_CONSOLIDATED_BY", "note": "Hafez's 1970 'Corrective Movement' established the Assad family's personal dynasty within the Baath Party"}, {"entity": "Syrian Civil War", "relationship": "STATE_PERPETRATOR_OF", "note": "The Syrian Baath regime's 2011 violent response to protests triggered the civil war killing 500,000+"}, {"entity": "Hama Massacre", "relationship": "PERPETRATED", "note": "Hafez al-Assad's 1982 Hama massacre (10,000-40,000 killed) defined the Baath party's brutal opposition suppression model"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Syrian Baath Party — ruling 60+ years, perpetrating the Hama Massacre, triggering the Syrian Civil War that killed 500,000+ and displaced 13 million, and transforming from pan-Arab ideology to Assad family instrument — is one of the most destructive political parties in the modern Middle East.", "significanceCategory": "world-changing"},
    }),
    ("alliance-party-of-northern-ireland", {
        "summary": "The Alliance Party of Northern Ireland, founded in 1970 as a cross-community party explicitly bridging Northern Ireland's Protestant-unionist and Catholic-nationalist divide, is the only significant political party in Northern Ireland that is neither unionist nor nationalist — instead advocating for a 'shared future' that transcends sectarian division — and has experienced dramatic growth since the 2022 Northern Ireland Assembly elections, becoming the third-largest party and signaling a significant shift in Northern Irish politics away from its traditional sectarian two-bloc structure.\n\nAlliance was founded by Phelim O'Neill, Anne Dickson, and others in the months before the Northern Ireland Troubles escalated into full-scale violence, embodying the hope that cross-community moderate politics could prevent the coming conflict. Through 50 years of violence, political deadlock, and sectarian polarization, Alliance maintained its cross-community stance while remaining relatively small. The 2016 Brexit referendum — which Northern Ireland voted 56% to Remain — transformed Alliance's position: its pro-European, cross-community stance resonated with a younger generation disillusioned with traditional unionist/nationalist politics.\n\nThe 2022 Stormont Assembly elections saw Sinn Féin emerge as the largest party (historic), the DUP as second, and Alliance as third with 17 seats — its best ever result. Alliance leader Naomi Long became the first Alliance politician to serve as First Minister-designate for any period. The party's growth reflects a broader shift in Northern Irish society toward a 'neither' identity — identifying as 'Northern Irish' rather than British or Irish — particularly among young voters in Belfast and other urban areas.",
        "causes": ["1970 founding as cross-community party opposing sectarian politics at the onset of the Troubles", "50-year commitment to 'shared future' politics maintaining presence through Troubles violence and deadlock", "2016 Brexit vote (56% Remain in Northern Ireland) benefiting Alliance's pro-European cross-community stance", "Growing 'neither' identity among younger Northern Irish rejecting unionist/nationalist binary"],
        "effects": ["2022 Assembly elections: Alliance third-largest party with 17 seats — best ever result", "Naomi Long becoming Alliance's first politician in First Minister-designate role", "Alliance growth signaling shift away from 100-year Protestant/Catholic political binary in Northern Ireland", "Cross-community party model proving viable in post-Good Friday Agreement Northern Ireland"],
        "relationships": [{"entity": "Northern Ireland Troubles", "relationship": "FOUNDED_AT_ONSET_OF", "note": "Alliance was founded in 1970 just before the Troubles' most violent period, maintaining cross-community stance throughout"}, {"entity": "Good Friday Agreement", "relationship": "SUPPORTED_POLITICALLY", "note": "Alliance was a supporter of the Good Friday Agreement and the power-sharing institutions it created"}, {"entity": "Brexit", "relationship": "ELECTORAL_BENEFICIARY_OF", "note": "The 2016 Brexit referendum boosted Alliance as a pro-European cross-community alternative to traditional parties"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Alliance Party of Northern Ireland — maintaining cross-community politics through 50 years of sectarian conflict, growing dramatically in the post-Brexit era, and representing a possible future beyond Northern Ireland's unionist-nationalist binary — is one of the most historically significant small parties in UK politics.", "significanceCategory": "continental"},
    }),
    ("all-india-forward-bloc", {
        "summary": "The All India Forward Bloc (AIFB), founded in 1939 by Subhas Chandra Bose — the most charismatic leader of Indian nationalism after Gandhi, who advocated armed struggle against British colonialism and eventually led the Indian National Army allied with Japan during World War II — was the breakaway left-nationalist party through which Bose attempted to build a radical alternative to Gandhi's nonviolent Congress strategy, and today remains a small but symbolically important left-wing party in West Bengal.\n\nSubhas Chandra Bose was twice elected President of the Indian National Congress (1937, 1939) but clashed fundamentally with Gandhi over strategy: Bose wanted an ultimatum to Britain during wartime, using Axis power support if necessary, while Gandhi opposed any cooperation with fascist powers. Bose resigned from the Congress presidency in 1939 and founded the Forward Bloc as his own political vehicle, seeking to unite all anti-imperialist forces.\n\nBose's subsequent history — escaping British house arrest, traveling to Germany and then Japan by submarine (1940-1941), broadcasting from Axis-controlled territories, and leading the Indian National Army that fought alongside Japan in Burma — made him the most dramatic figure of Indian independence politics. His mysterious death in a plane crash (1945) and the subsequent mythologization (many Indians refused to believe he died) gave the Forward Bloc a martyr-founder of immense symbolic power. Today, AIFB is primarily a small West Bengal party, a coalition partner in Left Front governments, but its historical significance derives from being Bose's political creation.",
        "causes": ["1939 founding by Subhas Chandra Bose after breaking with Gandhi over India's response to World War II", "Bose's rejection of Gandhi's nonviolent strategy in favor of exploiting Britain's wartime vulnerability", "Bose's founding vision of uniting all anti-British left-nationalist forces under radical leadership", "Bose's dramatic escape and INA leadership creating the party's enduring martyrdom mythology"],
        "effects": ["Forward Bloc as Bose's political legacy — embodying militant nationalist alternative to Gandhian Congress", "Bose's INA (Indian National Army) trials becoming nationalist cause célèbre accelerating British departure", "Forward Bloc's small but permanent West Bengal presence in Left Front coalition politics", "Bose mythology making him India's most romanticized nationalist figure alongside Gandhi and Nehru"],
        "relationships": [{"entity": "Subhas Chandra Bose", "relationship": "FOUNDED_BY", "note": "Bose founded the Forward Bloc in 1939 after breaking with Gandhi's Congress over wartime strategy"}, {"entity": "Indian National Army", "relationship": "POLITICAL_MOVEMENT_ASSOCIATED_WITH", "note": "Bose's Forward Bloc evolved into his political base before he led the INA against Britain with Japanese support"}, {"entity": "Indian National Congress", "relationship": "BREAKAWAY_FROM", "note": "The Forward Bloc was founded by Bose after breaking from the Congress over fundamental strategic disagreement with Gandhi"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The All India Forward Bloc — founded by Subhas Chandra Bose as the radical alternative to Gandhi's Congress, representing the militant nationalist tradition that used Japanese alliance against British colonialism, and the political vehicle of India's most romanticized independence leader — is a historically significant footnote in the drama of Indian independence.", "significanceCategory": "continental"},
    }),
    ("all-india-majlis-e-ittehadul-muslimeen", {
        "summary": "The All India Majlis-e-Ittehadul Muslimeen (AIMIM, All India Council for the Unity of Muslims), founded in its modern political form in 1927 by Nawab Mahmood Nawaz Khan Bahadur in Hyderabad, Deccan, and revived as a national political force under Asaduddin Owaisi (president since 2008), is India's most prominent Muslim-identity political party — controversial for its religiously explicit political messaging, accused by critics of polarizing Hindu-Muslim relations and by supporters of giving Muslims political representation outside the Congress umbrella.\n\nAIMIM has its historical roots in the Hyderabad state's politics during the princely era; after Indian independence (1947) and the integration of Hyderabad into India (1948), it became a Hyderabad municipal and state-level party. Under Asaduddin Owaisi and his brother Akbaruddin Owaisi, the party has sought to expand nationally — achieving representation in Maharashtra (particularly Aurangabad), Bihar, and other states with significant Muslim populations.\n\nThe party's electoral strategy is explicitly targeting Muslim voters as a distinct political constituency; its critics (including many within the Muslim community) argue it splits Muslim votes away from secular parties like Congress and inadvertently benefits the BJP by enabling identity-based polarization. Its defenders argue it provides Muslims direct representation not filtered through Hindu-majority coalition pressures. AIMIM's rise reflects the fragmentation of India's 'secular' political bloc and the increasing assertiveness of Muslim political identity in a period of rising Hindu nationalism.",
        "causes": ["1927 founding in Hyderabad as Muslim political organization during princely era", "Asaduddin Owaisi's post-2008 leadership transforming AIMIM into national political force", "BJP's Hindu nationalism creating demand for explicit Muslim-identity political representation", "Maharashtra and Bihar expansion establishing AIMIM as pan-Indian rather than Hyderabad-only party"],
        "effects": ["AIMIM's national expansion creating India's most prominent Muslim-identity party since Partition", "Split Muslim votes in Bihar and Maharashtra debates about electoral impact on secular coalition politics", "Owaisi's parliamentary speeches on Muslim rights becoming most-viewed political addresses in Indian social media", "AIMIM model representing one response to the challenge of Muslim political representation in a Hindu-majority democracy"],
        "relationships": [{"entity": "Asaduddin Owaisi", "relationship": "TRANSFORMED_INTO_NATIONAL_PARTY_BY", "note": "Owaisi's leadership (2008-) transformed AIMIM from a Hyderabad regional party to a national Muslim-identity force"}, {"entity": "Bharatiya Janata Party", "relationship": "RISING_AS_COUNTER_TO_HINDU_NATIONALISM_OF", "note": "BJP's Hindu nationalism provided the political context driving AIMIM's national expansion"}, {"entity": "Indian National Congress", "relationship": "ELECTORAL_COMPETITOR_FOR_MUSLIM_VOTES", "note": "AIMIM competes with Congress for Muslim votes, with critics arguing this benefits the BJP"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "AIMIM — India's most prominent Muslim-identity party, debated for either empowering or fragmenting Muslim political agency, and operating in the fraught intersection of Indian secularism and rising Hindu nationalism — represents one of the most contested questions in contemporary Indian democratic politics.", "significanceCategory": "regional"},
    }),
    ("all-india-muslim-league", {
        "summary": "The All-India Muslim League (AIML), founded in 1906 in Dhaka under Nawab Khwaja Salimullah's patronage — gathering Muslim elites who feared the impact of the 1905 Bengal Partition reversal and Hindu-dominated Congress politics on Muslim interests — became under Muhammad Ali Jinnah's leadership (1934-1947) the principal vehicle for the demand for a separate Muslim state of Pakistan, achieving partition of British India and the creation of Pakistan on August 14, 1947 — one of the largest and most violent forced migrations in human history.\n\nThe League's transformation from a conservative Muslim elite organization to a mass nationalist movement demanding partition was largely Jinnah's achievement. Jinnah (initially a Congress member committed to Hindu-Muslim unity) grew increasingly convinced after the 1937 provincial elections — where Congress refused to include League in coalition governments — that Muslims required a separate state. The 1940 Lahore Resolution formally demanded Pakistan; the 1942-1947 period saw intensifying Congress-League conflict.\n\nThe 1947 partition produced enormous violence: estimates of deaths range from 200,000 to 2 million, and 10-20 million people were displaced in both directions across the new India-Pakistan border — the largest forced migration in history until then. The League's demand for Pakistan and its achievement fundamentally reshaped the Indian subcontinent and the British Empire's end. The AIML itself effectively dissolved into Pakistani national politics after 1947, with successor parties using the Muslim League name in both Pakistan and India.",
        "causes": ["1906 founding by Muslim elites fearing Hindu-dominated Congress and partition reversal", "Jinnah's post-1937 conviction that Congress dominance made Muslim political rights unprotectable in united India", "1940 Lahore Resolution formally demanding a separate Muslim state", "World War II and Britain's weakening creating the window for rapid independence and partition"],
        "effects": ["Partition of British India (August 1947) creating Pakistan — one of the 20th century's most consequential geopolitical events", "200,000-2 million deaths and 10-20 million displaced in Partition violence — largest forced migration of the era", "Creation of Pakistan as the world's first state founded on religious identity (Muslim majority)", "Permanent India-Pakistan hostility including three wars (1947, 1965, 1971) shaping South Asian geopolitics"],
        "relationships": [{"entity": "Muhammad Ali Jinnah", "relationship": "TRANSFORMED_AND_LED_BY", "note": "Jinnah led the League from 1934-1947, transforming it into the movement that achieved Pakistani independence"}, {"entity": "Partition of India", "relationship": "ACHIEVED_THROUGH_POLITICAL_PRESSURE_OF", "note": "The League's demand for Pakistan culminated in the 1947 Partition — one of history's most violent mass migrations"}, {"entity": "Indian National Congress", "relationship": "PRINCIPAL_ADVERSARY_IN_INDEPENDENCE_POLITICS", "note": "The Congress-League conflict, particularly after 1937, drove the escalating demand for partition"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The All-India Muslim League — achieving the creation of Pakistan through one of history's most violent and consequential partitions, displacing 10-20 million people, and permanently reshaping South Asia — is one of the most historically consequential political parties in the 20th century.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 112 — Class 316 Parties VI: South Asian & Middle Eastern Parties")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
