#!/usr/bin/env python3
"""Batch 59 — Class 311 World Parliaments & Assemblies (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/311-Class-311"
FILE_PREFIX = "311"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("british-parliament", {
        "summary": "The Parliament of the United Kingdom is the supreme legislative body of the United Kingdom, consisting of the Sovereign, the House of Lords, and the House of Commons. Tracing its origins to the 13th-century Great Council and the 1215 Magna Carta's principle of royal consent for taxation, it is one of the world's oldest representative bodies and the template for parliamentary democracy globally.\n\nThe Model Parliament of 1295 under Edward I established the principle of representation from boroughs and counties alongside clergy and barons. The English Civil War (1642-1651), the execution of Charles I, and the Glorious Revolution of 1688 established parliamentary supremacy over the monarchy — principles codified in the 1689 Bill of Rights. Westminster became the model for parliaments in Canada, Australia, New Zealand, India, and dozens of other nations.\n\nThe Reform Acts of 1832, 1867, and 1884 progressively extended voting rights from landed gentry to the industrial working class, while the Parliament Acts of 1911 and 1949 reduced the Lords to a delaying chamber. Women gained the vote in 1918 (over 30) and 1928 (all women). The Human Rights Act 1998 incorporated European Convention on Human Rights into British law. Parliament's legislative sovereignty (parliamentary supremacy) — the doctrine that Parliament can pass any law — remains the cornerstone of the British constitutional order.",
        "causes": ["Norman feudal tradition requiring barons' consent for extraordinary taxation", "1215 Magna Carta establishing principle of constitutional limits on royal power", "English Civil War conflict between King and Parliament over taxation and religion", "Glorious Revolution of 1688 permanently subordinating monarchy to parliamentary law"],
        "effects": ["Westminster parliamentary model adopted by 50+ countries worldwide", "1689 Bill of Rights established rights of free speech, free elections, and no cruel punishment", "Reform Acts extended democracy from aristocracy to universal adult suffrage", "Parliamentary sovereignty principle made Britain resistant to written constitutional entrenchment"],
        "relationships": [{"entity": "Magna Carta", "relationship": "ORIGINATED_FROM", "note": "1215 Magna Carta established principles of parliamentary consent"}, {"entity": "Glorious Revolution", "relationship": "REFORMED_BY", "note": "1688 revolution established permanent parliamentary supremacy over monarchy"}, {"entity": "House of Commons", "relationship": "CONTAINS", "note": "Elected lower house that has been supreme over Lords since 1911"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The British Parliament created the template for parliamentary democracy, establishing the principles of representative governance, constitutional monarchy, and rule of law adopted by democracies across the globe.", "significanceCategory": "world-changing"},
    }),
    ("althing-the-worlds-oldest-surviving-parl", {
        "summary": "The Althing (Alþingi) is the national parliament of Iceland, established in 930 CE, making it the world's oldest surviving parliament in continuous operation. Meeting annually at Þingvellir (Parliament Plains) beside a dramatic rift valley, it was the governing assembly of the Icelandic Commonwealth (930-1262 CE) before Iceland fell under Norwegian and later Danish rule.\n\nThe Althing was established by Icelandic settlers — primarily Norse Vikings and Celtic slaves brought from the British Isles — as an outdoor assembly meeting for two weeks each summer at midsummer. It combined legislative, judicial, and executive functions: the Law Speaker (Lögsögumaður) memorized and recited the laws, the Lögrétta enacted legislation, and regional courts heard disputes. The conversion of Iceland to Christianity in 1000 CE was decided by vote at the Althing — one of history's most consequential democratic decisions.\n\nThe Althing lost power as Iceland came under Norwegian control in 1262, was dissolved under Danish rule in 1800, and reestablished in Reykjavík in 1844. Iceland's 1944 independence from Denmark and the establishment of the republic were proclaimed at Þingvellir, reconnecting modern Iceland to its ancient democratic tradition. The site is now a UNESCO World Heritage site and Iceland's most sacred national location.",
        "causes": ["Norse settlers' tradition of regional things (assemblies) for dispute resolution", "Iceland's lack of central authority requiring common meeting for law and governance", "Chieftain goðar system requiring a neutral forum for inter-chieftain disputes", "Annual summer gathering tradition from Norwegian and Northern European practice"],
        "effects": ["Created oldest surviving parliament model for subsequent representative assemblies", "Christianity's 1000 CE adoption preserved at Althing changed Icelandic culture permanently", "Diplomatic relations between chieftains prevented systematic feudal violence", "Modern Icelandic state deliberately connected to Althing tradition at independence in 1944"],
        "relationships": [{"entity": "Þingvellir", "relationship": "MET_AT", "note": "Original meeting place now UNESCO World Heritage site"}, {"entity": "Icelandic Commonwealth", "relationship": "GOVERNED", "note": "Served as central governing institution of the free state 930-1262 CE"}, {"entity": "Christianity", "relationship": "DECIDED", "note": "Iceland's conversion to Christianity voted at Althing in year 1000 CE"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Althing is the world's oldest surviving parliament, demonstrating that Germanic tribal assemblies could evolve into sophisticated representative institutions long before modern democracy, and inspiring Icelandic national identity.", "significanceCategory": "continental"},
    }),
    ("athenian-assembly", {
        "summary": "The Athenian Ekklesia (Assembly) was the primary governing body of direct democracy in ancient Athens during its classical period (508-322 BCE). Open to all male citizens over 18, the Assembly met regularly on the Pnyx hill to debate and vote on laws, foreign policy, war, treaties, and public officials — creating the world's first functioning democracy and establishing concepts still fundamental to democratic theory.\n\nCleisthenes' reforms of 508-507 BCE created the institutional structure: 10 new tribes replacing the four traditional phyle, creating a mixed citizen body that broke up aristocratic clan power. The Assembly, together with the Council of 500 (Boule) selected by lot, and the popular law courts (dikasteria), constituted Athenian demokratia. At its height, 6,000-8,000 citizens could participate in Assembly meetings on the Pnyx, though meetings of 40 per year typically saw smaller numbers.\n\nPericles' 'Funeral Oration' (431 BCE), recorded by Thucydides, articulated democracy's philosophical principles: 'We are called a democracy, for the administration is in the hands of the many and not of the few.' The assembly voted for the Sicilian Expedition (415 BCE) — a catastrophic decision killing 40,000 Athenian men — demonstrating both democracy's decisiveness and its vulnerability to demagogic persuasion. Democratic Athens produced Socrates, Plato, and Aristotle, who debated democracy's merits and limitations in texts still studied today.",
        "causes": ["Solon's early reforms addressing inequality between wealthy nobles and poor citizens", "Cleisthenes' democratic reforms following tyranny of Peisistratos", "Persian Wars creating civic identity and pride demanding political participation", "Pericles' radical democracy extending pay for jury service enabling poor participation"],
        "effects": ["Created model of direct democracy still invoked in political theory", "Ostracism innovation enabled removal of dangerous citizens without death penalty", "Athenian democratic culture produced Socrates, Plato, and Aristotle's political philosophy", "Pnyx became physical model for legislative chambers in semicircular design"],
        "relationships": [{"entity": "Cleisthenes", "relationship": "REFORMED_BY", "note": "508-507 BCE democratic reforms created tribal system enabling true democracy"}, {"entity": "Pericles", "relationship": "LED_UNDER", "note": "Athenian statesman who expanded and articulated democratic principles"}, {"entity": "Socrates", "relationship": "CONDEMNED_BY", "note": "Assembly voted 281-220 to execute Socrates for impiety and corrupting youth"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Athenian Assembly invented democracy as a governmental form, establishing participation, accountability, and civic equality as political ideals that have guided Western political thought for 2,500 years.", "significanceCategory": "world-changing"},
    }),
    ("bundesrat", {
        "summary": "The Bundesrat (Federal Council) is one of the two houses of the German parliament, representing the 16 federal states (Länder) of Germany in federal legislation and administration. Unlike elected upper houses elsewhere, Bundesrat members are appointed by state governments, with votes cast as bloc votes per state proportional to population — a unique system making it a direct voice of state executives in federal lawmaking.\n\nThe Bundesrat traces its origins to the North German Confederation of 1867 and the 1871 German Empire's Federal Council, which represented German princes and free cities. The modern Bundesrat was created by the 1949 Basic Law (Grundgesetz) as part of Germany's post-WWII constitutional architecture designed to prevent the concentration of power that enabled Hitler's rise.\n\nThe Bundesrat can veto constitutional amendments and legislation affecting state administrations, giving states significant co-legislative power over approximately 60% of federal legislation. Key areas requiring Bundesrat consent include fiscal legislation, administrative laws, and constitutional changes. The 2/3 majority requirement in both Bundestag and Bundesrat for constitutional amendments has kept the German Basic Law relatively stable. The Bundesrat's chamber in Berlin — the former Prussian Landtag — has hosted debates on German reunification, EU integration, and COVID emergency powers.",
        "causes": ["German federal tradition dating to Holy Roman Empire's diverse principalities", "Weimar Republic's weakness motivating stronger federalism in 1949 Basic Law", "Allied powers' insistence on decentralization preventing future authoritarian centralization", "German states' distinct cultural and economic identities requiring institutional voice"],
        "effects": ["Federalism entrenched prevents centralization enabling authoritarian takeover", "State consent requirement forces compromise and coalition-building in German governance", "Bundesrat veto on certain laws gives German states leverage in national policy", "German federal model influenced post-WWII constitution designs in Austria and Switzerland"],
        "relationships": [{"entity": "Bundestag", "relationship": "COLEGISLATES_WITH", "note": "Germany's elected lower house requires Bundesrat consent on many laws"}, {"entity": "Federal Republic of Germany", "relationship": "PART_OF", "note": "Upper house of Germany's parliament representing 16 Länder"}, {"entity": "Basic Law", "relationship": "ESTABLISHED_BY", "note": "1949 Basic Law created current Bundesrat structure as cornerstone of federalism"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Bundesrat embodies Germany's federalism as a constitutional safeguard against centralized power, representing the lessons drawn from the Weimar Republic's failure and Hitler's rise.", "significanceCategory": "regional"},
    }),
    ("african-union-commission", {
        "summary": "The African Union Commission (AUC) is the secretariat and administrative organ of the African Union, established in 2002 to succeed the Organization of African Unity (OAU). Headquartered in Addis Ababa, Ethiopia, the Commission implements AU decisions, initiates AU policies, and manages the day-to-day operations of Africa's primary pan-continental political institution.\n\nThe OAU was founded in 1963 by African nationalist leaders including Kwame Nkrumah, Haile Selassie, and Julius Nyerere in Addis Ababa to coordinate decolonization, promote pan-African unity, and prevent external interference in African affairs. The 2002 transformation into the African Union, modeled partially on the European Union, reflected ambitions for deeper integration including a common currency, open borders, and collective security mechanisms.\n\nThe AU Commission implements flagship programs including Agenda 2063 (Africa's long-term development vision), the Continental Free Trade Area (AfCFTA) creating the world's largest free trade zone by member countries, and the Africa CDC health emergency coordination. The Commission's enforcement of governance norms — condemning coups, facilitating elections — has been inconsistent, with member states often prioritizing sovereignty over accountability. The Peace and Security Council, a key AU body the Commission supports, has mediated conflicts in Sudan, Somalia, and the DRC.",
        "causes": ["African decolonization wave of 1950s-60s requiring coordination among new states", "OAU's limited effectiveness prompting demand for more integrated continental institution", "European Union model demonstrating regional integration's economic and political benefits", "African leaders' ambition for sovereign continental voice in global affairs"],
        "effects": ["AfCFTA creation of world's largest free trade area by number of member countries", "Agenda 2063 providing Africa's long-term development framework", "Peace and Security Council mediation in African conflicts", "AU peacekeeping missions in Somalia (AMISOM), Sudan, and other conflict zones"],
        "relationships": [{"entity": "Organization of African Unity", "relationship": "SUCCEEDED", "note": "OAU dissolved in 2002 as African Union was established"}, {"entity": "Addis Ababa", "relationship": "HEADQUARTERED_IN", "note": "Commission based in Ethiopian capital since OAU founding in 1963"}, {"entity": "Continental Free Trade Area", "relationship": "IMPLEMENTS", "note": "AfCFTA secretariat supported by AU Commission"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The African Union Commission represents Africa's attempt at continent-scale governance, embodying post-independence pan-African aspirations while navigating the tensions between sovereignty and collective action.", "significanceCategory": "continental"},
    }),
    ("assembly-of-experts-for-leadership", {
        "summary": "The Assembly of Experts for Leadership (Majles-e Khobregān-e Rahbari) is an 88-member elected body in Iran responsible for electing, supervising, and if necessary dismissing the Supreme Leader — the most powerful position in the Islamic Republic. Established by the 1979 Iranian constitution, it is the only body in the Iranian system with formal authority over the Supreme Leader.\n\nThe Assembly was established after the 1979 Islamic Revolution to institutionalize clerical governance as envisioned by Ayatollah Khomeini's doctrine of Velayat-e faqih (Guardianship of the Islamic Jurist). Members are Islamic scholars elected by popular vote to 8-year terms but must be approved by the Guardian Council, which vets candidates for religious and political acceptability. This creates a circular system where the Guardian Council (appointed by the Supreme Leader) approves candidates for the body that theoretically supervises the Supreme Leader.\n\nIn practice, the Assembly of Experts has never dismissed a Supreme Leader and has been criticized as a rubber stamp. It elected Ali Khamenei as Supreme Leader in 1989 following Khomeini's death. The body deliberated in 2016 over Khamenei's cancer, prompting speculation about succession. The Assembly's authority over choosing the next Supreme Leader makes it theoretically crucial to Iran's political future, as who leads after Khamenei could determine whether Iran evolves or becomes more hardline.",
        "causes": ["1979 Islamic Revolution creating need for institutional framework for clerical governance", "Khomeini's Velayat-e faqih doctrine requiring bodies to implement theocratic governance", "Need for legitimate mechanism to select and supervise the Supreme Leader", "1979 constitution's design creating checks within the clerical establishment"],
        "effects": ["Elected Ali Khamenei as Supreme Leader in 1989 upon Khomeini's death", "Debate over Khamenei succession makes Assembly crucial to Iran's political future", "Circular validation system with Guardian Council limits genuine democratic accountability", "Body's decisions could determine whether Iran becomes more or less reformist"],
        "relationships": [{"entity": "Supreme Leader of Iran", "relationship": "ELECTS", "note": "Assembly has sole authority to elect, supervise, and dismiss the Supreme Leader"}, {"entity": "Guardian Council", "relationship": "VETTED_BY", "note": "Guardian Council approves Assembly candidates, creating circular oversight"}, {"entity": "Ayatollah Khomeini", "relationship": "ESTABLISHED_BY", "note": "Khomeini's 1979 constitution created the Assembly of Experts"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Assembly of Experts is theoretically the most powerful body in Iran's theocratic system — the only institution with authority over the Supreme Leader — yet has functioned primarily as a legitimating body for clerical governance.", "significanceCategory": "continental"},
    }),
    ("cabinet-of-japan", {
        "summary": "The Cabinet of Japan (Naikaku) is the executive organ of the Japanese government, composed of the Prime Minister and up to 20 ministers of state. Established by the Cabinet Law of 1947 under the post-WWII constitution, the Cabinet holds executive power collectively and is responsible to the National Diet (legislature), creating Japan's parliamentary system of government.\n\nJapan's modern cabinet system was established in 1885 during the Meiji Era under Itō Hirobumi, Japan's first Prime Minister, who modeled it on European cabinet governments particularly the Prussian system. The 1947 post-WWII constitution, written under US occupation, transformed the Emperor from sovereign to constitutional monarch, making the Cabinet the real executive power responsible to the elected Diet rather than the Emperor.\n\nThe Cabinet system has been dominated by the Liberal Democratic Party (LDP) almost continuously since 1955, creating the world's most durable single-party democratic rule. Japan has had over 100 prime ministers, with frequent leadership changes creating political instability (average PM tenure less than 2 years). Abe Shinzō became Japan's longest-serving PM (2012-2020), implementing 'Abenomics' economic reform. The Cabinet's constitutional constraints on military force under Article 9 have been incrementally reinterpreted to allow greater Japan Self-Defense Forces roles.",
        "causes": ["Meiji Restoration of 1868 requiring modern Western-style government institutions", "Itō Hirobumi's study of European parliamentary models for Meiji modernization", "US occupation after WWII mandating democratic constitutional governance", "Cold War context requiring Japan to become a stable US ally with civilian oversight"],
        "effects": ["LDP's near-continuous rule from 1955 created uniquely stable single-party democracy", "Article 9 pacifist constraints shaped Japan's post-war foreign and defense policy", "Abenomics economic reforms attempted to revive Japan's stagnant economy", "Cabinet reinterpretation of Article 9 expanded Japan's collective self-defense posture"],
        "relationships": [{"entity": "Emperor of Japan", "relationship": "ADVISES", "note": "Cabinet advises Emperor who has ceremonial rather than executive role since 1947"}, {"entity": "National Diet", "relationship": "RESPONSIBLE_TO", "note": "Cabinet must maintain confidence of the elected National Diet"}, {"entity": "Liberal Democratic Party", "relationship": "DOMINATED_BY", "note": "LDP has controlled Cabinet almost continuously since 1955"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Japan's Cabinet system transformed the world's only country to experience nuclear warfare into a stable parliamentary democracy and economic powerhouse, while its Article 9 pacifism became a unique experiment in constitutionally renouncing war.", "significanceCategory": "continental"},
    }),
    ("amyotha-hluttaw", {
        "summary": "The Amyotha Hluttaw (House of Nationalities) is the upper house of the Pyidaungsu Hluttaw, Myanmar's bicameral parliament established under the 2008 constitution. Consisting of 224 members — 168 elected and 56 appointed by the military (Tatmadaw) — it represents Myanmar's diverse ethnic states and regions, though its structure embeds military veto power into civilian governance.\n\nMyanmar's parliamentary tradition dates to British colonial rule, but the Amyotha Hluttaw in its current form emerged from the 2008 constitution drafted during military rule, designed to ensure the Tatmadaw's continued political influence even after nominal democratization. The guaranteed 25% military appointment in both houses means constitutional amendments require military consent, effectively giving the Tatmadaw veto power over fundamental governance changes.\n\nThe 2015 elections that brought Aung San Suu Kyi's NLD party to power created a formal civilian government in which Suu Kyi served as State Counsellor, but military-appointed legislators remained present in the Hluttaw. The February 2021 military coup — when the Tatmadaw arrested Suu Kyi and dissolved parliament — ended Myanmar's democratic experiment and triggered a civil war that continues, with the Amyotha Hluttaw replaced by a State Administration Council under military rule.",
        "causes": ["2008 military-drafted constitution guaranteeing military parliamentary representation", "British colonial bicameral legislative tradition adapted for independent Burma", "Myanmar's ethnic diversity requiring upper house to represent states and regions", "Tatmadaw's insistence on maintaining political power during transition to civilian rule"],
        "effects": ["25% military quota blocked constitutional amendment enabling genuine democratic transition", "NLD election victories did not translate into full civilian control of security forces", "2021 coup dissolved parliament ending Myanmar's democratic period", "Civil war following coup has displaced millions and caused widespread human rights violations"],
        "relationships": [{"entity": "Aung San Suu Kyi", "relationship": "LED_UNDER", "note": "NLD won 2015 elections with Suu Kyi as State Counsellor before 2021 coup"}, {"entity": "Tatmadaw", "relationship": "CONTROLLED_BY", "note": "Military appoints 56 of 224 members and controls through structural veto"}, {"entity": "National League for Democracy", "relationship": "MAJORITY_HELD_BY", "note": "NLD won overwhelming majorities in 2015 and 2020 elections"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Amyotha Hluttaw's embedded military representation demonstrated how authoritarian structures can undermine democratic institutions even when elections occur, a cautionary model for hybrid democratic-military governance.", "significanceCategory": "regional"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 59 — Class 311 World Parliaments & Assemblies")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
