#!/usr/bin/env python3
"""Batch 110 — Class 341 Cathedrals V: Spanish & French Cathedrals (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/341-Class-341"
FILE_PREFIX = "341"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("cathedral-of-santiago-de-compostela", {
        "summary": "The Cathedral of Santiago de Compostela in Galicia, northwestern Spain, built over the believed tomb of St. James the Apostle beginning in the 9th century and substantially in its current Romanesque form between 1075-1211 CE, is one of the three great pilgrimage centers of medieval Christianity (alongside Rome and Jerusalem) and the destination of the Camino de Santiago (Way of St. James) — the most famous pilgrimage route in the Western world, which has experienced a remarkable modern revival with over 400,000 pilgrims completing it annually.\n\nThe Pórtico de la Gloria (1168-1188 CE) by Master Mateo — the cathedral's western sculptural portal — is one of the supreme achievements of Romanesque sculpture: 200 figures carved in a single integrated program depicting Christ in Majesty, the Last Judgment, Old and New Testament figures, and the Apostles with a psychological expressiveness and technical virtuosity that anticipated Gothic sculpture by decades. Pilgrims traditionally place their hands in the grooves worn into the central column (now protected with barriers) and knock their heads against the seated figure of Master Mateo himself — the 'Saint of Bumps' — hoping for his intelligence.\n\nSantiago de Compostela's role in medieval European history extended far beyond religious pilgrimage: the cathedral and the Camino were among the primary transmission routes for cultural exchange between the Iberian Peninsula and the rest of Europe during the 11th-13th centuries. The pilgrimage route spread Romanesque architectural styles, musical traditions (including polyphony), and commerce across France and Spain. UNESCO World Heritage Site since 1985.",
        "causes": ["9th century discovery of claimed tomb of St. James the Apostle establishing Santiago as pilgrimage site", "1075-1211 CE Romanesque cathedral construction providing Spain's greatest pilgrimage monument", "Pórtico de la Gloria (1168-1188) by Master Mateo as supreme Romanesque sculptural masterpiece", "Modern Camino revival (post-1980s) attracting over 400,000 pilgrims annually"],
        "effects": ["Camino de Santiago as one of the world's most famous pilgrimage routes — 400,000+ annual modern pilgrims", "Pórtico de la Gloria as one of Romanesque sculpture's greatest achievements anticipating Gothic expressiveness", "Medieval pilgrimage route as major cultural transmission channel between Iberia and Europe", "UNESCO World Heritage designation (1985) and modern tourism making Santiago globally iconic"],
        "relationships": [{"entity": "Way of St. James", "relationship": "DESTINATION_OF", "note": "Santiago Cathedral is the endpoint of the Camino de Santiago — the world's most famous pilgrimage route"}, {"entity": "Pórtico de la Gloria", "relationship": "CONTAINS_SCULPTURAL_MASTERWORK", "note": "Master Mateo's 1168-1188 portal is one of Romanesque sculpture's supreme achievements"}, {"entity": "St. James the Apostle", "relationship": "BUILT_OVER_CLAIMED_TOMB_OF", "note": "The cathedral was built over the claimed tomb of St. James the Apostle, discovered in the 9th century"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "Santiago de Compostela Cathedral — one of the three great pilgrimage centers of medieval Christianity, the Pórtico de la Gloria's sculptural masterpiece, the destination of the Camino de Santiago (400,000+ annual pilgrims), and a primary cultural transmission route between medieval Iberia and Europe — is one of the most historically consequential religious monuments in Western Christendom.", "significanceCategory": "world-changing"},
    }),
    ("pamplona-cathedral", {
        "summary": "Pamplona Cathedral (Cathedral of Santa María la Real de Pamplona) in Navarre, northern Spain — built in Gothic style between 1394-1501 CE on the site of a Romanesque cathedral destroyed by earthquake — is one of the finest Gothic cathedrals in Spain and the seat of the Archdiocese of Pamplona. The cathedral is particularly notable for its 14th-century Gothic cloister, considered one of the most beautiful Gothic cloisters in Europe and certainly the finest in Spain, with tracery and sculpture of exceptional delicacy.\n\nPamplona — the ancient Roman Pompaelo, the city made famous by Hemingway's The Sun Also Rises and the Running of the Bulls festival (San Fermín, July 6-14) — has been the capital of the Kingdom of Navarre, a historically strategic buffer kingdom between France and Spain that maintained its independence until 1512. The cathedral served as the burial place of the kings of Navarre including Charles III 'the Noble' (d. 1425) whose alabaster tomb, by Johan Lome de Tournai, is one of the masterpieces of late Gothic funerary sculpture in Europe.\n\nThe cathedral's 18th-century Neoclassical facade (by Ventura Rodríguez, 1783) contrasts with the Gothic interior, making Pamplona Cathedral an unusual fusion of Gothic and Neoclassical aesthetics. The cathedral stands on the pilgrimage route — Pamplona is one of the first major Camino de Santiago waypoints after entering Spain from France through the Pyrenees — giving it significance in the pilgrimage tradition alongside its role as Navarre's royal church.",
        "causes": ["1394-1501 CE Gothic construction on site of Romanesque cathedral destroyed by earthquake", "Kingdom of Navarre's royal patronage making the cathedral the burial church of Navarrese kings", "Gothic cloister (14th c.) as one of Europe's finest, with exceptional tracery and sculpture", "Camino de Santiago route through Pamplona making the cathedral a major pilgrimage waypoint"],
        "effects": ["Gothic cloister as finest in Spain and among the most beautiful in Europe", "Charles III's alabaster tomb as masterpiece of late Gothic funerary sculpture", "18th-century Neoclassical facade (1783) creating Gothic-Neoclassical fusion unique in Spanish cathedrals", "Pilgrimage route significance connecting Pamplona Cathedral to the broader Camino de Santiago tradition"],
        "relationships": [{"entity": "Kingdom of Navarre", "relationship": "ROYAL_BURIAL_CHURCH_OF", "note": "Pamplona Cathedral served as the burial church of the kings of Navarre, including Charles III the Noble"}, {"entity": "Way of St. James", "relationship": "MAJOR_WAYPOINT_ON", "note": "Pamplona is the first major Camino de Santiago waypoint after entering Spain from France via the Pyrenees"}, {"entity": "Johan Lome de Tournai", "relationship": "TOMB_SCULPTED_BY", "note": "Johan Lome's alabaster tomb of Charles III (d. 1425) is a masterpiece of late Gothic funerary sculpture"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Pamplona Cathedral — royal burial church of Navarre's kings, home to Spain's finest Gothic cloister, containing one of late Gothic funerary sculpture's masterpieces, and a key Camino de Santiago waypoint — is a monument where Navarrese royal history, Gothic architecture, and pilgrimage tradition converge.", "significanceCategory": "continental"},
    }),
    ("poitiers-cathedral", {
        "summary": "Poitiers Cathedral (Cathédrale Saint-Pierre de Poitiers) in western France, begun in the late 12th century (c. 1162 CE) under Henry II and Eleanor of Aquitaine — the most powerful couple in 12th-century Europe — and completed in the 13th-14th centuries, is one of the finest examples of Angevin Gothic (Plantagenet) architecture in France, distinguished by its distinctive wide nave with three aisles of almost equal height (hall church plan) and its exceptionally well-preserved medieval stained glass windows.\n\nThe association with Eleanor of Aquitaine — who was simultaneously Queen of France (to Louis VII) and later Queen of England (to Henry II), the mother of Richard I 'the Lionheart' and King John, and the most powerful woman in 12th-century Europe — makes Poitiers Cathedral a monument intimately connected to one of history's most remarkable dynasties. Eleanor and Henry II funded significant portions of the cathedral, and Poitiers (Eleanor's ancestral capital) was the center of her famous 'Courts of Love' where she patronized troubadour culture.\n\nPoitiers Cathedral's stained glass program — including one of France's oldest rose windows (c. 1162) and the magnificent Crucifixion window — is among the most complete Romanesque-to-Gothic stained glass ensembles surviving in France. The battle of Poitiers (1356) — where the Black Prince captured the French King John II — is historically the most famous event associated with Poitiers, but the cathedral predates it by two centuries and has outlasted all the conflicts that swirled around this strategically important city.",
        "causes": ["c. 1162 CE construction by Henry II and Eleanor of Aquitaine as Plantagenet royal patronage", "Angevin Gothic hall-church plan creating distinctive three-aisles-of-equal-height design", "Eleanor of Aquitaine's troubadour 'Courts of Love' making Poitiers a cultural and patronage center", "Medieval stained glass program (c. 1162 rose window) as one of France's oldest and most complete"],
        "effects": ["Angevin Gothic hall-church design as distinctive architectural contribution to French Gothic tradition", "Association with Eleanor of Aquitaine connecting the cathedral to 12th-century European political history", "Medieval stained glass ensemble including France's oldest rose window as major art historical resource", "Plantagenet royal patronage evidence embedded in one of western France's most important cathedrals"],
        "relationships": [{"entity": "Eleanor of Aquitaine", "relationship": "CO-FOUNDED_BY_PATRONAGE_OF", "note": "Eleanor and Henry II funded Poitiers Cathedral — Eleanor's ancestral capital was her 'Courts of Love' center"}, {"entity": "Henry II of England", "relationship": "CO-FOUNDER_AND_PATRON", "note": "Henry II (as Duke of Aquitaine and King of England) co-patronized the cathedral's construction c. 1162"}, {"entity": "Plantagenet Dynasty", "relationship": "ROYAL_PATRONAGE_MONUMENT_OF", "note": "Poitiers Cathedral is a key monument of Plantagenet royal patronage in France"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Poitiers Cathedral — built by Henry II and Eleanor of Aquitaine, a monument to Plantagenet cultural patronage, home to France's oldest rose window, and an architectural masterpiece of Angevin Gothic — is one of western France's most historically layered medieval religious monuments.", "significanceCategory": "continental"},
    }),
    ("autun-cathedral", {
        "summary": "Autun Cathedral (Cathédrale Saint-Lazare d'Autun) in Burgundy, France, built 1120-1146 CE and expanded later, is one of the supreme monuments of Romanesque sculpture — most notably for the tympanum over the central west portal depicting the Last Judgment, carved c. 1130-1145 CE and signed by the sculptor 'Gislebertus hoc fecit' (Gislebertus made this) — making it the rare case of a signed medieval sculptural masterpiece. The Gislebertus tympanum is widely considered the greatest Romanesque sculptural program north of the Alps.\n\nGislebertus's Last Judgment — depicting a serene but awesome Christ in majesty, with souls being weighed in the balance, the blessed rising to heaven in orderly columns, and the damned seized by enormous demonic hands in extraordinary expressions of terror — represents the high point of Romanesque sculpture's dramatic, expressive power. The individual capitals in the nave (some now in the Autun Rolin Museum to protect them) include the Flight into Egypt, the Three Magi asleep, and the Temptation of Eve — the latter (now in the Metropolitan Museum, New York) being one of the most sensuously expressive medieval sculptures in existence.\n\nAutun was founded by Augustus as the Roman city of Augustodunum, capital of the Aedui tribe, and its Roman heritage (including two surviving Roman gates — Porte d'Arroux and Porte Saint-André) makes it one of France's richest sites for Roman-medieval continuity. The cathedral's dedication to St. Lazarus (whose relics were brought from Marseille) made it a significant pilgrimage destination. The tympanum survived the Revolution only because it was plastered over in 1766 and not discovered until 1837.",
        "causes": ["1120-1146 CE construction as Burgundian Romanesque cathedral housing relics of St. Lazarus", "Gislebertus's c. 1130-1145 tympanum as greatest Romanesque sculptural program north of the Alps", "Autun's Roman heritage (Augustodunum) providing ancient foundations for medieval building", "Revolutionary plastering (1766) accidentally preserving the tympanum until rediscovery in 1837"],
        "effects": ["Gislebertus's signed Last Judgment as the supreme Romanesque sculptural achievement in northern Europe", "Temptation of Eve capital (now Metropolitan Museum) as most sensuously expressive medieval sculpture", "Autun as unique site combining Roman gates (Porte d'Arroux) with Romanesque cathedral in continuous occupation", "Medieval discovery tradition of signed sculpture preserved uniquely in Gislebertus's 'hoc fecit' inscription"],
        "relationships": [{"entity": "Gislebertus", "relationship": "SCULPTURAL_MASTERWORK_BY", "note": "Gislebertus carved the tympanum (c. 1130-1145) — the only signed Romanesque sculptural masterpiece"}, {"entity": "Cluny Abbey", "relationship": "ARTISTIC_TRADITION_OF", "note": "Autun Cathedral's Romanesque sculpture follows the Cluniac tradition — Gislebertus trained at Cluny"}, {"entity": "Metropolitan Museum of Art", "relationship": "TEMPTATION_OF_EVE_CAPITAL_NOW_IN", "note": "The Temptation of Eve capital (one of the most beautiful medieval sculptures) is now in the Met, New York"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Autun Cathedral — containing Gislebertus's signed Last Judgment tympanum (the supreme Romanesque sculpture north of the Alps), the Temptation of Eve (among history's most beautiful medieval sculptures), and sitting on a Roman imperial city — is one of the most artistically and historically significant medieval monuments in Europe.", "significanceCategory": "world-changing"},
    }),
    ("nancy-cathedral", {
        "summary": "Nancy Cathedral (Cathédrale Notre-Dame-de-l'Annonciation de Nancy) in Lorraine, France, built 1703-1742 CE in the Baroque style — one of France's finest Baroque cathedrals — was the court church of the Duchy of Lorraine and later became famous through its connection to Stanisław Leszczyński, the deposed King of Poland who ruled Lorraine (1737-1766) and transformed Nancy into one of the most beautiful Baroque cities in Europe with his construction of the Place Stanislas (1752-1756).\n\nNancy's Place Stanislas — built by Stanisław Leszczyński with his architect Emmanuel Héré de Corny — is one of the most complete and beautiful 18th-century royal squares in Europe, a UNESCO World Heritage Site (1983) and France's most magnificent Baroque ensemble. The cathedral forms part of this broader urban composition: Nancy under Stanisław became a showcase of French Rococo architecture, wrought-iron grillwork (by Jean Lamour), and urban planning that influenced European city design.\n\nStanisław Leszczyński's story is one of history's more poignant: twice elected King of Poland (1704, 1733), twice deposed, he received Lorraine as a consolation prize from his son-in-law Louis XV after the War of the Polish Succession — and transformed his loss into a cultural triumph by making Nancy one of Europe's most beautiful capitals. The cathedral was damaged during the French Revolution but restored; it remains an active cathedral and part of the UNESCO-protected Nancy Baroque ensemble.",
        "causes": ["1703-1742 CE Baroque construction as court church of the Duchy of Lorraine", "Stanisław Leszczyński's 1737-1766 rule transforming Nancy into a showcase Baroque city", "Place Stanislas (1752-1756) creating one of Europe's most complete 18th-century urban Baroque ensembles", "UNESCO World Heritage designation (1983) protecting Nancy's Baroque architectural ensemble"],
        "effects": ["Nancy Baroque ensemble (cathedral, Place Stanislas, Place de la Carrière) as France's most magnificent 18th-century urban composition", "Jean Lamour's wrought-iron grillwork of Place Stanislas as masterpiece of Rococo decorative arts", "Stanisław Leszczyński's patronage transforming political loss into one of Europe's great cultural achievements", "UNESCO protection of Nancy Baroque ensemble as one of France's most complete 18th-century urban spaces"],
        "relationships": [{"entity": "Stanisław Leszczyński", "relationship": "RULING_PATRON_WHO_TRANSFORMED_CITY", "note": "Twice-deposed King of Poland, Stanisław ruled Lorraine 1737-1766 and built the Baroque ensemble including Place Stanislas"}, {"entity": "Place Stanislas", "relationship": "FORMS_PART_OF_BAROQUE_ENSEMBLE_WITH", "note": "Nancy Cathedral and Place Stanislas form part of the UNESCO-protected Nancy Baroque urban composition"}, {"entity": "Emmanuel Héré de Corny", "relationship": "ARCHITECT_OF_CATHEDRAL_ENSEMBLE", "note": "Héré designed the Place Stanislas (1752-1756) that makes Nancy's Baroque ensemble one of Europe's finest"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Nancy Cathedral — part of the UNESCO-protected Baroque ensemble built by deposed Polish King Stanisław Leszczyński, whose cultural patronage transformed political exile into one of Europe's most beautiful cities — is a monument to 18th-century French Baroque urban achievement.", "significanceCategory": "continental"},
    }),
    ("our-lady-of-the-assumption-cathedral-granada", {
        "summary": "Granada Cathedral (Cathedral of the Incarnation / Catedral de la Encarnación, also known as Cathedral of the Assumption of Granada) in Granada, Andalusia, Spain — begun in 1523 CE on the site of the Great Mosque of Granada immediately after the Reconquista — is the first Renaissance cathedral built in Spain and one of the most historically charged religious buildings in the country, symbolizing the Spanish Catholic reconquest of the last Muslim kingdom on Iberian soil.\n\nThe cathedral was begun by Diego de Siloé (1528) who transformed an original Gothic design into the first Spanish Renaissance cathedral, creating a revolutionary new form — the capilla mayor (main chapel) as a massive circular rotunda surrounded by classical columns — that became the prototype for subsequent Spanish Renaissance churches. The circular capilla mayor is considered one of the supreme innovations of Spanish Renaissance architecture, anticipating Roman High Renaissance circular designs.\n\nGranada Cathedral's Royal Chapel (adjacent, technically separate) contains the tombs of Ferdinand and Isabella (Los Reyes Católicos) — the monarchs who completed the Reconquista (1492), expelled the Jews (1492), sponsored Columbus's voyage (1492), and established the Spanish Inquisition. The Royal Chapel with its effigies and the treasure of Queen Isabella (including her personal crown, scepter, and paintings) is the most historically charged royal burial chapel in Spain. The cathedral-mosque juxtaposition in Granada — the mosque's former minaret visible in the Giralda of Seville across Andalusia — makes it one of the most politically resonant sacred sites in Western history.",
        "causes": ["1523 CE construction beginning immediately after Reconquista on Great Mosque site as Christian triumph symbol", "Diego de Siloé's (1528) revolutionary circular capilla mayor creating the first Spanish Renaissance cathedral", "Royal Chapel housing tombs of Ferdinand and Isabella as monument to Reconquista monarchs", "Granada's symbolic weight as last Muslim kingdom in Spain making the cathedral political as well as religious"],
        "effects": ["First Renaissance cathedral in Spain — Diego de Siloé's circular capilla mayor prototyping Spanish Renaissance churches", "Royal Chapel with Ferdinand and Isabella's tombs as Spain's most politically charged royal burial site", "Cathedral-on-mosque construction as most powerful symbol of Reconquista Christian triumph", "Granada's multi-religious heritage (Muslim, Jewish, Christian) making it UNESCO World Heritage since 1984"],
        "relationships": [{"entity": "Diego de Siloé", "relationship": "REDESIGNED_AS_RENAISSANCE_BY", "note": "Diego de Siloé (from 1528) transformed Granada's Gothic cathedral plan into the first Spanish Renaissance cathedral"}, {"entity": "Ferdinand and Isabella", "relationship": "ROYAL_CHAPEL_TOMBS_OF_NEARBY", "note": "The adjacent Royal Chapel contains the tombs of the Catholic Monarchs who completed the Reconquista in 1492"}, {"entity": "Reconquista", "relationship": "BUILT_AS_VICTORY_MONUMENT_OF", "note": "Granada Cathedral was built on the Great Mosque site as the ultimate symbol of Christian reconquest of Iberia"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Granada Cathedral — Spain's first Renaissance cathedral, built on the Great Mosque site as the supreme Reconquista victory symbol, adjacent to the tombs of Ferdinand and Isabella, and containing one of the most revolutionary spatial innovations in Spanish architecture — is one of the most historically charged sacred monuments in Western history.", "significanceCategory": "world-changing"},
    }),
    ("basilica-of-saint-severinus-of-bordeaux", {
        "summary": "The Basilica of Saint-Seurin (Saint-Seurin de Bordeaux / Basilica of Saint Severinus of Bordeaux) in Bordeaux, France — one of the oldest Christian sites in France, with continuous sacred use from the 4th century CE through the present — is a UNESCO World Heritage Site as part of the Routes of Santiago de Compostela (1998), a major pre-Romanesque and Romanesque church complex whose crypt contains one of the most important early Christian archaeological ensembles in France.\n\nThe site's archaeological significance is extraordinary: excavations under the basilica revealed a 4th-century Christian cemetery and sarcophagi (the 'Paléochrétien' cemetery) containing the remains of early Christian bishops of Bordeaux, some of exceptional quality with carved reliefs depicting early Christian iconography. The sarcophagi are among the most important early Christian funerary monuments in France and provide direct archaeological evidence of 4th-century Christian community life in Gaul.\n\nSaint-Seurin stands on the Via Turonensis — one of the four main Camino de Santiago routes through France — and pilgrims have prayed here for over a millennium on their way to Santiago de Compostela. The church's legendary connection to Roland (Charlemagne's paladin killed at Roncevaux, 778 CE) — pilgrims reportedly left weapons at the church as votive offerings in Roland's memory — gives it a place in the Chansons de Geste literary tradition. The current Romanesque structure (11th-13th century) preserves the ancient crypt with its 4th-century Christian treasures.",
        "causes": ["4th century CE Christian cemetery establishment as one of France's earliest Christian sacred sites", "Early Christian sarcophagi of exceptional quality preserving 4th-century Gaulish Christian iconography", "Via Turonensis (French Camino) route making Saint-Seurin a 1,000-year pilgrimage waypoint", "UNESCO World Heritage designation (1998) as part of Routes of Santiago de Compostela"],
        "effects": ["4th-century Christian cemetery and sarcophagi as France's most important early Christian archaeological ensemble", "1,000-year pilgrimage tradition on Via Turonensis connecting Bordeaux to Santiago de Compostela", "Roland legend connection embedding Saint-Seurin in Chanson de Roland literary tradition", "UNESCO protection preserving Romanesque-early Christian layered heritage in the heart of Bordeaux"],
        "relationships": [{"entity": "Way of St. James", "relationship": "MAJOR_WAYPOINT_ON_VIA_TURONENSIS", "note": "Saint-Seurin stands on the Via Turonensis — one of the four main French Camino de Santiago routes"}, {"entity": "Early Christianity in Gaul", "relationship": "ARCHAEOLOGICAL_EVIDENCE_SITE_FOR", "note": "The 4th-century Christian sarcophagi are among France's most important early Christian archaeological finds"}, {"entity": "UNESCO World Heritage", "relationship": "DESIGNATED_AS_PART_OF", "note": "UNESCO 1998 designated Saint-Seurin as part of the Routes of Santiago de Compostela World Heritage Site"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Basilica of Saint-Seurin — with France's most important early Christian archaeological ensemble (4th-century sarcophagi), 1,000 years of Camino de Santiago pilgrimage tradition, a Roland legend connection, and UNESCO World Heritage status — is one of France's most historically layered sacred sites.", "significanceCategory": "continental"},
    }),
    ("basilica-of-st-martin-tours", {
        "summary": "The Basilica of Saint Martin of Tours in Tours, France — built over the tomb of Saint Martin of Tours (c. 316-397 CE), the Roman soldier turned monk who became Bishop of Tours and is the patron saint of France — is one of the most important pilgrimage sites in medieval Christianity. The original basilica, built by Bishop Perpetuus c. 470-490 CE, became the wealthiest and most visited pilgrimage church in medieval France; the current Neo-Byzantine basilica (1886-1924) replaces the medieval structure largely destroyed during the French Revolution.\n\nSaint Martin of Tours is one of the most consequential figures in Western Christianity: the story of his dividing his military cloak to share with a naked beggar (giving rise to the word 'chapel' from his 'capella' — small cloak — kept as a sacred relic carried into battle by Frankish kings) is one of Christianity's most famous acts of charity. Martin was the first non-martyr to be venerated as a saint in the Western church, and his cult — spread by his biographer Sulpicius Severus's Vita Martini (c. 397 CE) — was the most popular saint cult in early medieval Europe.\n\nThe Via Turonensis (one of the four French Camino de Santiago routes) begins at Saint Martin's basilica in Tours — pilgrimages to Santiago often began with a pilgrimage to Tours — making the basilica one of the starting points of the entire Camino de Santiago tradition. Alcuin of York, the great scholar of the Carolingian Renaissance, served as abbot of Saint Martin's from 796-804 CE and wrote many of his works there. The medieval basilica was one of the greatest in Europe before its Revolutionary destruction.",
        "causes": ["c. 470-490 CE original basilica construction over Saint Martin's tomb establishing the pilgrimage site", "Saint Martin's fame as patron of France and first non-martyr Western saint creating enormous pilgrimage draw", "Via Turonensis beginning at Tours making Saint Martin's basilica the starting point of the French Camino", "Alcuin of York's 796-804 CE abbacy making Saint Martin's a center of Carolingian scholarship"],
        "effects": ["Saint Martin's cult as most popular early medieval European saint spreading from Tours across Europe", "Word 'chapel' etymologically derived from Martin's capella relic — embedded in Christian liturgical vocabulary", "Via Turonensis starting at Tours connecting Saint Martin's basilica to the entire Camino de Santiago tradition", "Alcuin's abbacy making Tours a Carolingian intellectual center alongside Aachen and Fulda"],
        "relationships": [{"entity": "Saint Martin of Tours", "relationship": "BUILT_OVER_TOMB_OF", "note": "The basilica was built c. 470-490 CE over the tomb of St. Martin — patron saint of France"}, {"entity": "Way of St. James", "relationship": "STARTING_POINT_OF_VIA_TURONENSIS", "note": "The Via Turonensis (French Camino) traditionally begins at Saint Martin's basilica in Tours"}, {"entity": "Alcuin of York", "relationship": "ABBOT_WHO_MADE_TOURS_CAROLINGIAN_INTELLECTUAL_CENTER", "note": "Alcuin (796-804 CE) served as abbot of Saint Martin's and wrote major Carolingian scholarly works there"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Basilica of Saint Martin of Tours — tomb of France's patron saint, etymological origin of the word 'chapel', starting point of the Via Turonensis (French Camino), and Alcuin's Carolingian intellectual center — is one of medieval France's most historically consequential sacred sites.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 110 — Class 341 Cathedrals V: Spanish & French Cathedrals")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
