#!/usr/bin/env python3
"""Batch 93 — Class 344 Abbeys II (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/344-Class-344"
FILE_PREFIX = "344"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("iona-abbey", {
        "summary": "Iona Abbey on the Isle of Iona, off the western coast of Scotland, founded by the Irish monk Columba (Colum Cille) in 563 CE, is the founding institution of Celtic Christianity in Scotland and Northumbria — the monastery from which missionaries converted northern Britain, produced the Book of Kells (possibly begun at Iona), and transmitted the insular minuscule script that became medieval Europe's dominant writing hand. Iona's influence over early medieval Britain is disproportionate to its tiny size: a 5.5 km² island whose monastery shaped the religious culture of hundreds of thousands.\n\nColumba, a Irish nobleman and monk who had fled Ireland after a dispute over a psalter (possibly causing the Battle of Cúl Dreimhne, 561 CE), established his monastery on Iona as both penitential exile and missionary base. Iona's scriptorium produced illuminated manuscripts in the insular tradition; monks from Iona founded Lindisfarne (635 CE) on the northeast English coast, which became the greatest center of Northumbrian Christianity and produced the Lindisfarne Gospels. Iona's 'school' of abbots trained missionaries who Christianized the Picts of Scotland.\n\nViking raids beginning in 795 CE devastated Iona repeatedly — the Martyrdom of 68 monks in 806 CE forced the transfer of many monks and treasures (possibly including the Book of Kells) to Kells in Ireland. The Iona Community — a modern ecumenical Christian community founded in 1938 by George MacLeod — rebuilt the ruined abbey and continues its use as an active center of Christian pilgrimage, social justice advocacy, and community living. Over 250,000 people visit annually.",
        "causes": ["563 CE founding by Columba as Irish monk's penitential exile and Scottish missionary base", "Iona scriptorium Book of Kells production (or initiation) as peak of insular manuscript art", "Lindisfarne 635 CE founding from Iona creating Northumbrian Christianity center", "1938 Iona Community founding by MacLeod rebuilding ruins and continuing pilgrimage tradition"],
        "effects": ["Celtic Christianity transmission across Scotland and Northumbria from 563 CE", "Book of Kells (possibly) and insular manuscript tradition preserving Christian learning through Viking age", "Viking 806 CE massacre forcing monastery treasures to Ireland preserving cultural heritage", "250,000 annual visitors and Iona Community making it active 21st-century pilgrimage center"],
        "relationships": [{"entity": "Columba", "relationship": "FOUNDED_BY", "note": "Columba founded Iona in 563 CE as missionary base that Christianized Scotland and Northumbria"}, {"entity": "Lindisfarne", "relationship": "FOUNDED_DAUGHTER_MONASTERY", "note": "Iona monks founded Lindisfarne in 635 CE creating Northumbria's greatest Christian center"}, {"entity": "George MacLeod", "relationship": "IONA_COMMUNITY_FOUNDED_BY", "note": "MacLeod's 1938 Iona Community rebuilt the ruined abbey creating modern ecumenical pilgrimage center"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Iona Abbey — from a 5.5 km² island — transmitted Celtic Christianity to Scotland and Northumbria, possibly produced the Book of Kells, and founded Lindisfarne's scriptorium, making it the most consequential tiny monastery in European history in terms of the territory converted and the manuscripts produced.", "significanceCategory": "world-changing"},
    }),
    ("rievaulx-abbey", {
        "summary": "Rievaulx Abbey in North Yorkshire, England, founded in 1132 by a small group of Cistercian monks from Clairvaux sent by Bernard of Clairvaux, became — under its third abbot Aelred of Rievaulx (abbot 1147-1167) — the most spiritually influential Cistercian monastery in Britain, growing from 12 monks to 650 monks and lay brothers within 25 years and producing the first great spiritual writer in English monastic history. Aelred's Spiritual Friendship and Mirror of Charity are among the most psychologically sophisticated texts of medieval Christianity.\n\nThe Cistercian Order's expansion in 12th-century Britain was rapid: Rievaulx was England's first Cistercian abbey, followed quickly by Fountains (1132) and dozens of others. The Cistercian model — remote location, agricultural self-sufficiency, plain architecture rejecting Cluniac ornament — established a new form of monastic piety that appealed to Norman aristocracy seeking spiritual authenticity. Rievaulx's location in a narrow Yorkshire valley gave it the topography perfectly suited to Cistercian seclusion.\n\nAelred of Rievaulx's influence: his Spiritual Friendship (c. 1165) adapted Cicero's De Amicitia into a Christian theology of friendship as spiritual path, arguing that deep human friendship is not opposed to love of God but is its expression — a radical claim in an era when emotion was typically suspect in monastic literature. The monastery's 1538 dissolution under Henry VIII — its lead stripped, buildings demolished — left the ruins that are now among the most romantically beautiful in England, photographed for 250 years. The adjacent 18th-century landscape garden (Rievaulx Terrace) frames the ruins as a designed picturesque composition.",
        "causes": ["1132 founding by Bernard of Clairvaux's monks as England's first Cistercian abbey", "Aelred's abbacy (1147-1167) producing Spiritual Friendship — first great English monastic spiritual writing", "Growth from 12 to 650 monks under Aelred demonstrating Cistercian expansion's attraction", "1538 Henrician dissolution creating romantic ruins that inspired 250 years of picturesque art"],
        "effects": ["England's first Cistercian monastery establishing Cistercian monastic model across Britain", "Aelred's Spiritual Friendship as first great English monastic text and friendship theology", "Rievaulx ruins as most romantic monastery ruins in England inspiring picturesque art tradition", "18th-century Rievaulx Terrace landscape garden framing ruins as designed picturesque composition"],
        "relationships": [{"entity": "Aelred of Rievaulx", "relationship": "GREATEST_ABBOT", "note": "Aelred's 1147-1167 abbacy grew monastery to 650 and produced Spiritual Friendship"}, {"entity": "Bernard of Clairvaux", "relationship": "FOUNDED_BY_DISCIPLES_OF", "note": "Bernard sent founding monks from Clairvaux to establish England's first Cistercian monastery"}, {"entity": "Henry VIII", "relationship": "DISSOLVED_BY", "note": "1538 Henrician dissolution stripped and demolished Rievaulx creating romantic ruins"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Rievaulx Abbey — under Aelred's abbacy producing the first great English monastic spiritual writing and growing to 650 monks — represents the apex of 12th-century British Cistercian life, and its dissolution ruins are among England's most culturally productive: inspiring picturesque aesthetics for 250 years.", "significanceCategory": "continental"},
    }),
    ("whitby-abbey", {
        "summary": "Whitby Abbey in North Yorkshire, England, founded in 657 CE by the Northumbrian princess Hild (later Saint Hild or Hilda), is the site of the Synod of Whitby (664 CE) — the most consequential ecclesiastical council in early English history, which decided that the English church would follow Rome's Easter calculation rather than the Celtic tradition, effectively aligning Anglo-Saxon England with continental Catholic practice and ending the Celtic-Roman schism in Northumbria. Whitby is also where Caedmon — the first named poet in English literature — received his miraculous gift of song according to Bede.\n\nSaint Hild, a great-niece of Edwin of Northumbria, led Whitby as abbess of a double monastery (monks and nuns together under an abbess's authority) from 657-680 CE. The Synod of Whitby (664 CE) was called by King Oswiu of Northumbria to settle the Easter controversy — Celtic Christians following Columba's tradition calculated Easter differently from Rome. The debate, described by Bede, was between the Roman advocate Wilfrid and the Celtic advocate Colmán; Oswiu's decision for Rome ended the Celtic practice in Northumbria.\n\nCaedmon — a lay brother at Whitby who dreamed he received the gift of song, producing the first Old English religious poetry (Caedmon's Hymn, c. 657-680 CE) — is the first named poet in the English literary tradition, preserved in Bede's Ecclesiastical History. The Norman abbey (11th-13th century ruins visible today) replaced the original Saxon structure. Whitby's dramatic clifftop ruins featured in Bram Stoker's Dracula (1897), where Dracula arrives in England disguised as a giant black dog leaping ashore during a storm.",
        "causes": ["657 CE founding by Saint Hild as double monastery for Northumbrian royal family members", "664 CE Synod of Whitby deciding England's Easter calculation and aligning church with Rome", "Caedmon's Hymn (c. 657-680 CE) as first named English poet's only surviving work", "Norman rebuilding creating the clifftop ruins that inspired Bram Stoker's Dracula landing scene"],
        "effects": ["Synod of Whitby ending Celtic-Roman schism in Northumbria and aligning Anglo-Saxon England with Rome", "Caedmon's Hymn establishing English vernacular religious poetry tradition", "Clifftop ruins inspiring Dracula landing scene making Whitby globally famous through Gothic fiction", "Double monastery under woman abbess providing early precedent for female religious leadership"],
        "relationships": [{"entity": "Hild of Whitby", "relationship": "FOUNDED_BY", "note": "Saint Hild founded and led Whitby 657-680 CE; hosted 664 CE Synod that aligned England with Rome"}, {"entity": "Caedmon", "relationship": "FIRST_ENGLISH_POET_AT", "note": "Caedmon's Hymn composed at Whitby is first Old English religious poem by named poet"}, {"entity": "Bram Stoker", "relationship": "SETTING_FOR_DRACULA", "note": "Stoker used Whitby's clifftop ruins as the dramatic landing site for Dracula in his 1897 novel"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Whitby Abbey is where English ecclesiastical history (the Synod of Whitby's Rome alignment) intersects with English literary history (Caedmon's first named English poem) and Gothic fiction (Dracula's landing) — three distinct fields whose histories all pass through a single clifftop in North Yorkshire.", "significanceCategory": "world-changing"},
    }),
    ("ampleforth-abbey", {
        "summary": "Ampleforth Abbey in North Yorkshire, England, founded in 1802 by Benedictine monks who had maintained continuous English Catholic monasticism through the Reformation and Penal Laws — fleeing England in 1608 to Dieulouard in Lorraine, France, and returning after the French Revolution dispersed English Catholic communities in Europe — is Britain's largest working Benedictine monastery and the most prestigious English Catholic school (Ampleforth College). The Ampleforth community's unbroken 900-year chain from Westminster Abbey through French exile to Yorkshire demonstrates the tenacity of English Catholic institutional survival.\n\nThe English Benedictines who left for France in 1608 (founding Dieulouard, then St. Laurence's) maintained an English monastic identity through 200 years of French exile. The French Revolution dispersed them; they returned to England in 1793-1802, eventually settling in Ampleforth Valley in 1802. The abbey's school (Ampleforth College), founded in 1802 simultaneously, became Britain's leading Catholic boarding school — educating generations of English Catholic aristocracy and producing cardinals, ambassadors, and military officers.\n\nAmpleforth's influence on English Catholic culture was enormous through the 20th century: Cardinal Basil Hume (Archbishop of Westminster 1976-1999) was a monk and Abbot of Ampleforth before becoming England's most beloved Catholic cardinal. The abbey's 2013-2019 child abuse scandal — involving monks who had taught at Ampleforth College — severely damaged its reputation and resulted in criminal convictions and the college's removal from the Catholic Independent Schools Conference.",
        "causes": ["Medieval English Benedictine monasticism surviving Reformation through exile to Dieulouard, Lorraine in 1608", "French Revolution 1793 dispersal of English Catholic communities in France", "1802 return to England and establishment in Ampleforth Valley", "Ampleforth College founding simultaneously as leading English Catholic boarding school"],
        "effects": ["Unbroken 900-year English Benedictine monastic chain from Westminster Abbey through French exile", "Cardinal Basil Hume (1976-1999) as England's most beloved Catholic cardinal emerging from Ampleforth", "Ampleforth College educating English Catholic aristocracy for 220 years", "2013-2019 child abuse scandal severely damaging monastery and college reputation"],
        "relationships": [{"entity": "Basil Hume", "relationship": "MONK_AND_ABBOT", "note": "Hume was Ampleforth monk and abbot before becoming Archbishop of Westminster (1976-1999)"}, {"entity": "English Benedictine Congregation", "relationship": "MEMBER_OF", "note": "Ampleforth is part of the English Benedictine Congregation maintaining pre-Reformation tradition"}, {"entity": "Ampleforth College", "relationship": "SCHOOL_OPERATED_BY", "note": "Abbey-run Catholic boarding school educated English Catholic elite for 220 years"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Ampleforth Abbey's unbroken 900-year Benedictine chain — from pre-Reformation England through French exile through 19th-century return — represents the most complete institutional continuity of English Catholic monasticism, and Cardinal Hume's emergence as England's most beloved Catholic leader demonstrates the school's cultural influence.", "significanceCategory": "continental"},
    }),
    ("bury-st-edmunds-abbey", {
        "summary": "Bury St Edmunds Abbey in Suffolk, England, founded in 1020 CE to house the relics of Edmund, King of East Anglia (martyred by Vikings in 869 CE), became one of England's wealthiest and most powerful Benedictine monasteries — the place where, in November 1214 CE, the English barons secretly met, swore an oath on Edmund's shrine, and agreed to demand King John sign Magna Carta, making the abbey the indirect birthplace of English constitutional government. The abbey's 1214 barons' meeting directly set in motion the events leading to Magna Carta (1215 CE).\n\nEdmund, King of East Anglia, was killed by the Great Heathen Army of Viking invaders in 869 CE — according to tradition, tied to a tree, shot with arrows, and beheaded for refusing to share his kingdom with pagan Vikings. His body was taken to Bury (then Beodericsworth) in 903 CE and his relics attracted pilgrimage. King Canute founded the abbey in 1020 CE, granting it special liberty (the Liberty of St Edmund) — immunity from royal and episcopal jurisdiction, essentially making it an independent palatinate.\n\nThe abbey's wealth (it owned 170 manors) made it a political power center. The 1214 meeting — where Archbishop Stephen Langton read out Henry I's Coronation Charter to the barons, who recognized it as the basis for demanding John's reform — was a secret council. The barons' oath on Edmund's shrine gave their covenant religious sanction. Magna Carta was signed at Runnymede seven months later (June 1215). The abbey was dissolved in 1539, and its ruins now form a public garden at the center of Bury St Edmunds.",
        "causes": ["869 CE Edmund's Viking martyrdom creating saint's cult in East Anglia", "1020 CE King Canute founding abbey with Liberty of St Edmund autonomous status", "November 1214 barons' meeting swearing oath to demand Magna Carta from King John", "1539 dissolution under Henry VIII leaving ruins incorporated into town garden"],
        "effects": ["Magna Carta's indirect birthplace through 1214 barons' oath on Edmund's shrine", "Liberty of St Edmund palatinate creating autonomous zone exempt from royal and episcopal jurisdiction", "Abbey ruins forming public garden — one of England's most historically significant public spaces", "Edmund's martyrdom narrative making him Suffolk's patron saint 1,150 years after death"],
        "relationships": [{"entity": "Edmund the Martyr", "relationship": "HOUSES_RELICS_OF", "note": "Abbey built 1020 CE to house Edmund's relics; barons swore on shrine in 1214 CE"}, {"entity": "Magna Carta", "relationship": "BARONS_MET_TO_PLAN", "note": "November 1214 secret meeting at abbey directly set in motion Magna Carta's 1215 signing"}, {"entity": "Stephen Langton", "relationship": "READ_CORONATION_CHARTER_AT", "note": "Archbishop Langton read Henry I's Charter at 1214 meeting inspiring barons' constitutional demands"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Bury St Edmunds Abbey is where the barons who forced Magna Carta swore their constitutional oath — making it the indirect birthplace of English constitutional government, and the direct link between a 9th-century Viking martyrdom and the 13th-century constitutional revolution.", "significanceCategory": "world-changing"},
    }),
    ("byland-abbey", {
        "summary": "Byland Abbey in North Yorkshire, England, founded in 1177 CE after a remarkable 60-year search for a permanent home by Savignac (later Cistercian) monks who moved from Ireland to Wales to Scotland to six different Yorkshire locations before settling at Byland, is architecturally notable as the first English church to use a large rose window — an innovation that influenced the Gothic cathedrals of York, Lincoln, and eventually French Gothic design. The abbey's west front, with its fragmentary rose window (14 meters diameter), was the largest rose window in England.\n\nThe founding community began in 1134 as a Savignac abbey at Furness (Lancashire), then moved repeatedly: to Hood (1138), Byland (initial, 1143), Stocking (1147), and finally permanent Byland (1177) after resolving a complex dispute with Rievaulx Abbey (3 miles away) over the tolling of their bells — two Cistercian monasteries too close to each other created scheduling conflicts. The 60-year wandering before permanent settlement is unique in English monastic history.\n\nByland's architectural innovation — the west rose window of c. 1200 CE, using geometric tracery in a scale unprecedented in England — was observed and influenced York Minster's 13th-century construction (York's Dean's Eye, 1220 CE). The dissolution (1538) left extensive ruins including the distinctive half-standing west facade with its fragmentary rose wheel. Archaeological excavation revealed the original medieval tile floor — one of the most elaborate in England — now displayed in the site museum.",
        "causes": ["1134 Savignac founding with 60 years of wandering before 1177 permanent settlement at Byland", "Bell-tolling dispute with Rievaulx Abbey (3 miles away) forcing final location compromise", "c. 1200 CE rose window construction as first large rose window in England", "1538 dissolution creating extensive ruins including distinctive rose window facade"],
        "effects": ["First large English rose window (14 meters) influencing York Minster and English Gothic cathedral design", "60-year monastic wandering as unique record of founding community persistence and adaptation", "Medieval tile floor remains as one of England's most elaborate monastic floor programs", "Rose window facade ruins as defining image of North Yorkshire monastic landscape"],
        "relationships": [{"entity": "Rievaulx Abbey", "relationship": "BELL-TOLLING_DISPUTE_WITH", "note": "Bell conflict with Rievaulx (3 miles away) forced Byland's final location compromise"}, {"entity": "York Minster", "relationship": "ARCHITECTURAL_INFLUENCE_ON", "note": "Byland's c. 1200 rose window preceded and influenced York's 1220 Dean's Eye rose window"}, {"entity": "Henry VIII", "relationship": "DISSOLVED_BY", "note": "1538 dissolution left extensive ruins including distinctive fragmentary rose window facade"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "Byland Abbey's first large rose window (c. 1200 CE) — influencing York Minster and English Gothic cathedral development — demonstrates how a monastic building can create an architectural innovation that outlasts the institution itself by centuries.", "significanceCategory": "regional"},
    }),
    ("jervaulx-abbey", {
        "summary": "Jervaulx Abbey in North Yorkshire, England, founded in 1156 CE as a Cistercian monastery in the lower Ure valley (Jervaulx — 'Ure's valley' in Norman French), is perhaps the most picturesque and romantically overgrown monastic ruin in England — extensively covered in wildflowers and self-seeded plants that give it an organic, fairy-tale quality. Jervaulx is historically notable as the probable origin of Wensleydale cheese (Cistercian monks are credited with creating the first version using milk from local sheep) and the breeding of the English thoroughbred horse on monastic lands.\n\nThe abbey's founding community moved from Fors (in the Yorkshire Dales) to Jervaulx in 1156, attracted by better agricultural land. The Cistercian model of agricultural self-sufficiency — the 'White Monks' worked their granges (outlying farms) using lay brothers — was exceptionally well suited to the rich Ure valley. Jervaulx monks are credited with creating Wensleydale cheese (originally made with ewes' milk) as a means of preserving surplus dairy production, creating a product that survived the abbey's dissolution.\n\nJervaulx's last abbot, Adam Sedbergh, was involved in the Pilgrimage of Grace (1536) — the massive northern uprising against Henry VIII's dissolution of monasteries. Sedbergh was arrested, tried for treason, and hanged, drawn, and quartered. Henry VIII ordered Jervaulx's deliberate destruction (1537), and local farmers were granted permission to remove stones for building — creating the distinctive partial demolition that allowed self-seeding vegetation to colonize the ruins over 480 years.",
        "causes": ["1156 CE Cistercian founding in Ure valley demonstrating Cistercian agricultural land selection", "Wensleydale cheese creation attributed to Cistercian preservation of surplus sheep's milk", "Pilgrimage of Grace participation by last abbot Adam Sedbergh leading to treason execution", "Deliberate destruction ordered 1537 with stone removal permission creating overgrown romantic ruins"],
        "effects": ["Wensleydale cheese survival 480 years after monastery's destruction as culinary legacy", "Most romantically overgrown monastic ruins in England attracting landscape artists and photographers", "Thoroughbred horse breeding on monastic lands contributing to English racing tradition", "Adam Sedbergh's execution as symbol of northern resistance to Henrician dissolution"],
        "relationships": [{"entity": "Wensleydale Cheese", "relationship": "PROBABLE_CREATOR_OF", "note": "Cistercian monks' sheep's milk preservation created original Wensleydale — surviving 480 years after abbey"}, {"entity": "Adam Sedbergh", "relationship": "LAST_ABBOT", "note": "Last abbot hanged for Pilgrimage of Grace involvement; Henry VIII ordered Jervaulx's deliberate destruction"}, {"entity": "Pilgrimage of Grace", "relationship": "PARTICIPATED_IN", "note": "1536 northern uprising against dissolution; Jervaulx involvement led to abbot's execution and abbey's destruction"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "Jervaulx Abbey's legacy — Wensleydale cheese still produced 480 years after the monastery's dissolution — demonstrates the most delicious example of monastic agricultural innovation outlasting the institution that created it.", "significanceCategory": "regional"},
    }),
    ("klosterneuburg-monastery", {
        "summary": "Klosterneuburg Monastery (Stift Klosterneuburg), founded in 1114 CE by Margrave Leopold III of Austria (later canonized) in Lower Austria above the Danube just north of Vienna, is one of Austria's most important and oldest monasteries — housing the Verduner Altar (1181 CE, one of the greatest Romanesque enamel works in Europe, with 51 gilded enamel panels by Nicholas of Verdun), the coronation relics of the Babenberg dynasty, and a remarkable 18th-century imperial residential palace that Charles VI planned to rival Versailles. The monastery is both an active Augustinian canon community and one of Austria's top ten tourist destinations.\n\nLeopold III's founding legend: according to tradition, his wife's veil was blown from Klosterneuburg hill by wind on their wedding night; nine years later, Leopold found it preserved — undamaged — in a briar bush on the exact spot, interpreting this as a divine sign to found a monastery. The Verduner Altar (Klosterneuburger Altar, 1181 CE) — commissioned by Leopold's successor Provost Wernher and created by Nicholas of Verdun — is considered the most important Romanesque enamel work in the world, its 51 panels depicting Old and New Testament typological parallels in translucent enamel on gilded copper.\n\nThe 18th-century Habsburg expansion: Emperor Charles VI (r. 1711-1740) planned to transform Klosterneuburg into a Habsburg Escorial — an Austrian equivalent of Philip II's Spanish palace-monastery complex. Only one of nine planned domed towers was completed before Charles's death, but the single baroque dome — topped with an imperial crown and the Habsburg ducal crown (the crown's distinctive arched band) — became the iconic view of Klosterneuburg from the Danube. The monastery winery (one of Austria's largest, with 80 hectares of vineyard) produces award-winning wines.",
        "causes": ["1114 CE founding by Leopold III following divine sign legend on Klosterneuburg hill", "Verduner Altar 1181 CE commissioning creating most important Romanesque enamel work in Europe", "Charles VI's Escorial ambition transforming monastery into partial Baroque imperial palace", "Augustinian canon community continuous 910-year occupation making it active living monastery"],
        "effects": ["Verduner Altar's 51 Nicholas of Verdun enamel panels as peak Romanesque metalwork achievement", "Babenberg coronation relic treasury preserving Austria's founding dynastic heritage", "Partially completed Charles VI Baroque dome creating distinctive Danube panorama", "80-hectare monastery winery producing award-winning Lower Austrian wines"],
        "relationships": [{"entity": "Leopold III of Austria", "relationship": "FOUNDED_BY", "note": "Leopold III founded monastery 1114 CE following divine sign legend; later canonized as patron of Austria"}, {"entity": "Nicholas of Verdun", "relationship": "VERDUNER_ALTAR_BY", "note": "Nicholas's 51 enamel panels (1181 CE) constitute most important Romanesque enamel work in Europe"}, {"entity": "Charles VI", "relationship": "BAROQUE_EXPANSION_BY", "note": "Charles VI's unrealized Escorial plan produced one dome — the iconic Habsburg-crowned Danube landmark"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Klosterneuburg Monastery — housing the greatest Romanesque enamel work in Europe (Verduner Altar) and Austria's founding dynastic relics — is the physical repository of Austria's Babenberg heritage and the site where Habsburg imperial ambition (Charles VI's incomplete Escorial) meets Romanesque artistic achievement.", "significanceCategory": "continental"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 93 — Class 344 Abbeys II")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
