#!/usr/bin/env python3
"""Batch 70 — Class 330 Finance II (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/330-Class-330"
FILE_PREFIX = "330"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("citibank", {
        "summary": "Citibank (Citigroup Inc.) is one of the world's largest financial institutions, founded in 1812 as the City Bank of New York, becoming the first US bank to issue credit cards (1950 Diners Club partnership), first bank with an ATM network (1977), and one of the most globally interconnected banks in history. At its 2007 peak, Citigroup was the world's largest bank by assets, but its catastrophic exposure to subprime mortgage securities during the 2008 financial crisis required a $45 billion US government bailout.\n\nCitibank's history parallels American finance: founded by city merchants, it financed the US Civil War, helped fund the Erie Canal, and by the 1920s was America's largest bank. John Reed and Walter Wriston transformed Citibank in the 1970s-1980s through credit card innovations (including the Citi card's move to South Dakota to escape New York usury limits) and aggressive global expansion. Sandy Weill's 1998 merger of Citicorp with Travelers Group creating Citigroup was the largest corporate merger in history at the time, requiring repeal of the Glass-Steagall Act.\n\nThe 2008 crisis exposed Citigroup's overexposure to collateralized debt obligations: the bank lost $27.7 billion in 2008 alone and required three separate government bailouts totaling $45 billion. The US government owned 27% of Citigroup stock during the crisis period. Citigroup's near-collapse demonstrated the 'too big to fail' problem and directly influenced the Dodd-Frank financial reform legislation.",
        "causes": ["1812 founding as New York's commercial banking infrastructure", "Credit card innovation and global expansion under Reed and Wriston transforming retail banking", "1998 Citicorp-Travelers merger — largest in history — requiring Glass-Steagall repeal", "Aggressive subprime mortgage CDO accumulation creating catastrophic 2008 crisis exposure"],
        "effects": ["$45 billion US government bailout required making Citigroup emblem of 'too big to fail'", "2008 collapse directly influenced Dodd-Frank financial reform legislation", "Credit card innovations transformed consumer banking globally", "Glass-Steagall repeal for Citicorp merger accelerated banking deregulation"],
        "relationships": [{"entity": "2008 Financial Crisis", "relationship": "CENTRAL_TO", "note": "Citigroup's $45 billion bailout made it the emblematic 'too big to fail' bank"}, {"entity": "Sandy Weill", "relationship": "SHAPED_BY", "note": "Weill's 1998 Citicorp-Travelers merger created Citigroup as universal bank"}, {"entity": "Glass-Steagall Act", "relationship": "CONTRIBUTED_TO_REPEAL_OF", "note": "1998 Citicorp-Travelers merger required effective repeal of Glass-Steagall banking separation"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Citibank's 2008 near-collapse requiring $45 billion in government bailouts made it the defining emblem of 'too big to fail' financial institutions, and the credit card innovations it pioneered transformed global consumer banking.", "significanceCategory": "world-changing"},
    }),
    ("ubs", {
        "summary": "UBS Group AG is Switzerland's largest bank and one of the world's major wealth management institutions, formed through the 1998 merger of Union Bank of Switzerland (UBS) and Swiss Bank Corporation. As the world's largest private wealth manager with $3.9 trillion in assets under management, UBS serves ultra-high-net-worth individuals, sovereign wealth funds, and institutional investors across 50+ countries.\n\nSwitzerland's banking secrecy tradition, codified in the 1934 Federal Banking Act, made Swiss banks the global repository for assets requiring discretion — from Nazi-era Jewish accounts to tax evaders to legitimate wealth. UBS benefited from this tradition before becoming the subject of the most consequential banking secrecy dispute in history: a 2007 US Department of Justice investigation into UBS helping American clients evade taxes through secret accounts. In 2009, UBS agreed to pay $780 million in fines and provide names of 4,450 American account holders — effectively ending Swiss banking secrecy as traditionally practiced.\n\nUBS also suffered a 2008 financial crisis loss of $21 billion from subprime mortgage investments, requiring a 6 billion Swiss franc emergency bailout from the Swiss government. The bank's 2023 emergency acquisition of Credit Suisse — UBS's chief Swiss rival — for 3 billion Swiss francs (compared to Credit Suisse's book value of 45 billion) prevented a banking crisis but created a bank with a $1.6 trillion balance sheet larger than Switzerland's entire GDP, raising 'too big to fail' concerns for a small nation.",
        "causes": ["1998 UBS-Swiss Bank Corporation merger creating Switzerland's largest bank", "Swiss banking secrecy tradition making UBS global wealth management destination", "US DOJ 2007 investigation into UBS tax evasion assistance", "2008 subprime mortgage losses requiring Swiss government emergency bailout"],
        "effects": ["2009 settlement effectively ended Swiss banking secrecy as traditional practice", "Emergency Credit Suisse acquisition 2023 created bank larger than Switzerland's GDP", "$780 million fine and 4,450 account names handed to US DOJ", "World's largest private wealth manager with $3.9 trillion under management"],
        "relationships": [{"entity": "Swiss Banking Secrecy", "relationship": "ENDED_BY", "note": "2009 US DOJ settlement forcing UBS to reveal account names effectively ended Swiss banking secrecy"}, {"entity": "Credit Suisse", "relationship": "ACQUIRED", "note": "Emergency acquisition of Credit Suisse for 3 billion CHF in 2023 prevented banking crisis"}, {"entity": "2008 Financial Crisis", "relationship": "DAMAGED_BY", "note": "$21 billion subprime losses required 6 billion CHF Swiss government emergency bailout"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "UBS's 2009 surrender of 4,450 client names to the US DOJ effectively ended Swiss banking secrecy — a 75-year tradition that had sheltered wealth from Nazi persecution to tax evasion — transforming global private banking forever.", "significanceCategory": "world-changing"},
    }),
    ("unicredit", {
        "summary": "UniCredit is Italy's largest bank and one of Europe's major financial institutions, formed in 1998 from the merger of several Italian regional banks and transformed into a major European bank through acquisitions including HypoVereinsbank (Germany, 2005) and Bank Austria Creditanstalt (Austria). UniCredit operates in 17 European countries with particular strength in Germany, Austria, and Central and Eastern Europe.\n\nThe bank's origins trace to the Cassa di Risparmio di Verona (1825) and the merger wave that created modern Italian banking. UniCredit's cross-border European expansion made it a test case for the European single banking market — a bank headquartered in Milan with major operations in Germany and Austria operating under common ECB supervision after 2014. The European Central Bank's supervision of UniCredit began when the bank's assets exceeded €30 billion.\n\nUniCredit's exposure to Italian sovereign debt — one of Europe's most precarious — has made it a recurring focus of European financial stability concerns during the Eurozone debt crisis (2010-2015) and subsequent Italian political crises. CEO Andrea Orcel, who took over in 2021, has pursued aggressive capital return programs and expansion discussions with potential acquisition targets including Commerzbank (Germany, 2024 stake purchase) and Monte dei Paschi di Siena, positioning UniCredit as a potential European banking champion. The 2024 Commerzbank stake acquisition raised tensions with the German government.",
        "causes": ["1998 Italian banking merger wave creating unified national banking champion", "European single market requiring pan-European banking institutions", "HypoVereinsbank and Bank Austria acquisitions extending UniCredit across Central Europe", "ECB banking union supervision creating framework for cross-border European banking"],
        "effects": ["Pan-European operations in 17 countries made UniCredit test case for EU banking union", "Italian sovereign debt exposure made UniCredit focal point of Eurozone crisis concerns", "2024 Commerzbank stake purchase created tensions with German government over national ownership", "Andrea Orcel's aggressive expansion strategy positioned UniCredit as potential European banking champion"],
        "relationships": [{"entity": "European Central Bank", "relationship": "SUPERVISED_BY", "note": "ECB supervises UniCredit as systemically important European bank since banking union 2014"}, {"entity": "Commerzbank", "relationship": "ACQUIRED_STAKE_IN", "note": "2024 stake purchase in Commerzbank created German government tensions over banking sovereignty"}, {"entity": "Italian Sovereign Debt Crisis", "relationship": "EXPOSED_TO", "note": "UniCredit's Italian sovereign debt holdings made it focal point during Eurozone crisis"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "UniCredit's cross-border European expansion represents the realization of the EU single banking market, while its Italian sovereign debt exposure and Commerzbank acquisition ambitions make it a focal point of European financial integration debates.", "significanceCategory": "continental"},
    }),
    ("credit-suisse", {
        "summary": "Credit Suisse was Switzerland's second-largest bank and one of the world's major investment banks, founded in 1856 by Alfred Escher to finance Swiss railway construction. The bank's 167-year history ended dramatically in March 2023 when a cascade of scandals, client withdrawals, and loss of confidence forced an emergency acquisition by UBS for 3 billion Swiss francs — the largest bank rescue since the 2008 financial crisis and the end of Switzerland's 'two-bank' model.\n\nCredit Suisse's 2020s collapse resulted from a remarkable accumulation of scandals: a 2021 executive surveillance scandal (the bank spied on employees), the Archegos Capital collapse ($5.5 billion loss, 2021), the Greensill Capital supply-chain finance collapse ($10 billion in funds frozen, 2021), fines for helping Bulgarian cocaine traffickers launder money (2022), and a conviction for failing to prevent money laundering (2022). The scandals destroyed client confidence; in 2022, clients withdrew $120 billion in deposits in a single quarter.\n\nThe Swiss government's March 2023 emergency brokering of UBS's acquisition for 3 billion CHF (compared to Credit Suisse's stated book value of 45 billion CHF) wiped out $17 billion of AT1 (Additional Tier 1) bonds — bonds that in normal restructuring would have been protected above equity. The decision to honor equity claims while wiping AT1 bonds created controversy across global financial markets and highlighted the risks of complex bank capital structures.",
        "causes": ["Alfred Escher's 1856 founding to finance Swiss railway construction", "Accumulation of 2021-2023 scandals destroying client confidence and triggering deposit flight", "$5.5B Archegos and $10B Greensill losses exposing risk management failures", "2022 money laundering conviction undermining regulatory standing"],
        "effects": ["$120 billion client deposit withdrawal in single 2022 quarter showing bank run dynamics in modern banking", "UBS emergency acquisition for 3 billion CHF versus 45 billion book value destroyed shareholder value", "AT1 bond wipeout created global controversy about bank capital structure priorities", "End of Credit Suisse eliminated Switzerland's second bank and 167-year institution"],
        "relationships": [{"entity": "UBS", "relationship": "ACQUIRED_BY", "note": "Emergency UBS acquisition for 3 billion CHF in March 2023 ended Credit Suisse"}, {"entity": "Archegos Capital", "relationship": "DAMAGED_BY", "note": "$5.5 billion loss from Archegos collapse in 2021 was major factor in Credit Suisse's decline"}, {"entity": "Swiss Government", "relationship": "RESCUED_BY", "note": "Swiss government brokered emergency UBS acquisition to prevent Credit Suisse bankruptcy"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Credit Suisse's 2023 collapse — the largest Western bank failure since 2008 — demonstrated how accumulated scandals and loss of confidence can destroy even 167-year-old systemically important institutions, and its AT1 bond wipeout reverberated through global financial markets.", "significanceCategory": "continental"},
    }),
    ("standard-chartered", {
        "summary": "Standard Chartered is a British multinational banking and financial services company headquartered in London that operates primarily in Asia, Africa, and the Middle East — an unusual profile for a major Western bank. Founded through the 1969 merger of Standard Bank (South Africa) and Chartered Bank of India, Australia and China, Standard Chartered derives over 90% of its income from emerging markets, making it the most internationally exposed of the major British banks.\n\nThe bank's roots reflect British imperial expansion: Chartered Bank was founded in 1853 to finance trade between Britain, India, China, and Australia; Standard Bank was founded in 1862 to serve South African and West African trade. The bank financed Hong Kong's growth as a trading center and was the clearing bank for India before the Reserve Bank of India's establishment. Standard Chartered maintains a particularly strong presence in Sub-Saharan Africa, Hong Kong, Singapore, and the Middle East.\n\nStandard Chartered's modern history includes a $667 million settlement with US authorities in 2012 for violating Iran sanctions by processing billions in transactions with Iranian clients in violation of US law. A second 2019 settlement added $1.1 billion in fines for further sanctions violations. These sanctions breaches demonstrated the tension between a bank with deep Middle East roots and US extraterritorial enforcement of Iran sanctions — a controversy that affected all international banks with historical ties to sanctioned nations.",
        "causes": ["1969 merger of Standard Bank (South Africa) and Chartered Bank of India creating unified emerging markets bank", "British imperial banking networks in India, Hong Kong, Africa providing institutional foundation", "Emerging markets growth strategy requiring deep roots in Asia, Africa, Middle East", "Iran sanctions complexity affecting banks with historical Middle East business relationships"],
        "effects": ["$1.8 billion in US fines for Iran sanctions violations established high cost of sanctions non-compliance", "90% emerging markets income created different risk profile from Western-focused banks", "Maintained banking infrastructure in markets other Western banks avoided", "Iran sanctions settlements demonstrated US extraterritorial enforcement reach"],
        "relationships": [{"entity": "British Empire", "relationship": "ROOTED_IN", "note": "Bank's origins in imperial trading finance between Britain, India, China, and Africa"}, {"entity": "Hong Kong", "relationship": "CLEARING_BANK_FOR", "note": "Standard Chartered has been Hong Kong's principal clearing bank for over a century"}, {"entity": "US Department of Justice", "relationship": "FINED_BY", "note": "$1.8 billion in fines for Iran sanctions violations in 2012 and 2019"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "Standard Chartered's emergence as a major bank whose business is concentrated in Asia, Africa, and the Middle East represents the banking legacy of the British Empire and the continuing financial integration of developing world markets.", "significanceCategory": "continental"},
    }),
    ("credit-agricole-group", {
        "summary": "Crédit Agricole is France's largest bank by assets and one of Europe's largest banking groups, rooted in the cooperative agricultural credit network founded in 1894 by the French government to provide low-interest loans to farmers. The 'Green Bank' (from its agricultural origins) transformed over a century from local farm credit cooperatives into a full-service financial conglomerate with insurance, asset management, and investment banking operations across Europe.\n\nCrédit Agricole's cooperative structure is unique among major European banks: the bank is ultimately owned by 11 regional banks (Caisses régionales) that are in turn owned by 10.6 million farmer and customer-members. This mutuelle structure means Crédit Agricole has no external shareholders to satisfy, though it listed Crédit Agricole S.A. (the central entity) on the Paris stock exchange in 2001. The cooperative model has historically provided greater stability — Crédit Agricole survived the 2008 financial crisis without government bailout.\n\nCrédit Agricole serves 50 million clients in 50 countries and manages €2.1 trillion in assets. Its insurance subsidiary Predica (life insurance) and Pacifica (non-life insurance) make it one of France's largest insurers. The bank's 2003 acquisition of Crédit Lyonnais — one of France's most historic banks, which had required a 1993 government bailout of €18 billion — transformed Crédit Agricole from agricultural specialist to full-service bank. Amundi, Crédit Agricole's asset management subsidiary, is Europe's largest asset manager with €2 trillion in assets.",
        "causes": ["1894 French government creation of agricultural credit cooperatives to finance farmers", "Rural banking network's organic growth from farm credit to full-service banking", "Cooperative mutuelle ownership model providing stability through external crises", "Crédit Lyonnais acquisition 2003 transforming agricultural bank into financial conglomerate"],
        "effects": ["Cooperative ownership by 10.6 million members created uniquely stable European bank", "Amundi European asset management leadership with €2 trillion", "Agricultural credit model became template for rural cooperative banking globally", "Crédit Lyonnais acquisition resolved France's 1990s banking crisis legacy"],
        "relationships": [{"entity": "French Government", "relationship": "FOUNDED_BY", "note": "French government established agricultural credit cooperatives in 1894"}, {"entity": "Amundi", "relationship": "PARENT_OF", "note": "Crédit Agricole's Amundi is Europe's largest asset manager with €2 trillion"}, {"entity": "Crédit Lyonnais", "relationship": "ACQUIRED", "note": "2003 acquisition of historically important French bank expanded operations beyond agriculture"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "Crédit Agricole's transformation from government-created agricultural cooperative to Europe's largest bank represents a unique model of mutuelle banking — owned by farmer-members — that survived 2008 without government bailout and serves as alternative to shareholder-owned banking.", "significanceCategory": "continental"},
    }),
    ("banco-santander", {
        "summary": "Banco Santander is Spain's largest bank and one of Europe's biggest financial institutions, founded in 1857 in Santander, Spain, and transformed under Emilio Botín into a global banking powerhouse through acquisitions in Latin America, the UK, US, and Continental Europe. Santander's international expansion, particularly into Brazil (where Santander Brasil is one of the country's largest banks), Mexico, and the UK (through Abbey National acquisition, 2004), created a banking model that diversified geographic risk unlike purely domestic banks.\n\nEmilio Botín Sr. (1934-2014) led Santander for 29 years, expanding it from a medium-sized Spanish bank into the Eurozone's largest bank by market capitalization during his tenure. Botín's strategy of acquiring underperforming domestic banks in target markets (Abbey National in the UK, Sovereign Bancorp in the US, Banco Real in Brazil) and integrating them under Santander's systems created a scalable international model. His daughter Ana Botín succeeded him as executive chairman in 2014.\n\nSantander's exposure to Latin American economies creates both opportunity and risk: the bank has benefited from Brazil's economic growth but suffered during periods of Brazilian and Argentine economic instability. Santander Brasil's listing on the São Paulo stock exchange (Bovespa) created the largest Latin American bank IPO at the time. The bank serves 168 million customers in 10 core markets and manages €1.1 trillion in deposits.",
        "causes": ["1857 founding in Santander supporting Spain's northern trade and industrial development", "Emilio Botín's vision of international expansion through targeted domestic bank acquisitions", "Latin American banking markets offering growth opportunities exceeding slow-growth Europe", "Euro adoption enabling pan-European banking consolidation"],
        "effects": ["International model diversifying geographic risk across 10 core markets", "Brazil expansion making Santander Brasil one of Latin America's largest banks", "Abbey National acquisition extending Spanish banking into UK retail market", "168 million customers across 10 markets created globally diversified banking network"],
        "relationships": [{"entity": "Emilio Botín", "relationship": "EXPANDED_UNDER", "note": "Botín's 29-year leadership transformed Santander from Spanish regional bank to Eurozone giant"}, {"entity": "Abbey National", "relationship": "ACQUIRED", "note": "2004 UK acquisition extended Santander into British retail banking market"}, {"entity": "Brazil", "relationship": "MAJOR_MARKET_IN", "note": "Santander Brasil among largest Brazilian banks; major source of international revenues"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Banco Santander's transformation from regional Spanish bank to Europe's largest bank by market capitalization under Emilio Botín represents the most successful execution of international banking expansion through domestic acquisition in the European model.", "significanceCategory": "continental"},
    }),
    ("bank-of-amsterdam", {
        "summary": "The Wisselbank Amsterdam (Amsterdam Exchange Bank) was founded in 1609 by the Amsterdam city government as the world's first modern central bank and a precursor of modern banking systems. The Bank of Amsterdam introduced currency stability to a Dutch Republic flooded with debased foreign coins, accepted deposits of commercial coins and issued standardized bank money ('bank guilders') at their full metal value — creating a reliable transaction medium for Amsterdam's global trade network.\n\nThe Bank of Amsterdam's innovation was profound: by maintaining strict reserve requirements and issuing bank money that traders trusted because it was fully backed by metal reserves, the bank created the prototype of a central bank's monetary function. Amsterdam's status as the world's financial center in the 17th century — its stock exchange (founded 1611) was the world's first permanent stock exchange, and its VOC (Dutch East India Company) the world's first publicly traded company — depended fundamentally on the Bank of Amsterdam's monetary stability.\n\nThe bank operated for 183 years until 1791, when it collapsed after the French-backed Batavian Republic took power. Its final decades saw declining standards: the bank had lent money to the VOC (in violation of its charter) and to the City of Amsterdam, departing from its reserve backing. The Bank of Amsterdam's model directly influenced the Bank of England (founded 1694) and the theoretical development of central banking, making it arguably the most historically important financial institution ever created despite its relatively small scale.",
        "causes": ["Amsterdam's flooding with debased foreign coins requiring currency standardization", "Dutch Republic's global trade network requiring reliable payment medium", "City of Amsterdam's establishment of municipal bank to serve merchant community", "VOC and stock exchange activity requiring reliable financial infrastructure"],
        "effects": ["Bank guilder became trusted international trade currency through full metal backing", "Provided monetary foundation for Amsterdam's 17th-century position as world's financial center", "Bank of England and subsequent central banks modeled on Amsterdam's reserve principles", "183-year operation demonstrated viability of government-backed monetary institution"],
        "relationships": [{"entity": "Amsterdam Stock Exchange", "relationship": "SUPPORTED", "note": "Bank provided monetary infrastructure for world's first permanent stock exchange (1611)"}, {"entity": "Bank of England", "relationship": "MODELED", "note": "Bank of England (1694) directly modeled on Bank of Amsterdam's reserve principles"}, {"entity": "Dutch East India Company", "relationship": "SERVED", "note": "Bank provided financial infrastructure for VOC, world's first publicly traded company"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Bank of Amsterdam (1609) was the world's first modern central bank, whose reserve-backed currency innovation provided the monetary foundation for Amsterdam's 17th-century global financial supremacy and directly inspired the Bank of England — making it the founding institution of modern banking.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 70 — Class 330 Finance II")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
