#!/usr/bin/env python3
"""Batch 122 — Mixed: Class 344 Abbeys IV (4) + Class 343 Temples V (4)"""
import json, os
from datetime import datetime, timezone

FOLDER_344 = "data/appwrite-export/entities/344-Class-344"
FOLDER_343 = "data/appwrite-export/entities/343-Class-343"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("bective-abbey", {
        "summary": "Bective Abbey (Irish: Mainistir Bheigti), founded in 1147 CE on the banks of the River Boyne in County Meath, Ireland, by Murchad O'Melaghlin, King of Meath, as the second Cistercian monastery established in Ireland (after Mellifont in 1142), is one of the best-preserved medieval monastic sites in Ireland — featuring substantial surviving Gothic and Romanesque architecture including cloisters, chapter house, and church remains — and was historically significant as a major Cistercian foundation in the English Pale that wielded considerable religious and political influence in medieval Ireland.\n\nBective Abbey's Cistercian affiliation placed it within the most internationally connected religious order of the 12th-13th centuries. The Cistercian movement, founded at Cîteaux in 1098 and rapidly spreading across Europe under Bernard of Clairvaux's influence, brought standardized architectural forms, agricultural innovation, and liturgical practices to Ireland. Bective's relatively large endowment (given by the O'Melaghlin kings) enabled its substantial construction program. The abbey was the site of Hugh de Lacy's burial (head) in 1195 — Hugh de Lacy was one of the most powerful Anglo-Norman lords in Ireland, and his dismemberment meant different parts were buried in different locations.\n\nBective was dissolved during the Suppression of the Monasteries by Henry VIII in 1537 and converted into a fortified house for the Dillon family. The substantial masonry surviving today — particularly the square cloister with large Gothic windows and the impressive walls — represents the converted lay use period as well as the original monastery. The site is now a National Monument in State care and has appeared in several film and television productions including Braveheart (1995).",
        "causes": ["1147 founding by Murchad O'Melaghlin as part of the Cistercian expansion wave transforming medieval Irish monasticism", "Cistercian order's 12th-century European expansion requiring new foundations in newly converted kingdoms", "O'Melaghlin royal patronage providing endowments enabling substantial building program", "Hugh de Lacy's political significance and Bective's role in the Anglo-Norman settlement of Ireland"],
        "effects": ["Cistercian architectural standards introducing Romanesque and Gothic forms to medieval Irish sacred buildings", "Anglo-Norman Pale integration making Bective a religious institution in England's colonial Irish administration", "Henry VIII's 1537 Dissolution ending monastic life and converting the site to fortified private residence", "Bective's surviving masonry making it one of Ireland's best-preserved medieval monastic sites"],
        "relationships": [{"entity": "Cistercian Order", "relationship": "SECOND_IRISH_FOUNDATION_OF", "note": "Bective was the second Cistercian monastery in Ireland, part of the 12th-century wave transforming Irish monasticism"}, {"entity": "Hugh de Lacy", "relationship": "PARTIAL_BURIAL_SITE_OF", "note": "Hugh de Lacy's head was buried at Bective (1195) after his assassination — a political statement about the monastery's significance"}, {"entity": "Henrician Dissolution", "relationship": "SUPPRESSED_DURING", "note": "Bective was dissolved under Henry VIII's 1537 Dissolution of the Monasteries and converted to a fortified house"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "Bective Abbey — the second Cistercian house in Ireland, burial place of Hugh de Lacy, dissolved by Henry VIII, and one of Ireland's best-preserved medieval monastic ruins — is a historically significant monument of Irish medieval religion, Anglo-Norman colonialism, and Reformation disruption.", "significanceCategory": "continental"},
    }, FOLDER_344, "344"),
    ("chiaravalle-della-colomba-abbey", {
        "summary": "Chiaravalle della Colomba Abbey (Italian: Abbazia di Chiaravalle della Colomba, 'Chiaravalle of the Dove'), founded in 1136 CE in the Po Valley near Piacenza in northern Italy, is a significant Cistercian monastery established directly by Bernard of Clairvaux — the defining figure of medieval Cistercian monasticism — according to a foundation legend in which a dove (colomba) descended to mark the site's location chosen by Bernard on his personal visit to northern Italy, giving the abbey both its name and legendary foundation narrative.\n\nThe Chiaravalle della Colomba foundation is one of the few Italian Cistercian monasteries directly associated with Bernard of Clairvaux's own patronage. Bernard's Italian journey in 1135 was primarily political (to resolve the papal schism between Innocent II and Anacletus II), and his foundation of monasteries along the route was part of the Cistercian strategy of establishing spiritual and agricultural outposts throughout Europe. The dove legend and direct Bernardine founding gave Chiaravalle della Colomba exceptional prestige within the Italian Cistercian network.\n\nThe abbey's Lombard Romanesque church (12th-13th century) and cloisters represent significant medieval Italian architecture. The Po Valley setting was ideal for Cistercian agricultural development: the order's emphasis on draining marshlands, improving agricultural techniques, and creating economically productive monasteries transformed large areas of northern Italy. Chiaravalle della Colomba developed extensive agricultural estates and was an important cultural and economic institution in the Piacentine countryside for centuries before Napoleonic suppression in the late 18th century. The abbey was restored as an active monastic community in the 20th century.",
        "causes": ["1136 founding by Bernard of Clairvaux during his Italian political mission combining spiritual and diplomatic purposes", "Dove (colomba) legend providing foundation narrative connecting the site's divine selection to Bernard's direct intervention", "Cistercian agricultural mission transforming the Po Valley's marshlands into productive farmland", "Bernards's Italian journey (1135) establishing Cistercian footholds in the prosperous Lombard region"],
        "effects": ["Direct Bernardine founding giving exceptional prestige within Italian Cistercian institutional network", "Lombard Romanesque architecture representing finest 12th-century ecclesiastical building in the Piacentine region", "Po Valley agricultural transformation through Cistercian drainage and farming technology", "Napoleonic suppression in late 18th century followed by 20th-century Cistercian restoration"],
        "relationships": [{"entity": "Bernard of Clairvaux", "relationship": "DIRECTLY_FOUNDED_BY_DURING_ITALIAN_MISSION", "note": "Bernard personally founded Chiaravalle della Colomba in 1136 during his Italian mission, giving it exceptional Cistercian prestige"}, {"entity": "Cistercian Agricultural Innovation", "relationship": "PO_VALLEY_AGRICULTURAL_TRANSFORMATION_SITE_OF", "note": "The abbey's Cistercian management transformed the Po Valley through drainage and agricultural improvement"}, {"entity": "Lombard Region", "relationship": "PRINCIPAL_CISTERCIAN_INSTITUTION_OF", "note": "Chiaravalle della Colomba was the most prestigious Cistercian monastery in the Piacentine countryside"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Chiaravalle della Colomba Abbey — directly founded by Bernard of Clairvaux, home to significant Lombard Romanesque architecture, and transforming Po Valley agriculture through Cistercian management — is one of Italy's most historically significant medieval Cistercian monasteries.", "significanceCategory": "world-changing"},
    }, FOLDER_344, "344"),
    ("fischbeck-abbey", {
        "summary": "Fischbeck Abbey (German: Kloster Fischbeck) on the Weser River in Lower Saxony, Germany, founded circa 954-955 CE during the Ottonian dynasty as a women's religious foundation, is one of the oldest continuously existing women's religious communities in Germany — operating continuously for over a thousand years as a convent of canonesses (Damenstift) rather than strictly enclosed nuns, and maintaining its noble aristocratic character as a foundation for women of the German nobility throughout its history, surviving the Reformation as a Lutheran chapter house when the region converted to Protestantism in the 16th century.\n\nFischbeck's founding under the Ottonian dynasty reflects the active role of aristocratic women in establishing religious foundations in the medieval German world. Ottonian women — particularly the empresses and noblewomen of the 10th-century Ottonian Renaissance — were among the most significant religious patrons of their era. Fischbeck, like other Stifte (collegiate foundations) for women, provided noble women with religious community, education, and independence outside marriage while maintaining their aristocratic social position.\n\nThe abbey's survival through the Lutheran Reformation (unlike most Catholic monasteries that were suppressed) is historically significant: the region's 16th-century conversion to Lutheranism transformed Fischbeck into a Lutheran ladies' chapter (Damenstift), where noble women continued to live in community but without the strictly Catholic monastic framework. This Lutheran collegiate form for noblewomen has roots in the medieval Stift tradition. Fischbeck preserves Romanesque architecture (the church dates primarily to the 12th century) and remarkable medieval textiles including the famous Fischbeck Tapestries, a set of 12th-century narrative embroideries.",
        "causes": ["954-955 CE Ottonian founding as aristocratic women's religious foundation reflecting Ottonian patronage culture", "Noble women's Stift tradition requiring collegiate communities for unmarried or widowed noblewomen", "Romanesque church construction in 12th century creating architectural centerpiece of the foundation", "Lutheran Reformation survival through conversion to Protestant Damenstift retaining collegiate character"],
        "effects": ["Thousand-year continuous women's religious community making Fischbeck one of Germany's oldest intact institutions", "Fischbeck Tapestries preservation as 12th-century narrative textile treasures of European medieval art history", "Lutheran Stift model demonstrating how medieval aristocratic women's communities adapted to Reformation", "Weser Renaissance architectural additions creating distinctive multi-era architectural ensemble"],
        "relationships": [{"entity": "Ottonian Dynasty", "relationship": "FOUNDED_UNDER_PATRONAGE_OF", "note": "Fischbeck's ~954 founding reflects the Ottonian dynasty's active women's religious patronage"}, {"entity": "Lutheran Reformation", "relationship": "SURVIVED_THROUGH_CONVERSION_TO_PROTESTANT_DAMENSTIFT", "note": "Unlike most Catholic monasteries, Fischbeck survived the Reformation by converting to a Lutheran ladies' chapter"}, {"entity": "Fischbeck Tapestries", "relationship": "PRESERVED_12TH-CENTURY_TEXTILES_AT", "note": "The Fischbeck Tapestries are 12th-century narrative embroideries that are among Germany's most important medieval textile artworks"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Fischbeck Abbey — one of Germany's oldest continuously operating women's religious communities, surviving the Reformation as a Lutheran Damenstift, preserving 12th-century tapestries among Germany's finest medieval textiles, and exemplifying Ottonian aristocratic women's patronage — is a historically significant monument of German medieval and post-Reformation religious history.", "significanceCategory": "world-changing"},
    }, FOLDER_344, "344"),
    ("st-cecilias-abbey-solesmes", {
        "summary": "Saint-Cécile de Solesmes Abbey (Abbaye Saint-Cécile de Solesmes), a Benedictine women's monastery in Solesmes, Sarthe, France — the female counterpart community to the famous Saint-Pierre de Solesmes Abbey (founded 1010) and directly associated with Solesmes's world-renowned Gregorian chant research and performance tradition — was established in 1866 as the first new women's Benedictine community in France after the French Revolution's destruction of most religious houses, under the direction of Dom Prosper Guéranger, the pivotal figure in the 19th-century Gregorian chant revival.\n\nSaint-Cécile's founding by Guéranger in 1866 placed it at the center of the Solesmes Gregorian chant movement — one of the most important developments in the history of Catholic sacred music. Guéranger's Solesmes community had been systematically researching, reconstructing, and performing authentic medieval Gregorian chant since the 1830s, arguing that the corrupt and embellished 17th-18th century Baroque chant editions should be replaced by the medieval originals. This work produced the Solesmes school of chant paleography and performance practice that ultimately shaped the 1903 Motu Proprio of Pope Pius X, which established Gregorian chant as the official music of the Catholic Church's liturgy and explicitly cited the Solesmes research.\n\nThe women's community at Saint-Cécile participates in the same Gregorian chant tradition as Saint-Pierre. The Solesmes Abbey's chant research and the Éditions de Solesmes publications have shaped Catholic liturgical music worldwide. Saint-Cécile de Solesmes continues as an active Benedictine women's community and is internationally recognized for its chant.",
        "causes": ["Dom Guéranger's 1866 founding as female counterpart to Solesmes's Gregorian chant research community", "Post-Revolution restoration of French religious life creating space for new Benedictine foundations", "Gregorian chant revival movement at Solesmes requiring women's community to participate in complete monastic life", "Papal recognition of Solesmes chant work through Pius X's 1903 Motu Proprio legitimizing the research's conclusions"],
        "effects": ["Women's Benedictine community participation in the world's most influential Gregorian chant research tradition", "1903 Motu Proprio formally establishing Gregorian chant as Catholic liturgical music citing Solesmes scholarship", "Solesmes chant recording tradition including Saint-Cécile performances shaping 20th-century Catholic liturgical music worldwide", "Ongoing Benedictine women's community maintaining 150+ year tradition of contemplative life and chant performance"],
        "relationships": [{"entity": "Dom Prosper Guéranger", "relationship": "FOUNDED_AS_COMPANION_COMMUNITY_BY", "note": "Guéranger founded Saint-Cécile in 1866 as the women's counterpart to his Solesmes Gregorian chant research community"}, {"entity": "Gregorian Chant Revival", "relationship": "INSTITUTIONAL_PARTICIPANT_IN", "note": "Saint-Cécile participates in Solesmes's Gregorian chant research and performance tradition that shaped modern Catholic liturgical music"}, {"entity": "Saint-Pierre de Solesmes Abbey", "relationship": "FEMALE_COUNTERPART_COMMUNITY_TO", "note": "Saint-Cécile is the sister community to Saint-Pierre de Solesmes, together constituting Solesmes's full Benedictine monastic establishment"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Saint-Cécile de Solesmes Abbey — participating in the Gregorian chant revival that shaped Catholic liturgical music worldwide, founded by the pivotal Dom Guéranger, and continuing as an active Benedictine women's community — is historically significant as part of the Solesmes tradition that permanently transformed the Catholic Church's musical heritage.", "significanceCategory": "world-changing"},
    }, FOLDER_344, "344"),
    ("temple-of-ellesyia", {
        "summary": "The Temple of Ellesyia (Italian: Tempio di Ellesija) is an ancient Egyptian rock-cut temple originally located at Ellesija in Nubia (now submerged under Lake Nasser following the construction of the Aswan High Dam in the 1960s-1970s), dedicated primarily to Pharaoh Thutmose III (ruled 1479-1425 BCE) and to the gods Horus and Satet — and saved from the dam's flooding through the Italian government's UNESCO rescue effort, with the temple dismantled, transported to Turin, Italy, and reassembled in the Museo Egizio (Egyptian Museum of Turin), where it stands as one of the most unusual museum objects in the world: an entire ancient Egyptian temple rebuilt inside a museum.\n\nThe Temple of Ellesija dates to the New Kingdom (approximately 1430 BCE) and was carved directly into the sandstone cliffs of the Nubian Nile. Rock-cut temples were characteristic of Egyptian Nubian sacred architecture — the most famous examples being the Abu Simbel temples of Ramesses II. Ellesija's temple, though smaller, reflects the same architectural approach: creating sacred space within the living rock of a Nile cliff, with the inner sanctuary oriented to catch the rising sun's rays on specific sacred days.\n\nThe 1960s UNESCO Nubia Campaign to save monuments threatened by the Aswan High Dam's flooding was one of the largest international heritage rescue operations in history. Egypt and Sudan offered rescued monuments to contributing nations — Italy received Ellesija for its early contributions. The temple was dismantled block by block, transported to Turin, and reassembled in a specially designed gallery in the Museo Egizio. The Museo Egizio itself is the world's largest Egyptian museum outside Egypt, making Ellesija's display context extraordinary — an authentic ancient Nubian rock temple inside Italy's premier Egyptian collection.",
        "causes": ["Thutmose III's Nubian campaign establishing Egyptian dominance requiring temple construction in conquered territories", "Rock-cut temple architectural tradition in Nubian Egypt making cliff sanctuaries the regional sacred building norm", "Aswan High Dam UNESCO rescue campaign threatening Ellesija's submersion requiring international salvage effort", "Italy's UNESCO contribution resulting in Egypt's gift of the entire temple structure to the Italian nation"],
        "effects": ["Temple reassembly in Museo Egizio Turin creating one of the world's most extraordinary museum displays: complete ancient temple inside museum", "UNESCO Nubia Campaign establishing international heritage rescue cooperation as template for later UNESCO interventions", "Museo Egizio Turin acquiring world-class Nubian rock temple enhancing its status as premier Egyptian collection outside Egypt", "Ellesija's survival documenting Thutmose III's Nubian temple-building program that complemented his military campaigns"],
        "relationships": [{"entity": "Thutmose III", "relationship": "BUILT_BY_TO_COMMEMORATE_NUBIAN_CAMPAIGNS", "note": "Ellesija was dedicated to Thutmose III alongside Horus and Satet, commemorating his Nubian military dominance"}, {"entity": "UNESCO Nubia Campaign", "relationship": "SAVED_BY_INTERNATIONAL_RESCUE_OPERATION_OF", "note": "The 1960s UNESCO Nubia Campaign saved Ellesija from submersion by dismantling and transporting it to Turin"}, {"entity": "Museo Egizio Turin", "relationship": "REBUILT_AND_DISPLAYED_INSIDE", "note": "The complete Temple of Ellesija was reassembled inside Turin's Egyptian Museum as one of its most extraordinary exhibits"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Temple of Ellesija — saved by the landmark UNESCO Nubia Campaign, reassembled as a complete ancient Egyptian Nubian rock temple inside Turin's Museo Egizio, and documenting Thutmose III's Nubian building program — is historically significant for both its Egyptian content and as a monument to 20th-century international heritage rescue.", "significanceCategory": "world-changing"},
    }, FOLDER_343, "343"),
    ("temple-of-dakka", {
        "summary": "The Temple of Dakka (also: Temple of Thoth at Dakka), a Ptolemaic and Roman-era temple originally located at ancient Pselchis (Dakka) in Nubia — also saved from submersion by the Aswan High Dam's Lake Nasser through the UNESCO Nubia Campaign — is now reassembled at Wadi es-Sebua in southern Egypt, where it stands alongside the relocated temples of Wadi es-Sebua and Maharraqa as a cluster of rescued Nubian temples. The Temple of Dakka was primarily dedicated to Thoth (the god of wisdom, writing, and the moon) in his local Nubian manifestation.\n\nDakka's temple has an unusually complex construction history spanning several centuries: it was originally begun by the Meroitic Nubian King Arkamani (or Ergamenes I, circa 220 BCE) — making it unusual as a temple in Nubia built by the Nubian Meroitic kingdom rather than Egypt. It was subsequently expanded by Ptolemy IV Philopator (approximately 221-205 BCE) and further modified during the Roman period (Augustus through Diocletian, circa 30 BCE-300 CE). This multi-century, multi-cultural construction makes Dakka a unique example of how Nubian, Ptolemaic Greek, and Roman religious traditions interacted and overlapped at the southern margins of Egypt.\n\nThe temple's relocation and reassembly at Wadi es-Sebua makes it part of the remarkable open-air museum of relocated Nubian temples in southern Egypt — alongside Abu Simbel (moved 1968), Philae (moved 1980), Kalabsha, and others. Dakka's Thoth dedication and Meroitic origin provide valuable evidence for religious exchange between Egypt and the Nubian Meroitic Kingdom.",
        "causes": ["Meroitic King Arkamani's circa 220 BCE construction demonstrating Nubian kingdom's adoption of Egyptian temple architecture", "Ptolemaic expansion by Ptolemy IV integrating Dakka into the Greek-Egyptian religious framework", "Roman period modifications continuing the multi-cultural religious synthesis at the Nubian frontier", "Aswan High Dam UNESCO rescue campaign requiring relocation from original Pselchis/Dakka site"],
        "effects": ["Multi-century Meroitic-Ptolemaic-Roman construction sequence providing unique evidence of cultural synthesis at Egypt's southern frontier", "Relocation to Wadi es-Sebua creating open-air museum of rescued Nubian temples", "Thoth worship in Nubia documenting the extension of Egyptian writing and wisdom deity worship into Meroitic religious culture", "UNESCO Nubia Campaign template advancing international heritage cooperation for subsequent endangered site rescue"],
        "relationships": [{"entity": "Meroitic Kingdom", "relationship": "ORIGINALLY_BUILT_BY_KING_OF", "note": "Meroitic King Arkamani began Dakka's construction (~220 BCE), making it unusual as a Nubia-founded temple"}, {"entity": "Ptolemy IV", "relationship": "EXPANDED_DURING_REIGN_OF", "note": "Ptolemy IV Philopator expanded the temple as part of Ptolemaic integration of Nubian religious sites"}, {"entity": "UNESCO Nubia Campaign", "relationship": "RELOCATED_BY_FROM_ORIGINAL_DAKKA_SITE", "note": "UNESCO Nubia Campaign relocated the temple to Wadi es-Sebua alongside other rescued Nubian monuments"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Temple of Dakka — uniquely begun by a Meroitic Nubian king, expanded by Ptolemies and Romans, relocated by the UNESCO Nubia Campaign, and preserved as part of the Wadi es-Sebua open-air museum — is a historically significant example of Nubian-Egyptian-Greco-Roman religious cultural synthesis.", "significanceCategory": "world-changing"},
    }, FOLDER_343, "343"),
    ("temple-of-friendship", {
        "summary": "The Temple of Friendship at Stowe (Stowe Landscape Garden) in Buckinghamshire, England, designed by James Gibbs (circa 1739) and constructed in the grounds of Stowe House as one of the many classical temples in what is considered England's most famous 18th-century landscape garden, is a Doric circular pavilion built in the Ionic tradition and dedicated by the garden's owner (Lord Cobham, Richard Temple, Viscount Cobham) to his political allies — the 'Boy Patriots' including William Pitt the Elder, George Grenville, and other opponents of Robert Walpole — making it an unusual example of a 'temple' that was explicitly political rather than religious.\n\nStowe Landscape Garden is one of the most historically significant designed landscapes in the world — the prototype of the English landscape garden tradition that transformed European and global garden design in the 18th-19th centuries, replacing the formal geometric gardens of the French Baroque (Versailles tradition) with naturalistic landscapes of rolling hills, lakes, groves, and carefully placed classical buildings. The garden's 40+ temples and classical buildings were positioned to create sequences of associative meaning for visitors walking the grounds — each structure's dedication linking to philosophical, political, or moral concepts.\n\nThe Temple of Friendship (rebuilt 1747 after an initial structure) was explicitly political: Lord Cobham, an opponent of Prime Minister Robert Walpole, used the garden's buildings as political statements. The Boy Patriots who opposed Walpole's corrupt Whig administration and supported parliamentary reform were celebrated in the Temple of Friendship while the Temple of Modern Virtue was built as a deliberate ruin to mock Walpole's moral standards. Stowe and its temples influenced Thomas Jefferson (who visited in 1786), affecting the design of Monticello and American landscape philosophy.",
        "causes": ["Lord Cobham's political opposition to Walpole requiring symbolic landscape statements celebrating the Boy Patriots", "18th-century English landscape garden revolution using classical buildings to create associative meaning", "James Gibbs's architectural commission as part of Stowe's systematic garden building program", "Cobham's alliance with Pitt the Elder and other reformist politicians requiring physical commemoration"],
        "effects": ["Temple of Friendship as historically unusual example of explicitly political 'temple' in landscape garden tradition", "Stowe landscape influencing Thomas Jefferson's Monticello design and American landscape philosophy", "English landscape garden tradition (pioneered at Stowe) replacing French formal gardens as the global garden design standard", "Boy Patriots' political cause (Pitt the Elder's group) celebrated in permanent stone as monument to Whig reform opposition"],
        "relationships": [{"entity": "Lord Cobham", "relationship": "BUILT_BY_AS_POLITICAL_STATEMENT_OF", "note": "Cobham built the Temple of Friendship to celebrate his political allies (the Boy Patriots) opposing Walpole"}, {"entity": "Stowe Landscape Garden", "relationship": "PART_OF_MOST_FAMOUS_COMPONENT_OF", "note": "The Temple of Friendship is one of 40+ classical buildings in England's most historically significant landscape garden"}, {"entity": "William Pitt the Elder", "relationship": "HONORED_AS_BOY_PATRIOT_IN", "note": "Pitt the Elder was among the Boy Patriots celebrated in the Temple of Friendship as anti-Walpole political allies"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Temple of Friendship at Stowe — one of 40+ classical buildings in England's prototype landscape garden, explicitly commemorating anti-Walpole political allies, and part of the garden that influenced Jefferson and transformed global garden design — is historically significant as both political monument and landscape garden artifact.", "significanceCategory": "continental"},
    }, FOLDER_343, "343"),
    ("huguo-chan-buddhist-temple-of-the-linji-school", {
        "summary": "The Huguo Chan Buddhist Temple of the Linji School (护国禅寺, Huguo Chansi), associated with the Linji (Rinzai in Japanese) school of Chan Buddhism — the most influential school of Chinese Buddhist practice that transmitted to Japan as Rinzai Zen and to Korea as Imje Seon — represents a significant institution within one of Buddhism's most historically consequential contemplative lineages, whose emphasis on sudden enlightenment through koan (gong'an) practice, shouting, and unconventional methods profoundly shaped East Asian Buddhist culture, philosophy, and art.\n\nThe Linji school was founded by the 9th-century Tang Dynasty monk Linji Yixuan (d. 866 CE), whose teaching methods — including the famous shout (喝 hè, 'Katsu!' in Japanese) and physical blows as means to jolt students toward enlightenment — were recorded in the Linji lu (Record of Linji), one of the most important texts in Chan Buddhism. The Linji/Rinzai tradition's emphasis on koan practice (systematized in the 11th-12th centuries through collections like the Blue Cliff Record and the Gateless Gate) created one of Buddhist history's most distinctive pedagogical systems.\n\nThe Linji tradition's transmission to Japan through Eisai (1141-1215) and subsequently to the Korean peninsula created the dominant forms of Chan/Zen practice that shaped East Asian intellectual and cultural life from the Song Dynasty through the modern period. The patronage of Linji temples by imperial courts (particularly the Song, Yuan, and Ming dynasties in China, and the Kamakura shogunate in Japan) connected the school's institutions to the highest levels of political power. Huguo (protecting the nation) temple names reflect this imperial patronage tradition.",
        "causes": ["Linji Yixuan's 9th-century Tang Dynasty founding of the school through radical teaching methods emphasizing sudden enlightenment", "Koan practice systematization in Song Dynasty (11th-12th centuries) through Blue Cliff Record and Gateless Gate", "Imperial court patronage of Linji temples under Song, Yuan, and Ming dynasties connecting school to political power", "Transmission to Japan through Eisai creating Rinzai Zen and to Korea as Imje Seon"],
        "effects": ["Rinzai Zen transmission to Japan through Kamakura period becoming dominant Japanese imperial court Buddhism", "Koan practice influence on East Asian philosophy, literature, and art through chan/zen aesthetic ideals", "Linji lineage becoming primary carrier of chan Buddhism through Song-Yuan-Ming imperial patronage", "Huguo (nation-protecting) temple designation pattern reflecting imperial Buddhism's political legitimation functions"],
        "relationships": [{"entity": "Linji Yixuan", "relationship": "LINEAGE_FOUNDER_OF_THE_LINJI_SCHOOL", "note": "9th-century monk Linji Yixuan's radical teaching methods (shouts, blows) founded the most influential Chan Buddhism school"}, {"entity": "Rinzai Zen", "relationship": "JAPANESE_TRANSMISSION_OF_LINJI_SCHOOL", "note": "The Linji school was transmitted to Japan by Eisai as Rinzai Zen, becoming the dominant Japanese imperial court Buddhism"}, {"entity": "Koan Practice", "relationship": "PEDAGOGICAL_METHOD_SYSTEMATIZED_AND_TRANSMITTED_BY", "note": "The Linji/Rinzai school systematized koan practice through the Blue Cliff Record and Gateless Gate collections"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Huguo Chan Buddhist Temple of the Linji School — institutional node of the most historically consequential Chan Buddhism lineage, whose koan practice, sudden enlightenment methods, and Japanese Rinzai Zen transmission profoundly shaped East Asian culture and philosophy — is historically significant as part of one of Buddhism's most influential contemplative traditions.", "significanceCategory": "world-changing"},
    }, FOLDER_343, "343"),
]

def enrich_entity(slug, data, folder, prefix):
    fname = os.path.join(folder, f"{prefix}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 122 — Mixed: Class 344 Abbeys IV (4) + Class 343 Temples V (4)")
    for slug, data, folder, prefix in ENTITIES:
        enrich_entity(slug, data, folder, prefix)
    print("Done.")
