#!/usr/bin/env python3
"""Batch 148 — Class 342 Mosques VIII: Southeast Asian & Central Asian Mosques (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/342-Class-342"
FILE_PREFIX = "342"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("masjid-al-furqan", {
        "summary": "Masjid Al-Furqan (المسجد الفرقان) is a mosque in Singapore — one of the city-state's network of Muslim religious institutions serving Singapore's Malay Muslim community (approximately 15% of Singapore's multiethnic population) and reflecting Singapore's carefully managed multiculturalism that has balanced ethnic Chinese, Malay Muslim, and Tamil Hindu communities since independence in 1965 under Lee Kuan Yew's People's Action Party governance.\n\nSingapore's Muslim religious institutions, including Masjid Al-Furqan, operate under the Majlis Ugama Islam Singapura (MUIS, the Islamic Religious Council of Singapore), a statutory body that administers Islamic affairs including mosque construction, the halal certification system, and religious education. Singapore's model of managed multiculturalism has maintained inter-communal harmony through deliberate institutional mechanisms — including proportional representation of ethnic groups in parliament and public housing, the Presidential Council for Minority Rights, and MUIS's oversight of Muslim religious institutions.\n\nThe name 'Al-Furqan' (Arabic: الفرقان, 'the criterion' or 'the distinction') refers to the Quran and to the ability to distinguish truth from falsehood — a name reflecting the mosque's role in Islamic education and the Malay Muslim community's religious life in Singapore's multicultural context.",
        "causes": ["Singapore's Malay Muslim community (15% of population) requiring mosque infrastructure", "MUIS (Islamic Religious Council of Singapore) statutory framework managing mosque development", "Singapore's multicultural governance model requiring proportional religious infrastructure development", "Malay Muslim community's religious and social needs in Southeast Asia's most developed city-state"],
        "effects": ["Masjid Al-Furqan serving Malay Muslim community's worship and educational needs in Singapore", "MUIS-regulated mosque operating within Singapore's carefully managed multiculturalism framework", "Islamic religious education and community services provided within Singapore's multiethnic context", "Mosque contributing to the inter-communal harmony central to Singapore's national identity"],
        "relationships": [{"entity": "MUIS Singapore", "relationship": "OPERATES_UNDER_STATUTORY_OVERSIGHT_OF_ISLAMIC_RELIGIOUS_COUNCIL", "note": "Masjid Al-Furqan operates under MUIS, Singapore's statutory Islamic religious council"}, {"entity": "Singapore Multiculturalism", "relationship": "RELIGIOUS_INSTITUTION_WITHIN_MANAGED_MULTICULTURAL_FRAMEWORK_OF", "note": "The mosque is part of Singapore's carefully managed multicultural framework balancing ethnic and religious communities"}, {"entity": "Malay Muslim Community Singapore", "relationship": "PRIMARY_COMMUNITY_SERVED_BY_MOSQUE", "note": "The mosque serves Singapore's Malay Muslim community, approximately 15% of the city-state's population"}],
        "historicalSignificance": {"significanceScore": 4, "significanceNarrative": "Masjid Al-Furqan is historically significant as a community religious institution within Singapore's globally studied model of multicultural governance.", "significanceCategory": "local"},
    }),
    ("masjid-al-ghufran", {
        "summary": "Masjid Al-Ghufran (مسجد الغفران, 'Mosque of Forgiveness') is a mosque in Singapore — serving the Malay Muslim community in one of Singapore's residential estates, functioning within the MUIS (Majlis Ugama Islam Singapura) framework that governs Singapore's approximately 1,000 mosques and Muslim religious institutions across the island city-state.\n\nSingapore's mosque development reflects the city-state's unique approach to religious infrastructure planning: MUIS coordinates mosque development with Singapore's Housing Development Board (HDB) — which controls approximately 80% of Singaporeans' housing — to ensure that each HDB estate has access to a mosque for the Malay Muslim community's worship needs. This planning integration reflects Singapore's founding principle of creating multiculturalism 'by design' — with housing policy, religious infrastructure, and educational institutions all coordinated to prevent the formation of mono-ethnic enclaves.\n\nThe name 'Al-Ghufran' (Arabic: الغفران, 'the forgiveness') reflects the Islamic theological concept of divine forgiveness (maghfirah), a name commonly given to mosques to emphasize God's mercy and the Muslim community's spiritual orientation toward seeking divine pardon. The mosque's community programming — religious classes, Quran memorization programs, social services — reflects MUIS's emphasis on mosques as community development centers.",
        "causes": ["Singapore's HDB estate planning requiring mosque infrastructure for Malay Muslim community access", "MUIS statutory coordination of mosque development with residential planning", "Malay Muslim community's worship and religious education needs in specific Singapore residential area", "Singapore's multicultural policy ensuring proportional religious infrastructure across ethnic communities"],
        "effects": ["Masjid Al-Ghufran providing worship and community services for Malay Muslim residents of the area", "MUIS-regulated community programming providing religious education within Singapore's multicultural framework", "Mosque contributing to Singapore's deliberately engineered inter-communal harmony model", "Islamic community services integrated with broader Singapore social welfare infrastructure"],
        "relationships": [{"entity": "MUIS Singapore", "relationship": "GOVERNED_BY_STATUTORY_ISLAMIC_RELIGIOUS_COUNCIL_OF", "note": "Masjid Al-Ghufran operates within the MUIS framework governing Singapore's Muslim religious institutions"}, {"entity": "HDB Singapore", "relationship": "MOSQUE_INFRASTRUCTURE_PLANNED_IN_COORDINATION_WITH_HOUSING_DEVELOPMENT_BOARD", "note": "Singapore's mosque development is coordinated with HDB's estate planning"}, {"entity": "Singapore Multicultural Policy", "relationship": "RELIGIOUS_INSTITUTION_WITHIN_MANAGED_DIVERSITY_FRAMEWORK_OF", "note": "The mosque is part of Singapore's deliberately designed multicultural infrastructure"}],
        "historicalSignificance": {"significanceScore": 4, "significanceNarrative": "Masjid Al-Ghufran is historically significant as a community religious institution within Singapore's globally studied model of planned multicultural governance and coordinated religious infrastructure development.", "significanceCategory": "local"},
    }),
    ("masjid-al-huda", {
        "summary": "Masjid Al-Huda (مسجد الهدى, 'Mosque of Right Guidance') is a mosque in Singapore — one of the many mosques serving Singapore's Malay Muslim community that together form the infrastructure of Islamic religious life in one of Southeast Asia's most prosperous and religiously diverse city-states. The mosque's name, Al-Huda ('the guidance'), refers to the Quranic concept of divine guidance (huda), the direction toward truth and righteousness that Islam provides to believers.\n\nSingapore's Muslim community has developed a distinctive form of modern, progressive Islam that has been studied globally as a model of Islam's accommodation to secular modernity: MUIS (the Islamic Religious Council) has developed fatwa (religious rulings) addressing distinctly modern questions — organ donation, reproductive technology, financial services, and the compatibility of Islamic practice with Singapore's secular legal system. The Muis Fatwa Committee has been particularly active in developing halal certification standards that now influence global food industry practice.\n\nThe mosque functions as a community hub beyond worship: Islamic education programs (madrasah), Quran classes, social welfare services, and zakat (charitable giving) distribution are all organized through Singapore's mosque network under MUIS coordination. The integration of traditional Islamic community functions with modern social service delivery reflects Singapore's distinctive approach to managing religious institutions as part of the broader social safety net.",
        "causes": ["Singapore's Malay Muslim community's worship and religious education needs requiring mosque infrastructure", "MUIS statutory framework coordinating mosque development and programming", "Islamic community hub functions including education, social services, and zakat distribution requiring physical space", "Singapore's multicultural governance model ensuring Muslim community religious needs are met"],
        "effects": ["Masjid Al-Huda providing worship, education, and social services to the Malay Muslim community", "MUIS-developed modern Islamic jurisprudence addressing contemporary questions studied globally", "Halal certification systems developed through Singapore's mosque network influencing global food industry", "Community social services integrated with broader Singapore social infrastructure through mosque network"],
        "relationships": [{"entity": "MUIS Singapore", "relationship": "OPERATES_UNDER_STATUTORY_OVERSIGHT_DEVELOPING_MODERN_ISLAMIC_JURISPRUDENCE", "note": "Masjid Al-Huda operates under MUIS, which has developed progressive modern Islamic jurisprudence studied globally"}, {"entity": "Halal Certification System", "relationship": "MOSQUE_NETWORK_CONTRIBUTING_TO_STANDARDS_INFLUENCING_GLOBAL_FOOD_INDUSTRY", "note": "Singapore's mosque network under MUIS coordinates halal certification now influencing global food industry practice"}, {"entity": "Singapore Malay Muslim Community", "relationship": "PRIMARY_COMMUNITY_SERVED_WITH_WORSHIP_EDUCATION_AND_SOCIAL_SERVICES", "note": "The mosque serves Singapore's Malay Muslim community's religious, educational, and social welfare needs"}],
        "historicalSignificance": {"significanceScore": 4, "significanceNarrative": "Masjid Al-Huda is historically significant as a community religious institution within Singapore's globally studied model of modern Islamic governance and MUIS's development of contemporary Islamic jurisprudence.", "significanceCategory": "local"},
    }),
    ("masjid-al-istiqamah", {
        "summary": "Masjid Al-Istiqamah (مسجد الاستقامة, 'Mosque of Steadfastness/Uprightness') is a mosque in Singapore — serving the island's Malay Muslim community within MUIS's (Majlis Ugama Islam Singapura) regulatory framework. The name 'Al-Istiqamah' (Arabic: الاستقامة) refers to the Islamic concept of steadfastness, uprightness, and remaining firmly on the straight path (sirat al-mustaqim), a core Quranic value invoked in the Fatiha prayer recited seventeen times daily in five prayers.\n\nSingapore's mosque naming conventions frequently employ Arabic names reflecting core Islamic theological and ethical concepts — creating a landscape of religious institutions whose names collectively represent a theology of virtue: Al-Furqan (criterion), Al-Ghufran (forgiveness), Al-Huda (guidance), Al-Istiqamah (steadfastness) — together constituting a distributed theological curriculum in the urban landscape. This practice of meaningful naming is characteristic of Islamic religious architecture globally, where mosque names carry theological significance rather than merely locational or biographical reference.\n\nThe mosque serves its residential community through Friday prayers (khutbah, the sermon that provides weekly guidance to the congregation), daily prayers, Ramadan tarawih prayers, Eid celebrations, Islamic education classes, and social welfare services. Singapore's mosque network collectively manages the comprehensive religious life of approximately 600,000 Malay Muslims in one of the world's most efficiently governed city-states.",
        "causes": ["Singapore's residential planning requiring mosque infrastructure within MUIS's coordinated framework", "Malay Muslim community's daily worship and weekly Friday prayer needs requiring local mosque", "MUIS's comprehensive management of Singapore's Muslim religious life requiring distributed mosque network", "Islamic theological naming tradition providing community with physically encoded theological landscape"],
        "effects": ["Mosque providing daily, weekly, and annual religious cycle worship opportunities for local community", "MUIS-coordinated Islamic education and social services integrated with Singapore's social welfare system", "Singapore's distributed mosque network collectively serving approximately 600,000 Malay Muslims", "Islamic architectural landscape encoding theological concepts in the names of community religious institutions"],
        "relationships": [{"entity": "MUIS Singapore", "relationship": "OPERATES_WITHIN_STATUTORY_FRAMEWORK_MANAGING_SINGAPORE'S_MUSLIM_RELIGIOUS_LIFE", "note": "Masjid Al-Istiqamah is part of MUIS's comprehensive management of Singapore's 600,000-strong Malay Muslim community's religious life"}, {"entity": "Friday Prayer Khutbah", "relationship": "PROVIDES_WEEKLY_GUIDANCE_SERMON_FOR_CONGREGATION_IN_MOSQUE", "note": "The mosque provides weekly Friday khutbah (sermon) as central to Muslim community's religious education"}, {"entity": "Singapore Malay Muslim Community", "relationship": "LOCAL_COMMUNITY_WORSHIP_EDUCATION_AND_SOCIAL_SERVICES_PROVIDED_TO", "note": "The mosque serves the local Malay Muslim community's religious and social welfare needs"}],
        "historicalSignificance": {"significanceScore": 4, "significanceNarrative": "Masjid Al-Istiqamah is historically significant as a community religious institution within Singapore's internationally studied model of managed multicultural governance and coordinated Islamic community services.", "significanceCategory": "local"},
    }),
    ("masjid-al-khair", {
        "summary": "Masjid Al-Khair (مسجد الخير, 'Mosque of Goodness/Beneficence') is a mosque in Singapore — part of the island's extensive network of Muslim religious institutions serving the Malay Muslim community under the oversight of MUIS (Majlis Ugama Islam Singapura). The name 'Al-Khair' (Arabic: الخير, 'goodness,' 'beneficence,' 'virtue') reflects the Islamic concept of charitable goodness and moral virtue that Muslim religious institutions strive to embody and promote in their communities.\n\nSingapore's approach to managing Islamic religious institutions represents a globally significant model of how secular governance and religious life can be integrated without conflict: MUIS manages mosque finances through the Central Mosque Fund, standardizes Friday sermons (through the prepared khutbah texts distributed weekly to all imams), coordinates Islamic education through madrasahs and Quran classes, and regulates the hajj pilgrim management. This comprehensive management has been criticized by some as excessive government control over religious life, while others cite it as a model of how to prevent religious radicalization.\n\nThe mosque's community services extend beyond worship: zakat collection and distribution (the Islamic charitable obligation, one of the five pillars of Islam), social welfare assistance for needy Muslim families, interfaith activities within Singapore's multicultural framework, and youth programs aimed at integrating Muslim youth into Singapore's broader educational and economic life.",
        "causes": ["Singapore's Malay Muslim community requiring local mosque for worship and community services", "MUIS statutory framework managing mosque development and standardizing Islamic religious programming", "Central Mosque Fund coordinating mosque finances across Singapore's Muslim religious institutions", "Singapore's multicultural governance requiring balanced religious infrastructure development"],
        "effects": ["Masjid Al-Khair providing worship, zakat distribution, and social services to local Muslim community", "MUIS-standardized Friday khutbah providing consistent Islamic guidance to Singapore's mosque congregations", "Zakat collection and distribution supporting needy Muslim families through mosque social welfare network", "Interfaith activities contributing to Singapore's inter-communal harmony from mosque community base"],
        "relationships": [{"entity": "MUIS Singapore", "relationship": "MOSQUE_FINANCES_AND_PROGRAMMING_MANAGED_BY", "note": "Masjid Al-Khair's finances and religious programming are managed through MUIS's Central Mosque Fund and coordination"}, {"entity": "Zakat Islamic Obligation", "relationship": "COLLECTS_AND_DISTRIBUTES_CHARITABLE_GIVING_AS_FIFTH_PILLAR_OF_ISLAM", "note": "The mosque manages zakat collection and distribution as part of the Islamic charitable giving obligation"}, {"entity": "Singapore Interfaith Relations", "relationship": "CONTRIBUTES_TO_INTER-COMMUNAL_HARMONY_THROUGH_INTERFAITH_PROGRAMMING", "note": "The mosque participates in interfaith activities within Singapore's multicultural governance framework"}],
        "historicalSignificance": {"significanceScore": 4, "significanceNarrative": "Masjid Al-Khair is historically significant as a community religious institution within Singapore's internationally studied model of state-managed Islamic governance and multicultural harmony.", "significanceCategory": "local"},
    }),
    ("masjid-al-mawaddah", {
        "summary": "Masjid Al-Mawaddah (مسجد المودة, 'Mosque of Affection/Love') is a mosque in Singapore — serving the Malay Muslim community as part of Singapore's comprehensive mosque network. The name 'Al-Mawaddah' (Arabic: المودة) refers to the Islamic concept of loving affection and compassion between people, particularly the love and compassion between spouses mentioned in the Quran (30:21): 'And He placed between you affection and mercy' — a name suggesting the mosque's role in nurturing community bonds and family life.\n\nSingapore's Muslim community faces distinctive challenges and opportunities compared to Muslim communities elsewhere in the world: as a minority (15% Malay Muslim in an ethnic Chinese majority society) within a secular legal system that does not implement sharia family law, Singapore's Muslims must navigate between Islamic religious requirements and Singapore's civil legal framework. MUIS has developed sophisticated jurisprudential positions on these questions — including how Muslims should relate to Singapore's secular legal system, how Islamic family law principles can be maintained within a civil law jurisdiction, and how Muslim identity can be maintained in a hypercultural globalized city-state.\n\nThe mosque's role in maintaining Muslim family life — providing premarital counseling, managing nikah (marriage contracts), facilitating divorce mediation, and providing family counseling — makes it a central institution in the Malay Muslim family's life cycle, from birth naming ceremonies (aqiqah) through marriage to funeral arrangements.",
        "causes": ["Singapore's Malay Muslim community requiring local religious institution for family life-cycle ceremonies", "MUIS framework managing Muslim family law within Singapore's civil legal system", "Islamic community need for premarital counseling, marriage, divorce, and family services", "Singapore's multicultural context requiring Muslim institutions supporting minority community identity"],
        "effects": ["Mosque providing comprehensive family life-cycle services from birth ceremonies through marriage to funerals", "MUIS jurisprudential navigation of Islamic family law within Singapore's secular civil law system", "Malay Muslim family identity supported through mosque community services and religious education", "Community affection and social cohesion built through mosque-centered social programming"],
        "relationships": [{"entity": "MUIS Singapore", "relationship": "MOSQUE_OPERATING_WITHIN_STATUTORY_FRAMEWORK_NAVIGATING_ISLAMIC_AND_CIVIL_LAW", "note": "Masjid Al-Mawaddah operates within MUIS's framework managing Islamic family law within Singapore's secular legal system"}, {"entity": "Muslim Family Law Singapore", "relationship": "MOSQUE_IMPLEMENTING_NIKAH_MARRIAGE_AND_FAMILY_SERVICES_UNDER", "note": "The mosque provides nikah and family services within Singapore's Muslim family law framework"}, {"entity": "Singapore Malay Muslim Community", "relationship": "FAMILY_LIFE_CYCLE_CEREMONIES_AND_COMMUNITY_COHESION_SERVED_BY", "note": "The mosque serves the Malay Muslim community's family life-cycle needs and builds community affection"}],
        "historicalSignificance": {"significanceScore": 4, "significanceNarrative": "Masjid Al-Mawaddah is historically significant as a community religious institution managing Muslim family life within Singapore's model of navigating Islamic religious requirements within a secular civil law system.", "significanceCategory": "local"},
    }),
    ("masjid-al-mukminin", {
        "summary": "Masjid Al-Mukminin (مسجد المؤمنين, 'Mosque of the Believers') is a mosque in Singapore — one of the city-state's approximately 70 mosques serving the Malay Muslim community under the MUIS framework. The name 'Al-Mukminin' (Arabic: المؤمنين, 'the believers') refers to the Islamic theological concept of the believing community (ummah) — those who have accepted faith (iman) in Allah, the prophethood of Muhammad, and the other pillars of Islamic belief.\n\nThe Quran's 23rd chapter is titled 'Al-Mu'minun' (The Believers), beginning with the famous verse describing the characteristics of successful believers: those who are humble in their prayers, who turn away from vain talk, who give zakat, who guard their chastity, and who honor their trusts and covenants. A mosque named Al-Mukminin thus invokes this Quranic ideal of the righteous believing community as the standard to which its congregation aspires.\n\nSingapore's mosque network of approximately 70 mosques serves approximately 600,000 Malay Muslims, giving an average congregation of approximately 8,500 per mosque — though Friday prayer attendance varies significantly by location. The mosques are funded through the waqf (Islamic endowment) system managed by MUIS, which administers approximately S$500 million in waqf assets across Singapore, using the returns to fund mosque operations, madrasah education, and Muslim social welfare.",
        "causes": ["Singapore's Malay Muslim community requiring local mosque for worship and community religious life", "MUIS waqf endowment system funding mosque operations from approximately S$500 million in managed assets", "Islamic theological ideal of the believing community providing the aspirational framework for mosque community", "Singapore's multicultural governance ensuring Muslim religious infrastructure proportional to community needs"],
        "effects": ["Mosque providing worship space and community services for local Malay Muslim believers", "MUIS waqf management of S$500 million in endowment assets funding mosque network across Singapore", "Islamic education and social services funded through waqf returns under MUIS administration", "Quranic ideal of righteous believers encoded in mosque naming providing community with aspirational framework"],
        "relationships": [{"entity": "MUIS Waqf Management", "relationship": "MOSQUE_FUNDED_THROUGH_S$500_MILLION_WAQF_ASSETS_MANAGED_BY", "note": "Masjid Al-Mukminin is funded through MUIS's management of approximately S$500 million in waqf endowment assets"}, {"entity": "Quran Al-Muminun", "relationship": "NAMED_AFTER_CHAPTER_23_DESCRIBING_IDEAL_BELIEVERS", "note": "The mosque's name references the Quran's 23rd chapter describing the characteristics of successful believers"}, {"entity": "Singapore Muslim Social Welfare", "relationship": "WAQF_RETURNS_FUNDING_MOSQUE_EDUCATION_AND_SOCIAL_SERVICES_FOR", "note": "MUIS waqf returns fund mosque operations, madrasah education, and Muslim social welfare services"}],
        "historicalSignificance": {"significanceScore": 4, "significanceNarrative": "Masjid Al-Mukminin is historically significant as a community religious institution within Singapore's MUIS waqf endowment management system — a model of Islamic financial institution management studied globally.", "significanceCategory": "local"},
    }),
    ("masjid-al-muttaqin", {
        "summary": "Masjid Al-Muttaqin (مسجد المتقين, 'Mosque of the God-Fearing/Pious') is a mosque in Singapore — serving the Malay Muslim community within MUIS's comprehensive framework. The name 'Al-Muttaqin' (Arabic: المتقين, 'the pious,' 'the god-fearing') refers to the Islamic concept of taqwa — God-consciousness, piety, and fear of God — considered one of the highest virtues in Islam and the Quran's most frequently cited criterion for spiritual excellence (the Quran states that 'the most honored of you in the sight of God is the most righteous among you,' 49:13).\n\nSingapore's mosque naming conventions collectively create a theological landscape encoding Islamic virtues: Al-Furqan (discernment), Al-Ghufran (divine forgiveness), Al-Huda (divine guidance), Al-Istiqamah (steadfastness), Al-Khair (goodness), Al-Mawaddah (affection), Al-Mukminin (believers), Al-Muttaqin (the pious) — together representing a comprehensive Islamic moral vocabulary embedded in the city's religious architecture. This practice reflects Islamic civilization's tradition of naming religious institutions to encode theological aspirations.\n\nThe mosque serves the full range of Islamic community needs: the five daily prayers, Friday khutbah (sermon), Ramadan tarawih prayers and iftar gatherings, Eid prayer celebrations, Islamic education (fardhu ain — the basic religious obligations), and social services including zakat distribution and family counseling. Singapore's MUIS coordinates all these services across the mosque network, ensuring quality and consistency in religious programming.",
        "causes": ["Singapore's Malay Muslim community requiring local mosque serving theological concept of taqwa (God-consciousness)", "MUIS framework coordinating comprehensive religious programming including prayers, education, and social services", "Islamic naming tradition encoding theological virtues in mosque names creating embodied moral landscape", "Singapore's multicultural governance ensuring proportional religious infrastructure for Muslim community"],
        "effects": ["Mosque embodying taqwa aspiration as community standard for religious and moral life", "MUIS-coordinated comprehensive religious programming providing complete Islamic community services", "Singapore's mosque naming landscape encoding Islamic theological virtues in the urban religious environment", "Malay Muslim community served through complete religious life-cycle from daily prayers to Eid celebrations"],
        "relationships": [{"entity": "MUIS Singapore", "relationship": "COMPREHENSIVE_RELIGIOUS_PROGRAMMING_COORDINATED_THROUGH_STATUTORY_COUNCIL", "note": "Masjid Al-Muttaqin's religious programming is coordinated through MUIS's comprehensive management of Singapore's mosque network"}, {"entity": "Islamic Concept of Taqwa", "relationship": "EMBODIED_IN_MOSQUE_NAME_AS_ASPIRATION_FOR_COMMUNITY", "note": "The mosque's name embodies the Islamic concept of taqwa (God-consciousness and piety) as the community's aspiration"}, {"entity": "Singapore Islamic Naming Landscape", "relationship": "CONTRIBUTES_TO_THEOLOGICAL_VIRTUE_ENCODED_IN_URBAN_RELIGIOUS_ARCHITECTURE", "note": "The mosque's name is part of Singapore's mosque naming tradition encoding Islamic theological virtues in the city's religious landscape"}],
        "historicalSignificance": {"significanceScore": 4, "significanceNarrative": "Masjid Al-Muttaqin is historically significant as a community religious institution within Singapore's comprehensive model of state-managed Islamic religious governance and the creation of a theologically encoded urban Muslim landscape.", "significanceCategory": "local"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 148 — Class 342 Mosques VIII: Singapore Mosque Network")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
