#!/usr/bin/env python3
"""Batch 84 — Class 381 Universities III (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/381-Class-381"
FILE_PREFIX = "381"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("massachusetts-institute-of-technology", {
        "summary": "The Massachusetts Institute of Technology (MIT), founded in 1861 in response to the American Industrial Revolution by William Barton Rogers, is the world's leading research university for science, engineering, and technology — producing more Nobel laureates, Turing Award winners, and billion-dollar technology companies than any comparable institution. MIT's 97 Nobel laureates, 26 Turing Award winners, and alumni who founded companies worth $1.9 trillion (equivalent to the world's 10th-largest economy) have made it the single most economically productive university in history.\n\nRogers founded MIT on the principle of 'mens et manus' ('mind and hand') — explicitly rejecting European pure-science academic traditions to combine research with practical application. The move to Cambridge across the Charles River from downtown Boston in 1916 enabled campus expansion; the invention of modern architecture under Alvar Aalto and I.M. Pei's iconic Stata Center created a campus where buildings are intellectual statements. MIT's Lincoln Laboratory (radar), Instrumentation Laboratory (Apollo guidance computer), and Media Lab (wearable computing, e-ink) created the research spin-off model that made Silicon Valley possible.\n\nThe MIT-Stanford technology corridor is the template for the entire global technology startup ecosystem. MIT alumni founded Hewlett-Packard, Texas Instruments, Qualcomm, Intel, McDonnell Douglas, and Dropbox. The MIT OpenCourseWare initiative (2002) — placing the entire undergraduate and graduate curriculum online free — revolutionized global educational access. MIT's AI lab, founded by Marvin Minsky and John McCarthy in 1956, created artificial intelligence as a formal academic discipline.",
        "causes": ["1861 founding by Rogers to apply scientific education to Industrial Revolution practical problems", "Mens et manus principle combining research and practical application", "Lincoln Laboratory and Instrumentation Lab creating government-funded research spin-off model", "MIT AI Lab founding 1956 by Minsky and McCarthy creating artificial intelligence as formal discipline"],
        "effects": ["97 Nobel laureates and 26 Turing Award winners making MIT most decorated science university", "Alumni companies worth $1.9 trillion equivalent to world's 10th-largest economy", "OpenCourseWare 2002 placing entire curriculum online free revolutionizing global education access", "AI Lab founding created artificial intelligence as academic discipline shaping 21st-century technology"],
        "relationships": [{"entity": "William Barton Rogers", "relationship": "FOUNDED_BY", "note": "Rogers founded MIT in 1861 on principle of combining scientific research with practical application"}, {"entity": "Marvin Minsky", "relationship": "AI_LAB_FOUNDED_BY", "note": "Minsky co-founded MIT AI Lab in 1956 creating artificial intelligence as formal academic discipline"}, {"entity": "Apollo Program", "relationship": "GUIDANCE_COMPUTER_FROM", "note": "MIT Instrumentation Lab designed Apollo guidance computer enabling Moon landing"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "MIT's alumni companies worth $1.9 trillion — combined with the AI discipline it founded and the OpenCourseWare revolution in global education access — make it the single most economically and intellectually productive university in history.", "significanceCategory": "world-changing"},
    }),
    ("eth-zurich", {
        "summary": "ETH Zurich (Eidgenössische Technische Hochschule Zürich — Swiss Federal Institute of Technology), founded in 1855 by the Swiss Confederation, is Europe's leading science and technology university — producing 21 Nobel laureates and alumni including Albert Einstein, Wilhelm Röntgen, and Nils Bohr. Einstein completed his physics degree at ETH in 1900 and returned as a professor in 1912; the Annalen der Physik submission containing his 1905 special relativity paper was drafted while he was a clerk at the Bern patent office trying to escape ETH's rejection of his graduate application.\n\nThe Swiss Confederation established ETH as a national engineering and science institution to accelerate Swiss industrialization — building on Switzerland's watchmaking, textile, and chemical manufacturing base. ETH's Location in Zurich gave it access to Switzerland's banking, pharmaceutical, and precision engineering industries. The main building on Rämistrasse, designed by Gottfried Semper (also designer of Vienna's natural history museum), looks down over the old town from its hill.\n\nETH Zurich's research legacy spans relativity (Einstein), X-rays (Röntgen studied here), the World Wide Web prototype (Tim Berners-Lee worked at CERN nearby), chemistry (Linus Pauling's collaborator Robert Huber), and materials science. The ETH domain includes EMPA (materials), PSI (particle physics), Eawag (water research), and WSL (forest and landscape ecology) — creating an integrated Swiss science ecosystem. Switzerland's per-capita Nobel Prize rate (highest in the world for natural sciences) depends substantially on ETH research productivity.",
        "causes": ["1855 founding by Swiss Confederation as national science-engineering institution for industrialization", "Einstein's 1900 degree and 1912 return professorship associating ETH with relativity's development", "Swiss precision engineering and pharmaceutical industries providing research partnerships", "Gottfried Semper's classical building creating academic identity on Rämistrasse hill above Zurich"],
        "effects": ["21 Nobel laureates including Einstein, making ETH Europe's most decorated technology university", "Switzerland's highest per-capita natural science Nobel rate driven by ETH research productivity", "ETH domain of research institutes (EMPA, PSI, Eawag, WSL) creating integrated science ecosystem", "Einstein's rejection then return to ETH created the 1905 'miracle year' that produced special relativity"],
        "relationships": [{"entity": "Albert Einstein", "relationship": "EDUCATED_AND_EMPLOYED", "note": "Einstein completed degree 1900 and returned as professor 1912; ETH shaped his scientific formation"}, {"entity": "Gottfried Semper", "relationship": "MAIN_BUILDING_DESIGNED_BY", "note": "Semper designed ETH's classical main building above Zurich — also designed Vienna's NHM"}, {"entity": "Swiss Confederation", "relationship": "FOUNDED_BY", "note": "Federal government founded ETH in 1855 as national science institution for Swiss industrialization"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "ETH Zurich's most consequential contribution — Einstein's formation and return — connected the institution to the development of special relativity, the most transformative scientific theory of the 20th century.", "significanceCategory": "world-changing"},
    }),
    ("university-of-chicago", {
        "summary": "The University of Chicago, founded in 1890 with a gift from oil magnate John D. Rockefeller, is the only research university in history to have created two entirely new academic disciplines — economics (the Chicago School) and sociology (the Chicago School of Sociology) — while simultaneously transforming law through the Law and Economics movement and philosophy through Pragmatism and logical positivism. The University's 100 Nobel laureates (the most per enrolled student of any university) and the Chicago School economic theories that governed global free-market policy from 1970-2008 make it the most intellectually influential university of the 20th century.\n\nRockefeller's 1890 gift established the university on Frederick Law Olmsted's Gothic campus in Hyde Park. The first president, William Rainey Harper, created the quarter system and emphasized research over teaching — establishing the research university model. The 1942 Chicago Pile-1 nuclear reactor under Stagg Field — constructed by Enrico Fermi's team including 49 scientists — created the first artificial self-sustaining nuclear chain reaction on December 2, 1942, enabling the Manhattan Project.\n\nMilton Friedman's Chicago School economics — monetarism, free-market anti-Keynesian theory, privatization — became the intellectual foundation for Reagan-Thatcher economic policy, the 'Washington Consensus' imposed on developing countries by the IMF, and the Chilean 'Chicago Boys' economic reforms under Pinochet. The Chicago School's global influence from 1970-2008 transformed economic governance in 50+ countries. Gary Becker's application of economic analysis to marriage, crime, and discrimination created 'economics imperialism' — the extension of economic methodology into all social sciences.",
        "causes": ["1890 founding with Rockefeller gift on Frederick Law Olmsted Gothic campus in Hyde Park", "Chicago Pile-1 1942 first nuclear chain reaction under Enrico Fermi enabling Manhattan Project", "Milton Friedman's Chicago School monetarism becoming foundation of Reagan-Thatcher economic policy", "Chicago School of Sociology creating urban sociological research methods adopted globally"],
        "effects": ["100 Nobel laureates — most per enrolled student of any university globally", "Fermi's nuclear chain reaction enabled Manhattan Project and nuclear age", "Chicago School economics governed global free-market policy in 50+ countries 1970-2008", "Law and Economics movement transformed legal scholarship and antitrust law globally"],
        "relationships": [{"entity": "John D. Rockefeller", "relationship": "ENDOWED_BY", "note": "Rockefeller's 1890 gift established university; he remained lifelong donor to Baptist educational mission"}, {"entity": "Enrico Fermi", "relationship": "HOSTED_NUCLEAR_BREAKTHROUGH", "note": "Fermi's Chicago Pile-1 reactor under Stagg Field created first nuclear chain reaction December 2, 1942"}, {"entity": "Milton Friedman", "relationship": "CHICAGO_SCHOOL_LED_BY", "note": "Friedman's monetarism and free-market theory governed global economic policy 1970-2008"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The University of Chicago created the first nuclear chain reaction (enabling atomic weapons and nuclear power), the Chicago School economics (governing global free-market policy for 40 years), and 100 Nobel laureates — making it the most consequential research university in 20th-century science and economics.", "significanceCategory": "world-changing"},
    }),
    ("peking-university", {
        "summary": "Peking University (北京大学, Běijīng Dàxué — commonly Beida), founded in 1898 as the Imperial University of Peking during the Hundred Days Reform of Emperor Guangxu, is China's oldest modern research university and the intellectual birthplace of Chinese communism, the May Fourth Movement, and modern Chinese literature. The university's role in 1919 May Fourth Movement — whose student protests at Peking University catalyzed a national cultural revolution that rejected Confucianism in favor of science and democracy — makes it the most politically consequential campus in Chinese history.\n\nThe university was established by the Guangxu Emperor as part of his 100-day reform program, modeled on Western universities, to modernize China. After the Boxer Rebellion and Qing restoration destroyed the original reforms, Peking University was reorganized in 1912 under the Republic and in 1916 brought progressive president Cai Yuanpei, who invited anarchists, liberals, Marxists, and Confucians to debate freely — the 'hundred schools of thought' moment of modern China.\n\nLi Dazhao (university librarian) and Chen Duxiu (dean of letters) founded the Chinese Communist Party Study Group at Peking University in 1920 — with Li employing a young Hunan library assistant named Mao Zedong. Chen's New Youth magazine published Lu Xun's 'Diary of a Madman' (1918), the first modern Chinese literature work in vernacular language, launching Chinese literary modernism. The 1989 Tiananmen Square protests began at Peking University and ended 200 meters from its gates.",
        "causes": ["1898 founding by Emperor Guangxu as Imperial University during Hundred Days Reform", "1916 Cai Yuanpei's presidency inviting anarchists, Marxists, and liberals to debate freely", "1919 May Fourth Movement student protests catalyzing national cultural revolution", "Li Dazhao and Chen Duxiu founding Communist Party Study Group employing young Mao Zedong"],
        "effects": ["May Fourth Movement 1919 catalyzed Chinese cultural revolution rejecting Confucianism for science/democracy", "Chinese Communist Party intellectual roots at Peking University shaped ideology of PRC", "Lu Xun's vernacular literature published in Chen's New Youth launched Chinese literary modernism", "1989 Tiananmen protests beginning at Peking University connected institution to democracy movement"],
        "relationships": [{"entity": "Li Dazhao", "relationship": "COMMUNIST_FOUNDING_FACULTY", "note": "Li as university librarian co-founded CCP Study Group employing young Mao Zedong"}, {"entity": "Cai Yuanpei", "relationship": "TRANSFORMATIVE_PRESIDENT", "note": "Cai's 1916-1927 presidency created intellectual freedom enabling May Fourth Movement to emerge"}, {"entity": "Mao Zedong", "relationship": "EARLY_EMPLOYMENT_OF", "note": "Young Mao worked as library assistant under Li Dazhao before becoming Communist Party leader"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Peking University was the intellectual birthplace of Chinese communism — Li Dazhao's library assistant Mao Zedong absorbed Marxism here — and the 1919 May Fourth Movement that rejected Confucianism for science and democracy was the cultural revolution that made 20th-century China possible.", "significanceCategory": "world-changing"},
    }),
    ("california-institute-of-technology", {
        "summary": "The California Institute of Technology (Caltech), founded in 1891 in Pasadena by Amos Throop as a vocational school and transformed into a world-class research university by physicist Robert Millikan in 1921, has the highest Nobel Prize per-capita rate of any university in the world — 72 Nobel laureates from an institution with only 2,300 students. Caltech operates NASA's Jet Propulsion Laboratory (JPL) and has managed the majority of America's robotic space exploration program, including the Mars rovers Curiosity and Perseverance.\n\nCaltech's transformation began when Robert Millikan (Nobel 1923 for measuring electron charge) came from Chicago in 1921 and recruited the world's best physicists. Richard Feynman's Caltech lectures (1961-1963) became the greatest physics textbooks ever written (The Feynman Lectures on Physics). Linus Pauling developed quantum chemistry and crystal structure analysis at Caltech, winning two Nobel Prizes (Chemistry 1954, Peace 1962 — the only person to win two unshared Nobels).\n\nJPL, managed by Caltech under NASA contract since 1958, has operated every American robotic solar system mission — Voyager 1 and 2 (now beyond the solar system), Mars Pathfinder, Spirit, Opportunity, Curiosity, Perseverance, and the Ingenuity helicopter (first powered flight on another planet). Caltech's LIGO (Laser Interferometer Gravitational-Wave Observatory), developed with MIT, detected gravitational waves for the first time in 2015 — confirming Einstein's 100-year-old prediction and creating an entirely new astronomical instrument.",
        "causes": ["1891 founding by Amos Throop as vocational school in Pasadena", "Robert Millikan's 1921 transformation of Caltech into world-class physics research university", "JPL creation enabling NASA's robotic solar system exploration program management", "LIGO development with MIT detecting first gravitational waves confirming Einstein's prediction"],
        "effects": ["72 Nobel laureates from 2,300 students giving highest per-capita Nobel rate of any university", "JPL management of Mars rovers Curiosity and Perseverance advancing planetary science", "LIGO's 2015 gravitational wave detection opened new era of multi-messenger astronomy", "Feynman Lectures on Physics became most widely used physics textbooks in history"],
        "relationships": [{"entity": "Robert Millikan", "relationship": "TRANSFORMED_BY", "note": "Millikan's 1921 arrival as first director transformed Caltech from vocational school to world-class university"}, {"entity": "Richard Feynman", "relationship": "ICONIC_PROFESSOR", "note": "Feynman's 1961-1963 lectures became history's most celebrated physics textbooks"}, {"entity": "NASA Jet Propulsion Laboratory", "relationship": "MANAGES", "note": "Caltech manages JPL under NASA contract directing majority of American robotic space exploration"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Caltech's JPL management of NASA's robotic solar system exploration — from Voyager beyond the solar system to Perseverance on Mars — combined with LIGO's gravitational wave detection makes it the university with the greatest contribution to expanding humanity's physical knowledge of the cosmos.", "significanceCategory": "world-changing"},
    }),
    ("carnegie-mellon-university", {
        "summary": "Carnegie Mellon University (CMU), founded in 1900 by industrialist Andrew Carnegie as the Carnegie Technical Schools in Pittsburgh's Oakland neighborhood, is the world's leading computer science university — responsible for creating artificial intelligence as a formal discipline (with Simon and Newell's Logic Theorist, 1956), pioneering human-computer interaction (HCI), and producing a disproportionate share of Silicon Valley's technical leadership. CMU alumni and researchers founded or lead Google, Oracle, Intel, Lyft, and hundreds of other technology companies.\n\nAndrew Carnegie founded the institution to provide practical technical education for Pittsburgh's working-class industrial families. The 1967 merger with the Mellon Institute of Industrial Research (funded by the Mellon banking family) created Carnegie Mellon University. Herbert Simon and Allen Newell's Logic Theorist (1956) — the first artificial intelligence program, demonstrated at Dartmouth Conference — was created at what is now CMU. The CMU Computer Science Department (established 1965) was the first separate computer science department at any university.\n\nCMU's School of Computer Science encompasses multiple sub-fields that it pioneered: machine learning (with the first ML PhD program), robotics (the National Robotics Engineering Center), computational biology, human-computer interaction (the first HCI PhD program), and language technologies. CMU's autonomous vehicle research program — including the 1995 No Hands Across America demonstration (a car driving coast-to-coast with 98% autonomous control) — laid groundwork for self-driving vehicles. The Duolingo language learning app, used by 500 million people, was built on CMU language technology research.",
        "causes": ["1900 founding by Andrew Carnegie for practical technical education of Pittsburgh working-class families", "1956 Logic Theorist by Simon and Newell — first AI program — created at what became CMU", "1965 first separate computer science department at any university", "Autonomous vehicle research from 1995 No Hands demonstration to self-driving car groundwork"],
        "effects": ["First AI program created at CMU; first CS department making it AI discipline's founding institution", "Machine learning, robotics, and HCI PhD programs shaped these fields globally", "Duolingo language learning (500 million users) built on CMU language technology research", "Alumni and researchers founding or leading Google, Oracle, Intel, Lyft creating technology leadership pipeline"],
        "relationships": [{"entity": "Andrew Carnegie", "relationship": "FOUNDED_BY", "note": "Carnegie founded Technical Schools in 1900 for Pittsburgh working-class industrial education"}, {"entity": "Herbert Simon", "relationship": "AI_PIONEERED_BY", "note": "Simon and Newell's 1956 Logic Theorist — first AI program — created at CMU precursor institution"}, {"entity": "Allen Newell", "relationship": "AI_CO-PIONEERED_BY", "note": "Newell co-created Logic Theorist with Simon; both received 1975 Turing Award"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Carnegie Mellon created the first AI program (Logic Theorist, 1956) and the first computer science department (1965), making it the founding institution of computer science as an academic discipline — the discipline that defined the 21st century's most consequential technologies.", "significanceCategory": "world-changing"},
    }),
    ("university-of-melbourne", {
        "summary": "The University of Melbourne, founded in 1853 as Australia's second oldest university (after Sydney, 1850), is Australia's highest-ranked research university and a member of the Group of Eight research universities that produce the majority of Australia's research output. The university's sandstone Gothic buildings in Parkville, Melbourne, and its 220 Nobel laureates, prime ministers, and vice-chancellors among alumni make it the institutional center of Australian intellectual and professional life for 170 years.\n\nThe University of Melbourne was established in the aftermath of the Victoria gold rush (1851) as the young colony's cultural statement — building elaborate Gothic Revival buildings by German architect Friedrich Kawerau to rival Oxford and Cambridge. The university's medical school (established 1862) was Australia's first and produced the Nobel laureates who developed penicillin applications, cancer research, and immunology advances. Melbourne's Law School produced four of Australia's seven prime ministers since 1975.\n\nThe Melbourne Model (2008) — replacing undergraduate specialization with broad generalist bachelor degrees followed by professional graduate schools — was Australia's most radical university reform since federation, modeled on American liberal arts traditions. The model influenced Australian universities nationally and its graduate professional schools in law, medicine, education, and engineering are now ranked among Asia-Pacific's finest. The university's BioMedical Precinct — co-located with the Royal Melbourne Hospital and Walter and Eliza Hall Institute of Medical Research — creates an integrated medical research ecosystem.",
        "causes": ["1853 founding from Victoria gold rush wealth as colony's cultural and intellectual statement", "Gothic Revival architecture by Kawerau creating Oxford-Cambridge visual identity in Melbourne", "Medical school 1862 founding producing Australia's Nobel laureate researchers in immunology and cancer", "Melbourne Model 2008 replacing undergraduate specialization with American liberal arts generalist approach"],
        "effects": ["Highest-ranked Australian research university with 170-year contribution to national intellectual life", "Four of seven Australian prime ministers since 1975 educated at Melbourne Law School", "Melbourne Model influenced Australian higher education reform nationally", "BioMedical Precinct creating integrated medical research ecosystem with Nobel Prize-winning track record"],
        "relationships": [{"entity": "Friedrich Kawerau", "relationship": "EARLY_BUILDINGS_DESIGNED_BY", "note": "German architect Kawerau designed Gothic Revival buildings creating Oxford-Cambridge identity"}, {"entity": "Walter and Eliza Hall Institute", "relationship": "RESEARCH_PARTNER", "note": "Co-located medical research institute produced Nobel laureates in immunology and cancer biology"}, {"entity": "Melbourne Model", "relationship": "IMPLEMENTED", "note": "2008 reform replacing specialization with generalist bachelor degrees influenced Australian higher education"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The University of Melbourne's 170-year centrality to Australian intellectual, professional, and political life — combined with the Melbourne Model's influence on higher education reform — makes it the most consequential institution in Australian academic history.", "significanceCategory": "continental"},
    }),
    ("university-of-bologna", {
        "summary": "The University of Bologna (Alma Mater Studiorum), founded in 1088, is the world's oldest continuously operating university — predating Oxford by over a century, the printing press by nearly 400 years, and the discovery of the Americas by 400 years. Bologna's foundation established the template for every subsequent university on earth: autonomous academic guild, faculty organized by discipline, degree conferral as intellectual certification, and the concepts of academic freedom and university self-governance. When medieval kings and popes wanted educated administrators, they looked to Bologna's graduates.\n\nBologna emerged from the Investiture Controversy (1076-1122) — the conflict between Holy Roman Emperors and Popes over who could appoint bishops. Both sides needed legal scholars to argue their cases from Roman law. Irnerius began teaching Roman law in Bologna around 1088, attracting students from across Europe. The term 'university' (universitas) originally meant not the institution but the student guild — Bologna's students hired and fired their own professors, set their own curriculum, and fined professors who lectured beyond the scheduled time.\n\nBologna's greatest graduate was Dante Alighieri (briefly enrolled), but its most consequential were the generations of jurists who systematized Roman and canon law. Gratian's Decretum (1140) — compiled at Bologna — created Catholic canon law as a systematic discipline. Thomas Becket studied at Bologna. The 1158 Authentica Habita of Frederick Barbarossa gave students imperial protection — the first legal guarantee of academic freedom — at a conference at Bologna's request. The 2000-era Bologna Process (harmonizing European university degrees) was named for the institution.",
        "causes": ["1088 founding from Irnerius's Roman law teaching serving Investiture Controversy legal debates", "Student-guild governance model giving students power to hire/fire professors", "Gratian's 1140 Decretum creating Catholic canon law as systematic discipline", "1158 Authentica Habita giving students imperial protection as first legal guarantee of academic freedom"],
        "effects": ["World's oldest continuously operating university providing template for every subsequent institution", "Canon law systematization governing Catholic Church governance for centuries", "Academic freedom concept from 1158 imperial guarantee became foundation of university autonomy everywhere", "Bologna Process 2000 harmonizing European university degrees named in honor of the founding institution"],
        "relationships": [{"entity": "Irnerius", "relationship": "FOUNDED_BY", "note": "Irnerius began teaching Roman law at Bologna around 1088 attracting Europe's first student body"}, {"entity": "Gratian", "relationship": "CANON_LAW_COMPILED_BY", "note": "Gratian compiled Decretum at Bologna in 1140 creating Catholic canon law as systematic discipline"}, {"entity": "Frederick Barbarossa", "relationship": "ACADEMIC_FREEDOM_GUARANTEED_BY", "note": "Barbarossa's 1158 Authentica Habita provided first legal guarantee of academic freedom at Bologna's request"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "As the world's oldest university (1088), Bologna created the template for academic organization — degree conferral, faculty guilds, academic freedom — that every university on earth has followed for 936 years, making it the founding institution of the entire global system of higher education.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 84 — Class 381 Universities III")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
