#!/usr/bin/env python3
"""Batch 58 — Class 312 Dynasties III (qin, qing, seleucid, umayyad, safavid, timurid, pallava, zhou) (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/312-Class-312"
FILE_PREFIX = "312"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("qin-dynasty", {
        "summary": "The Qin dynasty (221–206 BCE) was the first unified Chinese empire, founded by Qin Shi Huang who conquered the six rival states in 221 BCE after centuries of warfare in the Warring States period. Though lasting only 15 years, the Qin's standardization of writing, currency, weights, measures, and road gauge unified China so thoroughly that its political legacy endured for 2,000 years — the very name 'China' derives from 'Qin.'\n\nQin Shi Huang's standardization reforms were revolutionary: a unified script allowed officials from different regions to communicate; standardized axle widths made roads traversable by all vehicles; standardized bronze weights enabled commerce; standardized coinage replaced dozens of regional currencies. The First Emperor also began construction of the Great Wall to defend against Xiongnu nomads and built a magnificent burial complex guarded by the Terracotta Army — 8,000 individually sculpted warriors discovered in 1974.\n\nThe Qin's harsh Legalist governance, book burnings, and massive labor conscription — building the Great Wall, Epang Palace, and the imperial mausoleum with hundreds of thousands of workers — created intense resentment. Revolts erupted within years of the First Emperor's death in 210 BCE, and the dynasty collapsed in 206 BCE after just 15 years. But the Han dynasty that followed maintained Qin's administrative structure, making Qin the essential precedent for Chinese civilization.",
        "causes": ["Centuries of Warring States warfare creating competitive pressure for military innovation", "Qin's adoption of Legalist philosophy enabling meritocratic military promotion", "Lord Shang Yang's radical administrative reforms transforming Qin's military power", "Geographic advantages of Qin heartland in Guanzhong basin"],
        "effects": ["Chinese script standardization enabled imperial unity across linguistic diversity", "Great Wall construction created enduring boundary between nomadic and agricultural civilizations", "Terracotta Army became world's greatest archaeological discovery revealing ancient Chinese art", "Name 'Qin' became 'China' in Western languages, defining the civilization's identity"],
        "relationships": [{"entity": "Qin Shi Huang", "relationship": "LED_BY", "note": "First Emperor who unified China and built Terracotta Army"}, {"entity": "Han dynasty", "relationship": "SUCCEEDED_BY", "note": "Han maintained Qin administrative structures proving their effectiveness"}, {"entity": "Great Wall of China", "relationship": "BUILT", "note": "Qin linked and extended walls to defend northern frontier"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Qin dynasty's standardization of script, currency, and measurement unified China so fundamentally that the civilization it created persisted for 2,000 years — earning it the title of China's foundational dynasty.", "significanceCategory": "world-changing"},
    }),
    ("qing-dynasty", {
        "summary": "The Qing dynasty (1644–1912) was the last imperial dynasty of China, founded by the Manchu Aisin Gioro clan who invaded from Manchuria. At its height in the 18th century, the Qing ruled the largest empire in Chinese history, encompassing China proper, Mongolia, Tibet, Xinjiang, and Taiwan — a territory still largely defining modern China's borders.\n\nThe Kangxi, Yongzheng, and Qianlong emperors presided over China's High Qing period (1661-1799), an era of territorial expansion, economic prosperity, and cultural achievement. The Qianlong Emperor's military campaigns established Chinese sovereignty over Tibet and Xinjiang, created the enduring political entity that Chinese nationalists would later claim. The Qing population grew from 100 million to 400 million during the 18th century, enabled by New World crops like sweet potatoes and maize.\n\nThe 19th century saw catastrophic decline: the Opium Wars forced China to open trade and cede Hong Kong to Britain; the Taiping Rebellion (1850-1864) killed an estimated 20-30 million people; and the Boxer Rebellion's suppression brought foreign troops into Beijing. The 1912 revolution of Sun Yat-sen ended the dynasty, replacing it with the Republic of China. The Qing's territorial legacy shaped modern China's territorial claims including Tibet, Xinjiang, and Taiwan controversies.",
        "causes": ["Ming dynasty's internal rebellion and military weakness enabling Manchu invasion", "Manchu military superiority through Eight Banner system and cavalry warfare", "Ming loyalist Wu Sangui opening Shanhaiguan Pass to Manchu armies", "Qing adoption of Confucian governance and Chinese administrative traditions"],
        "effects": ["Tibet and Xinjiang incorporation created enduring Chinese territorial claims", "Opium Wars forced open China to Western trade and ended 'Celestial Empire' self-sufficiency", "Population explosion from New World crops transformed Chinese agriculture and demographics", "Qing's fall ended 2,000 years of imperial governance and inaugurated modern Chinese state"],
        "relationships": [{"entity": "Kangxi Emperor", "relationship": "LED_BY", "note": "Second Qing emperor who consolidated control and expanded territorial borders"}, {"entity": "Opium Wars", "relationship": "AFFECTED_BY", "note": "British victories in 1839-42 and 1856-60 forced treaty ports and cessions"}, {"entity": "Republic of China", "relationship": "OVERTHROWN_BY", "note": "1912 revolution under Sun Yat-sen ended Qing dynasty"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Qing dynasty defined modern China's borders through territorial expansion, then suffered its humiliation through Western imperialism — creating the historical wounds and ambitions that shape Chinese foreign policy today.", "significanceCategory": "world-changing"},
    }),
    ("seleucid-dynasty", {
        "summary": "The Seleucid Empire (312–63 BCE) was a Hellenistic state founded by Seleucus I Nicator, one of Alexander the Great's generals, after the Wars of the Diadochi that fragmented Alexander's empire. At its height the Seleucid Empire stretched from Thrace to the borders of India, spreading Greek culture (Hellenism) across the Near East, Persia, and Central Asia.\n\nSeleucus I received Babylon after the 311 BCE Settlement of Triparadisus and built his capital at Antioch-on-the-Orontes (modern Antakya, Turkey) in 300 BCE, founding dozens of new Greek cities including Seleucia, Apamea, and Laodicea. The empire's multicultural Hellenistic character — Greek ruling class over Persian, Babylonian, Syrian, and Jewish subjects — created the cultural synthesis that later Roman Syria and Byzantium inherited. The Seleucid calendar, beginning in 312 BCE, was used by Jewish and Arabic communities for centuries.\n\nSeleucid conflict with the Maccabees in Judea (producing Hanukkah) and the gradual independence of Bactria, Parthia, and Judea under regional rulers eroded the empire. Rome's defeat of Antiochus III at Magnesia in 190 BCE broke Seleucid power in Asia Minor. The empire shrank to Syria, Phoenicia, and Mesopotamia before Tigranes of Armenia and Pompey of Rome completed its dissolution by 63 BCE.",
        "causes": ["Alexander the Great's conquests creating Hellenistic world requiring new governance", "Wars of the Diadochi enabling Seleucus to carve out Mesopotamian-Persian territory", "Greek colonization policy creating new cities as administrative and cultural centers", "Trade routes between Mediterranean and Central Asia generating commercial wealth"],
        "effects": ["Hellenistic culture spread Greek language, art, and philosophy to Middle East and Central Asia", "Antioch became one of antiquity's largest and most important cities", "Maccabean conflict with Seleucids produced Jewish festival of Hanukkah", "Greek cultural synthesis with Persian traditions created Greco-Roman-Eastern civilization"],
        "relationships": [{"entity": "Seleucus I Nicator", "relationship": "FOUNDED_BY", "note": "Alexander's general who received Babylon and built empire to its greatest extent"}, {"entity": "Alexander the Great", "relationship": "SUCCEEDED_FROM", "note": "Empire carved from Alexander's conquests after his death in 323 BCE"}, {"entity": "Roman Republic", "relationship": "DEFEATED_BY", "note": "Battle of Magnesia (190 BCE) broke Seleucid power west of Taurus Mountains"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Seleucid Empire spread Hellenism from Syria to Bactria, creating the cultural synthesis that bridged Greek and Persian civilizations and shaped Judaism, Christianity, and Islam through its Hellenistic legacy.", "significanceCategory": "world-changing"},
    }),
    ("umayyad-caliphate", {
        "summary": "The Umayyad Caliphate (661–750 CE) was the second Islamic caliphate, founded by Muawiyah I after the First Islamic Civil War. The largest empire in history up to that point, the Umayyads expanded from Spain and Morocco in the west to the borders of China and India in the east, spreading Islam across three continents in less than a century.\n\nMuawiyah I's establishment of the Umayyad caliphate in Damascus transformed Islam from a prophetic movement to an imperial administration. Arabic became the language of administration across the empire. The Dome of the Rock in Jerusalem (691 CE) and the Great Mosque of Damascus (706-715 CE) were built under Umayyad patronage, establishing Islamic monumental architecture. The conquest of the Iberian Peninsula (711-719 CE) introduced Islamic civilization to Europe.\n\nThe Umayyad expansion brought Islam's greatest military achievements but also its most controversial political developments: the marginalization of non-Arab Muslims (mawali) and the transformation of the caliphate into an Arab monarchy generated resentment that fueled the Abbasid Revolution of 750. A surviving Umayyad prince, Abd al-Rahman I, escaped to Spain and established the Emirate of Córdoba, preserving the dynasty until 1031 CE. Córdoba under Umayyad rule became medieval Europe's largest and most sophisticated city.",
        "causes": ["First Islamic Civil War (656-661) enabling Muawiyah's consolidation as caliph", "Arab military superiority over weakened Byzantine and Sasanian empires", "Islam providing ideological unity for diverse conquering armies", "Damascus strategic location as administrative capital bridging Arabia and the Fertile Crescent"],
        "effects": ["Islam spread from Atlantic to Central Asia in under a century", "Córdoba became medieval Europe's largest city under Spanish Umayyads", "Dome of the Rock established Jerusalem as sacred Islamic site", "Arabic language became lingua franca of science, trade, and governance across the Middle East"],
        "relationships": [{"entity": "Muawiyah I", "relationship": "FOUNDED_BY", "note": "First Umayyad caliph who moved capital to Damascus and established hereditary rule"}, {"entity": "Abbasid Caliphate", "relationship": "OVERTHROWN_BY", "note": "Abbasid Revolution of 750 CE ended Umayyad caliphate in the east"}, {"entity": "Dome of the Rock", "relationship": "BUILT", "note": "Caliph Abd al-Malik built Dome of the Rock in Jerusalem in 691 CE"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Umayyad Caliphate created the largest empire of its time and spread Islam from the Atlantic to Central Asia, establishing the geographic and cultural foundations of the Islamic world that persist today.", "significanceCategory": "world-changing"},
    }),
    ("safavid-empire", {
        "summary": "The Safavid Empire (1501–1736) was a Persian imperial dynasty that established Twelver Shia Islam as the state religion of Iran — a decision that permanently defined Iranian national identity and created the Sunni-Shia divide shaping the Middle East today. Founded by Ismail I, who conquered much of Persia by age 14, the Safavids made Iran Shia when 90% of its population was Sunni.\n\nShah Ismail I's conversion of Iran to Shia Islam, accomplished through military conquest, religious coercion, and systematic killing of Sunni religious scholars, was one of history's most consequential acts of religious policy. The Safavid-Ottoman wars, motivated partly by Sunni-Shia rivalry, defined the Middle Eastern political landscape for two centuries. Shah Abbas I (r.1587-1629) made Isfahan his capital, creating one of the world's most beautiful cities, and built the Safavid empire to its greatest territorial extent.\n\nThe Safavid Empire fostered Persian art, literature, and architecture at extraordinary levels: Isfahan's Naqsh-e Jahan Square, the Shah Mosque (1611-1629), and Ali Qapu Palace represent the apex of Safavid aesthetics. Persian became the literary language of Mughal India and Ottoman courts. The empire's decline under later weak rulers and the 1722 Afghan Ghilzai invasion ended Safavid rule, though Iran's Shia identity — their most enduring creation — defines Iranian civilization.",
        "causes": ["Ismail I's Shia Sufi order (Safaviyya) providing ideological and military foundation", "Qizilbash Turkic tribal warriors providing military force for Ismail's conquests", "Sunni Ottoman pressure making Shia identity a marker of Iranian distinctiveness", "Persian cultural traditions distinct from Arab-dominated Sunni Islam"],
        "effects": ["Twelve Imam Shia Islam became Iranian state religion defining national identity", "Sunni-Shia division between Safavid and Ottoman empires created enduring regional fault line", "Isfahan became one of world's most beautiful cities with magnificent architectural legacy", "Persian cultural golden age created art, literature, and philosophy still celebrated globally"],
        "relationships": [{"entity": "Ismail I", "relationship": "FOUNDED_BY", "note": "Teenage conqueror who made Twelver Shia Islam Iran's state religion"}, {"entity": "Shah Abbas I", "relationship": "GREATEST_RULER", "note": "Abbas rebuilt empire after Ottoman defeats and created Isfahan as cultural capital"}, {"entity": "Ottoman Empire", "relationship": "FOUGHT_WITH", "note": "Century-long Ottoman-Safavid wars defined western border and Sunni-Shia frontier"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Safavid Empire's conversion of Iran to Shia Islam created the sectarian identity shaping Middle Eastern geopolitics today, making it one of the most consequential acts of religious engineering in history.", "significanceCategory": "world-changing"},
    }),
    ("timurid-dynasty", {
        "summary": "The Timurid Empire (1370–1507) was a Turco-Mongol empire founded by Timur (Tamerlane) in Central Asia, with Samarkand as its magnificent capital. One of history's most feared conquerors, Timur's campaigns from Anatolia to Delhi left millions dead and cities in ruin, yet his Timurid successors presided over one of the Islamic world's greatest cultural renaissances in Samarkand, Bukhara, and Herat.\n\nTimur's military campaigns between 1370 and 1405 CE crushed the Ottoman Turks at Ankara (1402), sacked Delhi (1398) killing 100,000, and devastated the Golden Horde. He built towers of skulls from conquered enemies as a psychological weapon and killed an estimated 17 million people — 5% of the world's population at that time. Samarkand, beautified with the spoils of conquest, featured the Registan mosque complex and the Gur-e-Amir mausoleum (Timur's own tomb), still standing as masterworks of Islamic architecture.\n\nThe Timurid cultural renaissance under Timur's successors — particularly Shahrukh, Ulugh Beg, and Sultan Husayn Bayqara — produced extraordinary achievements: Ulugh Beg built the world's most advanced pre-telescopic observatory, his astronomical tables remaining accurate for centuries. Persian miniature painting reached its classical peak. The poet Jami, the philosopher Mir Ali Shir Nava'i, and Herat's literary circle set standards that influenced Mughal India and Safavid Persia.",
        "causes": ["Post-Mongol power vacuum in Central Asia enabling Timur's rise as Chagatai commander", "Timur's military genius combining Mongol cavalry tactics with siege warfare", "Silk Road trade routes through Samarkand generating wealth for cultural patronage", "Turkish-Mongol warrior traditions valuing both conquest and cultural achievement"],
        "effects": ["Ottoman defeat at Ankara temporarily halted Ottoman expansion into Europe", "Delhi sack accelerated Sultanate's decline opening path for Mughal invasion", "Samarkand's Registan Square became apex of Timurid Islamic architectural achievement", "Timurid cultural renaissance influenced Mughal and Safavid court culture for centuries"],
        "relationships": [{"entity": "Timur (Tamerlane)", "relationship": "FOUNDED_BY", "note": "Founded empire through conquest from 1370, capital at Samarkand"}, {"entity": "Ulugh Beg", "relationship": "PRODUCED_SCHOLAR", "note": "Timurid prince who built world's most advanced pre-telescopic observatory"}, {"entity": "Mughal Empire", "relationship": "INSPIRED", "note": "Babur, Timurid prince, founded Mughal Empire claiming Timurid legacy"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Timurid Empire combined history's most destructive conqueror with a cultural golden age that transmitted Islamic-Persian aesthetics to Mughal India and Safavid Persia, shaping South and Central Asian civilization for centuries.", "significanceCategory": "world-changing"},
    }),
    ("pallava-dynasty", {
        "summary": "The Pallava dynasty (275–897 CE) was a South Indian dynasty that ruled the region of Tondaimandalam (northern Tamil Nadu) from Kanchipuram, one of the sacred seven cities of Hinduism. The Pallavas were master builders and patrons of literature, creating the Shore Temple at Mahabalipuram and rock-cut monuments that became the prototype for Dravidian temple architecture across South and Southeast Asia.\n\nThe Pallavas reached their peak under Mahendravarman I and Narasimhavarman I (7th century CE), who defeated the Chalukyas in a series of wars. Narasimhavarman I earned the title 'Vatapi Kondan' (Conqueror of Vatapi) after sacking the Chalukya capital. The Mahabalipuram shore temple complex, built on the Bay of Bengal coast, includes the famous rathas (chariot temples) carved from single granite boulders, the Descent of the Ganges bas-relief (the world's largest open-air rock relief), and the Shore Temple — all UNESCO World Heritage sites.\n\nThe Pallavas are credited with developing the Grantha script from which Tamil, Malayalam, Sinhala, and several Southeast Asian scripts including Khmer, Javanese, and Thai scripts ultimately derive. The spread of Pallava-influenced architecture and Buddhism through trade networks shaped the temple traditions of Cambodia, Thailand, and Indonesia.",
        "causes": ["Geographic position between northern and southern Indian cultural spheres", "Control of major trade routes between India and Southeast Asia through Bay of Bengal", "Brahmin patronage providing literary and religious intellectual leadership", "Competition with Chalukya and Pandya dynasties driving military and artistic achievement"],
        "effects": ["Dravidian temple architecture style originated with Pallava builders", "Grantha script became ancestor of Tamil and Southeast Asian writing systems", "Shore Temple at Mahabalipuram became UNESCO World Heritage site and prototype", "Pallava cultural influence shaped Cambodian Khmer and Indonesian Java temple traditions"],
        "relationships": [{"entity": "Narasimhavarman I", "relationship": "GREATEST_RULER", "note": "7th-century king who defeated Chalukyas and built Mahabalipuram monuments"}, {"entity": "Chola dynasty", "relationship": "OVERTHROWN_BY", "note": "Chola king Aditya I conquered last Pallava ruler Aparajita in 897 CE"}, {"entity": "Chalukya dynasty", "relationship": "FOUGHT_WITH", "note": "Century-long Pallava-Chalukya wars shaped the 7th-century South Indian political landscape"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Pallava dynasty's architectural and script innovations created Dravidian temple aesthetics and Southeast Asian writing systems, making Pallava cultural influence one of the most geographically extensive legacies in Asian history.", "significanceCategory": "continental"},
    }),
    ("zhou-dynasty", {
        "summary": "The Zhou dynasty (1046–256 BCE) was the longest-lasting dynasty in Chinese history, ruling for 790 years. Though weakening politically in its final centuries into the Warring States period, the Zhou era produced Confucius, Laozi, Sun Tzu, and Mencius — making it the most intellectually fertile period in Chinese history and the source of Confucianism, Daoism, Legalism, and Mohism in the Hundred Schools of Thought.\n\nThe Western Zhou (1046-771 BCE) established the feudal system that decentralized power to regional lords in exchange for loyalty. When nomads sacked the capital Hao in 771 BCE, the Eastern Zhou period began, which despite political weakness produced the Chinese philosophical golden age. The Spring and Autumn period (770-476 BCE) saw the rise of Confucius (551-479 BCE), whose ethical teachings about proper relationships, benevolent governance, and self-cultivation became the foundation of Chinese civilization and East Asian culture broadly.\n\nThe Warring States period (475-221 BCE) saw seven competing kingdoms develop competing philosophies and innovative military and administrative techniques. Sun Tzu's 'The Art of War,' written during this era, remains the most widely read strategic text in military history. Iron smelting, cavalry warfare, and bureaucratic administration innovations during the Zhou period laid the technical and institutional foundations that the Qin dynasty unified under one rule.",
        "causes": ["King Wu of Zhou's military victory over Shang dynasty at Battle of Muye", "Feudal decentralization enabling effective governance of large territory", "Bronze Age technology providing military advantages to Zhou forces", "Heaven's Mandate (Tianming) ideology legitimizing Zhou rule over Shang"],
        "effects": ["Confucianism established as foundational Chinese social and political philosophy", "Daoism and Legalism emerged as alternative philosophical traditions", "Sun Tzu's Art of War became globally influential strategic text", "Hundred Schools of Thought created China's philosophical golden age"],
        "relationships": [{"entity": "Confucius", "relationship": "PRODUCED", "note": "Confucius (551-479 BCE) developed his teachings during Zhou's Spring and Autumn period"}, {"entity": "Laozi", "relationship": "PRODUCED", "note": "Traditional founder of Daoism, associated with Eastern Zhou era"}, {"entity": "Qin dynasty", "relationship": "ENDED_BY", "note": "Qin king unified China in 221 BCE absorbing last Zhou territory"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Zhou dynasty's intellectual flowering — producing Confucius, Laozi, and the Hundred Schools of Thought — created the philosophical foundations of Chinese civilization that remain central to East Asian culture 2,500 years later.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 58 — Class 312 Dynasties III")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
