#!/usr/bin/env python3
"""Batch 98 — Class 330 Companies VI (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/330-Class-330"
FILE_PREFIX = "330"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("bayer", {
        "summary": "Bayer AG, founded 1863 in Barmen, Germany by Friedrich Bayer and Johann Friedrich Weskott as a synthetic dye manufacturer, is one of the world's largest pharmaceutical and agricultural science companies — known for aspirin (Bayer's most iconic product, first synthesized by Felix Hoffmann at Bayer in 1897), heroin (also first synthesized by Bayer in 1898 and marketed as a cough suppressant until 1913), and glyphosate (Roundup herbicide, inherited through the $63 billion acquisition of Monsanto in 2018). Bayer's history encapsulates both the triumphs and controversies of 20th-century German science.\n\nBayer chemist Felix Hoffmann synthesized acetylsalicylic acid (aspirin) on August 10, 1897, producing a stable form of a compound known for centuries in willow bark. Aspirin became the world's best-selling drug for most of the 20th century — over 40,000 tonnes consumed annually worldwide. In the same period, Hoffmann synthesized diacetylmorphine (heroin) — Bayer trademarked the name 'Heroin' and marketed it as a non-addictive cough suppressant 1898-1913, sold over the counter in 23 countries.\n\nBayer was part of I.G. Farben (1925-1945) — the industrial conglomerate that manufactured Zyklon B for the Nazi Holocaust and used concentration camp labor. Bayer was reconstituted as an independent company after WWII. The 2018 Monsanto acquisition — including glyphosate's Roundup — immediately embroiled Bayer in massive litigation: US courts have awarded billions in damages to cancer patients claiming glyphosate caused their non-Hodgkin lymphoma, with Bayer settling for $10+ billion.",
        "causes": ["1863 Barmen founding as synthetic dye company entering pharmaceutical production", "1897 Felix Hoffmann aspirin synthesis creating world's best-selling 20th-century drug", "1898 heroin synthesis and marketing as cough suppressant until 1913 addiction recognition", "2018 $63 billion Monsanto acquisition inheriting Roundup/glyphosate cancer litigation"],
        "effects": ["Aspirin as world's best-selling drug for most of 20th century — 40,000 tonnes consumed annually", "Heroin naming and marketing creating global opioid addiction precedent", "I.G. Farben participation linking Bayer to Zyklon B and Holocaust industrial complex", "$10+ billion Roundup cancer litigation settlement as largest pharmaceutical liability in history"],
        "relationships": [{"entity": "Felix Hoffmann", "relationship": "ASPIRIN_SYNTHESIZED_BY", "note": "Hoffmann's August 10, 1897 acetylsalicylic acid synthesis created aspirin and heroin on the same day"}, {"entity": "Monsanto", "relationship": "ACQUIRED", "note": "2018 $63 billion acquisition inherited Roundup/glyphosate and $10+ billion cancer litigation"}, {"entity": "I.G. Farben", "relationship": "CONSTITUENT_COMPANY_OF", "note": "Bayer was part of I.G. Farben 1925-1945, which manufactured Zyklon B for the Holocaust"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Bayer's simultaneous invention of aspirin (the 20th century's most beneficial drug) and heroin (one of its most destructive) on the same day in 1897 — by the same chemist — is history's most striking illustration that the same chemical ingenuity can produce salvation and catastrophe simultaneously.", "significanceCategory": "world-changing"},
    }),
    ("canon-inc", {
        "summary": "Canon Inc., founded 1937 in Tokyo by Takeshi Mitarai and Saburo Uchida as Precision Optical Instruments Laboratory, became Japan's leading camera manufacturer and then one of the world's dominant imaging technology companies — known for pioneering autofocus SLR cameras (Canon AE-1, 1976, the best-selling SLR in history), laser printing (Canon's laser engine powered the original HP LaserJet, 1984), and digital mirrorless camera systems (EOS R series). Canon's partnership with HP to create the laser printer industry is one of technology's most consequential corporate collaborations.\n\nCanon's AE-1 (1976) was the first camera to use a microprocessor for automation control — the first mass-market affordable SLR with electronic automatic exposure. It sold 1 million units in the first two years, then 5 million total (twice the sales of any previous SLR) — the camera that democratized 35mm photography for amateur users. Canon's 1969 Canon F-1 professional system was the choice of photojournalists at the 1972 Munich Olympics.\n\nThe HP-Canon laser printing partnership (1984): Canon developed the compact laser engine; HP provided the computer interface and printer design. The HP LaserJet (1984) launched desktop laser printing for offices worldwide. Canon's laser engine continued powering HP LaserJets through dozens of generations, creating a licensing revenue stream that funded Canon's camera R&D. Canon's global workforce: 180,000 employees, ¥4 trillion annual revenue, operations in 200+ countries. The EOS R mirrorless system (2018) competes with Sony and Nikon for professional digital photography.",
        "causes": ["1937 founding as Precision Optical Instruments Laboratory in wartime Japan", "1976 AE-1 microprocessor-controlled SLR as first mass-market affordable camera selling 5 million units", "1984 HP-Canon laser engine partnership creating desktop laser printing industry", "2018 EOS R mirrorless system launch entering competitive mirrorless camera market"],
        "effects": ["AE-1 democratizing 35mm SLR photography for amateur market — 5 million units sold", "HP LaserJet powered by Canon engine transforming office document production globally", "Canon-HP partnership creating desktop publishing and office laser printing revolution", "180,000 employees and ¥4 trillion revenue making Canon a major Japanese technology conglomerate"],
        "relationships": [{"entity": "HP (Hewlett-Packard)", "relationship": "LASER_PRINTING_PARTNERSHIP", "note": "Canon's laser engine powered HP LaserJet 1984 creating desktop laser printing industry"}, {"entity": "AE-1 Camera", "relationship": "MANUFACTURED", "note": "AE-1 (1976) sold 5 million units as first microprocessor-controlled mass-market SLR"}, {"entity": "Takeshi Mitarai", "relationship": "CO-FOUNDED_BY", "note": "Mitarai co-founded Precision Optical Instruments Laboratory in 1937 that became Canon"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Canon — democratizing photography with the AE-1 and creating office laser printing through the HP partnership — participated in two of the most consequential democratizations of visual and document technology in the 20th century.", "significanceCategory": "continental"},
    }),
    ("caixabank", {
        "summary": "CaixaBank, S.A., the retail banking arm of the La Caixa foundation (founded 1904 in Barcelona by Francesc Moragas Barret), is Spain's largest domestic bank by retail market share — with €680 billion in assets, 21 million customers in Spain and Portugal, and the most extensive ATM network in Spain. CaixaBank is unique among major European banks in having a charitable foundation as its majority shareholder: the 'la Caixa' Foundation (holding 31.5% after the 2012 IPO) is Europe's largest private charitable foundation, distributing €500 million annually in social programs.\n\nLa Caixa was founded as a savings bank (caixa d'estalvis) serving Barcelona's working class — a 'popular bank' where workers could deposit small savings and access credit. The savings bank model (caixes d'estalvis in Catalan, cajas de ahorros in Castilian) was a Mediterranean banking tradition oriented toward social purpose rather than shareholder profit. La Caixa grew to Spain's second-largest bank (after Banco Santander) through the 20th century.\n\nThe 2010-2012 Spanish banking crisis — triggered by the collapse of Spain's real estate bubble — caused most Spanish savings banks (cajas) to be nationalized or merged. La Caixa restructured by separating its banking operations into CaixaBank (publicly traded, 2012) while the Foundation retained majority ownership. CaixaBank's 2021 merger with Bankia (the nationalized bank) created Spain's largest domestic bank. The La Caixa Foundation's €500 million annual social distribution — in education, social inclusion, research, and art — makes it the largest private philanthropic operation in Spain.",
        "causes": ["1904 Barcelona founding as workers' savings bank serving Catalan working class", "20th-century growth making La Caixa Spain's second-largest bank", "2010-2012 Spanish banking crisis requiring restructuring into foundation-owned listed bank", "2021 Bankia merger creating Spain's largest domestic bank"],
        "effects": ["Spain's largest domestic bank by retail market share with 21 million customers", "La Caixa Foundation as Europe's largest private charitable foundation distributing €500M annually", "Foundation-controlled listed bank model as unique European banking ownership structure", "2021 Bankia merger making CaixaBank dominant in Spain's post-crisis consolidated banking sector"],
        "relationships": [{"entity": "La Caixa Foundation", "relationship": "MAJORITY_OWNED_BY", "note": "La Caixa Foundation (31.5% stake) is Europe's largest private charitable foundation — unique ownership"}, {"entity": "Bankia", "relationship": "MERGED_WITH", "note": "2021 CaixaBank-Bankia merger created Spain's largest domestic bank"}, {"entity": "Francesc Moragas Barret", "relationship": "FOUNDED_BY", "note": "Moragas founded La Caixa as Barcelona workers' savings bank in 1904"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "CaixaBank's foundation-controlled ownership structure — a charitable foundation as majority shareholder of a publicly traded major bank — is Europe's most unusual banking governance model, demonstrating that 'social purpose' banking can compete with shareholder-maximizing banks at scale.", "significanceCategory": "regional"},
    }),
    ("banco-bilbao-vizcaya-argentaria", {
        "summary": "Banco Bilbao Vizcaya Argentaria (BBVA), formed through a series of mergers culminating in 1999 (Banco Bilbao Vizcaya + Argentaria), is Spain's second-largest bank and one of Europe's major financial groups — with €800 billion in assets, operations in 25 countries, and a unique position as the dominant bank in Latin America (Mexico, Peru, Colombia, Turkey), where it operates as a full-service retail bank rather than merely an investment presence. BBVA's Latin American footprint makes it the leading European bank in emerging markets.\n\nThe constituent banks have 19th-century origins: Banco de Bilbao (1857) and Banco de Vizcaya (1901) from the Basque industrial heartland; they merged in 1988 as BBV. Argentaria was a state banking conglomerate (privatized 1993-1998); its 1999 merger with BBV created BBVA. The Basque industrial origin — the Bilbao steel and shipping economy — gave the bank its conservative risk culture and its regional identity.\n\nBBVA's digital transformation: under CEO Francisco González (2000-2018), BBVA became one of Europe's most digitally advanced banks, launching a digital-only bank (BBVA Simple in the US, later Atom Bank partnership in the UK) and investing heavily in fintech. BBVA attempted a hostile takeover of Banco Sabadell in 2024 — Spain's largest corporate takeover attempt — to create a dominant domestic Spanish banking giant. The bank's Turkish subsidiary (Garanti BBVA) is Turkey's second-largest private bank.",
        "causes": ["1857 Banco de Bilbao founding in Basque industrial heartland of Spanish steel and shipping economy", "1988 Banco de Bilbao-Vizcaya merger creating BBV as major Spanish bank", "1999 BBV-Argentaria merger creating BBVA as Spain's second-largest bank", "Latin American expansion making BBVA dominant European bank in emerging markets"],
        "effects": ["Spain's second-largest bank with €800 billion assets and 25-country operations", "Dominant European bank in Latin America — Mexico, Peru, Colombia major markets", "Digital transformation under González making BBVA model for European banking digitalization", "2024 hostile Sabadell takeover attempt as Spain's largest-ever corporate takeover bid"],
        "relationships": [{"entity": "Banco Santander", "relationship": "SECOND_TO_IN_SPAIN", "note": "BBVA is Spain's second-largest bank after Santander; both are major international operations"}, {"entity": "Francisco González", "relationship": "DIGITAL_TRANSFORMATION_UNDER", "note": "González's 2000-2018 leadership drove BBVA's digital banking transformation"}, {"entity": "Garanti BBVA", "relationship": "TURKISH_SUBSIDIARY", "note": "Garanti BBVA is Turkey's second-largest private bank demonstrating BBVA's emerging market strategy"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "BBVA — the dominant European bank in Latin America and a pioneer of digital banking transformation — demonstrates how Spanish banks leveraged cultural and linguistic ties to build the largest European financial presence in the world's largest Spanish-speaking markets.", "significanceCategory": "continental"},
    }),
    ("alpha-bank", {
        "summary": "Alpha Bank, founded 1879 in Kalamata, Greece by Ioannis F. Costopoulos, is one of Greece's four systemic banks — a major lender that survived the Greek financial crisis (2010-2018) through recapitalization, asset sales, and loan restructuring, and is now (with €80 billion in assets) one of the most important financial institutions in southeastern Europe. Alpha Bank's history traces Greek economic development from the 19th-century Kingdom of Greece through the 20th-century industrialization and the 21st-century sovereign debt crisis.\n\nThe Costopoulos family maintained bank ownership across generations from 1879 through the 20th century, making Alpha Bank Greece's most important family-controlled bank. Alpha Bank's growth through the 20th century tracked Greece's economic expansion: from a Peloponnesian regional bank to a national lender. The 1993-2000 Balkan expansion — establishing operations in Albania, Bulgaria, Serbia, Romania, and Cyprus — positioned Alpha Bank as a southeastern European financial institution.\n\nThe 2010-2018 Greek crisis: Greece's sovereign debt crisis triggered a banking crisis — Greek banks held massive amounts of Greek government bonds that were restructured at 50%+ losses (PSI 2012). Alpha Bank required two recapitalizations (2012 and 2015) from the Hellenic Financial Stability Fund, receiving €4+ billion in state support. The bank's non-performing loan (NPL) ratio reached 50%+ at peak crisis; it declined to 8% by 2023 through securitization programs (Project Galaxy, COSMOS). The 2023 partial privatization saw the Greek state's HFSF stake reduced to below 10%.",
        "causes": ["1879 Kalamata founding by Costopoulos family as regional Greek bank", "1993-2000 Balkan expansion establishing southeastern European banking presence", "2010-2012 Greek sovereign debt crisis and PSI causing massive Greek bank losses", "2012 and 2015 state recapitalizations preserving Alpha as systemic Greek bank"],
        "effects": ["Systemic Greek bank survival through worst European banking crisis in decades", "50%+ NPL ratio at peak crisis declining to 8% through securitization programs", "Southeastern European banking presence across Balkans inherited from 1990s expansion", "2023 partial privatization reducing state HFSF stake below 10%"],
        "relationships": [{"entity": "Ioannis Costopoulos", "relationship": "FOUNDED_BY", "note": "Costopoulos family founded Alpha Bank 1879 and maintained ownership through 20th century"}, {"entity": "Greek Financial Crisis", "relationship": "SEVERELY_AFFECTED_BY", "note": "2010-2018 crisis required two state recapitalizations totaling €4+ billion for Alpha Bank survival"}, {"entity": "Hellenic Financial Stability Fund", "relationship": "RECAPITALIZED_BY", "note": "HFSF provided €4+ billion in 2012 and 2015 recapitalizations keeping Alpha Bank viable"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "Alpha Bank's survival through the Greek financial crisis — the most severe banking stress test experienced by a eurozone member state — demonstrates both the fragility of small-economy banks exposed to sovereign debt and the effectiveness of eurozone bailout mechanisms in preserving systemic financial institutions.", "significanceCategory": "regional"},
    }),
    ("australia-and-new-zealand-banking-group", {
        "summary": "Australia and New Zealand Banking Group (ANZ), one of the 'Big Four' Australian banks, traces its origins to the Bank of Australasia (1835) — founded in London to finance Australian colonial settlement — and is now (with AUD 1 trillion+ in assets) one of the Southern Hemisphere's largest banks, with particular strength in Asian banking (among the most Asia-focused of the major Australian banks) and Pacific island markets. ANZ's 2023 acquisition of Suncorp Bank created Australia's most significant banking consolidation in decades.\n\nThe Bank of Australasia (1835) — founded in London by investors supporting British colonial settlement — was one of the first banks established to serve the Australian colonies, financing wool and grain exports, pastoral loans, and colonial infrastructure. The Bank of New Zealand (1861) was founded separately; both were merged through ANZ's predecessor structures over the 20th century. ANZ in its current form emerged from the 1970 merger of the Australia and New Zealand Bank with the English, Scottish and Australian Bank.\n\nANZ's Asian strategy: under CEO Mike Smith (2007-2016), ANZ made a strategic push to become Australia's most internationally connected bank with a particular focus on Asia — acquiring stakes in Asian banks (AmBank Malaysia, PT Panin Bank Indonesia), growing Asian institutional business, and positioning itself as the primary banker for Australia-Asia trade flows. The 2023 AUD 4.9 billion Suncorp Bank acquisition — pending regulatory approval — would make ANZ the second-largest Australian bank by retail deposits.",
        "causes": ["1835 Bank of Australasia London founding to finance British Australian colonial settlement", "20th-century mergers creating Australia and New Zealand Banking Group", "2007-2016 Asian strategy positioning ANZ as Australia's most Asia-connected major bank", "2023 Suncorp Bank acquisition as largest Australian banking consolidation in decades"],
        "effects": ["AUD 1 trillion+ assets making ANZ one of Southern Hemisphere's largest banks", "Asia-focused strategy making ANZ primary banker for Australia-Asia trade flows", "Pacific island banking presence making ANZ dominant in Pacific small-economy markets", "2023 Suncorp acquisition pending creating Australia's second-largest bank by retail deposits"],
        "relationships": [{"entity": "Bank of Australasia", "relationship": "DESCENDED_FROM", "note": "1835 Bank of Australasia is ANZ's oldest predecessor institution"}, {"entity": "Mike Smith", "relationship": "ASIAN_STRATEGY_UNDER", "note": "Smith's 2007-2016 leadership drove ANZ's Asia positioning as most internationally connected Australian bank"}, {"entity": "Suncorp Bank", "relationship": "ACQUIRED", "note": "2023 AUD 4.9 billion Suncorp acquisition — largest Australian banking consolidation in decades"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "ANZ — descending from a London-founded colonial bank that financed Australian settlement, grown into a trillion-dollar institution, and now pursuing Asia's banking opportunities — traces the entire arc of Australian economic development from British colonial wool exports to 21st-century Indo-Pacific trade finance.", "significanceCategory": "regional"},
    }),
    ("british-south-africa-company", {
        "summary": "The British South Africa Company (BSAC), founded 1889 and chartered by Royal Charter in 1889 by Cecil Rhodes (Prime Minister of the Cape Colony), governed the territories of Rhodesia (present-day Zimbabwe and Zambia) from 1890 to 1923-1924 — one of the last and most extensive examples of a private company exercising governmental sovereignty over occupied territory in the colonial era. The BSAC's Pioneer Column (1890) conquered Matabeleland and Mashonaland; Rhodes's personal ambition to build a 'Cape-to-Cairo' British corridor through Africa drove the company's territorial expansion.\n\nCecil Rhodes — already controller of De Beers (90% of world's diamond production) and Consolidated Gold Fields — obtained the Royal Charter to govern 'Zambesia' (named Rhodesia after him). The BSAC's Pioneer Column (1890) — 200 settlers and 500 police — occupied Mashonaland (modern Zimbabwe) without treaty with the Ndebele or Shona peoples. The First and Second Matabele Wars (1893, 1896-97) — including the Ndebele Uprising (Umvukela) and Shona Rising — suppressed indigenous resistance at the cost of thousands of lives.\n\nThe BSAC governed Rhodesia (Northern and Southern) for 34 years, raising taxes, distributing land to white settlers, and running railways and mines. Southern Rhodesia became a self-governing British colony (1923); Northern Rhodesia became a Crown Protectorate (1924) — ending BSAC governance. Rhodes's Cape-to-Cairo railway ambition was never completed. The territories became Zimbabwe and Zambia at independence (1965/1980 and 1964). The Jameson Raid (1895-1896) — BSAC-supported attempt to overthrow the Transvaal Republic — was a foreign policy disaster.",
        "causes": ["1889 Cecil Rhodes Royal Charter founding to colonize and govern Zambesia territories", "1890 Pioneer Column occupation of Mashonaland without indigenous treaty", "1893-1896 Matabele Wars suppressing Ndebele and Shona resistance to colonial occupation", "1923-1924 handover to Crown governance ending private company territorial rule"],
        "effects": ["34 years of private company governance over Rhodesia (Zimbabwe/Zambia) territories", "White settler land distribution creating racial land inequality lasting through 21st century", "Rhodes's Cape-to-Cairo ambition driving infrastructure (railways, telegraph) across sub-Saharan Africa", "Jameson Raid political scandal contributing to Cecil Rhodes's political downfall and Boer War tensions"],
        "relationships": [{"entity": "Cecil Rhodes", "relationship": "FOUNDED_BY", "note": "Rhodes obtained 1889 Royal Charter; Rhodesia named after him; company was vehicle for his Cape-to-Cairo ambition"}, {"entity": "Matabele Wars", "relationship": "CONDUCTED_COLONIAL_WARS", "note": "BSAC's 1893 and 1896-97 Matabele Wars suppressed Ndebele and Shona resistance at thousands of lives"}, {"entity": "Zimbabwe", "relationship": "COLONIAL_PREDECESSOR_OF", "note": "BSAC governance of Southern Rhodesia was colonial predecessor of independent Zimbabwe (1980)"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The British South Africa Company — governing Zimbabwe and Zambia as a private company for 34 years — is the last major instance of corporate colonial sovereignty, and its land distribution policies created racial inequalities that shaped Zimbabwean and Zambian politics through the 21st century, including Zimbabwe's land reform crisis.", "significanceCategory": "world-changing"},
    }),
    ("sumitomo-mitsui-financial-group", {
        "summary": "Sumitomo Mitsui Financial Group (SMFG), formed 2002 through the merger of Sumitomo Bank and Sakura Bank (itself descended from Mitsui Bank, founded 1876), is Japan's second-largest banking group by total assets (¥260 trillion+) — a successor institution to two of Japan's most ancient commercial dynasties, Sumitomo (founded 1590 as a copper smelting business by Masatomo Sumitomo) and Mitsui (founded 1673 as a kimono and money exchange business). SMFG thus unites two zaibatsu-era trading empires whose commercial origins predate the Meiji industrialization by centuries.\n\nSumitomo origins: Masatomo Sumitomo founded the company in Kyoto in 1590 initially as a medicine and book shop; his brother-in-law Riemon Soga developed the Nanban-buki copper smelting technique (refining copper from silver content) that became Sumitomo's foundational business. The Sumitomo copper mines at Besshi (founded 1691) operated for 283 years. Sumitomo became one of Japan's four great zaibatsu (alongside Mitsui, Mitsubishi, Yasuda).\n\nMitsui origins: the Mitsui-gumi was founded by Hachirobei Mitsui in 1673, opening dry goods stores in Edo and Kyoto, then pioneering the customer-pays-cash, fixed-price retail model — a retail innovation that became standard. Mitsui Bank (1876) was Japan's first private bank. Both Sumitomo and Mitsui zaibatsu were dissolved under American occupation (1947-1952) and reconstituted as keiretsu. SMFG's 2020 acquisition of 4.9% of Jefferies Group (US investment bank) and its 2023 stake in SBI Holdings represent major international diversification.",
        "causes": ["1590 Sumitomo founding as copper smelting empire; 1673 Mitsui founding as retail and banking pioneer", "Meiji industrialization transforming zaibatsu into modern banking and industrial conglomerates", "Post-WWII zaibatsu dissolution and keiretsu reconstitution under American occupation", "2002 merger of Sumitomo Bank and Sakura Bank creating SMFG"],
        "effects": ["¥260 trillion+ assets making SMFG Japan's second-largest banking group", "Union of two 400-year-old Japanese commercial dynasties in single financial institution", "2020 Jefferies stake and 2023 SBI Holdings stake representing international banking diversification", "Besshi copper mine operation for 283 years as one of Japan's longest industrial operations"],
        "relationships": [{"entity": "Masatomo Sumitomo", "relationship": "FOUNDED_BY_ANCESTOR", "note": "Sumitomo's 1590 founding by Masatomo is SMFG's oldest institutional ancestor"}, {"entity": "Mitsui Group", "relationship": "MERGED_WITH", "note": "Mitsui Bank (1876) lineage through Sakura Bank merged with Sumitomo Bank to form SMFG in 2002"}, {"entity": "Zaibatsu Dissolution", "relationship": "DISSOLVED_AND_RECONSTITUTED", "note": "Both Sumitomo and Mitsui zaibatsu dissolved 1947-1952 and reconstituted as keiretsu before merging"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Sumitomo Mitsui Financial Group — uniting two of Japan's most ancient commercial dynasties (Sumitomo 1590, Mitsui 1673) in a single bank — is the institutional embodiment of Japanese commercial capitalism's 400-year continuity from Edo-period copper smelting and kimono retail to 21st-century global investment banking.", "significanceCategory": "continental"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 98 — Class 330 Companies VI")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
