#!/usr/bin/env python3
"""Batch 137 — Class 340 Religious Orgs VI: Eastern European & Orthodox Churches (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/340-Class-340"
FILE_PREFIX = "340"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("baptist-union-of-romania", {
        "summary": "The Baptist Union of Romania (Romanian: Uniunea Bisericilor Creștine Baptiste din România) is one of Romania's largest Protestant denominations, with roots in German and Swiss Baptist missions of the 1860s-1870s — developing into a significant religious community that faced severe persecution under Romanian Communist rule (1947-1989) while growing remarkably in the post-Communist era to become one of Eastern Europe's most vibrant Baptist movements, with the Romanian diaspora carrying the faith to Western Europe and beyond.\n\nRomanian Baptists' history under Communist persecution is one of the most compelling chapters of 20th-century church history: the Communist regime (following its 1947 seizure of power) attempted to control, suppress, and ultimately eliminate independent religious organizations. Romanian Baptists, whose evangelical faith made them particularly resistant to state religious compromise, faced systematic imprisonment of pastors, harassment of congregations, banning of religious education, and restrictions on church buildings. The faith grew nonetheless — partly because persecution galvanized commitment.\n\nAfter Romania's 1989 revolution (in which Romanian evangelical Christians, particularly in Timișoara, played a significant early role — the December 1989 confrontation began around the defense of the Reformed pastor László Tőkés), Baptist and evangelical churches experienced explosive growth. The Baptist Union grew dramatically through the 1990s-2000s, with Romanian Baptists becoming among Europe's most active evangelists and church planters, sending missionaries across Europe and to other continents.",
        "causes": ["German and Swiss Baptist missions in Romania (1860s-1870s) establishing the Baptist community", "Romanian Baptist community's resistance to Communist religious control growing the church through persecution", "1989 Romanian Revolution with evangelical Christian participation creating conditions for post-Communist religious revival", "Romanian diaspora migration to Western Europe creating dynamic Romanian Baptist presence across Europe"],
        "effects": ["Romanian Baptist Union as one of Eastern Europe's largest and most dynamic Protestant denominations", "Baptist community's Communist-era resilience documented as a case study of church growth under persecution", "Post-1989 church planting explosion making Romanian Baptists major evangelists in Eastern and Western Europe", "Romanian Baptist diaspora establishing new Baptist communities across Western Europe and beyond"],
        "relationships": [{"entity": "Romanian Communism", "relationship": "CHURCH_GROWN_THROUGH_PERSECUTION_UNDER", "note": "Romanian Baptists faced severe Communist persecution but grew nonetheless, emerging dramatically after 1989"}, {"entity": "1989 Romanian Revolution", "relationship": "EVANGELICAL_CHRISTIANS_PARTICIPATING_IN_EARLY_STAGES_OF", "note": "Romanian evangelical Christians, including those around pastor László Tőkés, played roles in the December 1989 Revolution"}, {"entity": "Eastern European Evangelicalism", "relationship": "ONE_OF_MOST_VIBRANT_AND_INFLUENTIAL_COMPONENTS_OF", "note": "Romanian Baptists are among Eastern Europe's most dynamic evangelical movements, planting churches across the continent"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Baptist Union of Romania — growing through Communist persecution to become one of Eastern Europe's most dynamic Protestant movements, connected to the 1989 Revolution, sending missionaries across Europe — is historically significant as a monument to religious resilience and post-Communist evangelical revival.", "significanceCategory": "world-changing"},
    }),
    ("baptist-union-of-wales", {
        "summary": "The Baptist Union of Wales (Welsh: Undeb Bedyddwyr Cymru) is one of Wales's most historically significant religious bodies, rooted in the Welsh Baptist tradition that began with the 1649 founding of the first Welsh-language Baptist congregation (Ilston, Gower Peninsula) and developed through the transformative Welsh religious revivals of the 18th and 19th centuries — particularly the 1859 Revival and the 1904-1905 Welsh Revival led by Evan Roberts, one of the most remarkable religious events in modern Christian history.\n\nThe 1904-1905 Welsh Revival is one of the most documented and debated events in 20th-century Christian history: within months of beginning, approximately 100,000 people were reported to have converted across Wales (in a country of approximately 1.5 million at the time — roughly 7% of the population). The revival spread internationally, influencing Pentecostalism's emergence (the Azusa Street Revival of 1906 in Los Angeles was influenced by the Welsh Revival), and transformed Welsh social life — reports of decreased alcohol consumption, crime reduction, and the conversion of prominent miners becoming prevalent.\n\nWales's distinctive Baptist tradition operates primarily in the Welsh language, making the Baptist Union of Wales an important institution for Welsh language preservation and cultural identity. Welsh-language Baptist congregations have been centers of Welsh-language literacy, singing (the Welsh male voice choir tradition emerged partly from Nonconformist chapel culture), and cultural life for over 350 years.",
        "causes": ["1649 founding of first Welsh-language Baptist congregation at Ilston establishing the tradition", "18th-19th century Welsh Nonconformist revivals dramatically expanding Baptist membership in Wales", "1904-1905 Evan Roberts Revival achieving mass conversion and international influence from Wales", "Welsh language preservation requiring Welsh-medium Baptist congregations as cultural identity anchors"],
        "effects": ["Baptist Union as major component of Welsh Nonconformist tradition that shaped Welsh cultural identity", "1904-1905 Revival influencing Pentecostalism's global emergence through its international spread", "Welsh-language Baptist congregations preserving Welsh language through hymn-singing and Biblical literacy", "Welsh male voice choir tradition emerging partly from Nonconformist chapel singing culture"],
        "relationships": [{"entity": "1904-1905 Welsh Revival", "relationship": "BAPTIST_TRADITION_CENTRAL_TO_GLOBALLY_INFLUENTIAL", "note": "The 1904-1905 Revival emerging partly from Welsh Baptist and Nonconformist culture influenced global Pentecostalism"}, {"entity": "Welsh Language", "relationship": "PRESERVATION_INSTITUTION_FOR_WELSH-LANGUAGE_RELIGIOUS_CULTURE", "note": "Welsh-language Baptist congregations have been Welsh language preservation centers for 350+ years"}, {"entity": "Global Pentecostalism", "relationship": "WELSH_REVIVAL_INFLUENCING_EMERGENCE_OF", "note": "The Welsh Revival influenced the 1906 Azusa Street Revival, connecting Welsh Baptism to global Pentecostalism's origins"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Baptist Union of Wales — tradition of the 1904-1905 Revival that influenced global Pentecostalism, guardians of Welsh-language chapel culture — is historically significant as a monument to one of modern Christianity's most remarkable mass conversion events and Welsh cultural preservation.", "significanceCategory": "world-changing"},
    }),
    ("belarusian-autocephalous-orthodox-church", {
        "summary": "The Belarusian Autocephalous Orthodox Church (BAOC, Belarusian: Беларуская аўтакефальная праваслаўная царква) is a non-recognized Orthodox Christian denomination that emerged from the aspiration for an independent (autocephalous) Belarusian Orthodox Church distinct from the Russian Orthodox Church — an aspiration that has repeatedly manifested during periods of Belarusian national consciousness: in the 1920s during the brief Belarusian Democratic Republic period, during the German occupation of WWII, and in the post-Soviet independence period.\n\nBelarusian Orthodox ecclesiastical independence is both a religious and national identity question: the Russian Orthodox Church (Moscow Patriarchate) has historically administered the Belarusian Orthodox Church as an exarchate (the Belarusian Exarchate of the Russian Orthodox Church), reflecting both the Russian Orthodox Church's imperial legacy and Belarus's long political union with Russia. Advocates for the BAOC argue that an autocephalous Belarusian church would better serve Belarusian national and cultural identity.\n\nThe BAOC has operated primarily in the Belarusian diaspora (in the United States, Canada, and Western Europe) since the WWII period when some Belarusian clergy established autocephalous institutions in exile. In Belarus itself, the Russian Orthodox Church's Belarusian Exarchate remains the dominant Orthodox body, and the BAOC has limited legal recognition. The question of Belarusian Orthodox autocephaly has taken on additional urgency following the 2022 Russian invasion of Ukraine and the Ukrainian Orthodox Church's 2019 grant of autocephaly — a precedent that Belarusian independence advocates cite.",
        "causes": ["Belarusian national consciousness requiring independent Orthodox church distinct from Russian Orthodox Church", "Brief Belarusian Democratic Republic (1918) creating context for autocephalous church aspiration", "WWII period Belarusian diaspora establishing autocephalous institutions outside Russian Orthodox Church control", "Ukrainian Orthodox autocephaly (2019) providing precedent that Belarusian independence advocates cite"],
        "effects": ["BAOC operating primarily in Belarusian diaspora as church of Belarusian national identity in exile", "Russian Orthodox Church's Belarusian Exarchate maintaining dominant Orthodox position within Belarus", "Belarusian national identity question connected to Orthodox ecclesiastical independence in post-Soviet era", "2022 Russian-Ukraine war increasing BAOC's symbolic relevance as Belarusian autocephaly advocates"],
        "relationships": [{"entity": "Russian Orthodox Church", "relationship": "INDEPENDENT_ALTERNATIVE_TO_BELARUSIAN_EXARCHATE_OF", "note": "The BAOC seeks independence from the Russian Orthodox Church's Belarusian Exarchate"}, {"entity": "Ukrainian Orthodox Autocephaly", "relationship": "PRECEDENT_CITED_BY_ADVOCATES_OF_BELARUSIAN_AUTOCEPHALY", "note": "The 2019 Ukrainian Orthodox Church's autocephaly grant provides a precedent Belarusian independence advocates cite"}, {"entity": "Belarusian Diaspora", "relationship": "PRIMARY_GEOGRAPHIC_BASE_OF_OPERATING_MAINLY_IN", "note": "The BAOC operates primarily among Belarusian diaspora communities in North America and Western Europe"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "The Belarusian Autocephalous Orthodox Church — representing aspirations for Belarusian Orthodox independence from the Russian Church, operating primarily in diaspora — is historically significant as a monument to Belarusian national-religious identity and the tension between Eastern Orthodox national churches.", "significanceCategory": "continental"},
    }),
    ("brazilian-catholic-apostolic-church", {
        "summary": "The Brazilian Catholic Apostolic Church (Portuguese: Igreja Católica Apostólica Brasileira, ICAB), founded in 1945 by ex-Roman Catholic Bishop Carlos Duarte Costa — is Brazil's largest independent Catholic church, representing a permanent schism from the Roman Catholic Church that established an alternative Catholic institution maintaining sacraments, apostolic succession, and liturgy while rejecting papal authority and adopting Brazilian nationalist and social reform orientations.\n\nCarlos Duarte Costa was a Brazilian bishop who became increasingly critical of the Roman Catholic Church's alignment with Brazil's Conservative elites and its silence on social justice issues in the 1930s-1940s. He was excommunicated by Pope Pius XII in 1945 and subsequently founded the ICAB as an independent Catholic church that would prioritize Brazilian national identity, clerical marriage, vernacular worship (before Vatican II), and social justice — several positions that the Vatican II Council eventually adopted for Roman Catholicism.\n\nThe ICAB has grown into a substantial Brazilian institution, claiming hundreds of thousands of members and ordaining both men and women as priests. Its founder's progressive theological positions — vernacular Mass, married clergy, social justice orientation — were remarkably prescient of subsequent Roman Catholic reforms, though the schism was never healed. Brazil's complex Catholic landscape — the world's largest Catholic country (approximately 125 million Catholics) but one where Pentecostalism has grown dramatically — makes the ICAB an interesting case study in Catholic institutional alternatives.",
        "causes": ["Bishop Duarte Costa's progressive social justice theology clashing with conservative Vatican positions in the 1940s", "1945 papal excommunication of Duarte Costa providing the catalyst for founding an independent Catholic church", "Brazilian nationalist sentiment supporting a Brazilian Catholic alternative to Roman authority", "Vernacular worship and married clergy positions requiring institutional alternative to Roman Catholicism"],
        "effects": ["ICAB as Brazil's largest independent Catholic institution with hundreds of thousands of members", "Vernacular Mass and married clergy in ICAB preceding and arguably influencing Vatican II reforms", "Women's ordination in ICAB decades before becoming a major Roman Catholic debate", "Brazilian Catholic landscape complicated by significant independent Catholic alternative"],
        "relationships": [{"entity": "Carlos Duarte Costa", "relationship": "FOUNDED_BY_EXCOMMUNICATED_BISHOP_WHO_CREATED", "note": "Bishop Duarte Costa founded the ICAB in 1945 after papal excommunication, creating Brazil's largest independent Catholic church"}, {"entity": "Roman Catholic Church", "relationship": "INDEPENDENT_SCHISM_FROM_MAINTAINING_CATHOLIC_SACRAMENTS_WITHOUT_PAPAL_AUTHORITY", "note": "ICAB maintains Catholic apostolic succession and sacraments while rejecting Roman papal authority"}, {"entity": "Vatican II", "relationship": "ANTICIPATED_SEVERAL_REFORMS_THAT_WERE_SUBSEQUENTLY_ADOPTED_BY", "note": "ICAB's vernacular Mass and social justice orientation anticipated several positions that Vatican II eventually adopted for Rome"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Brazilian Catholic Apostolic Church — founded in 1945, anticipating Vatican II reforms in vernacular Mass and social justice orientation, growing into Brazil's largest independent Catholic institution — is historically significant as a monument to Catholic reform movements and independent Catholicism in Latin America.", "significanceCategory": "continental"},
    }),
    ("british-orthodox-church", {
        "summary": "The British Orthodox Church (BOC) is a small autocephalous Oriental Orthodox Christian denomination in the United Kingdom under the Coptic Pope of Alexandria — established to provide a home for British Christians drawn to Oriental Orthodox (Coptic) Christianity without requiring them to integrate into the primarily Egyptian Coptic church. The BOC attempts to express Orthodox Christianity through traditional British liturgical and theological heritage while maintaining communion with the Coptic Orthodox Church.\n\nThe British Orthodox Church represents one of several Western Christian attempts to adopt Eastern Orthodox theology and spirituality in a culturally indigenous Western form — a recurring impulse in 20th-century ecumenical history. The founding figures included John Kersey and other Britons who were drawn to the Coptic Orthodox tradition and worked to establish an officially recognized autocephalous church for British Orthodox Christians.\n\nThe BOC's relationship with the Coptic Orthodox Church gives it unusual legitimacy among non-Eastern Orthodox churches seeking Eastern connections: the Coptic Orthodox Church (one of the world's oldest Christian churches, tracing to the apostle Mark in Alexandria, 1st century CE) is fully independent of Rome and Constantinople and has the authority to grant communion and recognition to affiliated churches. The BOC's tiny size (a few hundred to a few thousand members) contrasts with its theological ambition of representing a genuine indigenous British form of Orthodox Christianity.",
        "causes": ["British Christians' attraction to Oriental Orthodox theology and spirituality seeking a culturally indigenous expression", "Coptic Orthodox Church's willingness to extend recognition to a British indigenous Orthodox expression", "Ecumenical movement encouraging exploration of ancient Christian traditions by Western Christians", "20th-century interest in Oriental Orthodox Christianity creating demand for Western-accessible Orthodox institutions"],
        "effects": ["British Orthodox Church providing Coptic-affiliated Orthodox home for British converts to Oriental Christianity", "Indigenous Western Orthodox expression experimenting with the synthesis of British and Oriental Christian traditions", "Coptic-affiliated Western church creating unusual ecumenical bridge between ancient Oriental and Western Christianity", "Small but theologically significant denomination demonstrating interest in ancient Eastern Christianity among Western Christians"],
        "relationships": [{"entity": "Coptic Orthodox Church", "relationship": "AUTOCEPHALOUS_AFFILIATE_OF_UNDER_COPTIC_PATRIARCH_OF_ALEXANDRIA", "note": "The BOC is an autocephalous church under the Coptic Pope of Alexandria, giving it Oriental Orthodox legitimacy"}, {"entity": "Oriental Orthodox Christianity", "relationship": "WESTERN_EXPRESSION_OF_IN_INDIGENOUS_BRITISH_FORM", "note": "The BOC attempts to express Oriental Orthodox (Coptic) Christianity through a culturally British theological and liturgical heritage"}, {"entity": "Western Orthodox Movement", "relationship": "BRITISH_COMPONENT_OF_20TH-CENTURY", "note": "The BOC is part of the broader 20th-century Western Orthodox movement seeking indigenous Western expressions of Eastern Christianity"}],
        "historicalSignificance": {"significanceScore": 4, "significanceNarrative": "The British Orthodox Church — a tiny Coptic-affiliated autocephalous church attempting an indigenous British expression of Oriental Orthodox Christianity — is locally significant as an unusual ecumenical experiment connecting ancient Eastern Christianity to British cultural heritage.", "significanceCategory": "local"},
    }),
    ("celtic-orthodox-church", {
        "summary": "The Celtic Orthodox Church (French: Église Orthodoxe Celtique) is a French-based small Christian denomination that claims continuity with or inspiration from the ancient Celtic Christian tradition of the early medieval British Isles and Gaul — the distinctive form of Christianity practiced in Ireland, Scotland, Wales, Brittany, and Cornwall (5th-8th centuries CE) before the Roman Catholic church's liturgical and canonical uniformity was imposed through the Synod of Whitby (664 CE) and subsequent missions.\n\nCeltic Christianity — the tradition associated with figures like St. Patrick (Ireland), St. Columba (Scotland/Iona), St. David (Wales), St. Brigid (Kildare), and the Irish peregrini (wandering monks who evangelized continental Europe) — is often romanticized as a more decentralized, nature-mystical, and contemplative form of Christianity compared to Roman institutional Christianity. This romanticism has inspired numerous modern church movements claiming Celtic identity, though historians debate how distinct Celtic Christianity actually was from Roman practice.\n\nThe Celtic Orthodox Church's positioning as 'Orthodox' reflects the modern Orthodox-influenced idea that ancient Celtic Christianity, pre-Whitby, was closer to Eastern Orthodox theology than to Roman Catholicism — a claim with some scholarly support (Celtic Christianity lacked papal supremacy, had different Easter dating traditions, had monastic rather than episcopal governance centers) but also significant historical controversy. The movement represents the modern Celtic spirituality revival's institutional expression.",
        "causes": ["Modern Celtic spirituality revival romanticizing pre-Whitby Celtic Christianity as an alternative to Roman Catholicism", "French/Breton interest in Celtic cultural heritage including religious traditions connecting Brittany to the Celtic Christian world", "Orthodox theological framework appealing to those seeking pre-schism ancient Christian identity", "Critique of Roman Catholic institutional Christianity expressed through alternative ancient Christian heritage"],
        "effects": ["Celtic Orthodox Church providing institutional expression for modern Celtic spiritual renewal movement", "Breton/French Celtic cultural identity expressed through religious revival movement", "Historical debates about Celtic Christianity's distinctiveness stimulated by modern Celtic church movements", "Alternative Christian identity offered to those seeking ancient roots outside both Roman Catholicism and mainstream Protestantism"],
        "relationships": [{"entity": "Celtic Christianity", "relationship": "CLAIMS_CONTINUITY_WITH_ANCIENT_PRE-WHITBY_TRADITION_OF", "note": "The Celtic Orthodox Church claims inspiration or continuity with pre-664 CE Celtic Christian tradition"}, {"entity": "Synod of Whitby 664", "relationship": "DEFINES_ITSELF_AGAINST_ROMAN_UNIFORMITY_IMPOSED_AT", "note": "The church positions itself as preserving Celtic practice before the 664 Synod of Whitby imposed Roman liturgical uniformity"}, {"entity": "Modern Celtic Spirituality", "relationship": "INSTITUTIONAL_EXPRESSION_OF_RELIGIOUS_DIMENSION_OF", "note": "The Celtic Orthodox Church represents the institutional religious expression of the modern Celtic cultural and spiritual revival movement"}],
        "historicalSignificance": {"significanceScore": 4, "significanceNarrative": "The Celtic Orthodox Church — claiming continuity with pre-Whitby Celtic Christianity, representing the institutional expression of the modern Celtic spiritual revival — is locally significant as a monument to the enduring fascination with ancient Celtic Christian tradition as an alternative to mainstream Western Christianity.", "significanceCategory": "local"},
    }),
    ("catholic-orthodox-church-of-france", {
        "summary": "The Catholic Orthodox Church of France (French: Église Catholique Orthodoxe de France, ECOF) was a significant 20th-century Western Orthodox church that attempted to create a fully French-language, Western-rite Orthodox liturgical tradition under the canonical umbrella of Eastern Orthodoxy — eventually receiving canonical recognition from the Russian Orthodox Church Outside Russia (ROCOR) and later entering a complex period of jurisdictional dispute that ultimately led to the church's dissolution and its members dispersing to other Orthodox jurisdictions.\n\nThe ECOF's founding inspiration was the work of Fr. Denis (Eugene Fellippe) in the post-WWII period and developed under the leadership of Archbishop Jean (Kovalevsky), who developed a distinctive Western-rite Orthodox liturgy in French combining ancient Gallican and other Western liturgical traditions with Orthodox theology. The project represented an ambitious attempt to demonstrate that Orthodoxy was not culturally tied to Greek, Russian, or other Eastern national traditions but could have an authentic Western expression.\n\nThe ECOF ultimately foundered on jurisdictional disputes — the ambiguity of its canonical status, questions about the validity of its orders, and controversies about its bishops led to a fragmentation that left the church without clear canonical standing. Its dissolution was a significant setback for the Western Orthodox movement, though it produced liturgical resources and theological explorations that continue to influence Western Orthodox experiments. Many former ECOF members moved into the Antiochian Orthodox Church's Western Rite Vicariate.",
        "causes": ["Post-WWII French interest in Orthodox Christianity requiring a French-language Western liturgical expression", "Archbishop Kovalevsky's theological vision of Western-rite Orthodox Christianity rooted in Gallican tradition", "Russian Orthodox Church Outside Russia's openness to canonical reception of Western-rite churches", "Broader Western Orthodox movement seeking indigenous expressions of Orthodox Christianity outside Eastern cultural forms"],
        "effects": ["ECOF developing influential Western-rite Orthodox liturgical resources used in subsequent Western Orthodox experiments", "Jurisdictional disputes and canonical ambiguity ultimately leading to the church's dissolution", "Former ECOF members joining Antiochian Orthodox Western Rite Vicariate and other Orthodox jurisdictions", "Western Orthodox movement advanced and complicated by ECOF's ambitious but ultimately unsuccessful experiment"],
        "relationships": [{"entity": "Western Orthodox Movement", "relationship": "SIGNIFICANT_EXPERIMENT_IN_DEVELOPING_WESTERN-RITE", "note": "ECOF was one of the most ambitious attempts to create an authentic Western-rite Orthodox church in France"}, {"entity": "Russian Orthodox Church Outside Russia", "relationship": "RECEIVED_CANONICAL_RECOGNITION_FROM_BEFORE_DISPUTES", "note": "ROCOR provided canonical recognition to ECOF before subsequent jurisdictional disputes led to dissolution"}, {"entity": "Gallican Christianity", "relationship": "LITURGICAL_FOUNDATION_FOR_WESTERN-RITE_ORTHODOXY_IN_ANCIENT", "note": "ECOF developed Western-rite Orthodox liturgy drawing on ancient Gallican and other pre-Roman Western liturgical traditions"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "The Catholic Orthodox Church of France — an ambitious attempt to create French-language Western-rite Orthodox Christianity, ultimately dissolved through jurisdictional disputes — is historically significant as the most developed experiment in Western Orthodox liturgical tradition and a monument to the challenges of Orthodox canonical diversity.", "significanceCategory": "continental"},
    }),
    ("chaldean-catholic-archdiocese-of-salmas", {
        "summary": "The Chaldean Catholic Archdiocese of Salmas (Urmia) in northwestern Iran is one of the historical dioceses of the Chaldean Catholic Church — the Eastern Catholic church of the ancient Christian community of Mesopotamia and northwestern Persia, descended from the Church of the East that was divided between those who accepted communion with Rome (Chaldean Catholic Church, formal union from 1552) and those who maintained independence (Assyrian Church of the East).\n\nSalmas (now called Shapur and historically part of Azerbaijan, in northwestern Iran near Lake Urmia) was a major center of Assyrian/Chaldean Christian population before WWI. The Urmia (Lake Urmia) region in northwestern Persia had one of the densest concentrations of Assyrian Christian communities anywhere outside Mesopotamia, including both Chaldean Catholics, Assyrian Church of the East members, and other Christian groups. American Presbyterian missionaries established their largest Persian mission in Urmia from the 1830s.\n\nThe Chaldean Catholic community in Salmas was devastated by the Seyfo (Assyrian Genocide) of WWI (1914-1918), during which Ottoman and Kurdish forces killed approximately 250,000-300,000 Assyrian and Chaldean Christians — roughly half the total Assyrian-Chaldean Christian population. The survivors mostly fled to Iraq or the West. The Archdiocese of Salmas today exists primarily as a titular see (a historical diocese without current resident bishop and active congregation) in the Chaldean Catholic Church's jurisdictional structure.",
        "causes": ["Ancient Chaldean Catholic presence in northwestern Persia requiring diocesan ecclesiastical structure", "Salmas area's dense Assyrian and Chaldean Christian population before WWI requiring bishop and archdiocese", "1552 union of part of the Church of the East with Rome creating the Chaldean Catholic Church", "Urmia region's significance to ancient Christianity in Persia requiring formal ecclesiastical recognition"],
        "effects": ["WWI Seyfo Genocide dramatically reducing the Chaldean Christian population requiring the archdiocese to serve", "Post-WWI archdiocese surviving as titular see after the Christian community's decimation and displacement", "Chaldean Catholic ecclesiastical structure maintaining historical continuity with ancient northwestern Persian Christianity", "Archdiocese as testimony to the devastated Chaldean Christian civilization in the Urmia region"],
        "relationships": [{"entity": "Chaldean Catholic Church", "relationship": "HISTORICAL_ARCHDIOCESE_IN_NORTHWESTERN_PERSIA_OF", "note": "The Archdiocese of Salmas is a historical Chaldean Catholic diocese serving the ancient Christian community of the Urmia region"}, {"entity": "Seyfo Genocide", "relationship": "CHRISTIAN_COMMUNITY_DEVASTATED_BY_WWI", "note": "The WWI Seyfo Genocide killed approximately half the Assyrian-Chaldean Christian population, decimating the archdiocese's community"}, {"entity": "Urmia Region", "relationship": "ARCHDIOCESE_SERVING_ANCIENT_CHRISTIAN_COMMUNITIES_OF", "note": "The Urmia/Lake Urmia region of northwestern Persia was one of the densest Assyrian and Chaldean Christian areas before WWI"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Chaldean Catholic Archdiocese of Salmas — serving the ancient Christian communities of northwestern Persia decimated by the WWI Seyfo Genocide — is historically significant as a monument to the ancient Chaldean Christian civilization of Mesopotamia and Persia and its tragic 20th-century destruction.", "significanceCategory": "continental"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 137 — Class 340 Religious Orgs VI: Eastern European & Orthodox Churches")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
