#!/usr/bin/env python3
"""Batch 55 — Class 330 Airlines, Telecom & Auto (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/330-Class-330"
FILE_PREFIX = "330"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("british-airways", {
        "summary": "British Airways plc is the flag carrier airline of the United Kingdom, founded in 1974 through the merger of British European Airways and British Overseas Airways Corporation. Operating from London Heathrow, the world's busiest international airport, it serves 170+ destinations across 80 countries and is one of the oldest airlines in the world.\n\nBritish Airways operated Concorde — the world's only commercial supersonic aircraft — from 1976 to 2003, carrying passengers across the Atlantic at Mach 2 in under three and a half hours, a luxury experience that defined a golden age of aviation glamour. The airline's 1987 privatization under Margaret Thatcher's government became a landmark in the global wave of state airline privatizations.\n\nBritish Airways' parent International Airlines Group (IAG), formed in 2011 with Iberia of Spain, also acquired Vueling and Aer Lingus, creating one of Europe's largest aviation groups. The airline suffered profound crises including the 2008 global financial shock, 2010 strike disruptions, a massive 2018 IT failure, a data breach exposing 500,000 customer records (£20 million GDPR fine), and the catastrophic COVID-19 pandemic causing 12,000 job losses. Its long-haul premium business class remains a benchmark in airline hospitality.",
        "causes": ["UK government consolidation of British European Airways and BOAC in 1974", "Concorde program requiring a national airline to operate the aircraft commercially", "Margaret Thatcher's privatization policy transforming state enterprises to public companies", "Heathrow's hub geography making BA central to North Atlantic travel"],
        "effects": ["Concorde operations created benchmark for luxury supersonic commercial aviation", "1987 privatization became template for global airline privatization wave", "IAG formation created European aviation consolidation model", "COVID pandemic forced restructuring reducing workforce by 30%"],
        "relationships": [{"entity": "International Airlines Group", "relationship": "MEMBER_OF", "note": "Merged with Iberia to form IAG parent company in 2011"}, {"entity": "Concorde", "relationship": "OPERATED", "note": "Flew Concorde on North Atlantic routes 1976-2003"}, {"entity": "Heathrow Airport", "relationship": "HUBS_AT", "note": "Primary hub at world's busiest international airport"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "British Airways shaped commercial aviation through Concorde operations, Thatcher-era privatization, and its role as a cultural ambassador for Britain on the world's busiest international routes.", "significanceCategory": "regional"},
    }),
    ("lufthansa", {
        "summary": "Deutsche Lufthansa AG is the flag carrier of Germany, founded in 1926 with predecessor roots in the Weimar Republic era. Europe's largest airline group by revenue and passengers, the Lufthansa Group encompasses Swiss International Air Lines, Austrian Airlines, Brussels Airlines, Eurowings, and a 40% stake in ITA Airways (Alitalia's successor).\n\nLufthansa was dissolved after WWII as part of Allied restrictions, then re-established in 1953 in West Germany, becoming a symbol of postwar German economic revival. Its MUC (Munich) and FRA (Frankfurt) hubs grew into major European transfer points rivaling Heathrow and Amsterdam. Lufthansa's acquisition strategy — absorbing national carriers of Germany's neighbors — created a Central European aviation empire.\n\nThe COVID-19 pandemic required a €9 billion German government bailout to prevent bankruptcy, making Germany a 25% shareholder temporarily. The German government's reacquisition of a stake mirrored debates globally about strategic industries and state support during crises. Lufthansa's Technik division, one of the world's largest aircraft maintenance providers, and LSG Sky Chefs, the world's largest airline catering company (partially sold), demonstrate vertical integration in aviation beyond passenger services.",
        "causes": ["German commercial aviation ambitions in Weimar Republic era", "Postwar West German economic recovery requiring air transport infrastructure", "European aviation deregulation enabling multi-carrier group consolidation", "Network hub strategy requiring strategic acquisitions of connecting carriers"],
        "effects": ["Frankfurt and Munich grew into major European aviation hubs", "Lufthansa Group created Central European aviation empire through acquisitions", "COVID bailout established German precedent for strategic industry state support", "Lufthansa Technik became global leader in aircraft MRO services"],
        "relationships": [{"entity": "Swiss International Air Lines", "relationship": "ACQUIRED", "note": "2005 acquisition integrated Swiss carrier into Lufthansa Group"}, {"entity": "German federal government", "relationship": "BAILED_OUT_BY", "note": "€9 billion COVID bailout made government temporary 25% shareholder"}, {"entity": "Air France-KLM", "relationship": "COMPETES_WITH", "note": "Rival European airline alliance competing for hub traffic"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "Lufthansa symbolizes German industrial revival and European aviation consolidation, its network spanning Central Europe and its history mirroring Germany's own 20th-century trajectory.", "significanceCategory": "regional"},
    }),
    ("delta-air-lines", {
        "summary": "Delta Air Lines, Inc. is an American airline founded in 1924 as Huff Daland Dusters, a crop-dusting operation in Macon, Georgia, pivoting to passenger service in 1929 after C.E. Woolman's leadership. Today one of the world's largest airlines by revenue, Delta serves over 180 million passengers annually from its Atlanta Hartsfield-Jackson hub, the world's busiest airport by passenger volume.\n\nDelta's 2005 bankruptcy and 2008 emergence, combined with its Northwest Airlines merger, created a transformed carrier that pioneered airline ancillary revenue, SkyMiles loyalty program innovations, and corporate contract reliability. Under CEO Ed Bastian, Delta consistently ranked as the most profitable US airline and one of the most reliable for on-time performance.\n\nDelta's Atlanta hub dominance, its Pacific routes through the former Northwest network, and its premium cabin products (Delta One, Delta Premium Select) repositioned it as the quality leader among US legacy carriers. Its investment in refinery operations (Monroe Energy) to hedge jet fuel costs was an unusual vertical integration move. Delta's response to COVID — booking middle seats empty to maintain spacing — was controversial but built significant customer loyalty. By 2023, Delta's $56 billion revenue made it one of the largest airlines in the world.",
        "causes": ["Boll weevil crop damage creating need for aerial crop-dusting in 1920s South", "Postwar US aviation deregulation enabling route expansion beyond regulated networks", "Hub-and-spoke model making Atlanta nexus for Southeast and national traffic", "Northwest merger creating coast-to-coast and Pacific network integration"],
        "effects": ["Atlanta Hartsfield-Jackson hub drives world's busiest airport development", "Northwest merger created world's largest airline briefly by capacity", "Ancillary revenue and loyalty program model influenced all US airline pricing", "Jet fuel refinery acquisition pioneered unusual airline vertical integration strategy"],
        "relationships": [{"entity": "Northwest Airlines", "relationship": "MERGED_WITH", "note": "2008 merger creating one of world's largest airlines"}, {"entity": "Hartsfield-Jackson Atlanta Airport", "relationship": "HUBS_AT", "note": "Primary hub at world's busiest airport by passenger volume"}, {"entity": "American Airlines", "relationship": "COMPETES_WITH", "note": "US legacy carrier rival competing for domestic and international passengers"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "Delta's transformation from crop-duster to world's most profitable airline exemplifies American aviation's evolution through deregulation, consolidation, and service innovation.", "significanceCategory": "regional"},
    }),
    ("aeroflot", {
        "summary": "Aeroflot — Russian Airlines is the flag carrier of Russia, founded in 1923 as the world's oldest national airline still in continuous operation. Once the world's largest airline in Soviet times, Aeroflot served as the state aviation monopoly connecting the USSR's vast territory and projecting Soviet power internationally.\n\nIn Soviet times, Aeroflot was more than an airline — it was a government ministry operating over 100 aircraft types, employing over 400,000 workers, and maintaining routes to every corner of the USSR's 11 time zones. Its size was extraordinary: in 1976 it carried over 100 million passengers, more than any airline in history at that time. Soviet Aeroflot also functioned as a troop transport and cargo system serving military and government needs.\n\nPost-Soviet Aeroflot shed its regional subsidiaries as Russia's republics formed independent airlines, focusing on international routes from Sheremetyevo Moscow. Its safety record, once abysmal, improved dramatically with fleet modernization using Western Airbus and Boeing aircraft. Russia's 2022 invasion of Ukraine triggered sweeping Western sanctions grounding 500+ aircraft leased from Western lessors, stranding Russia's aviation industry and forcing Aeroflot to rely on domestic Sukhoi Superjet and older aircraft while Western parts dwindled.",
        "causes": ["Soviet Union's vast geographic territory requiring aviation to connect regions", "Communist ideology requiring state control of all transport infrastructure", "Military utility of large aircraft fleet for troop movements", "Prestige of international routes as Cold War soft power projection"],
        "effects": ["USSR's aviation infrastructure connected remote Siberian communities otherwise inaccessible", "Post-1991 breakup created 15 new national carriers from Aeroflot subsidiaries", "2022 sanctions froze 500+ Western aircraft, reshaping Russian aviation economics", "Forced reliance on domestic aircraft accelerated Russian aerospace self-sufficiency drive"],
        "relationships": [{"entity": "Soviet Union", "relationship": "OPERATED_BY", "note": "Functioned as state aviation ministry under Soviet government for 70 years"}, {"entity": "Russian government", "relationship": "OWNED_BY", "note": "Majority state-owned enterprise with Kremlin-linked management"}, {"entity": "Sheremetyevo Airport", "relationship": "HUBS_AT", "note": "Primary hub at Moscow Sheremetyevo International Airport"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Aeroflot served as the Soviet Union's aviation lifeline, connecting an empire spanning 11 time zones, and its post-2022 crisis exposed the deep dependencies of Russian aviation on Western aerospace technology.", "significanceCategory": "continental"},
    }),
    ("air-canada", {
        "summary": "Air Canada is the flag carrier and largest airline of Canada, founded in 1937 as Trans-Canada Air Lines. Operating from hubs in Toronto Pearson, Montreal Trudeau, and Vancouver, it serves over 50 million passengers annually on routes spanning six continents, with particular strength in transatlantic and transpacific routes.\n\nAir Canada's privatization in 1988 and subsequent 2003 bankruptcy and emergence under restructuring created a leaner carrier that absorbed Canadian Airlines International in 2000, eliminating domestic competition. The SARS outbreak in 2003, 9/11 in 2001, and COVID-19 in 2020 each created severe crises requiring government support and restructuring. Air Canada received C$5.9 billion in COVID aid in 2021.\n\nAir Canada's bilingual operations, serving both English and French Canadian communities as a national requirement, reflect Canada's unique linguistic duality. Its Air Canada Rouge leisure subsidiary and Aeroplan loyalty program (spun off and reacquired) reflect modern airline revenue diversification. The airline's Dreamliner-heavy fleet positioned it for fuel-efficient long-haul expansion. Despite crises, Air Canada maintains Canada's connectivity to global markets and serves as a strategic national infrastructure company.",
        "causes": ["Canadian government need for national aviation coverage across vast territory", "Postwar Canadian industrial development requiring efficient air transport", "1988 privatization as part of Canadian deregulation and market liberalization", "Trans-Canada geography requiring aircraft for coast-to-coast service"],
        "effects": ["National aviation network connected Canada's far-flung communities and provinces", "2000 Canadian Airlines merger eliminated domestic competition temporarily", "COVID support deal maintained air connectivity during pandemic isolation", "Bilingual operations remain requirement reflecting Canada's linguistic duality"],
        "relationships": [{"entity": "Government of Canada", "relationship": "REGULATED_BY", "note": "Bilingual requirements and strategic national carrier status under federal oversight"}, {"entity": "Canadian Airlines International", "relationship": "ACQUIRED", "note": "2000 acquisition eliminated primary domestic rival"}, {"entity": "Toronto Pearson Airport", "relationship": "HUBS_AT", "note": "Primary hub at Canada's busiest international airport"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "Air Canada connects Canada's vast geography as the national carrier, serving both official languages and maintaining international connectivity essential for Canada's economy and identity.", "significanceCategory": "regional"},
    }),
    ("american-airlines", {
        "summary": "American Airlines Group, Inc. is an American airline holding company founded in 1934, historically tracing to 1930 through Charles Lindbergh's design of transcontinental routes for predecessor operators. The world's largest airline by passengers carried multiple times, American operates from hubs in Dallas-Fort Worth, Miami, Charlotte, Chicago, Philadelphia, and New York JFK.\n\nAmerican pioneered frequent flyer programs with AAdvantage in 1981, the world's first airline loyalty program, which transformed the travel industry by creating customer lock-in through accumulated points and miles. American's Sabre computerized reservation system, developed in the 1950s-60s in partnership with IBM, became the world's dominant airline booking platform, spun off as an independent technology company. These innovations shaped all commercial aviation marketing and distribution.\n\nAmerican's 2011-2013 bankruptcy was the largest airline bankruptcy in history, completed through restructuring and a 2013 merger with US Airways creating the current company. Despite its size, American struggled with profitability relative to Delta and United in the 2010s-2020s, burdened by debt and operational challenges. Its merger with US Airways created a coast-to-coast network with significant Caribbean and Latin American reach through Miami hub.",
        "causes": ["US airmail contracts providing seed revenue for early commercial aviation", "Transcontinental route development requiring hub-and-spoke organizational structure", "Postwar US commercial aviation deregulation enabling aggressive expansion", "Sabre technology investment enabling yield management and price optimization"],
        "effects": ["AAdvantage (1981) created the global airline loyalty program model", "Sabre reservation system shaped global travel distribution for decades", "US Airways merger created world's largest airline by passengers briefly", "Loyalty miles became alternative currency valued at hundreds of billions"],
        "relationships": [{"entity": "US Airways", "relationship": "MERGED_WITH", "note": "2013 merger created current American Airlines Group"}, {"entity": "Sabre Corporation", "relationship": "FOUNDED", "note": "Founded Sabre computerized reservations system in partnership with IBM"}, {"entity": "Delta Air Lines", "relationship": "COMPETES_WITH", "note": "Primary domestic and international rival in US aviation market"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "American Airlines invented the frequent flyer loyalty program and computerized reservation system, two innovations that transformed how airlines market and how passengers choose travel globally.", "significanceCategory": "world-changing"},
    }),
    ("att", {
        "summary": "AT&T Inc. is an American multinational telecommunications conglomerate headquartered in Dallas, Texas, tracing its origins to Alexander Graham Bell's telephone patent of 1876 and the American Telephone & Telegraph Company founded in 1885. Once the world's largest company and the sole provider of telephone service across much of the United States, AT&T's history spans the entire arc of modern telecommunications.\n\nThe Bell System's 1956 Consent Decree and 1982 antitrust breakup into seven 'Baby Bell' regional companies was the largest corporate breakup in American history, creating independent telecommunications companies across US regions. The reconsolidation of AT&T through acquisitions of SBC Communications (2005) and BellSouth (2006) essentially reassembled much of the original Bell System. AT&T then diversified into satellite TV (DirecTV, 2015) and entertainment through the $85 billion Time Warner acquisition (2018, renamed WarnerMedia), before spinning off WarnerMedia in 2022.\n\nAT&T's Bell Laboratories, operating 1925-1996, was the most productive industrial research laboratory in history: transistors, lasers, solar cells, cellular networks, UNIX operating system, C programming language, and information theory all emerged from Bell Labs. The lab's innovations created the digital age before AT&T's antitrust breakup scattered its researchers.",
        "causes": ["Alexander Graham Bell's 1876 telephone patent creating monopoly communications infrastructure", "Universal service obligation requiring national telephone connectivity", "Antitrust enforcement breaking up monopoly into regional competitors", "Digital convergence of telecommunications and media requiring content ownership"],
        "effects": ["Bell Labs produced transistors, lasers, and information theory defining digital age", "1982 antitrust breakup created modern competitive telecommunications landscape", "AT&T's 5G network deployment reshaped US mobile communications infrastructure", "WarnerMedia merger and split demonstrated telecoms' failed media diversification strategy"],
        "relationships": [{"entity": "Alexander Graham Bell", "relationship": "FOUNDED_BY_LINEAGE", "note": "AT&T evolved from Bell's 1885 American Telephone & Telegraph Company"}, {"entity": "Bell Laboratories", "relationship": "OPERATED", "note": "Research arm that produced transistors, lasers, UNIX, and C language"}, {"entity": "US Department of Justice", "relationship": "BROKEN_UP_BY", "note": "1982 antitrust consent decree broke AT&T into seven Baby Bells"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "AT&T's Bell Labs invented the transistor and created the information age's foundation, while AT&T itself defined and then dominated American telecommunications for over a century.", "significanceCategory": "world-changing"},
    }),
    ("audi-ag", {
        "summary": "Audi AG is a German automobile manufacturer headquartered in Ingolstadt, Bavaria, founded in 1909 by August Horch after he left Horch (later merged into Auto Union). Part of the Volkswagen Group, Audi operates as the premium/luxury segment brand alongside Lamborghini, Bentley, and Porsche, representing German engineering excellence in the global luxury automobile market.\n\nAudi's iconic four-ring logo represents the merger of four companies — Audi, Horch, DKW, and Wanderer — into Auto Union in 1932, a conglomerate that produced Silver Arrow Grand Prix racing cars that challenged Mercedes-Benz's dominance in 1930s motorsport. Postwar Audi was reestablished in West Germany and joined the Volkswagen Group in the 1960s, beginning a transformation into a premium brand.\n\nAudi's 1980 Quattro permanent four-wheel drive system, first demonstrated in the Audi Quattro rally car, revolutionized automotive traction control and launched an entirely new segment of performance all-wheel-drive vehicles. The Quattro's dominance in World Rally Championship, including Walter Röhrl's victories, created the brand association with dynamic safety that persists. Audi's contemporary lineup, including the e-tron and Q8 e-tron electric vehicles, and its Le Mans endurance racing dominance with the diesel-powered R10 (2006-2008), demonstrate technological breadth.",
        "causes": ["August Horch's second founding in Zwickau after leaving his original company", "Auto Union merger consolidating Saxon automotive industry during Depression", "Volkswagen Group strategy requiring premium brand to compete with BMW and Mercedes", "Consumer demand for performance cars combining luxury with practical all-weather capability"],
        "effects": ["Quattro all-wheel-drive system revolutionized performance car handling and safety", "Auto Union Silver Arrow dominated 1930s Grand Prix racing as Nazi prestige project", "Audi Le Mans diesel victories validated efficiency technology for performance cars", "Four-ring logo became globally recognized premium automotive brand symbol"],
        "relationships": [{"entity": "Volkswagen Group", "relationship": "OWNED_BY", "note": "Subsidiary of Volkswagen Group as premium luxury segment brand"}, {"entity": "August Horch", "relationship": "FOUNDED_BY", "note": "Founded as Audi in 1909, the Latin translation of his German surname"}, {"entity": "BMW", "relationship": "COMPETES_WITH", "note": "German premium rival in global luxury and performance automobile market"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "Audi's Quattro all-wheel-drive system and Auto Union racing heritage represent German automotive engineering innovation, while its evolution within VW Group demonstrates premium brand strategy in global automotive markets.", "significanceCategory": "regional"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 55 — Class 330 Airlines, Telecom & Auto")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
