#!/usr/bin/env python3
"""Batch 129 — MIXED 363(5)+361(3): Opera Houses + Museums (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER_363 = "data/appwrite-export/entities/363-Class-363"
FOLDER_361 = "data/appwrite-export/entities/361-Class-361"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("coliseum", {
        "summary": "The Coliseum (also spelled Colosseum) in Rome is the largest ancient amphitheater ever built — an iconic symbol of the Roman Empire's engineering genius, military power, and cultural values, constructed under the Flavian emperors (Vespasian began construction circa 72 CE, completed by Titus 80 CE, with later additions by Domitian) to accommodate approximately 50,000-80,000 spectators for gladiatorial combat, venationes (animal hunts), public executions, and theatrical spectacles. It is one of the New Seven Wonders of the World and among the world's most visited tourist sites.\n\nThe Colosseum's construction was made possible by the spoils of the Jewish War (66-73 CE), including the sacking of the Temple in Jerusalem (70 CE) by Titus — Jewish slaves (according to tradition, up to 100,000) reportedly provided much of the construction labor. The structure's concrete and stone construction, its sophisticated seating stratification (different sections for senators, knights, plebeians, and women), its underground hypogeum (animal and gladiator storage tunnels), and its awning system (velarium) for shade demonstrate extraordinary Roman engineering.\n\nThe gladiatorial games held at the Colosseum were fundamental to Roman cultural life — not merely entertainment but civic ritual, imperial propaganda, and the expression of Roman values around courage, death, and social hierarchy. The games continued for centuries before gradually declining in the 5th century CE. Medieval Rome used the Colosseum as a fortress, then a quarry for building material — much of the original marble and travertine was removed for medieval church and palace construction. It became a Christian pilgrimage site associated with early Christian martyrdom (though the historical evidence for mass Christian martyrdom there is debated).",
        "causes": ["Flavian emperors' political need for a public gift to Rome's populace following Nero's private Domus Aurea seizure of public land", "Jewish War spoils and slave labor funding and enabling the extraordinary construction program", "Roman cultural tradition of gladiatorial games as civic ritual requiring purpose-built amphitheater of maximum scale", "Flavian dynasty's legitimacy-building requiring the grandest public entertainment complex in history"],
        "effects": ["50,000-80,000 capacity amphitheater demonstrating Roman concrete and engineering at their most ambitious scale", "Gladiatorial games and venationes as civic ritual documenting Roman cultural values around death, courage, and entertainment", "Medieval quarrying removing much original marble leaving the ruined grandeur that became an Enlightenment symbol of fallen Rome", "Modern symbol of Rome and Italy recognized as one of the New Seven Wonders with 6+ million annual visitors"],
        "relationships": [{"entity": "Vespasian", "relationship": "CONSTRUCTION_BEGUN_BY_FLAVIAN_EMPEROR", "note": "Vespasian began Colosseum construction circa 72 CE using Jewish War spoils and slave labor"}, {"entity": "Roman Gladiatorial Games", "relationship": "PRIMARY_VENUE_FOR_CENTURIES_OF", "note": "The Colosseum was the premier venue for gladiatorial combat, venationes, and public spectacle in Roman civic life"}, {"entity": "Roman Empire", "relationship": "MOST_ICONIC_ENGINEERING_MONUMENT_OF", "note": "The Colosseum is the single most recognizable symbol of Roman imperial power and engineering achievement"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Roman Colosseum — the largest ancient amphitheater, built with Jewish War spoils, venue of gladiatorial combat for centuries, and one of the world's most recognized monuments — is among the most historically significant structures in human history, embodying Roman imperial civilization, engineering, and cultural values.", "significanceCategory": "world-changing"},
    }, FOLDER_363, "363"),
    ("donetsk-state-academic-opera-and-ballet-theatre", {
        "summary": "The Donetsk State Academic Opera and Ballet Theatre, founded in 1932 in Donetsk (formerly Stalino, then Donetsk), Ukraine — one of the major opera and ballet companies of Ukraine, situated in the industrial Donbas region — is historically significant both as a major cultural institution of Soviet-era industrial Ukraine and as a monument now tragically caught at the epicenter of the Russo-Ukrainian War (2014-present), with Donetsk under Russian-backed separatist control since 2014 and the theater's status representing the broader cultural destruction of the conflict.\n\nDonetsk (known as Stalino under Stalin, renamed Donetsk in 1961) was developed as the industrial capital of the Donbas coal and steel region — one of the Soviet Union's most productive industrial areas. Soviet cultural policy invested heavily in creating cultural infrastructure for the industrial workers, including the opera and ballet theater that was a flagship institution of Donbas Soviet culture. The theater presented opera and ballet in both Russian and Ukrainian, reflecting the bilingual character of the Donbas region.\n\nThe 2014 Russian-backed separatist takeover of Donetsk transformed the theater's situation: Ukrainian cultural institutions in the occupied territories were faced with impossible choices about identity, language policy, and institutional loyalty. The theater continued to operate under the Donetsk People's Republic (DNR), and with the escalation of the Russo-Ukrainian War after Russia's 2022 full-scale invasion, Donetsk's cultural institutions became symbols of the broader cultural dimension of the conflict — Russian claims of 'protecting Russian-speakers' versus Ukrainian claims of cultural rights in the Donbas.",
        "causes": ["Soviet cultural policy creating flagship opera company for the Donbas industrial region's workers", "Donetsk's industrial development under Stalin requiring cultural institutions to demonstrate socialist cultural achievement", "Donbas bilingual character (Russian and Ukrainian) creating complex cultural identity for the theater", "2014 Russian-backed separatist takeover of Donetsk forcing the theater into the conflict's cultural dimension"],
        "effects": ["Donetsk Opera as symbol of Soviet Donbas industrial culture and worker-oriented performing arts investment", "Post-2014 operation under DNR control representing the cultural dimension of the Russo-Ukrainian conflict", "Theater's continuation documenting Russian cultural policy in occupied Ukrainian territories", "Donbas cultural institutions caught in the conflict between Ukrainian and Russian cultural claims"],
        "relationships": [{"entity": "Donbas", "relationship": "FLAGSHIP_CULTURAL_INSTITUTION_OF_INDUSTRIAL_REGION_OF", "note": "The theater was built as the primary performing arts center for Soviet Ukraine's most productive industrial region"}, {"entity": "Russo-Ukrainian War", "relationship": "CULTURAL_INSTITUTION_CAUGHT_AT_EPICENTER_OF", "note": "Donetsk's 2014 separatist takeover placed the theater in the cultural dimension of the Russo-Ukrainian conflict"}, {"entity": "Soviet Cultural Policy", "relationship": "FOUNDED_UNDER_WORKER-CULTURE_PROGRAM_OF", "note": "The theater was created under Soviet policy of providing cultural institutions for the industrial working class"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Donetsk State Opera and Ballet Theatre — a major Soviet-era cultural institution of Ukraine's industrial Donbas, now caught at the epicenter of the Russo-Ukrainian War and representing the cultural dimension of the conflict over Ukrainian identity — is historically significant both for its Soviet heritage and its tragic contemporary relevance.", "significanceCategory": "continental"},
    }, FOLDER_363, "363"),
    ("egyptian-royal-opera-house", {
        "summary": "The Egyptian Royal Opera House (Khedivial Opera House, Arabic: دار الأوبرا الخديوية) in Cairo, built in 1869 to celebrate the opening of the Suez Canal, was one of the most historically significant opera houses in the world — inaugurated with Rigoletto (originally Verdi was commissioned to write Aida specifically for the new opera house and the canal opening, but it was not ready; Aida premiered there in 1871) — representing the Khedive Ismail's extraordinary Westernization project for Egypt and the 'opening of Egypt to civilization' that the canal symbolized. The opera house burned down in 1971 and was replaced by the modern Cairo Opera House (1988).\n\nKhedive Ismail's Egypt (1863-1879) was engaged in a massive modernization project: building the Suez Canal (completed 1869), developing Cairo's European-style quarter (Ismailia), and creating cultural institutions that would signal Egypt's membership in the family of 'civilized nations' — a term that in 19th-century colonial discourse meant adopting European cultural forms. The opera house, designed in Italian Renaissance style, was specifically intended to demonstrate Egypt's cultural equality with European nations during the canal's international inauguration ceremonies.\n\nVerdi's Aida (commissioned for the opening but delayed by the Franco-Prussian War blocking scenery transport, finally premiering in 1871) became one of the most beloved operas in the repertoire. Aida's ancient Egyptian setting and its premiere at the Cairo Opera House gave the work a unique connection between Italian grand opera and Egyptian cultural identity — Aida became, paradoxically, the European opera most associated with ancient Egypt, premiered in a modern Egyptian opera house built to demonstrate European sophistication.",
        "causes": ["Khedive Ismail's Suez Canal opening (1869) requiring cultural celebrations demonstrating Egypt's modernization", "Ismail's Westernization project requiring European-style cultural institutions to signal civilization membership", "Verdi's Aida commission for the canal opening creating the most famous opera associated with ancient Egypt", "Italian Renaissance-style design by Pietro Avoscani expressing European architectural vocabulary for Egyptian cultural ambitions"],
        "effects": ["Aida's 1871 premiere at the Khedivial Opera House creating the canonical link between Italian grand opera and ancient Egyptian imagery", "Opera house as symbol of Egyptian Westernization burning in 1971 creating symbolic loss of a colonial-era cultural monument", "Cairo Opera House (1988) replacing the Khedivial as Egypt's primary performing arts center", "Suez Canal opening ceremonies including the opera house inaugurating the 'golden age of Khedivial Cairo'"],
        "relationships": [{"entity": "Aida", "relationship": "PREMIERED_AT_IN_1871_AS_COMMISSIONED_WORK_FOR", "note": "Verdi's Aida, commissioned for the canal opening, premiered at the Khedivial Opera House in 1871"}, {"entity": "Suez Canal", "relationship": "BUILT_TO_CELEBRATE_1869_OPENING_OF", "note": "The opera house was constructed for the Suez Canal's opening ceremonies as a symbol of Egyptian modernization"}, {"entity": "Khedive Ismail", "relationship": "COMMISSIONED_BY_AS_WESTERNIZATION_SYMBOL", "note": "Ismail's opera house commission was part of his ambitious project to modernize Egypt along European cultural lines"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Egyptian Royal Opera House — built for the 1869 Suez Canal opening, site of Aida's 1871 premiere, and symbol of Khedive Ismail's Westernization project — is one of history's most historically resonant opera houses, connecting Egyptian modernity, European opera, and the Suez Canal's world-historical significance.", "significanceCategory": "world-changing"},
    }, FOLDER_363, "363"),
    ("folkoperan", {
        "summary": "Folkoperan (Folk Opera) in Stockholm, Sweden, is one of Scandinavia's most innovative and significant opera companies — founded in 1976 by director Claes Fellbom with a mission to make opera accessible to a broader audience through staging works in Swedish, using contemporary theatrical approaches, performing in an intimate (rather than monumental) theater, and challenging the elitist conventions of traditional opera production. Folkoperan has been internationally recognized for its artistic innovation and its approach to opera as popular rather than elite cultural form.\n\nFolkoperan's founding in 1976 was part of a broader movement in European opera in the 1970s-1980s that challenged the institutional opera establishment: using vernacular languages, alternative staging spaces, contemporary theatrical direction, and lower ticket prices to create more accessible opera experiences. Folkoperan's specifically Swedish mission — presenting opera in Swedish, reflecting Swedish theatrical traditions — distinguished it from the international opera establishment's preference for original-language performance.\n\nThe company has produced notable world premieres of Swedish operas and has commissioned new works that engage with contemporary Swedish social issues, making Folkoperan a forum for Swedish cultural debates as well as a performing arts institution. Its intimate theater (the Folkoperan building in Södermalm, Stockholm) and its programming philosophy of mixing classic and contemporary repertoire, always in Swedish, have made it one of Europe's distinctive alternative opera institutions.",
        "causes": ["1976 founding mission to make opera accessible through Swedish-language performance and intimate theater", "Swedish cultural policy supporting performing arts innovation and democratic access to the arts", "Broader 1970s European opera democratization movement challenging elite institutional opera conventions", "Södermalm location in Stockholm's culturally creative neighborhood supporting the company's alternative positioning"],
        "effects": ["Folkoperan as one of Europe's most distinctive alternative opera companies performing exclusively in Swedish", "World premieres of Swedish operas and new commissions expanding the Swedish-language operatic repertoire", "Intimate theater model demonstrating that opera can be effective in non-monumental spaces", "International recognition for artistic innovation influencing global opera accessibility debates"],
        "relationships": [{"entity": "Swedish Opera Tradition", "relationship": "POPULAR_ALTERNATIVE_TO_ESTABLISHMENT_OF", "note": "Folkoperan was founded as an alternative to the Royal Opera's elite traditions, performing exclusively in Swedish"}, {"entity": "Opera Democratization", "relationship": "LEADING_INSTITUTION_OF_EUROPEAN_MOVEMENT_FOR", "note": "Folkoperan's founding mission positioned it as a leading example of 1970s opera democratization in Europe"}, {"entity": "Claes Fellbom", "relationship": "FOUNDED_BY_ARTISTIC_DIRECTOR", "note": "Fellbom's 1976 founding established Folkoperan's distinctive mission and approach"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "Folkoperan Stockholm — founded 1976 as Scandinavia's leading alternative opera company performing exclusively in Swedish, commissioning new works, and demonstrating opera's accessibility in intimate spaces — is historically significant as an innovative model of opera democratization with international influence.", "significanceCategory": "continental"},
    }, FOLDER_363, "363"),
    ("forest-opera", {
        "summary": "The Forest Opera (Polish: Opera Leśna) in Sopot, Poland — an open-air amphitheater in a natural forest setting on the slopes of a hill near the Baltic Sea — is one of Europe's most distinctive and beloved outdoor performing arts venues, founded in 1909 as an outdoor summer theater, capable of seating approximately 5,000 spectators, and now most famous as the venue of the Sopot International Song Festival (founded 1961) — the oldest and most prestigious popular music competition in the Eastern Bloc during the Communist era and one of Europe's important music festivals.\n\nThe Forest Opera's natural setting — a circular auditorium cut into a forest hillside, with trees forming the natural backdrop for the stage — creates one of the world's most unusual and atmospheric performing spaces. The venue's acoustics (naturally amplified by the surrounding trees) and its open-air character make it particularly suited to summer opera and concert performances. Before WWII, it hosted major opera and theater productions; after the war, under Polish communist administration, it became famous primarily for popular music.\n\nThe Sopot International Song Festival (1961-present), held at the Forest Opera, was one of the most significant cultural events of the Communist Eastern Bloc: it allowed Western popular music artists to perform behind the Iron Curtain (ABBA performed at Sopot in 1976, as did other Western artists) and served as a platform for Eastern European pop music talent. During the Cold War, Sopot was a rare cultural bridge point between East and West — the festival's international character made it a subtle form of cultural diplomacy.",
        "causes": ["1909 natural forest amphitheater construction creating one of Europe's most atmospheric outdoor performing venues", "Sopot's development as a Baltic Sea resort requiring cultural entertainment infrastructure for summer visitors", "1961 International Song Festival founding creating an Eastern Bloc cultural event connecting Western and Eastern popular music", "Cold War cultural diplomacy enabling Western artists to perform at Sopot as a rare cross-Iron Curtain cultural exchange"],
        "effects": ["Sopot Song Festival as premier Eastern Bloc popular music platform connecting Western and Eastern European music cultures", "ABBA's 1976 Sopot performance among the most famous Western artist appearances in Communist-era Eastern Europe", "Forest Opera's preservation as a distinctive natural performance space combining ecology and acoustic architecture", "Post-communist continuation of the Sopot festival maintaining its status as Poland's most prestigious music event"],
        "relationships": [{"entity": "Sopot International Song Festival", "relationship": "PRIMARY_VENUE_OF_EASTERN_BLOC'S_MOST_IMPORTANT_MUSIC_FESTIVAL", "note": "The Forest Opera hosts the Sopot Song Festival (1961-present), the Eastern Bloc's most significant popular music competition"}, {"entity": "Cold War Cultural Exchange", "relationship": "RARE_PLATFORM_FOR_WESTERN-EASTERN_MUSIC_THROUGH", "note": "The Sopot festival's open-air performances allowed Western artists (including ABBA) to appear in Communist-era Eastern Europe"}, {"entity": "Sopot", "relationship": "DEFINING_CULTURAL_LANDMARK_OF_POLISH_BALTIC_RESORT_CITY", "note": "The Forest Opera is Sopot's most distinctive cultural venue, established when the city was a fashionable German Baltic resort"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Forest Opera Sopot — one of Europe's most atmospheric natural outdoor amphitheaters, venue of the Eastern Bloc's most important popular music festival, and Cold War cultural bridge point between East and West through ABBA's 1976 appearance — is historically significant for its unique role in Communist-era cultural diplomacy.", "significanceCategory": "world-changing"},
    }, FOLDER_363, "363"),
    ("a-kasteyev-state-museum-of-arts", {
        "summary": "The A. Kasteyev State Museum of Arts (Kazakhstani: Абылхан Қастеев атындағы Мемлекеттік өнер мұражайы) in Almaty, Kazakhstan — the largest and most important art museum in Kazakhstan, named for Abylkhan Kasteyev (1904-1973), the father of Kazakh fine arts — houses the most comprehensive collection of Kazakhstani art, including Kasteyev's own foundational works, Soviet-era Kazakhstani painting, decorative art, and international collections assembled during the Soviet period.\n\nAbylkhan Kasteyev is considered the founder of Kazakh professional fine arts — the first self-taught Kazakh artist to master European oil painting techniques while simultaneously celebrating Kazakh nomadic culture, landscapes, and traditions. Growing up in the nomadic steppe culture and self-teaching himself artistic skills (reportedly copying images from books), Kasteyev became the first Kazakhstani artist to gain recognition in the broader Soviet art world. His paintings of Kazakh landscapes, horsemen, yurts, and historical scenes created the visual language of modern Kazakh identity.\n\nThe museum bearing his name houses approximately 25,000 works including Kazakhstani fine and decorative arts, Russian and Soviet art, and a collection of Western European artworks. As Kazakhstan's premier art museum, it serves as the institutional home of Kazakh visual art tradition — both the modern fine arts tradition initiated by Kasteyev and the rich decorative arts tradition of Kazakh nomadic culture (felt work, metalwork, jewelry, textiles). The museum's Almaty location reflects the city's role as Kazakhstan's cultural capital even after Nur-Sultan (Astana) became the administrative capital.",
        "causes": ["Abylkhan Kasteyev's founding of Kazakh fine arts through self-taught European oil painting celebrating nomadic culture", "Soviet cultural investment creating formal museum infrastructure for Kazakhstani art collections", "Kazakhstan's need for a national art museum housing both traditional decorative arts and modern fine arts", "Almaty's cultural capital status requiring the nation's premier art museum despite administrative capital transfer"],
        "effects": ["Kazakhstan's largest art museum collection of 25,000+ works documenting the full range of Kazakh and Soviet art", "Kasteyev's foundational paintings establishing the visual vocabulary of Kazakh national identity in fine arts", "Museum as primary institution for Kazakhstani art education, research, and cultural heritage preservation", "National art collection including Western European artworks assembled during Soviet period expanding cultural scope"],
        "relationships": [{"entity": "Abylkhan Kasteyev", "relationship": "NAMED_FOR_AND_HOUSES_WORKS_OF_FATHER_OF_KAZAKH_FINE_ARTS", "note": "The museum honors Kasteyev, whose self-taught oil paintings founded the Kazakh fine arts tradition"}, {"entity": "Kazakhstan", "relationship": "PREMIER_ART_MUSEUM_HOUSING_NATIONAL_COLLECTION_OF", "note": "The Kasteyev Museum is Kazakhstan's most important art institution with the nation's largest art collection"}, {"entity": "Soviet Cultural Policy", "relationship": "FORMAL_MUSEUM_INFRASTRUCTURE_CREATED_UNDER", "note": "The museum's collection and infrastructure were developed under Soviet cultural investment in Kazakhstani arts"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The A. Kasteyev State Museum of Arts — Kazakhstan's premier art institution, housing the nation's largest art collection and works of the father of Kazakh fine arts — is historically significant as the primary cultural heritage institution documenting Kazakh visual identity from nomadic traditions to modern fine arts.", "significanceCategory": "continental"},
    }, FOLDER_361, "361"),
    ("adjara-state-museum", {
        "summary": "The Adjara State Museum (Georgian: აჭარის სახელმწიფო მუზეუმი) in Batumi, Adjara (Autonomous Republic of Adjara, Georgia) — houses the primary collection of historical, archaeological, and natural history materials from Adjara, the Black Sea coastal region of southwestern Georgia with a unique history as a Georgian Muslim-majority region that was part of the Ottoman Empire until 1878 and retains distinctive cultural characteristics blending Georgian Orthodox and Ottoman-Muslim heritage.\n\nAdjara's historical complexity — Georgian Orthodox Christian roots, Ottoman rule from 1614 to 1878, Russian imperial incorporation after the 1878 Russo-Turkish War, Soviet Autonomous Republic status from 1921, and current status as an Autonomous Republic within Georgia — created a rich archaeological and historical heritage that the Adjara State Museum preserves. The museum's collections include materials from the ancient Colchis kingdom (home of the Golden Fleece legend), medieval Georgian Christian churches, Ottoman-era artifacts, and Soviet-era items.\n\nBatumi's position as the Black Sea terminus of the Baku-Batumi oil pipeline (built 1883) made it one of the first oil export terminals in history — a crucial node in the global oil economy even before the 20th century's petroleum era. The Adjara State Museum's historical collections document this remarkable convergence of ancient mythology (Colchis/Golden Fleece), medieval Christianity, Ottoman-Muslim culture, and modern industrial oil infrastructure in a single coastal region.",
        "causes": ["Adjara's unique convergence of Georgian Orthodox, Ottoman-Muslim, and Soviet cultural layers requiring comprehensive museum documentation", "Ancient Colchis kingdom archaeological materials requiring systematic collection and preservation", "Soviet autonomous republic status requiring institutional cultural infrastructure including state museum", "Batumi's Black Sea port and oil pipeline terminus history creating significant industrial heritage materials"],
        "effects": ["Museum preserving the complex multi-layered cultural heritage of a region shaped by Greek, Georgian, Ottoman, and Russian influences", "Colchis kingdom materials documenting the ancient civilization at the source of the Golden Fleece legend", "Ottoman-era Adjara heritage preserved alongside Georgian Orthodox materials in unique cultural synthesis collection", "Adjara State Museum as primary heritage institution for the Autonomous Republic's complex historical identity"],
        "relationships": [{"entity": "Adjara", "relationship": "PRIMARY_HERITAGE_INSTITUTION_OF_AUTONOMOUS_REPUBLIC_OF", "note": "The museum is the main repository of Adjara's historical and archaeological heritage"}, {"entity": "Colchis", "relationship": "ANCIENT_KINGDOM_DOCUMENTED_IN_ARCHAEOLOGICAL_COLLECTIONS_OF", "note": "Adjara's Colchis kingdom materials in the museum document the ancient civilization associated with the Golden Fleece legend"}, {"entity": "Ottoman Georgia", "relationship": "OTTOMAN-MUSLIM_HERITAGE_PRESERVED_ALONGSIDE_ORTHODOX_IN", "note": "The museum uniquely preserves both Ottoman-Muslim and Georgian Orthodox materials from Adjara's complex religious history"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "The Adjara State Museum Batumi — preserving the multi-layered heritage of a region uniquely shaped by ancient Colchis, medieval Georgia, Ottoman rule, and Russian/Soviet incorporation — is regionally significant as the primary heritage institution documenting one of the Caucasus's most culturally complex regions.", "significanceCategory": "local"},
    }, FOLDER_361, "361"),
    ("alisher-navoi-state-museum-of-literature", {
        "summary": "The Alisher Navoi State Museum of Literature (Uzbek: Alisher Navoiy nomidagi O'zbekiston davlat adabiyot muzeyi) in Tashkent, Uzbekistan — named for Alisher Navoi (1441-1501), the 15th-century Chagatai poet considered the father of Uzbek literature and one of the greatest literary figures in the Islamic literary tradition — is Uzbekistan's primary literary museum, housing manuscripts, documents, and materials related to Navoi and the broader history of Uzbek and Central Asian literature.\n\nAlisher Navoi is one of the towering figures of Islamic literary history: writing in Chagatai Turkish (the literary language of Central Asia that is the ancestor of modern Uzbek), he produced extraordinary poetry (especially his Khamsa, five allegorical masnavi poems responding to Nizami Ganjavi's classical Khamsa), prose works, and a foundational comparative linguistic treatise (Muhakamat al-lughatayn, comparing Chagatai Turkish and Persian). He served as a vizier to the Timurid Sultan Husayn Bayqara in Herat and was central to the last great flowering of Timurid culture.\n\nNavoi's significance extends beyond literature: he championed the use of Chagatai Turkish as a literary language worthy of comparison with Persian (the dominant literary language of the Islamic world), legitimizing Turkic literary culture at a time when Persian was considered culturally superior. His works became the foundation of Uzbek literary identity, and Soviet cultural policy used Navoi as a national symbol of Uzbek cultural heritage — naming the national opera theater and major institutions after him. The museum bearing his name serves as the primary institutional guardian of Uzbek literary heritage.",
        "causes": ["Alisher Navoi's foundational role in Chagatai-Uzbek literary tradition requiring institutional preservation", "Soviet cultural policy using Navoi as Uzbek national cultural symbol requiring named institutions", "Timurid cultural heritage's significance requiring systematic preservation of manuscript and literary materials", "Uzbekistan's independent national identity requiring primary literary museum honoring the nation's founding poet"],
        "effects": ["Museum as primary repository of Navoi manuscripts and materials documenting Central Asian literary heritage", "Uzbek literary identity institutionalized through the museum's educational and heritage preservation role", "Timurid cultural renaissance's literary legacy preserved in a national institution accessible to Uzbek scholars", "International recognition of Navoi's significance extended through the museum's research and exhibition programs"],
        "relationships": [{"entity": "Alisher Navoi", "relationship": "NAMED_FOR_AND_DEDICATED_TO_HERITAGE_OF", "note": "The museum honors Navoi (1441-1501), father of Uzbek literature and one of the Islamic literary tradition's greatest figures"}, {"entity": "Uzbek Literature", "relationship": "PRIMARY_INSTITUTIONAL_HOME_OF_HISTORY_OF", "note": "The museum is Uzbekistan's main repository for literary heritage from Navoi to modern Uzbek literature"}, {"entity": "Timurid Cultural Renaissance", "relationship": "LITERARY_LEGACY_OF_PRESERVED_IN", "note": "Navoi's works represent the literary peak of Timurid cultural achievement documented in the museum's collections"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Alisher Navoi State Museum of Literature — dedicated to the father of Uzbek literature who championed Chagatai Turkish against Persian cultural dominance and produced the Timurid era's greatest literary works — is historically significant as the primary guardian of Central Asian Turkic literary heritage.", "significanceCategory": "world-changing"},
    }, FOLDER_361, "361"),
]

def enrich_entity(slug, data, folder, prefix):
    fname = os.path.join(folder, f"{prefix}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 129 — MIXED 363(5)+361(3): Opera Houses + Museums")
    for slug, data, folder, prefix in ENTITIES:
        enrich_entity(slug, data, folder, prefix)
    print("Done.")
