#!/usr/bin/env python3
"""Batch 85 — Class 340 Religious Orgs II (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/340-Class-340"
FILE_PREFIX = "340"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("church-of-england", {
        "summary": "The Church of England, established in 1534 when Henry VIII's Act of Supremacy declared the English monarch head of the English Church rather than the Pope, is the world's third-largest Christian denomination (85 million members in 165 countries through the Anglican Communion) and the established national church of England — its 26 bishops sitting by right in the House of Lords (Lords Spiritual) as the only religious body with reserved parliamentary seats in any modern democracy. The Church of England's establishment bridged Catholic tradition and Protestant theology through the 'via media' principle, creating a distinctive Anglican identity.\n\nHenry VIII's break with Rome was motivated by his desire to annul his marriage to Catherine of Aragon — Pope Clement VII refused, being effectively a prisoner of Catherine's nephew Emperor Charles V. Archbishop Thomas Cranmer drafted the Book of Common Prayer (1549, revised 1662) — arguably the most influential text in the history of the English language, shaping Shakespeare's vocabulary, the King James Bible's cadences, and the prose style of Lincoln and Churchill. Cranmer was burned at the stake under Mary I before Elizabeth I's Settlement confirmed Protestantism.\n\nThe Church of England's 39 Articles (1563) defined Anglican theology as Reformed Catholic — maintaining bishops, liturgy, and sacraments from Catholic tradition while rejecting papal authority and affirming Protestant justification by faith. The Archbishop of Canterbury serves as 'first among equals' in the 165-country Anglican Communion. The 1994 decision to ordain women priests and 2014 women bishops caused ongoing tensions; the 2023 Prayers of Love and Faith for same-sex couples provoked a threatened Global South Anglican schism.",
        "causes": ["1534 Act of Supremacy making Henry VIII head of English Church to annul Catherine of Aragon marriage", "Thomas Cranmer's Book of Common Prayer 1549 creating distinctive Anglican liturgical tradition", "39 Articles 1563 defining Anglican via media between Catholic tradition and Protestant theology", "Elizabeth I's Settlement confirming Protestantism after Mary I's Catholic restoration"],
        "effects": ["Book of Common Prayer shaped English language prose through Shakespeare, King James Bible, and political oratory", "85 million members in 165 countries through Anglican Communion making it world's third-largest denomination", "Lords Spiritual bishops — 26 reserved parliamentary seats — unique religious constitutional arrangement", "Women's ordination 1994 and same-sex blessings 2023 creating Anglican Communion schism tensions"],
        "relationships": [{"entity": "Henry VIII", "relationship": "ESTABLISHED_BY", "note": "Henry's 1534 Act of Supremacy created Church of England to enable marriage annulment"}, {"entity": "Thomas Cranmer", "relationship": "LITURGY_CREATED_BY", "note": "Cranmer's Book of Common Prayer 1549 created Anglican worship tradition; he was burned at stake under Mary I"}, {"entity": "Elizabeth I", "relationship": "SETTLEMENT_CONFIRMED_BY", "note": "Elizabeth's Religious Settlement confirmed Protestantism after Mary's Catholic restoration"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Church of England's Book of Common Prayer shaped the English language more than any text except the Bible — its cadences appear in Shakespeare, Lincoln's Gettysburg Address, and Churchill's wartime speeches — making it the theological institution with the greatest literary and linguistic influence in history.", "significanceCategory": "world-changing"},
    }),
    ("methodist-church-of-great-britain", {
        "summary": "The Methodist Church of Great Britain, formally constituted in 1784 when John Wesley (an Anglican priest who never formally left the Church of England) died and his movement became independent, is the world's founding Methodist body and the parent denomination of 80 million Methodists worldwide — the largest Protestant family after Lutheranism and Reformed traditions. Methodism's social mission — prioritizing the working poor, opposing slavery, establishing Sunday schools, and founding hospitals — made it the defining working-class religious movement of the Industrial Revolution.\n\nJohn Wesley, an Oxford-educated Anglican priest, experienced his 'Aldersgate conversion' on May 24, 1738 — feeling his heart 'strangely warmed' — and became an open-air evangelist preaching to miners, factory workers, and the urban poor excluded from Anglican parish churches. Wesley rode 250,000 miles on horseback across Britain and Ireland, delivered 40,000 sermons, and organized converts into 'classes' — small accountability groups of 12 that became the template for cell church movements globally.\n\nMethodism's practical Christianity pioneered: Sunday Schools (Robert Raikes, 1780, providing working-class children their only education), hospital founding (Wesley's Dispensary, 1746), prison reform advocacy (alongside Quakers), and the most vocal early anti-slavery movement (Wesley's last letter was to William Wilberforce encouraging abolition). American Methodism (founded from British parent) became America's largest denomination by 1850, with circuit riders carrying Wesley's message to frontier settlements. The YMCA, Salvation Army, and many other social welfare organizations trace their heritage to Methodist working-class ministry.",
        "causes": ["1738 Aldersgate conversion inspiring Wesley's outdoor preaching to industrial working poor", "Wesley's organization of converts into 'classes' of 12 creating accountability group template", "Sunday School founding 1780 providing working-class children their only literacy education", "Wesley's 1791 death formalizing independent Methodist connection from Anglican parent"],
        "effects": ["80 million Methodists worldwide making it the largest Protestant family after Lutheran and Reformed", "Sunday Schools providing first literacy education to millions of working-class Industrial Revolution children", "Anti-slavery advocacy Wesley's last letter to Wilberforce contributing to abolition movement", "YMCA, Salvation Army, and social welfare organizations tracing heritage to Methodist social mission"],
        "relationships": [{"entity": "John Wesley", "relationship": "FOUNDED_BY", "note": "Wesley's 1738 conversion and 40,000 sermons created Methodist movement; died 1791 formalizing independence"}, {"entity": "William Wilberforce", "relationship": "ENCOURAGED_IN_ABOLITION", "note": "Wesley's last letter before death encouraged Wilberforce to persist in anti-slavery campaign"}, {"entity": "Robert Raikes", "relationship": "SUNDAY_SCHOOLS_PIONEERED_WITH", "note": "Raikes's 1780 Sunday Schools built on Methodist social mission to educate working-class children"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Methodism's Sunday Schools provided literacy to millions of Industrial Revolution working-class children — creating the educational foundation for the labor movement — while its anti-slavery advocacy contributed to abolition, making it the most socially consequential Protestant denomination in history.", "significanceCategory": "world-changing"},
    }),
    ("methodist-episcopal-church", {
        "summary": "The Methodist Episcopal Church, founded in Baltimore in 1784 as the American Methodist organization organized by Francis Asbury and Thomas Coke after the American Revolution, was America's largest Protestant denomination from approximately 1820 to 1850 and the institutional force that evangelized the American frontier through the circuit rider system. The church's 1844 split over slavery — creating northern and southern Methodist bodies — was the largest Protestant schism in American history before the Civil War and anticipated the political division that would cause the war itself.\n\nJohn Wesley sent Thomas Coke and Francis Asbury to organize American Methodism after the Revolution cut ties with the Church of England. The Baltimore Christmas Conference of 1784 constituted the Methodist Episcopal Church, ordaining Asbury as the first American bishop. Asbury traveled 300,000 miles, organized the circuit rider system (preachers assigned to vast frontier territories), and grew the church from 15,000 to 214,000 members during his episcopate.\n\nThe 1844 split over Bishop James Andrew's slave ownership was the most consequential ecclesiastical division in American religious history — creating the Methodist Episcopal Church (North) and Methodist Episcopal Church, South (MEC-South). The split demonstrated that no major institution — not churches, not political parties, not families — could remain unified over the slavery question. The northern MEC's General Conference provided institutional support for abolition and Black education; Freedmen's Aid Society schools founded by northern Methodists became historically Black colleges including Clark Atlanta, Rust, and Wiley College.",
        "causes": ["1784 Baltimore Christmas Conference organizing American Methodist independence after Revolution", "Francis Asbury's circuit rider system evangelizing American frontier expanding membership from 15,000 to 214,000", "1844 split over Bishop Andrew's slave ownership creating northern and southern Methodist bodies", "Freedmen's Aid Society founding historically Black colleges supporting emancipated slaves' education"],
        "effects": ["Circuit rider system became template for evangelical frontier ministry reaching remote American settlements", "1844 slavery split was largest pre-Civil War Protestant schism and previewed Union collapse", "Northern Methodist support for Black education produced historically Black colleges including Clark Atlanta", "1939 reunion of northern and southern bodies (after 95 years) signaled post-Civil War reconciliation"],
        "relationships": [{"entity": "Francis Asbury", "relationship": "ORGANIZED_BY", "note": "Asbury traveled 300,000 miles organizing circuit riders and growing membership from 15,000 to 214,000"}, {"entity": "Thomas Coke", "relationship": "CO-ORGANIZED_BY", "note": "Wesley sent Coke alongside Asbury to organize American Methodism after Revolution"}, {"entity": "James Andrew", "relationship": "SPLIT_CAUSED_BY", "note": "1844 split over Bishop Andrew's slave ownership created northern and southern Methodist bodies"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Methodist Episcopal Church's 1844 slavery split — the largest religious schism in American history before the Civil War — demonstrated that no institution could remain united over slavery, prefiguring the Union collapse that caused the war itself.", "significanceCategory": "world-changing"},
    }),
    ("presbyterian-church", {
        "summary": "The Presbyterian Church, originating in John Calvin's Reformed theology applied to church governance by John Knox in Scotland (1560 Scottish Reformation) and institutionalized through the Westminster Confession of Faith (1646), governs worldwide through elder councils (presbyteries) rather than bishops — a democratic church governance structure that directly influenced the American republican system. The 750,000 members of the Presbyterian Church USA and 9 million members across worldwide Presbyterian bodies represent Calvinism's institutional legacy in governance, education, and democratic theory.\n\nJohn Calvin's Geneva (1541-1564) was the model city-state: governed by a Consistory of pastors and elected lay elders who enforced moral discipline, ran schools, trained ministers, and sent missionaries. Knox took Calvin's model to Scotland, converting the Scottish nobility and people in a decade and creating the Church of Scotland (1560) — governed by General Assembly of ministers and elders with democratic voting, the most democratic major institution in 16th-century Europe.\n\nThe Westminster Assembly (1643-1649) — convened during the English Civil War to create a Protestant settlement for Britain — produced the Westminster Confession of Faith, Westminster Larger and Shorter Catechisms, and the Directory for Worship, which remain the doctrinal standards of Presbyterian churches worldwide. Princeton Theological Seminary (1812) and the college it evolved from (1746, now Princeton University) were founded by Presbyterians. Five US presidents were Presbyterians, and the framers' understanding of limited government, covenant theology, and elder governance directly influenced the American Constitution's separation of powers.",
        "causes": ["Calvin's Geneva Consistory model combining pastoral and lay elder governance", "Knox's 1560 Scottish Reformation creating democratic General Assembly governance", "Westminster Confession 1646 creating doctrinal standards for world Presbyterian community", "Princeton University and Seminary founding connecting Calvinist theology to American republican education"],
        "effects": ["Presbyterian elder governance influenced American republican separation of powers and democratic theory", "Westminster Confession standards govern 9 million worldwide Presbyterians across 150 countries", "Princeton University founding from Presbyterian college model influenced American higher education", "Five US presidents and many Constitutional framers educated in Presbyterian theology"],
        "relationships": [{"entity": "John Calvin", "relationship": "THEOLOGICAL_FOUNDATION_BY", "note": "Calvin's Geneva Consistory model provided Presbyterian governance template"}, {"entity": "John Knox", "relationship": "SCOTTISH_REFORMATION_BY", "note": "Knox applied Calvin's model to Scotland creating democratic Church of Scotland General Assembly"}, {"entity": "Westminster Confession", "relationship": "DOCTRINAL_STANDARD", "note": "1646 Westminster documents remain governing confessions of worldwide Presbyterian churches"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Presbyterian elder governance — Calvin's Consistory applied by Knox to Scotland and the Westminster Assembly to Britain — directly influenced the American Constitution's separation of powers, making Calvinist church polity one of the sources of modern democratic government.", "significanceCategory": "world-changing"},
    }),
    ("the-church-of-jesus-christ-of-latter-day-saints", {
        "summary": "The Church of Jesus Christ of Latter-day Saints (LDS Church), founded in 1830 in Fayette, New York by Joseph Smith with the publication of the Book of Mormon, is the world's fastest-growing major religious denomination of the 20th century — growing from 1 million (1947) to 17 million members (2023) primarily through a worldwide 70,000-missionary program. The Church's economic infrastructure — the 10% tithing system, Deseret Industries, and Church welfare program — creates a self-sufficient member support network that has been studied by sociologists as the most effective religious community-building model in American history.\n\nJoseph Smith claimed to have received golden plates from the angel Moroni in upstate New York, which he translated as the Book of Mormon — the record of ancient American peoples who were visited by Jesus after the Resurrection. Smith's 1844 assassination in Carthage, Illinois — where he and his brother Hyrum were killed by a mob while in jail — created the succession crisis that divided the movement and produced Brigham Young's migration of 70,000 Saints to the Salt Lake Valley (1847), establishing Utah as a Mormon-dominated territory.\n\nThe Church's 1978 revelation extending priesthood to Black members — reversing a 130-year exclusion that had become increasingly untenable — was one of the most significant ecclesiastical policy reversals in 20th-century religious history. The Church's welfare system — developed during the Great Depression — operates 400 storehouses, 97 home storage centers, and a network of canneries, farms, and employment services providing member assistance. The genealogical research program (FamilySearch) has indexed over 3 billion records — the world's largest genealogical database.",
        "causes": ["1830 founding by Joseph Smith with Book of Mormon publication in Fayette New York", "Smith's 1844 assassination creating succession crisis and Brigham Young's 1847 Utah migration", "Missionary program of 70,000 missionaries driving fastest growth of any major denomination", "1978 revelation extending priesthood to Black members reversing 130-year exclusion"],
        "effects": ["Growth from 1 million (1947) to 17 million (2023) through worldwide missionary program", "Church welfare system operating 400 storehouses creating self-sufficient member support network", "FamilySearch genealogical database with 3 billion records is world's largest genealogical resource", "Utah settlement established theocratic territory that created unique American religious polity"],
        "relationships": [{"entity": "Joseph Smith", "relationship": "FOUNDED_BY", "note": "Smith founded church in 1830; assassinated 1844 creating succession crisis"}, {"entity": "Brigham Young", "relationship": "MIGRATION_LED_BY", "note": "Young led 70,000 Saints to Salt Lake Valley 1847 after Smith's assassination"}, {"entity": "FamilySearch", "relationship": "OPERATES", "note": "Church's genealogical database with 3 billion records is world's largest"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The LDS Church's growth from 1 million to 17 million members in 76 years — driven by a worldwide 70,000-missionary program — is the fastest growth of any major religious denomination in 20th-century history, making it America's most remarkable religious export.", "significanceCategory": "world-changing"},
    }),
    ("greek-orthodoxy", {
        "summary": "The Greek Orthodox Church (Patriarchate of Constantinople — the Ecumenical Patriarchate) represents the oldest continuous Christian episcopal see and the spiritual center of Eastern Orthodox Christianity's 220 million worldwide adherents. The Ecumenical Patriarch of Constantinople holds the primacy of honor (but not jurisdiction) over 14 autocephalous Orthodox churches — maintaining continuity with the Christian communities of Byzantium, the Great Schism of 1054 that split Eastern and Western Christianity, and the Byzantine Empire's 1,000-year theological tradition.\n\nConstantinople's Bishop claimed primacy in the Christian East from the Council of Constantinople (381 CE), which ranked the 'New Rome' above Alexandria and Antioch. The Ecumenical Patriarchate survived the Ottoman conquest of 1453 — Sultan Mehmed II deliberately preserved Patriarch Gennadios as leader of the Greek-speaking Christian community (millet) rather than risk Christian holy sites becoming political grievances. The Patriarchate operated from the Phanar (Fener) district of Istanbul under Ottoman authority for 469 years.\n\nThe Great Schism of 1054 — the mutual excommunication of Pope Leo IX's legate and Patriarch Michael Cerularius over the filioque clause (whether the Holy Spirit proceeds from the Father alone or from Father and Son) — divided Christianity's two great traditions permanently. Byzantine theology's influence on Renaissance humanism (via émigré scholars fleeing Ottoman conquest after 1453), Orthodox missions to the Slavic world (Saints Cyril and Methodius creating the Cyrillic alphabet), and the Hesychast controversy (Gregory Palamas's theology of divine light) define Orthodoxy's intellectual contributions.",
        "causes": ["381 CE Council of Constantinople ranking New Rome above Alexandria and Antioch", "1054 Great Schism mutual excommunication splitting Eastern and Western Christianity permanently", "Ottoman conquest 1453 preserving Patriarchate as Phanar millet leader under Islamic authority", "Byzantine émigré scholars fleeing 1453 carrying Greek texts to Florence contributing to Renaissance"],
        "effects": ["220 million Eastern Orthodox Christians worldwide through 14 autocephalous churches", "Great Schism 1054 split created Eastern and Western Christianity's enduring theological separation", "Cyrillic alphabet created by Orthodox missionaries Cyril and Methodius for Slavic evangelization", "Byzantine scholars after 1453 carrying Greek manuscripts to Florence contributing to Renaissance humanism"],
        "relationships": [{"entity": "Mehmed II", "relationship": "PATRIARCHATE_PRESERVED_BY", "note": "Ottoman sultan preserved Patriarch Gennadios as millet leader after 1453 Constantinople conquest"}, {"entity": "Gregory Palamas", "relationship": "HESYCHAST_THEOLOGY_DEVELOPED_BY", "note": "Palamas's theology of divine light through Hesychast practice represents Orthodox mystical theology peak"}, {"entity": "Cyril and Methodius", "relationship": "ALPHABET_CREATED_BY", "note": "Orthodox missionaries created Cyrillic alphabet for Slavic evangelization expanding Orthodox world"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Greek Orthodox Church's Great Schism of 1054 — splitting Christendom's two great traditions — and Cyrillic alphabet creation for Slavic peoples are among Christianity's most consequential institutional moments, shaping 220 million believers and 12 nations' writing systems.", "significanceCategory": "world-changing"},
    }),
    ("sufism", {
        "summary": "Sufism (Tasawwuf), the mystical dimension of Islam seeking direct personal experience of the Divine through spiritual practices (dhikr — remembrance, sama — sacred music, whirling meditation), emerged in 8th-century Baghdad as a reaction against Islam's legalistic and political corruptions and became the primary vehicle through which Islam spread peacefully in sub-Saharan Africa, South Asia, Southeast Asia, and Central Asia — regions where the majority of the world's Muslims now live. The Sufi orders (tariqa) — beginning with the Qadiriyya (founded by Abdul Qadir Gilani, Baghdad, 1166) — provided the organizational framework for both spiritual communities and political resistance to colonialism.\n\nThe name 'Sufi' derives from suf (wool), referring to the rough woolen garments of early ascetics rejecting worldly comfort. Al-Hallaj (858-922 CE) — the martyr who declared 'Ana al-Haqq' (I am the Truth/God) and was executed for blasphemy — established Sufism's mystical extremism. Rumi (1207-1273), whose Masnavi (50,000 verses) is the most widely read Persian poem in history, founded the Mevlevi Order (Whirling Dervishes) in Konya, Turkey — now the world's most recognized spiritual practice.\n\nSufi orders served as missionary organizations across Africa and Asia. In West Africa, the Qadiriyya and Tijaniyya orders spread Islam through trade networks rather than conquest. In South Asia, Sufi shrines (dargahs) like Ajmer Sharif in India and Data Darbar in Lahore attracted millions across religious boundaries. The colonial resistance role of Sufi orders — the Senussi order in Libya resisting Italian colonization, the Naqshbandiyya in Central Asia resisting Russian expansion — made them the primary institutional vehicle for both Islamic faith and anti-colonial nationalism.",
        "causes": ["8th-century Baghdad Sufi emergence as spiritual reaction against Islam's legalistic corruption", "Al-Hallaj's mystical martyrdom establishing Sufism's tradition of divine union theology", "Rumi's Masnavi creating the most influential literary expression of Islamic mysticism", "Sufi orders providing organizational framework for Islamic spread in Africa and Asia without conquest"],
        "effects": ["Peaceful Islamic expansion across sub-Saharan Africa, South Asia, and Southeast Asia through Sufi orders", "Rumi's poetry translated into 20+ languages becoming most-read medieval poet in 21st-century America", "Sufi shrines (dargahs) becoming pilgrimage centers attracting cross-religious devotion in South Asia", "Colonial resistance through Sufi orders (Senussi, Naqshbandiyya) combining faith and anti-imperial politics"],
        "relationships": [{"entity": "Rumi", "relationship": "GREATEST_POET", "note": "Rumi's Masnavi and founding of Mevlevi Order represent Sufism's highest literary and institutional expression"}, {"entity": "Al-Hallaj", "relationship": "MARTYRDOM_DEFINED_BY", "note": "Al-Hallaj's 922 execution for 'I am the Truth' established Sufism's mystical union theology"}, {"entity": "Abdul Qadir Gilani", "relationship": "FIRST_ORDER_FOUNDED_BY", "note": "Gilani founded Qadiriyya in Baghdad 1166 — first organized Sufi order that spread globally"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Sufism is the primary vehicle through which Islam spread peacefully to the majority of the world's Muslims — in sub-Saharan Africa, South Asia, and Southeast Asia — through trade networks, mystical appeal, and shrine devotion rather than conquest.", "significanceCategory": "world-changing"},
    }),
    ("anglican-communion", {
        "summary": "The Anglican Communion, formally constituted in 1867 at the first Lambeth Conference convened by Archbishop Longley, is a worldwide fellowship of 42 member churches and 85 million Christians — the third-largest Christian denomination — bound by common heritage from the Church of England but governed independently in each member country. The Communion's 'instruments of communion' (Lambeth Conference, Primates Meeting, Archbishop of Canterbury, Anglican Consultative Council) attempt to coordinate an increasingly diverse fellowship across 165 countries without central authority.\n\nAnglicanisms' global spread followed British colonialism: the Church of England's colonial chaplains established parishes in North America (1607), India (1813), Australia (1788), New Zealand (1814), Africa (1804), and the Caribbean — creating local churches that became autonomous. The Episcopal Church USA (founded 1789) was the first to achieve independence. Post-colonial Anglican churches in Africa (Uganda, Nigeria, Kenya, South Africa) now contain the majority of global Anglicans and have become more conservative than their North American and European counterparts.\n\nThe Windsor Report (2004) and subsequent crises over LGBTQ+ inclusion have created a deep north-south divide in the Communion. The election of Gene Robinson as first openly gay bishop (New Hampshire, 2003) prompted Global South African and Asian provinces to suspend communion with the Episcopal Church. The 2022 Global Anglican Future Conference (GAFCON) in Rwanda — attended by 1,300 delegates representing 85% of global Anglicanism — effectively constituted a parallel Anglican body, making the Communion's structural future uncertain.",
        "causes": ["1867 first Lambeth Conference creating global Anglican fellowship from British colonial church exports", "British colonial establishment of Anglican churches in North America, India, Australia, Africa", "Post-colonial Anglican churches growing larger than parent Church of England", "2003 Gene Robinson gay bishop election triggering Global South crisis threatening Communion unity"],
        "effects": ["85 million members in 165 countries making Anglican Communion third-largest Christian denomination", "Post-colonial African and Asian churches now containing majority of global Anglicanism", "2022 GAFCON conference in Rwanda effectively constituting parallel Communion threatening formal split", "Lambeth Conference model of bishop fellowship without central authority influenced ecumenical governance"],
        "relationships": [{"entity": "Archbishop of Canterbury", "relationship": "SYMBOLIC_HEAD", "note": "Archbishop of Canterbury is primus inter pares — symbolic head without jurisdiction over member churches"}, {"entity": "Gene Robinson", "relationship": "CRISIS_PRECIPITATED_BY", "note": "Robinson's 2003 election as first openly gay bishop triggered Global South withdrawal from Episcopal communion"}, {"entity": "GAFCON", "relationship": "CHALLENGED_BY", "note": "Global Anglican Future Conference 2022 effectively constituted parallel Communion from conservative Global South"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Anglican Communion's 2022 GAFCON crisis — with 85% of global Anglicanism effectively seceding from the liberal western churches over LGBTQ+ inclusion — is the largest Protestant schism of the 21st century and the most significant consequence of British colonial Christianization.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 85 — Class 340 Religious Orgs II")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
