#!/usr/bin/env python3
"""Batch 150 — MIXED: Class 311(2) + 312(2) + 363(2) + 364(2): Final Mixed Batch (8 entities)"""
import json, os
from datetime import datetime, timezone

NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("european-council", "data/appwrite-export/entities/311-Class-311", "311", {
        "summary": "The European Council — established informally in 1974 at the initiative of French President Valéry Giscard d'Estaing and West German Chancellor Helmut Schmidt, and formalized by the Lisbon Treaty in 2009 as one of the EU's seven institutions with its own permanent President — is the body of the European Union's heads of state and government that sets the EU's political agenda, defines its general direction, and makes the highest-level decisions that shape the integration of Europe's 27 member states and approximately 450 million citizens.\n\nThe European Council is often confused with the Council of the EU (the Council of Ministers), the Council of Europe (a separate non-EU pan-European organization), and the European Parliament. It is distinct from all: the European Council consists of the EU's national leaders (presidents and prime ministers), meets several times per year in Brussels, and decides by consensus on the EU's strategic direction — from Brexit negotiations to COVID recovery funds to Ukraine support — making it the body where the highest political will is formed or blocked.\n\nThe European Council's decisions shape the fundamental course of European integration: the Maastricht Treaty's decision to create the Euro, the enlargement decisions adding new member states, the Lisbon Treaty's reforms, the response to the 2008 financial crisis (austerity vs. solidarity), the 2015 refugee crisis response, the Brexit negotiations with the UK, and the unprecedented COVID-19 recovery fund (€750 billion) all emerged from European Council summits. The permanent President role (Herman Van Rompuy, Donald Tusk, Charles Michel) has given the institution a more sustained voice in European and global diplomacy.",
        "causes": ["Valéry Giscard d'Estaing and Helmut Schmidt's 1974 initiative creating informal summits of European leaders", "Need for highest-level political direction-setting that Council of Ministers and European Parliament could not provide", "Lisbon Treaty (2009) formalizing the European Council as an EU institution with permanent President", "European integration requiring regular summits to resolve major political disputes among member state leaders"],
        "effects": ["European Council setting EU's strategic direction on Euro creation, enlargement, Brexit, and COVID recovery", "Permanent President role (Van Rompuy, Tusk, Michel) giving the European Council a sustained diplomatic voice", "€750 billion COVID-19 recovery fund (2020) decided at European Council as unprecedented solidarity measure", "Brexit negotiations managed through European Council's Article 50 process with EU 27 maintaining unity"],
        "relationships": [{"entity": "European Union", "relationship": "HIGHEST-LEVEL_POLITICAL_DIRECTION-SETTING_INSTITUTION_OF", "note": "The European Council is the EU institution that sets the strategic political direction for European integration"}, {"entity": "Lisbon Treaty", "relationship": "FORMALIZED_AS_OFFICIAL_EU_INSTITUTION_WITH_PERMANENT_PRESIDENT_BY", "note": "The Lisbon Treaty (2009) formalized the European Council as an official EU institution with a permanent President"}, {"entity": "Brexit", "relationship": "NEGOTIATED_UK_EXIT_THROUGH_ARTICLE_50_PROCESS_MANAGING_EU_27_UNITY", "note": "The European Council managed Brexit negotiations under Article 50 while maintaining EU 27 solidarity"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The European Council — the summit of European leaders setting the EU's political agenda for 450 million citizens, deciding the Euro, enlargement, and COVID recovery — is historically significant as the highest political institution of the world's most ambitious supranational governance experiment.", "significanceCategory": "world-changing"},
    }),
    ("council-of-the-european-union", "data/appwrite-export/entities/311-Class-311", "311", {
        "summary": "The Council of the European Union (also called the Council of Ministers or simply 'the Council') — created by the founding treaties of the European Communities in the 1950s and now one of the EU's seven formal institutions — is the body where the ministers of the 27 EU member states meet to adopt legislation, coordinate policies, and make decisions alongside the European Parliament in the EU's ordinary legislative procedure, making it one of the world's most powerful legislative bodies for a community of approximately 450 million people.\n\nThe Council of the EU operates through ten different configurations depending on the policy area: the General Affairs Council (foreign ministers coordinating EU business), the Foreign Affairs Council (foreign and defense ministers), the Economic and Financial Affairs Council (Ecofin, finance ministers), and others covering agriculture, environment, education, etc. Each configuration represents a different sector of governmental activity, and each minister in the Council represents their national government's position. Decisions are made by qualified majority voting (QMV) in most areas (55% of member states representing 65% of the EU population), though unanimity is required for sensitive areas like taxation and foreign policy.\n\nThe Council's legislative power — combined with the European Parliament in the co-decision ordinary legislative procedure — means that EU legislation adopted by the Council directly applies in or requires transposition into the national laws of 27 countries. The Council's decisions have shaped everything from EU food safety standards to financial regulation, environmental policy, and the single market's operation, affecting the daily lives of 450 million Europeans.",
        "causes": ["European Communities founding treaties (1951 ECSC, 1957 Treaty of Rome) creating Council of Ministers", "Need for intergovernmental body representing national governments in EU legislative process", "Qualified majority voting (QMV) system balancing national sovereignty with supranational efficiency", "Lisbon Treaty reforms formalizing the Council's role in the ordinary legislative procedure with Parliament"],
        "effects": ["EU legislation co-adopted with European Parliament applying to or requiring transposition in 27 national legal systems", "Qualified majority voting enabling decisions without unanimity in most policy areas", "Council Presidencies (rotating 6-month terms) shaping EU legislative agenda priorities", "COREPER ambassadors' network coordinating national positions before formal ministerial meetings"],
        "relationships": [{"entity": "European Parliament", "relationship": "CO-LEGISLATOR_IN_ORDINARY_LEGISLATIVE_PROCEDURE_ALONGSIDE", "note": "The Council and European Parliament co-adopt EU legislation through the ordinary legislative procedure"}, {"entity": "European Commission", "relationship": "RECEIVES_LEGISLATIVE_PROPOSALS_FROM_AND_ADOPTS_EU_LAW_WITH", "note": "The European Commission proposes legislation that the Council and Parliament co-adopt into EU law"}, {"entity": "Qualified Majority Voting", "relationship": "DECISIONS_MADE_BY_55%_STATES_REPRESENTING_65%_POPULATION_THROUGH", "note": "Most Council decisions use QMV requiring 55% of member states representing 65% of the EU population"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Council of the EU — co-adopting legislation governing 450 million Europeans alongside the Parliament — is historically significant as the primary intergovernmental institution of the world's most ambitious supranational governance experiment.", "significanceCategory": "world-changing"},
    }),
    ("rashidun-caliphate", "data/appwrite-export/entities/312-Class-312", "312", {
        "summary": "The Rashidun Caliphate (Arabic: الخلافة الراشدية, al-Khilāfa al-Rāshidīya, 'the Rightly-Guided Caliphate') — established following the death of the Prophet Muhammad in 632 CE and ruled by four 'rightly-guided' caliphs (Abu Bakr, Umar ibn al-Khattab, Uthman ibn Affan, and Ali ibn Abi Talib) — was the first Islamic state that expanded from a small Arabian community into a vast empire stretching from Egypt to Persia within 30 years, one of the most rapid military and political expansions in human history.\n\nThe Rashidun period's historical significance is foundational for Islamic civilization: the compilation of the Quran (Uthman's standardized text, c.650 CE), the major Islamic conquests (Syria, Egypt, Mesopotamia, and Persia conquered between 632-661 CE from the Byzantine and Sasanian Empires), the establishment of Islamic governance principles (shura council, judicial practice), and the precedent of caliphal succession that would shape Islamic political thought for centuries. The Rashidun caliphs are venerated by Sunni Muslims as models of righteous governance.\n\nThe Rashidun Caliphate's end in 661 CE — with the assassination of Ali, the fourth caliph, and the establishment of the Umayyad Caliphate under Muawiyah — created the fundamental Sunni-Shia split in Islam that persists to the present day: Shia Muslims believe Ali should have been the first caliph and that legitimate leadership belongs to the Prophet's family (Ahl al-Bayt), while Sunni Muslims accept the Rashidun caliphs' legitimacy. This 1,400-year-old schism continues to shape geopolitics from Iran to Saudi Arabia.",
        "causes": ["Prophet Muhammad's 632 CE death creating the first succession crisis and the caliphate's establishment", "Abu Bakr's succession as first caliph and suppression of the Ridda wars restoring Arabian unity", "Military genius of Khalid ibn al-Walid and other commanders enabling extraordinary conquest speed", "Byzantine and Sasanian Empires' mutual exhaustion following decades of warfare enabling Islamic conquest"],
        "effects": ["Major Islamic conquests (Syria, Egypt, Mesopotamia, Persia) within 30 years of founding fundamentally reshaping the Middle East", "Uthman's Quran compilation (c.650 CE) creating the standardized Quranic text used by 1.8 billion Muslims", "Sunni-Shia split created by Ali's assassination and Umayyad succession shaping Islamic civilization for 1,400 years", "Islamic governance principles established by Rashidun caliphs providing the model for subsequent Islamic political thought"],
        "relationships": [{"entity": "Prophet Muhammad", "relationship": "SUCCESSOR_STATE_TO_MEDINA_COMMUNITY_FOUNDED_BY", "note": "The Rashidun Caliphate succeeded the Prophet Muhammad's Medina community as the first Islamic state"}, {"entity": "Sunni-Shia Split", "relationship": "FOUNDATIONAL_DISPUTE_ABOUT_SUCCESSION_CREATING_1400_YEAR_SCHISM", "note": "The Rashidun period's succession disputes created the Sunni-Shia split that persists for 1,400 years"}, {"entity": "Uthman Quran Compilation", "relationship": "STANDARDIZED_QURANIC_TEXT_USED_BY_1.8_BILLION_MUSLIMS_CREATED_DURING", "note": "Caliph Uthman's standardized Quran compilation (c.650 CE) is the text used by all Muslims today"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Rashidun Caliphate — conquering the Middle East in 30 years, compiling the Quran, creating the Sunni-Shia split — is one of history's most consequential states whose 632-661 CE existence shaped the religious and political landscape for 1.8 billion Muslims and the entire Middle East.", "significanceCategory": "world-changing"},
    }),
    ("umayyad-caliphate", "data/appwrite-export/entities/312-Class-312", "312", {
        "summary": "The Umayyad Caliphate (Arabic: الخلافة الأموية, al-Khilāfa al-Umawīya) — established in 661 CE when Muawiyah ibn Abi Sufyan became caliph following Ali's assassination, ruled from Damascus until 750 CE — was the Islamic world's first hereditary dynasty, expanding Islam from Spain and Portugal in the west to Central Asia and the borders of India and China in the east, creating one of the largest empires in history and spreading Islam across a vast territory that still has Muslim majorities today.\n\nThe Umayyad expansion was extraordinary: within 90 years of Muhammad's death, the Islamic world stretched from the Iberian Peninsula (Al-Andalus, conquered 711-718 CE) to the Indus Valley (Sindh conquered 711-712 CE) and Central Asia (Transoxiana, 705-715 CE). The Battle of Poitiers/Tours (732 CE) in France — where Charles Martel defeated the Umayyad forces — is often cited as the limit of westward Islamic expansion in Europe, though the significance of this single battle is debated by historians.\n\nThe Umayyad period established several enduring features of Islamic civilization: Arabic as the administrative and cultural language across the empire (replacing Greek, Persian, and Coptic in administration), the gold dinar and silver dirham as the Islamic monetary standard, the construction of iconic early Islamic monuments (the Dome of the Rock in Jerusalem, 691 CE; the Great Mosque of Damascus, 706-714 CE), and the first systematic translation movement of Greek scientific texts into Arabic. The Umayyad Caliphate's overthrow by the Abbasids in 750 CE (one surviving branch established the Emirate of Córdoba in Spain) ended the Umayyad dynasty's rule.",
        "causes": ["Muawiyah ibn Abi Sufyan's 661 CE succession establishing first hereditary Islamic dynasty from Damascus", "Syrian military base providing Umayyad political and military power through Muawiyah's governorship", "Extraordinary military commanders enabling rapid conquest of Iberian Peninsula and Central Asia simultaneously", "Arabic administrative language adoption enabling governance across enormously diverse conquered territories"],
        "effects": ["Islamic world expanding from Spain to Central Asia and Sindh within 90 years of Muhammad's death", "Arabic establishing as administrative and cultural language across the empire replacing Greek, Persian, and Coptic", "Dome of the Rock (691 CE) and Great Mosque of Damascus (706-714 CE) as iconic early Islamic monuments", "Battle of Poitiers/Tours (732 CE) marking the western limit of Umayyad expansion in Europe"],
        "relationships": [{"entity": "Dome of the Rock", "relationship": "ICONIC_691_CE_JERUSALEM_MONUMENT_BUILT_BY_UMAYYAD_CALIPH_ABD_AL-MALIK", "note": "The Dome of the Rock (691 CE) was built by Umayyad Caliph Abd al-Malik as one of Islam's earliest iconic monuments"}, {"entity": "Battle of Poitiers", "relationship": "WESTERN_EXPANSION_LIMIT_IN_FRANCE_732_CE_UNDER", "note": "The Battle of Poitiers (732 CE) marked the limit of Umayyad expansion in Western Europe"}, {"entity": "Abbasid Caliphate", "relationship": "OVERTHROWN_BY_750_CE_REVOLUTION_ESTABLISHING", "note": "The Umayyad Caliphate was overthrown by the Abbasid revolution in 750 CE"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Umayyad Caliphate — expanding Islam from Spain to Central Asia, building the Dome of the Rock, establishing Arabic as the imperial language — is one of history's most consequential empires whose territorial expansion spread Islam across territories with Muslim majorities today.", "significanceCategory": "world-changing"},
    }),
    ("la-scala-milan", "data/appwrite-export/entities/363-Class-363", "363", {
        "summary": "La Scala (Teatro alla Scala) in Milan — opened on August 3, 1778, built to replace the Ducal Theatre destroyed by fire in 1776 — is the world's most prestigious opera house and the supreme institution of Italian opera culture, the stage where the great operas of Rossini, Donizetti, Bellini, Verdi, and Puccini premiered or achieved their canonical performances, and where the world's greatest opera singers (from Maria Callas to Luciano Pavarotti to Plácido Domingo) have defined operatic standards.\n\nLa Scala's premieres constitute a who's who of operatic masterworks: Verdi's Nabucco (1842, whose 'Va, Pensiero' chorus became an Italian patriotic anthem during the Risorgimento), Otello (1887), and Falstaff (1893); Puccini's La Gioconda, Madama Butterfly (revised premiere 1904), and Turandot (posthumous premiere 1926); and Bellini's La Sonnambula (1831) and Norma (1831). The neoclassical facade and the tiers of red-and-gold boxes create one of music history's most legendary performance spaces.\n\nLa Scala's role in Italian national identity is profound: during the Risorgimento (Italian unification movement 1848-1871), Verdi's operas at La Scala were political events, with audience demonstrations for Italian unity ('Viva Verdi' a double meaning — 'Long live Verdi' and acronym for 'Viva Vittorio Emanuele Re D'Italia'). The annual December 7 opening night (St. Ambrose's Day, Milan's patron saint) is Italy's most socially significant cultural event, with Italy's president, business elite, and international celebrities attending.",
        "causes": ["1776 fire destroying the Ducal Theatre prompting the Empress Maria Theresa to commission a new opera house", "Milan's Neoclassical architectural fashion of 1778 shaping the new theatre's design by Giuseppe Piermarini", "Italian operatic tradition requiring a premiere venue worthy of the period's greatest composers and singers", "Milan's commercial and cultural wealth as the Habsburg Italian capital funding La Scala's construction"],
        "effects": ["Verdi premieres (Nabucco 1842, Otello 1887, Falstaff 1893) defining Italian operatic culture and Risorgimento identity", "Puccini premieres (Madama Butterfly, Turandot) cementing La Scala as the world's supreme opera house", "December 7 opening night becoming Italy's most significant annual social and cultural event", "Maria Callas's La Scala performances defining soprano standards for subsequent generations"],
        "relationships": [{"entity": "Giuseppe Verdi", "relationship": "MASTERWORKS_PREMIERING_AT_LA_SCALA_INCLUDING_NABUCCO_OTELLO_AND_FALSTAFF", "note": "Verdi's greatest operas premiered at La Scala, making it the supreme institution of Italian operatic culture"}, {"entity": "Maria Callas", "relationship": "DEFINING_SOPRANO_WHOSE_LA_SCALA_PERFORMANCES_SET_STANDARDS_FOR_GENERATIONS", "note": "Maria Callas's performances at La Scala defined soprano standards for subsequent generations"}, {"entity": "Italian Risorgimento", "relationship": "VERDI_OPERAS_AT_LA_SCALA_SERVING_AS_POLITICAL_EVENTS_FOR", "note": "Verdi's La Scala operas served as political events during the Italian Risorgimento unification movement"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "La Scala — where Verdi, Puccini, and Bellini's masterworks premiered, where Callas defined soprano standards, Milan's supreme cultural institution — is historically significant as the world's most prestigious opera house and the institutional center of Italian opera culture.", "significanceCategory": "world-changing"},
    }),
    ("royal-opera-house-london", "data/appwrite-export/entities/363-Class-363", "363", {
        "summary": "The Royal Opera House in Covent Garden, London — opened in its current form in 1858 (the third theatre on the site, previous versions opened in 1732 and 1809) — is Britain's premier opera and ballet venue, home to the Royal Opera and The Royal Ballet, one of the world's most prestigious performing arts institutions whose productions have defined British cultural achievement in music and dance for over 170 years.\n\nThe Royal Opera House's history extends to 1732 when the first theatre on the site (built by architect Edward Shepherd) presented theatre, opera, and pantomime. Handel composed works specifically for the original theatre (where many of his oratorios premiered). The 1858 building — designed by Edward Middleton Barry in a neo-Renaissance style with its distinctive colonnade — is one of London's most recognizable cultural landmarks, and the backstage areas are among the most technically sophisticated in the world, with machinery supporting the Royal Ballet's productions.\n\nThe Royal Ballet — founded by Ninette de Valois in 1931 as the Vic-Wells Ballet, achieving Royal Charter in 1956 — is one of the world's three supreme ballet companies (alongside the Bolshoi and the Paris Opéra Ballet), home to generations of legendary dancers from Margot Fonteyn (whose partnership with Rudolf Nureyev in the 1960s-70s is one of ballet history's greatest artistic collaborations) to Darcey Bussell and today's stars. The Royal Ballet's productions of Swan Lake, The Sleeping Beauty, and Giselle are reference performances in classical ballet.",
        "causes": ["1732 original theatre construction providing the site for subsequent opera houses", "Handel's compositions for the theatre establishing the site's connection to major musical creativity", "1858 Barry building creating the current neo-Renaissance venue with sophisticated technical infrastructure", "Ninette de Valois's 1931 Vic-Wells Ballet founding creating what would become the Royal Ballet"],
        "effects": ["Royal Ballet founding becoming one of world's three supreme ballet companies alongside Bolshoi and Paris Opera", "Margot Fonteyn and Rudolf Nureyev partnership defining one of ballet history's greatest artistic collaborations", "Royal Opera productions and recordings setting international standards for operatic performance", "Covent Garden as Britain's premier performing arts venue hosting world-class opera and ballet seasons"],
        "relationships": [{"entity": "Royal Ballet", "relationship": "HOME_VENUE_OF_ONE_OF_WORLD'S_THREE_SUPREME_BALLET_COMPANIES", "note": "The Royal Opera House is the home venue of the Royal Ballet, one of the world's three supreme ballet companies"}, {"entity": "Margot Fonteyn and Rudolf Nureyev", "relationship": "STAGE_FOR_ONE_OF_BALLET_HISTORY'S_GREATEST_ARTISTIC_PARTNERSHIPS", "note": "Fonteyn and Nureyev's legendary partnership was centered on the Royal Opera House"}, {"entity": "George Frideric Handel", "relationship": "ORIGINAL_THEATRE_SITE_WHERE_HANDEL_COMPOSED_AND_PREMIERED_WORKS", "note": "Handel composed works for the original 1732 Covent Garden theatre"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Royal Opera House — home to the Royal Ballet and Royal Opera, stage for Fonteyn-Nureyev's legendary partnership — is historically significant as Britain's premier performing arts institution and one of the world's supreme venues for opera and classical ballet.", "significanceCategory": "world-changing"},
    }),
    ("motown-records", "data/appwrite-export/entities/364-Class-364", "364", {
        "summary": "Motown Records — founded in Detroit, Michigan, in 1959 by Berry Gordy Jr. with an $800 loan — is one of the most consequential record labels in music history: the first Black-owned entertainment empire, the creator of the 'Motown Sound' (polished pop-soul combining gospel, rhythm and blues, and pop sensibilities), and the institution that brought African American music into white mainstream America during the Civil Rights era in a way that — some cultural historians argue — contributed to racial integration as powerfully as any political movement.\n\nMotown's artist roster from 1959-1972 constitutes the most extraordinary assembly of musical talent in popular music history: Stevie Wonder, Marvin Gaye, Diana Ross and the Supremes, The Temptations, The Four Tops, Smokey Robinson and the Miracles, Martha and the Vandellas, The Jackson 5 (launching Michael Jackson's career), Gladys Knight and the Pips, Lionel Richie and the Commodores, and many others. Berry Gordy's 'Hit and Quality' factory model — with in-house songwriting teams (Holland-Dozier-Holland), session musicians (the Funk Brothers), and artist development/etiquette training — created a pop production system of unprecedented effectiveness.\n\nMotown's cultural impact extended beyond music: its artists appeared on mainstream television shows (The Ed Sullivan Show, The Tonight Show) that had rarely featured Black performers, their success demonstrating to white mainstream America the talent and sophistication of Black artists. Marvin Gaye's What's Going On (1971) — produced against Berry Gordy's wishes — became a landmark political album addressing the Vietnam War, poverty, and racial injustice, demonstrating that Motown could transcend pop to social commentary.",
        "causes": ["Berry Gordy's 1959 $800 loan founding Motown as the first Black-owned entertainment empire in Detroit", "Detroit's Black community providing extraordinary musical talent concentration for Gordy's artist roster", "Holland-Dozier-Holland songwriting team and Funk Brothers session musicians creating the distinctive Motown Sound", "Civil Rights era providing both the social context and the commercial opportunity for integrated pop music"],
        "effects": ["Motown becoming the first Black-owned entertainment empire with global commercial success", "Motown Sound bringing African American music into white mainstream America during Civil Rights era", "Michael Jackson's Jackson 5 debut (1969) launching the most commercially successful music career in history", "Marvin Gaye's What's Going On (1971) demonstrating soul music's capacity for social and political commentary"],
        "relationships": [{"entity": "Berry Gordy Jr.", "relationship": "FOUNDED_AND_BUILT_INTO_FIRST_BLACK_ENTERTAINMENT_EMPIRE_BY", "note": "Berry Gordy founded Motown in 1959 with an $800 loan, building it into the first Black-owned entertainment empire"}, {"entity": "Marvin Gaye", "relationship": "WHAT'S_GOING_ON_1971_TRANSCENDING_POP_TO_POLITICAL_COMMENTARY_ON_MOTOWN", "note": "Marvin Gaye's What's Going On (1971) was recorded against Gordy's wishes and became a landmark political album"}, {"entity": "Jackson 5 Michael Jackson", "relationship": "MOTOWN_DEBUT_LAUNCHING_MOST_COMMERCIALLY_SUCCESSFUL_MUSIC_CAREER", "note": "The Jackson 5's Motown debut (1969) launched Michael Jackson's career toward becoming the world's most commercially successful musician"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "Motown Records — the first Black entertainment empire, creating the soundtrack of the Civil Rights era, launching Michael Jackson, and bringing African American music to white mainstream America — is one of the most culturally consequential record labels in history.", "significanceCategory": "world-changing"},
    }),
    ("universal-music-group", "data/appwrite-export/entities/364-Class-364", "364", {
        "summary": "Universal Music Group (UMG) — founded in 1934 as Decca Records in the United States, becoming MCA Records, then Universal Music Group following Seagram's 1998 acquisition of PolyGram to create the world's largest music company — is the world's largest music company with approximately 30-35% global market share, owning a catalog including hundreds of thousands of recordings from virtually every genre and era of recorded music, from Beethoven to The Beatles to Taylor Swift.\n\nUMG's catalog includes some of the most commercially and culturally significant recordings in history: The Beatles' catalogue (acquired through PolyGram's acquisition, originally on Capitol Records, a UMG subsidiary); Billie Holiday's recordings; Louis Armstrong's catalog; Miles Davis's Columbia catalog; Bob Dylan's early recordings; and contemporary artists including Taylor Swift (whose conflict over her master recordings with former UMG subsidiary Republic Records led to her re-recording her first six albums), Billie Eilish, Kendrick Lamar, and hundreds of others. The company's subsidiaries include Universal Records, Interscope, Republic Records, Def Jam, Island, Verve, Deutsche Grammophon, and many others.\n\nUMG's 2021 IPO on the Euronext Amsterdam stock exchange valued the company at approximately €33 billion, making it one of the world's most valuable media companies. The company's negotiations with digital streaming platforms (Spotify, Apple Music, Amazon) define the economics of digital music, with UMG's licensing agreements determining royalty rates for millions of artists. UMG's 2023 dispute with TikTok (removing UMG music from the platform over royalty disagreements) demonstrated the company's power to reshape digital music distribution.",
        "causes": ["1934 Decca Records founding providing the corporate ancestor of Universal Music Group", "Seagram's 1998 acquisition of PolyGram creating the world's largest music company through catalog consolidation", "Music industry consolidation from hundreds of labels to three major companies (UMG, Sony, Warner) in 1990s-2000s", "Digital revolution requiring large catalog holders to negotiate streaming rates with tech platforms"],
        "effects": ["UMG controlling approximately 30-35% of global recorded music market as the world's largest music company", "2021 €33 billion Euronext IPO making UMG one of the world's most valuable media companies", "Taylor Swift master recordings dispute triggering her re-recording and broader artist rights discussion", "2023 TikTok dispute demonstrating UMG's power to reshape digital music distribution economics"],
        "relationships": [{"entity": "The Beatles", "relationship": "CATALOG_OF_MOST_COMMERCIALLY_SIGNIFICANT_BAND_IN_HISTORY_IN_UMG_HOLDINGS", "note": "The Beatles' catalog is among UMG's most valuable holdings through its Capitol Records subsidiary"}, {"entity": "Taylor Swift", "relationship": "MASTER_RECORDINGS_DISPUTE_TRIGGERING_RE-RECORDING_AND_ARTIST_RIGHTS_DEBATE", "note": "Taylor Swift's dispute over her masters with UMG's former subsidiary triggered her re-recording and a broader artist rights debate"}, {"entity": "Spotify Apple Music", "relationship": "LICENSING_NEGOTIATIONS_WITH_STREAMING_PLATFORMS_DEFINING_DIGITAL_MUSIC_ECONOMICS", "note": "UMG's licensing negotiations with Spotify, Apple Music, and Amazon determine royalty rates for millions of artists"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Universal Music Group — controlling 30-35% of global recorded music, owner of The Beatles' catalog, shaper of digital music economics — is historically significant as the world's largest music company whose licensing decisions affect hundreds of millions of artists and listeners globally.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data, folder, prefix):
    fname = os.path.join(folder, f"{prefix}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 150 — MIXED: Class 311(2) + 312(2) + 363(2) + 364(2): Final Mixed Batch")
    for slug, folder, prefix, data in ENTITIES:
        enrich_entity(slug, data, folder, prefix)
    print("Done.")
