#!/usr/bin/env python3
"""Batch 142 — Class 340 Religious Orgs VII: Global Christian Churches (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/340-Class-340"
FILE_PREFIX = "340"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("church-of-the-east", {
        "summary": "The Church of the East (ܥܕܬܐ ܕܡܕܢܚܐ, ʿĒḏtā ḏ-Maḏnḥā), also called the Nestorian Church or the Assyrian Church of the East — is one of the oldest Christian churches in the world, tracing its origins to the apostolic mission of Thomas and Thaddaeus to Mesopotamia in the 1st century CE and developing as the major Christian tradition of the Persian (Sasanian) Empire and subsequently spreading across Central Asia, India, and China, reaching the Tang Dynasty court in China in 635 CE and establishing Christianity in parts of Asia centuries before European missionary efforts.\n\nThe Church of the East's extraordinary medieval geographic expansion made it, at its height (roughly 8th-13th centuries), the world's most geographically extensive Christian denomination — with dioceses stretching from Mesopotamia (the theological and patriarchal center) across Persia, through Central Asia along the Silk Road, reaching China (the Nestorian Stele of Xi'an, 781 CE, documents its presence), India (the Saint Thomas Christians of Kerala), and having communities among Mongol tribes. The Mongol Empire period saw the Church of the East particularly flourish, as several Mongol queens and generals were Eastern Christians.\n\nThe Mongol Empire's collapse and Timur's 14th-century massacres (particularly devastating for Eastern Christian communities) catastrophically reduced the Church of the East. The surviving community (primarily in the Urmia/Hakkari highlands region) suffered the Seyfo genocide in WWI and subsequent dispersal. The modern Assyrian Church of the East is the surviving remnant of this ancient tradition.",
        "causes": ["Apostolic founding tradition tracing to Thomas and Thaddaeus mission to Mesopotamia in 1st century CE", "Persian Empire's position as the Church of the East's home territory giving it distinct Syriac theological tradition", "Silk Road trade networks providing pathways for Church of the East missionary expansion across Central Asia to China", "Mongol royal patronage during the Mongol Empire period enabling the church's greatest geographic extent"],
        "effects": ["Church of the East reaching China by 635 CE documented in the 781 Nestorian Stele of Xi'an", "Saint Thomas Christians of Kerala representing the Church's 2000-year-old presence in India", "Timur's 14th-century massacres and subsequent WWI Seyfo genocide reducing the church to a small remnant", "Modern Assyrian Church of the East as the surviving continuation of one of Christianity's most ancient traditions"],
        "relationships": [{"entity": "Silk Road", "relationship": "MISSIONARY_EXPANSION_PATHWAY_ALONG_CENTRAL_ASIAN_ROUTES_OF", "note": "The Church of the East spread across Central Asia to China along the Silk Road trade networks"}, {"entity": "Nestorian Stele", "relationship": "DOCUMENTED_BY_781_CHINESE_MONUMENT_AT_XI'AN", "note": "The 781 Nestorian Stele at Xi'an documents the Church of the East's Tang Dynasty Chinese presence"}, {"entity": "Saint Thomas Christians", "relationship": "INDIAN_COMMUNITY_TRACING_ORIGIN_TO_APOSTOLIC_MISSION_OF", "note": "Kerala's Saint Thomas Christians represent a 2000-year-old Church of the East presence in India"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Church of the East — once Christianity's most geographically extensive denomination reaching China along the Silk Road, nearly destroyed by Timur and WWI genocide — is historically significant as one of Christianity's most ancient and geographically adventurous traditions, now reduced to a small remnant.", "significanceCategory": "world-changing"},
    }),
    ("church-of-cyprus", {
        "summary": "The Church of Cyprus (Greek: Εκκλησία της Κύπρου, Ekklisia tis Kyprou) is one of the oldest autocephalous Orthodox Christian churches, founded according to tradition by the apostles Barnabas and Paul during their first missionary journey (Acts 13) — receiving formal autocephalous status at the Council of Ephesus in 431 CE, making it one of the earliest churches to achieve independence from Constantinople and one of the few pre-Schism churches with documented ancient self-governance.\n\nCyprus's ecclesiastical history reflects the island's complex political history: Byzantine, Frankish (Lusignan Crusader period 1192-1489), Venetian (1489-1571), and Ottoman (1571-1878) rule shaped the Church of Cyprus's role as the institutional guardian of Greek Cypriot identity when political sovereignty was foreign. During the Ottoman period, the Archbishop of Cyprus held the role of Ethnarch (ethnic leader) — the political representative of the Greek Cypriot community — a role that made the archbishop simultaneously religious and civil leader, a tradition continuing into the modern era.\n\nArchbishop Makarios III embodied this church-state fusion most dramatically: the Church of Cyprus Archbishop became Cyprus's first president (1960) when the island achieved independence from British rule. This church-state integration reflected the Eastern Orthodox tradition of symphonia (church-state cooperation) but in a more direct form than most Orthodox countries. The 1974 Turkish invasion and division of Cyprus (with approximately 37% of the island under Turkish control since 1974) has made the Church of Cyprus a significant voice for reunification advocacy.",
        "causes": ["Apostolic founding by Barnabas and Paul during first missionary journey establishing Cyprus's Christian tradition", "431 CE Council of Ephesus formally recognizing Cypriot church's autocephalous status", "Ottoman millet system giving Archbishop political as well as religious authority over Greek Cypriots", "Cyprus independence movement (1960) using the church as institutional foundation for nationalist politics"],
        "effects": ["Archbishop Makarios III becoming Cyprus's first president demonstrating church-state fusion in Orthodox tradition", "1974 Turkish invasion and occupation making the Church a major advocacy voice for reunification", "Church of Cyprus maintaining Greek Cypriot identity through centuries of foreign political rule", "Autocephalous status since 431 CE making Church of Cyprus one of Christianity's oldest independent churches"],
        "relationships": [{"entity": "Archbishop Makarios III", "relationship": "ARCHBISHOP_WHO_BECAME_CYPRUS'S_FIRST_PRESIDENT_EMBODYING_CHURCH-STATE_ROLE", "note": "Makarios III served simultaneously as Archbishop and Cyprus's first president (1960-1977)"}, {"entity": "Cyprus Division 1974", "relationship": "CHURCH_ADVOCACY_FOR_REUNIFICATION_FOLLOWING", "note": "The 1974 Turkish invasion dividing Cyprus made the Church of Cyprus a major voice for island reunification"}, {"entity": "Eastern Orthodox Autocephaly", "relationship": "ONE_OF_OLDEST_AUTOCEPHALOUS_CHURCHES_IN_SYSTEM_OF", "note": "Church of Cyprus received formal autocephalous status in 431 CE, making it one of the oldest independent Orthodox churches"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Church of Cyprus — autocephalous since 431 CE, guardian of Greek Cypriot identity through Byzantine, Crusader, and Ottoman rule, producing Cyprus's first president — is historically significant as one of Christianity's oldest independent churches and a central institution of Cypriot national identity.", "significanceCategory": "world-changing"},
    }),
    ("coptic-orthodox-church", {
        "summary": "The Coptic Orthodox Church of Alexandria is one of the world's oldest Christian churches — claiming founding by the Evangelist Mark in Alexandria, Egypt in approximately 42 CE — and represents the largest Christian community in the Middle East (approximately 10-15 million Copts, roughly 10% of Egypt's population) as well as a worldwide diaspora, maintaining one of the most ancient and unbroken Christian traditions in the world across nearly two millennia of continuous worship in Egypt.\n\nCoptic Christianity is extraordinarily ancient: the Coptic language (a descendant of ancient Egyptian, written in a Greek-derived alphabet) is still used in Coptic liturgy — representing one of the world's most ancient languages in continuous religious use, a direct link to ancient Egyptian civilization that predates the Arab conquest of Egypt (641 CE). Coptic art and iconography have distinctive ancient Egyptian aesthetic influences visible in icon painting styles, representing a unique synthesis of ancient Egyptian, Hellenistic, and Christian traditions.\n\nThe Coptic community has faced severe persecution: the Roman persecutions (particularly Diocletian's Great Persecution of 303-311 CE — still commemorated in the Coptic calendar beginning from 284 CE as the 'Era of Martyrs'), the subsequent Chalcedonian/non-Chalcedonian split that divided Eastern Christianity, and most recently in modern Egypt — attacks on Coptic churches, homes, and businesses (particularly during the 2011-2013 period of Islamic extremist violence), discrimination in education and employment, and barriers to church construction. Pope Tawadros II leads the church in the contemporary period.",
        "causes": ["Apostolic founding tradition tracing to Saint Mark's Alexandria mission in approximately 42 CE", "Ancient Egyptian Christian community's continuity through Roman, Byzantine, and Arab Islamic rule over 2000 years", "Chalcedonian controversy (451 CE) splitting Eastern Christianity with Coptic Church maintaining non-Chalcedonian Miaphysite theology", "Egyptian Arab conquest (641 CE) creating the minority Christian status that defines the Coptic community's subsequent history"],
        "effects": ["Coptic language preservation in liturgy maintaining the only living descendant of ancient Egyptian language", "Coptic icon tradition preserving ancient Egyptian aesthetic synthesis with Christian imagery", "Coptic community facing periodic persecution in modern Egypt including church attacks and civil discrimination", "Coptic diaspora spreading Coptic Christianity to North America, Europe, and Australia in the modern period"],
        "relationships": [{"entity": "Saint Mark", "relationship": "FOUNDED_BY_EVANGELIST_TRADITION_OF_ALEXANDRIA_MISSION_OF", "note": "The Coptic Church traces its foundation to Saint Mark's evangelization of Alexandria in approximately 42 CE"}, {"entity": "Coptic Language", "relationship": "LITURGICAL_LANGUAGE_PRESERVING_DESCENDANT_OF_ANCIENT_EGYPTIAN", "note": "The Coptic language used in Coptic liturgy is the direct descendant of ancient Egyptian, maintaining the last link to ancient Egyptian language"}, {"entity": "Arab Conquest of Egypt", "relationship": "TRANSFORMED_MAJORITY_CHURCH_INTO_MINORITY_CHRISTIAN_COMMUNITY_AFTER_641", "note": "The 641 CE Arab conquest transformed Egypt from a predominantly Christian to a Muslim-majority country, making Copts a minority"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Coptic Orthodox Church — claiming 2000 years of continuous Egyptian Christian tradition, preserving ancient Egyptian language in liturgy, representing the Middle East's largest Christian community — is historically significant as one of Christianity's most ancient traditions and a monument to Christian survival under Islamic majority rule.", "significanceCategory": "world-changing"},
    }),
    ("ethiopian-orthodox-tewahedo-church", {
        "summary": "The Ethiopian Orthodox Tewahedo Church (Amharic: የኢትዮጵያ ኦርቶዶክስ ተዋሕዶ ቤተ ክርስቲያን, Yä-Ityop'ya Ortodoks Täwahedo Bétä Kristiyan) is one of the world's oldest Christian churches — claiming connection to the 4th-century mission of Frumentius (ordained by Athanasius of Alexandria in approximately 330 CE), making Ethiopia one of the world's first Christian nations, while tradition also traces roots to the eunuch of Queen Candace baptized by Philip the Evangelist (Acts 8) — representing a Christian tradition that has maintained unbroken institutional continuity for approximately 1700 years.\n\nEthiopian Christianity has unique characteristics distinguishing it from both Western and Eastern Orthodox traditions: the Ethiopian Bible includes 81 books (including books not found in Catholic, Protestant, or Eastern Orthodox canons, such as 1 Enoch and Jubilees — texts that were preserved in Ethiopia when lost elsewhere), the Ark of the Covenant is traditionally held at Axum's Church of Our Lady Mary of Zion, Saturday is observed as Sabbath alongside Sunday worship, dietary laws similar to Jewish kashrut are observed, and the church has had intimate connections with Ethiopian statecraft through the Solomonic dynasty's claims of descent from Solomon and the Queen of Sheba.\n\nThe Tewahedo Church (Tewahedo meaning 'unified' in Amharic, referring to its non-Chalcedonian Miaphysite Christology) was autocephalous from 1959 and was intimately connected to imperial Ethiopian identity — Emperor Haile Selassie was the last Solomonic dynasty emperor, whose overthrow by the Derg in 1974 radically altered the church's state relationship. The church also inspired the Rastafari movement (which regards Haile Selassie as divine).",
        "causes": ["4th-century Frumentius mission making Ethiopia one of the world's first Christian nations", "Solomonic dynasty's claims of descent from Solomon and Queen of Sheba creating church-state fusion in Ethiopian imperial identity", "Isolation from Mediterranean Christianity allowing Ethiopian tradition to develop unique characteristics including the 81-book canon", "Ethiopian Orthodox Christianity's preservation of ancient texts (1 Enoch, Jubilees) lost in other Christian traditions"],
        "effects": ["Ethiopian Orthodox tradition preserving 1 Enoch and Jubilees as canonical texts lost in Western and Eastern Orthodox traditions", "Rastafari movement's global spread inspired by Ethiopian Orthodox Christianity and Haile Selassie's imperial tradition", "Tewahedo Church's 1959 autocephaly from Alexandria establishing independent Ethiopian Orthodox governance", "Derg overthrow of Haile Selassie (1974) radically disrupting the church-state fusion of Ethiopian imperial Christianity"],
        "relationships": [{"entity": "Haile Selassie", "relationship": "LAST_SOLOMONIC_EMPEROR_AND_CENTRAL_FIGURE_IN_STATE_CHURCH_FUSION_OF", "note": "Haile Selassie embodied the Ethiopian imperial-ecclesiastical tradition, with his overthrow disrupting the church's state role"}, {"entity": "Rastafari Movement", "relationship": "ETHIOPIAN_ORTHODOX_TRADITION_INSPIRING_GLOBAL", "note": "The Rastafari movement draws heavily from Ethiopian Orthodox Christianity and the Solomonic imperial tradition"}, {"entity": "Book of Enoch", "relationship": "PRESERVED_IN_ETHIOPIAN_ORTHODOX_CANON_WHEN_LOST_FROM_OTHER_TRADITIONS", "note": "The Ethiopian Orthodox canon preserved 1 Enoch and other texts that were lost from Catholic, Protestant, and Eastern Orthodox Bibles"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Ethiopian Orthodox Tewahedo Church — one of Christianity's oldest national churches, preserving unique ancient texts, inspiring Rastafari globally — is historically significant as one of the world's most ancient Christian traditions and a monument to Ethiopian civilization's extraordinary cultural heritage.", "significanceCategory": "world-changing"},
    }),
    ("greek-orthodox-church-of-antioch", {
        "summary": "The Greek Orthodox Patriarchate of Antioch and All the East is one of the original four patriarchates of early Christianity — established at Antioch (in modern-day Turkey, near the Syrian border), the city where followers of Jesus were first called Christians (Acts 11:26), making it arguably the original center of organized Christianity before Constantinople superseded it. Today headquartered in Damascus, Syria, the Antiochian Church serves primarily Arabic-speaking Orthodox Christians across the Middle East, with a significant diaspora in North and South America and Australia.\n\nAntioch's theological significance in early Christianity was enormous: it was a major center of early Christian theology, the missionary base for Paul's three missionary journeys, the home of key early Christian thinkers including John Chrysostom (Patriarch of Constantinople) and Ignatius of Antioch (martyred approximately 107 CE), and one of the sites of early Christological debates. The ancient city's theological legacy is embedded in the name 'Christian' itself — first used at Antioch.\n\nThe modern Antiochian Orthodox Church serves primarily Arab Orthodox Christians, with Arabic as its primary liturgical and pastoral language, while also having developed significant English-language Western Rite communities in North America (including many Anglican and Catholic converts to Orthodox Christianity). The Syrian Civil War (2011-present) has profoundly affected the church's home community — approximately 2 million Syrian Christians have fled the country, devastating the ancient Christian communities that the Antiochian Church serves.",
        "causes": ["Antioch's role as original center of organized Christianity where followers were first called Christians", "Paul's missionary journeys based at Antioch establishing the church's early missionary centrality", "Early Christian theological development at Antioch producing major thinkers including Ignatius and John Chrysostom", "Arabic-speaking Orthodox Christians of the Middle East requiring a patriarchate serving their linguistic and cultural community"],
        "effects": ["Antiochian Orthodox Church serving as primary institution for Arab Orthodox Christians in the Middle East for 2000 years", "Western Rite communities in North America providing Orthodox home for Anglican and Catholic converts", "Syrian Civil War devastating the ancient Syrian Christian communities the Antiochian Church serves", "Name 'Christian' originating at Antioch making the patriarchate's origin historically foundational for all Christianity"],
        "relationships": [{"entity": "Early Christianity", "relationship": "ORIGINAL_ORGANIZING_CENTER_WHERE_FOLLOWERS_OF_JESUS_FIRST_CALLED_CHRISTIANS", "note": "Antioch was the city where followers of Jesus were first called Christians (Acts 11:26), making it foundational to Christian identity"}, {"entity": "Syrian Civil War", "relationship": "DEVASTATING_HOME_COMMUNITY_OF_2_MILLION_CHRISTIAN_REFUGEES_FROM", "note": "The Syrian Civil War has driven approximately 2 million Syrian Christians from their ancient homeland, severely affecting the Antiochian Church"}, {"entity": "Paul the Apostle", "relationship": "MISSIONARY_JOURNEYS_BASED_AT_ANTIOCH_EXPANDING_CHURCH_FOUNDED_IN", "note": "Paul's three missionary journeys were based at Antioch, making the Antiochian church central to early Christian expansion"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Greek Orthodox Patriarchate of Antioch — site where followers of Jesus were first called Christians, one of the four original patriarchates — is historically significant as one of Christianity's foundational institutions, now facing devastating losses from the Syrian Civil War.", "significanceCategory": "world-changing"},
    }),
    ("maronite-church", {
        "summary": "The Maronite Church (Syriac: ܥܕܬܐ ܡܪܘܢܝܬܐ, ʿĒḏtā Māronāytā) is an Eastern Catholic church in full communion with the Pope of Rome — one of 23 Eastern Catholic churches — maintaining the Antiochene liturgical tradition (West Syriac rite) and tracing its origins to the 5th-6th-century Syrian monastic movement centered on Saint Maron and his disciples. The Maronites are unique among Eastern Catholic churches in never having had a period of formal separation from Rome and in being specifically Lebanese in their historical heartland.\n\nThe Maronite Church is inextricably linked with Lebanese national identity: Lebanon was carved out as a distinct entity partly to create a homeland where Maronite Christians would have political dominance (under French Mandate influence), and the Lebanese National Pact of 1943 (the unwritten agreement distributing political power among Lebanon's religious communities) reserved the presidency for Maronites, the prime ministership for Sunni Muslims, and the parliamentary speakership for Shia Muslims. This confessional system made the Maronite community central to Lebanese statehood.\n\nLebanon's political crises — the 1975-1990 Civil War (approximately 150,000-250,000 dead), the 2006 Hezbollah-Israel war, the 2019-2020 economic collapse, the 2020 Beirut port explosion, and the country's ongoing political paralysis — are all deeply connected to the confessional system in which the Maronite Church has been a central actor. The Maronite diaspora (Lebanese diaspora communities in Brazil, Argentina, Mexico, the United States, and Australia) is one of the largest relative to the home population, with more Maronites living outside Lebanon than within it.",
        "causes": ["5th-6th century Saint Maron's Syrian monastic movement establishing the Maronite monastic and theological tradition", "Maronites' Lebanese mountain strongholds providing geographic base for cultural and religious preservation during Arab and Ottoman rule", "French Mandate in Lebanon (1920-1943) privileging Maronite community in the creation of Greater Lebanon", "1943 Lebanese National Pact creating confessional political system with Maronite presidency as central feature"],
        "effects": ["Lebanese confessional political system with Maronite presidency creating the framework for Lebanese statehood and its crises", "Lebanese Civil War (1975-1990) devastating the Maronite community and triggering massive emigration", "Maronite diaspora larger than home community with communities throughout Latin America and beyond", "Maronite Church as unique Eastern Catholic church never separated from Rome maintaining Syriac liturgical tradition"],
        "relationships": [{"entity": "Lebanon", "relationship": "NATIONAL_CHURCH_WHOSE_IDENTITY_IS_INEXTRICABLY_LINKED_TO_STATEHOOD_OF", "note": "The Maronite Church is inextricably linked to Lebanese national identity, with the presidency reserved for Maronites"}, {"entity": "Lebanese Civil War", "relationship": "MAJOR_ACTOR_IN_DEVASTATING_1975-1990_CONFLICT_OF", "note": "The Maronite community was central to the Lebanese Civil War that killed 150,000-250,000 people and triggered massive emigration"}, {"entity": "Eastern Catholic Churches", "relationship": "UNIQUE_MEMBER_OF_NEVER_HAVING_SEPARATED_FROM_ROME_AMONG", "note": "The Maronite Church is unique among Eastern Catholic churches in never having had a formal period of separation from Roman communion"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Maronite Church — central to Lebanese national identity, never separated from Rome while maintaining Syriac liturgical tradition, central actor in Lebanon's Civil War — is historically significant as the ecclesiastical pillar of Lebanese statehood and one of the most politically consequential Christian communities in the modern Middle East.", "significanceCategory": "world-changing"},
    }),
    ("church-of-jesus-christ-of-latter-day-saints", {
        "summary": "The Church of Jesus Christ of Latter-day Saints (LDS Church), founded by Joseph Smith in 1830 in Fayette, New York — is one of the world's most significant religious organizations founded in the 19th century, claiming approximately 17 million members worldwide, with particular strength in the Western United States, Latin America (particularly Brazil and Mexico), and growing presence globally, representing a uniquely American religious tradition that has grown from a tiny frontier sect into a major world religion.\n\nJoseph Smith's founding narrative — the Book of Mormon as an additional scripture translated from golden plates, restorationist theology claiming to restore original Christianity, continuing revelation through a living prophet — created a religion that mainstream Christians consider outside traditional Christianity while LDS members consider themselves fully Christian. This theological liminal status has shaped the LDS Church's complex relationship with American society and global religious communities.\n\nThe LDS Church's unique features include: tithing (10% of income) generating approximately $100-150 billion in assets by some estimates; mandatory two-year missionary service for young men (and optional for women and seniors) creating one of the world's largest voluntary missionary programs (approximately 67,000 missionaries at peak); the Word of Wisdom prohibiting coffee, tea, alcohol, and tobacco; genealogical research infrastructure (FamilySearch) that is the world's largest genealogy database; and the Utah-centered cultural community that has made Salt Lake City a major American metropolis shaped by LDS institutional life.",
        "causes": ["Joseph Smith's 1830 founding vision restoring original Christianity through continuing revelation and new scripture", "American frontier religious culture's spiritual seeking creating receptive environment for restorationist movements", "Book of Mormon as additional scripture providing doctrinal foundation for a distinct religious tradition", "Early LDS migration to Utah (1847) under Brigham Young establishing the church's cultural and institutional heartland"],
        "effects": ["LDS Church growing from frontier sect to 17 million member worldwide religion within 200 years", "Utah/Mountain West shaped by LDS institutional culture into a distinctive American regional culture", "FamilySearch genealogy database becoming the world's largest genealogical resource open to all researchers", "LDS missionary program creating one of the world's largest volunteer missionary systems"],
        "relationships": [{"entity": "Joseph Smith", "relationship": "FOUNDED_BY_AND_FIRST_PROPHET_OF", "note": "Joseph Smith founded the LDS Church in 1830, claiming to restore original Christianity through continuing revelation and new scripture"}, {"entity": "Utah", "relationship": "INSTITUTIONAL_AND_CULTURAL_HEARTLAND_ESTABLISHED_IN_1847_MIGRATION_TO", "note": "Brigham Young's 1847 Mormon migration established Utah as the LDS Church's cultural and institutional center"}, {"entity": "American Religion", "relationship": "MOST_SIGNIFICANT_NEW_RELIGION_FOUNDED_IN_19TH-CENTURY", "note": "The LDS Church is one of the most significant new religious traditions to emerge from 19th-century American religious life"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Church of Jesus Christ of Latter-day Saints — from frontier sect to 17 million member world religion, shaping Utah and the American West — is historically significant as the most successful uniquely American religious tradition and one of the world's fastest-growing religions.", "significanceCategory": "world-changing"},
    }),
    ("seventh-day-adventist-church", {
        "summary": "The Seventh-day Adventist Church (SDA), formally organized in 1863 in Battle Creek, Michigan — emerging from the Millerite movement following the 'Great Disappointment' of 1844 (when William Miller's prediction of Christ's return proved unfounded) — is one of the world's most globally distributed Protestant denominations with approximately 21 million members, distinguishing itself by Sabbath worship on Saturday (rather than Sunday), anticipation of Christ's imminent return, health reform teachings that made Adventists pioneers of modern preventive health practices and vegetarianism, and an extraordinary global healthcare and educational network.\n\nThe Adventist health message has had remarkable scientific validation and global cultural impact: the Adventist Health Studies at Loma Linda University (California) — studying the health outcomes of Adventist communities — have been among the most significant longitudinal health research projects in dietary science. Loma Linda, California (home to Loma Linda University and a dense Adventist population) is one of Dan Buettner's famous 'Blue Zones' — the five areas of the world with the longest-lived populations. Adventist dietary practices (plant-based diet, no alcohol or tobacco) correlate with significantly longer life expectancy and lower rates of heart disease and cancer.\n\nThe SDA's global institutional network is extraordinary: approximately 8,000 schools and colleges worldwide (the world's second-largest Protestant educational system after Roman Catholic institutions), approximately 170 hospitals and hundreds of clinics globally (including some of the world's leading medical institutions like Loma Linda University Medical Center), and global missionary presence in nearly every country — creating one of the most globally comprehensive institutional Christian organizations outside of Roman Catholicism.",
        "causes": ["Millerite movement's 1844 'Great Disappointment' reinterpreted as heavenly sanctuary cleansing leading to Adventist founding", "Ellen G. White's prophetic ministry providing theological direction and health reform vision for early Adventism", "Saturday Sabbatarianism as distinctive theological marker separating Adventists from Sunday-worship Protestant traditions", "Health reform movement in 19th-century America aligning with Adventist theology to create distinctive health-focused religious culture"],
        "effects": ["Adventist Health Studies providing scientific validation for plant-based diet and longevity through Loma Linda Blue Zone research", "SDA global educational system as world's second-largest Protestant educational network with 8,000+ schools", "Adventist hospitals including Loma Linda University Medical Center contributing to global healthcare", "Adventist dietary practices (vegetarianism, no alcohol or tobacco) demonstrating measurably longer life expectancy"],
        "relationships": [{"entity": "Millerite Movement", "relationship": "EMERGED_FROM_1844_GREAT_DISAPPOINTMENT_OF", "note": "The SDA Church emerged from the Millerite movement's reinterpretation of the 1844 Great Disappointment"}, {"entity": "Loma Linda Blue Zone", "relationship": "ADVENTIST_COMMUNITY_DEMONSTRATING_LONGEVITY_AS_ONE_OF_WORLD'S", "note": "Loma Linda, California's Adventist community is one of Dan Buettner's five Blue Zones with the world's longest-lived populations"}, {"entity": "Ellen G. White", "relationship": "PROPHETIC_CO-FOUNDER_PROVIDING_THEOLOGICAL_AND_HEALTH_VISION_OF", "note": "Ellen G. White's prophetic ministry shaped Adventist theology, health reform, and global institutional development"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Seventh-day Adventist Church — pioneering plant-based health practices now scientifically validated, operating the world's second-largest Protestant educational system and global hospital network — is historically significant as one of the most globally impactful Protestant denominations in healthcare, education, and dietary science.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 142 — Class 340 Religious Orgs VII: Global Christian Churches")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
