#!/usr/bin/env python3
"""Batch 149 — Class 340 Religious Orgs IX: Global Protestant & Evangelical Churches (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/340-Class-340"
FILE_PREFIX = "340"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("church-of-england", {
        "summary": "The Church of England — founded in 1534 when King Henry VIII broke with Rome following the Pope's refusal to annul his marriage to Catherine of Aragon — is both the mother church of the worldwide Anglican Communion (approximately 85 million members across 165 countries) and the established church of England, with the British monarch as its Supreme Governor and the Archbishop of Canterbury as its spiritual leader, making it one of the most institutionally significant Christian churches in the world.\n\nThe Church of England's founding in the English Reformation created a distinctively English form of Christianity that attempted to occupy a middle way ('via media') between Roman Catholicism and continental Protestantism: retaining the episcopal structure (bishops), liturgy (the Book of Common Prayer, 1549, one of the most influential texts in the English language), and sacramental theology of Catholicism, while rejecting papal authority and incorporating Protestant theological emphases on scripture and faith. The Elizabethan Settlement (1559) defined this compromise in ways that have largely persisted.\n\nThe Church of England's modern challenges are profound: declining attendance (from approximately 40% weekly attendance in the 1960s to approximately 2-3% in recent years), debates about women's ordination (women ordained as priests since 1994, as bishops since 2014), same-sex relationships, and decolonization of its liturgy and governance. Its global Anglican Communion is deeply divided between conservative African provinces (opposing same-sex blessings) and progressive Western provinces, with the 2022 Lambeth Conference revealing possibly irreconcilable divisions.",
        "causes": ["Henry VIII's 1534 Act of Supremacy breaking with Rome following papal refusal to annul his marriage", "English Reformation creating a national church as part of the broader Protestant Reformation", "Elizabethan Settlement (1559) defining the Church of England's via media between Catholicism and Protestantism", "Book of Common Prayer (1549, revised 1662) creating unified English-language liturgy"],
        "effects": ["Anglican Communion founded as a worldwide family of churches comprising approximately 85 million members", "Book of Common Prayer profoundly shaping the English language and literature", "Church of England's established status creating unique Church-State relationship in modern Britain", "Global Anglican Communion deeply divided between conservative African and progressive Western provinces"],
        "relationships": [{"entity": "Henry VIII", "relationship": "FOUNDING_BREAK_WITH_ROME_TRIGGERED_BY", "note": "Henry VIII's Act of Supremacy (1534) founded the Church of England by breaking with papal authority"}, {"entity": "Anglican Communion", "relationship": "MOTHER_CHURCH_OF_85_MILLION_MEMBER_GLOBAL_COMMUNION", "note": "The Church of England is the mother church of the worldwide Anglican Communion of approximately 85 million"}, {"entity": "Book of Common Prayer", "relationship": "DEFINED_BY_DISTINCTIVE_LITURGY_PROFOUNDLY_SHAPING_ENGLISH_LANGUAGE", "note": "The Book of Common Prayer (1549) created the Church of England's liturgy and profoundly shaped the English language"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Church of England — founding the Anglican Communion through Henry VIII's break with Rome, creating the Book of Common Prayer that shaped the English language — is one of history's most consequential religious institutions whose establishment triggered the English Reformation and shaped modern English-speaking culture.", "significanceCategory": "world-changing"},
    }),
    ("lutheran-church", {
        "summary": "The Lutheran Church — the family of Christian denominations tracing their origin to Martin Luther's 1517 Ninety-five Theses challenging papal indulgences, which triggered the Protestant Reformation — comprises approximately 75 million members worldwide (the second-largest Protestant denomination after various evangelical/Pentecostal groupings), represented globally by the Lutheran World Federation (LWF, founded 1947, headquartered in Geneva).\n\nMartin Luther's theological challenge began with the practical abuse of indulgences but rapidly expanded into foundational questions of Christian theology: sola scriptura (scripture alone as authority, challenging Church tradition and papal pronouncements), sola fide (faith alone for salvation, challenging works-based theology), sola gratia (grace alone, challenging human merit), and sola Christus (Christ alone as mediator, challenging papal and priestly mediation). These 'four solae' became the foundational principles of Lutheran and broadly Protestant theology.\n\nLutheran churches have been particularly influential in German, Scandinavian, and Nordic cultures: Germany's Lutheran church shaped German national identity through Luther's Bible translation (1522-1534, the text credited with standardizing the German language); Scandinavian Lutheran state churches shaped the social democratic welfare state values of Denmark, Sweden, Norway, and Finland; and Lutheran missionaries were among the most active in sub-Saharan Africa and Asia, with Lutheran churches now among the fastest-growing in Ethiopia, Tanzania, and other African nations.",
        "causes": ["Martin Luther's 1517 Ninety-five Theses challenging papal indulgences triggering Protestant Reformation", "Four solae theological principles (sola scriptura, sola fide, sola gratia, sola Christus) defining Lutheran doctrine", "Luther's German Bible translation (1522-1534) creating a standard German language and accessible scripture", "Lutheran World Federation (1947) founding providing global organizational framework for Lutheran churches"],
        "effects": ["Protestant Reformation triggered by Luther's challenge to papal authority fragmenting Western Christendom", "Luther's German Bible standardizing the German language and profoundly shaping German culture", "Scandinavian Lutheran state churches shaping social democratic welfare state values of Nordic countries", "75 million global Lutherans including rapidly growing African churches in Ethiopia, Tanzania, and elsewhere"],
        "relationships": [{"entity": "Martin Luther", "relationship": "FOUNDER_WHOSE_THEOLOGICAL_CHALLENGE_TRIGGERED_PROTESTANT_REFORMATION", "note": "Martin Luther's 1517 Ninety-five Theses and subsequent theological work founded the Lutheran church tradition"}, {"entity": "Protestant Reformation", "relationship": "TRIGGERED_BY_LUTHERAN_THEOLOGICAL_CHALLENGE_TO_PAPAL_AUTHORITY", "note": "The Lutheran Reformation was the initial trigger for the broader Protestant Reformation fragmenting Western Christendom"}, {"entity": "German Language", "relationship": "STANDARDIZED_BY_LUTHER'S_BIBLE_TRANSLATION_AS_PART_OF_LUTHERAN_REFORMATION", "note": "Luther's German Bible translation (1522-1534) is credited with standardizing the German language"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Lutheran Church — born from Luther's Reformation, standardizing the German language, shaping Scandinavian social democracy — is one of history's most consequential religious institutions whose founding theology triggered the fragmentation of Western Christendom and shaped modern European culture.", "significanceCategory": "world-changing"},
    }),
    ("calvinist-reformed-church", {
        "summary": "The Reformed (Calvinist) Church tradition — founded by John Calvin in Geneva during the 1530s-1560s as the most systematic theological expression of Protestant Reformation principles — is the theological tradition underlying Presbyterianism, the Dutch Reformed Church, the Puritans who founded New England, and much of North American Protestantism, with approximately 80 million adherents globally represented by the World Communion of Reformed Churches.\n\nCalvin's systematic theology — articulated in the Institutes of the Christian Religion (1536, expanded through multiple editions) — was the most influential Protestant theological system, defining Calvinist doctrines including: total depravity (human nature fundamentally corrupted by original sin), unconditional election (God's predestined choice of those saved independent of human merit), limited atonement, irresistible grace, and perseverance of the saints ('TULIP'). Predestination — the doctrine that God has eternally decreed who will be saved — was Calvin's most controversial and influential contribution.\n\nCalvinism's social and political impact was extraordinary: Max Weber's The Protestant Ethic and the Spirit of Capitalism (1905) argued that Calvinist theology — with its this-worldly asceticism, rational organization of life, and vocational calling — contributed to the psychological infrastructure of capitalism. The Puritan settlers of New England created America's first democratic institutions on Calvinist covenant theology. Scotland's Presbyterian Church was founded on Calvinist principles. The Dutch Reformed Church shaped South African Calvinist theology, including the theological justifications for apartheid.",
        "causes": ["John Calvin's 1530s Geneva ministry developing the most systematic Reformed Protestant theology", "Institutes of the Christian Religion providing the theological framework for international Calvinist movement", "Calvin's five points (TULIP) providing distinctive doctrinal framework distinguishing Calvinism from Lutheranism", "Calvinist Geneva model of church-state relations influencing Reformed political theology globally"],
        "effects": ["Calvinist/Reformed churches comprising approximately 80 million members globally in Presbyterian and Reformed traditions", "Max Weber's thesis arguing Calvinist theology contributed to capitalism's psychological infrastructure", "Puritan New England settlements creating early American democratic institutions on Calvinist covenant theology", "Dutch Reformed theology shaping Afrikaner identity and providing theological justifications for apartheid"],
        "relationships": [{"entity": "John Calvin", "relationship": "FOUNDER_OF_MOST_SYSTEMATIC_PROTESTANT_THEOLOGY_IN_GENEVA", "note": "John Calvin founded the Reformed tradition in Geneva with his systematic theology"}, {"entity": "Max Weber Protestant Ethic", "relationship": "CALVINIST_THEOLOGY_ARGUED_BY_WEBER_TO_HAVE_CONTRIBUTED_TO_CAPITALISM", "note": "Max Weber's Protestant Ethic argued that Calvinist this-worldly asceticism contributed to capitalism's psychological infrastructure"}, {"entity": "Puritans New England", "relationship": "CALVINIST_COVENANT_THEOLOGY_INSPIRING_DEMOCRATIC_INSTITUTIONS_CREATED_BY", "note": "Puritan settlers brought Calvinist covenant theology to New England, creating early American democratic institutions"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Reformed Calvinist Church — whose theology Weber linked to capitalism's origins, whose Puritan adherents founded American democracy, and whose 80 million members span the world — is one of history's most intellectually and socially consequential religious traditions.", "significanceCategory": "world-changing"},
    }),
    ("methodist-church", {
        "summary": "The Methodist Church — founded by John Wesley (1703-1791) and his brother Charles Wesley (1707-1788) in England during the 1730s-1740s as a revival movement within the Church of England — grew into the world's fourth-largest Protestant denomination with approximately 80 million members globally, particularly influential in the United States (the United Methodist Church is the largest mainline Protestant denomination), and historically significant as the religious movement most associated with the abolitionist movement against slavery and the Social Gospel tradition of Christian social reform.\n\nJohn Wesley's theology combined Calvinist emphasis on grace with Arminian emphasis on free will and human response — rejecting Calvinist predestination in favor of 'prevenient grace' available to all people — and emphasized 'entire sanctification' (the possibility of perfection in Christian love). Wesley's open-air preaching to miners and working-class audiences reached people ignored by established churches, creating a revivalist movement that profoundly influenced working-class English and American religious culture. Charles Wesley's approximately 6,000 hymns (including 'And Can It Be,' 'Christ the Lord Is Risen Today,' 'Hark! The Herald Angels Sing') are among the most sung in Christian history.\n\nMethodism's social reform tradition is extraordinary: the abolitionist movement in Britain (William Wilberforce was Anglican, but Methodists were major abolitionists) and America; the temperance movement; the Social Gospel (Walter Rauschenbusch); labor rights advocacy; education founding (many American universities including Boston University, Duke University, and Emory University are Methodist-founded institutions).",
        "causes": ["John Wesley's 1730s Oxford Holy Club and field preaching movement creating Methodist revival within Church of England", "Arminian emphasis on free will and prevenient grace distinguishing Methodism from Calvinist predestination", "Working-class and mining community outreach creating the mass religious revival movement", "Wesley's organizational genius creating class meetings and circuit riders that sustained Methodist growth"],
        "effects": ["Methodist Church becoming world's fourth-largest Protestant denomination with 80 million members", "Abolitionist movement significantly advanced by Methodist theology and advocacy", "Charles Wesley's 6,000 hymns becoming among the most sung in Christian history", "Methodist-founded universities (Duke, Emory, Boston University) becoming major American research institutions"],
        "relationships": [{"entity": "John Wesley", "relationship": "FOUNDED_BY_REVIVALIST_THEOLOGIAN_REACHING_WORKING-CLASS_POPULATIONS", "note": "John Wesley founded Methodism through open-air preaching and organizational innovation"}, {"entity": "Abolitionist Movement", "relationship": "METHODIST_THEOLOGY_AND_ADVOCACY_SIGNIFICANTLY_ADVANCING", "note": "Methodist churches were major advocates for abolition of slavery in Britain and America"}, {"entity": "Charles Wesley", "relationship": "6,000_HYMNS_AMONG_MOST_SUNG_IN_CHRISTIAN_HISTORY_COMPOSED_BY", "note": "Charles Wesley composed approximately 6,000 hymns including 'Hark! The Herald Angels Sing'"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Methodist Church — founded by the Wesleys, advancing abolition, creating 6,000 enduring hymns, establishing major universities — is historically significant as one of the most socially reforming Protestant denominations and a major force in Anglo-American religious and cultural life.", "significanceCategory": "world-changing"},
    }),
    ("presbyterian-church", {
        "summary": "The Presbyterian Church — the Calvinist Reformed tradition organized by John Knox in Scotland (1560) and subsequently spreading globally — is one of the world's major Protestant denominations, governed by a distinctive democratic system of elected elders (presbyters) rather than bishops, representing approximately 80 million members globally and historically significant as the religious tradition that shaped Scottish national identity, American Calvinist theology, and the democratic governance structures adopted in many Christian and secular institutions.\n\nJohn Knox's Scottish Reformation (1560) established Presbyterianism as Scotland's national church (the Kirk) on Calvinist theological foundations, creating a distinctive combination of Reformed doctrine with democratic church governance: elders elected from congregations govern local churches, presbyteries govern regional groups of congregations, and General Assemblies govern nationally — a system that influenced democratic thinking broadly. The Westminster Confession (1647) remains the doctrinal standard for most Presbyterian and Reformed churches globally.\n\nPresbyterianism's influence on American history is profound: the Puritans who settled New England were largely Reformed/Calvinist; the Scots-Irish Presbyterian settlers of the Appalachian frontier shaped a distinctive American populist Protestant culture; Princeton University was founded by Presbyterians (1746); and the American Revolution had a significant Presbyterian dimension, with British observers calling it 'the Presbyterian Rebellion.' The Presbyterian Church USA is the largest Presbyterian denomination in America with approximately 1.5 million members, while the Global South Presbyterian churches continue to grow.",
        "causes": ["John Knox's 1560 Scottish Reformation establishing Presbyterianism as Scotland's national church", "Calvinist Reformed theology providing doctrinal foundation for Presbyterian church governance", "Westminster Confession (1647) establishing doctrinal standards still used by Presbyterian churches globally", "Democratic presbytery system of elected elders influencing broader democratic governance thinking"],
        "effects": ["Presbyterian Church of Scotland becoming the Kirk — Scotland's national church on Calvinist foundations", "Westminster Confession providing the doctrinal standard for Presbyterian and Reformed churches globally", "Princeton University founding by Presbyterians as major American research institution", "Scots-Irish Presbyterian settlers shaping American frontier populist Protestant culture"],
        "relationships": [{"entity": "John Knox", "relationship": "FOUNDED_SCOTTISH_PRESBYTERIAN_CHURCH_AND_NATIONAL_REFORMATION_BY", "note": "John Knox founded Presbyterianism as Scotland's national church through the 1560 Scottish Reformation"}, {"entity": "Westminster Confession", "relationship": "DOCTRINAL_STANDARD_OF_1647_STILL_USED_BY_MOST_PRESBYTERIAN_CHURCHES", "note": "The Westminster Confession (1647) remains the doctrinal standard for Presbyterian and Reformed churches globally"}, {"entity": "Princeton University", "relationship": "FOUNDED_1746_AS_PRESBYTERIAN_INSTITUTION_BECOMING_MAJOR_RESEARCH_UNIVERSITY", "note": "Princeton University was founded by Presbyterians in 1746 and became a major American research institution"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Presbyterian Church — founded by Knox, governing through democratic elected elders, shaping Scotland's national identity and American Calvinist culture — is historically significant as one of Protestantism's most democratically influential traditions whose governance structures influenced secular democratic thinking.", "significanceCategory": "world-changing"},
    }),
    ("baptist-church", {
        "summary": "The Baptist Church tradition — emerging in the early 17th century from English Separatist and Anabaptist movements, with the first English General Baptist church founded by John Smyth in Amsterdam in 1609 — is the world's largest Protestant denomination family with approximately 100-150 million members globally, particularly dominant in the American South (the Southern Baptist Convention, with approximately 13 million members, is the largest Protestant denomination in the United States) and historically significant for its pioneering advocacy of religious liberty and separation of church and state.\n\nBaptist distinctive theology emphasizes: believer's baptism (baptism of professing believers only, not infants, administered by immersion), congregational governance (each local church is autonomous), priesthood of all believers (no clergy-laity distinction in spiritual status), and religious liberty (the foundational Baptist conviction that civil government has no authority over religious conscience, articulated by Roger Williams who founded Rhode Island in 1636 as America's first colony with full religious toleration). These principles make Baptists among the most significant contributors to modern conceptions of religious freedom.\n\nThe Baptist tradition's complex history includes both progressive and regressive dimensions: Roger Williams's religious liberty advocacy; the Southern Baptist Convention's defense of slavery and segregation (the SBC was founded in 1845 explicitly to defend slaveholder missionaries, and officially apologized for this in 1995); Martin Luther King Jr.'s Baptist ministry at Dexter Avenue Baptist Church in Montgomery and Ebenezer Baptist Church in Atlanta, making the Black Baptist church tradition central to the Civil Rights Movement.",
        "causes": ["John Smyth's 1609 Amsterdam Baptist church founding from English Separatist movement", "Believer's baptism by immersion distinguishing Baptist practice from infant baptism traditions", "Roger Williams's 1636 Rhode Island religious liberty advocacy as foundational Baptist political theology", "Southern Baptist Convention founding in 1845 explicitly defending slaveholder missionaries"],
        "effects": ["Baptist tradition becoming world's largest Protestant denomination family with 100-150 million members", "Roger Williams's Rhode Island establishing America's first colony with full religious toleration", "Black Baptist church tradition providing institutional base for Martin Luther King Jr.'s Civil Rights leadership", "Southern Baptist Convention's 1995 apology for slavery advocacy following its 1845 founding to defend slavery"],
        "relationships": [{"entity": "Roger Williams", "relationship": "RELIGIOUS_LIBERTY_ADVOCACY_FOUNDING_RHODE_ISLAND_TOLERANCE_BY_BAPTIST_THEOLOGIAN", "note": "Roger Williams's Baptist theology of religious liberty led him to found Rhode Island as America's first tolerant colony"}, {"entity": "Martin Luther King Jr.", "relationship": "CIVIL_RIGHTS_MOVEMENT_LED_FROM_BLACK_BAPTIST_CHURCH_TRADITION_BY", "note": "MLK's Civil Rights leadership drew on the Black Baptist church tradition of his pastorates in Montgomery and Atlanta"}, {"entity": "Southern Baptist Convention", "relationship": "LARGEST_AMERICAN_PROTESTANT_DENOMINATION_FOUNDED_1845_TO_DEFEND_SLAVERY", "note": "The SBC was founded in 1845 to defend slaveholder missionaries and apologized for this position in 1995"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Baptist Church tradition — pioneering religious liberty, providing the institutional base for the Civil Rights Movement, the world's largest Protestant family — is historically significant as one of history's most consequential religious traditions whose advocacy for church-state separation shaped modern democracy.", "significanceCategory": "world-changing"},
    }),
    ("pentecostal-church", {
        "summary": "The Pentecostal movement — emerging from the Azusa Street Revival in Los Angeles in 1906, led by William J. Seymour (an African-American preacher, the son of formerly enslaved parents) — is the fastest-growing religious movement in 20th-21st century history, with approximately 500-600 million Pentecostal and Charismatic Christians worldwide representing the most significant religious growth since the Islamic expansion of the 7th-8th centuries.\n\nThe Azusa Street Revival's beginning on April 9, 1906, in a former stable and African Methodist Episcopal church on Azusa Street in Los Angeles is one of the most remarkable origins in religious history: Seymour's interracial services (radical for 1906 America) attracted people from across racial, ethnic, and social lines who experienced what they identified as the baptism of the Holy Spirit with speaking in tongues (glossolalia), divine healing, and prophetic utterance. News of these experiences spread globally within months, initiating a worldwide revival movement.\n\nPentecostalism's growth has been most explosive in the Global South: in sub-Saharan Africa (approximately 150 million Pentecostals), Latin America (approximately 150 million, with Brazil home to the world's largest Pentecostal church — the Assemblies of God Brazil with approximately 35 million members), and East and Southeast Asia. This growth represents a fundamental demographic shift in global Christianity: the majority of the world's Christians now live in the Global South, and the majority of those are Pentecostal or Charismatic.",
        "causes": ["William J. Seymour's April 1906 Azusa Street Revival founding Pentecostalism with interracial Spirit-baptism meetings", "African-American Holiness tradition providing theological framework for Spirit baptism with tongues", "Global communication networks spreading Azusa Street revival reports creating worldwide movement", "Pentecostal emphasis on direct experience of Holy Spirit attracting working-class and marginalized populations globally"],
        "effects": ["500-600 million Pentecostal and Charismatic Christians representing the most dramatic religious growth in modern history", "Global South Pentecostalism shifting the majority of world Christians to Africa, Latin America, and Asia", "Brazilian Assemblies of God becoming world's largest Pentecostal church with approximately 35 million members", "Pentecostal prosperity theology significantly influencing global Christian theology and practice"],
        "relationships": [{"entity": "William J. Seymour", "relationship": "FOUNDED_BY_AFRICAN-AMERICAN_PREACHER_WHOSE_AZUSA_REVIVAL_BEGAN_MOVEMENT", "note": "William J. Seymour's 1906 Azusa Street Revival launched the Pentecostal movement"}, {"entity": "Azusa Street Revival", "relationship": "FOUNDED_FROM_APRIL_1906_INTERRACIAL_REVIVAL_AT", "note": "The 1906 Azusa Street Revival is Pentecostalism's founding event"}, {"entity": "Global South Christianity", "relationship": "DRIVING_FORCE_OF_DEMOGRAPHIC_SHIFT_IN_WORLD_CHRISTIANITY_TO", "note": "Pentecostalism is the primary driver of the shift of global Christianity's majority to the Global South"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Pentecostal movement — born from Seymour's interracial revival, growing to 500-600 million adherents in the most dramatic religious expansion since Islam — is historically significant as the most consequential new religious movement of the 20th century and the driving force reshaping global Christianity.", "significanceCategory": "world-changing"},
    }),
    ("evangelical-covenant-church", {
        "summary": "The Evangelical Covenant Church (ECC) — founded in 1885 in Chicago by Swedish immigrants who brought with them the Pietist revival movement from Sweden (influenced by the Läsare or 'readers' movement and the Lutheran free church tradition) — is a North American Protestant denomination with approximately 900 congregations and 180,000 members, notable for its emphasis on Pietist spirituality, its early ordination of women, and its diverse membership that has grown beyond its Swedish immigrant founding community to include significant African American, Latino, and Asian American congregations.\n\nThe ECC's Pietist heritage reflects the 18th-19th century Scandinavian religious renewal: while remaining nominally Lutheran, the Pietist movement emphasized personal conversion experience, small-group Bible study (collegia pietatis, 'schools of piety'), and lived Christian faith over doctrinal confessionalism. Swedish Pietist immigrants brought these traditions to Illinois and Minnesota in the 1840s-1880s, creating congregations that eventually organized as the Evangelical Covenant Church in 1885.\n\nThe ECC's distinctive theological positioning — between doctrinally strict confessional Protestantism and theologically liberal mainline Protestantism — has allowed it to maintain evangelical convictions while embracing diversity and social justice concerns. The denomination's North Park University and Seminary in Chicago, and its significant international mission work in Congo, Ethiopia, Ecuador, and Japan, extend its institutional footprint beyond its modest membership size.",
        "causes": ["Swedish Pietist revival movement (Läsare) providing the theological tradition for immigrant congregations", "1885 Chicago organizing of Swedish immigrant Lutheran free church congregations as the Evangelical Covenant", "Pietist emphasis on personal conversion experience and small-group spirituality distinguishing from confessional Lutheranism", "Swedish immigrant communities in Illinois and Minnesota providing the founding constituency"],
        "effects": ["Evangelical Covenant Church developing into diverse multiethnic denomination beyond Swedish immigrant origins", "Early women's ordination reflecting Pietist egalitarian tradition within evangelical Protestantism", "North Park University and Seminary providing higher education from Covenant's Chicago headquarters", "International mission work in Congo, Ethiopia, Ecuador, and Japan extending the denomination's global presence"],
        "relationships": [{"entity": "Swedish Pietist Movement", "relationship": "THEOLOGICAL_TRADITION_BROUGHT_TO_AMERICA_BY_IMMIGRANT_FOUNDERS", "note": "The ECC was founded by Swedish immigrants carrying the Pietist revival tradition"}, {"entity": "North Park University", "relationship": "DENOMINATIONAL_HIGHER_EDUCATION_INSTITUTION_IN_CHICAGO_AFFILIATED_WITH", "note": "North Park University and Seminary in Chicago is the ECC's primary higher education institution"}, {"entity": "Evangelical Protestantism", "relationship": "POSITIONS_BETWEEN_CONFESSIONAL_STRICTNESS_AND_LIBERAL_THEOLOGY_WITHIN", "note": "The ECC occupies a distinctive middle position between doctrinally strict and liberal Protestant traditions"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "The Evangelical Covenant Church — founded by Swedish Pietist immigrants, now a diverse multiethnic denomination with pioneering women's ordination — is historically significant as a model of immigrant religious tradition adapting to American pluralism while maintaining evangelical conviction.", "significanceCategory": "continental"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 149 — Class 340 Religious Orgs IX: Global Protestant & Evangelical Churches")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
