#!/usr/bin/env python3
"""Batch 91 — Class 330 Companies V (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/330-Class-330"
FILE_PREFIX = "330"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("dutch-east-india-company", {
        "summary": "The Dutch East India Company (Vereenigde Oost-Indische Compagnie, VOC), chartered in 1602 and dissolved in 1799, was the world's first multinational corporation and the most powerful trading company in history — operating 4,785 ships, employing 1 million people, paying 18% annual dividends for almost 200 years, and having a peak valuation estimated at $7.9 trillion in today's dollars (greater than Apple, Google, Microsoft, Amazon, and Facebook combined). The VOC pioneered financial instruments (stocks, bonds, dividends) that created modern capital markets.\n\nThe VOC's founding in 1602 merged six competing Dutch trading companies under state charter, granting it monopoly rights over Dutch trade with Asia, plus quasi-governmental powers: the right to wage war, negotiate treaties, mint coins, and establish colonies. The Amsterdam Stock Exchange (founded 1602 specifically for VOC share trading) is the world's first stock exchange. The VOC issued the world's first publicly traded shares, making speculative investment in distant trade accessible to ordinary citizens — creating financial capitalism's foundational instruments.\n\nAt peak (1640s-1660s), the VOC controlled access to the Spice Islands (Maluku, Indonesia), giving it monopoly over nutmeg, mace, cloves, and pepper — the world's most profitable commodities. The Batavia (Jakarta) headquarters became Southeast Asia's commercial hub. The VOC's 1619 massacre at Banda Islands (killing approximately 15,000 Banda islanders for nutmeg monopoly) is one of history's most extreme cases of commercial violence. The VOC's 1799 bankruptcy — from corruption, competition, and war — transferred its colonial assets to the Dutch government, creating the Dutch East Indies (modern Indonesia).",
        "causes": ["1602 charter merging six Dutch trading companies with quasi-governmental monopoly powers", "Amsterdam Stock Exchange founding creating world's first publicly traded shares", "Spice Islands control giving monopoly over nutmeg, mace, cloves — world's most profitable commodities", "1619 Banda Islands massacre establishing total control of nutmeg supply"],
        "effects": ["$7.9 trillion peak valuation as most valuable company in history", "World's first stock exchange and publicly traded shares creating financial capitalism's foundations", "Dutch East Indies colonial legacy creating modern Indonesia", "VOC's bankruptcy transferring colonial assets to Dutch state establishing European colonial pattern"],
        "relationships": [{"entity": "Amsterdam Stock Exchange", "relationship": "CREATED_MARKET_FOR", "note": "VOC's 1602 share issue prompted Amsterdam Stock Exchange founding — world's first stock exchange"}, {"entity": "Jan Pieterszoon Coen", "relationship": "COLONIAL_GOVERNOR", "note": "Coen established Batavia (Jakarta) and ordered 1619 Banda Islands massacre for nutmeg monopoly"}, {"entity": "Dutch East Indies", "relationship": "COLONIAL_PREDECESSOR_OF", "note": "VOC's 1799 bankruptcy transferred its Asian colonial territories to the Dutch state"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The VOC — the first multinational corporation, the first publicly traded stock, the first stock exchange — created financial capitalism's foundational instruments, and its $7.9 trillion peak valuation (greater than today's five largest companies combined) makes it the most economically powerful entity in history.", "significanceCategory": "world-changing"},
    }),
    ("hyundai-motor-company", {
        "summary": "Hyundai Motor Company, founded in Seoul in 1967 by Chung Ju-yung and now part of the Hyundai Motor Group (with Kia and Genesis), is South Korea's largest automaker and the world's third-largest automotive group by sales volume — producing 7.2 million vehicles annually, employing 250,000 people, and transforming South Korea's economic development through vertical integration of steel, shipping, and automotive production in one family conglomerate. Hyundai's rise from a 1967 startup to a global top-3 automaker in 55 years is among history's most dramatic industrial ascents.\n\nChung Ju-yung (founder of Hyundai Engineering and Construction, 1947) applied his construction conglomerate's vertical integration model to automobiles — building the Ulsan automotive complex (1968, Korea's first dedicated car plant), and initially assembling Ford Cortinas under license. The first Hyundai-designed car, the Pony (1975, designed by Giorgio Giugiaro), was the first Korean-designed automobile and was exported to Canada in 1984 — beginning Hyundai's international expansion.\n\nHyundai's quality transformation (2000-2010) — from being North America's lowest-rated automaker (1990s) to among the highest (2010s) — is one of the most remarkable brand rehabilitation stories in automotive history. The 10-year/100,000-mile warranty (introduced 1998) forced quality improvement. Hyundai's IONIQ 5 and Genesis G90 demonstrate Korean automotive leadership in EV design. The Hyundai-Kia Group's 2023 acquisition of Boston Dynamics (robotics) signals diversification from automotive into robotics and future mobility.",
        "causes": ["1967 founding by Chung Ju-yung applying construction conglomerate's vertical integration to automobiles", "1975 Pony as Korea's first domestically designed automobile with Giugiaro styling", "1998 10-year/100,000-mile warranty forcing quality improvement and brand rehabilitation", "Hyundai-Kia Group formation creating third-largest automotive group by volume"],
        "effects": ["7.2 million annual vehicles produced making Hyundai third-largest automotive group globally", "South Korea's automotive industry development through Ulsan complex and vertical integration", "Brand rehabilitation from lowest-rated to highest-rated demonstrating quality transformation potential", "IONIQ EV and Boston Dynamics acquisition positioning for electric and robotic mobility leadership"],
        "relationships": [{"entity": "Chung Ju-yung", "relationship": "FOUNDED_BY", "note": "Chung founded Hyundai in 1967 applying his construction group's integration model to automobiles"}, {"entity": "Giorgio Giugiaro", "relationship": "DESIGNED_FIRST_MODEL_BY", "note": "Italian designer Giugiaro styled the Pony (1975) — Korea's first domestically designed automobile"}, {"entity": "Kia Motors", "relationship": "SISTER_COMPANY", "note": "Hyundai acquired Kia in 1998 forming the Hyundai-Kia Group — third-largest automotive group"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Hyundai's ascent from a 1967 startup to the world's third-largest automaker in 55 years is the most compressed industrial ascent in automotive history, and its quality rehabilitation from worst-rated to best-rated demonstrates the possibility of total organizational transformation through relentless improvement culture.", "significanceCategory": "world-changing"},
    }),
    ("suzuki-motor-corporation", {
        "summary": "Suzuki Motor Corporation, founded by Michio Suzuki in Hamamatsu, Japan in 1909 as a loom manufacturer and transformed into an automaker in 1954, is one of Japan's most innovative automotive companies — pioneering the kei car (minicar) category with the Suzulight (1955), the small motorcycle category with the Colleda, and the compact SUV category with the Samurai/SJ (1970s). Suzuki's kei car innovation addressed Japan's unique postwar economic circumstances (fuel scarcity, narrow roads, low incomes) and created an entire category that now represents 40% of Japanese domestic car sales.\n\nMichio Suzuki's loom-making company (1909) had developed precision manufacturing skills that transferred naturally to small-engine motorcycles (1952) and then to the Suzulight (1955) — Japan's first kei car designed to benefit from Japanese government tax and registration advantages for vehicles under 360cc. Suzuki's ability to engineer small, efficient, reliable vehicles at low cost made it dominant in emerging markets: India (Maruti Suzuki, founded 1981, controls 40%+ of Indian car market), Pakistan, Bangladesh, and Southeast Asia.\n\nMaruti Suzuki — the Indian government joint venture (1981) that brought Suzuki's small-car technology to India — democratized personal transportation for hundreds of millions. The Maruti 800 (1983, based on Suzuki Alto) gave India its first affordable mass-market car, transforming middle-class mobility. Maruti Suzuki is now India's largest car company with 40%+ market share. Suzuki's motorcycle division (producing 1.5 million bikes annually) and marine engine business further diversify the group.",
        "causes": ["1909 loom manufacturing founding developing precision engineering applicable to small engines", "1955 Suzulight kei car pioneering category addressing Japan's postwar fuel and road constraints", "1981 Maruti Suzuki India joint venture democratizing personal transportation for hundreds of millions", "Compact efficiency expertise enabling dominant position in emerging Asian automotive markets"],
        "effects": ["Kei car category creation now representing 40% of Japanese domestic automotive sales", "Maruti Suzuki's 40%+ India market share democratizing personal transport for Indian middle class", "Emerging market automotive leadership in India, Pakistan, Bangladesh, Southeast Asia", "Small-engine motorcycle and marine markets demonstrating platform technology versatility"],
        "relationships": [{"entity": "Michio Suzuki", "relationship": "FOUNDED_BY", "note": "Suzuki's loom precision engineering transferred to kei cars and motorcycles"}, {"entity": "Maruti Suzuki", "relationship": "JOINT_VENTURE", "note": "1981 Indian government joint venture made Suzuki dominant in world's fastest-growing auto market"}, {"entity": "Maruti 800", "relationship": "DEMOCRATIZING_PRODUCT", "note": "1983 Maruti 800 gave India its first affordable mass-market car transforming middle-class mobility"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Suzuki's kei car innovation and Maruti Suzuki's India market democratization — bringing personal transportation to hundreds of millions of emerging market consumers — demonstrates how engineering constraints (small, efficient, cheap) can create more social value than engineering ambition.", "significanceCategory": "continental"},
    }),
    ("honda", {
        "summary": "Honda Motor Co., Ltd., founded by Soichiro Honda and Takeo Fujisawa in Tokyo in 1948, is Japan's second-largest automaker and the world's largest motorcycle manufacturer — producing 4 million cars and 19 million motorcycles annually, with the world's most fuel-efficient internal combustion engines (VTEC, i-VTEC) and the first commercially successful hydrogen fuel cell vehicle (FCX Clarity, 2008). Honda's founding story — Soichiro Honda, a mechanical genius without business skills, partnering with Fujisawa's business genius — is a textbook study in complementary co-founder partnership.\n\nHonda's motorcycle breakthrough — the Super Cub (1958), the world's best-selling motor vehicle of all time at 100+ million units produced — transformed personal mobility across Asia and developing nations. The Super Cub's simplicity, reliability, and affordability democratized transportation in countries where automobiles were unaffordable: Honda's 1960s advertising ('You meet the nicest people on a Honda') changed the social perception of motorcycles from dangerous outlaw machines to mainstream transport.\n\nHonda's Formula One dominance (1986-1991, 6 Constructors' Championships; 2000-2006, 7 Constructors' Championships through partnerships with Williams, McLaren, and BAR) made it the most successful engine supplier in F1 history. The CVCC engine (1972) — the first to meet California's strict emission standards without a catalytic converter — demonstrated Honda's emissions engineering leadership. Honda's ASIMO humanoid robot (2000) advanced bipedal robotics; the Honda Jet (2015) entered business aviation. Honda's diverse technology portfolio — cars, motorcycles, jets, robots, power equipment — is the broadest of any company its size.",
        "causes": ["1948 founding by Soichiro Honda (engineering) and Takeo Fujisawa (business) as complementary partnership", "Super Cub 1958 launch democratizing personal transport across Asia and developing nations", "CVCC engine 1972 meeting California emissions standards without catalytic converter", "Formula One engine dominance 1986-2006 establishing Honda's engineering prestige"],
        "effects": ["Super Cub 100+ million units as world's best-selling motor vehicle ever produced", "19 million annual motorcycle production as world's largest motorcycle manufacturer", "Formula One championships advancing VTEC engine technology into commercial vehicles", "FCX Clarity 2008 as first commercially deployed hydrogen fuel cell vehicle"],
        "relationships": [{"entity": "Soichiro Honda", "relationship": "FOUNDED_BY", "note": "Honda combined Soichiro's engineering genius with Fujisawa's business genius in ideal complementary partnership"}, {"entity": "Super Cub", "relationship": "MOST_SIGNIFICANT_PRODUCT", "note": "Super Cub's 100+ million units makes it world's best-selling motor vehicle of all time"}, {"entity": "Ayrton Senna", "relationship": "CHAMPIONSHIP_PARTNER", "note": "Honda engines powered Senna's 1988-1991 McLaren championships — most celebrated F1 partnership"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Honda's Super Cub — the world's best-selling motor vehicle at 100+ million units — democratized personal mobility across Asia and the developing world, and Honda's engineering culture (from VTEC to hydrogen fuel cells to humanoid robots) demonstrates that automotive excellence is a platform for the broadest possible mechanical innovation.", "significanceCategory": "world-changing"},
    }),
    ("china-construction-bank", {
        "summary": "China Construction Bank Corporation (CCB), founded in Beijing in 1954 as the People's Construction Bank of China, is the world's second-largest bank by assets ($4.74 trillion) and China's primary lender for infrastructure and urban development — financing the Three Gorges Dam, the Beijing-Shanghai High Speed Railway, millions of housing units, and the Belt and Road Initiative's infrastructure loans across 60+ countries. CCB's transformation from a state construction treasury to a commercial bank (1994-2004) mirrors China's broader economic transformation.\n\nCCB was founded to manage state funds for China's First Five Year Plan (1953-1957) capital construction — effectively functioning as a government treasury rather than a bank. The 1994 Chinese banking reform separated policy banking from commercial banking, converting CCB into a commercial entity. The 2005 IPO on the Hong Kong Stock Exchange raised $9.2 billion — the world's largest IPO at the time — with Bank of America acquiring a 9% strategic stake.\n\nCCB's role in Chinese urbanization is structural: as China's population migrated from 20% urban (1980) to 65% urban (2023), CCB financed the apartment buildings, metro systems, highways, and commercial buildings that housed and connected 600 million new urban dwellers. The Belt and Road Initiative (since 2013) has made CCB a global infrastructure lender: CCB has financed ports, railways, power plants, and industrial parks across Africa, Asia, and Latin America — making it the world's most consequential development bank.",
        "causes": ["1954 founding to manage state funds for First Five Year Plan capital construction", "1994 banking reform separating policy and commercial banking creating modern CCB", "2005 Hong Kong IPO raising $9.2 billion as world's largest at time", "Belt and Road Initiative 2013 expanding CCB into global infrastructure lending across 60+ countries"],
        "effects": ["$4.74 trillion assets making CCB world's second-largest bank", "Chinese urbanization financing enabling 600 million people's migration from rural to urban", "Three Gorges Dam and Beijing-Shanghai HSR financing for China's defining infrastructure projects", "Belt and Road loans making CCB world's most consequential development lender"],
        "relationships": [{"entity": "Three Gorges Dam", "relationship": "FINANCED", "note": "CCB financed Three Gorges Dam — world's largest hydroelectric dam — as primary infrastructure bank"}, {"entity": "Belt and Road Initiative", "relationship": "PRIMARY_FUNDER_OF", "note": "CCB is principal lender for BRI infrastructure projects across 60+ countries"}, {"entity": "Bank of America", "relationship": "STRATEGIC_PARTNER", "note": "Bank of America acquired 9% CCB stake at 2005 IPO — world's largest at the time"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "China Construction Bank's role in financing China's urbanization — from 20% to 65% urban in 40 years, housing 600 million new city dwellers — and the Belt and Road Initiative's global infrastructure makes CCB the development bank whose lending has most immediately shaped 21st-century economic geography.", "significanceCategory": "world-changing"},
    }),
    ("sberbank", {
        "summary": "Sberbank (Savings Bank of the Russian Federation), founded in 1841 by Tsar Nicholas I as Russia's first savings bank, is Russia's largest bank by assets ($500+ billion), controlling 40%+ of Russian retail deposits, and the dominant financial institution in a country of 145 million people. Sberbank's transformation from a Soviet-era state savings institution to a 21st-century financial technology company — launching Sber, an ecosystem including food delivery, music streaming, telemedicine, and AI services — is among the most ambitious financial institution reinventions in banking history.\n\nNicholas I established the first Imperial Savings Bank in St. Petersburg in 1841 as a state institution for small depositors — bringing banking to Russia's newly urbanizing working class. The bank survived the Russian Revolution as Gosbank (State Bank of the USSR), absorbing the savings of Soviet citizens who had no alternative. Soviet citizens who deposited rubles in Gosbank before 1991 lost their savings to hyperinflation — a wound in Russian financial trust that Sberbank's successors have spent 30 years repairing.\n\nSberbank CEO Herman Gref (appointed 2007) initiated a dramatic transformation from Soviet-era institution to technology company. The 2020 rebranding as 'Sber' and launch of Sber Ecosystem — 50+ services from Samokat grocery delivery to SberHealth telemedicine to Salute voice assistant — represented an attempt to compete with tech platforms rather than banks. The 2022 Russian invasion of Ukraine triggered Western sanctions that effectively cut Sberbank off from international financial markets, but domestic dominance remains absolute.",
        "causes": ["1841 founding by Nicholas I as Russia's first savings bank for small depositors", "Soviet-era Gosbank monopoly on citizen savings creating 150-year institutional dominance", "Herman Gref's 2007 appointment launching technology transformation and Sber ecosystem", "2022 sanctions following Ukraine invasion cutting Sberbank from international markets"],
        "effects": ["40%+ Russian retail deposit share making Sberbank unavoidable in Russian financial life", "Sber ecosystem of 50+ services attempting to compete with global tech platforms", "1991 Soviet hyperinflation destroying depositor savings creating lasting Russian financial trauma", "Western sanctions creating opportunity for Chinese financial institutions to fill Russia's international banking gap"],
        "relationships": [{"entity": "Nicholas I of Russia", "relationship": "FOUNDED_BY_ORDER_OF", "note": "Nicholas I established first Imperial Savings Bank in 1841 as state institution for small depositors"}, {"entity": "Herman Gref", "relationship": "TRANSFORMED_BY_CEO", "note": "Gref's 2007 appointment initiated transformation from Soviet savings bank to Sber technology ecosystem"}, {"entity": "2022 Russia-Ukraine War", "relationship": "SANCTIONS_IMPACT", "note": "Western sanctions cut Sberbank from international markets while domestic dominance remained"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Sberbank's 180-year evolution from Nicholas I's 1841 savings bank through Soviet Gosbank monopoly to Gref's Sber technology ecosystem demonstrates how a state financial institution shaped by three political systems can attempt total transformation — and how geopolitical events can instantly terminate 30 years of modernization progress.", "significanceCategory": "continental"},
    }),
    ("ibm", {
        "summary": "IBM (International Business Machines Corporation), founded in Armonk, New York in 1911 as the Computing-Tabulating-Recording Company and renamed IBM in 1924 under Thomas J. Watson Sr., is the technology company most responsible for creating the modern computing industry — producing the System/360 (1964, the first family of mutually compatible computers), the IBM PC (1981, which defined personal computing standards), the Deep Blue chess computer (1997, which defeated Garry Kasparov), and Watson AI (2011, which defeated Jeopardy! champions). IBM has received more US patents than any other company for 28 consecutive years.\n\nThomas Watson Sr.'s IBM transformed punch card tabulation (used in the 1890 US Census) into a worldwide computing services business. The System/360 (1964) — a $5 billion development program, the largest private industrial investment in history at the time — created the first family of mutually compatible computers from mainframes to small systems, establishing the hardware compatibility standard that all subsequent computing inherited. IBM's 1981 PC decision — using open architecture and Microsoft's MS-DOS — inadvertently created the PC clone market that allowed competitors to undermine IBM's hardware dominance.\n\nIBM's transformation from hardware manufacturer to services and consulting company (1990s-2000s) under Louis Gerstner's turnaround saved IBM from bankruptcy after the PC clone market collapse. The 2019 Red Hat acquisition ($34 billion) repositioned IBM in hybrid cloud and Linux. IBM Watson AI — beating Jeopardy! champions in 2011 — pioneered natural language AI for enterprise applications. IBM's quantum computing research (IBM Quantum Network) is a leading civilian quantum computing program.",
        "causes": ["1911 founding as Computing-Tabulating-Recording Company for punch card tabulation", "System/360 1964 launch as first mutually compatible computer family defining hardware standards", "IBM PC 1981 open architecture inadvertently creating PC clone market undermining IBM's hardware dominance", "Louis Gerstner's 1993 turnaround transforming IBM from hardware to services company"],
        "effects": ["System/360 compatibility standard inherited by all subsequent computing hardware", "IBM PC's open architecture creating PC clone market and Microsoft's dominance", "Deep Blue 1997 Kasparov defeat demonstrating AI's game-playing potential", "28 consecutive years of most US patents demonstrating sustained innovation capacity"],
        "relationships": [{"entity": "Thomas J. Watson Sr.", "relationship": "TRANSFORMED_BY_CEO", "note": "Watson Sr. transformed CTR into IBM and built global computing services business"}, {"entity": "Bill Gates", "relationship": "PARTNER_MADE_DOMINANT", "note": "IBM's 1981 PC used Microsoft's MS-DOS — inadvertently making Microsoft dominant while IBM lost hardware control"}, {"entity": "Garry Kasparov", "relationship": "DEFEATED_BY_DEEP_BLUE", "note": "IBM's Deep Blue defeated world chess champion Kasparov in 1997 — milestone in AI development"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "IBM's System/360 (which created hardware compatibility standards inherited by all computing) and the IBM PC's open architecture (which inadvertently created Microsoft's dominance) make IBM the company that most shaped modern computing's technical architecture — twice creating industry standards that outgrew IBM itself.", "significanceCategory": "world-changing"},
    }),
    ("allianz-trade", {
        "summary": "Allianz Trade (formerly Euler Hermes), headquartered in Paris and owned by Allianz SE since 2018, is the world's largest trade credit insurance company — insuring approximately €995 billion in business transactions annually, covering 23,000 buyers in 160 countries, and providing the financial infrastructure that enables global trade by protecting companies against non-payment risk. Trade credit insurance — covering the risk that a buyer will not pay for delivered goods — is the invisible financial guarantee underlying approximately 10-15% of global trade flows.\n\nTrade credit insurance emerged in the 1920s as international trade expanded and companies needed protection against foreign buyer default. The Hermes export credit guarantee agency (founded 1917 in Germany) merged with Credit Alliance (France) and Trade Indemnity (UK) to form Euler Hermes — covering three of Europe's major export economies. The 2018 rebranding to Allianz Trade connected the business to Allianz's 130-million-customer financial services network.\n\nAllianz Trade's economic intelligence function — employing 400+ economists who monitor 80 million companies globally for financial distress signals — makes it one of the world's most sophisticated early-warning systems for corporate and sovereign credit risk. Its annual Insolvency Outlook reports are closely followed by governments, banks, and corporations planning trade and investment strategies. The COVID-19 pandemic (2020-2022) saw Allianz Trade insuring unprecedented volumes of trade receivables as payment defaults surged globally, demonstrating trade credit insurance's counter-cyclical stabilization function.",
        "causes": ["1917 German Hermes export credit founding insuring German export trade", "Euler Hermes formation merging Hermes, Credit Alliance, and Trade Indemnity", "2018 Allianz SE acquisition rebranding as Allianz Trade", "Global trade expansion requiring insurance for $995 billion in annual transactions"],
        "effects": ["World's largest trade credit insurer covering 10-15% of global trade flows against non-payment", "400+ economist team providing world's most comprehensive corporate insolvency early warning", "COVID-19 pandemic default surge demonstrating trade credit insurance's counter-cyclical function", "Allianz network integration creating 130-million-customer financial services reach"],
        "relationships": [{"entity": "Allianz SE", "relationship": "OWNED_BY", "note": "Allianz acquired Euler Hermes in 2018 rebranding as Allianz Trade"}, {"entity": "World Trade Organization", "relationship": "TRADE_FACILITATOR", "note": "Allianz Trade's insurance enables WTO-governed trade flows by removing non-payment risk for exporters"}, {"entity": "COVID-19 Pandemic", "relationship": "STRESS_TESTED_BY", "note": "Pandemic payment defaults tested Allianz Trade's capacity demonstrating trade credit insurance's counter-cyclical role"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "Allianz Trade's role as the world's largest trade credit insurer — protecting €995 billion in annual transactions against non-payment — represents the invisible financial infrastructure without which approximately 10-15% of global trade would be impossible or prohibitively expensive to conduct.", "significanceCategory": "continental"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 91 — Class 330 Companies V")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
