#!/usr/bin/env python3
"""Batch 132 — Class 381 Universities VI: Kyoto + National Universities (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/381-Class-381"
FILE_PREFIX = "381"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("kyoto-prefectural-university", {
        "summary": "Kyoto Prefectural University (京都府立大学, Kyōto Furitsu Daigaku), established in 1949 (with origins in a 1895 agricultural school), is a public university administered by Kyoto Prefecture focusing on life and environmental sciences, literature, and public policy — a regional university serving Kyoto Prefecture while situated in one of Japan's most academically competitive cities, home to Kyoto University (a top national research university), Doshisha University, Ritsumeikan University, and numerous other prestigious institutions.\n\nKyoto's extraordinary academic density — with 37 universities and colleges for a metropolitan population of approximately 1.5 million — reflects both the city's historical role as Japan's imperial capital and cultural center and the modern concentration of educational institutions that developed in the post-Meiji modernization period. Kyoto Prefectural University's focus on practical sciences (agriculture, food science, environmental studies) and humanities distinguishes it from the research-intensive national universities while serving the regional educational mission of Kyoto Prefecture.\n\nThe university's origins in a late Meiji-era agricultural school reflect the Meiji government's emphasis on practical scientific education to support Japan's modernization. Agricultural and applied science education was a priority as Japan sought to improve agricultural productivity to feed a rapidly industrializing population. The university's evolution from practical agricultural school to comprehensive prefectural university mirrors Japan's broader transformation from agricultural to industrial and post-industrial economy.",
        "causes": ["1895 Meiji-era agricultural school founding reflecting practical science education priorities of Japanese modernization", "Kyoto Prefecture's educational mission requiring a public university serving the region's practical educational needs", "Post-WWII university reorganization (1949) transforming technical schools into formal universities under new educational laws", "Kyoto's academic density creating demand for diverse institutional types including practical-focused prefectural universities"],
        "effects": ["Prefectural university serving regional practical science and humanities education in an academically competitive city", "Agricultural and food science programs supporting Kyoto Prefecture's traditional food culture industries", "Public university access providing affordable higher education as alternative to the expensive private universities dominant in Kyoto", "Institutional continuity from 1895 agricultural school demonstrating the long development of Japanese practical science education"],
        "relationships": [{"entity": "Kyoto Prefecture", "relationship": "ADMINISTERED_BY_AND_SERVES_EDUCATIONAL_MISSION_OF", "note": "The university is a public institution of Kyoto Prefecture providing regional practical education"}, {"entity": "Meiji Modernization", "relationship": "FOUNDED_AS_PRACTICAL_SCIENCE_SCHOOL_DURING", "note": "The 1895 agricultural school origin reflects Meiji Japan's practical science education priorities"}, {"entity": "Kyoto Academic Ecosystem", "relationship": "PART_OF_WORLD'S_MOST_DENSELY_ACADEMIC_CITY", "note": "The university is one of 37 institutions in Kyoto's extraordinarily dense academic environment"}],
        "historicalSignificance": {"significanceScore": 4, "significanceNarrative": "Kyoto Prefectural University — a Meiji-era agricultural school transformed into a comprehensive prefectural university, serving Kyoto's regional educational needs in one of Japan's most academically competitive cities — is locally significant as a practical-focused public institution in Japan's cultural capital.", "significanceCategory": "local"},
    }),
    ("kyoto-prefectural-university-of-medicine", {
        "summary": "Kyoto Prefectural University of Medicine (京都府立医科大学, Kyōto Furitsu Ika Daigaku), founded in 1872 as a medical school (one of Japan's earliest Western medicine institutions) and established as a full university in 1921 — is a prestigious specialized medical university in Kyoto, Japan, with a long history of medical education and research that places it among Japan's historically important medical institutions, having trained doctors for 150 years in the city that was Japan's imperial and cultural capital.\n\nThe 1872 founding of Kyoto's prefectural medical school was part of the Meiji government's urgent program to introduce Western medicine to Japan — replacing or supplementing traditional Chinese-influenced Kampo medicine with the European scientific medicine that the Meiji reformers believed was essential for national strength and modernization. Medical education was a high priority: Meiji Japan needed trained doctors to improve public health, treat industrial injuries, support military capacity, and demonstrate Japan's civilizational advancement to Western powers.\n\nKyoto Prefectural University of Medicine's 150-year history spans Japan's transformation from feudal to modern: training doctors during the Meiji industrial revolution, through the militarist period (wartime medical research), post-WWII reconstruction, and Japan's emergence as a leading global economy. The university's attached hospital is one of Kyoto's major medical centers. Research conducted at the university has contributed to Japanese medical science, and its graduates have practiced throughout Japan and internationally.",
        "causes": ["1872 Meiji government medical modernization program requiring Western medicine education institutions in major cities", "Kyoto Prefecture's public health needs requiring trained Western-medicine doctors replacing traditional Kampo practitioners", "Japan's military and industrial modernization requiring organized medical infrastructure including medical universities", "Post-WWII university law reorganization requiring formal university status for specialized medical schools"],
        "effects": ["150+ years of medical doctor training for Kyoto and the broader Kansai region", "Transition from Kampo traditional medicine to Western scientific medicine documented through the institution's evolution", "Medical research contributing to Japanese scientific advancement through the modern research university era", "Attached hospital providing major medical services to Kyoto while supporting clinical education"],
        "relationships": [{"entity": "Meiji Medical Modernization", "relationship": "FOUNDED_AS_EARLY_WESTERN_MEDICINE_INSTITUTION_OF", "note": "The 1872 medical school was among Japan's earliest Western medicine education institutions during Meiji modernization"}, {"entity": "Kyoto Prefecture", "relationship": "PREFECTURAL_MEDICAL_UNIVERSITY_OF", "note": "The university serves as Kyoto Prefecture's primary medical education and research institution"}, {"entity": "Japanese Medical Education", "relationship": "ONE_OF_JAPAN'S_OLDEST_MEDICAL_UNIVERSITY_TRADITIONS", "note": "The 1872 founding makes it one of Japan's earliest and most continuous medical education institutions"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "Kyoto Prefectural University of Medicine — one of Japan's earliest Western medicine institutions (1872), training doctors for 150 years during Japan's entire modern transformation — is historically significant as a monument to Meiji medical modernization and a century and a half of Japanese medical education.", "significanceCategory": "continental"},
    }),
    ("national-university-of-costa-rica", {
        "summary": "The National University of Costa Rica (Universidad Nacional, UNA, founded 1973 in Heredia) is one of Costa Rica's four public universities, established as part of the remarkable expansion of Costa Rican public higher education in the 1970s under President Daniel Oduber Quirós — a period when Costa Rica systematically invested in accessible public university education as part of its exceptional commitment to democratic development, social equity, and education-based human capital that has made Costa Rica one of Latin America's most stable democracies.\n\nCosta Rica's commitment to education as a national priority is extraordinary in the Latin American context: the country abolished its military in 1948 (the abolition declared by President José Figueres Ferrer, inscribed in the 1949 Constitution), redirecting military spending to education and health. This decision — unique in world history for a state voluntarily abolishing its armed forces — created the conditions for sustained educational investment that made Costa Rica a regional educational leader. The 1973 founding of UNA (alongside ITCR and the later UNED) was part of this educational investment strategy.\n\nThe National University of Costa Rica focuses particularly on environmental sciences, humanities, social sciences, and education — areas that reflect Costa Rica's national priorities. The university's environmental programs align with Costa Rica's extraordinary commitment to ecological conservation: the country has protected approximately 26% of its territory as national parks and reserves, making it a world leader in biodiversity conservation. UNA's research on tropical biodiversity has contributed significantly to global environmental science.",
        "causes": ["Costa Rica's 1948 military abolition redirecting defense spending to education and health creating conditions for university expansion", "1970s Costa Rican higher education expansion requiring new public universities for democratic access to tertiary education", "National development strategy emphasizing education and environmental conservation requiring university-level research capacity", "Heredia regional center requiring university to serve students outside the San José metropolitan area"],
        "effects": ["UNA providing accessible public higher education as part of Costa Rica's democratic educational commitment", "Environmental science programs supporting Costa Rica's extraordinary biodiversity conservation achievements", "Third public university expanding access to higher education for Costa Rican students across income levels", "Research contributions to tropical ecology and environmental science benefiting global environmental knowledge"],
        "relationships": [{"entity": "Costa Rican Democracy", "relationship": "PUBLIC_UNIVERSITY_COMPONENT_OF_EDUCATIONAL_INVESTMENT_OF", "note": "UNA was founded as part of Costa Rica's exceptional democratic commitment to accessible public higher education"}, {"entity": "Military Abolition 1948", "relationship": "EDUCATIONAL_INVESTMENT_ENABLED_BY_HISTORIC", "note": "Costa Rica's 1948 military abolition created sustainable educational funding that eventually enabled UNA's 1973 founding"}, {"entity": "Costa Rican Biodiversity Conservation", "relationship": "ENVIRONMENTAL_RESEARCH_SUPPORTING", "note": "UNA's environmental science programs support Costa Rica's world-leading biodiversity conservation policies"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The National University of Costa Rica — founded as part of the educational investment enabled by Costa Rica's historic 1948 military abolition, contributing to the democratic development that makes Costa Rica exceptional in Latin America — is historically significant as a monument to Central America's most democratic and educationally committed nation.", "significanceCategory": "continental"},
    }),
    ("national-university-of-east-timor", {
        "summary": "The National University of East Timor (Universidade Nacional Timor Lorosa'e, UNTL, founded 2000), established in Dili shortly after East Timor's independence referendum (1999) and formal independence (2002) — is the flagship higher education institution of one of the world's newest nations, a country that achieved independence after nearly 24 years of brutal Indonesian occupation (1975-1999) during which an estimated 100,000-180,000 Timorese died from violence, famine, and disease, and whose first post-independence generation required urgent educational infrastructure.\n\nEast Timor's path to independence is one of the most remarkable in modern history: a former Portuguese colony that Indonesia invaded in 1975 and occupied for 24 years against the will of the Timorese people, subject to systematic human rights abuses including the 1991 Santa Cruz Massacre (when Indonesian soldiers killed over 200 civilians in Dili) that became internationally televised, the country voted for independence in the 1999 UN-supervised referendum (78.5% for independence) and subsequently suffered violence by Indonesian-backed militias before UN peacekeeping intervention.\n\nUNTL was established in the immediate aftermath of independence to address East Timor's acute shortage of educational infrastructure — the Indonesian occupation had destroyed much of the educational system, and the post-referendum violence in 1999 further devastated what remained. The university operates in both Tetum (the national language) and Portuguese (the official language alongside Tetum), reflecting the complex linguistic heritage of Portuguese colonial period overlaid by Indonesian occupation and the need to rebuild institutional capacity in a newly independent state.",
        "causes": ["East Timor's 1999 independence referendum requiring immediate establishment of national educational institutions", "Indonesian occupation's destruction of educational infrastructure creating urgent need for university-level education", "Post-independence nation-building requiring institutions to train the professional cadre needed for a functioning state", "Linguistic complexity (Tetum, Portuguese, Indonesian) requiring university to operate in multiple languages"],
        "effects": ["UNTL as primary higher education institution training East Timor's post-independence professional class", "University operating in Tetum and Portuguese contributing to the revival of Portuguese as East Timor's official language", "International partnerships with Portuguese, Australian, and other universities supporting UNTL's capacity building", "Educational reconstruction contributing to East Timor's post-conflict state-building process"],
        "relationships": [{"entity": "East Timor Independence", "relationship": "IMMEDIATE_EDUCATIONAL_INSTITUTION_ESTABLISHED_AFTER", "note": "UNTL was founded in 2000 as one of the first national institutions after the 1999 independence referendum"}, {"entity": "Indonesian Occupation", "relationship": "EDUCATIONAL_RECOVERY_FROM_24-YEAR_DESTRUCTION_OF", "note": "UNTL was established to rebuild educational infrastructure destroyed during Indonesia's 1975-1999 occupation"}, {"entity": "East Timor", "relationship": "FLAGSHIP_HIGHER_EDUCATION_INSTITUTION_OF_WORLD'S_NEWEST_NATION", "note": "UNTL is the national university of one of the world's newest sovereign states, founded in 2000 after 1999 independence"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The National University of East Timor — founded in 2000 as one of the first institutions of one of the world's newest nations after 24 years of brutal Indonesian occupation — is historically significant as a monument to East Timorese national resilience and the educational reconstruction of a post-colonial, post-occupation society.", "significanceCategory": "world-changing"},
    }),
    ("kyoto-university-of-education", {
        "summary": "Kyoto University of Education (京都教育大学, Kyōto Kyōiku Daigaku, founded 1949 with origins in a 1876 Meiji-era normal school) is one of Japan's specialized national universities for teacher education, part of the network of prefectural and national education universities established throughout Japan to train the teachers who would staff Japan's world-class public school system — the educational infrastructure that underlay Japan's extraordinary post-Meiji economic and social development.\n\nJapan's emphasis on teacher education as a specialized discipline reflects its national commitment to education quality: Japan developed dedicated normal schools (师範学校, shihan gakkō) from the early Meiji period (1872 education law) specifically to train professional teachers according to modern pedagogical methods. These normal schools were a cornerstone of Japan's educational modernization — ensuring that the mass public education system being created had qualified teachers trained in systematic pedagogy.\n\nKyoto's University of Education's location in Japan's cultural capital gives it particular significance for teacher education: Kyoto's extraordinary cultural heritage (World Heritage Sites, traditional arts, classical Japanese literature, Buddhist and Shinto traditions) makes it an exceptionally rich environment for education in Japanese cultural subjects. Teachers trained in Kyoto bring exposure to the fullest expression of Japanese traditional culture. The university contributes to the teaching profession in the Kyoto-Osaka-Kobe metropolitan area, one of Japan's most populous and culturally rich regions.",
        "causes": ["Meiji 1872 normal school program requiring teacher training institutions in each prefecture", "Japan's educational modernization requiring systematically trained professional teachers for mass public schooling", "Post-WWII university reorganization (1949) transforming normal schools into formal universities", "Kyoto's cultural heritage making it an ideal location for teacher education in Japanese cultural subjects"],
        "effects": ["Teacher training contributing to Japan's exceptional public school system that supported economic modernization", "Kyoto-based teacher education exposing future teachers to Japan's richest cultural heritage environment", "Normal school network's transformation into education universities maintaining specialized pedagogy training", "Kansai regional teacher supply supported through the university's training programs"],
        "relationships": [{"entity": "Meiji Normal School System", "relationship": "EVOLVED_FROM_1876_NORMAL_SCHOOL_OF", "note": "The university originated in an 1876 Meiji-era normal school as part of Japan's systematic teacher education program"}, {"entity": "Japan's Public Education System", "relationship": "TEACHER_TRAINING_INSTITUTION_SUPPORTING", "note": "The university trains teachers for Japan's world-class public school system in the Kansai region"}, {"entity": "Kyoto Cultural Heritage", "relationship": "EDUCATIONAL_ENVIRONMENT_PROVIDING_JAPAN'S_RICHEST_CULTURAL_CONTEXT", "note": "Kyoto's extraordinary cultural heritage enriches teacher education in Japanese cultural subjects"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "Kyoto University of Education — evolved from an 1876 Meiji normal school, training teachers for Japan's exceptional public school system in Japan's cultural capital — is historically significant as part of the teacher education infrastructure that underpinned Japan's extraordinary educational and economic development.", "significanceCategory": "continental"},
    }),
    ("kyoto-university-of-foreign-studies", {
        "summary": "Kyoto University of Foreign Studies (京都外国語大学, Kyōto Gaikokugo Daigaku, founded 1947) is a private specialized university in Kyoto focusing on foreign language education, intercultural communication, and international studies — one of Japan's foreign-language universities that emerged from the post-WWII period's urgent need for Japanese professionals with foreign language skills to support Japan's reintegration into the international community and eventual economic export-led recovery.\n\nJapan's post-WWII language university boom reflected a specific historical necessity: Japan's defeat in WWII and American occupation created an urgent need for Japanese people who could communicate with Americans (English), while Japan's subsequent economic recovery required professionals who could navigate international business and diplomacy in multiple languages. Specialized foreign-language universities (like the Tokyo University of Foreign Studies, founded 1897 and reorganized post-WWII) were a Japanese educational response to this need.\n\nKyoto University of Foreign Studies' founding in 1947 — literally during the American occupation — reflects this post-war reorientation. The university has developed programs in English, Spanish, Portuguese, Chinese, and other languages, reflecting Japan's global economic relationships. Kyoto's context gives the university particular exposure to traditional Japanese culture alongside international perspectives — a combination that shapes its approach to intercultural education.",
        "causes": ["Post-WWII American occupation creating urgent demand for English-language competence in Japan", "Japan's economic recovery requiring internationally competent professionals for export-led growth strategy", "1947 founding during occupation reflecting the immediate post-war prioritization of international communication skills", "Kyoto's cultural environment providing traditional Japanese cultural context for international studies"],
        "effects": ["Foreign language education contributing to Japan's post-war economic integration and export competitiveness", "Multilingual professionals trained for Japanese international business in English, Spanish, Portuguese, Chinese", "Intercultural communication programs developing Japan's capacity for global engagement across multiple language communities", "Kyoto-based international studies combining traditional Japanese cultural education with foreign language competency"],
        "relationships": [{"entity": "Post-WWII Japan", "relationship": "FOUNDED_DURING_OCCUPATION_TO_ADDRESS_LANGUAGE_NEEDS_OF", "note": "The 1947 founding during the American occupation reflects post-war Japan's urgent need for foreign language competence"}, {"entity": "Japanese Export Economy", "relationship": "FOREIGN_LANGUAGE_EDUCATION_SUPPORTING_INTERNATIONAL_COMPETITIVENESS_OF", "note": "The university trained multilingual professionals who contributed to Japan's export-led economic recovery"}, {"entity": "Kyoto", "relationship": "TRADITIONAL_CULTURAL_CONTEXT_FOR_INTERCULTURAL_STUDIES", "note": "Kyoto's extraordinary cultural heritage provides unique context for international studies education"}],
        "historicalSignificance": {"significanceScore": 4, "significanceNarrative": "Kyoto University of Foreign Studies — founded during the American occupation (1947) to address post-war Japan's foreign language needs, contributing to Japan's international economic reintegration — is locally significant as part of Japan's post-WWII educational adaptation to internationalization.", "significanceCategory": "local"},
    }),
    ("kyoto-sangyo-university", {
        "summary": "Kyoto Sangyo University (京都産業大学, Kyōto Sangyō Daigaku, founded 1965) is a comprehensive private university in Kyoto, Japan — one of the major private universities in the Kansai region — offering programs in sciences, economics, business, foreign languages, law, and cultural studies. The university was founded during Japan's high-growth economic period (1960s) when rapid industrialization created demand for business and technical education that existing universities could not fully meet, and its name ('Sangyo' meaning 'industry/production') reflects its original emphasis on practical business and economic education.\n\nJapan's 1960s university expansion occurred alongside the extraordinary economic growth period (approximately 1955-1973) during which Japan achieved the fastest sustained economic growth in history, transforming from a devastated post-war economy to the world's second-largest economy. This transformation created massive demand for business, engineering, and technical education that drove the founding of many new private universities across Japan.\n\nKyoto Sangyo University has grown to approximately 13,000 students and offers a broad curriculum including notable programs in international relations, cultural studies, and science. Its Kamigamo campus in northern Kyoto is situated near some of Kyoto's most important Shinto shrines (Kamigamo Shrine, UNESCO World Heritage). The university contributes to Kyoto's educational ecosystem while focusing more on practical business and science education than the classical humanities emphasis of some of Kyoto's older institutions.",
        "causes": ["Japan's high-growth 1960s economy creating demand for business and technical higher education institutions", "Private university sector expansion filling gaps in public university capacity during Japan's rapid industrialization", "Kyoto's educational market providing context for a comprehensive private university serving the Kansai region", "'Sangyo' founding emphasis on industry and business reflecting 1960s Japan's practical educational priorities"],
        "effects": ["Comprehensive private university providing business, science, and cultural studies education in Kyoto", "13,000+ student enrollment making it a significant component of Kyoto's higher education ecosystem", "Post-war Japan's economic modernization supported through business and technical professional training", "Northern Kyoto campus contributing to the academic presence near Kamigamo Shrine area"],
        "relationships": [{"entity": "Japan High-Growth Period", "relationship": "FOUNDED_DURING_ECONOMIC_EXPANSION_REQUIRING_MORE_UNIVERSITIES", "note": "The 1965 founding reflects Japan's high-growth economy's demand for expanded business and technical higher education"}, {"entity": "Kyoto", "relationship": "PRIVATE_UNIVERSITY_COMPONENT_OF_ACADEMIC_ECOSYSTEM_OF", "note": "The university is one of approximately 37 higher education institutions in Kyoto's exceptionally dense academic environment"}, {"entity": "Kansai Region", "relationship": "COMPREHENSIVE_PRIVATE_UNIVERSITY_SERVING", "note": "The university serves the Kansai region's higher education needs alongside the major national universities"}],
        "historicalSignificance": {"significanceScore": 3, "significanceNarrative": "Kyoto Sangyo University — founded during Japan's high-growth 1960s economic transformation to meet demand for business and technical education — is locally significant as part of Kyoto's comprehensive educational ecosystem during Japan's most dramatic economic period.", "significanceCategory": "local"},
    }),
    ("national-university-of-engineering", {
        "summary": "The National University of Engineering (Universidad Nacional de Ingeniería, UNI, founded 1876 in Lima, Peru) is one of Latin America's oldest engineering universities — established during Peru's post-War of the Pacific reconstruction period when the country needed trained engineers for infrastructure rebuilding, mining development, and modernization — and has since become Peru's premier engineering institution, training the technical professionals who shaped Peru's 20th-century development.\n\nThe 1876 founding of UNI (originally as the Escuela de Ingeniería) came in the context of Peru's devastating defeat in the War of the Pacific (1879-1884, in which Peru lost its southern provinces of Tarapacá and Arica to Chile along with the valuable nitrate deposits). The need to rebuild Peru's devastated infrastructure and develop its remaining natural resources required trained engineers. UNI was established to train the Peruvian engineers who would rebuild the country and manage its technical development.\n\nUNI has been Peru's primary source of engineering education for nearly 150 years, training civil, mining, industrial, and systems engineers who constructed Peru's modern infrastructure, managed its mining industry (one of the world's most important mineral producers), and drove its technological development. The university's central Lima campus and its research in areas like seismic engineering (crucial for Peru's earthquake-prone geography) have made it Peru's most technically significant educational institution.",
        "causes": ["War of the Pacific (1879-1884) defeat requiring Peruvian engineering education for infrastructure reconstruction", "Peru's mineral wealth requiring trained mining engineers for responsible resource development", "1876 founding reflecting Latin American nations' need for technical education institutions to support modernization", "Lima's position as Peru's capital and economic center requiring technical university for national engineering training"],
        "effects": ["Nearly 150 years of engineering education producing Peru's technical professional cadre across all engineering disciplines", "Infrastructure rebuilding after War of the Pacific supported through trained civil and mining engineers", "Peru's mining industry development managed by UNI-trained mining engineers contributing to mineral export economy", "Seismic engineering research supporting construction practices in one of the world's most earthquake-prone nations"],
        "relationships": [{"entity": "War of the Pacific", "relationship": "POST-WAR_RECONSTRUCTION_CONTEXT_FOR_1876_FOUNDING_OF", "note": "UNI was founded in the aftermath of Peru's devastating War of the Pacific defeat requiring engineering education for rebuilding"}, {"entity": "Peru", "relationship": "PREMIER_ENGINEERING_UNIVERSITY_OF", "note": "UNI is Peru's most important engineering institution, training the technical professionals who built modern Peru"}, {"entity": "Latin American Technical Education", "relationship": "ONE_OF_OLDEST_ENGINEERING_UNIVERSITIES_IN", "note": "The 1876 founding makes UNI one of Latin America's oldest and most historically significant engineering universities"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The National University of Engineering Lima — one of Latin America's oldest engineering universities, founded after Peru's devastating War of the Pacific defeat to train the engineers who rebuilt the country — is historically significant as Peru's premier technical institution over nearly 150 years of national development.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 132 — Class 381 Universities VI: Kyoto + National Universities")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
