#!/usr/bin/env python3
"""Batch 144 — Class 312 Dynasties XIV: Asian Imperial Dynasties (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/312-Class-312"
FILE_PREFIX = "312"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("qing-dynasty", {
        "summary": "The Qing Dynasty (清朝, Qīng Cháo), founded in 1644 when the Manchu Aisin Gioro clan conquered China from the north replacing the Ming Dynasty — was China's last imperial dynasty, ruling approximately 400-500 million people at its height across the largest Chinese empire ever assembled (including Xinjiang, Tibet, Mongolia, and Taiwan), and ending in 1912 when Emperor Puyi abdicated following the Xinhai Revolution, closing 2,132 years of Chinese imperial rule.\n\nThe Qing rulers were ethnic Manchus — a small northeastern people who conquered the vastly more numerous Han Chinese — and the dynasty's management of this demographic asymmetry was one of history's most sophisticated strategies of minority rule: Manchu banners maintained military control while Han Chinese were incorporated into governance through the civil service examination system; Qing emperors presented themselves as universal rulers to different subjects (Confucian Son of Heaven to Han Chinese, Khan to Mongols, Patron of Tibetan Buddhism to Tibetans), creating a multi-ethnic imperial synthesis.\n\nQing's decline and fall is one of history's most consequential collapses: the Opium Wars (1839-1842, 1856-1860) opened China to Western commercial dominance; the Taiping Rebellion (1850-1864, approximately 20-30 million dead — possibly history's deadliest civil war) nearly destroyed the dynasty; the 1895 Sino-Japanese War lost Taiwan and revealed Qing weakness; the Boxer Rebellion (1900) led to humiliating Western occupation of Beijing. The 1911 Xinhai Revolution ended 2,000 years of imperial governance, creating the Republic of China.",
        "causes": ["Manchu military power overcoming Ming Dynasty's defensive weakness and internal rebellions in 1644", "Li Zicheng's rebel forces capturing Beijing (1644) creating the power vacuum that enabled Manchu Qing conquest", "Qing adoption of Ming administrative and Confucian governance systems enabling Han Chinese acceptance of Manchu rule", "Multi-ethnic governing strategy allowing Qing to rule Tibet, Mongolia, and Xinjiang as a multi-civilizational empire"],
        "effects": ["Qing Dynasty ruling China for 268 years (1644-1912) as the last Chinese imperial dynasty", "Qing territorial expansion assembling the largest Chinese empire incorporating Xinjiang, Tibet, and Mongolia", "Opium Wars opening China to Western commercial and political dominance and triggering a century of humiliation", "1911 Xinhai Revolution ending 2,132 years of Chinese imperial governance and establishing the Republic of China"],
        "relationships": [{"entity": "Ming Dynasty", "relationship": "CONQUERED_AND_REPLACED_AS_CHINA'S_RULING_DYNASTY", "note": "The Qing Dynasty conquered and replaced the Ming in 1644, ending 276 years of Ming rule"}, {"entity": "Taiping Rebellion", "relationship": "NEARLY_DESTROYED_BY_CATASTROPHIC_20_MILLION_DEAD_CIVIL_WAR_OF", "note": "The Taiping Rebellion (1850-1864) killed approximately 20-30 million people and severely weakened the Qing Dynasty"}, {"entity": "Xinhai Revolution", "relationship": "OVERTHROWN_BY_1911_ENDING_CHINESE_IMPERIAL_SYSTEM", "note": "The 1911 Xinhai Revolution ended Qing rule and 2,132 years of Chinese imperial governance"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Qing Dynasty — China's last imperial dynasty ruling 400-500 million people, assembling China's largest empire, whose collapse ended 2,132 years of imperial rule — is one of history's most consequential ruling houses, whose fall created modern China's political and territorial foundations.", "significanceCategory": "world-changing"},
    }),
    ("ming-dynasty", {
        "summary": "The Ming Dynasty (明朝, Míng Cháo), founded in 1368 by Zhu Yuanzhang (the Hongwu Emperor) when he expelled the Mongol Yuan Dynasty — ruled China for 276 years and represented one of history's greatest periods of orderly governance, economic prosperity, and cultural florescence, achieving an estimated 25-35% of world GDP at its height, overseeing Zheng He's extraordinary naval expeditions (1405-1433), building the Great Wall in its current form, and creating a sophisticated bureaucratic state that has significantly influenced subsequent Chinese governance.\n\nMing China's scale was extraordinary: at its height, the Ming capital Nanjing (then Beijing after the 15th-century capital move) governed approximately 200-300 million people with a sophisticated civil service examination system, a professional bureaucracy, and an agricultural economy that sustained one of the world's largest populations. The Yongle Emperor (r. 1402-1424) built the Forbidden City in Beijing and sponsored Zheng He's seven naval expeditions — the largest pre-modern naval fleet in history, reaching East Africa and potentially further.\n\nMing's fall in 1644 resulted from a combination of factors: climate disruption (the Little Ice Age reducing agricultural yields), peasant rebellions (Li Zicheng's forces capturing Beijing), Manchu military pressure from the northeast, and fiscal exhaustion. The Chinese Ming-Qing transition of the 1640s was one of the most catastrophically violent dynastic transitions in history, with death tolls estimated at 25 million or more across the decades of warfare.",
        "causes": ["Zhu Yuanzhang's peasant revolt expelling the Mongol Yuan Dynasty and founding the Ming in 1368", "Han Chinese nationalism following Mongol rule providing the political legitimacy for Ming restoration of Chinese culture", "Sophisticated civil service examination system creating a meritocratic bureaucracy capable of governing vast territories", "Yongle Emperor's ambitions sponsoring the Forbidden City's construction and Zheng He's naval expeditions"],
        "effects": ["Ming governance of approximately 200-300 million people representing one of history's largest and most sophisticated states", "Zheng He's seven naval expeditions (1405-1433) reaching East Africa as the world's largest pre-modern naval exploration", "Great Wall's current form built primarily under Ming dynasty as northern defense against nomadic peoples", "Ming-Qing transition (1644) killing approximately 25 million people in one of history's most violent dynastic changes"],
        "relationships": [{"entity": "Yuan Dynasty", "relationship": "EXPELLED_MONGOL_DYNASTY_REPLACED_BY_CHINESE_RESTORATION", "note": "The Ming was founded when Zhu Yuanzhang expelled the Mongol Yuan Dynasty in 1368"}, {"entity": "Zheng He", "relationship": "SPONSORED_SEVEN_NAVAL_EXPEDITIONS_OF_WORLD'S_LARGEST_PRE-MODERN_FLEET", "note": "The Ming Yongle Emperor sponsored Zheng He's seven naval expeditions with hundreds of ships reaching East Africa"}, {"entity": "Qing Dynasty", "relationship": "REPLACED_BY_MANCHU_CONQUEST_IN_1644", "note": "The Ming Dynasty was conquered by the Manchu Qing in 1644, ending 276 years of Ming rule"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Ming Dynasty — governing a quarter of world GDP with sophisticated bureaucracy, sponsoring history's largest naval expeditions, building the Great Wall — is one of history's greatest states and the foundation of China's pre-modern peak.", "significanceCategory": "world-changing"},
    }),
    ("tang-dynasty", {
        "summary": "The Tang Dynasty (唐朝, Táng Cháo), ruling China from 618-907 CE — is considered China's golden age: the most cosmopolitan, internationally connected, culturally vibrant, and artistically creative period in Chinese history, when Chang'an (modern Xi'an) was arguably the world's largest and most culturally diverse city, Chinese poetry reached its apex with Li Bai and Du Fu, Buddhism flourished while other religions including Nestorian Christianity and Islam were tolerated, and the Tang empire represented approximately 25-30% of world GDP at its height.\n\nTang cosmopolitanism was remarkable for the pre-modern world: Chang'an's population of approximately 1 million included Persians, Arabs, Turks, Koreans, Japanese, Sogdian Central Asians, and others — making it one of history's most multiethnic metropolises. The Silk Road connecting China to Central Asia, Persia, and the Roman/Byzantine world was at its height under Tang patronage, with silk, porcelain, and tea flowing west while Buddhism, music, and new foods traveled east. The Nestorian Stele (781 CE) documents the Church of the East's flourishing in Tang China.\n\nTang decline — beginning with the catastrophic An Lushan Rebellion (755-763 CE, possibly killing 36 million people, approximately 1/6 of the world's population at the time) — represents one of history's most dramatic fall from zenith to fragmentation. The Tang never fully recovered, and the dynasty ended in 907 with the Five Dynasties and Ten Kingdoms period. Tang cultural achievements — poetry (Li Bai, Du Fu), Buddhist art, ceramics — remain foundational to East Asian civilization.",
        "causes": ["Li Yuan's 618 CE founding of the Tang Dynasty after Sui Dynasty's collapse creating conditions for strong new governance", "Tang cosmopolitan openness to foreign ideas, religions, and peoples creating the conditions for cultural golden age", "Silk Road commerce at maximum development connecting Tang China to the entire Eurasian world", "Tang military expansion establishing a vast empire incorporating Central Asia and creating conditions for multiethnic capital"],
        "effects": ["Chang'an becoming arguably the world's largest and most cosmopolitan city with approximately 1 million diverse inhabitants", "Chinese poetry reaching its apex with Li Bai and Du Fu's works remaining foundational to Chinese literary culture", "An Lushan Rebellion (755-763) killing approximately 36 million people and permanently weakening Tang governance", "Tang culture providing the foundational aesthetic for East Asian civilization including Japanese and Korean cultural traditions"],
        "relationships": [{"entity": "Silk Road", "relationship": "IMPERIAL_PATRON_AT_HEIGHT_OF_EURASIAN_TRADE_NETWORK_DEVELOPMENT", "note": "The Tang Empire was at the height of Silk Road commercial development, connecting China to the entire Eurasian world"}, {"entity": "An Lushan Rebellion", "relationship": "FATALLY_WEAKENED_BY_755-763_REBELLION_KILLING_36_MILLION", "note": "The An Lushan Rebellion devastated Tang China, killing an estimated 36 million people and permanently weakening the dynasty"}, {"entity": "Li Bai and Du Fu", "relationship": "GOLDEN_AGE_OF_CHINESE_POETRY_SUPPORTED_BY", "note": "The Tang Dynasty's patronage supported Li Bai and Du Fu, the twin peaks of Chinese poetry still considered foundational"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Tang Dynasty — China's golden age with the world's most cosmopolitan capital, peak Chinese poetry, and Silk Road maximum flourishing — is one of history's greatest civilizational achievements and the foundational cultural period for East Asian civilization.", "significanceCategory": "world-changing"},
    }),
    ("song-dynasty", {
        "summary": "The Song Dynasty (宋朝, Sòng Cháo), ruling China from 960-1279 CE — is widely considered history's most economically and technologically innovative pre-modern society, producing the Four Great Inventions (paper already existing, but papermaking spread; printing press with movable type invented by Bi Sheng c.1040; gunpowder weaponized; magnetic compass for navigation) that would transform global history centuries later when they reached Europe, while also achieving the world's first paper currency, sophisticated financial instruments, and an urbanization rate comparable to 18th-century England.\n\nSong China's economic sophistication was extraordinary: the world's first paper money (jiaozi, early Song), sophisticated financial markets, a commercialized economy with significant merchant class, one of the world's most advanced agricultural systems, and an urbanization level unprecedented in pre-industrial history. Song cities like Hangzhou and Kaifeng were among the world's largest and most commercially sophisticated urban environments. Historian Robert Hartwell estimated Song China may have had 25-30% of world GDP.\n\nSong China faced constant military pressure from northern nomadic peoples — eventually losing northern China to the Jurchen Jin Dynasty (1127, beginning the Southern Song period) before the entire dynasty was conquered by the Mongol Yuan Dynasty in 1279 (the last Song resistance at Yamen involving approximately 100,000 people drowning when the last Song child emperor died). Despite military weakness, Song China's technological and commercial achievements made it one of the most significant civilizational periods in human history.",
        "causes": ["Zhao Kuangyin's 960 CE founding after Five Dynasties period reunifying China around civilian rather than military governance", "Song emphasis on civil governance over military creating conditions for commercial and technological innovation", "Neo-Confucian intellectual renaissance under Song patronage producing sophisticated philosophical synthesis", "Agricultural productivity increases feeding dense commercial urban population supporting technological innovation"],
        "effects": ["Four Great Inventions (movable type printing, gunpowder weaponry, compass) eventually transforming global history when reaching Europe", "World's first paper currency and sophisticated financial instruments pioneering commercial capitalism", "Song urbanization rate and commercial sophistication comparable to 18th-century England three to four centuries earlier", "Mongol conquest (1279) ending Song Dynasty after one of the most catastrophic resistance defeats at Yamen"],
        "relationships": [{"entity": "Four Great Inventions", "relationship": "CIVILIZATION_PRODUCING_TRANSFORMATIVE_TECHNOLOGIES_OF", "note": "Song Dynasty China produced movable type printing (c.1040), weaponized gunpowder, and compass navigation that later transformed European history"}, {"entity": "Mongol Conquest", "relationship": "CONQUERED_BY_YUAN_DYNASTY_IN_1279_ENDING", "note": "The Mongol Yuan Dynasty conquered the last Song resistance in 1279 at the Battle of Yamen"}, {"entity": "World Commercial Economy", "relationship": "PIONEERED_PAPER_CURRENCY_AND_FINANCIAL_INSTRUMENTS_FOUNDATIONAL_TO", "note": "Song China's world-first paper currency and financial instruments pioneered commercial economic innovations later adopted globally"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Song Dynasty — producing the Four Great Inventions, world's first paper currency, and pre-modern peak commercial sophistication — is one of history's most innovative civilizations whose technological achievements transformed subsequent global history.", "significanceCategory": "world-changing"},
    }),
    ("han-dynasty", {
        "summary": "The Han Dynasty (漢朝, Hàn Cháo), ruling China from 206 BCE to 220 CE (with a brief interruption by Wang Mang's Xin Dynasty 9-23 CE) — is one of the most significant dynasties in Chinese history, establishing the model of Chinese governance, culture, and identity that has defined China ever since: the Han people (汉族, Hànzú) — the ethnic designation of 92% of China's 1.4 billion people today — take their name from this dynasty, indicating its foundational role in Chinese civilization.\n\nHan governance achievements were foundational: Emperor Wu (r. 141-87 BCE) institutionalized Confucianism as state philosophy (creating the civil service examination system's predecessor), expanded China's territory through military campaigns to Korea, Central Asia, and Vietnam, established the Silk Road trade networks with Rome and Parthia, and created the Han empire covering approximately 6 million square kilometers. Ban Zhao (45-116 CE) was one of history's earliest known female historians. Sima Qian (c.145-90 BCE) wrote the Shiji (Records of the Grand Historian), the foundational work of Chinese historical tradition.\n\nHan China's trade connections reached the Roman Empire: archaeological evidence and Roman historical sources document silk imports from China ('the land of Seres'), and diplomatic missions may have reached Rome. The Silk Road under Han patronage was one of history's most consequential trade networks, spreading Buddhism (which entered China in this period), silk technology, and eventually facilitating the transmission of Chinese inventions westward.",
        "causes": ["Liu Bang's founding of the Han Dynasty after defeating Qin's successor states following the Qin Dynasty's brief reign", "Institutionalization of Confucianism as state philosophy by Emperor Wu creating the examination system's foundations", "Han military expansion under Emperor Wu incorporating Central Asia and establishing Silk Road connections", "Population growth and agricultural productivity under stable Han governance enabling economic and cultural florescence"],
        "effects": ["'Han people' ethnic designation for 92% of Chinese population deriving from this dynasty's foundational cultural identity", "Civil service examination system's predecessor institutionalizing merit-based governance with 2000-year legacy", "Silk Road establishment connecting China to Rome and Parthia facilitating Eurasian goods and ideas exchange", "Confucianism's Han institutionalization shaping Chinese governance and social organization for 2000+ years"],
        "relationships": [{"entity": "Qin Dynasty", "relationship": "SUCCEEDED_AND_EXPANDED_UPON_UNIFIED_IMPERIAL_SYSTEM_OF", "note": "The Han succeeded the Qin Dynasty, maintaining unified imperial governance while softening the Qin's harsh legalism with Confucianism"}, {"entity": "Silk Road", "relationship": "ESTABLISHED_AND_PATRONIZED_EURASIAN_TRADE_NETWORK_UNDER_EMPEROR_WU", "note": "Emperor Wu's Han campaigns into Central Asia established and secured the Silk Road connecting China to Parthia and Rome"}, {"entity": "Confucianism", "relationship": "INSTITUTIONALIZED_AS_STATE_PHILOSOPHY_AND_GOVERNANCE_FOUNDATION_BY", "note": "The Han Dynasty under Emperor Wu institutionalized Confucianism as state philosophy, shaping Chinese governance for 2000+ years"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Han Dynasty — whose name designates 92% of China's population, who institutionalized Confucianism, established the Silk Road, and created the model of Chinese governance — is one of history's most consequential dynasties and the foundational period of Chinese civilizational identity.", "significanceCategory": "world-changing"},
    }),
    ("mughal-empire", {
        "summary": "The Mughal Empire (Persianate: مغل سلطنت, Mughal Saltanat), founded in 1526 when Babur — a Timurid prince from Central Asia descended from Timur and Genghis Khan — defeated the Delhi Sultanate at the First Battle of Panipat — ruled most of the Indian subcontinent from 1526-1857 (though significantly weakened from the 18th century), governing approximately 100-150 million people at its height under Akbar, representing one of the world's largest economies (approximately 25% of world GDP under Aurangzeb) and producing extraordinary cultural syntheses of Persian, Central Asian, and Indian civilization.\n\nMughal cultural achievement was extraordinary: the Taj Mahal (1632-1653, built by Shah Jahan as a mausoleum for his wife Mumtaz Mahal) is perhaps the world's most widely recognized monument of beauty; the Fatehpur Sikri complex, Mughal miniature painting tradition, Urdu language development (a Persian-Arabic-Sanskrit synthesis), and Mughal architectural style all represent profound cultural syntheses of Persian-Islamic and Indian Hindu traditions. Emperor Akbar's policy of Sulh-e-kul (universal peace, religious tolerance) — allowing Hindu practices, abolishing the jizya tax on non-Muslims, and marrying Hindu Rajput princesses — represented the empire's most enlightened period.\n\nMughal decline after Aurangzeb's death (1707) was rapid: Aurangzeb's imposition of Islamic orthodoxy (reimposing the jizya, destroying Hindu temples) reversed Akbar's tolerance and alienated Hindu and Sikh subjects, fueling Maratha and Sikh resistance. The East India Company gradually absorbed Mughal territories in the 18th-19th centuries, until the 1857 Indian Rebellion's failure led the British Crown to formally abolish the Mughal throne and exiling the last emperor Bahadur Shah Zafar to Burma.",
        "causes": ["Babur's 1526 First Battle of Panipat victory over the Delhi Sultanate founding the Mughal Empire in India", "Timurid and Mongol military traditions providing the military superiority enabling Mughal conquest", "Akbar's religious tolerance (Sulh-e-kul) enabling the consolidation of Mughal rule over India's Hindu majority", "Persian language and culture providing the administrative and artistic framework of Mughal governance"],
        "effects": ["Taj Mahal constructed as the world's most widely recognized monument of beauty under Shah Jahan", "Akbar's Sulh-e-kul religious tolerance policy as a model of interfaith governance in a multi-religious empire", "Mughal economic peak representing approximately 25% of world GDP under Aurangzeb", "1857 Indian Rebellion leading to formal abolition of Mughal throne and British Crown's direct rule over India"],
        "relationships": [{"entity": "Taj Mahal", "relationship": "COMMISSIONED_WORLD'S_MOST_RECOGNIZED_MONUMENT_BY_SHAH_JAHAN_OF", "note": "Mughal Emperor Shah Jahan commissioned the Taj Mahal (1632-1653) as the world's most widely recognized monument"}, {"entity": "Akbar", "relationship": "GREATEST_EMPEROR_WHOSE_SULH-E-KUL_TOLERANCE_DEFINED_BEST_PERIOD_OF", "note": "Akbar's religious tolerance and administrative genius defined the Mughal Empire's greatest period"}, {"entity": "British East India Company", "relationship": "GRADUALLY_SUPPLANTED_BY_ABSORBING_TERRITORIES_OF", "note": "The East India Company gradually absorbed Mughal territories in the 18th-19th centuries, ending Mughal power"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Mughal Empire — governing one of history's largest economies, producing the Taj Mahal, synthesizing Persian-Islamic and Indian civilization under Akbar's tolerance — is one of history's greatest empires and the foundational period of South Asian Islamic and hybrid civilization.", "significanceCategory": "world-changing"},
    }),
    ("ottoman-empire", {
        "summary": "The Ottoman Empire (Ottoman Turkish: دولت عليه عثمانيه, Devlet-i ʿAlīye-i ʿOsmānīye, 'The Sublime Ottoman State'), founded by Osman I in approximately 1299 in northwestern Anatolia — was one of history's longest-lasting and most consequential empires, ruling from the Balkans and southeastern Europe through Anatolia and the Arab Middle East to North Africa for over 600 years, governing approximately 20-35 million people at its height and controlling the strategic crossroads between Europe and Asia at its center in Constantinople (Istanbul).\n\nThe Ottoman Empire's conquest of Constantinople in 1453 (by Mehmed II, aged 21) was one of history's most consequential military events: ending the Byzantine Empire (a direct successor to the Roman Empire in continuous existence for 1,500 years), shifting the balance of power between Christianity and Islam, and forcing European trade routes away from the Ottoman-controlled eastern Mediterranean — thus encouraging the search for alternative routes that directly triggered the Age of Exploration and Columbus's 1492 voyage to the Americas.\n\nOttoman decline and the empire's disintegration in WWI (losing approximately 20% of its total Muslim population to deaths and displacement, while committing the Armenian Genocide killing approximately 600,000-1.5 million Armenians) created the modern Middle East whose borders were drawn at the 1920 Paris Peace Conference (Treaty of Sèvres, superseded by Treaty of Lausanne 1923) by Britain and France — creating artificial states including Iraq, Syria, Lebanon, Jordan, and Palestine whose borders have generated conflict ever since.",
        "causes": ["Osman I's 1299 founding of the Ottoman state in northwestern Anatolia from a small Turkic principality", "Ottoman military system (devshirme slave soldiers, Janissary corps) providing superior military organization", "1453 Constantinople conquest under Mehmed II fulfilling Islamic aspiration and creating the Ottoman capital", "Ottoman governance of diverse ethnic and religious communities through the millet system enabling multi-ethnic empire management"],
        "effects": ["1453 Constantinople conquest forcing European trade rerouting that encouraged the Age of Exploration and Columbus's voyage", "Ottoman governance for 600 years creating the multi-ethnic, multi-religious framework of the Middle East's cultural and political landscape", "Armenian Genocide (1915-1923) killing approximately 600,000-1.5 million Armenians in WWI", "Post-WWI Middle East created by Ottoman collapse with artificial borders generating a century of regional conflict"],
        "relationships": [{"entity": "Constantinople", "relationship": "IMPERIAL_CAPITAL_CONQUERED_IN_1453_AND_RENAMED_ISTANBUL_BY", "note": "Mehmed II conquered Constantinople in 1453, ending Byzantium and creating the Ottoman capital Istanbul"}, {"entity": "Armenian Genocide", "relationship": "COMMITTED_BY_EMPIRE_KILLING_600,000-1.5_MILLION_ARMENIANS_IN_WWI", "note": "The Ottoman Empire committed the Armenian Genocide during WWI, killing approximately 600,000-1.5 million Armenians"}, {"entity": "Age of Exploration", "relationship": "OTTOMAN_CONTROL_OF_EASTERN_TRADE_ROUTES_INDIRECTLY_TRIGGERING", "note": "Ottoman control of Constantinople (1453) forced European trade rerouting that encouraged Columbus's voyage and the Age of Exploration"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Ottoman Empire — 600-year Eurasian empire whose 1453 Constantinople conquest triggered the Age of Exploration, whose WWI collapse created the modern Middle East's conflict-generating borders, and whose genocide of Armenians was the 20th century's first genocide — is one of history's most consequential states.", "significanceCategory": "world-changing"},
    }),
    ("abbasid-caliphate", {
        "summary": "The Abbasid Caliphate (Arabic: الخلافة العباسية, al-Khilāfa al-ʿAbbāsiyya), founded in 750 CE when the Abbasid clan overthrew the Umayyad Caliphate in a revolutionary movement — ruled the Islamic world from Baghdad for approximately 500 years, presiding over the Islamic Golden Age (8th-13th centuries) when Baghdad was arguably the world's largest city and the global center of mathematics, astronomy, medicine, philosophy, and literature, preserving and transmitting Greek knowledge while making original contributions that shaped the Renaissance and scientific revolution in Europe.\n\nThe Abbasid 'House of Wisdom' (Bayt al-Hikmah) in Baghdad — founded in the early 9th century under the Caliph Harun al-Rashid and expanded by al-Ma'mun — was one of history's most significant intellectual institutions: translating Greek texts (Aristotle, Plato, Euclid, Hippocrates, Ptolemy) into Arabic and Persian, producing original works in mathematics (al-Khwarizmi invented algebra and the term 'algorithm' derives from his name), optics (Ibn al-Haytham), medicine (Ibn Sina/Avicenna), and philosophy (al-Farabi, Ibn Rushd/Averroes). This knowledge transmission was crucial: when medieval Europe eventually translated Arabic versions of ancient Greek texts, it helped trigger the Renaissance.\n\nThe Abbasid Caliphate's 1258 destruction by the Mongols under Hulagu Khan — when Baghdad was sacked and approximately 200,000-800,000 people massacred, the House of Wisdom's books thrown into the Tigris River (reportedly turning the river black with ink) — was one of history's most catastrophic cultural destructions, ending the Islamic Golden Age and permanently shifting the center of gravity of Islamic civilization.",
        "causes": ["Abbasid revolution of 750 CE overthrowing Umayyad Caliphate with support from Persian Muslims and mawali (non-Arab converts)", "Baghdad's 762 CE foundation as Abbasid capital creating an ideally positioned commercial and intellectual center", "Caliph al-Mansur and successors' patronage of Greek text translation establishing the House of Wisdom", "Persian administrative and intellectual traditions incorporated into Abbasid governance providing sophisticated institutional foundation"],
        "effects": ["Islamic Golden Age (8th-13th centuries) producing original contributions in algebra, optics, medicine, and philosophy", "House of Wisdom's Arabic translations of Greek texts preserving knowledge that later enabled European Renaissance", "Al-Khwarizmi's invention of algebra and algorithmic mathematics providing foundational tools for all subsequent mathematics", "1258 Mongol destruction of Baghdad ending the Islamic Golden Age and destroying incalculable cultural heritage"],
        "relationships": [{"entity": "House of Wisdom", "relationship": "FOUNDED_AND_PATRONIZED_WORLD'S_GREATEST_MEDIEVAL_INTELLECTUAL_INSTITUTION", "note": "The Abbasid Caliphate founded Baghdad's House of Wisdom, producing the Islamic Golden Age's greatest intellectual achievements"}, {"entity": "Mongol Invasion of Baghdad", "relationship": "CATASTROPHICALLY_DESTROYED_BY_1258_SACK_BY_HULAGU_KHAN", "note": "Hulagu Khan's 1258 sack of Baghdad destroyed the Abbasid Caliphate, killing hundreds of thousands and ending the Islamic Golden Age"}, {"entity": "European Renaissance", "relationship": "ARABIC_TRANSLATIONS_OF_GREEK_TEXTS_HELPING_TRIGGER", "note": "Abbasid Arabic translations of Greek knowledge were transmitted to Europe and helped trigger the Renaissance"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Abbasid Caliphate — presiding over the Islamic Golden Age, preserving Greek knowledge in Baghdad's House of Wisdom, producing algebra — is one of history's most consequential civilizations whose intellectual achievements shaped the European Renaissance and all subsequent mathematics and science.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 144 — Class 312 Dynasties XIV: Asian Imperial Dynasties")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
