#!/usr/bin/env python3
"""Batch 134 — Class 342 Mosques V: Southeast Asian & Global Mosques (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/342-Class-342"
FILE_PREFIX = "342"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("al-azhar-mosque", {
        "summary": "Al-Azhar Mosque (Arabic: الجامع الأزهر, Al-Jāmiʿ al-Azhar — 'The Most Resplendent Mosque') in Cairo, Egypt, founded in 970–972 CE by the Fatimid Caliph al-Muizz's general Jawhar al-Siqilli — is one of the world's oldest mosques and universities, and the most important institution of Sunni Islamic scholarship in the world. Al-Azhar University (founded alongside the mosque) is the world's oldest continuously operating university (predating Bologna by over a century), and Al-Azhar's scholarly opinions (fatwas) on Islamic jurisprudence, theology, and contemporary issues carry authoritative weight throughout the Sunni Muslim world.\n\nAl-Azhar's founding by the Fatimid Caliphate (a Shi'a Ismaili dynasty) as an Ismaili institution is a profound historical irony: after Saladin (Salah ad-Din, founder of the Ayyubid dynasty) overthrew the Fatimids in 1171, Al-Azhar was converted to Sunni Shafi'i use and eventually became the greatest center of Sunni scholarship — despite its Ismaili origins. Al-Azhar's evolution reflects Islamic history's complex sectarian transformations and the remarkable adaptability of religious institutions.\n\nIn the modern era, Al-Azhar serves as the most authoritative voice of mainstream Sunni Islam globally: its fatwas on contested issues (suicide bombing, interfaith marriage, Islamic finance) are followed by Muslim communities worldwide, and its certification of Islamic educational materials influences the curriculum in Muslim-majority countries across Asia, Africa, and the Middle East. With approximately 500,000 students from 100+ countries, Al-Azhar University remains the world's largest institution of Islamic education.",
        "causes": ["Fatimid Caliphate's founding of Cairo (969 CE) requiring central mosque for the new Shi'a Ismaili capital", "Fatimid political-religious mission requiring educational institution to propagate Ismaili scholarship", "Saladin's 1171 Ayyubid overthrow of Fatimids converting Al-Azhar to Sunni use", "Medieval Cairo's emergence as the Muslim world's most important city making Al-Azhar the center of Sunni scholarship"],
        "effects": ["Al-Azhar as the world's most authoritative Sunni Islamic scholarly institution for over 1,000 years", "Al-Azhar University as one of the world's oldest continuously operating universities (predating Bologna)", "Global Islamic jurisprudence shaped by Al-Azhar fatwas affecting 1.8 billion Muslims worldwide", "500,000+ students from 100+ countries making it the world's largest institution of Islamic religious education"],
        "relationships": [{"entity": "Fatimid Caliphate", "relationship": "FOUNDED_BY_AS_ISMAILI_INSTITUTION_LATER_CONVERTED", "note": "Al-Azhar was founded by the Fatimid Caliphate in 970-972 CE as an Ismaili mosque, later converted to Sunni use"}, {"entity": "Sunni Islam", "relationship": "MOST_AUTHORITATIVE_SCHOLARLY_INSTITUTION_OF", "note": "Al-Azhar is the world's most authoritative Sunni Islamic scholarship center, its fatwas followed by Muslims globally"}, {"entity": "Islamic Education", "relationship": "WORLD'S_OLDEST_AND_LARGEST_INSTITUTION_OF_RELIGIOUS", "note": "Al-Azhar University (founded c.972 CE) is among the world's oldest universities and the largest institution of Islamic education"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "Al-Azhar Mosque and University — founded 970 CE, the world's most authoritative Sunni Islamic scholarly institution for over 1,000 years, one of the oldest continuously operating universities, shaping Islamic jurisprudence for 1.8 billion Muslims — is among the most historically significant religious and educational institutions in human history.", "significanceCategory": "world-changing"},
    }),
    ("al-baitul-amien-mosque", {
        "summary": "Al-Baitul Amien Grand Mosque (Indonesian: Masjid Agung Al-Baitul Amien) in Jember, East Java, Indonesia, is one of East Java's significant regional mosques, serving the Muslim community of Jember — a major agricultural town in East Java known for tobacco cultivation — and reflecting the deep integration of Islamic practice into Javanese and Indonesian social and cultural life. The mosque represents the local expression of Indonesian Islamic architecture that blends Middle Eastern influences with Javanese cultural elements.\n\nIndonesia is the world's most populous Muslim-majority country (approximately 270 million population, approximately 87% Muslim), and Java — with approximately 150 million people — is the world's most populous island and home to the majority of Indonesian Muslims. East Java is historically significant for Islam: the Wali Songo (Nine Saints, Islamic missionaries who spread Islam in Java in the 15th-16th centuries) had significant presence in East Java, and the region developed a distinctive Javanese Islam that synthesized Islamic practice with pre-Islamic Javanese culture.\n\nJember's Al-Baitul Amien mosque, as a major city mosque in East Java, serves the community functions that mosques play in Indonesian Islamic life: not only daily prayers and Friday sermons but Islamic education, social welfare programs, and community organization. The mosque's architecture — combining dome and minaret elements with local Javanese architectural traditions — reflects the visual synthesis that characterizes Indonesian mosque design.",
        "causes": ["Jember's Muslim community requiring a major congregational mosque reflecting community's size and piety", "East Java's Islamic tradition requiring expression in significant local mosque architecture", "Indonesian Islamic architectural tradition combining Middle Eastern and Javanese elements in regional mosque design", "Jember's agricultural wealth (tobacco industry) providing resources for mosque construction"],
        "effects": ["Mosque serving as Jember's primary congregational and community center for the local Muslim majority", "East Javanese Islamic architecture represented in Jember's most significant religious building", "Islamic education and community programs based in the mosque serving Jember's Muslim population", "Local expression of Indonesian Islamic synthesis documented in mosque's architectural character"],
        "relationships": [{"entity": "East Java", "relationship": "SIGNIFICANT_REGIONAL_MOSQUE_REPRESENTING_ISLAMIC_TRADITION_OF", "note": "The mosque represents East Java's deep Islamic heritage shaped by the Wali Songo missionaries"}, {"entity": "Indonesian Islam", "relationship": "LOCAL_EXPRESSION_OF_JAVANESE_ISLAMIC_ARCHITECTURAL_SYNTHESIS", "note": "The mosque's architecture reflects the Indonesian blend of Middle Eastern Islamic and Javanese cultural elements"}, {"entity": "Jember", "relationship": "MAJOR_CONGREGATIONAL_MOSQUE_OF_AGRICULTURAL_CITY", "note": "Al-Baitul Amien serves as the primary congregational mosque of Jember, East Java's major tobacco agricultural center"}],
        "historicalSignificance": {"significanceScore": 3, "significanceNarrative": "Al-Baitul Amien Grand Mosque Jember — representing East Java's Islamic architectural tradition in the world's most populous Muslim-majority country — is locally significant as a community center of Jember's Muslim population.", "significanceCategory": "local"},
    }),
    ("baitul-awwal-mosque", {
        "summary": "Baitul Awwal Mosque, one of the Ahmadiyya Muslim Community's mosque buildings, represents the global mosque-building program of the Ahmadiyya Muslim Community — an Islamic movement founded in 1889 by Mirza Ghulam Ahmad in Qadian, India, which claims to be the reforming movement of Islam in the modern era but is considered heretical and non-Muslim by mainstream Sunni and Shia authorities, resulting in its members being officially declared non-Muslims in Pakistan (1974) and subject to severe persecution in Pakistan and parts of Indonesia.\n\nThe Ahmadiyya Muslim Community's global mosque-building program ('100 Mosques Campaign' and similar initiatives) has resulted in hundreds of mosques worldwide named with the 'Baitul' (House of) prefix — Baitul Awwal (First House), Baitul Futuh (House of Victories, the largest mosque in Western Europe, in London), etc. — as part of the community's systematic global expansion and its claim to represent true Islam.\n\nThe Ahmadiyya movement is historically significant in several ways: it was founded in British India during the late 19th-century Islamic reform movement, it has been the subject of the most sustained state-sanctioned religious persecution in the modern Islamic world (Pakistan's blasphemy laws making Ahmadi religious practice a criminal offense), and its global missionary activity has made it one of the fastest-growing Islamic movements internationally. The baitul mosques worldwide represent both a religious community's determination and the contested boundaries of Islamic identity.",
        "causes": ["Ahmadiyya Muslim Community's global mosque-building program creating 'Baitul' named mosques worldwide", "Ahmadiyya founder Mirza Ghulam Ahmad's 1889 Islamic reform movement claiming prophetic renewal requiring global propagation", "Ahmadiyya community's systematic global expansion requiring physical mosques in each location", "Persistent Ahmadiyya identity despite official Pakistani designation as non-Muslim"],
        "effects": ["Global network of Ahmadiyya mosques bearing 'Baitul' names representing worldwide community presence", "Ahmadiyya mosque construction as act of faith and identity assertion despite anti-Ahmadiyya persecution", "Global Islamic landscape complicated by Ahmadiyya community's large mosque network in contested Muslim identity space", "Ahmadiyya community's religious freedom advocacy connected to mosque presence in democratic countries"],
        "relationships": [{"entity": "Ahmadiyya Muslim Community", "relationship": "MOSQUE_OF_GLOBAL_BUILDING_PROGRAM_OF", "note": "The mosque is part of the Ahmadiyya Community's global mosque-building program creating hundreds of 'Baitul' named mosques"}, {"entity": "Islamic Identity", "relationship": "CONTESTED_BOUNDARY_OF_REPRESENTED_BY_AHMADIYYA", "note": "Ahmadiyya mosques operate in the contested space of Islamic identity — declared non-Muslim by mainstream authorities but self-identifying as Muslim"}, {"entity": "Religious Persecution", "relationship": "COMMUNITY_FACING_STATE-SANCTIONED_PERSECUTION_BUILDING", "note": "Ahmadiyya mosques represent a community's religious determination despite state-sanctioned persecution in Pakistan and Indonesia"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "Baitul Awwal Mosque — representing the Ahmadiyya Muslim Community's global mosque-building program in the face of state-sanctioned persecution — is historically significant as a monument to a controversial Islamic reform movement's determination and the contested boundaries of Islamic identity in the modern era.", "significanceCategory": "local"},
    }),
    ("baitul-falah", {
        "summary": "Baitul Falah (Arabic: بيت الفلاح, House of Success/Salvation) is an Ahmadiyya mosque name used in multiple global locations by the Ahmadiyya Muslim Community — reflecting the community's systematic naming tradition for mosques using 'Baitul' (House of) Arabic phrases. As with other Ahmadiyya mosque buildings worldwide, Baitul Falah mosques represent local Ahmadiyya community centers that provide prayer spaces, Islamic education, and community organization for Ahmadiyya Muslims in their respective cities.\n\nThe name 'Falah' (فلاح, meaning success, prosperity, salvation, or welfare) is a significant concept in Islamic tradition, appearing in the call to prayer (Adhan) in the phrase 'Hayya 'ala al-falah' (Come to success/salvation). Ahmadiyya mosques bearing this name reflect the community's identification with classical Islamic terminology and its self-understanding as a movement toward genuine Islamic success and welfare.\n\nAhmadiyya mosques globally play a distinctive role in their local Muslim communities: as members of a community officially designated non-Muslim in Pakistan and persecuted in several other countries, Ahmadiyya Muslims in democratic countries often participate more visibly in interfaith dialogue, social service activities, and civic engagement — using their mosque buildings as centers of community outreach that distinguish them from mainstream Muslim communities. This pattern is evident in how Ahmadiyya mosques function in North American, European, and African locations.",
        "causes": ["Ahmadiyya Muslim Community's global mosque-building program creating mosques named with 'Baitul Falah'", "Local Ahmadiyya community's need for a dedicated prayer and community center", "Ahmadiyya tradition of systematic naming using Arabic 'House of' phrases for all community mosques", "Community identity maintenance requiring physical mosque presence in diverse global locations"],
        "effects": ["Local Ahmadiyya prayer space and community center created for the Muslim minority group", "Interfaith dialogue activities hosted through Ahmadiyya mosques demonstrating community's civic engagement approach", "Ahmadiyya community visibility in local civic life using mosque as outreach and service center", "Islamic community presence in non-Muslim majority areas facilitated through Ahmadiyya mosque establishment"],
        "relationships": [{"entity": "Ahmadiyya Muslim Community", "relationship": "LOCAL_MOSQUE_OF", "note": "Baitul Falah is one of the Ahmadiyya Community's global network of mosques named with Baitul Arabic phrases"}, {"entity": "Islamic Prayer Tradition", "relationship": "MOSQUE_NAMED_FOR_FALAH_CONCEPT_IN", "note": "The name references the Islamic prayer tradition's call to 'falah' (success/salvation) in the Adhan"}, {"entity": "Interfaith Relations", "relationship": "LOCAL_AHMADIYYA_MOSQUE_ADVANCING", "note": "Ahmadiyya mosques often serve as centers of interfaith dialogue, reflecting the community's civic engagement in democratic countries"}],
        "historicalSignificance": {"significanceScore": 2, "significanceNarrative": "Baitul Falah — an Ahmadiyya mosque in the global network of the controversial Islamic reform movement — is locally significant as a community center for a minority Muslim group facing official non-Muslim designation in Pakistan.", "significanceCategory": "local"},
    }),
    ("baitul-huda-mosque", {
        "summary": "Baitul Huda Mosque (Arabic: بيت الهدى, House of Guidance) is one of the larger Ahmadiyya Muslim Community mosques in Australia, located in Sydney — representing the Ahmadiyya community's significant presence in Australia, where the community has been active since the early 20th century and where Australian Ahmadiyya Muslims have built a visible mosque infrastructure and engaged in prominent interfaith activities.\n\nThe Ahmadiyya Muslim Community's Australian presence dates to the 1970s-1980s as South Asian migration to Australia increased following the 1973 relaxation of the White Australia Policy. Ahmadiyya Muslims from Pakistan and India settled in Australia and established community institutions, including mosques. The Sydney Baitul Huda mosque is among Australia's larger mosques and the Ahmadiyya community's primary facility in New South Wales.\n\nAustralia's Muslim community (approximately 3.2% of the population, about 800,000 people) is predominantly South Asian, Lebanese, and Somali in heritage. The Ahmadiyya community within Australian Islam occupies a complex position: respected by Australian society for their interfaith engagement and civic contributions, but not recognized as Muslim by mainstream Sunni and Shia communities. The Baitul Huda mosque in Sydney represents the Ahmadiyya community's established and visible presence in Australian religious life.",
        "causes": ["Post-1973 South Asian migration to Australia including Ahmadiyya Muslims from Pakistan and India", "Australian Ahmadiyya community's need for a substantial mosque reflecting community size in Sydney", "Ahmadiyya global mosque-building program including Australian locations", "Sydney's large Australian Muslim population requiring diverse mosque facilities including Ahmadiyya spaces"],
        "effects": ["Sydney Ahmadiyya community center enabling prayer, Islamic education, and community activities", "Australian Ahmadiyya interfaith engagement using the mosque as a center of civic and religious dialogue", "Ahmadiyya presence in Australian Muslim community landscape contributing to diversity within Islam in Australia", "South Asian Ahmadiyya diaspora community in Sydney maintained through mosque as community hub"],
        "relationships": [{"entity": "Ahmadiyya Muslim Community Australia", "relationship": "PRIMARY_MOSQUE_OF_IN_NEW_SOUTH_WALES", "note": "Baitul Huda is the Ahmadiyya Community's main mosque facility in New South Wales, Australia"}, {"entity": "Australian Muslim Community", "relationship": "AHMADIYYA_COMPONENT_OF_REPRESENTED_BY", "note": "The mosque represents the Ahmadiyya presence within Australia's diverse Muslim community of approximately 800,000"}, {"entity": "South Asian Diaspora", "relationship": "RELIGIOUS_INSTITUTION_SERVING_AHMADIYYA_COMPONENT_OF_AUSTRALIAN", "note": "The mosque serves Ahmadiyya Muslims who immigrated to Australia primarily from Pakistan and India"}],
        "historicalSignificance": {"significanceScore": 3, "significanceNarrative": "Baitul Huda Mosque Sydney — the Ahmadiyya Community's major Australian mosque, representing the community's interfaith engagement in Australian civic life — is locally significant as a monument to a minority Islamic community's established presence in Australian religious life.", "significanceCategory": "local"},
    }),
    ("baitul-jame", {
        "summary": "Baitul Jame (Arabic: بيت الجامع, House of the Congregation) is an Ahmadiyya Muslim Community mosque, reflecting the community's mosque-naming tradition using Arabic 'Baitul' (House of) phrases for community prayer centers worldwide. The name 'Jame' or 'Jami' refers to the congregational nature of Friday mosque worship — a 'Masjid Jami' (congregational mosque) is traditionally one large enough and properly established to hold the Friday (Jumu'ah) prayer that is obligatory for adult Muslim men.\n\nThe Ahmadiyya use of the 'Jame' (congregational) designation in a mosque name reflects the community's identification with central Islamic traditions and its claim to mainstream Islamic practice — a claim explicitly denied by Pakistan's 1974 Second Constitutional Amendment declaring Ahmadis non-Muslims and the subsequent 1984 Ordinance XX making it a criminal offense for Ahmadis to call themselves Muslim, use Islamic greetings, or pray in mosques.\n\nAhmadiyya mosque buildings named 'Baitul Jame' in various countries outside Pakistan represent the community's assertion of Islamic identity and practice in contexts where they are free to do so. This diaspora religious practice — maintaining Islamic identity abroad in the face of official designation as non-Muslim at home — is a recurring pattern in the history of religious minorities whose home states have declared their practices illegal.",
        "causes": ["Ahmadiyya Muslim Community's global mosque-building program creating Baitul Jame named mosques", "Local Ahmadiyya community's need for a congregational mosque facility", "Ahmadiyya assertion of Islamic identity through congregational mosque naming despite official non-Muslim designation", "Community diaspora maintaining Islamic practice abroad in response to persecution at home"],
        "effects": ["Local Ahmadiyya congregational prayer space established serving the community's Friday prayer needs", "Islamic identity assertion through 'Jame' (congregational) designation despite mainstream Islamic rejection", "Community resilience demonstrated through mosque establishment in the face of official home-country persecution", "Diaspora Islamic practice maintained through mosque-centered community organization"],
        "relationships": [{"entity": "Ahmadiyya Muslim Community", "relationship": "CONGREGATIONAL_MOSQUE_OF", "note": "Baitul Jame is a congregational mosque of the Ahmadiyya community, using the traditional 'Jami' designation"}, {"entity": "Ordinance XX 1984", "relationship": "DIASPORA_MOSQUE_REPRESENTING_IDENTITY_DESPITE_PERSECUTION_OF", "note": "Pakistan's 1984 Ordinance XX criminalized Ahmadiyya Islamic practice, making diaspora mosques like this an assertion of identity"}, {"entity": "Islamic Congregational Prayer", "relationship": "AHMADIYYA_EXPRESSION_OF_TRADITIONAL_FRIDAY_PRAYER_TRADITION", "note": "The 'Jame' designation claims the traditional Islamic congregational prayer tradition for the Ahmadiyya community"}],
        "historicalSignificance": {"significanceScore": 2, "significanceNarrative": "Baitul Jame — an Ahmadiyya congregational mosque representing a persecuted minority's assertion of Islamic identity in diaspora — is locally significant as a monument to religious minority resilience in the global Ahmadiyya community.", "significanceCategory": "local"},
    }),
    ("baitul-makmur-meulaboh-grand-mosque", {
        "summary": "Baitul Makmur Grand Mosque (Indonesian: Masjid Agung Baitul Makmur) in Meulaboh, Aceh province, Indonesia, is one of the most historically significant mosques of the 2004 Indian Ocean Tsunami's aftermath — the Meulaboh mosque was among the relatively few structures that survived the December 26, 2004 tsunami that devastated Meulaboh, killing approximately 40,000 of the town's 50,000 inhabitants. The mosque's survival became a symbol of spiritual resilience and was widely reported in international media coverage of the disaster.\n\nThe 2004 Indian Ocean Tsunami — triggered by a 9.1-9.3 magnitude undersea earthquake off Sumatra's northwestern coast — is the deadliest tsunami in recorded history, killing approximately 227,898 people across 14 countries. The Indonesian province of Aceh (at the epicenter) suffered the greatest casualties: approximately 130,000 dead or missing in Aceh alone, with coastal towns like Meulaboh virtually destroyed. The mosque's prominent dome structure and reinforced construction allowed it to withstand the catastrophic inundation that flattened surrounding neighborhoods.\n\nMeulaboh and the Baitul Makmur mosque also have significance in Aceh's complex history: Aceh is historically Indonesia's most strictly Islamic province (known as 'Serambi Mecca' — the porch of Mecca), the site of a prolonged separatist conflict (GAM, Free Aceh Movement, 1976-2005 peace agreement), and a province that implemented Islamic sharia law following the post-tsunami autonomy agreement with Jakarta. The mosque's survival in this context carried profound symbolic weight.",
        "causes": ["2004 Indian Ocean Tsunami devastating Meulaboh and killing approximately 40,000 of 50,000 inhabitants", "Mosque's reinforced construction allowing it to survive the catastrophic tsunami that destroyed surrounding structures", "Aceh's deeply Islamic culture making mosque survival spiritually significant for the surviving community", "Meulaboh's position near the tsunami epicenter making its mosque one of the most extreme survival cases"],
        "effects": ["Mosque survival becoming a powerful international symbol of spiritual resilience amid catastrophic destruction", "Post-tsunami reconstruction centering the surviving mosque as community anchor for Meulaboh's rebuilding", "International media coverage of surviving mosque contributing to global documentation of the disaster", "Aceh's post-tsunami Islamic governance (sharia law) giving the mosque renewed significance in the reconstructed province"],
        "relationships": [{"entity": "2004 Indian Ocean Tsunami", "relationship": "SURVIVED_CATASTROPHIC_DESTRUCTION_OF_THE", "note": "The mosque survived the 2004 tsunami that killed approximately 40,000 of Meulaboh's 50,000 inhabitants"}, {"entity": "Aceh", "relationship": "SYMBOLIC_MOSQUE_IN_INDONESIA'S_MOST_STRICTLY_ISLAMIC_PROVINCE", "note": "The mosque's survival holds special significance in Aceh — Indonesia's 'Serambi Mecca' that implemented Islamic sharia law after the tsunami"}, {"entity": "Meulaboh", "relationship": "SURVIVING_SPIRITUAL_ANCHOR_OF_TSUNAMI-DEVASTATED_CITY", "note": "The mosque served as Meulaboh's spiritual anchor during reconstruction after the tsunami destroyed most of the city"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Baitul Makmur Grand Mosque Meulaboh — a survivor of the world's deadliest tsunami (2004) that killed 40,000 of 50,000 inhabitants, becoming a global symbol of spiritual resilience — is historically significant as a monument to the 2004 Indian Ocean Tsunami's catastrophic impact and human spiritual endurance.", "significanceCategory": "world-changing"},
    }),
    ("demolition-of-masjid-al-dirar", {
        "summary": "The Demolition of Masjid al-Dirar (Arabic: مسجد الضرار, the Mosque of Harm/Dissension) is one of the most significant events in early Islamic history, recorded in the Quran (Surah At-Tawbah 9:107-110): during the Prophet Muhammad's return from the Tabuk expedition (630 CE), a group of hypocrites (munafiqun) in Medina had built a second mosque at Dhuba, near the original Quba Mosque, ostensibly for worship but actually (according to the Quran's account) for divisive purposes and to serve as a base for an enemy agent named Abu Amir al-Rahib. The Prophet Muhammad ordered the mosque demolished.\n\nThe Quran's verses about Masjid al-Dirar establish the theological principle that a mosque built for harmful or divisive purposes rather than genuine worship is not a legitimate place of worship and should not be prayed in. This principle has been cited in Islamic jurisprudence for 1,400 years in discussions of mosque legitimacy, the conditions for valid mosque founding, and the distinction between genuine Islamic worship and weaponized religious institutions.\n\nThe event carries exceptional theological weight in Islamic tradition: it is one of the very few historical events explicitly addressed and condemned in the Quran itself, establishing a precedent that even a physical mosque building is not automatically sacred or legitimate if founded for wrong purposes. This theological-jurisprudential principle has been applied in many subsequent contexts, including contemporary debates about mosques used for radical recruitment and similar situations.",
        "causes": ["Hypocrites (munafiqun) building a rival mosque near Quba Mosque for divisive purposes during Muhammad's absence", "Abu Amir al-Rahib's use of the mosque as a base for opposition to the Muslim community", "Prophet Muhammad's Tabuk expedition return creating the context for the mosque's investigation and demolition", "Quran's direct condemnation (9:107-110) establishing the theological basis for the demolition decree"],
        "effects": ["Demolition establishing the Quranic principle that mosques built for harm are not legitimate places of worship", "1,400-year jurisprudential tradition about mosque legitimacy and conditions of valid worship space founded on this event", "Theological precedent for distinguishing genuine religious institutions from weaponized religious buildings", "Contemporary Islamic jurisprudence citing this event in discussions of radicalized or harmful mosque use"],
        "relationships": [{"entity": "Quran", "relationship": "QURANIC_CONDEMNATION_IN_SURAH_AT-TAWBAH_OF", "note": "The Quran directly condemns Masjid al-Dirar in Surah At-Tawbah (9:107-110), one of few historical events explicitly addressed"}, {"entity": "Prophet Muhammad", "relationship": "ORDERED_DEMOLITION_OF_MOSQUE_CONDEMNED_BY_QURAN", "note": "The Prophet ordered the demolition upon returning from the Tabuk expedition in 630 CE"}, {"entity": "Islamic Jurisprudence", "relationship": "FOUNDATIONAL_PRECEDENT_FOR_MOSQUE_LEGITIMACY_DOCTRINE_IN", "note": "The event establishes the principle that mosques built for divisive or harmful purposes are not legitimate — a doctrine applied in Islamic law for 1,400 years"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Demolition of Masjid al-Dirar — one of the few historical events directly addressed and condemned in the Quran, establishing the principle of mosque legitimacy in Islamic jurisprudence — is historically significant as a foundational event in early Islamic theological-legal tradition with 1,400 years of jurisprudential application.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 134 — Class 342 Mosques V: Southeast Asian & Global Mosques")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
