#!/usr/bin/env python3
"""Batch 86 — Class 316 Parties IV (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/316-Class-316"
FILE_PREFIX = "316"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("fianna-fáil", {
        "summary": "Fianna Fáil ('Soldiers of Destiny'), founded in 1926 by Éamon de Valera after his split from Sinn Féin over the Anglo-Irish Treaty, was the dominant party in Irish politics from 1932 to 2011 — governing Ireland for more than 60 of those 79 years and shaping the country's conservative Catholic social policy, protectionist economics, and republican nationalist identity. De Valera's 1937 Constitution — which gave special recognition to the Catholic Church, banned divorce and contraception, and defined women's role as domestic — shaped Irish society until the liberal reforms of the 1990s.\n\nDe Valera founded Fianna Fáil as the 'slightly constitutional' alternative to Sinn Féin — accepting parliamentary politics while maintaining republican principles. The party's first government (1932) reversed the pro-British policies of the Cumann na nGaedheal government by abolishing the oath of allegiance to the British crown, withholding land annuities, and entering an 'Economic War' with Britain. De Valera's 1937 Constitution established Ireland as a sovereign state in fact if not yet in name (formal Republic declared 1948).\n\nFianna Fáil's long dominance — 16 unbroken years (1932-1948), then alternation with Fine Gael — ended catastrophically with the 2007-2010 financial crisis, when a construction bubble inflated by Fianna Fáil's light-touch regulation burst. GDP fell 14%, unemployment trebled, and Ireland required an EU-IMF bailout of €85 billion. The 2011 election reduced Fianna Fáil from 77 to 20 seats — the worst electoral collapse of any governing party in Irish history. Fianna Fáil's recovery and 2020 coalition with its historic rival Fine Gael marked a pragmatic end to the Civil War-era political divide.",
        "causes": ["1926 founding by de Valera after Anglo-Irish Treaty split from Sinn Féin", "1932 first government reversing pro-British policies and entering Economic War with Britain", "1937 Constitution establishing Ireland's conservative Catholic social framework", "2007-2010 construction bubble collapse requiring €85 billion EU-IMF bailout"],
        "effects": ["60+ years of government 1932-2011 shaping conservative Catholic Ireland's social and economic policy", "1937 Constitution's Catholic provisions governing Irish society until 1990s liberal reforms", "2011 electoral collapse from 77 to 20 seats — worst governing party collapse in Irish history", "2020 coalition with Fine Gael ended Civil War political divide lasting 90 years"],
        "relationships": [{"entity": "Éamon de Valera", "relationship": "FOUNDED_BY", "note": "De Valera founded Fianna Fáil in 1926 and shaped Irish policy through 1959 as Taoiseach"}, {"entity": "1937 Irish Constitution", "relationship": "DRAFTED_UNDER", "note": "De Valera's constitution gave Catholic Church special recognition and defined women's domestic role"}, {"entity": "Fine Gael", "relationship": "RIVAL_THEN_COALITION_PARTNER", "note": "Civil War rival governed alternately for 90 years before historic 2020 coalition"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Fianna Fáil's 1937 Constitution — which embedded Catholic social teaching into Irish law and shaped the country's social conservatism for 60 years — and its catastrophic 2011 collapse after causing Ireland's financial crisis define the rise and fall of 20th-century Irish political nationalism.", "significanceCategory": "continental"},
    }),
    ("fine-gael", {
        "summary": "Fine Gael ('Family of the Irish'), founded in 1933 from the merger of Cumann na nGaedheal, the National Centre Party, and the Army Comrades Association (Blueshirts), is the senior partner of the 2020 coalition that ended Ireland's Civil War political divide — traditionally the more pro-European, pro-NATO, and economically liberal of Ireland's two main parties, with roots in the pro-Treaty side of the Irish Civil War (1922-1923). Fine Gael produced Ireland's most internationally significant Taoiseach in Garret FitzGerald (the Anglo-Irish Agreement, 1985) and governed through Ireland's economic recovery.\n\nFine Gael's predecessor Cumann na nGaedheal governed the Irish Free State 1922-1932, accepting the Anglo-Irish Treaty partition as a practical step toward full independence. The merger with the Blueshirts — a semi-fascist movement that sent volunteers to fight for Franco in Spain — created lasting reputational complications. Fine Gael positioned itself as the 'responsible' pro-market, pro-European party versus Fianna Fáil's protectionist nationalism.\n\nGarret FitzGerald's Anglo-Irish Agreement (1985) — signed with Margaret Thatcher — gave the Irish government a formal consultative role in Northern Irish governance for the first time, breaking the post-partition political stalemate. The agreement's recognition of the Irish nationalist community's rights in Northern Ireland created the framework for the Good Friday Agreement (1998) that ended the Troubles. Enda Kenny's 2011-2016 government managed Ireland's EU-IMF bailout recovery, restoring creditworthiness and returning to growth.",
        "causes": ["1933 founding from pro-Treaty Cumann na nGaedheal, Centre Party, and Blueshirt merger", "Civil War pro-Treaty stance defining Fine Gael as establishment constitutional party", "FitzGerald's 1985 Anglo-Irish Agreement giving Irish government role in Northern Ireland governance", "2011 election landslide managing EU-IMF bailout recovery after Fianna Fáil's financial crisis"],
        "effects": ["Anglo-Irish Agreement 1985 created framework for Good Friday Agreement ending Northern Ireland Troubles", "2011-2016 economic recovery from EU-IMF bailout restoring Irish creditworthiness", "2020 coalition with Fianna Fáil and Greens ending 90-year Civil War political divide", "Ireland's pro-EU policy under Fine Gael governments secured continued EU membership and Single Market access"],
        "relationships": [{"entity": "Garret FitzGerald", "relationship": "TRANSFORMATIVE_TAOISEACH", "note": "FitzGerald's 1985 Anglo-Irish Agreement gave Irish government Northern Ireland consultative role"}, {"entity": "Enda Kenny", "relationship": "RECOVERY_TAOISEACH", "note": "Kenny managed 2011-2016 EU-IMF bailout recovery restoring Irish economic credibility"}, {"entity": "Anglo-Irish Agreement", "relationship": "NEGOTIATED", "note": "1985 agreement with Thatcher created framework for Good Friday Agreement ending Northern Ireland conflict"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Fine Gael's Anglo-Irish Agreement (1985) — giving the Irish government a formal role in Northern Ireland governance for the first time — created the political framework that made the 1998 Good Friday Agreement possible, ending the Troubles and achieving the peaceful partition settlement that shaped modern Ireland.", "significanceCategory": "continental"},
    }),
    ("sinn-féin", {
        "summary": "Sinn Féin ('We Ourselves'), founded in 1905 by Arthur Griffith, is the Irish republican political party with the most historically significant transformation in European politics — from terrorist-adjacent party representing the IRA's political wing during The Troubles to the largest party in the Republic of Ireland (2020 election) and the first time a party seeking Irish unification received a Northern Irish plurality (2022 assembly). The 2020 simultaneous plurality in both Irish jurisdictions for the first time in a century, combined with the 2022 Northern Ireland result, represented the most dramatic shift in Irish political history since partition.\n\nGriffith founded Sinn Féin as a non-violent Hungarian-style dual monarchy campaign, but the party's name became associated with the 1916 Easter Rising (which was actually organized by the Irish Republican Brotherhood). The 1918 election gave Sinn Féin 73 of Ireland's 105 Westminster seats — the mandate for independence. After the 1922 Treaty split, Sinn Féin declined into a minor party while de Valera's Fianna Fáil inherited its nationalist constituency.\n\nModern Sinn Féin's association with the Provisional IRA during The Troubles (1969-1998) made it radioactive in mainstream politics — the Irish and British governments refused to negotiate with Gerry Adams until the Good Friday Agreement. The 2005 IRA decommissioning and the Good Friday Agreement implementation transformed Sinn Féin into a normal electoral party. The 2020 Irish election — where housing crisis, healthcare, and cost of living drove record Sinn Féin voting from younger generations who didn't experience The Troubles — marked the most dramatic electoral realignment in modern Irish history.",
        "causes": ["1905 founding by Arthur Griffith as non-violent republican movement", "1918 election giving 73 Westminster seats as mandate for independence", "Provisional IRA association during Troubles relegating party to pariah status", "2020 housing crisis driving younger voters to Sinn Féin in unprecedented election plurality"],
        "effects": ["2020 Irish election plurality first time in century for party seeking unification", "2022 Northern Ireland assembly first-place result first nationalist plurality since partition", "Good Friday Agreement 1998 required Sinn Féin's IRA decommissioning and policy transformation", "Rise in both jurisdictions creating first credible Irish unification political trajectory"],
        "relationships": [{"entity": "Arthur Griffith", "relationship": "FOUNDED_BY", "note": "Griffith founded Sinn Féin in 1905 as non-violent dual monarchy campaign"}, {"entity": "Gerry Adams", "relationship": "TRANSFORMED_UNDER", "note": "Adams transformed Sinn Féin from IRA political wing to mainstream party through Good Friday Agreement"}, {"entity": "Good Friday Agreement", "relationship": "TRANSFORMED_BY", "note": "1998 agreement required IRA decommissioning enabling Sinn Féin electoral mainstreaming"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Sinn Féin's simultaneous plurality in both Irish jurisdictions in 2020-2022 — after decades as a pariah party associated with IRA terrorism — is the most dramatic political rehabilitation and electoral transformation of any Western European party, and the first credible Irish unification political trajectory since partition.", "significanceCategory": "continental"},
    }),
    ("vox", {
        "summary": "Vox, founded in 2013 by Santiago Abascal and former People's Party politicians dissatisfied with the PP's centrist drift, became the third-largest party in the Spanish Congress of Deputies in 2019 elections — ending Spain's 40-year post-Franco democratic consensus that had excluded far-right parties from government. Vox's entry into the Andalusian regional coalition (2019) was the first time a far-right party entered Spanish government since Franco's death, marking the end of the exceptional Spanish democratic taboo on far-right governance.\n\nVox was founded by Santiago Abascal and other PP politicians who believed the party was too willing to compromise with Catalan and Basque nationalism and insufficiently conservative on social issues. The party's breakthrough came in the December 2018 Andalusian elections (the party's first regional representation) and 2019 general elections (52 seats). Vox campaigns against Catalan independence, immigration, Islam, abortion rights, gender equality laws, and the 2007 Historical Memory Law — which recognized Franco-era victims.\n\nVox's most distinctive policy is its opposition to Spain's autonomous community system — arguing for recentralization that would abolish regional self-government as a response to Catalan independence demands. The party's entry into the Castilla y León regional government coalition with the PP (2022) and national coalition talks in 2023 (when PP won elections but lacked majority) demonstrated how far-right parties in Southern Europe can shift governing coalitions. Vox has become the reference point for Spanish-speaking populist right parties in Latin America.",
        "causes": ["2013 founding by Abascal from PP politicians opposing Catalan appeasement and social liberalism", "2018-2019 breakthrough elections ending 40-year Spanish post-Franco far-right exclusion", "Catalan independence crisis 2017-2019 radicalizing Spanish nationalist voter base", "Economic resentment and immigration concerns in rural Spain creating new electoral constituency"],
        "effects": ["2019 entry ended Spain's post-Franco democratic consensus excluding far-right from government", "Vox's anti-autonomous community policy shifted national debate on Spanish territorial organization", "Castilla y León coalition 2022 was first far-right regional government since Franco", "Vox influence extended to Latin America as reference party for Spanish-speaking populist right"],
        "relationships": [{"entity": "Santiago Abascal", "relationship": "FOUNDED_BY", "note": "Abascal founded Vox in 2013 from PP politicians opposing Catalan nationalism and social liberalism"}, {"entity": "People's Party of Spain", "relationship": "SPLIT_FROM", "note": "Vox founders left PP believing it too centrist on Catalan nationalism and social conservatism"}, {"entity": "Catalan independence movement", "relationship": "REACTION_TO", "note": "2017-2019 Catalan independence crisis created the voter radicalization that enabled Vox's breakthrough"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Vox's 2019 breakthrough ended Spain's unique post-Franco democratic taboo on far-right participation in government — the 40-year consensus that had distinguished Spanish democracy from France, Italy, and Austria — marking the normalization of far-right politics across the entire European South.", "significanceCategory": "continental"},
    }),
    ("baath-party", {
        "summary": "The Arab Ba'ath Party (Hizb al-Ba'ath al-'Arabi — 'Arab Resurrection Party'), founded in Damascus in 1947 by Michel Aflaq and Salah al-Din al-Bitar, was the pan-Arab socialist party that governed Iraq (1968-2003) and Syria (1963-present) — its two branches conducting opposite paths from the same ideological origin, with Saddam Hussein's Iraq and Hafez al-Assad's Syria becoming bitter enemies despite sharing Ba'athist governance. The Ba'ath Party's influence on Middle Eastern authoritarianism, from Iraq's genocidal 1988 Anfal campaign against Kurds to Syria's 2011 brutal civil war suppression, defines 20th-century Arab nationalist state violence.\n\nMichel Aflaq, a Greek Orthodox Christian Arab nationalist, and Salah al-Din al-Bitar founded the Arab Ba'ath Party with the slogan 'Unity, Freedom, Socialism' (Wahda, Hurriyya, Ishtirakiyya). The party's core ideology combined pan-Arab nationalism (all Arabs are one nation with a common language, history, and destiny) with secular socialism. Ba'ath came to power in Syria in 1963 and Iraq in 1968 through military coups.\n\nIn Iraq, Saddam Hussein dominated Ba'athist governance from 1969 (as party strongman) and became president in 1979. The 1988 Anfal campaign (using chemical weapons against Kurdish villages, killing 50,000-182,000 civilians) and the 1980-1988 Iran-Iraq War (500,000-1 million dead) were the regime's most catastrophic actions. The 2003 US-led invasion and Paul Bremer's De-Ba'athification — dissolving the Iraqi military and banning Ba'ath Party members from public service — created the power vacuum that produced Al-Qaeda in Iraq and later ISIS.",
        "causes": ["1947 Damascus founding by Aflaq and Bitar combining pan-Arab nationalism with secular socialism", "1963 Syria and 1968 Iraq military coups bringing Ba'ath to power", "Saddam Hussein's 1968-2003 Ba'athist Iraq producing Iran-Iraq War and Anfal Kurdish genocide", "2003 De-Ba'athification dissolving Iraqi military and banning party members from public service"],
        "effects": ["Anfal 1988 chemical weapons campaign against Kurds killed 50,000-182,000 civilians", "Iran-Iraq War 1980-1988 500,000-1 million dead one of 20th century's most destructive conflicts", "De-Ba'athification 2003 created power vacuum producing Al-Qaeda Iraq and ultimately ISIS", "Syrian Ba'ath Party civil war suppression 2011-present killed 500,000 and displaced 14 million"],
        "relationships": [{"entity": "Michel Aflaq", "relationship": "FOUNDED_BY", "note": "Greek Orthodox Christian Arab nationalist founded Ba'ath Party in Damascus 1947"}, {"entity": "Saddam Hussein", "relationship": "MOST_DESTRUCTIVE_LEADER", "note": "Hussein's Ba'athist Iraq conducted Anfal genocide and Iran-Iraq War before 2003 US invasion"}, {"entity": "Paul Bremer", "relationship": "PARTY_DISSOLVED_BY", "note": "Bremer's 2003 De-Ba'athification created power vacuum that produced Al-Qaeda Iraq and ISIS"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Ba'ath Party's two branches — Saddam's Iraq and Assad's Syria — conducted the Arab world's most catastrophic 20th-century state violence; and De-Ba'athification's 2003 vacuum produced ISIS, making the party's dissolution as consequential as its rule.", "significanceCategory": "world-changing"},
    }),
    ("brothers-of-italy", {
        "summary": "Brothers of Italy (Fratelli d'Italia, FdI), founded in 2012 by Giorgia Meloni from the post-fascist National Alliance and its MSI predecessor, became the largest Italian party and formed Italy's most right-wing government since World War II after the September 2022 elections. Meloni became Italy's first female prime minister and the first post-fascist leader of a G7 country — her party still features the tricolor flame of the MSI (founded by Mussolini loyalists in 1946) as its official symbol.\n\nFratelli d'Italia traces its lineage directly from the Italian Social Movement (MSI, 1946-1994) — founded by Mussolini loyalists and using the fascist tricolor flame symbol. The post-war Italian democratic system systematically excluded MSI from government coalitions (the arco costituzionale). Gianfranco Fini's 1994 transformation of MSI into National Alliance, and his embrace of democratic norms, broke the exclusion partially. Meloni's 2012 founding of FdI after the National Alliance merged with Berlusconi's Forza Italia maintained the tricolor flame continuity.\n\nMeloni's 2022 victory came from a rightward shift of Italian voters exhausted by coalition instability — Italy had 69 governments in 76 years since 1946. Her government combined conservative social policy (opposition to LGBTQ+ rights, immigration restriction) with Atlanticist foreign policy (supporting Ukraine against Russia) and a pragmatic relationship with EU institutions — confounding predictions of a Eurosceptic populist governance. The FdI coalition's durability tested whether Italy's political system had finally achieved governmental stability.",
        "causes": ["2012 founding by Meloni from National Alliance after its merger with Forza Italia", "Direct lineage from MSI (1946) post-fascist party using Mussolini-era tricolor flame symbol", "2022 Italian voter exhaustion with coalition instability after 69 governments in 76 years", "Rightward European populist wave enabling post-fascist party to govern G7 country"],
        "effects": ["First Italian female prime minister and first post-fascist G7 country leader after 2022 election", "Italy's most right-wing government since WWII while maintaining Atlanticist Ukraine support", "MSI tricolor flame as official symbol normalizing post-fascist iconography in European mainstream governance", "Meloni government's stability testing whether Italy could achieve durable majority governance"],
        "relationships": [{"entity": "Giorgia Meloni", "relationship": "FOUNDED_BY_AND_LED_BY", "note": "Meloni founded FdI in 2012 and became Italy's first female prime minister after 2022 victory"}, {"entity": "Italian Social Movement", "relationship": "IDEOLOGICAL_DESCENDENT_OF", "note": "FdI retains MSI's tricolor flame symbol; direct lineage from Mussolini loyalists' 1946 party"}, {"entity": "Gianfranco Fini", "relationship": "PREDECESSOR_PARTY_TRANSFORMED_BY", "note": "Fini's National Alliance transformation of MSI in 1994 began normalization of post-fascist Italian politics"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Brothers of Italy's 2022 victory — installing the first post-fascist leader of a G7 country, from a party still using Mussolini-era symbols — represents the furthest normalization of far-right politics in Western European governance since the end of World War II.", "significanceCategory": "world-changing"},
    }),
    ("ciudadanos", {
        "summary": "Ciudadanos (Citizens), founded in Catalonia in 2006 by Albert Rivera and a group of Catalan intellectuals opposing both Catalan independence and the PP-PSOE duopoly, briefly became Spain's third-largest party (2015-2019) promising to break the political deadlock — before collapsing from 57 seats (2019 April) to 10 seats (2019 November) in a single year in one of the fastest electoral collapses in European democratic history. Ciudadanos represents the pattern of centrist 'third way' parties that rise rapidly during political crises then collapse when voters return to established parties.\n\nCiudadanos was founded by Albert Rivera, a lawyer and politician, as a response to Catalan nationalism's dominance of the region's political discourse. The party's Catalan origins — unusual for a Spanish unionist party — gave it credibility as defending civic rather than ethnic Spanish identity. Rivera's charisma, centrist positioning (between PP and PSOE), and anti-corruption platform drove rapid national growth after 2015.\n\nThe party's fatal strategic error came when Rivera refused to support Pedro Sánchez's PSOE government after the April 2019 election (when Ciudadanos was within 4 seats of PSOE), forcing new elections in November 2019. The second 2019 election, called as tactical masterstroke by Sánchez, saw Ciudadanos voters flee to the PP (fearing Sánchez coalition with Podemos). The 82% seat collapse in 7 months remains the most catastrophic electoral implosion of any major Spanish party. Rivera resigned, and Ciudadanos declined to 6 seats by 2023.",
        "causes": ["2006 founding in Catalonia opposing independence movement and PP-PSOE duopoly", "Charismatic Rivera leadership and centrist positioning driving rapid 2015-2019 growth", "April 2019 57-seat result making Ciudadanos potentially decisive coalition partner", "November 2019 refusal to support Sánchez forcing new elections causing 82% seat collapse"],
        "effects": ["Ciudadanos's April-to-November 2019 collapse from 57 to 10 seats as fastest major party implosion in modern European politics", "Rivera's resignation after collapse illustrating costs of miscalculated tactical positioning", "Party's decline to 6 seats by 2023 completing collapse of centrist alternative", "Ciudadanos case study became template for analyzing centrist party vulnerability to tactical errors"],
        "relationships": [{"entity": "Albert Rivera", "relationship": "FOUNDED_BY", "note": "Rivera founded Ciudadanos in 2006; resigned after catastrophic 2019 November election collapse"}, {"entity": "Pedro Sánchez", "relationship": "TACTICAL_DEFEAT_BY", "note": "Sánchez's forced November 2019 election destroyed Ciudadanos by driving voters to PP"}, {"entity": "People's Party of Spain", "relationship": "VOTE_COMPETED_WITH", "note": "PP absorbed fleeing Ciudadanos voters in 2019 November election ending centrist challenge"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "Ciudadanos's 82% seat collapse in a single year — from 57 to 10 seats in 2019 — is the fastest major party implosion in modern European democratic history and the definitive case study of how centrist parties can destroy themselves through single tactical miscalculations.", "significanceCategory": "regional"},
    }),
    ("forza-italia", {
        "summary": "Forza Italia ('Let's Go Italy'), founded in 1994 by media magnate Silvio Berlusconi in 90 days using his Mediaset television empire's organizational infrastructure, transformed Italian politics by becoming the first major party in European democracy created primarily through television advertising and celebrity founder charisma — without a traditional party organization, trade union base, or ideological tradition. Berlusconi governed Italy as prime minister three times (1994-1995, 2001-2006, 2008-2011) — more than any post-war Italian leader — combining unprecedented conflicts of interest between government authority and media ownership.\n\nBerlusconi created Forza Italia after the 1993-1994 Tangentopoli ('Bribesville') corruption scandal destroyed Italy's traditional party system (Christian Democracy, Socialist Party, Communist Party). His three commercial television channels (Canale 5, Italia 1, Rete 4) had created a mass audience culture that he converted directly into a voter base through saturation advertising. The party was named after a football chant, and club memberships were organized through Mediaset corporate structures.\n\nBerlusconi's three governments were characterized by attempts to change laws that applied to his own legal cases (including trials for bribery, tax fraud, and underage prostitution), and the most extreme conflict of interest in any European democracy — a prime minister who controlled 90% of Italian TV broadcasting. His 2011 resignation during the European debt crisis, while crowds celebrated in the streets of Rome, marked the end of his governing career. Berlusconi's death in June 2023 was followed by Forza Italia's continuation under Antonio Tajani as a moderate conservative coalition partner.",
        "causes": ["1994 founding using Mediaset television infrastructure to create party without traditional organization", "Tangentopoli 1993-1994 corruption scandal destroying traditional Italian parties creating political vacuum", "Television advertising saturation converting Mediaset audience into Forza Italia voter base", "Three coalition governments 1994-2011 governing Italy for over 9 years"],
        "effects": ["First major European party created primarily through television and celebrity founder — model for media-driven politics", "Unprecedented media-government conflict of interest with PM controlling 90% of Italian TV broadcasting", "Berlusconi era produced multiple laws benefiting defendant in his own criminal trials", "Forza Italia's TV-driven creation model influenced Trump, Macron, and 21st-century personality-party politics"],
        "relationships": [{"entity": "Silvio Berlusconi", "relationship": "FOUNDED_BY", "note": "Berlusconi created Forza Italia in 90 days using Mediaset television infrastructure; governed 3 times"}, {"entity": "Mediaset", "relationship": "ORGANIZATIONAL_INFRASTRUCTURE_FROM", "note": "Berlusconi's three commercial TV channels provided organizational base and voter mobilization"}, {"entity": "Tangentopoli", "relationship": "EMERGED_FROM", "note": "1993-1994 bribesville corruption scandal destroyed traditional parties creating vacuum Berlusconi filled"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Forza Italia was the first major European party created through television advertising and celebrity founder charisma — pioneering the media-party model that influenced Trump, Macron, and every subsequent personality-driven political movement, while demonstrating the corruption risks of media-government conflict of interest.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 86 — Class 316 Parties IV")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
