#!/usr/bin/env python3
"""Batch 139 — Class 316 Parties IX: Arab & Middle Eastern Political Parties (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/316-Class-316"
FILE_PREFIX = "316"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("arab-socialist-union", {
        "summary": "The Arab Socialist Union (ASU, الاتحاد الاشتراكي العربي, Al-Ittihad al-Ishtiraki al-Arabi), founded by Egyptian President Gamal Abdel Nasser in 1962 as Egypt's sole ruling party — was the mass political organization of Nasserist Egypt's socialist state, designed to mobilize popular support for Nasser's Arab socialist revolution, express his pan-Arab nationalist ideology, and organize political participation within Egypt's one-party authoritarian system, serving until Anwar Sadat's subsequent restructuring.\n\nNasser's ASU was part of his broader vision of 'Arab socialism' — a non-communist but strongly state-interventionist economic system combined with pan-Arab nationalism and anti-imperialism. The ASU replaced earlier political organizations (the Liberation Rally, the National Union) that had proved inadequate as mass mobilization vehicles, and was modeled partly on the FLN in Algeria and the Ba'ath Party in Syria and Iraq, though Nasser's Egypt never successfully merged with either Ba'athist country despite the brief United Arab Republic experience (1958-1961).\n\nNasser's 1967 defeat in the Six-Day War severely damaged his political authority despite his nominal survival in power until his death in 1970. After Nasser's death, Sadat gradually dismantled the ASU structure: in 1976, he reorganized the ASU into three 'platforms' (left, center, right), then in 1978 dissolved the ASU and created the National Democratic Party, initiating Egypt's controlled multi-party system that persisted until the 2011 Egyptian Revolution.",
        "causes": ["Nasser's Arab socialist ideology requiring a mass political organization to mobilize and direct popular participation", "Egypt's post-1952 revolutionary state requiring institutional political organization beyond military rule", "Pan-Arab nationalist project needing organizational infrastructure for Egypt's leadership role in the Arab world", "Socialist economic transformation of Egypt requiring party apparatus to implement nationalization and land reform policies"],
        "effects": ["ASU serving as Egypt's mass political mobilization vehicle for Nasser's Arab socialist revolution (1962-1971)", "1967 Six-Day War's catastrophic defeat undermining Nasser's authority and the ASU's legitimacy", "Sadat's dismantling of the ASU leading to Egypt's controlled multi-party system (National Democratic Party era)", "Nasserism as political legacy continuing to influence pan-Arab nationalist politics beyond the ASU's existence"],
        "relationships": [{"entity": "Gamal Abdel Nasser", "relationship": "MASS_POLITICAL_ORGANIZATION_OF_EGYPT_CREATED_BY", "note": "Nasser created the ASU in 1962 as the institutional expression of his Arab socialist and pan-Arab nationalist vision"}, {"entity": "Arab Socialism", "relationship": "INSTITUTIONAL_VEHICLE_FOR_NASSER'S_IDEOLOGY_OF", "note": "The ASU expressed Nasser's Arab socialist ideology — state interventionism, pan-Arab nationalism, and anti-imperialism"}, {"entity": "Anwar Sadat", "relationship": "SUCCESSOR_WHO_DISMANTLED_AND_REPLACED_WITH_MULTI-PARTY_SYSTEM", "note": "Sadat gradually dismantled the ASU, leading to Egypt's National Democratic Party controlled multi-party system"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Arab Socialist Union — Nasser's mass party for Egypt's Arab socialist revolution, destroyed by the 1967 defeat — is historically significant as the institutional expression of Nasserism, one of the 20th century's most influential Arab political ideologies.", "significanceCategory": "world-changing"},
    }),
    ("armenian-democratic-liberal-party", {
        "summary": "The Armenian Democratic Liberal Party (ADL, Armenian: Ռամկավար Ազատական Կուսակցություն, Ramkavar Azatakan Kusaktsutyun), founded in 1921 through the merger of the Armenian Constitutional Democratic Party (Sahmanadrutyun) and the Armenian Democratic Liberal Party — is one of the three traditional Armenian diaspora political parties (alongside the Armenian Revolutionary Federation/Dashnaks and the Hunchakian Party), representing the liberal democratic strand of Armenian diaspora politics across North America, Europe, and the Middle East.\n\nThe three traditional Armenian political parties were founded in the late 19th and early 20th centuries to advocate for Armenian rights in the Ottoman Empire and to mobilize the Armenian diaspora communities created by the Armenian Genocide (1915-1923). The ARF (Dashnak) represents a more nationalist and sometimes socialist position; the Hunchakian Party originated as a socialist organization; and the Ramkavar (ADL) has historically taken a more liberal democratic and diaspora-focused position.\n\nThe ADL's political positions have been shaped by its diaspora orientation: unlike the ARF, which historically had ambivalent positions on the Soviet Armenian Republic, the ADL was more willing to cooperate with Soviet Armenia (and the Soviet-era Armenian SSR government) as a pragmatic means of preserving Armenian culture and connections. After Armenian independence (1991), the ADL has been active in Armenia's political sphere though remaining primarily a diaspora institution. The ADL publishes the Armenian Mirror-Spectator (Boston), one of the oldest Armenian-American newspapers.",
        "causes": ["1921 merger of Armenian Constitutional Democratic Party and Armenian Democratic Liberal Party creating the ADL", "Armenian Genocide creating diaspora communities requiring political representation and advocacy", "Three-way ideological split in Armenian diaspora politics requiring distinct liberal democratic institutional expression", "Diaspora Armenian community's need for cultural institutions including Armenian-language press"],
        "effects": ["ADL as one of three pillars of Armenian diaspora political organization for over a century", "Armenian Mirror-Spectator newspaper as one of the longest-running Armenian-American publications", "ADL's pragmatic stance toward Soviet Armenia maintaining cultural connections between diaspora and Soviet-era Armenia", "Post-independence Armenia's political sphere influenced by diaspora party institutions including the ADL"],
        "relationships": [{"entity": "Armenian Diaspora", "relationship": "LIBERAL_DEMOCRATIC_PILLAR_OF_POLITICAL_ORGANIZATION_IN", "note": "ADL is one of the three traditional parties organizing Armenian diaspora political life for over a century"}, {"entity": "Armenian Genocide", "relationship": "ADVOCACY_INSTITUTION_FOR_DIASPORA_COMMUNITIES_CREATED_BY", "note": "The party was shaped by and advocates for Armenian Genocide recognition alongside the other diaspora parties"}, {"entity": "Armenian Revolutionary Federation", "relationship": "LIBERAL_DEMOCRATIC_ALTERNATIVE_TO_NATIONALIST", "note": "The ADL represents the liberal democratic strand distinct from the ARF (Dashnak) nationalist position in Armenian diaspora politics"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Armenian Democratic Liberal Party — one of three traditional Armenian diaspora parties sustaining political and cultural life for Armenian Genocide survivors and their descendants for over a century — is historically significant as an institution of Armenian diaspora resilience and political organization.", "significanceCategory": "continental"},
    }),
    ("article-1-democratic-and-progressive-movement", {
        "summary": "Article 1 - Democratic and Progressive Movement (French: Article 1 - Mouvement démocrate et progressiste, also known as 'L'Article 1') was a French social democratic political party founded in 2017 when former Prime Minister Manuel Valls left the Socialist Party to support Emmanuel Macron's En Marche! movement — a split that symbolized the Socialist Party's catastrophic collapse as Macron's centrist movement attracted numerous center-left figures away from the traditional left.\n\nManuel Valls had been Prime Minister under Socialist President François Hollande from 2014-2016 before resigning to run unsuccessfully in the 2017 presidential primary. His decision to subsequently support Macron's centrist La République En Marche! rather than support the Socialist Party's candidate Benoît Hamon was part of the broader defection of centrist Social Democrats to Macron that effectively destroyed the French Socialist Party's national viability in the 2017 elections (Hamon received only 6.36% in the first round).\n\nArticle 1 represented an attempt to create a vehicle for Valls and other center-left Social Democrats who supported Macron while maintaining a distinct political identity — in practice, the organization merged into or closely aligned with La République En Marche! The broader significance is as documentation of the French left's 2017 collapse and the centrist reconfiguration of French politics under Macron that left both the traditional left and the traditional right fragmented.",
        "causes": ["Manuel Valls's departure from Socialist Party to support Macron after losing 2017 presidential primary", "French Socialist Party's ideological fragmentation between center-left (Valls) and more left (Hamon) factions", "Emmanuel Macron's centrist La République En Marche! attracting center-left politicians away from the Socialist Party", "2017 French elections seeing the Socialist Party collapse from governing party to 6% first-round support"],
        "effects": ["Article 1 providing a vehicle for Valls and center-left Social Democrats to support Macron while maintaining identity", "French Socialist Party's catastrophic 2017 collapse partly caused by centrist defections to Macron's movement", "French center-left political space fragmented between Macron's centrist movement and Mélenchon's France Insoumise", "French political landscape reconfigured around Macron's En Marche!/LREM replacing traditional left-right axis"],
        "relationships": [{"entity": "Manuel Valls", "relationship": "FOUNDED_BY_FORMER_PM_AS_VEHICLE_FOR_CENTRIST_SOCIAL_DEMOCRATS", "note": "Valls founded Article 1 after leaving the Socialist Party to support Macron's centrist movement"}, {"entity": "French Socialist Party", "relationship": "FOUNDED_AFTER_BREAKING_FROM_REPRESENTING_CENTRIST_DEFECTION_FROM", "note": "Article 1's founding represented the centrist Social Democratic defection that accelerated the Socialist Party's 2017 collapse"}, {"entity": "Emmanuel Macron", "relationship": "ALIGNED_WITH_LA_REPUBLIQUE_EN_MARCHE_OF", "note": "Article 1 effectively aligned with and supported Macron's La République En Marche! centrist movement"}],
        "historicalSignificance": {"significanceScore": 4, "significanceNarrative": "Article 1 — Manuel Valls's vehicle for center-left Social Democrats supporting Macron, representing the centrist defection that collapsed the French Socialist Party — is historically significant as a documentation of the 2017 French left's transformation and Macron's centrist political realignment.", "significanceCategory": "continental"},
    }),
    ("assyrian-democratic-organization", {
        "summary": "The Assyrian Democratic Organization (ADO, Syriac: ܡܛܟܣܬܐ ܕܝܡܩܪܛܝܬܐ ܐܬܘܪܝܬܐ, Mțaksyayto Demokratayto Atwroyto), founded in Syria in 1957 — is one of the oldest Assyrian political parties, representing the Assyrian Christian minority of Syria (and the broader Assyrian diaspora) in advocating for Assyrian cultural, linguistic, and political rights within the framework of a democratic, secular state. It has maintained its identity as an Assyrian national organization through Syria's various political convulsions including the Ba'ath Party's authoritarian rule and the Syrian Civil War.\n\nThe Assyrian Christians of Syria — primarily in the northeast (Jazira region, now including much of the Autonomous Administration of North and East Syria/Rojava) — are remnants of the ancient Syriac-speaking Christian civilization that predates Islam in the Middle East. The Assyrian (also called Syriac or Aramean, with complex internal naming disputes) Christian communities speak modern Neo-Aramaic dialects descended from the language of Jesus of Nazareth and the ancient Near Eastern Christian tradition.\n\nThe ADO's position during the Syrian Civil War (2011-present) has been particularly complex: with the rise of the Autonomous Administration of North and East Syria (AANES/Rojava), many Assyrian Christians in the northeast came under the Kurdish-led administration, and Assyrian institutions including the ADO had to navigate relationships with the AANES, the Syrian government, and various external powers. The ADO has generally supported the Rojava democratic experiment while maintaining Assyrian specific autonomy demands.",
        "causes": ["1957 founding as political representation vehicle for Assyrian Christians in Syria demanding cultural and linguistic rights", "Assyrian Christian minority's marginalization in Arab nationalist Ba'ath Syria requiring organized political advocacy", "Assyrian language and cultural preservation requiring institutional political support in an Arabizing state", "Syriac-speaking Christian community's need for political organization distinct from Arab and Kurdish parties"],
        "effects": ["ADO providing sustained political representation for Assyrian Christians in Syria for 60+ years", "Syrian Civil War's Rojava experiment creating new contexts for Assyrian political engagement", "ADO navigating between Syrian government, Rojava/AANES, and diaspora Assyrian communities", "Assyrian political voice in post-civil war Syria's future preserved through ADO's organizational continuity"],
        "relationships": [{"entity": "Assyrian Christians of Syria", "relationship": "POLITICAL_REPRESENTATIVE_BODY_OF_SINCE_1957", "note": "ADO has been the primary political organization representing Syria's Assyrian Christian minority since its 1957 founding"}, {"entity": "Syrian Civil War", "relationship": "NAVIGATED_COMPLEX_ALIGNMENTS_DURING", "note": "The ADO navigated relationships with the Syrian government, Rojava/AANES, and diaspora during the Syrian Civil War"}, {"entity": "Autonomous Administration of North and East Syria", "relationship": "ASSYRIAN_POLITICAL_PARTICIPANT_IN_DEMOCRATIC_EXPERIMENT_OF", "note": "ADO has participated in and engaged with the AANES (Rojava) democratic administration in northern Syria"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Assyrian Democratic Organization — representing the ancient Syriac-speaking Christian community of Syria for 65+ years through Ba'ath dictatorship and civil war — is historically significant as a monument to Assyrian Christian political resilience and the survival of one of the Middle East's most ancient Christian communities.", "significanceCategory": "continental"},
    }),
    ("all-india-muslim-league-founded-at-dhaka", {
        "summary": "The All-India Muslim League, founded at Dhaka (then Dacca, in British India's Bengal province) on December 30, 1906 — was the political organization that ultimately achieved the creation of Pakistan in 1947, representing the political consciousness of South Asia's Muslim minority within the British Indian Empire and eventually adopting Mohammad Ali Jinnah's 'Two-Nation Theory' that Muslims and Hindus were separate nations requiring separate states.\n\nThe 1906 Dhaka founding occurred when Muslim leaders gathered for the All-India Muhammadan Educational Conference at the invitation of the Nawab of Dhaka, Khwaja Salimullah, who was the primary organizer. The founding context was the 1905 Partition of Bengal (later reversed in 1911) and Muslim leaders' concerns about Hindu-dominated Indian National Congress's political power in a future self-governing India. The league initially sought constitutional protections for Muslims within a unified India rather than separation.\n\nThe transformation from a Muslim political organization seeking constitutional protections to a independence movement demanding Pakistan is one of the most dramatic political evolutions in modern history: under Muhammad Ali Jinnah's leadership (from 1913, increasingly dominant after 1934), the League shifted from supporting Congress's Indian nationalism to the 1940 Lahore Resolution demanding a separate Muslim state. The 1947 Partition of India — creating Pakistan and resulting in one of history's largest forced migrations (approximately 10-20 million people displaced, and 200,000-2,000,000 killed in communal violence) — was the League's ultimate legacy.",
        "causes": ["British India's Muslim minority leaders' concerns about underrepresentation in a Hindu-majority future self-governing India", "1905 Partition of Bengal creating political crisis that catalyzed Muslim political organization", "Nawab of Dhaka Khwaja Salimullah's organizing efforts bringing Muslim leaders to Dhaka in December 1906", "Muslim leaders' desire for separate electoral rolls and constitutional protections within British India"],
        "effects": ["All-India Muslim League evolving from constitutional reform advocate to Pakistani independence movement under Jinnah", "1940 Lahore Resolution demanding a separate Muslim state as League's official position", "1947 Partition of India creating Pakistan and displacing 10-20 million people with massive communal violence", "Two-Nation Theory becoming the foundational ideology of Pakistani nationalism"],
        "relationships": [{"entity": "Mohammad Ali Jinnah", "relationship": "DOMINANT_LEADER_AFTER_1934_GUIDING_PARTY_TO_PAKISTAN_CREATION", "note": "Jinnah's leadership transformed the League from constitutional Muslim advocacy to the Two-Nation Theory and Pakistani independence"}, {"entity": "Partition of India 1947", "relationship": "FOUNDING_ORGANIZATION_THAT_ACHIEVED_THROUGH_LEAGUE", "note": "The All-India Muslim League's ultimate achievement was the 1947 Partition creating Pakistan"}, {"entity": "Dhaka", "relationship": "FOUNDING_CITY_AND_HISTORICAL_SEAT_OF_MUSLIM_LEAGUE'S_CREATION", "note": "The League was founded at Dhaka in 1906, making it the birthplace of the political movement that created Pakistan and eventually Bangladesh"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The All-India Muslim League founded at Dhaka — which evolved from Muslim constitutional advocacy to achieving the creation of Pakistan in 1947, one of the 20th century's most significant and violent political transformations — is one of modern history's most consequential political organizations.", "significanceCategory": "world-changing"},
    }),
    ("arab-socialist-baath-independent", {
        "summary": "The Arab Socialist Ba'ath Party (Arabic: حزب البعث العربي الاشتراكي, Hizb al-Ba'th al-'Arabi al-Ishtiraki, meaning 'Arab Renaissance/Resurrection Socialist Party'), founded in Damascus in 1947 by Michel Aflaq (a Syrian Christian intellectual) and Salah al-Din al-Bitar — was one of the 20th century's most influential and destructive political movements, organizing pan-Arab nationalist regimes in Syria and Iraq that ruled for decades through authoritarian means, launching major wars, and committing mass atrocities against their own populations.\n\nBa'athism's founding ideology combined three elements: Arab nationalism (al-'uruba), socialism (al-ishtirākiyya), and pan-Arab unity (al-wahda) under the motto 'Unity, Freedom, Socialism' (Wahda, Hurriyya, Ishtirākiyya). Aflaq believed that Arabs constituted a single nation that had been fragmented by European imperialism, and that a renaissance (ba'th) of Arab civilization would reunite them. The ideology was explicitly secular — positioning Arab identity over religious identity in contrast to Islamist movements.\n\nThe Ba'ath Party split in 1966 into Syrian and Iraqi factions that became bitter rivals, undermining the pan-Arab unity project the party was founded to achieve. The Iraqi Ba'ath Party under Saddam Hussein (1968-2003) committed the Anfal genocide against Iraqi Kurds (1986-1989, approximately 50,000-182,000 killed), used chemical weapons at Halabja (1988), invaded Kuwait (1990), and was ultimately overthrown by the 2003 US invasion. The Syrian Ba'ath under the Assad family has ruled since 1970 and launched a brutal civil war (2011-present) killing approximately 500,000.",
        "causes": ["Michel Aflaq's pan-Arab nationalist ideology requiring a political organization to implement Arab unity and renaissance", "Post-WWII Arab world's fragmentation by European colonialism creating appeal for pan-Arab unity movements", "1948 Arab-Israeli War's humiliation galvanizing Arab nationalist sentiment for radical pan-Arab solutions", "Syrian intellectual milieu of Damascus in the 1940s producing secular nationalist alternatives to both communism and Islamism"],
        "effects": ["Ba'ath Party seizing power in both Syria (1963, consolidated 1970) and Iraq (1963, definitively 1968) creating rival Ba'athist dictatorships", "Iraqi Ba'ath under Saddam committing Anfal genocide, chemical weapons use at Halabja, and Kuwait invasion", "Syrian Ba'ath under Assad dynasty ruling from 1970 to present, launching brutal civil war after 2011", "Arab nationalist Ba'athism as ideology influencing regional politics for 70+ years despite catastrophic failures"],
        "relationships": [{"entity": "Michel Aflaq", "relationship": "INTELLECTUAL_FOUNDER_AND_IDEOLOGICAL_ARCHITECT_OF", "note": "Aflaq founded the Ba'ath Party in Damascus in 1947, providing its ideological framework of pan-Arab nationalism, socialism, and unity"}, {"entity": "Saddam Hussein", "relationship": "IRAQI_BRANCH_BROUGHT_TO_POWER_AND_LED_BY", "note": "Saddam Hussein led the Iraqi Ba'ath from 1968, committing the Anfal genocide and multiple wars before the 2003 US overthrow"}, {"entity": "Assad Dynasty", "relationship": "SYRIAN_BRANCH_PROVIDING_IDEOLOGICAL_FRAMEWORK_FOR", "note": "Syria's Ba'ath Party has been controlled by the Assad family since Hafez al-Assad's 1970 seizure of power"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Arab Socialist Ba'ath Party — founding ideology of the dictatorships that committed the Anfal genocide, the Halabja massacre, the Kuwait invasion, and the Syrian Civil War — is historically significant as one of the 20th century's most influential and destructive political movements.", "significanceCategory": "world-changing"},
    }),
    ("asean-peoples-assembly", {
        "summary": "The ASEAN Peoples' Assembly (APA) was a civil society-initiated initiative launched in 2000 in Batam, Indonesia — designed to create a people-centered counterpart to the official Association of Southeast Asian Nations (ASEAN) governmental process, bringing together civil society organizations, academics, and non-governmental organizations from across Southeast Asia to articulate a vision for regional integration that centered human rights, labor rights, and democratic governance alongside the economic integration focus of official ASEAN.\n\nASEAN, founded in 1967 by Thailand, Malaysia, the Philippines, Singapore, and Indonesia — primarily as an anti-communist geopolitical alignment that subsequently evolved into a broader regional economic and political cooperation body — has been consistently criticized for its prioritization of 'non-interference' in member states' internal affairs and economic cooperation over human rights and democratic governance. ASEAN's consensus-based decision-making and non-interference norms allowed members like Burma/Myanmar, Cambodia, and Vietnam to maintain authoritarian governments without ASEAN criticism.\n\nThe APA process brought together NGOs, academics, and civil society voices to develop the concept of an 'ASEAN Community' that would be people-centered rather than state-centered — a vision that eventually influenced official ASEAN processes, as the 2007 ASEAN Charter and the subsequent ASEAN Community vision (implemented from 2015) incorporated some people-centered language, though critics argue the official process fell far short of the APA's vision for genuine democratic accountability.",
        "causes": ["ASEAN's state-centered non-interference norms requiring civil society pressure for human rights and democratic accountability", "2000 Batam initiative bringing together Southeast Asian civil society organizations to articulate people-centered regional integration", "Academic and NGO community's desire to influence ASEAN toward greater democratic and human rights commitments", "Broader global civil society movement parallel-tracking official international organizations"],
        "effects": ["APA articulating people-centered vision of ASEAN community that influenced subsequent official ASEAN Community process", "2007 ASEAN Charter incorporating some people-centered language in response to civil society pressure", "ASEAN Community (implemented 2015) including people-centered pillar partly influenced by APA vision", "Southeast Asian civil society networks strengthened through APA collaboration and cross-border networking"],
        "relationships": [{"entity": "ASEAN", "relationship": "CIVIL_SOCIETY_COUNTERPART_TO_OFFICIAL_PEOPLE-CENTERED_ALTERNATIVE_TO", "note": "APA was designed as a people-centered civil society alternative to ASEAN's state-centered intergovernmental process"}, {"entity": "ASEAN Community", "relationship": "VISION_PARTLY_INFLUENCING_2015_IMPLEMENTATION_OF", "note": "APA's people-centered vision influenced the official ASEAN Community process including its people-centered pillar"}, {"entity": "Southeast Asian Civil Society", "relationship": "REGIONAL_NETWORKING_PLATFORM_FOR", "note": "APA served as a platform for regional networking and collaboration among Southeast Asian civil society organizations"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "The ASEAN Peoples' Assembly — civil society counterpart to official ASEAN processes, advocating people-centered regional integration — is historically significant as an example of civil society pressure influencing intergovernmental institutions toward democratic and human rights commitments.", "significanceCategory": "continental"},
    }),
    ("arakan-national-party", {
        "summary": "The Arakan National Party (ANP), formed in 2014 through the merger of two Rakhine Buddhist nationalist parties — the Rakhine Nationalities Development Party (RNDP) and the Arakan League for Democracy (ALD) — is the primary political party representing the ethnic Rakhine (Arakan) Buddhist majority of Rakhine State (historically known as Arakan) in western Myanmar, and has been centrally involved in the political context surrounding the Rohingya genocide.\n\nRakhine State is one of Myanmar's most ethnically complex and politically volatile regions: the Buddhist Rakhine people (also called Arakan) are an ethnic minority in Myanmar overall but the majority in Rakhine State, and they have historically experienced both marginalization by the dominant Burman Buddhist majority and deep tensions with the Muslim Rohingya minority in the same state — the Rohingya being one of the world's most persecuted minority groups. The Arakan National Party represents Rakhine Buddhist interests and has been associated with positions that critics characterize as contributing to anti-Rohingya discrimination.\n\nThe Rohingya genocide (2016-2017), in which Myanmar military operations drove approximately 700,000 Rohingya to flee to Bangladesh amid killings, rape, and burning of villages — documented by the UN as bearing the hallmarks of genocide — occurred in the political context of Rakhine Buddhist nationalism. The ANP's political positioning, while formally a Myanmar political party, operates in a context where Rakhine Buddhist nationalism has been implicated in the dehumanization of the Rohingya that preceded the military's genocidal operations.",
        "causes": ["2014 merger of Rakhine Buddhist parties to consolidate Rakhine ethnic representation in Myanmar's political system", "Rakhine State's ethnic complexity requiring a unified Rakhine Buddhist political voice in Myanmar's national politics", "Myanmar's post-2010 partial democratization creating space for ethnic nationalist parties to compete electorally", "Rakhine Buddhist community's marginalization within Myanmar requiring organized political advocacy"],
        "effects": ["ANP as primary political representative of Rakhine Buddhist interests in Myanmar parliament", "Rakhine political context surrounding the 2016-2017 Rohingya genocide operations by Myanmar military", "Rohingya crisis in Rakhine State displacing 700,000+ people in what the UN characterized as genocide", "Myanmar's ethnic politics further complicated by Rakhine-center conflicts alongside Rohingya crisis"],
        "relationships": [{"entity": "Rakhine State", "relationship": "PRIMARY_POLITICAL_REPRESENTATIVE_OF_RAKHINE_BUDDHIST_MAJORITY_IN", "note": "ANP is the main party representing ethnic Rakhine Buddhist interests in Rakhine State and Myanmar's national parliament"}, {"entity": "Rohingya Genocide", "relationship": "OPERATING_IN_THE_POLITICAL_CONTEXT_OF_RAKHINE_BUDDHISM_SURROUNDING", "note": "The ANP operates in the political context where Rakhine Buddhist nationalism has been implicated in the dehumanization preceding the Rohingya genocide"}, {"entity": "Myanmar Ethnic Politics", "relationship": "RAKHINE_BUDDHIST_NATIONALIST_COMPONENT_OF_COMPLEX", "note": "ANP represents the Rakhine ethnic dimension of Myanmar's extraordinarily complex multi-ethnic political landscape"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Arakan National Party — primary political representative of Rakhine Buddhists in the context of the Rohingya genocide — is historically significant as a central actor in one of the 21st century's most serious human rights catastrophes.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 139 — Class 316 Parties IX: Arab & Middle Eastern Political Parties")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
