#!/usr/bin/env python3
"""Batch 100 — Class 341 Cathedrals IV (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/341-Class-341"
FILE_PREFIX = "341"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("cathedral-of-the-immaculate-conception", {
        "summary": "The Cathedral of the Immaculate Conception in Fort Wayne, Indiana, USA (completed 1859, current cathedral since 1857), is the mother church of the Diocese of Fort Wayne-South Bend — one of the oldest Catholic dioceses in the American Midwest, covering Notre Dame University's home territory. Built in the Gothic Revival style by architect Patrick Charles Keely (who designed over 700 Catholic churches in America), the cathedral represents the frontier Catholicism of mid-19th-century Midwestern settlement, serving the German and Irish immigrant communities that built Fort Wayne's industrial base.\n\nKeely's cathedral design (1857-1859) used the Gothic Revival aesthetic then fashionable for Catholic American churches — pointed arches, stone facade, and stained glass windows — scaled to a frontier city that had only 2,000 residents at its founding. Fort Wayne's Catholicism was shaped by the University of Notre Dame (30 miles south) and the Congregation of Holy Cross — the priests who founded Notre Dame in 1842 also served early Fort Wayne's Catholic community.\n\nThe Cathedral Basilica designation (granted by Pope Francis in 2019) elevated it to minor basilica status — one of approximately 85 minor basilicas in the United States. The current cathedral serves as the spiritual center for Indiana's second-largest Catholic diocese, encompassing 14 counties across northern Indiana. Its connection to Notre Dame University — America's most famous Catholic university — makes it theologically and institutionally significant within American Catholicism.",
        "causes": ["1857 cathedral founding serving German and Irish immigrant frontier Catholic communities in Fort Wayne", "Patrick Charles Keely Gothic Revival design as part of 700+ Keely Catholic churches in America", "Notre Dame University and Holy Cross congregation shaping Fort Wayne Catholic institutional identity", "2019 Pope Francis minor basilica designation elevating cathedral status"],
        "effects": ["Mother church of Fort Wayne-South Bend diocese covering Notre Dame University territory", "Gothic Revival model of frontier Catholicism for mid-19th-century Midwest immigrant communities", "2019 minor basilica designation as one of 85 US basilicas", "Connection to Notre Dame University as institutional link between frontier and elite American Catholicism"],
        "relationships": [{"entity": "Patrick Charles Keely", "relationship": "DESIGNED_BY", "note": "Keely designed 700+ American Catholic churches including Fort Wayne cathedral in Gothic Revival"}, {"entity": "University of Notre Dame", "relationship": "DIOCESE_INCLUDES_TERRITORY_OF", "note": "Fort Wayne-South Bend diocese covers Notre Dame University's northern Indiana territory"}, {"entity": "Pope Francis", "relationship": "MINOR_BASILICA_DESIGNATED_BY", "note": "Pope Francis granted minor basilica status in 2019 to the cathedral"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "The Cathedral of the Immaculate Conception in Fort Wayne — Gothic Revival frontier Catholicism serving German and Irish immigrants at America's Midwest frontier, architecturally typical of Keely's 700+ American Catholic churches — represents the institutional form that spread Catholicism across the 19th-century American interior.", "significanceCategory": "local"},
    }),
    ("basilica-of-notre-dame-de-fourvière", {
        "summary": "The Basilica of Notre-Dame de Fourvière in Lyon, France, built 1872-1896 on Fourvière Hill (the site of the original Roman Lugdunum, capital of Gaul) by architect Pierre Bossan in a Byzantine-Romanesque style following a vow made by the Archbishop of Lyon during the Franco-Prussian War (1870-1871), is Lyon's most recognizable landmark — visible from throughout the city and illuminated at night — and one of France's most visited pilgrimage sites (2 million annual visitors). Lyon's special Marian devotion (the city is considered 'Mary's city') predates the basilica by centuries.\n\nThe Fourvière Hill has been Lyon's most sacred site since early Christianity: Saint Pothinus, the first Bishop of Lyon, was martyred here in 177 CE; the hill's 'Our Lady of Fourvière' small chapel (12th century) was a major medieval pilgrimage site. During the 1643 plague, Lyon's citizens vowed to make a procession to Fourvière on September 8 (Nativity of Mary) — a tradition maintained since 1643. The 1870-1871 Franco-Prussian War vow by Archbishop Ginoulhiac to build a great basilica if Lyon was spared Prussian occupation was fulfilled when Prussians bypassed the city.\n\nBossan's eclectic design — combining Byzantine mosaics, Romanesque arches, and Gothic spires — was controversial: Gustave Eiffel (who built the basilica's iron framework) reportedly called it a 'strange elephant upside down.' The basilica's interior mosaic cycle depicts major events in French Catholic history. The annual 'Fête des Lumières' (Festival of Lights, December 8) originated as candles lit in Fourvière windows to honor Mary — it is now Europe's largest light festival attracting 4 million visitors annually.",
        "causes": ["177 CE Saint Pothinus martyrdom on Fourvière Hill establishing Lyon's earliest Christian sacred site", "1643 plague vow establishing annual September 8 Marian procession tradition maintained 380+ years", "1870-1871 Franco-Prussian War archbishop's vow building basilica if Lyon spared Prussian occupation", "Annual Fête des Lumières December 8 originating as Fourvière window candle tradition"],
        "effects": ["2 million annual pilgrims making Notre-Dame de Fourvière one of France's most visited sites", "Lyon's 'Mary's city' identity reinforced through 380-year continuous Marian devotion tradition", "Fête des Lumières Festival of Lights growing from basilica window candles to Europe's largest light festival with 4 million visitors", "Eiffel's iron framework providing structural innovation beneath Bossan's eclectic exterior"],
        "relationships": [{"entity": "Pierre Bossan", "relationship": "DESIGNED_BY", "note": "Bossan's 1872-1896 Byzantine-Romanesque eclectic design created Lyon's most recognized landmark"}, {"entity": "Gustave Eiffel", "relationship": "IRON_FRAMEWORK_BY", "note": "Eiffel built the basilica's iron structural framework — one of his major projects before the Eiffel Tower"}, {"entity": "Fête des Lumières", "relationship": "ORIGIN_TRADITION_OF", "note": "Europe's largest light festival (4 million visitors) originated as candles lit in basilica windows on December 8"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Notre-Dame de Fourvière — on a hill where Lyon's first bishop was martyred in 177 CE, built after a Franco-Prussian War vow, with Eiffel's iron structure inside Bossan's eclectic exterior — connects Roman Lugdunum, medieval plague piety, 19th-century war prayers, and 21st-century Europe's largest light festival in a single Lyon hilltop.", "significanceCategory": "continental"},
    }),
    ("crystal-cathedral", {
        "summary": "The Crystal Cathedral in Garden Grove, California, completed 1980 and designed by Philip Johnson and John Burgee, is one of the most architecturally innovative religious buildings of the 20th century — a steel space-frame structure sheathed in 10,000 panes of silver-reflective glass, inspired by the star pattern of a diamond, that seats 2,736 people and was the home of Robert H. Schuller's 'Hour of Power' television ministry (the world's most watched religious television program in the 1980s-1990s, broadcast to 20 million viewers in 180 countries). The Crystal Cathedral represented the apex of American televangelism architecture.\n\nRobert H. Schuller founded the Garden Grove Community Church in 1955, initially holding services in a drive-in theater (cars parked, services broadcast through speakers). The 'drive-in church' concept — which Schuller called his vision of a church accessible to California car culture — was his innovation before television. Philip Johnson's 1980 glass structure was the culmination of Schuller's 'possibility thinking' theology and his television ministry that made him the most televised American Protestant minister.\n\nThe Schuller organization went bankrupt in 2010 following internal family conflicts, excessive debt, and declining television ratings. The Crystal Cathedral and campus were sold to the Roman Catholic Diocese of Orange for $57.5 million in 2012 — converted into Christ Cathedral, the new Roman Catholic cathedral of the Diocese of Orange. The conversion of a Reformed Church in America congregation's landmark into a Catholic cathedral was a remarkable institutional reversal. Philip Johnson's glass structure was preserved with modifications; the campus has been restored to active worship.",
        "causes": ["1955 Robert Schuller drive-in theater church founding as California car culture Christianity innovation", "1980 Philip Johnson glass space-frame completion as televangelism architectural apex", "Hour of Power broadcast to 20 million viewers in 180 countries making Schuller global evangelist", "2010 bankruptcy and 2012 sale to Catholic Diocese of Orange for $57.5 million"],
        "effects": ["World's most watched religious TV program in 1980s-1990s with 20 million viewers in 180 countries", "10,000-pane silver glass space-frame as most architecturally innovative US religious building of its era", "2012 Catholic conversion of Reformed church landmark creating Christ Cathedral Roman Catholic diocese", "Drive-in church model pioneering accessibility-focused American Protestant church design"],
        "relationships": [{"entity": "Philip Johnson", "relationship": "DESIGNED_BY", "note": "Johnson and Burgee's 1980 glass space-frame is considered most innovative US religious building of its era"}, {"entity": "Robert H. Schuller", "relationship": "FOUNDED_BY_MINISTER", "note": "Schuller's Hour of Power broadcast to 20 million in 180 countries was made from Crystal Cathedral"}, {"entity": "Diocese of Orange", "relationship": "SOLD_TO_AND_CONVERTED_BY", "note": "2012 sale to Roman Catholic Diocese of Orange converted Protestant landmark to Christ Cathedral"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Crystal Cathedral — the architectural apex of American televangelism, broadcasting to 20 million viewers in 180 countries from a 10,000-pane glass structure, then sold to the Catholic church after bankruptcy — encapsulates the rise and fall of 20th-century American Protestant media megachurch culture in a single building.", "significanceCategory": "continental"},
    }),
    ("amalfi-cathedral", {
        "summary": "The Cathedral of Saint Andrew (Duomo di Sant'Andrea) in Amalfi, Italy, founded in the 9th century CE and expanded in the 10th-11th centuries in a remarkable Arab-Norman Romanesque style — a product of Amalfi's unique position as one of medieval Italy's most powerful maritime republics with close trading connections to the Arab world and the Byzantine Empire — is one of southern Italy's most architecturally distinctive churches. The Amalfi Cathedral's striped geometric facade and bronze doors (cast in Constantinople in 1065 CE) reflect the Mediterranean cosmopolitan culture of the Amalfitan Republic at its height.\n\nThe Amalfitan Republic (839-1137 CE) was one of the Italian Maritime Republics (with Venice, Genoa, and Pisa) — small city-states that dominated Mediterranean trade in the early medieval period. Amalfi was the wealthiest of the four in the 10th-11th centuries, with a population of 70,000 (larger than Milan at the time). The republic's merchants pioneered the magnetic compass's adoption in European navigation; Amalfi's 'Tabula Amalfitana' (10th-12th century maritime law code) was the foundation of Mediterranean maritime law.\n\nThe cathedral houses relics of Saint Andrew the Apostle (brought from Constantinople in 1208 CE after the Fourth Crusade's looting) — a relic that made Amalfi a major pilgrimage site. The Chiostro del Paradiso (Paradise Cloister, 1268 CE) — an exquisite interlaced Arab arches cloister — is one of southern Italy's most beautiful medieval spaces. Annual pilgrimage (June 27, Feast of Saint Andrew) continues to draw thousands.",
        "causes": ["9th-century CE founding serving Amalfitan Republic as maritime city-state's cathedral", "10th-11th century Arab-Norman expansion reflecting Amalfi's Mediterranean cosmopolitan trading culture", "1065 CE Constantinople bronze doors as product of Byzantine commercial connection", "1208 CE Saint Andrew relics arrival from Fourth Crusade creating major pilgrimage destination"],
        "effects": ["Arab-Norman Romanesque architecture as unique fusion style preserving Amalfitan Mediterranean cosmopolitanism", "Saint Andrew relics making Amalfi major pilgrimage destination from 1208 CE to present", "Tabula Amalfitana maritime law influence through Amalfitan Republic's legal innovations", "Paradise Cloister 1268 CE as one of southern Italy's most beautiful medieval architectural spaces"],
        "relationships": [{"entity": "Amalfitan Republic", "relationship": "CATHEDRAL_OF", "note": "Cathedral served Amalfi as one of Italy's most powerful medieval maritime republics"}, {"entity": "Saint Andrew the Apostle", "relationship": "HOUSES_RELICS_OF", "note": "Andrew's relics brought from Constantinople 1208 CE after Fourth Crusade made Amalfi a pilgrimage site"}, {"entity": "Byzantine Empire", "relationship": "BRONZE_DOORS_COMMISSIONED_FROM", "note": "1065 CE bronze doors cast in Constantinople reflect Amalfi's Byzantine commercial relationship"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Amalfi Cathedral — in Arab-Norman Romanesque style with Constantinople bronze doors and Fourth Crusade relics — is the architectural record of a city that once had 70,000 people, pioneered Mediterranean maritime law, and traded cosmopolitically across the medieval world before being eclipsed by Venice and Genoa.", "significanceCategory": "regional"},
    }),
    ("anagni-cathedral", {
        "summary": "The Cathedral of Santa Maria Annunziata in Anagni, Italy, built 1073-1104 CE in the Romanesque style, is famous primarily as the site of the 'Slap of Anagni' (Schiaffo di Anagni) — the September 7, 1303 confrontation where agents of King Philip IV of France (including Guillaume de Nogaret) seized Pope Boniface VIII in his chamber in Anagni (Boniface's hometown), physically manhandled him, and held him prisoner for three days before townspeople freed him. Boniface died a month later; the incident was the turning point that ended papal political supremacy over European monarchs.\n\nBoniface VIII had issued the papal bull Unam Sanctam (1302) — the most extreme claim of papal supremacy over secular rulers, asserting that 'every human creature' was subject to the Roman pontiff 'as necessary for salvation.' Philip IV of France (who had been taxing French clergy without papal consent) refused this claim; Nogaret's 1303 assault on Boniface was Philip's answer. Whether Boniface was actually slapped (the 'Slap' may be legendary) is disputed, but his physical humiliation by French agents — and his death a month after release — ended the era of medieval papal political supremacy.\n\nThe cathedral's interior contains extraordinary 12th-13th century fresco cycles in the crypt — considered among the finest Romanesque fresco programs in Italy — painted by the 'Cosmati' school (named for the mosaic-paving Roman families). The Cathedral Treasury includes remarkable medieval goldsmith works. The cathedral's Romanesque facade with sculpted portal is one of the most complete examples of Lazio Romanesque.",
        "causes": ["1073-1104 CE Romanesque construction serving Anagni as birthplace of multiple medieval popes", "1302 Unam Sanctam Boniface VIII papal supremacy bull as most extreme medieval papal sovereignty claim", "1303 Nogaret confrontation as Philip IV's answer to papal political supremacy claims", "Extraordinary 12th-13th century Cosmati fresco cycles making cathedral Italy's finest Romanesque program"],
        "effects": ["1303 Slap of Anagni ending medieval papal political supremacy over European monarchs", "Boniface VIII's death one month later as symbolic close of the papal monarchy era", "Avignon Papacy (1309-1377) following as direct consequence of French royal humiliation of papacy", "Cosmati fresco crypt as finest Romanesque fresco program in Lazio preserving medieval iconographic tradition"],
        "relationships": [{"entity": "Pope Boniface VIII", "relationship": "SITE_OF_HUMILIATION_OF", "note": "1303 French agents' Anagni confrontation ended Boniface's life and papal political supremacy"}, {"entity": "Philip IV of France", "relationship": "ASSAULT_ORDERED_BY", "note": "Philip's response to Unam Sanctam; Nogaret's agents seized Boniface in Anagni"}, {"entity": "Avignon Papacy", "relationship": "PRECEDED_MOVE_TO", "note": "1303 humiliation contributed to French papal dominance and 1309-1377 Avignon relocation"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Anagni Cathedral — where agents of the French king physically seized the pope who had declared himself sovereign over all rulers — is the site where medieval papal political supremacy died in 1303, making a small Lazio town's cathedral one of the most historically consequential buildings in the history of church-state relations.", "significanceCategory": "world-changing"},
    }),
    ("angers-cathedral", {
        "summary": "The Cathedral of Saint Maurice in Angers, France, rebuilt in the 12th-13th centuries in Angevin Gothic style — the distinctive architectural school developed in Anjou (the Plantagenet dynasty's home county) — is one of the most important examples of early Gothic architecture outside Île-de-France, notable for its extraordinarily wide nave (16.48 meters, among the widest Gothic naves in France) achieved through Angevin vault technique ('domed' ribbed vaults with a single bay covering very large areas rather than the Parisian two-bay system). The cathedral's Plantagenet connection makes it a center of English royal history.\n\nAnjevine Gothic (also called Plantagenet Gothic after the dynasty) was developed in the Loire Valley in the 12th century as an alternative to the Île-de-France Gothic pioneered at Saint-Denis and Notre-Dame de Paris. The Angevin vault — higher, domed, with a single bay spanning 16+ meters — was technically distinct from Parisian Gothic. Angers Cathedral's nave (rebuilt 1149-1240 CE) is the masterwork of this regional style. Geoffrey V of Anjou (d. 1151, father of Henry II of England) commissioned the earliest phases.\n\nAngers is the capital of Anjou — the Plantagenet dynasty's ancestral county — making the cathedral the spiritual center of the dynasty that ruled England (1154-1485, Henry II through Richard III) and controlled territories from Scotland to the Pyrenees. The cathedral's 12th-century tapestry collection (Notre-Dame de Nantilly) is one of France's most important medieval textile holdings. The Apocalypse Tapestry (1377-1382, commissioned by Louis I of Anjou) — the world's largest surviving medieval tapestry series, 140 meters long — is housed in Angers Castle nearby.",
        "causes": ["12th-century Angevin Gothic architectural school development as Loire Valley alternative to Île-de-France Gothic", "Plantagenet dynasty ancestral territory making Angers cathedral spiritual center of English royal history", "16.48-meter nave width among France's widest using distinctive Angevin vault technique", "Louis I of Anjou 1377-1382 Apocalypse Tapestry commission as world's largest medieval tapestry series"],
        "effects": ["Angevin Gothic style influence on Loire Valley and Norman church architecture", "Plantagenet dynastic identity centered on Angers as ancestral religious and political capital", "16.48-meter Angevin vault nave as technical achievement influencing Gothic architectural development", "Apocalypse Tapestry nearby as world's largest surviving medieval textile series at 140 meters"],
        "relationships": [{"entity": "Plantagenet Dynasty", "relationship": "DYNASTIC_CATHEDRAL_OF", "note": "Angers was ancestral Plantagenet county seat; cathedral served dynasty ruling England 1154-1485"}, {"entity": "Angevin Gothic", "relationship": "MASTERWORK_OF", "note": "Cathedral's 12-13th century nave is the masterwork of Angevin Gothic's wide-bay vault technique"}, {"entity": "Louis I of Anjou", "relationship": "TAPESTRY_COMMISSIONED_BY", "note": "Louis I commissioned 1377-1382 Apocalypse Tapestry (140 meters), world's largest medieval tapestry series"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Angers Cathedral — ancestral spiritual center of the Plantagenet dynasty that ruled England for 331 years, masterwork of Angevin Gothic's wide-bay vault innovation, and adjacent to the world's largest surviving medieval tapestry — is one of the most historically dense provincial French cathedrals, connecting English royal history to architectural innovation.", "significanceCategory": "continental"},
    }),
    ("assisi-cathedral", {
        "summary": "The Cathedral of San Rufino in Assisi, Italy, consecrated in 1253 by Pope Innocent IV, is the most historically important Romanesque cathedral of Umbria — not primarily for its architecture (though its 12th-century pink limestone facade is one of Italy's finest Romanesque) but because it is where Francis of Assisi and Clare of Assisi were both baptized, making it the baptismal church of both founders of the Franciscan and Poor Clares orders. The font where both were baptized — still present in the cathedral — is one of the most theologically significant baptismal fonts in Christianity.\n\nFrancis of Assisi (c. 1181-1226), baptized at San Rufino in 1182, underwent his conversion experience in Assisi at age 20-25 (c. 1201-1206), renouncing his cloth merchant father's wealth at the bishop's court to live in poverty. Clare of Assisi (1194-1253) was also baptized at San Rufino and followed Francis in 1212 to establish the Poor Ladies (Poor Clares). The Franciscan Order, founded 1209, became the largest mendicant religious order in history — currently 25,000+ friars globally.\n\nAssisi's concentration of Franciscan sacred geography: San Rufino (baptisms), San Damiano (Francis's conversion), Porziuncola chapel (Francis's founding community), and the Basilica of San Francesco (Francis's burial place and greatest Gothic cycle by Cimabue and Giotto) make the town the most theologically dense small city in Catholicism. The baptismal font where both Francis and Clare were baptized is preserved behind the high altar — visited by millions annually as part of the Assisi UNESCO pilgrim route.",
        "causes": ["1182 Francis of Assisi baptism at San Rufino font founding Franciscan connection", "1194 Clare of Assisi baptism at same font founding Poor Clares connection", "1253 consecration by Pope Innocent IV as Umbria's most important Romanesque cathedral", "Francis's 1206 poverty renunciation and 1209 Franciscan Order founding from Assisi context"],
        "effects": ["Baptismal font of both Franciscan and Poor Clares founders making San Rufino theologically unique", "25,000+ Franciscan friars globally traceable to 1182 baptism at San Rufino font", "Assisi as most theologically dense small Catholic city combining Francis, Clare, and Franciscan geography", "UNESCO pilgrim route making Assisi one of world's most visited religious pilgrimage destinations"],
        "relationships": [{"entity": "Francis of Assisi", "relationship": "BAPTIZED_AT", "note": "Francis baptized at San Rufino font c. 1182; his Franciscan Order grew to 25,000+ friars globally"}, {"entity": "Clare of Assisi", "relationship": "BAPTIZED_AT", "note": "Clare baptized at same San Rufino font in 1194; founded Poor Clares following Francis's model"}, {"entity": "Basilica of San Francesco", "relationship": "PART_OF_FRANCISCAN_SACRED_COMPLEX", "note": "San Rufino is part of Assisi's Franciscan sacred geography alongside San Damiano and San Francesco"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Assisi Cathedral — housing the baptismal font where both Francis and Clare of Assisi were baptized — is the single most theologically significant baptismal site in Catholic history: the font that initiated two of Christianity's most beloved saints and the founders of religious orders with 25,000+ friars and 20,000+ sisters globally.", "significanceCategory": "world-changing"},
    }),
    ("cremona-cathedral", {
        "summary": "The Cathedral of Santa Maria Assunta in Cremona, Italy, a masterwork of Lombard Romanesque begun in 1107 CE (and its associated baptistery, 1167 CE, and Torrazzo bell tower, 1267-1309 CE), is notable both architecturally — the Torrazzo at 112.7 meters was the tallest campanile in Italy for centuries and remains the tallest pre-modern bell tower in the world — and for its cultural connection to Cremona's unique identity as the birthplace of the violin. The Cathedral Piazza — with the baptistery, Torrazzo, Loggia dei Militi, and town hall — is one of Italy's most complete medieval civic and religious ensembles.\n\nCremona's Romanesque cathedral was begun in 1107 CE as a replacement for the earlier cathedral damaged in an earthquake. The Torrazzo — 'big tower' in the Cremonese dialect — was built 1267-1309 CE by the Comune of Cremona as a civic symbol. At 112.7 meters, it is taller than the Leaning Tower of Pisa and was for centuries Italy's tallest building. The tower contains an astronomical clock (c. 1583 CE) — one of the world's largest — still operational today.\n\nCremona's violin identity: Andrea Amati (c. 1505-1577) invented the modern violin in Cremona and founded a dynasty of luthiers; his students included Nicolò Amati, who taught Antonio Stradivari (1644-1737) — whose 650 surviving instruments are the most valuable handmade objects in the world (individual Stradivarius violins sell for $10-16 million). The cathedral's music program employed professional musicians since the 16th century; Claudio Monteverdi served as cathedral organist 1609-1612 before moving to Venice.",
        "causes": ["1107 CE Romanesque construction after earthquake damage as major Lombard architectural project", "1267-1309 Torrazzo construction as civic tower reaching 112.7 meters — Italy's tallest pre-modern campanile", "16th-century Amati violin invention making Cremona global center of violin making", "Claudio Monteverdi's 1609-1612 cathedral organist role before founding Baroque opera"],
        "effects": ["Torrazzo at 112.7 meters as tallest pre-modern bell tower in world and tallest in Italy for centuries", "1583 astronomical clock among world's largest still operational after 440 years", "Amati-Stradivari violin tradition making Cremona birthplace of the world's most valuable handmade instruments", "Monteverdi's cathedral service bridging Renaissance polyphony to Baroque opera development"],
        "relationships": [{"entity": "Antonio Stradivari", "relationship": "CREMONA_VIOLIN_TRADITION_CULMINATION", "note": "Stradivari worked in Cremona; 650 surviving Stradivarius violins are world's most valuable handmade objects"}, {"entity": "Claudio Monteverdi", "relationship": "CATHEDRAL_ORGANIST", "note": "Monteverdi served as cathedral organist 1609-1612 before moving to Venice and pioneering Baroque opera"}, {"entity": "Andrea Amati", "relationship": "VIOLIN_INVENTION_CITY", "note": "Amati invented the modern violin in Cremona c. 1550; his dynasty trained Stradivari"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Cremona Cathedral — adjacent to the world's tallest pre-modern campanile, in the city where the violin was invented and Stradivarius worked, with Monteverdi as organist — sits at an extraordinary intersection of architectural, musical, and instrument-making history, making Cremona the single city most responsible for classical music's acoustic foundation.", "significanceCategory": "continental"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 100 — Class 341 Cathedrals IV")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
