#!/usr/bin/env python3
"""Batch 138 — Class 316 Parties VIII: Indian & African Political Parties (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/316-Class-316"
FILE_PREFIX = "316"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("all-india-united-democratic-front", {
        "summary": "The All India United Democratic Front (AIUDF), founded in 2005 by Maulana Badruddin Ajmal — a wealthy Muslim politician and perfume businessman from Assam — is a regional political party in Assam, India, representing primarily the Muslim minority of the Brahmaputra Valley and particularly the Bengali-speaking Muslim community in the districts along the Brahmaputra river. The party has become a major force in Assam politics while becoming one of India's most politically controversial regional parties due to its association with the Bengali Muslim minority and its opposition to the Citizenship Amendment Act (2019).\n\nAssam's Muslim population (approximately 34% of the state's 31 million people, the third-highest Muslim percentage of any Indian state) is divided between indigenous Assamese-speaking Muslims (Goriya Muslims, who have been in Assam for centuries) and Bengali-speaking Muslims (many of whom or whose ancestors came from East Bengal/Bangladesh in the 19th-20th centuries). The question of citizenship and 'illegal immigrants' — particularly the National Register of Citizens (NRC) process that attempted to identify undocumented Bengali Muslims — has made the AIUDF a central actor in one of India's most contentious citizenship debates.\n\nThe AIUDF's rise parallels the Hindu nationalist BJP's rise in Assam: as the BJP has made the illegal immigration issue central to Assamese politics, the AIUDF has organized Muslim electoral consolidation. The Citizenship Amendment Act (2019), which granted fast-track citizenship to non-Muslim immigrants from neighboring countries but not Muslims — seen by critics as discriminatory — triggered massive protests in which Assam was a center of opposition.",
        "causes": ["Maulana Badruddin Ajmal founding AIUDF in 2005 to represent Assam's underpresented Muslim minority", "Assam's large Muslim minority (34%) requiring effective political representation in increasingly Hindu nationalist Assam politics", "Bengali Muslim community's citizenship insecurity in the context of illegal immigration debates and NRC process", "BJP's rise in Assam creating political polarization requiring Muslim electoral consolidation"],
        "effects": ["AIUDF becoming a major force in Assam politics representing Muslim minority interests", "Citizenship Amendment Act controversy making AIUDF central to Assam's most divisive political debates", "NRC citizenship verification process threatening Bengali Muslim communities the party represents", "Assam's political polarization between BJP (Hindu nationalist) and AIUDF (Muslim minority representation) deepening"],
        "relationships": [{"entity": "Assam", "relationship": "MAJOR_REGIONAL_POLITICAL_FORCE_IN", "note": "AIUDF is one of Assam's most significant political parties representing the Muslim minority in the Brahmaputra Valley"}, {"entity": "Citizenship Amendment Act 2019", "relationship": "MAJOR_OPPONENT_OF_DISCRIMINATORY_AGAINST_MUSLIMS", "note": "AIUDF led opposition to the CAA which critics argued discriminatorily excluded Muslims from citizenship fast-track"}, {"entity": "National Register of Citizens", "relationship": "REPRESENTS_COMMUNITIES_THREATENED_BY_ASSAM'S_CONTROVERSIAL", "note": "AIUDF represents Bengali Muslim communities whose citizenship was questioned by the NRC process"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The All India United Democratic Front — representing Assam's Muslim minority in one of India's most contentious citizenship debates, opposing the Citizenship Amendment Act — is historically significant as a central actor in the NRC/CAA controversy that raised fundamental questions about Indian secular citizenship.", "significanceCategory": "continental"},
    }),
    ("alliance-of-democratic-forces-for-the-liberation-of-congo", {
        "summary": "The Alliance of Democratic Forces for the Liberation of Congo-Zaire (ADFLC or AFDL, Alliance des forces démocratiques pour la libération du Congo-Zaïre), founded in 1996 and led by Laurent-Désiré Kabila — was the rebel movement that overthrew Mobutu Sese Seko's 32-year dictatorship in the Democratic Republic of Congo (then Zaire), ending one of Africa's most notorious kleptocratic regimes in the First Congo War (1996-1997) with the crucial military support of Rwanda and Uganda.\n\nThe ADFLC's 1996-1997 military campaign — which swept from eastern Congo across the entire country in approximately seven months, covering one of the largest territories in Africa — was made possible primarily by Rwandan military support. Rwanda's new Tutsi-led government (post-1994 genocide) had strong motivation to pursue the Hutu interahamwe génocidaires who had fled into eastern Congo after the genocide, and the ADFLC's campaign served as cover for Rwanda's military objectives. This Rwandan military support, along with Ugandan assistance, was the real military force behind the ADFLC's extraordinary swift conquest.\n\nLaurent-Désiré Kabila became President of the DRC in 1997 but proved as disappointing as Mobutu in many respects — quickly falling out with his Rwandan backers (triggering the Second Congo War in 1998, one of Africa's most catastrophic conflicts, killing approximately 5 million people directly and indirectly). Kabila was assassinated in 2001 and succeeded by his son Joseph Kabila. The ADFLC's overthrow of Mobutu thus led not to a genuine democratic transformation but to another authoritarian regime and an even worse war.",
        "causes": ["Mobutu Sese Seko's 32-year kleptocratic dictatorship creating conditions for armed rebellion", "Rwanda's need to pursue Hutu genocide perpetrators who fled into eastern Congo after 1994 genocide", "Eastern Congo's Congolese Tutsi (Banyamulenge) community's marginalization and threat creating recruitment base for ADFLC", "Uganda's strategic interest in destabilizing Mobutu's Congo supporting the rebel movement"],
        "effects": ["ADFLC's seven-month campaign overthrew Mobutu's 32-year Zairian dictatorship in May 1997", "Laurent-Désiré Kabila's disappointing presidency falling out with Rwanda and triggering the catastrophic Second Congo War", "Second Congo War (1998-2003+) killing approximately 5 million people making it Africa's deadliest modern conflict", "DRC's continuing cycle of violence and instability partly traced to the power vacuum and instability following Mobutu's fall"],
        "relationships": [{"entity": "Mobutu Sese Seko", "relationship": "REBEL_MOVEMENT_THAT_OVERTHREW_32-YEAR_DICTATOR", "note": "The ADFLC overthrew Mobutu after a seven-month campaign across the vast DRC territory"}, {"entity": "Rwanda", "relationship": "MILITARY_FORCE_BEHIND_THE_ADFLC_CAMPAIGN_PROVIDED_BY", "note": "Rwanda provided the primary military support for the ADFLC, using the campaign to pursue Hutu genocidaires in eastern Congo"}, {"entity": "Second Congo War", "relationship": "ADFLC_LEADER_KABILA'S_POLICIES_TRIGGERING", "note": "Laurent Kabila's falling out with Rwanda triggered the 1998 Second Congo War that killed approximately 5 million people"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The ADFLC — which overthrew Mobutu's 32-year Zairian dictatorship but led to the catastrophic Second Congo War killing approximately 5 million people — is historically significant as a turning point in central African history whose consequences include Africa's deadliest modern conflict.", "significanceCategory": "world-changing"},
    }),
    ("alliance-of-independent-social-democrats", {
        "summary": "The Alliance of Independent Social Democrats (SSDS, Szövetség a Független Szociáldemokratákért) was a post-communist Hungarian political party that emerged in the fragmented political landscape of Hungary's 1989-1990 democratic transition — representing one of many short-lived centrist and social democratic parties that attempted to fill the space between the Hungarian Socialist Party (the reformed communist party) and the various conservative and nationalist parties that dominated Hungary's first free elections.\n\nHungary's 1990 democratic transition was one of the most peaceful and negotiated of the Eastern European revolutions of 1989: the Hungarian Socialist Workers' Party (communist) had been reforming itself since 1988, and the 'Negotiated Transition' (Kerekasztal Tárgyalások, Round Table Negotiations) between the communist government and opposition groups produced a remarkably orderly transition. This negotiated character of Hungarian democratization meant that the political landscape was more complex than in countries with more dramatic revolutionary breaks.\n\nThe Alliance of Independent Social Democrats, like many small centrist parties in Hungary's early democratic period, attempted to occupy the center-left space but faced competition from both the reformed Hungarian Socialist Party and the various new democratic parties. Most such small centrist parties either merged with larger organizations or disappeared in subsequent elections as Hungary's party system consolidated around fewer, larger parties.",
        "causes": ["Hungary's 1990 democratic transition creating political space for multiple new parties including centrist social democrats", "Negotiated transition's complex political landscape enabling small parties to form without clear dominant ideological successor", "Center-left political space requiring alternatives between reformed communist party and conservative/nationalist parties", "Post-communist fragmentation before party system consolidation supporting multiple competing small parties"],
        "effects": ["Small centrist party attempting to occupy social democratic space in Hungary's early democratic period", "Party system fragmentation in Hungary's first free elections involving dozens of small parties and coalitions", "Subsequent party consolidation marginalizing small centrist parties that could not reach electoral thresholds", "Hungarian social democracy eventually consolidated into the Hungarian Socialist Party rather than independent small parties"],
        "relationships": [{"entity": "Hungary's Democratic Transition", "relationship": "PARTY_EMERGING_FROM_1989-1990_NEGOTIATED", "note": "The party emerged from Hungary's negotiated democratic transition that created space for multiple new centrist parties"}, {"entity": "Hungarian Socialist Party", "relationship": "CENTER-LEFT_COMPETITOR_TO_REFORMED_COMMUNIST_PARTY_TURNED", "note": "The party competed with the MSZP (Hungarian Socialist Party) for center-left voters in Hungary's early democratic period"}, {"entity": "Post-Communist Party Fragmentation", "relationship": "SMALL_PARTY_TYPICAL_OF_EASTERN_EUROPEAN", "note": "The party is typical of the small centrist parties that emerged in Eastern European democratic transitions before party system consolidation"}],
        "historicalSignificance": {"significanceScore": 3, "significanceNarrative": "The Alliance of Independent Social Democrats Hungary — a small centrist party in Hungary's 1990 democratic transition, typical of the fragmented political landscape before consolidation — is locally significant as documentation of the complexity of Eastern European democratic transitions.", "significanceCategory": "local"},
    }),
    ("alternative-democratic-pole", {
        "summary": "The Alternative Democratic Pole (Polo Democrático Alternativo, PDA) was a Colombian left-wing political party formed in 2006 through the merger of several Colombian left-wing organizations — representing a significant development in Colombian politics as one of the few successful left-wing parties in a country where leftist political movements had historically been extremely vulnerable to assassination by paramilitary groups associated with Colombia's decades-long armed conflict.\n\nColombia's political history has been marked by extraordinary political violence against the left: the Unión Patriótica (UP), a leftist party formed in 1985 as part of peace negotiations with the FARC guerrillas, was subjected to systematic assassination — approximately 3,000-5,000 UP members were killed between 1985 and 1993, including presidential candidates, senators, and local officials. This genocide of a political party effectively destroyed the UP and demonstrated the extreme danger of left-wing political participation in Colombia.\n\nThe PDA's formation in 2006 thus represented a significant courage: organizing a legal left-wing party in a country where this had historically been a death sentence. The party achieved significant electoral success, winning the Bogotá mayorship (Samuel Moreno, 2007; Gustavo Petro, 2011) and national congressional representation. Gustavo Petro, the most prominent PDA-associated politician, became Colombia's president in 2022 — the first left-wing president in Colombia's history, an extraordinary development given the country's history of left-wing political violence.",
        "calls": [],
        "causes": ["Colombia's 2006 political opening allowing left-wing parties to organize after decades of extreme violence against the left", "Merger of Colombian left-wing organizations providing strength in numbers and organizational cohesion", "Bogotá's progressive urban electorate providing electoral base for left-wing municipal politics", "International and domestic pressure for Colombian political inclusion of the left after the UP genocide"],
        "effects": ["PDA winning Bogotá mayorship multiple times demonstrating left-wing electoral viability", "Gustavo Petro's PDA-associated career culminating in Colombia's first ever left-wing presidency (2022)", "Legal left-wing politics in Colombia made viable despite the country's history of left-wing political violence", "Colombia's political landscape transformed by first left-wing presidential victory after decades of exclusion"],
        "relationships": [{"entity": "Gustavo Petro", "relationship": "MOST_PROMINENT_POLITICIAN_ASSOCIATED_WITH_PARTY_BECOMING_COLOMBIA'S_FIRST_LEFT_PRESIDENT", "note": "Petro's career through PDA led to his 2022 election as Colombia's first ever left-wing president"}, {"entity": "Unión Patriótica", "relationship": "SUCCESSOR_TO_POLITICAL_TRADITION_AFTER_UP_GENOCIDE", "note": "PDA represents left-wing political organization in Colombia after the UP was effectively destroyed through systematic assassination"}, {"entity": "Bogotá", "relationship": "ELECTORAL_BASE_WINNING_MULTIPLE_MAYORAL_ELECTIONS_IN", "note": "The party won multiple Bogotá mayoral elections, establishing left-wing governance in Colombia's capital"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Alternative Democratic Pole Colombia — organizing legal left-wing politics in a country where this had historically meant death, launching Gustavo Petro's career to Colombia's first left-wing presidency — is historically significant as a monument to Colombian democratic opening after decades of political violence against the left.", "significanceCategory": "world-changing"},
    }),
    ("alternative-democratic-reform-party", {
        "summary": "The Alternative Democratic Reform Party (ADR) is a Luxembourgish conservative political party founded in 1987, originally as a pensioners' and retirees' party (CSV, Comité pour la Solidarité des Victimes de la vie) before evolving into a broader right-wing conservative party — representing a strand of conservative politics in Luxembourg, one of the world's wealthiest nations and the heart of European financial infrastructure, where economic liberalism and social conservatism compete with the dominant Christian social and socialist parties.\n\nLuxembourg's political landscape is shaped by its extraordinary wealth (GDP per capita among the world's highest, driven by financial services, steel, and EU institutions) and its unique position as both a founding EU member and host of major EU institutions (European Court of Justice, European Court of Auditors, European Investment Bank). Luxembourg's small population (~660,000) includes a large immigrant component (~47% non-citizen residents) that shapes political debates about identity, welfare, and civic participation.\n\nThe ADR has positioned itself on issues of national identity and immigration, opposing the extension of voting rights to non-citizens and advocating Luxembourgish language and cultural identity protection. The party has had limited but consistent electoral presence in Luxembourg's parliament, typically receiving 5-10% of the vote, and represents the conservative-nationalist strand in an otherwise quite internationalist and progressive small nation.",
        "causes": ["1987 founding as pensioners' advocacy group responding to Luxembourg's social welfare policy debates", "Evolution into broader conservative party filling right-wing nationalist space in Luxembourg's political landscape", "Immigration and national identity issues creating constituency for a party protecting Luxembourgish cultural identity", "Luxembourg's large non-citizen resident population creating debates about voting rights and civic participation"],
        "effects": ["ADR providing consistent conservative-nationalist voice in Luxembourg's overwhelmingly internationalist political environment", "Non-citizen voting rights debates in Luxembourg influenced by ADR's opposition", "Luxembourgish language and cultural identity advocacy in one of Europe's most multilingual societies", "Small but persistent parliamentary presence demonstrating consistent conservative-nationalist electoral constituency"],
        "relationships": [{"entity": "Luxembourg", "relationship": "CONSERVATIVE-NATIONALIST_PARTY_IN_ONE_OF_WORLD'S_WEALTHIEST_AND_MOST_INTERNATIONALIST_NATIONS", "note": "ADR is Luxembourg's conservative-nationalist party in a country that is one of the world's wealthiest and most internationally integrated"}, {"entity": "Luxembourg Immigration", "relationship": "OPPOSITION_TO_NON-CITIZEN_VOTING_RIGHTS_REPRESENTING_RESPONSE_TO", "note": "ADR's key positions respond to Luxembourg's unique situation where nearly half the residents are non-citizens"}, {"entity": "European Integration", "relationship": "CONSERVATIVE_VOICE_QUESTIONING_PACE_OF_IN_EU'S_ADMINISTRATIVE_CENTER", "note": "ADR provides a conservative-national counterweight to Luxembourg's pro-European consensus"}],
        "historicalSignificance": {"significanceScore": 3, "significanceNarrative": "The Alternative Democratic Reform Party Luxembourg — a conservative-nationalist party in Europe's wealthiest small nation, advocating Luxembourgish identity amid 47% non-citizen population — is locally significant as a monument to conservative-nationalist politics in an otherwise highly internationalist EU hub.", "significanceCategory": "local"},
    }),
    ("amhara-democratic-party", {
        "summary": "The Amhara Democratic Party (ADP, later renamed the Amhara National Movement, now part of the Prosperity Party) was one of the ethnic-based regional parties in Ethiopia's ruling coalition (EPRDF, Ethiopian People's Revolutionary Democratic Front) from 1991 to 2019, representing the Amhara region of Ethiopia — home to Ethiopia's most historically powerful ethnic group that dominated the Ethiopian Empire under the Solomonic dynasty emperors and the Haile Selassie monarchy.\n\nEthiopia's ethnic federalism — established by the EPRDF after it overthrew the Derg military dictatorship in 1991 — organized the country along ethnic-regional lines, with each major ethnic group having its own regional state and a corresponding ethnic party within the ruling coalition. The Amhara Democratic Party (originally the Amhara National Democratic Movement) represented the Amhara regional state, giving institutional form to Amhara political interests within a federal system designed partly to prevent any single ethnic group's domination.\n\nThe Amhara question in Ethiopian politics is extraordinarily complex: Amharas were historically the dominant group of the Solomonic empire (Amharic became Ethiopia's official language, the Orthodox church used Ge'ez, an Amhara cultural tradition) but were subject to the EPRDF's ethnic federalism framework that limited Amhara influence. The ADP's evolution, its incorporation into Abiy Ahmed's Prosperity Party (2019), and the subsequent Tigray War (2020-2022) — in which Amhara militia fought alongside the federal government against the TPLF — all reflect Ethiopia's extraordinarily complex ethnic political dynamics.",
        "causes": ["EPRDF's 1991 ethnic federalism creating ethnic-based regional parties including the Amhara party", "Amhara region's representation in the ruling coalition requiring formal institutional party structure", "Ethiopia's ethnic federalism framework requiring each major ethnic group's party within the EPRDF coalition", "Post-Derg democratization process creating institutional structures for ethnic-regional political representation"],
        "effects": ["Amhara Democratic Party representing Amhara interests within EPRDF ethnic coalition from 1991-2019", "ADP merger into Abiy Ahmed's Prosperity Party (2019) as part of EPRDF restructuring", "Tigray War (2020-2022) revealing Amhara-Tigray tensions in which Amhara forces fought alongside federal government", "Ethiopia's ethnic federal system proving fraught as Amhara-Tigray and Amhara-Oromo conflicts emerged"],
        "relationships": [{"entity": "EPRDF", "relationship": "CONSTITUENT_ETHNIC_PARTY_IN_RULING_COALITION_OF", "note": "ADP was one of EPRDF's four constituent ethnic parties representing the Amhara region from 1991-2019"}, {"entity": "Ethiopian Ethnic Federalism", "relationship": "INSTITUTIONAL_EXPRESSION_OF_AMHARA_REPRESENTATION_IN", "note": "The party was created as part of Ethiopia's ethnic federalism that organized politics along ethnic-regional lines"}, {"entity": "Prosperity Party", "relationship": "MERGED_INTO_ABIY_AHMED'S_2019", "note": "ADP was merged with other EPRDF constituent parties into Abiy Ahmed's Prosperity Party in 2019"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Amhara Democratic Party — representing Ethiopia's historically dominant Amhara ethnic group in the EPRDF's ethnic federal system, merged into the Prosperity Party before the Tigray War — is historically significant as a central institution of Ethiopia's fraught ethnic federalism experiment.", "significanceCategory": "world-changing"},
    }),
    ("antigua-and-barbuda-labour-party", {
        "summary": "The Antigua and Barbuda Labour Party (ABLP), founded in 1946 by Vere Cornwall Bird — one of the Caribbean's most significant trade union and political leaders — has been the dominant political party in Antigua and Barbuda for most of the country's modern history, holding power for most of the years from 1956 to the present and guiding the twin-island nation through the transition from British colonial status to independence (1981) as one of the Caribbean's most continuous political dynasties, centered on the Bird family.\n\nVere Cornwall Bird's founding of the ABLP in the context of the Antiguan labor movement (after organizing the Antigua Trades and Labour Union) followed the pattern of Caribbean political development in which labor unions became the foundation of mass political movements that led to independence. This model — union organizing → political party → electoral politics → independence — was the typical trajectory of Caribbean decolonization, and Bird's ABLP was one of its most successful examples.\n\nThe Bird family's dominance of Antiguan politics — Vere Cornwall Bird served as premier/prime minister from 1960-1994, and his son Lester Bird served as prime minister from 1994-2004 — represents one of the Caribbean's most sustained political family dynasties. The ABLP's long rule has been associated with both Antigua's economic development (tourism-based economy, tax haven status) and controversy (Birdnest scandals, gun-running scandal involving Lester Bird's brother Vere Jr., and other corruption allegations).",
        "causes": ["Vere Cornwall Bird's trade union organizing establishing the labor movement base for the ABLP's 1946 founding", "Caribbean decolonization movement requiring mass political parties to negotiate independence from Britain", "Antigua's working class and sugar industry laborers forming the ABLP's initial electoral base", "British Caribbean constitutional evolution creating elected government structures for labor-backed parties to contest"],
        "effects": ["ABLP dominating Antiguan politics for most of the period from 1956 to present", "Antigua and Barbuda independence (1981) achieved under ABLP leadership", "Bird family political dynasty as one of the Caribbean's most sustained with father-son prime ministerial succession", "Antigua's tourism and financial services economy developed under ABLP's long governance"],
        "relationships": [{"entity": "Vere Cornwall Bird", "relationship": "FOUNDED_BY_AND_FIRST_LED_BY_LABOR_LEADER", "note": "V.C. Bird founded the ABLP in 1946, led the independence movement, and served as prime minister from 1960-1994"}, {"entity": "Antigua and Barbuda Independence", "relationship": "PARTY_THAT_NEGOTIATED_AND_ACHIEVED_1981", "note": "The ABLP under V.C. Bird led Antigua and Barbuda to independence from Britain in 1981"}, {"entity": "Caribbean Labour Movement", "relationship": "EXEMPLARY_CASE_OF_TRADE_UNION_TO_INDEPENDENCE_PARTY_IN", "note": "The ABLP's development from labor union to independence party is the classic Caribbean decolonization trajectory"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Antigua and Barbuda Labour Party — founded by V.C. Bird's labor movement, dominant in Antiguan politics for most of 70+ years, achieving independence in 1981 — is historically significant as one of the Caribbean's most successful and sustained independence-era political institutions.", "significanceCategory": "continental"},
    }),
    ("arab-nationalist-movement", {
        "summary": "The Arab Nationalist Movement (ANM, حركة القوميين العرب, Harakat al-Qawmiyyin al-Arab), founded in 1951 at the American University of Beirut by George Habash (a Palestinian Christian), Wadi' Haddad, and others — was one of the most significant pan-Arab political movements of the 1950s-1970s, beginning as an idealistic student movement committed to Arab unity and Palestinian liberation and evolving into a radicalized militant organization that pioneered international airplane hijacking and became a significant actor in Cold War terrorism.\n\nGeorge Habash's ANM was founded in the immediate aftermath of the 1948 Arab-Israeli War and the Nakba (Palestinian Catastrophe), in which approximately 700,000 Palestinians fled or were expelled from their homeland. This founding trauma shaped the ANM's ideology: unlike the Ba'ath Party's focus on state-level Arab nationalism, the ANM focused on pan-Arab unity as the prerequisite for Palestinian liberation, arguing that only a unified Arab world could defeat Israel.\n\nThe ANM's evolution from student movement to militant organization reflects the radicalization of Palestinian politics after successive Arab defeats: after the catastrophic 1967 Six-Day War destroyed the pan-Arab project, the ANM reconstituted as the Popular Front for the Liberation of Palestine (PFLP), which under Wadi' Haddad pioneered airplane hijacking as a political tactic — a tactical innovation that transformed global terrorism and counter-terrorism. George Habash and the PFLP's 1968-1972 airplane hijacking campaign permanently changed international aviation security.",
        "causes": ["1948 Nakba's expulsion of 700,000 Palestinians creating the traumatic founding context for Palestinian political movements", "George Habash's experience at AUB during the 1948 war transforming idealistic students into political activists", "Pan-Arab ideology arguing that Palestinian liberation required Arab unity as prerequisite", "1967 Six-Day War's catastrophic defeat radicalizing the ANM into militant PFLP"],
        "effects": ["ANM reconstituting as PFLP after 1967 defeat pioneering international airplane hijacking", "PFLP's 1968-1972 hijacking campaigns permanently transforming global aviation security protocols", "Palestinian political radicalization trajectory documented in ANM's evolution from student movement to terrorism", "Pan-Arab idealism's failure creating the conditions for Palestinian secular nationalist and later Islamist militancy"],
        "relationships": [{"entity": "George Habash", "relationship": "FOUNDED_BY_CHRISTIAN_PALESTINIAN_PHYSICIAN_TURNED_MILITANT_LEADER", "note": "George Habash, a Palestinian Christian physician, founded the ANM at AUB in 1951 and led its evolution into the PFLP"}, {"entity": "Popular Front for the Liberation of Palestine", "relationship": "RECONSTITUTED_AS_AFTER_1967_DEFEAT", "note": "The ANM reconstituted as the PFLP in 1967, becoming the organization that pioneered international airplane hijacking"}, {"entity": "International Terrorism", "relationship": "AIRPLANE_HIJACKING_AS_POLITICAL_TACTIC_PIONEERED_BY", "note": "The PFLP evolved from the ANM pioneered international airplane hijacking, permanently transforming global security"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Arab Nationalist Movement — founded after the 1948 Nakba, evolving into the PFLP that pioneered international airplane hijacking, permanently transforming global aviation security — is historically significant as a monument to Palestinian political radicalization and the origins of modern international terrorism.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 138 — Class 316 Parties VIII: Indian & African Political Parties")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
