#!/usr/bin/env python3
"""Batch 82 — Class 312 Dynasties V (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/312-Class-312"
FILE_PREFIX = "312"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("yuan-dynasty", {
        "summary": "The Yuan Dynasty (1271–1368 CE), established by Kublai Khan as the Chinese manifestation of the Mongol Empire, was the first foreign dynasty to conquer and rule all of China — governing the world's largest economy and most populous civilization from Beijing (Khanbaliq) for nearly a century. The Yuan period was the apex of Eurasian connectivity: Marco Polo's journey (1271-1291) traversed a Pax Mongolica that enabled safe trade from Venice to Beijing, bringing silk, spices, paper money, and gunpowder technology westward.\n\nKublai Khan, grandson of Genghis Khan, conquered the Southern Song Dynasty in 1279 after 40 years of warfare — the final absorption completing the Mongol reunification of China. Kublai adopted Chinese administrative practices, employed Chinese officials, revived the Confucian examination system, and patronized Chinese culture while maintaining the Mongol ruling class. Yuan China had 60 million inhabitants — more than contemporary Europe — and its capital Khanbaliq (Beijing) was the world's largest city.\n\nThe Yuan's collapse came from the combination of economic mismanagement (massive paper money inflation), discriminatory ethnic policies (ranking Mongols, Central Asians, northern Chinese, and southern Chinese in descending legal status), natural disasters, and the 1331-1353 bubonic plague (Black Death spreading from Mongol trade routes to Europe). Zhu Yuanzhang, a Buddhist monk and commoner soldier, overthrew the Yuan in 1368 and founded the Ming Dynasty — one of history's most dramatic reversals of foreign rule.",
        "causes": ["Kublai Khan's conquest of Southern Song Dynasty in 1279 completing all-China Mongol rule", "Pax Mongolica creating safe Eurasian trade routes enabling Marco Polo's journey", "Chinese administrative adoption enabling governance of world's largest civilization by steppe nomads", "Black Death spreading through Mongol trade routes simultaneously weakening Yuan and killing European third of population"],
        "effects": ["First complete foreign conquest of China establishing template for Manchu Qing Dynasty 300 years later", "Marco Polo's account introduced Chinese paper money, pasta, silk, and gunpowder concepts to Europe", "Black Death's spread westward on Mongol trade routes killed one-third of Europe's population", "Yuan's collapse under Zhu Yuanzhang established Ming Dynasty's 276-year Chinese imperial restoration"],
        "relationships": [{"entity": "Kublai Khan", "relationship": "FOUNDED_BY", "note": "Kublai Khan declared Yuan Dynasty in 1271 as Chinese branch of Mongol Empire"}, {"entity": "Marco Polo", "relationship": "DESCRIBED_BY", "note": "Polo's 1271-1291 journey through Yuan China introduced Chinese civilization to European awareness"}, {"entity": "Black Death", "relationship": "WEAKENED_BY", "note": "Bubonic plague spreading on Mongol trade routes simultaneously weakened Yuan and killed one-third of Europe"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Yuan Dynasty's Pax Mongolica created the first reliable Eurasian transcontinental trade network — spreading Marco Polo's revelations of Chinese civilization westward and the Black Death with catastrophic consequences, making it the dynasty that most changed the trajectory of both East and West simultaneously.", "significanceCategory": "world-changing"},
    }),
    ("almohad-caliphate", {
        "summary": "The Almohad Caliphate (al-Muwahhidun — 'Those who affirm Divine Unity'), founded in 1121 by Ibn Tumart in the Atlas Mountains of Morocco, was the last great Berber empire of North Africa and al-Andalus, ruling from the Atlantic to Tripolitania and from the Sahara to Toledo at its height (1150-1220). The Almohads produced medieval philosophy's two greatest minds — Averroes (Ibn Rushd) and Maimonides — while simultaneously conducting religious persecutions that forced both out of al-Andalus; this paradox defines the complexity of medieval Islamic cultural history.\n\nIbn Tumart, a Berber scholar who studied in Baghdad and returned preaching strict theological unitarianism, declared himself the Mahdi and began a religious reform movement from the Moroccan High Atlas. The Almohads overthrew the Almoravid Dynasty (itself a Berber empire) in 1147, then conquered al-Andalus, uniting North Africa and Spain under Berber rule for the first time. The Almohads' architectural legacy — the Giralda (Seville), Koutoubia Mosque (Marrakesh), and Hassan Tower (Rabat) — represents the apex of Berber-Islamic architecture.\n\nAverroes (1126-1198), the court physician and philosopher who wrote commentaries on Aristotle so influential that European scholastics called Aristotle 'the Philosopher' and Averroes 'the Commentator,' and Maimonides (1135-1204), the greatest medieval Jewish philosopher, both lived and worked in Almohad Córdoba — before persecution drove them out, Averroes to exile, Maimonides to Egypt. The Almohads' forced conversion of Jews and Christians created the first mass refugee crisis in Iberian history.",
        "causes": ["1121 founding by Ibn Tumart in Atlas Mountains preaching strict theological unitarianism", "Almohad overthrow of Almoravid Dynasty in 1147 and conquest of al-Andalus", "Almohad court patronage of Averroes and Maimonides creating medieval philosophy's greatest works", "Forced conversion of Jews and Christians creating first mass Iberian refugee crisis"],
        "effects": ["Averroes's Aristotle commentaries transmitted to Latin Europe and sparked Scholastic revolution", "Maimonides's Guide for the Perplexed influenced Thomas Aquinas and medieval Christian theology", "Giralda, Koutoubia, and Hassan Tower represent apex of Berber-Islamic architectural achievement", "Almohad persecution creating Iberian Jewish refugee crisis that seeded communities across Mediterranean"],
        "relationships": [{"entity": "Ibn Tumart", "relationship": "FOUNDED_BY", "note": "Ibn Tumart declared himself Mahdi and launched Almohad movement from Atlas Mountains in 1121"}, {"entity": "Averroes", "relationship": "PATRONIZED_THEN_EXILED", "note": "Averroes served as Almohad court physician and wrote Aristotle commentaries before exile"}, {"entity": "Maimonides", "relationship": "PRODUCED_EXILE_OF", "note": "Almohad persecution forced Maimonides to flee to Egypt where he wrote Guide for the Perplexed"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Almohad Caliphate hosted Averroes and Maimonides — medieval philosophy's two greatest minds — while simultaneously persecuting them, and the Averroes commentaries transmitted to Latin Europe triggered the Scholastic revolution that produced Thomas Aquinas, the Renaissance, and ultimately Western science.", "significanceCategory": "world-changing"},
    }),
    ("ahom-dynasty", {
        "summary": "The Ahom Dynasty (1228–1826 CE), established by Sukaphaa in the Brahmaputra Valley of Assam (northeastern India), was medieval Southeast Asia's most exceptional polity — ruling Assam continuously for 598 years, the longest period of any dynasty in Indian history, and successfully defeating 17 Mughal invasions while every other northeastern Indian kingdom fell. The Ahoms created a unique synthesis of Tai (Thai-Shan) Buddhist and Hindu cultures in the Assamese jungles, developing the Ahom script, distinctive architecture, and a paik corvée labor system.\n\nSukaphaa, a Tai prince who migrated from the Shan Plateau of Burma with a small band of followers, crossed the Patkai hills into Assam in 1228. The Ahoms absorbed indigenous Bodo-Kachari and Bengali populations, gradually converting from Tai Buddhism to Hinduism while preserving Ahom ritual language. The Ahom administrative system — dividing territory among princes with specific corvée labor responsibilities — proved uniquely effective at organizing forest-kingdom governance.\n\nThe Battle of Saraighat (1671) — where Ahom general Lachit Borphukan defeated Aurangzeb's Mughal fleet on the Brahmaputra River — is celebrated as India's most significant defeat of the Mughal Empire. After 17 Mughal attempts, the Brahmaputra Valley remained unsubdued. The Ahoms fell not to the Mughals but to the Burmese Kon-Baung invasion (1817-1822), followed by British annexation under the Treaty of Yandabo (1826) — becoming part of British Bengal. Lachit Borphukan is now a national hero celebrated on Lachit Divas.",
        "causes": ["1228 founding by Tai prince Sukaphaa crossing Patkai hills with followers from Shan Plateau", "Unique Tai-Hindu cultural synthesis creating distinctive Assamese civilization", "Paik corvée system providing administrative and military labor for forest-kingdom governance", "17 successful repulsions of Mughal invasions culminating in 1671 Battle of Saraighat"],
        "effects": ["598-year Ahom rule was longest continuous dynasty in Indian history", "Battle of Saraighat 1671 defeat of Mughal fleet became India's celebrated anti-imperial resistance victory", "Ahom synthesis created distinctive Assamese language, script, and culture surviving to present", "Treaty of Yandabo 1826 British annexation ended last pre-colonial northeastern Indian dynasty"],
        "relationships": [{"entity": "Sukaphaa", "relationship": "FOUNDED_BY", "note": "Tai prince Sukaphaa founded Ahom dynasty in Brahmaputra Valley in 1228"}, {"entity": "Lachit Borphukan", "relationship": "GREATEST_GENERAL", "note": "Borphukan's 1671 Saraighat victory defeated Mughal fleet; now celebrated as national hero"}, {"entity": "Aurangzeb", "relationship": "DEFEATED_INVASION_OF", "note": "17 Mughal invasions under multiple emperors including Aurangzeb failed to conquer Ahom kingdom"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Ahom Dynasty's 598-year reign — the longest continuous dynasty in Indian history — and its 17 successful defeats of Mughal invasion make it the most extraordinary example of a small jungle kingdom resisting a continental superpower.", "significanceCategory": "continental"},
    }),
    ("chakri-dynasty", {
        "summary": "The Chakri Dynasty of Thailand, founded in 1782 by General Chakri (Rama I) after the capital was moved from Thonburi to Bangkok, has ruled Thailand continuously for over 240 years — making it one of the world's longest-reigning royal dynasties. The Chakri Dynasty's most significant achievement is Thailand's survival as the only Southeast Asian country never colonized by a European power — maintained through skilled diplomacy under Ramas IV and V (Mongkut and Chulalongkorn) who modernized the kingdom while ceding peripheral territories to appease colonial appetites.\n\nRama I established Bangkok (Krung Thep Mahanakhon — the 'City of Angels') as the new capital after the Burmese destroyed Ayutthaya in 1767. The Chakri kings consciously modeled Bangkok on Ayutthaya, constructing the Grand Palace, Wat Phra Kaew (Temple of the Emerald Buddha), and the Rattanakosin island administrative complex. The Chakri Reformation under Rama IV (Mongkut, 1851-1868) — the king portrayed in The King and I — introduced Western science and legal reform while resisting European colonization.\n\nRama V (Chulalongkorn, 1868-1910) was Thailand's greatest modernizing monarch — abolishing slavery, building railways, reforming the legal code, creating a modern bureaucracy, and personally conducting diplomatic missions to Europe. He ceded Laos, Cambodia, and the Malay states to France and Britain as buffer zones while maintaining Thai independence. Rama IX (Bhumibol Adulyadej, 1946-2016) — who reigned for 70 years — became the world's longest-reigning monarch and a beloved unifying figure through periods of military coups and political crises.",
        "causes": ["1782 founding by Rama I after moving capital to Bangkok post-Burmese destruction of Ayutthaya", "Ramas IV-V diplomatic modernization strategy maintaining Thai independence during colonial era", "Bangkok construction as magnificent new capital rivaling and honoring destroyed Ayutthaya", "Rama IX's 70-year reign providing continuity through decades of Thai political instability"],
        "effects": ["Thailand became only Southeast Asian country never colonized by a European power", "Bangkok's construction created one of Asia's most magnificent cities from a fishing village", "Chulalongkorn's slavery abolition and modernization transformed Thailand into modern state", "Bhumibol's 70-year reign was world's longest monarchy, providing stabilizing continuity"],
        "relationships": [{"entity": "Rama I", "relationship": "FOUNDED_BY", "note": "General Chakri crowned Rama I in 1782 and established Bangkok as new Thai capital"}, {"entity": "Chulalongkorn", "relationship": "GREATEST_REFORMER", "note": "Rama V abolished slavery, built railways, and preserved Thai independence through European buffer-zone concessions"}, {"entity": "Bhumibol Adulyadej", "relationship": "LONGEST_REIGNING", "note": "Rama IX's 70-year reign was world's longest; stabilized Thailand through multiple coup cycles"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Chakri Dynasty's preservation of Thai independence through the entire European colonial era — by modernizing just enough and ceding just enough territory to satisfy colonial powers — is the most successful example of a small kingdom using diplomacy to survive imperial conquest.", "significanceCategory": "world-changing"},
    }),
    ("tudor-period", {
        "summary": "The Tudor Dynasty of England (1485–1603), founded when Henry Tudor defeated Richard III at Bosworth Field and became Henry VII, was arguably the most consequential dynasty in English history — encompassing the English Reformation, the break with Rome, the dissolution of the monasteries, the Elizabethan literary and musical renaissance, the beginning of British global exploration, and the Protestant-Catholic religious wars that shaped British identity for 400 years. Five Tudors governed a century that transformed England from a medieval Catholic kingdom to a Protestant nation-state.\n\nHenry VII (1485-1509) ended the Wars of the Roses and stabilized English finances. Henry VIII (1509-1547) broke with Rome (1534) to annul his marriage to Catherine of Aragon, dissolved over 800 monasteries, executed two wives and two chancellors, and created the Church of England — a theological and political revolution that established English Protestantism. Edward VI's brief Protestant radicalism was followed by 'Bloody Mary' (Mary I) burning 300 Protestants before Elizabeth I's 45-year reign created England's golden age.\n\nElizabeth I's reign (1558-1603) produced Shakespeare, Marlowe, and Spenser; Drake's circumnavigation; Raleigh's Virginia expeditions; the Armada defeat; and the creation of a Protestant English national identity. The Tudor century created most of the institutions — Parliament's independence, common law courts, English Bible, Church of England — that became the foundation of English constitutionalism exported to America, Australia, and India through the British Empire.",
        "causes": ["1485 Bosworth Field victory by Henry Tudor ending Wars of the Roses and establishing dynasty", "Henry VIII's 1534 break with Rome to annul Catherine of Aragon marriage creating Church of England", "Dissolution of the monasteries redistributing 25% of English land wealth to gentry and crown", "Elizabeth I's 45-year reign creating Protestant national identity through Shakespeare, Armada, and exploration"],
        "effects": ["Church of England creation established English Protestantism that shaped British identity for 400 years", "Dissolution of monasteries created Protestant landowning gentry class that supported Parliamentary power", "Elizabeth I's reign produced Shakespeare and English literary renaissance that shaped global culture", "Tudor constitutional precedents — Parliament, common law, English Bible — became English constitutionalism's foundation"],
        "relationships": [{"entity": "Henry VIII", "relationship": "MOST_TRANSFORMATIVE_MONARCH", "note": "Henry VIII's break with Rome and dissolution of monasteries were Tudor century's defining events"}, {"entity": "Elizabeth I", "relationship": "GREATEST_TUDOR", "note": "Elizabeth's 45-year reign produced Shakespeare, Armada victory, and English Protestant national identity"}, {"entity": "Thomas Cromwell", "relationship": "IMPLEMENTED_REFORMATION", "note": "Cromwell managed the dissolution of monasteries and Reformation's administrative machinery before execution"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Tudor Dynasty created the Church of England, dissolved the monasteries, produced Shakespeare, and established the Protestant English national identity — a century of transformation that shaped the British constitutional tradition exported via empire to a billion people.", "significanceCategory": "world-changing"},
    }),
    ("delhi-sultanate-afghanistan", {
        "summary": "The Delhi Sultanate (1206–1526 CE), founded by Qutb ud-Din Aibak — a Turkic slave general of the Ghurid rulers of Afghanistan — was the first major Islamic empire in South Asia, ruling the Indian subcontinent for 320 years through five successive Turkic and Afghan dynasties. The Sultanate repelled the Mongol invasions of the 13th century (when the Mongols destroyed every major civilization from Baghdad to Korea), preserving Islamic civilization in South Asia while Baghdad, Merv, and Samarkand burned. The Qutb Minar (1193-1220) in Delhi remains the world's tallest brick minaret.\n\nQutb ud-Din Aibak, a slave (mamluk) soldier who rose to become governor of northern India under Muhammad of Ghor, declared independence after his master's assassination in 1206 — founding the 'Slave Dynasty,' the first of five Delhi Sultanate dynasties. The Sultanate's most significant act was Iltutmish's successful resistance of the Mongol armies of Genghis Khan's grandsons — turning them back at the Indus River three times (1221, 1228, 1241), sparing Delhi while the Mongols destroyed Baghdad (1258) and burned Central Asia's libraries and cities.\n\nThe Delhi Sultanate brought Persian as the court language, Islamic law (sharia) courts, Afghan-Mughal architectural traditions, and Sufi orders to South Asia. Alauddin Khalji's market reforms (1303-1316) — fixing prices of grain, cloth, and cattle — represent medieval India's most ambitious economic intervention. The Sultanate was finally destroyed by Babur's Mughal invasion at the First Battle of Panipat (1526), which substituted Mughal for Afghan-Turkic rule.",
        "causes": ["1206 founding by slave general Qutb ud-Din Aibak after Ghurid master's assassination", "Successful repulsion of three Mongol invasions (1221, 1228, 1241) preserving South Asian civilization", "Persian court culture, Islamic law, and Sufi orders transforming South Asian society", "Alauddin Khalji's market reforms as medieval India's most ambitious economic intervention"],
        "effects": ["Three successful Mongol repulsions preserved Islamic civilization in South Asia while Baghdad burned", "Qutb Minar remains world's tallest brick minaret as Delhi Sultanate's greatest architectural achievement", "Persian as court language established the Indo-Persian cultural tradition inherited by Mughal Empire", "First Battle of Panipat 1526 Mughal victory ended Sultanate and began Mughal era"],
        "relationships": [{"entity": "Qutb ud-Din Aibak", "relationship": "FOUNDED_BY", "note": "Slave general Aibak founded Delhi Sultanate in 1206 after Ghurid master's assassination"}, {"entity": "Genghis Khan", "relationship": "REPELLED_INVASION_OF", "note": "Delhi Sultanate turned back three Mongol invasions that destroyed Baghdad and Central Asia"}, {"entity": "Babur", "relationship": "OVERTHROWN_BY", "note": "Babur's 1526 Panipat victory destroyed Delhi Sultanate and established Mughal Empire"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Delhi Sultanate's three repulsions of the Mongol invasions that destroyed Baghdad and Central Asia — preserving Islamic South Asian civilization during the 13th century's greatest catastrophe — was the most consequential military achievement in South Asian history.", "significanceCategory": "world-changing"},
    }),
    ("inca-empire-argentina", {
        "summary": "The Inca Empire (Tawantinsuyu — 'The Four Regions'), the largest pre-Columbian empire in the Americas, extended at its peak (1438-1533 CE) from present-day Colombia through Ecuador, Peru, Bolivia, northwest Argentina, and central Chile — a territory of approximately 2 million square kilometers governed without writing, wheels, iron, or monetary currency. The Incas governed 10-12 million people through a sophisticated system of census quipus (knotted strings encoding statistical data), mit'a labor service, food storage, and 40,000 kilometers of stone roads.\n\nThe Inca expansion began under Pachacuti (1438-1471), who transformed the Cusco valley chiefdom into a continental empire in 33 years — the fastest imperial expansion in American history. Pachacuti's architects built Machu Picchu (c. 1450) — a royal estate and astronomical observatory on a cloud-forest ridge above the Urubamba River — that now represents Inca civilization to the world. The Inca road system (Qhapaq Ñan) — carved through Andean peaks and jungle, complete with suspension bridges, relay stations, and way-markers — was the most sophisticated infrastructure in pre-Columbian America.\n\nFrancisco Pizarro's conquest (1532-1533) was history's most asymmetric victory: 168 Spanish soldiers captured Inca Emperor Atahualpa at Cajamarca, killing 7,000 Inca warriors in a few hours. Atahualpa offered to fill his prison room with gold and twice over with silver — producing 24 tons of metal — before Pizarro executed him anyway. Within 40 years, disease (smallpox) killed 90% of the Andean population, the fastest demographic catastrophe in recorded history.",
        "causes": ["Pachacuti's 1438-1471 rapid continental expansion transforming Cusco chiefdom into empire", "Mit'a labor service and food storage network enabling governance without currency or writing", "Qhapaq Ñan road system of 40,000 km enabling troop movement and communication across Andes", "1532 Cajamarca ambush by Pizarro capturing Atahualpa and destroying Inca military coordination"],
        "effects": ["24 tons of gold and silver ransom of Atahualpa triggered Spanish treasure fleets and inflation that disrupted European economies", "Smallpox killed 90% of Andean population — fastest demographic catastrophe in recorded history", "Inca road network preserved and extended as Spanish colonial infrastructure", "Machu Picchu's 20th-century rediscovery (Bingham 1911) became symbol of lost civilization romanticism"],
        "relationships": [{"entity": "Pachacuti", "relationship": "GREATEST_EMPEROR", "note": "Pachacuti expanded Cusco chiefdom into continental empire in 33 years and built Machu Picchu"}, {"entity": "Francisco Pizarro", "relationship": "CONQUERED_BY", "note": "168 Spanish soldiers at Cajamarca captured emperor and destroyed empire; followed by 90% population death"}, {"entity": "Atahualpa", "relationship": "LAST_SOVEREIGN_EMPEROR", "note": "Captured at Cajamarca; provided 24 tons of gold ransom before Pizarro's execution"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Inca Empire's conquest by 168 soldiers — the most asymmetric imperial conquest in history — and the subsequent 90% population death from disease represent the most catastrophic demographic and civilizational collapse ever recorded.", "significanceCategory": "world-changing"},
    }),
    ("sassanid-empire-iran", {
        "summary": "The Sassanid Empire (224–651 CE), founded by Ardashir I after defeating the last Parthian king, was the last great pre-Islamic Persian empire — the defining civilization of Iran for 400 years and the major rival of the Roman and Byzantine empires in the West. The Sassanids created Zoroastrian state religion, Persian court ceremony, the Shahnama literary tradition, and a bureaucratic state that became the template for the early Islamic caliphates that succeeded them. The Arab-Islamic conquest of 651 CE that ended the Sassanids transformed the conquerors as much as the conquered.\n\nArdashir I, a local Persian king who defeated the Parthian Arsacid Dynasty at the Battle of Hormozdegan (224 CE), established a centralized empire with Zoroastrianism as state religion. The Sassanid capital at Ctesiphon (near modern Baghdad) was the world's largest city for periods in the 4th-5th centuries. The Sassanids established the divinity of the Zoroastrian fire — constructing fire temples across Iran — and codified Zoroastrian scripture in the Avesta.\n\nThe Byzantine-Sassanid wars (502-628 CE), the longest interstate conflict in world history, exhausted both empires. Khosrow II briefly conquered Egypt, Syria, Palestine, and Anatolia (619-628 CE) — the greatest Persian expansion since Achaemenid times — before Heraclius reversed all gains. Both empires were so weakened that Arab-Islamic armies swept through Persian territory in 633-651, defeating the last Sassanid emperor Yazdegerd III. The Sassanid administrative tradition, court ceremony, and Persian language became the foundations of Abbasid Islamic civilization.",
        "causes": ["224 CE founding by Ardashir I defeating Parthian Arsacid Dynasty at Battle of Hormozdegan", "Zoroastrian state religion establishment creating unified Iranian identity and fire temple network", "400-year Byzantine-Sassanid wars mutual exhaustion enabling Arab-Islamic conquest of both", "Khosrow II's 619-628 CE maximum expansion recapturing Egyptian and Syrian territories"],
        "effects": ["Sassanid court ceremony, bureaucracy, and Persian language became foundations of Abbasid Islamic civilization", "Zoroastrian fire temple network created Iranian religious landscape enduring through Islamic conversion", "Byzantine-Sassanid exhaustion enabled Arab conquest of both major empires in single generation", "Shahnama literary tradition preserved Sassanid epic heritage through Ferdowsi's 1010 CE masterpiece"],
        "relationships": [{"entity": "Ardashir I", "relationship": "FOUNDED_BY", "note": "Ardashir defeated Parthians at Hormozdegan 224 CE and established Zoroastrian empire"}, {"entity": "Khosrow II", "relationship": "GREATEST_EXPANSION_UNDER", "note": "Khosrow II conquered Egypt and Syria 619-628 CE before Byzantine reversal"}, {"entity": "Yazdegerd III", "relationship": "LAST_EMPEROR", "note": "Last Sassanid emperor defeated by Arab-Islamic armies 651 CE; fled east before assassination"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Sassanid Empire created the Persian cultural tradition — court ceremony, bureaucracy, Zoroastrian faith — that the Arab-Islamic conquerors absorbed and transmitted to the Abbasid caliphate, making Sassanid Persia the cultural foundation of medieval Islamic civilization.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 82 — Class 312 Dynasties V")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
