#!/usr/bin/env python3
"""Batch 95 — Class 361 Museums III (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/361-Class-361"
FILE_PREFIX = "361"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("anne-frank-house", {
        "summary": "The Anne Frank House in Amsterdam, Netherlands, is the preserved building at Prinsengracht 263 where Anne Frank, her family, and four others hid in a concealed annexe for 761 days (July 1942 – August 1944) before being betrayed to the Gestapo — and where Anne wrote the diary that became one of the most widely read books of the 20th century, with over 35 million copies sold in 70+ languages. The diary's intimate account of hiding, fear, hope, and adolescence gave the Holocaust a specific human face that no statistical account could achieve.\n\nOtto Frank, Anne's father and the only annexe inhabitant to survive, returned to Amsterdam after liberation to find that his employee Miep Gies had preserved Anne's papers, which included her diary and loose pages. Otto compiled and published the diary in Dutch in 1947; it was translated into German (1950) and English (1952). Anne's diary became the most famous personal account of the Holocaust: her line 'I still believe, in spite of everything, that people are truly good at heart' became one of the most quoted statements of the 20th century.\n\nThe Anne Frank House museum (opened 1960) preserves the empty annexe — Anne's father decided not to restore the furniture, leaving the bare rooms as witness — with the original pencil marks on the wall recording the children's heights, the cutout movie star pictures Anne glued to her bedroom wall, and the bookcase that concealed the annexe entrance. The museum receives 1.2 million visitors annually, operates a major Holocaust education program, and has become a global symbol of the persecution of Jews and the importance of documenting ordinary lives under totalitarianism.",
        "causes": ["July 1942 Frank family entry into the Prinsengracht annexe to hide from Nazi deportation", "Anne's diary writing 761 days of hiding creating intimate Holocaust testimony", "August 1944 Gestapo betrayal and arrest ending hiding with only Otto surviving", "Miep Gies preserving Anne's papers enabling 1947 diary publication"],
        "effects": ["35 million copies in 70+ languages making Anne Frank's diary most widely read Holocaust testimony", "Museum opened 1960 preserving empty annexe as witness against Holocaust denial", "1.2 million annual visitors making it Amsterdam's most visited site", "Anne Frank's diary giving Holocaust a specific human face transforming 20th-century moral memory"],
        "relationships": [{"entity": "Anne Frank", "relationship": "MEMORIALIZES", "note": "Museum preserves annexe where Anne wrote her diary; her face became the Holocaust's most recognized"}, {"entity": "Otto Frank", "relationship": "DIARY_PUBLISHED_BY", "note": "Sole survivor; compiled and published Anne's diary starting with 1947 Dutch edition"}, {"entity": "Miep Gies", "relationship": "DIARY_PRESERVED_BY", "note": "Frank employee who hid and preserved Anne's papers enabling post-war publication"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Anne Frank House — through its preservation of a specific hiding place and a 13-year-old's diary — achieved what no aggregate Holocaust statistic could: giving the genocide a personal, intimate, and universally legible human face, making it the most morally consequential museum in the world.", "significanceCategory": "world-changing"},
    }),
    ("jewish-museum", {
        "summary": "The Jewish Museum Berlin, designed by architect Daniel Libeskind and opened in 2001, is the most architecturally and emotionally radical museum building of the 20th century — a titanium-zinc zinc-clad structure of intersecting and fragmented lines that deliberately disorients visitors, uses slanted floors, narrow windows (called 'voids'), and dead-end corridors (the Holocaust Tower, the Garden of Exile) to simulate the disorientation, isolation, and despair experienced by Jews in Nazi Germany. The building is considered the masterwork of deconstructivist architecture.\n\nLibeskind won the 1989 competition with a design titled 'Between the Lines' — two intersecting lines, one straight (German-Jewish history in continuity) and one zigzag (the broken, fragmented history of Jewish suffering). The building's plan is a distorted Star of David; windows are cut at angles derived from addresses of Berlin Jews who were murdered; the six pointed voids that cut through all floors represent the void left by destroyed Jewish life. The Holocaust Tower — a dark, bare concrete chamber lit only by a thin slit of light far above — is entered and then sealed, creating profound claustrophobia.\n\nThe permanent collection documents 2,000 years of German-Jewish history — from the Ashkenazi cultural formation to the Holocaust and its aftermath. The museum reopened in 2020 after a major renovation. The Jewish Museum Berlin's building became so famous as architecture that the institution was forced to open the building to visitors before any collection was installed — people came to experience the architecture itself. Libeskind's design influenced Holocaust memorial architecture globally.",
        "causes": ["1989 Libeskind competition win with 'Between the Lines' deconstructivist design", "2001 opening presenting 2,000 years of German-Jewish history with radical architectural language", "Holocaust Tower and void spaces creating experiential simulation of Nazi persecution's psychological reality", "Building architecture becoming so renowned it opened without collection due to visitor demand"],
        "effects": ["Deconstructivist architecture masterwork influencing Holocaust memorial and museum architecture globally", "German-Jewish history documentation covering 2,000 years including Holocaust", "Holocaust Tower experiential design becoming model for memorial museum architecture worldwide", "Building's architectural fame preceding collection making it as landmark as exhibit"],
        "relationships": [{"entity": "Daniel Libeskind", "relationship": "DESIGNED_BY", "note": "Libeskind's 'Between the Lines' design won 1989 competition; building is his deconstructivist masterwork"}, {"entity": "Holocaust", "relationship": "COMMEMORATES", "note": "Museum documents 2,000 years of German-Jewish history with Holocaust as central rupture"}, {"entity": "Deconstructivism", "relationship": "EXEMPLIFIES_ARCHITECTURAL_MOVEMENT", "note": "Jewish Museum Berlin is the defining built example of deconstructivist architecture"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Jewish Museum Berlin — through Libeskind's radical deconstructivist architecture that physically simulates persecution's disorientation — proved that a building's form could carry moral meaning as powerfully as its collection, transforming museum architecture globally.", "significanceCategory": "world-changing"},
    }),
    ("national-museum-of-history", {
        "summary": "The National Museum of History of China in Beijing (Zhongguo Guojia Bowuguan), reopened in its current form in 2011 after a massive renovation and expansion, is the largest history museum in the world by exhibition area (approximately 200,000 square meters) and holds over 1.4 million artifacts documenting 5,000 years of Chinese civilization — including the Simuwu Rectangular Ding (the world's largest bronze vessel, c. 1300 BCE), the Houmuwu Ding, and extraordinary collections from every dynasty from Shang through Qing. The museum occupies the eastern side of Tiananmen Square, directly facing the Great Hall of the People.\n\nThe museum's location on Tiananmen Square (opposite the Great Hall of the People, flanking the Monument to the People's Heroes) is politically deliberate: it frames Chinese Communist Party governance within the narrative of 5,000 years of continuous Chinese civilization. The museum merged two previous institutions — the Museum of Chinese History and the Museum of the Chinese Revolution (1949-) — in 2003, combining dynastic history with CCP revolutionary history in a single national narrative.\n\nThe Simuwu Rectangular Ding (also called Houmuwu Ding) — a massive bronze ritual vessel cast c. 1300 BCE during the Shang dynasty, weighing 832.84 kg and measuring 133 cm tall — is the world's largest known ancient bronze casting and the museum's most important artifact. It was discovered by farmers in 1939, hidden from Japanese occupiers during WWII, and acquired by the National Museum. Annual attendance exceeds 7 million, making it among the world's most visited museums.",
        "causes": ["5,000 years of Chinese civilization artifact collection from every major dynasty", "2011 reopening after major renovation creating world's largest history museum by area", "Tiananmen Square location linking 5,000-year history with CCP revolutionary narrative", "Simuwu Ding (c. 1300 BCE, 832 kg) as world's largest ancient bronze vessel centerpiece"],
        "effects": ["World's largest history museum (200,000 sqm) with 1.4 million artifacts", "7 million+ annual visitors making it one of world's most visited museums", "National narrative linking 5,000 years of Chinese dynastic history with CCP governance", "Simuwu Ding as supreme artifact establishing museum as global bronze age repository"],
        "relationships": [{"entity": "Simuwu Rectangular Ding", "relationship": "HOUSES_MASTERPIECE", "note": "c. 1300 BCE bronze vessel (832 kg) is world's largest ancient bronze casting"}, {"entity": "Tiananmen Square", "relationship": "LOCATED_ON", "note": "Eastern side of Tiananmen Square, flanking CCP political center in symbolic pairing"}, {"entity": "Chinese Communist Party", "relationship": "NATIONAL_NARRATIVE_SHAPED_BY", "note": "Museum merges dynastic history with CCP revolutionary history in unified national story"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The National Museum of History of China — world's largest history museum, on Tiananmen Square, holding 1.4 million artifacts from 5,000 years — is the most politically and culturally loaded national history institution on Earth, deliberately framing the CCP's 75-year rule within the narrative of one of humanity's oldest continuous civilizations.", "significanceCategory": "world-changing"},
    }),
    ("hiroshima-peace-memorial-museum", {
        "summary": "The Hiroshima Peace Memorial Museum, opened 1955 in Hiroshima, Japan, adjacent to the Hiroshima Peace Memorial (Genbaku Dome — the only surviving structure near the bomb's hypocenter, preserved at 160 meters from ground zero), documents the August 6, 1945 atomic bombing that killed 70,000-80,000 people instantly and 90,000-140,000 within four months — the first use of nuclear weapons in war — through survivor testimony, personal artifacts, and graphic documentation that made it the global center of nuclear abolition advocacy. The museum's visitors include every US President who has visited Japan.\n\nThe atomic bomb 'Little Boy' (uranium gun-type device, 15 kiloton yield) exploded 580 meters above Hiroshima at 8:15 AM on August 6, 1945. The hypocenter was 160 meters southeast of the Genbaku Dome (Hiroshima Prefectural Industrial Promotion Hall). The dome's iron skeleton survived because the blast was almost directly overhead; it was preserved as a memorial and designated UNESCO World Heritage Site in 1996. The museum's founding in 1955 was an act of deliberate memory against nuclear forgetting.\n\nThe museum's exhibits include a child's destroyed tricycle, a shadow burned into stone steps (where a human body vaporized, leaving only a shadow), watch faces stopped at 8:15, and vivid survivor (hibakusha) testimonies. President Obama became the first sitting US president to visit in May 2016 — a visit watched worldwide, though he did not apologize for the bombing. Over 1.7 million visitors annually include school groups from across Japan as part of mandatory peace education.",
        "causes": ["August 6 1945 atomic bombing killing 70,000-80,000 instantly as first nuclear weapon use in war", "1955 museum opening as deliberate act of preservation against nuclear weapon normalization", "Genbaku Dome preservation 160 meters from hypocenter as UNESCO World Heritage Site", "Obama 2016 visit as first sitting US president to Hiroshima creating global media moment"],
        "effects": ["Global center of nuclear abolition advocacy through 70+ years of survivor testimony", "1.7 million annual visitors including mandatory Japanese school peace education programs", "UNESCO World Heritage status (1996) making Genbaku Dome globally protected peace symbol", "Shadow burned in stone and stopped watches becoming nuclear horror's defining visual symbols"],
        "relationships": [{"entity": "Atomic Bombing of Hiroshima", "relationship": "DOCUMENTS", "note": "Museum documents August 6, 1945 bombing that killed 70,000-140,000 people"}, {"entity": "Genbaku Dome", "relationship": "ADJACENT_TO", "note": "Dome 160 meters from hypocenter is UNESCO World Heritage Site and museum's physical symbol"}, {"entity": "Barack Obama", "relationship": "VISITED_BY", "note": "2016 Obama visit as first sitting US president created global attention without apology"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Hiroshima Peace Memorial Museum — preserving the human reality of the first nuclear weapon use in war through survivor artifacts and testimony — has been the world's most powerful argument for nuclear abolition for 70 years, making it the museum whose collection could most directly save human lives if heeded.", "significanceCategory": "world-changing"},
    }),
    ("nagasaki-atomic-bomb-museum", {
        "summary": "The Nagasaki Atomic Bomb Museum, opened 1996 in Nagasaki, Japan (replacing a smaller exhibition hall), documents the August 9, 1945 plutonium implosion bomb 'Fat Man' (21 kiloton yield) that killed 35,000-40,000 people instantly and 60,000-80,000 total in a city that was not the primary target that day (Kokura was, but cloud cover redirected the mission to Nagasaki) — making it a memorial to both the second nuclear attack and the contingency by which a city became the world's last nuclear victim. The museum complements Hiroshima's Peace Memorial Museum in Japan's nuclear testimony.\n\n'Fat Man' exploded at 11:02 AM on August 9, 1945, 503 meters above Nagasaki's Urakami district — 2.5 km north of the intended aim point due to cloud cover. The hypocenter was the Urakami Cathedral district, home to Nagasaki's large Catholic community: the cathedral (rebuilt 1925) was destroyed. Nagasaki had been Japan's only open port for European trade from 1641-1853 (Dutch East India Company trading post on Dejima island) — the bombing destroyed a city with the longest continuous Western contact history in Japan.\n\nThe Nagasaki museum's exhibits include a melted rosary (fused by the bomb's heat), the reconstructed iron cross from Urakami Cathedral, deformed bottles and tiles, and the famous photograph of the 'Nagasaki boy' (Tanimoto's photograph of a standing boy cremating his younger brother in post-bomb Nagasaki) that became iconic. The museum opened in 1996 — 51 years after the bombing — as part of Japan's commitment to nuclear testimony ahead of the NPT Review Conference.",
        "causes": ["August 9 1945 Fat Man bombing killing 35,000-80,000 as world's last nuclear attack", "Cloud cover over primary target Kokura redirecting attack to Nagasaki by contingency", "Urakami Catholic community concentration making Christian minority the bombing's main victims", "1996 museum opening 51 years later as NPT Review Conference nuclear testimony"],
        "effects": ["World's last nuclear attack site becoming global symbol of nuclear abolition alongside Hiroshima", "Melted rosary and Urakami Cathedral cross as iconic artifacts of Christian minority's fate", "Nagasaki as contingency victim demonstrating nuclear targeting's arbitrary mortal consequences", "Japanese nuclear testimony tradition (hibakusha survivor testimony) complementing Hiroshima's record"],
        "relationships": [{"entity": "Atomic Bombing of Nagasaki", "relationship": "DOCUMENTS", "note": "Museum documents August 9, 1945 bombing that killed 35,000-80,000 people"}, {"entity": "Urakami Cathedral", "relationship": "BOMBED_SITE_ADJACENT", "note": "Cathedral destroyed at hypocenter; reconstructed iron cross in museum as Christian community symbol"}, {"entity": "Hiroshima Peace Memorial Museum", "relationship": "PARTNER_NUCLEAR_TESTIMONY", "note": "Nagasaki museum complements Hiroshima's in Japan's comprehensive nuclear bombing testimony tradition"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Nagasaki Atomic Bomb Museum documents not only the second nuclear attack but its contingency — the cloud cover over Kokura that redirected the mission — making it a memorial to how random targeting decisions killed a city of Catholic Christians who had maintained Japan's longest Western contact, a confluence of ironies unique in military history.", "significanceCategory": "world-changing"},
    }),
    ("auschwitz", {
        "summary": "The Auschwitz-Birkenau State Museum in Oświęcim, Poland, established 1947 in the preserved buildings of the Nazi German concentration and extermination camp complex where approximately 1.1 million people (90% Jewish) were murdered between 1940-1945, is the largest site of mass murder in human history and the world's most important Holocaust memorial — visited by 2.3 million people annually, designated UNESCO World Heritage Site in 1979, and the physical location where 'Auschwitz' became synonymous with the Holocaust itself. The name 'Auschwitz' has become the defining noun of absolute evil in the 20th century.\n\nAuschwitz I (the main camp, opened 1940) was originally built as a Polish political prisoner camp; Auschwitz II-Birkenau (1942) was the largest extermination center, with four gas chamber-crematoria complexes capable of killing 6,000 people per day. 'Selection' on the Birkenau railway ramp (where arriving deportees were separated into those to be killed immediately and those for forced labor) was performed by SS doctors including Josef Mengele. The Zyklon B gas chambers, the massive prisoner barracks, the Appellplatz, the Wall of Death, and the crematoria remains are preserved.\n\nThe museum's exhibits include 3,800 kg of human hair (shorn from victims), 110,000 shoes, 12,000 pots and pans, and hundreds of thousands of personal items — the systematic collection of valuables, hair, teeth, and clothing was part of the Nazi industrial murder process. The liberation by Soviet troops (January 27, 1945) is commemorated annually as International Holocaust Remembrance Day. Pope John Paul II, the Dalai Lama, and every major world leader have visited; Israeli school groups make pilgrimage as part of the March of the Living.",
        "causes": ["1940-1945 Nazi operation of largest concentration and extermination camp complex", "Systematic murder of 1.1 million people (90% Jewish) using industrial gas chambers", "1947 Polish state decision to preserve and memorialize the site immediately after liberation", "1979 UNESCO World Heritage designation recognizing global significance of preserved horror"],
        "effects": ["2.3 million annual visitors making it world's most visited Holocaust memorial", "Name 'Auschwitz' becoming global synonymous with the Holocaust and absolute evil", "International Holocaust Remembrance Day (January 27) commemorating Soviet liberation date", "3,800 kg preserved human hair and 110,000 shoes as most visceral industrial genocide evidence"],
        "relationships": [{"entity": "Holocaust", "relationship": "PRIMARY_SITE_OF", "note": "1.1 million murdered at Auschwitz-Birkenau; site became synonymous with Holocaust itself"}, {"entity": "Nazi Germany", "relationship": "OPERATED_BY", "note": "Nazi SS operated Auschwitz 1940-1945; Mengele performed selections at Birkenau ramp"}, {"entity": "Soviet Union", "relationship": "LIBERATED_BY", "note": "Soviet troops liberated Auschwitz January 27, 1945; date now International Holocaust Remembrance Day"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "Auschwitz-Birkenau is the defining site of 20th-century human evil — where the murder of 1.1 million people was industrialized, and where the Nazi regime's genocidal project is most viscerally preserved: 3,800 kg of human hair and 110,000 shoes that no statistical summary can replace.", "significanceCategory": "world-changing"},
    }),
    ("imperial-war-museum-london", {
        "summary": "The Imperial War Museum (IWM) in London, founded 1917 during World War I by Sir Alfred Mond to record and exhibit material related to British and Imperial military operations — initially conceived as a record of WWI but expanded to cover all conflicts involving Britain from 1914 to the present — is now a network of five museums and the UK's primary institution for documenting the human experience of war. The London branch occupies the former Bethlem Royal Hospital (Bedlam) — the world's most famous psychiatric institution — giving the museum a building with its own harrowing history.\n\nThe IWM was founded in 1917, unprecedented — a museum established during an ongoing conflict to document it in real time, including from all perspectives (military, civilian, enemy). The collection now exceeds 23 million items: 20 million documents and photographs, 33,000 art works (including the largest collection of WWI art anywhere), and major holdings of film and sound archives. Paul Nash's 'We Are Making a New World' and Christopher Nevinson's 'Paths of Glory' — key images of WWI's industrial horror — are at IWM.\n\nThe IWM's Holocaust Exhibition (2000) is considered the best Holocaust exhibition outside of Israel, using personal testimony to document the progression from discrimination through deportation to extermination. The Visitors' atrium now displays a V-2 rocket, a Spitfire, and the Enigma machine. IWM Duxford (Cambridgeshire) is Europe's premier aviation museum; HMS Belfast (moored on the Thames) documents WWII naval warfare. The IWM's 'Lives of the First World War' digital memorial catalogued 8 million WWI service records.",
        "causes": ["1917 WWI founding by Mond as real-time conflict documentation unprecedented in museum history", "23 million item collection covering all British conflicts from 1914 to present", "Holocaust Exhibition 2000 establishing best Holocaust display outside Israel", "Former Bethlem Royal Hospital building combining war and psychiatric history in single location"],
        "effects": ["23 million item collection as UK's comprehensive war experience documentation", "Lives of the First World War digital memorial cataloguing 8 million WWI service records", "Holocaust Exhibition model influencing Holocaust memorial museum design globally", "Five-museum IWM network making war experience documentation accessible across UK"],
        "relationships": [{"entity": "World War I", "relationship": "FOUNDED_TO_DOCUMENT", "note": "IWM founded 1917 during WWI to document conflict in real time — unprecedented museum founding during ongoing war"}, {"entity": "Alfred Mond", "relationship": "FOUNDED_BY", "note": "Mond's 1917 initiative created IWM as real-time conflict documentation institution"}, {"entity": "Holocaust Exhibition", "relationship": "CONTAINS", "note": "IWM's 2000 Holocaust Exhibition considered best outside Israel; uses personal testimony"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Imperial War Museum — founded during WWI itself, housing 23 million items including the largest WWI art collection, and containing the best Holocaust exhibition outside Israel — is the world's most comprehensive institution for documenting the human experience of modern war.", "significanceCategory": "world-changing"},
    }),
    ("national-war-museum", {
        "summary": "The National War Museum of Scotland at Edinburgh Castle, established in its current form in 1933 within the castle's former gunpowder magazine and hospital buildings (now converted), documents Scotland's military history from the 17th century to the present — covering Highland regiments, Jacobite conflicts, the Napoleonic Wars, the World Wars, and Scottish soldiers' global service in the British Empire. Edinburgh Castle is Scotland's most visited tourist destination (2.2 million annual visitors), making the museum Scotland's most prominent military heritage institution.\n\nThe museum building — converted from the Crown Square gunpowder magazine (built 1753-1757) and the barracks hospital — is embedded within Edinburgh Castle's medieval fortification complex, giving the museum an atmospheric setting. The collection includes regimental colors, Highland dress, equipment from Scotland's major battles (Culloden 1746, Waterloo 1815), Victoria Crosses won by Scottish soldiers, and extraordinary personal items. A display case features a cast of Private Peter Edwards's facial prosthetic from WWI (facial reconstruction surgery was pioneered partly for Scottish soldiers).\n\nThe museum's coverage of Highland regiments — the Black Watch, Argyll and Sutherland Highlanders, Gordon Highlanders — documents the transformation of the Highland clans from Jacobite rebels (1745) into the British Empire's most celebrated soldiers within a generation, a remarkable cultural reversal. The Jacobite room documents the 1745 Rising and Culloden — the military defeat that ended the Highland clan system. The museum is free (included with Edinburgh Castle admission).",
        "causes": ["1933 conversion of castle gunpowder magazine and hospital into dedicated Scottish military museum", "Edinburgh Castle's strategic position housing Scotland's national military collection since medieval period", "Highland regiment transformation from Jacobite rebels to British Empire soldiers documenting cultural reversal", "WWI facial reconstruction display preserving evidence of pioneering medical innovation"],
        "effects": ["Scotland's most prominent military heritage institution within 2.2 million annual visitor Edinburgh Castle", "Highland regiment documentation preserving Jacobite-to-Empire military transformation record", "Victoria Cross collection honoring Scottish soldiers' contributions to British military history", "WWI facial prosthetic display as exceptional evidence of pioneering reconstructive surgery"],
        "relationships": [{"entity": "Edinburgh Castle", "relationship": "LOCATED_WITHIN", "note": "Museum embedded in Edinburgh Castle's 17th-century gunpowder magazine within medieval fortress"}, {"entity": "Black Watch Regiment", "relationship": "REGIMENTAL_COLLECTION_INCLUDES", "note": "Black Watch and Highland regiments are central collection subjects documenting Scotland's imperial military service"}, {"entity": "Battle of Culloden", "relationship": "DOCUMENTS", "note": "1746 Culloden defeat ending Highland clan system is pivotal museum narrative turning point"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The National War Museum of Scotland — documenting the transformation of Jacobite Highland rebels into the British Empire's most decorated soldiers within a generation — captures one of history's most dramatic cultural reversals: a defeated warrior people becoming the conquerors' most prized military instrument.", "significanceCategory": "regional"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 95 — Class 361 Museums III")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
