#!/usr/bin/env python3
"""Batch 83 — Class 361 Museums II (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/361-Class-361"
FILE_PREFIX = "361"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("smithsonian-institution", {
        "summary": "The Smithsonian Institution, founded in 1846 through a bequest of £104,960 from British scientist James Smithson (who never visited America) to create 'an establishment for the increase and diffusion of knowledge,' is the world's largest museum complex — encompassing 19 museums, 21 libraries, 9 research centers, and over 154 million artifacts and specimens. The Smithsonian's free-admission National Mall museums in Washington D.C. receive 22 million visitors annually, making it the most visited museum complex on earth.\n\nJames Smithson, an illegitimate son of the Duke of Northumberland who achieved scientific distinction without social recognition, bequeathed his estate to a country he had never visited — apparently motivated by a desire to spite the English aristocracy that had excluded him. The 1836 bequest and the 8-year American congressional debate about accepting it (many saw it as inappropriate for a republic to accept money from a foreign aristocrat) eventually created the 'National Attic' of American civilization under first Secretary Joseph Henry.\n\nThe Smithsonian's collections span from the Hope Diamond (at the Natural History Museum) and the Wright Brothers' 1903 Flyer (at Air and Space) to the original Star-Spangled Banner flag and the first McDonald's french fry machine. The Institution runs the world's largest biological specimen collection (145 million), publishes the Smithsonian Magazine (3 million subscribers), and operates research stations from the Amazon to the Arctic. The Smithsonian's free admission policy — funded by the federal government — embodies a democratic commitment to public education unique among world-class museums.",
        "causes": ["1836 bequest of £104,960 by James Smithson to 'increase and diffuse knowledge' in America", "1846 congressional acceptance after 8-year debate creating Institution under Joseph Henry", "Congressional appropriations enabling free admission to all 19 museums on National Mall", "Growth through acquisition and donation into world's largest museum complex"],
        "effects": ["22 million annual visitors to free National Mall museums democratizing access to world's cultural heritage", "154 million artifacts creating world's largest museum collection", "Free admission policy became model for democratic public education through museums", "Smithsonian Magazine reaching 3 million subscribers extended institutional knowledge mission"],
        "relationships": [{"entity": "James Smithson", "relationship": "ENDOWED_BY", "note": "Smithson's 1836 bequest of £104,960 created Institution he never visited"}, {"entity": "Joseph Henry", "relationship": "FIRST_SECRETARY", "note": "Henry shaped Smithsonian's first decades prioritizing scientific research over museum collecting"}, {"entity": "United States Congress", "relationship": "GOVERNED_BY", "note": "Congressional appropriations fund free admission and operations; Institution is trust instrumentality"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Smithsonian's free admission policy — serving 22 million visitors annually at the world's largest museum complex — represents the most successful democratic model of publicly funded cultural education in world history.", "significanceCategory": "world-changing"},
    }),
    ("natural-history-museum", {
        "summary": "The Natural History Museum in London, opened in 1881 in Alfred Waterhouse's Romanesque-Gothic cathedral of science in South Kensington, holds over 80 million specimens — the largest natural history collection in the world — accumulated through 400 years of British imperial scientific expeditions. The museum's collections include specimens gathered by Darwin on the Beagle voyage (1831-1836), type specimens defining over 30,000 species (including the holotype of Homo neanderthalensis), and the most comprehensive collection of meteorites outside the United States.\n\nThe museum's origins lie in Hans Sloane's private collection (71,000 objects) purchased by Parliament in 1753 to form the British Museum. Darwin's Beagle specimens, collected 1831-1836, were deposited here — including the Galápagos finches that inspired natural selection theory. The museum's Victorian cathedral-science architecture deliberately echoed medieval cathedrals to position science as humanity's new religion. The central hall's 25-meter diplodocus skeleton (nicknamed Dippy) became the 20th century's most famous museum exhibit.\n\nThe NHM's DNA Bank and Frozen Ark program — preserving genetic material from thousands of species — has become critical biodiversity infrastructure as extinction rates accelerate. The museum's citizen science programs engage 400,000 volunteers in monitoring species across Britain. The 2017 replacement of Dippy the diplodocus with a blue whale skeleton (Hope) signaled a deliberate refocus from past wonder to present ecological crisis — one of the most powerful symbolic acts of any museum.",
        "causes": ["1753 foundation from Hans Sloane's 71,000-object collection purchased by Parliament", "Darwin's Beagle specimens including Galápagos finches deposited after 1836 voyage", "Alfred Waterhouse's 1881 Romanesque-Gothic building positioning science as secular cathedral", "British imperial expeditions accumulating 80 million specimens from global natural history"],
        "effects": ["80 million specimens create world's largest natural history collection supporting global scientific research", "30,000+ type specimens defining species across all major taxonomic groups", "DNA Bank and Frozen Ark preserving genetic material from thousands of species facing extinction", "Blue whale skeleton replacing Dippy (2017) reoriented museum from past wonder to ecological crisis messaging"],
        "relationships": [{"entity": "Charles Darwin", "relationship": "COLLECTIONS_FROM", "note": "Darwin's Beagle specimens including Galápagos finches are among museum's most scientifically significant holdings"}, {"entity": "Hans Sloane", "relationship": "FOUNDED_FROM_COLLECTION_OF", "note": "Sloane's 71,000-object collection purchased by Parliament in 1753 formed British Museum nucleus"}, {"entity": "Alfred Waterhouse", "relationship": "DESIGNED_BY", "note": "Waterhouse's 1881 Romanesque-Gothic building is Victorian science architecture's masterpiece"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Natural History Museum's 80 million specimens — accumulated through centuries of British scientific expeditions — constitute the world's most comprehensive natural history archive, providing the type specimens and reference collections against which all biological knowledge is measured.", "significanceCategory": "world-changing"},
    }),
    ("palace-museum", {
        "summary": "The Palace Museum (故宫博物院, Gùgōng Bówùyuàn), established in 1925 within the Forbidden City of Beijing after the expulsion of the last Qing emperor Puyi, is the world's most visited museum (14.5 million visitors in 2018) and the guardian of over 1.86 million cultural relics representing the accumulated treasures of Chinese imperial civilization across five dynasties spanning 600 years. The Forbidden City itself — 980 buildings covering 720,000 square meters — is the world's largest palace complex and the best-preserved medieval imperial palace anywhere.\n\nThe Forbidden City was constructed between 1406-1420 by the Yongle Emperor of the Ming Dynasty, using 1 million workers and 100,000 artisans, with timber from Yunnan and stone from Beijing quarries. The complex served as the home and administrative center of 24 emperors — 14 Ming (1420-1644) and 10 Qing (1644-1912) — over 492 years. Its name 'Forbidden City' reflected the prohibition on ordinary citizens entering without imperial permission.\n\nIn 1933, as Japanese forces threatened Beijing, 13,427 crates of Palace Museum artifacts (approximately 600,000 objects) were secretly transported south to Shanghai, then to caves in Sichuan province, surviving the entire Sino-Japanese War (1937-1945) and Civil War. After 1949, the Nationalist government transported 2,972 crates to Taiwan (now the National Palace Museum, Taipei). The Beijing collection retains 1.86 million objects; Taipei holds 700,000. Both claim to be the 'real' Palace Museum — the same institutional, cultural, and political division that defines the China-Taiwan relationship.",
        "causes": ["1406-1420 construction by Yongle Emperor using 1 million workers as imperial palace for Ming-Qing dynasties", "1925 establishment as public museum after expulsion of last Qing emperor Puyi", "1933 secret evacuation of 13,427 crates to protect artifacts from Japanese invasion", "1949 split: Nationalist government transported 2,972 crates to Taiwan creating two Palace Museums"],
        "effects": ["1.86 million cultural relics in Beijing plus 700,000 in Taipei represent greatest repository of Chinese imperial art", "14.5 million annual visitors making Palace Museum world's most visited museum", "Beijing-Taipei institutional split mirrors and symbolizes the China-Taiwan political division", "Forbidden City's preservation as UNESCO World Heritage Site protects world's largest palace complex"],
        "relationships": [{"entity": "Yongle Emperor", "relationship": "CONSTRUCTION_ORDERED_BY", "note": "Yongle ordered Forbidden City construction 1406-1420 using 1 million workers"}, {"entity": "Puyi", "relationship": "EXPELLED_FROM", "note": "Last Qing emperor expelled from Forbidden City in 1924, enabling museum establishment in 1925"}, {"entity": "National Palace Museum Taipei", "relationship": "SPLIT_COLLECTION_WITH", "note": "1949 Nationalist evacuation of 2,972 crates to Taiwan created parallel institution holding 700,000 objects"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Palace Museum's 1.86 million imperial relics — the accumulated treasury of Chinese civilization across 600 years — and its 14.5 million annual visitors make it the world's most visited repository of a single civilization's cultural heritage.", "significanceCategory": "world-changing"},
    }),
    ("field-museum-of-natural-history", {
        "summary": "The Field Museum of Natural History in Chicago, opened in 1893 from the collections assembled for the World's Columbian Exposition, holds 40 million specimens across natural history, anthropology, and zoology — including Sue, the most complete and largest Tyrannosaurus rex skeleton ever found. The Field Museum's DNA lab sequences new species at rates exceeding any comparable institution, and its ethnographic collections from 140 countries document disappearing cultures with scholarly comprehensiveness.\n\nThe Field Museum was established with a gift from Marshall Field (of Marshall Field & Company department stores) to preserve natural history specimens from the 1893 World's Columbian Exposition in Chicago's Jackson Park. Its current building in Grant Park (1921) was designed by Daniel Burnham, Chicago's great urban planner. The museum's early anthropological expeditions — in the era before professional ethics standards — assembled comprehensive collections from Native American, Pacific Island, and African cultures that are now subject to repatriation debates.\n\nSue, the Tyrannosaurus rex skeleton discovered in South Dakota in 1990, was sold at auction for $8.36 million (at the time the most expensive fossil ever) to the Field Museum with support from McDonald's, Walt Disney World, and the California State University system. Sue's mounting in the Field's main hall (1997) — revealing a robust, heavily-built predator with excellent binocular vision — reshaped paleontological understanding of T. rex biology. Sue has been visited by over 30 million people, making her the world's most-seen dinosaur.",
        "causes": ["1893 World's Columbian Exposition creating specimen collections that became museum foundation", "Marshall Field's gift enabling preservation and expansion of exposition natural history collections", "Daniel Burnham's 1921 Grant Park building providing magnificent permanent home", "Sue T. rex 1990 discovery and 1997 mounting becoming world's most visited dinosaur skeleton"],
        "effects": ["40 million specimens creating one of world's largest natural history repositories", "Sue T. rex reshaping paleontological understanding of Tyrannosaurus biology", "DNA lab sequencing new species at rates establishing Field as molecular taxonomy leader", "Repatriation negotiations over ethnographic collections creating model for colonial-era museum ethics reform"],
        "relationships": [{"entity": "Marshall Field", "relationship": "FUNDED_BY", "note": "Field's founding gift from department store magnate preserved 1893 Exposition collections"}, {"entity": "Sue (T. rex)", "relationship": "HOLDS", "note": "Most complete T. rex ever found; acquired for $8.36 million and visited by 30 million"}, {"entity": "Daniel Burnham", "relationship": "BUILDING_DESIGNED_BY", "note": "Chicago urban planner designed 1921 Grant Park building in neoclassical style"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Field Museum's Sue — the most complete T. rex skeleton and the most visited dinosaur specimen — reshaped scientific understanding of Tyrannosaurus while serving as the public face of paleontology for 30 million visitors.", "significanceCategory": "continental"},
    }),
    ("national-museum-of-anthropology", {
        "summary": "The National Museum of Anthropology (Museo Nacional de Antropología) in Mexico City, opened in 1964 in Pedro Ramírez Vázquez's architectural masterpiece in Chapultepec Park, is the Western Hemisphere's greatest pre-Columbian museum — holding the world's most comprehensive collection of Mesoamerican artifacts, including the Aztec Sun Stone (incorrectly called the Aztec Calendar), the Jade Mask of Pakal, and over 600,000 archaeological objects spanning 11,000 years of Mexican civilization. The museum's political purpose — celebrating Mexico's indigenous heritage as the foundation of national identity — was as deliberate as its architectural magnificence.\n\nPresident López Mateos commissioned the museum as a statement of national identity: Mexico is not a European colonial extension but an indigenous civilization that absorbed and transformed Spanish conquest. Pedro Ramírez Vázquez's building, centered on a massive umbrella-canopy fountain sustained by a single pillar (the 'Umbrella of Tláloc'), creates a ceremonial sequence from Mesoamerican outdoor plazas to interior galleries. The first room presents early Mexican hominid fossils to assert pre-European American habitation.\n\nThe Aztec Sun Stone (1427 CE), weighing 24 tons and discovered beneath Mexico City's main plaza in 1790, is the museum's central artifact — a solar calendar and ritual object that has become the symbol of Mexican national identity. The Jade Mask of Pakal (683 CE), from Palenque's royal tomb, represents Maya artistic achievement. The museum's 12 permanent rooms present 11,000 years of civilization — from Paleolithic hunters to Aztec empire — arguing for Mexico's indigenous roots as the true foundation of national character.",
        "causes": ["1964 opening commissioned by President López Mateos as political statement of indigenous national identity", "Pedro Ramírez Vázquez's architectural design creating ceremonial sequence from plaza to galleries", "Aztec Sun Stone discovery in 1790 under Mexico City plaza becoming national symbol", "Government policy asserting Mexican national identity as indigenous civilizational heritage"],
        "effects": ["Museum's political mission successfully established indigenous heritage as Mexican national identity foundation", "600,000+ artifacts created Western Hemisphere's most comprehensive pre-Columbian collection", "Aztec Sun Stone became symbol of Mexican identity recognized globally", "Architectural model influenced museum design across Latin America and postcolonial world"],
        "relationships": [{"entity": "Adolfo López Mateos", "relationship": "COMMISSIONED_BY", "note": "President López Mateos commissioned museum as deliberate political statement of indigenous national identity"}, {"entity": "Pedro Ramírez Vázquez", "relationship": "DESIGNED_BY", "note": "Ramírez Vázquez's umbrella-canopy building is Mexico's most celebrated modern institutional architecture"}, {"entity": "Aztec Sun Stone", "relationship": "HOUSES", "note": "24-ton solar calendar discovered 1790 is museum's central artifact and Mexican national symbol"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Mexico's National Museum of Anthropology — deliberately designed to argue that Mexican national identity is rooted in indigenous Mesoamerican civilization rather than Spanish colonialism — became the most politically consequential museum building in the Western Hemisphere.", "significanceCategory": "world-changing"},
    }),
    ("natural-history-museum-vienna", {
        "summary": "The Natural History Museum Vienna (Naturhistorisches Museum Wien), opened in 1889 in Gottfried Semper's twin-towered Renaissance palace on Maria-Theresien-Platz, is one of the world's oldest and most scientifically significant natural history museums — holding 30 million objects including the Venus of Willendorf (24,000 BCE), the Hallstatt-Dachstein archaeological collection defining European Iron Age cultures, and one of the world's five largest meteorite collections. The museum's Habsburg imperial collections represent the cumulative scientific acquisitions of Europe's most acquisitive dynasty.\n\nThe Habsburgs began assembling natural history specimens in the 16th century under Rudolf II, who employed alchemists, astronomers, and naturalists at his Prague court. Maria Theresia organized the imperial collections and established the court Naturalienkabinett in 1748. The collections expanded through the voyages of the Novara (1857-1859), Austria's only circumnavigation expedition, and 400 years of imperial acquisitions from around the world.\n\nThe Venus of Willendorf — an 11 cm limestone figurine of a female form, carved approximately 25,000 BCE, discovered near Willendorf, Austria in 1908 — is one of the oldest known works of representational art and the most celebrated prehistoric sculpture in the world. Its exaggerated female features have made it central to feminist art history and human evolutionary debates. The museum's meteorite collection includes specimens from the Moon and Mars, and a fragment of the Tissint meteorite (the most recently fallen Martian meteorite) collected in 2011.",
        "causes": ["Habsburg imperial collections assembled from 16th century under Rudolf II through Maria Theresia", "Gottfried Semper's 1889 twin-tower Renaissance palace creating paired museum complex with Kunsthistorisches", "Novara circumnavigation 1857-1859 adding specimens from global voyage", "Venus of Willendorf 1908 discovery making museum home to world's most famous prehistoric sculpture"],
        "effects": ["30 million objects representing one of world's most comprehensive natural history collections", "Venus of Willendorf became world's most famous prehistoric art object and feminist cultural symbol", "Hallstatt collection defined 'Hallstatt Culture' as Iron Age European archaeological standard", "Meteorite collection including Moon and Mars specimens supporting planetary science research"],
        "relationships": [{"entity": "Maria Theresia", "relationship": "COLLECTION_ORGANIZED_BY", "note": "Empress organized imperial natural history collections and established 1748 Naturalienkabinett"}, {"entity": "Gottfried Semper", "relationship": "DESIGNED_BY", "note": "Semper's twin Renaissance palaces created paired Natural History and Art History museums"}, {"entity": "Venus of Willendorf", "relationship": "HOUSES", "note": "25,000 BCE limestone figurine discovered 1908; world's most famous prehistoric sculpture"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Natural History Museum Vienna's Venus of Willendorf — a 25,000-year-old figurine discovered in 1908 — became the most celebrated prehistoric art object in the world, transforming understanding of Paleolithic human creativity and sexual symbolism.", "significanceCategory": "continental"},
    }),
    ("natural-history-museum-of-los-angeles-county", {
        "summary": "The Natural History Museum of Los Angeles County (NHM), established in 1913 as the Museum of History, Science, and Art, is the largest natural history museum in the western United States — holding 35 million specimens including the world's largest collection of Ice Age megafauna from the La Brea Tar Pits, one of North America's most important dinosaur collections, and comprehensive Native California ethnographic collections. The museum's Urban Nature project transformed the surrounding campus into a biodiversity research site, discovering 30 new species within Los Angeles city limits.\n\nThe La Brea Tar Pits, in the heart of Los Angeles' Hancock Park district adjacent to the museum, are the world's richest Ice Age fossil site — with 3.5 million bones from over 600 species preserved in natural asphalt seeps over 50,000 years. The collections include complete skeletons of saber-toothed cats (Smilodon), dire wolves, Colombian mammoths, and ground sloths from the Pleistocene era. The tar pits were being actively excavated as recently as 2023 in conjunction with the Los Angeles Metro Purple Line extension.\n\nThe museum's Urban Nature project (2013-) documented 30 new species within Los Angeles city limits — including four new bee species, six new millipedes, and the urban coyote population — demonstrating that megacities contain undiscovered biodiversity. The project's data showed Los Angeles's urban canyon system (irrigated lawns, drainage channels, street trees) creates habitat for over 2,000 species, challenging assumptions about urban ecological sterility.",
        "causes": ["1913 establishment as Museum of History, Science, and Art serving Los Angeles cultural aspirations", "La Brea Tar Pits proximity providing world's richest Ice Age fossil excavation site", "35 million specimen collection built through 100 years of regional and global field work", "Urban Nature project 2013 discovering 30 new species within Los Angeles city limits"],
        "effects": ["La Brea collection providing most complete Ice Age megafauna record in North America", "Urban Nature project demonstrating urban biodiversity exceeding prior scientific assumptions", "Smilodon and dire wolf specimens defining Ice Age California ecosystem understanding", "New species discoveries in urban LA challenging assumptions about city ecological sterility"],
        "relationships": [{"entity": "La Brea Tar Pits", "relationship": "ADJACENT_TO", "note": "World's richest Ice Age fossil site adjacent to museum; 3.5 million bones preserved in asphalt"}, {"entity": "Smilodon", "relationship": "MAJOR_COLLECTION_OF", "note": "La Brea's saber-toothed cat specimens are the most complete Ice Age predator collection"}, {"entity": "Los Angeles", "relationship": "URBAN_RESEARCH_SITE", "note": "Urban Nature project found 30 new species within city limits including new bee and millipede species"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The NHM's La Brea Tar Pit collection — 3.5 million Ice Age specimens from the world's richest asphalt fossil site — provides the most complete record of North American Pleistocene ecology and the extinction event that ended the age of mammoths and saber-toothed cats.", "significanceCategory": "regional"},
    }),
    ("science-museum", {
        "summary": "The Science Museum in London, established in 1857 as part of the South Kensington Museum (the cultural complex created from profits of the Great Exhibition of 1851), holds over 300,000 objects documenting the history of science and technology — including Stephenson's Rocket (1829), the Apollo 10 command module, and the world's oldest surviving steam engine (Boulton and Watt, 1788). The museum's IMAX theatre and interactive Wonderlab galleries serve 3 million visitors annually, making it the UK's second-most visited museum.\n\nThe Science Museum emerged from Henry Cole's vision of using the £180,000 profit from Prince Albert's 1851 Great Exhibition to create a cultural district in South Kensington. The original Patent Office Museum of 1857 became the Science Museum in 1909. The museum's collections trace the Industrial Revolution through original artifacts: James Watt's rotative steam engine (1788), Arkwright's water frame (1769), Babbage's Difference Engine (1832 partial), and Fleming's original penicillin cultures from 1928.\n\nThe museum's climate science gallery (Energy: Fuelling the Future, 2004) was controversial for being funded by Shell and BP while presenting climate change as disputed — a corporate sponsorship debate that became the template for museum ethics discussions about fossil fuel funding. The 2021 opening of the free IMAX Climate documentary series represented a course correction. The museum's Wellcome Wing holds the world's largest collection of medical history objects, including plague doctor costumes, Victorian surgical instruments, and the iron lung respirator that marked the polio era.",
        "causes": ["1857 establishment from profits of Prince Albert's 1851 Great Exhibition of South Kensington complex", "300,000 artifacts documenting Industrial Revolution and scientific history accumulated over 160 years", "Stephenson's Rocket, Boulton-Watt steam engine, and Babbage's Difference Engine as founding collection", "South Kensington Museum district vision of Henry Cole creating integrated cultural complex"],
        "effects": ["3 million annual visitors making museum UK's second-most visited cultural institution", "Industrial Revolution artifact collection including original steam engines and water frames", "Corporate sponsorship controversy became template for museum ethics debate about fossil fuel funding", "Wellcome Wing medical history collection providing most comprehensive history of medicine anywhere"],
        "relationships": [{"entity": "Prince Albert", "relationship": "FOUNDING_INSPIRATION", "note": "Great Exhibition 1851 profits funded South Kensington complex including Science Museum"}, {"entity": "Stephenson's Rocket", "relationship": "HOUSES", "note": "Original 1829 locomotive that won Rainhill Trials is museum's most famous transportation artifact"}, {"entity": "Charles Babbage", "relationship": "PRESERVES_WORK_OF", "note": "Museum holds Babbage's 1832 Difference Engine — earliest mechanical computer prototype"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Science Museum's collection of original Industrial Revolution artifacts — James Watt's steam engine, Arkwright's water frame, and Stephenson's Rocket — constitutes the most complete physical record of the technological revolution that transformed human civilization.", "significanceCategory": "continental"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 83 — Class 361 Museums II")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
