#!/usr/bin/env python3
"""Batch 117 — Class 361 Museums IV: National & Memorial Museums (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/361-Class-361"
FILE_PREFIX = "361"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("centre-georges-pompidou", {
        "summary": "The Centre Georges Pompidou (commonly known as the Pompidou Centre or Beaubourg), opened in 1977 in Paris's Beaubourg district and designed by Renzo Piano and Richard Rogers in a radically unconventional high-tech architectural style — with its structural and mechanical systems (escalators, air ducts, water pipes) exposed on the building's exterior and color-coded — is one of the 20th century's most architecturally controversial and most-visited cultural institutions, housing the Bibliothèque publique d'information (BpI) and the Museum of Modern Art (Musée National d'Art Moderne, MNAM) with one of Europe's greatest collections of modern and contemporary art.\n\nThe Centre was initiated by President Georges Pompidou (1969-1974), a modernist who wanted to create a genuinely innovative cultural institution that could challenge French cultural conservatism. The Piano-Rogers design was selected from 681 international competition entries — and shocked France: critics called it an oil refinery, a factory, a monster. But the 'inside-out' architecture — freeing the interior from structural constraints by placing everything on the facade — has been vindicated by 50 years of operation and inspired an entire school of high-tech architecture (including Piano's and Rogers's own subsequent careers).\n\nThe MNAM is one of the world's premier modern art museums, with exceptional holdings of Fauvism (Matisse, Derain), Cubism (Picasso, Braque), Surrealism (Ernst, Dalí), Abstract Expressionism, Conceptual Art, and contemporary work. The Centre has attracted approximately 3 million visitors annually, making it France's most-visited attraction during some years. A major renovation (2023-2027) is underway, and satellite centers in Metz (Centre Pompidou-Metz, opened 2010) and Málaga have extended the brand.",
        "causes": ["President Pompidou's initiative creating France's most innovative cultural institution", "1977 Piano-Rogers radical high-tech 'inside-out' design shocking Paris while revolutionizing museum architecture", "Competition-winning design from 681 international entries selecting most unconventional proposal", "French government investment in creating genuinely international contemporary art institution"],
        "effects": ["Centre Pompidou as one of the most-visited cultural institutions in Europe with ~3 million annual visitors", "Piano-Rogers high-tech architecture founding a school of exposed-structure design (Lloyd's of London, HSBC HQ Hong Kong)", "MNAM's world-class modern art collection with Fauvism, Cubism, Surrealism, and contemporary holdings", "Beaubourg district regeneration through cultural anchor transforming a run-down Paris neighborhood"],
        "relationships": [{"entity": "Renzo Piano and Richard Rogers", "relationship": "DESIGNED_BY", "note": "Piano and Rogers's 1977 inside-out design revolutionized museum architecture and launched both architects' international careers"}, {"entity": "Musée National d'Art Moderne", "relationship": "HOUSES_ONE_OF_EUROPE'S_PREMIER_COLLECTIONS", "note": "The MNAM within the Pompidou holds one of Europe's greatest modern art collections"}, {"entity": "Georges Pompidou", "relationship": "INITIATED_BY_AND_NAMED_FOR", "note": "French President Pompidou initiated the centre project; it was named for him posthumously after his 1974 death"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Centre Pompidou — a 1977 architectural revolution that exposed the functional as aesthetic, housing one of Europe's great modern art collections, attracting millions annually, and spawning a global high-tech architecture movement — is one of the most consequential cultural buildings of the 20th century.", "significanceCategory": "world-changing"},
    }),
    ("bardo-national-museum", {
        "summary": "The Bardo National Museum (Musée National du Bardo), housed in the former Hafsid and Husainid palace complex outside Tunis — a 9th-century origin site expanded and rebuilt through Ottoman and then Husainid Bey eras — is the largest museum in North Africa and one of the world's greatest repositories of ancient Roman mosaic art, containing the most extensive and spectacular collection of Roman mosaics in existence, including room-sized masterpieces from Carthaginian and Roman North African sites.\n\nThe museum's Roman mosaic collection is extraordinary: hundreds of mosaics from the Roman provinces of Africa Proconsularis and Byzacena (modern Tunisia) represent the height of the art form — depicting mythological scenes, gladiatorial combats, marine life, portrait busts, and Dionysian revels in works that surpass anything found in Rome itself. The mosaics from the royal Bardo palace renovations and archaeological sites at El Djem (the third-largest Roman amphitheater), Thuburbo Majus, Dougga, and Utica provide unparalleled documentation of Roman provincial life in Africa.\n\nBeyond the Roman collection, the Bardo holds Carthaginian steles and votives, prehistoric artifacts, Islamic arts, and the remarkable Mahdia shipwreck collection — a 1st-century BC Greek ship carrying Greek artworks looted for Roman buyers, salvaged in the 1900s. The museum suffered a devastating terrorist attack in March 2015, when Islamist gunmen killed 22 tourists and security guards — one of the worst attacks on cultural heritage in North Africa. This attack was both a tragedy for the museum and a statement of Islamist hostility to Western tourism and cross-cultural heritage.",
        "causes": ["Hafsid palace origins (13th century) providing the architectural shell converted to museum use", "19th-century conversion of the Husainid Bey palace to house Tunisia's growing archaeological collections", "Roman North African mosaic production in Africa Proconsularis and Byzacena creating the world's greatest Roman mosaic legacy", "North African archaeological excavations (1800s-1900s) systematically recovering Roman and Carthaginian artifacts"],
        "effects": ["World's most extensive Roman mosaic collection — unmatched documentation of Roman provincial art in Africa", "2015 Bardo terrorist attack killing 22 tourists devastating Tunisian tourism economy and security posture", "Mahdia shipwreck collection as unique documentation of Greek artwork trade in the late Roman Republic", "Most comprehensive window into ancient North African Roman life available in a single institution"],
        "relationships": [{"entity": "Roman North Africa", "relationship": "PREMIER_MUSEUM_DOCUMENTING_CIVILIZATION_OF", "note": "Bardo's mosaic collection is the world's greatest documentation of Roman art and life in North Africa"}, {"entity": "2015 Bardo National Museum Attack", "relationship": "DEVASTATED_BY", "note": "The March 2015 terrorist attack killing 22 tourists was a major blow to Tunisian heritage and tourism"}, {"entity": "Mahdia Shipwreck", "relationship": "HOUSES_ARTIFACTS_FROM", "note": "The 1st-century BC Greek ship's Greek artworks salvaged from the Mahdia shipwreck are among Bardo's treasures"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Bardo National Museum — housing the world's greatest Roman mosaic collection, holding irreplaceable North African archaeological treasures, and surviving a 2015 terrorist attack that highlighted both its cultural significance and vulnerability — is Africa's most important ancient art museum and a vital window into the Roman world's African provinces.", "significanceCategory": "world-changing"},
    }),
    ("andy-warhol-museum-of-modern-art", {
        "summary": "The Andy Warhol Museum of Modern Art in Medzilaborce, Slovakia — not to be confused with The Andy Warhol Museum in Pittsburgh, Pennsylvania — is a small but culturally significant institution in the village where Andy Warhol's Ruthenian (Rusyn) parents, Andrej and Júlia Warhola, were born before emigrating to the United States in the early 20th century. The museum, founded in 1991 shortly after Slovakia's transition from communism, contains one of the largest Warhol collections outside of Pittsburgh, including original silkscreen prints, drawings, and personal memorabilia.\n\nAndy Warhol (born Andrew Warhola, 1928-1987) was the son of Carpatho-Rusyn Greek Catholic immigrants from the village of Miková, near Medzilaborce, in what was then the Kingdom of Hungary (later Czechoslovakia, now northeastern Slovakia). His parents' Byzantine Greek Catholic faith shaped aspects of Warhol's art — some scholars argue his iconic imagery (repeated images of consumer goods, celebrity portraits) has roots in the Eastern Christian icon tradition of repetitive sacred imagery.\n\nThe museum in Medzilaborce represents Slovakia's reclamation of its connection to one of the 20th century's most important artists, establishing cultural heritage tourism in an otherwise economically peripheral region of eastern Slovakia near the Ukrainian border. The museum has become an unexpected pilgrimage site for Warhol enthusiasts worldwide, and its existence highlights the global diaspora connections of Central and Eastern European immigrant communities to major 20th-century American cultural figures.",
        "causes": ["1991 founding shortly after Slovak transition from communism reclaiming Warhol's Rusyn cultural heritage", "Andy Warhol's parents' emigration from Miková village near Medzilaborce — direct local connection to Pop Art icon", "Slovak cultural heritage tourism developing after communism's fall to attract international visitors", "Large Warhol collection assembled including silkscreens, drawings, and memorabilia"],
        "effects": ["Medzilaborce establishing unexpected cultural heritage tourism destination in peripheral eastern Slovakia", "Scholarly attention to Warhol-Eastern Christian icon tradition connections informed by Rusyn roots", "Global Warhol enthusiast pilgrimage to small Slovak village highlighting Central European-American cultural connections", "Museum as model for Eastern European communities reclaiming cultural heritage links to American cultural figures"],
        "relationships": [{"entity": "Andy Warhol", "relationship": "DEDICATED_TO_RUSYN_HERITAGE_OF", "note": "The museum celebrates Warhol's Rusyn roots — his parents emigrated from Miková village near Medzilaborce"}, {"entity": "Ruthenian-Rusyn Diaspora", "relationship": "CULTURAL_HERITAGE_INSTITUTION_FOR", "note": "The museum represents Slovak reclamation of Warhol as part of the Ruthenian-Rusyn diaspora's cultural legacy"}, {"entity": "The Andy Warhol Museum Pittsburgh", "relationship": "COUNTERPART_INSTITUTION_TO", "note": "The Pittsburgh Warhol Museum (founded 1994) and the Medzilaborce museum are the two principal Warhol institutions"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Andy Warhol Museum of Modern Art in Medzilaborce — preserving the Rusyn roots of America's most important Pop artist, establishing unexpected cultural heritage tourism in eastern Slovakia, and illuminating Central European immigrant contributions to American culture — is a uniquely meaningful if small institution in the global network of cultural heritage.", "significanceCategory": "regional"},
    }),
    ("central-state-museum-of-kazakhstan", {
        "summary": "The Central State Museum of Kazakhstan, established in 1931 in Alma-Ata (now Almaty) as the Central Museum of the Kazakh SSR and relocated to its current purpose-built building in 1985, is the largest and most comprehensive museum in Central Asia — holding approximately 300,000 items documenting Kazakhstan's natural history, archaeological heritage (from the Bronze Age Botai culture through the Saka, Wusun, and Khazar periods), and the traditions of Kazakhstan's nomadic steppe cultures, including the famous Golden Warrior (Altyn Adam) replica.\n\nThe museum's holdings reflect Kazakhstan's extraordinary archaeological richness: the Eurasian steppe was home to the world's first horse domestication cultures (Botai, ca. 3500 BC), the Scythian-Saka golden art tradition, the Silk Road trade cultures, and the medieval Kazakh Khanate. The Golden Warrior (reconstructed from a 5th-4th century BC burial at Issyk near Almaty) — a warrior in golden scale armor with a distinctive pointed headdress — has become a national symbol of Kazakhstan, featured in state emblems and tourist imagery.\n\nEstablished under Soviet colonial archaeology (which systematically excavated the steppe while simultaneously suppressing Kazakh nomadic culture), the museum's collections carry the complex legacy of Soviet knowledge production about Central Asian civilizations. Post-independence Kazakhstan (1991) has repositioned the museum as an institution of Kazakh national identity — emphasizing the Golden Warrior, the yurt tradition, and pre-Russian Kazakh cultural achievement. The museum represents Kazakhstan's effort to construct a national historical narrative from steppe nomadic heritage.",
        "causes": ["1931 Soviet establishment as Kazakh SSR central museum conducting colonial archaeological documentation", "1985 relocation to purpose-built Almaty building creating Central Asia's largest museum facility", "Kazakhstan's extraordinary steppe archaeological richness — horse domestication, Saka gold, Silk Road cultures", "Post-1991 independence repositioning as institution of Kazakh national identity and nomadic heritage pride"],
        "effects": ["Central Asia's largest museum with 300,000 items documenting steppe cultures from Bronze Age through Kazakh Khanate", "Golden Warrior (Altyn Adam) becoming Kazakhstan's national symbol through museum display and promotion", "Post-independence narrative reframing from Soviet colonial archaeology to Kazakh national heritage institution", "Steppe horse domestication and Saka gold documentation providing world-class prehistoric cultural record"],
        "relationships": [{"entity": "Golden Warrior of Kazakhstan", "relationship": "HOUSES_AND_PROMOTES_NATIONAL_SYMBOL", "note": "The Altyn Adam replica and associated golden artifacts are the museum's most iconic holdings and Kazakhstan's national symbol"}, {"entity": "Kazakh Steppe Cultures", "relationship": "PREMIER_REPOSITORY_OF_HERITAGE_OF", "note": "The museum documents 5,000 years of Eurasian steppe civilization from horse domestication to Kazakh Khanate"}, {"entity": "Soviet Archaeology in Central Asia", "relationship": "LEGACY_INSTITUTION_OF", "note": "The museum's collections were built through Soviet archaeological programs that both documented and distorted Kazakh heritage"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Central State Museum of Kazakhstan — Central Asia's largest museum, housing the Golden Warrior national symbol, documenting the world's first horse domestication cultures, and navigating the transition from Soviet colonial archaeology to Kazakh national heritage institution — is the premier repository for understanding Eurasian steppe civilization.", "significanceCategory": "continental"},
    }),
    ("bangkok-national-museum", {
        "summary": "The Bangkok National Museum (พิพิธภัณฑสถานแห่งชาติพระนคร, National Museum Bangkok), established in 1874 by King Chulalongkorn (Rama V) as a public museum — the first in Thailand — and housed in part of the former Wang Na (Front Palace) complex adjacent to the Grand Palace complex, is Thailand's largest and most comprehensive museum, with collections spanning Thai art and history from prehistoric periods through the Bangkok period Rattanakosin era, and one of the finest collections of Southeast Asian art in the world.\n\nThe museum's founding by Chulalongkorn was part of his extraordinary modernization program that saved Siam from direct colonization by demonstrating to European powers that Siam was a civilized, modern state. The Wang Na complex (former residence of the Vice-King or 'Second King') was converted to museum use after the Vice-Kingship was abolished. Chulalongkorn's museum initiative, alongside his railroad-building, educational reforms, and abolition of slavery, established Thailand's modern institutional infrastructure.\n\nThe museum's collection is extraordinary: prehistoric artifacts from the Ban Chiang culture (among the world's earliest bronze-using cultures, ca. 2100 BC), Dvaravati Buddhist art (6th-11th centuries), Khmer-period art from when much of modern Thailand was under Khmer Empire influence, Sukhothai and Ayutthaya-period masterworks, and the finest collection of royal regalia, thrones, carriages, and ceremonial objects representing Thai royal culture. The museum includes Buddhaisawan Chapel (1795) housing one of Thailand's most sacred Buddha images, the Phra Phuttha Sihing.",
        "causes": ["1874 founding by Chulalongkorn as Thailand's first public museum during royal modernization program", "Wang Na complex conversion after Vice-Kingship abolition providing royal palace complex as museum setting", "Chulalongkorn's modernization program requiring cultural institutions to demonstrate Thai civilization to European powers", "Royal collections from Rattanakosin dynasty (1782-present) providing extraordinary material for national museum"],
        "effects": ["Thailand's largest museum with prehistoric through modern Thai art and royal material culture", "Chulalongkorn's modernization program including museum as demonstration of Thai civilization to prevent colonization", "Buddhaisawan Chapel housing Phra Phuttha Sihing — one of Thailand's most sacred Buddha images", "World-class Southeast Asian art collection including Ban Chiang prehistoric bronze culture and Dvaravati Buddhist art"],
        "relationships": [{"entity": "Chulalongkorn (Rama V)", "relationship": "FOUNDED_BY_AS_PART_OF_MODERNIZATION_PROGRAM", "note": "Chulalongkorn established Thailand's first public museum in 1874 as part of his successful anti-colonization modernization"}, {"entity": "Thai Royal Collection", "relationship": "HOUSES_MAJOR_PORTION_OF", "note": "The museum holds royal regalia, thrones, ceremonial objects, and art from the Rattanakosin dynasty's Bangkok period"}, {"entity": "Ban Chiang Culture", "relationship": "MAJOR_COLLECTION_OF_ARTIFACTS_FROM", "note": "The museum holds major Ban Chiang prehistoric bronze artifacts (ca. 2100 BC) — among the world's earliest bronze culture"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Bangkok National Museum — Thailand's oldest and largest museum, founded by Chulalongkorn as evidence of Thai civilization while resisting colonization, housing Ban Chiang prehistoric bronzes and the sacred Phra Phuttha Sihing, and containing one of the world's finest Southeast Asian art collections — is Central Thailand's most important cultural institution.", "significanceCategory": "world-changing"},
    }),
    ("bangladesh-national-museum", {
        "summary": "The Bangladesh National Museum (বাংলাদেশ জাতীয় জাদুঘর), established in 1913 as the Dhaka Museum under British colonial rule and renamed after Bangladesh's independence (1971), is the largest and most comprehensive museum in Bangladesh — holding approximately 83,000 items spanning archaeological artifacts from the ancient Bengal region, Islamic art from the Mughal and Sultanate periods, natural history, and contemporary Bangladeshi art — and representing Bangladesh's effort to construct a national cultural identity from Bengal's extraordinarily rich but multiply-claimed heritage.\n\nBangladesh's national heritage narrative is politically complex: its territory encompasses the eastern half of the ancient Bengal region, which has been variously claimed by Hindu, Muslim, Buddhist, and Bengali nationalist frameworks. The museum's collection reflects pre-Islamic Hindu and Buddhist sculpture from the Pala dynasty (8th-12th centuries), which ruled Bengal during the period when Nalanda and Vikramashila universities flourished — making eastern Bengal a center of Buddhist scholarship. Mughal-period Dhaka was known for muslin fabric of legendary fineness (Dhaka muslin, so fine it was called 'woven air'), documented in the museum.\n\nThe museum was significantly relevant during the 1971 Bangladesh Liberation War: Pakistani forces and their local collaborators (Al-Badr) specifically targeted Bengali intellectuals and cultural figures in the December 14, 1971 massacre — an attack on Bengali cultural identity that the National Museum has subsequently worked to memorialize. Post-independence Bangladesh has invested in the museum as an institution of national memory alongside language rights (the 1952 Bengali Language Movement, celebrated as International Mother Language Day since 1999).",
        "causes": ["1913 colonial Dhaka Museum establishment by British administration documenting Bengal's archaeological heritage", "1971 Bangladesh independence creating need to rename and reframe museum as national institution", "Bangladesh's complex heritage from Hindu, Buddhist, Muslim, and Bengali nationalist frameworks", "1971 Liberation War and intellectual massacre creating new memorial dimension for national museum"],
        "effects": ["83,000-item collection documenting Bengal's cultural heritage from prehistoric through contemporary periods", "Pala dynasty Buddhist and Hindu sculpture collection preserving 8th-12th century eastern Bengal artistic heritage", "National museum as institution of memory for 1971 Liberation War and Bengali intellectual martyrdom", "Museum documentation of Dhaka muslin tradition (legendary 'woven air' fabric) preserving intangible heritage"],
        "relationships": [{"entity": "Bangladesh", "relationship": "NATIONAL_MUSEUM_OF", "note": "Bangladesh National Museum is the premier cultural institution of the world's eighth-most-populous country"}, {"entity": "1971 Bangladesh Liberation War", "relationship": "MEMORIALIZES_AND_WAS_AFFECTED_BY", "note": "The museum memorializes 1971 intellectual massacre victims while Pakistani forces specifically targeted Bengali cultural figures"}, {"entity": "Pala Dynasty", "relationship": "HOUSES_MAJOR_ART_COLLECTION_FROM", "note": "The museum's Pala-period Buddhist and Hindu sculpture collection documents 8th-12th century eastern Bengal's Buddhist heritage"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Bangladesh National Museum — documenting ancient Bengal's Buddhist and Muslim heritage, memorializing the 1971 Liberation War's intellectual massacre, and constructing national identity from a multiply-claimed cultural heritage — is the central institution in Bangladesh's cultural self-definition as a nation.", "significanceCategory": "continental"},
    }),
    ("carthage-national-museum", {
        "summary": "The Carthage National Museum (Musée National de Carthage), established in 1875 under French Protectorate patronage on Byrsa Hill — the citadel of ancient Carthage, near Tunis — is a major archaeological museum housing artifacts from one of the ancient world's most powerful and historically demonized civilizations: the Phoenician city-state of Carthage (founded 814 BC according to tradition) that controlled Mediterranean trade for centuries before its total destruction by Rome in the Third Punic War (146 BC).\n\nThe museum's archaeological context is exceptional: Byrsa Hill itself contains the ruins of the last inhabited Carthaginian residential quarter (the 'Carthage Quarter' excavated by French archaeologists in the 1970s) showing how ordinary Carthaginians lived in the 2nd-century BC city before its annihilation. The museum holds Punic stelae, terracotta figurines, jewelry, coins, and tophet (sanctuary of Baal Hammon) artifacts including the most controversial of Carthaginian objects — the urns from the tophet that Roman (and modern) sources interpreted as evidence of child sacrifice, a claim still debated by archaeologists.\n\nCarthage's legacy has been fundamentally shaped by Roman historiography: Livy, Polybius, and Roman sources portrayed Carthaginians as treacherous, cruel, and given to child sacrifice — propaganda that shaped Western understanding for 2,000 years. The Carthage National Museum has been central to the 20th-21st century archaeological reappraisal of Punic civilization, which has revealed a sophisticated merchant republic with far-reaching trade networks, advanced agricultural techniques (Mago's agricultural treatise was preserved by Roman translation), and complex religious and material culture.",
        "causes": ["1875 French Protectorate establishment of museum on Byrsa Hill during early archaeological excavations", "Ancient Carthage's destruction in 146 BC by Rome creating exceptional archaeological site for excavation", "French Protectorate interest in documenting and claiming the ancient Mediterranean heritage of Tunisia", "20th-century international archaeological campaigns revealing Carthaginian urban life and challenging Roman propaganda"],
        "effects": ["World's premier repository for Punic/Carthaginian archaeology and material culture", "Archaeological reappraisal of Carthaginian civilization correcting 2,000 years of Roman-biased historiography", "Tophet archaeology fueling ongoing scholarly debate about Punic child sacrifice practices", "UNESCO World Heritage Site (1979) status for ancient Carthage supported by museum's documentation work"],
        "relationships": [{"entity": "Ancient Carthage", "relationship": "PRIMARY_ARCHAEOLOGICAL_MUSEUM_FOR", "note": "The museum is the world's principal institution documenting Punic Carthaginian civilization"}, {"entity": "Punic Wars", "relationship": "DOCUMENTS_CIVILIZATION_DESTROYED_IN", "note": "Carthage's total destruction in the Third Punic War (146 BC) made archaeological excavation the only way to access its civilization"}, {"entity": "Phoenician Civilization", "relationship": "PRESERVES_WESTERN_HERITAGE_OF", "note": "Carthage was founded by Phoenicians from Tyre; the museum documents the western Phoenician colonial legacy"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Carthage National Museum — on the citadel of one of the ancient world's great powers, reappraising Punic civilization against 2,000 years of Roman demonization, and holding the world's most significant Carthaginian archaeological collection — is a vital institution for understanding the ancient Mediterranean world.", "significanceCategory": "world-changing"},
    }),
    ("auschwitz-birkenau-state-museum", {
        "summary": "The Auschwitz-Birkenau State Museum (Państwowe Muzeum Auschwitz-Birkenau), established in 1947 on the site of the Nazi German concentration and extermination camps of Auschwitz I and Auschwitz II-Birkenau where approximately 1.1 million people were murdered (90% Jewish, along with Polish political prisoners, Roma, Soviet POWs, and others), is the most visited Holocaust memorial and museum in the world — with approximately 1.5-2 million visitors annually — and a UNESCO World Heritage Site since 1979 designated as a site of exceptional universal significance.\n\nAuschwitz was the largest single site of the Holocaust: its gas chambers and crematoria killed more people than any other single location in human history in the modern era. The museum's preserved buildings — the entry gate with its cynical 'Arbeit Macht Frei' ('Work makes you free') inscription, the rows of brick barracks, the ruins of the Birkenau crematoria dynamited by retreating SS, the victims' belongings (suitcases, shoes, hair, eyeglasses) displayed in Block 4 — constitute one of the most powerful architectural testimonies to human evil ever preserved.\n\nThe museum's mission — 'to preserve the authentic historical site' and 'to document the history of Auschwitz' — faces ongoing challenges: the wooden Birkenau barracks are deteriorating, the authentic evidence is fragile, and the volume of visitors requires careful management. The museum has been central to Holocaust education worldwide, training teachers and hosting school groups; the 'Arbeit Macht Frei' gate was stolen and recovered in 2009. As the last Auschwitz survivors age, the museum's role in Holocaust memory is transitioning from living testimony to institutional memory.",
        "causes": ["1947 Polish state establishment of museum on Auschwitz site immediately after liberation (January 1945)", "UNESCO World Heritage designation (1979) recognizing site's exceptional universal significance", "Holocaust memorial responsibility requiring preservation of authentic evidence — gas chambers, victims' belongings, barracks", "Growing global Holocaust education movement creating 1.5-2 million annual visitors"],
        "effects": ["Auschwitz as most-visited Holocaust memorial — central institution in global Holocaust memory and education", "Preserved authentic evidence (victims' belongings, gas chamber ruins) providing unmediated testimony to the Shoah", "UNESCO World Heritage status (1979) establishing international recognition and resources for preservation", "Museum as 'last witness' institution transitioning from survivor testimony to institutional memory after survivors age"],
        "relationships": [{"entity": "The Holocaust", "relationship": "PREMIER_MEMORIAL_MUSEUM_FOR_LARGEST_SINGLE_SITE_OF", "note": "Auschwitz was the Holocaust's largest single killing site — 1.1 million murdered — and the museum is the world's most significant Holocaust memorial"}, {"entity": "Nazi Germany", "relationship": "DOCUMENTS_AND_MEMORIALIZES_CRIMES_OF", "note": "The museum preserves the authentic physical evidence of Nazi Germany's industrialized genocide"}, {"entity": "UNESCO World Heritage Sites", "relationship": "INSCRIBED_AS_EXCEPTIONAL_UNIVERSAL_SIGNIFICANCE", "note": "Auschwitz-Birkenau received UNESCO World Heritage status in 1979 for its universal significance as Holocaust site"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "Auschwitz-Birkenau State Museum — the memorial to the 20th century's most devastating genocide, the most-visited Holocaust site, preserving authentic evidence of humanity's greatest evil, and the world's most important institution of Holocaust memory — is among the most historically significant sites and institutions on Earth.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 117 — Class 361 Museums IV: National & Memorial Museums")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
