#!/usr/bin/env python3
"""Batch 130 — Class 361 Museums V: Central Asian & Caucasian State Museums (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/361-Class-361"
FILE_PREFIX = "361"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("assam-state-museum", {
        "summary": "The Assam State Museum in Guwahati, Assam, India — one of India's most important regional museums — houses an exceptional collection of archaeological artifacts, sculptures, natural history specimens, ethnographic materials, and historical documents from Assam and the broader Northeast India region. The museum preserves the remarkable heritage of one of India's most historically and culturally distinct regions — home to the ancient Kamarupa kingdom (the first reference to Assam), the Ahom Kingdom (which resisted Mughal expansion for nearly 600 years, 1228-1826), and the extraordinary diversity of Northeast India's tribal and linguistic cultures.\n\nAssam's historical significance is extraordinary and often underappreciated: the Ahom Kingdom, established by Tai-Ahom migrants from Southeast Asia in 1228, successfully repelled seventeen Mughal invasions over six centuries — a resistance record unmatched in Indian history. The Ahom maintained their sovereignty until British annexation in 1826 (Treaty of Yandaboo). The Assam State Museum's collection includes materials from the Kamarupa period, Ahom sculptures and artifacts, temple sculptures (including from the Kamakhya Temple tradition), and natural history materials from one of the world's most biodiverse regions.\n\nNortheast India's extraordinary tribal diversity — with hundreds of distinct ethnic groups, languages, and material cultures — is documented in the museum's ethnographic collections. The museum's role in preserving Assam's heritage takes on additional significance given the region's history of political instability, ethnic conflicts, and the complex legacies of British colonialism and Indian independence.",
        "causes": ["Assam's extraordinary historical heritage (Kamarupa, Ahom Kingdom) requiring systematic museum preservation", "Ahom Kingdom's 600-year Mughal resistance making its archaeological and cultural materials uniquely significant", "Northeast India's exceptional ethnic and linguistic diversity requiring ethnographic documentation and preservation", "Guwahati's status as Assam's major urban center providing institutional context for regional heritage museum"],
        "effects": ["Museum preserving the archaeological and cultural materials of the Ahom Kingdom's 600-year resistance tradition", "Kamarupa kingdom materials documenting Assam's ancient Hindu and Buddhist heritage", "Ethnographic collections providing comprehensive documentation of Northeast India's tribal cultural diversity", "Museum's heritage preservation supporting Assamese identity in a region with complex modern political challenges"],
        "relationships": [{"entity": "Ahom Kingdom", "relationship": "ARTIFACTS_AND_HERITAGE_PRESERVED_IN", "note": "The museum houses materials from the Ahom Kingdom that resisted Mughal expansion for nearly 600 years"}, {"entity": "Kamarupa", "relationship": "ANCIENT_KINGDOM_DOCUMENTED_IN_COLLECTIONS_OF", "note": "The museum preserves materials from the Kamarupa period, one of India's earliest historically documented kingdoms"}, {"entity": "Northeast India", "relationship": "PRIMARY_HERITAGE_INSTITUTION_OF_DIVERSE_REGION", "note": "The museum documents the exceptional ethnic, linguistic, and cultural diversity of Northeast India"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Assam State Museum — preserving the heritage of the Ahom Kingdom's 600-year Mughal resistance, the ancient Kamarupa civilization, and Northeast India's extraordinary cultural diversity — is historically significant as the primary institution documenting one of India's most distinct and underrepresented regional heritages.", "significanceCategory": "continental"},
    }),
    ("goa-state-museum", {
        "summary": "The Goa State Museum (Portuguese: Museu do Estado de Goa) in Panaji, Goa, India — established in 1977 after Goa's integration with India (1961) — preserves the unique heritage of Goa, the former Portuguese colony (1510-1961) that holds the distinction of being the last European colonial possession in India and one of the longest-lasting Portuguese territorial holdings in the world, with a cultural heritage that uniquely fuses Konkani Indian tradition with Portuguese Catholic influence across 451 years of colonial presence.\n\nGoa's Portuguese colonial history (1510-1961, longer than British India's 1858-1947) created one of the most distinctive cultural fusions in the world: Old Goa's Baroque churches (including the Basilica of Bom Jesus, housing St. Francis Xavier's incorrupt body — a UNESCO World Heritage Site), the Goan Catholic community's Portuguese-influenced Konkani culture, Goa's music (the mando tradition combining Portuguese and Indian elements), and its cuisine (vindaloo, balchão, bebinca) all reflect this deep cultural synthesis.\n\nThe Goa State Museum houses collections including Hindu temple artifacts, Portuguese colonial art and furniture, Goan Catholic religious art, natural history specimens, and documents from the colonial and independence periods. The museum's challenge — preserving both the ancient Hindu heritage and the 451-year Portuguese colonial overlay — makes it one of India's most culturally complex regional museums. Goa's 1961 'Liberation' (or annexation, depending on perspective) was India's last act of anti-colonial integration.",
        "causes": ["Goa's 1961 integration into India requiring cultural institution to preserve 451-year Portuguese colonial heritage", "Unique fusion of Konkani Hindu tradition and Portuguese Catholic influence requiring comprehensive documentation", "Old Goa's UNESCO World Heritage Baroque churches and St. Francis Xavier's legacy requiring institutional heritage context", "Goa's complex identity — both ancient Indian and uniquely Portuguese-influenced — requiring museum to address both layers"],
        "effects": ["Museum preserving the full range of Goan heritage from ancient Hindu artifacts to Portuguese colonial art", "Goan Catholic artistic tradition documented alongside Hindu temple materials in unique cultural synthesis", "Institutional context for Old Goa's UNESCO World Heritage Baroque church ensemble", "Post-colonial Goan identity supported through museum's preservation of both pre-colonial and colonial heritage"],
        "relationships": [{"entity": "Portuguese Goa", "relationship": "COLONIAL_HERITAGE_PRESERVED_IN", "note": "The museum preserves 451 years of Portuguese colonial material culture in India's last European colonial possession"}, {"entity": "Old Goa", "relationship": "HERITAGE_CONTEXT_FOR_UNESCO_BAROQUE_CHURCHES_OF", "note": "The museum provides institutional context for Old Goa's UNESCO World Heritage Baroque church ensemble"}, {"entity": "Goan Cultural Synthesis", "relationship": "PRIMARY_DOCUMENTATION_INSTITUTION_OF_UNIQUE", "note": "The museum documents the unique fusion of Konkani Hindu and Portuguese Catholic cultures that defines Goan identity"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Goa State Museum — preserving the heritage of the world's longest-lasting Portuguese colonial territory in Asia, documenting the unique Goan fusion of Konkani and Portuguese Catholic culture — is historically significant as the primary institution of India's most culturally distinctive former colonial region.", "significanceCategory": "continental"},
    }),
    ("artsakh-state-museum", {
        "summary": "The Artsakh State Museum (Armenian: Արցախի Պետական Թանգարան) in Stepanakert (Khankendi), the capital of the Republic of Artsakh (Nagorno-Karabakh) — a de facto independent Armenian-majority republic in the South Caucasus whose status has been one of the most intractable post-Soviet territorial conflicts — housed collections documenting Armenian cultural heritage in the Karabakh region, including archaeological materials from ancient Artsakh (one of the traditional provinces of ancient Armenia), medieval Armenian Christian churches, and modern Armenian cultural materials.\n\nThe Nagorno-Karabakh conflict (1988-1994, 2020, 2023) between Armenia and Azerbaijan over the Armenian-majority enclave within Soviet Azerbaijan's administrative borders is one of the most complex and tragic territorial disputes of the post-Soviet era. The Artsakh State Museum's existence and collections were central to Armenian claims of centuries-old cultural heritage in the region — a heritage Azerbaijanis disputed and re-interpreted as Azerbaijani Caucasian Albanian heritage.\n\nIn September 2023, Azerbaijan's military offensive (Operation Vengeance) recaptured the entirety of Nagorno-Karabakh, causing the mass exodus of over 100,000 Armenians from the region within days. The Republic of Artsakh dissolved on January 1, 2024. The fate of the Artsakh State Museum's collections — and of Armenian cultural heritage in Nagorno-Karabakh generally — became an urgent international concern, with fears that Armenian churches, monasteries, and museum collections would be destroyed or re-attributed under Azerbaijani control.",
        "causes": ["Armenian cultural heritage claims in Karabakh requiring museum documentation of centuries-old Armenian presence", "Post-Soviet Republic of Artsakh requiring state cultural institutions including a national museum", "Nagorno-Karabakh conflict making cultural heritage preservation both a practical and political priority", "Medieval Armenian Christian churches and archaeological materials requiring systematic collection and protection"],
        "effects": ["Museum's Armenian heritage collections providing documentary basis for Armenian historical claims in the region", "2023 Azerbaijani offensive and Armenian exodus raising urgent concerns about the collections' fate", "Dissolution of the Republic of Artsakh (January 2024) leaving the museum's future under Azerbaijani control uncertain", "International cultural heritage preservation concerns triggered by the potential destruction of Armenian cultural materials"],
        "relationships": [{"entity": "Republic of Artsakh", "relationship": "STATE_MUSEUM_OF_NOW_DISSOLVED", "note": "The museum served the Republic of Artsakh until its dissolution in January 2024 following the 2023 Azerbaijani offensive"}, {"entity": "Nagorno-Karabakh Conflict", "relationship": "CULTURAL_HERITAGE_CAUGHT_AT_CENTER_OF", "note": "The museum's Armenian collections were central to the conflicting Armenian and Azerbaijani heritage claims over Karabakh"}, {"entity": "Armenian Cultural Heritage", "relationship": "PRIMARY_INSTITUTIONAL_GUARDIAN_OF_KARABAKH", "note": "The museum was the primary institutional guardian of Armenian heritage documentation in the disputed Karabakh region"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Artsakh State Museum — preserving Armenian cultural heritage in one of the world's most intractable post-Soviet territorial disputes, dissolved with the Republic of Artsakh in January 2024 — is historically significant as a monument to the cultural dimension of the Nagorno-Karabakh conflict and the fate of cultural heritage in contested territories.", "significanceCategory": "world-changing"},
    }),
    ("astra-national-museum-complex", {
        "summary": "The ASTRA National Museum Complex (Romanian: Complexul Național Muzeal ASTRA) in Sibiu (Hermannstadt), Transylvania, Romania — one of the largest outdoor open-air ethnographic museums in the world, covering 96 hectares with over 400 traditional buildings — documents the extraordinary richness of Romanian folk architecture, traditional crafts, and rural life through an outdoor museum that preserves actual historic buildings relocated from throughout Romania. ASTRA (the Transylvanian Association for Romanian Literature and Culture of the Romanian People, founded 1861) is itself historically significant as the principal institution of Transylvanian Romanian national cultural awakening.\n\nThe ASTRA association, founded during the Habsburg period when Transylvania was part of the Austrian Empire, was the most important institution of the Transylvanian Romanian national cultural movement — publishing works in Romanian, promoting Romanian language education, and documenting Romanian folk culture at a time when Transylvania's Romanians faced pressure toward Magyarization (Hungarianization). ASTRA's cultural work was a form of national resistance through cultural documentation.\n\nThe ASTRA National Museum Complex includes the remarkable open-air Civilizations Museum in the Dumbrava Forest — Europe's largest and one of the world's largest open-air ethnographic museums — where traditional Romanian farmhouses, mills, churches, and craft workshops from every region of Romania have been reassembled. The complex also includes multiple indoor museums covering Romanian history, Saxon Transylvanian heritage, and natural history. Sibiu's role as European Capital of Culture (2007) highlighted the city's and ASTRA's significance in European cultural heritage.",
        "causes": ["ASTRA association's 1861 founding as Romanian cultural resistance to Habsburg Magyarization pressures in Transylvania", "Transylvanian Romanian national awakening requiring documentary preservation of folk cultural heritage", "Dumbrava Forest open-air museum creation systematically preserving threatened traditional Romanian architecture", "Sibiu's rich multicultural heritage (Romanian, Saxon, Habsburg) providing context for comprehensive regional museum complex"],
        "effects": ["ASTRA open-air museum as one of Europe's largest ethnographic museums preserving traditional Romanian built heritage", "Romanian folk architecture systematically documented and preserved through relocated historic buildings from all regions", "Sibiu's European Capital of Culture 2007 designation highlighting the city's and ASTRA's European cultural significance", "Transylvanian Romanian national identity institutionalized through ASTRA's 160+ years of continuous cultural work"],
        "relationships": [{"entity": "ASTRA Association", "relationship": "CREATED_BY_ROMANIAN_NATIONAL_CULTURAL_INSTITUTION_OF", "note": "The museum complex was created by ASTRA, the 1861 Transylvanian Romanian cultural association that resisted Magyarization"}, {"entity": "Sibiu", "relationship": "FLAGSHIP_CULTURAL_HERITAGE_INSTITUTION_OF_2007_CAPITAL_OF_CULTURE", "note": "ASTRA is central to Sibiu's identity as a major cultural heritage center, highlighted as 2007 European Capital of Culture"}, {"entity": "Romanian Folk Architecture", "relationship": "LARGEST_PRESERVATION_INSTITUTION_OF", "note": "The open-air museum with 400+ relocated buildings is Europe's most comprehensive Romanian folk architecture repository"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The ASTRA National Museum Complex Sibiu — created by the institution that led Transylvanian Romanian national cultural resistance, Europe's largest ethnographic open-air museum with 400+ traditional buildings — is historically significant as a monument of Romanian national cultural awakening and the world's most comprehensive Romanian folk heritage institution.", "significanceCategory": "world-changing"},
    }),
    ("azerbaijan-state-art-gallery", {
        "summary": "The Azerbaijan State Art Gallery (Azerbaijani: Azərbaycan Dövlət İncəsənət Muzeyi) in Baku, Azerbaijan — one of the Caucasus region's most important art museums — houses an extensive collection of Azerbaijani fine art alongside significant holdings of European, Russian, and Oriental art, serving as the primary institution for Azerbaijani visual art heritage and documenting the development of Azerbaijani fine arts from the late 19th century through the Soviet period and post-independence era.\n\nAzerbaijani fine arts developed in the context of the country's extraordinary cultural position — at the intersection of Persian, Turkish, Russian, and Western influences — with the Baku Oil Boom (1870s-1900s) creating the wealth that sponsored Azerbaijani cultural institutions. The Azerbaijan Democratic Republic (1918-1920, the world's first secular democratic Muslim-majority republic) created cultural institutions including art galleries; the subsequent Soviet period invested heavily in Azerbaijani cultural infrastructure.\n\nThe Azerbaijan State Art Gallery's collection includes work by major Azerbaijani painters such as Sattar Bahlulzade (landscape painter), Tahir Salahov (whose monumental realism was among the most internationally recognized Soviet art), and other figures who created distinctively Azerbaijani artistic traditions fusing Eastern and Western visual vocabularies. The gallery's role in documenting and teaching Azerbaijani visual heritage is particularly important given the country's 70-year Soviet period during which official art was constrained by Socialist Realism.",
        "causes": ["Baku Oil Boom wealth creating Azerbaijani cultural institutions including art collections in the late 19th century", "Azerbaijan Democratic Republic (1918-1920) establishing art gallery as part of first secular Muslim democratic republic's cultural program", "Soviet cultural investment creating formal art museum infrastructure for Azerbaijani national art", "Azerbaijani fine arts development requiring institutional home documenting the tradition from 19th century to present"],
        "effects": ["Gallery as primary repository of Azerbaijani fine arts documenting the tradition from 19th-century oil boom to post-Soviet era", "Tahir Salahov and other Azerbaijani artists' international recognition documented and celebrated in national gallery", "Soviet-era Socialist Realism alongside independent artistic expression preserved in comprehensive national collection", "Post-independence Azerbaijani cultural identity expressed through gallery's assertion of distinctive Azerbaijani artistic tradition"],
        "relationships": [{"entity": "Azerbaijan", "relationship": "PRIMARY_FINE_ARTS_INSTITUTION_OF", "note": "The gallery is Azerbaijan's main art museum, housing the comprehensive national collection of Azerbaijani fine arts"}, {"entity": "Baku Oil Boom", "relationship": "WEALTH_THAT_ENABLED_CULTURAL_INSTITUTIONS_INCLUDING", "note": "The Baku oil wealth of the 1870s-1900s created the conditions for Azerbaijani cultural investment including art collections"}, {"entity": "Tahir Salahov", "relationship": "INTERNATIONALLY_RECOGNIZED_AZERBAIJANI_ARTIST_REPRESENTED_IN", "note": "Salahov's monumental realist works, among the most internationally recognized Soviet art, are central to the gallery's collection"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "The Azerbaijan State Art Gallery — preserving Azerbaijani fine arts from the Baku oil boom era through Soviet Socialist Realism to post-independence expression — is regionally significant as the primary institution documenting the visual arts tradition of the Caucasus's most oil-wealthy nation.", "significanceCategory": "local"},
    }),
    ("azerbaijan-state-museum-of-history-of-karabakh", {
        "summary": "The Azerbaijan State Museum of History of Karabakh (Azerbaijani: Azərbaycan Dövlət Qarabağ Tarixi Muzeyi) in Shusha (Shushi), Karabakh — established after Azerbaijan recaptured Shusha in May 2020 and subsequently all of Nagorno-Karabakh in September 2023 — is an official Azerbaijani cultural institution presenting the Azerbaijani historical narrative of Karabakh as an integral part of Azerbaijan's territorial and cultural heritage, directly counterpointing Armenian claims to the same territory.\n\nShusha (known to Armenians as Shushi) is one of the most symbolically contested cities in the South Caucasus: historically a significant Azerbaijani khanate capital and cultural center (described as the 'Conservatory of the Caucasus' for its musical traditions), it was majority-Armenian before 1920 and majority-Azerbaijani in the 18th-19th centuries. Shusha's capture in May 2020 (during the 44-Day War) was celebrated by Azerbaijan as the 'liberation' of its most culturally significant city; its loss was mourned by Armenians as the fall of a city they considered the 'cultural capital' of Artsakh.\n\nThe museum represents Azerbaijan's effort to institutionalize its historical narrative about Karabakh — presenting Azerbaijani khanate history, cultural heritage, and the Karabakh War from an Azerbaijani perspective. Its existence in Shusha alongside the reconstruction of Azerbaijani cultural sites (while Armenian churches face questions about their preservation status) reflects the broader cultural dimension of a post-conflict territorial reintegration.",
        "causes": ["Azerbaijan's 2020 military recapture of Shusha requiring cultural institution establishment to assert Azerbaijani historical narrative", "Long-running Nagorno-Karabakh conflict's cultural dimension requiring museum to document Azerbaijani historical presence in Karabakh", "Shusha's cultural significance to Azerbaijan as 'Conservatory of the Caucasus' requiring dedicated heritage institution", "Post-2023 full reintegration of Karabakh requiring comprehensive cultural infrastructure including historical museums"],
        "effects": ["Museum institutionalizing the Azerbaijani historical narrative of Karabakh countering Armenian claims", "Shusha's reconstruction as Azerbaijani cultural center including museum, mosque restoration, and cultural events", "Cultural dimension of post-conflict territorial administration including narrative control through museums and heritage sites", "International attention to questions of cultural heritage presentation in post-conflict contexts"],
        "relationships": [{"entity": "Shusha", "relationship": "LOCATED_IN_MOST_CULTURALLY_SIGNIFICANT_AZERBAIJANI_CITY_OF_KARABAKH", "note": "The museum is in Shusha, Azerbaijan's most culturally symbolic Karabakh city recaptured in May 2020"}, {"entity": "Nagorno-Karabakh Conflict", "relationship": "CULTURAL_NARRATIVE_INSTITUTION_OF_POST-CONFLICT", "note": "The museum is part of Azerbaijan's cultural narrative assertion in Karabakh following military resolution of the conflict"}, {"entity": "Azerbaijan", "relationship": "STATE_CULTURAL_INSTITUTION_ASSERTING_HISTORICAL_CLAIMS_OF", "note": "The museum presents the official Azerbaijani historical narrative of Karabakh as integral to Azerbaijani cultural territory"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Azerbaijan State Museum of History of Karabakh in Shusha — established after Azerbaijan's 2020-2023 military resolution of the Nagorno-Karabakh conflict, institutionalizing the Azerbaijani historical narrative — is historically significant as a monument to the cultural dimension of one of the post-Soviet era's most intractable territorial conflicts.", "significanceCategory": "world-changing"},
    }),
    ("azerbaijan-state-museum-of-history-of-religion", {
        "summary": "The Azerbaijan State Museum of History of Religion (Azerbaijani: Azərbaycan Dövlət Din Tarixi Muzeyi) in Baku, Azerbaijan, preserves and presents materials documenting the extraordinary religious diversity and historical evolution of religious practice in Azerbaijan — a country at the crossroads of ancient Zoroastrianism (the Ateshgah fire temple and Azerbaijan's reputation as the 'Land of Fire'), early Christianity (Caucasian Albanian Christianity), Islam (the dominant religion since the 7th-8th centuries CE), and Soviet state atheism that suppressed all religious practice for 70 years.\n\nAzerbaijan's religious history is exceptionally rich: the Baku area's natural gas vents (eternal flames) made it a sacred site of Zoroastrian fire worship from ancient times; the Ateshgah Fire Temple near Baku was used by Hindu Sikh and Zoroastrian pilgrims well into the 19th century. Caucasian Albania (the ancient Christian kingdom of what is now Azerbaijan, 1st-8th centuries CE) had its own autocephalous church tradition before being Islamicized. The country then received Shi'a Islam through Safavid Persian influence in the 16th century, making Azerbaijan (along with Iran) one of the world's predominantly Shi'a-Muslim countries.\n\nThe museum's collection spans Zoroastrian fire worship artifacts, Caucasian Albanian Christian materials, Islamic art and documents, Jewish (Mountain Jews) heritage, and materials from the Soviet atheist period. This comprehensive scope makes it one of the world's most unusual religion museums — covering the full evolutionary arc of spiritual practice in a single territory.",
        "causes": ["Azerbaijan's extraordinary religious diversity (Zoroastrian, Caucasian Albanian Christian, Shi'a Muslim) requiring comprehensive documentation", "Ateshgah fire temples and Baku's natural gas vents creating ancient Zoroastrian heritage requiring preservation", "Post-Soviet Azerbaijan's religious pluralism revival requiring institutional documentation of suppressed religious heritage", "Caucasian Albanian Christian heritage providing historical legitimacy for non-Islamic cultural claims in Azerbaijani territory"],
        "effects": ["Museum documenting the full arc of Azerbaijani religious evolution from Zoroastrianism through Christianity to Islam", "Caucasian Albanian Christian heritage presented through Azerbaijani nationalist lens in disputes with Armenian heritage claims", "Ateshgah Zoroastrian/Hindu fire temple history documented as unique world heritage combining multiple pilgrimage traditions", "Post-Soviet religious freedom restoration supported through museum's documentation of suppressed religious traditions"],
        "relationships": [{"entity": "Zoroastrianism", "relationship": "ANCIENT_RELIGIOUS_HERITAGE_OF_AZERBAIJAN_DOCUMENTED_IN", "note": "Azerbaijan's ancient Zoroastrian fire worship heritage, centered on Baku's natural gas vents, is central to the museum's collections"}, {"entity": "Caucasian Albania", "relationship": "ANCIENT_CHRISTIAN_KINGDOM'S_HERITAGE_PRESERVED_IN", "note": "The Caucasian Albanian Christian tradition (1st-8th centuries) is documented as part of Azerbaijan's pre-Islamic religious history"}, {"entity": "Shi'a Islam", "relationship": "DOMINANT_RELIGIOUS_TRADITION_OF_AZERBAIJAN_DOCUMENTED_IN", "note": "Azerbaijan's Shi'a Muslim heritage (from Safavid Persian influence) is documented alongside earlier religious traditions"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Azerbaijan State Museum of History of Religion — covering the full arc from ancient Zoroastrian fire worship through Caucasian Albanian Christianity to Shi'a Islam, documenting one of the world's most religiously diverse historical territories — is historically significant as a monument to Azerbaijan's extraordinary religious heritage spanning millennia.", "significanceCategory": "world-changing"},
    }),
    ("azerbaijan-state-museum-of-musical-culture", {
        "summary": "The Azerbaijan State Museum of Musical Culture (Azerbaijani: Azərbaycan Dövlət Musiqi Mədəniyyəti Muzeyi) in Baku, Azerbaijan, documents the rich history of Azerbaijani musical culture — encompassing the ancient mugham tradition (UNESCO Intangible Cultural Heritage), the ashik (troubadour) oral epic tradition, the tar (the Azerbaijani lute that is a national symbol), and the modern Azerbaijani classical music tradition that produced composers like Uzeyir Hajibeyov (composer of Leyli and Majnun, the first opera in the Muslim East, 1908) and Fikret Amirov.\n\nUzeyir Hajibeyov's 1908 composition of Leyli and Majnun in Baku was a watershed moment in Islamic cultural history: it was the first opera composed and performed in a Muslim-majority context, breaking the Islamic tradition's suspicion of theatrical performance involving women's voices, and creating a new form that synthesized European opera structure with Azerbaijani mugham musical tradition. This achievement placed Azerbaijan at the center of Islamic cultural modernization debates — preceding Turkey's similar experiments by decades.\n\nThe Azerbaijani mugham tradition — the sophisticated modal classical music performed by masters (khans) in intimate settings, combining instrumental improvisation with classical poetry sung in Persian or Azerbaijani — is one of the great musical traditions of the Islamic world. Recognized by UNESCO as Intangible Cultural Heritage, mugham's relationship to Persian classical music and its distinctively Azerbaijani character makes it central to Azerbaijani national identity. The museum preserves instruments, recordings, manuscripts, and documents related to this tradition.",
        "causes": ["Azerbaijani mugham tradition as UNESCO-recognized cultural heritage requiring institutional preservation", "Uzeyir Hajibeyov's 1908 first Muslim opera requiring documentary preservation as cultural watershed", "Azerbaijani classical music development under Soviet period requiring systematic documentation", "Tar and other traditional Azerbaijani instruments requiring preservation as symbols of national musical identity"],
        "effects": ["Museum documenting the full range of Azerbaijani musical culture from ancient mugham to modern classical composition", "Hajibeyov's legacy as creator of the first Muslim opera preserved as central cultural achievement", "Mugham tradition materials providing research resources for scholars of Islamic classical music", "Azerbaijani musical culture's contribution to world music heritage documented and promoted internationally"],
        "relationships": [{"entity": "Mugham", "relationship": "PRIMARY_DOCUMENTARY_INSTITUTION_FOR_AZERBAIJANI", "note": "The museum preserves materials documenting the mugham tradition, Azerbaijan's UNESCO-recognized classical music heritage"}, {"entity": "Uzeyir Hajibeyov", "relationship": "LEGACY_OF_FIRST_MUSLIM_OPERA_COMPOSER_PRESERVED_IN", "note": "Hajibeyov's 1908 Leyli and Majnun (first opera in the Muslim East) is central to the museum's collections"}, {"entity": "Azerbaijani National Identity", "relationship": "MUSICAL_CULTURAL_HERITAGE_INSTITUTIONALIZED_BY", "note": "The museum institutionalizes Azerbaijani musical heritage as a core component of national cultural identity"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Azerbaijan State Museum of Musical Culture — preserving the mugham tradition (UNESCO Intangible Heritage), Uzeyir Hajibeyov's legacy as creator of the first opera in the Muslim East, and Azerbaijani musical heritage — is historically significant as the primary institution of one of the Islamic world's most distinctive musical traditions.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 130 — Class 361 Museums V: Central Asian & Caucasian State Museums")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
