#!/usr/bin/env python3
"""Batch 101 — Class 312 Dynasties IX: Major European Royal Houses (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/312-Class-312"
FILE_PREFIX = "312"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("house-of-plantagenet", {
        "summary": "The House of Plantagenet, a dynasty of English kings who ruled from 1154 to 1485, was founded when Henry II ascended the English throne following the Anarchy (civil war between Stephen and Matilda), inheriting through his mother Empress Matilda and ruling vast territories from Ireland to the Pyrenees in what historians call the 'Angevin Empire.' During their 331-year reign, the Plantagenets produced some of England's most consequential monarchs — Richard I (Lionheart), John (who sealed Magna Carta 1215), Henry III, Edward I (Hammer of the Scots), Edward III, and the Black Prince — and fundamentally shaped English constitutional, legal, and cultural development.\n\nThe dynasty's defining achievements: Magna Carta (1215, under John) established that no one — including the king — was above the law; Edward I's Model Parliament (1295) established the principle of parliamentary consent for taxation; the reign of Edward III inaugurated the Hundred Years' War (1337-1453) with France and established English common law courts. Henry II's legal reforms (1166 Assize of Clarendon, 1176 Assize of Northampton) created the common law jury system that influenced all English-speaking legal systems.\n\nThe dynasty's later period — the Lancaster-York conflict (Wars of the Roses, 1455-1485) — saw the Plantagenet line fracture between the House of Lancaster (red rose, descended from John of Gaunt) and the House of York (white rose), ending when Henry Tudor (a Lancastrian) defeated Richard III at Bosworth Field 1485, founding the Tudor dynasty. The Plantagenet legacy persists in Magna Carta's influence on the US Constitution and the English common law tradition across the global common law world.",
        "causes": ["1154 Henry II's accession ending the Anarchy and founding Plantagenet rule", "Angevin Empire inheritance through Empress Matilda creating England-France dominion", "Magna Carta 1215 establishing constitutional limits on royal power", "Wars of the Roses (1455-1485) fragmenting the dynasty between Lancaster and York"],
        "effects": ["Magna Carta 1215 foundation of constitutional monarchy and rule of law tradition", "English common law jury system from Henry II's 1166 Assize of Clarendon", "Model Parliament 1295 establishing parliamentary consent for taxation", "Tudor dynasty founded 1485 after Plantagenet end at Bosworth Field"],
        "relationships": [{"entity": "Henry II of England", "relationship": "DYNASTY_FOUNDED_BY", "note": "Henry II's 1154 accession founded the Plantagenet dynasty; his legal reforms created common law"}, {"entity": "Magna Carta", "relationship": "PRODUCED_FOUNDATIONAL_DOCUMENT", "note": "King John's 1215 Magna Carta — world's first constitutional limitation on royal power"}, {"entity": "Tudor Dynasty", "relationship": "SUCCEEDED_BY", "note": "Henry VII's 1485 Tudor dynasty founded after Plantagenet end at Bosworth Field"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The House of Plantagenet — producing Magna Carta (foundation of constitutional law), the English common law system (governing 30% of the world's population), and parliamentary government — is one of history's most constitutionally consequential dynasties, directly shaping the US Constitution and Anglo-American legal civilization.", "significanceCategory": "world-changing"},
    }),
    ("capetian-dynasty", {
        "summary": "The Capetian dynasty (987-1328 CE), founded when Hugh Capet was elected King of France in 987 CE and ruling France continuously for 341 years — the longest unbroken royal dynasty in European history — built the French state from a weak feudal monarchy controlling only the Île-de-France region around Paris into a centralized kingdom that dominated European politics. The Capetians' patient expansion — through inheritance, conquest, and marriage — gradually absorbed Normandy, Anjou, Poitiers, Languedoc, and other territories, creating the geographic and administrative basis of modern France.\n\nKey Capetian reigns: Louis IX (Saint Louis, r. 1226-1270) — the most admired medieval French king, led two Crusades, reformed justice with the Parlement of Paris, banned trial by combat, and was canonized as a saint; Philip II Augustus (r. 1180-1223) quadrupled the crown's territory, drove the English out of Normandy (1204), and built Paris's first wall; Philip IV (r. 1285-1314) expelled the Jews (1306), destroyed the Knights Templar (1307-1314), and moved the papacy to Avignon (1309) — demonstrating the Capetians' transformation from feudal lord to Europe's most powerful monarch.\n\nThe Capetian legacy: the French administrative tradition (Parlement, royal council, tax system), the university of Paris (Sorbonne), French legal code, and the geographic consolidation of France. The dynasty ended when Charles IV died without male heirs in 1328, but Capetian cadet branches — Valois, Bourbon — continued ruling France until the French Revolution (1792) and beyond.",
        "causes": ["987 CE Hugh Capet's election as French king founding the dynasty over the Carolingian succession", "Patient territorial expansion through marriage, inheritance, and conquest over 341 years", "Philip II Augustus's expulsion of English from Normandy (1204) building the French state", "Philip IV's Templar destruction (1307) and Avignon papacy (1309) demonstrating royal supremacy"],
        "effects": ["341-year unbroken dynasty as longest continuous royal line in European history", "French administrative tradition (Parlement, royal council) shaping European governance models", "Geographic consolidation of France creating the modern French national territory", "Capetian cadet branches (Valois, Bourbon) continuing dynasty through to the French Revolution"],
        "relationships": [{"entity": "Hugh Capet", "relationship": "FOUNDED_BY", "note": "Hugh Capet's 987 CE election as king founded the dynasty that ruled France for 341 years"}, {"entity": "Louis IX of France", "relationship": "PEAK_RULER", "note": "Saint Louis (1226-1270) was the most admired Capetian king; canonized as a saint"}, {"entity": "French Revolution", "relationship": "CADET_BRANCHES_RULED_UNTIL", "note": "Capetian cadet branches Valois and Bourbon ruled France until the 1792 Revolution"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Capetian dynasty — ruling France unbroken for 341 years and building the French state from a small Île-de-France lordship to Europe's dominant kingdom — created the administrative and geographic foundations of France that persist to the present, making it one of history's most consequential state-building dynasties.", "significanceCategory": "world-changing"},
    }),
    ("house-of-bourbon", {
        "summary": "The House of Bourbon, a cadet branch of the Capetian dynasty that rose to ruling prominence when Henry IV (Henry of Navarre) united the French crown and his Bourbon inheritance in 1589 following the Wars of Religion, subsequently produced the longest-ruling royal house of France (1589-1792, 1814-1830), the royal family of Spain (from Philip V, 1700-present, making it Europe's longest-continuing royal dynasty), and the royal families of Naples, Two Sicilies, Parma, and Luxembourg — making the Bourbons the most widely distributed royal house in European history.\n\nThe French Bourbons' defining moments: Henry IV's Edict of Nantes (1598) granting religious toleration to Huguenots — ending 36 years of religious civil war; Louis XIV (the Sun King, r. 1643-1715) — the epitome of European absolute monarchy, building Versailles as the model for European courts, reorganizing France's entire administrative system, and centralizing power so thoroughly he reportedly said 'L'état, c'est moi' ('I am the state'); Louis XVI's 1789 execution — the most consequential royal execution in modern history, inaugurating the French Revolutionary period.\n\nThe Spanish Bourbons (since Philip V, 1700) transformed Spain into a more centralized state following the War of the Spanish Succession (1701-1714). The current King of Spain Felipe VI (b. 1968) continues the Bourbon line, making Spain's royal family the last surviving European Bourbon monarchy and the only royal house founded after a major European war (War of Spanish Succession) still ruling its original kingdom.",
        "causes": ["Henry IV's 1589 accession uniting Navarre and France in Bourbon hands ending Wars of Religion", "Edict of Nantes 1598 establishing religious toleration as model of state-managed pluralism", "Louis XIV's absolutism (1643-1715) building Versailles and centralizing French royal power", "Philip V's 1700 accession beginning Bourbon dynasty in Spain after War of Spanish Succession"],
        "effects": ["Most widely distributed royal house — France, Spain, Naples, Parma, Luxembourg", "Versailles model influencing European absolutist court culture across 18th century", "Louis XVI's 1789 execution inaugurating French Revolutionary period and modern age", "Spanish Bourbon continuity (1700-present) as Europe's longest-surviving royal dynasty"],
        "relationships": [{"entity": "Henry IV of France", "relationship": "FRENCH_LINE_FOUNDED_BY", "note": "Henry IV's 1589 accession united Navarre and France under Bourbon rule; issued Edict of Nantes"}, {"entity": "Louis XIV of France", "relationship": "ABSOLUTE_MONARCHY_EPITOME", "note": "Sun King (1643-1715) built Versailles; his absolutism was the model for European monarchy"}, {"entity": "Felipe VI of Spain", "relationship": "CURRENT_REPRESENTATIVE", "note": "Current King of Spain (b. 1968) continues unbroken Bourbon line since Philip V (1700)"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The House of Bourbon — producing Louis XIV's model absolutism, Henry IV's religious toleration, Louis XVI's revolutionary execution, and continuing today in Spain — is the most widely distributed royal house in European history and the only one whose founding dynasty (1700) still rules its original kingdom, making it a unique bridge between early modern and contemporary European history.", "significanceCategory": "world-changing"},
    }),
    ("house-of-habsburg", {
        "summary": "The House of Habsburg (also Habsburg-Lorraine from 1736), originally a Swiss noble family that rose through marriage to control the Holy Roman Empire nearly continuously from 1438 to 1806 (368 years), was at its 16th-century peak under Charles V (r. 1519-1556) simultaneously ruling Spain, the Americas, Italy, the Netherlands, Austria, and Burgundy — the largest empire in European history at that point. The Habsburg Empire's dissolution in 1918 ended one of history's longest-ruling dynasties and its breakup created many of modern Central Europe's nation-states.\n\nThe Habsburgs' dynastic strategy — 'Bella gerant alii, tu felix Austria nube' ('Let others wage war; you, happy Austria, marry') — relied on marriage diplomacy: Charles V inherited Spain from his grandmother Isabella, Austria from his grandfather Maximilian, the Netherlands from his grandmother Mary of Burgundy, and Burgundy from the same source. This marriage empire required constant resource mobilization; Charles V spent 40 of his 56 years of reign at war.\n\nThe Habsburg legacy: the Austro-Hungarian Empire (1867-1918) was Europe's second-largest state and governed 11 national languages; its dissolution created Austria, Hungary, Czechoslovakia, Yugoslavia, Poland (partial), Romania (partial), and Italy (partial). The Habsburgs also shaped global history through the Spanish branch: Charles V's Spanish empire funded the conquest of the Americas; the Spanish Habsburgs ruled the Philippines (named for Philip II) and shaped Latin American civilization. The House continues as a private family today; Archduke Karl von Habsburg is its current head.",
        "causes": ["Marriage diplomacy 'Bella gerant alii, tu felix Austria nube' building empire without war", "Charles V inheriting Spain, Austria, Netherlands, Burgundy creating the largest European empire", "Holy Roman Empire near-continuous Habsburg rule (1438-1806) creating Central European dominance", "Austro-Hungarian Compromise 1867 extending dynasty into 20th century"],
        "effects": ["Charles V's empire creating largest European territorial domain in 16th century", "Spanish Habsburg colonization of the Americas shaping Latin American civilization", "Austro-Hungarian Empire dissolution 1918 creating modern Central European nation-states", "Habsburg legacy governing 50+ million people across 11 languages in 1914"],
        "relationships": [{"entity": "Charles V, Holy Roman Emperor", "relationship": "DYNASTY_PEAK_RULER", "note": "Charles V's 1519-1556 empire — largest in European history — spanned four continents"}, {"entity": "Austro-Hungarian Empire", "relationship": "FINAL_FORM_OF", "note": "Austro-Hungarian Empire (1867-1918) was the Habsburg dynasty's final incarnation before 1918 dissolution"}, {"entity": "Holy Roman Empire", "relationship": "RULED_NEARLY_CONTINUOUSLY", "note": "Habsburgs ruled Holy Roman Empire nearly continuously 1438-1806 (368 years)"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The House of Habsburg — governing the largest European empire (under Charles V), ruling the Holy Roman Empire for 368 years, shaping Latin American civilization through the Spanish branch, and creating modern Central Europe through the 1918 dissolution — is one of history's most consequential dynasties, governing more diverse peoples for longer than almost any other European house.", "significanceCategory": "world-changing"},
    }),
    ("house-of-romanov", {
        "summary": "The House of Romanov, Russia's ruling dynasty from Michael Romanov's election by the Zemsky Sobor (1613) following the Time of Troubles (a succession crisis) until Nicholas II's abdication (1917) and execution (1918), ruled Russia for 304 years through its transformation from a backward Muscovite principality into a European great power and the world's largest territorial state. The Romanovs' reign encompasses Russia's European emergence under Peter the Great, Catherine the Great's Enlightenment absolutism, the Napoleonic Wars, the emancipation of serfs (1861), and the 1917 Revolution that ended the dynasty.\n\nKey Romanov reigns: Peter the Great (r. 1682-1725) Westernized Russia, built St. Petersburg (on land conquered from Sweden), established the Russian Navy, and personally led military campaigns — transforming Russia into a Baltic power; Catherine the Great (r. 1762-1796) — actually a German princess (Sophia of Anhalt-Zerbst) who had her husband Peter III murdered/deposed — expanded Russia's borders to the Black Sea, partitioned Poland three times, and maintained correspondence with Voltaire and Diderot while suppressing the Pugachev Rebellion.\n\nThe dynasty's end: Nicholas II's disastrous military leadership in WWI (1914-1917), combined with food shortages, military mutinies, and the Rasputin scandal, led to the February Revolution (1917); Nicholas abdicated March 1917. The Bolsheviks executed Nicholas, his wife Alexandra, and their five children (including Anastasia) at Yekaterinburg on July 17, 1918 — one of history's most consequential royal executions, inaugurating Soviet Russia. Romanov descendants (via Nicholas II's siblings) survive today as claimants to a restored Russian throne.",
        "causes": ["1613 Zemsky Sobor election following the Time of Troubles founding Romanov rule", "Peter the Great's Westernization and St. Petersburg founding establishing Russia as European power", "Emancipation of serfs (1861) as the dynasty's most consequential domestic reform", "WWI military failures and Rasputin scandal causing 1917 Revolution and dynasty's end"],
        "effects": ["Russia's transformation from Muscovite principality to world's largest territorial state", "St. Petersburg as European capital and Russia's 'window to Europe' for 200+ years", "1918 Yekaterinburg execution of Nicholas II family inaugurating Soviet Russia", "Romanov legacy shaping Russian national identity and 21st-century restoration debates"],
        "relationships": [{"entity": "Peter the Great", "relationship": "DYNASTY_TRANSFORMED_BY", "note": "Peter (1682-1725) Westernized Russia, built St. Petersburg, and made Russia a Baltic power"}, {"entity": "Catherine the Great", "relationship": "ENLIGHTENED_ABSOLUTISM_UNDER", "note": "Catherine (1762-1796) expanded to Black Sea, partitioned Poland, and corresponded with philosophes"}, {"entity": "Nicholas II of Russia", "relationship": "LAST_RULER", "note": "Nicholas II abdicated 1917; he and his family were executed by Bolsheviks July 17, 1918"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The House of Romanov — ruling Russia's transformation from feudal principality to world superpower across 304 years, ending in the Bolshevik execution that inaugurated Soviet Russia — is one of history's most consequential dynasties, and its collapse is one of the defining moments of 20th-century history.", "significanceCategory": "world-changing"},
    }),
    ("house-of-hohenzollern", {
        "summary": "The House of Hohenzollern, originally a Swabian noble family that rose to rule Brandenburg (from 1415), Prussia (from 1618), and ultimately the German Empire (1871-1918), transformed from a minor German principality into Europe's most militaristic great power in 250 years. The Hohenzollerns built the Prussian military state — known for the phrase attributed to Voltaire ('Where some states have an army, the Prussian army has a state') — and under Wilhelm I and Bismarck unified the German states into the German Empire (1871), creating modern Germany.\n\nThe dynasty's defining rulers: Frederick the Great (r. 1740-1786) — the paradigmatic 'enlightened despot,' musician, philosopher, and military genius who seized Silesia from Austria (1740), survived the Seven Years' War against France, Austria, Russia, and Sweden simultaneously, and doubled Prussia's size; Otto von Bismarck's master-diplomacy under Wilhelm I (1861-1888) — three wars (Danish War 1864, Austro-Prussian War 1866, Franco-Prussian War 1870-71) in 7 years unified Germany.\n\nWilhelm II (r. 1888-1918) — aggressive, impulsive, and obsessed with naval expansion — is historians' foremost example of a ruler whose personality shaped world events: his dismissal of Bismarck (1890), his naval arms race with Britain (driving the Anglo-French Entente), and his 'blank check' to Austria in July 1914 contributed directly to WWI. His abdication November 9, 1918 — the same day the German Republic was proclaimed — ended both the dynasty and the German Empire. The house's legacy is thus inseparable from WWI, the German defeat, and the conditions that led to WWII.",
        "causes": ["1415 Brandenburg acquisition beginning Hohenzollern rise to German power", "Frederick the Great's Silesian seizure (1740) and Seven Years' War survival making Prussia a great power", "Bismarck's three-war unification strategy (1864-1871) creating the German Empire", "Wilhelm II's naval expansion and July 1914 blank check contributing directly to WWI"],
        "effects": ["German Empire 1871 unification creating modern Germany through military force", "Prussian military culture ('the army has a state') influencing German political culture", "WWI German defeat and November 1918 abdication ending the dynasty", "Wilhelm II legacy as warning about autocratic rulers in modern industrial states"],
        "relationships": [{"entity": "Frederick the Great", "relationship": "DYNASTY_TRANSFORMED_BY", "note": "Frederick (1740-1786) seized Silesia and survived the Seven Years' War, creating Prussian great-power status"}, {"entity": "Otto von Bismarck", "relationship": "UNIFICATION_CHANCELLOR_UNDER", "note": "Bismarck unified Germany under Wilhelm I through three wars (1864-1871)"}, {"entity": "Wilhelm II of Germany", "relationship": "DYNASTY_ENDED_BY_RULE_OF", "note": "Wilhelm II's 1918 abdication ended both the dynasty and the German Empire after WWI defeat"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The House of Hohenzollern — building Europe's most militaristic state, unifying Germany under Bismarck, and ending in WWI's catastrophe — shaped 20th-century world history more than almost any dynasty: its military culture, unification, and Wilhelm II's role in WWI directly caused the chain that led to the Second World War and the Holocaust.", "significanceCategory": "world-changing"},
    }),
    ("flavian-dynasty", {
        "summary": "The Flavian dynasty (69-96 CE), founded by Vespasian after the Year of the Four Emperors (69 CE) — the chaotic year when four men claimed the Roman Empire in succession (Galba, Otho, Vitellius, Vespasian) following Nero's suicide — ruled Rome for 27 years through three emperors: Vespasian (69-79 CE), Titus (79-81 CE), and Domitian (81-96 CE). Despite its short duration, the Flavian dynasty accomplished the greatest construction project in Roman history (the Colosseum), suppressed the Jewish Revolt with the destruction of Jerusalem (70 CE), and survived the Vesuvius eruption (79 CE) that destroyed Pompeii and Herculaneum.\n\nVespasian (r. 69-79 CE) was a practical, frugal emperor who restored financial stability after the civil wars and began construction of the Flavian Amphitheatre (Colosseum); his son Titus completed it. The Colosseum — completed 80 CE and inaugurated with 100 days of games — remains the world's most iconic ancient building and the architectural symbol of Rome. Titus's brief reign (79-81 CE) was marked by the Vesuvius eruption (August 24, 79 CE) that buried Pompeii, Herculaneum, and Stabiae — preserving a snapshot of Roman urban life that has shaped archaeology and our understanding of ancient Rome.\n\nDomitian (81-96 CE) — Titus's younger brother — ruled increasingly autocratically, claiming the title 'dominus et deus' ('lord and god'), persecuting senators and Christians, and was assassinated by his own court officials in 96 CE. His assassination inaugurated the reign of the Five Good Emperors (Nerva, Trajan, Hadrian, Antoninus Pius, Marcus Aurelius) — considered Rome's golden age — making the Flavian dynasty the transition between the troubled Julio-Claudians and Rome's imperial peak.",
        "causes": ["69 CE Year of Four Emperors following Nero's suicide establishing Vespasian's rule", "Vespasian's fiscal competence restoring Roman stability after civil war devastation", "Jewish Revolt suppression (70 CE) destruction of Jerusalem Temple shaping Jewish history", "79 CE Vesuvius eruption preserving Pompeii as world's best Roman archaeological site"],
        "effects": ["Colosseum (80 CE) as world's most iconic ancient building and Roman architectural symbol", "Pompeii preservation as most complete Roman urban site shaping archaeological understanding", "Destruction of Jerusalem's Temple (70 CE) pivotal event in Jewish and Christian history", "Domitian's assassination inaugurating Five Good Emperors and Rome's imperial golden age"],
        "relationships": [{"entity": "Colosseum", "relationship": "BUILT_BY", "note": "Vespasian began and Titus completed the Colosseum (80 CE) — Rome's most iconic ancient monument"}, {"entity": "Pompeii", "relationship": "PRESERVED_BY_VESUVIUS_ERUPTION_UNDER", "note": "Titus's 79 CE Vesuvius eruption preserved Pompeii as history's most complete Roman city"}, {"entity": "Destruction of the Temple", "relationship": "ORDERED_DESTRUCTION_OF", "note": "Titus destroyed Jerusalem's Second Temple in 70 CE — pivotal event in Jewish and Christian history"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Flavian dynasty — building the Colosseum (world's most iconic ancient monument), presiding over Pompeii's destruction that preserved the best Roman urban site, and destroying Jerusalem's Temple in 70 CE — created three of antiquity's most consequential physical legacies in just 27 years.", "significanceCategory": "world-changing"},
    }),
    ("julio-claudian-dynasty", {
        "summary": "The Julio-Claudian dynasty (27 BCE - 68 CE), Rome's first imperial dynasty founded when Augustus Caesar (Octavian) ended the Republic by defeating Mark Antony and Cleopatra at Actium (31 BCE) and establishing the Principate, ruled Rome through five emperors — Augustus, Tiberius, Caligula, Claudius, and Nero — during the period when Rome completed its transformation from Republic to Empire and Christian civilization began. The dynasty's 95-year reign encompassed the Pax Romana's beginning, the birth of Jesus Christ, and the first Christian persecutions.\n\nAugustus (r. 27 BCE - 14 CE) — the most successful statesman in Western history — created the imperial system while maintaining the fiction of republican government ('first citizen,' not king), reformed the Roman army into a permanent professional force, inaugurated the Pax Romana (200 years of relative peace), rebuilt Rome ('I found Rome brick, I left it marble'), and presided over Virgil, Horace, Livy, and Ovid's Golden Age. The population of the empire at his death was ~50-70 million.\n\nCaligula (r. 37-41 CE) and Nero (r. 54-68 CE) — the dynasty's most notorious emperors — represent the pathological potential of absolute power: Caligula's madness, cruelty, and possible incest; Nero's murder of his mother Agrippina, his persecution of Christians (blaming them for the 64 CE Rome fire), and his suicide ('What an artist dies with me!') ending the dynasty. The Julio-Claudian period thus established both the heights and depths of Roman imperial governance, directly shaping Western political thought about tyranny, virtue, and the dangers of unchecked power.",
        "causes": ["31 BCE Actium defeat of Antony and Cleopatra founding Augustus's empire", "Augustus's Principate fiction maintaining republican forms while establishing imperial reality", "Birth of Jesus Christ (~4 BCE) and crucifixion (~33 CE) within dynasty's reign", "Nero's persecution of Christians (64 CE) as first state persecution of Christianity"],
        "effects": ["Pax Romana beginning under Augustus — 200 years of relative Roman peace", "Roman administrative system (provinces, legions, census) shaping Western governance", "Caligula and Nero as archetypes of tyranny in Western political philosophy", "Nero's 64 CE Christian persecution founding martyrology tradition in Christianity"],
        "relationships": [{"entity": "Augustus Caesar", "relationship": "FOUNDED_BY", "note": "Augustus's 27 BCE Principate founded the imperial system; his reign was Rome's model of wise governance"}, {"entity": "Jesus Christ", "relationship": "CONTEMPORARY_WITH", "note": "Jesus was born, preached, and was crucified (under Pontius Pilate) during the Julio-Claudian dynasty"}, {"entity": "Nero", "relationship": "DYNASTY_ENDED_BY_RULE_OF", "note": "Nero's 68 CE suicide after military revolts ended the Julio-Claudian line"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Julio-Claudian dynasty — creating the Roman imperial system under Augustus, providing the political context for Jesus Christ's birth and crucifixion, and establishing the archetypes of both virtuous governance (Augustus) and tyranny (Caligula, Nero) that shaped Western political philosophy for 2,000 years — is one of history's most consequential ruling houses.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 101 — Class 312 Dynasties IX: European Royal Houses")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
