#!/usr/bin/env python3
"""Batch 90 — Class 364 Studios & Publishers III (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/364-Class-364"
FILE_PREFIX = "364"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("hbo", {
        "summary": "HBO (Home Box Office), launched in 1972 as the first American cable television network and now owned by Warner Bros. Discovery, is the most critically acclaimed television network in history — producing The Sopranos, The Wire, Sex and the City, Game of Thrones, Succession, and The White Lotus across 50+ years of prestige television that redefined what the medium could achieve. HBO's 'It's Not TV. It's HBO.' slogan (launched 1996) articulated a genuine quality distinction that the Emmys have confirmed: HBO has won more Emmy Awards than any other network in history.\n\nHBO's business model innovation preceded its artistic one: as a pay-cable subscription service (not advertising-supported), HBO could produce content for subscriber retention rather than mass audience ratings — allowing explicit content, morally complex characters, and narrative risk impossible on broadcast television. The Sopranos (1999-2007) created the template for prestige television drama; The Wire (2002-2008) is consistently rated the greatest television drama ever made; Game of Thrones (2011-2019) achieved the largest simultaneous global television audience in history (estimated 44 million per episode).\n\nHBO's streaming service HBO Max (now Max) launched in 2020 with 76.8 million subscribers. The network has received 2,700+ Emmy nominations and won 600+ Emmy Awards. Its impact extends beyond television: HBO's success demonstrated that subscription television could generate greater artistic freedom than advertising-supported models, directly inspiring Netflix, Amazon Prime, and Apple TV+ to adopt subscription-based prestige content strategies.",
        "causes": ["1972 launch as first American cable network enabling subscription rather than advertising-based model", "The Sopranos 1999 creating prestige TV template and Emmy-winning drama standard", "Game of Thrones 2011-2019 achieving 44 million simultaneous viewers making HBO globally dominant", "HBO Max 2020 streaming launch with 76.8 million subscribers transitioning to digital distribution"],
        "effects": ["600+ Emmy Awards making HBO most decorated television network in history", "Sopranos and Wire templates inspiring Netflix, Amazon, Apple TV+ prestige content strategies", "Game of Thrones 44-million viewer record demonstrating pay television's global scale", "Subscription model demonstrating advertising-free television enables greater artistic freedom"],
        "relationships": [{"entity": "The Sopranos", "relationship": "PRODUCED", "note": "Sopranos (1999-2007) created prestige TV template and is HBO's most influential production"}, {"entity": "Game of Thrones", "relationship": "PRODUCED", "note": "Game of Thrones (2011-2019) reached 44 million simultaneous viewers making HBO globally dominant"}, {"entity": "Warner Bros. Discovery", "relationship": "OWNED_BY", "note": "Warner Bros. Discovery acquired HBO through WarnerMedia merger, now operating Max streaming"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "HBO's subscription model — producing The Sopranos, The Wire, and Game of Thrones for subscriber retention rather than advertising ratings — proved that commercial television could achieve artistic excellence, inspiring Netflix and Amazon to transform global media into a prestige content competition.", "significanceCategory": "world-changing"},
    }),
    ("lionsgate-films", {
        "summary": "Lionsgate Films, founded in Vancouver in 1997 and now headquartered in Santa Monica, is the largest independent film studio in Hollywood — producing Saw (2004), Hostel (2005), Crash (2004 Best Picture), The Hunger Games franchise ($2.95 billion worldwide), the Twilight franchise ($3.3 billion), and John Wick franchise, while also distributing Michael Moore's Fahrenheit 9/11 (the highest-grossing documentary in US history). Lionsgate's success demonstrated that an independent studio could compete with the six major studios by identifying genre niches (horror, action, young adult) and executing them efficiently.\n\nLionsgate was founded by Frank Giustra with Jon Feltheimer as CEO, growing rapidly through acquisitions including Artisan Entertainment (2003, gaining American History X, Pi, and The Blair Witch Project's library), Trimark Pictures, and Summit Entertainment (2012, gaining Twilight). The studio's horror strategy — low-budget, high-return R-rated films — was perfected with Saw ($103 million worldwide on $1.2 million budget) and continued with 7 sequels grossing $980 million total.\n\nThe Hunger Games ($2.95 billion worldwide) and Twilight ($3.3 billion) demonstrated Lionsgate's ability to acquire and execute young adult (YA) franchise properties before the major studios recognized the genre's potential. Lionsgate's STARZ acquisition (2016, $4.4 billion) and STARZ streaming platform (now 41+ million subscribers) transformed it from pure film studio to diversified media company. The John Wick franchise ($1+ billion) demonstrated Lionsgate's ability to launch original franchises.",
        "causes": ["1997 Vancouver founding by Frank Giustra as Canadian independent studio", "Artisan Entertainment 2003 acquisition gaining horror and indie film library", "Saw 2004 low-budget horror success establishing franchise model", "Summit Entertainment 2012 acquisition including Twilight franchise"],
        "effects": ["Hunger Games $2.95 billion and Twilight $3.3 billion demonstrating YA franchise value before major studios", "Saw franchise $980 million total from $1.2 million original budget demonstrating horror economics", "STARZ 2016 acquisition creating diversified media company with 41+ million streaming subscribers", "John Wick franchise demonstrating independent studio capacity to create original action franchises"],
        "relationships": [{"entity": "Jon Feltheimer", "relationship": "LED_BY", "note": "Feltheimer as CEO oversaw Lionsgate's growth into largest independent Hollywood studio"}, {"entity": "The Hunger Games", "relationship": "PRODUCED", "note": "Hunger Games franchise $2.95 billion demonstrated YA property value before major studios noticed"}, {"entity": "STARZ", "relationship": "ACQUIRED", "note": "2016 $4.4 billion STARZ acquisition transformed Lionsgate into diversified media company"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Lionsgate's identification of horror and young adult franchise niches before the major studios — Saw, Twilight, Hunger Games — demonstrates the independent studio's capacity to outmaneuver larger rivals through genre specialization and swift execution.", "significanceCategory": "continental"},
    }),
    ("universal-pictures", {
        "summary": "Universal Pictures, founded in 1912 by Carl Laemmle as one of Hollywood's original studios, is the world's oldest and one of the highest-grossing film studios — producing Jaws (1975), E.T. (1982), Jurassic Park (1993), the Fast & Furious franchise ($7+ billion), the Despicable Me franchise ($3.7+ billion), and the Universal Classic Monsters (Dracula, Frankenstein, The Mummy) that defined horror cinema's golden age. Universal's history encompasses 110+ years of American cinema, from silent nickelodeon to streaming, and the Jurassic World Evolution theme park business.\n\nCarl Laemmle's Universal Film Manufacturing Company opened Universal City (1915) — Hollywood's first purpose-built studio with public tours that continue today — establishing the studio tour model. Universal's 1931-1936 Classic Monsters cycle (Dracula with Bela Lugosi, Frankenstein with Boris Karloff, The Mummy, The Wolf Man) created the horror genre's foundational archetypes. Steven Spielberg's Jaws (1975, $476 million worldwide on $9 million budget, Universal) invented the summer blockbuster model that still governs studio economics.\n\nUniversal's NBCUniversal acquisition by Comcast (2011, $30 billion) gave it cable television assets alongside film. The Jurassic World and Fast & Furious franchises — each exceeding $7 billion worldwide — demonstrated Universal's 21st-century franchise ability. Universal's theme park business (Universal Studios Hollywood, Universal Orlando, Universal Japan) generates $5+ billion annually, with Jurassic World attractions using the film brand to create physical entertainment. Peacock streaming (launched 2020) added Universal's content to the streaming wars.",
        "causes": ["1912 founding by Carl Laemmle as one of Hollywood's original studios", "1931-1936 Classic Monsters cycle establishing horror genre's foundational archetypes", "Jaws 1975 inventing summer blockbuster model governing studio economics", "Fast & Furious and Jurassic World franchises each exceeding $7 billion in 21st century"],
        "effects": ["110+ year history as world's oldest major film studio", "Classic Monsters defining horror cinema's archetypal characters from Dracula to Frankenstein", "Jaws summer blockbuster invention transforming studio release strategy", "Theme park business generating $5+ billion annually extending film brands to physical entertainment"],
        "relationships": [{"entity": "Carl Laemmle", "relationship": "FOUNDED_BY", "note": "Laemmle founded Universal in 1912 and opened Universal City — Hollywood's first studio with tours — in 1915"}, {"entity": "Steven Spielberg", "relationship": "DEFINING_DIRECTOR", "note": "Spielberg's Jaws (1975) at Universal invented the summer blockbuster model"}, {"entity": "Comcast", "relationship": "OWNED_BY", "note": "Comcast acquired Universal through $30 billion NBCUniversal purchase in 2011"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Universal Pictures' 110-year history — from Laemmle's nickelodeon era through Classic Monsters to Jaws's summer blockbuster invention to Jurassic World's theme park empire — spans the entire arc of American cinema, making Universal the studio whose history most completely encodes Hollywood's evolution.", "significanceCategory": "world-changing"},
    }),
    ("warner-bros-entertainment", {
        "summary": "Warner Bros. Entertainment, founded in 1923 by the four Warner brothers (Harry, Albert, Sam, Jack) and now part of Warner Bros. Discovery, is the studio that introduced synchronized sound to cinema (The Jazz Singer, 1927), created the gangster film genre (Little Caesar, The Public Enemy, 1931), and produced the highest-grossing film franchise in history (the DC Extended Universe, Harry Potter franchise at $9.7 billion, and Looney Tunes), making it one of the most consequential creative institutions of the 20th century. The 1927 Jazz Singer — featuring Al Jolson speaking (not just singing) — ended the silent film era overnight.\n\nThe Jazz Singer (1927) was not the first sound film but the first commercially successful one — Warner Bros. had bet the company on the Vitaphone synchronized-sound system, nearly bankrupting itself. The gamble succeeded beyond imagination: silent cinema ended within two years. Warner's 1930s gangster cycle (James Cagney, Edward G. Robinson, Humphrey Bogart) defined American cinema's most influential genre. Casablanca (1942) is consistently voted one of the greatest films ever made; Citizen Kane was distributed (not produced) by RKO but Warner produced comparable landmark films.\n\nWarner's DC Comics ownership (Superman 1978, Batman 1989, Dark Knight trilogy, Aquaman, Wonder Woman) and Harry Potter ($9.7 billion franchise from J.K. Rowling's books) plus Looney Tunes (Bugs Bunny, Daffy Duck) give it three of entertainment's most commercially durable franchises. The AT&T acquisition (2018, $85 billion) and subsequent Discovery merger (2022) transformed Warner into Warner Bros. Discovery, with the HBO Max (now Max) streaming service competing with Netflix.",
        "causes": ["1923 founding by four Warner brothers as Hollywood studio", "The Jazz Singer 1927 synchronized sound introduction ending silent cinema era", "1930s gangster cycle defining American cinema's most influential genre", "DC Comics and Harry Potter franchise acquisitions creating $9.7 billion+ franchise values"],
        "effects": ["Silent cinema's end after Jazz Singer commercial success transforming entire industry within two years", "Casablanca and Warner gangster films defining American cinema's Golden Age", "Harry Potter $9.7 billion franchise and DC Extended Universe dominating superhero era", "AT&T $85 billion acquisition and Discovery merger creating Warner Bros. Discovery streaming competitor"],
        "relationships": [{"entity": "Al Jolson", "relationship": "STAR_OF_SOUND_REVOLUTION", "note": "Jolson's The Jazz Singer (1927) at Warner Bros. commercially ended silent cinema era"}, {"entity": "J.K. Rowling", "relationship": "SOURCE_FOR_FRANCHISE", "note": "Harry Potter adaptation ($9.7 billion) is Warner's most commercially successful book-to-film franchise"}, {"entity": "Warner Bros. Discovery", "relationship": "NOW_PART_OF", "note": "AT&T $85 billion acquisition (2018) and Discovery merger (2022) created current parent company"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Warner Bros.' introduction of synchronized sound in The Jazz Singer (1927) — which ended silent cinema overnight — is the single most disruptive technological event in film history, and the studio's subsequent 100-year run from gangster films to Harry Potter makes it American cinema's most historically consequential studio.", "significanceCategory": "world-changing"},
    }),
    ("national-geographic-society", {
        "summary": "The National Geographic Society, founded in Washington D.C. in 1888 'for the increase and diffusion of geographic knowledge,' is one of the world's largest nonprofit scientific and educational institutions — funding 15,000+ research, exploration, and conservation projects, publishing the National Geographic magazine (since 1888, 35 million global circulation at peak), producing iconic wildlife photography, and now operating National Geographic cable channels and streaming through a Disney majority partnership. The yellow-bordered magazine cover is one of the most recognized design elements in publishing history.\n\nNational Geographic's founding membership of 33 geographers, explorers, and scientists grew rapidly after Gilbert Grosvenor (editor 1899-1954) introduced photographic illustration — revolutionary for 1900s magazines — making geographic exploration visual and accessible. The magazine's photography — from Luis Marden's 1956 discovery of the Bounty wreck, to the 1984 'Afghan Girl' portrait, to Jane Goodall's chimpanzee photos — created icons of environmental consciousness and cultural encounter.\n\nNational Geographic's scientific contributions include: funding Robert Peary's (disputed) 1909 North Pole expedition, Jacques Cousteau's undersea films, Richard Leakey's Kenyan fossil discoveries, and Jane Goodall's chimpanzee research. The 1984 'Afghan Girl' (Sharbat Gula, photographed by Steve McCurry) is the most recognized magazine cover photograph ever taken. National Geographic's partnership with Disney (launched 2019, 73% Disney ownership) merged it with Disney's streaming strategy while the Society retains its scientific grant-making mission through the National Geographic Foundation.",
        "causes": ["1888 Washington D.C. founding by 33 geographers for geographic knowledge diffusion", "Gilbert Grosvenor's 1899-1954 editorship introducing photography making exploration visual", "Afghan Girl 1984 photograph becoming most recognized magazine cover ever taken", "Disney 2019 partnership (73% ownership) integrating into streaming strategy"],
        "effects": ["35 million peak global circulation making National Geographic one of world's most distributed magazines", "15,000+ funded projects making Society major source of geographic and conservation research", "Wildlife photography creating icons of environmental consciousness globally", "Yellow-bordered cover becoming one of most recognized design elements in publishing history"],
        "relationships": [{"entity": "Gilbert Grosvenor", "relationship": "TRANSFORMED_BY_EDITOR", "note": "Grosvenor's 55-year editorship introduced photography making National Geographic a visual institution"}, {"entity": "Jane Goodall", "relationship": "RESEARCH_FUNDED", "note": "National Geographic funded Goodall's chimpanzee research creating most important primatology science"}, {"entity": "The Walt Disney Company", "relationship": "MAJORITY_PARTNER", "note": "2019 Disney acquired 73% stake integrating National Geographic into Disney streaming strategy"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "National Geographic Society's marriage of scientific exploration and photographic storytelling — from Peary's North Pole to Goodall's chimpanzees to the Afghan Girl — created the world's most powerful visual record of geographic and environmental knowledge, making exploration emotionally accessible to millions.", "significanceCategory": "world-changing"},
    }),
    ("showtime", {
        "summary": "Showtime Networks Inc., launched in 1976 as America's second premium cable channel (after HBO) and now owned by Paramount Global, is the premium television network that produced Dexter, Homeland, Billions, Shameless (US), The Affair, and Nurse Jackie — building a prestige television identity focused on moral complexity and protagonist anti-heroes. Showtime's business model — subscription premium cable without advertising — mirrors HBO's, but Showtime carved a distinct brand identity through crime drama and political thriller rather than HBO's literary prestige.\n\nShowtime's 1984 addition of SHO 2 (now Showtime 2) and subsequent multiplex channels created a multi-feed premium model. The network's original programming breakthrough came with Queer as Folk (2000-2005) — the first US drama with gay characters as primary protagonists, predating broader LGBTQ+ representation in American television by a decade. The L Word (2004-2009) similarly pioneered lesbian representation. Showtime's identity as a network willing to tackle marginalized perspectives preceded similar moves by broadcast and basic cable networks.\n\nDexter (2006-2013) — a serial killer working for Miami Metro Police — was Showtime's highest-rated series and defined the anti-hero crime drama genre alongside Breaking Bad. Homeland (2011-2020, 8 seasons) won the Golden Globe and Emmy for Best Drama Series in 2012. Billions (2016-ongoing) created the finance drama genre. Showtime's 2023 merger with Paramount+ created a combined streaming service, integrating Showtime's premium content library with Paramount's broader entertainment assets.",
        "causes": ["1976 launch as America's second premium cable channel after HBO", "Queer as Folk 2000 pioneering LGBTQ+ protagonist representation decade before mainstream television", "Dexter 2006 defining anti-hero crime drama genre alongside Breaking Bad", "Homeland 2011 winning Best Drama Emmy demonstrating political thriller prestige"],
        "effects": ["LGBTQ+ representation pioneer through Queer as Folk and L Word shaping television representation norms", "Dexter anti-hero model influencing crime drama television globally", "Homeland's Emmy win establishing political thriller as prestige television genre", "Paramount+ merger 2023 integrating premium cable into streaming distribution"],
        "relationships": [{"entity": "Dexter", "relationship": "PRODUCED", "note": "Dexter (2006-2013) was Showtime's highest-rated series and defined anti-hero crime drama"}, {"entity": "Homeland", "relationship": "PRODUCED", "note": "Homeland (2011-2020) won Emmy and Golden Globe for Best Drama, establishing political thriller prestige"}, {"entity": "Paramount Global", "relationship": "OWNED_BY", "note": "Paramount Global owns Showtime following merger with Paramount+ streaming service"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Showtime's pioneering LGBTQ+ representation through Queer as Folk and The L Word — a decade before mainstream television followed — demonstrates how premium subscription television's advertising-free model enables cultural risk-taking that transforms representation norms.", "significanceCategory": "continental"},
    }),
    ("touchstone-pictures", {
        "summary": "Touchstone Pictures, a Walt Disney Company label launched in 1984 specifically to produce R-rated and PG-13 films without Disney's family-friendly brand constraint, released Splash (1984), Down and Out in Beverly Hills (1986), Good Morning Vietnam (1987), Dead Poets Society (1989), Pretty Woman (1990), and The Sixth Sense (1999) — films that would have been impossible under Disney's core brand but were commercially essential for Disney's adult audience strategy. Touchstone was a creative solution to the brand management challenge of a family entertainment company wanting adult market share.\n\nDisney CEO Michael Eisner and President Frank Wells created Touchstone to solve a genuine business problem: Disney's animated family brand was so strong that distributing adult films under the Disney name would confuse audiences and potentially damage the family brand. Touchstone debuted with Ron Howard's Splash (1984) — a mermaid comedy with brief nudity — impossible under the Disney name. The success enabled Disney to acquire adult hits without brand risk.\n\nTouchstone's most significant contribution was as distributor for films produced outside Disney's studio: Wes Anderson's Rushmore (1998), M. Night Shyamalan's The Sixth Sense (1999, $672 million worldwide, the 7th highest-grossing film of 1999), Pretty Woman (1990, $463 million worldwide, making Julia Roberts a star). Touchstone was effectively retired as an active label in 2008 when Disney began releasing adult content under the main Disney or Walt Disney Pictures banner, though the label occasionally surfaces for specific releases.",
        "causes": ["1984 launch by Eisner and Wells to release adult content without damaging Disney's family brand", "Splash 1984 debut demonstrating adult content commercial viability under separate brand", "Pretty Woman 1990 and Dead Poets Society 1989 establishing Touchstone's prestige adult film identity", "The Sixth Sense 1999 distribution earning $672 million on Shyamalan's breakthrough film"],
        "effects": ["Brand segregation model allowing family company to pursue adult market without brand contamination", "Dead Poets Society and Pretty Woman creating defining cultural moments of 1989-1990 cinema", "The Sixth Sense's $672 million establishing M. Night Shyamalan as major director", "2008 label retirement demonstrating Disney's evolution to direct adult content under core brand"],
        "relationships": [{"entity": "Michael Eisner", "relationship": "CREATED_BY_EXECUTIVE", "note": "Eisner and Frank Wells created Touchstone in 1984 to solve Disney's adult content brand challenge"}, {"entity": "Robin Williams", "relationship": "STAR_OF_DEFINING_FILMS", "note": "Williams starred in Good Morning Vietnam and Dead Poets Society — Touchstone's defining prestige films"}, {"entity": "M. Night Shyamalan", "relationship": "FILMMAKER_LAUNCHED_BY", "note": "The Sixth Sense (1999) distributed by Touchstone grossed $672 million launching Shyamalan's career"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "Touchstone Pictures solved the fundamental brand management challenge of a family entertainment company seeking adult market share — creating the label segregation model that demonstrated how IP-heavy studios can serve multiple audience demographics without brand damage.", "significanceCategory": "regional"},
    }),
    ("bbc-film", {
        "summary": "BBC Film (BBC Films), the theatrical film production arm of the British Broadcasting Corporation, founded in 1990, has produced or co-produced some of the most critically celebrated British films of the past 35 years — Four Weddings and a Funeral (1994), Mrs Brown (1997), Billy Elliot (2000), The History Boys (2006), The Queen (2006), 12 Years a Slave (2013), Paddington (2014), Lady Bird (2017, co-production), Belfast (2021) — with a production budget of approximately £15-20 million annually that consistently punches far above its weight. BBC Film productions have won 6 Academy Awards for Best Picture nominations and multiple wins.\n\nBBC Film's model — investing relatively small sums (typically £1-3 million per film) as co-producer alongside commercial partners — gives it creative influence disproportionate to its budget. Four Weddings and a Funeral (1994) cost £3 million and grossed $245 million worldwide; The Queen (2006, co-produced with Pathe) won Helen Mirren an Academy Award; 12 Years a Slave (2013) won Best Picture. The model works because BBC Film's creative development team identifies scripts at an early stage when commercial producers are risk-averse.\n\nBBC Film's distinctive contribution is supporting distinctly British stories — Billy Elliot's working-class Northern England, The History Boys' comprehensive school education, Belfast's Troubles — that might not attract American commercial investment. The public funding dimension (BBC is publicly funded via the licence fee) creates accountability to British cultural storytelling that commercial studios lack. BBC Film serves as a kind of literary development fund for British cinema, discovering and nurturing screenwriting talent.",
        "causes": ["1990 founding as BBC's theatrical film production arm to extend BBC storytelling into cinema", "Four Weddings and a Funeral 1994 grossing $245 million on £3 million demonstrating co-production model", "12 Years a Slave 2013 Best Picture win establishing BBC Film as award-worthy co-producer", "Public funding accountability requiring distinctly British cultural storytelling"],
        "effects": ["6 Best Picture nominations and multiple Academy Awards from £15-20 million annual budget", "Billy Elliot, The History Boys, and Belfast supporting British working-class storytelling", "Co-production model demonstrating small investment can produce outsized critical impact", "Distinctive British cultural voice in cinema preserved through public funding accountability"],
        "relationships": [{"entity": "Four Weddings and a Funeral", "relationship": "PRODUCED", "note": "BBC Film co-produced Four Weddings (1994) — £3 million budget, $245 million gross — establishing co-production model"}, {"entity": "12 Years a Slave", "relationship": "CO-PRODUCED", "note": "BBC Film co-produced Steve McQueen's 2013 Best Picture winner demonstrating award reach"}, {"entity": "British Broadcasting Corporation", "relationship": "DIVISION_OF", "note": "BBC Film is BBC's theatrical film arm, funded by licence fee with accountability to British culture"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "BBC Film's model — tiny public investment producing outsized critical impact from Four Weddings to 12 Years a Slave — demonstrates that publicly-funded cultural investment in distinctly national storytelling can achieve global prestige that commercial calculation would have bypassed.", "significanceCategory": "continental"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 90 — Class 364 Studios & Publishers III")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
