#!/usr/bin/env python3
"""Batch 63 — Class 381 Universities I (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/381-Class-381"
FILE_PREFIX = "381"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("harvard-university", {
        "summary": "Harvard University, founded in 1636 in Cambridge, Massachusetts, is the oldest university in the United States and one of the most prestigious in the world. With an endowment exceeding $50 billion — the world's largest — Harvard has produced 162 Nobel laureates, 8 US presidents, and 32 heads of state, making it the most consequential single educational institution in modern history.\n\nFounded just six years after the Massachusetts Bay Colony's establishment as Harvard College, the institution was named after its first major benefactor, clergyman John Harvard, who donated half his estate and his 400-volume library in 1638. Originally training Puritan ministers, Harvard evolved into a comprehensive research university whose graduate schools in law, medicine, business, and government have trained generations of global leaders.\n\nHarvard Business School's MBA program, founded in 1908, created the modern business school model; Harvard Law School trained three of nine current Supreme Court Justices; Harvard Kennedy School shapes global governance policy. The university's Cambridge campus and Massachusetts Hall (1720), the oldest surviving university building in North America, anchor America's most prestigious academic cluster. Harvard's decision to remain selective has been challenged by lawsuits over affirmative action (Students for Fair Admissions v. Harvard, 2023) in which the Supreme Court ruled race-conscious admissions unconstitutional.",
        "causes": ["Puritan Massachusetts Bay Colony's need to train ministers and educated leaders", "John Harvard's 1638 bequest of library and estate funding the early institution", "American colonial ambition to establish educational institutions equivalent to Oxford and Cambridge", "Boston's intellectual culture creating demand for advanced education"],
        "effects": ["8 US presidents and 162 Nobel laureates established Harvard as world's most consequential university", "$50 billion endowment enabled cutting-edge research across all disciplines", "Harvard Law and Medical Schools set professional education standards globally", "2023 Supreme Court ruling on Harvard admissions ended race-conscious university admissions nationwide"],
        "relationships": [{"entity": "John Harvard", "relationship": "NAMED_AFTER", "note": "1638 bequest of 400 books and half his estate named the college after him"}, {"entity": "Massachusetts Institute of Technology", "relationship": "COMPLEMENTARY_WITH", "note": "Harvard-MIT collaboration created world's most productive academic cluster"}, {"entity": "Harvard Business School", "relationship": "CONTAINS", "note": "HBS MBA program created modern business school education model"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "Harvard University has educated more US presidents, heads of state, and Nobel laureates than any other institution, making it the single most consequential university in the formation of modern global leadership.", "significanceCategory": "world-changing"},
    }),
    ("princeton-university", {
        "summary": "Princeton University, founded in 1746 as the College of New Jersey, is one of America's oldest and most prestigious research universities, located in Princeton, New Jersey. With an undergraduate enrollment of only 5,500 students — among the smallest in the Ivy League — Princeton has produced 69 Nobel laureates, 2 US presidents (James Madison and Woodrow Wilson), and maintains the world's highest faculty-to-student ratio among major research universities.\n\nPrinceton was founded by New Light Presbyterians seeking an alternative to Harvard's Congregationalism, and was the scene of a pivotal Revolutionary War battle in 1777 when George Washington defeated British forces at the Battle of Princeton. The university's Nassau Hall (1756) served briefly as the US Capitol in 1783 when Congress met there, and was the site where the Continental Congress learned of the peace treaty with Britain.\n\nPrinceton's Graduate School, Institute for Advanced Study (associated with but independent of Princeton), and Woodrow Wilson School of Public and International Affairs have made it a center for mathematics, physics, and political science. Albert Einstein spent his later career at the Institute for Advanced Study, working in Princeton from 1933 until his death in 1955. John Nash (A Beautiful Mind), Alan Turing, and Kurt Gödel were also associated with Princeton's mathematical tradition. Princeton's residential college system and eating clubs create a distinctive social culture.",
        "causes": ["New Light Presbyterian denominational rivalry with Harvard's Congregationalism", "Colonial New Jersey's need for an educational institution in the Middle Colonies", "Revolutionary War battles at Princeton making it symbol of American independence", "Post-war wealth of industrial America funding research university development"],
        "effects": ["Institute for Advanced Study created unique model for pure research without teaching obligations", "Albert Einstein's Princeton years produced late-career theoretical physics work", "Woodrow Wilson's Princeton presidency shaped his progressive political philosophy", "John Nash's game theory developed at Princeton transformed economics and social science"],
        "relationships": [{"entity": "Albert Einstein", "relationship": "ASSOCIATED_WITH", "note": "Einstein worked at Princeton's Institute for Advanced Study 1933-1955"}, {"entity": "Woodrow Wilson", "relationship": "SHAPED_BY", "note": "Wilson served as Princeton president 1902-1910 before becoming US President"}, {"entity": "John Nash", "relationship": "PRODUCED", "note": "Nash developed game theory at Princeton; subject of A Beautiful Mind"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Princeton University's mathematical and scientific tradition — Einstein, Nash, Turing, Gödel — and its role as brief US capital make it a university where both the American republic and modern theoretical science took defining shape.", "significanceCategory": "world-changing"},
    }),
    ("stanford-university", {
        "summary": "Stanford University, founded in 1885 in Palo Alto, California by railroad magnate Leland Stanford in memory of his son, is the world's most entrepreneurially productive university, having created or incubated companies including Google, Yahoo, Hewlett-Packard, Netflix, LinkedIn, and hundreds of others. The university's proximity to Silicon Valley and its culture of faculty entrepreneurship made it the intellectual engine of the technology revolution.\n\nLeland Stanford and his wife Jane established the university with a $5 million endowment and revolutionary mandate: to produce useful graduates rather than gentlemen scholars. The university opened in 1891 with 555 students and free tuition (maintained until 1920). Founding president David Starr Jordan's pragmatic educational philosophy aligned perfectly with California's entrepreneurial culture, establishing a partnership with technology that would define the 20th century.\n\nStanford's Industrial Park (1951), created by Frederick Terman, housed Hewlett-Packard and became the template for university-industry partnerships creating Silicon Valley. Google was invented in Stanford's computer science building; Yahoo by Stanford students; the concept of the integrated circuit developed by Stanford-connected researchers. The Hoover Institution at Stanford became a major conservative policy research center. With an endowment exceeding $37 billion, Stanford's per-student research spending exceeds any other university.",
        "causes": ["Leland Stanford's grief over son's death motivating memorial university creation", "California's 1880s explosive growth requiring a major Pacific Coast research university", "Pragmatic education philosophy aligning with California's gold rush entrepreneurial culture", "Frederick Terman's deliberate strategy of connecting university to technology industry"],
        "effects": ["Google, Yahoo, HP, Netflix, LinkedIn and hundreds of other companies founded by alumni/faculty", "Silicon Valley created as university-industry technology cluster", "Venture capital industry developed in partnership with Stanford network", "Stanford earned over $1 billion from licensing Google's PageRank algorithm alone"],
        "relationships": [{"entity": "Leland Stanford", "relationship": "FOUNDED_BY", "note": "Railroad magnate founded university in 1885 in memory of his son Leland Jr."}, {"entity": "Google", "relationship": "INCUBATED", "note": "Larry Page and Sergey Brin developed PageRank algorithm as Stanford PhD students"}, {"entity": "Silicon Valley", "relationship": "CREATED", "note": "Stanford Industrial Park (1951) and Terman's industry strategy created Silicon Valley"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "Stanford University's entrepreneurial culture and Silicon Valley partnerships made it the intellectual engine of the digital revolution, incubating companies that collectively transformed global economy, communication, and culture.", "significanceCategory": "world-changing"},
    }),
    ("yale-university", {
        "summary": "Yale University, founded in 1701 in New Haven, Connecticut, is the third-oldest university in the United States and one of the most prestigious in the world. With 65 Nobel laureates, 5 US presidents, and the country's second-largest university endowment ($41 billion), Yale has been central to American law, politics, and arts for three centuries, producing more US Supreme Court Justices than any other law school.\n\nFounded by Congregationalist ministers as the Collegiate School of Connecticut, then renamed after benefactor Elihu Yale in 1718, the university evolved from a strictly religious institution to a comprehensive research university. Yale's residential college system, adopted from Oxford and Cambridge in 1933, created a distinctive undergraduate culture. The Yale Law School and its Federalist Society affiliates have profoundly shaped American constitutional law for decades.\n\nYale's contributions to arts and culture are distinctive: the Yale School of Drama, founded in 1924, has trained generations of American theater and film talent including Meryl Streep, Jodie Foster, and Paul Newman; the Yale School of Music has produced major American composers. Yale's Beinecke Rare Book Library, one of the largest buildings in the world devoted to rare books, houses original manuscripts including Gutenberg Bibles and the controversial Voynich Manuscript. Skull and Bones, the most famous secret society in America, was founded at Yale.",
        "causes": ["Congregationalist ministers' desire for educational institution closer to Connecticut than Harvard", "Elihu Yale's 1718 benefaction providing resources enabling expansion", "New England theological tradition requiring learned ministry", "Colonial American civilization's development requiring multiple educational centers"],
        "effects": ["Yale Law School graduates shaped American constitutional jurisprudence", "Yale Drama School graduates Streep, Foster, and Newman defined American acting", "Beinecke Library preserved rare book heritage including Gutenberg Bibles", "Skull and Bones society alumni network created informal power network in American life"],
        "relationships": [{"entity": "Elihu Yale", "relationship": "NAMED_AFTER", "note": "British merchant donated goods enabling expansion; university named in his honor 1718"}, {"entity": "Yale Law School", "relationship": "CONTAINS", "note": "Has produced more US Supreme Court Justices than any other law school"}, {"entity": "Yale School of Drama", "relationship": "CONTAINS", "note": "Trained Meryl Streep, Jodie Foster, and Paul Newman among many major talents"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Yale's law school has shaped American constitutional law more than any other institution, while its arts schools and Beinecke Library make it the most culturally comprehensive of America's oldest universities.", "significanceCategory": "world-changing"},
    }),
    ("sorbonne", {
        "summary": "The Sorbonne (University of Paris) is one of the world's oldest universities, founded around 1150-1200 CE in Paris, and the mother institution from which modern Western university culture descended. For centuries the most prestigious center of theological and philosophical learning in the Christian world, the Sorbonne's faculties of theology, arts, and medicine trained the scholars, bishops, and jurists who governed medieval European civilization.\n\nThe University of Paris emerged from the cathedral schools of Notre-Dame de Paris, gaining papal recognition around 1200 CE. The Sorbonne itself — the collège de Sorbonne — was founded in 1257 by Robert de Sorbon, confessor to King Louis IX, as a residence for poor theology students. The university's conflict with the French Crown over jurisdiction and its 1229 strike (first university strike in history) established the precedent of university autonomy from secular authority.\n\nThe Sorbonne was the epicenter of medieval scholasticism: Thomas Aquinas taught there, Albertus Magnus taught there, and the Summa Theologica was developed in its intellectual environment. The university also condemned Joan of Arc in 1431 and later condemned Copernicus. The French Revolution disrupted the Sorbonne, which was closed 1793-1808. The May 1968 student uprising that triggered France's most significant modern political crisis began at Nanterre and moved to the Sorbonne, making the university permanently associated with radical student politics.",
        "causes": ["Cathedral school tradition of Paris creating intellectual cluster for advanced learning", "Papal interest in standardizing theological education across Christendom", "Royal French patronage seeing university as source of learned administrators", "Robert de Sorbon's vision of accessible theological education for poor scholars"],
        "effects": ["Medieval scholasticism — synthesizing Aristotle and Christian theology — developed at Sorbonne", "University autonomy precedent established through 1229 strike", "Aquinas's Summa Theologica created from Sorbonne intellectual environment", "May 1968 student revolt at Sorbonne triggered France's largest postwar political crisis"],
        "relationships": [{"entity": "Thomas Aquinas", "relationship": "EDUCATED", "note": "Aquinas taught at Paris and developed Summa Theologica in the Sorbonne's intellectual environment"}, {"entity": "Joan of Arc", "relationship": "CONDEMNED", "note": "University of Paris condemned Joan of Arc at 1431 ecclesiastical trial"}, {"entity": "May 1968", "relationship": "EPICENTER_OF", "note": "Student uprising began at Sorbonne, triggering France's largest postwar political crisis"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Sorbonne as medieval Europe's foremost theological university created the model for Western academic culture, hosted the development of scholasticism, and has been France's intellectual heart through revolution, Napoleon, and 1968.", "significanceCategory": "world-changing"},
    }),
    ("nalanda-university", {
        "summary": "Nalanda University was the world's first residential university and one of the greatest centers of learning in the ancient world, located in Bihar, India. Flourishing from the 5th to 12th centuries CE, it attracted students and scholars from China, Korea, Japan, Tibet, Mongolia, Turkey, and Sri Lanka, teaching subjects including philosophy, logic, mathematics, astronomy, medicine, and Buddhist studies to 10,000 resident students taught by 2,000 teachers.\n\nFounded during the Gupta Empire in the 5th century CE, Nalanda received royal patronage from emperors Kumāragupta and Harsha, who built separate monasteries and libraries. The Chinese pilgrim Xuanzang visited in 637 CE and described the university in detail: eight halls, 300 lecture rooms, observatory, library (called Dharmaganja — 'Treasury of Truth'), and dormitories requiring every applicant to pass entrance exams. His account is the primary historical source for Nalanda's scale and curriculum.\n\nNalanda was destroyed in 1193 CE by the army of Bakhtiyar Khilji, a commander of the Delhi Sultanate, who burned the libraries — reportedly burning for three months, consuming the greatest collection of Buddhist manuscripts in existence. The destruction of Nalanda effectively ended Buddhism's intellectual dominance in the Indian subcontinent, scattering the monastic scholarly tradition to Tibet and Southeast Asia. A new Nalanda University was established by the Indian government in 2010, reopening in 2014 near the original site.",
        "causes": ["Gupta Empire's Buddhist patronage supporting large-scale monastic education", "Indian tradition of gurukul education scaling to institutional residential learning", "International Buddhist network creating demand for a central scholarly hub", "Bihar's geographic position on trade routes making it accessible to Asian scholars"],
        "effects": ["Created model of residential university with entrance examinations", "Xuanzang's account preserved knowledge of ancient Indian higher education", "1193 destruction eliminated largest collection of Buddhist manuscripts in existence", "Destruction scattered Buddhist scholars to Tibet preserving texts in Tibetan translation"],
        "relationships": [{"entity": "Xuanzang", "relationship": "DOCUMENTED_BY", "note": "Chinese pilgrim's 637 CE account provides primary historical evidence of Nalanda's scale"}, {"entity": "Bakhtiyar Khilji", "relationship": "DESTROYED_BY", "note": "1193 CE attack burned libraries and killed resident monks"}, {"entity": "Buddhism", "relationship": "SERVED_AS_CENTER_OF", "note": "World's foremost center of Buddhist scholarship for 700 years"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Nalanda as the world's first residential university created the model for institutional higher education, and its 1193 destruction by fire represents one of history's greatest losses of human knowledge.", "significanceCategory": "world-changing"},
    }),
    ("humboldt-university-berlin", {
        "summary": "Humboldt University of Berlin, founded in 1810 by Wilhelm von Humboldt, is the institution that created the modern research university model — combining teaching with original research, graduate seminars, and academic freedom — which became the global standard for higher education. The 'Humboldtian model' diffused worldwide, particularly to American universities, transforming how humanity generates and transmits knowledge.\n\nWilhelm von Humboldt's founding vision was revolutionary: professors should be active researchers generating new knowledge, not merely transmitting received wisdom; students should participate in research, not just memorize; and the university should be free from state interference in academic inquiry. These principles — Lehr- und Lernfreiheit (freedom to teach and learn) — created the conditions for the extraordinary German scientific dominance of the 19th century.\n\nHumboldt University's faculty reads as a roll call of modern intellectual history: Hegel lectured philosophy; Marx was a student; Einstein taught physics; Max Planck discovered quantum mechanics; Otto von Bismarck studied law. The university was home to 29 Nobel Prize winners including Planck, Einstein, and Hertz. Nazi persecution ended this golden age — nearly a third of faculty were dismissed after 1933, triggering the brain drain to American universities that transferred German scientific leadership to the US. The book burning in Bebelplatz opposite the university (1933) became the symbol of academic freedom under totalitarianism.",
        "causes": ["Prussia's military defeat by Napoleon motivating radical educational reform", "Wilhelm von Humboldt's philosophical commitment to education as self-cultivation", "Berlin's position as Prussian capital requiring a world-class research institution", "Enlightenment ideal of systematic inquiry replacing dogmatic theological education"],
        "effects": ["Humboldtian research university model adopted globally including by American universities", "German scientific dominance in 19th century built on Humboldt University's model", "Nazi persecution 1933 sent Humboldt scholars to American universities, transferring scientific leadership", "1933 Bebelplatz book burning became enduring symbol of intellectual freedom's fragility"],
        "relationships": [{"entity": "Wilhelm von Humboldt", "relationship": "FOUNDED_BY", "note": "Prussian reformer's 1810 vision created the modern research university model"}, {"entity": "Karl Marx", "relationship": "EDUCATED", "note": "Marx studied philosophy at Humboldt from 1836-1841"}, {"entity": "Max Planck", "relationship": "PRODUCED", "note": "Planck discovered quantum mechanics at Humboldt; Nobel Prize 1918"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "Humboldt University created the research university model — teaching combined with original inquiry — that became the global standard for higher education, making it the most influential university in the history of how knowledge is produced.", "significanceCategory": "world-changing"},
    }),
    ("university-of-oxford", {
        "summary": "The University of Oxford is the oldest English-speaking university in the world, with teaching dating from 1096 CE and developing rapidly after 1167 CE. A collegiate university of 44 colleges and 7 permanent private halls, Oxford has educated 28 British prime ministers, over 50 Nobel laureates, and shaped the English-speaking world's legal, political, and cultural tradition more than any other institution.\n\nOxford's origins lie in the royal court scholars gathered in Oxford's strategic location at the confluence of the Thames and Cherwell rivers. The expulsion of English students from Paris in 1167 CE accelerated Oxford's growth. By 1209 CE, violence between town and gown sent a group of scholars to Cambridge, founding that rival university. The collegiate system — individual colleges as self-governing scholarly communities within a larger university — was Oxford's unique innovation, creating communities that combined residence, dining, teaching, and scholarship.\n\nOxford's tutorial system, in which undergraduates meet one-on-one or in pairs with expert tutors weekly, is its most distinctive educational feature, producing extraordinary depth of individual scholarly development. Alumni include Roger Bacon (early scientific method), John Wycliffe (Bible translation), John Locke (social contract theory), Adam Smith (economics), Oscar Wilde (literature), Margaret Thatcher (chemistry to politics), and Bill Clinton. The Bodleian Library, one of Europe's oldest libraries (1602), holds over 13 million items including the Gutenberg Bible and Shakespeare First Folio.",
        "causes": ["English royal court's need for educated administrators creating demand for scholarly center", "1167 expulsion of English scholars from Paris forcing Oxford's rapid development", "Collegiate system innovation creating sustainable model for scholarly community", "Papal and royal patronage establishing institutional permanence"],
        "effects": ["28 British prime ministers educated at Oxford shaped modern British governance", "Tutorial system created model for intensive individual intellectual development", "Bodleian Library preserved Europe's greatest collection of manuscripts and rare books", "Rhodes Scholarship from 1902 created global network of Oxford-educated international leaders"],
        "relationships": [{"entity": "Cambridge University", "relationship": "SPAWNED", "note": "Violence in Oxford in 1209 caused scholars to leave and found Cambridge"}, {"entity": "Adam Smith", "relationship": "EDUCATED", "note": "Smith studied at Balliol College Oxford; described it negatively in Wealth of Nations"}, {"entity": "Bodleian Library", "relationship": "CONTAINS", "note": "One of Europe's oldest research libraries with 13 million items"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "Oxford University's 900-year history as the intellectual home of 28 British prime ministers and major thinkers from Locke to Smith to Wilde makes it the most consequential educational institution in the formation of English-speaking civilization.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 63 — Class 381 Universities I")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
