#!/usr/bin/env python3
"""Batch 146 — Class 381 Universities VIII: European & Global Universities (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/381-Class-381"
FILE_PREFIX = "381"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("leiden-university", {
        "summary": "Leiden University (Universiteit Leiden), founded in 1575 in Leiden, Netherlands — is the Netherlands' oldest university, founded by William the Silent (Prince of Orange) as a reward to Leiden for its heroic resistance to the Spanish siege (1573-1574), during which approximately one-third of the city's population died of plague and starvation but the city refused to surrender to Spanish Habsburg forces — making the university itself a monument to Dutch independence and resistance to Spanish rule.\n\nLeiden's intellectual legacy is extraordinary: it was the leading center of the Scientific Revolution in the 17th-century Dutch Golden Age — Rembrandt, Jan Steen, and other Dutch Masters painted; René Descartes studied in Leiden; Antonie van Leeuwenhoek (inventor of the microscope, discoverer of bacteria and protozoa) was a Leiden connection; Herman Boerhaave (the father of clinical medicine and clinical teaching) created Leiden's medical school as the model for European medical education; Christiaan Huygens studied there; and the university's printing presses published some of the most important Enlightenment texts.\n\nLeiden's modern excellence includes 16 Nobel Prize laureates affiliated with the university, a world-renowned Asia collection and East Asian library, outstanding law and humanities faculties, and the Leiden Observatory (founded 1633, one of the world's oldest continuously operating observatories). The university's international orientation — historically studying Arabic, Persian, and East Asian languages when few European universities did — made it a pioneer of non-European scholarship.",
        "causes": ["William the Silent's 1575 founding as reward for Leiden's heroic resistance to Spanish siege creating a monument to Dutch independence", "Dutch Golden Age's commercial wealth funding a scientifically and intellectually innovative university environment", "Herman Boerhaave's 18th-century medical school creating the European model for clinical medical education", "Netherlands' international commercial and colonial connections encouraging pioneering non-European language scholarship"],
        "effects": ["Leiden becoming the leading Scientific Revolution center with connections to Descartes, van Leeuwenhoek, Huygens, and Boerhaave", "Herman Boerhaave's clinical teaching model at Leiden becoming the foundation of European medical education", "16 Nobel Prize laureates affiliated with Leiden representing continued excellence in multiple fields", "Asia Collection and non-European language scholarship pioneering European understanding of Eastern civilizations"],
        "relationships": [{"entity": "William the Silent", "relationship": "FOUNDED_BY_AS_REWARD_FOR_DUTCH_SIEGE_RESISTANCE", "note": "William the Silent founded Leiden University in 1575 as a reward for the city's heroic resistance to Spanish siege"}, {"entity": "Dutch Scientific Revolution", "relationship": "LEADING_INSTITUTIONAL_CENTER_OF_17TH_CENTURY", "note": "Leiden was the leading institutional center of the Dutch Golden Age Scientific Revolution"}, {"entity": "Herman Boerhaave", "relationship": "CLINICAL_MEDICAL_EDUCATION_MODEL_CREATED_AT_LEIDEN_BY", "note": "Herman Boerhaave's Leiden medical school created the clinical teaching model adopted across Europe"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Leiden University — the Netherlands' oldest university, center of the Dutch Scientific Revolution, home to Boerhaave's clinical medicine model — is one of Europe's most historically significant universities whose contributions to medicine, astronomy, and Enlightenment thought shaped modern science.", "significanceCategory": "world-changing"},
    }),
    ("university-of-edinburgh", {
        "summary": "The University of Edinburgh, founded in 1583 by Edinburgh Town Council (one of Europe's first civic-founded universities) — was the primary institutional center of the Scottish Enlightenment, arguably the most intellectually productive national intellectual movement in 18th-century Europe: David Hume (Scotland's greatest philosopher), Adam Smith (author of The Wealth of Nations, 1776, the foundational text of modern economics), and Joseph Black (discoverer of carbon dioxide and latent heat) were all Edinburgh-connected figures in what was arguably the most productive per capita intellectual environment in the 18th-century Atlantic world.\n\nEdinburgh's intellectual productivity derived from several factors: Scotland's distinctive legal and educational tradition created an environment valuing practical knowledge; Edinburgh's civic founding (unlike most European universities founded by church or crown) encouraged a broad, practical curriculum; the Medical School (founded 1726) was, alongside Leiden, the premier center of European medical education in the 18th century; and the small, intense intellectual community of Edinburgh's Old Town created a club culture (clubs like the Select Society, the Poker Club) where philosophers, scientists, lawyers, and ministers debated foundational questions of human society.\n\nEdinburgh's modern standing is excellent: consistently ranked among the world's top 20-30 universities, with 29 Nobel Prize laureates, world-class medical and veterinary schools, and a position in a city of extraordinary architectural and cultural quality. Charles Darwin studied at Edinburgh (though he left before completing his degree, finding chemistry boring and surgery traumatic — before going to Cambridge and eventually proposing the theory of evolution). Alexander Graham Bell was born in Edinburgh.",
        "causes": ["1583 Edinburgh Town Council founding creating one of Europe's first civic-funded universities", "Scottish Enlightenment environment concentrating exceptional intellectual talent in a small, intense intellectual community", "Medical School (1726) founding alongside Leiden as the premier European centers for clinical medical education", "Scottish distinctive legal and educational tradition valuing practical knowledge and philosophical skepticism"],
        "effects": ["Scottish Enlightenment's extraordinary intellectual productivity with David Hume, Adam Smith, and Joseph Black", "Adam Smith's Wealth of Nations (1776) founding modern economics and capitalism's intellectual framework", "Edinburgh Medical School training medical professionals from across Europe and America in 18th century", "29 Nobel Prize laureates representing continued 20th-21st century academic excellence"],
        "relationships": [{"entity": "Scottish Enlightenment", "relationship": "PRIMARY_INSTITUTIONAL_CENTER_OF_18TH_CENTURY", "note": "Edinburgh University was the primary institutional center of the Scottish Enlightenment"}, {"entity": "Adam Smith", "relationship": "EDUCATED_AND_CONNECTED_ECONOMIST_WHOSE_WEALTH_OF_NATIONS_FOUNDED_MODERN_ECONOMICS", "note": "Adam Smith's Wealth of Nations (1776), foundational to modern economics, was created in Edinburgh's intellectual environment"}, {"entity": "Charles Darwin", "relationship": "EARLY_STUDIES_AT_BEFORE_CAMBRIDGE_AND_FORMULATING_EVOLUTION_THEORY", "note": "Charles Darwin studied at Edinburgh before moving to Cambridge and eventually formulating the theory of evolution"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The University of Edinburgh — the Scottish Enlightenment's institutional center producing David Hume, Adam Smith, and Joseph Black in the 18th century's most productive intellectual environment — is historically significant as the birthplace of modern economics and a leading center of Enlightenment thought.", "significanceCategory": "world-changing"},
    }),
    ("university-of-amsterdam", {
        "summary": "The University of Amsterdam (Universiteit van Amsterdam, UvA), founded in 1632 as the Athenaeum Illustre — is the Netherlands' largest research university, the flagship institution of Amsterdam, Europe's most tolerant 17th-century city and the center of early modern European intellectual and commercial life. The university's Golden Age foundations reflect Amsterdam's unique position as a haven for religious refugees, free-thinkers, and intellectual radicals whose ideas could not be published elsewhere in Europe.\n\nThe 17th-century Amsterdam intellectual environment that shaped the university's founding was extraordinary: Baruch Spinoza (the most radical philosopher of the early modern period, whose Ethics proposed a pantheistic materialism that scandalized European Christianity) was a product of Amsterdam's Jewish community; René Descartes lived in Amsterdam for much of his career (appreciating the city's tolerance and anonymity); John Locke took refuge in Amsterdam's intellectual circles; and Amsterdam's printing presses published texts banned throughout Europe. The university's Athenaeum Illustre was part of this environment.\n\nThe University of Amsterdam's modern standing is exceptional: consistently ranked among Europe's top 10 research universities, particularly strong in economics, political science, and the social sciences, with approximately 37,000 students and a global research profile. The Amsterdam campus's integration with the city — multiple buildings scattered through Amsterdam's historic canal district — makes it one of Europe's most architecturally embedded universities, with the historic Agnietenkapel (1470) as the university museum.",
        "causes": ["1632 Amsterdam founding as Athenaeum Illustre in Europe's most tolerant and commercially vibrant city", "Amsterdam's intellectual openness hosting Descartes, Spinoza, and religious refugees creating exceptional intellectual environment", "Dutch trading empire creating a cosmopolitan city that valued practical knowledge and international perspectives", "17th-century Amsterdam printing culture publishing banned European texts creating an intellectual freedom tradition"],
        "effects": ["Amsterdam intellectual environment contributing to Spinoza's and Descartes' philosophical works", "University developing strong social sciences tradition reflecting Amsterdam's empirical, pragmatic culture", "Modern ranking among Europe's top 10 research universities with global research profile", "Historic canal district campus integration making it one of Europe's architecturally distinctive university environments"],
        "relationships": [{"entity": "Baruch Spinoza", "relationship": "AMSTERDAM'S_JEWISH_INTELLECTUAL_COMMUNITY_NURTURING_MOST_RADICAL_PHILOSOPHER", "note": "Spinoza was a product of Amsterdam's Jewish intellectual community whose tolerance shaped the university's founding context"}, {"entity": "René Descartes", "relationship": "LIVED_AND_WORKED_IN_AMSTERDAM_VALUING_TOLERANCE_OF_UNIVERSITY'S_FOUNDING_CITY", "note": "Descartes lived in Amsterdam for much of his career, appreciating the city's intellectual tolerance"}, {"entity": "Dutch Golden Age", "relationship": "FOUNDED_AND_SHAPED_BY_THE_INTELLECTUAL_AND_COMMERCIAL_CONTEXT_OF", "note": "The University of Amsterdam was founded and shaped by the Dutch Golden Age's intellectual and commercial flourishing"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The University of Amsterdam — founded in Europe's most tolerant 17th-century intellectual environment, shaped by Spinoza and Descartes' presence — is historically significant as a leading European research university whose intellectual tradition reflects the Dutch Golden Age's unique contribution to freedom of thought.", "significanceCategory": "world-changing"},
    }),
    ("yale-university", {
        "summary": "Yale University, founded in 1701 in New Haven, Connecticut — is one of the world's premier research universities and the third-oldest university in the United States, originally founded by Congregationalist ministers concerned that Harvard had become too liberal for orthodox Calvinist education. Yale's subsequent history represents one of the most remarkable transformations in intellectual history: from a conservative orthodox institution to one of the world's most diverse and intellectually adventurous research universities.\n\nYale's contributions to American intellectual, political, and cultural life are extraordinary: 5 U.S. Presidents (including George H.W. Bush and George W. Bush, Bill Clinton's Yale Law degree), 62 Nobel Prize laureates, 52 MacArthur Fellows, the Yale School of Drama training generations of theater artists, Yale Law School consistently ranked among the top three law schools in the United States, and the Beinecke Rare Book and Manuscript Library holding one of the world's greatest collections including the Gutenberg Bible and the Voynich Manuscript. The Yale Peabody Museum of Natural History was founded by Othniel Marsh, who assembled remarkable dinosaur collections in the 19th century.\n\nYale's architectural significance is substantial: the Gothic Revival campus buildings (particularly Sterling Memorial Library, designed to resemble a cathedral with the circulation desk as an 'altar to learning') represent one of the most coherent architectural statements in American higher education. The university's position in New Haven — a struggling post-industrial city — creates an interesting tension between elite academic wealth and urban poverty that has shaped Yale's community engagement.",
        "causes": ["1701 Congregationalist ministers' founding as orthodox alternative to Harvard perceived as too liberal", "Yale's religious and educational mission evolving from orthodox Calvinist to comprehensive research university", "New Haven's Connecticut location creating a major Ivy League research center in the northeastern corridor", "Endowment wealth (among the world's largest university endowments) enabling world-class research and scholarship"],
        "effects": ["62 Nobel Prize laureates representing extraordinary contributions to world scholarship across multiple fields", "5 U.S. Presidents educated at Yale representing disproportionate political influence in American governance", "Yale Law School producing a significant portion of American Supreme Court justices and leading legal scholars", "Beinecke Library's Gutenberg Bible and rare manuscript collections as world-class research resources"],
        "relationships": [{"entity": "Harvard University", "relationship": "FOUNDED_AS_ORTHODOX_CALVINIST_ALTERNATIVE_TO_LIBERAL", "note": "Yale was founded in 1701 by Congregationalist ministers concerned that Harvard had become too religiously liberal"}, {"entity": "United States Presidents", "relationship": "EDUCATED_5_PRESIDENTS_INCLUDING_MULTIPLE_BUSH_AND_CLINTON", "note": "Yale educated 5 U.S. Presidents including George H.W. Bush, George W. Bush, and Bill Clinton (Yale Law)"}, {"entity": "Yale Peabody Museum", "relationship": "NATURAL_HISTORY_COLLECTIONS_INCLUDING_MARSH'S_DINOSAUR_FOSSILS_HOUSED_AT", "note": "The Yale Peabody Museum holds Othniel Marsh's 19th-century dinosaur fossil collections"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Yale University — educating 5 U.S. Presidents, 62 Nobel laureates, and generations of American leaders from its 1701 founding — is one of the world's most consequential universities whose influence on American law, politics, and intellectual life is unmatched.", "significanceCategory": "world-changing"},
    }),
    ("university-of-melbourne", {
        "summary": "The University of Melbourne, founded in 1853 — is Australia's second oldest university (after the University of Sydney, 1850) and consistently ranked as Australia's top or co-top research university, the flagship institution of the state of Victoria and Australia's cultural capital city. Melbourne was founded just years after Victoria's 1851 gold rush transformed the region from a frontier colony into one of the world's wealthiest cities, and the university's rapid development reflected the new colony's ambitions and wealth.\n\nThe University of Melbourne's Parkville campus is architecturally significant: the historic quadrangle buildings in bluestone (a distinctive Melbourne architectural material) represent Victorian-era Australian ambitions to create an institution equivalent to the ancient English universities. The university's growth in the late 19th and early 20th centuries coincided with Melbourne's period as Australia's financial capital and de facto national capital (until Canberra was established in 1927), and many of Australia's most significant 19th-20th century figures — judges, politicians, scientists — were educated there.\n\nMelbourne's academic strength is broad: the faculties of law, medicine, engineering, and the sciences are all nationally premier. Notable alumni include Graeme Clark (inventor of the cochlear implant, a technology that has restored hearing to over 700,000 people globally, one of the most significant medical technology achievements in history), multiple Australian Prime Ministers, and internationally significant scholars. The university's 2008 Melbourne Model restructured undergraduate education to graduate professional schools, influencing Australian higher education broadly.",
        "causes": ["1853 founding following Victoria's gold rush transforming Melbourne into one of the world's wealthiest cities", "Colonial ambitions to establish a world-class university equivalent to Oxford and Cambridge driving institutional development", "Melbourne's position as Australia's financial and cultural capital creating demand for professional and academic education", "Victorian-era bluestone campus construction reflecting the new colony's wealth and ambitions"],
        "effects": ["Consistent ranking as Australia's top research university representing 170+ years of academic excellence", "Graeme Clark's cochlear implant invention restoring hearing to 700,000+ people globally as extraordinary medical achievement", "Melbourne Model (2008) restructuring undergraduate education influencing Australian higher education nationally", "Multiple Australian Prime Ministers educated at Melbourne representing disproportionate political influence"],
        "relationships": [{"entity": "Graeme Clark", "relationship": "EDUCATION_CONTRIBUTING_TO_COCHLEAR_IMPLANT_INVENTOR_WHO_RESTORED_HEARING_TO_700,000", "note": "Graeme Clark, educated at Melbourne, invented the cochlear implant that has restored hearing to over 700,000 people globally"}, {"entity": "Victorian Gold Rush", "relationship": "FOUNDED_IN_WEALTH_GENERATED_BY_1851_TRANSFORMATION_OF", "note": "The University of Melbourne was founded in 1853 directly following Victoria's gold rush that made Melbourne one of the world's wealthiest cities"}, {"entity": "Melbourne Model", "relationship": "2008_EDUCATIONAL_RESTRUCTURING_INFLUENCING_AUSTRALIAN_HIGHER_EDUCATION", "note": "Melbourne's 2008 Melbourne Model restructured undergraduate education to graduate professional schools"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The University of Melbourne — Australia's top research university whose alumni invented the cochlear implant restoring hearing to 700,000+ people — is historically significant as the flagship of Australian academic excellence and a major contributor to global medical technology.", "significanceCategory": "world-changing"},
    }),
    ("university-of-cape-town", {
        "summary": "The University of Cape Town (UCT), founded in 1829 as the South African College — is Africa's top-ranked university and the highest-ranked African institution in most global rankings, a research-intensive university on the slopes of Table Mountain in one of the world's most spectacular city settings, whose history is inseparable from South Africa's transition from apartheid to democracy and whose student body and academic community have been central to social justice struggles throughout the 20th century.\n\nUCT's position as Africa's leading research university gives it continental significance: producing research on tropical diseases, African economics, African history, and African cultural studies that would not be produced elsewhere, training the continent's future academic and professional leaders, and serving as a beacon for African intellectual ambition. The university's Groote Schuur campus (designed partly by Herbert Baker) features some of South Africa's most significant colonial and post-colonial architecture, including the historic UCT library collections.\n\nUCT's modern political history is marked by its role in anti-apartheid struggle and post-apartheid transformation debates: the 2015-2016 #RhodesMusFall movement (beginning at UCT and spreading globally as #RhodesMustFall) — demanding the removal of Cecil John Rhodes's statue on campus and challenging colonial intellectual legacies in higher education — initiated a global conversation about colonial statues and intellectual decolonization that became one of the 21st century's most significant cultural debates, with impacts from Oxford to Cape Town to Harvard.",
        "causes": ["1829 South African College founding as the Cape Colony's primary educational institution", "Post-apartheid transformation enabling UCT to develop into Africa's leading research university", "Table Mountain Groote Schuur campus providing exceptional intellectual environment in Africa's most cosmopolitan city", "South Africa's scientific and medical research infrastructure supporting UCT's research excellence"],
        "effects": ["UCT consistently ranking as Africa's top university providing continental scientific and research leadership", "#RhodesMustFall movement (2015-2016) beginning at UCT and triggering global debate about colonial intellectual legacies", "African research on tropical diseases, economics, and history produced at world-class standard", "UCT Law School producing South African Constitutional Court judges who shaped post-apartheid justice"],
        "relationships": [{"entity": "Rhodes Must Fall Movement", "relationship": "CAMPUS_WHERE_GLOBAL_COLONIAL_STATUE_DEBATE_BEGAN_IN_2015", "note": "UCT was where the #RhodesMustFall movement began in 2015, triggering a global debate about colonial statues"}, {"entity": "Cecil Rhodes", "relationship": "RHODES_STATUE_ON_CAMPUS_WHOSE_REMOVAL_TRIGGERED_GLOBAL_DECOLONIZATION_DEBATE", "note": "Cecil Rhodes's statue on UCT's campus was the focus of the #RhodesMustFall movement"}, {"entity": "African Research", "relationship": "AFRICA'S_TOP-RANKED_INSTITUTION_LEADING_CONTINENTAL_SCHOLARSHIP_IN", "note": "UCT is Africa's top-ranked research university providing continental leadership in African scholarship"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The University of Cape Town — Africa's top-ranked university, where the #RhodesMustFall movement began triggering global colonial legacy debates — is historically significant as Africa's premier research institution and a catalyst for 21st-century global debates about decolonizing intellectual institutions.", "significanceCategory": "world-changing"},
    }),
    ("pontifical-gregorian-university", {
        "summary": "The Pontifical Gregorian University (Pontificia Università Gregoriana) in Rome — founded in 1551 by St. Ignatius of Loyola as the Roman College (Collegium Romanum), renamed Gregorian in honor of Pope Gregory XIII who provided a major endowment — is one of the world's most historically significant universities, having educated approximately 25 popes, cardinals, bishops, and priests who have shaped Catholic doctrine and governance across 470 years, making it the most influential theological institution in Catholicism.\n\nThe Gregorian's founding context was the Counter-Reformation: Ignatius of Loyola founded the Society of Jesus (Jesuits) in 1540 explicitly to defend Catholic doctrine against Protestant Reformation challenges, and the Roman College was the Jesuits' flagship institution for training priests and missionaries who would carry reformed Catholicism across the world. The Council of Trent (1545-1563) defined orthodox Catholic doctrine in many areas, and the Gregorian's scholars were deeply involved in implementing and articulating this doctrine.\n\nThe Gregorian's alumni list includes some of the most consequential figures in modern Catholic history: multiple popes (including the recently canonized popes of the 20th century), theologians including Karl Rahner (one of Vatican II's most important theological voices), and the intellectual architects of the Second Vatican Council (1962-1965) that modernized Catholicism. The university's role in training the global Catholic clergy — through its connection to the Pontifical Biblical Institute, Pontifical Oriental Institute, and multiple other Roman institutions — makes it the intellectual center of a church of approximately 1.3 billion Catholics.",
        "causes": ["Ignatius of Loyola's 1551 founding as Counter-Reformation response to Protestant challenges requiring trained theologians", "Pope Gregory XIII's major endowment and patronage enabling the university's expansion and international reach", "Jesuit educational mission creating a rigorous pedagogical model that would influence Catholic education globally", "Rome's position as Catholic Church headquarters making a major theological university there essential"],
        "effects": ["Approximately 25 popes educated or trained at the Gregorian University over 470 years", "Counter-Reformation theological framework articulated and disseminated by Gregorian-trained clergy globally", "Vatican II (1962-1965) intellectual preparation significantly influenced by Gregorian-trained theologians including Karl Rahner", "Global Catholic clergy training through connection to multiple Pontifical Roman institutions"],
        "relationships": [{"entity": "Society of Jesus Jesuits", "relationship": "FOUNDED_BY_IGNATIUS_OF_LOYOLA_AS_FLAGSHIP_JESUIT_COUNTER-REFORMATION_INSTITUTION", "note": "Ignatius of Loyola founded the Gregorian as the Jesuits' flagship Roman institution for Counter-Reformation theology"}, {"entity": "Second Vatican Council", "relationship": "INTELLECTUAL_PREPARATION_AND_THEOLOGIANS_INCLUDING_KARL_RAHNER_SHAPED_BY", "note": "Vatican II's theological direction was significantly influenced by Gregorian-trained theologians"}, {"entity": "Counter-Reformation", "relationship": "FOUNDED_TO_DEFEND_CATHOLIC_DOCTRINE_AND_TRAIN_CLERGY_FOR", "note": "The Gregorian was founded explicitly as a Counter-Reformation institution to train clergy defending Catholicism against Protestant challenges"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Pontifical Gregorian University — founded by Ignatius of Loyola for the Counter-Reformation, educating 25 popes, shaping Vatican II — is historically significant as the intellectual heart of global Catholicism whose trained clergy have shaped the doctrine and governance of a 1.3 billion-member church.", "significanceCategory": "world-changing"},
    }),
    ("university-of-warsaw", {
        "summary": "The University of Warsaw (Uniwersytet Warszawski), founded in 1816 — is Poland's largest and most prestigious university, the flagship institution of the Polish nation's capital and central to Poland's intellectual tradition of resistance to foreign occupation. Warsaw's history as a capital of a nation that was partitioned between Russia, Prussia, and Austria (1795-1918), occupied by Nazi Germany (1939-1945, with the city 85% destroyed after the 1944 Warsaw Uprising), and then placed under Soviet-backed communist rule (1945-1989), makes the University of Warsaw one of history's most persistently challenged academic institutions.\n\nThe University of Warsaw's founding by the Kingdom of Poland (under Russian tsar's control) in 1816 was repeatedly suppressed: the November Uprising (1830-1831) led to the university's closure; the January Uprising (1863) led to closure again; World War I disruption; and Nazi occupation during World War II saw the university operate clandestinely (the 'Underground University' — Tajne Komplety — with approximately 1,000 students maintaining education at risk of death). The Warsaw Uprising of August-October 1944 devastated the city and the university's facilities, with the German army's systematic destruction leaving Warsaw 85% ruined.\n\nModern Warsaw University has regained its position as one of Central Europe's leading research universities: producing important scholarship in mathematics (the Warsaw School of Mathematics — Banach-Tarski paradox, Steinhaus, Sierpiński — was one of the 20th century's most remarkable mathematical concentrations), physics, humanities, and social sciences. Poland's post-1989 democratic transition saw the university flourish as a free academic institution for the first time in its history.",
        "causes": ["1816 Kingdom of Poland founding as the new Polish capital's academic flagship", "Polish national identity under Russian, Prussian, and Austrian partition requiring universities as cultural resistance institutions", "Underground University (Tajne Komplety) during Nazi occupation maintaining education at risk of death", "Post-1989 democratic transition allowing the university to operate freely for the first time"],
        "effects": ["Warsaw School of Mathematics producing the Banach-Tarski paradox and foundational 20th-century mathematical discoveries", "Underground University during Nazi occupation maintaining Polish intellectual resistance at risk of death", "Post-1989 democratic transformation enabling Warsaw University to flourish as a free academic institution", "Poland's EU integration supported by Warsaw University-trained scholars and policymakers"],
        "relationships": [{"entity": "Warsaw Uprisings", "relationship": "REPEATEDLY_CLOSED_AND_DEVASTATED_BY_NOVEMBER_AND_JANUARY_AND_1944_UPRISINGS", "note": "The University of Warsaw was repeatedly closed and devastated by Polish uprisings and German occupation"}, {"entity": "Warsaw School of Mathematics", "relationship": "INSTITUTIONAL_HOME_OF_EXTRAORDINARY_MATHEMATICAL_CONCENTRATION_INCLUDING_BANACH-TARSKI", "note": "Warsaw University hosted the Warsaw School of Mathematics, producing foundational 20th-century mathematical discoveries"}, {"entity": "Nazi German Occupation", "relationship": "UNDERGROUND_UNIVERSITY_OPERATING_CLANDESTINELY_AT_RISK_OF_DEATH_DURING", "note": "During Nazi occupation, the university operated as an underground institution with approximately 1,000 students"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The University of Warsaw — repeatedly suppressed, operating underground during Nazi occupation at risk of death, producing the Warsaw School of Mathematics — is historically significant as a symbol of Polish intellectual resistance and one of Central Europe's most persistently resilient academic institutions.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 146 — Class 381 Universities VIII: European & Global Universities")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
