#!/usr/bin/env python3
"""Batch 96 — Class 316 Political Parties V (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/316-Class-316"
FILE_PREFIX = "316"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("communist-party-of-cuba", {
        "summary": "The Communist Party of Cuba (Partido Comunista de Cuba, PCC), established in its current form in 1965 by Fidel Castro through the merger of three revolutionary organizations (the 26th of July Movement, the Popular Socialist Party, and the Revolutionary Directorate), is the only legally recognized political party in Cuba and the governing party of the Cuban state — constitutionally designated as 'the leading force of society and the state' in Article 5 of the Cuban Constitution. The PCC has governed Cuba uninterruptedly since 1965, making it one of the world's longest-ruling governing parties.\n\nCuba's pre-1959 Communist Party (founded 1925) was not the revolutionary vehicle; it was Castro's 26th of July Movement — launched with the failed 1953 Moncada Barracks attack and the 1956-1959 guerrilla campaign — that overthrew Batista. Castro's ideological evolution was gradual: he did not declare Cuba socialist until April 1961 (the day before the Bay of Pigs invasion), and merged the revolutionary organizations into the PCC in 1965. The party's relationship with Moscow was close during the Cold War — Soviet subsidies (approximately $5 billion annually by 1988) kept the Cuban economy viable.\n\nThe PCC's 'Special Period' (1990-1994) following Soviet collapse saw Cuba's economy contract by 35%, requiring dramatic measures (bicycles replacing cars, urban agriculture, tourism expansion). Fidel Castro transferred power to Raúl Castro in 2008 (permanent transfer 2011); Raúl to Miguel Díaz-Canel in 2018 — the first non-Castro to lead Cuba since 1959. The 2021 anti-government protests (11J) were the largest public demonstrations since 1959, testing the party's stability.",
        "causes": ["1959 Cuban Revolution overthrow of Batista by Castro's 26th of July Movement", "1965 merger of three revolutionary organizations into unified PCC under Castro", "Cold War Soviet subsidies $5 billion annually sustaining Cuba's party-state model", "1990 Soviet collapse triggering Special Period and forced economic adaptation"],
        "effects": ["60+ year one-party rule with PCC constitutionally designated state's leading force", "Special Period 1990-1994 forcing 35% economic contraction and major survival adaptations", "2018 Díaz-Canel succession as first non-Castro Cuban leader since 1959", "2021 11J protests as largest anti-government demonstrations in 60+ years of PCC rule"],
        "relationships": [{"entity": "Fidel Castro", "relationship": "FOUNDED_AND_LED_BY", "note": "Castro merged revolutionary organizations into PCC in 1965; led Cuba until 2008 power transfer"}, {"entity": "Soviet Union", "relationship": "SUBSIDIZED_BY", "note": "Soviet $5 billion annual subsidies sustained Cuba's PCC-led economy during Cold War"}, {"entity": "Miguel Díaz-Canel", "relationship": "CURRENT_SECRETARY_GENERAL", "note": "First non-Castro PCC leader since 1959; took power from Raúl Castro in 2018"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Communist Party of Cuba — governing uninterruptedly since 1965 through Soviet subsidies, Cold War confrontation with the US, Soviet collapse, and the end of Castro family rule — represents the most durable one-party state in the Western Hemisphere and the primary test case for post-Soviet communist governance adaptation.", "significanceCategory": "world-changing"},
    }),
    ("communist-party-of-vietnam", {
        "summary": "The Communist Party of Vietnam (Đảng Cộng sản Việt Nam, CPV), founded 1930 by Hồ Chí Minh in Hong Kong with Comintern support, is the governing and only legal party of Vietnam — leading the country through French colonial resistance (1930-1954), division and reunification war (1954-1975), and post-war transformation from centrally planned to market-oriented economy (Đổi Mới reforms, 1986) that grew Vietnam into one of Asia's fastest-growing economies. The CPV's 'bamboo diplomacy' — flexible foreign policy maintaining autonomy from both China and the West — is considered a model for small-state diplomacy.\n\nHồ Chí Minh founded the Indochinese Communist Party in 1930, reorganized as the Vietnam Workers' Party (1951) and Communist Party of Vietnam (1976 following reunification). The Viet Minh — the CPV's wartime front — expelled French forces after the Battle of Điện Biên Phủ (1954), then resisted American intervention (1965-1973) and reunified Vietnam under communist rule in 1975 after the fall of Saigon.\n\nThe 1986 Đổi Mới ('renovation') reforms — launching a socialist-oriented market economy — transformed Vietnam from one of Asia's poorest countries to one of its fastest-growing: GDP growth averaging 6-7% annually for 30 years, extreme poverty falling from 58% (1993) to under 5% (2023). Vietnam maintains single-party control while pursuing economic liberalization — the CPV's 'bamboo diplomacy' maintains relations with the US (normalized 1995), Russia, and China simultaneously. Vietnam has 100 million people and is the world's largest exporter of cashews and second-largest of coffee.",
        "causes": ["1930 Comintern-backed founding by Hồ Chí Minh in Hong Kong as Indochinese Communist Party", "1954 Điện Biên Phủ victory expelling French colonial forces from Indochina", "1975 Saigon fall and Vietnam reunification under CPV governance", "1986 Đổi Mới market reforms transforming Vietnam into fast-growing economy"],
        "effects": ["1954 Điện Biên Phủ inspiring global anticolonial movements as proof of guerrilla victory over Western power", "1975 reunification creating unified Vietnamese state after 30 years of war", "Đổi Mới reducing extreme poverty from 58% to 5% in 30 years", "Bamboo diplomacy model maintaining US, Russia, China relations simultaneously"],
        "relationships": [{"entity": "Hồ Chí Minh", "relationship": "FOUNDED_BY", "note": "Hồ founded the Indochinese Communist Party in 1930; led Vietnam's independence movement"}, {"entity": "Đổi Mới", "relationship": "LAUNCHED", "note": "CPV's 1986 market reforms transformed Vietnam from poverty to fast-growing economy"}, {"entity": "Battle of Điện Biên Phủ", "relationship": "DECISIVE_VICTORY_AT", "note": "1954 CPV/Viet Minh victory expelled French; inspired global anticolonial movements"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Communist Party of Vietnam — defeating France at Điện Biên Phủ, defeating the US in the longest American war, and then launching Đổi Mới market reforms that lifted millions from poverty — achieved both the 20th century's most stunning military upset and one of its most successful economic transformations.", "significanceCategory": "world-changing"},
    }),
    ("a-just-russia", {
        "summary": "A Just Russia — Patriots — For Truth (Spravedlivaya Rossiya — Patrioty — Za Pravdu), formed as A Just Russia in 2006 by Kremlin orchestration merging three smaller parties (Rodina, Russian Party of Life, and Russian Pensioners' Party) under Sergei Mironov, is Russia's nominally social-democratic opposition party that functions as a 'systemic opposition' — permitted to exist and criticize the government within limits set by the Kremlin, while never challenging Vladimir Putin's power in any fundamental way. Russia's system of 'managed democracy' requires visible multi-party competition without real competitive challenge.\n\nA Just Russia was created by the Kremlin's political technologists as a second 'loyal opposition' party to the Communist Party — giving Russian voters who disliked United Russia (Putin's party) but didn't want communism a third option. Mironov has supported Putin consistently on major foreign policy and national security questions (including the 2022 invasion of Ukraine) while criticizing specific domestic social policies. The party's 2021 merger with Patrioti Rossii and Za Pravdu (a nationalist grouping) broadened its nationalist credentials.\n\nThe party holds approximately 27 seats in the State Duma (2021 elections), making it the fourth-largest party. Its social democratic platform — higher wages, stronger social safety net, workers' rights — appeals to nostalgia for Soviet-era social guarantees. The party is considered one of Russia's 'parliamentary parties' (Duma parties) that participate in the Kremlin's managed democratic system without threatening it.",
        "causes": ["2006 Kremlin orchestration merging Rodina, Russian Party of Life, and Pensioners' Party", "Managed democracy design requiring visible social-democratic alternative to United Russia", "Sergei Mironov leadership providing loyal opposition persona while supporting Putin on major issues", "2021 merger with nationalist groupings broadening electoral appeal"],
        "effects": ["Systemic opposition model demonstrating how managed democracy requires contained multi-party facade", "27 Duma seats providing Kremlin-controlled 'social democratic' voice in parliament", "Consistent Putin support on foreign policy including 2022 Ukraine invasion", "Social democratic platform appealing to Soviet social guarantee nostalgia"],
        "relationships": [{"entity": "Sergei Mironov", "relationship": "LED_BY", "note": "Mironov founded and leads A Just Russia; consistently supports Putin on major policy questions"}, {"entity": "United Russia", "relationship": "MANAGED_OPPOSITION_TO", "note": "A Just Russia is Kremlin-designed alternative to United Russia for social-democratic voters"}, {"entity": "Vladimir Putin", "relationship": "SUPPORTS_WITHIN_MANAGED_DEMOCRACY", "note": "Party participates in Russia's managed democracy; never fundamentally challenges Putin's rule"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "A Just Russia is the clearest institutional example of Russia's 'managed democracy' — a political party created by the Kremlin specifically to simulate social-democratic opposition while ensuring no real challenge to United Russia's dominance, making it the definitional case study of political theater in an authoritarian system.", "significanceCategory": "regional"},
    }),
    ("la-france-insoumise", {
        "summary": "La France Insoumise (France Unbowed, LFI), founded in 2016 by Jean-Luc Mélenchon as an anti-establishment left-wing party after his break from the Socialist Party, became France's largest left-wing party by 2022 — winning 142 seats in the National Assembly (second largest party) and making Mélenchon the primary challenger to Emmanuel Macron in the 2022 presidential election, where he came third (21.95%) but nearly edged out Marine Le Pen for the runoff. LFI's emergence displaced the Socialist Party (governing 1997-2002, 2012-2017) as France's dominant left force.\n\nMélenchon created LFI as a 'France Unbowed' movement — deliberately evoking the language of national sovereignty and resistance to neoliberal economics and EU austerity, while maintaining left-wing economics (wealth taxation, minimum wage increases, public services expansion). LFI's social media strategy (YouTube, Hologram rallies where Mélenchon appeared simultaneously at 7 locations via hologram projection) pioneered digital political communication in France. The 2017 presidential campaign (19.58% in first round) established LFI as a major force.\n\nThe 2022 NUPES alliance — LFI leading a left electoral coalition (Socialists, Greens, Communists) for the legislative elections — achieved 142 seats and nearly formed the opposition government. LFI's positions include France's withdrawal from NATO command, renegotiation of EU treaties, and the Sixth Republic (replacing the Fifth Republic's presidential system). The party's anti-Zionism positions have been controversial, with critics alleging antisemitism and supporters defending anti-imperialism.",
        "causes": ["2016 Mélenchon founding after break with Socialist Party to create left alternative to neoliberal PS", "2017 hologram campaign strategy pioneering digital political communication in France", "2022 presidential election 21.95% nearly entering runoff, displacing PS as France's left force", "NUPES coalition 2022 legislative elections winning 142 seats as major National Assembly force"],
        "effects": ["Socialist Party displacement as France's dominant left force after 2022 elections", "142 National Assembly seats making LFI France's main opposition grouping", "Digital campaign innovation (hologram rallies) influencing French political communication", "Anti-NATO, anti-EU austerity platform challenging mainstream French foreign policy consensus"],
        "relationships": [{"entity": "Jean-Luc Mélenchon", "relationship": "FOUNDED_AND_LED_BY", "note": "Mélenchon founded LFI 2016 after PS break; 2022 presidential near-runoff established LFI dominance"}, {"entity": "Socialist Party of France", "relationship": "DISPLACED", "note": "LFI displaced PS as France's primary left force in 2022 elections"}, {"entity": "NUPES", "relationship": "LED_COALITION", "note": "LFI led 2022 NUPES left coalition (Socialists, Greens, Communists) to 142 National Assembly seats"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "La France Insoumise — displacing France's century-old Socialist Party as the dominant left force in 10 years and pioneering hologram political rallies — represents the most complete left-party realignment in French political history since the PS's founding, and a global model for insurgent left digital political campaigns.", "significanceCategory": "continental"},
    }),
    ("podemos", {
        "summary": "Podemos (We Can), founded in January 2014 in Spain by Pablo Iglesias Turrión and a group of political scientists from the Complutense University of Madrid following the 15-M Indignados movement (2011), rose from 0 to 5 MEPs in four months, became Spain's third party in 2015 national elections, and entered government as a junior coalition partner with the PSOE (2020) — the first time a leftist coalition had governed Spain since the Second Republic (1931-1936). Podemos pioneered the 'discursive war' strategy: reframing politics as 'people vs. caste' rather than 'left vs. right'.\n\nThe 15-M Indignados movement (May 2011) — when hundreds of thousands occupied squares across Spain in protest against austerity, unemployment (25%, youth 50%), and political corruption — was Podemos's founding energy. Iglesias's 'Podemos' lecture at Complutense (January 2014) proposed a 'discourse machine': avoiding left-right framing in favor of 'democratic regeneration vs. the caste.' The January 2014 founding manifesto gathered 50,000 signatures in 24 hours.\n\nPodemos's structural innovations: elected leadership through online voting (circulares), citizens' assemblies for policy, and deliberate use of TV talk shows (Iglesias became Spain's most famous political commentator before founding Podemos). The 2015 'Vistalegre I' assembly approved a more hierarchical structure; the 2020 coalition with PSOE (Pedro Sánchez) made Iglesias Vice President. Iglesias resigned in 2021 to run (unsuccessfully) for Madrid Community President; Yolanda Díaz succeeded him as Sumar leader, broadening the coalition.",
        "causes": ["2011 15-M Indignados movement occupying squares against austerity, 25% unemployment, and corruption", "January 2014 founding by Iglesias and Complutense academics using discourse-machine strategy", "2015 5.2 million votes (20.65%) in national elections as Spain's third party", "2020 PSOE-Podemos coalition as Spain's first leftist governing coalition since 1936"],
        "effects": ["First leftist governing coalition in Spain since Second Republic (1931-1936)", "People vs. caste political framing influencing European left populist parties globally", "Yolanda Díaz Sumar coalition succeeding Podemos and expanding left electoral front", "Podemos pioneering online membership voting and citizens' assemblies in party democracy"],
        "relationships": [{"entity": "Pablo Iglesias Turrión", "relationship": "FOUNDED_AND_LED_BY", "note": "Iglesias founded Podemos 2014; served as VP of Spain 2020-2021 in PSOE coalition"}, {"entity": "15-M Indignados Movement", "relationship": "EMERGED_FROM", "note": "2011 Indignados squares occupation provided Podemos's founding political energy and audience"}, {"entity": "Pedro Sánchez", "relationship": "COALITION_PARTNER", "note": "PSOE-Podemos 2020 coalition under Sánchez made Spain's first leftist government since 1936"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Podemos — rising from 0 to government in six years using digital organization, discourse-machine strategy, and Indignados energy — achieved Spain's first leftist government since 1936 and pioneered the European left-populist political formula that inspired Syriza, LFI, and Corbynism.", "significanceCategory": "world-changing"},
    }),
    ("united-russia", {
        "summary": "United Russia (Yedinaya Rossiya), founded 2001 by the merger of three pro-Kremlin parties under Vladimir Putin's patronage, is Russia's dominant governing party — holding 324 of 450 State Duma seats (2021), providing the institutional architecture for Putin's political system, and functioning less as an ideological party than as a 'party of power' that aggregates bureaucratic, military, and business elites around the presidential office. United Russia is the world's largest right-wing governing party by membership (2 million members) and the institutional backbone of Putin's system.\n\nUnited Russia was created in 2001 through the merger of Unity (Yedinstvo, founded 1999 immediately before the 1999 Duma elections to support Putin) with Fatherland-All Russia (Otechestvo-Vsya Rossiya). Its 2003 Duma supermajority was achieved through a combination of genuine popularity (Putin's approval ratings 70-80%) and systematic voter manipulation. The party's ideology — 'conservatism' and 'sovereign democracy' — was formulated by Kremlin political technologist Vladislav Surkov.\n\nUnited Russia's paradox: Putin himself is not formally a member (though he chairs the party and endorses its candidates), creating the unusual fiction of a party-of-power whose leader stands above the party. The party's 2011 protest crisis — when massive protests followed fraudulent Duma elections (the 'For Fair Elections' protests, December 2011-January 2012) — briefly threatened its dominance. Opposition blogger Alexei Navalny called it the 'Party of Crooks and Thieves,' a label that spread widely. The 2022 Ukraine invasion was unanimously supported by United Russia Duma members.",
        "causes": ["2001 founding through merger of Unity and Fatherland-All Russia under Putin patronage", "2003 Duma supermajority combining genuine popularity with systematic election manipulation", "Vladislav Surkov 'sovereign democracy' ideology formulating conservative nationalist party identity", "2022 unanimous Duma support for Ukraine invasion demonstrating party-state integration"],
        "effects": ["324 of 450 Duma seats (2021) providing institutional backbone for Putin's political system", "Party of power model aggregating bureaucratic, military, business elites around presidency", "'Party of Crooks and Thieves' label by Navalny spreading as anti-corruption opposition symbol", "2011 For Fair Elections protests testing but not breaking United Russia's dominance"],
        "relationships": [{"entity": "Vladimir Putin", "relationship": "PATRONIZED_AND_CHAIRS", "note": "Putin chairs United Russia without formal membership; party functions as institutional vehicle for his system"}, {"entity": "Vladislav Surkov", "relationship": "IDEOLOGY_FORMULATED_BY", "note": "Surkov's 'sovereign democracy' concept defined United Russia's conservative nationalist ideology"}, {"entity": "Alexei Navalny", "relationship": "OPPOSED_BY", "note": "Navalny's 'Party of Crooks and Thieves' label became primary anti-United Russia slogan"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "United Russia — the world's largest right-wing governing party, designed by Kremlin political technologists as a party-of-power apparatus rather than an ideological movement — is the definitive institutional model for 21st-century authoritarian 'managed democracy,' where electoral competition exists within a system designed to guarantee one outcome.", "significanceCategory": "world-changing"},
    }),
    ("pirate-party", {
        "summary": "The Pirate Party (Piratpartiet), founded January 1, 2006, in Sweden by Rick Falkvinge, is the world's first and globally most influential digital rights political party — established in direct response to the Swedish Antipiracy Bureau's January 2006 police raid on The Pirate Bay servers, growing from Swedish municipal politics to the European Parliament (2 MEPs in 2009, 3 in 2014), inspiring pirate parties in 60+ countries, and fundamentally inserting digital rights, internet freedom, privacy, transparency, and copyright reform into mainstream European political discourse.\n\nFalkvinge launched the party three days after the Pirate Bay raid, gathering 1,000 supporters in 24 hours. The 2009 European Parliament elections — boosted by the Pirate Bay trial (Gottfrid Svartholm, Peter Sunde convicted of copyright infringement in April 2009) — gave the party 7.1% of the Swedish EP vote and 2 seats, making it the EU's first digital rights party in the European Parliament. Pirate parties spread globally: Germany's Piratenpartei entered the Berlin state parliament (2011, 8.9%) and won seats in four German state parliaments; Iceland's Pirate Party polled 22% nationally (2016); Czech Pirates entered government.\n\nThe Pirate Party's legacy is primarily discursive: parties that did not survive electorally nonetheless forced major parties to address digital rights, privacy (GDPR), copyright reform, and internet freedom. The 2016 WikiLeaks/Assange era gave pirate politics renewed urgency. Czech Pirate Party (Piráti) entered the Czech governing coalition (2021). The movement pioneered liquid democracy (delegative voting), open source party governance, and unconditional basic income as policy.",
        "causes": ["January 2006 founding by Falkvinge in direct response to Pirate Bay server raid", "2009 Pirate Bay trial convictions boosting Swedish EP vote to 7.1% and first EU seats", "Global spread to 60+ countries with Germany and Iceland achieving most significant electoral results", "GDPR and EU digital rights legislation influenced by decade of pirate party advocacy"],
        "effects": ["First digital rights party in EU Parliament (2009) forcing mainstream parties to address internet freedom", "GDPR and EU copyright reform influenced by decade of pirate party digital rights advocacy", "Liquid democracy political model pioneered and spreading through pirate party governance", "Czech Pirate Party entering governing coalition (2021) as movement's highest governmental achievement"],
        "relationships": [{"entity": "Rick Falkvinge", "relationship": "FOUNDED_BY", "note": "Falkvinge founded Pirate Party January 1, 2006, three days after Pirate Bay raid"}, {"entity": "The Pirate Bay", "relationship": "FOUNDED_IN_RESPONSE_TO_RAID_ON", "note": "January 2006 Pirate Bay server raid directly triggered party's founding"}, {"entity": "European Parliament", "relationship": "WON_SEATS_IN", "note": "2 MEPs in 2009 elections (boosted by Pirate Bay trial) made it first digital rights EU parliamentary party"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Pirate Party — emerging from a file-sharing piracy controversy and spreading to 60 countries — proved that a political party founded on digital rights could force GDPR-level privacy legislation and copyright reform by inserting digital issues into mainstream discourse, even when the party itself lost most elections.", "significanceCategory": "continental"},
    }),
    ("green-party-of-the-united-states", {
        "summary": "The Green Party of the United States (GPUS), founded 2001 as a national federation of state Green parties (the oldest of which date to 1984), is America's most significant third party of the left — achieving national prominence through Ralph Nader's 2000 presidential campaign (2.74%, 2.88 million votes) that many Democrats blame for Al Gore's Florida defeat and George W. Bush's election, making the Greens the most consequential spoiler party in American electoral history. Nader's 97,421 votes in Florida (Bush won by 537) remains the most debated third-party vote in US history.\n\nThe Green Party emerged from the Green movement (environmental politics, Four Pillars: ecology, social justice, grassroots democracy, nonviolence) brought to the US from German Grünen influence. State Green parties formed from the 1980s; Nader ran as Green presidential candidate in 1996 (0.71%) and 2000 (2.74%). The 2000 election controversy made the Greens politically radioactive to many left-leaning voters: 'lesser-evil' voting became the dominant strategy for progressives, suppressing Green support for 20 years.\n\nJill Stein ran as Green presidential candidate in 2012 (0.36%) and 2016 (1.07%, 1.46 million votes) — with her 51,463 Wisconsin votes exceeding Trump's 22,748 margin again raising the spoiler debate. The Green Party's Four Pillars platform (ecology, social justice, grassroots democracy, nonviolence) and Green New Deal proposal preceded and influenced the Democratic Party's own Green New Deal (2019) championed by Alexandria Ocasio-Cortez.",
        "causes": ["1984-1990s state Green party formations from German Grünen environmental politics influence", "2001 national GPUS federation formation from state Green party network", "2000 Nader campaign 2.74% nationally with 97,421 Florida votes making Greens decisive spoiler", "Green New Deal proposal preceding and influencing AOC-championed 2019 Democratic version"],
        "effects": ["2000 Florida spoiler role (97,421 Nader votes vs. 537 Bush margin) shaping 20 years of US left politics", "Lesser-evil voting norm among US progressives suppressing Green support as direct result", "Green New Deal concept developed by GPUS preceding mainstream Democratic adoption", "Jill Stein 2016 Wisconsin spoiler debate reinvigorating Nader spoiler controversy"],
        "relationships": [{"entity": "Ralph Nader", "relationship": "2000_PRESIDENTIAL_CANDIDATE", "note": "Nader's 97,421 Florida votes vs. Bush's 537 margin made Greens US history's most consequential spoiler"}, {"entity": "Al Gore", "relationship": "SPOILER_AGAINST", "note": "2000 Florida spoiler argument: Nader votes caused Gore's Florida defeat and Bush's election"}, {"entity": "Green New Deal", "relationship": "PIONEERED_POLICY", "note": "GPUS Green New Deal proposal preceded and influenced Democratic Party's 2019 GND version"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Green Party of the United States — through Nader's 97,421 Florida votes in 2000 that almost certainly cost Al Gore the presidency — is the most consequential spoiler party in American electoral history, with downstream effects on climate policy (Bush's rejection of Kyoto), the Iraq War, and two decades of US political development.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 96 — Class 316 Political Parties V")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
