#!/usr/bin/env python3
"""Batch 74 — Class 341 Cathedrals II (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/341-Class-341"
FILE_PREFIX = "341"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("abbey-of-st-victor", {
        "summary": "The Abbey of Saint-Victor in Paris was a medieval Augustinian abbey founded in 1108 by William of Champeaux, one of the greatest philosophical minds of the early 12th century, which became a leading center of mystical theology and scholarship in medieval Europe. The Victorine school of theology it produced — combining rigorous biblical scholarship with mystical contemplation — influenced Thomas Aquinas, Bonaventure, and the entire scholastic tradition of medieval Christian thought.\n\nWilliam of Champeaux founded Saint-Victor after losing a famous debate to his student Peter Abelard, withdrawing from Paris's cathedral schools to establish a regular monastic community. The school attracted outstanding scholars: Hugh of Saint-Victor (1096-1141), whose Didascalicon created medieval Europe's first systematic classification of the sciences, and Richard of Saint-Victor, whose mystical theology on contemplation influenced Dante and medieval mysticism.\n\nThe Victorine synthesis of rational scholarship and mystical contemplation represented a distinctive approach: unlike Peter Abelard's purely dialectical theology or Bernard of Clairvaux's purely affective mysticism, the Victorines sought to integrate both reason and love in the ascent to God. Hugh of Saint-Victor's phrase 'Learn everything; you will find later that nothing is superfluous' became a motto for medieval encyclopedic learning. The abbey survived until the French Revolution, when it was suppressed in 1790.",
        "causes": ["William of Champeaux's 1108 withdrawal from Paris cathedral schools after defeat by Abelard", "Augustinian Rule providing intellectual framework for monastic-scholarly life", "Paris's emergence as European intellectual center creating demand for theological synthesis", "Biblical scholarship tradition requiring systematic hermeneutical method"],
        "effects": ["Victorine school synthesized rational scholarship and mystical contemplation influencing scholasticism", "Hugh of Saint-Victor's Didascalicon created first medieval classification of sciences", "Richard of Saint-Victor's mystical theology influenced Dante and medieval Christian mysticism", "Victorine approach shaped Thomas Aquinas's integration of faith and reason"],
        "relationships": [{"entity": "William of Champeaux", "relationship": "FOUNDED_BY", "note": "Founded abbey in 1108 after losing debate to Abelard"}, {"entity": "Hugh of Saint-Victor", "relationship": "PRODUCED", "note": "Hugh's Didascalicon and theological works defined Victorine school's intellectual tradition"}, {"entity": "Peter Abelard", "relationship": "INTELLECTUALLY_OPPOSED_BY", "note": "Abelard's defeat of Champeaux in debate triggered Saint-Victor's founding"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Abbey of Saint-Victor's Victorine school produced medieval Europe's most successful synthesis of rational scholarship and mystical contemplation — an approach that influenced Thomas Aquinas, Dante, and the entire trajectory of Western Christian thought.", "significanceCategory": "continental"},
    }),
    ("hagia-sophia-church", {
        "summary": "Hagia Sophia (Holy Wisdom) in Constantinople/Istanbul is the world's most historically significant religious building, serving consecutively as a Byzantine Christian cathedral (537-1453 CE), Ottoman imperial mosque (1453-1934 CE), secular museum (1934-2020 CE), and active mosque again (2020-present) — embodying 1,500 years of religious and political contest over the Eastern Mediterranean's holiest space. Its dome, rising 55.6 meters above the floor on a 31-meter diameter, was the world's largest for nearly a millennium, inspiring every subsequent great dome in Islamic and Christian architecture.\n\nJustinian I commissioned Hagia Sophia after the original church was burned in the Nika Riots (532 CE). Architects Anthemios of Tralles and Isidoros of Miletus designed an unprecedented structure: a massive dome appearing to float on light through 40 windows at its base, supported by half-domes and piers in a revolutionary solution to the problem of placing a round dome on a square floor plan. 'Solomon, I have surpassed thee!' Justinian reportedly said upon entering — claiming superiority over the First Temple.\n\nMehmed II converted Hagia Sophia to a mosque in 1453 immediately after conquering Constantinople, adding minarets, Islamic calligraphic medallions, and covering Christian mosaics with plaster. Mustafa Kemal Atatürk converted it to a secular museum in 1934 as a symbol of modern Turkish secularism. Erdoğan's 2020 reconversion to an active mosque — greeted with prayer outside by thousands of Turkish Muslims — reversed Atatürk's secularist symbol and provoked international controversy.",
        "causes": ["Byzantine Emperor Justinian I's commissioning of new cathedral after Nika Riots 532 CE", "Anthemios and Isidoros's revolutionary structural engineering solving dome-on-square problem", "Ottoman conquest 1453 requiring conversion of Constantinople's central church to mosque", "Atatürk's 1934 secularization reflecting Kemalist modernism and rejection of Ottoman identity"],
        "effects": ["Dome design inspired Sultanahmet (Blue Mosque), Süleymaniye, and all subsequent Ottoman mosque architecture", "1,500 years of continuous religious use across multiple faiths is unmatched", "2020 reconversion to mosque reversed Atatürk's secular symbol", "Largest dome in the world for nearly 1,000 years established standard for monumental religious architecture"],
        "relationships": [{"entity": "Justinian I", "relationship": "COMMISSIONED_BY", "note": "Justinian built Hagia Sophia 532-537 CE after Nika Riots destroyed predecessor"}, {"entity": "Mehmed II", "relationship": "CONVERTED_BY", "note": "Mehmed converted Hagia Sophia to mosque immediately after conquering Constantinople in 1453"}, {"entity": "Atatürk", "relationship": "SECULARIZED_BY", "note": "Atatürk converted to museum in 1934 as symbol of Turkish secularism; reversed by Erdoğan in 2020"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "Hagia Sophia's 1,500-year history as a contested sacred space — converted from cathedral to mosque to museum to mosque again — makes it the single building most expressive of the religious and political contest between Christianity and Islam over the Eastern Mediterranean.", "significanceCategory": "world-changing"},
    }),
    ("st-pauls-cathedral", {
        "summary": "St Paul's Cathedral in London is the masterpiece of Sir Christopher Wren, built between 1675 and 1710 CE on the site of Old St Paul's Cathedral destroyed in the Great Fire of London (1666), and the spiritual centre of the Church of England. Its iconic dome — 111 metres tall, the second-largest cathedral dome in the world after St Peter's in Rome — has dominated London's skyline for 300 years and became a symbol of British national resilience during the Second World War when the cathedral miraculously survived the Blitz.\n\nOld St Paul's Cathedral, built from 1087, was the largest church in medieval England and one of Europe's great cathedrals. The Great Fire of London (September 1666) destroyed it entirely. Christopher Wren submitted five designs before the final was approved — the 'Warrant Design' — though Wren continued modifying it throughout construction. The dome uses an innovative triple-shell design: an inner dome visible from the interior, a brick cone supporting the stone lantern above, and an outer lead-covered dome visible from the city.\n\nSt Paul's hosted the funerals of Horatio Nelson (1806), Arthur Wellesley Duke of Wellington (1852), Winston Churchill (1965), and the weddings of Prince Charles and Diana Spencer (1981). The wartime photograph of St Paul's dome rising through smoke and flames during the December 1940 Blitz became one of Britain's most iconic images — used by the Ministry of Information to demonstrate national resilience.",
        "causes": ["Great Fire of London 1666 destroying Old St Paul's Cathedral creating need for replacement", "Christopher Wren's appointment as Surveyor of the King's Works enabling architectural genius", "Church of England's need for symbolic metropolitan cathedral matching Catholic St Peter's", "Donations and coal tax funding enabling 35-year construction"],
        "effects": ["300-year London skyline dominance making it Britain's most recognizable non-secular building", "Wren's triple-dome innovation influenced Georgian and neoclassical church architecture worldwide", "1940 Blitz photo of dome through smoke became defining image of British wartime resilience", "State funerals of Nelson, Wellington, Churchill established cathedral as national memorial space"],
        "relationships": [{"entity": "Christopher Wren", "relationship": "DESIGNED_BY", "note": "Wren's masterpiece built 1675-1710 after Great Fire destroyed medieval predecessor"}, {"entity": "Winston Churchill", "relationship": "FUNERAL_OF", "note": "Churchill's 1965 state funeral at St Paul's — last great imperial state funeral"}, {"entity": "Great Fire of London", "relationship": "OCCASIONED_BY", "note": "1666 fire destroyed Old St Paul's necessitating Wren's new cathedral"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "St Paul's Cathedral's survival of the 1940 Blitz while serving as the focal point of British national resilience — immortalized in photographs — made it not merely a cathedral but the symbol of a nation refusing to yield.", "significanceCategory": "world-changing"},
    }),
    ("notre-dame-cathedral", {
        "summary": "Notre-Dame Cathedral of Paris (Notre-Dame de Paris) is the supreme example of French Gothic architecture, built between 1163 and 1345 CE on the Île de la Cité, heart of medieval Paris, and one of the world's most visited sacred monuments before its devastating 2019 fire. Notre-Dame has witnessed France's most significant historical events for 800 years: Henry VI of England crowned King of France within its walls (1431), Napoleon's coronation as Emperor (1804), Charles de Gaulle's liberation mass (1944), and the funerals of French presidents and military heroes.\n\nBishop Maurice de Sully began construction in 1163 under Louis VII. Notre-Dame was an architectural laboratory for Gothic innovations: flying buttresses (enabling walls of stained glass), ribbed vaulting, and pointed arches reaching 35 metres. The cathedral's three rose windows — especially the north rose window (1250 CE) — are among the greatest achievements of medieval stained glass art, their deep blues and reds created through techniques partially lost in the 12th century.\n\nThe April 2019 fire, broadcast live to the world, destroyed the 19th-century spire and most of the lead roof, and shocked the global public with what felt like the destruction of civilization itself. Emmanuel Macron's promise to rebuild Notre-Dame within five years became a national and global project: €840 million was raised within 48 hours from the Pinault and Arnault families alone. The cathedral is scheduled to reopen in December 2024 — testimony to the power of architectural heritage to mobilize collective resources.",
        "causes": ["Bishop Maurice de Sully's 1163 vision for cathedral worthy of Paris's emerging prominence", "Gothic architectural revolution enabling unprecedented height and light through new structural techniques", "Île de la Cité's political centrality making cathedral expression of French royal power", "April 2019 fire during restoration work triggering global cultural emergency response"],
        "effects": ["Flying buttresses demonstrated at Notre-Dame became defining Gothic structural innovation", "Napoleon's 1804 coronation made Notre-Dame symbolic locus of French imperial power", "2019 fire raised €840 million globally in 48 hours demonstrating cultural heritage value", "Scheduled 2024 reopening after €840 million restoration is largest single heritage restoration"],
        "relationships": [{"entity": "Napoleon Bonaparte", "relationship": "CORONATION_SITE_OF", "note": "Napoleon crowned himself Emperor at Notre-Dame in 1804"}, {"entity": "Victor Hugo", "relationship": "IMMORTALIZED_BY", "note": "Hugo's 1831 'Notre-Dame de Paris' novel made cathedral famous and spurred Gothic Revival preservation"}, {"entity": "Maurice de Sully", "relationship": "COMMISSIONED_BY", "note": "Bishop of Paris began construction in 1163"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Notre-Dame de Paris — whose 2019 fire mobilized €840 million in 48 hours from across the world — is the building that most dramatically demonstrated that architectural heritage transcends religion, nationality, and politics in its claim on human emotion.", "significanceCategory": "world-changing"},
    }),
    ("orvieto-cathedral", {
        "summary": "Orvieto Cathedral (Duomo di Orvieto) in Umbria, central Italy, is one of the finest examples of Italian Gothic architecture, begun in 1290 CE to commemorate the Miracle of Bolsena (1263), and famous for Luca Signorelli's Last Judgment fresco cycle (1499-1504 CE) in the Chapel of San Brizio — a work that profoundly influenced Michelangelo's Sistine Chapel ceiling. The cathedral's polychrome marble façade, designed by Lorenzo Maitani, is considered the most beautiful Gothic facade in Italy.\n\nThe cathedral was built to house the Corporal of Bolsena — a linen cloth stained with blood from a eucharistic miracle in 1263, when a German priest's doubts about transubstantiation were resolved when the host bled. Pope Urban IV witnessed the relic, issued the bull Transiturus in 1264, and commissioned Thomas Aquinas to write Corpus Christi — the feast celebrating the Eucharist. Orvieto Cathedral was thus built to honor the theological controversy that produced one of Christianity's greatest feasts.\n\nLuca Signorelli's frescoes in the San Brizio chapel (1499-1504) depicting the Antichrist, the End of Days, the Resurrection of the Dead, and the Damned Cast into Hell, are considered the most radical pre-Renaissance treatment of the Last Judgment. Michelangelo visited Orvieto specifically to study Signorelli's muscular, foreshortened figures before painting the Sistine Chapel — making Signorelli's work arguably the most influential fresco in Italian art history beyond Michelangelo himself.",
        "causes": ["Miracle of Bolsena 1263 and resulting Corpus Christi doctrine requiring commemorative cathedral", "Pope Urban IV's bull Transiturus making Orvieto pilgrimage destination for relic", "Maitani's polychrome marble façade design establishing Italian Gothic aesthetic", "Signorelli's commission to complete San Brizio chapel begun by Fra Angelico"],
        "effects": ["Corpus Christi feast initiated by Bolsena miracle became universal Catholic celebration", "Signorelli's Last Judgment frescoes directly influenced Michelangelo's Sistine Chapel", "Maitani's polychrome façade established model for Italian Gothic church decoration", "Cathedral preserved Corporal of Bolsena making Orvieto Eucharistic pilgrimage destination"],
        "relationships": [{"entity": "Luca Signorelli", "relationship": "FRESCOED_BY", "note": "Signorelli's 1499-1504 Last Judgment frescoes directly influenced Michelangelo"}, {"entity": "Thomas Aquinas", "relationship": "CONNECTED_TO", "note": "Aquinas wrote Corpus Christi liturgy 1264 in response to Bolsena miracle that prompted cathedral"}, {"entity": "Michelangelo", "relationship": "INFLUENCED", "note": "Michelangelo studied Signorelli's Orvieto frescoes before painting Sistine Chapel"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Orvieto Cathedral's significance transcends architecture: its Signorelli frescoes directly influenced Michelangelo's Sistine Chapel, making it the overlooked link in Western art's greatest chain of inspiration.", "significanceCategory": "continental"},
    }),
    ("ravenna-cathedral", {
        "summary": "Ravenna Cathedral (Cattedrale dell'Assunzione di Maria Vergine) and the complex of Early Christian and Byzantine monuments surrounding it in Ravenna, Italy, represent the world's most complete surviving collection of early Byzantine mosaics, dating from the 5th and 6th centuries CE when Ravenna served as capital of the Western Roman Empire (402-476 CE), the Ostrogothic Kingdom (493-540 CE), and the Byzantine Exarchate of Ravenna (540-751 CE). The eight UNESCO-listed Ravenna monuments contain mosaics of extraordinary quality from every phase of this period.\n\nRavenna's mosaics span the three great political-religious phases: the Western Roman/Arian Christian period (Mausoleum of Galla Placidia, Baptistery of Neon), the Ostrogothic/Arian period (Arian Baptistery, Theodoric's Palace), and the Byzantine/Orthodox period (San Vitale, Sant'Apollinare Nuovo, Sant'Apollinare in Classe). San Vitale's famous mosaic panels showing Emperor Justinian I and Empress Theodora (c. 547 CE) are the finest surviving portraits of Byzantine imperial power.\n\nDante Alighieri, exiled from Florence in 1302, spent his final years in Ravenna (1318-1321), completing the Divine Comedy there and dying in the city. His tomb in Ravenna remains a pilgrimage site; Florence has periodically requested his remains but Ravenna refuses. Ravenna's combination of the world's greatest Byzantine mosaics and Dante's tomb makes it among Italy's most culturally significant cities beyond Rome and Florence.",
        "causes": ["Western Roman Empire's 402 transfer of capital to Ravenna making it imperial administrative center", "Theodoric the Great's Ostrogothic kingdom using Ravenna as capital for prosperous reign", "Justinian I's Byzantine reconquest creating need for new Orthodox Christian artistic program", "Ravenna's stability protecting monuments from destruction suffered elsewhere in post-Roman West"],
        "effects": ["World's most complete collection of early Byzantine mosaics survived in Ravenna", "Justinian and Theodora mosaic portraits created definitive images of Byzantine imperial couple", "Dante's exile and death in Ravenna connecting medieval literary masterpiece to mosaic city", "UNESCO recognition of eight monuments creating Italy's most complete early Christian complex"],
        "relationships": [{"entity": "Justinian I", "relationship": "DEPICTED_IN", "note": "San Vitale mosaics (547 CE) show Justinian and Theodora in finest surviving Byzantine imperial portraits"}, {"entity": "Theodoric the Great", "relationship": "PATRONIZED_BY", "note": "Ostrogothic king's Ravenna court produced Arian baptistery and palace mosaics"}, {"entity": "Dante Alighieri", "relationship": "DIED_IN", "note": "Dante completed Divine Comedy in Ravenna exile and died there 1321"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Ravenna's mosaic complex preserves more of the ancient and early medieval world in a single city than any other site in Western Europe — spanning Roman, Ostrogothic, and Byzantine civilization in continuous artistic program across 350 years.", "significanceCategory": "world-changing"},
    }),
    ("notre-dame-cathedral-basilica", {
        "summary": "The Notre-Dame Cathedral Basilica of Ottawa (Basilique-cathédrale Notre-Dame d'Ottawa) is Canada's oldest and most historically significant Roman Catholic cathedral, built between 1839 and 1885 CE and designated a National Historic Site of Canada. It stands at the heart of Ottawa, overlooking Parliament Hill, and was the primary Catholic cathedral during the formation of the Canadian Confederation (1867) — its Gothic Revival twin spires rising beside the Parliament buildings that shaped the symbolic landscape of Canada's capital.\n\nThe cathedral was built on land set aside by Colonel By, founder of Bytown (now Ottawa), during the construction of the Rideau Canal. Father Joseph-Bruno Guigues, the first Bishop of Ottawa, oversaw the early construction, which was completed over decades. The twin towers, completed in 1858 and 1890, were designed to visually counterbalance Parliament's Centre Block across the Ottawa River, creating the distinctive Ottawa skyline that frames Canadian federal power between church and state.\n\nThe cathedral houses the famous 1894-1895 pipe organ by Casavant Frères — one of Canada's finest historic instruments — and contains decorative programs reflecting French-Canadian Catholic heritage in the capital. The cathedral's presence beside Parliament Hill, where the French-Canadian Catholic community's national cathedral stands alongside English Protestant governmental buildings, encapsulates the bilingual, bicultural tension and compromise at the heart of Canadian confederation.",
        "causes": ["1839 establishment on land allocated by Canal founder By for Catholic presence in Bytown", "French-Canadian Catholic community's need for cathedral in the emerging capital city", "Canadian Confederation 1867 requiring symbolic religious counterpart to parliamentary buildings", "Gothic Revival architecture's popularity in British colonial religious construction"],
        "effects": ["Twin spires created Ottawa skyline balancing church and state in Canada's capital", "Cathedral served French-Canadian Catholic community in predominantly Protestant capital", "1894 Casavant Frères organ became one of Canada's finest historic instruments", "National Historic Site designation acknowledging role in Canadian confederation history"],
        "relationships": [{"entity": "Canadian Confederation", "relationship": "CONTEMPORANEOUS_WITH", "note": "Cathedral construction and completion occurred alongside Canadian Confederation 1867"}, {"entity": "Parliament of Canada", "relationship": "VISUALLY_BALANCES", "note": "Gothic twin spires designed to counterbalance Parliament Hill across Ottawa skyline"}, {"entity": "Casavant Frères", "relationship": "ORGAN_BY", "note": "Famous 1894-95 Casavant Frères pipe organ is one of Canada's finest historic instruments"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "Ottawa's Notre-Dame Cathedral Basilica, rising beside Parliament Hill as the French-Canadian Catholic community's symbolic presence in the capital, embodies the church-state balance and French-English duality at the founding of Canadian Confederation.", "significanceCategory": "regional"},
    }),
    ("st-paulus-dom", {
        "summary": "The St. Paulus Dom (Cathedral of Saint Paul) in Münster, Germany, is a Westphalian Romanesque-Gothic cathedral built between 1225 and 1265 CE and one of the most historically significant buildings in Germany due to its role as the site of the Peace of Westphalia negotiations (1648) — the treaties that ended the Thirty Years' War and created the modern state system. The cathedral's St. Paul's Chamber (Friedenssaal, or Hall of Peace) is where delegations from Spain, France, the Holy Roman Empire, Sweden, and the German states negotiated the peace that shaped European political order for centuries.\n\nThe cathedral was originally built in the Romanesque style but transitional Gothic elements were incorporated during construction. Its most famous feature is the astronomic clock (1540 CE) — one of the most complex medieval astronomical clocks in the world, combining calendar, astronomical, and mechanical functions with automated figures processing daily at noon. The clock survived the massive Allied bombing of Münster in 1944 that destroyed 90% of the city.\n\nThe Peace of Westphalia (1648) negotiations in Münster (and simultaneously in Osnabrück) are considered the foundation of the Westphalian system — the principle of national sovereignty and non-interference in internal affairs that became the basis of international law. The treaties recognized Protestant states in the Holy Roman Empire, established religious tolerance principles, and created the balance-of-power framework in Europe. The Friedenssaal (Hall of Peace) preserves the portraits of all 246 peace delegates.",
        "causes": ["1225 bishop's decision to build new cathedral replacing earlier structure", "Westphalian Romanesque-Gothic architectural tradition shaping distinctive construction style", "Münster's selection as negotiation site for Peace of Westphalia 1644-1648", "Thirty Years' War's devastation requiring urgent peace settlement across Europe"],
        "effects": ["Peace of Westphalia signed 1648 established principle of national sovereignty in international law", "Westphalian system created balance-of-power framework shaping European politics to present", "Hall of Peace preserves 246 delegate portraits documenting 1648 negotiations", "Cathedral's 1540 astronomical clock survived 1944 bombing when 90% of city was destroyed"],
        "relationships": [{"entity": "Peace of Westphalia", "relationship": "HOSTED", "note": "1648 Westphalia negotiations in cathedral's Friedenssaal ended Thirty Years' War"}, {"entity": "Thirty Years' War", "relationship": "ENDED_NEGOTIATIONS_AT", "note": "Peace negotiations 1644-1648 at Münster and Osnabrück ended Europe's most destructive war"}, {"entity": "Holy Roman Empire", "relationship": "DIPLOMATIC_VENUE_FOR", "note": "Cathedral's Friedenssaal hosted delegations from across Holy Roman Empire during peace negotiations"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "St. Paulus Dom in Münster hosted the Peace of Westphalia negotiations that created the Westphalian system of national sovereignty — the foundation of international law still governing relations between states 375 years later.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 74 — Class 341 Cathedrals II")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
