#!/usr/bin/env python3
"""Batch 136 — Class 340 Religious Orgs V: African & Apostolic Churches (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/340-Class-340"
FILE_PREFIX = "340"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("african-orthodox-church", {
        "summary": "The African Orthodox Church (AOC), founded in 1921 in New York by George Alexander McGuire — a Black Anglican priest from Antigua who had been associated with Marcus Garvey's Universal Negro Improvement Association (UNIA) — was one of the most significant African American religious institutions of the Harlem Renaissance era, representing the movement for Black religious self-determination that sought to liberate African American Christianity from white ecclesiastical control and create a church that honored the African heritage of its members.\n\nGeorge Alexander McGuire's founding of the African Orthodox Church reflected the broader Black nationalist intellectual movement of the 1920s: at a time when Marcus Garvey was promoting Pan-African pride through UNIA and the Black Star Line, McGuire created a church that deliberately broke with white-controlled denominations, established its own apostolic succession (through the Orthodox Christian succession line), and promoted a theology and liturgy that celebrated African identity — including controversially promoting representations of a Black Madonna and Black Christ as legitimate images.\n\nThe African Orthodox Church had an unexpected influence in East Africa: it provided apostolic succession to the Kikuyu-founded African Independent Pentecostal Church in Kenya and similar African Indigenous Christian movements that sought authentic Christian ordination independent of European missions. This African American-to-African ecclesiastical connection — flowing from Harlem's Black nationalism to East African independence-era Christianity — represents one of the most unusual trans-Atlantic religious connections of the 20th century.",
        "causes": ["George Alexander McGuire's break from white-controlled Anglican/Episcopal hierarchy to establish Black self-governing church", "Marcus Garvey's Pan-African movement providing ideological context for African American religious self-determination", "Harlem Renaissance cultural milieu demanding Black-affirming religious institutions independent of white denominations", "African Americans' desire for authentic apostolic succession independent of racially segregated mainstream churches"],
        "effects": ["African Orthodox Church providing apostolic succession to East African independent church movements", "Black Madonna and Black Christ theology challenging white-dominated Christian iconographic tradition", "Pan-African religious self-determination model influencing African Indigenous Christianity worldwide", "Harlem Renaissance-era Black nationalism institutionalized in independent Black Christian ecclesiastical structure"],
        "relationships": [{"entity": "George Alexander McGuire", "relationship": "FOUNDED_BY_BLACK_NATIONALIST_PRIEST", "note": "McGuire founded the AOC in 1921 as a Black self-governing church during the Harlem Renaissance"}, {"entity": "Marcus Garvey", "relationship": "IDEOLOGICALLY_LINKED_TO_PAN-AFRICAN_MOVEMENT_OF", "note": "The AOC was founded in the context of Garvey's UNIA Pan-African movement that influenced its Black nationalist theology"}, {"entity": "African Independent Churches", "relationship": "PROVIDED_APOSTOLIC_SUCCESSION_TO_EAST_AFRICAN", "note": "The AOC's most lasting impact was providing apostolic succession to East African independent Christian churches seeking non-European ordination"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The African Orthodox Church — founded during the Harlem Renaissance as a monument to Black religious self-determination, providing apostolic succession to East African independent churches — is historically significant as a Harlem Renaissance institution that connected Black American religious nationalism to African independent Christianity.", "significanceCategory": "world-changing"},
    }),
    ("afrikaanse-protestantse-kerk", {
        "summary": "The Afrikaanse Protestantse Kerk (APK, Afrikaans Protestant Church), founded in 1987 as a breakaway from the Nederduits Gereformeerde Kerk (Dutch Reformed Church, DRC) — was established by a minority faction that rejected the DRC's 1986 decision to declare apartheid a sin and to open its congregations to all races, representing the extreme theological right-wing of Afrikaner Christianity that maintained the 19th-century Dutch Reformed theological justification for racial separation.\n\nThe APK's founding in 1987 — just as apartheid was beginning to face increasing international pressure and internal resistance — reflected the divisions within Afrikaner society between those who recognized apartheid as unjust and those who maintained it as God-ordained. The Dutch Reformed Church's role in providing theological legitimacy to apartheid (a role the DRC itself has subsequently repented and confessed as sinful) was central to apartheid's cultural foundation; when the DRC began to reverse this position, conservatives broke away.\n\nThe APK remains a small denomination whose founding represents the extreme theological position that racial separation is divinely mandated — a position now widely condemned as incompatible with Christian ethics. The church's existence is a historical monument to the theological extremity of apartheid justification and a reminder that the DRC's apartheid theology had true believers even as the apartheid system was collapsing.",
        "causes": ["DRC's 1986 declaration that apartheid is a sin prompting conservative breakaway rejecting racial integration", "Apartheid's theological justification by Dutch Reformed Church creating a faction that maintained this position after the DRC renounced it", "Afrikaner theological conservatism maintaining 19th-century race-based Biblical interpretation against reform", "Political pressure on apartheid creating theological division between those who adapted and those who held extreme positions"],
        "effects": ["APK as monument to the extreme theological position that maintained apartheid as divinely ordained even as the system collapsed", "Tiny denomination representing the remnant of apartheid theology after the DRC's repentance", "Historical evidence of how far apartheid theology could go — founding a new denomination rather than accepting racial equality", "APK's existence complicating post-apartheid South Africa's racial and religious reconciliation narrative"],
        "relationships": [{"entity": "Apartheid", "relationship": "THEOLOGICAL_DEFENDERS_WHO_FOUNDED_CHURCH_TO_MAINTAIN_JUSTIFICATION_OF", "note": "The APK was founded by those who maintained apartheid's divine justification when the DRC renounced it in 1986"}, {"entity": "Nederduits Gereformeerde Kerk", "relationship": "FOUNDED_AS_BREAKAWAY_FROM_WHEN_DRC_RENOUNCED_APARTHEID", "note": "The APK broke from the DRC in 1987 specifically rejecting the DRC's 1986 condemnation of apartheid as sinful"}, {"entity": "Afrikaner Christian Nationalism", "relationship": "EXTREME_THEOLOGICAL_POSITION_OF_INSTITUTIONALIZED_IN", "note": "The APK institutionalizes the extreme theological wing of Afrikaner Christian nationalism that refused to accept apartheid's moral failure"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Afrikaanse Protestantse Kerk — founded in 1987 to maintain apartheid theology after the Dutch Reformed Church renounced it — is historically significant as a monument to the extreme theological justification of racial separation and the Afrikaner Christian nationalism that undergirded apartheid.", "significanceCategory": "continental"},
    }),
    ("apostolic-brethren", {
        "summary": "The Apostolic Brethren (also known as the Apostolici or Apostolic Brothers) were a late medieval Italian apocalyptic movement (c.1260-1307) led by Gerard Segarelli and later by Fra Dolcino — one of the most significant heretical movements of the High Middle Ages, condemned by the Catholic Church, persecuted through Inquisition, and ultimately suppressed through a crusade (1305-1307) in the mountains of northern Italy. The movement's destruction culminated in the Crusade of Novara, in which papal forces besieged Fra Dolcino's community in the Piedmontese Alps.\n\nGerard Segarelli founded the Apostolic Brethren in Parma around 1260 as a radical poverty movement inspired by the Franciscan ideals of apostolic poverty taken to an extreme that the Church could not accept: the Brethren rejected all property, clergy, and sacraments, living as wandering beggars in imitation of what they believed was the lifestyle of the original apostles. Segarelli was eventually burned at the stake in 1300, and Fra Dolcino led the movement's final apocalyptic phase.\n\nFra Dolcino's leadership transformed the Apostolic Brethren from a poverty movement into an apocalyptic-revolutionary sect: he developed an elaborate prophetic scheme and eventually led approximately 3,000 followers into the mountains of Piedmont, where they survived for several years against papal crusading forces before their defeat in 1307. Fra Dolcino was captured and tortured to death with extreme cruelty, and his movement was destroyed. Dante Alighieri placed Fra Dolcino in the Inferno as a heretic.",
        "causes": ["Segarelli's 1260s radical apostolic poverty vision inspired by Franciscan ideals taken to heretical extremes", "High Medieval poverty controversy pitting Church wealth against apostolic poverty ideals creating heretical movements", "Fra Dolcino's apocalyptic transformation of the movement into a prophetic-revolutionary sect", "Papal crusade ordered against the movement representing Church's violent response to organized heresy in Italy"],
        "effects": ["Crusade of Novara (1305-1307) destroying the Apostolic Brethren through military force", "Fra Dolcino's martyrdom creating a legendary figure of resistance against Church authority", "Dante's Inferno immortalizing Fra Dolcino as a cautionary example of prophetic heresy", "Movement's suppression contributing to the broader pattern of Church violence against apostolic poverty movements in the Middle Ages"],
        "relationships": [{"entity": "Fra Dolcino", "relationship": "LED_BY_APOCALYPTIC_PROPHET_WHO_TRANSFORMED_MOVEMENT_INTO", "note": "Fra Dolcino transformed the Apostolic Brethren from a poverty movement into an apocalyptic-revolutionary community"}, {"entity": "Inquisition", "relationship": "SUPPRESSED_THROUGH_CRUSADE_ORGANIZED_BY", "note": "The Church used Inquisition and ultimately a crusade to destroy the Apostolic Brethren in the mountains of Piedmont"}, {"entity": "Dante Alighieri", "relationship": "MOVEMENT_IMMORTALIZED_IN_INFERNO_BY", "note": "Dante placed Fra Dolcino in the Inferno, preserving the movement's memory in the greatest literary monument of the Middle Ages"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Apostolic Brethren — one of the High Middle Ages' most significant heretical movements, destroyed through a papal crusade and immortalized by Dante — are historically significant as a monument to the radical poverty movement's challenge to Church authority and the violence of medieval religious repression.", "significanceCategory": "world-changing"},
    }),
    ("apostolic-united-brethren", {
        "summary": "The Apostolic United Brethren (AUB), founded in 1951 as a breakaway from the Fundamentalist Church of Jesus Christ of Latter-Day Saints (FLDS) — is the second-largest fundamentalist Mormon group in North America, practicing polygamy (plural marriage) as a religious obligation based on the original 19th-century teachings of Joseph Smith and Brigham Young that were officially discontinued by the LDS Church in 1890. The AUB is based primarily in Bluffdale, Utah, and the Rocky Mountain region, with thousands of members.\n\nFundamentalist Mormon polygamy is one of the most persistent and legally complex religious minority practices in American history: despite the 1890 LDS manifesto formally suspending polygamy (issued under extreme US government pressure including anti-polygamy laws, the seizure of Church property, and threatened disenfranchisement of Utah Territory), various Mormon fundamentalist groups have maintained polygamy as a religious practice, believing the 1890 manifesto was an impermissible capitulation to government coercion that violated divine revelation.\n\nThe AUB, unlike the more publicly controversial FLDS led by Warren Jeffs, has generally maintained a lower profile and been more open to outsider contact. The group was brought to national attention through the reality television series 'Sister Wives,' which followed an AUB family, bringing rare sympathetic public exposure to the fundamentalist Mormon polygamy community. The AUB's legal status in the US remains complex — polygamy is technically illegal in all states, but prosecutorial practice has varied.",
        "causes": ["1951 split from FLDS reflecting leadership disputes within fundamentalist Mormon polygamy community", "Continuation of Joseph Smith's and Brigham Young's original polygamy revelation rejected by mainstream LDS in 1890", "Conviction that the 1890 LDS manifesto was unconstitutional capitulation to government pressure violating divine revelation", "Fundamentalist Mormon community requiring institutionalized structure for the plural marriage religious practice"],
        "effects": ["AUB as second-largest fundamentalist Mormon group maintaining polygamy as active religious practice", "'Sister Wives' reality television bringing rare sympathetic public exposure to fundamentalist Mormon communities", "Complex legal status navigating American anti-polygamy laws while maintaining religious practice", "AUB distinguished from FLDS by lower-profile, less authoritarian leadership approach"],
        "relationships": [{"entity": "Fundamentalist LDS Movements", "relationship": "SECOND-LARGEST_ORGANIZATION_IN_AMERICAN_FUNDAMENTALIST_MORMON_TRADITION", "note": "The AUB is the second-largest fundamentalist Mormon group maintaining polygamy as a religious practice"}, {"entity": "Joseph Smith", "relationship": "MAINTAINS_ORIGINAL_PLURAL_MARRIAGE_REVELATION_OF", "note": "The AUB continues practicing polygamy based on Joseph Smith's original revelation, rejecting the 1890 LDS manifesto"}, {"entity": "Sister Wives", "relationship": "COMMUNITY_BROUGHT_TO_PUBLIC_ATTENTION_THROUGH_REALITY_TV_SHOW", "note": "The 'Sister Wives' reality show following an AUB family provided rare sympathetic public exposure to the community"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "The Apostolic United Brethren — the second-largest fundamentalist Mormon group maintaining original plural marriage theology, brought to national attention through 'Sister Wives' — is regionally significant as a monument to the persistence of 19th-century Mormon polygamy practice in modern America.", "significanceCategory": "local"},
    }),
    ("assembly-of-canonical-orthodox-bishops-of-france", {
        "summary": "The Assembly of Canonical Orthodox Bishops of France is the coordinating body for Eastern Orthodox Christian bishops in France whose dioceses are recognized as canonical (legitimate) by at least one autocephalous Orthodox church — bringing together bishops of Greek, Russian, Romanian, Serbian, Antiochian, and other Orthodox jurisdictions whose overlapping territorial presence in France represents one of the most complex canonical situations in contemporary Eastern Orthodoxy.\n\nFrance has become one of the most jurisdictionally complex countries in Eastern Orthodoxy: unlike the traditional Eastern Orthodox practice of one bishop per territory (the principle of territorial episcopate), France has multiple Orthodox bishops of different national churches, all claiming canonical status, serving the same French territory. This situation arose from the 20th-century emigration waves — Russian emigration after the 1917 Revolution, Greek emigration throughout the 20th century, Romanian and Bulgarian emigration after WWII and communism, and various other waves — each bringing their respective national church structures.\n\nThe Assembly of Canonical Orthodox Bishops represents the ecumenical Orthodox effort to create coordination among these overlapping jurisdictions while working toward the long-term Orthodox goal of a single local church (according to ancient canonical principles). France's approximately 300,000-400,000 Orthodox Christians represent one of Western Europe's largest Orthodox communities, with the Russian Orthodox tradition (in its various subdivisions, including the Russian Orthodox Church Outside Russia, the Moscow Patriarchate Paris Diocese, and others) being particularly significant.",
        "causes": ["Post-1917 Russian Revolution emigration creating large Russian Orthodox community in France", "20th-century Orthodox emigration waves from Greece, Romania, Bulgaria, Serbia bringing overlapping jurisdictions", "Traditional Orthodox canonical principle of territorial episcopate challenged by diaspora reality in Western Europe", "Ecumenical Orthodox efforts to coordinate overlapping jurisdictions and work toward canonical order"],
        "effects": ["Coordination of multiple Orthodox jurisdictions in France reducing inter-jurisdictional conflicts", "Orthodox ecumenical dialogue in France advanced through bishops' assembly meetings", "300,000-400,000 French Orthodox Christians served through coordinated jurisdictional structure", "Model for Orthodox diaspora coordination in Western Europe influencing similar assemblies in other European countries"],
        "relationships": [{"entity": "Eastern Orthodoxy", "relationship": "JURISDICTIONAL_COORDINATION_BODY_FOR_DIASPORA_PRESENCE_OF", "note": "The Assembly coordinates multiple Orthodox jurisdictions whose overlapping presence in France violates traditional canonical principles"}, {"entity": "Russian Orthodox Emigration", "relationship": "POST-1917_EMIGRATION_CREATING_PRIMARY_ORTHODOX_COMMUNITY_COORDINATED_BY", "note": "The 1917 Russian Revolution emigration created the largest French Orthodox community whose jurisdictional complexity drives the Assembly"}, {"entity": "Orthodox Canonical Order", "relationship": "WORKING_TOWARD_SINGLE_LOCAL_CHURCH_THROUGH_COORDINATING", "note": "The Assembly represents the Orthodox effort to eventually establish canonical order with a single French Orthodox bishop"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "The Assembly of Canonical Orthodox Bishops of France — coordinating multiple overlapping Orthodox jurisdictions created by 20th-century emigration, working toward canonical order in one of Western Europe's most complex Orthodox diaspora situations — is regionally significant as a monument to Orthodox ecumenical coordination.", "significanceCategory": "local"},
    }),
    ("assyrian-evangelical-church", {
        "summary": "The Assyrian Evangelical Church (also known as the Evangelical Church of the East among Assyrian communities) is one of the Protestant denominations that emerged among Assyrian Christians (also known as Nestorian Christians, or members of the Assyrian Church of the East) through the work of American Presbyterian and later British missions in the 19th century — representing one of the most significant episodes of Protestant missionary activity in the ancient Christian communities of Mesopotamia and Persia.\n\nAssyrian Christians are among the world's oldest Christian communities: the Assyrian Church of the East traces its origins to the apostolic mission of Thomas the Apostle in Mesopotamia and claims direct succession to the ancient church that spread Christianity eastward along the Silk Road to China and India by the 7th century CE. This ancient church was nearly destroyed by Tamerlane's massacres (1380s-1400s) and subsequently survived as a small minority in the Hakkari mountains of southeastern Turkey and northwestern Persia.\n\nAmerican Presbyterian missionaries arriving in Urmia (Persia, now Iran) in the 1830s found the Assyrian Church of the East in weakened condition and began educational and spiritual work that led to conversions to Protestantism, creating the Assyrian Evangelical Church as a new denomination within the broader Assyrian community. The Assyrian Christians' 20th century experiences — including the Seyfo (Genocide) during WWI, mass displacement, diaspora — gave the evangelical community's survival particular poignancy.",
        "causes": ["American Presbyterian missionaries arriving in Urmia (Persia) in the 1830s finding the Assyrian Church of the East in weakened condition", "19th-century Protestant missionary movement targeting ancient Eastern Christian communities for revival and reform", "Assyrian Church of the East's theological differences from Western Christianity making Protestant reform appealing to some members", "Educational mission establishing schools among Assyrian communities creating social conditions for evangelical conversion"],
        "effects": ["New Evangelical denomination within Assyrian Christianity creating internal theological pluralism", "Educational institutions established by missions improving literacy and modern education among Assyrian communities", "Assyrian Evangelical community surviving WWI Seyfo Genocide and continuing in diaspora", "Protestantism's introduction among ancient Eastern Christian communities complicating the already complex Assyrian Christian landscape"],
        "relationships": [{"entity": "Assyrian Church of the East", "relationship": "EVANGELICAL_DENOMINATION_EMERGING_FROM_MISSIONS_TO", "note": "The Assyrian Evangelical Church emerged from Protestant missionary work among members of the ancient Assyrian Church of the East"}, {"entity": "American Presbyterian Missions", "relationship": "FOUNDED_THROUGH_19TH-CENTURY_MISSIONARY_WORK_OF", "note": "American Presbyterian missionaries in Urmia (1830s) began the work that led to the Assyrian Evangelical Church's formation"}, {"entity": "Seyfo Genocide", "relationship": "COMMUNITY_SURVIVING_WWI_MASS_KILLING_OF_ASSYRIAN_CHRISTIANS", "note": "The Assyrian Evangelical community survived the WWI Seyfo (Genocide) that killed large proportions of all Assyrian Christian communities"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Assyrian Evangelical Church — formed through American Presbyterian missions to one of the world's oldest Christian communities, surviving the WWI Seyfo Genocide — is historically significant as a monument to Protestant missionary transformation of ancient Eastern Christianity and Assyrian Christian survival.", "significanceCategory": "continental"},
    }),
    ("baptist-convention-of-angola", {
        "summary": "The Baptist Convention of Angola (Portuguese: Convenção Baptista de Angola) is one of the largest Protestant denominations in Angola, emerging from British Baptist Missionary Society work that began in 1878 when George Grenfell and Thomas Comber established missions in the Congo region — creating the most significant Protestant tradition in what became Angola, a tradition with particularly deep roots in the Bakongo people of northern Angola and the Democratic Republic of Congo border region.\n\nThe Baptist Missionary Society's Congo mission (1878 onward) was one of the most historically significant missionary enterprises in Central Africa: establishing schools, translating the Bible into Kikongo and other local languages, training African pastors, and creating an institutional network that survived both Belgian/Portuguese colonialism and the brutal post-independence civil war (1975-2002). The Baptist church networks in the Bakongo region were among the few civil society institutions that maintained continuity through Angola's catastrophic 27-year civil war.\n\nAngola's Baptist Christians — particularly among the Bakongo — have a distinctive historical relationship with Angolan nationalism: many of the founders of the MPLA (Movement for the Popular Liberation of Angola) and FNLA (National Front for the Liberation of Angola) had Baptist education backgrounds, and the church's institutional networks were channels through which nationalist consciousness developed. The independence movement's emergence from mission-educated Angolans created a complex church-state relationship in post-independence Angola.",
        "causes": ["British Baptist Missionary Society Congo mission (1878) establishing Christian presence in what became northern Angola", "George Grenfell and Thomas Comber's foundational missionary work creating sustainable Baptist institutions", "Bakongo people's receptivity to Baptist missions creating a regional religious-cultural transformation", "Bible translation and literacy missions creating educated Angolan leadership that channeled into nationalist movements"],
        "effects": ["Baptist Convention as one of Angola's largest Protestant denominations with Bakongo cultural roots", "Mission-educated Angolans contributing significantly to the independence movement through nationalist organizations", "Church network surviving Angola's catastrophic 27-year civil war (1975-2002) as one of few civil society institutions", "Bible translation into Kikongo and other languages preserving and standardizing African languages through religious publication"],
        "relationships": [{"entity": "Baptist Missionary Society", "relationship": "FOUNDED_THROUGH_1878_CONGO_MISSION_OF", "note": "The Convention emerged from the BMS's 1878 Congo mission by George Grenfell and Thomas Comber"}, {"entity": "Bakongo People", "relationship": "DEEPEST_ROOTS_AMONG_BAKONGO_OF_ANGOLA_AND_CONGO_BORDER", "note": "The Baptist Convention has its strongest roots among the Bakongo people of northern Angola"}, {"entity": "Angolan Independence Movement", "relationship": "MISSION-EDUCATED_NATIONALISTS_EMERGING_FROM_INSTITUTIONAL_NETWORK_OF", "note": "Many MPLA and FNLA founders were Baptist-educated, connecting the church to Angola's independence movement"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Baptist Convention of Angola — emerging from the 1878 BMS Congo mission, deeply rooted in the Bakongo people, whose educational networks produced Angolan nationalist leaders — is historically significant as a monument to the complex relationship between Protestant missions, African literacy, and anti-colonial nationalism.", "significanceCategory": "world-changing"},
    }),
    ("baptist-convention-of-hong-kong", {
        "summary": "The Baptist Convention of Hong Kong (Chinese: 香港浸信會聯會) is one of Hong Kong's most significant Protestant denominations, rooted in American Southern Baptist missions that began in Hong Kong in the 1840s-1850s — representing a major stream of Hong Kong Christianity that has contributed significantly to Hong Kong's extensive private educational network, healthcare institutions, and social services over 170+ years of institutional presence.\n\nHong Kong's Christian community (~11% of the population) has extraordinary institutional significance disproportionate to its size: Christian hospitals, schools, and social service organizations provide a major fraction of Hong Kong's social infrastructure. The Baptist Convention's hospitals (including Baptist Hospital), schools, and social service organizations are among the most important non-government institutions in the territory. Baptist University of Hong Kong (formerly Hong Kong Baptist College, founded 1956) is one of Hong Kong's eight universities.\n\nThe Baptist Convention's history in Hong Kong spans the colonial period, the 1949 Communist victory in China that brought a massive wave of mainland Chinese refugees to Hong Kong (swelling Baptist church membership significantly), the economic miracle of Hong Kong's development into a global financial center, and now the complex post-2020 political situation following the National Security Law that has raised questions about Hong Kong civil society's future. The Convention's institutional networks are among Hong Kong's most important civil society infrastructure.",
        "causes": ["American Southern Baptist missions beginning in Hong Kong (1840s-1850s) establishing Protestant presence", "1949 Communist victory driving mainland Chinese refugees (including Baptist Christians) to Hong Kong", "Hong Kong's British colonial context providing protected space for Christian institution-building", "Baptist Convention's educational and healthcare mission creating extensive institutional infrastructure"],
        "effects": ["Baptist Convention hospitals and schools as major components of Hong Kong's social infrastructure", "Baptist University of Hong Kong (founded 1956) as one of Hong Kong's eight universities", "1949 refugee wave dramatically expanding the Baptist community in Hong Kong", "Post-2020 National Security Law raising questions about Christian civil society's future in Hong Kong"],
        "relationships": [{"entity": "American Southern Baptist Mission", "relationship": "FOUNDED_THROUGH_1840S-50S_HONG_KONG_MISSION_OF", "note": "The Convention emerged from American Southern Baptist missions in Hong Kong beginning in the 1840s-1850s"}, {"entity": "Hong Kong", "relationship": "MAJOR_INSTITUTIONAL_PROVIDER_OF_HOSPITALS_SCHOOLS_AND_SOCIAL_SERVICES_IN", "note": "The Convention's hospitals, schools, and social services are major components of Hong Kong's social infrastructure"}, {"entity": "Baptist University of Hong Kong", "relationship": "FOUNDED_CONVENTION'S_EDUCATIONAL_CROWN_JEWEL", "note": "Baptist University of Hong Kong (1956) is the Convention's most significant educational institution and one of Hong Kong's eight universities"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Baptist Convention of Hong Kong — founding Baptist University and major hospitals and schools, absorbing 1949 mainland refugees, providing critical social infrastructure — is historically significant as one of Hong Kong's most institutionally significant religious bodies over 170+ years.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 136 — Class 340 Religious Orgs V: African & Apostolic Churches")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
