#!/usr/bin/env python3
"""Batch 88 — Class 341 Cathedrals III (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/341-Class-341"
FILE_PREFIX = "341"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("sacré-cœur", {
        "summary": "The Basilica of Sacré-Cœur (Sacred Heart) on Montmartre hill in Paris, consecrated in 1919 after 44 years of construction (begun 1875), is the most politically charged religious building in France — built as a 'national vow' of atonement for the French defeat in the Franco-Prussian War (1870) and the Paris Commune (1871), which conservatives interpreted as divine punishment for France's moral decline. Montmartre hill, where the Paris Commune began (the Commune members shot two generals here in March 1871), became the site of the national Catholic atonement monument — a deliberate political provocation.\n\nThe Sacré-Cœur project was promoted by Catholics who saw France's 1870 defeat by Prussia as God's punishment for the liberal anti-clerical politics of the Second Empire. The National Assembly authorized the church's construction in 1873, with the specific political intent of asserting Catholic France against anticlerical republicanism. The site on Montmartre — the birthplace of the Paris Commune — was chosen by conservatives to symbolically 'reclaim' the hill from revolutionary leftism.\n\nThe basilica was designed by Paul Abadie in Romano-Byzantine style, with its distinctive white travertine stone that actually becomes whiter with rain (calcite washing). The interior houses the largest mosaic in France — Christ in Majesty (475 m²), designed by Luc-Olivier Merson. The bell (La Savoyarde, 19 tons) is France's largest. Sacré-Cœur receives 10 million visitors annually, making it one of Paris's most visited monuments, though it remains a liturgically active basilica with perpetual adoration since 1885.",
        "causes": ["1870 Franco-Prussian War defeat and Paris Commune interpreted by conservatives as divine punishment", "1873 National Assembly authorization as 'national vow' of Catholic atonement", "Montmartre site deliberately chosen to symbolically reclaim Commune birthplace for Catholic France", "44-year construction 1875-1919 funded by Catholic national subscription"],
        "effects": ["Politically charged construction symbolizing Catholic-anticlerical conflict in Third Republic France", "Romano-Byzantine architecture introducing Oriental elements to Paris's predominantly Gothic and Classical skyline", "10 million annual visitors making it one of Paris's most visited sites alongside Eiffel Tower and Louvre", "Perpetual adoration since 1885 maintaining liturgical activity through 140 years of political controversy"],
        "relationships": [{"entity": "Paris Commune", "relationship": "ATONEMENT_FOR", "note": "Conservatives saw Commune as divine punishment; Sacré-Cœur was built on the Commune's birthplace as atonement"}, {"entity": "Paul Abadie", "relationship": "DESIGNED_BY", "note": "Abadie's Romano-Byzantine design with white travertine creates Montmartre's distinctive skyline"}, {"entity": "Franco-Prussian War", "relationship": "ATONEMENT_CONTEXT", "note": "1870 defeat interpreted as divine punishment motivating the national vow for Sacré-Cœur's construction"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Sacré-Cœur is the only major cathedral built as an explicit political act — the Catholic right deliberately constructing it on the Paris Commune's birthplace as a statement of atonement and reclamation — making it the most politically charged religious building in France.", "significanceCategory": "continental"},
    }),
    ("ulm-minster", {
        "summary": "Ulm Minster (Ulmer Münster), a Lutheran Gothic church in Ulm, Baden-Württemberg begun in 1377 and whose main spire was completed in 1890 (after 513 years of construction), holds the world's tallest church steeple at 161.53 meters — surpassing Cologne Cathedral's 157.38 meters to claim the title that the medieval builders had planned but could not achieve. The minster is a civic church (never a cathedral — Ulm had no bishop), built and funded by the city's burghers as a statement of urban pride and civic wealth.\n\nThe foundation stone was laid in 1377 at the decision of Ulm's town council — a civic rather than episcopal institution — to build the grandest church possible as a statement of Ulm's commercial prosperity. The initial architect Ulrich von Ensingen developed the design, with successive master builders refining the drawings over centuries. When the Reformation reached Ulm in 1530, the city converted to Lutheranism and the church became a Protestant minster, abandoning Catholic liturgical requirements while continuing physical construction.\n\nThe 19th-century completion was motivated by German nationalist romanticism — completing medieval projects became a statement of German cultural identity (Cologne Cathedral completed 1880, Ulm 1890). The minster's 768-step spiral staircase to the tower platform, and the 15th-century choir stalls (154 misericords), represent the building's great interior treasures. The city of Ulm was 80% destroyed in a single RAF bombing raid on December 17, 1944, but the minster survived intact — its steeple visible above the rubble — a symbol of continuity amid destruction.",
        "causes": ["1377 civic foundation by Ulm town council as statement of urban commercial prosperity", "Gothic design by Ulrich von Ensingen planned for world's tallest spire from initial conception", "1530 Reformation conversion to Lutheran church changing liturgical use while continuing construction", "1890 completion after 513 years motivated by German nationalist medieval project completion movement"],
        "effects": ["161.53 meter steeple is world's tallest church spire — the medieval ambition finally realized", "Civic ownership model (city, not bishop) demonstrating Protestant urban church independence", "1944 RAF bombing destruction of 80% of Ulm while minster survived becoming symbol of continuity", "768-step tower climb provides most dramatic urban panorama in southwestern Germany"],
        "relationships": [{"entity": "Ulrich von Ensingen", "relationship": "ORIGINAL_ARCHITECT", "note": "Von Ensingen designed the west tower system that would eventually become world's tallest church spire"}, {"entity": "Ulm City Council", "relationship": "FOUNDED_AND_OWNED_BY", "note": "Civic ownership (not episcopal) reflects Lutheran Protestant civic church independence"}, {"entity": "1944 RAF Bombing of Ulm", "relationship": "SURVIVED", "note": "Minster survived intact while 80% of Ulm was destroyed December 17, 1944"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Ulm Minster's 513-year construction — from 1377 to 1890 — producing the world's tallest church spire is the most ambitious multi-generational civic construction project in history, and its survival amid Ulm's 80% wartime destruction made it a symbol of German cultural continuity.", "significanceCategory": "continental"},
    }),
    ("seville-cathedral", {
        "summary": "The Cathedral of Saint Mary of the See in Seville (Catedral de Santa María de la Sede), built between 1401 and 1506 on the site of the Almohad Great Mosque of Seville, is the world's largest Gothic cathedral by floor area, the third-largest church by volume, and the burial site of Christopher Columbus — making it simultaneously the greatest achievement of Gothic ecclesiastical architecture and a monument to the Age of Exploration's most consequential figure. The Giralda bell tower (originally the Almohad mosque's minaret, 1184-1196) was incorporated into the cathedral as a symbol of Reconquista triumph.\n\nWhen the Almohad mosque was converted after the Christian reconquest of Seville (1248), it served the Christian community until the 15th century chapter decided to build 'a church so beautiful and so great that those who see it finished shall think we were mad.' The 116-year construction produced the largest Gothic building in the world by floor area (11,520 m²), with 80 chapels, 93 stained glass windows, and the Capilla Mayor altarpiece (the world's largest retable, 20.5 × 18 meters, with 36 scenes in gilded wood).\n\nColumbus's remains were transferred to Seville from Havana in 1898 after Cuba's independence from Spain, and his coffin is carried by four figures representing the kingdoms of Castile, León, Aragón, and Navarre. The Giralda tower — the Almohad minaret completed in 1198 with a ramp system (not stairs) allowing mounted horses to ascend for the call to prayer — was topped with Renaissance additions in 1568, becoming the model for hundreds of cathedral towers in the Americas built by Spanish colonial church builders.",
        "causes": ["1401 construction beginning on Almohad mosque site with ambition to build world's greatest Gothic church", "116-year construction (1401-1517) producing largest Gothic church by floor area", "Giralda minaret incorporation as symbol of Reconquista triumph over Islamic Seville", "Columbus remains transferred from Havana in 1898 making cathedral American discovery monument"],
        "effects": ["World's largest Gothic cathedral (11,520 m² floor area) and UNESCO World Heritage Site", "Columbus tomb attracting millions of visitors connecting cathedral to American history", "Giralda tower model exported to American colonial cathedrals creating architectural legacy", "World's largest retable altarpiece representing peak of medieval gilded woodwork achievement"],
        "relationships": [{"entity": "Christopher Columbus", "relationship": "BURIAL_SITE_OF", "note": "Columbus remains transferred from Havana 1898; coffin carried by four Spanish kingdom figures"}, {"entity": "Almohad Caliphate", "relationship": "BUILT_ON_MOSQUE_OF", "note": "Cathedral built on 1184 Almohad Great Mosque; Giralda minaret incorporated as bell tower"}, {"entity": "1248 Christian Reconquest of Seville", "relationship": "OCCASIONED_BY", "note": "Fernando III's 1248 reconquest set stage for eventual Gothic cathedral replacing mosque"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Seville Cathedral — the world's largest Gothic church and Columbus's tomb — synthesizes the two defining events of Spanish medieval history: the Reconquista's defeat of the Almohad Caliphate (the Giralda minaret converted to bell tower) and the discovery of the Americas (Columbus's remains).", "significanceCategory": "world-changing"},
    }),
    ("albi-cathedral", {
        "summary": "Albi Cathedral (Cathédrale Sainte-Cécile d'Albi), begun in 1282 and built over 200 years in southern France's Languedoc region, is the world's largest brick cathedral and a fortified church deliberately designed as a military monument — its walls are 1.5 meters thick, its windows minimal, and its overall form resembles a fortress rather than a church. The cathedral's construction followed the Albigensian Crusade (1209-1229), which the Pope launched to exterminate the Cathar heresy; its architectural fortification embodies the Catholic Church's determination to demonstrate power over the region that had harbored heretics.\n\nThe Cathars, a Gnostic dualist sect particularly strong in the Languedoc, had been declared heretical by Pope Innocent III, who launched the Albigensian Crusade in 1209 to destroy them. The Crusade's culminating massacre at Béziers (1209), where 20,000 people were killed including Catholics (the Papal legate reportedly said 'Kill them all, God will know His own'), demonstrated the crusade's total war character. Albi, the region's center, gave the heretics their name — Albigenses.\n\nThe cathedral's interior contains an extraordinary contrast to the austere exterior: the greatest Gothic painted ceiling in the world (flamboyant Gothic paintings covering the entire vault, 1505-1512), an ornate rood screen (1500), and a 15th-century polychrome Last Judgment painting at the west end covering 200 m². The Toulouse-Lautrec Museum, housed in the adjacent Episcopal Palace, makes Albi a dual monument to medieval ecclesiastical power and 19th-century bohemian art. The cathedral's fortified form has been called the most terrifying building of the French Middle Ages.",
        "causes": ["1282 construction beginning as Catholic Church's power statement after Albigensian Crusade destroyed Cathar heresy", "Fortified design with 1.5-meter walls reflecting military character of post-Crusade Catholic reconsolidation", "200-year construction producing world's largest brick building", "Interior decoration 1505-1512 adding elaborate Gothic painted ceiling contrasting with military exterior"],
        "effects": ["World's largest brick cathedral combining military fortress aesthetics with Gothic interior decoration", "Albigensian Crusade architectural monument embedding crusade history in stone", "UNESCO World Heritage Site designation 2010 recognizing unique fortified Gothic architecture", "Toulouse-Lautrec Museum in adjacent Episcopal Palace creating unusual juxtaposition of medieval and modern art"],
        "relationships": [{"entity": "Albigensian Crusade", "relationship": "BUILT_IN_AFTERMATH_OF", "note": "Cathedral's military fortress design embodies Catholic reconsolidation after 1209-1229 Cathar extermination"}, {"entity": "Pope Innocent III", "relationship": "INSTITUTIONAL_AUTHORITY_OF", "note": "Innocent III launched Albigensian Crusade in 1209; Albi Cathedral represents his Church's triumphant power"}, {"entity": "Toulouse-Lautrec", "relationship": "MUSEUM_ADJACENT", "note": "Episcopal Palace houses Toulouse-Lautrec Museum creating medieval-modern artistic pilgrimage site"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Albi Cathedral — the world's largest brick building and a fortified monument to the Albigensian Crusade — is the most architecturally explicit embodiment of medieval Catholic power over heresy, its military exterior encoding the violence used to establish religious conformity.", "significanceCategory": "continental"},
    }),
    ("notre-dame-de-la-garde", {
        "summary": "Notre-Dame de la Garde ('Our Lady of the Watchtower'), the Romano-Byzantine basilica crowning the highest point in Marseille at 162 meters above sea level, completed in 1864 under Napoleon III, is the most beloved building in Marseille and the city's most visible landmark — watched over by a 9.7-meter gilded bronze statue of the Virgin Mary that has guided sailors since the chapel's founding in 1214. The basilica is known by Marseillais as 'La Bonne Mère' (the Good Mother) and remains one of France's most visited pilgrimage sites.\n\nA chapel dedicated to the Virgin Mary has stood on the Garde hill since 1214, when a monk named Pierre obtained permission to build an oratory. The current Neo-Byzantine basilica was designed by architect Henri-Jacques Espérandieu and built 1853-1864, replacing an earlier medieval chapel. The site served as a Royalist and later Vichy stronghold during WWII, and bullet holes from the 1944 Liberation of Marseille are preserved in the basilica's interior walls as deliberate memorials.\n\nThe basilica's interior is decorated with thousands of ex-votos (votive offerings) — small paintings, model ships, photographs, and plaques placed by sailors, fishermen, and pilgrims who survived danger or received answered prayers. The collection of over 5,000 ex-votos represents one of the most remarkable records of popular devotion in France. The gilded Virgin atop the bell tower is visible from 50 kilometers at sea — her most ancient function as maritime landmark preserved in her name.",
        "causes": ["1214 original oratory founding giving 800 years of Marian devotion continuity on the hill", "Napoleon III's 1853-1864 Neo-Byzantine basilica construction replacing medieval chapel", "Maritime role as landmark for Marseille sailors giving practical devotional significance", "Liberation battle 1944 bullet holes preserved as memorial giving WWII historical dimension"],
        "effects": ["La Bonne Mère identity as Marseille's most beloved building and civic symbol", "5,000+ ex-votos creating France's largest collection of popular votive devotion", "2 million annual visitors making it France's most visited non-Parisian religious site", "Gilded Virgin visible 50 km at sea preserving 800-year maritime landmark function"],
        "relationships": [{"entity": "Henri-Jacques Espérandieu", "relationship": "DESIGNED_BY", "note": "Espérandieu's 1853-1864 Neo-Byzantine design created Marseille's most distinctive building"}, {"entity": "Liberation of Marseille", "relationship": "BATTLE_SITE", "note": "1944 Liberation battle bullet holes preserved in interior walls as deliberate memorial"}, {"entity": "Marseille", "relationship": "CIVIC_SYMBOL_OF", "note": "La Bonne Mère identity as city's beloved Good Mother makes basilica Marseille's primary civic symbol"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Notre-Dame de la Garde's 800-year continuity as maritime landmark, its 5,000 ex-votos recording popular devotion, and its preserved Liberation bullet holes make it the building that most completely encodes Marseille's identity as Mediterranean port city and wartime resistance survivor.", "significanceCategory": "continental"},
    }),
    ("saint-patricks-cathedral", {
        "summary": "St Patrick's Cathedral in New York City, the largest decorated Gothic Revival Catholic church in the United States, completed in 1878 and designed by James Renwick Jr. on Fifth Avenue facing Rockefeller Center, served as the physical symbol of Irish Catholic immigrant identity in America — built when Irish immigrants were the most despised ethnic group in American cities, and now receiving 5.5 million visitors annually in New York's most expensive real estate district. The cathedral's construction (1858-1878) during the Civil War era represented an act of community assertion by a community facing 'No Irish Need Apply' discrimination.\n\nArchbishop John Hughes ('Dagger John'), who commissioned the cathedral in 1858, was the most combative figure in American Catholic history — he had threatened to burn New York to the ground if Catholic churches were attacked during anti-Irish riots. The site on Fifth Avenue at 50th Street was then outside the city limits, with Archbishop Hughes purchasing it precisely because it was remote — he foresaw Manhattan's northward expansion. The cathedral cost $2 million, financed almost entirely by small donations from Irish immigrant workers.\n\nSt Patrick's Cathedral has hosted the funerals of every New York Cardinal, Robert F. Kennedy's 1968 funeral, Babe Ruth's funeral (1948), and the funerals of multiple NYPD and FDNY officers — becoming the ceremonial center of New York's Catholic institutional life. The cathedral's Lady Chapel (east end), choir and liturgical music program, and annual St Patrick's Day connections make it the most symbolically loaded Catholic building in America. The 2015 renovation ($175 million) restored it to its Victorian polychrome marble interior.",
        "causes": ["1858 commission by Archbishop Hughes as Irish immigrant community assertion amid 'No Irish Need Apply' era", "Fifth Avenue site chosen by Hughes anticipating Manhattan's northward expansion", "$2 million construction cost financed by Irish immigrant small donations", "1878 completion establishing Gothic Revival architecture as symbol of American Catholic institutional power"],
        "effects": ["Physical symbol of Irish Catholic immigrant community assertion against discrimination", "5.5 million annual visitors making it most visited Catholic cathedral in United States", "RFK funeral, Babe Ruth funeral, and NYPD/FDNY ceremonial center establishing civic importance", "Gothic Revival architecture on Fifth Avenue facing Rockefeller Center creating definitive New York skyline element"],
        "relationships": [{"entity": "John Hughes", "relationship": "COMMISSIONED_BY", "note": "Archbishop Hughes commissioned cathedral in 1858 as Irish immigrant community assertion"}, {"entity": "James Renwick Jr.", "relationship": "DESIGNED_BY", "note": "Renwick's Gothic Revival design made cathedral America's largest decorated Gothic Catholic church"}, {"entity": "Robert F. Kennedy", "relationship": "FUNERAL_SITE", "note": "RFK's 1968 funeral at St Patrick's was most politically significant American cathedral service of 20th century"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "St Patrick's Cathedral's construction by Irish immigrants facing systematic discrimination — and its transformation into the ceremonial center of American Catholic life hosting Kennedy funerals, presidential masses, and civic ceremonies — is the most complete architectural embodiment of immigrant community assertion in American history.", "significanceCategory": "world-changing"},
    }),
    ("st-stephens-basilica", {
        "summary": "St Stephen's Basilica (Szent István-bazilika) in Budapest, Hungary, consecrated in 1905 after 54 years of construction (a dome collapse delayed completion by 20 years), is Hungary's largest church and co-equal national cathedral — housing the mummified right hand (the Holy Right, Szentjobb) of Hungary's founding king Stephen I, which has been carried in annual processions since 1083 CE, making it the oldest continuously venerated relic in Central Europe. The basilica's construction coincided with Budapest's unification (1873) and the Austro-Hungarian Compromise (1867), making it a monument to Hungarian national identity.\n\nConstruction began in 1851 under architect József Hild, who continued the neoclassical design until the dome collapsed in 1868, requiring complete reconstruction. Architect Miklós Ybl rebuilt the basilica in neo-Renaissance style, with his death delaying completion further. The final architect József Kauser completed the building in 1905. Emperor Franz Joseph I attended the consecration, symbolically linking Hungarian Catholic identity with Austro-Hungarian political union.\n\nThe Holy Right — St Stephen's mummified hand, kept in a Byzantine-style reliquary — has been Hungary's most sacred relic since Stephen's canonization in 1083 CE. The August 20 procession on St Stephen's Day (Hungary's national holiday commemorating the founding) carries the relic through Budapest in an elaborate ceremony watched by hundreds of thousands. The basilica's dome (96 meters, matching the Hungarian Parliament Building across the Danube at exactly 96 meters — commemorating the Magyar conquest of 896 CE) creates a deliberate visual symmetry expressing state-church equality in Hungarian national life.",
        "causes": ["1851 construction beginning as statement of Hungarian national identity after 1848 revolution", "1868 dome collapse requiring complete reconstruction adding 20 years of delay", "1905 consecration coinciding with Austro-Hungarian period of Budapest's architectural golden age", "Holy Right relic of Stephen I giving basilica 1,000-year devotional continuity"],
        "effects": ["Hungary's largest church and co-equal national cathedral with Parliament Building", "Holy Right relic procession on August 20 creating oldest continuous Central European relic ceremony", "96-meter dome matching Parliament Building creating state-church visual equality in Budapest skyline", "Annual St Stephen's Day ceremony making basilica center of Hungarian national identity celebration"],
        "relationships": [{"entity": "Stephen I of Hungary", "relationship": "HOUSES_RELIC_OF", "note": "Basilica houses Stephen's mummified right hand — Hungary's most sacred relic since 1083 CE canonization"}, {"entity": "Miklós Ybl", "relationship": "REBUILT_BY", "note": "Ybl rebuilt basilica in neo-Renaissance style after 1868 dome collapse"}, {"entity": "Franz Joseph I", "relationship": "CONSECRATION_ATTENDED_BY", "note": "Emperor attended 1905 consecration symbolically linking Hungarian Catholicism with Austro-Hungarian identity"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "St Stephen's Basilica's Holy Right relic — venerated continuously since 1083 CE — and the 96-meter dome deliberately matching the Hungarian Parliament Building create the most complete architectural expression of state-church symbiosis in Central European national identity.", "significanceCategory": "continental"},
    }),
    ("basilica-of-bom-jesus", {
        "summary": "The Basilica of Bom Jesus ('Good Jesus') in Old Goa, India, completed in 1605, houses the incorrupt body of St Francis Xavier — one of the founders of the Jesuit order and Asia's most successful Catholic missionary — and is the most visited Christian pilgrimage site in South Asia, receiving 1 million pilgrims during the periodic Exposition of Xavier's body (held every 10-12 years). The basilica is the earliest example of Baroque architecture in India and a UNESCO World Heritage Site, representing the physical legacy of Portuguese colonialism and Jesuit missionary activity across Asia.\n\nFrancisco de Xavier (1506-1552), co-founder of the Society of Jesus with Ignatius Loyola, spent his apostolic career (1541-1552) traveling from Goa to India, Sri Lanka, Malacca, the Moluccas, Japan, and China — baptizing an estimated 30,000-700,000 people (numbers vary wildly) in 11 years. He died at Shangchuan Island near China, and his body was brought to Goa in 1554. The body's reported incorruption — preserved without embalming since 1552 — became the basis for Xavier's beatification and the greatest Christian relic in Asia.\n\nThe Exposition of Xavier's body, which began in 1782 and occurs every 10-12 years, draws 1 million pilgrims in 45 days. During the 2014 Exposition, 2 million people attended. In the 17th-18th centuries, Portuguese colonial governors carried the body in processions for swearing oaths of office. The basilica's Italian Baroque architecture — the most elaborate church in Portuguese India — represents the Jesuits' use of artistic magnificence as missionary tool: beauty as argument for the Catholic faith.",
        "causes": ["Francis Xavier's death 1552 on Shangchuan Island and transfer of body to Goa in 1554", "Reported incorruption of Xavier's body providing relic basis for beatification and pilgrimage", "1605 completion of baroque basilica as showcase of Jesuit architectural magnificence", "Periodic Exposition since 1782 creating pilgrimage tradition drawing millions"],
        "effects": ["Most visited Christian pilgrimage site in South Asia with 1-2 million per Exposition", "First Baroque architecture in India establishing European aesthetic in Indian religious building", "Xavier's body as foundation of Goa's religious tourism economy and UNESCO heritage status", "Jesuit missionary legacy in Asia preserved through pilgrimage creating Catholic continuity"],
        "relationships": [{"entity": "Francis Xavier", "relationship": "HOUSES_BODY_OF", "note": "Basilica houses Xavier's reportedly incorrupt body since 1554; periodic Expositions draw millions"}, {"entity": "Society of Jesus", "relationship": "BUILT_BY", "note": "Jesuit order built basilica as showcase of Baroque architectural magnificence and missionary power"}, {"entity": "Portuguese Empire", "relationship": "COLONIAL_CONTEXT", "note": "Goa as Portuguese colonial capital gave basilica role in colonial governance and oath-taking ceremonies"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Basilica of Bom Jesus — housing Francis Xavier's reportedly incorrupt body and drawing millions of pilgrims — is the most significant monument of Catholic missionary activity in Asia, demonstrating the Jesuit use of architectural magnificence and saintly relics as instruments of religious conversion.", "significanceCategory": "continental"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 88 — Class 341 Cathedrals III")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
