#!/usr/bin/env python3
"""Batch 135 — Class 342 Mosques VI: Indonesian & Malaysian Mosques (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/342-Class-342"
FILE_PREFIX = "342"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("jami-mosque-of-pontianak", {
        "summary": "The Jami Mosque of Pontianak (Indonesian: Masjid Jami' Sultan Syarif Abdurrahman) in Pontianak, West Kalimantan, Indonesia — built in 1771 as the city mosque of the newly founded Sultanate of Pontianak — is one of the oldest extant mosques in Kalimantan (Indonesian Borneo) and a monument to the founding of Pontianak by Arab-Malay Sultan Syarif Abdurrahman al-Qadri in 1771, making it among the earliest documented Islamic institutional foundations in Borneo's interior regions.\n\nPontianak's founding is historically distinctive: the city sits on the equator (making it one of the few cities in the world directly on the equatorial line) and was founded at the confluence of the Kapuas and Landak rivers specifically as a new sultanate capital by Syarif Abdurrahman, who was of Arab (Hadhrami) descent — reflecting the pattern of Arab and Hadhrami merchants and clerics who established Islamic sultanates across maritime Southeast Asia from the 15th-18th centuries. This Arab-Malay expansion of Islam across maritime Southeast Asia was one of the most successful religious expansions in world history.\n\nThe Jami Mosque's traditional Malay Islamic architecture — featuring a multi-tiered wooden roof rather than a dome (the characteristic pre-colonial Southeast Asian mosque style before Middle Eastern influences modernized mosque design) — represents the distinctive regional Islamic architectural tradition of maritime Southeast Asia. The mosque has been renovated multiple times but retains its traditional character and continues to serve as Pontianak's central congregational mosque.",
        "causes": ["Sultan Syarif Abdurrahman's 1771 founding of Pontianak as an Arab-Malay Islamic sultanate requiring a central mosque", "Arab-Hadhrami Islamic expansion across maritime Southeast Asia requiring mosque foundations in new sultanate capitals", "Pontianak's strategic river confluence location providing the geographical context for sultanate founding", "Borneo's conversion to Islam through Arab and Malay traders requiring mosque institutions to anchor the new Muslim communities"],
        "effects": ["1771 mosque establishing Pontianak as an Islamic sultanate capital and anchoring Muslim community identity", "Traditional Malay Islamic architectural style preserved in one of Borneo's oldest surviving mosque buildings", "Mosque serving as Pontianak's central congregational institution for 250+ years of continuous use", "Historical evidence of Arab-Hadhrami Islamic expansion's reach into Borneo's interior documented through the mosque foundation"],
        "relationships": [{"entity": "Sultan Syarif Abdurrahman", "relationship": "FOUNDING_MOSQUE_BUILT_BY_PONTIANAK'S_ARAB-MALAY_FOUNDER", "note": "The mosque was built in 1771 by Sultan Syarif Abdurrahman when he founded Pontianak as an Islamic sultanate capital"}, {"entity": "Maritime Southeast Asian Islam", "relationship": "ARCHITECTURAL_MONUMENT_TO_ARAB-MALAY_ISLAMIC_EXPANSION_OF", "note": "The mosque represents the Arab-Malay Islamic expansion that established sultanates across maritime Southeast Asia"}, {"entity": "Pontianak", "relationship": "FOUNDING_MOSQUE_AND_SPIRITUAL_ANCHOR_OF", "note": "The Jami Mosque was built at Pontianak's founding and has been the city's central mosque for 250+ years"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Jami Mosque of Pontianak — built in 1771 as a monument to the Arab-Malay Islamic expansion that founded Pontianak as a sultanate capital, one of Borneo's oldest surviving mosques — is historically significant as evidence of the remarkable Islamic expansion across maritime Southeast Asia.", "significanceCategory": "world-changing"},
    }),
    ("khanegah-mosque-quba", {
        "summary": "Khanegah Mosque Quba (Persian: مسجد خانقاه قبا) is one of the mosque complexes in the Quba area of Medina, Saudi Arabia — a locality of extraordinary Islamic historical significance as the site of the Masjid Quba (Quba Mosque), the first mosque ever built in Islamic history (622 CE), erected by the Prophet Muhammad upon his arrival from Mecca at the beginning of the Hijra (migration) that marks the start of the Islamic calendar.\n\nQuba's historical significance is immense: it was the location of the Prophet Muhammad's first stop after leaving Mecca during the Hijra (622 CE), and the Quran (9:108) specifically praises the Quba mosque as one 'founded from the first day on piety.' The Prophet reportedly said that praying two rak'ahs (units of prayer) at Quba is equivalent to the reward of one Umrah (minor pilgrimage). The area around Quba thus developed as one of the most religiously significant zones in Medina, with multiple mosque buildings and religious complexes.\n\nA khanegah (خانقاه, also written khanqah or khaneqah) is a Sufi lodge — a building complex used by Sufi orders (tariqas) for communal living, spiritual practice, and teaching. The combination of khanegah (Sufi lodge) and mosque in the sacred Quba area reflects the historical presence of Sufi orders in Medina and their establishment of spiritual centers in the sacred geography of early Islam.",
        "causes": ["Prophet Muhammad's Hijra arrival at Quba (622 CE) making the area Islam's most historically significant religious zone", "Sufi orders establishing khanegah-mosque complexes in Medina's sacred areas for spiritual practice", "Quba Mosque's Quranic commendation making the area particularly significant for Islamic devotion", "Medina's Islamic heritage development requiring multiple mosque facilities to serve pilgrims and residents"],
        "effects": ["Khanegah-mosque complex providing Sufi spiritual practice space in Islam's most sacred residential city", "Quba area's development as a multi-mosque sacred zone reflecting Islamic historical tradition", "Sufi orders' presence near the Prophet's mosque and Quba documented through khanegah foundations", "Medina's role as center of global Islamic devotion maintained through preservation of historic mosque complexes"],
        "relationships": [{"entity": "Masjid Quba", "relationship": "COMPLEX_IN_AREA_OF_ISLAM'S_FIRST_EVER_MOSQUE", "note": "Khanegah Mosque Quba is in the Quba area where the Prophet built Islam's first mosque (622 CE) upon his Hijra arrival"}, {"entity": "Sufism", "relationship": "KHANEGAH_REPRESENTING_SUFI_ORDER_PRESENCE_IN_MEDINA'S_SACRED_ZONE", "note": "The khanegah element represents Sufi lodge tradition establishing spiritual practice centers in sacred Medina"}, {"entity": "Prophet Muhammad", "relationship": "MOSQUE_IN_AREA_CONSECRATED_BY_FIRST_ARRIVAL_OF", "note": "The Quba area was consecrated by the Prophet's arrival during the Hijra, making all mosques there historically significant"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Khanegah Mosque Quba — a Sufi lodge-mosque complex in the sacred Quba area where the Prophet Muhammad built Islam's first mosque upon his 622 CE arrival — is historically significant as part of the most sacred zone in Medina, connected to the founding moment of the Islamic community.", "significanceCategory": "world-changing"},
    }),
    ("masjid-al-abdul-razak", {
        "summary": "Masjid Al-Abdul Razak is a mosque in Singapore, one of approximately 70 mosques serving Singapore's Muslim community (approximately 15% of the population, predominantly Malay-Muslim). The mosque reflects Singapore's distinctive position as a prosperous multi-religious city-state in which Islam's institutional presence is carefully managed through the Majlis Ugama Islam Singapura (MUIS, Islamic Religious Council of Singapore), which oversees mosques, zakat (Islamic tax), halal certification, and Islamic education.\n\nSingapore's approach to mosque governance is distinctive: MUIS administers a mosque-building fund (MBMF, Mosque Building and Mendaki Fund) through monthly salary deductions from Muslim workers, systematically funding mosque construction and management. This institutional approach to Islamic community organization — combining state oversight with community funding — has made Singapore's mosque system one of the most efficiently managed in the world.\n\nSingapore's Malay-Muslim community has historically faced particular challenges: as an ethnic and religious minority in a majority-Chinese, secular state, Malay-Singaporeans have had to navigate between Malay cultural identity, Islamic religious identity, and Singaporean civic integration. Singaporean mosques, including Masjid Al-Abdul Razak, function as community anchors for this navigation — providing Islamic education, social services, and cultural programming that supports Malay-Muslim identity within Singapore's multicultural framework.",
        "causes": ["Singapore's Malay-Muslim community requiring mosque institutions for religious practice and cultural maintenance", "MUIS mosque-building fund providing systematic financing for Singapore mosque construction", "Malay-Muslim minority community requiring neighborhood mosque as community identity anchor", "Singapore's multicultural framework requiring official mosque management through MUIS oversight"],
        "effects": ["Mosque serving Singapore's Malay-Muslim community as religious and cultural community center", "MUIS-managed mosque contributing to Singapore's systematic Islamic institutional governance", "Malay-Muslim identity in multicultural Singapore maintained through mosque-based religious and cultural programming", "Singapore's Muslim minority integration into secular state supported through efficient mosque management"],
        "relationships": [{"entity": "Singapore", "relationship": "MOSQUE_IN_OFFICIALLY_MANAGED_ISLAMIC_INSTITUTIONAL_SYSTEM_OF", "note": "The mosque is part of Singapore's MUIS-administered system of approximately 70 mosques serving the Malay-Muslim community"}, {"entity": "Malay-Muslim Community", "relationship": "COMMUNITY_ANCHOR_MOSQUE_FOR_SINGAPORE'S", "note": "The mosque serves Singapore's Malay-Muslim minority community maintaining Islamic identity in a majority-Chinese secular state"}, {"entity": "MUIS", "relationship": "MOSQUE_ADMINISTERED_UNDER_SINGAPORE'S_ISLAMIC_RELIGIOUS_COUNCIL", "note": "MUIS oversees Singapore's mosques including this one, through a systematic funding and management approach"}],
        "historicalSignificance": {"significanceScore": 3, "significanceNarrative": "Masjid Al-Abdul Razak Singapore — part of the world's most efficiently managed mosque system, serving Singapore's Malay-Muslim community within the multicultural city-state's carefully balanced religious institutional framework — is locally significant as a community institution of Singapore's Islamic minority.", "significanceCategory": "local"},
    }),
    ("masjid-al-abrar", {
        "summary": "Masjid Al-Abrar (Arabic: مسجد الأبرار, Mosque of the Righteous) is a historic mosque in Singapore's Telok Ayer (Chinatown) district — one of Singapore's oldest mosques, built in 1827 by the Bugis community from Sulawesi (Indonesia) who were among the first Muslim maritime traders to settle in Singapore after Stamford Raffles founded the British trading post in 1819. The mosque, listed as a national monument, is nicknamed 'Kuchu Palli' (Hunchback Mosque) for its unusual architectural profile.\n\nSingapore's early Islamic history is inseparable from the Bugis maritime traders — the most active seafaring people of maritime Southeast Asia, whose trading networks extended from Sulawesi across the Indonesian archipelago to the Malay Peninsula and beyond. When Raffles established Singapore in 1819, Bugis traders quickly settled, establishing one of the first Muslim communities and building the Al-Abrar mosque in 1827. The mosque predates almost all other Singapore religious buildings and is a monument to Singapore's earliest multicultural foundation.\n\nThe Al-Abrar mosque's survival in the heart of what became Singapore's Chinatown reflects the multicultural layering that has characterized Singapore's urban geography: a Bugis Muslim mosque in a predominantly Chinese commercial district, both co-existing in a British colonial port city, now preserved as a national monument in a secular independent state. This physical monument to multicultural coexistence is precisely the kind of heritage that Singapore celebrates as foundational to its national identity.",
        "causes": ["Bugis maritime traders' 1819-1827 settlement in Singapore requiring a mosque for their community", "Bugis community's deep Islamic identity requiring early mosque establishment in Singapore's first decade", "British East India Company's free port status attracting Bugis and other Muslim maritime traders", "Singapore's 1827 Bugis Muslim community size justifying permanent mosque construction"],
        "effects": ["1827 mosque one of Singapore's oldest buildings and a monument to the Bugis maritime trading community's early presence", "National monument status preserving Singapore's earliest Muslim heritage in the midst of Chinatown", "Multicultural Singapore identity symbolized by Bugis Muslim mosque in the Chinese commercial district", "Historical evidence of Bugis maritime trading network's extension to Singapore in the British colonial period"],
        "relationships": [{"entity": "Bugis Maritime Traders", "relationship": "BUILT_BY_MARITIME_COMMUNITY_AS_THEIR_SINGAPORE_MOSQUE", "note": "The mosque was built in 1827 by Bugis traders from Sulawesi, among Singapore's first Muslim settlers"}, {"entity": "Singapore", "relationship": "NATIONAL_MONUMENT_AMONG_OLDEST_HISTORIC_BUILDINGS_OF", "note": "Masjid Al-Abrar is a Singapore national monument and one of the city's oldest surviving buildings (1827)"}, {"entity": "Maritime Southeast Asian Islam", "relationship": "MONUMENT_TO_BUGIS_ISLAMIC_PRESENCE_IN", "note": "The mosque represents the Bugis maritime community's role in spreading Islam across maritime Southeast Asia"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Masjid Al-Abrar Singapore — built in 1827 by Bugis maritime traders, one of Singapore's oldest buildings and national monuments, a monument to the Bugis Islamic maritime community that was among Singapore's earliest settlers — is historically significant as evidence of maritime Southeast Asian Islam's commercial and cultural expansion.", "significanceCategory": "world-changing"},
    }),
    ("masjid-al-amin", {
        "summary": "Masjid Al-Amin (Arabic: مسجد الأمين, Mosque of the Trustworthy — a title of the Prophet Muhammad) is a significant mosque in Singapore serving the Bedok North area of the island's eastern region, one of the larger mosques in Singapore's MUIS-administered network of approximately 70 mosques. The mosque serves the Malay-Muslim community of Bedok, one of Singapore's most densely populated residential areas and home to a significant Muslim population.\n\nThe name 'Al-Amin' (the Trustworthy) was a honorific given to the Prophet Muhammad before he received his prophetic mission — acknowledging his reputation for integrity and reliability among his Meccan community before 610 CE. This pre-prophetic title reflects a tradition of naming mosques after attributes or titles that evoke the Prophet's character and moral qualities.\n\nBedok's demographic composition — with a significant Malay-Muslim community in a predominantly HDB (Housing Development Board) public housing estate — reflects Singapore's pattern of ethnic integration through public housing: Singapore's HDB policy deliberately mixes ethnic groups within housing estates, but Malay-Muslim families have naturally clustered somewhat more in certain areas. Masjid Al-Amin serves as the community's religious and social anchor in Bedok's dense residential environment.",
        "causes": ["Bedok North's significant Malay-Muslim population requiring neighborhood mosque for convenient daily prayer", "Singapore's MUIS mosque-building program funding and establishing mosques in densely populated residential areas", "HDB public housing estate density creating concentrated Muslim community requiring mosque facility", "Prophet Muhammad's 'Al-Amin' (Trustworthy) title providing meaningful mosque name reflecting prophetic heritage"],
        "effects": ["Mosque serving as Bedok's primary Malay-Muslim community center for religious and social activities", "MUIS-funded mosque representing Singapore's systematic religious infrastructure investment", "Daily prayer facilitation for Muslim workers and residents in one of Singapore's most densely populated areas", "Islamic education programs serving Malay-Muslim families in Bedok's residential community"],
        "relationships": [{"entity": "Bedok", "relationship": "MOSQUE_SERVING_MALAY-MUSLIM_COMMUNITY_OF_SINGAPORE'S_RESIDENTIAL_AREA", "note": "Masjid Al-Amin serves Bedok, one of Singapore's most densely populated residential areas with a significant Muslim community"}, {"entity": "Singapore Muslim Community", "relationship": "NEIGHBORHOOD_MOSQUE_IN_MUIS-ADMINISTERED_NETWORK_OF", "note": "The mosque is part of the MUIS-administered network of approximately 70 mosques serving Singapore's Malay-Muslim minority"}, {"entity": "Prophet Muhammad", "relationship": "NAMED_FOR_AL-AMIN_TITLE_OF", "note": "The mosque is named for the Prophet Muhammad's honorific 'Al-Amin' (Trustworthy) given before his prophetic mission"}],
        "historicalSignificance": {"significanceScore": 2, "significanceNarrative": "Masjid Al-Amin Bedok — a neighborhood mosque in Singapore's systematic MUIS-administered Islamic institutional framework — is locally significant as a community religious center for Singapore's Malay-Muslim minority.", "significanceCategory": "local"},
    }),
    ("masjid-al-ansar", {
        "summary": "Masjid Al-Ansar (Arabic: مسجد الأنصار, Mosque of the Helpers/Supporters) in Singapore's Bedok area is one of Singapore's significant mosques, named for the Ansar — the Medinese Muslims who welcomed and supported the Prophet Muhammad and the Meccan Muslim migrants (Muhajirin) when they arrived in Medina during the Hijra of 622 CE. The Ansar's welcoming of the Muhajirin is one of the most celebrated acts of solidarity in Islamic history, representing the ideal of Islamic brotherhood.\n\nThe name 'Al-Ansar' (the Helpers/Supporters) carries deep Islamic historical resonance: the Ansar were the Medinese tribes (primarily the Aws and Khazraj, who converted to Islam) who offered refuge to the persecuted Meccan Muslims and shared their resources with the new arrivals. The Prophet Muhammad is recorded as saying that the Ansar occupy a special place in his heart, and they are frequently honored in Islamic tradition as exemplars of generosity and solidarity.\n\nSingapore's Masjid Al-Ansar serves the Bedok area's Malay-Muslim community alongside Masjid Al-Amin, reflecting the density of Singapore's eastern residential areas and the mosque needs of the Muslim population. The mosque's name — evoking the ideal of welcoming and supporting newcomers — may hold particular significance in Singapore's multicultural context, where the Malay-Muslim community as a minority has had to navigate between hosting roles and minority status.",
        "causes": ["Bedok area's significant Malay-Muslim population requiring additional mosque capacity beyond Masjid Al-Amin", "MUIS mosque-building program funding mosques in high-density residential areas with substantial Muslim populations", "Ansar's historical significance as exemplars of Islamic solidarity providing meaningful mosque name", "Singapore's eastern residential development requiring additional mosque infrastructure"],
        "effects": ["Mosque serving Bedok's Malay-Muslim community alongside other area mosques in the MUIS network", "Ansar name invoking the ideal of Islamic solidarity and generosity in the mosque's community identity", "Muslim community religious infrastructure in Singapore's eastern residential zone maintained through the mosque", "MUIS systematic mosque administration exemplified in Bedok's multiple mosque network"],
        "relationships": [{"entity": "The Ansar", "relationship": "NAMED_TO_HONOR_MEDINESE_HELPERS_OF_PROPHET_MUHAMMAD", "note": "The mosque is named for the Ansar — the Medinese Muslims who welcomed the Prophet and Meccan migrants during the 622 CE Hijra"}, {"entity": "Singapore Muslim Community", "relationship": "BEDOK_AREA_MOSQUE_OF", "note": "Masjid Al-Ansar serves Singapore's Bedok area Malay-Muslim community as part of the MUIS network"}, {"entity": "Islamic Solidarity", "relationship": "MOSQUE_NAMED_FOR_IDEAL_OF_COMMUNITY_SUPPORT_IN", "note": "The Ansar name evokes the Islamic ideal of community solidarity and support for fellow Muslims"}],
        "historicalSignificance": {"significanceScore": 2, "significanceNarrative": "Masjid Al-Ansar Singapore — a neighborhood mosque named for the Medinese Muslims who exemplified Islamic solidarity, serving Bedok's Malay-Muslim community — is locally significant as a community institution in Singapore's efficiently managed mosque network.", "significanceCategory": "local"},
    }),
    ("masjid-al-dahab", {
        "summary": "Masjid Al-Dahab (Arabic: مسجد الذهب, Mosque of Gold) — an informal name for the Al-Azhar Mosque annex or a specific prayer hall in Cairo, Egypt, or alternatively a mosque in Morocco known as the 'Golden Mosque' — represents the tradition of naming mosques with evocative Arabic phrases that capture architectural features, spiritual qualities, or historical associations. The 'Dahab' (gold) name in mosque context typically refers to gilded decoration, golden dome or minarets, or a location with historical associations to golden age prosperity.\n\nMosques named with 'Dahab' or golden associations reflect the Islamic architectural tradition of using precious metal ornamentation to express the mosque's status as the house of God deserving the most beautiful physical expression. The Dome of the Rock in Jerusalem (completed 691 CE), with its golden dome covered in gold-anodized aluminum (original gilded tiles), is the most famous example of 'golden' Islamic architecture conveying divine presence through precious material.\n\nIn Egypt, Cairo has historically been associated with gold through the medieval Islamic trade economy — Cairo's markets (khans) were the commercial hub of the medieval Islamic world, and its mosques reflected the wealth generated by trade. Any mosque bearing the 'Dahab' name in Cairo participates in this tradition of associating the mosque with the highest material and spiritual values of Islamic civilization.",
        "causes": ["Islamic architectural tradition of using gold ornamentation to express mosque's sacred status", "Cairo's historical prosperity through medieval Islamic trade economy creating gold-associated place names", "Tradition of naming mosques with evocative Arabic phrases capturing spiritual or material qualities", "Golden mosque architecture reflecting the Islamic principle that sacred spaces deserve the most beautiful material expressions"],
        "effects": ["Golden mosque tradition contributing to Islamic architectural heritage linking material beauty to spiritual aspiration", "Cairo's mosque landscape reflecting the medieval Islamic world's most prosperous commercial city", "Islamic architectural terminology preserving the tradition of precious material in sacred architecture", "Mosque naming traditions reflecting the linguistic and spiritual richness of Islamic architectural heritage"],
        "relationships": [{"entity": "Islamic Architecture", "relationship": "MOSQUE_NAMED_FOR_GOLDEN_ORNAMENTATION_TRADITION_OF", "note": "The 'Dahab' (gold) name reflects the Islamic architectural tradition of using precious materials to express a mosque's sacred status"}, {"entity": "Cairo", "relationship": "MOSQUE_IN_MEDIEVAL_ISLAMIC_WORLD'S_MOST_PROSPEROUS_CITY", "note": "Cairo's historical prosperity through Islamic trade created the context for gold-associated mosque architecture"}, {"entity": "Dome of the Rock", "relationship": "GOLDEN_DOME_TRADITION_SHARED_WITH_ICONIC", "note": "The golden mosque tradition is most famously exemplified by the Dome of the Rock, Islam's most recognizable golden architectural monument"}],
        "historicalSignificance": {"significanceScore": 3, "significanceNarrative": "Masjid Al-Dahab — representing the Islamic architectural tradition of associating mosques with gold and precious beauty as expressions of divine presence — is locally significant as a monument to the Islamic sacred architecture's use of material beauty for spiritual aspiration.", "significanceCategory": "local"},
    }),
    ("masjid-al-falah", {
        "summary": "Masjid Al-Falah (Arabic: مسجد الفلاح, Mosque of Success/Salvation) is a significant mosque in Singapore's Orchard Road area — one of Singapore's largest and most prominently located mosques, situated near Singapore's premier shopping district and serving both Singapore's Muslim community and Muslim visitors and tourists who frequent the Orchard Road area. The mosque is among Singapore's most architecturally distinctive, featuring traditional Malay Islamic architectural elements in a modern urban commercial context.\n\nThe Orchard Road location of Masjid Al-Falah is historically significant: it reflects Singapore's colonial-era urban planning in which mosques were distributed across the city, and some mosques found themselves in areas that subsequently developed into commercial zones. The mosque's presence on Orchard Road — surrounded by luxury malls, hotels, and international stores — is a striking visual reminder of Singapore's multi-religious heritage in its most commercially prominent street.\n\nMasjid Al-Falah's position near Orchard Road also makes it one of Singapore's most visited mosques by international Muslim visitors, who use it for Friday prayers and daily prayers while visiting Singapore for tourism or business. The mosque thus plays a role in Singapore's Islamic hospitality — serving the 15% Muslim minority population alongside international Muslim visitors in a city that takes pride in its multicultural welcome and efficiency of religious infrastructure.",
        "causes": ["Historical mosque location near what became Singapore's premier shopping district", "Singapore's Muslim community requiring mosque in the city's central commercial area for prayer during shopping or work", "Colonial-era Singapore urban planning distributing mosques across the city before Orchard Road's commercialization", "MUIS mosque network requiring representation in Singapore's most prominent commercial zone"],
        "effects": ["Orchard Road mosque serving both local Muslim community and international Muslim visitors to Singapore's premier shopping area", "Singapore's multicultural visual identity reinforced by mosque presence amid luxury commercial development", "International Muslim visitors served through strategically located mosque near Singapore's tourist and business center", "Traditional Malay Islamic architecture preserved in Singapore's most modern commercial district"],
        "relationships": [{"entity": "Orchard Road", "relationship": "MOSQUE_PROMINENTLY_LOCATED_IN_SINGAPORE'S_PREMIER_COMMERCIAL_DISTRICT", "note": "Masjid Al-Falah's Orchard Road location makes it one of Singapore's most prominently situated mosques"}, {"entity": "Singapore Muslim Community", "relationship": "CENTRAL-CITY_MOSQUE_SERVING_LOCAL_AND_TOURIST", "note": "The mosque serves both local Muslims and the large number of international Muslim tourists visiting Orchard Road"}, {"entity": "Singapore Multicultural Identity", "relationship": "MOSQUE_SYMBOLIZING_RELIGIOUS_DIVERSITY_IN_COMMERCIAL_HEART_OF", "note": "The mosque's Orchard Road presence visually symbolizes Singapore's commitment to multicultural religious accommodation"}],
        "historicalSignificance": {"significanceScore": 4, "significanceNarrative": "Masjid Al-Falah Singapore — prominently located near Orchard Road, serving local and international Muslims in Singapore's commercial heart — is regionally significant as a symbol of Singapore's multicultural accommodation and the presence of Islamic heritage in its most modern urban environment.", "significanceCategory": "local"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 135 — Class 342 Mosques VI: Indonesian & Malaysian Mosques")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
