#!/usr/bin/env python3
"""Batch 115 — Class 311 Parliaments III: Regional & Historical Assemblies (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/311-Class-311"
FILE_PREFIX = "311"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("assembly-of-corsica", {
        "summary": "The Assembly of Corsica (Assemblée de Corse), established in its current form in 2018 as a merger of the Corsican Regional Council and the General Councils of Haute-Corse and Corse-du-Sud, is the single territorial assembly governing the French island of Corsica — an autonomous collectivity within France that has experienced decades of nationalist movement activity, occasional political violence, and ongoing debate about independence, autonomy, and cultural preservation of the Corsican language and identity.\n\nCorsica's distinctive political status reflects its complex history: a Genoese possession for centuries, transferred to France in 1768 (one year before Napoleon Bonaparte was born there), Corsica has always maintained a strong separate identity from the French mainland. The FLNC (National Liberation Front of Corsica) conducted bombings and attacks from 1976 until its 2014 ceasefire, representing the armed wing of Corsican nationalism. French governments have been cautious about expanding Corsican autonomy, fearing precedent for Brittany, Alsace, and other regions.\n\nThe 2018 elections gave Corsican nationalist parties (Gilles Simeoni's Femu a Corsica coalition) an absolute majority in the new Assembly — the first time nationalists held outright power. The Assembly has advocated for co-official status for the Corsican language, tax autonomy, and a special constitutional status for Corsica distinct from mainland French departments. The French government under Emmanuel Macron opened negotiations about Corsican autonomy, making the Assembly's relationship with Paris the defining political question of contemporary Corsica.",
        "causes": ["2018 merger of Corsican Regional Council and two General Councils creating single territorial assembly", "Nationalist electoral dominance enabling Femu a Corsica coalition to hold Assembly majority", "FLNC ceasefire (2014) shifting Corsican nationalism from violent to democratic institutional strategy", "Macron government opening autonomy negotiations creating new context for Assembly's French-relations agenda"],
        "effects": ["First nationalist Assembly majority advocating Corsican language co-official status and tax autonomy", "Assembly-Paris negotiations on Corsican constitutional status representing most serious autonomy talks in decades", "Corsican nationalist movement demonstrating democratic path after FLNC's decades of political violence", "Assembly model of merged territorial governance providing administrative efficiency for island of 350,000"],
        "relationships": [{"entity": "Corsican Nationalist Movement", "relationship": "INSTITUTIONAL_EXPRESSION_OF", "note": "The Assembly is the democratic institutional vehicle through which Corsican nationalists pursue autonomy goals"}, {"entity": "French Republic", "relationship": "CONSTITUTIONAL_UNIT_WITHIN_AND_NEGOTIATING_WITH", "note": "The Assembly negotiates Corsican autonomy within France's constitutional framework with the central government"}, {"entity": "Corsican Language", "relationship": "ADVOCATES_FOR_CO-OFFICIAL_STATUS_OF", "note": "The nationalist Assembly majority has pushed for Corsican language co-official status with French in Corsica"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Assembly of Corsica — the institutional expression of an island's centuries-long separate identity, achieving nationalist electoral majority in 2018, and conducting the most serious autonomy negotiations with France in modern history — represents a significant test of French unitary republicanism's adaptability to regional distinctiveness.", "significanceCategory": "regional"},
    }),
    ("assembly-of-vizille", {
        "summary": "The Assembly of Vizille, convened on July 21, 1788 at the Château de Vizille near Grenoble — bringing together representatives of the three estates of the Dauphiné province (clergy, nobility, and Third Estate) in defiance of royal prohibition on regional assemblies — is regarded by historians as the 'spark of the French Revolution': the first successful assertion of representative government against royal absolutism, which preceded and directly inspired the Estates-General convened in 1789 that launched the French Revolution.\n\nThe Assembly was convened in response to Louis XVI's May 1788 edicts suppressing existing parlements (regional courts with quasi-legislative powers) and centralizing judicial-administrative power in new royal courts. The three estates of Dauphiné, led by the lawyer Antoine Barnave (later a Constituent Assembly leader), the nobleman Mounier, and others, met at the home of Claude Périer — a wealthy merchant — to protest the royal edicts. Crucially, the three estates met and voted jointly rather than separately, prefiguring the key revolutionary demand of the Third Estate in 1789.\n\nThe Assembly of Vizille demanded the restoration of the Dauphiné provincial estates, the convocation of the Estates-General (not called since 1614), and the restoration of traditional liberties — all demands that became the opening salvos of the French Revolution. The revolutionary innovation of joint deliberation across the three orders was a direct precursor to the Third Estate's June 1789 decision to constitute itself as the National Assembly. The Vizille meeting thus stands at the very beginning of the constitutional chain that produced the Declaration of the Rights of Man.",
        "causes": ["Louis XVI's May 1788 edicts suppressing regional parlements and centralizing royal power", "Dauphiné estates' joint resistance defying the royal prohibition on regional assembly", "Claude Périer providing Château de Vizille as private meeting space circumventing royal authority", "Three-estate joint deliberation at Vizille prefiguring the key procedural innovation of the 1789 National Assembly"],
        "effects": ["Joint deliberation of three estates establishing revolutionary precedent for the 1789 National Assembly formation", "Dauphiné demands for Estates-General convocation helping pressure Louis XVI to call the 1789 assembly", "Antoine Barnave launched as revolutionary leader through Vizille organization", "Vizille establishing that provincial assemblies could successfully defy royal prohibitions — crucial precedent"],
        "relationships": [{"entity": "French Revolution", "relationship": "DIRECT_PRECURSOR_AND_SPARK_OF", "note": "The 1788 Vizille assembly's joint deliberation and demands directly inspired the 1789 French Revolution's opening constitutional moves"}, {"entity": "Antoine Barnave", "relationship": "LEADER_LAUNCHED_BY", "note": "Barnave rose to prominence through organizing the Vizille assembly and became a key Constituent Assembly figure"}, {"entity": "Estates-General of 1789", "relationship": "DEMANDED_CONVOCATION_OF", "note": "Vizille's demands included calling the Estates-General — not assembled since 1614 — which became the French Revolution's formal opening"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Assembly of Vizille — the 1788 provincial assembly that first successfully defied royal absolutism through joint three-estate deliberation, demanded the Estates-General, and established the procedural precedent for the National Assembly — is the direct institutional spark of the French Revolution.", "significanceCategory": "world-changing"},
    }),
    ("anti-fascist-assembly", {
        "summary": "The Anti-Fascist Council for the National Liberation of Yugoslavia (AVNOJ, Antifašističko Vijeće Narodnog Oslobođenja Jugoslavije), convened first at Bihać in November 1942 and then as the Second Session at Jajce in November 1943 — where it declared itself the supreme legislative and executive body of Yugoslavia — was the wartime parliament through which Josip Broz Tito's Partisans established the legal foundations of socialist Yugoslavia, simultaneously organizing the anti-Nazi resistance and laying the constitutional groundwork for the postwar state.\n\nThe Second Session at Jajce (November 29, 1943) was AVNOJ's defining moment: it declared Yugoslavia a federal state of equal peoples, established Tito as Marshal and chairman of the National Committee (effectively Prime Minister), stripped the royal government-in-exile of legitimacy, and banned King Peter II from returning. These decisions — made in a liberated provincial town while the German-Italian occupation still controlled most of Yugoslavia — constituted a revolutionary act of constitutional self-determination within wartime conditions.\n\nAVNOJ's constitutional framework became the basis of socialist Yugoslavia. The multinational federation (six republics and two autonomous provinces) reflected AVNOJ's founding principle of South Slavic 'brotherhood and unity' among Serbs, Croats, Slovenes, Bosnians, Macedonians, and Montenegrins. The November 29 date (1943 AVNOJ session) became Yugoslavia's national day. The AVNOJ constitutional model — and its tensions around republic-level national identities — directly foreshadowed the ethnic and constitutional conflicts that led to Yugoslavia's violent dissolution in the 1990s.",
        "causes": ["November 1942 first AVNOJ session organizing anti-fascist resistance under Tito's Partisans", "November 1943 second session declaring sovereign authority superseding the government-in-exile", "Tito's Partisan military success providing the military credibility behind AVNOJ's political claims", "Soviet and Allied recognition of AVNOJ legitimacy giving international backing to its constitutional claims"],
        "effects": ["Yugoslavia established as federal socialist republic of six equal nations (1943 declaration)", "Government-in-exile stripped of legitimacy and King Peter II banned — Yugoslav monarchy ended", "Six-republic, two-autonomous-province federal structure creating Yugoslavia's ethnic-federal architecture", "AVNOJ constitutional tensions over republic-level national identities directly foreshadowing 1990s dissolution"],
        "relationships": [{"entity": "Josip Broz Tito", "relationship": "CHAIRMAN_AND_LEADER_OF", "note": "Tito was declared Marshal and National Committee chairman at the 1943 AVNOJ Jajce session"}, {"entity": "Socialist Federal Republic of Yugoslavia", "relationship": "CONSTITUTIONAL_FOUNDING_BODY_OF", "note": "AVNOJ's decisions at Jajce established the constitutional framework for socialist Yugoslavia"}, {"entity": "Yugoslav Wars of the 1990s", "relationship": "CONSTITUTIONAL_FRAMEWORK_THAT_PRESAGED", "note": "AVNOJ's six-republic federal structure and national identity recognition contained the tensions that produced Yugoslavia's dissolution"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "AVNOJ — the wartime parliament that constitutionally founded socialist Yugoslavia in a liberated village while Nazi occupation continued, establishing the six-republic federal framework that both united and ultimately dissolved the South Slavic nations — is one of the most consequential wartime legislative acts in 20th-century European history.", "significanceCategory": "world-changing"},
    }),
    ("assembly-of-french-polynesia", {
        "summary": "The Assembly of French Polynesia (Assemblée de la Polynésie française), the 57-member territorial parliament of French Polynesia — France's largest overseas collectivity comprising 118 islands in the South Pacific (5 archipelagos, total land area 4,167 km², scattered over an area the size of Europe) with approximately 280,000 people — has been the arena for French Polynesia's complex politics, which oscillate between pro-independence and pro-autonomy parties and navigate the legacies of French nuclear testing, colonial administration, and indigenous Mā'ohi cultural identity.\n\nFrench Polynesia acquired its current autonomy status (collectivité d'outre-mer) through the 2004 Organic Statute that significantly expanded self-governance while maintaining French sovereignty. The Territory's political life has been dominated by Oscar Temaru's pro-independence Tavini Huiraatira party and Gaston Flosse's pro-France Tahoeraa Huiraatira party — with frequent changes of government through Assembly votes of no-confidence, making French Polynesia one of the most politically unstable French territories.\n\nFrench Polynesia bears the specific legacy of France's nuclear testing program: 193 atmospheric and underground nuclear tests were conducted at Mururoa and Fangataufa atolls (1966-1996), affecting health and environment in the surrounding Pacific communities. The Assembly has been a persistent advocate for recognition of nuclear testing victims' health compensation rights — a major ongoing political issue — and has voted declarations supporting independence, though formal independence remains a minority position. The Assembly's relationship with Paris balances economic dependence (80%+ of budget from French transfers) against the aspirations of Mā'ohi self-determination.",
        "causes": ["2004 Organic Statute establishing French Polynesia's current broad autonomy framework", "France's 1966-1996 nuclear testing program at Mururoa creating lasting political grievance", "Oscar Temaru's independence movement vs. Flosse's pro-France camp defining political polarization", "Economic dependence on French financial transfers constraining independence aspirations"],
        "effects": ["French Polynesia's political instability through frequent no-confidence votes and government changes", "Assembly advocacy for nuclear testing victims' health compensation as major ongoing political cause", "Mā'ohi cultural rights including Te Reo Māohi language recognition advocated through Assembly", "French Polynesia independence debates contributing to broader Pacific decolonization discourse"],
        "relationships": [{"entity": "Oscar Temaru", "relationship": "INDEPENDENCE_MOVEMENT_LED_IN", "note": "Temaru's Tavini party has been the Assembly's pro-independence force, making him PM multiple times"}, {"entity": "French Nuclear Testing in Pacific", "relationship": "ADVOCACY_AGAINST_LEGACY_OF", "note": "The Assembly has persistently demanded compensation for 193 nuclear tests conducted at Mururoa (1966-1996)"}, {"entity": "France", "relationship": "AUTONOMOUS_COLLECTIVITY_WITHIN", "note": "French Polynesia remains an overseas collectivity with broad autonomy but French sovereignty and financial support"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Assembly of French Polynesia — the democratic institution of a nuclear-tested Pacific territory balancing Mā'ohi self-determination aspirations with French economic dependence, and advocating for justice for nuclear testing victims — is a significant institution in Pacific decolonization and French colonial legacy politics.", "significanceCategory": "regional"},
    }),
    ("central-african-federation-malawi", {
        "summary": "The Central African Federation (CAF), also known as the Federation of Rhodesia and Nyasaland (1953-1963), was the political union imposed by the British Colonial Office on Northern Rhodesia (Zambia), Southern Rhodesia (Zimbabwe), and Nyasaland (Malawi) — a federation that African populations in all three territories overwhelmingly opposed from its inception as representing white settler political domination under British colonial architecture, and whose dissolution after a decade proved that African majority opposition to colonial political structures could succeed.\n\nThe Federation was imposed despite almost universal African opposition, particularly from Nyasaland's Congress movement led by Dr. Hastings Banda (who returned from exile to lead the Nyasaland African Congress in 1958). Britain's Devlin Report (1959) — commissioned after the 1959 State of Emergency crackdown on African nationalist protests — memorably described Nyasaland as 'a police state.' The Monckton Commission (1960) recommended that territories should have the right to secede.\n\nNyasaland under Banda was the first to negotiate independence, with Malawi gaining independence on July 6, 1964. Northern Rhodesia followed as Zambia in October 1964. Southern Rhodesia's white minority government declared Unilateral Declaration of Independence (UDI) in 1965 — the crisis that would take another 15 years to resolve through guerrilla war and Lancaster House Agreement (1979). The CAF's failure and dissolution demonstrated that British colonial administrators could not impose multiracial but white-dominated federal structures against African nationalist will — a crucial precedent for subsequent decolonization.",
        "causes": ["British Colonial Office imposing federation despite African population's near-universal opposition", "White settler minority interests in Southern Rhodesia driving federation structure to preserve political dominance", "Nyasaland African Congress opposition under Hastings Banda mounting irresistible campaign for dissolution", "1959 Devlin Report documenting Nyasaland as 'police state' internationally delegitimizing the federation"],
        "effects": ["Malawi independence (1964) as first successful dissolution of the failed federation", "Zambia independence (1964) completing the federation's peaceful dissolution into independent African states", "Southern Rhodesia UDI (1965) creating 15-year crisis as white minority refused to accept African majority rule", "Federation failure demonstrating that British colonial imposed multiracial structures against African will were unviable"],
        "relationships": [{"entity": "Hastings Banda", "relationship": "PRINCIPAL_OPPONENT_WHOSE_MOVEMENT_DISSOLVED", "note": "Banda led the Nyasaland African Congress in the campaign that successfully demanded the federation's dissolution"}, {"entity": "Malawi", "relationship": "SUCCESSOR_STATE_OF_NYASALAND_COMPONENT", "note": "Independent Malawi (1964) emerged from Nyasaland's exit from the Central African Federation"}, {"entity": "Southern Rhodesia", "relationship": "COMPONENT_WHOSE_CONTINUATION_BECAME_UDI_CRISIS", "note": "Southern Rhodesia's white minority government refused dissolution in favor of independence, declaring UDI in 1965"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Central African Federation — the British colonial-imposed white-dominated union that three African nationalist movements dismantled, whose dissolution led to Malawi, Zambia independence, and the Southern Rhodesia UDI crisis that took 15 more years to resolve — is one of the most significant colonial political structures in African decolonization history.", "significanceCategory": "world-changing"},
    }),
    ("chamber-of-states", {
        "summary": "The Chamber of States (Ständerat), Switzerland's upper chamber — part of the Federal Assembly alongside the National Council — is the council representing Switzerland's 26 cantons and half-cantons, with each full canton sending 2 representatives and each half-canton 1, regardless of population size. The 46-member chamber has co-equal legislative power with the National Council (200 seats based on population) and embodies Switzerland's federal principle that the Confederation is a union of equal sovereign states as well as a democratic state of equal citizens.\n\nThe Chamber of States (modeled partly on the US Senate) represents the cantonal dimension of Swiss federalism — a particularly important institution given that Switzerland's extreme decentralization gives cantons responsibility for education, health, police, and significant taxation. Swiss cantons range from Geneva (population 500,000) to Appenzell Innerrhoden (16,000), all sending equal delegates to the Ständerat.\n\nThe chamber's political dynamics are distinctive: because rural, smaller, and more conservative cantons are overrepresented relative to their population, the Chamber of States tends to lean more right and centrist than the population-based National Council. The Swiss People's Party (SVP/UDC) — which wins the most seats in the National Council — tends to underperform in the Ständerat because its support is concentrated in populous cantons. The two chambers must agree on all legislation; when they disagree, a conference committee resolves differences. The chamber has served since 1848 as one of the world's most enduring federal upper houses.",
        "causes": ["1848 Swiss Federal Constitution establishing the bicameral Federal Assembly with cantonal Chamber of States", "Need for equal cantonal representation alongside population-based representation in Swiss federal structure", "US Senate model providing institutional template for equal cantonal representation", "Swiss federalism requiring institutional expression of cantonal sovereignty alongside national democracy"],
        "effects": ["Cantonal equal representation giving smaller rural cantons equal legislative weight to larger urban cantons", "Chamber of States conservative tilt relative to National Council moderating Swiss federal legislation", "Swiss legislative bicameralism requiring agreement between population-based and cantonal chambers for all laws", "1848-present continuous operation making Ständerat one of the world's most stable federal upper chambers"],
        "relationships": [{"entity": "Swiss Federal Assembly", "relationship": "UPPER_CHAMBER_OF", "note": "The Ständerat and National Council together form the Swiss Federal Assembly with co-equal legislative authority"}, {"entity": "Swiss Cantons", "relationship": "REPRESENTS_EQUALLY_REGARDLESS_OF_SIZE", "note": "Each of 26 cantons sends equal delegates (2 or 1 for half-cantons) regardless of population"}, {"entity": "United States Senate", "relationship": "INSTITUTIONAL_MODEL_FOR", "note": "The Swiss Ständerat was modeled partly on the US Senate's principle of equal state representation"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Switzerland's Chamber of States — the equal-cantonal-representation upper house operating since 1848, moderating Swiss federal legislation through bicameral requirement, and embodying the world's most extreme federalism — is one of the most stable and sophisticated federal legislative chambers in history.", "significanceCategory": "continental"},
    }),
    ("basutoland-congress", {
        "summary": "The Basutoland Congress Party (BCP), founded in 1952 by Ntsu Mokhehle in Basutoland (the British protectorate that became Lesotho in 1966), was the principal nationalist movement that led Lesotho's independence campaign and has remained a significant if divided political force in one of the world's most geographically unusual countries — a landlocked kingdom entirely surrounded by South Africa.\n\nBasutoland's political status was distinctive in the colonial era: the mountain kingdom (historically the refuge to which Moshoeshoe I rallied the Basotho people from Zulu and Boer pressure in the 1820s-1830s) had avoided direct incorporation into South Africa during the apartheid era — unlike neighboring Bechuanaland (Botswana) and Swaziland, Basutoland maintained British protectorate status partly because its mountain geography made it economically marginal and militarily defensible. This geography gave the BCP's independence campaign particular significance: it was simultaneously obtaining independence and refusing incorporation into apartheid South Africa.\n\nLesotho's post-independence history has been turbulent: the BCP won the 1965 pre-independence elections but was denied power; subsequent decades saw military coups, electoral fraud, and political instability. Ntsu Mokhehle finally became Prime Minister in 1993 after the BCP won elections; the party later split, with Mokhehle forming the Lesotho Congress for Democracy. Contemporary Lesotho politics features extreme fragmentation among multiple successor parties of the BCP tradition. Lesotho remains the world's only country entirely enclosed within another country at high altitude (it is the only country entirely above 1,000m), a landlocked mountain nation whose political independence from South Africa remains its defining characteristic.",
        "causes": ["1952 founding by Ntsu Mokhehle as principal independence movement for British Basutoland protectorate", "Moshoeshoe I's 1820s-1830s mountain refuge establishing the Basotho kingdom that became Lesotho", "Basutoland's refusal of South African incorporation during apartheid giving independence movement strategic urgency", "1965 pre-independence elections and subsequent denial of power creating founding political grievances"],
        "effects": ["Lesotho independence (1966) as triumph of BCP's independence campaign avoiding South African incorporation", "Post-independence turbulence including military coups and electoral fraud creating chronic political instability", "1993 Mokhehle premiership as BCP's delayed fulfillment of independence mandate", "BCP splits and successor parties fragmenting Lesotho's politics across multiple competing organizations"],
        "relationships": [{"entity": "Ntsu Mokhehle", "relationship": "FOUNDED_BY_AND_LED_BY", "note": "Mokhehle founded the BCP in 1952 and finally served as Lesotho's Prime Minister from 1993"}, {"entity": "Lesotho", "relationship": "FOUNDING_INDEPENDENCE_MOVEMENT_OF", "note": "The BCP led Basutoland's independence campaign, achieved as Lesotho's independence in 1966"}, {"entity": "South Africa", "relationship": "SURROUNDING_STATE_INDEPENDENCE_PRESERVED_AGAINST_INCORPORATION_BY", "note": "BCP's independence campaign prevented Lesotho's incorporation into apartheid South Africa"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Basutoland Congress Party — founding movement of Lesotho's independence from Britain while maintaining separation from apartheid South Africa, established in the mountain kingdom whose geographic isolation is its political asset — is a significant institution in southern African decolonization and anti-apartheid resistance.", "significanceCategory": "regional"},
    }),
    ("congress-argentina", {
        "summary": "The Argentine National Congress (Congreso de la Nación Argentina), the bicameral legislature comprising the Chamber of Deputies (257 members elected for 4-year terms, half renewed every 2 years) and the Senate (72 senators, 3 per province and Buenos Aires City, 6-year terms), established by the 1853 Constitution of Argentina, is the legislative institution of Latin America's third-largest economy and one of the region's most politically volatile democracies — having experienced 6 complete democratic breakdowns through military coups in the 20th century.\n\nArgentina's Congress has operated under interrupted democratic conditions: military coups in 1930, 1943, 1955, 1962, 1966, and 1976 suspended congressional activity at various intervals, most devastatingly under the 1976-1983 military dictatorship that disappeared approximately 30,000 people. The restoration of democracy in 1983 under Raúl Alfonsín was followed by constitutional reform in 1994 (under President Carlos Menem's Pacto de Olivos) which introduced direct presidential election, PASO primary elections, and a third Senator per province.\n\nArgentina's Congress has been the arena for some of Latin America's most dramatic political crises: the 2001-2002 economic collapse and default (when Congress selected three presidents in two weeks during December 2001 street protests), and the Peronist-vs.-non-Peronist political polarization that has defined Argentine politics since 1946. The Kirchnerismo era (Néstor Kirchner 2003-2007, Cristina Fernández de Kirchner 2007-2015) used congressional majorities to pass major economic and human rights legislation; the opposition Macri and current Milei governments reflect the pendulum of Argentine politics.",
        "causes": ["1853 Constitution establishing Argentina's bicameral congress as central legislative institution", "Military coup cycles (1930-1983) creating repeated congressional interruptions undermining institutional continuity", "1994 constitutional reform (Pacto de Olivos) modernizing congressional structure with direct presidential election", "2001 economic collapse and default creating Congress's most dramatic emergency succession crisis"],
        "effects": ["Congress's 2001-2002 selection of three presidents in two weeks during economic collapse as extreme political crisis", "Kirchnerismo congressional majorities enabling major social, economic, and human rights legislation (2003-2015)", "Argentina's democratic restoration (1983) using Congress to process military dictatorship accountability", "Peronist domination of congressional politics creating Argentina's distinctive left-populist political tradition"],
        "relationships": [{"entity": "Argentine Constitution of 1853", "relationship": "ESTABLISHED_BY", "note": "Argentina's 1853 constitution created the bicameral Congress; the 1994 reform updated its structure"}, {"entity": "Kirchnerismo", "relationship": "LEGISLATIVE_VEHICLE_OF", "note": "Néstor and Cristina Kirchner used congressional majorities to enact landmark social and economic legislation"}, {"entity": "2001 Argentine Economic Crisis", "relationship": "CONSTITUTIONAL_CRISIS_MANAGER_DURING", "note": "Congress selected three presidents in two weeks during December 2001 as Argentina defaulted"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Argentina's National Congress — repeatedly suspended by six military coups, managing the 2001 economic collapse crisis through unprecedented presidential succession, and arena of Latin America's most dynamic Peronist/anti-Peronist political competition — is the central institution in one of Latin America's most turbulent yet enduring democratic traditions.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 115 — Class 311 Parliaments III: Regional & Historical Assemblies")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
