#!/usr/bin/env python3
"""Batch 107 — Class 344 Abbeys III: Medieval European Abbeys (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/344-Class-344"
FILE_PREFIX = "344"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("bec-abbey", {
        "summary": "Bec Abbey (Abbaye Notre-Dame du Bec) in Normandy, France, founded c. 1034 by the knight Herluin who renounced his military career for monastic life, became in the 11th-12th centuries the most intellectually influential monastery in Western Christendom — not because of its wealth or political power, but because of the extraordinary scholars it attracted. Lanfranc of Pavia (prior 1045-1063), the Italian-born teacher who made Bec famous for its school, was followed by Anselm of Aosta (prior 1063-1078) — one of the greatest philosophers of the Middle Ages, whose Proslogion (1077-78) contained the ontological argument for God's existence.\n\nAnselm's impact through Bec was enormous: he became Archbishop of Canterbury (1093-1109) and his philosophical works — the Cur Deus Homo (Why God Became Man), the Monologion, and Proslogion — defined the 'faith seeking understanding' approach that shaped Scholastic theology for centuries. Lanfranc also became Archbishop of Canterbury (1070-1089), reorganizing the English church after the Norman Conquest. Bec thus supplied two of the most consequential Archbishops of Canterbury in English church history through its intellectual tradition.\n\nBec Abbey was suppressed during the French Revolution (1790), its buildings sold and converted to a prison. The community was restored in 1948 and the abbey continues as a Benedictine monastery today. Its medieval library — which once held manuscripts studied by Anselm — was dispersed, but the intellectual tradition it created in the 11th century shaped Western theology and philosophy for the subsequent millennium.",
        "causes": ["c. 1034 founding by knight Herluin's conversion from military to monastic life", "Lanfranc's intellectual school attracting scholars from across Europe to Bec", "Anselm's Proslogion (1077-78) containing the ontological argument making Bec philosophically famous", "Norman Conquest (1066) elevating Bec's Norman monks to English church leadership"],
        "effects": ["Lanfranc as first post-Conquest Archbishop of Canterbury reorganizing the English church", "Anselm's ontological argument as most influential philosophical proof for God's existence in Western philosophy", "Cur Deus Homo and Monologion defining 'faith seeking understanding' — Scholasticism's foundational method", "Bec tradition providing intellectual foundation for Canterbury's primacy in English Christianity"],
        "relationships": [{"entity": "Anselm of Canterbury", "relationship": "GREATEST_SCHOLAR_PRODUCED_BY", "note": "Anselm (prior 1063-1078, Archbishop 1093-1109) wrote the Proslogion and Cur Deus Homo at Bec"}, {"entity": "Lanfranc of Canterbury", "relationship": "INTELLECTUAL_TRADITION_FOUNDED_BY", "note": "Lanfranc's school (1045-1063) made Bec Europe's most intellectually prestigious monastery"}, {"entity": "Norman Conquest", "relationship": "MONKS_ELEVATED_TO_ENGLISH_CHURCH_LEADERSHIP_BY", "note": "1066 Conquest brought Lanfranc and Anselm from Bec to Canterbury as Archbishops"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Bec Abbey — producing Anselm's ontological argument (the most debated proof for God's existence in Western philosophy), supplying two of Canterbury's most consequential archbishops, and establishing Scholasticism's foundational method — was the 11th century's most intellectually influential institution in Western Christendom.", "significanceCategory": "world-changing"},
    }),
    ("fleury-abbey", {
        "summary": "Fleury Abbey (Saint-Benoît-sur-Loire), founded c. 640 CE on the Loire river in the Orléanais region of France and claiming possession of the relics of St. Benedict of Nursia (founder of Western monasticism) since the late 7th century, was the most important Benedictine monastery in France from the 8th to 11th centuries and a major center of Carolingian Renaissance scholarship. The monks' claim to have stolen Benedict's relics from Monte Cassino (c. 672 CE) gave Fleury enormous prestige throughout the Frankish kingdom.\n\nFleury's 9th-century scriptorium — active during the Carolingian Renaissance under Charlemagne and his successors — produced illuminated manuscripts of exceptional quality and preserved classical texts that might otherwise have been lost. Abbot Theodulf of Orléans (bishop, not monk, but closely associated) and other Carolingian intellectuals worked in the Loire valley; Fleury's library contained Boethius's Consolation of Philosophy, Virgil, and other ancient texts copied for the Carolingian court.\n\nIn the 10th century, Fleury under Abbot Odo of Cluny and subsequently its own abbots became the model for Benedictine reform that spread across France and into England (Abbo of Fleury visited England in 985-987, influencing the Monastic Revival under Dunstan of Canterbury). The Abbey's 11th-12th century basilica (partly surviving today) is one of the finest Romanesque buildings in France. Fleury was suppressed in 1790 but refounded in 1944; it remains an active Benedictine monastery and pilgrimage site.",
        "causes": ["c. 640 CE founding near the Loire providing strategic location in the Frankish heartland", "Possession of St. Benedict's relics (claimed from Monte Cassino, c. 672) giving Fleury enormous prestige", "Carolingian Renaissance (8th-9th c.) making Fleury a scriptorium center preserving classical texts", "10th century Benedictine reform role spreading monastic renewal to England"],
        "effects": ["Benedictine reform tradition spread from Fleury to England through Abbo's 985-987 visit", "Carolingian manuscript preservation maintaining classical texts (Boethius, Virgil) through Dark Ages", "Romanesque basilica as finest 11th-12th century religious architecture in the Loire valley", "St. Benedict's relics making Fleury France's most important Benedictine pilgrimage destination"],
        "relationships": [{"entity": "St. Benedict of Nursia", "relationship": "CLAIMS_RELICS_OF", "note": "Fleury's claim to Benedict's relics (stolen from Monte Cassino c. 672) made it France's premier Benedictine center"}, {"entity": "Carolingian Renaissance", "relationship": "SCRIPTORIUM_CENTER_DURING", "note": "Fleury's 9th-century scriptorium copied classical texts during the Carolingian cultural revival"}, {"entity": "Abbo of Fleury", "relationship": "SCHOLAR_WHO_SPREAD_REFORM_TO_ENGLAND", "note": "Abbo's 985-987 English visit brought Fleury's Benedictine reform tradition to Anglo-Saxon monasticism"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Fleury Abbey — preserving classical texts during Europe's darkest centuries, spreading Benedictine reform from France to England, and claiming the relics that made it Western monasticism's most revered French site — was a pivotal transmission point for European civilization from antiquity to the medieval period.", "significanceCategory": "world-changing"},
    }),
    ("moissac-abbey", {
        "summary": "Moissac Abbey (Abbaye Saint-Pierre de Moissac) in the Tarn-et-Garonne department of southern France, founded in the 7th century and affiliated with Cluny in 1047, is home to one of the greatest surviving ensembles of Romanesque sculpture in the world — the south portal tympanum (c. 1115 CE) depicting Christ in Majesty surrounded by the four evangelists and 24 elders of the Apocalypse, and the cloister (1100 CE) with 76 decorated columns and 116 bas-relief capitals, both listed as UNESCO World Heritage Sites.\n\nThe Moissac portal tympanum — one of the supreme achievements of Western medieval art — depicts Christ enthroned with an expression of remote transcendence, surrounded by swirling figures of extraordinary emotional intensity. Art historians including Meyer Schapiro have argued that the Moissac cloister's animated, expressive figures represent a revolution in Western figural art — moving from hieratic Byzantine flatness to psychological expressiveness that anticipated Gothic and eventually Renaissance humanistic sculpture.\n\nMoissac's position on the Way of St. James (Camino de Santiago) — the great medieval pilgrimage route to Santiago de Compostela — meant that its sculptural program was viewed by hundreds of thousands of medieval pilgrims, spreading Romanesque artistic innovation across France and the Iberian Peninsula. The abbey was suppressed in 1790 and partially demolished; the Napoleonic railway threatened further demolition but local preservation efforts saved it. UNESCO World Heritage designation (1998) recognized it as part of the Routes of Santiago de Compostela in France.",
        "causes": ["7th century founding with Cluniac affiliation (1047) providing reform prestige and artistic patronage", "South portal tympanum (c. 1115) and cloister (1100) created as supreme Romanesque sculptural programs", "Position on Way of St. James spreading Moissac's artistic influence across medieval Europe", "UNESCO World Heritage designation (1998) as part of Routes of Santiago de Compostela"],
        "effects": ["Romanesque tympanum as one of Western art's greatest sculptural achievements", "Psychological expressiveness of Moissac figures anticipating Gothic and Renaissance figural sculpture", "Pilgrimage route influence spreading Romanesque sculptural innovation to France and Iberian Peninsula", "UNESCO recognition preserving abbey as essential medieval heritage site"],
        "relationships": [{"entity": "Way of St. James", "relationship": "LOCATED_ON", "note": "Moissac's Camino de Santiago position meant hundreds of thousands of pilgrims viewed its sculpture"}, {"entity": "UNESCO World Heritage", "relationship": "DESIGNATED_BY", "note": "UNESCO 1998 designated Moissac as part of Routes of Santiago de Compostela World Heritage Site"}, {"entity": "Cluny Abbey", "relationship": "AFFILIATED_WITH", "note": "1047 Cluniac affiliation provided reform prestige and artistic patronage for Moissac's sculptural program"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Moissac Abbey — home to one of Western art's greatest sculptural programs (the 1115 tympanum and 1100 cloister), a revolutionary step toward psychological expressiveness in medieval art, and a Way of St. James stop spreading innovation across medieval Europe — is one of the most artistically consequential medieval monasteries.", "significanceCategory": "world-changing"},
    }),
    ("solesmes-abbey", {
        "summary": "Solesmes Abbey (Abbaye Saint-Pierre de Solesmes) in the Sarthe department of western France, founded in the 11th century and re-established in 1833 by Prosper Guéranger as the center of the 19th-century Benedictine revival in France, is the most influential monastery in modern Catholic Church music — the abbey whose monks pioneered the scholarly reconstruction of Gregorian chant that resulted in Pope Pius X's 1903 decree mandating Gregorian chant as the Catholic Church's official liturgical music.\n\nProsper Guéranger (abbot 1833-1875) transformed Solesmes from a ruined medieval building into the intellectual and spiritual center of Benedictine renewal in France — a renewal that spread to 300+ Benedictine monasteries worldwide. His liturgical writings (L'Année Liturgique, multi-volume) revived knowledge of the medieval liturgy; his scholarly approach to Gregorian chant reconstruction — based on medieval manuscripts rather than corrupted baroque versions — was continued by his successors Dom Joseph Pothier and Dom André Mocquereau.\n\nThe Solesmes scholars' reconstruction of authentic Gregorian chant — culminating in the Graduale Romanum (official Roman Catholic chant book, multiple editions through the 20th century) — was adopted by the Vatican as the official Catholic liturgical music. This directly affected the musical life of every Catholic parish worldwide. Solesmes was expelled from France during the anti-clerical laws of 1901, briefly operating from the Isle of Wight (England), before returning to France. Today Solesmes remains the world's leading center of Gregorian chant research and performance.",
        "causes": ["Prosper Guéranger's 1833 re-establishment as center of French Benedictine revival", "Dom Pothier and Dom Mocquereau's 19th-century scholarly Gregorian chant reconstruction from manuscripts", "Pope Pius X's 1903 decree mandating Gregorian chant as Catholic official liturgical music", "Anti-clerical 1901 French laws expelling monks — temporary English exile before return"],
        "effects": ["Gregorian chant reconstructed by Solesmes adopted as official Catholic liturgical music worldwide", "300+ Benedictine monasteries revived through Solesmes's reform model", "Graduale Romanum (official Catholic chant book) produced by Solesmes scholars for Vatican", "Solesmes chant recordings (LP era to digital) bringing Gregorian chant to global audiences"],
        "relationships": [{"entity": "Prosper Guéranger", "relationship": "RE-FOUNDED_AND_SHAPED_BY", "note": "Guéranger's 1833-1875 abbacy made Solesmes the center of Catholic liturgical revival"}, {"entity": "Pope Pius X", "relationship": "SCHOLARLY_WORK_MANDATED_BY", "note": "Pius X's 1903 decree adopted Solesmes's Gregorian chant reconstruction as official Catholic liturgical music"}, {"entity": "Gregorian Chant", "relationship": "PRIMARY_SCHOLARLY_CENTER_FOR", "note": "Solesmes is the world's leading center for Gregorian chant research, performance, and recording"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Solesmes Abbey — reconstructing authentic Gregorian chant, having it mandated as official Catholic music (affecting a billion Catholics), and reviving the Benedictine monastic tradition across 300+ monasteries — is the most liturgically and musically influential monastery of the modern era.", "significanceCategory": "world-changing"},
    }),
    ("corbie-abbey", {
        "summary": "Corbie Abbey in Picardy, northern France, founded c. 657-661 CE by the Frankish queen Bathilde and her son Chlothar III in the Somme valley, was one of the most important Carolingian-era scriptoria and a founding center of the 'Corbie script' — an influential Carolingian minuscule hand whose clarity and consistency influenced the development of the script that, via Italian humanists in the 15th century, became the basis of modern Roman typefaces. Corbie's scriptorium produced hundreds of manuscripts that preserved classical Latin texts.\n\nCorbie was a major intellectual center in the 8th-9th centuries: the monk Alcuin of York worked in the orbit of Corbie's tradition, and Ratramnus of Corbie (d. c. 868) was a theologian whose writings on predestination and the Eucharist were significant in Carolingian theological debates. Paschasius Radbertus (c. 790-865), abbot of Corbie, wrote De Corpore et Sanguine Domini — the first systematic treatise on the Eucharist — whose controversy with Ratramnus previewed the 11th-century Berengarian controversy about transubstantiation.\n\nCorbie's artistic production included illuminated manuscripts of extraordinary quality. The Maurdramnus Bible (c. 781-783 CE) — produced under Abbot Maurdramnus, a former chancellor of Charlemagne — is one of the most beautiful Carolingian manuscripts and a key witness to the Carolingian 'rebirth' of classical Latin script. The abbey was sacked by Vikings (881 CE), recovered, but never fully regained its 8th-9th century intellectual eminence. It was suppressed in 1790 and the buildings substantially demolished.",
        "causes": ["c. 657-661 founding by Queen Bathilde providing royal Frankish patronage from the outset", "Carolingian Renaissance (8th-9th c.) making Corbie a major scriptorium producing classical text copies", "Development of 'Corbie script' (Carolingian minuscule variant) influencing European handwriting", "Paschasius Radbertus's Eucharist treatise (c. 831) initiating medieval debates on transubstantiation"],
        "effects": ["Corbie script influencing Carolingian minuscule tradition ancestral to modern Roman typefaces", "Maurdramnus Bible as masterpiece of Carolingian manuscript illumination", "Paschasius Radbertus's Eucharist treatise triggering medieval debates culminating in 1215 transubstantiation dogma", "Classical text preservation in Corbie manuscripts passing ancient literature to medieval Europe"],
        "relationships": [{"entity": "Charlemagne", "relationship": "ABBOT_WAS_CHANCELLOR_OF", "note": "Abbot Maurdramnus (c. 781-783) was a former chancellor of Charlemagne; Corbie was part of the Carolingian court circle"}, {"entity": "Paschasius Radbertus", "relationship": "ABBOT_WHO_WROTE_FOUNDATIONAL_EUCHARIST_TREATISE", "note": "Paschasius Radbertus (abbot 844-853) wrote De Corpore et Sanguine Domini — first Eucharist systematic treatise"}, {"entity": "Carolingian Renaissance", "relationship": "MAJOR_SCRIPTORIUM_CENTER_DURING", "note": "Corbie's 8th-9th century scriptorium was among the most productive of the Carolingian cultural revival"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Corbie Abbey — developing the script tradition ancestral to modern Roman typefaces, producing the Maurdramnus Bible, and initiating medieval debates about the Eucharist that led to 1215 transubstantiation dogma — was one of the most intellectually consequential Carolingian monasteries.", "significanceCategory": "world-changing"},
    }),
    ("chiaravalle-abbey", {
        "summary": "Chiaravalle Abbey (Abbazia di Chiaravalle) near Milan, founded in 1135 by Bernard of Clairvaux — the most influential churchman of the 12th century — as one of the first Cistercian monasteries in Lombardy, represents the expansion of Cistercian monasticism across northern Italy and the agricultural and cultural transformation that Cistercian communities brought to the Po Valley. The abbey's brick construction (completed 13th century) reflects the Lombard Romanesque tradition adapted to Cistercian austerity principles.\n\nBernard of Clairvaux — who founded Chiaravalle as part of his campaign to spread Cistercian reform across Europe — was the most powerful religious figure of the 12th century: he preached the Second Crusade (1147), condemned the philosopher Abelard at the Council of Sens (1140), and influenced the election of Pope Eugenius III (a Cistercian). Chiaravalle's founding was part of Bernard's vision of Cistercian communities as both spiritual and agricultural reform centers.\n\nChiaravalle's monks drained the marshy land around their abbey and introduced improved agricultural techniques (water mills, crop rotation) that transformed Lombard agriculture. The abbey's dairy farming — particularly the aging of cheese in its cellars — contributed to the development of Italian cheeses; Chiaravalle monks are credited with innovations in Lombard cheese-making that preceded modern Grana Padano and related cheeses. The abbey was suppressed by Napoleon in 1798 but refounded; it remains an active Cistercian community and is a major tourist attraction near Milan.",
        "causes": ["1135 founding by Bernard of Clairvaux as part of Cistercian reform expansion across Italy", "Bernard's 12th-century influence making Cistercian foundations politically and spiritually significant", "Cistercian agricultural reform (marsh drainage, water mills) transforming Po Valley land use", "Lombard Romanesque brick building tradition creating distinctive Italian Cistercian architecture"],
        "effects": ["Cistercian agricultural transformation of Po Valley marshes through drainage and improved techniques", "Lombard cheese-making traditions associated with Chiaravalle monks influencing Grana Padano development", "Cistercian reform model spread across northern Italy through Bernard's personal founding initiative", "13th-century brick complex as finest example of Italian Cistercian architecture near Milan"],
        "relationships": [{"entity": "Bernard of Clairvaux", "relationship": "FOUNDED_BY", "note": "Bernard of Clairvaux founded Chiaravalle in 1135 as part of his Cistercian reform campaign"}, {"entity": "Cistercian Order", "relationship": "ITALIAN_EXPANSION_EXAMPLE_OF", "note": "Chiaravalle represents Cistercian monasticism's early entry into northern Italy"}, {"entity": "Po Valley", "relationship": "AGRICULTURAL_TRANSFORMATION_OF", "note": "Chiaravalle monks drained marshes and introduced agricultural improvements transforming Lombard land use"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Chiaravalle Abbey — founded by St. Bernard of Clairvaux as a Cistercian reform center, transforming Po Valley agriculture through drainage and improved techniques, and contributing to Lombard cheese-making traditions — is a key institution in the story of medieval monasticism's agricultural and cultural impact on northern Italy.", "significanceCategory": "continental"},
    }),
    ("abbey-of-san-galgano", {
        "summary": "The Abbey of San Galgano in Tuscany, built 1218-1288 CE in the Merse valley and abandoned by 1786 when the last monk left, is today one of Europe's most hauntingly beautiful architectural ruins — a Gothic Cistercian church whose roof collapsed in the 17th century, leaving the soaring stone nave open to the sky, floored with grass, used as a natural amphitheater. The adjacent Hermitage of Montesiepi contains the original chapel of St. Galgano Guidotti (who thrust his sword into a stone as a renunciation of his military life, the probable historical inspiration for the Arthurian sword-in-stone legend).\n\nThe Abbey's historical significance extends beyond its aesthetic beauty: Cistercian monks from San Galgano managed the finances and public works of the Sienese Republic in the 13th century — building the Siena Cathedral (they managed its construction), helping design the Palazzo Pubblico, and effectively serving as Siena's public administrators. The monks' mathematical and engineering expertise made them indispensable to medieval Italian city-states.\n\nThe sword in the stone at Montesiepi — a real medieval sword thrust into the rock by St. Galgano (according to tradition, c. 1180 CE) — has recently been investigated by metallurgical analysis, which confirmed it is a genuine medieval sword of the late 12th century, supporting the historical core of the legend. The abbey ruins are UNESCO-protected and appear in Federico Fellini films; the association with the Arthurian sword-in-stone motif makes San Galgano one of the most mysterious and historically layered sites in Italy.",
        "causes": ["1218-1288 CE Cistercian construction creating one of Tuscany's finest Gothic churches", "Cistercian monks' mathematical expertise making them Sienese Republic's financial and architectural managers", "St. Galgano's sword-in-stone tradition (c. 1180) preceding Arthurian legends and possibly influencing them", "17th-18th century abandonment and roof collapse creating spectacular Gothic ruin"],
        "effects": ["San Galgano ruins as one of Europe's most beautiful architectural ruins — open-sky Gothic nave", "Cistercian management of Siena Cathedral construction defining Siena's architectural masterpiece", "Sword in the stone (confirmed medieval by metallurgical analysis) as possible historical basis for Arthurian legend", "UNESCO protection and film appearances (Fellini) making it iconic in modern Italian culture"],
        "relationships": [{"entity": "Siena Cathedral", "relationship": "CONSTRUCTION_MANAGED_BY", "note": "San Galgano monks managed construction of Siena Cathedral — one of Italy's great Gothic buildings"}, {"entity": "Sienese Republic", "relationship": "FINANCIAL_ADMINISTRATORS_OF", "note": "Cistercian monks from San Galgano served as Siena's public accountants and building managers in 13th century"}, {"entity": "Arthurian Legend", "relationship": "SWORD_IN_STONE_POSSIBLE_HISTORICAL_BASIS_FOR", "note": "Galgano's sword thrust into rock (c. 1180, confirmed medieval) may be historical basis for Arthurian sword-in-stone"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "San Galgano Abbey — managing Siena Cathedral's construction, serving as the Sienese Republic's financial administrators, containing the probable historical sword-in-stone that inspired Arthurian legend, and existing as one of Europe's most beautiful Gothic ruins — is among Italy's most historically layered and artistically significant medieval sites.", "significanceCategory": "continental"},
    }),
    ("hermitage-of-camaldoli", {
        "summary": "The Hermitage of Camaldoli (Sacro Eremo di Camaldoli) in the Casentino forest of Tuscany, founded c. 1012 CE by St. Romuald of Ravenna as the mother house of the Camaldolese order — a distinctive monastic tradition combining the solitary hermit life of the Desert Fathers with Benedictine community living — is one of the most intellectually and spiritually influential medieval hermitages, producing scholars and church reformers who shaped 15th-century Humanism and early church reform.\n\nThe Camaldolese tradition — a unique compromise between complete hermitage and communal Benedictine life — was St. Romuald's synthesis of the Egyptian Desert Fathers' solitary tradition with Western Benedictine order; each monk lives in a separate cell (hermitage) with a small garden, but within a community providing liturgy and mutual support. This model influenced later orders including the Carthusians.\n\nIn the 15th century, the Camaldolese hermitage at Florence (Santa Maria degli Angeli) became one of the key sites of Italian Humanism: the abbot Ambrogio Traversari (1386-1439) was the foremost Greek scholar in Italy before the Byzantine emigration of the 1450s, translating Diogenes Laertius, John Chrysostom, and Greek church fathers — making Greek patristic literature available to Italian Humanists. His work directly influenced Cosimo de' Medici's patronage of Greek studies. The Camaldoli forest is now a protected nature reserve; the hermitage is an active monastic community and major pilgrimage destination.",
        "causes": ["c. 1012 founding by St. Romuald creating a unique hermit-community hybrid monasticism", "Camaldolese synthesis of Desert Father solitude with Benedictine community inspiring subsequent orders", "Ambrogio Traversari's Greek translations (1410s-1430s) introducing Greek patristic texts to Italian Humanism", "Casentino forest protection creating one of Italy's best-preserved medieval natural environments"],
        "effects": ["Camaldolese order model influencing Carthusian and other hybrid contemplative orders", "Traversari's Greek translations directly enabling Medici patronage of Greek classical scholarship", "Hermitage as model for individual contemplative cells-within-community adopted globally", "Casentino forest protection as one of Italy's oldest continuously managed forests"],
        "relationships": [{"entity": "St. Romuald of Ravenna", "relationship": "FOUNDED_BY", "note": "Romuald founded Camaldoli c. 1012 as synthesis of Egyptian hermit and Benedictine community tradition"}, {"entity": "Ambrogio Traversari", "relationship": "MOST_CONSEQUENTIAL_CAMALDOLESE_SCHOLAR", "note": "Traversari's Greek translations (1410s-1430s) were crucial to Italian Humanism before Byzantine emigration"}, {"entity": "Italian Renaissance", "relationship": "INDIRECTLY_CONTRIBUTED_TO_VIA_TRAVERSARI", "note": "Traversari's Greek scholarship and Medici connection made Camaldoli a contributor to Renaissance Humanism"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Camaldoli Hermitage — founding a unique hybrid monasticism that influenced subsequent orders, producing Traversari's Greek translations that fed Italian Renaissance scholarship, and maintaining the Casentino forest for a millennium — is one of Italy's most intellectually and environmentally consequential monastic foundations.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 107 — Class 344 Abbeys III: Medieval European Abbeys")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
