#!/usr/bin/env python3
"""Batch 124 — Class 341 Cathedrals VI: Toledo + Nancy Churches (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/341-Class-341"
FILE_PREFIX = "341"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("church-of-san-ildefonso-toledo", {
        "summary": "The Church of San Ildefonso (also known as El Transparente church or the Jesuit Church of Toledo) in Toledo, Spain, is a Baroque masterpiece completed in 1765 by the Jesuit order, renowned primarily for its extraordinary El Transparente altarpiece (1732, by Narciso Tomé) — a revolutionary Baroque sculptural and architectural composition in which a hole was cut in the cathedral vault to allow natural light from above to illuminate the golden altarpiece below, creating a theatrical light effect that was one of the most innovative and controversial Baroque decorative programs in Spain and indeed in all of European religious art.\n\nEl Transparente (literally 'The Transparent One') is the defining architectural achievement of Toledo's San Ildefonso: Narciso Tomé's composition combined painting, sculpture, and architecture in a total Gesamtkunstwerk where real sunlight was used as a medium for religious illumination. The dramatic light effect — with clouds, angels, and golden rays sculpted in the stone of the vault opening, giving the impression that the tabernacle of the Eucharist is bathed in heavenly light — was intended to create an experiential demonstration of Eucharistic theology. Contemporary viewers were both awed and disturbed by its theatrical excess.\n\nThe church's facade and interior are among the finest Baroque architectural achievements in Toledo, a city already extraordinary for its medieval Gothic Cathedral (one of Spain's greatest), El Greco's paintings, and Mudejar heritage. The Jesuits established the church as their Toledo institution but were expelled from Spain in 1767 (two years after completion) when Charles III expelled the entire Jesuit order from Spanish territories — meaning the church was barely used as a Jesuit institution before their expulsion.",
        "causes": ["Jesuit order's Toledo mission requiring an architectural statement competing with the city's Gothic Cathedral", "Baroque theatrical religious art tradition reaching its zenith in El Transparente's light manipulation", "Narciso Tomé's innovative combination of architecture, sculpture, and natural light in revolutionary altarpiece", "Charles III's 1767 Jesuit expulsion creating irony of Jesuit church used barely before builders' expulsion"],
        "effects": ["El Transparente as one of the most technically innovative and controversial Baroque decorative programs in European religious art", "Natural light as artistic medium demonstrating the Baroque period's integration of theater, architecture, and religion", "Post-Jesuit-expulsion church continuing as important Toledo monument under secular or diocesan administration", "Toledo's Baroque heritage enriched alongside its Gothic Cathedral and El Greco legacy"],
        "relationships": [{"entity": "Narciso Tomé", "relationship": "EL_TRANSPARENTE_DESIGNED_BY", "note": "Narciso Tomé's El Transparente altarpiece (1732) is the church's defining achievement using natural light as artistic medium"}, {"entity": "Society of Jesus", "relationship": "BUILT_AND_BRIEFLY_USED_BY", "note": "The Jesuits built San Ildefonso but were expelled from Spain (1767) just two years after its completion"}, {"entity": "Toledo", "relationship": "BAROQUE_MASTERPIECE_AMONG_HERITAGE_OF", "note": "San Ildefonso adds Baroque heritage to Toledo's extraordinary portfolio of Gothic, Mudejar, and Renaissance monuments"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Church of San Ildefonso Toledo — with El Transparente's revolutionary natural-light Baroque altarpiece among the most innovative religious art programs in Spain — is a historically significant monument of Spanish Baroque excess, Jesuit artistic ambition, and the Enlightenment-era Jesuit expulsion.", "significanceCategory": "world-changing"},
    }),
    ("church-of-santa-leocadia-toledo", {
        "summary": "The Church of Santa Leocadia in Toledo, Spain, is historically significant as one of the sites associated with the Councils of Toledo — a series of important ecclesiastical and political assemblies held in Visigothic Spain from the 4th through 7th centuries that were among the most consequential church councils in the early medieval period, addressing theological controversies (particularly Arianism), church-state relations, Jewish persecution policies, and the legal structure of the Visigothic kingdom — with the church's dedication to Santa Leocadia, Toledo's 4th-century virgin martyr who died during Diocletian's persecution, rooting it in the city's earliest Christian heritage.\n\nToledo was the capital of the Visigothic Kingdom (from circa 554 CE) and the site of nineteen major church councils between 400 and 702 CE. The Third Council of Toledo (589 CE) was the most historically significant: it formalized the Visigothic King Reccared's conversion from Arianism to Nicene Christianity, marking the completion of the Visigothic kingdom's religious unification and the alliance between church and state that would characterize medieval Iberian Catholicism. The Church of Santa Leocadia, associated with Visigothic royalty and the Toledo councils, embodies this early Iberian Christian history.\n\nThe current church is a much later reconstruction — Toledo's medieval fabric was repeatedly rebuilt, and early Visigothic structures rarely survived. The historical association with the Visigothic councils makes Santa Leocadia's site historically significant even if the standing architecture is later. Toledo's extraordinary concentration of religious history — Visigothic, Muslim (750-year presence), Jewish, and Catholic — makes each monument part of an exceptionally dense historical landscape.",
        "causes": ["Leocadia's 4th-century martyrdom during Diocletian's persecution establishing the church's titular saint", "Visigothic Toledo's status as Iberian Catholic capital requiring major churches dedicated to local saints", "Third Council of Toledo (589 CE) and other Visigothic councils elevating Toledo's ecclesiastical significance", "Toledo's Reconquista Christian restoration requiring dedication of key sites to Visigothic heritage saints"],
        "effects": ["Church's site preserving memory of the Visigothic Toledo councils that shaped medieval Iberian Catholicism", "Santa Leocadia's cult maintaining the memory of Toledo's early Christian martyrdom tradition", "Visigothic Toledo's council tradition providing constitutional precedents for medieval church-state relations in Spain", "Toledo's religious landscape enriched by layering of Visigothic, Muslim, and Catholic heritage"],
        "relationships": [{"entity": "Councils of Toledo", "relationship": "ASSOCIATED_WITH_SITE_OF", "note": "The Church of Santa Leocadia is associated with the Visigothic-era Councils of Toledo that shaped early medieval Iberian Christianity"}, {"entity": "Third Council of Toledo", "relationship": "SYMBOLICALLY_LINKED_TO_VISIGOTHIC_CAPITAL_OF", "note": "The 589 CE Third Council's conversion of the Visigothic kingdom to Nicene Christianity was Toledo's defining religious moment"}, {"entity": "Santa Leocadia", "relationship": "DEDICATED_TO_TOLEDO'S_EARLY_CHRISTIAN_MARTYR", "note": "The church honors Leocadia, Toledo's 4th-century martyr who died during Diocletian's persecution"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Church of Santa Leocadia Toledo — associated with the Visigothic Councils of Toledo that shaped Iberian Christianity, dedicated to Toledo's early martyr, and part of one of Europe's most historically layered religious cities — is a historically meaningful monument of early Spanish Christianity.", "significanceCategory": "continental"},
    }),
    ("church-of-st-james-toledo", {
        "summary": "The Church of Saint James (Iglesia de Santiago del Arrabal) in Toledo, Spain, is a 13th-century Mudejar church — one of Toledo's finest examples of the Mudejar architectural style, the unique synthesis of Islamic and Christian architectural forms that developed in medieval Iberia as Christian kingdoms expanded into formerly Muslim territories and employed Muslim craftsmen (mudejares) to build Christian churches using their traditional Islamic skills and decorative vocabulary. The church features a distinctive Mudejar bell tower and interior decorations that are among the finest surviving examples of this distinctly Iberian architectural fusion.\n\nMudejar architecture, developed primarily in the 12th-15th centuries in Castile, Aragon, and Toledo, is one of art history's most remarkable examples of cultural synthesis: it emerged when Christian patrons commissioned skilled Islamic craftsmen (mudejares) to build churches using the brickwork, geometric ornament, wooden ceiling (artesonado), ceramic tile (azulejo), and blind arcade forms of Andalusian Islamic architecture. The result was buildings that are unmistakably Christian in function and plan but Islamic in decorative vocabulary and construction technique — a fusion without precise parallel elsewhere in world architectural history.\n\nThe Church of Santiago del Arrabal stands outside the original city walls (del Arrabal means 'of the suburb') in the area where Saint Leocadia supposedly died in prison. The Mudejar tower is particularly notable — its elaborately patterned brickwork and blind arcades are characteristic of the Toledo Mudejar school. Toledo's concentration of Mudejar buildings (along with churches, synagogues, and mosques) is part of its UNESCO World Heritage designation as an exceptional example of a multicultural medieval city.",
        "causes": ["13th-century Toledo Reconquista expansion requiring Christian church construction using available Muslim craftsmen", "Mudejar architectural tradition emerging from Muslim craftsmen's employment by Christian patrons in reconquered territories", "Santiago (Saint James) dedication connecting the church to the Reconquista's patron saint symbolism", "Del Arrabal suburban location associated with early Christian martyrdom traditions outside Toledo's city walls"],
        "effects": ["Finest Mudejar tower in Toledo as primary example of Islamic-Christian architectural synthesis", "Toledo's Mudejar heritage ensemble contributing to UNESCO World Heritage designation for multicultural medieval city", "Mudejar architectural tradition documented through Toledo's concentration of surviving examples", "Cultural synthesis of Islamic and Christian building traditions as unique contribution to world architectural history"],
        "relationships": [{"entity": "Mudejar Architecture", "relationship": "FINEST_TOLEDO_EXAMPLE_OF", "note": "Santiago del Arrabal is one of Toledo's finest Mudejar churches demonstrating Islamic-Christian architectural synthesis"}, {"entity": "Toledo UNESCO Heritage", "relationship": "COMPONENT_OF_MULTICULTURAL_CITY_DESIGNATION", "note": "The church is part of Toledo's UNESCO World Heritage designation as exceptional multicultural medieval city"}, {"entity": "Reconquista", "relationship": "BUILT_DURING_EXPANSION_OF", "note": "The 13th-century construction occurred during the Reconquista period when Christian patrons employed Muslim Mudejar craftsmen"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Church of Saint James (Santiago del Arrabal) Toledo — a 13th-century Mudejar masterpiece combining Islamic and Christian architectural traditions, part of UNESCO's multicultural Toledo heritage, and demonstrating the unique Iberian cultural synthesis of the Reconquista era — is historically significant for both its architectural innovation and its multicultural meaning.", "significanceCategory": "world-changing"},
    }),
    ("iglesia-de-los-santos-justo-y-pastor-toledo", {
        "summary": "The Church of Saints Justus and Pastor (Iglesia de los Santos Justo y Pastor) in Toledo, Spain, is a historic Catholic church dedicated to Saints Justus and Pastor, two child martyrs from Alcalá de Henares who were executed during the Diocletian persecution (circa 304 CE) and are the patron saints of Alcalá and of the Complutense University tradition — with their cult spreading throughout Castile and their dedication in Toledo churches reflecting the early Christian martyrdom tradition that deeply shaped Iberian Catholic identity.\n\nSaints Justus and Pastor (San Justo y Pastor) were legendary child martyrs of approximately 13 and 7 years old who, according to hagiographic tradition, voluntarily presented themselves to the Roman governor in Alcalá de Henares (then Complutum) to be martyred after hearing of others being executed for Christianity. Their youth, courage, and voluntary martyrdom made them powerful symbols of Christian commitment; their cult was well established by the 4th century and their feast day (August 6) was observed throughout the Iberian Church.\n\nThe Toledo church dedicated to Saints Justus and Pastor reflects the dense network of martyr-saint dedications in Toledo's ecclesiastical geography. Toledo's churches collectively preserve the memory of the entire range of early Christian martyrdom traditions, both local (Santa Leocadia) and regional (Saints Justus and Pastor from nearby Alcalá). Toledo's extraordinary religious concentration — with hundreds of historic churches in a small walled city — makes each dedication part of a continuous liturgical memory of Iberian Christianity extending from the Roman period through the Reconquista to the present.",
        "causes": ["Saints Justus and Pastor cult establishment throughout Castile following their 304 CE child martyrdom in Alcalá", "Toledo's dense ecclesiastical geography requiring church dedications to the full range of regional Iberian saints", "Child martyrdom symbolism in early Christian tradition creating powerful devotional appeal for Justus and Pastor", "Alcalá de Henares (Complutum) connection to Toledo through regional Castilian ecclesiastical networks"],
        "effects": ["Martyr cult preservation in Toledo contributing to the continuous memory of early Iberian Christian persecution", "Santos Justo y Pastor dedication in multiple Castilian cities documenting the saints' regional cult spread", "Toledo's church network collectively forming a complete memorial of Iberian Christianity's first centuries", "Child martyrdom devotion connecting popular Catholicism to the early persecutions that formed Christian identity"],
        "relationships": [{"entity": "Saints Justus and Pastor", "relationship": "DEDICATED_TO_CHILD_MARTYRS", "note": "The church honors the child martyrs of Alcalá (304 CE) whose voluntary martyrdom made them powerful symbols of Christian faith"}, {"entity": "Diocletian Persecution", "relationship": "MARTYRDOM_CONTEXT_FOR_PATRON_SAINTS_OF", "note": "Saints Justus and Pastor were executed during the Diocletian persecution, the most severe Roman anti-Christian campaign"}, {"entity": "Toledo's Ecclesiastical Network", "relationship": "PART_OF_DENSE_MARTYR-SAINT_DEDICATIONS_OF", "note": "The church is one node in Toledo's extraordinary network of churches preserving Iberian Christian martyrdom memory"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "The Church of Saints Justus and Pastor Toledo — dedicated to Castile's beloved child martyrs, part of Toledo's extraordinary ecclesiastical network, and preserving memory of the Diocletian persecution's Iberian victims — is historically meaningful as a node in early Iberian Christian martyrdom commemoration.", "significanceCategory": "local"},
    }),
    ("iglesia-de-santiago-el-real", {
        "summary": "The Church of Santiago el Real (Royal Church of Saint James) is an important ecclesiastical institution in Spain with notable examples in multiple cities — most significantly in Logroño (La Rioja), where the Church of Santiago el Real stands as the city's most important church on the Camino de Santiago, housing the famous Matamoros (Moor-slayer) statue of Santiago over its portal, and in Medina de Rioseco (Valladolid), where another Santiago el Real contains extraordinary Renaissance and Baroque retablos. The Logroño Santiago el Real exemplifies the fusion of Reconquista religious ideology and Camino de Santiago pilgrimage culture that made Santiago Matamoros one of the most powerful iconographic programs in Spanish history.\n\nLogroño's Santiago el Real stands directly on the Camino Francés (French Way) — the main Santiago pilgrimage route — and the Matamoros figure over the portal (Santiago on horseback trampling Moorish soldiers) is one of the most explicit visual statements of the Reconquista religious ideology. Santiago Matamoros first appeared at the Battle of Clavijo (circa 844 CE) where, according to legend, the Apostle James miraculously appeared on horseback to help Christian forces defeat the Moors — a legend that was politically developed by the medieval Iberian kingdoms to give the Reconquista divine legitimacy.\n\nThe Santiago el Real designation ('el Real' indicating royal patronage or affiliation) connects the church to the Spanish Crown's long association with the Santiago cult and the Military Order of Santiago (founded 1170), which combined knightly warfare with Camino pilgrimage protection. The Santiago el Real in Medina de Rioseco contains one of Spain's finest collections of Renaissance and Baroque retablos, including works by major Spanish Renaissance artists.",
        "causes": ["Santiago Matamoros cult development as divine legitimation of the Reconquista from the 9th century", "Camino de Santiago pilgrimage route requiring major churches with Santiago iconography along the way", "Royal patronage ('el Real') connecting Spanish Crown to Santiago cult and Military Order of Santiago", "Logroño's position on Camino Francés making it appropriate site for major pilgrim-route Santiago church"],
        "effects": ["Matamoros figure documenting the fusion of holy warfare ideology and pilgrimage culture in Reconquista Spain", "Church as Camino pilgrimage landmark welcoming pilgrims to Logroño as a primary stage on the French Way", "Santiago el Real dedications throughout Spain documenting the royal investment in the Santiago cult's political uses", "Medina de Rioseco retablos preserving major Renaissance and Baroque religious art collections"],
        "relationships": [{"entity": "Camino de Santiago", "relationship": "PILGRIMAGE_LANDMARK_ON_FRENCH_WAY", "note": "Logroño's Santiago el Real stands directly on the Camino Francés as a major pilgrimage stage church"}, {"entity": "Santiago Matamoros", "relationship": "PRINCIPAL_ICONOGRAPHIC_PROGRAM_OF", "note": "The Matamoros statue over the portal represents the Reconquista ideology of Santiago as divine warrior against Islam"}, {"entity": "Reconquista", "relationship": "RELIGIOUS_IDEOLOGY_MEMORIALIZED_IN_CHURCH_OF", "note": "Santiago el Real's Matamoros iconography is one of the most explicit visual statements of the Reconquista's religious legitimation"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Church of Santiago el Real (Logroño) — standing on the Camino Francés with a Matamoros figure among the most powerful visual statements of Reconquista ideology, and representing royal Santiago cult patronage on the pilgrimage route — is historically significant for the intersection of holy warfare, pilgrimage, and Spanish national religious identity.", "significanceCategory": "world-changing"},
    }),
    ("basilique-du-sacré-coeur-de-nancy", {
        "summary": "The Basilica of the Sacred Heart of Nancy (Basilique du Sacré-Cœur de Nancy), a neogothic basilica constructed in Nancy, Lorraine, France between 1901 and 1953, is one of the significant Catholic churches of Nancy — a city that already possessed the extraordinary UNESCO-listed Place Stanislas and its 18th-century Baroque heritage — representing the 19th-20th century Sacred Heart devotion movement that produced major basilicas throughout France (most famously the Sacré-Cœur of Paris, 1875-1914) as expressions of Catholic piety in the context of post-1870 French religious-political polarization.\n\nThe Sacred Heart devotion (Sacré-Cœur), rooted in the visions of Saint Margaret Mary Alacoque in 17th-century France and institutionalized through the Jesuits, experienced an extraordinary revival after France's 1870 defeat in the Franco-Prussian War and the Paris Commune. Many French Catholics interpreted these disasters as divine punishment for France's secularization and atheism, and the building of Sacred Heart basilicas was conceived as a national act of reparation and consecration. The Paris Sacré-Cœur on Montmartre was the most famous expression; provincial basilicas like Nancy's participated in the same religious-political movement.\n\nNancy's Basilica of the Sacred Heart, though less architecturally famous than Paris's, is significant in the context of Lorraine — the French-German borderland that was ceded to Germany after 1870 (Lorraine was partially annexed) and remained a contested territory until 1918. The Sacred Heart basilica in Nancy, the regional capital of the unannexed portion of Lorraine, carried particular patriotic and religious meaning for Lorrainers who regarded themselves as guardians of French Catholic tradition.",
        "causes": ["Post-1870 Franco-Prussian War defeat triggering Catholic 'national reparation' basilica building movement in France", "Sacred Heart devotion revival as Catholic response to French secularization and political anti-clericalism", "Lorraine's special status as contested Franco-German borderland intensifying the basilica's patriotic religious meaning", "Neogothic architectural fashion for major French Catholic churches of the 1900-1950 period"],
        "effects": ["Nancy's basilica participating in the national Sacred Heart basilica building movement as Lorraine's contribution", "Lorraine Catholic identity consolidated around the basilica during French-German border tensions 1870-1918", "Neogothic architecture complementing Nancy's extraordinary 18th-century Baroque heritage", "Sacred Heart movement connecting individual Marian and Christological devotion to French national religious politics"],
        "relationships": [{"entity": "Sacred Heart Devotion", "relationship": "ARCHITECTURAL_MONUMENT_TO", "note": "The basilica embodies the post-1870 Sacred Heart building movement as Catholic response to French secularization"}, {"entity": "Lorraine", "relationship": "REGIONAL_CATHOLIC_LANDMARK_OF_CONTESTED_BORDERLAND", "note": "Nancy's Sacred Heart basilica carried special patriotic meaning as Lorraine's French Catholic monument during German annexation period"}, {"entity": "Sacré-Cœur Paris", "relationship": "PROVINCIAL_COUNTERPART_TO", "note": "Nancy's basilica participates in the same post-1870 Sacred Heart basilica movement as Paris's famous Montmartre Sacré-Cœur"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "The Basilica of the Sacred Heart of Nancy — participating in the post-1870 French Catholic national reparation movement, serving as Lorraine's patriotic Catholic monument during the contested French-German border period, and adding neogothic heritage to Nancy's extraordinary Baroque city — is historically meaningful in its regional religious and political context.", "significanceCategory": "local"},
    }),
    ("basilique-notre-dame-de-lourdes-de-nancy", {
        "summary": "The Basilica of Notre-Dame de Lourdes in Nancy (Basilique Notre-Dame de Lourdes de Nancy), a 20th-century Catholic basilica in Nancy, Lorraine, France dedicated to the Virgin of Lourdes — representing the Lourdes Marian apparition tradition (1858) that has made Lourdes the most visited pilgrimage site in the world — is one of the several Lourdes-dedicated churches built throughout France and the world as 'proxy Lourdes' pilgrimage and devotional centers for communities unable to travel to the original Lourdes grotto in the Pyrenees.\n\nThe apparitions of the Virgin Mary to Bernadette Soubirous at Lourdes in 1858, subsequently confirmed by the Catholic Church as authentic apparitions, made Lourdes the center of one of the most powerful Catholic pilgrimage traditions in modern history. The spring discovered during the apparitions became associated with miraculous cures, and Lourdes grew to receive 6 million pilgrims annually by the 20th century. The devotion to Notre-Dame de Lourdes spread worldwide through replica grottos, dedicated chapels, and basilicas constructed in every country with significant Catholic populations.\n\nNancy's Notre-Dame de Lourdes basilica belongs to this worldwide network of Lourdes-dedicated sacred spaces. Its construction and dedication reflect the extraordinary impact of the Lourdes apparitions on 19th-20th century French Catholicism — particularly in Lorraine, where Marian devotion was combined with patriotic sentiment (the 1870 defeat, German annexation, and hope for return of Alsace-Lorraine intensified French Catholic Marian piety). The basilica continues to serve Nancy's Catholic community as a Lourdes-affiliated pilgrimage site.",
        "causes": ["1858 Lourdes apparitions creating worldwide Catholic demand for Notre-Dame de Lourdes dedicated churches", "French Catholic devotion to Lourdes as proxy for pilgrimage accessible to those unable to travel to the Pyrenees", "Lorraine's patriotic Marian piety combining devotion to the Virgin with hope for return of annexed territories", "20th-century Catholic church building program in Nancy requiring additional parishes and devotional centers"],
        "effects": ["Nancy Lourdes basilica as node in worldwide network of thousands of Lourdes-dedicated sacred spaces", "Catholic community pilgrimage center providing Lourdes devotion without requiring long-distance travel to the Pyrenees", "Lorraine's Marian devotion institutionalized through permanent basilica dedicated to the apparition Virgin", "Lourdes apparition's global impact demonstrated through the proliferation of dedicated churches on every continent"],
        "relationships": [{"entity": "Our Lady of Lourdes", "relationship": "DEDICATED_TO_APPARITION_VIRGIN_OF", "note": "The basilica is dedicated to the Virgin Mary as she appeared at Lourdes in 1858 to Bernadette Soubirous"}, {"entity": "Lourdes Pilgrimage", "relationship": "PROXY_CENTER_FOR", "note": "Like thousands of similar churches worldwide, the Nancy basilica serves as a local Lourdes pilgrimage destination"}, {"entity": "Nancy", "relationship": "MARIAN_DEVOTION_MONUMENT_OF", "note": "The basilica contributes to Nancy's Catholic religious heritage alongside its better-known Baroque civic monuments"}],
        "historicalSignificance": {"significanceScore": 4, "significanceNarrative": "The Basilica of Notre-Dame de Lourdes Nancy — one of thousands of Lourdes-dedicated churches worldwide, serving as a local proxy pilgrimage site, and reflecting the extraordinary global impact of the 1858 Lourdes apparitions on Catholic devotion — is locally significant and part of the most widespread Catholic pilgrimage devotion network in modern history.", "significanceCategory": "local"},
    }),
    ("basilique-sainte-clotilde-de-reims", {
        "summary": "The Basilica of Sainte-Clotilde de Reims, dedicated to Saint Clotilde (also Clothilde, circa 474-545 CE) — the Frankish queen who converted her husband, Clovis I (King of the Franks), to Christianity in 496 CE, one of the most consequential religious conversions in European history — is a Catholic church in Reims, the city already famous as the coronation site of French kings and as the location of the magnificent Gothic Reims Cathedral. Clotilde's role in Clovis's baptism at Reims by Bishop Remigius links her directly to the founding religious act of the French nation.\n\nSaint Clotilde's historical significance is extraordinary: as a Burgundian Christian princess who married the pagan Frankish king Clovis I, her persistent encouragement of her husband's conversion was pivotal in his decision to receive Christian baptism in Reims (traditionally dated to December 25, 496 CE, though scholars debate the exact date). Clovis's baptism had enormous consequences: it made the Frankish kingdom an ally of the Catholic Church against Arian Christianity (most other Germanic kingdoms were Arian), provided the ideological foundation for the later alliance between the French monarchy and the papacy, and began the process by which the Franks became the most powerful Catholic kingdom in Europe — ultimately leading to Charlemagne's 800 CE coronation as Holy Roman Emperor.\n\nThe Reims basilica honoring Clotilde stands in the city that witnessed the baptism she facilitated — making the dedication historically resonant. Reims Cathedral is the place where most French kings were subsequently anointed and crowned, continuing the religious legitimation tradition that Clotilde's influence on Clovis initiated. The basilica represents the Catholic Church's recognition of Clotilde's role in France's foundational religious transformation.",
        "causes": ["Clotilde's role in Clovis I's 496 CE Christian baptism at Reims — foundational event of French national Catholic identity", "Reims's special status as baptismal and coronation city of France requiring church dedicated to its founding saint", "Catholic Church's recognition of Clotilde's missionary role among Germanic kingdoms through canonization", "Reims Cathedral's coronation tradition making the entire city a site of French royal religious history"],
        "effects": ["Clotilde's conversion of Clovis enabling Frankish Catholic alliance with Rome against Arian Christianity", "Reims as baptismal and coronation city of France tracing its sacred status directly to Clotilde's influence", "Frankish Catholic kingdom's long-term consequences including Charlemagne's Holy Roman Empire", "French national Catholic identity's foundational narrative rooted in Clotilde's quiet missionary influence"],
        "relationships": [{"entity": "Clotilde", "relationship": "DEDICATED_TO_FOUNDER_OF_FRANKISH_CHRISTIANITY", "note": "The basilica honors Clotilde whose influence on Clovis's 496 CE baptism was pivotal for European Christian history"}, {"entity": "Clovis I", "relationship": "CONVERSION_FACILITATED_BY_SAINT_COMMEMORATED_IN", "note": "Clotilde's persistent influence led to Clovis's baptism at Reims, making the Frankish kingdom Catholic"}, {"entity": "Reims Cathedral", "relationship": "STANDS_IN_CITY_WHOSE_SACRED_STATUS_WAS_INITIATED_BY", "note": "Reims's coronation and baptism status as France's holy city began with Clotilde's facilitation of Clovis's 496 CE baptism"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Basilica of Sainte-Clotilde de Reims — honoring the queen whose conversion of Clovis I made the Franks Catholic and transformed European religious history, standing in the city whose sacred status she created — is historically meaningful as a monument to one of the most consequential royal conversions in Western history.", "significanceCategory": "continental"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 124 — Class 341 Cathedrals VI: Toledo + Nancy Churches")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
