#!/usr/bin/env python3
"""Batch 109 — Class 342 Mosques IV: Global Mosques (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/342-Class-342"
FILE_PREFIX = "342"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("al-nabi-mosque", {
        "summary": "Al-Nabi Mosque (Mosque of the Prophet) in Sana'a, Yemen, one of the oldest mosques in the world, traditionally believed to have been founded by the Prophet Muhammad himself c. 628 CE — making it among the earliest mosques established during the Islamic expansion into Yemen under the Prophet's emissary Muadh ibn Jabal. The mosque stands in the historic old city of Sana'a, itself a UNESCO World Heritage Site since 1986 for its extraordinary ensemble of tower houses and ancient Islamic architecture.\n\nSana'a's old city contains over 100 mosques, 12 hammams, and 6,500 multi-story tower houses with unique architectural decorations, and Al-Nabi Mosque is the most historically significant among them — its association with the Prophet's personal religious missions to Yemen making it a site of pilgrimage and reverence. The mosque's current structure, while restored and rebuilt over centuries, preserves its ancient sacred significance.\n\nYemen's early Islamic history (Islam spread to Yemen before Muhammad's death in 632 CE) makes Sana'a one of the oldest continuously Islamic cities in the world; Al-Nabi Mosque's founding tradition places it among the small number of mosques with a direct historical connection to the Prophet's era. The Yemeni civil war (from 2015) and Saudi-led coalition airstrikes have damaged parts of Sana'a's historic district, making documentation and preservation of sites like Al-Nabi Mosque urgent. The mosque remains an active place of worship.",
        "causes": ["c. 628 CE founding tradition linking mosque to Prophet Muhammad's emissary Muadh ibn Jabal in Yemen", "Yemen's early Islamic conversion (pre-632 CE) making Sana'a one of Islam's oldest urban centers", "UNESCO World Heritage designation of Sana'a old city (1986) protecting the architectural ensemble", "Yemeni civil war (2015-) threatening historic Islamic monuments with damage and destruction"],
        "effects": ["One of the earliest mosques established during the Prophet's era making Al-Nabi a key pilgrimage site", "Sana'a old city as UNESCO-protected ensemble preserving over 100 ancient mosques", "Yemen's Islamic heritage documenting the faith's earliest geographic expansion beyond Arabia", "Civil war damage creating urgent preservation crisis for one of Islam's oldest urban Islamic ensembles"],
        "relationships": [{"entity": "Muadh ibn Jabal", "relationship": "TRADITIONALLY_ESTABLISHED_BY_EMISSARY", "note": "The mosque is traditionally linked to Muadh ibn Jabal, the Prophet's emissary to Yemen c. 628 CE"}, {"entity": "UNESCO World Heritage", "relationship": "LOCATED_IN_DESIGNATED_SITE", "note": "Al-Nabi Mosque stands in Sana'a old city, UNESCO World Heritage Site since 1986"}, {"entity": "Early Islam", "relationship": "FOUNDING_ERA_MOSQUE_OF", "note": "Al-Nabi's founding tradition places it among the few mosques with a direct Prophet-era historical connection"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Al-Nabi Mosque in Sana'a — one of Islam's oldest mosques with a founding tradition linking it to the Prophet's era, located in a UNESCO World Heritage old city now under civil war threat — is a monument at the intersection of Islam's earliest history and the urgent preservation crisis in Yemen.", "significanceCategory": "world-changing"},
    }),
    ("baitul-mukarram-national-mosque", {
        "summary": "Baitul Mukarram (House of the Noble, or National Mosque of Bangladesh) in Dhaka, completed in 1968 — designed in a modernist interpretation of the Kaaba's cubic form by the Bangladeshi architects Tabith ul Islam and others, with a concrete exterior modeled on the holy Kaaba in Mecca — is the national mosque of Bangladesh, capable of holding 30,000 worshippers, and a symbol of Bangladeshi national religious identity that was constructed during the final decade of Pakistan's rule over East Pakistan (now Bangladesh).\n\nThe mosque's design is distinctive in the history of Islamic architecture: its cubic form consciously evokes the Kaaba (the holy structure at the center of Masjid al-Haram in Mecca that Muslims face in prayer), making it one of the few mosques worldwide that uses the Kaaba's geometric form as its architectural model. This theological-architectural statement — placing a Kaaba-form structure in Dhaka — was an assertion of East Pakistan's Islamic identity during a period of political tension with West Pakistan.\n\nBangladesh's independence (1971), achieved through the Liberation War against Pakistan, transformed the mosque's symbolism: built as a Pakistani national mosque, it became a symbol of Bangladeshi national identity and the most important mosque in the world's third-largest Muslim-majority country. The mosque hosts the second-largest congregation in Bangladesh for Eid prayers (after national Eid grounds) and serves as a center for Islamic scholarship and national religious ceremonies.",
        "causes": ["1960s construction during Pakistani rule of East Pakistan as assertion of Islamic identity", "Tabith ul Islam's design consciously modeling the mosque on the cubic form of the Kaaba in Mecca", "Bangladesh Liberation War (1971) transforming the mosque from Pakistani to Bangladeshi national symbol", "National mosque status making Baitul Mukarram the center of Bangladeshi state Islamic ceremonies"],
        "effects": ["Kaaba-form design as one of the few mosques worldwide using the holy Kaaba as architectural model", "National mosque status as primary site for Bangladeshi state Islamic ceremonies and Eid prayers", "30,000-capacity congregation making it Bangladesh's largest urban mosque", "Symbol of Bangladeshi Muslim identity through both Pakistani era and post-independence national life"],
        "relationships": [{"entity": "Kaaba", "relationship": "ARCHITECTURALLY_MODELED_ON", "note": "Baitul Mukarram's cubic design consciously evokes the Kaaba's form — unique in global mosque architecture"}, {"entity": "Bangladesh Liberation War", "relationship": "POLITICAL_CONTEXT_TRANSFORMED_BY", "note": "1971 independence transformed the mosque from a Pakistani to a Bangladeshi national symbol"}, {"entity": "Bangladesh", "relationship": "NATIONAL_MOSQUE_OF", "note": "Baitul Mukarram serves as Bangladesh's national mosque, hosting state Islamic ceremonies"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Baitul Mukarram — Bangladesh's national mosque designed with the unique Kaaba-form architecture, built during Pakistani rule and transformed into a Bangladeshi national symbol by the 1971 Liberation War — represents both architectural innovation and the intersection of Islamic identity with national independence.", "significanceCategory": "continental"},
    }),
    ("ghana-national-mosque", {
        "summary": "The National Mosque of Ghana in Accra, officially opened in 2004 — built with funding from the Islamic Development Bank and designed to accommodate 15,000 worshippers, with a capacity for an additional 20,000 in its courtyard — is one of West Africa's largest mosques and a symbol of Ghana's growing Muslim community (approximately 18-20% of Ghana's 32 million people) and of the strengthening ties between Ghana and the broader Islamic world, particularly the Gulf states and the OIC.\n\nGhana's Muslim community has deep historical roots: Islam entered the region that is now northern Ghana via trans-Saharan trade routes from the 14th-15th centuries, and the northern regions of Ghana (Upper East, Upper West, Northern) have Muslim majorities. The National Mosque in Accra represents the emergence of this historically northern Ghanaian Muslim tradition into the capital's public life and national symbolism.\n\nThe mosque's construction, funded by the Islamic Development Bank (IDB) with additional support from Muslim-majority states, is part of a broader pattern of Gulf-funded mosque construction across sub-Saharan Africa that has both strengthened Muslim communities' physical infrastructure and raised questions about the spread of more conservative Wahhabi/Salafi Islamic practices alongside the financial support. Ghana's tradition of religious tolerance (Christianity and Islam have coexisted peacefully) makes the National Mosque a symbol of Ghana's pluralistic religious landscape.",
        "causes": ["Islamic Development Bank funding enabling construction of a major national mosque in Accra", "Ghana's 18-20% Muslim population requiring a national-level mosque in the capital", "Historical roots of Islam in northern Ghana via 14th-15th century trans-Saharan trade routes", "Gulf states' mosque-funding programs strengthening Muslim communities across sub-Saharan Africa"],
        "effects": ["15,000-capacity mosque with 20,000 courtyard providing West Africa's major Islamic gathering space in Accra", "National mosque as symbol of Ghanaian Muslim community's national-level presence in the capital", "Gulf-funded construction representing broader Gulf Islamic soft power across sub-Saharan Africa", "Ghana's pluralistic religious model (Christian-Muslim coexistence) exemplified by national mosque presence"],
        "relationships": [{"entity": "Islamic Development Bank", "relationship": "FUNDED_BY", "note": "The IDB provided primary funding for Ghana's National Mosque construction"}, {"entity": "Ghana", "relationship": "NATIONAL_MOSQUE_OF", "note": "The mosque serves as Ghana's official national mosque, hosting state Islamic ceremonies"}, {"entity": "Trans-Saharan Trade Routes", "relationship": "HISTORICAL_ROOTS_OF_ISLAM_VIA", "note": "Islam entered northern Ghana via trans-Saharan trade routes in the 14th-15th centuries"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "Ghana's National Mosque — representing the national presence of Ghana's historically rooted Muslim community, funded by Islamic Development Bank as part of Gulf soft power in Africa, and a symbol of Ghana's religious pluralism — reflects the growing prominence of Islam in West African national life.", "significanceCategory": "regional"},
    }),
    ("kapitan-keling-mosque", {
        "summary": "Kapitan Keling Mosque in George Town, Penang, Malaysia, built c. 1800 by Cauder Mohudeen — a wealthy Indian Muslim merchant and the first 'Kapitan Keling' (captain/headman of the Indian Muslim community in Penang) appointed by the British East India Company — is the oldest and most historically significant mosque in Penang and one of the most architecturally distinctive mosques in Southeast Asia, blending Mughal, Indian, and British colonial architectural styles.\n\nThe mosque's architectural syncretism reflects the multicultural history of Penang: founded in 1786 by Francis Light of the British East India Company, Penang attracted Indian Muslim, Chinese, Malay, and European settlers. The mosque served the large South Indian Muslim (Tamil Muslim/Chuliah) merchant community that formed an important segment of Penang's early commercial elite. The term 'Kapitan Keling' reflects the British colonial practice of appointing ethnic community leaders ('kapitans') to administer their communities.\n\nGeorge Town, Penang — including Kapitan Keling Mosque — was designated a UNESCO World Heritage Site in 2008 as part of the Historic Cities of the Straits of Malacca (shared with Melaka), recognizing George Town's exceptional multicultural heritage as a trading port. The mosque stands in the heart of George Town's 'Little India' district, near the Sri Mahamariamman Temple and the Sri Mahamariamman Kovil, creating one of Southeast Asia's most remarkable concentrations of multicultural religious heritage in a single street.",
        "causes": ["c. 1800 founding by Cauder Mohudeen as the first Kapitan Keling serving the Indian Muslim community", "Penang's British East India Company founding (1786) attracting South Indian Muslim merchants", "Mughal-Indian-British architectural synthesis reflecting Penang's multicultural trading port character", "UNESCO World Heritage designation (2008) protecting George Town's multicultural colonial heritage"],
        "effects": ["Oldest mosque in Penang serving the South Indian Muslim (Tamil Muslim/Chuliah) merchant community", "Architectural syncretism (Mughal, Indian, British) representing Penang's multicultural building tradition", "UNESCO protection of George Town's multicultural heritage including mosque, temples, and colonial buildings", "George Town 'Little India' district as Southeast Asia's most concentrated multicultural religious heritage site"],
        "relationships": [{"entity": "Cauder Mohudeen", "relationship": "FOUNDED_BY", "note": "Cauder Mohudeen, first Kapitan Keling of Penang, built the mosque c. 1800 to serve the Indian Muslim community"}, {"entity": "George Town, Penang", "relationship": "LOCATED_IN_UNESCO_HERITAGE_SITE", "note": "George Town was designated UNESCO World Heritage in 2008 — Kapitan Keling Mosque is a key monument"}, {"entity": "British East India Company", "relationship": "COLONIAL_CONTEXT_OF_FOUNDING", "note": "The British East India Company's founding of Penang (1786) created the multicultural merchant community the mosque served"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Kapitan Keling Mosque — Penang's oldest mosque, an architectural synthesis of Mughal, Indian, and British styles, a monument to South Indian Muslim merchants in colonial Penang, and part of a UNESCO World Heritage Site — is one of Southeast Asia's most historically layered Islamic monuments.", "significanceCategory": "continental"},
    }),
    ("abuja-national-mosque", {
        "summary": "The Nigerian National Mosque (Abuja National Mosque) in Abuja, Nigeria, inaugurated in 1984 — with its distinctive four minarets and golden dome visible from across the new capital city — was one of the first major structures built in Nigeria's planned federal capital Abuja, intended to serve Nigeria's approximately 100 million Muslims (roughly half the country's population, making it Africa's largest Muslim community by absolute numbers) and to symbolize the equal status of Islam and Christianity in Nigeria's secular federal republic.\n\nAbuja itself was a planned capital designed from scratch and built in the 1980s to replace Lagos as Nigeria's capital, chosen for its central location that was intended to reduce ethnic and regional tensions in Africa's most populous country. The National Mosque and the nearby Nigerian National Christian Centre were built simultaneously and placed close together as physical symbols of Nigeria's constitutional commitment to religious equality — a deliberate architectural and political statement in a country where religious tensions (particularly between the predominantly Muslim north and predominantly Christian south) have periodically erupted into violence.\n\nThe mosque's architectural design draws on North African and Middle Eastern mosque traditions adapted to African context, with Saudi Arabian financial support for its construction reflecting Gulf states' investment in West African Islamic infrastructure. The mosque serves as the site of national Islamic prayers on Eid al-Fitr and Eid al-Adha, attended by Nigeria's head of state, and functions as a symbol of the federal government's formal recognition of Islam's place in Nigerian public life.",
        "causes": ["1980s Abuja planned capital construction requiring national mosque and church as symbols of religious equality", "Nigeria's approximately 100 million Muslims (half the population) requiring a national-level mosque", "Saudi Arabian funding reflecting Gulf states' Islamic soft power investment in Nigeria", "Constitutional religious equality principle making simultaneous mosque-church construction a political statement"],
        "effects": ["National mosque serving approximately 100 million Nigerian Muslims — Africa's largest Muslim community by numbers", "Simultaneous mosque-church construction as architectural symbol of Nigerian religious constitutional equality", "Presidential attendance at Eid prayers making the mosque the site of national Islamic state ceremonies", "Gulf-funded construction establishing Saudi/Gulf influence in Nigeria's national religious infrastructure"],
        "relationships": [{"entity": "Nigeria", "relationship": "NATIONAL_MOSQUE_OF", "note": "The Abuja mosque serves Nigeria — home to Africa's largest Muslim community by absolute numbers (~100 million)"}, {"entity": "Nigerian National Christian Centre", "relationship": "SYMBOLIC_PAIR_WITH", "note": "Built simultaneously with the National Christian Centre as architectural symbols of Nigerian religious equality"}, {"entity": "Abuja", "relationship": "FOUNDING_MONUMENT_OF_CAPITAL", "note": "The National Mosque was one of Abuja's first major structures when Nigeria's planned capital was built in the 1980s"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Abuja National Mosque — serving Africa's largest Muslim community, built as a deliberate symbol of Nigerian religious equality alongside the National Christian Centre, and a Gulf-funded assertion of Islamic presence in Africa's most populous country — is a key monument in West African Islamic and political history.", "significanceCategory": "continental"},
    }),
    ("baitul-futuh-mosque", {
        "summary": "Baitul Futuh Mosque (House of Victories) in Morden, London, United Kingdom, inaugurated in 2003 — the largest mosque in Western Europe at time of completion, designed by the Ahmadiyya Muslim Community's in-house architects and built primarily by volunteer labor from the Ahmadiyya community worldwide — is one of the most significant Islamic monuments in the United Kingdom and a symbol of the Ahmadiyya Muslim Community's Western presence and its distinct theological tradition.\n\nThe Ahmadiyya Muslim Community, founded in British India in 1889 by Mirza Ghulam Ahmad (who claimed to be the Mahdi and promised Messiah), is a heterodox Islamic movement considered apostate by mainstream Sunni and Shia Islam but claims approximately 10-20 million followers worldwide. The community has been persecuted in Pakistan (where Ahmadis are legally barred from calling themselves Muslims), Indonesia, and other Muslim-majority countries, making the UK — where they have been free to practice since establishing a presence in the early 20th century — their most important Western base.\n\nBaitul Futuh's construction, with its dome, minarets, and capacity for 10,000 worshippers, represents the Ahmadiyya community's most prominent architectural statement in the West. The mosque complex includes a library, museum, offices, and residential quarters, making it a comprehensive Islamic community center. Its inauguration was attended by 30,000 people from 100 countries, demonstrating the global reach of the Ahmadiyya network centered on their London caliph.",
        "causes": ["Ahmadiyya Muslim Community's Western European headquarters in London requiring a major mosque", "2003 completion representing the community's largest architectural project in the Western hemisphere", "Ahmadiyya persecution in Pakistan and Muslim-majority countries making UK their most important free base", "Volunteer labor from worldwide Ahmadiyya community building the mosque as a collective religious act"],
        "effects": ["Largest mosque in Western Europe at completion — 10,000 capacity — establishing Ahmadiyya architectural presence", "Complex with library, museum, and offices creating a comprehensive Ahmadiyya community center in the UK", "Inauguration by 30,000 people from 100 countries demonstrating global reach of the London-based caliph", "Symbol of Ahmadiyya religious freedom in UK contrasted with persecution in Pakistan and Muslim-majority states"],
        "relationships": [{"entity": "Ahmadiyya Muslim Community", "relationship": "HEADQUARTERS_MOSQUE_OF", "note": "Baitul Futuh is the primary mosque for the Ahmadiyya community's London caliphate headquarters"}, {"entity": "Mirza Ghulam Ahmad", "relationship": "FOUNDER_OF_MOVEMENT_THAT_BUILT", "note": "Baitul Futuh was built by the Ahmadiyya community founded by Mirza Ghulam Ahmad in 1889"}, {"entity": "United Kingdom", "relationship": "LARGEST_MOSQUE_IN_WESTERN_EUROPE", "note": "Baitul Futuh was Western Europe's largest mosque at completion (2003) with 10,000-person capacity"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Baitul Futuh Mosque — Western Europe's largest mosque at completion, headquarters of the Ahmadiyya caliphate in London, built by volunteer community labor, and a symbol of Ahmadiyya religious freedom in the West contrasting with persecution in Muslim-majority states — is the most important Ahmadiyya monument in the Western world.", "significanceCategory": "continental"},
    }),
    ("baitul-aman-mosque", {
        "summary": "Baitul Aman Mosque (House of Peace) in Barisal, Bangladesh, is one of the most architecturally distinctive mosques in Bangladesh — known for its extraordinary dome-heavy design featuring numerous small domes surrounding a central large dome, creating a silhouette unlike any other mosque in the country. Built in the early 21st century with local and diaspora funding, the mosque reflects Bangladesh's thriving tradition of elaborate mosque construction that has accelerated since independence (1971), particularly in smaller cities and towns.\n\nBangladesh is the world's third-largest Muslim-majority country with approximately 150 million Muslims (roughly 90% of the population), and mosque construction has been a prominent form of community investment and piety. The post-independence period has seen extraordinary mosque-building across Bangladesh, from simple rural mosques to elaborate urban structures. Baitul Aman's multi-dome design draws on the Mughal mosque tradition (notably the famous Sixty Dome Mosque at Bagerhat, a UNESCO World Heritage Site) while adapting it to modern construction techniques and materials.\n\nBarisal — the main city of Bangladesh's Barisal Division — is a river delta city surrounded by waterways, and the Baitul Aman Mosque serves as one of the region's major religious landmarks and a gathering point for the substantial Muslim community of southern Bangladesh. The mosque exemplifies how Bangladeshi Islamic architecture has created a distinct regional tradition combining historical Mughal and Indian Islamic influences with modernist construction.",
        "causes": ["Post-independence (1971) Bangladesh mosque-building acceleration as community investment in Islamic identity", "Local and diaspora funding enabling elaborate architectural project beyond government resources", "Mughal multi-dome tradition of Bangladesh (Sixty Dome Mosque of Bagerhat) inspiring modern interpretations", "Barisal's position as major city of southern Bangladesh requiring prominent regional mosque"],
        "effects": ["Multi-dome architectural design creating Bangladesh's most visually distinctive regional mosque", "Regional landmark serving the southern Bangladeshi Muslim community of Barisal Division", "Demonstration of Bangladeshi diaspora investment in hometown religious and cultural infrastructure", "Continuation of Mughal-influenced mosque architecture tradition in modern Bangladeshi Islamic buildings"],
        "relationships": [{"entity": "Bangladesh", "relationship": "LOCATED_IN", "note": "Baitul Aman serves the Muslim community of Barisal, Bangladesh — the world's third-largest Muslim-majority country"}, {"entity": "Sixty Dome Mosque", "relationship": "ARCHITECTURAL_TRADITION_INSPIRED_BY", "note": "Baitul Aman's multi-dome design draws on the UNESCO-listed Sixty Dome Mosque of Bagerhat tradition"}, {"entity": "Mughal Architecture", "relationship": "ARCHITECTURAL_TRADITION_OF", "note": "The mosque adapts the Mughal multi-dome mosque tradition to modern Bangladeshi construction"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "Baitul Aman Mosque — a distinctive multi-dome regional landmark in Bangladesh combining Mughal architectural heritage with modern construction, representing post-independence Bangladeshi mosque-building culture and diaspora investment in homeland religious infrastructure — reflects the vitality of Islamic architectural tradition in South Asia.", "significanceCategory": "local"},
    }),
    ("abu-al-hassan-al-marini-mosque", {
        "summary": "The Abu al-Hassan Mosque (Mosque of Abu al-Hassan) in Salé, Morocco, built c. 1341 CE by Abu al-Hassan Ali ibn Othman — the Black Sultan, Marinid sultan of Morocco (r. 1331-1351) — is one of the finest examples of Marinid Islamic architecture in Morocco, a dynasty that produced some of the most exquisite medieval Islamic monuments including the Bou Inania Madrasa in Fez (1355 CE). Abu al-Hassan was the most powerful Marinid sultan, extending his rule briefly over all of the Maghreb and al-Andalus.\n\nAbu al-Hassan (the Black Sultan, so called because his mother was a Sub-Saharan African slave) was renowned as both a military conqueror and a great patron of Islamic art and architecture. Under his reign, Moroccan-Andalusian artistic production reached its peak: the intricate stucco, zellij (geometric tilework), and carved cedarwood that characterize Marinid architecture were brought to their highest technical refinement. His mosque in Salé exemplifies this tradition.\n\nSalé — across the Bou Regreg River from Rabat — was one of medieval Morocco's most important cities, and the Abu al-Hassan mosque is one of its most significant Islamic monuments. The mosque's mihrab, minaret, and decorative program demonstrate the sophisticated synthesis of Moroccan, Andalusian, and Eastern Islamic artistic traditions that characterize Marinid art at its peak. Abu al-Hassan's reign, though ultimately ended by defeat at the Battle of Taghaza (1347) and the Black Death, represents the Marinid dynasty's golden age.",
        "causes": ["c. 1341 CE construction by Abu al-Hassan at the height of Marinid political power over the entire Maghreb", "Marinid architectural patronage tradition producing Morocco's finest medieval Islamic monuments", "Salé's importance as a major medieval Moroccan city requiring a great royal mosque", "Abu al-Hassan's personal piety and architectural patronage defining his legacy beyond military conquests"],
        "effects": ["Mosque as finest example of Marinid architectural synthesis of Moroccan, Andalusian, and Eastern Islamic arts", "Zellij, stucco, and cedarwood decorative program at the peak of Marinid technical refinement", "Monument to Abu al-Hassan's golden age before Black Death and military reverses ended Marinid power", "Preservation of Marinid architectural tradition in Salé alongside major monuments in Fez and Meknes"],
        "relationships": [{"entity": "Abu al-Hassan Ali ibn Othman", "relationship": "BUILT_BY", "note": "The Black Sultan (r. 1331-1351) built the mosque at the height of Marinid power c. 1341 CE"}, {"entity": "Marinid Dynasty", "relationship": "ARCHITECTURAL_MASTERWORK_OF", "note": "The mosque represents Marinid architecture — Morocco's finest medieval Islamic building tradition — at its peak"}, {"entity": "Salé", "relationship": "MAJOR_MEDIEVAL_MONUMENT_OF", "note": "The mosque is one of Salé's most historically significant Islamic monuments from its medieval golden age"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "Abu al-Hassan Mosque in Salé — built at the peak of Marinid power by Morocco's most powerful medieval sultan, representing Moroccan-Andalusian Islamic architecture at its highest refinement — is a masterwork of the tradition that produced Morocco's most beautiful medieval Islamic monuments.", "significanceCategory": "continental"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 109 — Class 342 Mosques IV: Global Mosques")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
