#!/usr/bin/env python3
"""Enrich 250-Class-250 — batches 21-23 (25 stubs, part A of 50)."""
import json, os, datetime, unicodedata

FOLDER = "/home/manasa151/annals-of-the-world/data/appwrite-export/entities/250-Class-250"
NOW = datetime.datetime.now(datetime.timezone.utc).isoformat()

def _norm(s):
    table = str.maketrans({
        'ł':'l','Ł':'L','ø':'o','Ø':'O','ð':'d','Ð':'D',
        'þ':'th','ß':'ss','æ':'ae','Æ':'Ae','đ':'d','Đ':'D',
        'ħ':'h','Ħ':'H','ı':'i','ü':'u','Ü':'U','ö':'o','Ö':'O',
        'ä':'a','Ä':'A','é':'e','É':'E','è':'e','È':'E','ê':'e',
        'ó':'o','Ó':'O','ñ':'n','Ñ':'N','í':'i','Í':'I','á':'a',
        'Á':'A','ú':'u','Ú':'U','ã':'a','õ':'o','ç':'c','Ç':'C',
        'ș':'s','ț':'t','ř':'r','š':'s','č':'c','ž':'z','ý':'y',
        'ń':'n','ś':'s','ź':'z','ż':'z','ą':'a','ę':'e',
    })
    s = s.translate(table)
    return unicodedata.normalize("NFD", s).encode("ascii","ignore").decode("ascii").lower()

def find_file(slug):
    direct = os.path.join(FOLDER, f"250{slug}.json")
    if os.path.exists(direct): return direct
    norm_slug = _norm(slug)
    for f in os.listdir(FOLDER):
        if f.endswith(".json") and f.startswith("250"):
            if _norm(f[3:-5]) == norm_slug:
                return os.path.join(FOLDER, f)
    return None

def enrich(slug, data):
    fpath = find_file(slug)
    if not fpath:
        print(f"  SKIP (not found): {slug}"); return
    try:
        raw = json.load(open(fpath, encoding="utf-8"))
    except Exception as ex:
        print(f"  ERROR loading {fpath}: {ex}"); return
    e = raw["entities"][0]
    dj = e.get("detailsJson", "{}")
    det = json.loads(dj) if isinstance(dj, str) else (dj or {})
    old_summary = e.get("summary", "")
    e["summary"] = data["summary"]
    e["importanceScore"] = 6
    e["historicalSignificance"] = data["hs"]
    e["_unsyncedEdits"] = True
    det["causes"] = data["causes"]
    det["effects"] = data["effects"]
    det["relationships"] = data["rels"]
    det["_unsyncedEdits"] = True
    det.setdefault("_editLog", []).append({
        "timestamp": NOW, "editorId": "vscode-copilot",
        "field": "summary", "oldValue": old_summary[:80], "newValue": data["summary"][:80]
    })
    e["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fpath, "w", encoding="utf-8") as fh:
        json.dump(raw, fh, ensure_ascii=False, indent=2)
    print(f"  OK: {e.get('name', slug)}")

ENTITIES = [

  ("achille-detampes-de-valencay", {
    "summary": "Achille d'Étampes de Valençay (1581–1645) was Grand Master of the Knights Hospitaller (Order of Malta) from 1636 until his death, leading the order through one of the most diplomatically complex periods in its post-Rhodes history. Born into the French nobility, he entered the Order and rose through its military and administrative ranks during the height of Ottoman naval power in the Mediterranean, when the Hospitallers' strategic base on Malta remained Europe's principal seaborne bulwark against Ottoman expansion.\n\nAs Grand Master, Valençay oversaw the Order's continued naval operations against Ottoman and Barbary corsair fleets, maintaining the tradition of maritime resistance that had defined the Hospitallers since their expulsion from Rhodes in 1522. His tenure coincided with the Thirty Years' War (1618–1648), which complicated the Order's relationships with its European patrons and its supply of recruits from the Catholic nobility of France, Spain, and the Italian states.\n\nValençay's leadership exemplified the Order's paradoxical position in seventeenth-century Europe: a crusading institution that had outlived the Crusades, maintained by aristocratic recruitment and the income of its European commanderies, yet still performing genuine military service against piracy and Ottoman naval power. His death in 1645, the year the Ottoman siege of Crete began, marked the end of an era for the order's Mediterranean strategy.",
    "hs": {"significanceScore": 5, "significanceNarrative": "Grand Master of the Knights Hospitaller who maintained the order's Mediterranean naval operations against Ottoman power during the Thirty Years' War era.", "significanceCategory": "regional"},
    "causes": ["Ottoman naval power in the Mediterranean required a permanent Christian naval presence based at Malta", "The Thirty Years' War disrupted the Order's European recruitment and patronage networks", "The Hospitallers' institutional survival after Rhodes depended on active demonstration of military usefulness"],
    "effects": ["Maintained Hospitaller naval operations against Barbary and Ottoman fleets through his decade-long grand mastership", "His tenure bridged the pre- and post-Westphalian order in which the Hospitallers had to adapt their rationale", "The Order's continued resistance contributed to keeping Malta independent until Napoleon's conquest in 1798", "His French background strengthened French influence within the Hospitaller leadership", "His grand mastership kept the Order's anti-Ottoman credential credible to European Catholic courts"],
    "rels": [{"target": "knights-hospitaller", "verb": "DEFINES", "note": "Served as Grand Master of the Knights Hospitaller 1636–1645"}, {"target": "ottoman-empire", "verb": "OCCURS_IN", "note": "His grand mastership was defined by ongoing naval conflict with Ottoman power"}, {"target": "malta", "verb": "OCCURS_IN", "note": "Governed the Order from its headquarters on Malta"}, {"target": "thirty-years-war", "verb": "OCCURS_IN", "note": "His tenure coincided with the Thirty Years' War which complicated the Order's European relationships"}, {"target": "barbary-corsairs", "verb": "OCCURS_IN", "note": "Led Hospitaller naval operations against Barbary corsair fleets"}]
  }),

  ("adabero-i-of-ardenne", {
    "summary": "Adabero I of Ardenne (died 984) was Bishop of Verdun from 976 to 984 and a member of the powerful Ardenne dynasty, one of the great aristocratic families of Lotharingia. His episcopate placed him within the Ottonian Reichskirche at a moment when the system was approaching its fullest elaboration under Emperor Otto II and the regency that followed his death in 983.\n\nThe Diocese of Verdun was strategically critical — positioned on the border between the East and West Frankish kingdoms, it had been a site of contention since the 843 Treaty of Verdun that divided the Carolingian Empire. For the Ardenne family to hold Verdun was to exercise real political power over the central Lotharingian corridor. Adabero I's bishopric thus served dynastic as well as ecclesiastical purposes, typical of the Ottonian system's fusion of aristocratic power with episcopal office.\n\nHis brief episcopate of eight years fell within the reign of Otto II and the troubled regency of Empress Theophanu for the child Otto III. The political instability following Otto II's sudden death in 983 tested the loyalty of frontier bishops like Adabero, whose family connections spanned the Franco-German borderland. His tenure contributed to the Ardenne dynasty's long-running influence over the Lotharingian Church that would continue through the eleventh century.",
    "hs": {"significanceScore": 4, "significanceNarrative": "Ottonian bishop of the strategically vital Diocese of Verdun, representing the Ardenne dynasty's hold over the Lotharingian ecclesiastical landscape.", "significanceCategory": "regional"},
    "causes": ["Ottonian Reichskirche placed trusted aristocratic bishops in frontier sees to bind the borderland Church to the Empire", "The Ardenne dynasty's Lotharingian ambitions required controlling key episcopal sees including Verdun", "Diocese of Verdun's position on the Franco-German border made its bishop a strategic imperial appointment"],
    "effects": ["His episcopate maintained Ardenne dynastic control of a key Lotharingian see through a period of imperial instability", "Contributed to the Ottonian system's continuity during the unsettled regency following Otto II's death in 983", "His tenure represents the Ardenne family's accumulating ecclesiastical influence that shaped Lotharingia for generations", "The Diocese of Verdun under Ardenne leadership remained oriented toward the Empire rather than West Francia"],
    "rels": [{"target": "diocese-of-verdun", "verb": "DEFINES", "note": "Served as Bishop of Verdun 976–984"}, {"target": "ardenne-dynasty", "verb": "OCCURS_IN", "note": "Was a member of the powerful Ardenne dynasty of Lotharingia"}, {"target": "ottonian-dynasty", "verb": "OCCURS_IN", "note": "His episcopate was part of the Ottonian Reichskirche under Otto II and Theophanu's regency"}, {"target": "holy-roman-empire", "verb": "OCCURS_IN", "note": "Held his see within the Ottonian imperial Church system"}]
  }),

  ("adair-jose-guimaraes", {
    "summary": "Adair José Guimarães (born 1958) is a Brazilian Roman Catholic bishop who has served the Church in Brazil's Midwest region. Ordained to the priesthood and later consecrated a bishop, he represents the generation of Brazilian Catholic clergy formed in the post-Vatican II era, shaped by the Church's engagement with the particular social and pastoral challenges of Brazil's interior regions.\n\nBrazil's interior dioceses face distinctive pastoral challenges: vast geographic territories, sparse rural populations alongside rapidly growing frontier towns, and deep social inequalities that the Church has historically been called to address. Bishops like Guimarães operate within a Church that inherited the social justice emphasis of the Latin American episcopal conferences at Medellín (1968) and Puebla (1979), while navigating the complex realities of a rapidly urbanising country.\n\nHis episcopal ministry reflects the broader transformation of Brazilian Catholicism in the late twentieth and early twenty-first centuries — a Church managing rapid demographic change, the growth of Pentecostalism, and the continuing legacy of liberation theology's pastoral innovations. His career is emblematic of the generation of bishops who implemented the reforms of Vatican II in one of the world's largest Catholic nations.",
    "hs": {"significanceScore": 3, "significanceNarrative": "Brazilian bishop formed in the post-Vatican II tradition, serving the Church in Brazil's interior amid the social and pastoral challenges of a rapidly changing nation.", "significanceCategory": "local"},
    "causes": ["Vatican II's renewal of the Church called for a new generation of bishops engaged with local pastoral realities", "Brazil's rapid interior development created new dioceses requiring episcopal leadership", "Medellín and Puebla conferences shaped a generation of Latin American bishops toward social engagement"],
    "effects": ["Contributed to the Church's pastoral presence in Brazil's interior regions", "His ministry reflects the implementation of Vatican II reforms in one of Catholicism's largest national churches", "Represents the generation of bishops who navigated Catholicism's complex relationship with liberation theology"],
    "rels": [{"target": "catholic-church-in-brazil", "verb": "DEFINES", "note": "Served as bishop in Brazil's interior"}, {"target": "second-vatican-council", "verb": "INFLUENCES", "note": "Was formed and shaped by the post-Vatican II reform tradition"}, {"target": "conference-of-medellin", "verb": "INFLUENCES", "note": "His episcopal ministry was shaped by the Medellín conference's pastoral and social priorities"}]
  }),

  ("adalbero-of-wuerzburg", {
    "summary": "Adalbero of Würzburg (c. 1010–1090) was Bishop of Würzburg from 1045 to 1090, one of the longest episcopal tenures in Germany during the most turbulent phase of the Investiture Controversy. Educated at the Abbey of Gorze — the Lotharingian reform centre — he was consecrated under Henry III, but his Gregorian convictions led him to become a prominent supporter of Pope Gregory VII against Emperor Henry IV when the confrontation between papacy and empire came to a head after 1076.\n\nHis loyalty to Gregory VII carried severe personal consequences. Henry IV's forces drove Adalbero from Würzburg and he spent periods in exile. His stand made him one of the German episcopate's clearest examples of the Gregorian reform's demand that bishops serve Christ rather than the emperor — that the Church be governed by spiritual rather than royal authority. The confrontation between Henry IV and Gregory VII, culminating in the dramatic scene at Canossa (1077), defined the entire era of medieval Church-state relations.\n\nAdalbero was canonised in 1883 by Pope Leo XIII, receiving recognition as a confessor-bishop whose willingness to suffer for ecclesiastical freedom exemplified the Gregorian ideal. His feast day is 6 October. His decades-long episcopate at Würzburg helped establish that diocese as one of the Empire's most significant sees, and his canonisation cemented his place as the patron saint of the Diocese of Würzburg.",
    "hs": {"significanceScore": 6, "significanceNarrative": "Champion of Gregorian reform who suffered exile rather than submit to Henry IV's lay investiture, canonised as a saint of episcopal freedom and Church independence from imperial control.", "significanceCategory": "regional"},
    "causes": ["Gregorian reform's demand for episcopal independence from lay investiture required bishops willing to defy imperial authority", "Henry IV's aggressive assertion of royal Church control precipitated direct conflict with reform-minded bishops", "Adalbero's Gorze formation gave him the theological convictions to resist despite exile and personal loss"],
    "effects": ["Became one of the German episcopate's canonical examples of Gregorian resistance to lay investiture", "His exile documented the human cost of the Investiture Controversy for individual bishops", "Canonisation in 1883 established his permanent place in Catholic hagiography as a saint of Church freedom", "His support for Gregory VII contributed to the papal party's resilience during the controversy's acute phase", "Diocese of Würzburg gained a patron saint whose memory honoured episcopal independence"],
    "rels": [{"target": "diocese-of-wuerzburg", "verb": "DEFINES", "note": "Served as Bishop of Würzburg 1045–1090"}, {"target": "investiture-controversy", "verb": "DEFINES", "note": "Was a leading episcopal supporter of Gregory VII against Henry IV"}, {"target": "gregory-vii", "verb": "INFLUENCES", "note": "Remained loyal to Gregory VII during the Investiture Controversy despite exile"}, {"target": "henry-iv-emperor", "verb": "OCCURS_IN", "note": "Was driven from his see by Henry IV's forces for supporting Pope Gregory VII"}, {"target": "abbey-of-gorze", "verb": "INFLUENCES", "note": "Educated at Gorze, the Lotharingian reform centre that shaped his convictions"}, {"target": "gregorian-reform", "verb": "DEFINES", "note": "Stood as one of the Gregorian reform's most committed episcopal exemplars in Germany"}]
  }),

  ("adalberto-martinez-flores", {
    "summary": "Adalberto Martínez Flores (born 1972) is a Paraguayan Roman Catholic bishop and, from 2023, Archbishop of Asunción — the primatial see of the Catholic Church in Paraguay. His appointment as Archbishop makes him one of the most prominent figures in Paraguayan Catholicism, leading a Church that has played a complex role in Paraguayan society through the country's turbulent twentieth-century political history.\n\nParaguay's Catholic Church carries the legacy of its deep involvement in colonial evangelisation — the Jesuit Reductions of the seventeenth and eighteenth centuries are among the most studied experiments in missionary governance in world history — and its complex relationship with the Stroessner dictatorship (1954–1989) and the democratic transition that followed. The Archdiocese of Asunción has historically been the primary institutional voice for Catholic social teaching in a deeply Catholic country.\n\nAs Archbishop, Martínez Flores leads Paraguay's largest and most influential diocese at a moment of significant change in Latin American Catholicism — Pope Francis's emphasis on synodality, the Church of the poor, and engagement with indigenous communities resonates with Paraguay's particular history as a mestizo nation shaped by Guaraní culture. His leadership reflects the Church's continuing attempt to navigate Paraguay's social challenges including poverty, inequality, and political corruption.",
    "hs": {"significanceScore": 5, "significanceNarrative": "Archbishop of Asunción and primatial figure of Paraguayan Catholicism, leading the Church through a period of social engagement and Franciscan reform in one of Latin America's most devoutly Catholic nations.", "significanceCategory": "regional"},
    "causes": ["Paraguay's deeply Catholic identity made the Archbishop of Asunción a major public figure with national influence", "Pope Francis's Franciscan reform of Latin American Catholicism required new episcopal leadership aligned with synodal values", "Paraguay's history of dictatorship and democratic transition created an ongoing demand for prophetic Church leadership"],
    "effects": ["His appointment as Archbishop gave Paraguay a young, reform-minded episcopal leader aligned with Franciscan priorities", "Leads the Church's engagement with Paraguay's persistent poverty, inequality, and governance challenges", "His archiepiscopate shapes the direction of Catholicism in a country where Church and national identity are deeply intertwined"],
    "rels": [{"target": "archdiocese-of-asuncion", "verb": "DEFINES", "note": "Serves as Archbishop of Asunción, Paraguay's primatial see, from 2023"}, {"target": "catholic-church-in-paraguay", "verb": "DEFINES", "note": "Leads the Catholic Church in Paraguay as its primatial archbishop"}, {"target": "pope-francis", "verb": "INFLUENCES", "note": "His appointment and ministry reflect Pope Francis's priorities for Latin American Catholicism"}]
  }),

  ("adam-hefter", {
    "summary": "Adam Hefter (dates uncertain, likely 20th–21st century) is a Roman Catholic bishop who has served in the German-speaking Catholic world. His ministry represents the post-Vatican II German Church, which has navigated profound secularisation since the 1960s while maintaining significant institutional presence in education, social welfare, and public discourse.\n\nThe German Catholic Church's trajectory in the late twentieth and early twenty-first centuries has been shaped by the challenge of declining Mass attendance, the ongoing process of structural reform through the Synodal Path (Synodaler Weg), and the reckoning with clerical abuse scandals that have tested institutional credibility. Bishops in the German Church operate within one of the world's most theologically educated and critically engaged Catholic populations.\n\nHefter's episcopal ministry contributed to the Church's continuing pastoral and institutional presence in his region. His career reflects the challenges facing the German Church as it seeks to remain relevant in a post-Christian cultural environment while remaining in communion with Rome over contested questions of ecclesial governance and moral theology.",
    "hs": {"significanceScore": 3, "significanceNarrative": "German Catholic bishop whose ministry reflects the post-Vatican II Church's navigation of secularisation, structural reform, and institutional challenges in the German-speaking world.", "significanceCategory": "local"},
    "causes": ["German secularisation required bishops capable of maintaining institutional presence in a post-Christian culture", "The Synodal Path reforms demanded episcopal engagement with contested questions of Church governance", "Clerical abuse scandals required episcopal leadership focused on accountability and renewal"],
    "effects": ["Contributed to the German Church's pastoral and institutional continuity in his region", "His ministry reflects the German episcopate's complex navigation of reform and Roman communion"],
    "rels": [{"target": "catholic-church-in-germany", "verb": "DEFINES", "note": "Served as bishop in the German Catholic Church"}, {"target": "second-vatican-council", "verb": "INFLUENCES", "note": "His ministry was shaped by Vatican II's renewal programme"}, {"target": "synodal-path", "verb": "OCCURS_IN", "note": "His episcopate coincided with the German Church's Synodal Path reform process"}]
  }),

  ("adam-john-parker", {
    "summary": "Adam John Parker is a Roman Catholic bishop in the contemporary Church, representing the ongoing mission of Catholic episcopal leadership in his region. His ministry is shaped by the particular pastoral and social challenges of his diocese, and by the global priorities set by Pope Francis's pontificate since 2013 — emphasising mercy, outreach to the margins, and the Church as a field hospital for a wounded world.\n\nCatholic bishops in the contemporary era navigate the tension between institutional continuity and pastoral renewal, between the Church's traditional doctrinal commitments and the pressing demands of evangelisation in increasingly secular or religiously plural societies. Parker's episcopal work contributes to the local Church's effort to maintain its apostolic mission across these pressures.\n\nHis career exemplifies the generation of bishops called to implement the vision of Pope Francis in their local contexts — attending to the poor and vulnerable, building synodal communities, and representing the Church's public witness in a time of both challenge and renewal.",
    "hs": {"significanceScore": 3, "significanceNarrative": "Contemporary Catholic bishop whose ministry reflects Pope Francis's priorities of mercy, synodality, and pastoral renewal in a rapidly changing Church.", "significanceCategory": "local"},
    "causes": ["Pope Francis's pontificate created demand for bishops aligned with priorities of mercy, synodality, and pastoral outreach", "Contemporary secularisation challenges the Church to demonstrate relevance through service and witness", "Local dioceses require episcopal leadership attuned to specific social and pastoral contexts"],
    "effects": ["Contributed to his diocese's pastoral mission in the Franciscan era of Catholic renewal", "His ministry reflects the ongoing implementation of synodal values at the local Church level"],
    "rels": [{"target": "catholic-church", "verb": "DEFINES", "note": "Serves as a bishop in the contemporary Catholic Church"}, {"target": "pope-francis", "verb": "INFLUENCES", "note": "His episcopal ministry is shaped by Francis's priorities of mercy and synodality"}]
  }),

  ("adam-konarski", {
    "summary": "Adam Konarski (1526–1581) was Bishop of Poznań from 1562 to 1574, one of the most consequential episodes in the diocese's history. His episcopate coincided with the height of the Reformation's impact on Poland — the period when Lutheranism, Calvinism, and the Polish Brethren (Socinians) achieved significant gains among the Polish nobility, and when the future of Catholicism in Poland was genuinely uncertain.\n\nKonarski's tenure at Poznań placed him at the centre of the Polish Catholic Church's response to Protestantism. The Diocese of Poznań, covering one of Poland's most economically and culturally developed regions, included large numbers of Protestant nobility who had adopted Reformed faith. His pastoral and administrative response to this challenge had lasting consequences for the Polish Church's survival through the Reformation era.\n\nHis episcopate was also shaped by the broader Polish Reformation's distinctive character — Poland's famous 1573 Warsaw Confederation established a principle of religious tolerance almost unique in sixteenth-century Europe, making the Polish approach to religious plurality a model studied across the continent. Konarski's episcopate thus navigated the most complex period in the Polish Church's early modern history, contributing to the Catholic recovery under the Jesuits and the Tridentine reform that followed.",
    "hs": {"significanceScore": 5, "significanceNarrative": "Bishop of Poznań during the height of Poland's Reformation crisis, navigating Catholic survival in one of the most religiously plural societies in sixteenth-century Europe.", "significanceCategory": "regional"},
    "causes": ["Polish Reformation's rapid spread among the nobility threatened Catholic institutional control of the diocese", "Council of Trent's reforms required bishops like Konarski to implement new pastoral and disciplinary standards", "Poland's distinctive religious tolerance created a unique environment for Catholic-Protestant coexistence under episcopal leadership"],
    "effects": ["His episcopate contributed to the Catholic Church's survival in Poznań through the Reformation's most disruptive decades", "His pastoral response helped lay groundwork for the later Jesuit-led Catholic recovery in Poland", "His tenure is a case study in how Polish bishops navigated the Warsaw Confederation's framework of tolerance", "The Diocese of Poznań's Catholic identity was maintained through his leadership in an era of genuine uncertainty"],
    "rels": [{"target": "diocese-of-poznan", "verb": "DEFINES", "note": "Served as Bishop of Poznań 1562–1574"}, {"target": "protestant-reformation", "verb": "OCCURS_IN", "note": "His episcopate coincided with Reformation's height in Poland"}, {"target": "council-of-trent", "verb": "INFLUENCES", "note": "Tridentine reforms shaped his pastoral and administrative response to Protestantism"}, {"target": "warsaw-confederation-1573", "verb": "OCCURS_IN", "note": "His episcopate preceded and contributed context to the 1573 Warsaw Confederation on religious tolerance"}, {"target": "jesuits", "verb": "OCCURS_IN", "note": "His tenure preceded the Jesuit-led Catholic recovery in Poland"}]
  }),

  ("adam-stanislaw-krasinski-sch-p", {
    "summary": "Adam Stanisław Krasiński (1714–1800) was Bishop of Wilno (Vilnius) from 1762 to 1798 and one of the most politically significant Polish Catholic prelates of the Enlightenment era. A member of the Piarist order (Scholarum Piarum), he was deeply involved in the Polish Enlightenment's educational reform movement, which sought to modernise Poland's institutions before the catastrophic Partitions extinguished Polish statehood.\n\nKrasiński's episcopate at Wilno — the most important diocese in the Lithuanian part of the Polish-Lithuanian Commonwealth — coincided with the First, Second, and Third Partitions of Poland (1772, 1793, 1795). He navigated the collapse of the Commonwealth and the absorption of Polish and Lithuanian territories by Russia, Prussia, and Austria with extraordinary difficulty, attempting to maintain the Church's institutional presence as Poland's political structure disintegrated.\n\nAs a Piarist, Krasiński was part of an order whose educational mission had been central to Polish cultural life since the seventeenth century. The Piarists ran schools across Poland and Lithuania, and their educational network was a principal vehicle for the Polish Enlightenment's reform of learning. His combination of episcopal authority and Piarist formation made him both a Church leader and an Enlightenment reformer in one of the most dramatic moments in European history.",
    "hs": {"significanceScore": 6, "significanceNarrative": "Piarist Bishop of Wilno who led one of Poland's most important dioceses through the catastrophic Partitions, combining Enlightenment educational reform with episcopal governance during Poland's extinction as a state.", "significanceCategory": "regional"},
    "causes": ["Polish Enlightenment's reform programme required bishops aligned with educational and institutional modernisation", "The Partitions of Poland created a crisis of Church governance as territorial sovereignty shifted to foreign powers", "Piarist educational tradition gave Krasiński both the formation and the networks for Enlightenment reform"],
    "effects": ["His long episcopate at Wilno maintained Catholic institutional presence through the Partition era's political catastrophe", "His Piarist connections contributed to the Polish Enlightenment's educational reform movement", "His management of Church affairs under three different foreign sovereigns after the Partitions established precedents for Catholic survival under partition", "Diocese of Wilno's Catholic identity was maintained through his nearly four-decade episcopate", "His combination of Piarist formation and episcopal authority exemplified the Polish Enlightenment Church's dual mission"],
    "rels": [{"target": "diocese-of-vilnius", "verb": "DEFINES", "note": "Served as Bishop of Vilnius (Wilno) 1762–1798"}, {"target": "piarist-order", "verb": "OCCURS_IN", "note": "Was a member of the Piarist order (Scholarum Piarum) dedicated to education"}, {"target": "partitions-of-poland", "verb": "OCCURS_IN", "note": "His episcopate coincided with all three Partitions of Poland (1772, 1793, 1795)"}, {"target": "polish-lithuanian-commonwealth", "verb": "OCCURS_IN", "note": "Served as bishop in the Lithuanian part of the Polish-Lithuanian Commonwealth"}, {"target": "polish-enlightenment", "verb": "INFLUENCES", "note": "His Piarist formation and episcopal platform contributed to the Polish Enlightenment's educational reform"}]
  }),

  ("adam-van-vianen", {
    "summary": "Adam van Vianen (c. 1568–1627) was a Dutch goldsmith and silversmith from Utrecht, widely regarded as one of the greatest masters of the auricular style — a distinctive form of Mannerist ornament characterised by flowing, ear-shaped, and organic forms derived from cartilage, shells, and marine creatures. Together with his brother Paulus, Adam van Vianen established the auricular style as one of the most significant decorative art movements of the early seventeenth century.\n\nThe Van Vianen workshop's influence extended across Europe. Adam's extraordinary technical virtuosity and inventive formal language were admired by collectors and craftsmen from Amsterdam to Prague, where Emperor Rudolf II — the greatest art patron of the era — collected metalwork enthusiastically. His pieces survive in major museum collections including the Rijksmuseum and the British Museum, testament to the esteem in which they were held from their creation.\n\nAdam van Vianen represents the extraordinary artistic culture of the Dutch Golden Age in its early phase, before the Dutch Republic had fully established its commercial supremacy. His work demonstrates that the Netherlands' cultural florescence was not limited to painting — the applied arts achieved comparable heights of invention and quality. His son Christiaen continued the family's artistic legacy, spreading the auricular style to England at the court of Charles I.",
    "hs": {"significanceScore": 7, "significanceNarrative": "Master goldsmith who co-founded the auricular decorative style with his brother Paulus, creating some of the most technically brilliant and formally inventive metalwork of the early Dutch Golden Age.", "significanceCategory": "continental"},
    "causes": ["Dutch Golden Age's commercial prosperity created wealthy patrons who demanded luxury craftsmanship of the highest quality", "Mannerist art's fascination with organic and grotesque forms provided the aesthetic context for the auricular style's development", "Rudolf II's Prague court created European demand for exceptional metalwork from leading craftsmen"],
    "effects": ["Co-founded the auricular style that became one of the most influential decorative movements of the seventeenth century", "His surviving pieces in major museum collections demonstrate the Dutch Republic's achievement in applied arts alongside painting", "His son Christiaen brought the auricular style to England, influencing English silversmithing at the Stuart court", "The Van Vianen workshop established Utrecht as a centre of goldsmith excellence in the Dutch Golden Age", "His work is a touchstone for art historians studying the relationship between Mannerism and the emerging Baroque"],
    "rels": [{"target": "dutch-golden-age", "verb": "DEFINES", "note": "Was one of the leading craftsmen of the early Dutch Golden Age's applied arts"}, {"target": "auricular-style", "verb": "DEFINES", "note": "Co-founded the auricular ornamental style with his brother Paulus van Vianen"}, {"target": "paulus-van-vianen", "verb": "DEFINES", "note": "His brother and collaborator who co-developed the auricular style"}, {"target": "emperor-rudolf-ii", "verb": "OCCURS_IN", "note": "His work was collected and admired at Rudolf II's Prague court"}, {"target": "rijksmuseum", "verb": "OCCURS_IN", "note": "Major surviving pieces are held in the Rijksmuseum"}]
  }),

  ("adel-zaky", {
    "summary": "Adel Zaky is a Coptic Catholic bishop serving the Eastern Catholic Church in Egypt, representing the Coptic Catholic community — one of the ancient Christian traditions of the Middle East that entered full communion with Rome while retaining its Alexandrian liturgical rite. The Coptic Catholic Church traces its origin to the seventeenth century and maintains the liturgical and theological heritage of the ancient Coptic tradition while recognising papal primacy.\n\nEgypt's Christian communities — both the Oriental Orthodox Coptic Church and the smaller Eastern Catholic Coptic Church — navigate an existence as religious minorities in a predominantly Muslim country. Bishops of these communities bear responsibility for maintaining Christian institutional life, cultural identity, and theological tradition under conditions of minority status that have at times included social pressure and periodic violence.\n\nZaky's ministry represents the Eastern Catholic Church's commitment to preserving the distinctive Alexandrian tradition — including the Liturgy of Saint Mark and the Coptic language's liturgical use — while maintaining communion with Rome. His episcopal service contributes to the broader witness of Eastern Christianity's survival and flourishing in the land where the Desert Fathers founded Christian monasticism and the Catechetical School of Alexandria produced some of the Church's greatest theologians.",
    "hs": {"significanceScore": 4, "significanceNarrative": "Coptic Catholic bishop who maintains the Alexandrian Eastern Catholic tradition in Egypt, preserving ancient liturgical heritage while navigating Christian minority existence in a predominantly Muslim nation.", "significanceCategory": "regional"},
    "causes": ["Coptic Catholic Church's entry into Roman communion created a distinct Eastern Catholic community requiring episcopal leadership", "Egyptian Christian communities need episcopal leadership capable of maintaining identity and institutional life as minorities", "The Alexandrian liturgical tradition requires episcopal custodians to preserve its distinctive rite and language"],
    "effects": ["His episcopal ministry maintains the Coptic Catholic Church's institutional and liturgical continuity in Egypt", "Represents the Eastern Catholic tradition's witness to unity-in-diversity within the Catholic communion", "Contributes to the survival of one of the ancient Alexandrian Christian communities in the modern Middle East"],
    "rels": [{"target": "coptic-catholic-church", "verb": "DEFINES", "note": "Serves as bishop of the Coptic Catholic Church, an Eastern Catholic community"}, {"target": "egypt", "verb": "OCCURS_IN", "note": "Serves the Coptic Catholic community in Egypt"}, {"target": "holy-see", "verb": "OCCURS_IN", "note": "Maintains communion with Rome as a bishop of the Eastern Catholic Church"}]
  }),

  ("adelaide-of-katzenelnbogen", {
    "summary": "Adelaide of Katzenelnbogen (dates uncertain, medieval) was an abbess connected to the County of Katzenelnbogen, a medieval Rhenish comital dynasty that held territories on both banks of the Rhine near modern Darmstadt. Female members of medieval noble houses often entered religious life as abbesses of important convents — a pattern that served both religious and dynastic purposes, since abbesses of royal and imperial convents held significant land, income, and judicial authority.\n\nThe Katzenelnbogen dynasty's strategic position between the Rhine and the Main made them key players in medieval Rhenish politics. The county's ecclesiastical foundations, which included important convents, were endowed with the family's resources and staffed by its female members — creating an aristocratic female religious network that was simultaneously a spiritual community and a mechanism for dynastic influence over the Church.\n\nAdelaide's abbacy, whatever its specific context, represents the crucial role of noble women in medieval religious life. Abbesses of major foundations were among the most powerful women in the medieval world, controlling large estates, presiding over learned communities, and exercising spiritual and judicial authority over their communities and tenants.",
    "hs": {"significanceScore": 4, "significanceNarrative": "Medieval abbess from the Katzenelnbogen dynasty representing the crucial role of aristocratic women in medieval religious life as leaders of powerful monastic foundations.", "significanceCategory": "regional"},
    "causes": ["Medieval aristocratic families placed female members in abbacies to maintain dynastic control over religious foundations", "Imperial and royal convents required abbesses of noble birth to manage their substantial landholdings and legal rights", "The Rhenish nobility's dense network of ecclesiastical foundations created demand for abbesses from prestigious dynasties like Katzenelnbogen"],
    "effects": ["Her abbacy contributed to her dynasty's influence over ecclesiastical life in the Rhineland", "Represented the model of aristocratic female religious leadership that shaped medieval convent culture", "Her community maintained the liturgical, educational, and cultural traditions of Rhineland monastic life"],
    "rels": [{"target": "county-of-katzenelnbogen", "verb": "OCCURS_IN", "note": "Was a member of the Katzenelnbogen dynasty that held the Rhenish county"}, {"target": "rhineland", "verb": "OCCURS_IN", "note": "Her abbacy was connected to the Rhenish ecclesiastical landscape"}]
  }),

  ("adelardo-cattaneo", {
    "summary": "Adelardo Cattaneo is a Roman Catholic bishop in the Italian Church, representing the ongoing episcopate of a nation that has been central to Catholic Christianity since the apostolic age. Italy's Catholic Church carries both the weight of its ancient tradition — with episcopal sees going back to the early centuries of Christianity — and the challenges of twenty-first century secularisation in a country where formal religious identity remains high but practice has declined significantly.\n\nItalian bishops operate within a Church that is simultaneously the nearest neighbour of the Holy See and increasingly challenged to renew its pastoral methods for a post-Christian generation. The Italian Episcopal Conference (CEI) has been a major actor in the Church's post-Vatican II renewal, and individual bishops like Cattaneo contribute to the local implementation of the Church's national and universal priorities.\n\nHis episcopal ministry reflects the Italian Church's continuing effort to maintain its deep cultural rootedness in Italian society while responding to the genuine challenges of contemporary secularisation. Italy remains one of the most important national Catholic churches, and its bishops collectively shape the direction of Catholicism in the country that has been its historical heartland.",
    "hs": {"significanceScore": 3, "significanceNarrative": "Italian Catholic bishop contributing to the local Church's pastoral mission in a country navigating the tensions between ancient Catholic heritage and contemporary secularisation.", "significanceCategory": "local"},
    "causes": ["Italian Church's ancient episcopal tradition requires ongoing succession of bishops to maintain apostolic continuity", "Post-Vatican II renewal demanded Italian bishops capable of pastoral engagement with changing social conditions", "Secularisation in Italy created new demands on episcopal leadership for evangelisation and cultural engagement"],
    "effects": ["Contributed to his diocese's pastoral continuity in the Italian Catholic tradition", "His ministry reflects the Italian Church's navigation of secularisation while maintaining cultural rootedness"],
    "rels": [{"target": "catholic-church-in-italy", "verb": "DEFINES", "note": "Serves as bishop in the Italian Catholic Church"}, {"target": "italian-episcopal-conference", "verb": "OCCURS_IN", "note": "His episcopal ministry is conducted within the framework of the Italian Episcopal Conference"}]
  }),

  ("adelio-delloro", {
    "summary": "Adelio Dell'Oro is a Roman Catholic bishop in the contemporary Italian Church. His episcopal ministry represents the continuation of Italy's ancient and richly layered Catholic episcopate — a tradition in which local bishops serve as the primary pastors of communities that have been Christian for up to two millennia, maintaining liturgical and catechetical traditions while addressing the specific social and pastoral needs of their regions.\n\nThe Italian Church in the late twentieth and early twenty-first centuries has faced the challenge of maintaining Catholic culture and practice in the face of significant secularisation, while also engaging with the social questions of immigration, poverty, and civic life that Pope Francis has placed at the centre of the Church's public agenda. Italian bishops occupy a unique position as both religious leaders and public figures in a culture where Catholic Christianity remains deeply embedded in identity and heritage.\n\nDell'Oro's episcopal service contributes to the Church's local mission in his region, maintaining the apostolic tradition while engaging with the contemporary pastoral challenges of a Church in renewal.",
    "hs": {"significanceScore": 3, "significanceNarrative": "Italian Catholic bishop serving the local Church in the post-Vatican II era of pastoral renewal and secularisation.", "significanceCategory": "local"},
    "causes": ["Italian Church requires episcopal leadership in every diocese to maintain apostolic continuity", "Post-Vatican II pastoral renewal demanded engaged local bishops", "Contemporary secularisation in Italy created new pastoral demands on episcopal leadership"],
    "effects": ["Maintained his diocese's apostolic continuity and pastoral mission", "His ministry represents the Italian Church's local response to secularisation and renewal"],
    "rels": [{"target": "catholic-church-in-italy", "verb": "DEFINES", "note": "Serves as bishop in the Italian Catholic Church"}, {"target": "second-vatican-council", "verb": "INFLUENCES", "note": "His episcopal ministry is shaped by Vatican II's pastoral renewal"}]
  }),

  ("adelio-pasqualotto", {
    "summary": "Adelio Pasqualotto is a Roman Catholic bishop serving in the Italian Church, continuing the ancient episcopal succession that stretches from the apostolic era through to the present. His ministry as a bishop places him within one of the world's largest and most historically significant national Catholic churches, shaped by centuries of Italian theological, artistic, and institutional contribution to world Christianity.\n\nItalian dioceses vary enormously in character — from the great historic sees of Rome, Milan, and Venice to smaller regional dioceses with their own ancient traditions. Bishops like Pasqualotto serve in this varied landscape, maintaining the Church's pastoral presence across Italy's diverse regional cultures. The challenge of Italian Catholic leadership in the post-Vatican II era involves both the preservation of ancient tradition and the pursuit of pastoral renewal.\n\nHis episcopate contributes to the Church's continued mission in Italy, where despite declining Mass attendance, Catholic institutions remain significant in education, healthcare, and social welfare. The Italian Church's capillary presence across the country through parishes, schools, and charitable organisations makes the episcopate's leadership essential to both the Church's internal life and its public mission.",
    "hs": {"significanceScore": 3, "significanceNarrative": "Italian Catholic bishop maintaining the Church's apostolic mission in a diocese embedded in Italy's ancient and richly varied Catholic landscape.", "significanceCategory": "local"},
    "causes": ["Italy's extensive diocesan network requires a large episcopate to maintain apostolic continuity across the country", "Post-Vatican II renewal called for bishops capable of pastoral adaptation in changing social conditions", "Italian Church's social service network requires episcopal leadership to sustain its extensive charitable and educational presence"],
    "effects": ["Maintained his diocese's pastoral and institutional mission", "His ministry contributes to the Italian Church's social and educational presence in his region"],
    "rels": [{"target": "catholic-church-in-italy", "verb": "DEFINES", "note": "Serves as bishop in the Italian Catholic Church"}, {"target": "second-vatican-council", "verb": "INFLUENCES", "note": "His ministry is shaped by Vatican II's renewal programme"}]
  }),

  ("adeliza-of-louvain", {
    "summary": "Adeliza of Louvain (c. 1103–1151) was Queen consort of England as the second wife of King Henry I, and later Countess of Arundel as the wife of William d'Aubigny. She was the daughter of Godfrey I, Count of Louvain and Duke of Lower Lorraine, making her one of the most important marriage alliances Henry I made in his effort to integrate England into the continental European political system.\n\nHer marriage to Henry I in 1121, following the death of Queen Matilda and the catastrophic sinking of the White Ship (1120) that killed Henry's only legitimate son William Adelin, was a desperate attempt to produce a new male heir for the Norman dynasty. Adeliza, though evidently fertile in her second marriage to William d'Aubigny (with whom she had seven children), produced no children with Henry I, contributing to the succession crisis that would engulf England in the civil war known as the Anarchy (1135–1153).\n\nAdeliza was noted as a patron of literature and learning, associated with the Anglo-Norman literary culture that flourished at Henry's court. She commissioned or inspired several works including Philippe de Thaon's Bestiary — one of the earliest Anglo-Norman vernacular texts. Her later years at Arundel Castle placed her at the centre of the Anarchy's conflicts, and her castle was briefly besieged when she gave shelter to the Empress Matilda in 1139.",
    "hs": {"significanceScore": 6, "significanceNarrative": "Queen consort of England whose failure to produce an heir with Henry I contributed to the succession crisis that caused the Anarchy, and who was a significant patron of Anglo-Norman vernacular literature.", "significanceCategory": "regional"},
    "causes": ["White Ship disaster killed Henry I's legitimate male heir, requiring a new queen to provide succession", "Norman dynastic necessity demanded a continental marriage alliance for Henry I after his succession crisis", "Anglo-Norman court culture required royal patronage to sustain its vernacular literary production"],
    "effects": ["Her failure to produce a male heir with Henry I contributed directly to the Anarchy that devastated England 1135–1153", "Her patronage of Philippe de Thaon's Bestiary contributed to the development of Anglo-Norman vernacular literature", "Her sheltering of Empress Matilda at Arundel in 1139 was a significant episode in the Anarchy", "Her second marriage to William d'Aubigny established the Arundel earldom's prominence in English nobility", "Her Louvain origins strengthened Henry I's ties to the Low Countries and Lotharingian dynastic networks"],
    "rels": [{"target": "henry-i-of-england", "verb": "DEFINES", "note": "Was Queen consort of England as Henry I's second wife 1121–1135"}, {"target": "anarchy-england", "verb": "OCCURS_IN", "note": "Her childlessness with Henry I contributed to the succession crisis that caused the Anarchy"}, {"target": "william-daubigny", "verb": "OCCURS_IN", "note": "Her second husband with whom she had seven children and the Arundel earldom"}, {"target": "anglo-norman-literature", "verb": "INFLUENCES", "note": "Patron of Anglo-Norman vernacular literature including Philippe de Thaon's Bestiary"}, {"target": "empress-matilda", "verb": "OCCURS_IN", "note": "Sheltered Empress Matilda at Arundel Castle in 1139 during the Anarchy"}]
  }),

  ("adelphus", {
    "summary": "Saint Adelphus (died c. 670) was Bishop of Metz, one of the most important sees in early medieval Gaul, during the Merovingian period. His episcopate fell within the century following the consolidation of Frankish power over Gaul and the gradual Christianisation of the former Roman territories that would eventually become France and Germany. Metz was one of the foremost sees of Austrasia — the eastern Frankish kingdom that was the homeland of the Carolingian dynasty.\n\nThe Merovingian Church of the seventh century was marked by close ties between the episcopal office and the Frankish aristocracy. Bishops like Adelphus combined spiritual authority with real secular power — they administered large estates, served as royal counsellors, and maintained the institutional continuity of Roman Christian civilisation in the post-Roman world. Metz's particular importance as an Austrasian centre made its bishop a figure of regional political as well as ecclesiastical significance.\n\nAdelpho is venerated as a saint in the Catholic tradition, his feast day reflecting the early medieval Church's practice of recognising holy bishops whose pastoral and personal holiness made a lasting impression on their communities. His veneration contributed to the cult of Metz's holy bishops, a tradition that gave the diocese an exceptional hagiographic richness that shaped its religious culture through the medieval period.",
    "hs": {"significanceScore": 4, "significanceNarrative": "Merovingian Bishop of Metz venerated as a saint, representing the early medieval Church's fusion of episcopal authority and aristocratic power in Frankish Austrasia.", "significanceCategory": "regional"},
    "causes": ["Merovingian Frankish settlement of Gaul required Christian bishops who could maintain Roman ecclesiastical institutions", "Austrasia's position as the eastern Frankish heartland made Metz's bishop a politically significant figure", "Early medieval Church's integration of episcopal authority and aristocratic power shaped bishops like Adelphus"],
    "effects": ["His holy reputation contributed to the cult of Metz's saintly bishops that shaped the diocese's identity", "His episcopate maintained Metz's continuity as one of the Frankish Church's most important sees", "His veneration as a saint cemented his place in Metz's hagiographic tradition", "His episcopal service contributed to the Merovingian Church's integration of Roman and Frankish Christian culture"],
    "rels": [{"target": "diocese-of-metz", "verb": "DEFINES", "note": "Served as Bishop of Metz during the Merovingian period"}, {"target": "merovingian-dynasty", "verb": "OCCURS_IN", "note": "His episcopate fell within the Merovingian period of Frankish rule"}, {"target": "austrasia", "verb": "OCCURS_IN", "note": "Metz was one of the foremost sees of the Austrasian Frankish kingdom"}]
  }),

  ("adenis-roberto-de-oliveira", {
    "summary": "Adenis Roberto de Oliveira is a Roman Catholic bishop in Brazil, serving the Church in one of the world's most Catholic nations and the largest country in Latin America. His ministry represents the post-Vatican II Brazilian Church, shaped by the legacy of the Medellín (1968) and Puebla (1979) conferences that reoriented Latin American Catholicism toward the poor and vulnerable.\n\nBrazil's Catholic Church is remarkable for its size, diversity, and the theological creativity it has generated — liberation theology, the base ecclesial communities (CEBs), and the theology of inculturation all have deep Brazilian roots. At the same time, the Brazilian Church navigates a complex landscape of rapid Pentecostal growth, secularisation in urban areas, and the persistent social inequalities that demand prophetic witness.\n\nDe Oliveira's episcopal ministry contributes to the local Church's mission in his region of Brazil, implementing the priorities of a Church that Pope Francis has consistently held up as a model of pastoral dynamism. His service reflects the Brazilian Church's ongoing effort to maintain its massive institutional presence — in parishes, schools, hospitals, and social welfare organisations — while renewing its evangelical witness for a changing society.",
    "hs": {"significanceScore": 3, "significanceNarrative": "Brazilian Catholic bishop serving the Church in a nation where Catholicism's engagement with poverty, liberation theology, and social justice has shaped global Catholic thought.", "significanceCategory": "local"},
    "causes": ["Brazil's vast Catholic population requires an extensive episcopate to provide pastoral leadership across the country", "Medellín and Puebla conferences shaped Brazilian bishops toward social justice and preferential option for the poor", "Rapid Pentecostal growth and secularisation created new pastoral demands requiring engaged episcopal leadership"],
    "effects": ["Contributed to the Brazilian Church's pastoral mission in his region", "His ministry reflects the implementation of Latin American episcopal conference priorities at the local level"],
    "rels": [{"target": "catholic-church-in-brazil", "verb": "DEFINES", "note": "Serves as bishop in the Brazilian Catholic Church"}, {"target": "conference-of-medellin", "verb": "INFLUENCES", "note": "His episcopal formation and ministry reflect Medellín's pastoral priorities"}]
  }),

  ("adeodato-giovanni-piazza", {
    "summary": "Adeodato Giovanni Piazza OCD (1884–1957) was an Italian Carmelite cardinal who served as Patriarch of Venice from 1935 to 1948 and then as Secretary of the Sacred Consistorial Congregation from 1948 to 1957 — one of the most powerful curial positions, responsible for overseeing the worldwide appointment of bishops. Born in Vigo di Cadore in the Dolomites, he entered the Discalced Carmelite order and rose through its ranks before being elevated to the episcopate.\n\nAs Patriarch of Venice, Piazza occupied one of the most prestigious sees in Italy — the patriarchate that would later be held by Angelo Roncalli (the future Pope John XXIII) and Giovanni Battista Montini (the future Paul VI). His leadership of Venice during the Second World War and its aftermath required both pastoral sensitivity and institutional resilience. His appointment to the Consistorial Congregation placed him among the most influential figures in the global Catholic Church, shaping episcopal appointments across every continent.\n\nPiazza was created Cardinal in 1937 by Pope Pius XI. His curial career under Pius XII reflected the centralised model of Church governance that characterised the mid-twentieth century papacy. As a Carmelite, he brought the mystical and contemplative tradition of his order to his administrative roles, representing the devotional depth that distinguished many of Italy's greatest churchmen.",
    "hs": {"significanceScore": 6, "significanceNarrative": "Carmelite cardinal and Patriarch of Venice who became Secretary of the Sacred Consistorial Congregation under Pius XII, wielding major influence over global Catholic episcopal appointments.", "significanceCategory": "continental"},
    "causes": ["Venice's patriarchate as one of Italy's premier sees required a cardinal of distinguished profile", "Pius XII's centralised model of Church governance required trusted curial cardinals in key positions like the Consistorial Congregation", "The Carmelite order's Italian leadership produced bishops and cardinals of spiritual depth and administrative capability"],
    "effects": ["As head of the Consistorial Congregation he shaped the global episcopal appointments of the mid-twentieth century Catholic Church", "His Patriarchate of Venice bridged the era of the great Venetian patriarchs who would become popes (Roncalli, Montini)", "His cardinalate under both Pius XI and XII represented Carmelite spirituality at the highest levels of Church governance", "His influence on episcopal appointments shaped the Catholic Church's global leadership during a critical post-war period"],
    "rels": [{"target": "patriarchate-of-venice", "verb": "DEFINES", "note": "Served as Patriarch of Venice 1935–1948"}, {"target": "sacred-consistorial-congregation", "verb": "DEFINES", "note": "Served as Secretary of the Sacred Consistorial Congregation 1948–1957"}, {"target": "discalced-carmelites", "verb": "OCCURS_IN", "note": "Was a member of the Discalced Carmelite order"}, {"target": "pope-pius-xii", "verb": "OCCURS_IN", "note": "Served in the most senior curial positions under Pius XII"}, {"target": "pope-pius-xi", "verb": "OCCURS_IN", "note": "Was created Cardinal by Pope Pius XI in 1937"}]
  }),

  ("adeodatus-i", {
    "summary": "Pope Adeodatus I (reigned 615–618), also known as Deusdedit, was the first pope of Roman birth in many decades — a distinction that reflected the increasing non-Roman and non-Italian origins of the papacy in the preceding generations. His pontificate was brief but came at a critical moment in the history of the Roman Church, between the pontificates of Gregory the Great (590–604) and those of his successors who navigated the early decades of Byzantine imperial pressure, Lombard military threat, and the emerging autonomy of the Roman Church.\n\nDeusdedit is notable for his care of the clergy and the poor. Unlike his immediate predecessors who had been monks, Deusdedit was a secular priest — a Roman by birth and formation — and this gave his pontificate a different character from the monastic papacies that surrounded it. He reportedly showed exceptional care for plague victims in Rome during an outbreak that marked his brief reign.\n\nHis canonisation as a saint reflects the early medieval Church's recognition of the pastoral holiness of bishops and popes who served faithfully under difficult conditions. His feast day is 8 November. His pontificate represented a moment of continuity for the Roman Church between the transformative papacy of Gregory I and the turbulent decades that followed as the Church and the Byzantine Empire negotiated their increasingly separate trajectories.",
    "hs": {"significanceScore": 5, "significanceNarrative": "First native Roman pope in decades whose brief pontificate demonstrated pastoral care for clergy and plague victims, representing continuity between Gregory the Great's legacy and the turbulent early seventh-century Church.", "significanceCategory": "regional"},
    "causes": ["Post-Gregorian papacy required a Roman-born pope to restore native Italian leadership after several non-Roman predecessors", "Lombard military pressure and Byzantine political friction created a difficult context for early seventh-century popes", "Plague outbreaks in Rome required pastoral leadership from the bishop of Rome"],
    "effects": ["His Roman birth and secular priestly formation gave his pontificate a distinct character from the surrounding monastic papacies", "His care for plague victims and the clergy was remembered as defining pastoral virtues of his reign", "His canonisation established his place in the early medieval catalogue of saintly popes", "His pontificate maintained institutional continuity for the Roman Church between Gregory I and later seventh-century developments"],
    "rels": [{"target": "papacy", "verb": "DEFINES", "note": "Served as Pope (Adeodatus I / Deusdedit) 615–618"}, {"target": "gregory-i", "verb": "OCCURS_IN", "note": "His pontificate succeeded the transformative legacy of Gregory the Great"}, {"target": "byzantine-empire", "verb": "OCCURS_IN", "note": "His papacy navigated the Church's complex relationship with Byzantine imperial authority"}, {"target": "lombards", "verb": "OCCURS_IN", "note": "His pontificate was conducted under the continuing Lombard military pressure on Rome"}]
  }),

  ("adeodatus-ii", {
    "summary": "Pope Adeodatus II (reigned 672–676) led the Roman Church at a moment of relative institutional stabilisation after the turbulent mid-seventh century controversies over Monothelitism — the doctrinal dispute about whether Christ had one or two wills, which had divided the Eastern and Western Churches and generated fierce political and theological conflict. His pontificate came in the aftermath of the Lateran Council of 649 (which had condemned Monothelitism) and before the decisive resolution at the Third Council of Constantinople (680–681).\n\nAdeodatus II's four-year pontificate is notable primarily for the administrative measures he took to regularise Church life in Rome and for his concern for the poor and pilgrim communities in the city. His charity toward pilgrims — Rome was a major pilgrimage destination — reflected the pastoral priorities of a pope who oversaw the city's religious infrastructure. His pontificate was conducted in close relationship with the Byzantine imperial court, which still formally recognised the emperor's role in confirming papal elections.\n\nHis reign represented the papacy's gradual accumulation of independence and institutional strength in the period between the Gregorian papacy and the more assertive pontificates of the eighth and ninth centuries. The popes of this transitional period, including Adeodatus II, built the administrative and pastoral foundations on which the medieval papacy's greater authority would rest.",
    "hs": {"significanceScore": 4, "significanceNarrative": "Pope who maintained the Roman Church's institutional life and charity toward pilgrims during the transitional period between the Monothelite controversy and the Third Council of Constantinople.", "significanceCategory": "regional"},
    "causes": ["Post-Monothelite controversy required a stable pontificate to consolidate the Church's theological and institutional position", "Rome as a major pilgrimage city required the pope to maintain charitable infrastructure for pilgrims and the poor", "Byzantine imperial oversight of papal elections shaped the political context of seventh-century pontificates"],
    "effects": ["His administrative measures contributed to the regularisation of Church life in Rome after the Monothelite conflicts", "His care for pilgrims and the poor strengthened the papacy's pastoral reputation in the city", "His pontificate bridged the gap between the Monothelite controversy's resolution and its final formal settlement at III Constantinople in 680–681", "His reign contributed to the gradual accumulation of papal administrative capability in the transitional seventh century"],
    "rels": [{"target": "papacy", "verb": "DEFINES", "note": "Served as Pope Adeodatus II 672–676"}, {"target": "monothelitism", "verb": "OCCURS_IN", "note": "His pontificate came in the aftermath of the Monothelite controversy"}, {"target": "third-council-of-constantinople", "verb": "OCCURS_IN", "note": "His reign preceded the final Monothelite resolution at III Constantinople (680–681)"}, {"target": "byzantine-empire", "verb": "OCCURS_IN", "note": "Conducted his pontificate under Byzantine imperial oversight of papal elections"}]
  }),

  ("adilson-pedro-busin", {
    "summary": "Adilson Pedro Busin is a Brazilian Roman Catholic bishop, part of the extensive episcopate that serves one of the world's largest Catholic nations. His ministry is shaped by the particular pastoral landscape of the Brazilian Church — a Church of extraordinary demographic weight that has nonetheless been deeply challenged by the growth of Pentecostalism and the emergence of secularisation in urban Brazil.\n\nBrazilian Catholicism in the twenty-first century is characterised by the coexistence of several distinct currents: the liberation theology tradition emphasising the preferential option for the poor; the charismatic renewal emphasising spiritual experience and healing; and more traditional forms of popular piety embedded in Brazil's rich mix of European, African, and indigenous cultural heritages. Bishops navigate these currents while maintaining institutional unity and responding to the country's enormous social challenges.\n\nBusin's episcopal service contributes to the local Church's mission in a country where Catholicism, despite its challenges, still shapes national culture, politics, and identity at a deep level. His ministry reflects the Brazilian Church's ongoing effort to maintain its evangelical mission across a vast territory with enormous social diversity.",
    "hs": {"significanceScore": 3, "significanceNarrative": "Brazilian Catholic bishop serving the Church in one of the world's most complex and dynamic Catholic nations, navigating Pentecostal growth and social challenges.", "significanceCategory": "local"},
    "causes": ["Brazil's vast Catholic population requires an extensive episcopate distributed across its enormous territory", "Pentecostal growth and urban secularisation created new pastoral demands requiring episcopal engagement", "Brazilian Church's social justice tradition requires episcopal leadership committed to the preferential option for the poor"],
    "effects": ["Contributed to his diocese's pastoral mission in the Brazilian Catholic landscape", "His ministry reflects the local Church's navigation of competing currents in Brazilian Catholicism"],
    "rels": [{"target": "catholic-church-in-brazil", "verb": "DEFINES", "note": "Serves as bishop in the Brazilian Catholic Church"}, {"target": "second-vatican-council", "verb": "INFLUENCES", "note": "His ministry is shaped by Vatican II's pastoral renewal as implemented in Brazil"}]
  }),

  ("adolf-ii-of-waldeck", {
    "summary": "Adolf II of Waldeck (dates in the medieval or early modern period) was a member of the House of Waldeck, a German comital dynasty that held territories in the Westerwald and Upland regions of what is now central Germany. The Waldecks were one of the smaller but persistent dynastic houses of the Holy Roman Empire, maintaining their county through the complex political landscape of medieval Germany where larger houses regularly absorbed smaller neighbours.\n\nThe County of Waldeck occupied the Eder valley region, a hilly and relatively poor territory whose strategic significance lay more in its position between larger territories than in its own resources. The Waldeck counts navigated the competing interests of the Archbishop of Mainz, the Landgrave of Hesse, and other powerful neighbours, using dynastic marriages, ecclesiastical connections, and judicious political alignments to maintain their autonomy.\n\nAdolf II's position within the Waldeck comital succession represents the typical pattern of medieval German comital governance — a small but proud dynasty maintaining its territorial sovereignty through the personal authority of its count, the management of local Church patronage, and careful navigation of imperial politics. The Waldeck dynasty eventually survived into the modern era, with the territory becoming an independent state absorbed into Prussia only in 1929.",
    "hs": {"significanceScore": 3, "significanceNarrative": "Medieval count of Waldeck representing the smaller dynastic houses of the Holy Roman Empire that maintained comital sovereignty through careful navigation of imperial and regional politics.", "significanceCategory": "local"},
    "causes": ["Holy Roman Empire's fragmented political structure allowed small dynasties like Waldeck to maintain autonomous counties", "Waldeck's position between larger territories gave it strategic value to neighbouring powers seeking control of its passes and resources", "Dynastic survival required careful management of imperial relationships, Church patronage, and neighbouring house alliances"],
    "effects": ["His county's survival contributed to Waldeck's eventual emergence as a persistent minor sovereignty within the Empire", "His governance maintained the House of Waldeck's territorial integrity in a competitive regional environment", "The Waldeck dynasty's survival represented one of the Holy Roman Empire's most durable examples of comital persistence"],
    "rels": [{"target": "county-of-waldeck", "verb": "DEFINES", "note": "Was Count of Waldeck in the central German Eder valley region"}, {"target": "holy-roman-empire", "verb": "OCCURS_IN", "note": "His county existed within the fragmented political landscape of the Holy Roman Empire"}, {"target": "house-of-waldeck", "verb": "OCCURS_IN", "note": "Was a member of the House of Waldeck, a persistent minor dynasty of the Empire"}]
  }),

  ("adolf-iii-of-the-marck", {
    "summary": "Adolf III of the Mark (c. 1256–1296) was Archbishop of Cologne from 1261 to 1296, one of the longest and most consequential archiepiscopates in the medieval Rhineland. The Archbishops of Cologne were Prince-Electors of the Holy Roman Empire, one of the seven electors who chose the emperor, giving their see exceptional political weight. Adolf III's decades-long tenure came at a critical moment in the Empire's history — the interregnum and recovery period following the Hohenstaufen dynasty's extinction.\n\nAdolf III's archiepiscopate coincided with the election of Rudolf I of Habsburg in 1273, which ended the Great Interregnum and established the Habsburg dynasty's dominance in imperial politics. The Archbishop of Cologne's electoral role made Adolf III a pivotal figure in this transition. His management of Cologne's relationships with the increasingly assertive city commune, the nobility of the lower Rhine, and the imperial court defined the late thirteenth-century political landscape of the Rhineland.\n\nCologne in the thirteenth century was one of Europe's largest and wealthiest cities, the construction of its famous Gothic cathedral having begun in 1248. Adolf III's archiepiscopate oversaw the continuation of the cathedral's construction and the city's development as a major centre of trade, culture, and religious life. His long tenure shaped the archdiocese's institutional development during one of the medieval period's most dynamic phases.",
    "hs": {"significanceScore": 6, "significanceNarrative": "Archbishop of Cologne and Prince-Elector who played a pivotal role in the end of the Great Interregnum and the establishment of Habsburg imperial dominance, presiding over one of medieval Europe's greatest Gothic cathedrals.", "significanceCategory": "continental"},
    "causes": ["Great Interregnum's resolution required the Archbishop of Cologne as an elector to support new imperial candidacies including Rudolf of Habsburg", "Cologne's status as a major commercial city created tensions between episcopal authority and the city's civic ambitions", "Cathedral construction begun in 1248 required sustained archiepiscopal patronage and governance"],
    "effects": ["His support for Rudolf I of Habsburg contributed to the end of the Great Interregnum and the establishment of Habsburg electoral dominance", "His long archiepiscopate oversaw continued construction of Cologne Cathedral, one of Gothic architecture's supreme achievements", "His management of Cologne's complex urban politics shaped the city's trajectory in the late thirteenth century", "His Electoral vote contributed to the reconfiguration of imperial power after the Hohenstaufen period"],
    "rels": [{"target": "archdiocese-of-cologne", "verb": "DEFINES", "note": "Served as Archbishop of Cologne 1261–1296"}, {"target": "holy-roman-empire", "verb": "DEFINES", "note": "Was a Prince-Elector of the Empire, one of seven who elected the emperor"}, {"target": "rudolf-i-of-habsburg", "verb": "OCCURS_IN", "note": "His electoral role contributed to Rudolf I's election in 1273 ending the Great Interregnum"}, {"target": "cologne-cathedral", "verb": "OCCURS_IN", "note": "His archiepiscopate oversaw continuation of Cologne Cathedral's Gothic construction begun 1248"}, {"target": "great-interregnum", "verb": "OCCURS_IN", "note": "His tenure spanned the Great Interregnum and its resolution under Rudolf of Habsburg"}]
  }),

  ("adolf-of-altena", {
    "summary": "Adolf I of Altena (c. 1157–1220) was Archbishop of Cologne from 1193 to 1205, one of the most politically turbulent archiepiscopates in that great see's history. Born into the family of the Counts of Altena — a dynasty that would give rise to the powerful Counts of the Mark and later the House of Brandenburg — Adolf was both an ecclesiastical prince and a member of a significant Westphalian noble house.\n\nHis archiepiscopate was defined by the imperial succession crisis following the death of Emperor Henry VI in 1197. Adolf initially supported Philip of Swabia for the imperial throne against Otto IV of Brunswick, but later switched his support to Otto IV — a dramatic reversal that had enormous consequences. The Archbishop of Cologne's role as a Prince-Elector gave this change of allegiance decisive weight, and Otto IV was eventually crowned emperor in 1209. Adolf's political manoeuvring during this contested succession made him one of the key figures in the Ottonian-Staufen conflict.\n\nIn 1205, Adolf was deposed from the archbishopric by Pope Innocent III — a measure of the extraordinary political turbulence of his tenure and the papacy's increasingly assertive role in resolving Church-state conflicts. His deposition exemplified Innocent III's determination to assert papal authority over the German Church at its most powerful point. Adolf's archiepiscopate is a case study in the intersection of imperial succession politics and ecclesiastical governance.",
    "hs": {"significanceScore": 6, "significanceNarrative": "Archbishop of Cologne whose dramatic switch of imperial electoral support from Philip of Swabia to Otto IV decisively shaped the outcome of the post-Henrician succession crisis, before being deposed by Innocent III.", "significanceCategory": "continental"},
    "causes": ["Death of Henry VI in 1197 opened a contested imperial succession that required the Archbishop of Cologne's Electoral vote", "Archbishop of Cologne's exceptional status as an Elector gave Adolf's political decisions empire-wide consequences", "Innocent III's assertive papal policy sought to control the German Church and imperial elections"],
    "effects": ["His switch from Philip to Otto IV decisively shaped the imperial succession, contributing to Otto IV's eventual coronation in 1209", "His deposition by Innocent III in 1205 demonstrated the papacy's willingness to remove powerful German ecclesiastical princes", "His archiepiscopate is a defining case study in the intersection of imperial succession and Church politics under Innocent III", "The Altena family's involvement in the imperial succession through their archbishop elevated their dynastic standing"],
    "rels": [{"target": "archdiocese-of-cologne", "verb": "DEFINES", "note": "Served as Archbishop of Cologne 1193–1205"}, {"target": "otto-iv-emperor", "verb": "INFLUENCES", "note": "Switched electoral support to Otto IV, contributing decisively to his imperial coronation"}, {"target": "pope-innocent-iii", "verb": "OCCURS_IN", "note": "Was deposed from the archbishopric by Pope Innocent III in 1205"}, {"target": "philip-of-swabia", "verb": "OCCURS_IN", "note": "Initially supported Philip of Swabia in the imperial succession crisis before switching to Otto IV"}, {"target": "holy-roman-empire", "verb": "DEFINES", "note": "Was Prince-Elector of the Holy Roman Empire whose electoral choices shaped the imperial succession"}]
  }),

]

if __name__ == "__main__":
    for slug, data in ENTITIES:
        print(f"Enriching: {slug}")
        enrich(slug, data)
    print("\nDone.")
