#!/usr/bin/env python3
"""Batch 145 — Class 361 Museums VII: African & Asian State Museums (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/361-Class-361"
FILE_PREFIX = "361"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("borno-state-museum", {
        "summary": "The Borno State Museum is a cultural institution in Maiduguri, the capital of Borno State in northeastern Nigeria — preserving the extraordinary cultural heritage of the ancient Kanem-Bornu Empire, one of the longest-lasting states in African history (approximately 9th century CE to 1900 CE), and documenting the material culture, Islamic scholarship tradition, and archaeological heritage of the Lake Chad Basin civilization that flourished for over a thousand years.\n\nBorno State is historically significant as the heartland of the Kanem-Bornu Empire, which was one of the most sophisticated and enduring states in sub-Saharan Africa — maintaining continuous governance for approximately 1,000 years through multiple ruling dynasties (the Saifawa dynasty, the longest-lived ruling dynasty in recorded African history), establishing significant trade routes connecting sub-Saharan Africa to North Africa and the Mediterranean, and developing a tradition of Islamic scholarship and governance. The city of Maiduguri sits near the ancient capitals of this empire.\n\nIn the modern period, Borno State has become tragically associated with the Boko Haram insurgency (2009-present) — the Islamist terrorist group that began in Maiduguri and has devastated northeastern Nigeria, displacing millions of people and destroying cultural heritage. The Borno State Museum's preservation role has taken on additional urgency as cultural institutions in the region face threats from conflict, with thousands of artifacts representing the ancient Lake Chad Basin civilization at risk from the ongoing insurgency.",
        "causes": ["Kanem-Bornu Empire's 1000-year heritage requiring institutional preservation of material culture in Borno State's capital", "Lake Chad Basin civilization's unique archaeological and cultural significance requiring dedicated museum institution", "Post-independence Nigeria's cultural institution-building creating state museums to preserve regional heritage", "Islamic scholarly tradition of the region requiring documentation and preservation for public education"],
        "effects": ["Museum preserving the material culture of one of Africa's longest-lasting state traditions", "Borno State cultural heritage preservation amid the Boko Haram insurgency threatening northeastern Nigeria", "Ancient Kanem-Bornu artifacts and Islamic manuscripts protected as documentation of Lake Chad civilization", "Cultural institution maintaining historical memory of pre-colonial African state traditions"],
        "relationships": [{"entity": "Kanem-Bornu Empire", "relationship": "PRESERVES_MATERIAL_CULTURE_AND_HERITAGE_OF_ANCIENT", "note": "The Borno State Museum preserves the heritage of the Kanem-Bornu Empire, one of Africa's longest-lasting states"}, {"entity": "Boko Haram", "relationship": "CULTURAL_HERITAGE_THREATENED_BY_INSURGENCY_DEVASTATING_REGION", "note": "The Boko Haram insurgency (2009-present) threatens Borno State's cultural heritage institutions and the region's historical patrimony"}, {"entity": "Maiduguri", "relationship": "LOCATED_IN_CAPITAL_OF_ANCIENT_KANEM-BORNU_HEARTLAND", "note": "The museum is located in Maiduguri, the capital of Borno State in the historical heartland of the Kanem-Bornu Empire"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Borno State Museum — preserving the heritage of one of Africa's longest-lasting empires amid Boko Haram insurgency — is historically significant as a cultural preservation institution facing extraordinary threats in one of the world's most conflict-affected regions.", "significanceCategory": "continental"},
    }),
    ("burundi-national-museum", {
        "summary": "The Burundi National Museum (Musée National du Burundi) in Gitega — Burundi's political capital — is the primary cultural institution of one of Africa's smallest and most densely populated countries, preserving the heritage of the Kingdom of Burundi (a sophisticated centralized monarchy that existed from approximately the 17th century until Belgian colonial incorporation) and documenting the rich material culture, royal court traditions, and ethnic history of a country that has experienced devastating ethnic violence since independence.\n\nBurundi's cultural heritage is inseparable from its tragic modern history: the country achieved independence from Belgian colonial rule in 1962 as a constitutional monarchy under the Ganwa ruling class (the royal lineage connecting Hutu, Tutsi, and Twa aristocratic traditions). The breakdown of this post-colonial settlement led to periodic massacres — the 1972 Burundian Genocide (approximately 200,000-300,000 Hutus killed by the Tutsi-led army), the 1993 assassination of the democratically elected Hutu President Melchior Ndadaye, and the 1993-2005 civil war (approximately 300,000 dead).\n\nThe Burundi National Museum's preservation role extends to documenting the Kingdom of Burundi's sophisticated court traditions — the royal drums (the ingoma), royal genealogies, and court ceremonies that represented the kingdom's governance and cultural achievement before colonialism. The royal drums of Burundi are UNESCO-recognized Intangible Cultural Heritage, reflecting their significance. The museum functions as one of the few institutions maintaining cultural memory of the pre-colonial Burundian kingdom's achievements.",
        "causes": ["Kingdom of Burundi's sophisticated pre-colonial governance requiring museum documentation of royal court traditions", "Post-independence cultural institution-building creating national museums to preserve pre-colonial and colonial-era heritage", "Burundian ethnic conflicts requiring cultural preservation as documentation of shared pre-colonial identity", "UNESCO recognition of royal drums as Intangible Cultural Heritage highlighting significance of cultural preservation"],
        "effects": ["Museum preserving the royal court traditions and material culture of the Kingdom of Burundi", "Royal drums (ingoma) and court ceremonial objects documented as UNESCO Intangible Cultural Heritage", "Cultural institution maintaining historical memory amid Burundi's repeated cycles of ethnic violence", "Gitega capital's museum serving as cultural anchor for post-civil war national reconciliation"],
        "relationships": [{"entity": "Kingdom of Burundi", "relationship": "PRESERVES_HERITAGE_OF_PRE-COLONIAL_MONARCHY", "note": "The museum preserves the material culture and royal traditions of the Kingdom of Burundi's sophisticated pre-colonial governance"}, {"entity": "Royal Drums of Burundi", "relationship": "CUSTODIAN_OF_UNESCO_INTANGIBLE_HERITAGE_INGOMA", "note": "The museum is the custodian of the royal ingoma drums recognized as UNESCO Intangible Cultural Heritage"}, {"entity": "Burundian Ethnic Conflicts", "relationship": "CULTURAL_PRESERVATION_AMID_REPEATED_CYCLES_OF", "note": "The museum maintains cultural memory of pre-colonial shared identity amid Burundi's devastating post-independence ethnic conflicts"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Burundi National Museum — preserving the royal drums and court traditions of the Kingdom of Burundi amid the country's devastating ethnic violence — is historically significant as a cultural preservation institution documenting pre-colonial African kingdom achievement.", "significanceCategory": "continental"},
    }),
    ("cambodian-national-museum", {
        "summary": "The National Museum of Cambodia (Khmer: សារមន្ទីរជាតិ, Phnom Penh) is one of Southeast Asia's most significant cultural institutions — housing the world's finest collection of Khmer art and sculpture, including pieces from the Angkor period (9th-15th centuries CE) when the Khmer Empire was one of Southeast Asia's dominant powers and Angkor Wat was the world's largest religious monument. The museum's terracotta-colored pavilions, built in Khmer style in 1917-1920 (designed by George Groslier under French colonial administration), themselves represent a significant architectural achievement.\n\nThe National Museum's collection spans the entire history of Khmer civilization: pre-Angkorean pieces from the Funan and Chenla kingdoms (1st-8th centuries), Angkorean masterpieces from the empire's height under Jayavarman VII (12th-13th centuries), and post-Angkorean pieces. The most celebrated piece is the Harihara statue from Prasat Andet — a stunning fusion of Vishnu and Shiva that exemplifies the Khmer synthesis of Hindu and Buddhist traditions. Bronze dancing figures, stone lingas, and elaborate bas-relief panels represent the full range of Khmer artistic achievement.\n\nThe museum's 20th-century history reflects Cambodia's catastrophic modern experience: during the Khmer Rouge period (1975-1979), the museum was largely abandoned and some pieces were lost, stolen, or damaged, while the broader Cambodian cultural patrimony was devastated by the genocidal regime that killed approximately 1.5-2 million Cambodians (25% of the population). Post-Khmer Rouge recovery has involved international repatriation efforts to return Khmer artifacts from foreign collections.",
        "causes": ["French colonial administration founding the museum in 1917-1920 to preserve and display Khmer archaeological heritage", "Angkor period's extraordinary artistic achievement requiring institutional preservation and scholarly study", "George Groslier's vision of a museum in authentic Khmer architectural style housing the finest Khmer art collection", "Colonial-era archaeological excavations at Angkor producing artifacts requiring professional museum curation"],
        "effects": ["World's finest Khmer art collection assembled in Phnom Penh as reference for Khmer civilization study", "Khmer Rouge period abandonment causing losses and damage to the collection", "Post-genocide recovery involving international repatriation efforts to return stolen Khmer artifacts", "Museum serving as anchor for Cambodia's post-genocide cultural identity recovery and tourism development"],
        "relationships": [{"entity": "Angkor Khmer Empire", "relationship": "HOUSES_WORLD'S_FINEST_COLLECTION_OF_ART_FROM", "note": "The museum holds the world's finest collection of Khmer art from the Angkor Empire period"}, {"entity": "Khmer Rouge", "relationship": "MUSEUM_ENDANGERED_AND_COLLECTION_DAMAGED_DURING", "note": "The Khmer Rouge period (1975-1979) saw the museum largely abandoned and some collection pieces lost or damaged"}, {"entity": "Harihara Statue Prasat Andet", "relationship": "HOLDS_CELEBRATED_KHMER_MASTERPIECE", "note": "The museum's most celebrated piece is the Harihara statue from Prasat Andet, a stunning Vishnu-Shiva fusion"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The National Museum of Cambodia — housing the world's finest Khmer art collection, surviving the Khmer Rouge, serving post-genocide cultural recovery — is historically significant as the primary custodian of one of Southeast Asia's greatest civilizations' material heritage.", "significanceCategory": "world-changing"},
    }),
    ("cape-verde-national-museum", {
        "summary": "The Cape Verde National Museum (Portuguese: Museu Nacional de Cabo Verde) in Praia is the primary cultural institution of the Cape Verde archipelago — ten volcanic islands in the Atlantic Ocean off West Africa that were uninhabited before Portuguese colonization in the 1460s and subsequently became one of the Atlantic slave trade's most significant transit hubs, creating a unique Creole culture (Kriolu) that blends Portuguese, African, and Atlantic maritime traditions into one of the world's most distinctive post-colonial cultural identities.\n\nCape Verde's cultural uniqueness stems from its historical role as a Portuguese colonial hub and slave trade transit point: Portuguese colonists, freed African slaves, and enslaved Africans from the West African mainland created a mestizo population speaking a distinctive Kriolu language and developing a musical tradition (morna, coladeira) that is among the world's most emotionally distinctive, centered on the concept of saudade (a Portuguese/Kriolu word for melancholic longing). Cesária Évora, the internationally celebrated 'Barefoot Diva,' brought this tradition to global audiences.\n\nCape Verde achieved independence from Portugal in 1975 under the PAIGC/PAICV leadership of Amílcar Cabral's movement (though Cabral was assassinated in 1973), and has since developed into one of Africa's most stable democracies and successful development stories — achieving lower-middle income status and significant human development improvements, making it a model for small island developing states.",
        "causes": ["Portuguese colonization of previously uninhabited islands (1460s) creating a blank-slate colonial culture", "Atlantic slave trade's Cape Verde hub role creating the African-Portuguese-maritime cultural synthesis", "Kriolu language and morna music developing as unique Creole cultural expressions requiring institutional preservation", "Cape Verde independence (1975) requiring national cultural institution to document and preserve unique island heritage"],
        "effects": ["Cape Verde National Museum preserving the unique Creole cultural heritage of Atlantic slave trade-era civilization", "Morna music tradition documented with Cesária Évora's global success raising Cape Verde's cultural profile internationally", "UNESCO inscription of morna as Intangible Cultural Heritage recognizing Cape Verde's unique musical tradition", "Cape Verde's democratic development success documented as model for small island post-colonial states"],
        "relationships": [{"entity": "Atlantic Slave Trade", "relationship": "CULTURAL_HERITAGE_MUSEUM_DOCUMENTING_ISLANDS_SHAPED_AS_TRANSIT_HUB_OF", "note": "Cape Verde's unique culture emerged from its Atlantic slave trade transit hub role, which the museum documents"}, {"entity": "Morna Music", "relationship": "CULTURAL_TRADITION_PRESERVED_AND_DOCUMENTED_WITH_UNESCO_HERITAGE_STATUS", "note": "The museum preserves Cape Verde's morna musical tradition, recognized as UNESCO Intangible Cultural Heritage"}, {"entity": "Cesária Évora", "relationship": "CULTURAL_TRADITION_BROUGHT_TO_GLOBAL_AUDIENCES_BY", "note": "Cape Verde's morna tradition was brought to global audiences by Cesária Évora, the internationally celebrated 'Barefoot Diva'"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "The Cape Verde National Museum — preserving the unique Creole Atlantic heritage created by the slave trade's transit hub — is historically significant as the custodian of one of the world's most distinctive post-colonial cultural identities.", "significanceCategory": "continental"},
    }),
    ("chinese-national-palace-museum", {
        "summary": "The National Palace Museum (國立故宮博物院, Guólì Gùgōng Bówùyùan), located in Taipei, Taiwan — houses one of the world's largest and most important collections of Chinese art and imperial artifacts, containing approximately 700,000 pieces including the treasures of the imperial collection assembled over thousands of years by Chinese emperors, evacuated from Beijing's Palace Museum (Forbidden City) to Taiwan by the Nationalist government in 1948-1949 before the Communist victory in the Chinese Civil War — making the museum's very existence a monument to the unresolved political division of China.\n\nThe collection's extraordinary breadth spans 8,000 years of Chinese civilization: Neolithic jade pieces, Shang Dynasty bronzes (1600-1046 BCE), Zhou Dynasty vessels, Han Dynasty lacquerware, Tang Dynasty ceramics, Song Dynasty paintings (including landscapes by Mi Fu and Fan Kuan), Ming Dynasty porcelains, and Qing Dynasty jade and ivory carvings. The Jade Cabbage (Cuiyu Baicai) and Meat-shaped Stone (Dongpo Pork) are among the most visited pieces — extraordinary feats of jade carving. The emperor Qianlong's personal collection was among the world's greatest individual art collections.\n\nThe museum's political significance is profound: both the government of the Republic of China (Taiwan) and the People's Republic of China (mainland) claim to be the legitimate successor to the Chinese imperial legacy, with the Taiwan-held collection representing one argument for Taiwanese cultural legitimacy as the preserver of Chinese civilization. The question of whether the collection should be returned to mainland China is a politically charged aspect of cross-strait relations.",
        "causes": ["Chinese imperial collection accumulated over thousands of years by successive dynasties requiring institutional preservation", "1948-1949 Nationalist government's evacuation of 600,000+ imperial artifacts to Taiwan from Beijing", "Chinese Civil War outcome forcing the collection's permanent separation from mainland China", "Taipei's National Palace Museum founding (1965) creating permanent home for the evacuated imperial collection"],
        "effects": ["World's largest concentration of Chinese imperial art assembled in Taipei representing 8,000 years of Chinese civilization", "Collection's Taiwan location representing a major cultural legitimacy argument in cross-strait political disputes", "Chinese art scholarship's primary reference collection located in Taipei rather than mainland China", "Museum's most popular pieces (Jade Cabbage, Meat-shaped Stone) becoming global icons of Chinese artistic achievement"],
        "relationships": [{"entity": "Chinese Imperial Collection", "relationship": "HOUSES_TREASURES_ACCUMULATED_ACROSS_THOUSANDS_OF_YEARS_BY", "note": "The museum holds the imperial collection assembled by Chinese emperors across thousands of years of dynastic rule"}, {"entity": "Chinese Civil War", "relationship": "COLLECTION_EVACUATED_TO_TAIWAN_AS_RESULT_OF_NATIONALIST_DEFEAT_IN", "note": "The Nationalist government evacuated the collection to Taiwan in 1948-1949 before losing the Civil War to the Communists"}, {"entity": "Cross-Strait Relations", "relationship": "COLLECTION'S_LOCATION_REPRESENTING_CULTURAL_LEGITIMACY_DIMENSION_OF", "note": "The imperial collection's Taiwan location is a cultural legitimacy argument in the politically charged cross-strait relationship"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The National Palace Museum Taipei — holding the world's greatest Chinese imperial art collection evacuated to Taiwan in the Civil War, its location a monument to China's political division — is historically significant as both the premier repository of Chinese civilization's material heritage and a monument to 20th-century Chinese political history.", "significanceCategory": "world-changing"},
    }),
    ("colombian-national-museum", {
        "summary": "The National Museum of Colombia (Museo Nacional de Colombia) in Bogotá — founded in 1823, making it the oldest museum in the Americas continuously operating since independence — is housed in the remarkable Panóptico building (1874, designed by Thomas Reed), a 19th-century panopticon prison converted to a museum that itself reflects Colombia's complex history of colonial architecture, penal reform, and institutional continuity from the 19th century.\n\nThe National Museum's collection spans pre-Columbian, colonial, and modern Colombian history: the pre-Columbian gold collections document the remarkable Muisca confederation (the Chibcha-speaking people whose legendary El Dorado myth originated from the Muisca ritual of gilded chiefs — zipa and zaque — performing offerings in Lake Guatavita), the Zenú people's goldwork, and other Colombian indigenous civilizations. Colonial-era paintings, Simón Bolívar memorabilia, and 19th-20th century Colombian art round out the collection.\n\nColombia's turbulent modern history is documented through the museum's 19th-20th century collections: the Thousand Days War (1899-1902), the post-1948 La Violencia period (approximately 200,000-300,000 dead in partisan conflict), Pablo Escobar and the drug cartel era, the FARC civil war (approximately 260,000 dead over 50+ years), and the ongoing peace process. The museum navigates Colombian identity in a country that has experienced near-continuous political violence while also producing extraordinary cultural achievements in literature (Gabriel García Márquez, Nobel Prize 1982), art, and music.",
        "causes": ["1823 founding as one of Colombia's first post-independence institutions reflecting republican nation-building cultural agenda", "Pre-Columbian gold heritage requiring institutional preservation of Muisca, Zenú, and other indigenous civilizations' goldwork", "Panóptico building's 1874 construction providing the museum's distinctive architectural home", "Colombian cultural nationalism requiring a national museum as repository of the country's complete historical narrative"],
        "effects": ["Americas' oldest continuously operating post-independence museum maintaining institutional continuity since 1823", "Pre-Columbian Muisca gold collection preserving the heritage that inspired the El Dorado legend", "Panóptico building's conversion from prison to museum documenting the evolution of Colombian institutional architecture", "Colombian history documentation including colonial period, independence, and modern violent political conflicts"],
        "relationships": [{"entity": "Muisca Confederation", "relationship": "PRESERVES_GOLDWORK_HERITAGE_OF_EL_DORADO_LEGEND_SOURCE", "note": "The museum holds the Muisca gold collections whose ritual practices inspired the El Dorado legend"}, {"entity": "Simón Bolívar", "relationship": "HOUSES_LIBERATOR'S_MEMORABILIA_AS_MONUMENT_TO", "note": "The museum contains significant Simón Bolívar memorabilia documenting Colombia's independence hero"}, {"entity": "Colombian History", "relationship": "COMPREHENSIVE_INSTITUTIONAL_DOCUMENTATION_FROM_1823_TO_PRESENT_OF", "note": "The museum documents Colombia's complete history from pre-Columbian times through colonial rule, independence, and modern conflicts"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The National Museum of Colombia — the Americas' oldest post-independence museum, preserving Muisca gold heritage and El Dorado legend sources — is historically significant as a foundational Latin American cultural institution and repository of pre-Columbian and independence-era South American heritage.", "significanceCategory": "world-changing"},
    }),
    ("democratic-republic-of-congo-national-museum", {
        "summary": "The National Museum of the Democratic Republic of Congo (Musée National de la République Démocratique du Congo) in Kinshasa is the primary cultural institution of the DRC — one of Africa's largest and most biodiverse countries and the site of some of the continent's richest pre-colonial cultural traditions — though the museum has faced significant challenges from the DRC's chronic political instability and the devastation of repeated civil wars including the catastrophic Second Congo War (1998-2003, approximately 5 million dead).\n\nThe DRC's cultural heritage is extraordinary: the Kingdom of Kongo (approximately 14th-19th centuries, centered in what is now DRC/Angola/Republic of Congo) developed sophisticated political institutions, distinctive visual arts, and one of Africa's most complex pre-colonial state systems. Kongo art — particularly the minkisi power objects, nkisi nkondi figurines embedded with nails and other materials, and masks — has been globally influential in modern art (Picasso and other cubists were influenced by African art including Kongo pieces). The Luba Empire, Lunda confederacy, and other central African kingdoms developed elaborate visual cultures that are now housed in the museum.\n\nThe massive loss of Congolese cultural heritage through colonial looting — the Belgian Congo under King Leopold II's rule (1885-1908) and the subsequent Belgian colonial administration removed enormous quantities of cultural objects to European museums (the Royal Museum for Central Africa at Tervuren, Belgium holds the world's largest collection of Congolese artifacts) — makes the DRC National Museum's repatriation advocacy particularly important.",
        "causes": ["DRC independence (1960) requiring national museum to preserve and document the country's extraordinary pre-colonial cultural heritage", "Kingdom of Kongo and Luba Empire traditions requiring institutional preservation of their sophisticated visual art traditions", "Belgian colonial looting removing enormous quantities of Congolese cultural objects requiring repatriation advocacy", "DRC's position as one of Africa's largest countries with dozens of distinct cultural traditions requiring comprehensive museum documentation"],
        "effects": ["National Museum preserving what remains of DRC's cultural heritage after colonial-era looting", "Repatriation advocacy for Congolese artifacts held in Belgian Tervuren museum and other European collections", "DRC civil wars (particularly Second Congo War, 5 million dead) challenging museum institutional continuity", "Kongo art's global influence on modern art documented as part of the museum's cultural significance narrative"],
        "relationships": [{"entity": "Kingdom of Kongo", "relationship": "PRESERVES_HERITAGE_OF_SOPHISTICATED_PRE-COLONIAL_KINGDOM", "note": "The museum preserves the visual art traditions of the Kingdom of Kongo, including minkisi and nkisi nkondi pieces"}, {"entity": "Royal Museum for Central Africa Tervuren", "relationship": "ADVOCATES_REPATRIATION_OF_COLLECTIONS_HELD_AT_BELGIAN_COLONIAL", "note": "The museum advocates for repatriation of the enormous Congolese collection held at Belgium's Tervuren museum"}, {"entity": "African Art Cubism", "relationship": "KONGO_ART_INFLUENCING_PICASSO_AND_CUBIST_REVOLUTION_DOCUMENTED_AS", "note": "Kongo art held in the museum's tradition was influential on Picasso and the cubist revolution in modern art"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The DRC National Museum — preserving the heritage of the Kingdom of Kongo whose art influenced Picasso and Cubism, advocating for repatriation of colonial-looted collections — is historically significant as the cultural institution of Africa's most biodiverse country and a central actor in African heritage repatriation debates.", "significanceCategory": "world-changing"},
    }),
    ("ghana-national-museum", {
        "summary": "The Ghana National Museum in Accra is the primary cultural institution of Ghana — the first sub-Saharan African country to achieve independence from colonial rule (1957, under Kwame Nkrumah's leadership) — preserving the heritage of the Ashanti Empire and its extraordinary goldwork tradition, the ancient Ghana Empire (4th-13th centuries CE, actually located in what is now Mali and Mauritania rather than modern Ghana), and the diverse cultural traditions of over 100 ethnic groups in what was British Gold Coast.\n\nGhana's cultural heritage is remarkable for its gold traditions: the Ashanti (Asante) people of south-central Ghana developed the world's most sophisticated gold artistry among sub-Saharan peoples — the Golden Stool (Sika Dwa Kofi), the sacred throne of the Asante king (Asantehene), is the most sacred object in Akan culture, symbolizing the soul of the Asante nation. Kente cloth (the colorful woven textile made by Akan people in strips), Adinkra symbols (an abstract graphic language encoding wisdom concepts), and Ashanti goldweights (brass figurines and geometric forms used as weighing instruments for gold dust currency) all represent extraordinary material culture achievements.\n\nGhana's role in the Atlantic slave trade — the Gold Coast was one of the primary slave-exporting regions, and Cape Coast Castle and Elmina Castle were major slave-holding forts — is also documented in Ghana's museums and historical sites. Ghana's leadership in pan-African thought under Kwame Nkrumah, the founding of the Organization of African Unity (1963), and Ghana's subsequent democratic development make it one of Africa's most historically significant nations.",
        "causes": ["Ghana independence (1957) under Kwame Nkrumah requiring national cultural institution building as pan-African symbol", "Ashanti Empire's extraordinary gold and cultural traditions requiring institutional preservation and documentation", "Gold Coast's role in Atlantic slave trade requiring documentation and memorialization in national institutions", "Over 100 ethnic groups' diverse cultural traditions requiring comprehensive national museum curation"],
        "effects": ["Ghana National Museum preserving Ashanti goldwork, Kente cloth, and Adinkra symbol traditions as national heritage", "Kwame Nkrumah's pan-African legacy documented in Ghana's national institutions", "Slave trade heritage documented alongside pre-colonial cultural achievements in Ghana's historical memory", "Ashanti cultural traditions (Golden Stool, Kente cloth, goldweights) internationally recognized as extraordinary human achievements"],
        "relationships": [{"entity": "Ashanti Empire", "relationship": "PRESERVES_EXTRAORDINARY_GOLDWORK_AND_CULTURAL_HERITAGE_OF", "note": "The museum preserves the Ashanti Empire's goldwork, Kente cloth, and cultural traditions"}, {"entity": "Kwame Nkrumah", "relationship": "NATIONAL_INSTITUTION_DOCUMENTING_LEGACY_OF_GHANA'S_INDEPENDENCE_LEADER", "note": "The museum documents Kwame Nkrumah's legacy as Ghana's independence leader and pan-African advocate"}, {"entity": "Atlantic Slave Trade", "relationship": "GOLD_COAST_SLAVE_TRADE_HERITAGE_DOCUMENTED_ALONGSIDE_PRE-COLONIAL_CULTURE", "note": "Ghana's national institutions document the Gold Coast's significant role in the Atlantic slave trade"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Ghana National Museum — preserving the Ashanti Empire's extraordinary goldwork and pan-African independence heritage of sub-Saharan Africa's first independent country — is historically significant as the cultural institution of Africa's symbolic first independence nation.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 145 — Class 361 Museums VII: African & Asian State Museums")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
