#!/usr/bin/env python3
"""Batch 123 — Mixed: Class 343 Temples VI (1) + Class 341 Cathedrals IX (7)"""
import json, os
from datetime import datetime, timezone

FOLDER_343 = "data/appwrite-export/entities/343-Class-343"
FOLDER_341 = "data/appwrite-export/entities/341-Class-341"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("chinese-temple-of-dili", {
        "summary": "The Chinese Temple of Dili (also known as the Chinese Community Temple or Templo Chinês de Díli), located in Dili, the capital of Timor-Leste (East Timor), is one of the most significant religious and cultural institutions of the overseas Chinese community in one of the world's newest nations — established during the Portuguese colonial era as a center of Chinese syncretic religion (combining Taoist, Buddhist, and folk religious traditions) and serving as a cultural anchor for the Chinese diaspora community that has played a significant economic role in East Timorese society since the Portuguese colonial period.\n\nTimor-Leste's Chinese community has roots in the Portuguese colonial period (the Portuguese established Dili as their administrative center in the 19th century, and Chinese traders and merchants followed colonial trade routes). The Chinese temple in Dili served the community's religious life through the Portuguese colonial period, the Indonesian occupation (1975-1999), and the post-independence period. The Indonesian occupation period was catastrophically destructive for all Timorese institutions, and the temple's survival and restoration is part of the broader post-independence cultural reconstruction effort.\n\nThe Chinese Temple of Dili represents the broader pattern of Chinese diaspora religious institutions throughout Southeast Asia — from Malacca to Batavia to Dili — that combined Chinese folk religion's three traditions (Taoism, Buddhism, Confucian ancestor veneration) in syncretic temple spaces serving communities far from China. These temples have often served simultaneously as community centers, welfare institutions, and cultural preservation sites for diaspora communities maintaining identity across generations and under colonial and post-colonial pressures.",
        "causes": ["Chinese community establishment in Portuguese Timor through colonial trade networks during 19th-20th centuries", "Chinese diaspora religious traditions requiring syncretic temple spaces combining Taoist, Buddhist, and folk practices", "Dili's role as Portuguese colonial capital attracting Chinese merchant and trader community settlement", "Post-Indonesian-occupation reconstruction of cultural institutions as part of Timor-Leste's national renewal"],
        "effects": ["Chinese diaspora community cultural anchor in one of the world's newest nation-states", "Syncretic religious practice combining Taoist, Buddhist, and Confucian traditions for overseas Chinese community", "Post-independence restoration demonstrating Timor-Leste's commitment to multicultural heritage recognition", "Chinese diaspora economic and cultural presence preserved through religious institution survival across colonial transitions"],
        "relationships": [{"entity": "Chinese Diaspora in Southeast Asia", "relationship": "DILI_NODE_OF", "note": "The Dili Chinese Temple is one node in the network of Chinese diaspora religious institutions throughout Southeast Asia"}, {"entity": "Timor-Leste", "relationship": "CULTURAL_MONUMENT_OF_CHINESE_COMMUNITY_IN", "note": "The temple serves the Chinese community in one of the world's newest nations and is part of its multicultural heritage"}, {"entity": "Portuguese Colonial Timor", "relationship": "ESTABLISHED_DURING_COLONIAL_ERA_OF", "note": "The Chinese temple was founded during Portuguese colonial rule when Chinese traders followed colonial trade networks to Timor"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "The Chinese Temple of Dili — cultural anchor for the Chinese diaspora in one of the world's newest nations, surviving Portuguese colonialism, Indonesian occupation, and independence to serve as community religious institution — is historically significant for illuminating Chinese diaspora religious traditions in the easternmost reaches of the Southeast Asian colonial world.", "significanceCategory": "local"},
    }, FOLDER_343, "343"),
    ("basilica-of-st-michael-bordeaux", {
        "summary": "The Basilica of Saint-Michel in Bordeaux (French: Basilique Saint-Michel de Bordeaux), a Gothic masterpiece begun in 1350 and completed in the 16th century in the Saint-Michel quarter of Bordeaux, is one of the largest Gothic churches in southwestern France — notable for its detached bell tower (the Flèche de Saint-Michel, 114 meters tall), the highest structure in southern France and the second highest in France after Chartres until the construction of the Eiffel Tower — and for the extraordinary mummified bodies (momies de la Crypte Saint-Michel) discovered in its charnel house in the 18th century and exhibited for several centuries.\n\nSaint-Michel Bordeaux represents Bordeaux's medieval prosperity as a commercial city under both English (the Duchy of Aquitaine, controlled by the English Crown from 1152 to 1453 through Henry II's marriage to Eleanor of Aquitaine) and later French sovereignty. The church was built in the Flamboyant Gothic style — the final, most ornate phase of French Gothic — reflecting the economic wealth generated by Bordeaux's wine trade and Atlantic commerce. The detached campanile-style bell tower, built separately from the church in the Italianate campanile tradition (like the Leaning Tower of Pisa's relationship to Pisa Cathedral), was one of the most distinctive architectural choices in medieval southwestern France.\n\nThe Saint-Michel quarter historically housed Bordeaux's artisans, Jewish community, and immigrant populations — it is today one of Bordeaux's most multicultural and lively neighborhoods. The church was classified as a UNESCO World Heritage Site component as part of the Pilgrimage Routes to Santiago de Compostela (Saint-Michel was on a route for pilgrims traveling through southwestern France). The famous mummified bodies in the crypt attracted scientific and popular attention from the 18th century.",
        "causes": ["1350 construction beginning during Bordeaux's prosperous English Duchy of Aquitaine period", "Flamboyant Gothic architectural fashion requiring ambitious decorative building program", "Saint-Michel quarter artisan and immigrant community requiring major parish church", "Detached bell tower construction in Italian campanile tradition reflecting Bordeaux's Mediterranean commercial connections"],
        "effects": ["114-meter Flèche de Saint-Michel as highest structure in southern France and second in all France before the Eiffel Tower", "Mummified crypt bodies attracting scientific and popular curiosity from 18th century onward", "UNESCO Pilgrimage Routes to Santiago de Compostela recognition connecting church to European pilgrimage network", "Saint-Michel quarter's diverse character preserved around the landmark Gothic basilica"],
        "relationships": [{"entity": "Duchy of Aquitaine", "relationship": "BUILT_DURING_ENGLISH_SOVEREIGNTY_PERIOD_OF", "note": "Saint-Michel's construction (from 1350) occurred during Bordeaux's English period as part of the Duchy of Aquitaine"}, {"entity": "Pilgrimage Routes to Santiago de Compostela", "relationship": "UNESCO_COMPONENT_OF", "note": "The basilica is recognized as part of the UNESCO World Heritage Santiago de Compostela pilgrimage routes"}, {"entity": "Bordeaux", "relationship": "MAJOR_GOTHIC_MONUMENT_OF", "note": "The Flèche de Saint-Michel (114m) was the tallest structure in southern France and defined Bordeaux's skyline for centuries"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Basilica of Saint-Michel Bordeaux — Flamboyant Gothic masterpiece with southwestern France's tallest medieval tower, site of famous mummified remains, and UNESCO World Heritage component on the Santiago pilgrimage routes — is one of France's historically significant Gothic religious monuments.", "significanceCategory": "world-changing"},
    }, FOLDER_341, "341"),
    ("church-of-san-juan-of-portomarín", {
        "summary": "The Church of San Juan (or San Nicolás) of Portomarín in Galicia, northwestern Spain — one of the most architecturally unusual churches on the Camino de Santiago pilgrimage route — is a 12th-century Romanesque-Gothic church that was originally built by the Knights of Saint John of Jerusalem (Knights Hospitaller) and was relocated stone by stone to higher ground in 1962-1963 when the Portomarín valley was flooded to create the Belesar reservoir on the Miño River, making it one of the most dramatic modern examples of historic building relocation and one of the most remarkable architectural survivals on the entire Camino de Santiago.\n\nPortomarín's original settlement in the Miño River valley was an important stage on the French Way (Camino Francés) to Santiago de Compostela — the most traveled pilgrimage route to the tomb of Saint James. The Knights Hospitaller church of San Juan was built in the 12th-13th centuries in the heavy defensive Romanesque style characteristic of military-religious orders. The church's fortress-like exterior (with battlements and few windows) was designed for both religious use and potential defensive purpose — reflecting the military order's dual nature.\n\nThe 1962 construction of the Belesar Dam requiring the valley's flooding created an unprecedented heritage challenge: the medieval village of Portomarín (and its remarkable church) faced permanent submersion. The Spanish government authorized the systematic relocation — stones were numbered, removed, transported up the hill, and reassembled at the new higher Portomarín. During droughts, the ruins of the original village occasionally re-emerge from the reservoir, creating an eerie visual reminder of the lost settlement. The relocated church continues to welcome Camino pilgrims.",
        "causes": ["12th-13th century Knights Hospitaller construction on the Camino de Santiago as military-religious order hospitality station", "Strategic Miño River valley position making Portomarín an important Camino pilgrimage stop", "1962 Belesar Dam reservoir construction requiring unprecedented stone-by-stone church relocation to higher ground", "Pilgrimage route strategic importance justifying exceptional preservation effort"],
        "effects": ["Stone-by-stone relocation (1962-1963) as one of the most dramatic modern examples of historic building relocation", "Relocated church continuing to serve Camino pilgrims as one of the route's most historically distinctive buildings", "Original village ruins periodically re-emerging from Belesar reservoir during droughts", "Church's distinctive military Romanesque architecture (battlements, minimal windows) preserved as example of Knights Hospitaller building style"],
        "relationships": [{"entity": "Knights Hospitaller", "relationship": "BUILT_AS_HOSPITALLER_CHURCH_OF", "note": "The church was built by the Knights of Saint John as a Romanesque-Gothic pilgrimage hospitality building on the Camino"}, {"entity": "Camino de Santiago", "relationship": "IMPORTANT_STAGE_CHURCH_ON_FRENCH_WAY", "note": "Portomarín's church is one of the most historically significant pilgrimage stops on the French Way (Camino Francés)"}, {"entity": "Belesar Dam", "relationship": "RELOCATED_STONE-BY-STONE_TO_AVOID_FLOODING_BY", "note": "The 1962 dam construction forced the systematic stone-by-stone relocation of the entire medieval church"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Church of San Juan of Portomarín — a Knights Hospitaller Romanesque masterpiece, stone-by-stone relocated from a flooded valley in 1962, and one of the Camino de Santiago's most historically distinctive pilgrimage churches — combines medieval military-religious heritage with one of history's most remarkable modern building relocations.", "significanceCategory": "world-changing"},
    }, FOLDER_341, "341"),
    ("church-of-santiago-de-gobiendes", {
        "summary": "The Church of Santiago de Gobiendes (Iglesia de Santiago de Gobiendes) in Asturias, northwestern Spain, is a pre-Romanesque Asturian church dating to the 9th century CE — built during the Kingdom of Asturias, the small Christian kingdom in northern Iberia that survived the Muslim conquest of most of Spain and from which the later Spanish Reconquista (the 800-year Christian reconquest) would ultimately spring. The church is part of the group of pre-Romanesque Asturian monuments that represent some of the earliest surviving Christian sacred architecture in Iberia after the 8th-century Muslim conquest.\n\nThe Kingdom of Asturias (718-924 CE) was the last surviving Visigothic-Christian stronghold in Iberia after the Umayyad conquest of 711-719 CE wiped out the Visigothic kingdom. Asturian kings built a distinctive series of churches in the 9th century — including Santa María del Naranco, San Miguel de Lillo, Santa Cristina de Lena, and smaller churches like Gobiendes — that represent a unique architectural tradition combining Visigothic, Mozarabic (Christian architecture influenced by Islamic forms), and early Romanesque elements.\n\nThe Church of Santiago de Gobiendes's direct dedication to Santiago (Saint James the Apostle) is particularly significant: the cult of Saint James — his supposed relics at Santiago de Compostela — was being developed during exactly the 9th-century Asturian period as a unifying religious symbol for the Reconquista. The church's location in rural Asturias reflects the dense network of small pre-Romanesque sacred buildings through which the Asturian kingdom populated its contested territory with Christian sacred presence.",
        "causes": ["9th-century Kingdom of Asturias building program establishing Christian sacred presence in post-conquest northern Iberia", "Santiago cult development as Reconquista religious symbol requiring churches dedicated to Saint James throughout Asturias", "Asturian architectural tradition combining Visigothic, Mozarabic, and early Romanesque elements in distinctive regional style", "Rural Asturian Christian community religious needs requiring parish church construction"],
        "effects": ["Pre-Romanesque architectural evidence documenting the earliest post-conquest Christian building tradition in Iberia", "Santiago dedication contributing to the development of the Saint James cult and Camino de Santiago pilgrimage network", "Asturian monument group (including Gobiendes) recognized as UNESCO World Heritage site for its pre-Romanesque significance", "Asturian building program establishing architectural precedents for later Spanish Romanesque and Gothic development"],
        "relationships": [{"entity": "Kingdom of Asturias", "relationship": "BUILT_AS_PART_OF_ASTURIAN_SACRED_ARCHITECTURE_OF", "note": "The church represents the 9th-century Asturian building program establishing Christian sacred presence in post-conquest northern Iberia"}, {"entity": "Santiago de Compostela Pilgrimage", "relationship": "EARLY_DEDICATION_CONTRIBUTING_TO_DEVELOPMENT_OF", "note": "The church's Santiago dedication in 9th-century Asturias contributes to the early history of the Camino de Santiago cult"}, {"entity": "Pre-Romanesque Asturian Architecture", "relationship": "EXAMPLE_OF_UNESCO-RECOGNIZED", "note": "The church is part of the UNESCO-recognized group of pre-Romanesque Asturian monuments"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Church of Santiago de Gobiendes — a 9th-century pre-Romanesque Asturian church dedicated to Saint James, part of the UNESCO-recognized Asturian monument group, and representing the earliest Christian architecture in post-Muslim-conquest Iberia — is historically significant as evidence of the Kingdom of Asturias that gave birth to the Reconquista.", "significanceCategory": "continental"},
    }, FOLDER_341, "341"),
    ("basílica-del-corazón-de-maría-santiago-de-chile", {
        "summary": "The Basilica del Corazón de María (Basilica of the Heart of Mary) in Santiago de Chile is a significant neogothic Catholic basilica completed in 1927 in the Barrio Italia neighborhood of Santiago, built under the patronage of the Claretian Missionaries (Congregation of the Missionary Sons of the Immaculate Heart of Mary, founded by Saint Anthony Mary Claret) — reflecting the 19th-20th century wave of devotion to the Heart of Mary in parallel with the Sacred Heart of Jesus devotion that produced numerous major basilicas across Latin America.\n\nThe Heart of Mary (Immaculate Heart) devotion, rooted in the Fatima apparitions of 1917 (where the Virgin Mary supposedly appeared to three Portuguese shepherd children and requested consecration to her Immaculate Heart) and in 19th-century Marian theology, was particularly strong in Latin American Catholicism where Marian devotion has historically been one of the most powerful forces in popular religious life. The Claretians, who administered the basilica, were founded in 1849 in Spain by Anthony Mary Claret — himself closely associated with Chile (he was confessor of Queen Isabella II of Spain and spent time in Cuba) — giving the congregation Latin American associations.\n\nSantiago de Chile's neogothic basilicas represent the 19th-20th century Catholic building program in Chile that sought to Europeanize religious architecture after independence. The European Gothic revival style imported through Jesuit and Claretian church builders gave Santiago a series of architecturally ambitious churches that sought to rival European Gothic cathedrals in ambition if not in scale.",
        "causes": ["Claretian Missionaries' 19th-20th century Chilean mission requiring basilica dedicated to their founding devotion", "Heart of Mary devotion intensified by 1917 Fatima apparitions creating demand for Marian heart basilicas", "Barrio Italia's growing Catholic community requiring parish church of appropriate scale", "Neogothic architectural fashion in post-independence Latin America seeking European architectural prestige"],
        "effects": ["Neogothic basilica as landmark of Barrio Italia neighborhood and Santiago's Catholic architectural heritage", "Marian Heart devotion institutionalized through permanent basilica dedicated to the Heart of Mary in Chile's capital", "Claretian mission presence in Chile consolidated through permanent church building", "European Gothic revival influence documented in Santiago's religious architecture"],
        "relationships": [{"entity": "Claretian Missionaries", "relationship": "BUILT_AND_ADMINISTERED_BY", "note": "The Claretian Missionaries built the basilica as the center of their Chilean mission's Marian devotion"}, {"entity": "Immaculate Heart of Mary Devotion", "relationship": "ARCHITECTURAL_MONUMENT_TO", "note": "The basilica embodies the Heart of Mary devotion strengthened by the 1917 Fatima apparitions"}, {"entity": "Santiago de Chile", "relationship": "NEOGOTHIC_RELIGIOUS_LANDMARK_OF", "note": "The basilica is one of Santiago's significant neogothic Catholic buildings from the 20th-century church building program"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "The Basilica del Corazón de María in Santiago — a neogothic Claretian basilica embodying Latin American Marian devotion and the European Gothic revival in Chilean religious architecture — is historically significant for its devotional and architectural context.", "significanceCategory": "local"},
    }, FOLDER_341, "341"),
    ("cathedral-basilica-of-our-lady-of-the-assumption-santiago-de-cuba", {
        "summary": "The Cathedral Basilica of Our Lady of the Assumption of Santiago de Cuba (Catedral Basílica de Nuestra Señora de la Asunción de Santiago de Cuba), founded in 1514 as one of the first Catholic cathedrals in the Americas following the Spanish colonization of Cuba, is the mother church of the Archdiocese of Santiago de Cuba and one of the oldest continuously functioning cathedrals in the Western Hemisphere — located in Cuba's second city and historic eastern capital, and serving as the religious center of a city that has been pivotal in Cuban history from the colonial period through the wars of independence and the Cuban Revolution.\n\nSantiago de Cuba was established by Diego Velázquez de Cuéllar in 1515 as one of the original seven Spanish colonial settlements (villas) in Cuba, and was Cuba's first capital before Havana assumed that role. The Cathedral of the Assumption, built on the Plaza de Armas (now Parque Céspedes) facing the city hall, occupies the same symbolic space as the political authority — the characteristic colonial urban plan of church and state facing each other across the main plaza.\n\nThe cathedral's construction history spans five centuries: repeatedly rebuilt and renovated due to earthquakes and deterioration, the current primarily Baroque structure dates largely to the 17th-19th centuries. The tomb of Diego Velázquez de Cuéllar, Cuba's first governor, was reportedly associated with the early cathedral. Santiago de Cuba's Afro-Cuban religious culture — where Santería, the syncretic Yoruba-Catholic religion, has been particularly strong — has created a complex religious landscape in which the cathedral's official Catholic presence coexists with a rich underground of African-derived religious practice.",
        "causes": ["1514 founding as one of first Catholic cathedrals in Americas following Spanish colonization of Cuba", "Santiago de Cuba's status as Cuba's first capital requiring cathedral as the colony's mother church", "Colonial urban plan tradition placing cathedral facing city hall across the main plaza", "5-century rebuilding program following earthquakes and tropical deterioration"],
        "effects": ["One of Western Hemisphere's oldest continuously functioning cathedrals as monument to Spanish colonial religious establishment", "Afro-Cuban Santería and Catholicism coexistence in Santiago creating complex religious landscape around cathedral", "Diego Velázquez burial connection making cathedral a monument to Cuba's founding colonial history", "Cuban Revolution's religious-political tensions played out against Santiago's cathedral as Catholic institutional symbol"],
        "relationships": [{"entity": "Diego Velázquez de Cuéllar", "relationship": "FOUNDED_WITH_CUBA'S_FIRST_GOVERNOR", "note": "The cathedral was established in 1514 along with the city founded by Cuba's first governor Diego Velázquez"}, {"entity": "Spanish Colonial Cuba", "relationship": "MOTHER_CHURCH_OF_COLONIAL_PERIOD", "note": "As Santiago de Cuba's cathedral from 1514, it served as the religious center of Spain's first Cuban colonial capital"}, {"entity": "Santería", "relationship": "COEXISTS_IN_SANTIAGO_ALONGSIDE", "note": "Santiago de Cuba's strong Afro-Cuban Santería traditions created a complex religious landscape around the Catholic cathedral"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Cathedral Basilica of Santiago de Cuba — one of the Western Hemisphere's oldest cathedrals (1514), mother church of the first Cuban capital, and religious center of a city crucial to Cuban history from colonialism through Revolution — is an important monument of Spanish American religious and colonial history.", "significanceCategory": "world-changing"},
    }, FOLDER_341, "341"),
    ("cathedral-of-martin-of-tours-mukacheve", {
        "summary": "The Cathedral of Saint Martin of Tours in Mukacheve (Ukrainian: Собор святого Мартина Турського, Mukachevo, Zakarpattia Oblast, western Ukraine) is a Gothic and Baroque Catholic cathedral in a city that has been one of Central Europe's most contested crossroads — passed through Hungarian, Austro-Hungarian, Czechoslovak, Soviet, and now Ukrainian sovereignty — with the cathedral reflecting the region's historically Catholic (predominantly Hungarian-speaking) religious heritage, standing as a monument to Transcarpathia's complex Central European cultural identity.\n\nMukacheve (Hungarian: Munkács) is the historical center of Subcarpathian Rus' (also called Carpatho-Ukraine or Ruthenia) — a region at the junction of Hungarian, Czech, Slovak, Ukrainian, and Romanian cultures that has been among Europe's most politically volatile territories. The Cathedral of Saint Martin represents the region's Latin Catholic (Roman Catholic) heritage, primarily associated with the Hungarian-speaking community that was the dominant presence in the city during Hungarian and Austro-Hungarian rule (from the medieval period through 1918 and again 1938-1944).\n\nMukacheve's complex history includes: Hungarian medieval kingdom, Ottoman pressure, Habsburg control, Czechoslovak interwar republic (1919-1938), Hungarian annexation (1938), Soviet incorporation (1944-1991), and Ukrainian independence. Each political transformation produced religious upheaval — with Catholic, Greek Catholic, Orthodox, and Protestant communities all present and each associated with different political identities. The cathedral's Gothic origins (founded medieval, rebuilt in Baroque style) document the region's Central European Catholic heritage before the Soviet period dramatically reduced Catholic institutional life.",
        "causes": ["Medieval Hungarian kingdom establishment of Catholic cathedral in Mukacheve as regional ecclesiastical center", "Austro-Hungarian period Catholic church expansion and renovation in Baroque style", "Hungarian-speaking Catholic community's institutional presence through successive political transformations", "Transcarpathia's position at Central European cultural crossroads creating multi-denominational religious landscape"],
        "effects": ["Cathedral preservation through Hungarian, Czechoslovak, Soviet, and Ukrainian periods documenting religious survival in politically unstable region", "Latin Catholic heritage preservation as cultural memory of the region's pre-Soviet Central European identity", "Soviet period restrictions reducing but not eliminating Catholic institutional life in Mukacheve", "Post-1991 Ukrainian independence enabling Catholic church restoration and revitalization"],
        "relationships": [{"entity": "Mukacheve", "relationship": "PRINCIPAL_CATHOLIC_MONUMENT_OF", "note": "The cathedral is Mukacheve's most significant Catholic building representing the city's Hungarian-era Latin Catholic heritage"}, {"entity": "Kingdom of Hungary", "relationship": "ORIGINAL_FOUNDATION_CONTEXT_OF", "note": "The cathedral's origins are in the medieval Hungarian kingdom's ecclesiastical network in Subcarpathian territory"}, {"entity": "Transcarpathia", "relationship": "LATIN_CATHOLIC_LANDMARK_OF_CONTESTED_REGION", "note": "The cathedral represents the Latin Catholic heritage of Europe's most politically contested 20th-century region"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Cathedral of Saint Martin in Mukacheve — representing Latin Catholic heritage in Central Europe's most politically contested region, surviving Hungarian, Czechoslovak, Soviet, and Ukrainian sovereignty, and documenting Transcarpathia's complex cultural crossroads identity — is historically significant as a monument of religious and political survival.", "significanceCategory": "continental"},
    }, FOLDER_341, "341"),
    ("san-francisco-church-santiago-de-chile", {
        "summary": "The Church and Convent of San Francisco (Iglesia y Convento de San Francisco) in Santiago de Chile, completed in 1618 in the colonial center of the city, is the oldest surviving building in Santiago and one of the oldest colonial-era buildings in Chile — a Franciscan church and convent built in a distinctive colonial baroque style adapted to Chile's seismic conditions, housing the famous Virgin of the Carmen of Las Peñas (La Virgen del Carmen de las Peñas), one of the most venerated Catholic images in Chile, and serving as the Franciscan order's central institution in Chile since the colonial founding.\n\nThe Church of San Francisco was founded by the Franciscan order in Santiago following the Spanish conquest of Chile in the 1540s. Pedro de Valdivia, the conquistador who founded Santiago in 1541, granted the Franciscans land in the colonial city center to establish their convent. The current church building, replacing earlier structures, dates to 1618 and was designed with unusually thick adobe and stone walls to withstand the earthquakes that characterize the Chilean seismic zone — an early example of seismic-aware religious architecture in the Americas.\n\nThe Virgin of the Carmen de las Peñas is a 17th-century carved image that has been the center of intense popular devotion in Chile for over three centuries. The church's location in the Barrio París-Londres area, Santiago's bohemian historic district, makes it both a religious landmark and a cultural focal point. The adjacent Franciscan Museum (Museo Colonial de San Francisco) contains one of Chile's most important collections of colonial religious art — the Franciscan order's educational and evangelical mission preserved an extraordinary collection of colonial paintings, including a famous series depicting the life of Saint Francis.",
        "causes": ["Pedro de Valdivia's 1541 Santiago founding granting Franciscans land for convent in the colonial center", "Franciscan evangelization mission requiring permanent church and convent as base for Chilean missionary work", "1618 thick-walled construction as earthquake-resistant adaptation to Chile's seismic conditions", "Virgin of the Carmen de las Peñas veneration establishing the church as center of popular Marian devotion"],
        "effects": ["Oldest surviving building in Santiago as irreplaceable monument of colonial Chilean history", "Seismic-resistant thick adobe walls as early example of earthquake-aware architectural adaptation in the Americas", "Franciscan Museum collection becoming one of Chile's most important repositories of colonial religious art", "Virgin of the Carmen popular devotion making the church one of Santiago's most visited pilgrimage sites"],
        "relationships": [{"entity": "Pedro de Valdivia", "relationship": "FOUNDING_LAND_GRANT_GIVEN_BY", "note": "Chile's conquistador and Santiago's founder granted Franciscans the colonial city center land for their convent"}, {"entity": "Franciscan Order", "relationship": "PRINCIPAL_CHILEAN_INSTITUTION_OF", "note": "San Francisco has been the Franciscan order's central Chilean institution since the colonial founding"}, {"entity": "Virgin of the Carmen de las Peñas", "relationship": "HOUSES_MOST_VENERATED_IMAGE_OF", "note": "The 17th-century carved Virgin housed at San Francisco is one of Chile's most venerated Catholic religious images"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Church of San Francisco in Santiago — the oldest surviving building in Chile's capital, pioneer of seismic-resistant religious architecture in the Americas, repository of colonial art in the Franciscan Museum, and home to Chile's most venerated Marian image — is one of South America's most historically significant colonial religious monuments.", "significanceCategory": "world-changing"},
    }, FOLDER_341, "341"),
]

def enrich_entity(slug, data, folder, prefix):
    fname = os.path.join(folder, f"{prefix}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 123 — Mixed: Class 343 Temples VI (1) + Class 341 Cathedrals IX (7)")
    for slug, data, folder, prefix in ENTITIES:
        enrich_entity(slug, data, folder, prefix)
    print("Done.")
