#!/usr/bin/env python3
"""Batch 108 — Class 343 Temples II: Ancient & Sacred Temples (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/343-Class-343"
FILE_PREFIX = "343"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("pashupatinath-temple", {
        "summary": "Pashupatinath Temple in Kathmandu, Nepal, on the banks of the Bagmati River, is the most sacred Hindu temple in the world for Shaivites — devotees of Shiva — and the most important religious site in Nepal. Dedicated to Pashupatinath (Lord of All Animals), an aspect of Shiva, the temple complex dates in its current form to the 5th century CE (though the site's religious significance extends much earlier), and the main pagoda-style shikhara was rebuilt in the 17th century. UNESCO World Heritage Site since 1979.\n\nPashupatinath is Nepal's most important pilgrimage site, drawing hundreds of thousands of Hindu pilgrims annually, particularly during Maha Shivaratri (Shiva's great night) when over a million devotees gather from across South Asia. The complex includes the main two-storied pagoda temple (non-Hindus not admitted inside), cremation ghats on the Bagmati River where Hindus are cremated and their ashes consigned to the river flowing to the Ganges, and a vast complex of smaller temples, ashrams, and shrines.\n\nThe Bagmati River ghats at Pashupatinath are one of the most spiritually charged sites in Hinduism: open-air cremations are performed continuously, and dying Hindus from across Nepal and India are brought to spend their final hours near the temple. The site's philosophical centrality to the Hindu understanding of life, death, and moksha (liberation) makes it one of the most profound living religious complexes in the world. UNESCO protection and its status as Nepal's national religious symbol make it central to Nepali national identity.",
        "causes": ["5th century CE temple establishment with royal Licchavi dynasty patronage", "Pashupatinath worship as Nepal's state deity making this the national sacred site", "Bagmati River location connecting cremation rites to the sacred Ganges via tributaries", "UNESCO World Heritage designation (1979) preserving the complex's ancient architectural ensemble"],
        "effects": ["Annual Maha Shivaratri pilgrimage drawing over one million devotees from across South Asia", "Cremation ghats as Nepal's primary site for Hindu last rites — symbolizing liberation (moksha)", "Pashupatinath as Nepal's national religious symbol embedded in national identity and state ceremonies", "UNESCO protection preserving 5th-17th century temple architecture for global heritage"],
        "relationships": [{"entity": "Shiva", "relationship": "DEDICATED_TO_ASPECT_OF", "note": "Temple dedicated to Pashupatinath — Lord of Animals — an aspect of Shiva as protector of all living beings"}, {"entity": "Maha Shivaratri", "relationship": "PRIMARY_FESTIVAL_SITE_FOR", "note": "Over one million pilgrims gather at Pashupatinath during Maha Shivaratri annually"}, {"entity": "Bagmati River", "relationship": "SACRED_CREMATION_SITE_ON", "note": "Cremation ghats on the Bagmati (tributary to Ganges) make Pashupatinath Nepal's primary moksha site"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Pashupatinath Temple — Nepal's most sacred site, the world's premier Shaivite pilgrimage destination, a living site of Hindu last rites philosophy, and a UNESCO World Heritage site — is one of Hinduism's most spiritually and culturally significant living religious complexes.", "significanceCategory": "world-changing"},
    }),
    ("dambulla-cave-temple", {
        "summary": "The Dambulla Cave Temple (Golden Temple of Dambulla) in central Sri Lanka, carved into a massive rock outcrop rising 160 meters above the surrounding plains, is the largest and best-preserved cave temple complex in Sri Lanka — a UNESCO World Heritage Site (1991) containing 153 Buddha statues, 3 statues of Sri Lankan kings, and 4 statues of gods across five caves, with wall paintings covering 2,100 square meters of ceiling and walls dating from the 1st century BCE through the 18th century CE.\n\nThe caves were used as a refuge by King Vattagamani Abhaya (Valagamba) when he fled the Chola invasion in 103 BCE; after recapturing his throne (88 BCE), he transformed the natural caves into a magnificent Buddhist temple complex as an act of thanksgiving. The Royal Cave Temple (Cave II) is the largest — 52 meters long — containing a massive reclining Buddha (15 meters) carved from solid rock, with the ceiling covered in intricate 18th-century paintings depicting the life of the Buddha and scenes from Sri Lankan history.\n\nDambulla's importance extends beyond its artistic achievement: the site represents 2,100 years of continuous Buddhist worship, making it one of the longest continuously used sacred sites in Asia. The paintings represent five distinct stylistic periods spanning 2,000 years, providing an unbroken visual record of Sri Lankan Buddhist art. The temple is still an active place of worship for Sri Lankan Buddhists, and the pilgrimage up the rock face is one of the island's most important religious acts.",
        "causes": ["1st century BCE founding by King Vattagamani Abhaya as thanksgiving after recapturing his throne", "Natural rock outcrop providing ideal cave spaces for carving Buddhist sanctuaries", "Royal patronage across 2,100 years adding statues, paintings, and new cave chambers continuously", "UNESCO World Heritage designation (1991) preserving 153 statues and 2,100 sq m of cave paintings"],
        "effects": ["2,100 years of continuous Buddhist worship making Dambulla one of Asia's oldest active sacred sites", "153 Buddha statues and 2,100 sq m of paintings constituting Sri Lanka's greatest Buddhist art ensemble", "Five distinct stylistic periods of paintings providing unbroken visual record of Sri Lankan Buddhist art", "UNESCO recognition bringing global awareness to Sri Lanka's Buddhist heritage"],
        "relationships": [{"entity": "King Vattagamani Abhaya", "relationship": "ESTABLISHED_AS_TEMPLE_BY", "note": "King Vattagamani (88 BCE) transformed the caves into a royal temple after reconquering Sri Lanka from Chola invaders"}, {"entity": "Theravada Buddhism", "relationship": "SACRED_CENTER_OF_IN_SRI_LANKA", "note": "Dambulla is one of Sri Lanka's most revered Theravada Buddhist pilgrimage sites"}, {"entity": "UNESCO World Heritage", "relationship": "DESIGNATED_BY", "note": "UNESCO designated Dambulla in 1991 recognizing its 2,100-year cultural and artistic significance"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Dambulla Cave Temple — 2,100 years of continuous Buddhist worship, 153 statues and 2,100 square meters of paintings representing Sri Lanka's greatest Buddhist art ensemble, and a UNESCO World Heritage Site — is one of Asia's most important and continuously used sacred cave complexes.", "significanceCategory": "world-changing"},
    }),
    ("temple-of-athena-nike", {
        "summary": "The Temple of Athena Nike on the Athenian Acropolis, built c. 425-420 BCE in the Ionic order by the architect Callicrates — the same architect who co-designed the Parthenon — is a small but exquisitely proportioned amphiprostyle temple (4 columns on each short end) dedicated to Athena as goddess of victory (nike). It stands on the southwestern bastion of the Acropolis, commanding views over the Saronic Gulf, and its frieze depicted the Battle of Marathon and mythological battles between Greeks and Persians and Greeks and Giants.\n\nThe temple was dismantled by the Ottomans in 1686 to build a gun battery (the same year they blew up the Parthenon) and its stones were incorporated into a defensive wall. The temple was reconstructed from the scattered blocks in 1836-1842 under the newly independent Greek state — one of the first systematic archaeological reconstructions in history — and again more carefully in 1998-2010 using improved anastylosis techniques.\n\nThe Temple of Athena Nike represents the peak of Ionic refinement at the Athenian Acropolis building program (Periclean era, c. 450-400 BCE): its sculptural frieze, the balustrade around the bastion (c. 410 BCE) depicting winged Nikes adjusting their sandals, and its perfect proportions within a confined space demonstrate the Athenian achievement of architectural harmony. The balustrade Nike reliefs — particularly the 'Nike fastening her sandal' (now in the Acropolis Museum) — are among the most admired works of 5th-century BCE Greek sculpture.",
        "causes": ["c. 425-420 BCE construction during Periclean building program celebrating Athenian victory over Persia", "Callicrates's Ionic amphiprostyle design creating perfect proportional harmony on a confined bastion", "Frieze depicting Marathon and Persian War battles commemorating Athenian military victories", "1686 Ottoman dismantling and 1836-2010 reconstruction demonstrating modern archaeological methodology"],
        "effects": ["Balustrade Nike reliefs (particularly 'Nike fastening her sandal') as 5th-century BCE sculptural masterpieces", "1836-1842 reconstruction as one of history's first systematic archaeological monument restorations", "1998-2010 anastylosis reconstruction establishing modern standards for ancient monument restoration", "Temple as part of Periclean Acropolis ensemble that defined Western architectural aesthetics"],
        "relationships": [{"entity": "Acropolis of Athens", "relationship": "SOUTHWESTERN_BASTION_COMPONENT_OF", "note": "Temple of Athena Nike guards the southwestern entrance bastion of the Acropolis complex"}, {"entity": "Callicrates", "relationship": "DESIGNED_BY", "note": "Callicrates (co-designer of the Parthenon) designed the Temple of Athena Nike c. 425-420 BCE"}, {"entity": "Periclean Building Program", "relationship": "PART_OF", "note": "The temple was part of Pericles's ambitious Acropolis rebuilding program (c. 450-400 BCE)"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Temple of Athena Nike — a peak of Ionic architectural refinement, source of Nike sculpture masterpieces, and subject of one of history's first archaeological reconstructions — is a defining monument of the Periclean golden age and Western classical heritage.", "significanceCategory": "world-changing"},
    }),
    ("temple-of-caesar", {
        "summary": "The Temple of Divus Julius (Temple of the Deified Julius Caesar) in the Roman Forum, dedicated in 29 BCE by Augustus at the spot where Julius Caesar's body was cremated in 44 BCE following his assassination, was the first temple in Rome dedicated to a mortal elevated to divine status (apotheosis) — establishing the precedent for the Imperial cult that would shape Roman state religion, legitimize successive emperors, and create a model of ruler-divinity that influenced later European monarchical ideology.\n\nJulius Caesar was assassinated on the Ides of March (15 March 44 BCE); his body was cremated in the Roman Forum in a spontaneous public outpouring of grief. The spot of his cremation became an immediate cult site; Octavian (the future Augustus) exploited this to have Caesar officially deified (Divus Julius) by the Senate in 42 BCE and built the temple at the cremation spot, consecrated 29 BCE after his victory over Antony and Cleopatra at Actium.\n\nThe political and religious significance of the Temple of Divus Julius cannot be overstated: by deifying Caesar, Augustus simultaneously legitimized his own position as Caesar's adoptive son (thus 'son of a god' — divi filius), established the template for imperial apotheosis, and fused Roman religious and political authority in a way that would define the Roman Empire for the next 400 years. The precedent of emperor-divinity was later adapted by Constantine in his Christian synthesis, and influenced the 'divine right of kings' traditions of medieval Europe.",
        "causes": ["Julius Caesar's 44 BCE assassination creating immediate popular cult at his cremation site", "Senate's 42 BCE deification of Caesar as Divus Julius establishing precedent for mortal apotheosis", "Augustus's political exploitation of Caesar's divinity to claim status as 'son of a god'", "29 BCE temple dedication at Actium victory consolidating Imperial cult as Roman state religion"],
        "effects": ["Imperial apotheosis model established — all subsequent emperors could claim posthumous deification", "Augustus's legitimacy as 'son of Divus Julius' cementing the Julio-Claudian dynasty", "Imperial cult fusing Roman political and religious authority shaping 400 years of Roman Empire", "Precedent influencing Christian Roman emperors and medieval divine-right-of-kings ideology"],
        "relationships": [{"entity": "Julius Caesar", "relationship": "DEDICATED_TO_CREMATION_SITE_OF", "note": "Temple built at exact spot where Caesar's body was cremated in the Roman Forum in 44 BCE"}, {"entity": "Augustus", "relationship": "BUILT_BY_AS_POLITICAL_LEGITIMATION_BY", "note": "Augustus built the temple to legitimize his position as 'son of Divus Julius' — son of a god"}, {"entity": "Imperial Cult", "relationship": "FOUNDING_MONUMENT_OF", "note": "Temple established the precedent for emperor apotheosis that shaped Roman Imperial religion for 400 years"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Temple of Divus Julius — establishing the precedent for mortal apotheosis, legitimizing Augustus's regime, creating the imperial cult model that shaped Roman and subsequently European political-religious ideology — is one of the most politically consequential sacred monuments in Western history.", "significanceCategory": "world-changing"},
    }),
    ("temple-of-apollo-sosianus", {
        "summary": "The Temple of Apollo Sosianus in Rome (also known as Temple of Apollo Medicus), one of Rome's oldest Apolline temples (originally founded c. 431 BCE, the second temple built to Apollo in Rome), rebuilt magnificently by Gaius Sosius (consul 32 BCE) using Greek spoils — including Greek sculptures looted from conquered territories — is notable as one of the few surviving Republican-era temple structures in Rome with three standing columns still visible today in the Campo Marzio.\n\nThe temple was significant in the context of late Republican and Augustan Rome as a monument of cultural appropriation: Sosius's rebuilding incorporated Greek sculptures (including a 5th-century BCE work attributed to the workshop of Pheidias depicting Heracles) into an explicitly Roman religious monument, demonstrating Rome's pattern of absorbing Greek culture while asserting Roman dominance. Augustus associated Apollo particularly closely with himself (the Battle of Actium was on the Apolline cape Actium), and the Apollo Sosianus temple sat within the Campus Martius near his own Mausoleum.\n\nArchaeologically, the Temple of Apollo Sosianus is valuable because its three standing Corinthian columns (from Sosius's c. 33-20 BCE reconstruction) preserve some of the most complete surviving examples of Late Republican temple architecture. The sculptural program of the pediment (fragments in the Capitoline Museums) depicted a Triumphal procession — one of the most detailed representations of a Roman triumph in sculpture — making it a key document for Roman iconographic programs.",
        "causes": ["c. 431 BCE founding as Rome's early Apolline cult site during Samnite Wars plague", "Sosius's c. 33-20 BCE rebuilding using Greek spoils and sculptures looted from conquered territories", "Apollo's association with Augustus following Actium making Apolline temples politically significant", "Survival of three Corinthian columns as rare intact example of Late Republican Roman temple architecture"],
        "effects": ["Pediment sculptures (now Capitoline Museums) as most detailed representation of Roman triumph in sculpture", "Three surviving Corinthian columns preserving Late Republican temple architectural techniques", "Greek sculptural appropriation demonstrating Rome's cultural absorption patterns", "Augustan Apolline building program using Apollo temples to legitimize Imperial ideology"],
        "relationships": [{"entity": "Augustus", "relationship": "POLITICALLY_ASSOCIATED_APOLLINE_MONUMENT", "note": "Augustus closely associated himself with Apollo; the temple's location near his Mausoleum reinforced this"}, {"entity": "Gaius Sosius", "relationship": "REBUILT_BY", "note": "Sosius rebuilt the temple c. 33-20 BCE using spoils from his eastern military campaigns"}, {"entity": "Capitoline Museums", "relationship": "PEDIMENT_SCULPTURES_NOW_IN", "note": "The temple's triumphal pediment sculptures (key Roman iconographic document) are now in the Capitoline Museums"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Temple of Apollo Sosianus — preserving three of Rome's few standing Republican-era temple columns, housing pediment sculptures that are the most detailed depiction of a Roman triumph, and demonstrating Roman cultural appropriation of Greek art — is a key archaeological monument for understanding Late Republican Rome.", "significanceCategory": "regional"},
    }),
    ("temple-of-hera-olympia", {
        "summary": "The Temple of Hera at Olympia (Heraion of Olympia) in the Peloponnese, built c. 600 BCE — making it one of the oldest surviving monumental Greek temples — was originally a joint temple to both Hera and Zeus before Zeus received his own separate colossal temple (c. 460 BCE). The Heraion is archaeologically revolutionary: it shows the transition from wooden to stone columns in the most direct way possible — some columns were still wooden when the classical traveler Pausanias visited in the 2nd century CE, preserving the history of Greek architectural development within a single building.\n\nOlympia was the site of the ancient Olympic Games (traditionally begun 776 BCE), and the Temple of Hera housed some of antiquity's most precious objects: the famous archaic Hermes of Praxiteles (or its Praxiteles school) was found here, and the chest of Cypselus (an elaborate cedar chest described by Pausanias) was kept in the temple. The Hermes of Praxiteles — if genuine — would be the only original marble statue by a great 4th-century BCE Greek master in existence, making it one of the most debated works in ancient art history.\n\nThe Temple of Hera is also the origin point for the modern Olympic torch relay: the Hestia altar within the Heraion precinct is where the Olympic flame is kindled by a high priestess using a parabolic mirror to concentrate sunlight, preserving the ancient sacred fire tradition. This ceremony — revived for the 1936 Berlin Olympics and continued ever since — connects the modern Olympic movement directly to the ancient Heraion of Olympia.",
        "causes": ["c. 600 BCE construction as one of Greece's earliest stone temples demonstrating wooden-to-stone architectural transition", "Olympia's role as site of Olympic Games (traditionally 776 BCE) making the Heraion central to pan-Hellenic religion", "Housing the Hermes of Praxiteles (if genuine) as only surviving original marble by a great classical master", "Modern Olympic torch relay kindled at Hestia altar perpetuating ancient sacred fire tradition"],
        "effects": ["Transition from wooden to stone columns preserved within single building as unique architectural-historical document", "Hermes of Praxiteles discovery as most-debated work in ancient art history", "Olympic flame ceremony (revived 1936) connecting modern Olympics to ancient Heraion tradition", "Oldest surviving monumental Greek temple establishing baseline for understanding Archaic temple design"],
        "relationships": [{"entity": "Olympic Games", "relationship": "SACRED_CENTER_OF", "note": "The Heraion was at the heart of Olympia — site of the ancient Olympic Games since traditionally 776 BCE"}, {"entity": "Hermes of Praxiteles", "relationship": "FIND_SITE_OF", "note": "The Hermes statue was found in the Heraion in 1877, potentially the only original marble by Praxiteles"}, {"entity": "Modern Olympic Torch Relay", "relationship": "CEREMONIAL_ORIGIN_POINT_OF", "note": "The Olympic flame is kindled at the Hestia altar in the Heraion precinct before every modern Olympics"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Temple of Hera at Olympia — Greece's oldest surviving monumental temple, site of the Hermes of Praxiteles, origin point of the modern Olympic torch relay, and a unique record of wooden-to-stone architectural transition — is one of the most historically layered sacred sites in the ancient world.", "significanceCategory": "world-changing"},
    }),
    ("construction-of-prambanan-the-largest-hi", {
        "summary": "Prambanan Temple Compounds in Central Java, Indonesia — constructed c. 850 CE by the Hindu Mataram Kingdom (specifically attributed to King Rakai Pikatan or his successor Lokapala) — is the largest Hindu temple complex in Indonesia and one of the greatest Hindu temples in Southeast Asia, dedicated to the Trimurti (Brahma, Vishnu, Shiva) with the central Shiva temple rising 47 meters, making it one of the tallest Hindu temples ever built. UNESCO World Heritage Site since 1991.\n\nPrambanan's construction represented the assertion of Hindu political and religious power in Java at a time when both Hindu and Buddhist kingdoms competed for dominance: the Mataram Hindu dynasty built Prambanan partly in response to the Buddhist Sailendra dynasty's Borobudur (completed c. 825 CE). The complex originally consisted of 240 temples; the Shiva Mahadeva temple at its center is a masterpiece of Hindu temple architecture, with the Ramayana reliefs on its balustrade (totaling 1,500 relief panels across the compound) constituting one of the most extensive Ramayana narrative sculptures in the world.\n\nPrambanan was abandoned after a volcanic eruption and earthquake c. 930 CE caused the Mataram court to move east, and the temples collapsed over centuries (a major earthquake in 1549 toppled most spires). Dutch colonial reconstruction began in 1918; modern UNESCO-supported restoration continues. The 2006 Yogyakarta earthquake caused additional damage. Prambanan today remains an active Hindu temple and pilgrimage site for the small Balinese Hindu community and for Javanese visitors, while also being one of Indonesia's most visited tourist sites.",
        "causes": ["c. 850 CE Mataram Hindu Kingdom construction as assertion of Hindu dominance over Buddhist Sailendras", "King Rakai Pikatan's political motivation to rival Borobudur (Buddhist) with a Hindu mega-complex", "Trimurti theology making Prambanan a theological statement about Hindu cosmic order", "UNESCO World Heritage designation (1991) protecting one of Southeast Asia's greatest Hindu complexes"],
        "effects": ["1,500 Ramayana relief panels constituting one of the world's most extensive Ramayana narrative sculptures", "Shiva Mahadeva temple at 47 meters among the tallest Hindu temples ever built", "Prambanan as physical evidence of Hindu-Buddhist dynastic competition in 9th-century Java", "Active pilgrimage site for Indonesian Hindus connecting modern Bali-Java Hindu tradition to 9th-century origins"],
        "relationships": [{"entity": "Borobudur", "relationship": "BUILT_AS_HINDU_COUNTERPART_TO", "note": "Prambanan was built c. 850 CE partly to rival the Buddhist Borobudur — both are World Heritage Sites in Central Java"}, {"entity": "Ramayana", "relationship": "1500_PANEL_RELIEF_NARRATIVE_OF", "note": "The balustrade of Prambanan's temples contains 1,500 panels depicting the Ramayana — one of the world's most extensive"}, {"entity": "Mataram Kingdom", "relationship": "BUILT_BY", "note": "The Hindu Mataram Kingdom built Prambanan c. 850 CE as its greatest religious monument"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "Prambanan — the largest Hindu temple complex in Indonesia, a theological and political monument rivaling Buddhist Borobudur, containing one of the world's most extensive Ramayana relief sculptures, and a UNESCO World Heritage Site — is Southeast Asia's greatest Hindu architectural achievement.", "significanceCategory": "world-changing"},
    }),
    ("five-pagoda-temple-of-hohhot", {
        "summary": "The Five Pagoda Temple (Wuta Si) in Hohhot, Inner Mongolia, China, built in 1732 CE during the Qing dynasty's reign of the Yongzheng Emperor, is a unique architectural monument combining Indian-style vajra throne (diamond throne) design — a form originating in Buddhist India (the Bodh Gaya Mahabodhi Temple) — with Chinese architectural decoration, making it one of the finest examples of the synthesis between Tibetan-Mongolian Buddhism and Chinese imperial architecture.\n\nThe Five Pagoda Temple's most remarkable feature is its southern wall relief, which contains an astronomical chart inscribed in Mongolian script — one of only three known astronomical charts written in Mongolian, and a unique document of Mongolian scientific knowledge during the Qing period. The chart depicts the celestial sphere with constellation positions translated into the Mongolian astronomical tradition, making it invaluable for historians of Inner Asian science.\n\nThe Five Pagoda Temple was built under the auspices of the Qing dynasty's policy of patronizing Tibetan-Mongolian Buddhism as a means of consolidating control over Mongolia and Tibet: the Qing emperors (particularly Qianlong) built extensive Buddhist monuments throughout Inner Mongolia and Beijing's Tibetan-style temples (such as Yong He Gong) as tools of imperial soft power. The Hohhot temple's diamond-throne design, modeled on Indian prototypes, represents the meeting point of Indian Buddhist theology, Tibetan religious art, Mongolian culture, and Chinese imperial architecture in a single building.",
        "causes": ["1732 CE Qing dynasty construction under Yongzheng Emperor as Imperial Buddhist patronage in Inner Mongolia", "Qing policy of patronizing Mongolian Buddhism to consolidate control over Mongolia and Tibet", "Diamond-throne (vajra throne) architectural form transmitted from India via Tibet and Mongolia", "Mongolian astronomical chart inscription preserving unique scientific knowledge in Mongolian script"],
        "effects": ["Mongolian-script astronomical chart (one of only three known) as unique Inner Asian scientific document", "Diamond-throne architectural synthesis combining Indian Buddhist design with Chinese decorative tradition", "Qing Buddhist patronage model demonstrating imperial soft power through religious architecture", "Hohhot monument as tangible evidence of Buddhism's transmission from India through Tibet to Inner Mongolia"],
        "relationships": [{"entity": "Qing Dynasty", "relationship": "BUILT_BY_AS_IMPERIAL_POLICY", "note": "Qing emperors built Mongolian Buddhist temples including Hohhot's Five Pagoda Temple to control Inner Mongolia"}, {"entity": "Tibetan Buddhism", "relationship": "ARCHITECTURAL_AND_THEOLOGICAL_TRADITION_OF", "note": "The diamond-throne design and Tibetan-Mongolian Buddhist iconography define the Five Pagoda Temple's character"}, {"entity": "Mongolian Astronomical Tradition", "relationship": "UNIQUE_DOCUMENT_OF", "note": "The southern wall's Mongolian-script astronomical chart is one of only three known such documents"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Five Pagoda Temple of Hohhot — synthesizing Indian Buddhist, Tibetan, Mongolian, and Chinese architectural traditions, preserving one of only three known Mongolian astronomical charts, and embodying the Qing dynasty's Buddhist soft-power policy in Inner Mongolia — is a unique document of cultural synthesis at the intersection of four civilizations.", "significanceCategory": "continental"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 108 — Class 343 Temples II: Ancient & Sacred Temples")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
