#!/usr/bin/env python3
"""Batch 97 — Class 312 Dynasties VII (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/312-Class-312"
FILE_PREFIX = "312"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("al-bu-said-dynasty", {
        "summary": "The Al-Bu Said dynasty, founded 1744 in Oman by Ahmad ibn Said Al-Bu Said after driving out the Persian Afsharid occupation, is the ruling dynasty of the Sultanate of Oman — the oldest continuously ruling dynasty in the Arab world and one of the world's longest-reigning royal families. The dynasty established Oman as a major maritime empire in the 18th-19th centuries, controlling Zanzibar, the East African coast (Mombasa, Malindi), and trading posts in the Persian Gulf and India, making Muscat the dominant Indian Ocean commercial hub for a century.\n\nAhmad ibn Said's 1744 expulsion of Persian forces and election as Imam of Oman established the dynasty; his successors expanded maritime power dramatically. Sayyid Said bin Sultan (r. 1804-1856) moved the capital to Zanzibar in 1840, making it the center of the East African clove trade and the largest slave market in the Indian Ocean — Zanzibar exported 50,000-60,000 enslaved people annually at its peak. After Said's death, the empire split into Oman (under one son) and Zanzibar (under another), with Britain arbitrating the division in 1861.\n\nSultan Qaboos bin Said (r. 1970-2020) — who overthrew his isolationist father in a 1970 British-backed coup — transformed Oman from one of the world's most underdeveloped countries (only 3 schools, 10 km of paved roads in 1970) into a modern state using oil revenues, while maintaining Oman's tradition of balanced foreign policy ('Omani diplomacy') serving as mediator between the US and Iran. Qaboos's 50-year rule is considered the most successful modernization program in Gulf history.",
        "causes": ["1744 Ahmad ibn Said founding after expelling Persian Afsharid forces from Oman", "19th-century Zanzibar empire building as Indian Ocean maritime trading and slave trade center", "1861 empire division into Oman and Zanzibar sultanates after Sayyid Said's death", "1970 Sultan Qaboos coup launching rapid modernization from extreme underdevelopment"],
        "effects": ["Oldest continuously ruling dynasty in Arab world spanning 280+ years", "19th-century Zanzibar as largest Indian Ocean slave market exporting 50,000-60,000 annually", "Qaboos 50-year modernization from 3 schools to modern state using oil revenues", "Omani diplomacy model as mediator between US and Iran in 21st-century Gulf tensions"],
        "relationships": [{"entity": "Ahmad ibn Said", "relationship": "FOUNDED_BY", "note": "Ahmad expelled Persian forces in 1744 and was elected Imam of Oman founding the dynasty"}, {"entity": "Sultan Qaboos", "relationship": "MOST_TRANSFORMATIVE_RULER", "note": "Qaboos's 1970-2020 rule transformed Oman from extreme underdevelopment to modern Gulf state"}, {"entity": "Zanzibar", "relationship": "CONTROLLED_EMPIRE_INCLUDING", "note": "Sayyid Said moved capital to Zanzibar 1840; 19th-century clove trade and slave market hub"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Al-Bu Said dynasty — ruling Oman for 280+ years as the Arab world's oldest continuous dynasty — achieved both the 19th century's most powerful Indian Ocean maritime empire (Zanzibar) and the 20th century's most dramatic Gulf modernization (Qaboos transforming 3-school Oman to modern state in 50 years).", "significanceCategory": "continental"},
    }),
    ("alawi-dynasty", {
        "summary": "The Alawi dynasty (Alaouite dynasty), founded in Morocco in 1631 when Moulay al-Sharif became the first Alawi Sultan of Tafilalt, is the reigning dynasty of the Kingdom of Morocco — the world's oldest continuously reigning royal family from Africa, ruling for 393+ years (longer than any European dynasty). The Alawis trace descent from the Prophet Muhammad through his grandson Hassan, giving the Moroccan monarchy its religious legitimacy (Commander of the Faithful — Amir al-Mu'minin). Morocco has never been colonized by a Muslim power and the Alawi dynasty represents an unbroken indigenous sovereignty.\n\nThe dynasty consolidated Moroccan sovereignty in the 17th-18th centuries, resisting Ottoman expansion while the rest of North Africa became Ottoman provinces — Morocco remains the only North African country that was never Ottoman-controlled. Sultan Muhammad III (r. 1757-1790) was the first foreign head of state to recognize the United States (1777), establishing the Morocco-US Treaty of Friendship (1786) — the oldest unbroken bilateral treaty in US history.\n\nFrance established a protectorate over Morocco (1912-1956) but did not depose the Alawi sultans — instead ruling through them, then exiling Sultan Muhammad V (1953) after his nationalist stance, then restoring him (1955) as nationalist pressure grew. Muhammad V became King at independence (1956); Hassan II (r. 1961-1999) ruled Morocco through the Cold War 'Years of Lead' using emergency power. Muhammad VI (r. 1999-present) has pursued gradual liberalization. Morocco is the world's largest phosphate reserve holder and a major agricultural exporter.",
        "causes": ["1631 Moulay al-Sharif founding Alawi rule in Tafilalt with Sharifian Islamic legitimacy", "17th-18th century resistance to Ottoman expansion keeping Morocco the only non-Ottoman North Africa country", "1777 first-nation US recognition establishing oldest unbroken US bilateral treaty", "French protectorate 1912-1956 ruling through (then exiling, then restoring) Alawi sultans"],
        "effects": ["393+ year Alawi rule as world's longest ruling African dynasty", "Morocco's unique non-Ottoman North African sovereignty distinguishing it from all regional neighbors", "1786 Morocco-US Treaty of Friendship as oldest unbroken bilateral treaty in US history", "Muhammad VI's 1999-present liberalization program modernizing Moroccan governance"],
        "relationships": [{"entity": "Muhammad V of Morocco", "relationship": "NATIONALIST_SULTAN", "note": "Muhammad V's independence stance led to French exile (1953) and restoration (1955) then independence (1956)"}, {"entity": "United States", "relationship": "FIRST_RECOGNIZER_OF", "note": "Morocco was first state to recognize US in 1777; 1786 treaty is oldest US bilateral treaty"}, {"entity": "Ottoman Empire", "relationship": "RESISTED_EXPANSION_OF", "note": "Alawi Morocco uniquely resisted Ottoman control — the only non-Ottoman North African country"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Alawi dynasty — world's longest-ruling African dynasty, first to recognize the United States, and unique in resisting Ottoman expansion that absorbed all other North African states — represents the most durable non-European sovereignty in Africa and the first official international recognition of American independence.", "significanceCategory": "world-changing"},
    }),
    ("amarna-period", {
        "summary": "The Amarna Period (c. 1353-1336 BCE) is the 17-year reign of Egyptian Pharaoh Amenhotep IV (who renamed himself Akhenaten) during which he abolished the traditional Egyptian pantheon, established the monotheistic worship of the Aten (solar disk), moved the capital from Thebes to a new city (Akhetaten, modern Amarna), and commissioned an entirely new artistic style (Amarna art) — elongated, naturalistic, domestic — that was obliterated by his successors, making the Amarna Period one of history's most dramatic and completely reversed religious and cultural revolutions. Some scholars consider Akhenaten the world's first monotheist.\n\nAkhenaten's reforms (from Year 5 of his reign) closed temples of all gods except the Aten, redistributed their vast wealth to the crown, and required all religious worship through the pharaoh as the Aten's sole earthly intermediary. His wife Nefertiti may have been co-ruler; the famous 'Berlin Nefertiti' bust (c. 1345 BCE, discovered 1912) is considered one of the greatest portrait sculptures in history. Akhenaten's capital Akhetaten was built in 17 years on virgin desert; abandoned within a decade of his death.\n\nTutankhamun (Akhenaten's son or son-in-law, r. c. 1332-1323 BCE) reversed all Amarna reforms — restoring the Amun priesthood, abandoning Amarna, and erasure of Akhenaten's name from monuments — so completely that Akhenaten was forgotten for 3,000 years until 19th-century archaeological discovery. The Amarna Letters (382 clay tablets, diplomatic correspondence between Egypt and Near Eastern powers) are the most important diplomatic archive from the ancient world, revealing the geopolitics of the Late Bronze Age international system.",
        "causes": ["Amenhotep IV (Akhenaten) Year 5 abolition of traditional Egyptian pantheon and Aten monotheism", "Capital move from Thebes to new Akhetaten (Amarna) built in 17 years on virgin desert", "Amarna art revolution — naturalistic, domestic, elongated style replacing traditional Egyptian canon", "Post-Akhenaten erasure by Tutankhamun and successors obliterating all Amarna-period records"],
        "effects": ["World's first possible monotheistic state religion experiment — preceding Mosaic Judaism", "Amarna Letters (382 tablets) as most important ancient diplomatic archive of Late Bronze Age", "Berlin Nefertiti bust as one of history's greatest portrait sculptures", "3,000-year obliteration of Akhenaten's memory until 19th-century archaeological rediscovery"],
        "relationships": [{"entity": "Akhenaten", "relationship": "REIGN_OF", "note": "Akhenaten's 17-year reign created and destroyed Amarna Period's revolutionary monotheistic experiment"}, {"entity": "Nefertiti", "relationship": "QUEEN_CONSORT_POSSIBLY_CO-RULER", "note": "Nefertiti possibly co-ruled; Berlin Nefertiti bust is one of history's greatest portrait sculptures"}, {"entity": "Tutankhamun", "relationship": "REVERSED_BY", "note": "Tutankhamun restored traditional polytheism, abandoned Amarna, and erased Akhenaten's name"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Amarna Period — the world's first possible state-imposed monotheism, an entirely new capital, an entirely new art style, and the most complete political erasure in ancient history — represents the most radical cultural revolution in Egyptian civilization and a possible prototype for all later monotheistic traditions.", "significanceCategory": "world-changing"},
    }),
    ("amorian-dynasty", {
        "summary": "The Amorian dynasty (Phrygian dynasty), founded 820 CE by Michael II of Amorion (from the Phrygian city of Amorion), ruled the Byzantine Empire for three generations (820-867 CE) through one of its most turbulent periods — the final phase of Byzantine Iconoclasm and its resolution, the emergence of the Bulgarian Khanate as an existential threat, and the missions of Constantine (Cyril) and Methodius that created the Cyrillic alphabet and brought Christianity to the Slavs. Michael III (the 'Drunkard') was assassinated by Basil the Macedonian, ending the dynasty and beginning the greatest Byzantine imperial era.\n\nMichael II (820-829 CE) was a soldier from Amorion who had been imprisoned and was scheduled for execution when he led a coup against Leo V; his guards interrupted the emperor's Christmas morning church service. Michael restored a moderate form of Iconoclasm (the second Iconoclasm phase). His son Theophilos (829-842 CE) was the last Iconoclast emperor — an educated, aesthetically sophisticated ruler who enforced Iconoclasm while admiring Islamic art.\n\nEmpress Theodora (widow of Theophilos, regent for Michael III) ended Iconoclasm in 843 CE — the 'Triumph of Orthodoxy,' still celebrated annually in Eastern Orthodox Christianity on the first Sunday of Lent. Michael III (842-867 CE) invited Constantine (Cyril) and Methodius to create an alphabet for the Slavic languages — producing the Glagolitic (later Cyrillic) alphabet — and authorized their mission to Moravia (863 CE) that created Slavic Christian civilization. Basil I assassinated Michael III in 867 CE, founding the Macedonian dynasty.",
        "causes": ["820 CE Michael II coup from prison creating dynasty in extraordinary circumstances", "Empress Theodora's 843 CE Triumph of Orthodoxy ending Byzantine Iconoclasm", "Constantine (Cyril) and Methodius mission to Moravia creating Slavic alphabet and Christianization", "867 CE Basil I assassination of Michael III ending dynasty and founding Macedonian era"],
        "effects": ["843 CE Triumph of Orthodoxy celebrated annually as first Sunday of Lent in Eastern Christianity", "Cyrillic alphabet creation enabling Slavic Christian civilization across Eastern Europe and Russia", "Slavic Christianization from Michael III's era shaping Russian and Eastern European cultural identity", "Macedonian dynasty founding by assassin creating Byzantine golden age after Amorian instability"],
        "relationships": [{"entity": "Empress Theodora", "relationship": "REGENT_WHO_ENDED_ICONOCLASM", "note": "Theodora's 843 CE Triumph of Orthodoxy ending Iconoclasm is still celebrated as Orthodox feast"}, {"entity": "Constantine (Cyril)", "relationship": "COMMISSIONED_SLAVIC_MISSION", "note": "Michael III commissioned Cyril and Methodius to create Slavic alphabet and Christianize Moravia"}, {"entity": "Basil I", "relationship": "SUCCEEDED_BY_ASSASSIN", "note": "Basil I assassinated Michael III in 867 CE, founding the Macedonian dynasty's golden age"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Amorian dynasty — through Empress Theodora's ending of Iconoclasm and Michael III's commissioning of Cyril and Methodius — created two of Byzantine civilization's most durable legacies: the Orthodox Triumph feast still celebrated annually, and the Cyrillic alphabet shaping the written culture of 250 million people.", "significanceCategory": "continental"},
    }),
    ("ancient-china", {
        "summary": "Ancient China refers to Chinese civilization from its earliest known organized states (Xia dynasty, c. 2070 BCE, if historical) through the Shang (c. 1600-1046 BCE) and Zhou (1046-256 BCE) dynasties — the formative period when Chinese writing, bronze metallurgy, silk production, ancestor worship, the Mandate of Heaven political theology, Confucianism, Daoism, and Legalism were established, creating the cultural, philosophical, and political foundations that shaped Chinese civilization for 4,000 years. The Zhou's Spring and Autumn period (771-476 BCE) was China's 'Axial Age' — producing Confucius, Laozi, and Sunzi simultaneously.\n\nThe Shang dynasty (c. 1600-1046 BCE) produced oracle bone script (the earliest confirmed Chinese writing), massive bronze ritual vessels (the Simuwu Ding is a Shang creation), horse-drawn chariots, and systematic ancestor worship. Shang kings communicated with ancestors through oracle bones — tortoise shells or ox scapulae heated until cracked, with cracks interpreted as divine answers. The Zhou overthrew the Shang (1046 BCE) using the 'Mandate of Heaven' (tianming) theology: rulers lose heaven's mandate through immoral governance, justifying revolution.\n\nThe Zhou Spring and Autumn Period (771-476 BCE) saw the 'Hundred Schools of Thought' — Confucius (551-479 BCE) teaching moral self-cultivation and ethical governance; Laozi (6th century BCE, if historical) teaching the Dao; Sunzi (544-496 BCE) writing The Art of War. These texts — the Analects, the Tao Te Ching, and The Art of War — are among the most influential books in world history. The Warring States Period (475-221 BCE) ended with Qin unification creating Imperial China.",
        "causes": ["Shang dynasty oracle bone script creating China's earliest confirmed writing system", "Zhou Mandate of Heaven theology creating political legitimacy framework for 3,000 years", "Spring and Autumn Period Confucius, Laozi, Sunzi producing most influential Chinese philosophical texts", "Warring States Period competition producing Legalism that unified China under Qin"],
        "effects": ["Chinese writing system continuous 3,300-year development from oracle bones to modern characters", "Mandate of Heaven theology justifying dynastic cycles throughout all Chinese imperial history", "Confucianism shaping Chinese, Korean, Japanese, Vietnamese governance philosophy for 2,500 years", "The Art of War as most widely read military strategy text in world history"],
        "relationships": [{"entity": "Confucius", "relationship": "PHILOSOPHICAL_TRADITION_FOUNDED_DURING", "note": "Confucius (551-479 BCE) founded Confucianism during Zhou Spring and Autumn Period"}, {"entity": "Oracle Bone Script", "relationship": "WRITING_SYSTEM_DEVELOPED", "note": "Shang dynasty oracle bones are earliest confirmed Chinese writing — foundation of all later Chinese script"}, {"entity": "Zhou Dynasty", "relationship": "POLITICAL_THEOLOGY_ESTABLISHED_BY", "note": "Zhou's Mandate of Heaven theology shaped Chinese political legitimacy for 3,000 years"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "Ancient China — establishing Chinese writing, Mandate of Heaven, Confucianism, Daoism, and Legalism simultaneously during the Zhou Axial Age — created the philosophical and political foundations that governed the world's most populous civilization for 4,000 years, making it one of the most consequential cultural formations in human history.", "significanceCategory": "world-changing"},
    }),
    ("al-rashid", {
        "summary": "The Al-Rashid dynasty of Ha'il (Emirate of Jabal Shammar), founded 1836 by Abdullah ibn Rashid in the Najd region of central Arabia, was the main rival to the Al-Saud dynasty in the 19th and early 20th centuries — capturing Riyadh and expelling the Al-Saud in 1891, ruling most of northern and central Arabia for decades, and finally being absorbed by Ibn Saud's reconquering Al-Saud when the Emirate of Ha'il fell to Saudi forces in 1921. The Al-Rashid briefly appeared to be the dynasty that would unite the Arabian Peninsula.\n\nAbdullah ibn Rashid established the Emirate of Jabal Shammar in the 1830s as a client of the Egyptian Muhammad Ali's expanding influence in Arabia, then achieved independence. His successors — particularly Muhammad ibn Rashid (r. 1869-1897, the 'Lion of the Najd') — expanded the emirate to its peak: capturing Riyadh (1891), expelling the Al-Saud, and controlling territory from the Hejaz border to the Persian Gulf coast. Muhammad ibn Rashid is considered one of the greatest Arab military commanders of the 19th century.\n\nThe emirate's decline resulted from repeated succession crises (multiple amirs assassinated by relatives) and the resurgent Al-Saud under Ibn Saud (Abdulaziz ibn Saud), who captured Riyadh in 1902 with 40 men and systematically reconquered Najd. Ha'il fell in 1921 after a siege; the last Amir Saud ibn Rashid surrendered. The Al-Rashid family was relocated to Riyadh under house arrest (later integrated into Saudi elite). The rivalry is a foundational narrative of modern Saudi state-formation.",
        "causes": ["1836 Abdullah ibn Rashid founding of Emirate of Jabal Shammar in Najd central Arabia", "1891 Muhammad ibn Rashid capture of Riyadh and expulsion of Al-Saud at emirate's peak", "Repeated succession crises and amiral assassinations weakening emirate's stability", "1921 Ibn Saud capture of Ha'il ending emirate and completing Saudi state formation"],
        "effects": ["19th-century main rival to Al-Saud revealing that modern Saudi Arabia was not inevitable", "1902 Ibn Saud's Riyadh reconquest narrative as founding myth of Saudi state", "Al-Rashid family integration into Saudi elite creating cross-dynastic reconciliation model", "Ha'il as historical center preserving pre-Saudi Arabian tribal political culture"],
        "relationships": [{"entity": "Muhammad ibn Rashid", "relationship": "GREATEST_RULER", "note": "Muhammad (1869-1897) conquered Riyadh, expelled Al-Saud, and built emirate to its territorial peak"}, {"entity": "Al-Saud Dynasty", "relationship": "PRIMARY_RIVAL_OF", "note": "Al-Rashid expelled Al-Saud in 1891; Ibn Saud reconquered Ha'il in 1921 ending the rivalry"}, {"entity": "Ibn Saud", "relationship": "CONQUERED_BY", "note": "Ibn Saud's 1921 Ha'il siege ended the emirate and absorbed Al-Rashid into Saudi governance"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Al-Rashid dynasty of Ha'il — briefly capturing Riyadh and controlling most of Arabia — reminds that the Saudi state's eventual dominance was contingent: the Arabian Peninsula might have been unified under the Rashidis instead, with profound consequences for 20th-century Islam and oil history.", "significanceCategory": "regional"},
    }),
    ("al-fayez", {
        "summary": "The Al-Fayez tribe and its ruling sheikhly family are one of Jordan's most prominent Bedouin tribal lineages — the paramount sheikhs of the Bani Sakhr confederation, historically the most powerful tribal group of Transjordan, who controlled the trade routes between Damascus and the Hejaz, resisted Ottoman taxation, and became one of the first tribes to recognize Emir Abdullah I's Hashemite authority in 1921, forming the bedrock of Jordanian tribal loyalty that has sustained the Hashemite monarchy for a century.\n\nThe Bani Sakhr confederation — historically occupying the black basalt desert of eastern Transjordan — were renowned horse breeders, skilled warriors, and controllers of the caravan routes between Syria and the Hejaz. Their Al-Fayez sheikhs negotiated with Crusaders, Mamluks, Ottomans, and British successively, maintaining tribal autonomy through alliance-switching and armed resistance. Their camels and horses were prized throughout the Arab world.\n\nAl-Fayez and Bani Sakhr recognition of Emir Abdullah I's authority in 1921 was pivotal: tribal confederation support legitimized the new Hashemite emirate at its most vulnerable founding moment. The Al-Fayez family has provided officers in the Jordan Arab Army, members of parliament, and government ministers across the 20th century — maintaining the traditional relationship between Hashemite monarchy and Jordan's tribal bedrock. Sheikh Akef Al-Fayez served in multiple Jordanian parliamentary and ministerial positions.",
        "causes": ["Pre-Islamic Bani Sakhr tribal confederation controlling Transjordan caravan routes from Damascus to Hejaz", "Al-Fayez paramount sheikhly status in Bani Sakhr as military and diplomatic power brokers", "1921 Hashemite recognition by Al-Fayez providing crucial tribal legitimacy for Jordan's founding", "Continuous Al-Fayez parliamentary and ministerial service sustaining tribal-monarchy compact"],
        "effects": ["Hashemite monarchy's founding tribal legitimacy provided by Al-Fayez and Bani Sakhr recognition", "Tribal-monarchy compact model sustaining Jordan through 100 years of regional instability", "Al-Fayez parliamentary and ministerial participation integrating tribal governance into modern state", "Bani Sakhr horse-breeding tradition preserving Arabian horse bloodlines prized globally"],
        "relationships": [{"entity": "Bani Sakhr", "relationship": "PARAMOUNT_SHEIKHS_OF", "note": "Al-Fayez are hereditary paramount sheikhs of Bani Sakhr — Jordan's most powerful tribal confederation"}, {"entity": "Abdullah I of Jordan", "relationship": "LEGITIMIZED_BY_RECOGNITION_OF", "note": "Al-Fayez recognition of Emir Abdullah I in 1921 provided crucial tribal legitimacy for Hashemite rule"}, {"entity": "Hashemite Kingdom of Jordan", "relationship": "TRIBAL_FOUNDATION_OF", "note": "Al-Fayez–Bani Sakhr tribal compact has sustained Jordanian Hashemite monarchy for 100 years"}],
        "historicalSignificance": {"significanceScore": 5, "significanceNarrative": "The Al-Fayez family — paramount sheikhs of Jordan's most powerful tribal confederation — demonstrates how in states with shallow institutional histories, individual tribal families can determine the survival or failure of entire regimes, with their 1921 recognition of Abdullah I directly enabling the Hashemite monarchy's century of rule.", "significanceCategory": "regional"},
    }),
    ("alids", {
        "summary": "The Alids (Alawids / descendants of Ali ibn Abi Talib) are the descendants of the fourth Caliph Ali ibn Abi Talib and his wife Fatima (daughter of the Prophet Muhammad) — the lineage from which Shi'a Islam derives its imams and from which dozens of ruling dynasties have claimed legitimacy across 1,400 years of Islamic history. The Alid claim to leadership (based on prophetic descent) versus the Umayyad/Abbasid claim (based on tribal seniority and political power) was the foundational schism of Islam, generating Shi'a theology, the Fatimid Caliphate, the Safavid Empire, and modern Iran.\n\nAli ibn Abi Talib (c. 600-661 CE) was the Prophet Muhammad's cousin and son-in-law; his supporters (Shi'at Ali — 'partisans of Ali') contested the first three caliphates as illegitimate, arguing that leadership should pass through Muhammad's family (ahl al-bayt). Ali became the fourth Caliph (656-661 CE) but was assassinated; his son Hasan renounced the caliphate; his son Husayn was killed with 72 companions at Karbala (680 CE) — the foundational trauma of Shi'a Islam, commemorated in Ashura.\n\nAlid dynasties include: Fatimids (909-1171, Tunisia/Egypt — claiming descent through Fatima), Zaydi imamates (still governing Yemen through 1962 and the Houthi movement today), Hasanid dynasties (Morocco's Alawi dynasty claims Hasanid descent), Idrisids of Morocco (788-985 CE), and the Safavids (who claimed Alid descent to legitimize their Shi'a Persian state). The 12 Imams of Twelver Shi'a Islam (the largest Shi'a branch, dominant in Iran, Iraq, and Lebanon) are all Alids — the Twelfth Imam (Muhammad al-Mahdi) is believed to be in occultation since 874 CE, awaiting eschatological return.",
        "causes": ["Ali ibn Abi Talib's disputed succession to Muhammad generating Shi'a-Sunni split", "Husayn's Karbala martyrdom (680 CE) creating foundational Shi'a trauma and Ashura commemoration", "Alid legitimacy claims generating Fatimid, Zaydi, Hasanid, and Safavid dynasties", "Twelver Shi'a twelve-imam theology making Alid lineage the basis of Iranian Islamic Republic"],
        "effects": ["Shi'a-Sunni split — Islam's fundamental division — originating in Alid succession dispute", "Ashura annual commemoration as most emotionally intense religious observance in Muslim world", "Fatimid Caliphate (Egypt 969-1171) establishing Cairo and al-Azhar from Alid legitimacy claim", "Iranian Islamic Republic (1979-present) deriving theological authority from Alid Twelver Shi'a tradition"],
        "relationships": [{"entity": "Ali ibn Abi Talib", "relationship": "DESCENDED_FROM", "note": "Alids are Ali's descendants; his assassination and Husayn's Karbala death created Shi'a Islam"}, {"entity": "Husayn ibn Ali", "relationship": "KARBALA_MARTYRDOM_AS_FOUNDING_TRAUMA", "note": "Husayn's 680 CE death at Karbala is Shi'a Islam's foundational event — commemorated as Ashura"}, {"entity": "Fatimid Caliphate", "relationship": "ALID_DYNASTY_FOUNDED", "note": "Fatimids claimed Alid descent; founded Cairo (969 CE) and al-Azhar as Shi'a caliphate"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Alids — through the Shi'a-Sunni split their legitimacy claim generated — are the ancestral lineage responsible for Islam's most consequential internal division, shaping the Fatimid Caliphate, Safavid Empire, and Islamic Republic of Iran, and making the 680 CE Battle of Karbala the most politically influential martyrdom in world history.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 97 — Class 312 Dynasties VII")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
