#!/usr/bin/env python3
"""Batch 57 — Class 312 Ancient Dynasties II (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/312-Class-312"
FILE_PREFIX = "312"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("ming-dynasty", {
        "summary": "The Ming dynasty (1368–1644) was the last Han Chinese imperial dynasty, ruling one of the largest and most powerful nations in the world. Founded by Zhu Yuanzhang (the Hongwu Emperor) after overthrowing the Mongol Yuan dynasty, the Ming restored Han Chinese rule and presided over some of China's greatest architectural, literary, and exploratory achievements.\n\nThe Yongle Emperor's construction of the Forbidden City in Beijing (1406-1420) created the world's largest palace complex. Zheng He's seven naval expeditions (1405-1433) sent fleets of over 300 ships and 28,000 men to Southeast Asia, South Asia, Arabia, and East Africa — voyages far exceeding European exploration of the same era. China's decision to halt these expeditions and focus inward rather than colonizing has been called one of history's most consequential strategic choices.\n\nThe Great Wall's most recognized sections were built or restored during the Ming period. The Wanli Emperor's reign saw the printing of the Yongle Dadian encyclopedia (22,877 volumes) and the development of porcelain, silk, and lacquerware exported globally through trade. The dynasty fell in 1644 when rebel Li Zicheng captured Beijing and the last Ming emperor committed suicide, with the Manchu Qing dynasty filling the power vacuum.",
        "causes": ["Zhu Yuanzhang's peasant rebellion overthrowing the Mongol Yuan dynasty", "Han Chinese desire to restore ethnic Chinese rule after Mongol domination", "Yongle Emperor's usurpation creating political need for grand projects demonstrating legitimacy", "Agricultural recovery following Black Death and Mongol disruption enabling population growth"],
        "effects": ["Forbidden City became world's largest palace complex and center of Chinese power", "Zheng He voyages demonstrated Chinese naval supremacy and geopolitical reach", "Great Wall expansion created defensive infrastructure still standing today", "Ming porcelain became global luxury trade good shaping European collector culture"],
        "relationships": [{"entity": "Zhu Yuanzhang", "relationship": "FOUNDED_BY", "note": "Hongwu Emperor who overthrew Yuan dynasty and founded Ming in 1368"}, {"entity": "Zheng He", "relationship": "EMPLOYED", "note": "Muslim eunuch admiral who led 7 naval expeditions to Asia and Africa"}, {"entity": "Qing dynasty", "relationship": "SUCCEEDED_BY", "note": "Manchu Qing conquered Beijing in 1644 ending Ming rule"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Ming dynasty's decision to halt Zheng He's global voyages — forgoing a potential Chinese maritime empire — is one of history's great counterfactual turning points, as Europe instead built its colonial empires in the same era.", "significanceCategory": "world-changing"},
    }),
    ("mughal-dynasty", {
        "summary": "The Mughal Empire (1526–1857) was an Islamic empire that at its height controlled most of the Indian subcontinent, ruling over 150 million people — a quarter of the world's population. Founded by Babur, a prince from Fergana Valley (Uzbekistan) descended from Timur and Genghis Khan, the Mughals created an extraordinary synthesis of Persian, Turkic, and Indian cultures.\n\nAkbar the Great (r.1556-1605) expanded the empire to its greatest extent while implementing a policy of religious tolerance (Sulh-e-Kul, 'universal peace'), abolishing the jizya tax on Hindus, marrying Hindu Rajput princess Jodha Bai, and creating a composite Mughal-Rajput cultural synthesis. Akbar's court produced extraordinary painting, literature, and architecture, while his revenue system designed by finance minister Raja Todar Mal set the fiscal foundation for both Mughal prosperity and later British administration.\n\nShah Jahan (r.1628-1658) built the Taj Mahal as a mausoleum for his wife Mumtaz Mahal — one of history's supreme architectural achievements. At its peak, the Mughal Empire generated 25% of world GDP. Its decline under Aurangzeb's religious intolerance and subsequent fragmentation enabled British East India Company expansion that culminated in the 1857 Rebellion and formal dissolution of the dynasty.",
        "causes": ["Babur's military genius with artillery defeating Lodi Sultanate at First Battle of Panipat", "Timurid court culture providing sophisticated Persian-Islamic administrative model", "Akbar's genius for synthesis integrating Hindu elites into Mughal governance", "India's agricultural wealth generating tax revenues enabling architectural patronage"],
        "effects": ["Taj Mahal became India's most recognized monument and global symbol of love", "Mughal administrative system provided foundation for British Indian revenue collection", "Akbar's religious tolerance policy delayed Hindu-Muslim conflict for generations", "Mughal court culture created Indo-Persian literary, musical, and artistic synthesis"],
        "relationships": [{"entity": "Babur", "relationship": "FOUNDED_BY", "note": "Timurid prince who defeated Ibrahim Lodi at Panipat in 1526"}, {"entity": "Akbar", "relationship": "GREATEST_RULER", "note": "3rd emperor whose religious tolerance and administration defined Mughal golden age"}, {"entity": "Taj Mahal", "relationship": "COMMISSIONED", "note": "Shah Jahan built Taj Mahal 1631-1648 as mausoleum for wife Mumtaz Mahal"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Mughal Empire unified South Asia under sophisticated administration, created enduring monuments, and generated 25% of world GDP at its peak, leaving cultural legacies that define India's art, cuisine, language, and architecture today.", "significanceCategory": "world-changing"},
    }),
    ("gupta-empire-india", {
        "summary": "The Gupta Empire (c.320–550 CE) was an Indian empire that presided over what historians call the Golden Age of India, during which science, mathematics, astronomy, philosophy, and literature reached extraordinary heights. Founded by Chandragupta I in the Ganges plain, the Gupta period saw India lead the world in mathematical and scientific knowledge.\n\nAryabhata (476-550 CE), a Gupta-era mathematician and astronomer, calculated pi to four decimal places, explained lunar eclipses, stated the Earth rotates on its axis (over 1,000 years before Copernicus in Europe), and created the positional notation system that became the basis of modern decimal arithmetic. The 'Arabic numerals' that the world uses today originated as Indian numerals transmitted through Arab scholars. Brahmagupta's work on zero as a number laid the foundation for modern algebra.\n\nThe Gupta period also produced Kalidasa, considered India's greatest classical Sanskrit poet and dramatist, whose works Shakuntala and Meghaduta influenced Goethe and countless later writers. Gupta art, including the Ajanta cave paintings and Sarnath sculpture, represents the pinnacle of Indian classical aesthetics. The Guptas were tolerant Hindu rulers who patronized Buddhism and Jainism alongside Hinduism, creating a pluralistic cultural environment.",
        "causes": ["Chandragupta I's political marriage to Lichchhavi princess providing legitimacy", "Recovery of trade routes after Kushan and Saka disruptions providing wealth", "Geographic concentration in fertile Gangetic plain enabling efficient administration", "Brahmanical intellectual tradition providing philosophical and mathematical framework"],
        "effects": ["Indian mathematical innovations created decimal arithmetic and zero concept used globally", "Aryabhata's heliocentric model predated European discoveries by a millennium", "Gupta art style defined classical Indian aesthetics for all subsequent periods", "Sanskrit literary tradition reached its apex creating enduring literary classics"],
        "relationships": [{"entity": "Chandragupta I", "relationship": "FOUNDED_BY", "note": "Founded Gupta Empire c.320 CE in Magadha region"}, {"entity": "Aryabhata", "relationship": "PRODUCED_SCHOLAR", "note": "Mathematician-astronomer who calculated pi and explained eclipses"}, {"entity": "Samudragupta", "relationship": "EXPANDED_BY", "note": "Second ruler who extended empire through military campaigns and cultural patronage"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Gupta Golden Age produced the mathematical and astronomical innovations — decimal arithmetic, zero, positional notation — that became the foundation of global mathematics, making it one of history's most consequential intellectual eras.", "significanceCategory": "world-changing"},
    }),
    ("khmer-empire", {
        "summary": "The Khmer Empire (802–1431 CE) was the largest empire in Southeast Asian history, centered on the hydraulic civilization of Angkor in present-day Cambodia. At its height under Suryavarman II and Jayavarman VII, it controlled modern Cambodia, Thailand, Laos, and southern Vietnam, and built the largest religious monument complex in the world at Angkor Wat.\n\nAngkor Wat, built by Suryavarman II between 1113 and 1150 CE, is the world's largest religious monument — a stone temple mountain symbolizing Mount Meru, the cosmic center of Hindu cosmology. With perimeter walls enclosing over 400 acres and bas-reliefs covering 1,200 meters, it represents the apex of Khmer art and engineering. The broader Angkor complex encompassed over 1,000 temples within an urban area of 400 square kilometers — making it arguably the world's largest pre-industrial city.\n\nThe empire's hydraulic engineering — a massive system of reservoirs (barays), canals, and moats — enabled intensive rice cultivation supporting a population estimated at 750,000 to 1 million in Angkor alone. Jayavarman VII (r.1181-1218) converted to Mahayana Buddhism, building Angkor Thom with its face-tower Bayon and 102 hospitals across the empire. Thai Ayutthaya attacks in the 14th-15th centuries and possible hydraulic system failure contributed to Angkor's abandonment around 1431.",
        "causes": ["Jayavarman II's declaration of independence from Java establishing Khmer sovereignty in 802", "Fertile Mekong Delta providing agricultural surplus for urban civilization", "Hindu cosmology providing template for monumental temple-mountain architecture", "Sophisticated hydraulic engineering enabling irrigation and flood control"],
        "effects": ["Angkor Wat became world's largest religious monument and UNESCO World Heritage Site", "Hydraulic civilization model demonstrated sophisticated pre-industrial urban planning", "Khmer cultural influence shaped art, architecture, and religion in Thailand and Laos", "Angkor's abandonment remains debated mystery in historical and environmental scholarship"],
        "relationships": [{"entity": "Suryavarman II", "relationship": "BUILT_BY", "note": "12th-century ruler who commissioned Angkor Wat temple complex"}, {"entity": "Jayavarman VII", "relationship": "GREATEST_RULER", "note": "Converted empire to Buddhism, built Angkor Thom and hospitals"}, {"entity": "Angkor Wat", "relationship": "BUILT", "note": "Commissioned world's largest religious monument complex"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Khmer Empire built Angkor Wat and sustained the world's largest pre-industrial city through hydraulic engineering, creating Southeast Asia's greatest civilization and a cultural heritage that defines Cambodian identity.", "significanceCategory": "continental"},
    }),
    ("ayyubid-dynasty", {
        "summary": "The Ayyubid dynasty (1171–1260 CE) was a Sunni Muslim dynasty founded by the Kurdish military commander Saladin (Salah ad-Din Yusuf ibn Ayyub). Ruling Egypt, Syria, the Jazira, Yemen, and parts of Arabia and North Africa, the Ayyubids are celebrated primarily for Saladin's reconquest of Jerusalem from the Crusaders in 1187 — one of the most significant military events of the medieval era.\n\nSaladin's 1187 defeat of the Crusader Kingdom at the Battle of Hattin and subsequent recapture of Jerusalem (lost to the First Crusade in 1099) shocked Christendom and prompted the Third Crusade. His chivalrous treatment of Jerusalem's Christian inhabitants — refusing the massacre that had accompanied the 1099 conquest — earned him respect from both Muslim and Christian sources, including admiration from his adversary Richard I of England.\n\nThe Ayyubid dynasty fostered trade between the Indian Ocean and Mediterranean, maintained Cairo as a center of Islamic learning, and patronized architecture including the Cairo Citadel. The Ayyubid administrative system — using a confederation of Kurdish and Turkish commanders governing subdivided territories — eventually led to the rise of Mamluk military slaves who overthrew the dynasty in 1250, with the Mongol Hulagu Khan's western campaigns completing the dynasty's fragmentation.",
        "causes": ["Nur ad-Din Zangi's death creating power vacuum in Syria for Saladin to fill", "Crusader kingdom's weakening through internal feuds and territorial losses", "Saladin's military genius at cavalry-based warfare and strategic patience", "Fatimid Caliphate's internal collapse enabling Saladin's vizier position in Egypt"],
        "effects": ["Jerusalem's reconquest ended the Crusader Kingdom of Jerusalem after 88 years", "Third Crusade launched by Richard I failed to retake Jerusalem from Saladin", "Chivalric legend of Saladin influenced medieval European notions of noble adversary", "Mamluk system established by Ayyubids produced the dynasty that replaced them"],
        "relationships": [{"entity": "Saladin", "relationship": "FOUNDED_BY", "note": "Kurdish general who founded dynasty after abolishing Fatimid Caliphate in 1171"}, {"entity": "Crusader Kingdom of Jerusalem", "relationship": "DEFEATED", "note": "Saladin defeated Crusaders at Hattin (1187) and retook Jerusalem"}, {"entity": "Richard I of England", "relationship": "OPPOSED", "note": "Third Crusade saw Richard I fight Saladin to diplomatic stalemate"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "Saladin's Ayyubid dynasty reconquered Jerusalem and demonstrated that Islamic civilization could match Crusader military power, becoming the defining symbol of Muslim resistance to European holy war.", "significanceCategory": "world-changing"},
    }),
    ("buyid-dynasty", {
        "summary": "The Buyid dynasty (934–1062 CE) was a Shia Muslim dynasty of Iranian origin (from Gilan on the Caspian coast) that seized effective control of the Abbasid Caliphate in Baghdad in 945 CE, reducing the Sunni caliphs to ceremonial figureheads while ruling Iran and Iraq. The Buyid period is notable for its patronage of learning, Persian cultural revival, and interfaith tolerance.\n\nWhen Buyid leader Muizz ad-Dawla entered Baghdad in 945 CE, he installed himself as amir al-umara (commander of commanders) while allowing the Abbasid caliph to maintain religious prestige. This arrangement — a Shia dynasty ruling in the name of a Sunni caliph — required remarkable pragmatism and demonstrated the separation of religious legitimacy from political power. The Buyids ruled three distinct regional kingdoms (Persia proper under Rukn ad-Dawla, Jibal under Imad ad-Dawla, and Iraq under Muizz ad-Dawla) in a form of shared dynastic rule.\n\nThe Buyid period saw flourishing of Persian language literature, with Ibn Sina (Avicenna) and al-Biruni doing their greatest works under Buyid patronage. Shia Twelver Islam consolidated its doctrines during the occultation of the twelfth imam, precisely during this era. The dynasty fell to the Sunni Seljuk Turks who entered Baghdad in 1055, restoring Sunni dominance.",
        "causes": ["Abbasid Caliphate's weakening through Turkish military slave commanders", "Buyid Daylamite warriors' military superiority in mountain warfare techniques", "Power vacuum in Baghdad after Turkish commanders' conflicts", "Gilan mountain origin providing military traditions distinct from lowland armies"],
        "effects": ["Buyid rule separated Abbasid religious authority from political power permanently", "Persian language and literature revived after Arabic literary dominance", "Ibn Sina and al-Biruni produced works under Buyid patronage shaping medieval science", "Shia Islam consolidated under Buyid protection developing distinctive practices"],
        "relationships": [{"entity": "Abbasid Caliphate", "relationship": "CONTROLLED", "note": "Reduced Abbasid caliphs to figureheads while exercising real power in Baghdad"}, {"entity": "Ibn Sina (Avicenna)", "relationship": "PATRONIZED", "note": "Great physician and philosopher worked under Buyid court patronage"}, {"entity": "Seljuk Turks", "relationship": "OVERTHROWN_BY", "note": "Seljuks entered Baghdad in 1055 ending Buyid control of caliphate"}],
        "historicalSignificance": {"significanceScore": 7, "significanceNarrative": "The Buyid dynasty's Shia rule over a Sunni caliphate created a pragmatic separation of religious and political authority while patronizing the Avicenna-era scientific golden age.", "significanceCategory": "continental"},
    }),
    ("carolingian-dynasty", {
        "summary": "The Carolingian dynasty (751–987 CE) was a Frankish royal house that produced Charlemagne (Charles the Great), who united most of Western Europe under one rule for the first time since the fall of Rome. The dynasty's cultural, religious, and administrative innovations created the foundations of medieval European civilization and the concept of a Christian Europe unified under church and empire.\n\nCharlemagne (r.768-814 CE) conquered the Saxons, Lombards, and Avars, creating an empire spanning modern France, Germany, Italy, and neighboring territories. His coronation as Holy Roman Emperor by Pope Leo III on Christmas Day 800 CE established the principle of papal authority to crown secular rulers — a relationship that dominated European politics for 700 years. The Carolingian Renaissance, promoted by Charlemagne at his court in Aachen, standardized Latin script, promoted literacy, and preserved classical manuscripts in monastery scriptoria.\n\nThe 843 Treaty of Verdun, dividing Charlemagne's empire among his three grandsons, created the territorial outlines of modern France and Germany — making it arguably the founding document of Western European nationhood. Charlemagne's administrative innovations (missi dominici, county system, standardized weights and measures) created governance templates that persisted through the High Middle Ages.",
        "causes": ["Merovingian dynasty's decline enabling Charles Martel and then Carolingians to take power", "Pope Stephen II's need for Frankish military protection against Lombards", "Charlemagne's extraordinary military and administrative talent", "Christianity providing ideological framework for unified European governance"],
        "effects": ["Christmas coronation of 800 CE established Holy Roman Empire lasting until 1806", "843 Treaty of Verdun created territorial foundations of modern France and Germany", "Carolingian Renaissance preserved classical manuscripts enabling European intellectual revival", "Standardized Latin script (Carolingian minuscule) became basis of modern European lettering"],
        "relationships": [{"entity": "Charlemagne", "relationship": "GREATEST_RULER", "note": "Greatest Carolingian ruler who unified Western Europe and was crowned Emperor in 800"}, {"entity": "Pope Leo III", "relationship": "CROWNED_BY", "note": "Pope crowned Charlemagne Holy Roman Emperor on Christmas Day 800"}, {"entity": "Holy Roman Empire", "relationship": "CREATED", "note": "Charlemagne's coronation established the Holy Roman Empire lasting to 1806"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Carolingian dynasty united Europe, created the Holy Roman Empire, and through the Treaty of Verdun established the territorial foundations of modern European nation-states — a political legacy lasting 1,200 years.", "significanceCategory": "world-changing"},
    }),
    ("hasmonean-dynasty", {
        "summary": "The Hasmonean dynasty (140–37 BCE) was a Jewish priestly and royal dynasty that arose from the Maccabean Revolt against Seleucid Greek rule over Judea. The only period of Jewish political independence between 586 BCE and 1948 CE, the Hasmonean state achieved territorial expansion, Hanukkah's origin story, and the codification of Jewish religious law that shaped Judaism as it exists today.\n\nThe revolt began in 167 BCE when Mattathias and his sons, the Maccabees, refused to follow Antiochus IV Epiphanes' decrees outlawing Jewish practice and desecrating the Temple with a statue of Zeus. The recapture and rededication of the Jerusalem Temple in 165 BCE — celebrated as Hanukkah — became one of the most important events in Jewish history. Simon Maccabee secured political independence from the Seleucids in 140 BCE, beginning the formal Hasmonean state.\n\nAt its height under Alexander Jannaeus (103-76 BCE), the Hasmonean kingdom controlled territory comparable to the biblical Kingdom of David, including Galilee, Samaria, Transjordan, and parts of the Mediterranean coast. The Hasmonean conversion of Idumean and Iturian peoples to Judaism created the demographic and religious context for later developments. Herod the Great (an Idumean by descent) married into the Hasmonean line before seizing power with Roman backing in 37 BCE.",
        "causes": ["Antiochus IV Epiphanes' desecration of the Jerusalem Temple and outlawing of Jewish practice", "Maccabee family's religious zeal and military organization in Judean hills", "Seleucid Empire's gradual weakening enabling Jewish independence", "Jewish population's deep attachment to Temple cult and Mosaic law"],
        "effects": ["Hanukkah festival commemorating Temple rededication celebrated by Jews globally", "Jewish law codification during Hasmonean era shaped Rabbinic Judaism", "Hasmonean expansion brought Galilee (future Jesus homeland) into Jewish cultural sphere", "Conversion policy created Idumean Jewish population producing Herod dynasty"],
        "relationships": [{"entity": "Maccabees", "relationship": "FOUNDED_BY", "note": "Hasmonean dynasty arose from Maccabean family revolt against Seleucids"}, {"entity": "Antiochus IV Epiphanes", "relationship": "REBELLED_AGAINST", "note": "Seleucid king whose Temple desecration triggered the Maccabean Revolt"}, {"entity": "Herod the Great", "relationship": "SUCCEEDED_BY", "note": "Idumean king who displaced last Hasmonean rulers with Roman support"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Hasmonean dynasty achieved the only period of Jewish independence for 2,500 years, created Hanukkah, and shaped the Judaism that survived Roman conquest and the diaspora, making it foundational to Jewish history.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 57 — Class 312 Ancient Dynasties II")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
