#!/usr/bin/env python3
"""Batch 77 — Class 363 Theaters II (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/363-Class-363"
FILE_PREFIX = "363"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("almeida-theatre", {
        "summary": "The Almeida Theatre in Islington, north London, is one of Britain's most artistically significant mid-scale theatres, established in 1837 as a Literary and Scientific Society building and repurposed as a theatre in 1980, which under artistic directors Jonathan Kent and Ian McDiarmid (1990-2002) became one of the world's most influential theatrical laboratories — producing work that transferred to the West End and Broadway and establishing Islington as a cultural destination. The Almeida's intimate 325-seat space enables an intensity of theatrical experience that larger venues cannot replicate.\n\nThe building served various purposes before its conversion: gas company offices, factory, and then theatre. Jonathan Kent and Ian McDiarmid transformed it from a struggling fringe venue to a prestige producing house by staging ambitious Shakespeare productions and new plays with major film and stage stars. Michael Gambon, Ralph Fiennes, Kevin Spacey, Juliette Binoche, and Nicole Kidman performed at the Almeida, giving productions Broadway-calibre casting in an intimate space.\n\nRupert Goold's subsequent artistic directorship continued the Almeida's tradition of bold interpretive risk — productions including a Macbeth set in a 1950s American diner, a Julius Caesar in modern West Africa, and a landmark run of Greek tragedies. The theatre's influence on British acting, directing, and playwriting is disproportionate to its modest size, making it the most important small theatre in Britain after the Royal Court.",
        "causes": ["1837 building constructed as Literary and Scientific Society facility", "1980 theatre conversion creating intimate north London performance space", "Jonathan Kent and Ian McDiarmid's 1990 artistic leadership transforming venue to prestige status", "Star casting combining major actors with intimate staging creating distinctive identity"],
        "effects": ["Almeida productions transferred to West End and Broadway raising its international profile", "Major film stars performing in intimate 325-seat venue created unique theatrical experience", "Rupert Goold's bold reinterpretations of classics established Almeida directorial style", "Islington became cultural destination partly through Almeida's prestige"],
        "relationships": [{"entity": "Jonathan Kent", "relationship": "TRANSFORMED_BY", "note": "Kent and McDiarmid's 1990-2002 artistic leadership made Almeida world-class"}, {"entity": "Royal Court Theatre", "relationship": "RIVALS", "note": "Almeida considered the second most important small theatre in Britain after Royal Court"}, {"entity": "Ralph Fiennes", "relationship": "ASSOCIATED_WITH", "note": "Major stars including Fiennes performed at Almeida giving productions prestige beyond venue size"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Almeida Theatre's transformation from a struggling fringe venue to a world-class producing house — staging major stars in intimate 325-seat productions that transferred to Broadway — is the most remarkable artistic reinvention in British theatrical history.", "significanceCategory": "regional"},
    }),
    ("royal-shakespeare-theatre", {
        "summary": "The Royal Shakespeare Theatre (RST) in Stratford-upon-Avon, Warwickshire, is the primary performance venue of the Royal Shakespeare Company (RSC), the world's leading Shakespeare-producing organization, built on the site of earlier Shakespeare theatres destroyed by fire and rebuilt in 1932 as the Shakespeare Memorial Theatre before major renovation completed in 2011. The RST's history — from Victorian memorial to 21st-century thrust stage — mirrors the evolution of Shakespeare performance from reverential monument to living theatre.\n\nThe original Shakespeare Memorial Theatre was built in 1879 to commemorate the Tercentenary of Shakespeare's birth. It burned down in 1926 and was replaced by the Elisabeth Scott-designed building (1932), the first major public building in Britain designed by a woman. The 2008-2011 renovation transformed the building from a Victorian proscenium arrangement into a thrust stage with three-sided seating bringing audiences within 15 meters of the actors — a transformation that redefined audience-actor relationship in large-scale Shakespeare performance.\n\nThe RSC under Peter Hall's founding directorship (1961) created the most influential Shakespeare producing company in history: Hall, Peter Brook, John Barton, and subsequent directors including Trevor Nunn, Adrian Noble, and Gregory Doran have shaped how Shakespeare is performed globally. The RSC's educational programs, touring productions, and international partnerships make it the world's most significant non-commercial theatre organization. RSC's global reach across 50 countries makes Stratford-upon-Avon the pilgrimage destination for worldwide Shakespeare enthusiasts.",
        "causes": ["1879 Victorian memorial theatre on Shakespeare's birthplace site", "1926 fire destroying original building and 1932 reconstruction", "Peter Hall's 1961 founding of RSC creating permanent ensemble company", "2011 thrust stage renovation transforming audience-actor relationship"],
        "effects": ["RSC became world's leading Shakespeare-producing company under Hall, Brook, and Nunn", "2011 thrust stage renovation redefined large-scale Shakespeare performance", "RSC educational programs shaped Shakespeare teaching globally", "Stratford-upon-Avon established as world's Shakespeare pilgrimage destination"],
        "relationships": [{"entity": "Royal Shakespeare Company", "relationship": "HOME_OF", "note": "RST is primary home of RSC, the world's leading Shakespeare organization"}, {"entity": "Peter Hall", "relationship": "SHAPED_BY", "note": "Hall founded RSC in 1961 transforming the theatre's identity"}, {"entity": "William Shakespeare", "relationship": "COMMEMORATES", "note": "Theatre built on Shakespeare's birthplace to perform and preserve his works"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Royal Shakespeare Theatre is the institutional home of the world's most influential Shakespeare company — whose productions, educational programs, and touring reach have shaped how Shakespeare is performed, taught, and experienced globally.", "significanceCategory": "world-changing"},
    }),
    ("royal-court-theatre", {
        "summary": "The Royal Court Theatre in Sloane Square, London, is the world's most significant new writing theatre, which under artistic director George Devine (1956-1965) introduced John Osborne's Look Back in Anger (1956) — the play that launched British Kitchen Sink drama and changed British theatre permanently. The Royal Court has since premiered plays by Samuel Beckett, Harold Pinter, Arnold Wesker, Caryl Churchill, David Hare, and over 200 other major playwrights, making it the institution most responsible for shaping British and international drama since 1956.\n\nThe Theatre was founded in 1870 and served various purposes before George Devine established the English Stage Company there in 1956. Look Back in Anger's premiere on 8 May 1956 is the most precisely datable transformation in British theatrical history: the play's working-class protagonist Jimmy Porter, raging against the established order, gave voice to post-war disillusionment with Britain's class structure and sparked an entire movement of socially engaged 'Angry Young Men' writing.\n\nThe Royal Court's 'upstairs' (Jerwood Theatre Upstairs) and 'downstairs' (Jerwood Theatre Downstairs) programming structure — producing both small experimental work and larger-scale new plays — has been widely replicated. The theatre's writers include Jez Butterworth (Jerusalem), Sarah Kane (Blasted), Martin McDonagh, and Conor McPherson. International programs support playwrights from Africa, Latin America, and Eastern Europe. The Royal Court's influence on global theatre through playwright development is unmatched.",
        "causes": ["1956 George Devine's English Stage Company founding at Royal Court", "Look Back in Anger's 8 May 1956 premiere launching Kitchen Sink drama movement", "Commitment to new writing rather than classical or commercial theatre", "Jerwood Theatre dual-space programming enabling experimental and main-stage work"],
        "effects": ["Look Back in Anger transformed British theatre's class and subject matter", "200+ major playwrights premiered at Royal Court including Beckett, Pinter, Churchill, Hare", "Kitchen Sink drama movement transformed British film, TV, and theatre for decades", "International playwright programs spread British new writing development model globally"],
        "relationships": [{"entity": "George Devine", "relationship": "TRANSFORMED_BY", "note": "Devine's 1956 English Stage Company made Royal Court Britain's premier new writing house"}, {"entity": "Look Back in Anger", "relationship": "PREMIERED", "note": "Osborne's 1956 play premiered at Royal Court launched Kitchen Sink drama movement"}, {"entity": "John Osborne", "relationship": "LAUNCHED", "note": "Osborne's Look Back in Anger launched from Royal Court; followed by 200+ major playwrights"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Royal Court Theatre's premiere of Look Back in Anger on 8 May 1956 is the most precisely datable revolution in British cultural history — transforming theatre's class dynamics, subject matter, and voice in a single evening.", "significanceCategory": "world-changing"},
    }),
    ("bolshoi-kamenny-theatre", {
        "summary": "The Bolshoi Kamenny Theatre (Grand Stone Theatre) in St. Petersburg, Russia, was one of Imperial Russia's most prestigious opera houses, built in 1783-1784 and serving as the primary venue for opera and ballet performance in the Russian capital until its closure in 1886 and subsequent conversion to a conservatoire building. The theatre played a central role in the development of Russian classical music, hosting premieres of major Russian operas and ballets during the golden era of Imperial Russian culture.\n\nThe Bolshoi Kamenny (meaning 'Big Stone Theatre' to distinguish it from the Maly or 'Small' theatre) was built under Catherine the Great's cultural expansion program that sought to establish St. Petersburg as Europe's cultural rival. It hosted performances by visiting Italian opera companies that shaped Russian operatic taste, and later Russian premieres including works by Glinka, Dargomyzhsky, and other founders of Russian nationalist opera. The theatre's stone construction was notable in an era when most Russian theatres were wooden.\n\nAfter the theatre's 1886 closure, its building was converted to house the St. Petersburg Conservatoire — the institution founded by Anton Rubinstein in 1862 that trained Tchaikovsky and remains Russia's premier music education institution. The building's conversion thus completed a symbolic handover from imported Italian opera to Russian classical music education — encapsulating the transition from European cultural dependency to Russian musical nationalism.",
        "causes": ["1783-1784 construction under Catherine the Great's cultural expansion program", "St. Petersburg's ambition to rival European capitals in opera and ballet provision", "Italian opera company residencies shaping Russian operatic taste", "Russian nationalist opera premieres including Glinka works"],
        "effects": ["Russian opera and ballet premieres hosted during formative period of Russian classical music", "1886 conversion to St. Petersburg Conservatoire housing Russia's premier music education institution", "Tchaikovsky trained at Conservatoire occupying Bolshoi Kamenny's former building", "Symbol of transition from Italian opera dependency to Russian musical nationalism"],
        "relationships": [{"entity": "Catherine the Great", "relationship": "BUILT_UNDER", "note": "Catherine's cultural program built Bolshoi Kamenny to rival European opera houses"}, {"entity": "St. Petersburg Conservatoire", "relationship": "CONVERTED_INTO", "note": "Building converted to Conservatoire in 1886; Tchaikovsky trained at its predecessor"}, {"entity": "Mikhail Glinka", "relationship": "HOSTED_PREMIERES_OF", "note": "Russian nationalist opera premieres including Glinka's works performed here"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Bolshoi Kamenny Theatre's conversion to the St. Petersburg Conservatoire symbolizes Russia's 19th-century transition from Italian cultural dependency to the Russian musical nationalism that produced Tchaikovsky, Rimsky-Korsakov, and Mussorgsky.", "significanceCategory": "regional"},
    }),
    ("vienna-state-opera-house", {
        "summary": "The Vienna State Opera (Wiener Staatsoper) is the world's leading opera house, founded in 1869 on the Ringstrasse as the Imperial Court Opera, where Brahms, Bruckner, Mahler, Richard Strauss, and hundreds of other composers and conductors have shaped the history of classical music. The Staatsoper's position in Vienna's musical culture — the city that produced Haydn, Mozart, Beethoven, Schubert, Brahms, Bruckner, Mahler, and the Second Viennese School — makes it the institution most embedded in Western music's greatest tradition.\n\nThe building was designed by August Sicard von Sicardsburg and Eduard van der Nüll in Neo-Renaissance style, opening on 25 May 1869 with Mozart's Don Giovanni. The architects were so devastated by public criticism of the building's design that van der Nüll hanged himself (1868) and Sicardsburg died of grief two months later. The bombing by Allied forces in March 1945 destroyed the auditorium; reconstruction was completed in 1955, and the reopening with Beethoven's Fidelio on 5 November 1955 was broadcast live on Austrian radio as a national celebration of reconstruction.\n\nGustav Mahler's directorship (1897-1907) transformed the Staatsoper into the world's leading opera house through his insistence on theatrical integrity: Mahler covered the house lights, refused late arrivals, and conducted from memory. Herbert von Karajan's era (1957-1964) combined musical genius with autocratic management. The Staatsoper presents 50-60 different operas in a single season — a repertory system unmatched anywhere — with approximately 300 performances per year.",
        "causes": ["1869 opening on Vienna Ringstrasse as part of Habsburg Emperor Franz Joseph's cultural building program", "Vienna's position as Habsburg capital requiring world-class opera venue", "Imperial Court Opera traditions dating from 17th century creating deep operatic culture", "Mahler's 1897-1907 directorship establishing theatrical and musical standards"],
        "effects": ["World's leading opera house presenting 50-60 operas and 300 performances annually", "Mahler's directorship transformed theatrical standards for opera houses globally", "1955 reopening after WWII destruction became symbol of Austrian reconstruction", "Staatsoper's rehearsal and performance standards train world's top singers and conductors"],
        "relationships": [{"entity": "Gustav Mahler", "relationship": "TRANSFORMED_BY", "note": "Mahler's 1897-1907 directorship made Staatsoper world's leading opera house"}, {"entity": "Herbert von Karajan", "relationship": "DIRECTED_BY", "note": "Karajan's 1957-1964 era combined genius with controversial autocratic management"}, {"entity": "Franz Joseph I", "relationship": "FOUNDED_BY", "note": "Habsburg Emperor's Ringstrasse cultural program opened the Imperial Court Opera in 1869"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Vienna State Opera's position at the heart of Vienna's musical tradition — the city that produced more great composers than any other — and its 50-60 opera repertory system make it the single most important institution in the history of Western classical music performance.", "significanceCategory": "world-changing"},
    }),
    ("palace-theatre", {
        "summary": "The Palace Theatre in the West End of London, built in 1891 as the Royal English Opera House, is one of London's most historic and architecturally significant theatres, famous as the original home of The Phantom of the Opera (1986-2011, the longest-running musical in West End history) and subsequent major productions. Its ornate terracotta exterior on Cambridge Circus and its imposing red-velvet interior make it one of the most recognizable theatre buildings in the world.\n\nThe theatre was built by impresario Richard D'Oyly Carte (famous for the Gilbert and Sullivan partnership) to present serious English opera as an alternative to the Italian opera that dominated Victorian London. The opening production was Sullivan's Ivanhoe (1891), but D'Oyly Carte sold the building after financial failure; it was renamed Palace Theatre in 1911 and became a variety and musical hall venue. Sarah Bernhardt, Pavlova, and Marie Lloyd performed there in the variety era.\n\nAndrew Lloyd Webber's The Phantom of the Opera ran at the Palace Theatre from 1986 until moving to His Majesty's Theatre in 2011 — its 9,887 performance London run made it the longest-running musical in West End history. Harry Potter and the Cursed Child, winner of the most Olivier Awards in history (9), opened at the Palace in 2016. The theatre was extensively renovated under its new owner, Nimax Theatres, to restore its Victorian grandeur.",
        "causes": ["1891 building by D'Oyly Carte to present English opera as alternative to Italian", "Financial failure of English opera program requiring programming pivot to variety", "1986 Phantom of the Opera's opening creating London's longest-running musical run", "Victorian terracotta exterior and red-velvet interior establishing iconic appearance"],
        "effects": ["Phantom of the Opera's 9,887-performance run made Palace Theatre world-famous", "Harry Potter and the Cursed Child's 9 Olivier Awards established venue's continued prestige", "Victorian architectural restoration preserved one of London's most ornate theatre interiors", "West End anchor venue through variety era to musical theatre era"],
        "relationships": [{"entity": "Andrew Lloyd Webber", "relationship": "ASSOCIATED_WITH", "note": "Lloyd Webber's Phantom of the Opera ran at Palace 1986-2011 — longest West End musical run"}, {"entity": "Richard D'Oyly Carte", "relationship": "BUILT_BY", "note": "D'Oyly Carte built theatre in 1891 for English opera after Gilbert and Sullivan success"}, {"entity": "The Phantom of the Opera", "relationship": "HOSTED", "note": "9,887-performance run 1986-2011 was longest in West End history"}],
        "historicalSignificance": {"significanceScore": 6, "significanceNarrative": "The Palace Theatre's hosting of The Phantom of the Opera — the longest-running musical in West End history — made it the institution most associated with Andrew Lloyd Webber's dominance of global musical theatre.", "significanceCategory": "regional"},
    }),
    ("theater-an-der-wien", {
        "summary": "The Theater an der Wien in Vienna, Austria, built in 1801 by Emanuel Schikaneder (librettist of Mozart's The Magic Flute), is one of the most historically significant opera and theatre venues in the world, famous as the site of world premieres of Beethoven's Fidelio (1805, 1806), his symphonies Nos. 2-8, and works by Mozart, Brahms, and Johann Strauss. The building where Beethoven himself lived while composing is a pilgrimage site for classical music history.\n\nEmanuel Schikaneder, who had written the libretto and played Papageno in The Magic Flute premiere at Vienna's Freihaus-Theater (1791), built the Theater an der Wien to capitalize on his success. Beethoven lived in apartments in the building between 1803-1804 while composing Fidelio, and the theatre served as the primary venue for premieres of his orchestral and operatic works. The venue was crucial during the Congress of Vienna (1814-1815), when European heads of state attended performances nightly.\n\nThe theater was converted to a television studio in 1955, but restored to full opera house operation in 2001, becoming Vienna's second opera house (alongside the Staatsoper) with a focus on Baroque and Classical opera performance. Its programming under artistic director Roland Geyer earned it the 'Opera House of the Year' award multiple times. The intimate 1,000-seat auditorium enables a proximity to performance impossible at the Staatsoper's 1,700-seat scale.",
        "causes": ["1801 construction by Schikaneder after Magic Flute success", "Beethoven's 1803-1804 residency making it his primary composition venue", "Congress of Vienna 1814-1815 requiring entertainment venues for assembled European heads of state", "2001 restoration creating Vienna's second opera house with Baroque and Classical focus"],
        "effects": ["Fidelio and Beethoven symphony premieres made Theater an der Wien central to classical music history", "Congress of Vienna entertainment program exposed European aristocracy to Viennese musical culture", "2001 restoration as Baroque-Classical opera house created Vienna's second major opera venue", "Multiple Opera House of the Year awards recognized restored programming quality"],
        "relationships": [{"entity": "Ludwig van Beethoven", "relationship": "PREMIERED_WORKS_OF", "note": "Beethoven lived in the building and premiered Fidelio and symphonies 2-8 here"}, {"entity": "Emanuel Schikaneder", "relationship": "BUILT_BY", "note": "Magic Flute librettist Schikaneder built theater in 1801"}, {"entity": "Congress of Vienna", "relationship": "HOSTED_ENTERTAINMENT_FOR", "note": "1814-1815 Congress participants attended Theater an der Wien nightly"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The Theater an der Wien, where Beethoven lived while composing and premiered his most important orchestral works, holds more classical music history within its walls than virtually any other building — making it a living archive of the Classical era's greatest achievements.", "significanceCategory": "world-changing"},
    }),
    ("theater-am-schiffbauerdamm", {
        "summary": "The Theater am Schiffbauerdamm in Berlin, Germany, built in 1892 and famous as the home of the Berliner Ensemble — Bertolt Brecht's legendary theatre company founded in 1949 — is one of the most politically and artistically significant theatre buildings in the world. The premiere of Brecht and Weill's The Threepenny Opera (Die Dreigroschenoper) at the theater on 31 August 1928 was the most successful premiere in German theatre history: the production ran for 400 performances, spread to 120 cities worldwide, and launched Brechtian theatrical revolution.\n\nThe Theatre am Schiffbauerdamm was built as a conventional Wilhelmine operetta house. The 1928 Threepenny Opera premiere — directed by Erich Engel, designed by Caspar Neher, with Weill's jazz-inflected music and Brecht's Marxist adaptation of John Gay's Beggar's Opera — shocked Berlin audiences and became an overnight sensation. Its critique of bourgeois capitalism through the criminal underworld's language resonated with Weimar Republic instability.\n\nBrecht returned from American exile to East Berlin in 1949, establishing the Berliner Ensemble at the Theater am Schiffbauerdamm with his wife Helene Weigel as co-director. Mother Courage, The Caucasian Chalk Circle, and The Good Person of Szechwan received definitive productions there. Brecht's Epic Theatre — the theory of alienation effect (Verfremdungseffekt) that prevents audiences from emotional identification — became the most influential theory of 20th-century theatrical practice. The theatre remains active as Berlin's most prestigious classical theatre.",
        "causes": ["1892 construction as conventional Wilhelmine operetta house", "1928 Threepenny Opera premiere making theater famous through sensational success", "Brecht's 1949 return from exile to establish Berliner Ensemble in East Berlin", "East German state support for Berliner Ensemble as prestige cultural institution"],
        "effects": ["Threepenny Opera's 400 Berlin performances and 120-city global spread launched Brechtian theatre", "Berliner Ensemble became world's most influential theatre company for political theatre", "Brecht's Epic Theatre theory became most influential theatrical theory of 20th century", "East Berlin theatre provided highest-prestige cultural institution in divided Berlin"],
        "relationships": [{"entity": "Bertolt Brecht", "relationship": "HOME_OF", "note": "Brecht established Berliner Ensemble here in 1949; Threepenny Opera premiered here 1928"}, {"entity": "The Threepenny Opera", "relationship": "PREMIERED", "note": "1928 premiere ran 400 times and spread to 120 cities — most successful German premiere"}, {"entity": "Kurt Weill", "relationship": "PREMIERED_WORKS_OF", "note": "Weill's jazz-Marxist Threepenny Opera score premiered at the theater in 1928"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Theater am Schiffbauerdamm's premiere of The Threepenny Opera and its subsequent role as Brecht's Berliner Ensemble home make it the single building most associated with 20th-century political theatre — where Brecht's Epic Theatre theory was first staged and perfected.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 77 — Class 363 Theaters II")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
