#!/usr/bin/env python3
"""Batch 143 — Class 311 Parliaments IV: Regional & Municipal Governments (8 entities)"""
import json, os
from datetime import datetime, timezone

FOLDER = "data/appwrite-export/entities/311-Class-311"
FILE_PREFIX = "311"
NOW = datetime.now(timezone.utc).isoformat()
EDITOR_ID = "vscode-copilot"

ENTITIES = [
    ("city-of-london-corporation", {
        "summary": "The City of London Corporation (also known simply as 'the City' or 'the Square Mile') is the municipal governing body of the City of London — the historic square-mile core of London that is one of the world's two most important financial centers (alongside New York), with a governance structure that is unique in the world: it is effectively a medieval city-state that has maintained continuous self-governance since the Norman Conquest, with rights and privileges unmatched by any other British local authority.\n\nThe City of London's governance is extraordinary in modern democratic terms: while most of its governing Common Council is elected by the business premises in the City (not just residents) — giving votes to corporations proportional to their number of employees, a business franchise system without parallel in democratic governance — the Corporation maintains ceremonial and practical autonomy including its own police force (City of London Police), its own Lord Mayor (distinct from the Mayor of Greater London), and certain historic privileges granted by successive monarchs from William the Conqueror onward.\n\nThe City's financial importance is immense: it houses the Bank of England, the London Stock Exchange, Lloyd's of London, and the global headquarters or major offices of hundreds of financial institutions. London's position as one of the world's top two financial centers (competing with New York) is partly sustained by the City Corporation's governance model, which critics argue gives financial corporations unusual political power while supporters argue creates an effective environment for global finance. Approximately 400,000 workers commute into the roughly 9,000 resident City daily.",
        "causes": ["Norman Conquest (1066) William the Conqueror confirming existing City of London rights and privileges rather than imposing new governance", "Medieval London's commercial and financial power requiring institutional self-governance independent of royal authority", "Business franchise voting system emerging from medieval guild traditions giving commercial entities political representation", "Bank of England (1694) and subsequent financial institution growth making the City the center of British and then global finance"],
        "effects": ["City of London maintaining unique business-franchise governance system giving financial corporations proportional political votes", "London's development as a global financial center partly sustained by City Corporation governance model", "City of London Police maintaining a separate police force independent of Metropolitan Police", "City Corporation as world's only surviving medieval city-state governance within a modern national democracy"],
        "relationships": [{"entity": "Bank of England", "relationship": "FOUNDED_WITHIN_AND_CENTRAL_INSTITUTION_OF_GOVERNED_TERRITORY", "note": "The Bank of England (1694) is located within the City of London Corporation's governance area"}, {"entity": "London Stock Exchange", "relationship": "HOUSED_WITHIN_UNIQUE_GOVERNANCE_TERRITORY_OF", "note": "The London Stock Exchange operates within the City Corporation's governance area"}, {"entity": "Global Finance", "relationship": "UNIQUE_GOVERNANCE_SUSTAINING_ONE_OF_WORLD'S_TOP_TWO_FINANCIAL_CENTERS", "note": "The City Corporation's unusual governance is credited with sustaining London's position as one of the world's two most important financial centers"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The City of London Corporation — the world's only surviving medieval city-state governance, sustaining one of the world's two most important financial centers through unique business-franchise democracy — is historically significant as a living monument to medieval institutional continuity and global financial geography.", "significanceCategory": "world-changing"},
    }),
    ("european-parliament", {
        "summary": "The European Parliament is the directly elected parliamentary institution of the European Union — the world's largest supranational parliamentary body, with 705 Members of the European Parliament (MEPs) elected by voters across the EU's 27 member states representing approximately 450 million people, exercising legislative, budgetary, and supervisory powers over EU institutions and policies in a political system that has evolved from a consultative assembly to a genuine co-legislative body over seven decades.\n\nThe Parliament's evolution from the 1952 Common Assembly of the European Coal and Steel Community to the directly elected European Parliament (first direct elections in 1979) to the increasingly powerful legislature of the contemporary EU — through successive treaties (Single European Act 1986, Maastricht 1992, Amsterdam 1997, Lisbon 2009) that expanded its powers — is one of the most extraordinary examples of supranational democratic institution-building in history. The Lisbon Treaty made the Parliament a genuine co-legislator with the Council of the EU on most EU legislation.\n\nThe European Parliament's significance is both institutional and symbolic: it represents the democratic accountability dimension of the EU project (complementing the technocratic European Commission and the intergovernmental European Council), it has pushed for stronger environmental, social, and human rights policies than many member state governments would choose, and it serves as the world's most significant experiment in supranational democratic governance — attempting to create democratic legitimacy for decisions affecting 450 million people across 27 diverse nations.",
        "causes": ["European Coal and Steel Community (1952) creating the original Common Assembly as consultative supranational body", "Founding European ideal of 'ever closer union' requiring democratic parliamentary institution for legitimacy", "1979 first direct elections to European Parliament creating direct democratic mandate for MEPs", "Successive EU treaties (Maastricht, Amsterdam, Lisbon) progressively expanding Parliament's legislative powers"],
        "effects": ["European Parliament becoming the world's largest directly elected supranational parliamentary body with 705 MEPs", "Lisbon Treaty (2009) making Parliament a genuine co-legislator on most EU legislation", "EU democratic legitimacy dimension represented by Parliament complementing technocratic Commission", "Environmental, social, and human rights policies pushed beyond what many member state governments would choose"],
        "relationships": [{"entity": "European Union", "relationship": "DIRECTLY_ELECTED_DEMOCRATIC_LEGISLATIVE_INSTITUTION_OF", "note": "The European Parliament is the EU's directly elected legislative body, representing 450 million EU citizens"}, {"entity": "Lisbon Treaty", "relationship": "GRANTED_FULL_CO-LEGISLATIVE_STATUS_BY_2009", "note": "The 2009 Lisbon Treaty made the Parliament a full co-legislator with the Council on most EU legislation"}, {"entity": "Supranational Democracy", "relationship": "WORLD'S_MOST_SIGNIFICANT_EXPERIMENT_IN", "note": "The European Parliament represents the world's most significant attempt to create democratic accountability for supranational governance"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The European Parliament — the world's largest directly elected supranational body representing 450 million people — is historically significant as the most ambitious experiment in democratic supranational governance in human history.", "significanceCategory": "world-changing"},
    }),
    ("roman-senate", {
        "summary": "The Roman Senate (Latin: Senatus Romanus) — the governing council of the Roman Republic and a significant institution throughout the Roman Empire — was one of the most consequential legislative and advisory bodies in world history, operating continuously in various forms for approximately 1,200 years (from the legendary founding of Rome in 753 BCE through the Eastern Roman Empire's continuation), and serving as the foundational model for parliamentary governance, the concept of a deliberative legislative body, and republican government that has influenced all subsequent democratic institutions.\n\nThe Republican Roman Senate (roughly 509-27 BCE) held extraordinary powers: controlling state finances and treasury, directing foreign policy and war declarations, ratifying laws, appointing governors, and serving as the supreme advisory body to the annually elected consuls. The Senate's composition of approximately 300-600 former magistrates (ex-consuls, ex-praetors, etc.) created a de facto oligarchic system dominated by the aristocratic class (patricians and subsequently wealthy plebeians) that limited popular democratic participation while maintaining collective governance.\n\nThe Senate's historical arc encapsulates Rome's constitutional history: from the Republic's Senate dominating Roman governance (the Senate's acronym SPQR — Senatus Populusque Romanus, 'Senate and People of Rome' — emblazoned on Roman standards), through the Republic's fall under Julius Caesar and Augustus (who maintained the Senate as an institution while draining it of real power), to the Empire's Senate as largely ceremonial but maintaining symbolic legitimacy, to the late Empire period when the Senate's authority collapsed with Rome's political crisis.",
        "causes": ["Roman Republic's constitution requiring a deliberative governing body to advise annually elected magistrates", "Aristocratic class's dominance requiring an institutional body to preserve its power across annual electoral cycles", "Roman state's complexity requiring a permanent institution with institutional memory beyond annual magistrates", "Roman Republic's anti-monarchical constitution channeling governance into collective deliberative body"],
        "effects": ["SPQR (Senatus Populusque Romanus) becoming the symbol of Roman republican governance", "Senate model influencing all subsequent Western republican and parliamentary institutions", "Julius Caesar's assassination by senators (44 BCE) as the Senate's desperate attempt to preserve republican governance", "Roman Senate's institutional persistence across 1200+ years demonstrating the durability of deliberative governing bodies"],
        "relationships": [{"entity": "Roman Republic", "relationship": "SUPREME_DELIBERATIVE_GOVERNING_INSTITUTION_OF_THE", "note": "The Senate was the primary governing body of the Roman Republic, controlling finance, foreign policy, and law"}, {"entity": "Julius Caesar", "relationship": "SENATORS_ASSASSINATING_TO_PREVENT_MONARCHICAL_OVERTHROW_OF_REPUBLICAN_SENATE", "note": "The Senate's senators assassinated Caesar in 44 BCE in an attempt to prevent the Republic's monarchical overthrow"}, {"entity": "Western Parliamentary Tradition", "relationship": "FOUNDATIONAL_MODEL_FOR_ALL_SUBSEQUENT_DELIBERATIVE_LEGISLATIVE_BODIES_IN", "note": "The Roman Senate is the foundational model for parliamentary and legislative governance in Western political tradition"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The Roman Senate — supreme governing institution of Rome for 1200+ years, foundational model for all subsequent parliamentary and republican governance — is one of the most historically consequential governing institutions in human civilization.", "significanceCategory": "world-changing"},
    }),
    ("house-of-commons-of-the-united-kingdom", {
        "summary": "The House of Commons of the United Kingdom is the lower house of the UK Parliament and the primary democratic legislative body of the world's oldest continuously functioning parliamentary democracy — the institution through which British government must maintain confidence to remain in power, and whose evolution from a medieval council of knights and burgesses to a democratically elected legislature over 750 years has provided the foundational model for parliamentary governance worldwide.\n\nThe Commons' constitutional evolution is one of history's most significant political stories: beginning with Simon de Montfort's 1265 Parliament (conventionally dated as the Commons' origin), through the Magna Carta's principles of consent to taxation, through the Glorious Revolution of 1688 (which established parliamentary supremacy over the monarchy), through the Great Reform Acts of 1832 and 1867 (extending the franchise), through the 1918 Representation of the People Act (extending suffrage to women over 30), to the 1928 full equal suffrage — the Commons evolved from a vehicle for elite consent to a mass democratic institution.\n\nThe Westminster System — the British parliamentary model in which the executive (government) must maintain the confidence of the elected lower house — has been exported to approximately 55 countries through British colonial expansion, making it the world's most widespread parliamentary system. India, Canada, Australia, New Zealand, Jamaica, and dozens of other former British territories use Westminster-derived systems, making the House of Commons the template for governance affecting approximately 2 billion people globally.",
        "causes": ["1265 de Montfort Parliament and subsequent medieval Parliaments establishing the Commons as council of knights and burgesses", "1688 Glorious Revolution establishing parliamentary supremacy over royal prerogative", "Great Reform Acts (1832, 1867) extending the franchise beyond a small elite toward mass democratic representation", "1918-1928 women's suffrage legislation completing the transformation to universal suffrage"],
        "effects": ["Westminster System exported to approximately 55 former British territories affecting approximately 2 billion people", "Cabinet responsibility doctrine requiring executive to maintain Commons confidence as foundational parliamentary democracy principle", "House of Lords Parliament Acts (1911, 1949) making Commons the dominant parliamentary chamber", "Universal suffrage (1928) completing the House of Commons' transformation to fully democratic representation"],
        "relationships": [{"entity": "Westminster System", "relationship": "ORIGIN_AND_MODEL_FOR_PARLIAMENTARY_SYSTEM_AFFECTING_2_BILLION_PEOPLE", "note": "The UK House of Commons is the original Westminster System parliament, now the template for governance in 55+ countries"}, {"entity": "Glorious Revolution 1688", "relationship": "PARLIAMENTARY_SUPREMACY_ESTABLISHED_BY", "note": "The 1688 Glorious Revolution established parliamentary supremacy over the monarchy, making the Commons supreme"}, {"entity": "Magna Carta", "relationship": "PRINCIPLES_OF_TAXATION_WITH_CONSENT_FOUNDATIONAL_TO_COMMONS_AUTHORITY", "note": "Magna Carta's principle of consent to taxation provided the philosophical foundation for parliamentary authority"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The House of Commons UK — the original Westminster parliamentary democracy, template for governance affecting 2 billion people in 55+ countries — is one of history's most consequential governing institutions and the foundational model for parliamentary democracy worldwide.", "significanceCategory": "world-changing"},
    }),
    ("national-assembly-of-france", {
        "summary": "The National Assembly of France (French: Assemblée nationale) is the lower house of the French Parliament and historically the most significant parliamentary body to emerge from the French Revolution — the institution whose transformation from the Estates-General to the National Assembly in June 1789 marked the revolutionary break with the Ancien Régime's corporate society and the assertion of popular sovereignty that changed the course of world history, making the French National Assembly one of the most historically consequential parliamentary institutions ever created.\n\nThe June 1789 transformation is one of the pivotal moments in political history: when the Third Estate (commoners) of the Estates-General was joined by liberal members of the First Estate (clergy) and Second Estate (nobility) to declare themselves the National Assembly with the right to represent the French nation — rather than the traditional three orders — they claimed the revolutionary principle that sovereignty resided in the nation (the people) rather than the king. This constitutional revolution preceded the political revolution of the Bastille (July 14, 1789) but was its deeper foundation.\n\nThe French National Assembly's subsequent history reflects France's extraordinary constitutional instability: the First Republic (1792-1799), the First Empire, the Restoration monarchy, the July Monarchy, the Second Republic, the Second Empire, the Third Republic (1870-1940), the Vichy regime, the Fourth Republic (1946-1958), and the Fifth Republic (1958-present) have all featured the National Assembly in different constitutional forms. France's 17 constitutions and multiple regime changes make French constitutional history one of the world's most complex.",
        "causes": ["Fiscal crisis of the French monarchy requiring convocation of Estates-General (1789) after 175 years without meeting", "Third Estate's rejection of voting by order (giving aristocracy/clergy veto over commoners) triggering the National Assembly claim", "Enlightenment philosophy of popular sovereignty providing ideological foundation for the National Assembly's constitutional claim", "June 1789 Tennis Court Oath cementing the National Assembly's refusal to dissolve until a constitution was established"],
        "effects": ["National Assembly's 1789 constitutional claim establishing the revolutionary principle of popular sovereignty that changed world history", "Declaration of the Rights of Man and Citizen (August 1789) drafted by the National Assembly as foundational human rights document", "French Revolution's constitutional principles (liberty, equality, popular sovereignty) spreading globally through revolutionary and Napoleonic wars", "French constitutional instability (17 constitutions) reflecting the ongoing tension between revolutionary and conservative political forces"],
        "relationships": [{"entity": "French Revolution", "relationship": "REVOLUTIONARY_INSTITUTION_WHOSE_1789_CLAIM_IGNITED", "note": "The National Assembly's June 1789 constitutional claim preceded and triggered the political revolution of 1789"}, {"entity": "Declaration of the Rights of Man and Citizen", "relationship": "DRAFTED_AND_ADOPTED_FOUNDATIONAL_HUMAN_RIGHTS_DOCUMENT", "note": "The National Assembly drafted and adopted the 1789 Declaration of the Rights of Man and Citizen"}, {"entity": "Popular Sovereignty", "relationship": "FIRST_MODERN_PARLIAMENTARY_BODY_TO_ASSERT_AND_INSTITUTIONALIZE", "note": "The National Assembly's 1789 claim was the first modern parliamentary assertion of popular sovereignty as the basis of government"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The National Assembly of France — whose 1789 transformation from Estates-General asserted popular sovereignty and ignited the French Revolution — is one of history's most consequential parliamentary institutions and the foundational claim that changed the basis of political legitimacy in the modern world.", "significanceCategory": "world-changing"},
    }),
    ("congress-of-the-united-states", {
        "summary": "The United States Congress is the bicameral legislature of the United States federal government — composed of the Senate (100 senators, two per state) and the House of Representatives (435 members apportioned by population) — and is the world's most powerful legislative body in the world's largest economy and most powerful military state, exercising legislative, budgetary, investigative, and confirmatory powers of extraordinary global consequence.\n\nCongress's constitutional design reflects the 1787 Constitutional Convention's compromise between large and small states (the Connecticut Compromise creating the bicameral structure), between federal and state power, and between different visions of representation. The Senate's equal representation of states regardless of population gives Wyoming (approximately 580,000 people) equal Senate votes as California (approximately 39 million) — a design choice that reflects the federal bargain but increasingly represents an anti-democratic bias toward rural and less populous states.\n\nCongress's role in American and global affairs is immense: it has the power to declare war (though this has been increasingly bypassed by presidential military authority), controls federal spending (approximately $6-7 trillion annually), confirms Supreme Court justices and cabinet officers, ratifies treaties, and through its legislation and regulatory authority shapes the world's largest economy. Dysfunctions of the contemporary Congress — chronic legislative gridlock, political polarization, filibuster abuse in the Senate — have become major subjects of constitutional analysis.",
        "causes": ["1787 Constitutional Convention creating bicameral legislature as compromise between large and small state interests", "Connecticut Compromise creating the Senate (equal state representation) and House (population-proportional) structure", "Articles of Confederation's weak unicameral Congress demonstrating need for stronger federal legislature", "Separation of powers doctrine distributing legislative authority to Congress independent of executive branch"],
        "effects": ["Congress controlling approximately $6-7 trillion in annual federal spending with global economic consequences", "Senate confirmation power shaping Supreme Court and federal judiciary through presidential nomination confirmation", "Congressional gridlock from political polarization creating chronic dysfunction in contemporary American governance", "Congressional war powers being increasingly superseded by presidential military authority in post-WWII era"],
        "relationships": [{"entity": "United States Constitution", "relationship": "CREATED_AND_EMPOWERED_BY_1787_AS_LEGISLATIVE_BRANCH_OF", "note": "Congress was created by the 1787 Constitutional Convention as the legislative branch of the US federal government"}, {"entity": "United States Federal Budget", "relationship": "CONTROLS_APPROPRIATIONS_AND_FISCAL_AUTHORITY_OF", "note": "Congress holds constitutional authority over federal appropriations, controlling approximately $6-7 trillion in annual spending"}, {"entity": "Supreme Court of the United States", "relationship": "SENATE_CONFIRMATION_SHAPING_COMPOSITION_OF", "note": "The Senate's confirmation power over Supreme Court nominations shapes the composition of the nation's highest court"}],
        "historicalSignificance": {"significanceScore": 10, "significanceNarrative": "The United States Congress — bicameral legislature of the world's most powerful nation, controlling the world's largest economy's federal budget — is historically significant as one of the world's most consequential governing institutions whose legislation and decisions affect the entire planet.", "significanceCategory": "world-changing"},
    }),
    ("diet-of-japan", {
        "summary": "The National Diet (国会, Kokkai) of Japan is the bicameral legislature of Japan — composed of the House of Representatives (衆議院, Shūgiin) and the House of Councillors (参議院, Sangiin) — established by Japan's 1947 Constitution (the 'Peace Constitution' written under American occupation and never subsequently amended) as the supreme organ of state power in Japan's parliamentary democracy, representing the governance of the world's third-largest economy and Asia's most established democracy.\n\nJapan's 1947 Constitution, drafted under General Douglas MacArthur's occupation administration, was a transformative document: Article 9 renounced war as a sovereign right and prohibited Japan from maintaining war potential (the 'no-war clause'), with subsequent reinterpretation and the Self-Defense Forces maintaining constitutional ambiguity about Japan's military capacity. The Diet's decades-long governance under the Liberal Democratic Party (LDP) — which governed Japan with only two brief interruptions from 1955 to the present — represents one of the world's most dominant single-party democracies.\n\nThe LDP's 1955-2009 uninterrupted governance (the '1955 System') defined Japan's post-war economic miracle: the close LDP-bureaucracy-business triangle (the 'Iron Triangle') coordinated Japan's extraordinary economic growth from post-war devastation to the world's second-largest economy. Japan's subsequent economic stagnation (the 'Lost Decades' from the early 1990s), demographic crisis (the world's most aged society), and geopolitical challenges (China's rise, North Korea's nuclear program) have all been addressed through Diet legislation under primarily LDP governance.",
        "causes": ["1947 Constitution drafted under American occupation establishing parliamentary democracy with the Diet as supreme organ of state", "Article 9 peace clause creating unique constitutional constraint on Japanese military power", "LDP's 1955 formation creating the dominant conservative party that would govern Japan for most of the post-war period", "Japan's post-war economic miracle requiring Diet legislation supporting the LDP-bureaucracy-business Iron Triangle"],
        "effects": ["Diet as supreme state organ governing Japan's development from post-war devastation to world's third-largest economy", "Article 9 peace clause making Japan a uniquely constrained military power dependent on US security alliance", "LDP dominance (1955 System) creating one of democracy's most stable single-party dominant systems", "Japanese constitutional reinterpretation debates regarding Article 9 ongoing as China rises and North Korea develops nuclear weapons"],
        "relationships": [{"entity": "Japan's 1947 Constitution", "relationship": "ESTABLISHED_BY_OCCUPATION-ERA_AS_SUPREME_ORGAN_OF_STATE_UNDER", "note": "The Diet was established and empowered by Japan's 1947 Constitution as the supreme organ of state power"}, {"entity": "Liberal Democratic Party", "relationship": "DOMINATED_BY_FOR_MOST_OF_POST-WAR_PERIOD_GOVERNING_THROUGH", "note": "The LDP has dominated Diet governance for most of the period since 1955, creating the dominant party democracy"}, {"entity": "Article 9", "relationship": "LEGISLATURE_OPERATING_UNDER_CONSTITUTIONAL_CONSTRAINT_OF_NO-WAR_CLAUSE", "note": "Article 9's peace clause creates the unique constitutional constraint on Japanese military power that the Diet governs within"}],
        "historicalSignificance": {"significanceScore": 8, "significanceNarrative": "The National Diet of Japan — governing the world's third-largest economy under the unique Article 9 peace constitution, dominated by the LDP's democratic one-party governance — is historically significant as Asia's most established parliamentary democracy and the governing body of post-war Japan's extraordinary economic transformation.", "significanceCategory": "world-changing"},
    }),
    ("bundestag", {
        "summary": "The Bundestag (German Federal Parliament, literally 'Federal Diet') is the federal parliament of Germany — the lower house of Germany's bicameral legislature (alongside the Bundesrat representing the states) and the primary democratic governing institution of Europe's largest economy and most populous EU member state, operating under the Basic Law (Grundgesetz) of 1949 that established the Federal Republic of Germany's democratic system after the Nazi dictatorship's catastrophic end.\n\nThe Bundestag's constitutional design reflects the lessons drawn from the Weimar Republic's failure: the constructive vote of no confidence (which requires the parliament to simultaneously elect a new chancellor when removing an old one, preventing purely negative majorities), the 5% electoral threshold (preventing extreme fragmentation of parties), federalism (with the Bundesrat providing state representation), an independent constitutional court (Bundesverfassungsgericht), and strong protection of fundamental rights — all designed to prevent the constitutional and democratic failures that allowed Hitler's rise.\n\nThe Bundestag's political history embodies Germany's post-war miracle: from West Germany's establishment in 1949 through Adenauer's Christian Democratic Union governance (building the 'social market economy' and NATO alliance), through Brandt's Ostpolitik (normalizing Eastern European relations), through Kohl's German reunification (1990), through Schröder's Agenda 2010 labor reforms, through Merkel's 16 years of 'muddling through' stability — the Bundestag has governed one of the world's most successful post-war state-building projects.",
        "causes": ["1949 Basic Law establishing the Bundestag as West Germany's democratic parliament after Nazi dictatorship", "Weimar Republic failures leading to constitutional safeguards including constructive vote of no confidence and party thresholds", "Allied occupation's insistence on democratic institutions and civilian governance in post-war Germany", "German federalism requiring a lower house (Bundestag) representing the national electorate distinct from state-representing Bundesrat"],
        "effects": ["Bundestag governing Europe's largest economy through 75+ years of West German and unified German democratic development", "Constructive vote of no confidence providing government stability absent from Weimar's chronically unstable coalitions", "German reunification (1990) legislated through the Bundestag as one of the 20th century's most significant democratic achievements", "Germany's role as EU's most powerful member state shaped by Bundestag legislative and budgetary decisions"],
        "relationships": [{"entity": "Basic Law Germany", "relationship": "ESTABLISHED_BY_1949_AS_DEMOCRATIC_PARLIAMENT_UNDER", "note": "The Bundestag was established by Germany's 1949 Basic Law as the democratic legislature of the Federal Republic"}, {"entity": "German Reunification", "relationship": "LEGISLATIVE_BODY_THAT_UNIFIED_GERMANY_IN_1990_THROUGH", "note": "German reunification was achieved through Bundestag legislation in 1990"}, {"entity": "Weimar Republic", "relationship": "CONSTITUTIONAL_SAFEGUARDS_DESIGNED_TO_PREVENT_FAILURES_OF", "note": "The Bundestag's constitutional design includes safeguards (constructive vote of no confidence, 5% threshold) to prevent Weimar's failures"}],
        "historicalSignificance": {"significanceScore": 9, "significanceNarrative": "The Bundestag Germany — governing Europe's largest economy, achieving reunification, designed to prevent the democratic failures that enabled Hitler — is historically significant as one of the most successful post-war parliamentary democracies and the central institution of Europe's most consequential democracy.", "significanceCategory": "world-changing"},
    }),
]

def enrich_entity(slug, data):
    fname = os.path.join(FOLDER, f"{FILE_PREFIX}{slug}.json")
    if not os.path.exists(fname):
        print(f"  SKIP (not found): {fname}"); return
    with open(fname, "r", encoding="utf-8") as f:
        doc = json.load(f)
    entity = doc["entities"][0]
    det = json.loads(entity.get("detailsJson", "{}"))
    edit_log = det.get("_editLog", [])
    for field in ("summary", "importanceScore", "historicalSignificance"):
        if field in data:
            old = entity.get(field)
            entity[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": str(old)[:300], "newValue": str(data[field])[:300]})
    for field in ("causes", "effects", "relationships"):
        if field in data:
            old = det.get(field, [])
            det[field] = data[field]
            edit_log.append({"timestamp": NOW, "editorId": EDITOR_ID, "field": field,
                             "oldValue": json.dumps(old)[:300], "newValue": json.dumps(data[field])[:300]})
    det["_editLog"] = edit_log
    det["_unsyncedEdits"] = True
    entity["_unsyncedEdits"] = True
    entity["detailsJson"] = json.dumps(det, ensure_ascii=False)
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    slen = len(entity.get("summary", ""))
    print(f"  ✓ {entity['name']} — sum={slen}c c={len(det.get('causes', []))} e={len(det.get('effects', []))}")

if __name__ == "__main__":
    print(f"Batch 143 — Class 311 Parliaments IV: Regional & Municipal Governments")
    for slug, data in ENTITIES:
        enrich_entity(slug, data)
    print("Done.")
